### ISSUE TITLE
Undo history clobbered by g:go_fmt_command

### ISSUE THREAD

**Issue by lpar** [fatih/vim-go#1001]
### Actual behavior

When I write a .go file, I lose my undo history.

### Expected behavior

With files other than .go files, Vim keeps my undo history across saves, because I have the persistent undo feature enabled in vimrc:

```
let g:go_fmt_command = "goimports"
if has('persistent_undo')
  set undofile
  set undolevels=100
  set undoreload=100
  set undodir=$HOME/.vimdata/undo
endif
```

I assume that this is something to do with how the automatic format-on-save is implemented.

I'm actually running NeoVim 0.1.4, in case it's a NeoVim-specific problem.

### Configuration

vim-go version is current Git checkout.

**Comment by fatih** [comment]
Can you please add `let g:go_fmt_experimental = 1` to your vimrc and try again? This is vim limitation and unfortunately there is no solution for this. Thanks.
