### ISSUE TITLE
How to plug go-fast into vim-go 1.7?

### ISSUE THREAD

**Issue by olebedev** [fatih/vim-go#1002]
There is [a quite good tool](https://github.com/kovetskiy/go-fast/issues/1) to build Golang packages on-the-flight just for workflow. Is it possible to use it for on-save builds in vim-go? Could you describe how to?

Thanks!

**Comment by fatih** [comment]
Hi @olebedev. Right now there is now way. This is a custom script and I don't want to add a custom script feature to vim-go. Thanks.
