### ISSUE TITLE
How to open the fixed buffer document

### ISSUE THREAD

**Issue by Everything2014** [fatih/vim-go#1005]
### How to open the fixed buffer document

![image](https://cloud.githubusercontent.com/assets/6560524/17642035/ff7c1ab6-6169-11e6-925e-baeec59b1e5d.png)

### Fxied

When I opened the function definition, if the document content is relatively small, the buffer will be following up the squeeze. How can fixed

**Comment by fatih** [comment]
Please reopen the issue and fill the issue template with information. You didn't provided it. I'm not able to help you in this form. Thanks
