### ISSUE TITLE
:GoImplements do not working

### ISSUE THREAD

**Issue by imroc** [fatih/vim-go#1008]
when I ran :GoImplements in the newest version,there came out a error like this:..guru...no initial package..
And I reset a old version of vim-go,then it works.

**Comment by nhooyr** [comment]
Try `:GoUpdateBinaries`

**Comment by therealplato** [comment]
thanks @nhooyr this solved a similar problem where my gorename was looking for go 1.6 packages instead of 1.7 packages

**Comment by fatih** [comment]
Closing as there is no information.
