### ISSUE TITLE
GoCoverage not hightlighting 

### ISSUE THREAD

**Issue by raphael** [fatih/vim-go#1012]
When I run `GoCoverage` the tests are executed and succeed but the text is not highlighted. I tried the following to no avail:
- Run `GoCoverageToggle` multiple times in a row
- Remove all plugins but `vim-go`
- Use different terminals (`gnome-terminal` and `urxvt`)
- Use different color schemes
- Change the value of `hi def      goCoverageCovered    ctermfg=green` to `red`
- Different Go versions (`1.6` and `1.7`)

I'm using the latest `vim-go` (a4ba0a5b1b619bfd0b41618620eed1fe6a22a0a2) although the problem has existed for a while across multiple versions so it's probably not a (recent) regression. Also the editor is the latest `neovim` (0.1.4).

Running out of ideas at this point... It seems to be purely a display issue but I can't figure out what exactly, any suggestion on how to proceed? Thanks!

**Comment by fatih** [comment]
Hi @raphael 

It's weird that a fundamental feature like this is not working for you. I assume your Go setup or the underlying goo tool does not work. What shows `:GoCoverageBrowser` for you? Also did you tried to check the coverage manually yourself?

Unfortunately I can't do much if you don't give me a reproducible case. Let me know how this works for you.

**Comment by amozoss** [comment]
This was happening to me as well.
I tracked it down to `vim-go/autoload/go/coverage.vim`  
```
let l:tmpname = tempname()
let args = [a:bang, 0, "-coverprofile", l:tmpname]
```
It seemed to not be passing the tmpname to `-coverprofile` as show by the log 

```Calling shell to execute: "(go test '-coverprofile' '') >/tmp/vLAX4Wy/11 2>&1"```

Changing it to 
```
-   let l:tmpname = tempname()
+   let l:tmpname = "foo"
let args = [a:bang, 0, "-coverprofile", l:tmpname]
```
resulted in 

```Calling shell to execute: "(go test '-coverprofile' 'foo') >/tmp/vLAX4Wy/11 2>&1"```

And the highlighting started working. 



Vim version on Debian jessie: 
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:35:24)
Included patches: 1-488, 576
```

Not exactly sure why `tempname()` isn't working or what the real issue is..

**Comment by fatih** [comment]
Hi all, the code for `:GoCoverage` was changed recently. Can you please try again? Thanks.

**Comment by amozoss** [comment]
vim-go on commit `4944f0ef82efd9adda445249118cdff01afa7d58`

I'm still experiencing the same problems.  The log shows 
```
Calling shell to execute: "(go test '-coverprofile' '') >/tmp/vGRztFt/14 2>&1" 
```
Looking into it a bit more, removing `expand` seems to have fixed my problem.
```
diff --git a/autoload/go/cmd.vim b/autoload/go/cmd.vim
index d680c3f..a58ecb8 100644
--- a/autoload/go/cmd.vim
+++ b/autoload/go/cmd.vim
@@ -217,7 +217,7 @@ function! go#cmd#Test(bang, compile, ...) abort
 
   if a:0
     " expand all wildcards(i.e: '%' to the current file name)
-    let goargs = map(copy(a:000), "expand(v:val)")
+    let goargs = map(copy(a:000), "v:val")
     if !(has('nvim') || go#util#has_job())
       let goargs = go#util#Shelllist(goargs, 1)
     endif
```

Still not sure whats really going on, perhaps `expand` is swallowing a value?

print `goargs` before my change:
```
['-coverprofile', '']
```
after my change:
```
['-coverprofile', '/tmp/vDkkqsu/12']
```

**Comment by fatih** [comment]
You're right, that might one of the problem. If you use the latest Vim 8, then this problem doesn't exist there as we short return before we hit the common Test function. We need to pass a flag to test to indicate that we don't want to expand wildcards, as these arguments are passed from vim-go itself, and not from the vim command line. I'm looking into this, thanks for debugging it.

**Comment by fatih** [comment]
Please pull latest master and try again. Should work now for you.

**Comment by amozoss** [comment]
Works, thanks
