### ISSUE TITLE
vim-go command issue with vimproc on windows

### ISSUE THREAD

**Issue by jsfaint** [fatih/vim-go#1013]
**This issue is on windows only**

Some vim-go command will get below error messages.

![image](https://cloud.githubusercontent.com/assets/571829/17722189/e629936c-6462-11e6-9704-4b5151cd4522.png)
![image](https://cloud.githubusercontent.com/assets/571829/17722264/7d09e516-6463-11e6-9de6-c18fa215186b.png)

The default shellslash of windows is `\` not `/`
When vimproc is using, the shellslash need to convert before calling vimproc function like `vimproc#system()`, explanation by shougo in [this vimproc issue](https://github.com/Shougo/vimproc.vim/issues/264)

Thanks

**Comment by jsfaint** [comment]
Here is a convert function I use in my plugin
```
function! s:fix_path_for_windows(path)
  if has('win32') || has('win64')
    let l:path = substitute(a:path, '\\', '/', 'g')
    return l:path
  else
    return a:path
  endif
endfunction
```

**Comment by fatih** [comment]
Hi @jsfaint, sorry that you have this problem. I'm going to remove vimproc soon. I'm closing this as I don't have the time to fix it nor do I want to support it. Please do not use it for now. Let me know if you have other questions and feel free to open another issue. Thanks.

**Comment by jsfaint** [comment]
Got it and fully understand.
Thanks.
