### ISSUE TITLE
Go rename breaks when --tags are needed

### ISSUE THREAD

**Issue by EricLagergren** [fatih/vim-go#1025]
### Actual behavior

:GoRename throws all sorts of compile errors because some packages use build tags

### Expected behavior

To be able to pass `--tags=xxx` to :GoRename like I can for other commands, or something like `let :go_guru_tags=xxx` for :GoRename

### Steps to reproduce:

Run `:GoRename --tags=xxx` with a package that won't compile if the specific tags aren't passed

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. `mkdir -p /tmp/foo && curl  https://play.golang.org/p/zXu-aea778.go > /tmp/foo/main.go && https://play.golang.org/p/FEHRjpTA9u.go > /tmp/foo/foo.go && vim /tmp/foo/main.go`
2. `:GoRename Bar`
3. watch it explode

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: 7.4
* vim-go version HEAD
* go version 1.7

**Comment by nhooyr** [comment]
Can you try deleting it and then reinstalling?

**Comment by fatih** [comment]
Hi @EricLagergren . We have `:GoGuruTags`, please use that. Checkout the documentation on how to use it. Thanks
