### ISSUE TITLE
code complete displays "PANIC PANIC PANIC" after updating to 1.7

### ISSUE THREAD

**Issue by darrennoble** [fatih/vim-go#1027]
### Actual behavior
When I hit . after a struct name and the code complete selector pops up there is only one option and it has "PANIC PANIC PANIC" in it.

### Expected behavior
Code complete works...

After I updated my arch linux machine which included upgrading go and go-tools to 1.7.  I then rebooted and launched neovim.  When I tried to use code complete I get one option with the text "PANIC PANIC PANIC" even on files it worked on before the update.

I've also run GoUpdateBinaries just to make sure I didn't have any old binaries causing issues.  I've also tried plain vim in addition to neovim and have the same problem there.  I also tried running PlugUpdate to see if that would help, but it didn't.

**Comment by nhooyr** [comment]
Delete gocode and then reinstall.

**Comment by darrennoble** [comment]
do I just need to delete $GOPATH/bin/gocode?  After posting this I had the thought to "rm $GOPATH/bin/*" and rerun GoUpdateBinaries and I still have the same problem.

**Comment by nhooyr** [comment]
Run `gocode close`. Now try.

**Comment by darrennoble** [comment]
Thanks for the help, that fixed it!
