### ISSUE TITLE
vim-8.0: show_errors can fail with a list index out of range on Windows

### ISSUE THREAD

**Issue by vrischmann** [fatih/vim-go#1031]
### Actual behavior

On Windows, using the latest vim master build, and the latest vim-8.0 commit, :GoBuild fails randomly.

It fails at https://github.com/fatih/vim-go/blob/vim-8.0/autoload/go/job.vim#L176, because sometimes the spawned job for `go build` does not return any output to the callback and thus the errs argument is empty.

(I'm not on my Windows machine right now but I will post the complete error tonight).

After much debugging last night, I'm pretty sure it's a Vim bug (or at least a Vim bug when talking to `go build` or `go install` because it works correctly with other programs).

I'm posting this just for posterity and so that if people on Windows have the same problems, they might see this issue. Feel free to close if not relevant.

Maybe one thing that could be better is to not fail with a "list index out of range" error but something clearer like "no output from <command>" or something, not sure.
### Steps to reproduce:

Simply running :GoBuild on a Go package which has some errors in it will trigger the problem most of the time.
### Configuration
- I'll post the exact vim commit later, but it was a master build as of 15h~ ago.
- vim-go is the last commit from the vim-8.0 branch.
- go 1.7

**Comment by vrischmann** [comment]
So after more debugging, there's definitely something wrong with vim with output on stderr, on windows: vim bug is [here](https://github.com/vim/vim/issues/1026)

Right now this is the workaround I'm using:

```patch
diff --git a/autoload/go/job.vim b/autoload/go/job.vim
index 4c55250..dab792f 100644
--- a/autoload/go/job.vim
+++ b/autoload/go/job.vim
@@ -54,7 +54,12 @@ function! go#job#Spawn(bang, args)
     call s:show_errors(self.bang, self.combined, self.dir, self.winnr)
   endfunc
 
-  let s:job = job_start(a:args.cmd, {
+  let cmd = a:args.cmd
+  if has('win32')
+    let cmd = [&shell, &shellcmdflag] + a:args.cmd + ['2>&1']
+  endif
+
+  let s:job = job_start(cmd, {
         \	"callback": opts.callbackHandler,
         \	"exit_cb": opts.exitHandler,
         \	"close_cb": opts.closeHandler,
```

Basically redirecting stderr to stdout. This generates this command:

    C:\WINDOWS\system32\cmd.exe /c go build . errors 2>&1

and then it works. Probably not worth integrating until the Vim bug though.

**Comment by fatih** [comment]
@vrischmann I've merged the vim-8.0 branch to master. Mind testing on master again and if it's still an issue open a PR/fix ? Thanks.

**Comment by vrischmann** [comment]
Hey @fatih, I just tested with Vim 8.0.0095 and it's working fine now without the work around. Thanks !

**Comment by fatih** [comment]
Thanks for the feedback @vrischmann
