### ISSUE TITLE
got error when vim start with nmap of GoDefPop

### ISSUE THREAD

**Issue by simon-xia** [fatih/vim-go#1032]
### Actual behavior

when vim start, got error: vim-go: godef stack empty

### Expected behavior

No error display

### Steps to reproduce:

open a go file with vim and with the following conf in .vimrc

    au FileType go nmap <C-[> :GoDefPop<CR>

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce

        au FileType go nmap <C-[> :GoDefPop<CR>

* vim version:   VIM - Vi IMproved 7.4 (2013 Aug 10,
* vim-go version:  the latest version 
* go version   go version go1.7 darwin/amd64

**Comment by nhooyr** [comment]
This is an issue with your configuration, not vim-go. Try to bisect your .vimrc to see what is causing the issue.

**Comment by fatih** [comment]
Hi @simon-xia , as @nhooyr said it's not  a vim-go problem. Also please use our `Plug` mappings (checkout the docs and readme on how to define a mapping). Thanks.
