### ISSUE TITLE
GoCoverageClear removes custom highlights

### ISSUE THREAD

**Issue by jasonkeene** [fatih/vim-go#1034]
### Actual behavior

I have some custom highlights in my `.vimrc`:

``` vim
highlight ColorColumn ctermbg=235
highlight NonText ctermfg=239
highlight SpecialKey ctermfg=239
highlight goSameId term=bold cterm=bold ctermbg=250 ctermfg=239
```

When I run GoCoverageClear it resets them to the default values.
### Expected behavior

I would think it should not set the highlights to their default colors. Perhaps there is a way I can override this in my `.vimrc`?
### Steps to reproduce
1. Set a custom highlight in your `.vimrc` like above.
2. Run `:GoCoverageClear` or `:GoCoverageToggle`
### Configuration
- vim version: 7.4
- vim-go version: current master (c63c798f71790c7952a9adafa866be1523f38589)
- go version: 1.7

**Comment by jasonkeene** [comment]
I worked around this by re-setting the custom highlights after the call to `go#coverage#BufferToggle`:

```vim
function! s:toggle_coverage()
    call go#coverage#BufferToggle(!g:go_jump_to_error)
    highlight ColorColumn ctermbg=235
    highlight NonText ctermfg=239
    highlight SpecialKey ctermfg=239
    highlight goSameId term=bold cterm=bold ctermbg=250 ctermfg=239
endfunction

autocmd FileType go nmap <leader>c :<C-u>call <SID>toggle_coverage()<CR>
```

**Comment by fatih** [comment]
This is fixed now. `:GoCoverage` doesn't mess up with the syntax anymore, so you should be good to go. Thanks for reporting.

**Comment by jasonkeene** [comment]
@fatih thank you!
