### ISSUE TITLE
Highlight variable names in assignment statements

### ISSUE THREAD

**Issue by Quentin-M** [fatih/vim-go#1038]
It would be nice to highlight variable names in assignment statements.
For instance, the letters `a, b, c, d, e, f` would have to be highlighted in the following cases:

```
var a, b = "a", "b"
const c = "c"
d, e := "d", "e"
f = "f"
```

Thanks!

**Comment by fatih** [comment]
HI @Quentin-M 

The current state of highlighting is already complex and very large. I don't want to introduce anything else as it makes things more slower. Thanks for your feedback.

**Comment by xlucas** [comment]
Hello, and thanks for this great plugin!

I personally think it's a bit strange to highlight short variable declarations and not standard assignments. Many IDEs do highlight both and this allow reading code more quickly by identifying similar colors, meaning similar operations. For this reason, I've introduced `g:go_highlight_variable_assignments` in my own setup, is this part still frozen ?

**Comment by Carpetsmoker** [comment]
@xlucas This was actually added a while ago in #1426; you'll need to set `g:go_highlight_variable_declarations`.

**Comment by xlucas** [comment]
@Carpetsmoker I've already have. But this doesn't highlight variable assignments.

**Comment by Carpetsmoker** [comment]
@xlucas No, but that's a feature ;-)

If you already have some code which adds assignments too then I'm not opposed adding that too. If you open a PR I can take a look at it!

**Comment by xlucas** [comment]
@Carpetsmoker Great, here it is: #1458 :)
