### ISSUE TITLE
Gocode Windows Problem

### ISSUE THREAD

**Issue by LukeMauldin** [fatih/vim-go#1039]
### Actual behavior

Gocode auto completion is not working.  I have verified that auto completion does work in other buffers.

### Steps to reproduce:

I have attached my vim_version output and my vimrc

[vim_version.txt](https://github.com/fatih/vim-go/files/459722/vim_version.txt)

[vimrc.txt](https://github.com/fatih/vim-go/files/459728/vimrc.txt)

go version 1.7
vim-go latest version

**Comment by LukeMauldin** [comment]
I had to add this setting to my _vimrc:
`let g:go_gocode_socket_type = "tcp"`

Can that setting be defaulted on Windows or at least mentioned in the documentation?

**Comment by fatih** [comment]
Hi @LukeMauldin 

I don't want to use defaults for other types. It's in the gocode documentation and as well in the vim-go documentation. Thanks for the issue.
