### ISSUE TITLE
:GoImport doesn't auto-complete vendored packages

### ISSUE THREAD

**Issue by cskr** [fatih/vim-go#1040]
### Actual behavior

If a package is available only in vendor directory, but not elsewhere in GOPATH, it cannot be auto-completed in `:GoImport`.

### Expected behavior

Auto-complete must work for vendored packages.

### Steps to reproduce:

1. Using a vendoring tool like `govendor` fetch a package directly into vendor directory.
2. Try to auto-complete the package path in `:GoImport`.

### Configuration

* vim version: 7.4
* vim-go version: 8575d9e
* go version: 1.7.1

**Comment by fatih** [comment]
Hi @cskr 

We use `gocode` under the hood, so you should open an issue there. Thanks.

**Comment by cskr** [comment]
To be clear, I'm referring to auto-complete immediately after `:GoImport` in vim command line, not in the editor window. Is `gocode` used even there?

**Comment by fatih** [comment]
Sorry for misunderstanding. We don't have that feature. We only autocomplete package from GOPATH and GOROOT. Checking `vendor` is not supported. Feel free to open a PR, I'm more than happy to merge it in if it's fixes the problem in a simple way.
