### ISSUE TITLE
Highlights from :GoSameIds remain across files

### ISSUE THREAD

**Issue by cskr** [fatih/vim-go#1041]
### Actual behavior

Highlights created by `:GoSameIds` in a `.go` file remain at the same positions even after opening a different file.

### Expected behavior

The highlights must be hidden when switching to other files and must re-appear when switching back to the initially highlighted file.

### Steps to reproduce:

1. Open a `.go` file.
2. Highlight any identifier with `:GoSameIds`.
3. Open some other file in the same window.

### Configuration

* vim version: 7.4
* vim-go version: 8575d9e
* go version: 1.7.1

**Comment by bhcleek** [comment]
@fatih I'm willing to take this on if you want. I don't know if the entire request is possible or not, but certainly when `g:go_auto_sameids` is cleared vim-go should behave better than it does now.

**Comment by fatih** [comment]
@bhcleek sounds good 👍  I'll take a look once you open a PR. However if it'll take a long shoot, I would happy if you first comment here with the expected changes. Maybe there might be something I can give feedback. Thanks for your efforts here.
