### ISSUE TITLE
:GoBuild -tags 'debug' causes issue in neovim v.0.1.6-72

### ISSUE THREAD

**Issue by lukatendai** [fatih/vim-go#1042]
When I run 
`:GoBuild -tags 'debug'`
i got the message:
`vim-go: can't load package: package '-tags': cannot find package "'-tags'" in any of:`

it works in vim but it is broken in neovim

**Comment by fatih** [comment]
Hi @lukatendai 

I don't use neovim, and unfortunately have limited time to work on these. Unless someone wants to deal with it there is not much I can do. I'll keep this up for 1 month. If anyone comes during this time and want to work on this, let me know.

**Comment by lukatendai** [comment]
Hi,

It looks like the problem is with Spawn function. If I comment line 29 to 33 in vim-go/autoload/go/cmd.vim
then it works correctly...

Might be something with the args and escaping sing quotes too...

**Comment by lukatendai** [comment]
yah... looks like  go#util#Shelllist causes a problem with neovim... let me think about the solution
