### ISSUE TITLE
vim-go: guru: no object for identifier

### ISSUE THREAD

**Issue by danielmanesku** [fatih/vim-go#1044]
### Actual behavior

"vim-go: guru: no object for identifier" appearing in messages 

### Expected behavior

Definition/documentation shows up

### Steps to reproduce:

Have simplest go hello world code
```go
package main

import "fmt"

func main() {
        fmt.Println("vim-go")
}
```

1. Hover over "Println"
2. Hit "g d" or "ctrl + ]" to go to definition
3. Error `vim-go: guru: no object for identifier` shows up

### Configuration

Previously had NeoVim 0.1.13 from stable channel in brew and go 1.6.x. Things worked alright on this configuration. 
After upgrading to go 1.7.1, this started happening. In hope that things were fixed, I upgraded to latest NeoVim from dev channel and upgraded all vim plugins.

Now even going back to go 1.6.2 doesn't help. 

How to debug this issue?  
There is a similar issue #851, which further links to an issue with calling C code. Here we have the most basic code, the happy path. Can we at least confirm that we are calling `guru` in the right way? How to get byte offset from this example to `guru` from command line, in order to confirm/deny if the bug is on x/tools/cmd/guru side?

* `vimrc` you used to reproduce
```
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'fatih/vim-go'
call vundle#end()
filetype plugin indent on
```
* vim version: NVIM v0.1.6-84-g13db923
* vim-go version - latest probably 8575d9e, just updated it with PluginInstall
* go version - tried both 1.6.2 and 1.7.1

**Comment by nhooyr** [comment]
Have you tried `:GoUpdateBinaries`?

**Comment by danielmanesku** [comment]
@nhooyr thank you! It solved the problem.
Wrong assumption on my side that those will get automatically updated when switching to newer version of go.

**Comment by doop-ymc** [comment]
@danielmanesku is _:GoUpdateBinaries_ work?

**Comment by danielmanesku** [comment]
@doop-ymc yes, that solved it
