### ISSUE TITLE
Invite user to issue the command :GoInstallBinaries

### ISSUE THREAD

**Issue by RIscRIpt** [fatih/vim-go#1045]
Installed vim, go, and vim-go plugin. None of go binaries are compiled. Run vim:
#### Actual behavior

No warning message, that go binaries are not installed.
#### Expected behavior

Warning message: Please run the command `:GoInstallBinaries`, else other issues may occur.

This could fix a lot of issues and prevent headaches for new comers and for those who move around with their .vim files a lot and forget to install go binaries.
For example without go binaries [plugin neocomplete shows an error](https://github.com/Shougo/neocomplete.vim/issues/542):

```
[neocomplete] Error occurred calling omnifunction: go#complete#Complete
[neocomplete] function <SNR>137_complete_delay[3]..<SNR>137_do_auto_complete[43]..neocomplete#complete#_get_results[23]..neocomplete#complete#_set_results_words[25]..83[1]..<SNR>132_set_complete_results_words, line 11
[neocomplete] Vim(let):E121: Undefined variable: words
```

I suppose this should be fixed on the side of vim-go, as it will prevent issues in the other plugins, which rely on vim-go functionality as well.
#### Suggested fix

Use `echoerr` or `echom` instead of `echo` [when reporting this issue](https://github.com/fatih/vim-go/blob/1a9cc786751947441f05b92f380540dee388feff/autoload/go/path.vim#L164):
`"vim-go: could not find '" . basename . "'. Run :GoInstallBinaries to fix it."`

**Comment by nhooyr** [comment]
I really like this idea, I was very confused the first time I installed vim-go and nothing worked.

**Comment by fatih** [comment]
We have already this feature. If you for example run `:GoImports`, or `:GoDef` you'll get prompted. Are those not working anymore?

**Comment by fatih** [comment]
Thanks @johnzeng, so this issue is about giving an error if `gocode` is not installed for the completion commands.

**Comment by fatih** [comment]
Pushed the change to master.
