### ISSUE TITLE
Can not work with vimproc in win10

### ISSUE THREAD

**Issue by fcymk2** [fatih/vim-go#1050]
when i save by :w 
>[vimproc] vimproc#get_command_name: File "D:toolsGobingofmt.EXE" is not found

the go bin path is invalid,miss the "\"

If i disable vimproc, it work right.

vim version 8.0.0.3

**Comment by fatih** [comment]
Hi @fcymk2 

Thanks for the report, but going forward I'm going to remove vimproc support from vim-go. I'm not using it as well so I'm not able to help you. Thanks.

**Comment by uwydoc** [comment]
well, it should be a problem with `vimproc#get_command_name`(`go#util#System` internally invokes `vimproc#system2`, which internally invokes `vimproc#get_command_name`), which did not work well with the path returned by `exepath`(`go#path#CheckBinPath` internally invokes it) on Windows(it's not a win10 specific problem).
Here is a quick workaround from me: uwydoc/vim-go@fe54a4b7aaa8f54211a5b7a625a6186dace7c4a5
Just replace all '\' with '/' in the command name before passing it to vimproc.
