### ISSUE TITLE
Feature request: add go_command variable

### ISSUE THREAD

**Issue by fabstu** [fatih/vim-go#1054]
Hello fatih, I wrote my own little go wrapper which adds tags for me. I set 
```
alias go=my-wrapper
```
and this works in console, but vim does not take this up. So right now I'm moving /usr/bin/go -> /usr/bin/go.orig and calling that from my wrapper, that feels a little ugly.

# Feature g:go_command
g:go_command would be the variable where a custom go binary can be set, following the example of g:go_fmt_command.

This would be useful in cases like
- setting specific go release to use
- using custom go wrapper

Would you be willing to implement this? I've got no idea where to even start with vim.

**Comment by fatih** [comment]
Hi @fabstu 

Unfortunately due the way how vim-go works and enforces building it's not possible to change the default command. You still can change it yourself  however I do not plan to integrate something like this. Thanks!
