### ISSUE TITLE
No way to customize build command.

### ISSUE THREAD

**Issue by kojustin** [fatih/vim-go#1056]
### Actual behavior

I can't pass GOOS or GOARCH to the "go build" command

### Expected behavior

Be able to customize the build command

### Configuration

vim-go at 8205e35

The go build command respects the GOARCH and GOOS environment variables. These variables change the destination OS when building. I build on Mac but want to target Linux. It would be nice if vim-go supported passing these two env vars through to "go build".

**Comment by kojustin** [comment]
I can work around this by running vim with the var set `GOOS=linux vim`.

**Comment by nhooyr** [comment]
you can just do `:let $GOOS=linux` inside of vim.

**Comment by fatih** [comment]
ENV's should be set by the user. We only change the `GOPATH` and only do we add things, we don't remove them. Closing this as I believe this is not vim-go related issue. Thanks.
