### ISSUE TITLE
GoRename panic sometimes

### ISSUE THREAD

**Issue by AnomalRoil** [fatih/vim-go#1059]
### Actual behavior
When working on my latest project, I did a :GoRename logFile on a variable named file in my main function and then I got the following error: 
```
vim-go: panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x632da0, 0xc420012120)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
golang.org/x/tools/go/buildutil.ContainingPackage(0x783700, 0xc42001c044, 0x35, 0x7fff7fadf3e4, 0x3c, 0x2, 0x2, 0x69
5c95)
        /home/ubuntu/Code/golang/src/golang.org/x/tools/go/buildutil/util.go:77 +0x38d
golang.org/x/tools/refactor/rename.parseOffsetFlag(0x783700, 0x7fff7fadf3e4, 0x42, 0x8, 0x5d52634d62c7f0a9, 0x0)
        /home/ubuntu/Code/golang/src/golang.org/x/tools/refactor/rename/spec.go:222 +0x164
golang.org/x/tools/refactor/rename.Main(0x783700, 0x7fff7fadf3e4, 0x42, 0x0, 0x0, 0x7fff7fadf42b, 0x7, 0x0, 0x0)
        /home/ubuntu/Code/golang/src/golang.org/x/tools/refactor/rename/rename.go:240 +0xe89
main.main()
        /home/ubuntu/Code/golang/src/golang.org/x/tools/cmd/gorename/main.go:49 +0x1b9

Press ENTER or type command to continue
```

### Expected behavior
Well, I would have expected it to simply rename the said variable in all 5 occurrences in my function.

### Steps to reproduce:
I sadly _was not able to create a minimal working example_ of this behavior and my current project is not yet ready to be published.
I tried adding the following in my vim-go file "rename.vim" below the cmd line: 
`  let @a = cmd
  normal! G
  execute "put a"`
to get the cmd it tried to use and got the following:
` '/home/ubuntu/Code/golang/bin/gorename' -offset '/home/ubuntu/Code/golang/src/path/to/project/src/cdf.go:#2404' -to 'logFile'`
and--even more puzzling--when I tried to run it in my own terminal, **it worked** and did the job without panicking. So I really don't understand what is going on there.

The only oddity (maybe) about my project is that it has a main package split between multiple files (currently 8) for readability, but when I tried to do a MWE with 8 files for the main package, it worked.

### Configuration
I'm running VIM 7.4, huge version with most features included.
I'm using the go version 1.7.1 linux/amd64 binaries from the go website.
I've tried already to delete the compiled binaries and to do a :GoUpdateBinaries, but to no avail.

**Comment by fatih** [comment]
Hi @AnomalRoil,

This is not a vim-go issue, it's gorename that panics. You need to provide a `main.go` file, a simple file that compiles where I can test it. If you can't share your current workflow unfortunately there is no way I can reproduce it. Thanks.

**Comment by AnomalRoil** [comment]
@fatih well, I was finally able to reproduce it but it seems even stranger:
I've simply created a new file like this in a new folder in my $GOPATH/test/src/test.go:
```
package main

import "fmt"

func main() {
    fmt.Println("vim-go")
    test := 44
    fmt.Println(test)
}
```
And it has the exact same behavior: when I try to rename test, it panics, but if I copy-paste the command I get from the rename.vim file into my terminal, it works.
`'/home/ubuntu/Code/golang/bin/gorename' -offset '/home/ubuntu/Code/golang/src/test/src/test.go:#67' -to 'test2'`

It seems to come from the fact that my test folder has a src folder for the source files. (My main project folder also has a src folder for the sources.)
If I rename the src folder into something else, then it works again.

In both case it works if I use GoRename from the command line.
I don't see how to explain that it doesn't work within vim-go, but it works in the terminal.

**Comment by AnomalRoil** [comment]
@fatih The fact that it only crashes within vim-go when inside a 'src' folder could mean it is vim-go related, couldn't it?
