### ISSUE TITLE
Vim 8 branch - functional

### ISSUE THREAD

**Issue by the42** [fatih/vim-go#1065]
Is the Vim 8 - branch somewhat functional? I did a 

git clone -b vim-8.0 --single-branch https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go

but all commands available are :GoInstallBinaries, :GoUpdateBinaries and :GoPath. Is this normal?

**Comment by fatih** [comment]
It is function and works without any issues. I think how you install is wrong. I've didn't tested `vim/pack` yet, just checkout to the branch and use your usual plugin manager. Happy to get a pull request to fix the readme for installing as a pack if you want. Thanks.

**Comment by the42** [comment]
I have to come back on this. What I do is checkout the vim-8.0 branch and copy everything into
/pack/vim-go/start/vim-go/

The directory looks like this afterwards:

autoload/
compiler/
doc/
ftdetect/
ftplugin/
gosnippets/
indent/
plugin/
scripts/
syntax/
t/
templates/

When I open a go file for editing, the commands from /plugin, namely GoPath, GoUpdateBinaries and GoInstallBinaries are available. When I check this buffer with

:set ft?

it get's back with filetype=go so actually the script /ftplugin/go.vim should be read. But still only the three commands are available.

After reading http://learnvimscriptthehardway.stevelosh.com/chapters/42.html#vimplugin I do actually not see an issue here why the additional commands get not recognized.

**Comment by the42** [comment]
Sorry for all that noise, but I figured out that my install of vim had ftplugins disabled. After adding

filetype plugin on

to .vimrc all works fine now. Maybe useful here for reference.

**Comment by tsingakbar** [comment]
@the42  ur discovery saves my day
