### ISSUE TITLE
golint and gometalinter appear to be missing

### ISSUE THREAD

**Issue by aletheia7** [fatih/vim-go#1068]
I added a leader key for golint in .vimrc and it does not work. Key:

``` vim
au FileType go nmap <leader>l <Plug>(golint)
```
### Expected behavior

golint would run but does not.
gometalint does not work either. Are golint and gometalinter defined? :h vim-go says they should work.
### Steps to reproduce:

Add above leader key.
### Configuration

These work

```
:GoLint
:GoMetaLinter
```

**Comment by fatih** [comment]
Hi @aletheia7 

We have `(go-metalinter)` and `(go-vet)`. But there is no `(go-lint)`. These are defined here: https://github.com/fatih/vim-go/blob/master/ftplugin/go/mappings.vim#L67 If you want to use `(go-lint)` you need to add a new line. Mind opening a PR while you also test it? It's an easy addition and I think it would be beneficial for others as well ;)

**Comment by aletheia7** [comment]
Thank you @faith. I see that I misread the vim-go docs. I saw gometalinter and golint and thought there should have been a vim-go function entitled golint too. But the golint was referring to the go program called "golint."

I just added the following to .vimrc:
```vim
au FileType go nmap <Leader>l :GoLint<CR><CR>
```
