### ISSUE TITLE
[Question/Feature]highlight the function defined

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#1078]
```
 func a(){
}

func b(){

     a()
}
```

I want to highlight the a in b. Can it possible?

**Comment by fatih** [comment]
Add `let g:go_highlight_functions = 1` to your vimrc. Thanks

**Comment by jinleileiking** [comment]
@fatih I add this line, but cannot work in the situation I said.

**Comment by jinleileiking** [comment]
After update the plugin. It is ok!
