### ISSUE TITLE
feature requests: bind fg

### ISSUE THREAD

**Issue by miekg** [fatih/vim-go#1079]
I recently discovered 'fg', which opens the file under the cursor. It might be an interesting idea to make this do something when your cursor sits on a import path. I'm not clear exactly what, be it could open the containing directory and open the file explorer.

**Comment by fatih** [comment]
Hi @miekg 

I guess you mean `gf`? We already have a mapping `gd` that let's you jump into any file for the identifier under the cursor. I'm not sure how `gf` would be useful for Go source code. Also vim doesn't have any file explorer (expect netrw which doesn't work well). I do not think there is useful use case for us. If you provide a more useful concrete example, I'm more than happy to look at it. Thanks.
