### ISSUE TITLE
Quickfix window opening beneath TagBar

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#108]
Hi - thanks for the great work pulling `vim-go` together.

I'm using `vim-go` in combination with [TagBar](http://majutsushi.github.io/tagbar/), with TagBar taking up the standard ~10% right hand vertical of my Vim screen. 

The problem is that the quickfix window used by the various commands in `vim-go` (e.g. GoTest, the results from `gofmt`...) is placed at the bottom of the TagBar vertical split, and not across the entire bottom of the screen.

Patching `vim-go`, using `:botright cwindow` instead of plain `:cwindow` (per [the docs](http://vimdoc.sourceforge.net/htmldoc/windows.html#:botright)) fixes the issue, but I'm wondering whether I've missed something obvious on how to control where these splits/windows appear?

Thanks

**Comment by junkblocker** [comment]
Hey @fatih , can this be converted to an option? wincmd J for quickfix windows is very problematic. I'd be happy to submit a patch if you would consider accepting it.

**Comment by Rican7** [comment]
> You can add this to your vimrc, which will always push your quickfix to the bottom:
> 
> ```viml
> " This trigger takes advantage of the fact that the quickfix window can be
> " easily distinguished by its file-type, qf. The wincmd J command is
> " equivalent to the Ctrl+W, Shift+J shortcut telling Vim to move a window to
> " the very bottom (see :help :wincmd and :help ^WJ).
> autocmd FileType qf wincmd J
> ```

Commenting here for future reference, as this came up in search.

While adding `autocmd FileType qf wincmd J` to your vimrc will work, its not ideal, as "location lists" _also_ share the `qf` FileType.

If you'd like to set all quickfix windows to open full-width at the bottom, without effecting window-local location-lists, add this to your vimrc instead:

```vim
" Position the (global) quickfix window at the very bottom of the window
" (useful for making sure that it appears underneath splits)
"
" NOTE: Using a check here to make sure that window-specific location-lists
" aren't effected, as they use the same `FileType` as quickfix-lists.
autocmd FileType qf if (getwininfo(win_getid())[0].loclist != 1) | wincmd J | endif
```

(See https://github.com/Rican7/dotfiles/commit/5e00fa97267dcdef5b76f5289aefea14edcc2fc5 for example)
