### ISSUE TITLE
Using snippets with neosnippet

### ISSUE THREAD

**Issue by wayneashleyberry** [fatih/vim-go#1086]
### Actual behavior

Snippets don't expand when neosnippet is installed.
### Expected behavior

Snippets should expand as they do with ultisnips.
### Steps to reproduce:

Trying any of the aliases mentioned at https://github.com/fatih/vim-go-tutorial#snippets
### Configuration

Here's a sample `.vimrc`

```
call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
```

**Comment by fatih** [comment]
Hi @wayneashleyberry 

What do you mean they don't expand? Did you changed the setting for snippet engine  to `neosnippet`?

```
  let g:go_snippet_engine = "neosnippet"
```

**Comment by wayneashleyberry** [comment]
Turns out I didn't have neosnippet configured correctly, thanks @fatih

**Comment by NerdsvilleCEO** [comment]
I am running into this too, the snippet engine is set to neosnippet
