### ISSUE TITLE
Preview buffer does not show Comments

### ISSUE THREAD

**Issue by josefcs** [fatih/vim-go#1087]
This is a duplicate of #754 (but I can't reopen it), in which @fatih stated that the underlying problem has to be solved in order to proceedd further on this topic.

Now, with (go-doc) working and displaying the documentation for identifiers correctly, is there a chance that issue #754 will be revisited?

**Comment by fatih** [comment]
Hi @josefcs 

Thanks for opening. As I've said, it's not performant to call two explicit, independent commands for completion candidate. Completion candidates have to be very fast.  Until `gocode` has this feature there is not much to do. Thanks.
