### ISSUE TITLE
[feature]Highlight local vars

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#1088]
I know this is very difficult:

Hight the var in the func:

```
fun boo() {

   var  a string

 
    fmt.Println(a)

}

```

Highlight the a in `fmt.Println(a)`

**Comment by fatih** [comment]
Hi @jinleileiking 

Please read the tutorial https://github.com/fatih/vim-go-tutorial or the doc: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt 

These are all documented. For your case use `:GoSameIds` or `:GoSameIdsAutoToggle`

Thanks

**Comment by jinleileiking** [comment]
@fatih :GoSameId is not I want.
I mean highlight the vars, not at my cursor. 
Just like the functions, when open the file, it highlights.

**Comment by fatih** [comment]
@jinleileiking this is not supported as it requires AST based highlighting. Vim-go doesn't support it. However you can call `:GoSameIds` if needed. I know it's not the same but variable highlighting is not useful if you have multiple variables and they each share the same color. You have to create an AST tool that parses, have a color scala that increases for each new variable and be sure it's highlighted correctly.

**Comment by jinleileiking** [comment]
@fatih Thanks a lot, my load.
