### ISSUE TITLE
GoAddFields

### ISSUE THREAD

**Issue by pengux** [fatih/vim-go#1090]
This is a feature request. Running go vet command sometimes returns `composite literal uses unkeyed fields` where there is a struct initialization in the code with no field names. It would be great to have a command `GoAddFields` that works similar to `GoAddTags` and allows the user to add the fields to the struct.

**Comment by zmb3** [comment]
Sounds like a good idea for a tool that all editors can use.

**Comment by fatih** [comment]
We have it now with the :GoKeyify command (https://github.com/fatih/vim-go/pull/1258). Please pull latest master to use it. Thanks
