### ISSUE TITLE
:GoImports (and :GoFmt) do not work when buffer is not written to disk

### ISSUE THREAD

**Issue by opennota** [fatih/vim-go#1094]
### Actual behavior

`:GoImports` returns an error when called on an unsaved buffer.

### Expected behavior

`:GoImports` works without errors and adds all the necessary import statements.

### Steps to reproduce:

Open vim or neovim, do `:set ft=go` and type the following:
``` go
package main
func main() {
	fmt.Print()
}
```
Then do `:GoImports`. The editor displays an error:
```
Error detected while processing function go#fmt#Format:
E32: No file name
```

**Comment by Loggie** [comment]
The issue here is not that the buffer has not been written to the disk, but that vim was opened without a filename.  If a new filename is specified when opening vim then It appears vim-go automatically saves the file before performing these commands.

**Comment by fatih** [comment]
Hi @Loggie 

This is normal. You have to first write it, such as `:w main.go` and then call `:GoFmt` or `:GoImports`.  Because both commands work on files, not buffers. Also it's a very low probabiliy to open a text and setting the filetype. Thanks for opening.
