### ISSUE TITLE
Neovim v0.1.6 stable + vim-go + delimitMate = freeze

### ISSUE THREAD

**Issue by vbauerster** [fatih/vim-go#1095]
### Actual behavior

First, I'm not sure if it is vim-go problem, but the issue is specific to *.go file types only.
I have [delimitMate](https://github.com/Raimondi/delimitMate) plugin installed with `g:delimitMate_expand_cr=1` option on, which expands matched pair with indentation on the next line.
If I expand nested brackets `{}` neovim freezes. See below what I mean:
```
{
   {|}   // pressing enter here, causes neovim to freeze
}
```

I tested this with different file types like *.js, *.txt, etc, but freezing happens only with go files.
If you think it is not vim-go problem, please let me know, and I'll open it at delimitMate repo.

### Expected behavior

I expect nested brackets to expand, as it is in other file types.

### Steps to reproduce:
described above
### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
```vim
  let g:go_highlight_functions = 1
  let g:go_term_enabled = 1
  let g:go_fmt_command = "goimports"
  
  let g:delimitMate_expand_cr = 1
```
* nvim version: 0.1.6 stable
* vim-go version: 10c805b
* go version: 1.7.3

**Comment by rvolosatovs** [comment]
I am not using delimitMate, but I am experiencing constant freezes to the point where I have to close the terminal, as `vim-go` renders `nvim` is absolutely unusable(sometimes I manage to spam `^C` and type `:q!`, but that does not happen often. `:mes` shows nothing). The problem did not exist before and I can not believe I am the only one...

* nvim 0.1.6 (Build type: RelWithDebInfo)
* vim-go 10c805b
* go 1.7.3

**Comment by vbauerster** [comment]
I have switched to [auto-pairs](https://github.com/jiangmiao/auto-pairs), which so far plays nicely with vim-go.
@rvolosatovs Well I didn't have such problem. Does your terminal run any post close scripts, which may slow down closure?

**Comment by rvolosatovs** [comment]
no, not really.. I use `termite`

and the freezes happen as soon as I open any Go file. (also an empty one) Super weird - it appeared suddenly and I just can not figure out why

**Comment by fatih** [comment]
Hi Everyone,

I appreciate you guys open a bug report. However as I said here https://github.com/fatih/vim-go#using-with-neovim-beta I have limited time to look at issues. I expect someone from the community to look at these problems as I don't use Neovim. I'm tagging this as Neovim and if there is a solution, feel free to post it here so I can close it. I'm also installing latest Neovim to check if I can reproduce it (I'm using delimitmate with Vim 8.0 + vim-go without any single issue).

Thanks

**Comment by fatih** [comment]
Just tested with Neovim v0.2.0 and it doesn't freeze for me. Closing this as it seems like it might be caused my something else. Thanks!
