### ISSUE TITLE
cannot jump to symbol in vendored package

### ISSUE THREAD

**Issue by vimalk78** [fatih/vim-go#1096]
### Actual behavior

i have a project which has vendored packages under the folder $PROJECT/cmd/vendor

while jumping to definition, it should find the symbol from the vendor folder

### Expected behavior

but doing Ctrl+] is not able to jump to the symbol if the package is in vendor folder. it can only locate and jump if the package is under $GOPATH

### Steps to reproduce:

as mentioned above

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: 7.4.488
* vim-go version : master
* go version : 1.7

**Comment by edganiukov** [comment]
Do you use go1.6+ vendoring? If yes, then vendor directory should be under `$PROJECT/vendor`

**Comment by vimalk78** [comment]
the source i use is

https://github.com/coreos/etcd/tree/master/cmd/vendor

**Comment by edganiukov** [comment]
@vimalk78 yes, and as you can see in `build` file, its links to GOPATH
`ln -s ${CDIR}/cmd/vendor ${etcdGOPATH}/src`

**Comment by fatih** [comment]
Hi @vimalk78 

Please share your vimrc. with `Guru describe` vendoring is supporting and it shouldn't be a problem (I use it myself already without any issue). Or please update `guru` via `:GoUpdateBinaries`

**Comment by vimalk78** [comment]
hi @fatih 

here is my vimrc

[vimrc.txt](https://github.com/fatih/vim-go/files/576626/vimrc.txt)

**Comment by fatih** [comment]
Just tested it and it works fine without uses with standard mode `guru`:


```viml
  let g:go_def_mode = 'guru'
```

please be sure you're using latest vim-go with this setting. Thanks
