### ISSUE TITLE
:GoBuild leaves error window open

### ISSUE THREAD

**Issue by the42** [fatih/vim-go#1097]
### Actual behavior
When I :GoBuild a file with errors, the quickfixlist appears and I can jump to my errors. When I fix them and run :GoBuild again, the quickfix list remains as it was.

### Expected behavior

Quickfix list to disappear if there are no errors in code

### Configuration

vim version 8.0.69
go-vim version vim-8.0  9820d26 
go version 1.7.3

**Comment by fatih** [comment]
Hi @the42,

I've tested it again it closes the window. Can you please test against the latest master as it includes now vim 8.0 related changes

**Comment by the42** [comment]
I insert a link to imgur to show what I mean: GoBuild reports success whereas the Quickfix list shows there are still pending issues.

http://imgur.com/a/lIo9T

Used branch master at commit 59c56f0903a1ed

**Comment by fatih** [comment]
I wonder if this is the same problem as https://github.com/fatih/vim-go/issues/1109 

For me it, If I fix it it closes the error. @the42 and @vdemario, can you please update to at least version `8.0.91` ? Because there were some problems about getting the exit status, which was fixed lately.

**Comment by the42** [comment]
Concerning vim I am on 8.0.92, ppa from https://launchpad.net/~jonathonf/+archive/ubuntu/vim

I completely deleted vim-go and made a fresh clone of the master branch yesterday which should include your vim-8 merger.

Yes, this sounds definitely to be the same issue as #1109

**Comment by fatih** [comment]
Closing this, let's continue from #1109 as it's hard for me to track both issues.
