### ISSUE TITLE
Can not execute command

### ISSUE THREAD

**Issue by doublelucky** [fatih/vim-go#1105]
Hi fatih,
I have some difficulty about vim-go.
When I installed the plugin,only use some of the highlighted features.such as:  
```bash
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
```
These work well.But when I use some commands, such as GoInfo(au FileType go nmap <Leader>i <Plug>(go-info))..and more,Vim suggested me some mistakes,like:
![](http://ww3.sinaimg.cn/large/c704dca4gw1f9znlyt1vbj20qp02i0t1.jpg)  
Its English meaning is probably:  
E488: Extra trailing characters
E126: MIssing:endfunction
I have not edited any vim-go code,And is installed through the vundle.My os is Linux mint 18.3
I am a novice vimer,I did not search for a solution to the problem.May be a character reason?
(I have another computer with exactly the same system and vimrc,it can work well)
Thanks.
### Configuration
* `vimrc` you used to reproduce
about vim-go:
```bash
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_fmt_autosave = 1
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['errcheck', 'govet', 'golint']
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
let g:go_list_type = "quickfix"
let g:go_auto_type_info = 1

au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gi <Plug>(go-import)
au FileType go nmap <leader>gr <Plug>(go-run)
au FileType go nmap <leader>sr <Plug>(go-rename)
au FileType go nmap <leader>gb <Plug>(go-build)
au FileType go nmap <leader>gc <Plug>(go-callers)
au FileType go nmap <leader>gd <Plug>(go-doc-browser)
```
* vim version:
7.4.1689
* vim-go version
latest
* go version
1.7.3

**Comment by fatih** [comment]
Thanks @doublelucky. I've pushed a fix to master, pleasy try again.

**Comment by doublelucky** [comment]
Now,it works well! thank you.
