### ISSUE TITLE
:GoInfo not working in of 59c56f0

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#1108]
### Actual behavior

`:GoInfo` crashes with:

```
Error detected while processing function go#guru#DescribeInfo[103]..<SNR>99_run_guru[8]..<SNR>99_sync_guru[30]..<SNR>99_info:
line    9:
E121: Undefined variable: v:t_string
E15: Invalid expression: empty(a:output) || type(a:output) != v:t_string
```

### Expected behavior

With the cursor over an identifier in (valid) Go source code, `:GoInfo` should give type information about the identifier under the cursor

### Steps to reproduce:

Simply enable `vim-go` enabled and then:

1. Open a Go source file
2. Move the cursor to an identifier
3. Call `:GoInfo`

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce: minimal, only loading `vim-go`
* vim version: `NVIM v0.2.0-103-g6b1c8bb`
* vim-go version: `59c56f0`
* go version: `go version go1.7.3 linux/amd64`

### Notes

This was working fine in 10c805b, but it seems the implementation of `:GoInfo` was changed over to be `guru` based in https://github.com/fatih/vim-go/commit/dc8073386754bf5ca09a8dbe2bd9cc8886c61446

**Comment by kron4eg** [comment]
I'm experiencing the same, just want to add that it crashes only under neovim, under regular vim (8.0.0094) it's OK.

**Comment by fatih** [comment]
Thanks for opening the bug report. Part of merging to master is to see these kind of issues and fixes it until we release the stable release. I'm going to fix it while I'm back home (I'm currently on travel to home)

**Comment by fsouza** [comment]
@fatih I'm also seeing a similar failure with goSameIds + neovim. Should I open a new issue?

```
Error detected while processing function go#guru#SameIds[24]..<SNR>107_run_guru[8]..<SNR>107_sync_guru[30]..<SNR>107_same_ids_highlight:
line   11:
E121: Undefined variable: v:t_dict
E15: Invalid expression: type(result) != v:t_dict && !get(g:, 'go_auto_sameids', 0)
```

Thanks!

**Comment by fsouza** [comment]
@fatih are ``s/v:t_dict/type({})/`` | ``s/v:t_string/type("")/`` acceptable fixes for this issue?

**Comment by fatih** [comment]
@fsouza yes, was going to ditch the variables in favour of old ones.

**Comment by fatih** [comment]
Thanks for opening. Should be fixed now. I've double checked with neovim and works without any problem.

**Comment by myitcv** [comment]
Thanks @fatih, seems to work.

However, based on my immediate testing, I think we should revert the `guru`-based `:GoInfo`solution:

1. it is not quick enough for someone invoking `:GoInfo` manually (I don't have any experience with the new auto-info mode)
2. It's logic for type name qualification is different to that of `gocode`

I have:

```vim
nmap <buffer> <Leader>h : <C-u>:GoInfo<CR>
```

and hence expect a fast response to question; we don't have that with `guru` (yet), there is a noticeable lag (which would also be there in auto-info mode)

Also, given discussion in https://github.com/mdempsky/gocode/issues/18, qualification of type names is different. `guru` uses package path (as @mdempsky points out); `nsf/gocode` uses package name, and we're looking to improve that in `mdempsky/gocode` to be a function of the imports in the current file (i.e. the file in which `:GoInfo` has been invoked)

Can we leave `:GoInfo` as is for now, i.e. based on `gocode`, and use something else for the auto-info mode?

**Comment by fatih** [comment]
@myitcv thanks for the feedback. I'm using `:GoInfo` and also have quite the same experience. For `1`, `gocode` can't be beat as it's caching already and due it's server side architecture. For `2` I was thinking to fix it by changing the output of `guru`.

There is also another point (let's say `3`). Guru doesn't need the `GOPATH/pkg` folder at all and works for any kind of source code on the go. It's more reliable and always returns an information.

So my plan is. 

* Revert it back to `gocode`. 
* Add an option to switch the mode, (just like we have for `:GoDef`), such as `go_info_mode = "gocode"`
* Fix `guru` to return human readable identifier text

**Comment by myitcv** [comment]
Sounds like a good approach for now

**Comment by fatih** [comment]
I've implemented the new `go_info_mode` setting: https://github.com/fatih/vim-go/pull/1119 By default `gocode` is being used. I'm using myself `guru` and going to observe how it works in long term.

**Comment by myitcv** [comment]
Great, thanks - d079826 is working for me
