### ISSUE TITLE
Autowrite and external commands: disregard unnamed buffers

### ISSUE THREAD

**Issue by the42** [fatih/vim-go#1112]
### Actual behavior

When running :GoBuild (possibly other commands as well) throws an error if there are unnamed buffers:

Error detected while processing function go#cmd#Build[18]..<SNR>45_cmd_job[11]..go#cmd#autowrite
line 2
E141: No file name for buffer 5

### Expected behavior

disregard unnamed buffers when autowriting and calling external commands

### Configuration

Vim 8.0.92
go 1.7.3
vim-go 59c56f0903a1

**Comment by fatih** [comment]
Can you please provide a reproducible case. I don't know any details as you didn't provide it. Thanks

**Comment by the42** [comment]
1. Open a Go source file
2. :vnew a new buffer
3. Inset some text into that buffer
4. Switch to the buffer with the Go source file
5. execute any :Go - command which results in autosaving
6. Command will fail as there are buffers which can't be saved because they have to filename to write to

**Comment by fatih** [comment]
Thanks for the steps. I could reproduce it. That's weird though because we didn't changed how autorwite works. This is the code:

```
function! go#cmd#autowrite()
  if &autowrite == 1
    silent wall
  endif
endfunction
```

and `wall` explicitly says it doesn't write buffer with no name:

```
							*:wa* *:wall*
:wa[ll]			Write all changed buffers.  Buffers without a file
			name or which are readonly are not written. {not in
			Vi}
```

I wonder if there is a setting that changes this behaviour. Or this is a new bug that was introduced later.

**Comment by fatih** [comment]
Fixed it by swallowing the error for now, as other buffer doesn't interest us. Thanks for the feedback.

**Comment by the42** [comment]
I also filed a bug for vim and Bram replied, so it seems yielding an error here is the right behaviour:

https://github.com/vim/vim/issues/1272#issuecomment-262768182
