### ISSUE TITLE
GoTestFunc fails with vim8 (works with vim7)

### ISSUE THREAD

**Issue by rgerardi** [fatih/vim-go#1116]
### Actual behavior

Running `:GoTestFunc` in Vim 8 fails with the following error:
```
vim-go: can't load package: package '-run': cannot find package "'-run'" in any of: ^I/usr/local/Cellar/go/1.7.3/libexec/src/'-run' (from $GOROOT)...
```

GoTest works.

### Expected behavior

`:GoTestFunc` should succeed as it does when using Vim 7
```
vim-go: [test] PASS
```

### Steps to reproduce:

Created simple test scenario to reproduce the issue:

cat main.go
```
package main

import "fmt"

func sum(a, b int) int {
    return a + b
}

func main() {
    fmt.Println("Hello World")
}
```

cat main_test.go
```
package main

import "testing"

func Test_Sum(t *testing.T) {
    a := 5
    b := 6
    res := a + b

    actual := sum(a, b)

    if actual != res {
        t.Errorf("Test Sum failed. Expected %d, got %d\n", res, actual)
    }
}
```
Execute `:GoTestFunc`

### Configuration

* `vimrc` you used to reproduce
```
execute pathogen#infect()
syntax on
filetype plugin indent on
```

* vim version: Vim 8.0 patches: 1-94
* vim-go d3c4fb3d2413
* go 1.7.3

It works using the same version of Go and vim-go, in Vim 7

**Comment by fatih** [comment]
This is now fixed. Can you please pull latest master and try again? Let me know if it's still doesn't work for you. Thanks for the feedback, much appreciated 👍

**Comment by rgerardi** [comment]
Hi Fatih,
Tested and it's working perfectly!
Thank you!
Ricardo
