### ISSUE TITLE
:GoDef in modified buffer fails

### ISSUE THREAD

**Issue by bhcleek** [fatih/vim-go#1125]
This is a regression of changes introduced in #944 to avoid errors when trying to `:GoDef` in a modified buffer. The regression was introduced in #1083 (apparently deliberately?).

### Actual behavior

vim-go displays an error,
>  Error detected while processing function go#def#Jump[86]

### Expected behavior

A buffer should be opened and the cursor placed at the position of the definition of the identifier that was under the cursor when `:GoDef` was run.

### Steps to reproduce:

1. Open a file and modify it without saving
2. Place the cursor on an identifier that is declared in another file
3. run `:GoDef`

### Configuration
* vim-go version: 1.10

**Comment by fatih** [comment]
@bhcleek I've tried it and it works without a problem 🤔  I've even changed the settings and tried both with `guru` and `godef`. 

The change fixed the problem that it would open a new split if the file was modified. I think it's the correct thing, and the error you get doesn't happen for others (including me). Do you use a vim version that might be old? Or any plugin you added? Can you just try it with vim-go?

**Comment by bhcleek** [comment]
I'm using vim 8.0.0094 (installed with brew) on macOS Sierra. It happens when vim-go is the only plugin loaded. Is it possible that you're testing by jumping to a definition that's in the modified buffer instead of in another file?

**Comment by bhcleek** [comment]
@fatih I think you may not be seeing the error, because you have `hidden` enabled. After submitting #1132, I realized that to see this error `hidden` must be disabled.
