### ISSUE TITLE
gocode unimported packages not work with YouCompleteMe

### ISSUE THREAD

**Issue by on99** [fatih/vim-go#1126]
### Actual behavior

I've set `let g:go_gocode_unimported_packages = 1` in my vimrc but when I edit a new go file and enter `fmt. C-x C-o` the methods in fmt package do not populate.

### Expected behavior

Methods, types, constants in fmt package should populate.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: 8.0.94
* vim-go version: v1.10
* go version: go1.7.1

It works when YouCompleteMe is disabled. So this may not be an vim-go issue but YCM issue.

**Comment by fatih** [comment]
Hi @on99.

It works when you type `f` and then hit `c-x c-o` you should see that it tries to complete it. Unfortunately I don't have much to say here as YCM is a standalone plugin it self and it provides much of the vim-go functionality itself. Thanks for opening though.
