### ISSUE TITLE
Issues with redo after save

### ISSUE THREAD

**Issue by KarboniteKream** [fatih/vim-go#1134]
### Behavior
It seems that the issue described in #40 is happening again.

### Steps to reproduce:
1. Make two changes (`a:=123` and `foobar`).
2. Undo `foobar`.
3. Save the buffer.
4. Unable to redo `foobar`.

### Configuration
My vimrc only has `set nocompatible` and `vim-go`.

* vim version: MacVim 8.0.94
* vim-go version: master
* go version:  1.7.3

**Comment by fatih** [comment]
Hi @KarboniteKream 

Due the way how we format the buffer, unfortunately Vim messes up the history. Checkout `fmt.vim` for more info. There is an experimental mode, which for some works, you can try it to see if it fixes it for you:

```
let g:go_fmt_experimental = 1
```

Thanks
