### ISSUE TITLE
Weird underscoring of variables/type name with a wavy red line 

### ISSUE THREAD

**Issue by vitalyisaev2** [fatih/vim-go#1138]
First of all I would like to thank contributors for a very beautiful and useful Vim plugin.

### Behavior

I have just installed ```vim-go``` as a part of ```spf-13``` vim distribution on a brand new desktop (```Fedora 25```). When I open existing file in gvim, many variables are underscored with a red wavy line. What is it? How can I disable it?
[![Screenshot from 2016-12-06 15-58-36.png](https://s17.postimg.org/b8gdvtkj3/Screenshot_from_2016_12_06_15_58_36.png)](https://postimg.org/image/gjvagj6ln/)
### Steps to reproduce:

1. Prepare clean Fedora 25 instance;
2. ```dnf install gvim```;
3. ```echo "let g:spf13_bundle_groups=['general', 'writing', 'neocomplete', 'programming', 'go', 'scala', 'python', 'javascript', 'html', 'misc',]" >> ~/.vimrc.before.local```;
4. Launch Gvim and type ```:PluginInstall``` (this will install ```fatih/vim-go```);
5. Try to open some Go sources;

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vimrc: delivered via ```spf-13```, but with a custom ```.vimrc.before.local``` (see above)
* vim version: vim-X11-8.0.118-1.fc25.x86_64 (Fedora 25)
* vim-go version: latest
* go version: 1.7.3

**Comment by cznic** [comment]
`:set nospell`

See also https://www.linux.com/learn/using-spell-checking-vim

**Comment by vitalyisaev2** [comment]
@cznic many thanks!
