### ISSUE TITLE
Neovim: "E118: Too many arguments for function: <SNR>173_on_exit" 

### ISSUE THREAD

**Issue by entombedvirus** [fatih/vim-go#1144]
### Behavior
A change in neovim has caused commands that use `jobcontrol.vim` to throw this error:

```
E118: Too many arguments for function: <SNR>173_on_exit
```

The details of the neovim change is at https://github.com/neovim/neovim/wiki/Following-HEAD:

> 
>[ #5529](https://github.com/neovim/neovim/pull/5529) merged Vim's support for "partial functions" which made Nvim more strict about when the implicit self variable is available. Functions that reference self (which is common with job callbacks) must either be declared as dict functions:
> 
> function! s:on_stdout(id, data, event) dict abort
> or as part of the job options dictionary:
> 
> let s:opts = { ... }
> function! s:opts.on_stdout(id, data, event) abort
> Job callbacks also must have at least 3 parameters now. See https://github.com/neovim/neovim/issues/5763#issuecomment-266722407

I was expecting :GoBuild, :GoInstall etc to continue to work w/o error after upgrading the latest neovim.

### Steps to reproduce:

1. Install neovim from HEAD (`brew install neovim/neovim/neovim --HEAD`)
2. Install vim-go
3. Open any `.go` file
4: Issue command :GoBuild

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* neovim version: f089d29
* vim-go version: 08c881d
* go version: go1.7.4 linux/amd64

**Comment by dshcherb** [comment]
I can confirm this:
dpkg --status neovim | grep Version
Version: 0.1.5ubuntu1+git201612161508+2974+22~ubuntu16.04.1

:GoBuild results in "E118 Too many arguments for function: <SNR>76_on_exit"
