### ISSUE TITLE
Display shortened file name when using :GoCallers

### ISSUE THREAD

**Issue by skogar42** [fatih/vim-go#1147]
### Behavior

When I use :GoCallers, and the file is outside of the current directory, the full path of the file is displayed.  The way my workspace is structured, the directory depth is very deep. It would be nice to have an option to truncate the file display to be shorter.  If you think this is possible to do, I can try and make the change.

### Steps to reproduce:

1.  Under a project directory called "testing" (this can be whatever you want), create two files in different directories.  In my example, I have the directories and files: lib/lib.go and test/test.go.
2.  In lib.go, create a hello world library call:
```
package lib
import "fmt"
func Hello() {
    fmt.Println("Hello")
}
```
3. In test.go, call the function
```
package main
import "testing/lib"
func main() {
    lib.Hello()
}
```
4. :GoGuruScope testing/...
5. In lib/lib.go, :GoCallers on the Hello() function
6. I get this output:
```
lib.go|5 col 6| testing/lib.Hello is called from these 1 sites: 
/usr/local/home/me/workspace/go/src/testing/test/test.go|6 col 11| static function call from testing/test.main 
```

### Configuration

* `vimrc` you used to reproduce: I did nothing special for :GoCallers
* vim version: 7.4.1816
* vim-go version: v1.10
* go version: 1.6

**Comment by fatih** [comment]
Hi @skogar42 

Unfortunately there is no way to change that. It depends on where you're been. If you `cd` into one level below those will be displayed as shortened. This is a quickfix feature and we don't have any access over it unfortunately. Thanks.
