### ISSUE TITLE
GoImpl always creates pointer receiver

### ISSUE THREAD

**Issue by brunnre8** [fatih/vim-go#1148]
### Behavior

When one has the cursor on a type and hits `:GoImpl $INTERFACE` the interface implementation is generated (good) but always with pointer receivers. This happens even if the thing under the cursor is the concrete type and not a pointer to it.

This is in several cases not the desired behavior and it gets tedious if a interface is large and one has to adjust each and every method call.

Is this the expected behavior? Can this be overridden?
Should I file an upstream bug?

Thanks in advance.

### Steps to reproduce:

In `main.go`:
```go
package main

type test []int
```

put the cursor on test and do `:GoImpl sort.Interface`

ends up like this
```go
package main

type test []int

func (t *test) Len() int {
	panic("not implemented")
}

func (t *test) Less(i int, j int) bool {
	panic("not implemented")
}

func (t *test) Swap(i int, j int) {
	panic("not implemented")
}
```

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vim-go version: git master (v1.10)

**Comment by fatih** [comment]
Hi @brunnre8 

You're using the convenient shortcut of `:GoImpl`. However if you read the docs you'll see that there are many way of specifying the receiver.  You have to use:

```
:GoImpl t test sort.Interface
```

this will produce what you want. Thanks
