### ISSUE TITLE
GoImport doesn't work with 3rd party package names

### ISSUE THREAD

**Issue by fhmily** [fatih/vim-go#1150]
### Behavior

`:GoImport` suddenly doesn't work with package names. Which as far as I remember, should be working when I used it weeks ago.

Commands like `:GoImport redis` and `:GoImport json` failed
While: `:GoImport gopkg.in/redis.v5` and `:GoImport encoding/json` succeed

BTW, Both `:Goimports` and `:GoFmt` do the job while `:GoImport` doesn't.

### Steps to reproduce:

1. import vim-go as the only plugin through vim-plug
2. `:GoUpdateBinaries` reinstall all the dependencies, succeed
3. `vim main.go`, default func main with `fmt.Println("vim-go")` template loaded
4. `:GoImport os`, succeed
5. `go get gopkg.in/redis.v5`, succeed
6. `:GoImport redis`, error message: "_Can't find import: redis_"
7. `:GoImport json`, error message: "_Can't find import: json_"
8.  add `redis.NewClient()` line into the main func , run `:GoImports` or `:GoFmt`, then `redis "gopkg.in/redis.v5"` imported
9.  `:GoImport encoding/json`, succeed

### Configuration

* `vimrc` you used to reproduce: nothing special other than vim-go and vim-plug with some basic vim format settings
* vim version: 8.0.2
* vim-go version: lastest (auto installed by vim-plug)
* go version: 1.7.4

**Comment by fhmily** [comment]
I've tried to debug this myself but had no luck. 

One thing I noticed from vim log level 9 output is it seems the magic of `:GoImport` come from `go list`. Which should explain why the import failed. As this command also failed if I ran it manually in the shell with following outputs.
`can't load package: package redis: cannot find package "redis" in any of:`
	`/usr/local/go/src/redis (from $GOROOT)`
	`/Users/jack/gopath/src/redis (from $GOPATH)`

But what I don't understand is. How `:GoImport redis` accomplished the job before but not now.

**Comment by fatih** [comment]
Hi @fhmily 

The usage you're reporting is correct and it was always like that. I think it's like that for at least 9/10 months, not sure how it was before. We're also autocompleting `GOPATH` so you can write `:GoImport ...` and then hit tab to complete packages. Thanks!
