### ISSUE TITLE
GoErrCheck doesn't work in projects inside secondary GOPATH

### ISSUE THREAD

**Issue by gunnihinn** [fatih/vim-go#1151]
### Behavior

Running :GoErrCheck in a project that lives in a secondary directory in GOPATH fails.

### Steps to reproduce:

Suppose we've setup our GOPATH to have more than one directory, perhaps like this:

    GOPATH="$HOME/work/go:$HOME/golang"

If we now start a project in the *first* of these, say "$HOME/work/go/src/hello", then running :GoErrCheck fails with the error message

    import "$HOME/work/go/src/hello": cannot import absolute path
    error: failed to check packages: could not type check: no initial packages were loaded

### Thoughts on the problem

As far as I can tell, the problem is in the call to `go#package#ImportPath` in `go#lint#Errcheck`. The for loop in there always assigns `workspace` to the last of the dirs in GOPATH that passed the if check, and then assumes the project lives inside that directory. It then fails to dig the package name out of the absolute path. In our example, it tries to find the package name by deleting

    $HOME/golang/src/

from

    $HOME/work/go/src/hello

This of course deletes nothing, so we try to call

    errcheck $HOME/work/go/src/hello

which fails with the error message above.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce:

    call plug#begin('~/.config/nvim/plugged')
    Plug 'fatih/vim-go', { 'do': 'GoInstallBinaries' }
    call plug#end()

* vim version: Neovim 0.1.6
* vim-go version: Git commit e46dd4d from December 17, 2016
* go version: go1.7.3 darwin/amd64

**Comment by gunnihinn** [comment]
I can get :GoErrCheck to run by modifying `vim-go/autoload/go/package.vim` as follows:

    @@ -59,7 +59,7 @@ function! go#package#ImportPath(arg) abort
        let dirs = go#package#Paths()

        for dir in dirs
    -        if len(dir) && matchstr(escape(path, '\/'), escape(dir, '\/')) == 0
    +        if len(dir) && match(path, dir) == 0
                  let workspace = dir
              endif
        endfor

One problem seems to be that `matchstr` returns a string and not an integer; `match` returns the position in the first argument where the second one first matched. Based on the `== 0` check, this is probably what was intended.

Another problem is that Neovim won't match any of the paths once they've been escaped. I'm not able to reproduce this by `:echo match(...)` and don't know what's happening there.

**Comment by fatih** [comment]
Sorry for the very late response. This is fixed now and pushed to master. I'm using now by default `go list` which does all the heavy work and is much more reliable. Thanks for the feedback.
