### ISSUE TITLE
Add an option to kill goimports after a timeout

### ISSUE THREAD

**Issue by opennota** [fatih/vim-go#1169]
### Behavior

Sometimes it takes goimports a looooooooooong time to finish.

### Steps to reproduce:

For example, open the following file and call `:GoImports`:

```
package main

func main() {
	somepackage.Somefunc()
}
```

That makes goimports recursively search *all your GOPATH* for `somepackage`. All that time vim is unresponsive.

It would be nice to have an option to have goimports killed after a specified amount of time. Currently I have to switch to the console to do this.

Something like

`let g:go_imports_timeout = 2 " kill goimports if it has not finished in 2 seconds`

**Comment by fatih** [comment]
Hi @opennota 

Unfortunately this is not feasible. This is how `goimports` work. What you can do is use `gofmt` by default and use `:GoImports` explicitly whenever you need it. Thanks

**Comment by opennota** [comment]
@fatih Not even `killall goimports`?
