### ISSUE TITLE
GoErrCheck not working within softlinked directory

### ISSUE THREAD

**Issue by PragmaticCypher** [fatih/vim-go#1171]
### Behavior

GoErrCheck does not work when working from within a softlinked directory linked to a path outside of the GOPATH, however the errcheck command itself does.

### Steps to reproduce:

Create a temperary project directory:

    mkdir -p ~/temp
    vim ~/temp/main.go
    ... 

Now from within the $GOPATH:

    ln -s ~/temp
    cd temp && vim main.go

Running ;GoErrCheck will report "import /home/some/path cannot import absolute path"

### Configuration

* `vimrc` <- clean vimrc w/ pathogen + vim-go only
* vim version: vim 7.4 + nvim 0.1.7
* vim-go version: ba08326b294b77e39d4842bc94b0679c1912885f
* go version: 1.7.4

**Comment by fatih** [comment]
Hi @PragmaticCypher 

The error comes from `errcheck` tool, so you should check it out. What does it give if you don't use vim-go and call errcheck from the terminal? It'll probably give the same error. Thanks.

**Comment by PragmaticCypher** [comment]
from within the GOPATH directory 'errcheck' still works

bash-4.3$ pwd && errcheck
/home/.../code/go/src/github.com/optiopay/temp
main.go:11:11   someerror()
