### ISSUE TITLE
Should GoReferrers use the QuickFix instead of the LocationList?

### ISSUE THREAD

**Issue by thalesmello** [fatih/vim-go#1178]
### Behavior

I run the command GoReferrers, expecting it to open the QuickFixList. Instead, it opens the LocationList.

Since the referrers regard multiple files, and the location list is specific to the buffer, shouldn't the QuickFix list be used instead?

### Steps to reproduce:

Run GoReferrers over any keyword, and wait for the location list to open.

To confirm it's the LocationList by using `:lclose`

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce:

```
call plug#begin()
Plug 'fatih/vim-go'
call plug#end()
```

* vim version: NVIM 0.1.7
* vim-go version: `commit 3eb57ac`
* go version: 1.7.1

**Comment by bhcleek** [comment]
It uses the location list by default, because the source of the information is the current buffer. Contrast this to `:GoBuild`, which uses several files as the source of information (all the files in the package are built).

The output of any command that is delegated to guru is written to the location list window, because the input is the current buffer.

**Comment by thalesmello** [comment]
My issue with that is the lnext and lprevious commands. When the next
occurrence of the list is in another file, I get an error and the location
list is overwritten. I guesses it had something to do with it using the
location list.

**Comment by bhcleek** [comment]
I am unable to duplicate what you're describing. May I suggest that you close this issue now that the question you posed here is answered, and open a new issue describing the actual problem you're seeing?

**Comment by thalesmello** [comment]
Nevermind. My issue is actually with Neomake, witch overrides the location list whenever I open a new file. I just realized this. Thank you for your patience.

**Comment by fatih** [comment]
Closing this as this seems to be resolved. Feel free to open again if there is a problem. Thanks @bhcleek for support.
