### ISSUE TITLE
How to change the way GoSameIds is highlighted

### ISSUE THREAD

**Issue by vimalk78** [fatih/vim-go#1180]
in my setup, the same ids are highlighted by making it bold, which is not so visible in my terminal (using Terminal on Ubuntu)

is it possible to change the highlighting by changing the color and/or changing the background color ?

thanks,

[vimrc.txt](https://github.com/fatih/vim-go/files/708304/vimrc.txt)

**Comment by bhcleek** [comment]
You can modify the `goSameId` highlight group. By default it's linked to the `Search` highlight group: https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L375

You may find http://vimdoc.sourceforge.net/htmldoc/syntax.html#:highlight-link useful.

**Comment by vimalk78** [comment]
perhaps i should do 
`highlight link Search {to-group}`
what should be the to-group ?

**Comment by fatih** [comment]
Hi @vimalk78  See @bhcleek's answer. You can change it if you want. Thanks!
