### ISSUE TITLE
Snippet duplication?

### ISSUE THREAD

**Issue by codeinabox** [fatih/vim-go#1187]
Quick question, I've noticed there is a duplication of snippets ie a snippet for `if` in both Snipmate and Ultisnips format. Is this deliberate or accidental? I know with vim-snippets if a Snipmate version exists they only have a Ultisnips version if it adds extra functionality.

**Comment by fatih** [comment]
Hi @codeinabox 

That's normal, because they both share a different syntax and uses different plugins. If the duplicate is in the same file, then one should be removed. Let me know if that is the case or feel free to open a PR :) Thanks
