### ISSUE TITLE
secretly run go install on build/test run?

### ISSUE THREAD

**Issue by kevinburke** [fatih/vim-go#1190]
I frequently rebuild my Go version against the latest tip. A lot of times this means every package needs to get recompiled when I run :GoBuild/:GoTest and they're subsequently slow.

It would be really cool if there was a command to run :GoInstall in the background or something so that subsequent build/test commands after the first one are really fast. Not entirely sure of the API but it would be nice to cache the other package builds so we don't have to redo them constantly.

**Comment by fatih** [comment]
We don't have auto go-build on save. I think you can easily enable auto build by using an `autocmd`. Did you try it for the `:GoInstall` command ? (`go install` caches build targets so it should be fast).

**Comment by fatih** [comment]
Closing this as there is not much to do. We recently already added caching to the `go build` command so it should be fast. Also auto build on run could be done easily by adding a `autocmd` to your vimrc if you wish. Thanks for the feedback.
