### ISSUE TITLE
No flag to disable the template?

### ISSUE THREAD

**Issue by LEGOlord208** [fatih/vim-go#1191]
### Behavior
I have both vim-template to use some custom Go template, and vim-go.
When opening I get some strange mix of the two.

Example:
`vim test.go` (new file)
```Go
package main                                                                    

import "fmt"

func main() {
    fmt.Println("vim-go")
}
package main;

import (
    "fmt"
)

func main(){
    fmt.Println("Hello World");
```

### Steps to reproduce:

1. Get vim-template
2. Open a .go file.
3. That *should* be it, to already see some strange results.

If that doesn't work, try edit the =template=.go file under ~/.vim/plugged/vim-template/templates or similar.

### Configuration

Latest vim-go as of now. Not sure which version though.
go version go1.7.4 linux/amd64

**Comment by skhal** [comment]
Put following line in your `vimrc`:

    let g:go_template_autocreate = 0

**Comment by LEGOlord208** [comment]
Aha! Thanks, will do =)
