### ISSUE TITLE
show coverage for a particular test?

### ISSUE THREAD

**Issue by tmc** [fatih/vim-go#1196]
It would be cool if coverage had a :GoTestFunc / or go test -run equivalent so you could see coverage that a subset of tests contributes.

**Comment by fatih** [comment]
Hi @tmc. The coverage feature works for all functions as there is not a 1-1 mapping from a test to a coverage. You might have multiple tests that affect the same function. I assume we can evaluate for all tests and only display the result for a given function, however the coverage file doesn't have that feature (it only contains the file name with the offsets). Thanks for the idea

**Comment by tmc** [comment]
@fatih I opened a PR that enables this
