### ISSUE TITLE
GoImports Error

### ISSUE THREAD

**Issue by dineshkumar-cse** [fatih/vim-go#1200]
### GoImports failed to run 

When i run GoImports it errors out

```
Vim-go: couldn't find 'goimports'. Run GoInstallBinaries to fix it.
Error detected while processing function go#fmt#Format[40]..go#fmt#run:
List required
```
- I've installed vim-go with vundle, and i don't have any custom bindings related to vim-go.
- `GoBuild`, `GoFmt` is passing though.
- I've also done `GoInstallBinaries` and i've `goimports` available from terminal.

**Comment by fatih** [comment]
Hi @dineshkumar-cse 

Unfortunately this is not a vim-go problem, it's a `PATH` problem. Vim can't find it from your `PATH`, if you do a `which goimports` from Vim and your terminal you'll probably see they are different. Closing this, let me know if that is not the case.
