### ISSUE TITLE
Cannot override mapping overriden by vim-go

### ISSUE THREAD

**Issue by iliasr** [fatih/vim-go#1202]
### Behavior

I am using the `Ctrl-t` shortcut a lot for opening a new tab (`:tabnew `), and with vim-go installed (and its binary dependencies) this shortcut is overriden with `:GoDefPop`. The problem is that I cannot re-override it with my wanted mapping in my `after` plugin. If I call `unmap` in the `after` plugin, then it complains with `E31: No such mapping`, even though I can see it in the `:map` list.

### Steps to reproduce:

This is what I have tried adding in my `after` plugin:

```
" These fail with 'E31: No such mapping'
unmap <C-t>
unmap <C-T>

" Tried these with C-t and C-T as well
nnoremap <C-t> :tabnew 
inoremap <C-t> :tabnew
```

### Configuration

I am using vim 7.4 on OSX, and my vim-go is on commit `1425dec`.

Any help would be appreciated! Thanks!

**Comment by fatih** [comment]
Hi @iliasr 

You should be able to disable it by adding `let g:go_def_mapping_enabled = 0` to your virmc. 

Thanks

**Comment by guoxingx** [comment]
> Hi @fatih
> I am trying to disable `gogetdoc` shortcut `K` but noting works neither adding `let g:go_def_mapping_enabled = 0`, what I missed?
> Thanks

`let g:go_doc_keywordprg_enabled = 0` did the job.

**Comment by jimbo5644535** [comment]
@guoxingx thanks for sharing the solution, saved me time <3

**Comment by dreamerlzl** [comment]
As the author said, you can let `let g:go_def_mapping_enabled = 0` and `autocmd FileType go nmap gd <Plug>(go-def)`, so that you reserve gd behavior while overriding Ctrl t
