### ISSUE TITLE
Vim :GoInstallBinaries via Docker Build

### ISSUE THREAD

**Issue by Integralist** [fatih/vim-go#1203]
Just wondering if there was a way to do something like `RUN vim -E :GoInstallBinaries` from inside of a Dockerfile? I've tried but can't seem to get it to install the runtime dependencies when building the image.

Thanks for any guidance you can give me

**Comment by fatih** [comment]
Hi @Integralist 

The following work from terminal:

```
vim -c "GoInstallBinaries"
```

or 

```
vim -c "GoUpdateBinaries"
```

Thanks

**Comment by Integralist** [comment]
Thanks @fatih for the feedback. That does work ...in theory 😄 

And by that I mean, if you look at the following image you'll see [Docker builds starts to execute the command](https://github.com/Integralist/carbon/blob/master/Makefile#L12) but then gets stuck when asking for user feedback to continue...

![screen shot 2017-02-20 at 8 30 56 am](https://cloud.githubusercontent.com/assets/180050/23117332/1da9dbf4-f747-11e6-9fed-ee4a0c762d79.png)

You wouldn't happen to have any ideas how to side step that issue? 

Thanks again for your help, it's much appreciated.

**Comment by Integralist** [comment]
Although not ideal, this does work...

```Dockerfile
RUN vim -c "execute 'silent GoUpdateBinaries' | execute 'quit'"
```

See https://github.com/integralist/carbon for a Dockerfile example and Makefile example
