### ISSUE TITLE
add a GoBuildPlugin feature

### ISSUE THREAD

**Issue by vimalk78** [fatih/vim-go#1206]
since go1.8 supports plugins, vim-go can support a `:GoBuildPlugin` feature which will invoke `go build --buildmode=plugin`

**Comment by fatih** [comment]
Hi @vimalk78 

Did you tried `:GoBuild --buildmode=plugin` ?

**Comment by fatih** [comment]
Closing this as I didn't get an response. Feel free to reopen with a reproducible case. Thanks
