### ISSUE TITLE
Unnecessary "vim-go: SUCCESS" status message after :GoDef

### ISSUE THREAD

**Issue by dmac** [fatih/vim-go#1207]
### Behavior

As of dc8073386754bf5ca09a8dbe2bd9cc8886c61446, calling `:GoDef` prints `vim-go: SUCCESS` in the status line after the definition is found. This isn't useful, and replaces the old useful behavior of printing the name of the file that was opened (when the definition is in another file).

### Steps to reproduce:

Call `:GoDef` or `gd` on any symbol, especially one defined in another file.

### Configuration

* vim-go version: dc8073386754bf5ca09a8dbe2bd9cc8886c61446..master
* vim version:

        VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 16 2017 04:51:36)
        MacOS X (unix) version

**Comment by dmac** [comment]
After looking into this a bit more, I think the new "SUCCESS" message on :GoDef is due to using asynchronous jobs for code searching in Vim 8. Using an async job for what is effectively a code jump seems a little strange to me, since if the search takes a long time the user might think it hasn't worked, move around in their current file, and then suddenly be sent to the code location when the search finishes.

Would reverting to a synchronous behavior for :GoDef in Vim 8 be acceptable? If not, maybe an option could be introduced to control whether sync or async is used for :GoDef.

**Comment by fatih** [comment]
Hi @dmac 

We have already fix it for `cmd` for example. :GoBuild and co doesn't have this issue because there is a flag called `go_echo_command_info`. Add this and you're good to go:

```
let g:go_echo_command_info = 0
```

**Comment by dmac** [comment]
Hi @fatih, thanks for your response.

Sorry, I should have addressed `g:go_echo_command_info` in my previous message. Setting that flag is not ideal is because I *do* want the SUCCESS message in some circumstances. To give a specific difference:

1. If I use :GoInstall, the only indication that the install finished is the SUCCESS message. I want to see it in this case.

2. If I use :GoDef, I already know the command worked when I'm jumped to the definition in code. In this case, the SUCCESS message is redundant, and it hides the name of the newly opened file.

**Comment by fatih** [comment]
Valid point. I'll try to add a flag so you can customize it. Thanks for the feedback.

**Comment by fatih** [comment]
If anyone wants to tackle it. The `go_echo_command_info` command should be parametrized (such as changing it to a list of commands) and the name should be changed, such as `go_echo_commands_disabled` (it's a breaking change). So the setting would be like

```
let g:go_echo_commands_disabled = ['godef']
```

This would disable echoing for `godef`.  We should update the docs, fix current usages of `go_echo_command_info` and also update the docs.
