### ISSUE TITLE
GoFMT/GoImports should have a timeout on it

### ISSUE THREAD

**Issue by tarrant** [fatih/vim-go#1209]
### Behavior

I have somehow gotten my gopath into a state where goimports misbehaves and panics. This is causing attempts to save via vim-go to hang.

The main issue here is unrelated to vim-go, but in order to prevent this from locking up vim, vim-go should add some sort of a timeout around calls to gofmt. If gofmt doesn't return in sufficient time this should be considered an error and the operation aborted.

### Steps to reproduce:

1. Create a simple go program that will always `panic`.
2. Set that program as your gofmt command.
3. Attempt to save a file.

**Comment by fatih** [comment]
Hi @tarrant 

This comes a lot, but I think there is not much I can do. I don't want to complicate stuff. Goimports should be called once, and only once if you write new code. After that it should be called that much.  One of the thing that I've implemented is the explicit command `:GoImports`. So you can call `gofmt` on save, but call `goimports` with the exclusive `:GoImports` command. 

The reason I don't want to add timing out, is that it complicates the codebase for no reason. The user should be aware of the tool. If `goimports` provide a `-timeout` flag though, I'm willing to add it, as it would cost just couple of lines. `gometalinter` has something like that and therefore we have it in vim-go.

Also the tool itself shouldn't panic. So, again I think it's the tools responsibility to fix itself, not us. 

Thanks
