### ISSUE TITLE
:GoInstall with options unclear success status

### ISSUE THREAD

**Issue by the42** [fatih/vim-go#1210]
When I run :GoInstall (:GoBuild the like) with parameters as seen with :help :GoInstall, I get a red status message with the directory instead of the command being dispatched. I think :GoInstall is not executed.

I would like to force a rebuild with

:GoInstall -a

or eb. build with the debug flags

* vim version: 8.0.299
* vim-go version:v1.11
* go version:1.7.3

**Comment by fatih** [comment]
Fixed now, thanks for the feedback.
