### ISSUE TITLE
Template for test files (enhancement)

### ISSUE THREAD

**Issue by thomasheller** [fatih/vim-go#1216]
When we open a new `.go` file, vim-go inserts the `hello_world.go` template.

When opening a new `_test.go` file, I would expect vim-go to insert a slightly more appropriate template, like:

```go
package main

import "testing"

func TestHelloWorld(t *testing.T) {
}
```

**Comment by fatih** [comment]
Hi @thomasheller 

I've encountered that as well lately. Adding a flag so we can tackle it later. Thanks

**Comment by bhcleek** [comment]
I should be able to get to this in the next 2 weeks.

**Comment by fatih** [comment]
@bhcleek any chance you had a look for this?

**Comment by bhcleek** [comment]
Not yet. I'll plan to get to it this week, though.

sent from my phone

**Comment by fatih** [comment]
This is now in master thanks to @bhcleek recent PR. Please pull it and try it out.
