### ISSUE TITLE
Allow disabling gotags

### ISSUE THREAD

**Issue by ashwin** [fatih/vim-go#1217]
When I open a Go file, I get the error `Could not find gotags` and asks me to run `:GoInstallBinaries` to fix it.

Could you provide a flag to disable looking for gotags? I do not need it and do not want to be reminded about this every time I open a Go file.

**Comment by fatih** [comment]
Hi @ashwin 

I don't get the error. What exactly do you use? Seems like a different kind of plugin is causing this. We don't call `gotags` by default, I think one of your plugins is causing it.
