### ISSUE TITLE
If not imported package, YouCompleteMe Will not be prompted

### ISSUE THREAD

**Issue by unix2dos** [fatih/vim-go#1218]
How to solve this problem?

**Comment by edganiukov** [comment]
This is normal behavior of [gocode](https://github.com/nsf/gocode).

**Comment by unix2dos** [comment]
it can a few days ago

**Comment by unix2dos** [comment]
@edganiukov It can a few days ago

**Comment by unix2dos** [comment]
gocode set unimported-packages true
