### ISSUE TITLE
Add code generation of interface implementations

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#122]
This is an idea. Executing a vim-go command like:

```vim
:GoImplement io.Writer
```

generates a snippet like:

```go
type T struct{}

func (t T) Write(p []byte) (n int, err error) {
	return 0, nil
}
```

The zero value of return variables are optional.

**Comment by fatih** [comment]
There is already vim-go-impl. So no need to implement it.

**Comment by asb** [comment]
There could still be a benefit in integrating the functionality in vim-go though right? One of the nice things about vim-go is it packs in pretty much all the functionality you might want for writing Go in Vim.

**Comment by fatih** [comment]
You are right, but after I see the impl tool, I've opened this. Right after 4 hours vim-go-impl was created. What I could do is merge it into vim-go (with the permission of the author of course). Otherwise I need to write it from the scratch, which seems to be a duplicate effort.

**Comment by shazow** [comment]
Would love to see this merged into vim-go (so I can continue to tell people "hey just use vim-go and you get EVERYTHING!") but I respect that it should totally be up to @rhysd. :)

**Comment by fatih** [comment]
@rhysd are you ok with merging vim-impl into vim-go? It'll be a part of vim-go (docs, binary installation, etc..) and I think it would reach a larger audience. 

@shazow I totally agree, there are a couple of projects like that. Also the licenses are all in a good shape to allow us to include them with no worries.

**Comment by rhysd** [comment]
@fatih 

Sorry for the delay to catch this issue.

> @rhysd are you ok with merging vim-impl into vim-go?

Of course OK.  Using vim-go is a very standard way to write golang code in Vim.  Integrating impl to it leads writing golang code better.

**Comment by fatih** [comment]
Thanks @rhysd. I'm going to add it in the following days. It'll be a very useful addition.

**Comment by rhysd** [comment]
@fatih 

Thanks!  If you have any question about it, please ask me.

**Comment by fatih** [comment]
Also other tools from: https://github.com/fatih/vim-go/issues/666

To create interfaces based on a given type: https://github.com/rjeczalik/interfaces
To suggest interfaces based on a given type: https://github.com/mvdan/interfacer

**Comment by fatih** [comment]
This is now merged to master .Thanks again for @rhysd for his initial work 👍
