### ISSUE TITLE
Feature Request: Configurable "go" binary name

### ISSUE THREAD

**Issue by alercah** [fatih/vim-go#1222]
Currently, vim-go does not allow you to configure the binary name for "go". This is frustrating when working with the Google App Engine SDK, since it replaces "go" with a binary "goapp" which has some additional commands and sets a different environment. Without using a workaround, it is extremely difficult to use vim-go effectively in this environment because vanilla "go" cannot find the appengine packages.

**Comment by fatih** [comment]
Hi @alercah 

This seems like a weird issue indeed. I'm not using appengine or anything similiar. How exactly do you use vim-go with App Engine? Can you please show me the documentation for this app and how it replaces `go` ? I can't believe they override the actual binary.

**Comment by alercah** [comment]
The [SDK](https://cloud.google.com/appengine/docs/standard/go/download) adds a script `goapp` which is a wrapper around the `go` binary with additional plugins and, importantly, a different `GOROOT`. I would like to be able to configure it to use `goapp` instead of `go`.

Just symlinking `go` to `goapp` doesn't work, because `goapp` relies on finding `go` in the `PATH`.

**Comment by fatih** [comment]
Thanks for the info. This requires a lot of work and refactoring across all the files in vim-go as we just rely on a binary called `go` which based on the first occurrence in `PATH`. I'll close this issue if I find an elegant solution in the following weeks (hope note months).

**Comment by Carpetsmoker** [comment]
You could work around with by wrapping the `goapp` wrapper with a wrapper called `go` (need more wrappers!) None of this is tested, but the concept should work.

In `~/gohack/go`:

```
#!/bin/sh
# Remove gohack from path and run goapp.

PATH=${PATH#$HOME/gohack}
goapp $@
```

Now start Vim with `$HOME/gohack` as the first `PATH` entry, so it should use the "gohack go":

    PATH=~/gohack/:$PATH vim

If you can confirm that this works we could maybe add an FAQ entry for it?
