### ISSUE TITLE
Quickfix window below tabgbar when tagbar is open

### ISSUE THREAD

**Issue by the42** [fatih/vim-go#1229]
### Behavior

When I have :TabBar open and run a :GoBuild, the quickfix is under the Tagbar window (which is small) instead of being under the code window.

### Configuration

* vim version: 8.0.398
* vim-go version: 1.11
* go version: 1.8

**Comment by fatih** [comment]
Hi @the42 

Quickfix windows are global and it's a vim feature. What you can do to add something like the following to your vimrc:

```
" push quickfix window always to the bottom
autocmd FileType qf wincmd J
```

Thanks.
