### ISSUE TITLE
vim-go produces rendering artifacts in terminal vim

### ISSUE THREAD

**Issue by seletskiy** [fatih/vim-go#123]
Looks like that very handy option `g:go_auto_type_info` is evolved, because of when it's disabled then issue is not longer reproducing.

When I'm just moving around in my file in normal mode, keys I'm typing for movement sometimes leaves in cursor position like some kind of render overlay. When I hit `:redraw!`, they disappear.

Look at this little poopy cursor :cat::

![output](https://cloud.githubusercontent.com/assets/674812/3673248/ce46cf72-126a-11e4-898b-a6ea9f7a67aa.gif)

Using latest version of vim-go and vim.

**Comment by oryband** [comment]
@seletskiy i have the exact same issue: https://groups.google.com/forum/#!topic/vim_use/UVxDG3lMQ0U/discussion
