### ISSUE TITLE
running vim-go from non ~/.vim/ location

### ISSUE THREAD

**Issue by vimalk78** [fatih/vim-go#1231]
### Behavior

i am using vim-go with 
```
$ ls ~/.vim/bundle/
bufexplorer/  ctrlp.vim/  nerdtree/  syntastic/  tagbar/  vim-bufonly/  YouCompleteMe/

```
since i need to start working on Erlang, so i tried to separate the vim-go from the rest, by moving `vim-go` to a location inside `$GOPATH` . there is no more `vim-go` in `~/.vim/bundle`

```
$ ls /home/vimal/gowork/vim/govim/bundle/
vim-go/

```

and creating a `govimrc` with the following content

```
  1 set nocompatible
  2 set runtimepath+=$GOPATH/vim/govim/
  3 source ~/.vimrc
  4
  5
  6 execute pathogen#infect()
  7 syntax on
  8 filetype plugin indent on
 9
 10 let g:go_list_type = "quickfix"
 11
 12
 13
 14 "------------------------------------------------------------------------------
 15 " Vim-go
 16 "------------------------------------------------------------------------------
 17 source $GOPATH/vim/govim/colors/molokai.vim
 18 let g:go_fmt_fail_silently = 1
 19 let g:go_fmt_command = "goimports" "Explicited the formater plugin (gofmt, goimports, goreturn...)
 20
 21 " highlight what?
 22 let g:go_highlight_types = 1
 23 let g:go_highlight_fields = 1
 24 let g:go_highlight_functions = 1
 25 let g:go_highlight_methods = 1
etc...
```

the vim with go is invoked as
`vim -u $GOPATH/vim/govimrc`

this doesnt work as expected. The syntax highlighting is not good, and the tag jump is also screwed up. It just jumps wherever it finds a similar tag, no go package context is checked. i.e. trying to jump from `gob.NewEncoder` jumps to `encoding/ascii85/NewEncoder`. crazy...

But....
everything is fine if i put back `vim-go` to the `~/.vim/bundle`, and invoking the vim same as above `vim -u $GOPATH/vim/govimrc`

So i am confused, is there a restriction that `vim-go` will work from default .vim/bundle location only?

how do i make the above arrangement work?

### Steps to reproduce:

Please see above.

### Configuration

* `vimrc` you used to reproduce
* vim version:
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 12 2016 20:31:32)
Included patches: 1-2028
Compiled by vimal@BLR1000011929
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +digraphs        +folding         +libcall         +mouse_dec       -netbeans_intg   +quickfix        +tag_binary      +user_commands   +X11
+arabic          +cmdline_hist    +dnd             -footer          +linebreak       -mouse_gpm       +num64           +reltime         +tag_old_static  +vertsplit       -xfontset
+autocmd         +cmdline_info    -ebcdic          +fork()          +lispindent      -mouse_jsbterm   +packages        +rightleft       -tag_any_white   +virtualedit     +xim
+balloon_eval    +comments        +emacs_tags      +gettext         +listcmds        +mouse_netterm   +path_extra      +ruby            -tcl             +visual          +xsmp_interact
+browse          +conceal         +eval            -hangul_input    +localmap        +mouse_sgr       +perl            +scrollbind      +termguicolors   +visualextra     +xterm_clipboard
++builtin_terms  +cryptv          +ex_extra        +iconv           +lua             -mouse_sysmouse  +persistent_undo +signs           +terminfo        +viminfo         -xterm_save
+byte_offset     +cscope          +extra_search    +insert_expand   +menu            +mouse_urxvt     +postscript      +smartindent     +termresponse    +vreplace        +xpm
+channel         +cursorbind      +farsi           +job             +mksession       +mouse_xterm     +printer         +startuptime     +textobjects     +wildignore
+cindent         +cursorshape     +file_in_path    +jumplist        +modify_fname    +multi_byte      +profile         +statusline      +timers          +wildmenu
+clientserver    +dialog_con_gui  +find_in_path    +keymap          +mouse           +multi_lang      +python          -sun_workshop    +title           +windows
+clipboard       +diff            +float           +langmap         +mouseshape      -mzscheme        -python3         +syntax          +toolbar         +writebackup
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr
/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pix
man-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby1.9.1-1.9.3.484/debian/lib -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk
-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11
 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -ldl  -L/usr/include/lua5.1/lib/x86_64-linux-gnu -lluajit-5.1 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl
-ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions   -lruby-1.9.1 -lpthre
ad -lrt -ldl -lcrypt -lm  -L/usr/lib

* vim-go version: master

* go version:  go version go1.8 linux/amd64

**Comment by vimalk78** [comment]
hi,
i observed this behaviour in both Ubuntu Linux and on Max OSX

if this issue is not applicable to vim-go, kindly say so in comments.

thx!!

**Comment by vimalk78** [comment]
i see the following difference in runtimepath

the difference is vim-go present in rtp before or after `~/.vim/after`

**when it doesn't work**
runtimepath=~/.vim,
~/.vim/bundle/YouCompleteMe,
~/.vim/bundle/bufexplorer,
~/.vim/bundle/ctrlp.vim,
~/.vim/bundle/erlang-motions.vim,
~/.vim/bundle/nerdtree,
~/.vim/bundle/syntastic,
~/.vim/bundle/tagbar,
~/.vim/bundle/vim-bufonly,
/usr/local/share/vim/vimfiles,
/usr/local/share/vim/vim74,
/usr/local/share/vim/vimfiles/after,
~/.vim/bundle/erlang-motions.vim/after,
~/.vim/after,
~/gowork/vim/govim/,
~/gowork/vim/govim//bundle/vim-go

**when it works**
runtimepath=~/.vim,
~/.vim/bundle/YouCompleteMe,
~/.vim/bundle/bufexplorer,
~/.vim/bundle/ctrlp.vim,
~/.vim/bundle/erlang-motions.vim,
~/.vim/bundle/nerdtree,
~/.vim/bundle/syntastic,
~/.vim/bundle/tagbar,
~/.vim/bundle/vim-bufonly,
~/.vim/bundle/vim-go,
/usr/local/share/vim/vimfiles,
/usr/local/share/vim/vim74,
/usr/local/share/vim/vimfiles/after,
~/.vim/bundle/erlang-motions.vim/after,
~/.vim/after,
~/gowork/vim/govim/,
~/gowork/vim/govim//bundle/vim-go

**Comment by vimalk78** [comment]
it all works if i change runtimepath as follows
`set runtimepath^=$GOPATH/vim/govim/`

**Comment by vimalk78** [comment]
but i had a better idea, instead of invoking vim with a different vimrc with -u option, why not add the plugin depending on the filetype.

so i created a file `~/.vim/ftplugin/go.vim` and sourced the vim-go specific file from it. but i find something strange.

the runtimepath is same as i expect, but the syntax highlight and `Ctrl-[` is screwed, but it starts working immediately after i make one `Ctrl-[` invocation.

after 1 `Ctrl-[` invocation everything works fine, perhaps some initialization method is being invoked in vim-go which sets everything right.

how to resolve this issue, i.e. make that initialization occur as soon as a go file is detected.

**Comment by fatih** [comment]
@vimalk78 I don't support non custom or non vim related paths. It works with any other package maintainer. Please use that way if you can, doing it the other way is just asking for problems :) Thanks

**Comment by vimalk78** [comment]
thanks for your support.

i just wanted to be able to use same VIM for different languages. so wanted to separate plugin set and configs, and load it based on the filetype.

finally i put all plugins back in `~/.vim` and created a `ftplugin/go.vim` to load the `vim-go` specific settings.
the rtp is including the `vim-go`

but i find the same behaviour. need to invoke `Ctrl-[` once to properly load `vim-go` something is missing till in invoke `Ctrl-[`

perhaps i need to look in the `vim-go` plugin code.
