### ISSUE TITLE
How to disable the function godoc?(or what else) window

### ISSUE THREAD

**Issue by VanishingDante** [fatih/vim-go#1236]
<img width="676" alt="screen shot 2017-03-15 at 10 43 12 pm" src="https://cloud.githubusercontent.com/assets/15049134/23953882/cffc8374-09d0-11e7-9136-851d1de32dc1.png">
how to disable the window at the top or force it show at the bottom?

**Comment by edganiukov** [comment]
try
set completeopt-=preview

**Comment by fatih** [comment]
Hi @VanishingDante. See @edganiukov response. It's not a vim-go problem. Thanks
