### ISSUE TITLE
Better template for *_test.go files

### ISSUE THREAD

**Issue by mcandre** [fatih/vim-go#1239]
vim-go has a nifty template when creating `*.go` files. Unfortunately, this is a little overreaching.

When users create a new `*_test.go` file, please use a more appropriate template, like

```go
package name_test

import "testing"

func TestMethod(t *testing.T) {
	t.Error("Unimplemented")
}
```

**Comment by thomasheller** [comment]
Duplicate of #1216.

**Comment by fatih** [comment]
See #1216, thanks
