### ISSUE TITLE
Errcheck Flags

### ISSUE THREAD

**Issue by rossmcf** [fatih/vim-go#1244]
### Behavior

I'd like to have `errcheck` check for assignment of errors to the blank identifier using the `-blank` flag. I can do this manually by running `:GoErrCheck -blank`. Is there a way to add this flag when it's run by `:GoMetaLinter` and/or by syntastic on save?

### Configuration
Here's what I think are the relevant bits from my .vimrc:

    let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']
    let g:syntastic_go_checkers = ["go", "gofmt", "golint", "gotype", "govet", "errcheck"]

I've tried using `errcheck -blank` in both of those places, but to no avail.

**Comment by fatih** [comment]
Hi @rossmcf 

We don't support changing the linter or passing any flag. There is an option in the readme of `gometalinter` that says it's possible:

https://github.com/alecthomas/gometalinter/blob/master/README.md#details

Did you tried it on your terminal and see how it works. If yes what is the exact gometalinter command you used? Thanks

**Comment by fatih** [comment]
Closing this as I didn't get an response. Feel free to reopen with a reproducible case. Thanks
