### ISSUE TITLE
Incorrect indenting

### ISSUE THREAD

**Issue by LEGOlord208** [fatih/vim-go#1251]
Doing something like
```Go
if strings.HasPrefix(something, "https:/") {
    fmt.Println("Test");
}
```
works fine. But adding the last slash makes the rest of the code not work.  
I've tried a few different tests, and it seems to be the `//` causing it. No idea why.

**Comment by LEGOlord208** [comment]
(Keep in mind, the indent I'm talking about here is pressing `=` + movement.)

**Comment by fatih** [comment]
Hi @LEGOlord208 

I'm not sure I've understood  your question. We use gofmt and if you hit save, it'll be indented correctly. What exactly do you want to see?

**Comment by LEGOlord208** [comment]
@fatih Yeah, sorry. I disabled gofmt. Basically, when I use vim's indenting (`=` + movement, for example `gg=G`) is when it fails.

**Comment by fatih** [comment]
Please use gofmt (or goimports). This is how the code is formatted. I don't think we have the feature correctly set up for the `=` operator (it'll use c-indenting by default). Closing as we don't have this feature and don't think to implement as we already have a superior one. Thanks.
