### ISSUE TITLE
quickfix beneath the wrong split

### ISSUE THREAD

**Issue by jeromer** [fatih/vim-go#1254]
### Behavior

The quickfix error list is displayed beneath the wrong split.

### Steps to reproduce:

1. open foo.go
2. `:vs bar.go`
3. Generate a syntax error in `foo.go` and save
4. You will see the quicklist beneath `bar.go`

### Configuration

Add here your current configuration and additional information that might be useful, such as:

* `vimrc` you used to reproduce

```
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'fatih/vim-go'

let g:go_fmt_command = "goimports"
let g:go_autodetect_gopath = 1
let g:go_list_type = "quickfix"
let g:go_def_mapping_enabled = 0

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_generate_tags = 1
let g:go_fmt_experimental = 1
```

* vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 21 2015 13:03:49)
Included patches: 1-712
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
```
* vim-go version:

362e15ab492853ff9582ea5856878e1a5b64ed18

* go version:
`go version go1.8 linux/amd64`

**Comment by fatih** [comment]
Hi @jeromer 

Unfortunately  there is no notion of quickfix belonging to a window. For that see the docs to use "localionlist. If you want to put the quickfix always to the bottom use the following:

```
" put quickfix window always to the bottom
autocmd FileType qf wincmd J
```
