### ISSUE TITLE
feature request, set the position of go_term_mode

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [fatih/vim-go#1256]
### Behavior
hi, i'm using neovim, and the GoRun is great. I set go_term_mode='split' but the term position is on the top. how can i put it on the bottom?

**Comment by fatih** [comment]
what's the filetype of that window? I think you can use something like:

```
" put term always to the bottom
autocmd FileType term wincmd J
```
change `term` with the filetype of the window please. Thanks

**Comment by FinallyFinancialFreedom** [comment]
Well,`autocmd FileType go term wincmd J` is not work for me. The GoRun result is output at top.
BTW, vim-go works fine with deoplete when you set
```vim
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.go = '[^. *\t]\.\w*'
```
no need to use deoplete-go.
