### ISSUE TITLE
cannot jump a tag if import "C"

### ISSUE THREAD

**Issue by vimalk78** [fatih/vim-go#1259]
### Behavior

when i do 'Ctl-]" on a api call, i get error

vim-go: guru: package "so-and-so/gw" doesn't contain file so-and-so/gw/file.go^@

### Steps to reproduce:

package gw

```

/*
#include <dlfcn.h>
#include <limits.h>
#include <stdlib.h>
#include <stdint.h>

#include <stdio.h>
*/

import "C"

```

if the `import "C"` is removed, i dont get the error

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 12 2016 20:31:32)
Included patches: 1-2028

* vim-go version: master
* go version: 1.8.1

**Comment by fatih** [comment]
This is a known issue https://github.com/golang/go/issues/15710. Thanks!
