### ISSUE TITLE
Panics in :GoRun aren't shown correctly in Neovim

### ISSUE THREAD

**Issue by zgqq** [fatih/vim-go#1260]
### Behavior
I runned simple program with runtime error. The error output window was closed automatically and only show the location raising error on quickfix window. The is very very 
suck,because you don't know what error happen at all.
### Steps to reproduce:

```
func main() {
	list := make([]string, 2, 2)
	log.Println("ok")
	println("ok" + list[3])
}

```
I haved it several times,that is casued by log.Println("ok).
### Configuration
* `vimrc` you used to reproduce

```
Plug 'fatih/vim-go',{'do': ':GoInstallBinaries'}
if has("nvim")
    let g:go_term_enabled = 1
    let g:go_term_mode = "vsplit"
    let g:go_term_height = 30
    let g:go_term_width = 30
endif

" let g:go_fmt_fail_silently = 1
au FileType go nmap <leader>rt <Plug>(go-run-tab)
au FileType go nmap <Leader>rs <Plug>(go-run-split)
au FileType go nmap <Leader>rv <Plug>(go-run-vertical)
```

* vim version: 
NVIM 0.1.7
Build type: Release
* vim-go version: 1.12
* go version: 1.8-3

**Comment by fatih** [comment]
I don't use neovim, but the program above just panics. I think that might be the issue. I didn't understand what you mean it was caused by `log.Println`. Why should that be the case?

**Comment by Carpetsmoker** [comment]
Running the above program I get:
![2017-09-21-063214_666x323_scrot](https://user-images.githubusercontent.com/1032692/30680277-9ed45aaa-9e96-11e7-9e38-7e83f23da49d.png)

In Neovim I get one line in the location list:
![2017-09-21-063101_666x323_scrot](https://user-images.githubusercontent.com/1032692/30680255-7d798c9a-9e96-11e7-9c27-be2ba60d5564.png)

With Vim I get an error, and nothing in the location list:
![2017-09-21-063110_666x323_scrot](https://user-images.githubusercontent.com/1032692/30680254-7d784d6c-9e96-11e7-8ee8-1598a6d2e83d.png)
