### ISSUE TITLE
:GoVet is passing but file have errors

### ISSUE THREAD

**Issue by cassiobotaro** [fatih/vim-go#1261]
### Behavior

:GoVet is passing but file has errors.

![captura de tela de 2017-04-15 21-49-04](https://cloud.githubusercontent.com/assets/3127847/25067826/a78a0bc4-2225-11e7-8b85-3437af3dfd5a.png)

### Steps to reproduce:

1.Create a file with the follow content:

```go
//+buildlinux

package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}

```
2. :Govet 

### Configuration

* `vimrc` you used to reproduce: [vimrc](https://github.com/cassiobotaro/dotfiles/blob/master/.vimrc)
* vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Correções incluídas: 1-1689
Correções extras:8.0.0056
* vim-go version: 1.12
* go version: 1.8.1

**Comment by fatih** [comment]
Just looked at this, and found that this a `go vet` issue. I've tried to fix it here: https://go-review.googlesource.com/c/44371/ Let's see how it ends up. Thanks for the feedback.

**Comment by fatih** [comment]
This is now merged https://github.com/golang/go/commit/d64c49098c626ea58f2265866dd576e138c15b29 Thanks for the feedback again.

**Comment by cassiobotaro** [comment]
Awesome! Thanks @fatih !
