### ISSUE TITLE
:GoAddTags do not support camelcase

### ISSUE THREAD

**Issue by 812lcl** [fatih/vim-go#1265]
### Behavior

:GoAddTags do not support camelcase, even let g:go_snippet_case_type = "camelcase" in my .vimrc

### Steps to reproduce:

Re produce it with a minimal `vimrc` with all plugins disabled and
only `vim-go` enabled:

type Person struct {
    Name      string `json:"name"`
    Age           int    `json:"age"`
    ApplicationStatus string    `json:"application_status"`
}
1. let g:go_snippet_case_type = "camelcase" in .vimrc
2. cursor in Person struct
3. :GoAddTags
4. ApplicationStatus get a tag `json:"application_status"`,bug I want `json:"applicationStatus"`

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version:n 8.0.543
* vim-go version: 1.12
* go version: 1.8 darwin/amd64

**Comment by fatih** [comment]
Hi @812lcl 

The underlying tool https://github.com/fatih/gomodifytags supports it via the `transform` option however the setting you're using doesn't have any affect. I'm keeping this issue open so we can add it. If anyone feels adventurous, you have to change `autoload/go/tags.vim` to add support for `--transform` flag.

**Comment by 812lcl** [comment]
> you have to change autoload/go/tags.vim to add support for --transform flag

Thanks, this solved my problem and hope to integrate into vim-go later.

**Comment by Arial7** [comment]
I just opened #1275 in which I added a variable to set this option 😉

**Comment by fatih** [comment]
This is now merged and can be changed via `g:go_addtags_transform`
