### ISSUE TITLE
Text search?

### ISSUE THREAD

**Issue by shettyg** [fatih/vim-go#1266]
### Behavior

Reading the documentation and tutorial, it was not clear whether vim-go supports text search.

In a C repository, with ctags and cscope, one keep the cursor on top of a text and press "ctrl-\\" and it will show all the places (including other directories) where the text is used. You can then navigate to that location.

Does vim-go have such a feature? Ideally, it would be nice to look at all the places in GOPATH a string exists. For e.g all the places a function is invoked.

**Comment by fatih** [comment]
We have `:GoDef` and `:GoSameIds` which allows you to jump to any identifier or see the same identifiers. Plus you can also use `:GoReferrers` to see all references as well.  If you think these don't solve your problem feel free to provide more info.
