### ISSUE TITLE
:make doesn't compile current module

### ISSUE THREAD

**Issue by rahenri** [fatih/vim-go#1270]
If I do the following:

cd go/src/app
vim foo/bar.go
:make

Vim attempts to build the app packge, not the app/foo package. That doesn't happen with GoBuild, but it doesn't generate the executable.

**Comment by fatih** [comment]
You have to cd into the folder via `:cd foo`. That's a vim thing. `:GoBuild` tries to be smart that it automatically follows you. You can add the following to your vimrc to change the cd for the current file:

```
" Enter automatically into the files directory
autocmd BufEnter * silent! lcd %:p:h
```

**Comment by rahenri** [comment]
It would be nice if there was a flag to make GoBuild produce the binary.

Using the solution you proposed doesn't play very well with other plugins.
