### ISSUE TITLE
GoTest output cannot be read easily if test output is too wide

### ISSUE THREAD

**Issue by kevinburke** [fatih/vim-go#1271]
### Behavior

run GoTest with the following test:

```go
var normalizeTests = []struct {
	in  string
	out string
}{
	{"foo", "foo"},
	{"http://foo", "foo"},
	{"upspin-server.googlesource.com", "upspin.googlesource.com"},
}

func TestNormalizeServer(t *testing.T) {
	for _, tt := range normalizeTests {
		got := normalizeGerritServer(tt.in)
		if got != tt.out {
			t.Errorf("normalizeGerritServer(%q): got %q, want %q", tt.in, got, tt.out)
		}
	}
}
```

The error message is a little long:

```
$ go test ./maintner
--- FAIL: TestNormalizeServer (0.00s)
	gerrit_test.go:69: normalizeGerritServer("upspin-server.googlesource.com"): got "go.googlesource.com", want "upspin.googlesource.com"
FAIL
FAIL	golang.org/x/build/maintner	0.016s
```

You can't see all of it in vim-go test output:

<img src="https://monosnap.com/file/xubUrevnjsV0fO8V8Xnr0FEcpGPUMT.png">

Maybe this is a problem with my Vim configuration? I need to enable multiline output for quickfix or something... I'm not sure and searching about multiline quickfix wasn't really returning useful results.

I'm using neovim 0.1.7, and Go tip, on a Mac, and invoking `:GoTestFunc` with no other arguments.

**Comment by fatih** [comment]
Hi @kevinburke 

It's a Vim problem which you can easily solve by adding the following to your vimrc:

```
" wrap long lines in quickfix
augroup quickfix
    autocmd!
    autocmd FileType qf setlocal wrap
augroup END
```

Source: https://vi.stackexchange.com/questions/2843/how-to-automatically-set-wrapping-for-quickfix-window/2844

**Comment by kevinburke** [comment]
Thanks!

**Comment by juanpabloaj** [comment]
thanks for your suggestion, I added it to my `init.vim`

```
" wrap long lines in quickfix
augroup quickfix
    autocmd!
    autocmd FileType qf setlocal wrap
augroup END
```

although it doesn't work for me, an example 

```
func TestHello(t *testing.T) {
	s := ""

	for i := 0; i < 40; i++ {
		s += strconv.Itoa(i) + " "
	}

	t.Errorf("cheking the wrap" + s)
}
```

it doesn't wrap the line, 

<img width="633" alt="nvim" src="https://github.com/fatih/vim-go/assets/732415/2cda92fa-a457-4689-8a45-9c15db446537">


it only wraps the line if I have at least two error messages

```
	t.Errorf("cheking the wrap" + s)
	t.Errorf("cheking the wrap" + s)
```

I am using nvim 0.9.1.

thanks in advance for any suggestion.
