### ISSUE TITLE
Question: do you have plan to use Language Server Protocol (LSP)?

### ISSUE THREAD

**Issue by stamm** [fatih/vim-go#1272]
Recently I learned about [Language Server Protocol](http://langserver.org/).
And there is implementation for golang: https://github.com/sourcegraph/go-langserver
Is any thought about using it?
Btw, now it's not support completion, but still.

**Comment by fatih** [comment]
Hi @stamm 

Currently there is no plan to support it. Maybe in the future though. Thanks for asking.

**Comment by sandipb** [comment]
Just FYI. Guru doesn't work with symlinks in GOPATH, but the langserver does. A bunch of people are forced to use symlinks because Go's file layout sometimes doesn't match their organization's code conventions. The fact that Guru doesn't work is a major bummer.
