### ISSUE TITLE
Request: fuzzy completion for GoImport

### ISSUE THREAD

**Issue by momoneko** [fatih/vim-go#1273]
Because most Go packages have really long names, it would be awesome if there was some fuzzy completion feature when using `:GoImport`.

**Comment by fatih** [comment]
Hi @momoneko 

Thanks for the feature request. Unforunately we don't have native fuzzy search inside vim. Plugins like fzf or ctrlp provide them with thei UI's. I also think that `goimports` (the tool) already imports the import path once a small code is written. People less use `:GoImport` nowadays. I don't think this is a feature we should support. I'm closing this as I don't have any time or schedule, however if someone sees this closed issue and wants to implement it feel free to it (unless it's a very complex addition, which I wouldn't want to merge :))

**Comment by momoneko** [comment]
My use case for this was that I have to import a package before I can start an autocomplete on the identifiers inside the package. Can I do that in another way?
