### ISSUE TITLE
[feature]When save file auto run cmd `:GoImports`

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#1281]
We should have a setting, when it is true, GoImports will run before `:w` just like `go fmt`

**Comment by fatih** [comment]
Hi @jinleileiking . You can do it by adding the following to you vimrc:

```
let g:go_fmt_command = "goimports"
```

Thanks

**Comment by jinleileiking** [comment]
Magic!!

**Comment by jinleileiking** [comment]
@fatih ... I want to rune `:GoMetalinter` when `:w` .

The final result:

When I `:w`

* run gofmt
* run goimports
* run gometalinter.

Does this option supports array?

Thanks a lot.

**Comment by cassiobotaro** [comment]
@jinleileiking `let g:go_metalinter_autosave = 1` and set your linters with `let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']`

You can read more [here](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1353-L1396)

**Comment by jinleileiking** [comment]
@cassiobotaro thanks alot
