### ISSUE TITLE
Current working dir is wrong after running :GoRun in NeoVim

### ISSUE THREAD

**Issue by dorons** [fatih/vim-go#1289]
### Behavior

When executing `:GoRun` on an inner/nested *main* package within a project tree, the local current dir of the window from which `:GoRun` was commenced is changed to the path of the `package main` inner file and is no longer the project's root dir.

The issue seems to be that the `go#term#newmode` function changes `lcd` of the source (main.go) window and "restores" the original dir on the target window (terminal) instead.

### Steps to reproduce:

1. `cd $GOPATH/src/scratch/mypkg`
2. Start nvim
3. Open a sub-package main, such as: `:e ./cmd/util/main.go`
4. `:echo getcwd()` => **/Users/doron/go/src/scratch/mypkg**
5. `:GoRun`...  main runs in NeoVim's terminal mode in a new window
6. Go back to the main.go window
4. `:echo getcwd()` => **/Users/doron/go/src/scratch/mypkg/cmd/util** (inner path)

### Configuration

* vim version: NVIM v0.2.0-1523-g5d73a6e
* vim-go version: HEAD 7fb968
* go version: go version go1.8 darwin/amd64

**Comment by fatih** [comment]
Hi @dorons 

Can you try please: https://github.com/fatih/vim-go/pull/1296

I'm not using neovim so not sure if that fixes.

**Comment by fatih** [comment]
Ping @dorons , can you please test it ?

**Comment by fatih** [comment]
This is now in master. Let me know if you have still issues. Thanks.

**Comment by dorons** [comment]
Sorry for catching this late. Verified with master... works as advertized :)
