### ISSUE TITLE
Donot auto jump to the quickfix window when enable go_metalinter_enabled

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#1290]
Donot auto jump to the quickfix window when enable `go_metalinter_enabled`

Or , give me a config

**Comment by jinleileiking** [comment]
![qq20170516-172337](https://cloud.githubusercontent.com/assets/93968/26099146/76f56c84-3a5c-11e7-8eba-c718f34d03ac.jpg)

It seems in these codes.

**Comment by jinleileiking** [comment]
not this...

**Comment by edganiukov** [comment]
`:help vim-go` may help you.

**Comment by jinleileiking** [comment]
@edganiukov I cannot find the setting.

**Comment by jinleileiking** [comment]
![qq20170518-133431](https://cloud.githubusercontent.com/assets/93968/26187948/cf3193be-3bce-11e7-9c01-be20193e00c8.jpg)

Is it the feature I want?

**Comment by jinleileiking** [comment]
I go the solution from ale, I will give a pr.

**Comment by fatih** [comment]
This is now fixed
