### ISSUE TITLE
GoDoc Comment Wrapping and Reformatting

### ISSUE THREAD

**Issue by robmuh** [fatih/vim-go#1291]
This is not a bug.

I spend way too much time rewrapping GoDoc lines "by hand" and have embarked on my own custom way to do this with a filter/macro, which got me thinking.

What if there were a way to automatically wrap any line-commented GoDoc in the file. There are many ways people do this in their own config, but it seems a natural fit here. The wrapping algorithm would need to identify indented blocks and ignore them, but I think that is all. The keywords `func`, `type` and such could be identified as the markers at which to stop the commenting.

You may find no value in this suggestion but found it worth putting out there. I am working on a go package to do the same thing for other reasons related to godoc-like wrapping behavior that I use to change text to fit on a screen.

**Comment by fatih** [comment]
Hi @robmuh 

What exactly and how do you "rewrap"? What does it mean? I need more concrete examples pls. In vim you can easily wrap long lines by selecting a number of lines and then run `gq` in normal mode.

**Comment by robmuh** [comment]
Well `gq` usually needs a `gq/fun` to wrap up to the function, and if that code contains any indented blocks they are also wrapped. I was hoping to find a way to ignore them. Wrap all the other stuff but not those.

**Comment by fatih** [comment]
Thanks @robmuh. I don't think this is a feasible product to implement in long term due the complexity and maintainability. Comment's are written once and never changed. If you create a program just for this you can use vim's `formatprg` setting to override the `gq` command. Thanks for the feedback.

**Comment by robmuh** [comment]
Makes sense. I'll just finish the godoc-centric wrapper I started and will plugin with `formatprg` contextually in our `vimrc`. Thanks for the tip.
