### ISSUE TITLE
Gometalinter lints vendored packages

### ISSUE THREAD

**Issue by angrygoats** [fatih/vim-go#1294]
### Behavior

I use glide to manage my dependencies. I've noticed that on certain dependencies (in particular go-kit), the gometalinter on save command will run and lint additional packages in my vendor directory. 

### Steps to reproduce:

1. Install vim-go and enable gometalinter to fire using the following in your vimrc: `autocmd BufWritePost, FileWritePost *.go execute 'GoMetaLinter' | cwindow`
2. Install [glide](https://github.com/Masterminds/glide) 
3. `glide get github.com/go-kit/kit`
4. Use the below code:

```
import httptransport "github.com/go-kit/kit/transport/http"

func main() {
  handler := httptransport.NewServer()
}
```

This will fail to compile because you need to set up endpoints (and that's an involved process), however this should trigger GoMetaLinter to go lint the `http` part of go-kit.

I'm unsure if any other vendoring of packages causes this - however it's occurring for me with go-kit so I used that here.

### Configuration

* vim version: nvm 0.1.4
* vim-go version: current
* go version: 1.8.1

**Comment by angrygoats** [comment]
This seems to be due to an old go-kit package that I had. However, I'll leave this open because I'd like GoMetaLinter to not lint the vendored packages ideally.

Is this a vim configuration issue, or a vim-go issue? If it's a vim configuration issue I'll gladly close this issue.

Thanks!

**Comment by fatih** [comment]
We have already an automode for `:GoMetaLinter`. You don't have to add your own logic. Please consult our documentation (see readme).  Gometalinter is just a binary and any kind of vendored package shouldn't affect it's usage. Please let me know after you started using the correct setting. Thanks
