### ISSUE TITLE
`GoAddTags` use snake_case when set to camelcase

### ISSUE THREAD

**Issue by imroc** [fatih/vim-go#1298]
### Behavior
I set to camelcase in my vimrc:
`let g:go_snippet_case_type = "camelcase"`
it works when I press tab in the end of `json`,but it not work when I select lines in visual mode and use `:GoAddTags` cammand.

### Configuration

* vim version:8.0.398
* vim-go version: 1.12
* go version:1.8.1

**Comment by fatih** [comment]
H @imroc, you have to use `go_addtags_transform`. The `go_snippet_case_type` is used for snippets not `:GoAddTags`. I'm going to open a PR to unify both settings Thanks for the feedback

**Comment by fatih** [comment]
Here is the PR that unifies both settings: https://github.com/fatih/vim-go/pull/1299

**Comment by imroc** [comment]
thanks
