### ISSUE TITLE
GoBuild opens quickfix window and then closes it again

### ISSUE THREAD

**Issue by makkes** [fatih/vim-go#1302]
### Behavior

This is my `.vimrc/ftplugin/go.vim` file:

    autocmd BufWritePre <buffer> GoImports
    autocmd BufWritePre <buffer> GoBuild

Now, when I open a file that e.g. contains a call to a function that does not exist, I see that `GoBuild` is executed (since the quickfix window opens) but after a blink of an eye the quickfix window closes again.

* vim version: 7.4
* vim-go version: master branch at 403b9bb29bf16b69c4d16bae830f12f9871a89a5
* go version: 1.7

**Comment by fatih** [comment]
Please read the docs. For `goimports` we already have a setting. The reason `:GoBuild` closes is because `goimports` closes it automatically. Your command has a race condition. You need to create a single function and run first goimports and then gobuild so they don't interfere with each other.
