### ISSUE TITLE
GoBuild quickfix not working when setting go_list_type to "quickfix"

### ISSUE THREAD

**Issue by rahenri** [fatih/vim-go#1303]
I wanted GoImports to put the errors in the quickfix list just like GoBuild. I found out that a way to do that is to set go_list_type to "quickfix". That does the trick for GoImports, but once that is in place, GoBuild no longer add anything to the quickfix list. Is there a workaround that?

I'm using vim 8.0.95.

**Comment by fatih** [comment]
Thanks @rahenri for the feedback. Can you please try https://github.com/fatih/vim-go/pull/1304 ?

**Comment by rahenri** [comment]
Thanks for the fix!

**Comment by rahenri** [comment]
Looks like GoBuild quickfix is broken again, but this time without any flags set. I removed everything but vim-go from my vimrc and .vim. But running :GoBuild doesn't populate the quickfix in case of compilation errors (:make still works fine).
