### ISSUE TITLE
GoLint with no arguments does not work.

### ISSUE THREAD

**Issue by alercah** [fatih/vim-go#1305]
### Behavior

Write here what's happening and what you're expecting instead of...

`:GoLint` is saying that there are no linting errors even when `!golint` or `:GoLint <cwd>` report errors.

### Steps to reproduce:

1. Create the following file, named `foo.go`:

```go
package main

func Foo() {}
```
2. Run `:GoLint`, observe that there are no errors.
3. Run `!golint` and `:GoLint <cwd>`, observe the error for no comment on `Foo`.

### Configuration

* vim version: 8.0
* vim-go version: HEAD
* go version: 1.7.4

`vim-go` configuration:

```
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
```

**Comment by fatih** [comment]
I couldn't reproduce this. Here is a Gif:

![2017-05-28 01_38_54](https://cloud.githubusercontent.com/assets/438920/26524754/6e157be8-4346-11e7-8375-208cee7973d8.gif)

It's a very basic command and I think something with your local setup is wrong (such as Vim version)

**Comment by alercah** [comment]
It is working for me now. Strange.
