### ISSUE TITLE
^W ^] Doesn't work

### ISSUE THREAD

**Issue by korjavin** [fatih/vim-go#1307]
### Behavior

^W ^] Is "window version of ^] it should open defenition in the new window

### Steps to reproduce:

1. Open go source
2. Press ^W ^]
3. It shows Error

### Configuration

* vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 12:10:29)

* vim-go version:26362e4
* go version: go1.7.4 linux/amd64

**Comment by fatih** [comment]
I've just tested it and it works fine for me. We have the following mappings already defined:

```
  nnoremap <buffer> <silent> <C-w><C-]> :<C-u>call go#def#Jump("split")<CR>
  nnoremap <buffer> <silent> <C-w>] :<C-u>call go#def#Jump("split")<CR>
```

Please remove any other plugin and only use vim-go. I think one of your other plugins is interfering with it. You can see all mappings with `:map` to debug.

**Comment by korjavin** [comment]
You are right, something with my mappings. I am so sorry for distracting you.
