### ISSUE TITLE
GoDef does not work after setting GoBuildTags

### ISSUE THREAD

**Issue by tgrosinger** [fatih/vim-go#1312]
### Behavior

Setting `:GoBuildTags integration` does not cause ":GoDef" to correctly find a definition that is in a tagged file.

Write here what's happening and what you're expecting instead of...

### Steps to reproduce:

1. Create a file `A.go` in package `testutils` with `// +build integration unit` at the top. Create a function in this file.
2. Create file `B_test.go` in package `myapp` with `// +build integration` at the top. In it, create a function with a call to the function in file A.go
3. Place the cursor over the function call in `B_test.go`, and run `:GoDef`

Expected: Jump to function definition in `A.go`
Actual: red message at the bottom saying "vim-go: <my go path>"

### Configuration

* `vimrc` you used to reproduce: https://github.com/tgrosinger/dotfiles/blob/master/.vimrc
* vim version: 8.0.604
* vim-go version: 00ab89e4d48befa500f28ab34a3602454e3363ae
* go version: go1.8.1 linux/amd64

**Comment by fatih** [comment]
Hi @tgrosinger 

Thanks for the report. It's now fixed with: https://github.com/fatih/vim-go/pull/1319

Be sure you use `guru` for the `:GoDef` command as `godef` doesn't have support for build tags:

```
let g:go_def_mode = "guru"
```

Thanks

**Comment by tgrosinger** [comment]
Works for me! Thank you.
