### ISSUE TITLE
GoImpl cannot recognise Interface from aliased package

### ISSUE THREAD

**Issue by vbauerster** [fatih/vim-go#1313]
### Behavior

When trying to GoImpl Interface from aliased package, GoImpl cannot recognise the Interface.

### Steps to reproduce:

Try following command on [this](https://github.com/campoy/justforfunc/blob/c2447c446c26871401e9950fb1db88ecf6c2cd29/12-say-grpc/backend/main.go#L47) go file:
`:GoImpl t server pb.TextToSpeechServer`
and you'll get:
[![Screen Shot 2017-06-02 at 13.44.48.png](https://s25.postimg.org/9b02qbwsv/Screen_Shot_2017-06-02_at_13.44.48.png)](https://postimg.org/image/fop5tl1or/)

### Configuration

* My vim-go [config](https://github.com/vbauerster/dotfiles/blob/de3d014f4d0022cfa73ae851fb40faa37e2e793a/config/nvim/config/plugins/vim-go.vim)
* I got this in neovim v0.2.0, but it is same in vim 8
* vim-go version: 899b741
* go version: 1.8.3

**Comment by fatih** [comment]
Can you please open an issue to https://github.com/josharian/impl. Vim-go uses the impl tool. Thanks
