### ISSUE TITLE
GoTest never stops

### ISSUE THREAD

**Issue by imroc** [fatih/vim-go#1324]
I uprade to v1.13 from v1.12 today, when I run `:GoTest`, it never stops. I have tried `:GoUpdateBinaries", it still the same. Is that a bug ?

* vim version: 8.0.627
* vim-go version: 1.13
* go version: 1.8.3

**Comment by fatih** [comment]
Can you give more detail what it means it never stops? couple of screenshots would be useful as well.

**Comment by imroc** [comment]
![image](https://user-images.githubusercontent.com/7448852/26878701-f797adbe-4bc0-11e7-84e1-a85e7abd294a.png)

it never turn green

**Comment by vdemario** [comment]
The same is happening for me. If I run `go test` outside of vim it runs fine and passes but it never completes inside vim. I'm on 1.13 too.

One more thing that might be related. I have this in my `.vimrc` to compile tests without running them:

```
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#cmd#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Install(0)
  endif
endfunction
```

which I took from here: https://github.com/fatih/vim-go-tutorial#test-it.

It's failing on 1.13 with this error:

```
Error detected while processing function <SNR>1_build_go_files:
line    3:
E117: Unknown function: go#cmd#Test
```

**Comment by vdemario** [comment]
I ran a `git bisect` and found out my problems start at commit 8f96994867261a968b8c75fb1eedaab5e839c43c but that led me to seeing `go#cmd#Test` was now `go#test#Test`.

However, at that point `:GoTest` was working. Another bisect indicates `:GoTest` stopped responding for me at d2ff39ca7d146f2e1a64226f7f862e1febc8528b.

Hope this helps.

**Comment by fatih** [comment]
Oh I see. This is because I've disabled `echo` via:

```
let g:go_echo_command_info = 0
```

This is fixed now. Please pull latest master.

@vdemario 

I need to update the tutorial. Thanks for the heads up. The logic for `:GoTestXXX` commands  have been moved to it's own file, which give us more flexibility going forward.

**Comment by vdemario** [comment]
Everything is working now, thanks @fatih.

**Comment by kjelle** [comment]
@fatih, could you update vimrc#L169 with `go#test#Test`, it still contains `go#cmd#Test`. Thanks.

**Comment by fatih** [comment]
@kjelle where?

**Comment by kjelle** [comment]
@fatih check out https://github.com/fatih/vim-go-tutorial/blob/master/vimrc#L169
