### ISSUE TITLE
Suggestion: tag this repository with Semantic Versioning 2.0.0 spec

### ISSUE THREAD

**Issue by imroc** [fatih/vim-go#1325]
follow the SemVer has a lot of benefit : http://semver.org/

for example, if you found a bug, you can fix it immediately, and tag this repository with a new PATCH version number, and we can upgrade it to the latest tag version ( not latest master branch, becuase it may not stable ). and if you add some features, you can increment the MINOR tag version.

**Comment by fatih** [comment]
Thanks @imroc. But going forward I just want to increment the version numbers. It's easier and just works. I dont' have  time either to release intermediate releases or bug fixes. We have to channels, one is the master branch where you get all the goodness, or you wait for the releases.
