### ISSUE TITLE
[question or bug]Can not jump in grpc-middleware project.

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#1334]
![default](https://user-images.githubusercontent.com/93968/27522727-d84d592e-5a5a-11e7-8886-a516c56634d0.png)

can not jump to the `Info` definition. 

I do not know it is a guru bug or  vim-go bug.

**Comment by jinleileiking** [comment]
here is the file tree of zap in grpc-middleware
![default](https://user-images.githubusercontent.com/93968/27522779-24ad3aa0-5a5b-11e7-9f15-4bef93b2a65c.png)

**Comment by Carpetsmoker** [comment]
Do you have an example/test case I can work with? I can't really do anything with screenshots I'm afraid.

**Comment by jinleileiking** [comment]
can jump now. Reopen when I get this problem again.
