### ISSUE TITLE
:GoBuild on save .go and :GoTest on save _test.go

### ISSUE THREAD

**Issue by korjavin** [fatih/vim-go#1337]
Proposal:

What if there be some settings which allow automatically start 

GoBuild on save "*.go" file and GoTes on save "*_test.go" file.

I would be happy about it.

**Comment by Carpetsmoker** [comment]
You can already add this yourself with an `autocmd`; for example:

	" Build/Test on save.
	augroup autogo
		autocmd!
		autocmd BufWritePost *.go :GoBuild
		autocmd BufWritePost *_test.go :GoTest
	augroup end

In addition, I think you can use gometalinter to run tests too (`let g:go_metalinter_autosave_enabled = ['test', 'vet', 'golint']`? Didn't test).

**Comment by korjavin** [comment]
g:go_metalinter_autosave_enabled ['vet', 'golint', 'test']
doesn't work for me

**Comment by Carpetsmoker** [comment]
Did you read the documentation? I have no idea if that is a valid setting, but from memory I believe something like that should work (I could be mistaken!)

Either way, the autocmd should work for you.

**Comment by fatih** [comment]
Hi @korjavin 

There is no autobuild by default, you can use the command that @Carpetsmoker provided. Also the following indeed works for me

```
let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'test']
```

In your case the `=` is missing (not sure if that is related). Thanks for the feedback.
