### ISSUE TITLE
using goimports for go_fmt_command moves the cursor on save

### ISSUE THREAD

**Issue by clee** [fatih/vim-go#1342]
### Behavior

Anytime I add or delete a line that requires adding or deleting an import, my cursor gets moved when I save the file (when adding a line, my cursor gets moved up one line from where I was; when I delete a line, the cursor gets moved down a line, because goimports has added or removed lines). It would be nice if my cursor stayed locked to the same line of code I was on already, before saving.

### Steps to reproduce:

1. make sure to configure vim with `let g:go_fmt_command = "goimports"`
2. open a new Go file (using the default template)
3. add a line after `fmt.Println("vim-go")` with the contents:  
`    user := os.Getenv("user")`
4. position cursor on just-inserted line, at the `u` in `user`
5. save the file with `:w`

### Configuration

* `vimrc` contains only `let g:go_fmt_command = "goimports"`
* vim version: NVIM v0.2.1-15-g08b23d08
* vim-go version: bcf3f23dd76f39f3c3b840e3f95772ab46312219
* go version: go1.8.2 darwin/amd64

**Comment by fatih** [comment]
Thanks for the feedback. I know this is annoying. Actually the cursor still says on the same line number (vim does the correct thing) but because we added/removed lines, it seems like your cursor jumped to another position. Anyway, this is fixed now in master by getting the diff of the number of lines and then adjusting the cursor position after the formatting finishes. Please pull the latest master to use it.

**Comment by clee** [comment]
That's awesome! Thanks for addressing this so quickly. I was going to take a go at it this weekend but you beat me to it :)

I'm grabbing the code to test now.

**Comment by clee** [comment]
It looks like it retains the proper relative row now, but it seems like it's moving my cursor to the first column when goimports adjusts the file length (so the column position is getting lost).

**Comment by clee** [comment]
Figured out how to preserve the column index, submitted #1369. Hope it makes sense. Thanks, @fatih!
