### ISSUE TITLE
Is there a safe way to add new snippets.

### ISSUE THREAD

**Issue by korjavin** [fatih/vim-go#1343]
Is there a way to store my own snippets outside the bundle/vim-go ?

Somewhere close to .vimrc

**Comment by adelowo** [comment]
I think this should work (for Neosnippets)

```vim
let g:neosnippet#snippets_directory='~/path/to/snippets
```

**Comment by fatih** [comment]
For ultisnips you can add your custom folder like:

```
let g:UltiSnipsSnippetDirectories += ['~/my-custom-snippet-foler']
```

for neosnippet you use the following:

```
let g:neosnippet#snippets_directory += ['~/my-custom-snippet-foler']
```

This will be sure not to override the snippets in vim-go, but you can add your own snippets.

**Comment by korjavin** [comment]
I tried to put it in my vimrc and now see a strange thing:
```
E121: Undefined variable: g:UltiSnipsSnippetDirectories
```

**Comment by korjavin** [comment]
Ah, I found a way.
Just in case if someone interested, 
i can create UltiSnips/ dir under .vim 
and it starts to work without any settings
