### ISSUE TITLE
Start editing new file sets vim to edit template file instead.

### ISSUE THREAD

**Issue by wolf0403** [fatih/vim-go#1347]
### Behavior

Either by 
$ vim newfile.go
or within VIM:
:e newfile.go

VIM is set to edit ~/.vim/plugged/vim-go/templates/hello_world.go, instead of "newfile.go" in cwd.

### Steps to reproduce:

1. Enter vim
2. :e newfile.go
3. Observe statusline: 
"~/.vim/plugged/vim-go/templates/hello_world.go" 7L, 67C

### Configuration

* `vimrc` you used to reproduce

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()

* vim version: 7.4.2235, with 
* vim-go version:
commit f08fcab5c51bee18174340405b773a950446e9f5
Author: Fatih Arslan <ftharsln@gmail.com>
Date:   Thu Jul 6 23:26:49 2017 +0300

Installed with https://github.com/junegunn/vim-plug.

* go version:
go version go1.8beta2 darwin/amd64

**Comment by wolf0403** [comment]
First discovered with Windows Subsystem for Linux (Ubuntu on Windows) with vim 7.4.1689, with same version of vim-go / vim-plug.

**Comment by wolf0403** [comment]
Verified that v1.13 works fine.

**Comment by Carpetsmoker** [comment]
Note that v1.13 and master behave exactly the same for me. I don't see any changes that would explain this change in behaviour either; there haven't been many for this feature.

Either way, I created a PR which should fix this.

**Comment by peterwillcn** [comment]
neovim not work....
