### ISSUE TITLE
organize the go struct, in order to save memory.

### ISSUE THREAD

**Issue by sadegh-nikaein** [fatih/vim-go#1348]
i think this is good idea to write some plugin to organize the go struct for memory efficiency automatically ? i don't see any tools to do that . 
take look at this https://github.com/Tkanos/optimizing-memory-by-ordering-struct-by-type
@fatih thanks

**Comment by icholy** [comment]
The memory layout of a `struct`'s fields is undefined. AFAIK, the compiler currently preserves the order, but this should not be relied on.

**Comment by Carpetsmoker** [comment]
Useful commands: https://github.com/mdempsky/maligned https://go-review.googlesource.com/c/2179/3/cmd/wasted/main.go

Discussion about having the Go compiler do it: https://github.com/golang/go/issues/10014

It seems to me that this is a "niche issue". Sure, in some situations you care enough about the memory layout to do this, but those situations are few and far in-between; most of the time you couldn't care less.

**Comment by fatih** [comment]
Hi everyone 👋 

I don't think this is something we should tackle. as @Carpetsmoker said this is definitely under the "niche" region.  Thanks for the feedback.
