### ISSUE TITLE
"src" directory making :GoBuild fail.

### ISSUE THREAD

**Issue by icholy** [fatih/vim-go#1350]
### Behavior

`:GoBuild` is failing when there is a `src/` directory somewhere in the path.

```
b/b.go|10| cannot use "vendor/c".Thing literal (type "vendor/c".Thing) as type "github.com/icholy/vendor_err_case/src/vendor/c".Thing in argument to a.UseThing
```

### Steps to reproduce:

I've made a [repository](https://github.com/icholy/vendor_err_case) demonstrating the issue:

1. `git clone https://github.com/icholy/vendor_err_case.git`
2. Open `src/b/b.go` in vim.
3. Run `:GoBuild`

### Configuration

* vim 8
* latest vim-go

**Comment by icholy** [comment]
I've traced the issue down to the `go#path#Detect` function [here](https://github.com/fatih/vim-go/blob/f08fcab5c51bee18174340405b773a950446e9f5/autoload/go/path.vim#L87). 

Setting `g:go_autodetect_gopath` to `0` in my `.vimrc` solves the problem.

**Comment by Carpetsmoker** [comment]
What is your `$GOPATH` set to? I've had problems with `$GOPATH` containing two paths: `/home/martin/go:/home/martin/work`.

**Comment by icholy** [comment]
@Carpetsmoker my `GOPATH` contains only one path.

**Comment by fatih** [comment]
Thanks for the detailed report (especially on how to reproduce it). This is now fixed in master.
