### ISSUE TITLE
Ability to pass -coverpkg option

### ISSUE THREAD

**Issue by dobegor** [fatih/vim-go#1353]
Currently the GoCoverage just runs tests with coverage in current packages.

For integration tests written in Go a separate package is often used. However, coverage profile for that package is useless.

It would be nice to have an ability to somehow specify a -coverpkg option, so that we can get a nice coverage profile for handlers called during integration tests.

**Comment by fatih** [comment]
Hi @dobegor 

I think `:GoCoverage -coverpkg foo` should work. Did you tried it?

**Comment by Carpetsmoker** [comment]
`:GoCoverage -coverpkg foo` seems to work as expected. I'll close this for now, but feel to comment if you still have problems or questions @dobegor.

**Comment by dobegor** [comment]
Sorry, I somehow missed first Github notification on response to this issue.
Yes, it indeed works, thank you!
