### ISSUE TITLE
GoMetalinter pass when error occurs

### ISSUE THREAD

**Issue by cassiobotaro** [fatih/vim-go#1354]
### Behavior
Errcheck says:
![image](https://user-images.githubusercontent.com/3127847/28125151-22661106-66fc-11e7-8950-3fe8a53b5ceb.png)

Metalinter using errcheck:
![image](https://user-images.githubusercontent.com/3127847/28125175-35c3f7fe-66fc-11e7-8390-11b48cb21225.png)

Expect an error on `:GoMetalinter`

### Steps to reproduce:

Please create a reproducible case of your problem. If this step is
not provided, the issue will be **closed**

Re produce it with a minimal `vimrc` with all plugins disabled and
only `vim-go` enabled:

1.  install vim-plug: `curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`
2. copy .vimrc into ~
3. run :GoMetalinter

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` https://gist.github.com/cassiobotaro/71fd2ddc15ca0d996b55d07090a475b9
* vim version: 7.4.1689
* vim-go version: master
* go version: go1.8.3 linux/amd64

**Comment by maxcnunes** [comment]
I was just going to open the same issue. I have been debugging it for the last minutes and what I have found is that most go tools doesn't work well with absolute path:

```shell
varcheck returned exit status 1: import "/my/absolut/path": cannot import absolute path
```

**Full log using absolute path (It does not work)**

Using in my shell the command built by go-vim to execute the linter:
 
```shell
μ MyCompanyName/my-project-name master● ❯ gometalinter --debug --disable-all --enable=varcheck /Users/maxnunes/Development/go/src/github.com/MyCompanyName/my-project-name/clients/
DEBUG: PATH=/Users/maxnunes/.nvm/versions/node/v7.7.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/maxnunes/Development/go/bin:/usr/local/opt/go/libexec/bin
DEBUG: GOPATH=/Users/maxnunes/Development/go
DEBUG: GOBIN=
DEBUG: linting path /Users/maxnunes/Development/go/src/github.com/MyCompanyName/my-project-name/clients
DEBUG: executing /Users/maxnunes/Development/go/bin/varcheck /Users/maxnunes/Development/go/src/github.com/MyCompanyName/my-project-name/clients
DEBUG: warning: /Users/maxnunes/Development/go/bin/varcheck returned exit status 1: import "/Users/maxnunes/Development/go/src/github.com/MyCompanyName/my-project-name/clients": cannot import absolute path
2017/07/12 18:30:55 could not type check: no initial packages were loaded

DEBUG: varcheck hits 0: ^(?:[^:]+: )?(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$
DEBUG: varcheck linter took 9.354188ms
DEBUG: total elapsed time 19.053261ms
```

**Full log using relative path (It works)**

Using in my shell the command built by go-vim to execute the linter. But adapting that to use relative path:

```shell
μ MyCompanyName/my-project-name master● ❯ gometalinter --debug --disable-all --enable=varcheck clients
DEBUG: PATH=/Users/maxnunes/.nvm/versions/node/v7.7.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/maxnunes/Development/go/bin:/usr/local/opt/go/libexec/bin
DEBUG: GOPATH=/Users/maxnunes/Development/go
DEBUG: GOBIN=
DEBUG: linting path ./clients
DEBUG: executing /Users/maxnunes/Development/go/bin/varcheck ./clients
DEBUG: warning: /Users/maxnunes/Development/go/bin/varcheck returned exit status 1: github.com/MyCompanyName/my-project-name/clients: /Users/maxnunes/Development/go/src/github.com/MyCompanyName/my-project-name/clients/clients_test.go:12:5: x
github.com/MyCompanyName/my-project-name/clients: /Users/maxnunes/Development/go/src/github.com/MyCompanyName/my-project-name/clients/clients_test.go:13:5: userId

DEBUG: varcheck hits 2: ^(?:[^:]+: )?(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$
DEBUG: nolint: parsing clients/clients_test.go for directives
DEBUG: varcheck linter took 1.072668217s
DEBUG: nolint: parsing clients/clients_test.go took 466.831µs
clients/clients_test.go:12:5:warning: unused variable or constant x (varcheck)
clients/clients_test.go:13:5:warning: unused variable or constant userId (varcheck)
DEBUG: total elapsed time 1.082263742s
```

To solve that we would need to execute the linter from the package folder and pass the relative path to the linter. But I don't know if that is something possible in vim script. In NodeJS I could execute a binary with a `cwd - Current working directory of the child process`. I hope is possible to do the same with vim script. I will try to find that out. But if anyone knows the answer for that, please let me know.

**Comment by cassiobotaro** [comment]
After update binaries (`:GoUpdateBinaries`), problem was solved.
