### ISSUE TITLE
Does g:syntastic_go_gometalinter_args really works?

### ISSUE THREAD

**Issue by maxcnunes** [fatih/vim-go#1355]
The docs describes is possible to pass extra args to gometalinter through `g:syntastic_go_gometalinter_args` ([here](https://github.com/fatih/vim-go/blob/58bfea76bd11dc05b09f068a5c7a9a006db888c1/doc/vim-go.txt#L1683)). But I couldn't find any code referencing this variable:

* No code in go-vim: [search result](https://github.com/fatih/vim-go/search?utf8=%E2%9C%93&q=syntastic_go_gometalinter_args&type=)
* No code in syntastic: [search result](https://github.com/vim-syntastic/syntastic/search?utf8=%E2%9C%93&q=syntastic_go_gometalinter_args&type=)

If that setting is not possible. Would be better remove from docs.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 12 2017 08:56:45)
* vim-go version: Git commit f08fcab5c51bee18174340405b773a950446e9f5
* go version: go1.8.3 darwin/amd64

**Comment by Carpetsmoker** [comment]
It's only mentioned in the FAQ, and there isn't a section for this variable in the config.

Reading through `autoload/go/lint.vim` it seems you should be able to use `g:go_metalinter_command`:

    let g:go_metalinter_command = ["--somearg"]

The binary name is already added.

**Comment by maxcnunes** [comment]
I don't think that is the same variable I saw in the docs. The one I'm talking about is `g:syntastic_go_gometalinter_args`.

**Comment by Carpetsmoker** [comment]
No, it's not the same, but it acts as if `g:syntastic_go_gometalinter_args`.

**Comment by fatih** [comment]
Hi @maxcnunes 

It's for compatibility with `syntastic`, so it's not in vim-go at all, it's a `syntastic` setting.  That's why it's not under the `settings` in our documentation. If you want to change the setting inside vim-go, you have to use `g:go_metaliner_command`. Thanks
