### ISSUE TITLE
Last character of type being colored incorrectly.

### ISSUE THREAD

**Issue by wayneashleyberry** [fatih/vim-go#1357]
### Behavior

Last character of type being colored incorrectly.

### Steps to reproduce:

Try the following code in vim, with only `vim-go` and any color scheme. Look at the second last line.

```go
package main

type Video struct {
	ID  string `json:"id,omitempty"`
	URL string `json:"url,omitempty"`
}

func main() {
	v := &Video{}
}
```

### Configuration

```
call plug#begin('~/.config/nvim/plugged')
Plug 'fatih/vim-go'
call plug#end()

let g:go_auto_sameids = 1
let g:go_auto_type_info = 1
let g:go_fmt_command='goimports'
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
```

### Screenshots

<img width="1312" alt="screen shot 2017-07-13 at 6 01 21 pm" src="https://user-images.githubusercontent.com/727262/28176027-3b53773a-67f6-11e7-9a5a-4f428ff01f94.png">
<img width="1312" alt="screen shot 2017-07-13 at 6 05 36 pm" src="https://user-images.githubusercontent.com/727262/28176026-3b516922-67f6-11e7-9462-46dc67b503c6.png">

**Comment by Carpetsmoker** [comment]
This is caused by cfa9713e (my fault I'm afraid). I don't think we need to add the highlight offset anymore since that PR. Let me test and push a Pr.

**Comment by wayneashleyberry** [comment]
Thanks!
