### ISSUE TITLE
Unnecessary bold font inside var block declaration

### ISSUE THREAD

**Issue by vbauerster** [fatih/vim-go#1383]
When several variables are grouped in parentheses block, the first var gets its font in bold, while the rest is normal:
[![Screen Shot 2017-07-25 at 18.52.28.png](https://s25.postimg.org/cg1zct6fj/Screen_Shot_2017-07-25_at_18.52.28.png)](https://postimg.org/image/ttc9ro1qj/)
First I thought the problem is in [gruvbox](https://github.com/morhetz/gruvbox) colorscheme, which I do use, but with disabled vim-go plugin, there is no such problem.

**Comment by Carpetsmoker** [comment]
Which version are you using? Master? 1.13? And which `g:go_*` setting do you have enabled?

**Comment by Carpetsmoker** [comment]
Ah, can reproduce by setting `:let g:go_highlight_functions=1` in current master. The "bold" part has the `goFunction` syntax group applied.

**Comment by vbauerster** [comment]
Indeed I have `let g:go_highlight_functions=1` in my config.

**Comment by Carpetsmoker** [comment]
As a sidenote:

> First I thought the problem is in gruvbox colorscheme, which I do use, but with disabled vim-go plugin, there is no such problem.

It's never a bug in the colour scheme if something is highlighted wrong like this; all the colour schemes do is say "highlight a function in this way". It's the syntax file (from vim-go in this case) that says "this is what we consider to be a function".

**Comment by fatih** [comment]
The fix from @Carpetsmoker is now merged to master. Can you please try again @vbauerster ?

**Comment by vbauerster** [comment]
Confirm, it is ok now!
