### ISSUE TITLE
Feature request: Neoterm support

### ISSUE THREAD

**Issue by codeinabox** [fatih/vim-go#1392]
Is there a way to control where commands like `GoRun` are run? I am a big fan of using [Neoterm](https://github.com/kassio/neoterm) in my work flow so I can just reuse a single terminal. Happy to raise a PR if you can point me in the general direction

**Comment by Carpetsmoker** [comment]
You'd probably want to add it in [`term.vim`](https://github.com/fatih/vim-go/blob/master/autoload/go/term.vim). Also see [`go#cmd#Run()`](https://github.com/fatih/vim-go/blob/master/autoload/go/cmd.vim#L117).

**Comment by fatih** [comment]
@bhcleek is this supported now? I remember somehow reading this from NeoVim users. I'll try to validate.

**Comment by bhcleek** [comment]
I think this can be controlled using `g:go_term_mode` now.
