### ISSUE TITLE
Question: how to prevent template from being inserted in new files?

### ISSUE THREAD

**Issue by r0fls** [fatih/vim-go#1397]
### Behavior

Whenever I open an empty file I get:

```golang
package main

import "fmt"

func main() {
        fmt.Println("vim-go")
}
```

How can I disable that?

### Steps to reproduce:

Open an empty file.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vim version:  `7.4.8056` 
* vim-go version: not sure
* go version: `1.8.3 darwin/amd64`

**Comment by edganiukov** [comment]
I think it's related to https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1516

**Comment by r0fls** [comment]
Yay! Thank you!
