### ISSUE TITLE
vim-go maps the K key to doc lookup

### ISSUE THREAD

**Issue by fent** [fatih/vim-go#140]
Hi

I couldn't find information on how to unbind this key that vim-go seems to bind to looking up something. I use the K key myself for another mapping and I'm wondering if this can be turned off somehow.

**Comment by weibeld** [comment]
Thanks for this feature. I use `K` to move the cursor 10 lines up (analogous to `k` which moves one line up). So, it's really good that the vim-go mapping of `K` can be disabled.
