### ISSUE TITLE
No documentation for gotexttmpl or gohtmltmpl filetypes

### ISSUE THREAD

**Issue by docwhat** [fatih/vim-go#1403]
https://github.com/cespare/vim-go-templates says it was merged into vim-go, but there is no documentation in `:help vim-go`.  Searching for templates only returns the skeleton-file-on-new-file feature.

I expected there to be at least some minimal documentation on how to use these filetypes.

**Comment by Carpetsmoker** [comment]
I'm wondering what the best place to document this is; right now there isn't really a section where this would fit.
I was thinking of maybe adding a `go-syntax` section and add all syntax highlighting options and such there? Many built-in filetypes have such a help page (`ft-<filetype>-syntax`).

What do you think @fatih?

**Comment by fatih** [comment]
Syntax seems to have it's own file, so I think having a  `go-syntax` section is the best way. I don't like multiple different documentation/help pages as it's difficult to see and search things.
