### ISSUE TITLE
GoBuild overquotes it's arguments

### ISSUE THREAD

**Issue by ewtroan** [fatih/vim-go#1404]
### Behavior

When I run `GoBuild -tags=foo` strace shows the vim-go running `execve("go", [ "go", "'tags=foo'" ])` (note the extra quoting introduced in the tags argument).

Commenting out the lines in `cmd.vim`:

    " escape all shell arguments before we pass it to make
    if !has('nvim')
      let goargs = go#util#Shelllist(goargs, 1)
    endif

fixes this. It looks like the macro is expecting the command to be run via a shell (except for nvim?) when it is being directly executed.

This is with go-vim 1.1.14 (pulled from github juts now), go 1.8, and vim 8.0.823 using Fedora 26.

**Comment by Carpetsmoker** [comment]
Actual error from running `:GoBuild -tags=foo`:

vim-go: FAILED
vim-go: can't load package: package '-tags=foo': cannot find package "'-tags=foo'" in any of:
	/usr/lib/go/src/'-tags=foo' (from $GOROOT)
	/home/martin/go/src/'-tags=foo' (from $GOPATH)
	/home/martin/work/src/'-tags=foo' can't load package: package -i: cannot find package "-i" in any of:
	/usr/lib/go/src/-i (from $GOROOT)
	/home/martin/go/src/-i (from $GOPATH)
	/home/martin/work/src/-i
vim-go: /home/martin/go/src/a
