### ISSUE TITLE
feature-request: Initialize struct instance command

### ISSUE THREAD

**Issue by josephbuchma** [fatih/vim-go#1425]
It would be nice to have something like `:GoInitStruct`.
### Proposed workflow.
Consider we have this struct:
```go
type Car struct {
    Name string
    Color string
    Weight int
}
```
And when I create instance of it
```go
car := &Car{}
```
I place a cursor at `Car{}` and run `:GoInitStruct`, which converts the code to:
```go
car := &Car{
    Name: "",
    Color: "",
    Weight: 0,
}
```
[ideally] it also moves cursor to the first field value assignment [where I can start editing it immediately], and when I press Tab (for example), it moves cursor to next field assignment.

**Comment by fatih** [comment]
There is a tool already for this. I've talked with @davidrjenni back in GopherCon to implement something like this. Happy for us he did it with https://github.com/davidrjenni/reftools/tree/master/cmd/fillstruct all we need is to integrate into vim-go.
