### ISSUE TITLE
GoFmt errors don't go away after being fixed on latest master (but works on 1.14)

### ISSUE THREAD

**Issue by ebuchman** [fatih/vim-go#1427]
### Behavior

When I fix an error after GoFmt reports it and save the file again, the GoFmt logs should go away, but they don't.

### Steps to reproduce:

Follow the first few steps from https://unknwon.io/setup-vim-for-go-development/ up to "Install neocomplete"

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce

```
call pathogen#infect()

syntax enable  
filetype plugin on  
set number  
let g:go_disable_autoinstall = 0

" Highlight
let g:go_highlight_functions = 1  
let g:go_highlight_methods = 1  
let g:go_highlight_structs = 1  
let g:go_highlight_operators = 1  
let g:go_highlight_build_constraints = 1 
```

* vim version: 7.4.8056
* vim-go version: 52c5b1f 
* go version: `go1.8.3 darwin/amd64`

NOTE:

If I roll back vim-go to version v1.14, instead of latest master, it works fine!

**Comment by Carpetsmoker** [comment]
Sounds like the same as #1423?

**Comment by ebuchman** [comment]
Yes looks like it, thanks. I'll close this in favour of that.
