### ISSUE TITLE
vim freezes for a couple of seconds when saving go files

### ISSUE THREAD

**Issue by mhfs** [fatih/vim-go#144]
Hey there, first of all thanks for all the work on vim-go.

I started using it a few days ago and something weird that's happening is that every time I save a file vim freezes for a couple of seconds and then gets back to normal business.

Is this something other people experience or is it something with my setup? If the later, would you be able to help me debug where the slowness is?

I'd really appreciate any help.

Thanks!

**Comment by phuna** [comment]
Hi,
I got the same problem that saving go file makes vim freeze for around 3 seconds. I'm trying to profile :w but don't know how to do yet. In profile help there're file and func profile but still don't know how to apply them for :w. Could you help?
Thank you

**Comment by bawigga** [comment]
Also seeing slowness on save due to syntastic. `:GoFmt` is speedy, but with `SyntasticToggleMode` set to true it really slows down. 

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   8.455450   0.000031  <SNR>53_BufWritePostHook()
    1   8.455407   0.000166  <SNR>53_UpdateErrors()
    1   8.454063   0.000287  <SNR>53_CacheErrors()
    1   8.453097   0.000024  155()
    1   8.452995   0.000075  154()
    1   8.452778   0.000175  SyntaxCheckers_go_go_GetLocList()
    2   8.452195   0.001466  SyntasticMake()
    1   0.569477   0.002985  go#fmt#Format()
    3   0.052557   0.000922  <SNR>118_AutoUpdate()
    1   0.050932   0.004340  <SNR>118_ProcessFile()
    1   0.023980   0.000209  <SNR>118_ExecuteCtagsOnFile()
    1   0.023612   0.000285  <SNR>118_ExecuteCtags()
   57   0.014923   0.011349  <SNR>118_ParseTagline()
    3   0.008139   0.000372  <SNR>118_SortTags()
   15   0.006782   0.003099  airline#extensions#whitespace#check()
    1   0.005190   0.000014  290()
  241   0.004479             <SNR>118_CompareByKind()
   15   0.004004             airline#check_mode()
    3   0.003683             <SNR>89_check_mixed_indent()
    2   0.003430   0.000263  <SNR>105_OnCursorMovedNormalMode()
```

@phuna You can profile using the following:

```
:profile start profile.log
:profile func *
:profile file *
" At this point do slow actions
:profile pause
```
Then quit vim to write out the `profile.log` file. See [here](http://stackoverflow.com/a/12216578/105061)

**Comment by phuna** [comment]
@bawigga This slowness problem has gone few weeks ago after I updated all plugins. I'll keep the link for later check if problem occurs again. Thank you for pointing it out.

**Comment by cachance7** [comment]
I, too, was encountering a substantial delay. Was able to resolve my issue by setting the vim shell to bash; I use fish otherwise.

**Comment by ernestas-poskus** [comment]
For my case 'vim slowdown' was in a form of constant recompilation of binary when working with compilable (main) package. This was caused by scrooloose/syntastic - disabling it helped.

**Comment by vlad-doru** [comment]
Shout out to @ernestas-poskus .. Vim-go does not play well with syntastic.

**Comment by ernestas-poskus** [comment]
You are right, found the issue myself, Syntastic was recompiling Go project every time on save. Redefining ```g:syntastic_go_checkers``` checkers helped.

```vim
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
```

**Comment by mckelvin** [comment]
@ernestas-poskus :+1: for `let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']`

**Comment by leonlee** [comment]
@ernestas-poskus  +1

**Comment by ibash** [comment]
Thanks @ernestas-poskus!

**Comment by tsirolnik** [comment]
I've reproduced this issue.

For anyone looking for the problem - It's probably syntastic (This was the problem for me)

**Comment by rkuska** [comment]
I am running into the same issue. I have a clean installation of nvim together with vim-go. There is anything in my config file besides `Plug ....` for vim-go. On save nvim freezes for 20 seconds. 

I can see that most time spent is in promise.vim

```
FUNCTION  <SNR>49_await()
    Defined: ~/.vim/plugged/vim-go/autoload/go/promise.vim:37
Called 2 times
Total time:  20.056251
 Self time:  20.056072

count  total (s)   self (s)
    2              0.000025   let l:timer = timer_start(a:timeout, function('s:setretval', [a:default], self))
  395              0.004176   while !has_key(self, 'retval')
  393  20.049193  20.049015     sleep 50m
  395              0.002525   endwhile
    2              0.000026   call timer_stop(l:timer)
                            
    2              0.000021   if get(self, 'exception', 0)
                                throw self.retval
    2              0.000003   endif
    2              0.000018   return self.retval
```

And promise is used twice from lsp.vim:
```

                              " await the result to avoid any race conditions among autocmds (e.g.
                              " BufWritePre and BufWritePost)
    1  10.004114   0.000025   call l:handler.await()
```

There is another call like this. I am not sure what is it waiting for though. lsp is executed by gofmt (lsp#Format and lsp#Imports)

**Comment by rkuska** [comment]
I see the same behavior in both vim and nvim.

**Comment by rkuska** [comment]
I figured out this one, I run `vim -V12log` to get some logs to follow and I saw plenty of calls `go#path#ToURI` so I started thinking that 10s seems like some sort of timeout maybe. That's when I figured that I actually never built my project (I fresh installed my laptop) and I have some private repositories.

Got the necessary stuff to get private repository going, did `go mod tidy` and I have freezing no more.

**Comment by leppez** [comment]
Running into the same issue describes above:
`FUNCTION  <SNR>353_await()
    Defined: ~/dev/dotfiles/vim/pack/03_plugins/start/go/autoload/go/promise.vim:37
Called 2 times
Total time:  20.045644
 Self time:  19.998178

count  total (s)   self (s)
    2              0.000013   let l:timer = timer_start(a:timeout, function('s:setretval', [a:default], self))
  396              0.003118   while !has_key(self, 'retval')
  394  20.040039  19.992573     sleep 50m
  396              0.002180   endwhile
    2              0.000008   call timer_stop(l:timer)
                            
    2              0.000005   if get(self, 'exception', 0)
                                throw self.retval
    2              0.000001   endif
    2              0.000003   return self.retval
`

I have tried doing a `go mod tidy` on my basic hello, world project but no dice.

**Comment by shydefoo** [comment]
@carpet-stain I'm facing the same issue also with the promise.vim file. Did you manage to resolve this issue eventually? If so how?
