### ISSUE TITLE
GoBuild command fail

### ISSUE THREAD

**Issue by reireias** [fatih/vim-go#1444]
### Behavior

When I run `:GoBuild`, vim shows following error message.

```
vim-go: building dispatched ...                                                                                 
Error detected while processing function go#cmd#Build[32]..go#jobcontrol#Spawn[4]..<SNR>158_spawn:
line   47:
E745: Using a List as a Number
E15: Invalid expression: ['go'] + a:args
```

This error occurs later than df60f2652d2d85058cb46a5be6d5e933ebaded4b .

I think that the following lines of this commit are wrong.
https://github.com/fatih/vim-go/commit/df60f2652d2d85058cb46a5be6d5e933ebaded4b#diff-0754118ec7181423a7c0233b50dfaccfR40

The implementation is as follows:
```
function! s:spawn(bang, desc, args, for) abort
```

The correct implementation is as follows:
```
function! s:spawn(bang, desc, for, args) abort
```

### Configuration

* vim version: NVIM v0.2.1-dev
* vim-go version: 65a50ce

**Comment by Carpetsmoker** [comment]
@bhcleek Would you mind taking a look if you have time? Otherwise I can look later.

**Comment by bhcleek** [comment]
Yeah, I can take a look today.

**Comment by bhcleek** [comment]
This is very likely to have been caused by my changes in #1415. As a temporary work around, you can go back to `dfc8993`.
