### ISSUE TITLE
vim-go's syntactic highlighting makes vim super slow when dealing with long lines

### ISSUE THREAD

**Issue by louis-paul** [fatih/vim-go#145]
I needed to run a quick test on a snipped of text, which I pasted directly into my code (+/- 800 chars), between quotes. Immediately, the whole editor became unresponsive, taking seconds to make simple moves with hjkl.

Disabling vim-go or syntactic highlighting makes the problem go away instantly.

**Comment by saurabh-kushwah** [comment]
> I've played a bit with settings and it seems that `go_highlight_functions` produces the major hog of performances. When disabling it and disabling/enabling syntactic highlighting, vim goes a lot faster (but still feels irresponsive).
> 
> With more testing, disabling `go_highlight_structs` at the same time makes the editor responsive again.

Function and function calls both slow down completion. For me function call and fields highlighting slowed down.

```vim 
" Highlight Function Calls
let g:go_highlight_functions      = 1
let g:go_highlight_function_calls = 1

" Highlight struct fields 
let g:go_highlight_fields = 1

```
