### ISSUE TITLE
gocode installation on Windows with GoInstallBinaries breaks autocomplete

### ISSUE THREAD

**Issue by appul** [fatih/vim-go#1454]
### Behavior

Autocomplete breaks with the default gocode installation when using `GoInstallBinaries`, spawning a command prompt that hangs. It seemed to work fine on my Mac using Neovim with Deoplete, but not using Gvim 8.0 with Neocomplete.

I saw another issue that could be related to this; #1418 

### Steps to reproduce:

1. Install `fatih/vim-go` and `Shougo/neocomplete.vim`
2. `:GoInstallBinaries`
3. Open `.go` file
4. Try autocomplete, but it hangs

**It was fixed** by running the following; (this is mentioned in the [gocode readme](https://github.com/nsf/gocode/blob/master/README.md#setup))

`go get -u -ldflags -H=windowsgui github.com/nsf/gocode` 

### Configuration

GVim 8.0, Windows 7

```vim
Plug 'Shougo/neocomplete.vim'
set completeopt+=noinsert
set completeopt-=preview
let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 2

Plug 'fatih/vim-go'
let g:go_gocode_socket_type = "tcp"
let g:go_gocode_autobuild=0
let g:go_gocode_propose_builtins = 0
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 1
let g:go_highlight_types = 0
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 0
let g:go_auto_sameids = 0
let g:go_auto_type_info = 0
let g:go_updatetime = 800
let g:go_gorename_prefill = 0
let g:go_metalinter_autosave_enabled = ['vet']
let g:go_metalinter_enabled = ['vet', 'golint']
```

**Comment by appul** [comment]
`go get -u -ldflags -H=windowsgui github.com/nsf/gocode`
This stopped the command prompt from showing up constantly, but didn't actually fix autocompletion after all. Tried Neovim with Deoplete on Windows and the issue didn't arise; completion working fine.

**Comment by Carpetsmoker** [comment]
Does it work when you use Vim's omnicomplete (`<C-x><C-o>`) without additional plugins?
