### ISSUE TITLE
Problem with autocomplete

### ISSUE THREAD

**Issue by skytask** [fatih/vim-go#1457]
Autocomplete doesn't properly work for me! when i press `<C-x><C-o>` just receive a row with value of `PANIC` and not more.

1. Install `fatih/vim-go` and `Shougo/neocomplete.vim`
2. Install gocode

* vim version: latest
* vim-go version: latest
* go version: 1.9
* OS: Linux

**Comment by Carpetsmoker** [comment]
Does `:messages` say anything useful?

Maybe try restarting `gocode`? See `gocode status`, `gocode drop-cache`, and `gocode close` (and there's always `kill` of course).

**Comment by skytask** [comment]
This problem is relevant to `gocode`

**Comment by eggsbenjamin** [comment]
I managed to rectify this by reinstalling the `gocode` binary.

`rm $GOBIN/gocode`

then run `GoInstallBinaries` or manually reinstall `gocode`. Make sure that you stop any stale `gocode` processes that may be running.

**Comment by fredr** [comment]
for anyone coming across this, see https://github.com/joefitzgerald/go-plus/issues/433
