### ISSUE TITLE
Type alias quick fix error

### ISSUE THREAD

**Issue by gsquire** [fatih/vim-go#1459]
### Behavior

I updated to the latest commit on master and while saving a small example with the new type alias feature am receiving a quick fix formatting error.

### Steps to reproduce:
Here is a small valid code example:

```go
package main

import "fmt"

type a = int

func main() {
	var test a = 1
	fmt.Println(test)
}
```
Error output:

```sh
1 a.go|5 col 8| : expected type, found '='
0 a.go|9 col 2| : expected declaration, found 'IDENT' fmt
```

### Configuration

I don't think I need to share my vim RC file but I can if requested.

* vim version: 8.0.1100
* vim-go version: 1e7560e0e2cf5b423c3b3dbbad501cce9f9fde35
* go version: 1.9

**Comment by Carpetsmoker** [comment]
That file seems to work for me in a quick test.

I don't see which tool/command is failing; could you try running `:GoUpdateBinaries`? Maybe you have some old version of a tool.

**Comment by gsquire** [comment]
Running `GoUpdateBinaries` fixed it. Thanks for the help.
