### ISSUE TITLE
Working in project that uses build tags

### ISSUE THREAD

**Issue by dadgar** [fatih/vim-go#1464]
### Behavior

When working in files that have build tags, not much works. There is the command `:GoBuildTags` but it isn't pervasive. It would be nice if when you set that completion, go-to's, etc worked. This also applies to test files as well. If I set the build tag and run `:GoTestFunc` it would be nice for those to be applied rather than having to write `:GoTestFunc -tags <tag>` every time.

### Steps to reproduce:

1) Create two files, one guarded by a build tag `foo` and a main.go
2) Define a struct in the build tag version
3) Set `:GoBuilldTag foo`
4) Try using the struct in the main.go, autocomplete, goto, etc won't work.

### Configuration

* `vimrc`: Don't think it will be necessary to repro
* vim version: nvim v0.2.0
* vim-go version: Latest
* go version: 1.9.0

**Comment by Carpetsmoker** [comment]
Yeah, `:GoBuildTags` is somewhat inconsistently applies at the moment.

For the most part adding this should be simple; although some tools may not (fully) support it. For example `gocode` (which is used for the completion) doesn't seem to: https://github.com/nsf/gocode/issues/390

**Comment by bhcleek** [comment]
#1562 added support of `g:go_build_tags` to the `:GoTest` family of functions.

**Comment by bhcleek** [comment]
@Carpetsmoker do you know of any other tools that vim-go uses that we need to add this support to, or should we close this issue since #1562 took care of the `:GoTest` family of functions?

**Comment by dadgar** [comment]
If this issue is closed it would be nice to see other followup issues be filed for other features that break. I listed a few (goto, autocomplete, etc).
