### ISSUE TITLE
how can I find the place a function use?

### ISSUE THREAD

**Issue by widon1104** [fatih/vim-go#1472]
### Behavior

Write here what's happening and what you're expecting instead of...

### Steps to reproduce:

Please create a reproducible case of your problem. If this step is
not provided, the issue will be **closed**

Re produce it with a minimal `vimrc` with all plugins disabled and
only `vim-go` enabled:

1.
2.
3.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version:
* vim-go version:
* go version:

**Comment by Carpetsmoker** [comment]
I think you want either `:GoDef` or `:GoCallers`? See `:help <command>` for more information on both.

If that's now what you're after then could you please clarify your question? I'm afraid that right now it's kind of difficult to understand.
