### ISSUE TITLE
GoInstallBinaries fails in vim on Ubuntu/Bash for Windows

### ISSUE THREAD

**Issue by habeanf** [fatih/vim-go#1473]
### Behavior
Running GoInstallBinaries in vim on Ubuntu/Bash for Windows fails with:
```
vim-go: gocode not found. Installing github.com/nsf/gocode to folder /home/amir/go/bin/
Error installing github.com/nsf/gocode: github.com/nsf/gocode (download)
# cd .; git clone https://github.com/nsf/gocode /home/amir/go/src/github.com/nsf/gocode
package github.com/nsf/gocode: fork/exec /usr/bin/git: invalid argument
vim-go: gometalinter not found. Installing github.com/alecthomas/gometalinter to folder /home/amir/go/bin/
Error installing github.com/alecthomas/gometalinter: github.com/alecthomas/gometalinter (download)
# cd .; git clone https://github.com/alecthomas/gometalinter /home/amir/go/src/github.com/alecthomas/gometalinter
package github.com/alecthomas/gometalinter: fork/exec /usr/bin/git: invalid argument
...
```

### Steps to reproduce:

With vim-go installed, run :GoInstallBinaries

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

Using vimrc from:
https://github.com/meirkriheli/dotvim
* vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 21 2017 11:47:13)
Included patches: 1-1130
* vim-go version: 1.14
* go version: 1.9

**Comment by bhcleek** [comment]
Does `go  get -u github.com/nsf/gocode` work on Ubuntu/Bash for Windows?

**Comment by habeanf** [comment]
Good point. Surprisingly, no it does not:
```
$ go get -u github.com/nsf/gocode
# cd .; git clone https://github.com/nsf/gocode /home/amir/go/src/github.com/nsf/gocode
package github.com/nsf/gocode: fork/exec /usr/bin/git: invalid argument
```
I'll close but keep updating when I find the root cause

**Comment by habeanf** [comment]
FYI, might be related:
https://github.com/golang/go/issues/17365
