### ISSUE TITLE
GoInstallBinaries does not completely work on the terminal command line.

### ISSUE THREAD

**Issue by jongillham** [fatih/vim-go#1475]
### Behavior

I expect to be able to use the terminal command line syntax `vim +GoInstallBinaries +qall` to install the vim-go binaries without further input from the user. This greatly helps scripting the install of vim-go.

Unfortunately once the terminal screen is filled up with log messages I am required to press the space bar to continue with the binary install process.

### Steps to reproduce:

Set Go path:
`$ export GOPATH=/home/grace`

Install pathogen and vim-go for user `grace`:
```
$ mkdir -p /home/grace/.vim/autoload /home/grace/.vim/bundle \
        && curl -LSso /home/grace/.vim/autoload/pathogen.vim \
                https://tpo.pe/pathogen.vim \
        && touch /home/grace/.vimrc \
        && echo "execute pathogen#infect()" >> /home/grace/.vimrc \
        && echo "syntax on" >> /home/grace/.vimrc \
        && echo "filetype plugin indent on" >> /home/grace/.vimrc \
        && git clone --depth=1 https://github.com/fatih/vim-go.git \
                /home/grace/.vim/bundle/vim-go
```

Now install the binaries via the terminal command line:

`$ vim +GoInstallBinaries +qall`

The binaries start installing but get to the following point where the space bar must be pressed for the rest of the binaries to install:
<img width="602" alt="screen shot 2017-09-25 at 12 52 28" src="https://user-images.githubusercontent.com/1438213/30807138-792f6760-a1f0-11e7-9624-1cbfa0141ade.png">

### Configuration

Ubuntu 16.04

```
$ cat .vimrc 
   execute pathogen#infect()
   syntax on
   filetype plugin indent on

```
```
$ vim --version
   VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
   Included patches: 1-1689
   Extra patches: 8.0.0056
```

```
$ go version
   go version go1.9 linux/amd64
```

vim-go version: Unsure how to determine this but it's been downloaded within the last week.

Note that I created [this issue](https://github.com/fatih/vim-go-tutorial/issues/44) with the hope that it can be fixed with documentation.

**Comment by Carpetsmoker** [comment]
> Unfortunately once the terminal screen is filled up with log messages I am required to press the space bar to continue with the binary install process.

This is because the messages don't fit on your window; see [`:help hit-enter`](http://vimhelp.appspot.com/message.txt.html#git-enter) and [`:help 'shortmess'`](http://vimhelp.appspot.com/options.txt.html#%27shortmess%27).

The easiest way to fix it is to use `:silent` so that the messages aren't displayed at all:

    vim +'silent :GoInstallBinaries' +qall

**Comment by Carpetsmoker** [comment]
BTW, using something like `vim -esN +GoInstallBinaries +q` is perhaps better, since in Ex mode it won't clobber your terminal (coincidentally I was working on something else today that uses this).

**Comment by jongillham** [comment]
@Carpetsmoker thanks for your help.
