### ISSUE TITLE
Set ENV var before running :GoTest

### ISSUE THREAD

**Issue by khaiql** [fatih/vim-go#1480]
### Behavior

My project requires to set some env var before running go test. How can configure vim-go to do something like `source .env.dev && go test` ... upon calling `:GoTest` in vim?

**Comment by Carpetsmoker** [comment]
You can use the `$` notation to set environment variables in Vim: `let $MY_ENV_VAR = "my value"`.

You can chain Vim commands with `|`:

    :let $MY_ENV_VAR = "my value" | :GoTest

Of course, that's some typing so you may want to use a command:

    :command! VimTestEnv let $MY_ENV_VAR = "my value" | :GoTest

(note: if you use a mapping then read `:help map-bar`).

If you want to source a file then you can use the `source` command on a file that has a bunch of `let $ENV = "value"` commands.
