### ISSUE TITLE
functions, methods, arrays not highlight

### ISSUE THREAD

**Issue by NelsonKen** [fatih/vim-go#1481]
### Behavior

functions, methods, arrays not highlight

### Steps to reproduce:

step : open *.go will see that It's all gray 

Re produce it with a minimal `vimrc` with all plugins disabled and
only `vim-go` enabled:

step : open *.go will see that It's all gray 

issue:
functions, methods, arrays not highlight

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version:
* vim-go version:
* go version:

**Comment by Carpetsmoker** [comment]
Function names and such aren't highlighted by default. See `:help go-syntax` for the settings you can set.
