### ISSUE TITLE
GoBuild fails with E714: List required

### ISSUE THREAD

**Issue by turkenh** [fatih/vim-go#1483]
### Behavior

Running :GoBuild with simple [main.go](https://github.com/fatih/vim-go-tutorial/blob/master/main.go) in the tutorial errors instead of success.

### Steps to reproduce:

1. Just follow the [tutorial](https://github.com/fatih/vim-go-tutorial)
2. Run :GoBuild as in [build-it step](https://github.com/fatih/vim-go-tutorial#build-it)

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

* vim version: 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com

* vim-go version: master branch
* go version: go version go1.8.3 darwin/amd64

Only occurs from tip of master, not reproducible in v1.14
Instructing to use latest stable version in the tutorial might be a good idea.

**Comment by Carpetsmoker** [comment]
Strict type checking was removed in Vim 7.4.1546, but you're using Vim 7.4.898, which is almost two years old.

Easier way to fix it is to update Vim to a newer version. The lowest version I test stuff with is Vim 7.4.1689 (but I would recommend you use Vim 8).

**Comment by Carpetsmoker** [comment]
Fixed with #1498.

I would strongly recommend updating to a newer Vim version though.
