### ISSUE TITLE
vim go default browser

### ISSUE THREAD

**Issue by FractalWire** [fatih/vim-go#1487]
### Behavior

I try to launch every vim-go related command to a browser different to the default one. First I used : 
`let g:go_play_browser_command = 'chromium'`

There are two problems with that : 
1. If chromium is not already opened, it will froze neovim
2. It does not pass the adress to chromium correctly, and instead display the default starting page

To avoid problem 1, I can do that instead : 
`let g:go_play_browser_command = '(chromium & &> /dev/null)'`

So that chromium runs in its own subshell when launched.
But problem n° 2 is still there.

Is there a way to pass the correct address to chromium without having to manually paste it in the address bar ?

### Steps to reproduce:

Modify the default `g:go_play_browser_command` value, and try to use the `:GoDocBrowser` or `:GoPlay` command

### Configuration

OS : Linux (Archlinux)
Window Manager : i3

vim-go version : 1.14
go version : 1.9

vim version : 8.0
neovim version : 0.2.0

**Comment by mattes** [comment]
> It does not pass the adress to chromium correctly, and instead display the default starting page

I don't know what is causing it, but I ran into it, too. It will just open a blank page in chrome for Go docs.

**Comment by mattes** [comment]
Fixed my issue. It was actually Chrome related. `open -a Google\ Chrome https://www.google.com` would not work either. Upgraded to latest Chrome version and it is fixed.

**Comment by Carpetsmoker** [comment]
Can reproduce with Chromium 61.0.3163.100 on Linux. Works fine with Firefox.

As mattes mentioned, the problem seems to be in Chrome; but I think we can do better anyway by making sure that we never "brick" Vim by using e.g. `system('command &')`.

**Comment by FractalWire** [comment]
Hum, indeed the freeze is not there with `let g:go_play_browser_command = 'firefox'` however the url is not loaded either, it's a blank page instead.

chromium version : 61.0.3163.100
Firefox version : 55.0.3

**Comment by Carpetsmoker** [comment]
looking more deeply at this, I think you need to use `chromium %URL% &` and then it works as expected. It does for me anyway.

I'll make a PR to clarify the docs.

**Comment by FractalWire** [comment]
Using `chromium %URL% &` works as intended : no freezes, and the url is passed correctly.
Thanks !
