### ISSUE TITLE
(neo)Vim fails with at various steps

### ISSUE THREAD

**Issue by nikkolasg** [fatih/vim-go#1490]
Hi there,

I have trouble with vim-go. Some functions are fine sometimes, but most of the time it just does not work. Some examples:
 - GoTest fails at the end or right after with 
```
Error detected while processing function <SNR>53_auto_type_info[3]..go#tool#Info[3]..go#complete#Info[2]..go#complete#GetInfo[2]..<SNR>114_gocodeCurrentBuffer:                                             
line    2:
E482: Can't open file /tmp/nvimEbmuP4/63 for writing: no such file or directory
```

- Auto fmt when saving is enabled, so it does the same when I ":w"
- Sometimes, GoBuild and GoTest work fine but then, right after, trying GoCoverage fails with the same error. 
- Usually, after an error occured, I often get the  E79 error: 
```
E79: Cannot expand wildcards
``` 
popping up for example when I switch of buffers/windows

I fixed up my version of neo-vim at 1.7 before because of this error a while ago but it always did that from time to time. Today I went to full re-installation of neovim (2.0), and vim-go (+ GoUpdateBinaries) and it still fails. I just retried older versions of nvim and the problem still persists.
The permissions on my /tmp folder are OK.
```
drwxrwxrwt  10 root root   220 Oct  1 20:50 
```
Also I never experienced any similar problem in others context than with vim-go.

Any ideas ?

Thanks a lot.

* vim version: 0.2.0
* vim-go version: master branch up to date as today
* go version:go version go1.9 linux/amd64
* vim-plugins: ctrlp.vim  cvim  nerdcommenter  nerdtree  rust.vim  tagbar  tagbar-markdown  vim-airline  vim-airline-themes  vim-colors-solarized  vim-fugitive  vim-go  vim-surround  YouCompleteMe

**EDIT**: just tried with vim and bugs are still there:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 28 2017 23:18:29)
```

**EDIT 2**: I found out the minimum actions required to trigger the bug is to GoTest then try to save the file. Just saving the file right after opening vim works well.

**Comment by nikkolasg** [comment]
Well, after hours, I finally found a configuration that works so far. Everything is up-to-date and now I use ~/tmp as my tmp folder for vim using `let $TMPDIR = $HOME."/tmp" ` in my .vimrc.
I guess there are some problems with my /tmp folder which I need to resolve but that's another story.

**Comment by nikkolasg** [comment]
I thought it fixed the issue but no. In fact, my neovim is still using regular /tmp/ folder and the issue just re-surfaced :(

**Comment by Carpetsmoker** [comment]
hm, not sure what could be causing this.

Can you reproduce it with a minimal vimrc ([this page may help](https://vi.stackexchange.com/q/2003/51)) and a minimal Go package?

Could you also post he *full* output of `:messages`? Maybe there's is something in there that can provide a clue.

**Comment by Carpetsmoker** [comment]
I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.
