### ISSUE TITLE
logs output

### ISSUE THREAD

**Issue by flibustenet** [fatih/vim-go#1493]
When running `:GoTest` or `:GoTestFunc`i would like to see the logs.

I tried with `:GoTest -v` but it doesn't change.

Maybe there is an other way to develop tests than to see the logs at each step ?

**Comment by Carpetsmoker** [comment]
You can use the Neovim terminal if you use Neovim, but in Vim there isn't really a good way at the moment.

**Comment by bhcleek** [comment]
@flibustenet I believe #1513 at least partially addresses this. It won't show the `RUN`, `PASS`, `FAIL` entries, but it will show the `"testing.T".Log` lines.

**Comment by sashomasho** [comment]
I also would like to see test output (maybe like GoRun works). I'm new to go-vim and maybe I'm missing something, but for example sometimes tests are used to debug a problem and one can put a print here and there to see what's going on, and exiting from vim just to run the test and see a log sounds counterproductive.
