### ISSUE TITLE
Buffer filled with "ghost" [0A when using auto_sameids

### ISSUE THREAD

**Issue by MartyLake** [fatih/vim-go#1494]
### Behavior

Buffer is filled with "ghost" [0A when I move the cursor UP. Going to another page and going back to the page erases the [0A chars.

Moving cursor down spawns [0B, left [0C, right [0D

### Steps to reproduce:

Please create a reproducible case of your problem. If this step is
not provided, the issue will be **closed**

Re produce it with a minimal `vimrc` with all plugins disabled and
only `vim-go` enabled:

1.  auto_sameids: ON
2. open a go file, put cursor into variable, wait for updatetime to trigger
3. move cursor to other variable, see the [0A appears

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 22 2017 12:32:53)
Included patches: 1-983
* vim-go version:
* go version: 1.9

**Comment by Carpetsmoker** [comment]
Could you also add the second line of `:version` ("Included patches: ")? Thanks!

**Comment by MartyLake** [comment]
here you go ! :) [vimversion.txt](https://github.com/fatih/vim-go/files/1356052/vimversion.txt)

**Comment by bhcleek** [comment]
@MartyLake thank you for reporting this. It sounds suspiciously like other reports (I've been encountering it, too). Until we have a resolution, you may find `:redraw!` less cumbersome than swapping buffers.

**Comment by MartyLake** [comment]
Thanks for the tip !


---
Matthieu TALBOT
neogaldr@gmail.com

+33 629 22 15 70
fr.linkedin.com/in/matthieutalbot
http://www.soundcloud.com/Marty-Lake
http://lifehacker.com/5028808/how-eom-makes-your-email-more-efficient

**Comment by mlen108** [comment]
I'm experiencing the same issue, even on files which aren't Golang related. Redrawing the buffer (`Ctrl + L`) helps but it's a bit tiring to type it every time one uses a cursor.

**Comment by bhcleek** [comment]
Fixed by #1697
