### ISSUE TITLE
Lists (quickfix, location) can be difficult to read

### ISSUE THREAD

**Issue by hjma29** [fatih/vim-go#1499]
:GoDescribe/guru shows package path before symbols and it really makes it hard to read. Is this an expected behavior?

For example, doing :GoDescribe for NewFakeCli func in the following line
https://github.com/docker/cli/blob/master/cli/command/image/inspect_test.go#L79

The output has long package path like "github.com/docker/cli/internal/test" or "github.com/docker/cli/vendor/github.com/docker/docker/client" and it's very hard to read.

`cli/command/image/inspect_test.go|79 col 15| reference to func github.com/docker/cli/internal/test.NewFakeCli(client github.com/docker/cli/vendor/github.com/docker/docker/client.APIClient) *github.com/docker/cli/internal/test.FakeCli`

Hoping to generate the output like the following "go doc" or "gogetdoc".
`func NewFakeCli(client client.APIClient) *FakeCli
`

```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 19 2016 15:09:36)
Included patches: 1-898
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv


let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_variable_declarations = 1
let g:go_autodetect_gopath = 0
let g:go_list_type = "quickfix"
let g:go_info_mode = "guru"
let g:go_def_mode = "guru"
let g:go_def_reuse_buffer = 0


go ver: 1.9

vim-go: ## 1.15 - (October 3, 2017)
```

**Comment by bhcleek** [comment]
This is expected behavior; :GoDescribe` maps very closely to `guru describe`. Among other things, it's giving information about import path of the package, not just the package name (which could change from file to file).

**Comment by hjma29** [comment]
ok. thanks. 

However, this long full path of the package causes Dodescribe output not readable for some large structs/interfaces which implements tons of methods.

**Comment by hjma29** [comment]
Thanks Billie and Faith

I agree the path appending is from guru side. I did a guru CLI run against byte offset and it shows pretty much the same thing.

I looked at Emacs implementation of guru. It looks like they only show the last part of matching filenames and didn't show the row/column location. So lines align very neatly until the start of method name. This actually helps me to see which kind of methods the struct implements. I think maybe we can introduce an option in vim-go to not display matching file full path and emit row/column number.

for describing "fakeClient" struct in this line, the image below shows emacs guru plugin output.
https://github.com/docker/cli/blob/master/cli/command/node/client_test.go#L10


![image](https://user-images.githubusercontent.com/14317124/31350940-f385b116-acdd-11e7-83c1-e144c9b660d6.png)

**Comment by bhcleek** [comment]
@hjma29 I have been digging into this to see if there's anything we can or should do to make the output prettier. It's not integrated to vim-go yet, but you may find that using a syntax file for quickfix windows (`syntax/qf.vim`) with these contents:
```
" Quit when a syntax file was already loaded
if exists("b:current_syntax")
  finish
endif

" A bunch of useful C keywords
syn match	qfFileName	"^[^|]*" contains=qfShortFileName nextgroup=qfSeparator
syn match	qfShortFileName "^[^|]*\ze[^|]\{19}" contained contains=NONE transparent conceal cchar=…
syn match	qfSeparator	"|" nextgroup=qfLineNr contained
syn match	qfLineNr	"[^|]*" contained contains=qfError
syn match	qfError		"error" contained

" The default highlighting.
hi def link qfFileName	Directory
hi def link qfLineNr	LineNr
hi def link qfError	Error

let b:current_syntax = "qf"

" vim: ts=8
```
will give you more readable output. On my system, for instance, where I have
```
set conceallevel=1 concealcursor=nc
set listchars=tab:\|»,trail:·,extends:…,precedes:…,nbsp:¬,eol:¶ " highlight whitespace
```

I now see 
![image](https://user-images.githubusercontent.com/1958864/31574048-d7d3b3c2-b07b-11e7-993f-bbd11e1cd443.png)

It's not quite as pretty as we want, but it's an improvement....

**Comment by hjma29** [comment]
thanks @bhcleek ! it's much easier to read now.

**Comment by Carpetsmoker** [comment]
I'm not 100% sure this is something we need to do in vim-go to be honest. It seems better suited as a feature in [vim-qf](https://github.com/romainl/vim-qf) or something.

**Comment by fatih** [comment]
In addition to @Carpetsmoker , If this is something that can be changed from outside, let's put this inside the doc's FAQ section. Everyone can refer from there.

**Comment by Carpetsmoker** [comment]
This feature was rejected from vim-qf; see romainl/vim-qf#31, which also lists another solution.
