### ISSUE TITLE
Syntax highlighting doesn't work as expected (g:go_highlight_methods, g:go_highlight_functions )

### ISSUE THREAD

**Issue by alexbyk** [fatih/vim-go#1500]
### Behavior
![screenshot](http://alexbyk.com/vim-go-hightlight.png)
I would expect `g:go_highlight_methods` to highlight method names, `g:go_highlight_function` to highlight functions names.
Instead of that
- `g:go_highlight_methods=1; g:go_highlight_functions=0` highlights method invocations only
- `g:go_highlight_functions=1`  highlights method names, function names, methods invocations and `g:go_highlight_methods` doesn't matter in this case

Is there any way to highlight only function/method names, not method invocations? In the screenshot above I would expect `mymethod` and `main` to be highlighted, while `Println` to remain white

### Steps to reproduce:
1. open .go file
2. set g:go_highlight_function=1/0, g:go_highlight_methods=1/0
3. save file(or reload)

### Configuration

* `vimrc` you used to reproduce:
    full: https://github.com/alexbyk/rcfiles/blob/master/vimrc
    minimal: https://gist.github.com/alexbyk/b7023c32f304f055558c8ccb00efc871
* vim version: NVIM v0.2.0, also tried with gvim 7.4
* vim-go version: the latest

**Comment by Carpetsmoker** [comment]
See #1557 for a fix; with that patch setting just `g:go_highlight_functions = 1` should do what you want.
