### ISSUE TITLE
"unexpected signal during runtime execution" during :GoDef

### ISSUE THREAD

**Issue by sebiwi** [fatih/vim-go#1501]
### Behavior

I'm getting a "fatal error: unexpected signal during runtime execution" error when trying to use the :GoDef command on a huge codebase (Kubernetes). This doesn't happen every single time I try the GoDef command, but rather 4 out of 5 times.

I won't share the full error stack, since it's 1500+ lines long, but it goes somewhat like this:

```
|| fatal error: unexpected signal during runtime execution
|| 	/usr/local/go/src/runtime/panic.go:547 +0x90
|| 	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
|| 	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
|| 	/usr/local/go/src/runtime/mheap.go:492 +0x314
|| 	/usr/local/go/src/runtime/mheap.go:502 +0x41
|| 	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
|| 	/usr/local/go/src/runtime/mheap.go:503 +0x63
|| 	/usr/local/go/src/runtime/mcentral.go:209 +0x93
|| 	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
|| 	/usr/local/go/src/runtime/mcache.go:119 +0xcc
|| 	/usr/local/go/src/runtime/malloc.go:642 +0x2b
|| 	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
|| 	/usr/local/go/src/runtime/proc.go:1051
|| 	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82e6e8bd8 sp=0xc82e6e8bd0
|| 	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc82e6e8cb0 sp=0xc82e6e8bd8
|| 	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc82e6e8cf0 sp=0xc82e6e8cb0
|| 	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc82e6e8d40 sp=0xc82e6e8cf0
|| 	/usr/local/go/src/go/build/read.go:201 +0x1d6 fp=0xc82e6e8e80 sp=0xc82e6e8d40
|| 	/usr/local/go/src/go/build/build.go:1068 +0x864 fp=0xc82e6e8fd0 sp=0xc82e6e8e80
|| 	/usr/local/go/src/go/build/build.go:708 +0x1f3d fp=0xc82e6e9b30 sp=0xc82e6e8fd0
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:836 +0x37c fp=0xc82e6e9c08 sp=0xc82e6e9b30
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:862 +0x130 fp=0xc82e6e9db0 sp=0xc82e6e9c08
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:1000 +0x100 fp=0xc82e6e9e70 sp=0xc82e6e9db0
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:975 +0x1d0 fp=0xc82e6e9f48 sp=0xc82e6e9e70
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:956 +0x2b fp=0xc82e6e9f68 sp=0xc82e6e9f48
...
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/util.go:45 +0x4a
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/util.go:65 +0x41f
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:835 +0x30a
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:862 +0x130
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:1000 +0x100
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:975 +0x1d0
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:956 +0x2b
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/loader.go:958 +0x1d4
|| 	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
|| 	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:903 +0xa8
|| 	/usr/local/go/src/os/file_unix.go:97 +0x132
|| 	/usr/local/go/src/os/file.go:244 +0x48
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/util.go:55 +0x37f
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/util.go:65 +0x41f
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/util.go:45 +0x4a
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/util.go:65 +0x41f
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/util.go:45 +0x4a
|| 	/Users/sebiwi/stuff/go/src/golang.org/x/tools/go/loader/util.go:65 +0x41f

```

### Steps to reproduce:

1. git clone kubernetes (this needs to be done on the GOPATH of your computer, under the k8s.io namespace)
2. cd kubernetes
3. vim pkg/kubectl/cmd/create.go
4. Go to line 142, launch :GoDef on the Do() function
5. That should do it

<img width="1440" alt="screen shot 2017-10-08 at 18 15 51" src="https://user-images.githubusercontent.com/1782142/31318550-bf9bb910-ac54-11e7-8def-551ba5105004.png">

### Configuration

* MacOS Sierra 10.12.3 (16D32)
* vim version: 8.0.311
* vim-go version:
* go version: go1.9 darwin/amd64

vimrc:

```
" Disable vi compatibility
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'for': 'go' }
call plug#end()            " required
```

**Comment by bhcleek** [comment]
I've tried duplicating this mean times, but haven't seen the error you're describing. Which version of `godef` do you have installed?

**Comment by sebiwi** [comment]
I don't really know, I don't see any means of getting the godef version?

I still deleted it and reinstalled it, which I suppose means that I have the latest version. The problem is still there.

Is there any other information I can provide you with?

**Comment by Carpetsmoker** [comment]
This looks like a bug in either [`godef`](https://github.com/rogpeppe/godef) or [`guru`](https://github.com/golang/tools/tree/master/cmd/guru), and not vim-go (it's not clear to me which one you're using, but `guru` is the default).  
All vim-go does is call the `guru` or `godef` binary, and most of the code sits here. I'm not sure if there's anything we can do here, and I recommend you open a bug in one of those repos.

If you add a `echom command` in [`autoload/go/def.vim`](https://github.com/fatih/vim-go/blob/master/autoload/go/def.vim#L30) you can see which command is being run (use `:messages` to see it). You can try running that directly from the shell, for example:

It should also be useful for reporting the bug.

**Comment by fatih** [comment]
Yeap this is a tool error. Nothing we can do. 

@sebiwi best way to reproduce is to use `guru` or `godef` from your terminal and then open an issue.  

For `guru` open the issue here: https://github.com/golang/go with title prefix: `x/toold/cmd/guru: panics for ...`
For `godef` open the issue here: https://github.com/rogpeppe/godef


You can explicity set the godef mode in your vimrc to see which tool panics via:

```
let g:go_def_mode = "guru"

or

let g:go_def_mode = "godef"
```

Thanks

**Comment by sebiwi** [comment]
You were right, this doesn't happen when I set `let g:go_def_mode = "godef"`, so I think it
is a guru related issue. 

I'll open an issue on that repo instead. I can't seem to recover the command that was executed
through vim-go though. I tried adding an `echom command` in autoload/go/guru.vim, but I don't
see anything on the :messages buffer. Any help on that?

Thank you all for your help!

**Comment by Carpetsmoker** [comment]
That's the synchronous version for older Vims without async; you probably want to `echom` `result` [from here](https://github.com/fatih/vim-go/blob/master/autoload/go/guru.vim#L105).

**Comment by sebiwi** [comment]
I tried adding an `echom command` there, to no avail. I also added one [here](https://github.com/fatih/vim-go/blob/master/autoload/go/guru.vim#L140), which seems to be the async function for guru, and that didn't work either.

This makes me think that the actual error is produced somewhere else, even before that function is called.
