### ISSUE TITLE
GoTestFunc + tmux (how to run in a different panel)

### ISSUE THREAD

**Issue by nbari** [fatih/vim-go#1506]
### Behavior

How to customize `GoTestFunc` to run in a different tmux panel 

Normally I open `tmux` and split the window into two panels, therefore would like to take advantage of the `GoTestFunc` to run the command on the right pannel so that I could avoid switching between panels and run frequently something like: 

    go test -run TestName -v 

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: 8.0.1175 
* vim-go version: 1.15
* go version: go1.9.1 darwin/amd64

**Comment by bhcleek** [comment]
vim-go does not natively integrate with tmux. 

I'd recommend that you setup a mapping that will call a function. That function should build up a string and send it to `system()`. The string you want to build up is something like 
`"tmux split-window -h vim +[" . line(.) . "] +GoTestFunc " . expand("%:p")`

**Comment by nbari** [comment]
Hi @bhcleek Thanks, just one question, any idea about how to get only the function name so that I could later customize more my function?

**Comment by nbari** [comment]
I came up with this:

```
function TestGo()
    let test = search('func \(Test\|Example\)', "bcnW")

    if test == 0
        echo "vim-go: [test] no test found immediate to cursor"
        return
    end

    let line = getline(test)
    let name = split(split(line, " ")[1], "(")[0]
    let panels=system("tmux list-panes | wc -l | xargs echo -n")
    if panels == 1
        call system("tmux split-window -h -l 75")
    end
    let command = "tmux send-keys -t 1 \"go test -run " . name . " -v\" C-m"
    " :echo join(command)
    call system(command)
endfunction
nnoremap <leader>t :call TestGo()<CR>
```
