### ISSUE TITLE
add snippets for SliceTricks

### ISSUE THREAD

**Issue by tmc** [fatih/vim-go#1514]
It would be nice to have shortcuts for https://github.com/golang/go/wiki/SliceTricks

**Comment by bhcleek** [comment]
Great idea@smc. Do you have any snippets that you'd like to contribute?

**Comment by fatih** [comment]
We already have `ap` and `ap=` Which ones do you think is worth adding @tmc ?

**Comment by Carpetsmoker** [comment]
I'll close this due to lack of feedback. Feel free to open a PR which add snippets.
