### ISSUE TITLE
When ensuring if a test compiles, `TestMain()` and any `init()` functions are executed

### ISSUE THREAD

**Issue by apoydence** [fatih/vim-go#1515]
When using `go#test#Test` to test if a test file compiles, it runs the test setup. This looks deliberate from the given [commit](https://github.com/fatih/vim-go/commit/21376e689d6b701b4367cf121da4cfcf17e5fa19)

If the tests are intended to run with some form of configuration, then the developer can not use the function with their tests.

cc @enocom

**Comment by bhcleek** [comment]
@apoydence Do you have a minimal reproducible case?

**Comment by apoydence** [comment]
We have something here: https://github.com/cloudfoundry-incubator/loggregator-bench-release/blob/dccef944a73a7cfd268879d9e768e8d57a7a1dfd/src/code.cloudfoundry.org/loggregator-bench/doppler/init_test.go
