### ISSUE TITLE
Add new command :GoPlay which will send file to Go Playground

### ISSUE THREAD

**Issue by plutov** [fatih/vim-go#1517]
### What did you do?

https://play.golang.org/ is the best tool to share your Go code. It will be nice to have easy way to send file there.

### What did you expect to happen?

Type
```
:GoPlay
```

It will send file to playground and link will be copied to clipboard.

### What happened instead?

We need to make a lot of clicks and copy/paste.

### Configuration

We can install https://github.com/plutov/playgo during vim-go setup.

**Comment by Carpetsmoker** [comment]
`:GoPlay` is already a command in vim-go? What does the `playgo` command add to that?

**Comment by plutov** [comment]
It can be a new command, it will send file's content to play.golang.org and copy shareable link to clipboard.

**Comment by Carpetsmoker** [comment]
Isn't that what `:GoPlay` already does?

**Comment by plutov** [comment]
Awesome, closing!
