### ISSUE TITLE
Metalinter vs. GoVet

### ISSUE THREAD

**Issue by benknoble** [fatih/vim-go#1530]
### What did you do? (required. The issue will be **closed** when not provided.)

1. Call `:GoMetaLinter` inside a go file
1. Call `:GoVet` inside the same go file

Please provide a recipe to replicate your problem with a minimal `vimrc` with all plugins other than vim-go disabled.

### What did you expect to happen?

1. `vet`, `golint`, and `errcheck` to be run
2. `vet` to be run again

### What happened instead?

1. `golint` offers suggestions, `errcheck` appears not to produce any errors, and the bottom of the quickfix window says: `|| WARING: exec: "govet": executable file not found in $PATH`
2. `[vet] PASS`

Best guess is it meant to run `go vet`, two words, and somehow they got smashed together.

### Configuration

* vim version (major, minor, and included patches from `:version`):
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  5 2017 19:20:19)
MacOS X (unix) version
Included patches: 1-1175
Compiled by Homebrew
```
* vim-go version: 1.15 according to changelog
* go version (`go version`): 1.9.1 darwin
* operating system: Mac OS X
* `vimrc` you used to reproduce:

I couldn't get a *full* reproduce, as a minimal project gave me the following results instead:

1. MetaLinter had errors
2. `[vet] FAIL`

vimrc:
```vim
set nocompatible
filetype indent plugin on
syntax on
set rtp+=~/.vim/bundle/vim-go
```

**Comment by fatih** [comment]
Somehow `gometalinter` decided to run `govet` instead of `go vet`. Both are different tools. If you do `gometalinter --install` from your terminal it'll fix it. I think we should add now `govet` to `:GoInstallBinaries`. This is the third time people asked this to me.

**Comment by fatih** [comment]
From commit https://github.com/alecthomas/gometalinter/pull/375/commits/eb5786adba5507a65ecb01da6ae4fac3231c519a PR: https://github.com/alecthomas/gometalinter/pull/375

<img width="1373" alt="screen shot 2017-10-20 at 10 47 41 pm" src="https://user-images.githubusercontent.com/438920/31839183-b6a28544-b5e8-11e7-81c5-a671bd435154.png">

**Comment by fatih** [comment]
Seems like they even forked `go tool vet` to add some functionality.

**Comment by benknoble** [comment]
Adding it to binaries is probably a good idea, since it won't cause unexpected failures like above. Thanks for the quick reply!

**Comment by Carpetsmoker** [comment]
We could maybe also run `gometalinter --install` with `:Go{Install,Update}Binaries` ?

**Comment by Carpetsmoker** [comment]
See: #1555
