### ISSUE TITLE
Can't exclude packages from guru scope

### ISSUE THREAD

**Issue by skogar42** [fatih/vim-go#1532]
### What did you do? (required. The issue will be **closed** when not provided.)
My project layout is as follows:
github.com/user/pkg
github.com/user/vendor

I have one vendored package that guru cannot parse, and I cannot seem to exclude it.  This is my current guru scope:
```
vim-go: current guru scope: github.com/user/pkg/...,-github.com/user/vendor/...,-github.com/user/vendor/golang.org/x/net/http2
```

When I run :GoCallers, I get:
```
vim-go: analysing with scope github.com/user/pkg/...,-github.com/user/vendor/...,-github.com/user/vendor/golang.org/x/net/http2, (see '
:help go-guru-scope' if this doesn't work)...

/workspace/go/src/github.com/user/vendor/golang.org/x/net/http2/go19.go invalid operation: s (variable of type *net/http.Server) has no field or method RegisterOnShutdown 
guru: couldn't load packages due to errors: github.com/user/vendor/golang.org/x/net/http2
```
### What did you expect to happen?
Excluded packages should be ignored

### What happened instead?
guru still seems to try to load excluded packages

### Configuration

* vim version (major, minor, and included patches from `:version`): 8.0
* vim-go version: 1.15
* go version (`go version`): 1.8.3
* operating system: Linux
* `vimrc` you used to reproduce:
```
let g:go_guru_scope = ["github.com/user/pkg/...", "-github.com/user/vendor/...", "-github.com/user/vendor/golang.org/x/net/http2"]
```

**Comment by Carpetsmoker** [comment]
As far as I can see the `guru` tool doesn't have a feature to "exclude" packages.

The problem seems to be that you're using Go 1.8 with code that only works with Go 1.9, so either use a Go 1.8-compatible version, or upgrade to Go 1.9.
