### ISSUE TITLE
Can vim-go use multiple formatter?

### ISSUE THREAD

**Issue by kyoh86** [fatih/vim-go#1533]
### What did you do? (required. The issue will be **closed** when not provided.)

Vim-go has a option 'g:go_fmt_command' that can take just one command.

(ref: https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim#L8)

So we cannot call multiple commands in onetime.

### What did you expect to happen?

I want vim-go be able to format the file by "gofmt -s -w" and "goimports -w" in sequence.

### Configuration

* vim version (major, minor, and included patches from `:version`): VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 18 2017 13:48:25)
* vim-go version: 1.15
* go version (`go version`): go1.9 darwin/amd64
* operating system: macos Sierra 10.12.6
* `vimrc` you used to reproduce:

**Comment by Carpetsmoker** [comment]
You can add a simple `goimports` wrapper script which calls both; didn't test but something like this should work:

```
#!/bin/sh
set -euC
gofmt -s -w "$f1"
goimports -w "$1"
```

You should also consider writing a patch to the `goimports` tool to support the `-s` flag.

The entire logic surrounding restoration of undo states and such is already very complex, and adding the ability to run two commands would only add to that with very little benefit.

**Comment by kyoh86** [comment]
true.

**Comment by bhcleek** [comment]
Interestingly: https://github.com/golang/go/issues/21476
