### ISSUE TITLE
GoImport broken when adding to empty imports.

### ISSUE THREAD

**Issue by icholy** [fatih/vim-go#1534]
### What did you do?

``` go
package main

import ()
```

Execute: `:GoImport time`

### What did you expect to happen?

``` go
package main

import (
	"time"
)
```

### What happened instead?

``` go
package main

import ()
	"time"
```

### Configuration

* vim version: 8.0 Included patches: 1-1207
* vim-go version: 0878992106b60210722d202164e8ba8bf710e5d2 (HEAD)
* go version (`go version`): 1.9
* operating system: Ubuntu 16.04
* `vimrc` you used to reproduce:

``` vim
set nocompatible

" Plugins
call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go'

call plug#end()
```

**Comment by bhcleek** [comment]
Thank you for taking the time to report this. It looks to be a bug in goimports, though.

**Comment by icholy** [comment]
@bhcleek `:GoImport` doesn't use `goimports`

**Comment by bhcleek** [comment]
You're right, of course.

**Comment by fatih** [comment]
This is a very rare use case in my opinion. Not sure why one would want to write an empty import statement and then later import something? Or do I miss something here? 

I know it's not related, but tools like `goimports` even don't allow to save it in this format, they remove the empty `import ()` statement automatically.

**Comment by fatih** [comment]
This if fixed now in master, will be part of the upcoming release.
