### ISSUE TITLE
GoDef doesn't work

### ISSUE THREAD

**Issue by YvesZHI** [fatih/vim-go#1536]
I've installed all things of vim-go.<br>

Things like `:GoBuild`, `:GoRun` work fine except `:GoDef`. For example,

```
// main.go
func main(){
    Test();
}
// test.go
func Test(){
    println("hello world!")
}
```

Now I put the cursor on `Test` of main.go and type `:GoDef`, however, nothing happened whereas I expected that the cursor would jump to the definition of the function `Test` in the file test.go.<br>

When I type `:GoDef` on `Test` in the main.go, I get the error below:<br>

> vim-go: /PathOfProject

**Comment by AcuevasL** [comment]
Is your GOPATH correct?, since gopath auto detection is disabled.
To make sure type :GoPath, and it should be your current working directory.

**Comment by Carpetsmoker** [comment]
I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.

**Comment by maybe2009** [comment]
@YvesZHI Have you checked PATH? $GOPATH/bin should be added to your PATH.

**Comment by leslie-wang** [comment]
I saw the same error at ubuntu 16.04 with latest vim (Vi IMproved 8.1 (2018 May 18, compiled Aug  8 2018 13:08:47)). 

Same .vimrc file. It can work on my mac.

**Comment by leslie-wang** [comment]
If I run `[[`, it shows error `vim-go: could not find 'motion'. Run :GoInstallBinaries to fix it`. So after I run `GoInstallBinaries`, seems like it solves the issue. 
I'm using Vundle to install vim-go, guess it won't run GoInstallBinaries.

**Comment by sethRait** [comment]
I am also experiencing this error under similar circumstances. My GoPath is correct and I am running go version 1.11.5 and Vim 8.

**Comment by muhmah-motahari** [comment]
I have the same problem. When I try `:GoDef` vim show log `vim-go: [definition] SUCCESS`, but nothing happens.
This problem recently happened and until yesterday all worked perfectly.

**Comment by niksaak** [comment]
Hello there! If anyone's been running into this lately, run `:GoUpdateBinaries` and that should fix it.
