### ISSUE TITLE
Go*Vertical

### ISSUE THREAD

**Issue by webermaster** [fatih/vim-go#1539]
#Go*Vertical

As far as I have observed, Any command that open a vertical split open the new window to the right of the current window.

Two good examples are `:GoAlternateVertical` and `:GoDocVertical`.

Could these be configurable:

`let g:go_doc_vertical_open_to = 'right|left'`
`let g:go_alternate_vertical_open_to = 'right|left'`

**Comment by bhcleek** [comment]
Does manipulating ['splitright'](http://vimdoc.sourceforge.net/htmldoc/options.html#'splitright' ) give you the result you're looking for?

**Comment by Carpetsmoker** [comment]
This should work: `:call go#doc#Open('leftabove new', 'vsplit')`.

We can maybe add options for those parameters; I personally configured it make the window go at the bottom (rather than the top) for example.

Would not be in favour of adding new commands for it though.

**Comment by webermaster** [comment]
`splitright` definitely works for now.  I could definitely forsee a need for someone else to need to configure the split direction in their vimrc.  I'm with @Carpetsmoker that there doesn't need to be new commands, but configuration would be nice.  I have to admit, I did not know `splitright` existed until it was mentioned in this issue.  So I'm gonna rely on that for now.

**Comment by fatih** [comment]
Do we need a setting if this can be already configured? Let's add a section to FAQ and it's done.  We have already tons of features and more coming in the upcoming years. We should not add settings unless those are really needed or are part of vim-go itself. Seems like this can be solved in two ways already.

**Comment by bhcleek** [comment]
SGTM @fatih

**Comment by Carpetsmoker** [comment]
The problem is that it's a global setting, and will affect much more.

**Comment by fatih** [comment]
> The problem is that it's a global setting, and will affect much more.

True, but it's also a highly personal setting. Someone who wants it to be on the right side, wants probably anything to be on the right.

**Comment by Carpetsmoker** [comment]
> > The problem is that it's a global setting, and will affect much more.

> True, but it's also a highly personal setting. Someone who wants it to be on the right side, wants probably anything to be on the right.

Yes, exactly, which is also why an option makes sense here IMHO.

It's just a matter of changing this:

     go#doc#Open('new', 'split', <f-args>)

to:

    go#doc#Open(get(g:, 'go_doc_whatever, 'new'), get(g:, 'go_doc_whatever, 'split'), <f-args>)

And then everyone can change it to whatever they want.

**Comment by bhcleek** [comment]
I tend to agree with @fatih on this.

Another point to consider is that if someone wants they are free to define their own command to do it, even to the point of overriding the default command configuration.

**Comment by GetCurious** [comment]
i'm new to this, i'd like :GoRun to be on the right. where do i paste what?

**Comment by bhcleek** [comment]
@GetCurious you can set the the `'splitright'` option. See `:help splitright`.

**Comment by GetCurious** [comment]
`:help splitright`

```
                         'splitright' 'spr' 'nosplitright' 'nospr'
   1 'splitright' 'spr'      boolean (default off)
   2                         global
   3         When on, splitting a window will put the new window right of the   
   4         current one. :vsplit

```
how do i set this?

**Comment by bhcleek** [comment]
@GetCurious you can set it in your vimrc file.

It sounds like you're pretty new to both Go and to vim (and hence new to vim-go, too). vim-go's issues isn't the right place to ask for help for basic Vim usage and configuration. There are a number of places that you can get help about Vim generally. You'll have better luck in the vim_user list with general Vim questions: https://groups.google.com/forum/#!forum/vim_use. You might also want to checkout the `vimtutor` (just run it from the command line) or vim's help (see vim's `:help` command).

And commenting on or asking for help in closed issues isn't the best way to get a resolution, because they by definition the issues are considered resolved and are not usually monitored.
