### ISSUE TITLE
Can't get GoDoc to work

### ISSUE THREAD

**Issue by Integralist** [fatih/vim-go#1541]
### What did you do? (required. The issue will be **closed** when not provided.)

I've tried both `:GoDoc` with the cursor over a specific identifier (e.g. `Println`) and I've also tried it with a word like `:GoDoc Println`).

### What did you expect to happen?

I expected to see documentation listed in a preview/quickfix/location window.

### What happened instead?

I got an error.

With `:GoDoc` when cursor over `Println`:

```
vim-go: gogetdoc: couldn't get package for /Users/markmcdonnell/code/go/profiling/main.go: can't find package containing /Users/markmcdonnell/code/go/profiling/main.go
```

With `:GoDoc Println`:

> Note: I've also tried full package `:GoDoc fmt.Println`

```
2017/10/29 08:59:38 cannot find package "." in:                                                               
   /src/Println
```

### Configuration

* vim version (major, minor, and included patches from `:version`): 8.0
* vim-go version: commit = `0878992`
* go version (`go version`): go1.9.2 darwin/amd64
* operating system: macOS
* `vimrc` you used to reproduce: https://github.com/Integralist/dotfiles/blob/master/.vimrc

**Comment by Carpetsmoker** [comment]
Is that inside GOPATH?

**Comment by Carpetsmoker** [comment]
I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.
