### ISSUE TITLE
:GoImpl completion seems to break after an error

### ISSUE THREAD

**Issue by Carpetsmoker** [fatih/vim-go#1554]
:GoImpl <Tab>
    [completes as expected]
    :GoImpl asd
    vim-go: unrecognized interface: asd
    :GoImpl <Tab>
    [nothing happens]
    :w
    :GoImpl <Tab>
    [completes as expected]

(While editing `middleware/auditMiddleware/audit_test.go`; I'll investigate later).

**Comment by deltaskelta** [comment]
This is my first time trying to user `:GoImpl` but I cannot get it to work with anything. if I call it with the args `:GoImpl 'f *Foo' io.Reader` I get this error...

```
vim-go: impl <recv> <iface>
vim-go:
vim-go: impl generates method stubs for recv to implement iface.
vim-go:
vim-go: Examples:
vim-go:
vim-go: impl 'f *File' io.Reader
vim-go: impl Murmur hash.Hash
vim-go:
vim-go: Don't forget the single quotes around the receiver type
vim-go: to prevent shell globbing.
```

if I call it and hit `enter` and type in `io.Reader` at the prompt I get the same error

**Comment by Carpetsmoker** [comment]
You shouldn't add quotes @deltaskelta; this should work:

    :GoImpl f *Foo io.Reader

The quotes are in the help because `guru` assumes you're sunning it from a shell, in which case you need it to prevent shell escaping.

It's unrelated to this issue, but we should perhaps consider removing quotes for easier usage.

**Comment by deltaskelta** [comment]
actually I still get the error when I do that which is what led me to put the quotes there in the first place. I can open an issue if you think this is still unrelated though...I am not too familiar with the internals of how its being called

**Comment by Carpetsmoker** [comment]
Yes please @deltaskelta; then we also have all information about your Vim version etc.

The command as such works fine for me, it's just the tab-completion that occasionally breaks for me.
