### ISSUE TITLE
vim-go not working with vundle

### ISSUE THREAD

**Issue by mickethespike** [fatih/vim-go#1566]
### What did you do? (required. The issue will be **closed** when not provided.)
I recently switched from Pathogen to Vundle and I tried to install vim-go by adding a `Plugin 'fatih/vim-go'` to my vimrc. When I ran `:PluginInstall` I got no issues but when I try commands it doesn't work? It worked before when I was using Pathogen so I don't know what happened. All other plugins work fine.

### What did you expect to happen?
I thought it would work

### What happened instead?
It didn't

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
7.4 1-1938
* Go version (`go version`):
`go version go1.4.2 gccgo (GCC) 5.3.0 linux/amd64`
* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fish/src/go"
GORACE=""
GOROOT="/usr/lib64/go1.8.3/go"
GOTOOLDIR="/usr/libexec/gcc/x86_64-slackware-linux/5.3.0"
CC="/usr/bin/gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="/usr/bin/g++"
CGO_ENABLED="1"
```
* vim-go version:

The current one

* `vimrc`
```
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'

filetype plugin indent on
syntax on
set exrc
set secure
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab
set backspace=2 " make backspace work
"set cursorline
set visualbell
set confirm
"set ruler
set number
""highlight ColorColumn ctermbg=black
set wildmenu
set ignorecase
set nowb
set noswapfile
set smarttab
set cmdheight=2
set enc=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf8,prc
set lazyredraw
set magic
set nobackup       "no backup files
set nowritebackup  "only in case you don't want a backup file while editing
set noswapfile     "no swap files
set noundofile
```
There is a lot more but I shouldn't link that much so this is what ill give

**Comment by Carpetsmoker** [comment]
Shouldn't there be a `call vundle#end()` somewhere? That's what [the example on the website](https://github.com/VundleVim/Vundle.vim#quick-start) has, anyway.

**Comment by mickethespike** [comment]
Right! It works now, thanks a lot!
