### ISSUE TITLE
GoFreeVars miss parameters

### ISSUE THREAD

**Issue by iselind** [fatih/vim-go#1567]
### What did you do? (required. The issue will be **closed** when not provided.)
I visually select the if statment block of this function
```go
func TestBlaha(t *testing.T) {
        bar := Bar()
        if bar != "bar" {
                t.Errorf("Expecting bar, got %s", bar)
        }
}
```
and execute :GoFreeVars.

### What did you expect to happen?
What i get back should be that both `bar` and `t` are free variables.

### What happened instead?
What i get back is only that bar is a free variable, not t. If i was to extract the if block to another function i would require t as well, hence :GoFreeVars should have listed it.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Including patches: 1-1689
```
* Go version (`go version`):
```
go version go1.9 linux/amd64
```
* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/irina/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build973418672=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
* vim-go version:
`v1.15`
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
set expandtab

set ai si

set background=dark

execute pathogen#infect()

syntax on
filetype plugin indent on

map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

autocmd FileType go nmap <leader>b  <Plug>(go-build)
autocmd FileType go nmap <leader>r  <Plug>(go-run)

let g:go_list_type = "quickfix"
let g:go_fmt_command = "goimports"
```

**Comment by fatih** [comment]
Hi @iselind 

I don't see any problems with this issue. GoFreeVars will return identifiers that a references but not defined in the given selection. If you select inside the function and call it, all you get is `t` itself. `Bar()` is defined outside the function. Checkout the doc for guru for more details: https://docs.google.com/document/d/1_Y9xCEMj5S-7rv2ooHpZNH15JgRT5iM742gJkw5LtmQ/edit#heading=h.doa5wqsaooky vim-go just calls it, so on our side everything is fine, you have to open an issue to guru itself if you're not satisfied with the output and thing it's wrong. Thanks
