### ISSUE TITLE
:GoImpl gives error when called with example

### ISSUE THREAD

**Issue by deltaskelta** [fatih/vim-go#1568]
### What did you do? (required. The issue will be **closed** when not provided.)

`:GoImpl f *Foo io.Reader`

### What did you expect to happen?

the implementation of the interface would be inserted into the buffer

### What happened instead?

error printed to statusline
```
vim-go: impl <recv> <iface>
vim-go:
vim-go: impl generates method stubs for recv to implement iface.
vim-go:
vim-go: Examples:
vim-go:
vim-go: impl 'f *File' io.Reader
vim-go: impl Murmur hash.Hash
vim-go:
vim-go: Don't forget the single quotes around the receiver type
vim-go: to prevent shell globbing.
```

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
```
NVIM v0.2.0
Build type: Release
```
* Go version (`go version`):
```
go version go1.9.2 darwin/amd64
```
* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Jeff/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5q/6lv7fh7x0bv57t8m09n8j0xm0000gn/T/go-build210106567=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
* vim-go version:

commit c0d209c

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin('~/.config/nvim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

**Comment by Carpetsmoker** [comment]
Seems to work well for me in Neovim no matter what I try :-/

Maybe try running `:GoUpdateBinaries` to make sure you have the latest version of `impl`?

**Comment by deltaskelta** [comment]
The update worked, thanks!
