### ISSUE TITLE
gotags: command not found

### ISSUE THREAD

**Issue by glacjay** [fatih/vim-go#157]
But gotags is installed automatically by vim-go.

**Comment by heipacker** [comment]
i solve this problem set go:go_gotags_bin manually in my own .vimrc. likes below:
161 let g:go_gotags_bin = '/home/fupan/golib/bin/gotags'
162 let ctagsbin = 'gotags'
163 " check if vim-go is available and has the binary
164 if !executable('gotags') && !exists("g:go_gotags_bin")
165      let ctagsbin = expand(g:go_gotags_bin),
166 endif
167 let g:tagbar_type_go = {
168         \'ctagstype' : 'go',
169         \'kinds'     : ['p:package','i:imports:1','c:constants','v:variables','t:types','n:interfaces',
170                 \'w:fields','e:embedded','m:methods','r:constructor','f:functions'
171         \],
172         \'sro' : '.',
173         \'kind2scope' : {'t' : 'ctype','n' : 'ntype'},
174         \'scope2kind' : {'ctype' : 't','ntype' : 'n'},
175         \'ctagsbin'  : expand(g:go_gotags_bin),
176         \'ctagsargs' : '-sort -silent'
177 \}

**Comment by heipacker** [comment]
but i should do the same work for other command like GoDef
