### ISSUE TITLE
GoMetaLinter can't find available tools

### ISSUE THREAD

**Issue by Integralist** [fatih/vim-go#1570]
### What did you do? (required. The issue will be **closed** when not provided.)

I executed `:GoMetaLinter`

### What did you expect to happen?

For all linters defined in `g:go_metalinter_enabled` (see below) that were installed by `gometalinter --install` to be executed.

### What happened instead?

A message telling me certain linters were invalid.

For example, `gometalinter: error: invalid linter: "maligned"`

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 28 2017 13:23:55)                                                                                                          
MacOS X (unix) version
```

* Go version (`go version`):

```
go version go1.9.2 darwin/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/markmcdonnell/code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3m/3pnsckx15wgdv5cpynbtz4b40000gn/T/go-build898772173=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version:

I think it's `1.15` (by looking at CHANGELOG.md).

If I use `:PlugSnapshot` I see:

```
let g:plugs['vim-go'].commit = 'c0d209c'
```

Which is the latest commit hash for "Nov 6, 2017" (as of now, which is Mon 13th Nov).

Ps, is there any easier way to tell what version of a plugin I'm using?

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

Following `:GoInstallBinaries` and then from the shell `gometalinter --install` and verifying it works from the shell using `gometalinter --deadline 20s`

```viml
let g:go_fmt_command = 'goimports'
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck', 'deadcode', 'structcheck', 'maligned', 'megacheck', 'dupl', 'interfacer', 'goconst']
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck', 'deadcode', 'structcheck', 'maligned', 'megacheck', 'dupl', 'interfacer', 'goconst']
let g:go_metalinter_deadline = '20s'
```

**Comment by bhcleek** [comment]
Thank you for reporting.

We already have a few issues and pull requests to address this need, so I'm closing this since it effectively duplicates others. #1555 is a good place to get started to follow the work being done.
