### ISSUE TITLE
Hello (:

### ISSUE THREAD

**Issue by brunohenrique** [fatih/vim-go#1572]
Hi, @fatih. 
I want to apologize beforehand because I don't know if it's the right place to do this, but I'll take my chances.

Today I had a problem with vim-go. After some search for issues and related reports I couldn't find anything, so I decided to open one. But at the moment that I was with the issue's form open, I realized that I never thanked you, the other maintainers and contributors for the fantastic work that you did.

It's crazy to think that I use vim-go for almost two years and in the last ~729 days, it made my work exponentially easier and enjoyable.

So here I am to say thanks for your great work ❤️ 

btw, the problem was between the computer and the chair.

**Comment by nathanleclaire** [comment]
![image](https://user-images.githubusercontent.com/1476820/32856639-31dbdb1e-c9fa-11e7-8071-9efed87420c8.png)

**Comment by mgaffney** [comment]
+1. Thanks, @fatih!

**Comment by faraazkhan** [comment]
+1. Thank you for doing this. @fatih

**Comment by mccurdyc** [comment]
+1. @fatih admittedly, how much I enjoy writing in a language often depends on how well supported said language is in vim. I can say that I am extremely happy writing Go! Thank you!

**Comment by pierreprinetti** [comment]
Thank you Fatih :)

**Comment by motyar** [comment]
Thanks a lot 👍

**Comment by fatih** [comment]
Thank you all. This all made my day. Number one reason why I started vim-go, to make people happy when they use it. 

Don't forget to thank to all contributors: https://github.com/fatih/vim-go/graphs/contributors and also to @Carpetsmoker and @bhcleek as our latest collaborators. Let me also thank all you folks.
 
I'm very strict about issues so I'll close this, but feel free to comment whenever you feel :)

**Comment by vigo** [comment]
Although I'm neither a Vim user nor Go developer, Thank you for your great contributions to open source world! You rule PANZER!

**Comment by ShawnMilo** [comment]
As someone who agrees with the love expressed in this thread and with no personal affiliation with Fatih, may I remind everyone that this exists: https://www.patreon.com/fatih
