### ISSUE TITLE
Use Vim 8 features for updating the quickfix list without replacing quickfix lists from other plugins

### ISSUE THREAD

**Issue by yegappan** [fatih/vim-go#1574]
When vim-go plugin is updating a quickifx list asynchronously, some other
Vim plugin or user can create/modify the quickfix list resulting in vim-go
plugin updating the incorrect quickfix list. This can be avoided by using
the new features in Vim8. This issue with the vim-go and vim-ale plugins
is discussed at
https://www.reddit.com/r/vim/comments/7c5f1a/two_plugins_writing_to_quickfixloc_list_at_the/

Refer to the following thread for the steps to do this:
https://groups.google.com/forum/#!topic/vim_use/LTWNG0nRQCc

**Comment by Carpetsmoker** [comment]
I think this is the same as #1571 ?

**Comment by Carpetsmoker** [comment]
I'll close this on the assumption that it's the same issue as above, but please comment if it's not and I'll reopen it.
