### ISSUE TITLE
guru no identifiers here error

### ISSUE THREAD

**Issue by NikosEfthias** [fatih/vim-go#1590]
### What did you do? (required. The issue will be **closed** when not provided.)
opened a new buffer with a go file in `$GOPATH`

### What did you expect to happen?
open with no errors

### What happened instead?
got error message saying `guru:no identifiers here`

### Configuration (**MUST** fill this out):
I dont change anything in the original configuration of vim-go
* Vim version (first two lines from `:version`):
```vim
NVIM v0.2.0
Build type: Release
```
* Go version (`go version`):
`go version go1.9.1 darwin/amd64`
* Go environment (`go env`):
```bash
GOARCH="amd64"
GOBIN="/Users/nikos/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nikos/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bb/gch_ghjx6qs37zkj9drl895h0000gp/T/go-build269493977=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
* vim-go version:
![](https://i.imgur.com/ykFlJyz.png)
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```vim 
au!
"vim plug init
call plug#begin('~/plugged')
Plug 'keith/investigate.vim'
Plug 'w0rp/ale'
Plug 'altercation/vim-colors-solarized'
Plug 'noahfrederick/vim-hemisu'
Plug 'scrooloose/nerdcommenter'
Plug 'Raimondi/delimitMate'
Plug 'stephpy/vim-yaml'
Plug 'marcweber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'jwalton512/vim-blade'
Plug 'scrooloose/nerdtree'
Plug 'gregsexton/MatchTag'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-go'
Plug 'pangloss/vim-javascript'
Plug 'terryma/vim-multiple-cursors'
Plug 'fatih/vim-go'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'airblade/vim-gitgutter'
Plug 'zchee/deoplete-go'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'wakatime/vim-wakatime'
Plug 'bling/vim-airline'
call plug#end()
"settings
syntax on
set t_Co=256 
colorscheme solarized
"sets
set ignorecase
set background=dark
set linebreak
set wrap
set foldmethod=indent
set foldlevel=0
set nofoldenable
set tabstop=4
set noexpandtab
set shiftwidth=4
set list
set listchars=tab:▸\ ,eol:¬  
set nohlsearch
set wildmenu
set wildmode=longest,list
set wildignore=*node_modules/*,*/vendor/*
set wildignorecase
set nowrap
set spell
set splitbelow
set splitright
set path=.,/usr/include,,**
set nu
set smartindent
set backspace=2
set splitright
set mouse=a
set statusline+=%#warningmsg#
set statusline+=%*
set statusline=%{LinterStatus()}
let g:ale_fixers = {
			\   'javascript': ['eslint'],
			\}
let g:ale_linters = {
			\   'javascript': ['eslint'],
			\   'go':['gometalinter','go build'],
			\}
let g:ale_set_highlights= 1
let g:airline#extensions#ale#enabled = 1
let g:ale_fix_on_save = 1
let g:ale_completion_enabled = 1
let g:ale_sign_column_always = 1
let NERDTreeWinSize = 30
"maps
noremap <C-t><C-t> <esc>:e %<cr>
nnoremap <Del> "_x
noremap <C-w>r <esc>:so $MYVIMRC<cr>
noremap <C-w><C-s> <esc>:tabnew $MYVIMRC<cr>
noremap <Leader>1 ^
noremap <Leader>2 $
noremap <Leader>n :NERDTreeToggle<CR>
noremap <Leader>l :set list!<cr>
noremap <Leader>p <C-p>
noremap <C-b> :CtrlPBuffer<cr>
noremap <Leader><Leader> %
if has('nvim')
	noremap <Leader><cr> :vsp\|:term <cr> 
else
noremap <Leader><cr> <ESC>:!tmux a -t vim<cr>
endif
au VimLeavePre * :mksession! ./Session.vim 
au VimEnter * :call LoadSession()
autocmd FileType go nnoremap .. :GoImports<CR>
au FileType go noremap gd <esc>:vsp|:GoDef<cr>
au FileType go noremap <Leader>' <esc> :execute 'GoImport' input('name:')<cr>
"habbit breaking
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
"habbit breaking end
"functions
function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))

    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors

    return l:counts.total == 0 ? 'OK' : printf(
    \   '%dW %dE',
    \   all_non_errors,
    \   all_errors
    \)
endfunction
function! LoadSession()
	if argc()==0
		:silent! source ./Session.vim 
	endif

endfunction
```

**Comment by Carpetsmoker** [comment]
Try running `:GoUpdateBinaries` to update `guru`, maybe you have an old version?

Also please reproduce the problem with a *minimal* vimrc. Your vimrc has a lot of plugins and settings and stuff, any one of them could cause this issue.

Especially that `:silent! source ./Session.vim ` looks pretty suspicious btw.

**Comment by NikosEfthias** [comment]
i just updated the binaries and if i provide a filename after vim it doesnt actually call source the file but my problem still exists without it @Carpetsmoker

**Comment by NikosEfthias** [comment]
I already tried deleting all other packages and the problem still exists

**Comment by Carpetsmoker** [comment]
Could you post the vimrc file that you used to reproduce the issue? For example:

    $ vim -N --no-plugins -U NONE -u minimal-vimrc

There may also be things in your ~/.vim directory, so it may be wise to move that first:

    $ mv ~/.vim ~/vim-backup

**Comment by aletheia7** [comment]
@NikosEfthias https://github.com/nikosEfthias/proxyServer is missing.

**Comment by NikosEfthias** [comment]
its a private repository and it locally exists actually i found the issue but cant understand why this happens

when i add `au FileType go noremap gd <esc> :vsp | :GoDef <cr>` to my config this error happens

**Comment by NikosEfthias** [comment]
@aletheia7 @Carpetsmoker any idea why this happens ?

**Comment by Carpetsmoker** [comment]
`:GoDef <cr>` runs `:GoDef`, so that makes sense.
I think your intention was to use `<Bar>`? See [`:help map-bar`](http://vimhelp.appspot.com/map.txt.html#map-bar).

**Comment by NikosEfthias** [comment]
when i use bar instead of | it just opens the def in the same buffer its not the same behavior as `:vsp|:GoDef` so it actually doesnt solve the problem @Carpetsmoker it simply ignores the first part and runs the part after <Bar>

**Comment by NikosEfthias** [comment]
for some reason using <leader>g instead of gd makes it work just fine

**Comment by Carpetsmoker** [comment]
If your goal is to open GoDef in a new window then there's the `(go-def-vertical)` for that already.

This is what I have in my vimrc to make `gd` open stuff in a new tabs (yes I like tabs and I'm not ashamed of it):

```
let g:go_def_mapping_enabled = 0         " Don't map GoDef related stuff (we do this ourselves later).

augroup my_go_settings
	autocmd!
	" Need to map these defaults because go_def_mapping_enabled is off.
	autocmd FileType go nnoremap <buffer> <silent> <C-]> :GoDef<CR>
autocmd FileType go nnoremap <buffer> <silent> <C-t> :<C-U>call go#def#StackPop(v:count1)<CR>

	" Open gd in a new tab.
	autocmd FileType go nmap gd <Plug>(go-def-tab)
augroup end
```

Replacing `(go-def-tab)` with `(go-def-vertical)` should make it do what you want.

See `:help <topic>` for more detailed explanations for any of the things mentioned above.

**Comment by NikosEfthias** [comment]
i see thanks
