### ISSUE TITLE
go_highlight_functions is not unicode-aware

### ISSUE THREAD

**Issue by Carpetsmoker** [fatih/vim-go#1591]
If I enable `go_highlight_functions=1` then this file:

```
func main() {
    ﻝﻮﺣﺓ()
}

func ﻝﻮﺣﺓ() {
    fmt.Println("X")
}
```

shows as:

![2017-11-29-020120_239x178_scrot](https://user-images.githubusercontent.com/1032692/33354131-34350066-d4a9-11e7-85f6-ebc267edfbe5.png)

The `ﻝﻮﺣﺓ` function should be highlighted as a function, but it is not.

The same may apply to other highlights where unicode is allowed.

**Comment by mocheryl** [comment]
vim-go is using the `\w` regular expression class to match function definitions and some other identifiers. This class supports only regular ASCII characters while Go, as pointed out, supports also those from the Unicode range.

For a proper syntax highlighting, we would need to replace the `\w` class with regular expression ranges for all ~20000 letters Go can use as an (function) identifier and then another set of ranges for same letters plus ~600 numbers.

I could generate a syntax for all these ranges, but I don't know of a sane way of inserting all this data into a vim syntax file. At most I know, we could replace the aforementioned class with something like `\h\w*`. At least this would make the plugin match only valid identifiers.

**Comment by mocheryl** [comment]
vim-go is using the `\w` regular expression class to match function definitions and some other identifiers. This class supports only regular ASCII characters while Go, as pointed out, supports also those from the Unicode range.

For a proper syntax highlighting, we would need to replace the `\w` class with regular expression ranges for all ~20.000 letters Go can use as an (function) identifier and then another set of ranges for same letters plus ~600 numbers.

I could generate a syntax for all these ranges, but I don't know of a sane way of inserting all this data into a vim syntax file. At most I know, we could replace the aforementioned class with something like `\h\w*`. At least this would make the plugin match only valid identifiers.

**Comment by mocheryl** [comment]
vim-go is using the `\w` regular expression class to match function definitions and some other identifiers. This class supports only regular ASCII characters while Go, as pointed out, supports also those from the Unicode range.

For a proper syntax highlighting, we would need to replace the `\w` class with regular expression ranges for all ~20000 letters Go can use as an (function) identifier and then another set of ranges for same letters plus ~600 numbers.

I could generate a syntax for all these ranges, but I don't know of a sane way of inserting all this data into a vim syntax file. At most I know, we could replace the aforementioned class with something like `\h\w*`. At least this would make the plugin match only valid identifiers.

**Comment by Carpetsmoker** [comment]
We need to wait until Vim supports unicode character classes (e.g. `\p{L}`). No sense keeping this issue open, it's a very minor issue with no good fix.
