### ISSUE TITLE
I started to get "Press key" after linting

### ISSUE THREAD

**Issue by korjavin** [fatih/vim-go#1593]
### What did you do? (required. The issue will be **closed** when not provided.)
I edit go file, with metalinter on save enabled, when I save, 
I get "press entrer to continue"

### What did you expect to happen?
It was without key pressing before

### What happened instead?
Waiting for press

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 13 2017 22:38:50)
Заплатки: 1-1144
* Go version (`go version`):
go version go1.9 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/aa/Projects/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build244319486=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
* vim-go version:
current
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
Plugin 'tpope/vim-dispatch'

  let g:go_dispatch_enabled = 1


let g:go_list_type = "locationlist"
let g:go_list_height = 5
let g:go_metalinter_deadline = "150s"
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck','goconst','staticcheck','dupl','deadcode','ineffassign','megacheck','unconvert','misspell','vetshadow']
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
```

**Comment by Carpetsmoker** [comment]
This is usually because there is too much output. See `:help hit-enter`. It can somestimes happen when your window is too small for example (and a message is wrapped).

What is in `:messages`?

**Comment by korjavin** [comment]
There are two lines:
vim-go: linting started ...
vim-go: linting finished

**Comment by korjavin** [comment]
But, I just found that yes. Looks like :messages is accumulating all those  msgs.
When I start vim it's fine, but then when I work more, I am starting to get that behavior and
:messages now larger, like:
vim-go: linting started ...
vim-go: linting finished
vim-go: linting started ...
vim-go: linting finished
many times (and other messages about saving files)

**Comment by Carpetsmoker** [comment]
`:messages` shows the message log, so it "accumulating all those msgs" is normal.

Did you read the help page I linked? Did you try anything from that? There are also many many resources about this if you look it up on the internet. It's a common Vim problem.

We don't have access to your computer or Vim, so it's really hard to debug these sort of issues. This works for many other people, including myself and the other vim-go maintainers (as far as I know, anyway), so it looks like *something* is different on your system, somehow.

This *could* be a bug in vim-go, but as I said it's a common Vim problem that affects many things, so it's *probably* some sort of configuration error, and you're the person in the best position to get to the bottom of what it is, exactly.

**Comment by korjavin** [comment]
Yeah, you are right.
Why I think that it's related to vim-go is because I haven't changed my vimrc for the long time.

The only thing I did before problem is :BundleUpdate , and I update vim-go (and something else, but don't have the log now)

That "press enter" is so annoying that I had to switch off linter in the same day.

I understand that there is not too much usefull info from me, mostly because I don't understand well where to look.

I have my vimfiles shared there (https://github.com/korjavin/vimfiles)  and there have some history of changes.
I see now that dispatch plugin was update as well, and I changed g:go_list_type (but I tried to return it back already)

Just hope if someone more proficient will run into the same issue.

**Comment by Carpetsmoker** [comment]
Other plugins shouldn't matter at all if you can reproduce this while *only* loading vim-go.

> I have my vimfiles shared there (https://github.com/korjavin/vimfiles) and there have some history of changes.

I'm not going to install a massive directory tree of what is basically an untrusted source of code. Sorry :-(

**Comment by korjavin** [comment]
I reduced my vimrc to that:
```
"vundle

filetype off                   " required!
set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()
 
Bundle 'gmarik/vundle'
  
filetype plugin indent on     " required!

  
Bundle 'fatih/vim-go'


  let g:go_highlight_operators = 1
  let g:go_metalinter_autosave = 1

  let g:go_auto_type_info = 0


let g:go_metalinter_excludes = [".*\.pb\.go","_test\.go"]
let g:go_fmt_fail_silently = 1


let g:go_list_type = "locationlist"
"let g:go_list_type = "quickfix"
let g:go_list_height = 5
let g:go_metalinter_deadline = "150s"
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck','goconst','staticcheck','dupl','deadcode','ineffassign','megacheck','unconvert','misspell','vetshadow']
let g:go_metalinter_autosave_enabled = ['vet', 'golint']

let g:go_alternate_mode = "tabedit"

let g:syntastic_auto_jump = 3
```
exactly one plugin
and now I don't have "press any key" after each saving.
Looks like as you mentioned problem not in vim-go, but in some combination.

I'll try to enable plugins one-by-one

**Comment by korjavin** [comment]
I found it, it's Syntastic

Having both 
Syntastic and
Gometalinter
checks cause the problem.
It was not so recently though.

I don't know where exactly the problem is, I'm going just switch off one of them.

If that issue has no value for others it should be closed I believe

**Comment by Carpetsmoker** [comment]
Running both syntastic and vim-go on save isn't really supported; there is also no reason to, since they do exactly the same; so pick one :-)
