### ISSUE TITLE
:GoAlternate splits when alternate is a hidden buffer

### ISSUE THREAD

**Issue by bhcleek** [fatih/vim-go#1594]
### What did you do? (required. The issue will be **closed** when not provided.)
Update to a revision that includes #1585 and then
```
mkdir -p $(go env GOPATH)/src/foo
touch $(go env GOPATH)/src/foo/foo.go
touch $(go env GOPATH)/src/foo/foo_test.go
vim $(go env GOPATH)/src/foo/foo.go
:set hidden
:GoAlternate
:GoAlternate
```

### What did you expect to happen?
foo.go to be loaded into the current window

### What happened instead?
foo.go was opened in a new split

**Comment by Carpetsmoker** [comment]
Fixed with revert for now; will open a new PR later.
