### ISSUE TITLE
Files that are outside of GOPATH and symlinked in do not register in vim-go

### ISSUE THREAD

**Issue by vito-c** [fatih/vim-go#1599]
### What did you do? (required. The issue will be **closed** when not provided.)
create source outside of GOPATH symlink source into GOPATH

### What did you expect to happen?
I expected to be able to jump to a declaration of a nested struct in this file. For example I am in foo/foo.go and I have imported bar that has:
```
type struct Bar {
    Test []*TestThings
}
```
Then in foo I do something like `bar := bar.Bar{}` and then there is a line that has `bar.Test` and I can actually jump to bar.go when I `GoDef` on the `Bar{}` but not when I `GoDef` on the `Test`

### What happened instead?
```
vim-go: guru: directory /Users/vito-c/code/foo-test/src/github.com/vito-c/foo-test/bar is not beneath any of these GOROOT/GOPATH directories: /usr/local/Cellar/go/1.6.2/libexec/src, /Users/vito-c/code/go/src
```
I find it strange that I'm using go 1.9 but vim-go's GOROOT is 1.6 is that expected?

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
NVIM v0.2.0

* Go version (`go version`):
1.9.2

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vitocutten/code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3l/zlscbgpn2qj05x6kvthkfch40000gp/T/go-build884429755=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version:
456186f

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

**Comment by Carpetsmoker** [comment]
The problem is that Vim will disambiguate to the real path on many different levels. Try `:pwd` or `:echo getcwd()` or `:echo expand('%:p')`, etc. They all show the symlink destination (outside GOPATH).

I don't think there is a good way to fix this. The best solution is to use GOPATH.

rsc recently commented that he would like to move to a future where code outside GOPATH works as well as in GOPATH, so hopefully things will be better in 1.11 or beyond.

> I find it strange that I'm using go 1.9 but vim-go's GOROOT is 1.6 is that expected?

Maybe old `guru` compiled with Go 1.6? Try `:GoUpdateBinaries`

**Comment by fatih** [comment]
Symlinks are discouraged to use. Checkout go-nuts (mailing list) for some conversations. I know some people use it, but there is little we can do here. Thanks
