### ISSUE TITLE
Autorun gocode?

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [fatih/vim-go#1612]
### What did you do? (required. The issue will be **closed** when not provided.)
I've installed vim-go through pantheon in vim. However I never got auto completion to actually run by itself.

### What did you expect to happen?
I expected vim to automatically show the gocode auto completion while writing code. So if i'd write fmt.Pri, Then fmt.Println etc, would show up and be selectable. 

### What happened instead?
Currently i can while writing code, press first `<C-x>` and then `<C-o>` to get gocode suggestions. But how can i make it so gocode suggestions always automatically shows up?

Is it intentional to always not be automatically enabled by default?

### Configuration (**MUST** fill this out):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 20:13:43)
Included patches: 1-197, 322, 377-378, 422, 550

go version go1.9.1 linux/amd64

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/simon/Code/go/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build556381399=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
Latest vim-go version from github

```
execute pathogen#infect()
syntax on
filetype plugin indent on

"       Directory Tree Key-bind
map <C-n> :NERDTreeToggle<CR>

"       Enables all highlighting
let g:go_highlight_extra_types = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_arguments = 1
let g:go_highlight_methods = 1
let g:go_highlight_types = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_fields = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1

"       Enable Autoindent
set autoindent

set incsearch
set hlsearch
set noerrorbells
set number
set ignorecase

nnoremap n nzzzv
nnoremap N Nzzzv

autocmd BufEnter * silent! lcd %:p:h
```

**Comment by fatih** [comment]
There is no autocompletion in Vim. There are multiple plugins you can use, such as mucomplete, deoplete, etc.. Just pick one and start using. For us, it's out of scope currently to implement it ourself. Thanks
