### ISSUE TITLE
Feature Request: Confirmation before uploading code by GoPlay

### ISSUE THREAD

**Issue by ichitera** [fatih/vim-go#1615]
### What does vim-go do?
We run `GoPlay` command, then vim-go shares code immediately.

### What do you expect to happen?
I expected that:
1. vim-go confirms me that code should be shared before uploading, or
2. vim-go provides a method to disable `GoPlay` command temporally.

### What is a problem?
I am afraid that one day I will share some proprietary code by mistake, for example, when I run a command of vim-go from history or command completion.

I know that the real problem is carelessness, but I think that we will be saved from unfortunate mistake if vim-go provides some options for the above expectation.

**Comment by fatih** [comment]
Hm, I see your point and I agree that would be unfortunate. However, this is not something I would want to add. `:GoPlay` should just work and I'm don't want to add another layer and setting (as we already have hundreds of other settings). However here is something that allows you to override it and asks before uploading, hope that helps:

```viml
function! s:ask_go_play(count, line1, line2)
  let res = input("Uploading to play.golang.org? [Y]/n: \n")
  if empty(res)
    call go#util#EchoError("aborted")
    return
  endif

  if res isnot 'Y'
    call go#util#EchoError("aborted. Only 'Y' is accepted")
    return
  endif

  call go#play#Share(a:count, a:line1, a:line2)
endfunction

autocmd Filetype go command! -nargs=0 -range=% GoPlay call s:ask_go_play(<count>, <line1>, <line2>)
```

Add this to your `.vimrc`. After that `:GoPlay` will ask before you upload. If this comes a lot, we might rethink to make it part of vim-go. Thanks for the feedback.

**Comment by Carpetsmoker** [comment]
> vim-go provides a method to disable GoPlay command temporally.

Note you can do this with `:delcommand`.

**Comment by ichitera** [comment]
Thank you for the solutions! Both solutions work perfectly. Now, I no longer have the worry.
