### ISSUE TITLE
:GoMetaLinter waits for a key press when finished

### ISSUE THREAD

**Issue by kadfak** [fatih/vim-go#1617]
### What did you do? (required. The issue will be **closed** when not provided.)
After `:GoMetaLinter` (and gometalinter autosave) finishes with `vim-go: linting finished`, it starts waiting for key press to continue. Is there any way to skip the key press event? It's a small thing, but unproductive nevertheless.

Related to #1593 but it didn't help me.

### What did you expect to happen?
Smoothly skip the key press event.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 13 2017 20:57:42)
Included patches: 1-1389
```

* Go version (`go version`):
```
go version go1.9.2 linux/amd64
```

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/x/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build860268812=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version:
latest

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 1
let g:go_list_type = "locationlist"
```

**Comment by kadfak** [comment]
I'm no vim script wizard, so commenting out these two lines that just print out the status of the linting process seems to work well enough for me:
https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L308
https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L322

**Comment by Carpetsmoker** [comment]
This is usually because there isn't enough space to show all messages, so Vim starts the pager with the "hit enter" prompt. see `:help hit-enter`.

You can set `let g:go_echo_command_info=0` to disable informational messages like this.

**Comment by kadfak** [comment]
Thanks for the information! The setting you provided is definitely a better solution!

**Comment by damoye** [comment]
Same problem happens to me. If I use let g:go_echo_command_info=0, other messages like "Build Success" are gone too.

**Comment by michaelkrnac** [comment]
Same problem here.
