### ISSUE TITLE
GoTestFunc dont respect go_test_timeout

### ISSUE THREAD

**Issue by wmatusiak** [fatih/vim-go#1619]
### What did you do? (required. The issue will be **closed** when not provided.)
GoTestFunc on function with endless loop

### What did you expect to happen?
GoTestFunc should timeout after time specified in go test timeout

### What happened instead?
GoTestFunc  timeouts after 10m (default go test timeout)

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  5 2017 02:11:02)
Zadane łaty: 1-386

* Go version (`go version`):
go version go1.9.2 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ghost/Projects/go"
GORACE=""
GOROOT="/usr/lib64/go"
GOTOOLDIR="/usr/lib64/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build109089347=/tmp/go-build -gno-record-gcc-switches"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

* vim-go version:
978f01054e138b2eb53d361641f354e97c6ae1c9

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
empty

**Comment by bhcleek** [comment]
I can duplicate this. If, after the timeout elapses, you execute `:messages`, you'll see that `go test` paniced, but the message doesn't appear to clearly surfaced to the user.
