### ISSUE TITLE
Autocomplete from other packages in GOPATH

### ISSUE THREAD

**Issue by ghost** [fatih/vim-go#162]
Autocomplete is working great if I am trying to type something that is from within the package in the current file you are editing, or is in the go base library, ie `fmt.Prin`... however it appears not to work if you try to use a different package, ie if you are in package1, you cant autocomplete from package2, ie:
- $GOPATH/src/package1
- $GOPATH/src/package2

(Edit something in package2, and then try to autocomplete something from package1.)

**Comment by alienth** [comment]
Microsoft/vscode-go also uses gocode, and they get around this issue by enabling that autobuild option.

@fatih, would it be reasonable to have a default-disabled vim-go option which enabled autobuild on gocode? I understand it is experimental, but vscode-go seems to use it successfully, and after a cursory try on my end it seems to do the job. My only alternative at the moment is to manually enable this against gocode itself, which feels a bit messy.

**Comment by fatih** [comment]
@alienth that sounds a good plan. We can also enable it, just we need to be sure we do it the right way. Do you mind to open an issue and also point to the code how vscode-go does it? I know actually how to implement it, I just want to have some references for others. Thanks!
