### ISSUE TITLE
GoTest open empty file after compilation error

### ISSUE THREAD

**Issue by wmatusiak** [fatih/vim-go#1624]
### What did you do? (required. The issue will be **closed** when not provided.)
Run test on files with compilation error, like

```go
package main
func main() {
    a := 1
}
````

### What did you expect to happen?
File with errors in should be opened and cursor placed at line with error

### What happened instead?
Empty buffer with new file named "fileWithError.go:lineOfError" opened

My go print errors like file.go:line:column: i dont know if this is go version or configuration dependent but vim-go assume file.go:line:

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 21 2017 12:15:46)
Included patches: 1-1298

* Go version (`go version`):
go version go1.9.2 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ghost/Projects/go"
GORACE=""
GOROOT="/usr/lib64/go"
GOTOOLDIR="/usr/lib64/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build800808791=/tmp/go-build -gno-record-gcc-switches"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

* vim-go version:
f4b4ba1

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
empty

**Comment by Carpetsmoker** [comment]
Maybe #1620 already fixes it for you?

**Comment by wmatusiak** [comment]
Yes running `wget -O - https://patch-diff.githubusercontent.com/raw/fatih/vim-go/pull/1620.diff | patch -p1` in vim-go directory resolve problem.

**Comment by Carpetsmoker** [comment]
Thanks for confirming, I merged that patch now.

**Comment by wmatusiak** [comment]
Pull requests are one place I not check before submitting issue.
Next time i will check ;)
