### ISSUE TITLE
Conflicts with indentLine?

### ISSUE THREAD

**Issue by 0x5010** [fatih/vim-go#1625]
I install both python-mode and vim-go plugin, it works when I edit python file ,but not works for go file. I wonder if vim-go has conflicts with indentLine.

**Comment by fatih** [comment]
Hi @0x5010 

What do you mean by indentline? Closing this, please reopen again with the template issue as this is not helpful at all for us. Thanks

**Comment by coanor** [comment]
Try add `filetype plugin off` in your vimrc.

**Comment by jinbeomhong** [comment]
He says, vim-go conflicts with [https://github.com/Yggdroot/indentLine](indentLine).
