### ISSUE TITLE
when the file is saved the folds are closed regardless of the cursor position

### ISSUE THREAD

**Issue by NikosEfthias** [fatih/vim-go#1627]
### What did you do? (required. The issue will be **closed** when not provided.)
created folds based on indentation

### What did you expect to happen?
when i save the file the current fold block to stay opened

### What happened instead?
all the folds are closed including the cursor line

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
![](https://i.imgur.com/7S1MshB.png)
* Go version (`go version`):
`go version go1.9.2 darwin/amd64`
* Go environment (`go env`):
``` bash
GOARCH="amd64"
GOBIN="/Users/nikos/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nikos/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-p
refix-map=/var/folders/bb/gch_ghjx6qs37zkj9drl895h0000gp/T/go-build121844764=/tmp/go-build -gno-record
-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
* vim-go version:
[6fb095f](https://github.com/fatih/vim-go/commit/6fb095f1dfb2a41c0f9a06d25e2f13e023cd687b)
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
[my vimrc](https://github.com/nikosEfthias/vimrc)

**Comment by bhcleek** [comment]
Try setting `let g:go_fmt_experimental = 1`.

**Comment by NikosEfthias** [comment]
and what does it do actually ? @bhcleek

**Comment by bhcleek** [comment]
It uses `:mkview` and `:loadview` when you save so that folds will be restored. 

https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim#L33-L58. 

You could also try some autocommands:

```
augroup GoFolds
  au BufWrite *.go mkview
  au BufRead *.go silent loadview
augroup END
```

**Comment by NikosEfthias** [comment]
Actually what i noticed is this issue happens only when i use `:GoImports` `:GoFmt` is doing just fien

**Comment by bhcleek** [comment]
@NikosEfthias I'm going to close this issue then. Please open a new issue if you believe `:GoImports` is not working as expected.
