### ISSUE TITLE
Location list: 

### ISSUE THREAD

**Issue by al3xandru** [fatih/vim-go#1628]
### What did you do? (required. The issue will be **closed** when not provided.)

When typing, location list is automatically displayed with parsing errors.

### What did you expect to happen?

I'd like this behavior to be configurable in the sense that 

1.  the behavior of the location list should allow to 
2.  allow to configure when the errors are reported (delay, on save, etc.)

### What happened instead?

Location list opens and closes automatically leading to a lot of flickering that is very distracting.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 22 2017 03:30:17)
macOS version
Included patches: 1-1420
```

* Go version (`go version`):

`go version go1.9.2 darwin/amd64`

* Go environment (`go env`):

```
ARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alex/.golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/80/chdscn3n6l175yq91yhnr_nc0000gn/T/go-build279145063=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version:

`3a8cc93`

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

In a way this sounds a bit like #989, but that is very old and was closed without a resolution, which makes me wonder if this behavior is the result of the interaction of multiple plugins. Please let me know what additional details I can provide.

**Comment by al3xandru** [comment]
Further investigations make me believe this is actually the result of `w0rp/ale` plugin.  Once I'll have it confirmed, I'll close this ticket.

**Comment by fatih** [comment]
We don't have any kind of autoclose @al3xandru I'm definitely sure this is not vim-go. We even don't autocheck unless you explicitly enable it via a setting. I'm closing this but please let me know if you think this is vim-go related and we can reopen.

**Comment by al3xandru** [comment]
@fatih: I'm sure you are right. 

What is the autochecking setting in vim-go? So far I've been able to improve the behavior of w0rp/ale, but it's not perfect yet and so I'd like to continue to investigate.

**Comment by fatih** [comment]
Checkout this:

```
                                                  *'g:go_metalinter_autosave'*

Use this option to auto |:GoMetaLinter| on save. Only linter messages for
the active buffer will be shown. By default it's disabled.

  let g:go_metalinter_autosave = 0

```

You can also specify which linter should be executed on save:

```
Specifies the enabled linters for auto |:GoMetaLinter| on save. By
default it's using `vet` and `golint`.

  let g:go_metalinter_autosave_enabled = ['vet', 'golint']

```
