### ISSUE TITLE
GoInstallBinaries and GoUpdateBinaries using GOPATH instead of GOPATH/bin

### ISSUE THREAD

**Issue by al3xandru** [fatih/vim-go#1630]
### What did you do? (required. The issue will be **closed** when not provided.)

Run `:GoInstallBinaries` or `:GoUpdateBinaries`

### What did you expect to happen?

According to the docs, given I don't have `GOBIN` defined, binaries should have been installed in `$GOPATH/bin`

### What happened instead?

Binaries are installed in `$GOPATH` instead.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 22 2017 23:37:15)
macOS version
Included patches: 1-1400
```

* Go version (`go version`): `go1.9.2 darwin/amd64`

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alex/.golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/80/chdscn3n6l175yq91yhnr_nc0000gn/T/go-build900388694=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version: 3a8cc93e52ff246813bf2845501e458862c7d4f4

*I can manually move the binaries in the `$GOPATH/bin`, but I'm wondering:

1.  should I set a `GOBIN`?
2.  what leads to this behavior
3.  should I move the binaries manually?  and if I move the binaries manually will vim-go break?

**Comment by bhcleek** [comment]
@al3xandru Thank you for the bug report. I am not able to reproduce the behavior you are describing, though.

When you run `:GoUpdateBinaries` messages echoed to the screen describing which packages are being installed and to where they are being installed. What messages are echoed to your screen?

**Comment by al3xandru** [comment]
Haven't mentioned those as they confirm the report above:

```
vim-go: Updating gogetdoc. Reinstalling github.com/zmb3/gogetdoc to folder /Users/alex/.golang
vim-go: Updating guru. Reinstalling golang.org/x/tools/cmd/guru to folder /Users/alex/.golang
vim-go: Updating golint. Reinstalling github.com/golang/lint/golint to folder /Users/alex/.golang
vim-go: Updating fillstruct. Reinstalling github.com/davidrjenni/reftools/cmd/fillstruct to folder /Users/alex/.golang
vim-go: Updating godef. Reinstalling github.com/rogpeppe/godef to folder /Users/alex/.golang
vim-go: Updating motion. Reinstalling github.com/fatih/motion to folder /Users/alex/.golang
vim-go: Updating errcheck. Reinstalling github.com/kisielk/errcheck to folder /Users/alex/.golang
vim-go: Updating gocode. Reinstalling github.com/nsf/gocode to folder /Users/alex/.golang
vim-go: Updating gotags. Reinstalling github.com/jstemmer/gotags to folder /Users/alex/.golang
vim-go: Updating impl. Reinstalling github.com/josharian/impl to folder /Users/alex/.golang
vim-go: Updating goimports. Reinstalling golang.org/x/tools/cmd/goimports to folder /Users/alex/.golang
vim-go: Updating gomodifytags. Reinstalling github.com/fatih/gomodifytags to folder /Users/alex/.golang
vim-go: Updating keyify. Reinstalling github.com/dominikh/go-tools/cmd/keyify to folder /Users/alex/.golang
vim-go: Updating gorename. Reinstalling golang.org/x/tools/cmd/gorename to folder /Users/alex/.golang
vim-go: Updating asmfmt. Reinstalling github.com/klauspost/asmfmt/cmd/asmfmt to folder /Users/alex/.golang
vim-go: Updating gometalinter. Reinstalling github.com/alecthomas/gometalinter to folder /Users/alex/.golang
```

Interestingly, before running `:GoUpdateBinaries`, `:echo $GOBIN` returns empty.  After executing `:GoUpdateBinaries`, `:echo $GOBIN` returns the value of `$GOPATH` (but not `$GOPATH/bin`).

**Comment by bhcleek** [comment]
What is the value of your `g:go_bin_path`?

**Comment by al3xandru** [comment]
`echo g:go_bin_path` returns the same value as `$GOPATH` (`$HOME/.golang`)

**Comment by bhcleek** [comment]
That's why your binaries are being installed to `$HOME/.golang`. I'd recommend not setting `g:go_bin_path`.

**Comment by al3xandru** [comment]
Confirming that @bhcleek's answer above is capturing the cause of the behavior I reported.
