### ISSUE TITLE
arrow key control characters randomly showing up on screen

### ISSUE THREAD

**Issue by jonathanpittman** [fatih/vim-go#164]
I am using Vundle and have vim-go installed.  I also have an autocompletion package.  I have tried YouCompleteMe and NeoComplete.  The following issue seems to occur regardless of what other packages I have installed or removed (admittedly, I did not try removing Vundle).  The issue only seems to go away when I disable vim-go, but then so do all of the features it offers.

While moving the cursor around the screen (sometimes while typing even), I get random insertions of ^[OA, ^[OB, ^[OC, and ^[OD covering existing text locations.  If I move the buffer forward a page and back again, the original text is displayed again.

For example...

```
case reflect.String^[OD
    if f.Count() >^[OD{
```

If I jump back or forth and then back to this again, I see...

```
case reflect.String:
    if f.Count() > 40 {
```

I know what these stand for and I have even tried adding direct mapping in my .vimrc to make them map to the up, left, right, and down arrow keys to see if that would clear the issue.  I have not found anything to make it better other than removing vim-go.  I do not know that this is not an issue with my setup, but any insight you have is appreciated.

**Comment by jesusangelm** [comment]
I have a similar problem.
I just move the cursor from left to right in insert mode, and this happens:
I recorded [this](https://drive.google.com/file/d/0B4RlDirVodiXeFZMdXd5c3llMTA/view?usp=sharing) video to show the behavior.
