### ISSUE TITLE
Renaming a variable in a file that is in a subdirectory won't rename the whole repo

### ISSUE THREAD

**Issue by c9s** [fatih/vim-go#1642]
### What did you do? (required. The issue will be **closed** when not provided.)

GoRename a variable in a file that is in a subdirectory of a repository directory.

### What did you expect to happen?

Should rename all the typenames that are used in other subdirectories in the same repo.

### What happened instead?

Only files in package/subpackageA are renamed. 

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):

`Vim 8.0`

* Go version (`go version`):

`go version go1.8.3 darwin/amd64`

* Go environment (`go env`):

I don't think this is related to env.

* vim-go version:

master 3ceecc2bfa682a5f1f1db226b16bcd6edda8027b

**Comment by bhcleek** [comment]
Please provide the Go environment details, too; they may well be relevant.

I'm not able to duplicate the problem you're describing. Can you provide a more detailed replication plan?

**Comment by fatih** [comment]
Gorename works across all GOPATH, there is no distinction of subfolder or whatsoever. I think there is a misconfiguration of GOPATH for the OP, I'm not sure otherwise how this would fail.

**Comment by Carpetsmoker** [comment]
```
[~/go/src/a]% ls -l
total 4K
-rw-r--r-- 1 martin martin 1129 Jan  9 20:33 a.go

[~/go/src/a]% vim newdir/newdir.go
```

Now type something like (but don't `:w`):

```
package newdir

var a = "Hello"
```

And if you don't save/create the dir, you'll get this with `:GoRename b`:

    vim-go: gorename: no such file: newdir/newdir.go

But this isn't just for new dirs, also new files. If I create `newdir/asd.go` (after creating `newdir`) and use `:GoRename` I get pretty much the same:

    vim-go: gorename: no such file: /home/martin/go/src/a/newdir/asd.go

So I don't know if #1643 will fix it? Also not 100% sure if we *want* to fix it? This command operates on multiple files/packages, and not so much on unsaved buffers. We could at least improve the error though.

**Comment by bhcleek** [comment]
Closing due to lack of participation by the reporter. 

@Carpetsmoker while what you describe is true, @c9s didn't provide enough details to know whether the go files in which the identifier was not renamed was in a non-existent directory, and there is nothing in the issue report about @c9s having seen such an error. If we want to improve the messaging or call `go#cmd#autowrite` before invoking `gorename`, we can handle that on another issue to avoid muddying the waters.
