### ISSUE TITLE
I want to use quickfix when execute GoMetalinter but use locationlist when autosave 

### ISSUE THREAD

**Issue by hori-ryota** [fatih/vim-go#1644]
### What did you do? (required. The issue will be **closed** when not provided.)

Use GoMetalinter and `g:go_metalinter_autosave`

### What did you expect to happen?

We can separate list depending on autosave or not

### What happened instead?

We cannot it now

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):

NVIM v0.2.2

* Go version (`go version`):

1.9.2

* Go environment (`go env`):

* vim-go version:

`3ceecc2bfa682a5f1f1db226b16bcd6edda8027b` (latest of master branch)

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

---

I use quickfix when I explicitly run, and want to use locationlist in lint which runs automatically.

How about to allow following?
```
let g:go_list_type_commands = {"GoMetaLinterAutoSave": "locationlist"}
```

**Comment by bhcleek** [comment]
Sounds good to me.
