### ISSUE TITLE
GoRename doesn't work properly with symlinks

### ISSUE THREAD

**Issue by abates** [fatih/vim-go#1647]
My go src is linked to an alternate directory (using gvm linkthis). When using GoRename the resolved path (rather than linked path) is passed to GoRename and the gorename program then fails.

PR #1646 fixes this issue

### What did you do? (required. The issue will be **closed** when not provided.)
:GoRename NewName

### What did you expect to happen?
vim-go: Renamed 3 occurrences in 1 file in 1 package.

### What happened instead?
vim-go: gorename: can't find package containing /absolute/path/to/file.go

**Comment by bhcleek** [comment]
Generally, GOPATH does not support symlinks: https://github.com/golang/go/issues/15507

**Comment by bhcleek** [comment]
Thank you for creating an issue, @abates; your effort to make vim-go better is appreciated.

**Comment by sandipb** [comment]
Even if go/GOPATH doesn't support symlinks, I don't think this problem is related to that at all. If just the non-resolved path is provided to gorename, it would work - e.g. this works in vscode.
