### ISSUE TITLE
Autocomplete doesn't work automatically but works on ctrl-x ctrl-o.

### ISSUE THREAD

**Issue by xa0s-0** [fatih/vim-go#1649]
Autocomplete doesn't work automatically but works on ctrl-x ctrl-o. Nothing appears on the screen after typing for example `fmt.`

### Configuration:

* Vim version (first two lines from `:version`):
NVIM v0.2.2
Build type: Release

* Go version (`go version`):
go version go1.9.2 linux/amd64
* Go environment (`go env`):
I don't think this is related to env.

* vim-go version:

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

**Comment by Carpetsmoker** [comment]
That's because this isn't a feature that is implemented in either Vim or vim-go :-)

There are a bunch of plugins that do this, I think. `:help vim-go-plugins` mentions some of them.

**Comment by xa0s-0** [comment]
@Carpetsmoker Thanks, I did not know about it. Now everything works perfectly.
