### ISSUE TITLE
Plans to support CTRLSPACE

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#1650]
### What did you do? (required. The issue will be **closed** when not provided.)
Researched current VIM plugins utilizing GO as their backend

Just curious - https://github.com/vim-ctrlspace/vim-ctrlspace this looks like a great GO backed project. Are there any plans to support this in the same manner as CTRLP ?

**Comment by fatih** [comment]
Hi @ldelossa 

We have already united, denite, fzf and ctrlp support for :GoDeclsDir. Feel free to open a PR if you want to add support. Thanks
