### ISSUE TITLE
Tab Characters Display

### ISSUE THREAD

**Issue by MikeSofaer** [fatih/vim-go#1658]
Maybe setlocal nolist is a good idea?

### What did you do? (required. The issue will be **closed** when not provided.)
Opened a go file

### What did you expect to happen?
Not to see ^I

### What happened instead?
Saw ^I

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 30 2015 17:16:17)
MacOS X (unix) version
* Go version (`go version`):
go version go1.9.2 darwin/amd64
* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/michael/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zv/7p
ly8vgs76l_ps6wyvtctjvc0000gn/T/go-build991056540=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"  
* vim-go version:
Current today
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
set list

**Comment by bhcleek** [comment]
This is fully under your control; vim-go does not manage the `list` option.

**Comment by MikeSofaer** [comment]
I'm aware that vim-go does not manage the list option. vim-go not managing the list option is the issue. vim-go manages expandtab, it should manage list as well, for exactly the same reason.

**Comment by bhcleek** [comment]
It manages `expandtab`, because of community standards for writing Go. Whether you want to show tabs or not is a personal preference and does not affect the content of the file.

**Comment by MikeSofaer** [comment]
There are explicit official standards on how to display the tabs in Go as well.

Many languages in use today have community standards against using tabs, and for those languages it is helpful to see tabs called out. A multi-language setup should be aware of the contexts in which tabs are normative and not call them out.

Wanting tabs not to be called out in all Go files is a totally reasonable thing to want, even for a developer who uses `set list` in general because most coding communities don't want tabs. The easiest way to do that is in a plugin that is already detecting them.

**Comment by fatih** [comment]
@bhcleek is right. Also we don't add UI changes. That's a user preference. Just add it to your vimrc and you're good to go.

**Comment by MikeSofaer** [comment]
I guess something like `autocmd FileType go setlocal nolist shiftwidth=8 tabstop=8` will work. Thanks for talking me through your thinking on this.
