### ISSUE TITLE
Vim hangs for 20s on write (:w)

### ISSUE THREAD

**Issue by unrealsolver** [fatih/vim-go#1659]
### What did you do? (required. The issue will be **closed** when not provided.)
Configured gopath; opened a project; After few :w iterations vim start hanging for 20s
UPD:
I commented WriteBufPre/Post hooks, but it doesn't help - at some moment it started working really slow.
Maybe, it related to :GoMetaLint and also the project has tons of code and dependencies
UPD 2:
I've checked `htop` and noticed that each `:w` causes compile/build process. I think this is a cause. How can I prevent such behavior?
UPD 3
`let g:go_gocode_autobuild = 0` seem help.

### What did you expect to happen?
Save should work (almost) instantly

### What happened instead?
Save hangs vim for 20 seconds

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2018 07:13:39)
Included patches: 1-1415

* Go version (`go version`):
go version go1.9.2 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ruslan/dev/gopath"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build043770730=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

* vim-go version:
https://github.com/fatih/vim-go/commit/5a205d3a5741a68a47804bfda15121092ae1db3b

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

**Comment by bhcleek** [comment]
What is the value of your `g:go_info_mode` and `g:go_auto_type_info` options?

**Comment by unrealsolver** [comment]
@bhcleek , both are undefined. I set `go:go_golang_autobuild` to `0`. It seems it helped. Need some more time to check.

**Comment by fatih** [comment]
@unrealsolver we don't have a flag called `go_golang_autobuild`. Are you sure you don't another different plugin?

**Comment by unrealsolver** [comment]
@fatih , Sorry, I misspelled it, should be `go:go_gocode_autobuild`

**Comment by bhcleek** [comment]
Thanks @unrealsolver. I suspect that's going to solve your problem. Unfortunately, it will mean that gocode's cache will start to be invalid over time. I'll label this issue as waiting-for-info for now. If we don't hear back from you within a few days, then I'll assume that setting `g:go_gocode_autobuild=0` was successful at solving your long write times.

**Comment by Carpetsmoker** [comment]
> If we don't hear back from you within a few days, then I'll assume that setting g:go_gocode_autobuild=0 was successful at solving your long write times.

Making this assumption and closing the issue :-) Feel free to comment if you have further problems or questions and we can reopen this issue.
