### ISSUE TITLE
File switching appears to take time proportional to number of open buffers [edit]

### ISSUE THREAD

**Issue by nyarly** [fatih/vim-go#1660]
### What did you do? (required. The issue will be **closed** when not provided.)

I switch files in my Go project (c.f. https://github.com/opentable/sous). e.g. Using <C-^>.

### What did you expect to happen?

The new file to open nearly instantly.

### What happened instead?

There's a noticeable delay - on the order of half a second.

It's a drag but I've been living with it. 

Update: I had many dozens of files open in buffers. Closing those out (rather: restarting Vim after stripping my session) restores quick switching between buffers.

I don't think I've seen this behavior in e.g. Rails projects, which can also accumulate buffers quickly.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
```
NVIM v0.2.0                                                                                                                                                                      
Build type: Release
```
* Go version (`go version`):
```
go version go1.9.2 linux/amd64
```
* Go environment (`go env`):
```
GOARCH="amd64"                                                                                                                                                                  
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/judson/golang"
GORACE=""
GOROOT="/nix/store/0b91dwiap82wpar5b225bs8wig8c7xva-go-1.9.2/share/go"
GOTOOLDIR="/nix/store/0b91dwiap82wpar5b225bs8wig8c7xva-go-1.9.2/share/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build492100358=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
* vim-go version:
Newest? I just did a PlugUpdate

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

I'll run down a reduced vim in the near future. In the meantime, c.f. https://github.com/nyarly/dotfiles/tree/master/neovim/.config/nvim

**Comment by nyarly** [comment]
@fatih This is a follow-up to a tweet earlier today.

**Comment by Carpetsmoker** [comment]
This seems to work fine for me.

Could you please try and reproduce this with a minimal vimrc? This sounds like an `autocmd` misbehaving or firing multiple times or some such, but I'm not going to go through you huge vimrc directory to find that for you.

**Comment by Carpetsmoker** [comment]
I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.
