### ISSUE TITLE
GoDecls not populating CTRLP

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#1661]
### What did you do? (required. The issue will be **closed** when not provided.)
I type "GoDecls" in a go repository.

### What did you expect to happen?
Function definitions to be populated into CTRLP's menu

### What happened instead?
== NO ENTRIES == is displayed in GoDecls

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
```
❯ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 18 2017 10:09:08)
```

* Go version (`go version`):
```
❯ go version
go version go1.9.2 darwin/amd64
```

* Go environment (`go env`):
```
❯ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t8/0rn0lp953nb5lwv9vkn_mkr00000gp/T/go-build394277563=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version:
master

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
https://hastebin.com/equkurejaj.xml

**Comment by Carpetsmoker** [comment]
Could you please:

1. Try with a minimal configuration which adds only vim-go, CtrlP, and basic settings (e.g. enabling filetype and such)?
2. Provide a reproducible case, such as the Go file you used, and its location (e.g. is it inside GOPATH?)

Thanks!

**Comment by Carpetsmoker** [comment]
I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.

**Comment by mukhtar13** [comment]
I have the same issue please give solution if available any

**Comment by bhcleek** [comment]
This issue is years old. Feel free to open a new one to describe the problem and your configuration @mukhtar13
