### ISSUE TITLE
:GoFillStruct fails with "fillstruct: could not find file" when there are two different packages in the same directory

### ISSUE THREAD

**Issue by mirza-s** [fatih/vim-go#1665]
### What did you do? (required. The issue will be **closed** when not provided.)
Attempt to run GoFillStruct on any struct when two packages are defined in the same folder

Minimal repro:

main.go
```
package main

type test struct {
	A int
}

func main() {
	a := test{} // <-- run :GoFillStruct on this line
}
```

main_test.go
```
package main_test
```

### What did you expect to happen?
struct to become filled

### What happened instead?
```
vim-go: fillstruct: could not find file "/full/path/to/existing/file.go"
```

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  6 2018 15:48:06)
macOS version

* Go version (`go version`):
go version go1.9.3 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN="xxxx"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="xxxx"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nt/0hzfppd92jvbk99fhvnhy8ph0000gn/T/go-build334798808=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

* vim-go version:
v1.16

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

**Comment by Carpetsmoker** [comment]
You can't have two packages in the same directory. It's simply not something Go allows, and many tools will break.

It will work for some commands (like `go run file.go`) only, but those are the exception, not the rule.

In addition, ` GOPATH="xxxx"` seems a rather curious setting? Many tools also rely on GOPATH being set and used correctly.

**Comment by mirza-s** [comment]
The issue appears to be caused by `fillstruct` looking at only the first package set and never gets to evaluate the provided file if it is not part of that package set. 

https://github.com/davidrjenni/reftools/blob/master/cmd/fillstruct/main.go#L368

BTW,
I removed the actual GOPATH from the listing.
