### ISSUE TITLE
GoDoc returns error if go src is symlinked into GOPATH and the src file is in main pkg

### ISSUE THREAD

**Issue by greg-kent** [fatih/vim-go#1666]
### What did you do? (required. The issue will be **closed** when not provided.)
I noticed this on my work code environment, but reproduced it using vim-go-tutorial/main.go
For reasons out of my control we need to symlink our go src into a go env
Steps: 
1. git clone vim-go
2. mv vim-go-tutorial/main.go to a path outside the GOPATH
3. create a symlink from the new path of main.go to the the old main.go file location
4. open main.go in vim, and try :GoDoc
5. see the error
vim-go: gogetdoc: couldn't get package for /home/greg/main.go: can't find package containing /home/greg/main.go

In my work environment, I noticed that if the source file was not (main.go in the above example) in 'main' pkg then :GoDoc would succeed. 
in somefile.go ('main' pkg), :GoDoc on Println -> doesn't work
in somefile2.go ('somepkg' pkg), :GoDoc on Println -> works

Other info:
I tried opening the file in vim via the real path and then also via the symlink in GOPATH and got the same result.
All over vim-go commands seems to work.
:GoInfo works for Println in main.go

### What did you expect to happen?
I expected :GoDoc to work the same all go file whether they are in main pkg or not.

### What happened instead?
I got an error.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 29 2018 14:32:11)
Included patches: 1-1438

* Go version (`go version`):
go version go1.9.3 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/greg/Code/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
* vim-go version:
Latest

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd             " Show (partial) command in status line.
set showmatch           " Show matching brackets.
set ignorecase          " Do case insensitive matching
set smartcase           " Do smart case matching
set incsearch           " Incremental search
set autowrite           " Automatically save before commands like :next and :make
set hidden              " Hide buffers when they are abandoned
set mouse=a             " Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" Whitespace rules
autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4

call plug#begin()
  Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }

  " Split or join structs from multiline to singleline
  Plug 'AndrewRadev/splitjoin.vim'

  " Code snippets
  Plug 'SirVer/ultisnips'

  " Fuzzy finder for tags, files etc
  Plug 'ctrlpvim/ctrlp.vim'

  Plug 'nsf/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }
call plug#end()

**Comment by greg-kent** [comment]
In main.go if i run ':GoDoc fmt Println' then it works.

**Comment by fatih** [comment]
Please don't use symlinks. It's not supported by the Go toolchain. Thanks
