### ISSUE TITLE
Add: command for adding empty document string 

### ISSUE THREAD

**Issue by wzhliang** [fatih/vim-go#1667]
This is a feature request.

When exporting a function or structure, it's ideal to have comment on top of it like this:

    // Foo ...
    func Foo() {}

It'll nice to have a command that automatically add the comment part.

**Comment by fatih** [comment]
You can do this with the following: 

```
" create a go doc comment based on the word under the cursor
function! s:create_go_doc_comment()
  norm "zyiw
  execute ":put! z"
  execute ":norm I// \<Esc>$"
endfunction
nnoremap <leader>ui :<C-u>call <SID>create_go_doc_comment()<CR>

```

Put your cursor on something and press `<leader>ui` (or change it to your needs). 

I don't think this is something worth adding. It's just a comment and you can easily copy/paste it or create a function like the above. If you open a PR to the doc's FAQ with the snippet above I'm happy to include it though. Thanks!
