### ISSUE TITLE
Autocomplete not triggered if using imports in brackets 

### ISSUE THREAD

**Issue by criscola** [fatih/vim-go#1668]
### What did you do? 

1. Tried to use autocompletion with import like this:

`import { 
    "fmt" }` 

2. Wrote `fmt.` into main function
3. Pressed ctrl-x ctrl-o
4. Autocompletion not working
5. Tried to use autocompletion with import like this:
`import "fmt"`
6. Pressed ctrl-x ctrl-o in the same spot as before
7. Autocompletion is magically working

### What did you expect to happen?

I expected that using both import ways, autocompletion would work the same way

### What happened instead?

See "What did you do"

### Configuration 

* Vim version: 

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 20:13:43)
Included patches: 1-197, 322, 377-378, 422, 550
```

* Go version (`go version`):

`go version go1.8.3 linux/amd64`

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/criscola/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build529932359=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

* vim-go version:
Version is: `v1.16`

* `vimrc`
I'm using Plug for handling plugins, so there are just 3 lines (start, plug "vim-go", finish)

```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

I'm sorry if this is actually a feature and I didn't find it in the documentation or in another issue. If this isn't a feature (or even if it is...), shouldn't both import ways be equal for autocompletion? I spent a while debugging it thinking that my plugin was flawed somehow. 
Thank you.

**Comment by Carpetsmoker** [comment]
Ehm, `import { "fmt" }` is not valid Go syntax?

**Comment by criscola** [comment]
Now is working. Thank you
