### ISSUE TITLE
Vendored GOPATH not detected for dep

### ISSUE THREAD

**Issue by smlx** [fatih/vim-go#1674]
### What did you do?

* Set `goimports` to auto-run on save.
* Vendored my imports using [`dep`](https://github.com/golang/dep/)
* `:w`

### What did you expect to happen?

`goimports` format my imports.

### What happened instead?

`goimports` deleted one of my import lines which was actually used in the code.

My regular GOPATH didn't have the imported package installed. Instead I had installed the package in `/vendor` using [`dep`](https://github.com/golang/dep/). After I used `go get` to install the package in question to my regular GOPATH, `goimports` stopped deleting the import line from my code.

This behaviour seems to be due to `goimports` running in my regular GOPATH rather than the `dep` vendored GOPATH. `:GoPath` returns my regular GOPATH, not the `/vendor` path.

There's a [related TODO in path.vim](https://github.com/fatih/vim-go/blob/ffb2f4369f3d26b95161593ba6530366532d2c43/autoload/go/path.vim#L77). As `godep` et al. have now been deprecated in favour of `dep`, this function should probably be updated to support `dep`.

### Configuration:

* Vim version (first two lines from `:version`):
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707
```

* Go version (`go version`):

```
go1.9.2 linux/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/scott/dev/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build753951855=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version:

```
v1.15-94-g40e2e19
```

**Comment by fatih** [comment]
I think something is wrong with your setup. You don't need any kind of special setup. It should just work. This is not a vim-go problem at all. Try to call `goimports` on your terminal and observe how it behaves there. Check out your GOPATH. I think it's not set correctly. Thanks.
