### ISSUE TITLE
Add option to open :GoDef in new tabs?

### ISSUE THREAD

**Issue by wellsjo** [fatih/vim-go#1676]
Is this something that is possible or can be added?

**Comment by fatih** [comment]
Hi @wellsjo 

You can do this by adding the following:

```
  autocmd FileType go nmap <silent> <Leader>d <Plug>(go-def-tab)
```

now call `<leader>d` and it'll call :GoDef in a tab. You can change it to your own liking. 
Checkout the docs for more information.

**Comment by wellsjo** [comment]
Thanks @fatih ! I missed `go-def-tab` when I went through the docs
