### ISSUE TITLE
Documentation for g:go_metalinter_excludes is confusing

### ISSUE THREAD

**Issue by piersy** [fatih/vim-go#1680]
### What did you do? (required. The issue will be **closed** when not provided.)
Added the following line to my init.vim file

`let g:go_metalinter_excludes = [".*\.pb\.go"]`

### What did you expect to happen?
An error to be thrown because ".*\.pb\.go" is not a linter and the doc states

> Specifies the linters to be excluded from the |:GoMetaLinter| command. By
default it's empty

### What happened instead?
Files ending in `.pb.go` were excluded from linting

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
```
NVIM v0.2.3-1-gd6f9d1df0
Build type: RelWithDebInfo
```

* Go version (`go version`):
`go version go1.9.2 linux/amd64`

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/piers/projects/yoti_blockchain_gopath"
GORACE=""
GOROOT="/home/piers/programs/go1.9"
GOTOOLDIR="/home/piers/programs/go1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build337274581=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version:
`v1.13`

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin()
Plug 'fatih/vim-go', { 'tag': 'v1.13' }
call plug#end()

let g:go_metalinter_excludes = [".*\.pb\.go"]

" Required to work around a problem with nvim and garbage characters in my
" terminal.
set guicursor=
```

**Comment by Carpetsmoker** [comment]
This already got fixed in #1648.

It's probably better to use an autocmd if you don't want gometalinter to run on certain files, for example (untested):

```
augroup vim-go
  autocmd!
  autocmd BufNewFile,BufRead *.pb.go  let b:go_metalinter_autosave = 0
augroup end
```

to make that work, we'd have to add a `b:` option to override the `g:` one though.

**Comment by piersy** [comment]
@Carpetsmoker  #1648 seems to just change the name of the option. But the documentation still states.

```
Specifies the linters to disable for the |:GoMetaLinter| command. By default
it's empty
```

When in fact the option is controlling which files are chosen for linting.

**Comment by Carpetsmoker** [comment]
> When in fact the option is controlling which files are chosen for linting.

No. The behaviour now matches the documentation.

**Comment by piersy** [comment]
@Carpetsmoker thanks, I had not noticed that, probably should have read the pr comment :P I guess the issue can be closed.
