### ISSUE TITLE
Guru works incorrectly on Referrers call

### ISSUE THREAD

**Issue by regeda** [fatih/vim-go#1681]
### What did you do? (required. The issue will be **closed** when not provided.)
"exe GoReferrers" on a local variable

### What did you expect to happen?
output for variable's usage

### What happened instead?
nothing

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2018 11:01:36)
macOS version

* Go version (`go version`):
go version go1.8.7 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN="/Users/regeda/juno/work/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go@1.8/1.8.7/libexec"
GOTOOLDIR="/usr/local/Cellar/go@1.8/1.8.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bl/ct7mm5bj28n7tjmrb511cgbr0000gn/T/go-build452278442=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

* vim-go version:
master

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

After https://github.com/fatih/vim-go/commit/18b9897365810890d65ae617c18f97c0c6d4ed18#diff-319de9effd14629f8bc943280d8c81c2 reverting, Referrers works correctly.

**Comment by bhcleek** [comment]
Thank you for reporting this issue. I'm able to duplicate it as long as `g:go_auto_sameids` is set. Until this is fixed, you may consider making sure that `g:go_auto_sameids` is off.

**Comment by regeda** [comment]
Thanks! But when do you plan to fix it?
