### ISSUE TITLE
Can't debug some test files (?)

### ISSUE THREAD

**Issue by Carpetsmoker** [fatih/vim-go#1690]
It works for some test files, but not this particular one?

```
[~tw/kommentaar](master)% vi parse/parse_test.go
```

`:GoDebugStart` gives me:

```
vim-go: Starting GoDebug...
vim-go: 2018/02/27 19:26:12 debugger.go:98: launching process with args: [/tmp/vNu86sR/2]
vim-go: could not launch process: fork/exec /tmp/vNu86sR/2: no such file or directory
vim-go: could not remove /tmp/vNu86sR/2: remove /tmp/vNu86sR/2: no such file or directory
vim-go: 2018/02/27 19:26:12 debugger.go:98: launching process with args: [/tmp/vNu86sR/2]
vim-go: could not launch process: fork/exec /tmp/vNu86sR/2: no such file or directory
vim-go: could not remove /tmp/vNu86sR/2: remove /tmp/vNu86sR/2: no such file or directory
```

Seems to work on `parse/parse.go`, as well as on simpler test files (although this is not a particularly complicated file?)

This project isn't public, but just for my own future reference it can be reproduced with commit 5309c47

**Comment by Carpetsmoker** [comment]
I discovered the problem is how I opened the files. This fails

```
[~tw/kommentaar](master)% vi parse/parse_test.go
```

but this works:

```
[~tw/kommentaar](master)% cd parse
[~tw/kommentaar/parse](master)% vi parse_test.go
```

**Comment by fatih** [comment]
I see. I use the following in my vimrc:

```
" Enter automatically into the files directory
autocmd BufEnter * silent! lcd %:p:h
```

as I prefer to be in the directory of the file. Seems like this could be solved in a hacky way by cd'ing into the folder before we call delve.

**Comment by Carpetsmoker** [comment]
> Seems like this could be solved in a hacky way by cd'ing into the folder before we call delve.

Maybe for test files. It's intentional that we don't do this for regular Go files. Consider a package `foo` that has `package main`, and you load `subdir/sub.go`. You will usually want to debug the `foo` package, and not the `foo/subdir` package (Delve can't even run that as that's a non-main package).

I'm not sure what makes the most sense for test files though. A related issues I also had was that I wanted to add a breakpoint in `parse.go`, but I had to switch to the `parse_test.go` first and run `:GoDebugStart` there to run the tests (instead of the program). That's actually kind of annoying; I would prefer to add the breakpoint and then just run the tests without switching buffers. Maybe a flag to `:GoDebugtStart` or a separate `:GoDebugTest` command is better.
