### ISSUE TITLE
:GoDebugBreakpoint is not available anymore after a :GoDebugStop

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#1691]
To reproduce:

1. Call `:GoDebugBreakpoint` on a line
2. Start the debugger with `:GoDebugStart`
3. Stop the debugger with `:GoDebugStop`
4. Observe that `:GoDebugBreakpoint` is not available anymore

**Comment by Carpetsmoker** [comment]
I added it [here](https://github.com/fatih/vim-go/blob/master/autoload/go/debug.vim#L253) but now I get this after `:GoDebugStop`:

```
:GoDebugBreakpoint
sending to dlv RPCServer.CreateBreakpoint
vim-go: (call):E906: not an open channel
```

Looks like it's using the connection to the killed server.

Need to look more deeply later.
