### ISSUE TITLE
String values are displayed as individual bytes

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#1692]
Set a breakpoint to a variable assignment, such as: 

```
branch := "master"
```

The local variable is displayed as:

```
# Local Variables
branch: string[842351182208]: g�r
 branch[0]: byte(103)
 branch[1]: byte(14)
 branch[2]: byte(1)
 branch[3]: byte(0)
 branch[4]: byte(0)
 branch[5]: byte(0)
 branch[6]: byte(0)
 branch[7]: byte(27)
 branch[8]: byte(0)
 branch[9]: byte(0)
 branch[10]: byte(0)
```

Not sure whether it's vim-go related (as we display the variables) or delve. Adding here as a reminder. Here is a picture as well:

<img width="433" alt="screen shot 2018-02-27 at 10 55 34 pm" src="https://user-images.githubusercontent.com/438920/36751523-735f28ac-1c11-11e8-9592-8f0b67f031be.png">

**Comment by fatih** [comment]
Hm, interesting. Seems like this is an expected behaviour because the assignment is not done yet. If we step in, (the line below) than it shows it as master:

<img width="250" alt="screen shot 2018-02-27 at 11 00 06 pm" src="https://user-images.githubusercontent.com/438920/36751706-fa480d52-1c11-11e8-98a5-535ab993c14a.png">

I wonder if the number above is the pointer address of the variable 🤔

**Comment by Carpetsmoker** [comment]
Yeah, this is how Delve works, there is the same output on the command-line:

```
[~/go/src/a]% cat a.go
package main

import (
        "fmt"
)

func main() {
        branch := "master"
        fmt.Println(branch)
}

[~/go/src/a]% dlv debug .
Type 'help' for list of commands.

(dlv) break a.go:8
Breakpoint 1 set at 0x49c1af for main.main() ./a.go:8

(dlv) c
> main.main() ./a.go:8 (hits goroutine(1):1 total:1) (PC: 0x49c1af)
     3: import (
     4:         "fmt"
     5: )
     6:
     7: func main() {
=>   8:         branch := "master"
     9:         fmt.Println(branch)
    10: }

(dlv) locals
branch = "H�D$8�FH�D$(H���\x00\x00\x00H�\f$�G_\x03\x00H�D$\bH�D$8H�L$(Hǁ�\x00\x00\x00\x00\x00\x00\x00H�\f$H�D$\b\x03...+842350542940 more"

(dlv) step
> main.main() ./a.go:9 (PC: 0x49c1c4)
     4:         "fmt"
     5: )
     6:
     7: func main() {
     8:         branch := "master"
=>   9:         fmt.Println(branch)
    10: }

(dlv) locals
branch = "master"
```

Same with other variable types; for example `branch := 42` is `branch = 842350543032` on `locals`.

The reason for this is because the variables are undefined, but I can't really find any issue in the Delve bug tracker that mentions that this is by design.

I reported a new issue here: https://github.com/derekparker/delve/issues/1134
