### ISSUE TITLE
:GoImpl doesn't support error interface

### ISSUE THREAD

**Issue by WGH-** [fatih/vim-go#1694]
### What did you do?
Put cursor at this struct definition and typed `:GoImpl error`.
```
type Foo struct {
}
```

### What did you expect to happen?
```
type Foo struct {
}

func (f *Foo) Error() string {
	panic("not implemented")
}
```

### What happened instead?
```
vim-go: unrecognized interface: error
```

### Configuration:

* Vim version (first two lines from `:version`): 
>VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 25 2017 16:28:23)
> Included patches: 1-1298

* Go version (`go version`):
> go version go1.9.3 linux/amd64

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/wgh/go"
GORACE=""
GOROOT="/usr/lib64/go"
GOTOOLDIR="/usr/lib64/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build775235387=/tmp/go-build -gno-record-gcc-switches"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
* vim-go version: 6cc4fd8967b2576b43b4a37a616abf37def7cc01

**Comment by Carpetsmoker** [comment]
This is an issue in the up-stream `impl` tool. I created a PR to fix it there: https://github.com/josharian/impl/pull/24

**Comment by WGH-** [comment]
I initially thought you had linked to a PR that had been sitting waiting to be merged for a while, but then I realized that you've just submitted it. That was fast! :)

**Comment by Carpetsmoker** [comment]
It was an easy enough fix :-)
