### ISSUE TITLE
Feature: Add support for vgo

### ISSUE THREAD

**Issue by piersy** [fatih/vim-go#1695]
[vgo](https://github.com/golang/vgo) provides package versioned package support for golang. It is set to be included in the upcoming go releases.  A set of articles describing it in detail are here -  https://research.swtch.com/vgo

It would be great to be able to take advantage of vgo with the full support of vim-go.

**Comment by fatih** [comment]
Hi @piersy 

How would you like to use vgo and how do you use vim-go currently? I'm not sure there is anything to add on our side currently. I'm curious what your expectations are.

**Comment by piersy** [comment]
Hi @fatih 

If I drop in vgo as a replacement to my go binary then building and testing seem to work. Features such as GoDef, GoReferrers, GoImplements ... etc do not work. This is because (among other things) vgo sets up a different directory structure compared with the standard GOPATH layout.

I have not tested exhaustively, but I guess there will be other parts of vim-go that are not vgo compatible.

My expectation would be that I can use all the features of vim-go regardless of whether the projects are built using vgo or go. vim-go should determine if the project is a vgo project or normal go project and be able to handle either, this should be transparent to the users.

**Comment by fatih** [comment]
Thanks for the comment. I think there is a misunderstanding here. As far I as know, once vgo is out, it gives us a way to laid out our dependencies in a reproducible way. In no way should it infer with what we do currenty. The commands `:GoDef`, `:GoReferrers`, etc.. uses `guru` and not go it self. This means that `guru` needs to satisfy the new requirements. There is not much to do currently on our side. Seems like it's more a tooling thing. 

I need to checkout vgo in more detail, but I believe there is little to do on our side for the current set of features we have.

**Comment by piersy** [comment]
Thanks for filling me in, I hadn't realised that all the logic for navigating code was contained in external tools. I guess I can close this issue then.
