### ISSUE TITLE
[Question] Import a library to smooth async operation between vim and neovim

### ISSUE THREAD

**Issue by jsfaint** [fatih/vim-go#1704]
Hey guys, I noticed that vim-go call job_start(vim) and jobstart(neovim) directly.
Every time when a new command is adding into vim-go, it need to be done for both vim and neovim.
Maybe we should import a library to smooth the gap between vim and neovim?

Maybe [async.vim](https://github.com/prabirshrestha/async.vim) is good choice?
async.vim can integrate inside the vim-go easily.
https://github.com/prabirshrestha/async.vim#embedding
I saw several plugin using it already.

Any ideas?
Thanks

**Comment by bhcleek** [comment]
@jsfaint thank you for the pointer. I've recently taken a closer look at our handling of async jobs for vim8 and neovim, too, and have been planning to introduce some changes to unify our approach soon so that vim8 and neovim async jobs don't have multiple codepaths throughout vim-go.

**Comment by jsfaint** [comment]
@bhcleek Got it, thanks for your clarification.

**Comment by jsfaint** [comment]
The job related function was refactor recently, I should close this issue now.
Thanks for all your great works! @bhcleek
