### ISSUE TITLE
GoRename should be able to change package names

### ISSUE THREAD

**Issue by NikosEfthias** [fatih/vim-go#1708]
### What did you do? (required. The issue will be **closed** when not provided.)
Tried to GoRename on package name

### What did you expect to happen?
all the `package` clauses to be replaced with the new name as well as import paths

### What happened instead?
A message saying this is not supported yet

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
`NVIM v0.2.3-dev`
* Go version (`go version`):
`go version go1.10 darwin/amd64`
* Go environment (`go env`):
```:!go env
GOARCH="amd64"
GOBIN="/Users/nikos/go/bin"
GOCACHE="/Users/nikos/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nikos/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bb/gch_ghjx6qs37zkj9drl895h0000gp/T/go-build084811193=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
* vim-go version:
#1706

**Comment by Carpetsmoker** [comment]
This message is from the `gorename` tool, not vim-go. It needs to be fixed there. See:

https://github.com/golang/tools/blob/master/refactor/rename/rename.go#L111
https://github.com/golang/tools/blob/master/refactor/rename/spec.go#L345
