### ISSUE TITLE
GoMetaLinter autosave compile error

### ISSUE THREAD

**Issue by SidusCaelum** [fatih/vim-go#1710]
**Go version 1.10**
**go-vim version Latest**
vim version 8.0 (2016 Sep 12, compiled Apr 23 2017)(MS-Windows 32-bit GUI version with OLE support)
When I add let g:go_metalinter_autosave_enabled = [......] I get a issue when on save with the regexp. Expect result was for error output to quickfix.

```
|| panic: regexp: Compile(`^src\rest\handlers.go:.*$`): error parsing regexp: invalid escape sequence: `\h`
|| 
|| goroutine 1 [running]:
|| regexp.MustCompile(0xc0420083fa, 0x19, 0x1)
|| 	C:/Go/src/regexp/regexp.go:240 +0x178
|| main.processConfig(0x7eb420, 0x0, 0xc042073f28)
|| 	C:/GoDevelopment/src/github.com/alecthomas/gometalinter/main.go:271 +0x399
|| main.main()
|| 	C:/GoDevelopment/src/github.com/alecthomas/gometalinter/main.go:212 +0x3b2
```
This problem doesn't occur when I manually call the GoMetaLinter from the vim command prompt. I've tried to use several different configs of different linters, but the issue persists. I don't know if this is a issue with the actual call being made during save, considering manual calling works. I have also download the MetaLinter manually and installed all the linting tools outside vim itself. (i.e. go get and then gometalinter --install)

**Comment by Carpetsmoker** [comment]
Looks like the regexp is invalid? That's what it says anyway:

    regexp: Compile(`^src\rest\handlers.go:.*$`): error parsing regexp: invalid escape sequence: `\h`

Maybe try using `\\` instead of `\`?

Also, it would be helpful to include the *full* steps to reproduce the problem. I have no idea where this regexp is coming from now?

**Comment by SidusCaelum** [comment]
If you follow the error output its call made from inside of gometalinter for parsing something or another. I have listed out all the steps. There isn't anything to directly interact with. This is being called inside of vim on save and the error occurs. As mentioned before let g:go_metalinter_autosave was added to the .vimrc file and upon saving this error comes up. Manually calling the the tool by ":GoMetaLinter" produces correct working behavior. There isn't anything I'm adding to the call. Its a matter of the plugin calling it vs me calling manually.

**Comment by bhcleek** [comment]
@SidusCaelum What value did you assign to `g:go_metalinter_autosave_enabled`? If you assign `g:go_metalinter_enabled` to the same value, do you also see the the error when you run `:GoMetaLinter`?

**Comment by SidusCaelum** [comment]
I had it set to ['vet', 'golint', 'errcheck']. This might have might have to do on my end. My computer around this time seemed to be having issues running and high disk usage. I had to completely wipe my computer and reinstall everything. So far I do not have the same issues. I'll check in if anything comes up. Thanks for the help.
