### ISSUE TITLE
GoImport doesn't import commented packages

### ISSUE THREAD

**Issue by DevAlone** [fatih/vim-go#1717]
### What did you do? (required. The issue will be **closed** when not provided.)

```
import (
    "errors"
    // "fmt"
)
```

`:GoImport fmt`

### What did you expect to happen?
```
import (
    "errors"
    "fmt"
)
```

### What happened instead?
`"fmt" already being imported`

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):

NVIM v0.2.2
Build type: RelWithDebInfo

* Go version (`go version`):

go version go1.10 linux/amd64

* Go environment (`go env`):

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/opt/golang"
GOTMPDIR=""
GOTOOLDIR="/opt/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build027896217=/tmp/go-build -gno-record-gcc-switches"

* vim-go version:

Last installed by vim-plug

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

https://gist.github.com/DevAlone/4f5ec03f17d42ce3bb730060ac1eb594

**Comment by Carpetsmoker** [comment]
The entire thing is a regexp-based mess of ugly. I rewrote the lot with #1559, just need to finish that up when I have the time!
