### ISSUE TITLE
go-run start insert mode when using nvim with splitright

### ISSUE THREAD

**Issue by doubleloop** [fatih/vim-go#1718]
### What did you do?
```
$ nvim -u test_vimrc main.go
```
(main.go is some working go program)
in vim I did `go-run` (by pressing `\gr`) then pressed `j`

### What did you expect to happen?
Either the terminal window should be active after `\gr`
or file buffer should remain active and `j` press should act as normal motion key

### What happened instead?
The file buffer remained active but after pressing `j`, insert mode was started.

### Configuration
The problematic setting is `set splitright`

* `vimrc` you used to reproduce:
```
$ cat test_vimrc
call plug#begin('~/.local/share/nvim/plugged')
Plug 'fatih/vim-go'
call plug#end()
nmap <leader>gr  <Plug>(go-run)
au WinEnter term://* startinsert
set splitright
```
* Vim version: NVIM v0.2.3-533-g9a36337d3
* Go version: go version go1.9 linux/amd64
* Go environment (`go env`):
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/doubleloop/.gvm/pkgsets/go1.9/global"
GORACE=""
GOROOT="/home/doubleloop/.gvm/gos/go1.9"
GOTOOLDIR="/home/doubleloop/.gvm/gos/go1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build292584452=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
* vim-go version: d2b0a234ffb5441a3488c78fe8e5f551ddbdd454

**Comment by Carpetsmoker** [comment]
I think this is the same as #1412?

**Comment by doubleloop** [comment]
Yes, looks the same.
