### ISSUE TITLE
Support for Go type live

### ISSUE THREAD

**Issue by mocheryl** [fatih/vim-go#1735]
Add support for error highlighting in Go code as you type:

[Go type live](https://github.com/tylerb/gotype-live)

It needs to be fast, simple and unobtrusive:

-   Just 3 globally exposed auto load functions: To enable and disable the
    feature and its toggling.
-   Using the already built-in `SpellBad` syntax group for highlighting errors.
-   Make as much use of available utility functions as possible to perform
    common operations such as echoing messages, setting delay and calling
    external commands.

Anyway, I have a working draft available here:
[typelive-support-draft](https://github.com/mocheryl/vim-go/tree/typelive-support-draft).
It's literary just a single vim file you can drop into your Go auto load
directory.

You'll need the aforementioned package installed in your `$PATH`:

    go get -u github.com/tylerb/gotype-live

Please check it out and give me some feedback on your thoughts about it. If it
works out, I can extend it further by adding documentation and maybe even some
tests before making a pull request.

Control it with the following three functions:

-    `go#typelive#AutoTypeLiveEnable()`
-    `go#typelive#AutoTypeLiveDisable()`
-    `go#typelive#ToggleAutoTypeLive()`

![vim-go-type-live](https://user-images.githubusercontent.com/17129795/37787038-016f0ffe-2df6-11e8-9cc6-23f1fc01055c.gif)

**Comment by Carpetsmoker** [comment]
That `gotype-live` repo seems unmaintained and is lacking a license. I'm not sure if adding support for that is a good idea.

**Comment by mocheryl** [comment]
It probably looks unmaintained because there is nothing more to add. The lack of concrete license declaration, however, is troublesome. I only focused on the source code headers where it states that it's BSD-style. I guess the author was a bit careless when making a fork. How much of an issue is this?

Also, is the hesitation to implement this feature because of the general idea, or due to the specific package used to implement it? If later, I'm sure we can connect with some other tool to do source code checking.

**Comment by bhcleek** [comment]
Closing. `gopls` provides similar kind of functionality that we may work to integration soon. Additionally, some of what gotype live seems to be doing is already covered by vim-go's `g:go_auto_type_info` option.
