### ISSUE TITLE
:GoDoc seems to be in vi compatibility mode

### ISSUE THREAD

**Issue by inlined** [fatih/vim-go#1739]
### What did you do? (required. The issue will be **closed** when not provided.)
Even when I add `set nocompatible` to my .vimrc, I'm having trouble with GoDoc. Whenever I hit an arrow key, it closes the :GoDoc window and adds a newline with the character associated with that arrow key.

### What did you expect to happen?
For arrow keys to move the cursor work

### What happened instead?
The GoDoc split closes, a new line in my original file is added, and it has the character associated with that arrow key.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 23 2018 09:25:20)
macOS version

* Go version (`go version`):
go version go1.10 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/inlined/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/inlined/gopath"
GORACE=""
GOROOT="/Users/inlined/.homebrew/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/Users/inlined/.homebrew/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lh/52s939yd4m35fcf7f1kp8850003t3z/T/go-build929448649=/tmp/go-build -gno-record-gcc-switches -fno-common"

* vim-go version:
v1.6

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
none (reproduced without vimrc)

**Comment by Carpetsmoker** [comment]
vim-go [maps `<Esc>` to close the godoc buffer](https://github.com/fatih/vim-go/blob/cdf31fcf8028ed6e9b10cf52ed795b664fd11edf/autoload/go/doc.vim#L126). What I suspect is going on is that Vim doesn't recognize the escape codes for your arrow keys, so it sees `<Esc>[B` (or whatever your terminal sends).

This doesn't really sound like a vim-go problem, but more of a general issue with your Vim/terminal/system?

**Comment by 26000** [comment]
The same for me, `:h vim-go`, for example, works perfectly, while `:GoDoc` closes on every arrow key, pageup/pagedown, etc press.

**Comment by dsymonds** [comment]
I did a `git bisect`, and f478b53 is the commit at which this starts failing for me. If I `git reset --hard f478b53^` then I'm back to a working vim-go.

**Comment by fatih** [comment]
Thanks David, this is helpful. I'll look into it. I wonder what triggers this behavior.

**Comment by dsymonds** [comment]
Thanks for the fix. Arrow keys work now, but PageUp/PageDown are now broken.  :-(
