### ISSUE TITLE
Starting the debugger on a buffer with unsaved changes

### ISSUE THREAD

**Issue by Carpetsmoker** [fatih/vim-go#1744]
If you use `:GoDebugStart` then it will always operate on the files on disk, and not in the buffer. So if you have unsaved changes then this can be rather confusing.

Copying to a tmp dir isn't really an option, since the debugger operates on packages rather than files. We don't want to copy entire packages.

I'm not sure what the best course of action is here? Maybe just do nothing and leave it as is? Or silently write buffers? Or show a warning? Or something else?

**Comment by mocheryl** [comment]
>   Or silently write buffers?

A lot of IDEs I have used do this, so I support this option.

**Comment by carson8349** [comment]
Not sure if this will help:
Is there a way to: before debugging start, if not save change is detected, save reminder? or auto save?

**Comment by fatih** [comment]
We write with `:GoBuild` automatically if autowrite is enabled. We should do the same for this.

```
function! go#cmd#autowrite() abort
  if &autowrite == 1 || &autowriteall == 1
    silent! wall
  endif
endfunction

" inside start function
call go#cmd#autowrite()
```

**Comment by mocheryl** [comment]
>   Is there a way to: before debugging start, if un-saved change is detected, save reminder? or auto save?

That's actually a great idea, because you could sort of mimic the behaviour of the native `:quit` command. This way can quickly debug old, working code in case you don't want to save or undo while in the middle of a change. And combined with what fatih suggested, you can circumvent this behaviour with auto-saving. Here's an example code snippet:

    function! DebugWithSaveOrWarning() abort
        " TODO: Scope both these if branches to buffers in current project only.
        if &autowrite == 1 || &autowriteall == 1
            silent! wall
        else
            for l:i in tabpagebuflist()
                if getbufvar(l:i, '&mod')
                    call go#util#EchoWarning('No write since last change. Running debugger on unmodified code only.')
                    break
                endif
            endfor
        endif

        " Execute rest of the debugger script here.
    endfunction

**Comment by mocheryl** [comment]
To amend to my last suggestion, if changing the function signature is in order, we could also control this functionality with a bang statement like `:GoDebugStart!`, which I think is preferable. Here is the modified function with the proposed change.


    function! DebugWithSaveOrWarningBang(bang) abort
        " TODO: Scope both these if branches to buffers in current project only.
        if &autowrite == 1 || &autowriteall == 1
            silent! wall
        else
            for l:i in tabpagebuflist()
                if !getbufvar(l:i, '&mod')
                   continue
                endif

                if a:bang <= 0
                    call go#util#EchoError('No write since last change (add ! to override).')
                    return
                endif

                call go#util#EchoWarning('No write since last change. Running debugger on unmodified code only.')
                break
            endfor
        endif

        " Execute rest of the debugger script here.
    endfunction
