### ISSUE TITLE
Package comment folding can cause serious slowdowns

### ISSUE THREAD

**Issue by kalafut** [fatih/vim-go#1747]
### What did you do? (required. The issue will be **closed** when not provided.)
Edited https://github.com/hashicorp/vault/blob/master/vault/logical_system.go#L69

### What did you expect to happen?
Normal keyboard motion responsiveness.

### What happened instead?
Keyboard up/dn navigation became choppy around line 75.  I played around and noticed that the presence of numerous `/*` in the strings was related to the slowdown.  Made an extreme case by repeating line 85 many times and the file is barely usable in this section: https://gist.github.com/kalafut/efe4c028672df01e2dd93e8c4f358d72#file-logical_system-go-L85

Eventually traced the slowdown to package comment folding. When I turn package comment folding off via `let g:go_fold_enable = ['block', 'import', 'varconst' ]` in .vimrc, performance is fine.  So something about that pattern of text is really killing the package fold regex/logic.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 24 2018 08:30:22)
macOS version

* Go version (`go version`):
go1.10 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kalafut/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kalafut/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y1/vdw7z6tn3wj1drd98jmwwsdc0000gn/T/go-build427136356=/tmp/go-build -gno-record-gcc-switches -fno-common"

* vim-go version:
1.17

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
Simply enabling vim-go (no other plugins, no customization) will show the slow performance. Adding `let g:go_fold_enable = ['block', 'import', 'varconst' ]` will improve the performance.

**Comment by Carpetsmoker** [comment]
The regular file seems to work okay for me, but the [test case](https://gist.github.com/kalafut/efe4c028672df01e2dd93e8c4f358d72#file-logical_system-go-L85) is indeed rather slow.

I guess the problem is that the syntax [looks for the `start=` everywhere](https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L445). I'm not sure how to improve on that, other than perhaps limiting that to just the first line, or first bunch of lines. Although that may cause problems when people use excessive long copyright headers at the top of all their files (\*cough\* GPL \*cough\*).

**Comment by kalafut** [comment]
One idea, and I've not played with it yet, would be to work the beginning of document (`\%^`) into the regex. We know that the pattern has to be: [start of doc] [optional comment] ["package"].  There is no need for the regex to continue searching once it has passed "package", starting from the top of the doc. I think this would eliminate a lot of the unnecessary matching that it's attempting.

**Comment by Carpetsmoker** [comment]
FYI, I added a script to benchmark the syntax file in #1774. You can use it with any Go file, so you can use the test case you created.

**Comment by kalafut** [comment]
Thanks. I did a very quick test a few days ago that looked promising. I hope to get back to close this out soon.
