### ISSUE TITLE
in configs 'vet' runs govet, not "go vet"

### ISSUE THREAD

**Issue by kswope** [fatih/vim-go#1748]
### What did you do? (required. The issue will be **closed** when not provided.)

From my init.vim or from multiple places in documentation

let g:go_metalinter_autosave_enabled = ['vet', 'golint']

let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']

### What did you expect to happen?

Runs
```
go vet
```

### What happened instead?

runs
```
govet
```

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):

NVIM v0.2.2                                                                                                      
Build type: RelWithDebInfo 

* Go version (`go version`):

go version go1.10 linux/amd64

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kevin/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kevin/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build332877968=/tmp/go-build -gno-record-gcc-switches"
```

* vim-go version:

No idea, just updated with PlugInstall

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

Provided above

**Comment by bhcleek** [comment]
Thank you for taking the time to create an issue.

`gometalinter` uses `govet` instead of `go vet`. See https://github.com/fatih/vim-go/issues/1530
