### ISSUE TITLE
Warning markers are not reacting to code changes in case go_metalinter_autosave is enabled

### ISSUE THREAD

**Issue by svarogg** [fatih/vim-go#1750]
### What did you do? (required. The issue will be **closed** when not provided.)
Note: this is only one way to reproduce the problem. This happens with any type of warning.

1. Write some exported function (Don't add a comment above it)
2. Save the file
3. Expect warning appear in location list, saying function "should have comment or be unexported"
4. Expect warning marker appear at function's line, looking like 'S>'.
5. Add a comment as suggested by linter
6. Save the file again
7. Expect warning to disappear
8. Expect warning marker to disappear

### What did you expect to happen?
steps 3, 4, 7 and 8 should happen

### What happened instead?
Step 4 only happens if you select a warning and press Enter
Step 8 doesn't happen unless you execute :e! or something similar that reloads the buffer

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
NVIM v0.2.0
Build type: RelWithDebInfo

* Go version (`go version`):
go version go1.10 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/{user}/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/{user}/dev/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build920689159=/tmp/go-build -gno-record-gcc-switches"

* vim-go version:
v1.17
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
Using the "Ultimate vimrc" from https://github.com/amix/vimrc and also:

```
let g:go_auto_sameids = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
let g:go_auto_type_info = 1
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:deoplete#sources#go#pointer = 1
```

if I comment out `let g:go_metalinter_autosave = 1` everything works fine

**Comment by fatih** [comment]
> Expect warning marker appear at function's line, looking like 'S>'.

This is not vim-go. You must be using a different plugin. Please disable all plugins and only use vim-go, you'll see that there is no marker at all. Please reopen if you think this is vim-go related after testing it with just vim-go. Thanks.
