### ISSUE TITLE
There should be a way to open the quickfix full width

### ISSUE THREAD

**Issue by rahenri** [fatih/vim-go#1757]
Just opening it like ":botright copen" should do the trick. There could be a flag to control that behavior.

### What did you do? (required. The issue will be **closed** when not provided.)

Open go file with a compilation error
vertical split with :vsp
compile with GoBuild

### What did you expect to happen?

There should be a way to make the quickfix window open full width of the screen

### What happened instead?

quickfix window always opens on the rightmost pane

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):

NVIM v0.2.0  

* Go version (`go version`):

go version go1.8.3

* Go environment (`go env`):

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/raphael/relay/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build964880392=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

* vim-go version:

1.16

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

an empty one that just adds vim-go works

**Comment by bhcleek** [comment]
For the time being, you can get the behavior you want by putting `autocmd filetype qf wincmd J` in your vimrc.

**Comment by rahenri** [comment]
Nice trick, thanks!

**Comment by Rican7** [comment]
> For the time being, you can get the behavior you want by putting `autocmd filetype qf wincmd J` in your vimrc.

Commenting here for future reference, as this came up in search.

While adding `autocmd filetype qf wincmd J` to your vimrc will work, its not ideal, as "location lists" _also_ share the `qf` filetype.

If you'd like to set all quickfix windows to open full-width at the bottom, without effecting window-local location-lists, add this to your vimrc instead:

```vim
" Position the (global) quickfix window at the very bottom of the window
" (useful for making sure that it appears underneath splits)
"
" NOTE: Using a check here to make sure that window-specific location-lists
" aren't effected, as they use the same `FileType` as quickfix-lists.
autocmd FileType qf if (getwininfo(win_getid())[0].loclist != 1) | wincmd J | endif
```

(See https://github.com/Rican7/dotfiles/commit/5e00fa97267dcdef5b76f5289aefea14edcc2fc5 for example)
