### ISSUE TITLE
Opening `.go` files gives an "Invalid argument: env" error in "go#complete#Info"

### ISSUE THREAD

**Issue by t-0-m-1-3** [fatih/vim-go#1762]
### What did you do? (required. The issue will be **closed** when not provided.)
removed and reinstalled `vim-go` after reinstalling `go` itself

### What did you expect to happen?
business as usual

### What happened instead?
when opening a file 

```
Error detected while processing function <SNR>144_auto_type_info[3]..go#tool#Info[3]..go#complete#Info[2]..<SNR>256_async_info:
line   73:
E475: Invalid argument: env
```

### Configuration (**MUST** fill this out):

* vim-go version:
latest, i cloned today

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
i use these, with the additional settings from the `vim-go-tutorial`
[vim ultimate](https://github.com/amix/vimrc)
* Vim version (first three lines from `:version`):
```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 20:13:43)
Included patches: 1-197, 322, 377-378, 422, 550
Modified by pkg-vim-maintainers@lists.alioth.debian.org
```
* Go version (`go version`):
1.10
* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/t0m/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/t0m/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build553614837=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by Carpetsmoker** [comment]
The `env` parameter wasn't added to `job_start()` until Vim 8.0.902: https://github.com/vim/vim/commit/05aafed54b50b602315ae55d83a7d089804cecb0, and you're using Vim 8.0.197 (with some select patches applied).

Since https://github.com/fatih/vim-go/commit/b237f52ef7229fd3181330c4197aa1b97270b669 this uses the `env` parameter. (FYI @bhcleek)

I don't know if there is a better way to fix it, but the easiest way to fix it *right now* is to use a recent Vim version.

**Comment by bhcleek** [comment]
Yeah, the env parameter is basically required. The workarounds aren't worth the trouble.

**Comment by t-0-m-1-3** [comment]
my apologies, i updated vim and it worked like a charm.

**Comment by Carpetsmoker** [comment]
I've re-opened this issue as I think we should add a version check (or something) for this. Unfortunately too many distros insist on shipping with arbitrary Vim versions over a year old :-(
