### ISSUE TITLE
Debugger: Allow usage of multiple debugging backend

### ISSUE THREAD

**Issue by fntlnz** [fatih/vim-go#1764]
First things first: The new debugging feature is AWESOME.
In some cases could be super useful to be able to use a different backend than the `default` one while using the debugger.
In particular, delve supports:

```
default		Uses lldb on macOS, native everywhere else.
native		Native backend.
lldb		Uses lldb-server or debugserver.
rr		Uses mozilla rr (https://github.com/mozilla/rr).
```

Wdyt?

**Comment by Carpetsmoker** [comment]
Does it ever make sense to use something other than the default? I'm not opposed to adding this, but only when people are actually going to use/need it, and not just for the sake of it.

**Comment by bhcleek** [comment]
closed for lack of feedback
