### ISSUE TITLE
:GoDef trips guru error message

### ISSUE THREAD

**Issue by thatjames** [fatih/vim-go#1766]
### What did you do? (required. The issue will be **closed** when not provided.)
    :GoDef

### What did you expect to happen?
Guru runs

### What happened instead?
Received error message: vim:go Run 'guru -help' for more information.

### Configuration (**MUST** fill this out):

* vim-go version: 37fa8bc

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

https://gist.github.com/thatjames/e2ac9fdb6e734816cd6ed9d38f798ff7#file-vimrc

* Vim version (first three lines from `:version`):
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
```

* Go version (`go version`):

`go version go1.9.2 linux/amd64`

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/grey/gopath"
GORACE=""
GOROOT="/home/grey/.versions/go"
GOTOOLDIR="/home/grey/.versions/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build326176790=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
Git bisect indicates the issue appeared in commit ae4113148843856ef87460211cd17888ca7a8da4

**Comment by Carpetsmoker** [comment]
Hm, this seems to work correct for me.

Can you try updating your `guru` version with `:GoUpdateBinaries`?

**Comment by geoffcorey** [comment]
I have the same issue after doing a +PlugUpdate on NeoVim

After I found I had to upgrade python neovim
Reran +PlugUpdate
Remove vim-go and reinstalled
Ran :GoUpdateBinaries

When doing a `gd` aka GoDef I still get an error message `vim-go: Run guru --help for more information`

**Comment by geoffcorey** [comment]
Followup -

I replaced guru with a bash script that dumps the arguments passed.  Using that dump I passed to the real guru command and seems to work fine.

Edited the path but just want to show the args being passed.   
```-tags -json what /Users/geoffcorey/src/github.com/geoffcorey/myprojecti/main.go:#32```

So I'm not sure why NeoVim is displaying guru --help unless there is a follow up commend I am missing.

**Comment by geoffcorey** [comment]
The details
```
go version go1.10.1 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gwcorey@us.ibm.com/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/geoffcorey/"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_f/6dzq19pj0lq8ffzvvty913q80000gn/T/go-build594948376=/tmp/go-build -gno-record-gcc-switches -fno-common"

NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
```

**Comment by lukatendai** [comment]
the same problem here, however VIM works, only neovim has a problem

**Comment by lukatendai** [comment]
I am using self-built version from master:

NVIM v0.2.3-968-g7034feb66
Build type: Release
LuaJIT 2.0.5

I built it today. Everything was working fine, till I updated plugins and go binaries

**Comment by fervic** [comment]
Same problem here:

```
vim-go version:
37fa8bc6447eacc36eefe7bea35a9813f333e30a
```

```
Linux version 4.15.15-1-ARCH
```

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
```

```
go version go1.10.1 linux/amd64
```

**Comment by geoffcorey** [comment]
Confirmed.  Seems to work on Vim but not NeoVim.   When I use the mock bash script for guru both are sending the same arguments so I'm not sure what the difference would be.

**Comment by stevenroose** [comment]
Having the same issue.
```
$ nvim --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5

$ go version
go version go1.10 linux/amd64

$ uname -srvo
Linux 4.15.13-1-ARCH #1 SMP PREEMPT Sun Mar 25 11:27:57 UTC 2018 GNU/Linux
```

Arch Linux
vim-go: 434b824bb08c841d627f9ecd768e31de56025fda

**Comment by thatjames** [comment]
Confirmed fixed, thanks 👯‍♂️

**Comment by nmahoney-pivotal** [comment]
Thanks for the fix!
