### ISSUE TITLE
GoTest only seems to work if I'm in the same directory as source files

### ISSUE THREAD

**Issue by akostibas** [fatih/vim-go#1768]
### What did you do? (required. The issue will be **closed** when not provided.)

* The root of my project has no Go files in it, but it's often where I start my editor (eg. `vi pkg/models/user.go`)
* When opened in this way and I execute `:GoTest` I get an error: `can't load package: package github.com/xxx/yyy/pkg: no Go files in /Users/alexi/Documents/projects/golang/src/github.com/xxx/yyy/pkg`
* If I `cd` into any directory in my project that has Go source files, I'm able to run the tests.

### What did you expect to happen?

I'd expect to be able to run the tests of the file I have open regardless of what directory I was in when I opened vi.

### Configuration (**MUST** fill this out):

* vim-go version: `cc0467c3c567b9e95a694f160f2d5cd1cd21dad4`

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

Nothing relevant.

* Vim version (first three lines from `:version`):

```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
```
* Go version (`go version`): `go version go1.10.1 darwin/amd64`

* Go environment (`go env`):

```$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alexi/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alexi/Documents/projects/golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/88/t9zb01rx5g92g79q2sx6bblw0000gn/T/go-build714133284=/tmp/go-build -gno-record-gcc-switches -fno-common"```

**Comment by bhcleek** [comment]
What value do you have set for `g:go_autodetect_gopath`? What directories are in `/Users/alexi/Documents/projects/golang/src/github.com/xxx/yyy/pkg`?

**Comment by akostibas** [comment]
`g:go_autodetect_gopath` isn't set. If I set it to 1, I get:
`can't load package: package /Users/alexi/Documents/projects/golang/src/github.com/xxx/yyy: import "/Users/alexi/Documents/projects/golang/src/github.com/xxx/yyy": cannot import absolute path`

and if I set it to 0 I get:
`can't load package: package github.com/transcom/mymove: no Go files in /Users/alexi/Documents/projects/golang/src/github.com/xxx/yyy`

As for what's in `pkg/`, it's just more directories. Those directories themselves contain Go files.

The GOPATH in my shell is: `/Users/alexi/Documents/projects/golang`

**Comment by Carpetsmoker** [comment]
This works well for me, bhcleek, and as far as I know, everyone else. So there is either something wrong with your code or setup, or some specific combination that triggers a vim-go bug.

It would be extremely helpful if you could create a reproducible test. e.g. a tar.gz file with code, your *full* vimrc (minus any other plugins) that can be sued to reproduce the issue.

**Comment by Carpetsmoker** [comment]
I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.
