### ISSUE TITLE
Show sub-test failed as part of the GoTest output

### ISSUE THREAD

**Issue by gianarb** [fatih/vim-go#1797]
NB: This is not a bug report, it is a feature request
### What did you do? (required. The issue will be **closed** when not provided.)
Using the sub-test method Run like here:

```go
package test

import (
	"fmt"
	"testing"
)

func TestTest(t *testing.T) {
	f := map[string]string{
		"hello": "hello",
		"good":  "no",
	}
	for input, expected := range f {
		t.Run(fmt.Sprintf("Input %s.", input), func(t *testing.T) {
			if input != expected {
				t.Error("Wrong")
			}
		})
	}
}
```

### What did you expect to happen?
I get my vim cursor moved to the error, that's fine. But I would also like to see inside the output what sub-test failed.

The output report `Wrong`. But it's not clear which one failed.

![2018-04-13-11-03-35_677x925](https://user-images.githubusercontent.com/1630267/38726548-c22ecd90-3f0a-11e8-9a74-99937001ffbe.png)

Running `go test` via cli I have an idea about which one failed:

```
11:07 $ go test test_test.go 
--- FAIL: TestTest (0.00s)
    --- FAIL: TestTest/Input_good. (0.00s)
        test_test.go:16: Wrong
FAIL
FAIL    command-line-arguments  0.001s
```

Thanks a lot

**Comment by bhcleek** [comment]
The test name can be shown by setting `g:go_test_show_name=1`

**Comment by gianarb** [comment]
Ah great!! Thanks a lot @bhcleek !!
