### ISSUE TITLE
GoLint gives an error

### ISSUE THREAD

**Issue by dchenk** [fatih/vim-go#1798]
### What did you do? (required. The issue will be **closed** when not provided.)
:GoLint

### What did you expect to happen?
The code should be linted.

### What happened instead?
Vim gave an error:
```
|| flag provided but not defined: -1                                                                                                                                              
|| Usage of golint:
||      golint [flags] # runs on package in current directory
||      golint [flags] [packages] 
||      golint [flags] [directories] # where a '/...' suffix includes all sub-directories
||      golint [flags] [files] # all must belong to a single package
|| Flags:
||   -min_confidence float
||      minimum confidence of a problem to print it (default 0.8)
||   -set_exit_status
||      set exit status to 1 if any issues are found
```

### Configuration (**MUST** fill this out):

* vim-go version:
1.17

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
```

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)
Included patches: 1-503, 505-642
Compiled by root@apple.com

* Go version (`go version`):
go1.10 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/my/path/here/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/my/path"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9x/xp9y18vx58q815_7fp24cf5c0000gn/T/go-build519577590=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by ChanderG** [comment]
Running `:GoUpdateBinaries` has solved the issue for me, which is strange since I started with a fresh vim-go install at the time of my last comment.

**Comment by jadekler** [comment]
Also ran into this issue. `:GoUpdateBinaries` does not work for me. @fatih should I create a new issue or debug here?

**Comment by fatih** [comment]
@jadekler please re-open a new issue. Bonus points if you can provide us a Go file with the original content where you see the problem and if you can upload the binary you're using somewhere, so we can download and try it. Vim-go works fine with latest golint, not sure what the problem is you're seeing :)

**Comment by jadekler** [comment]
Thanks for the response @fatih. It appears as though my GOPATH being atypical causes the problem; `:echo go#package#ImportPath()` returns -1 for me. Do you think it's a reasonable ask to open an issue that requests there be some default behavior if -1 is returned (e.g. goimports should still work, afaik)? If not, no worries; an atypical GOPATH is my problem, not yours. :)
