### ISSUE TITLE
Unexpected auto-indent within raw string literal

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#1800]
### What did you do? (required. The issue will be **closed** when not provided.)

Create a go file with the following contents:

```go
package main

import "fmt"

func main() {
	const name = `
`
	fmt.Printf("this is my name: %v\n", name)
}
```

In normal mode, have the cursor over the `const` keyword. Now press `o` to begin a new line below the cursor and enter insert mode.

### What did you expect to happen?

The cursor should be place at the 0th column because we are within a raw string literal (cursor position indicated by `^` below; the line that includes the `^` does not exist in reality):

```go
package main

import "fmt"

func main() {
	const name = `

^
`
	fmt.Printf("this is my name: %v\n", name)
}
```

### What happened instead?

The new line is automatically indented and the cursor is placed after the indent:

```go
package main

import "fmt"

func main() {
	const name = `
	
	^
`
	fmt.Printf("this is my name: %v\n", name)
}

```

### Configuration (**MUST** fill this out):

* vim-go version: 7491209072ed4aa746e6fe7894f976ecd251801e

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 16 2018 07:40:43)
Included patches: 1-1722
Compiled by myitcv@myitcv-virtual-machine
```

* Go version (`go version`):

```
go version go1.10.1 linux/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build746364427=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by fatih** [comment]
This is fixed and merged to master. Thanks for the feedback Paul.

**Comment by myitcv** [comment]
Awesome!
