### ISSUE TITLE
Add a ``go-doc-toggle'' command

### ISSUE THREAD

**Issue by manifoldQAQ** [fatih/vim-go#1804]
### What did you do? (required. The issue will be **closed** when not provided.)
Feature request

### What did you expect to happen?
The opened pane by go-doc will close by go-doc-toggle, in this way, we can see the documentaion and return to coding quickly. Anyway , I don't want to modify the doc, right? :)

### Configuration (**MUST** fill this out):

* vim-go version:

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):

* Go version (`go version`):

* Go environment (`go env`):

**Comment by bhcleek** [comment]
The godoc window can be closed using either the escape or the enter key. re: https://github.com/fatih/vim-go/blob/master/autoload/go/doc.vim#L125-L127
