### ISSUE TITLE
GoRun not focusing on the proper split in NeoVim

### ISSUE THREAD

**Issue by manifoldQAQ** [fatih/vim-go#1806]
### What did you do? (required. The issue will be **closed** when not provided.)
execute GoRun in neovim command mode

### What did you expect to happen?
The cursor should focus on the terminal split as shown in #607

### What happened instead?
The cursor goes back to code split.

### Configuration (**MUST** fill this out):

* vim-go version:
latest

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
autocmd FileType go nmap <leader>c <Plug>(go-build)
autocmd FileType go nmap <leader>r <Plug>(go-run)
autocmd FileType go nmap <C-q> <Plug>(go-doc)
autocmd FileType go nmap <leader>i <Plug>(go-info)
autocmd FileType go nmap <leader>t <Plug>(go-test)
let g:go_list_type = "quickfix"
let g:go_fmt_command = "goimports"
let g:go_highlight_types = 1
```
* Vim version (first three lines from `:version`):
NVIM v0.3.0-dev
Build type: RelWithDebInfo
Lua 5.1

* Go version (`go version`):
go version go1.10.1 linux/amd64

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/manifold/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/manifold/repo/go"
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build877161923=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by viniarck** [comment]
I also hit this issue. Meanwhile, I'm using this workaround, if you run multiple times you'll open multiple splits though:

```
 " execute the whole project
  nnoremap <silent><Leader>l :vsplit term://go run *.go<CR>
 " execute current file
  nnoremap <silent><Leader>b :vsplit term://go run %<CR>
```

**Comment by bhcleek** [comment]
The current behavior of returning focus to the code window is intentional. See https://github.com/fatih/vim-go/issues/1412#issuecomment-374494290

**Comment by SurpassAll** [comment]
My env is neovim. Actually, the cursor will focus on the code panel, but I want focus on the output panel when exec :GoRun. So, what should I do?
