### ISSUE TITLE
GoRename doesn't work

### ISSUE THREAD

**Issue by risentveber** [fatih/vim-go#1808]
### What did you do? (required. The issue will be **closed** when not provided.)
Call `:GoRename` for some variable

### What did you expect to happen?
Renaming variable under cursor

### What happened instead?
A couple of weeks ago works perfect but now (maybe after some update) - Error occrued:
```
function go#rename#Rename[48]..<SNR>168_parse_errors
vim-go: FAILED
vim-go: flag needs an argument: -tags
vim-go: Usage of /Users/b.strelnikov/go/bin/gorename:
vim-go:   -d        display diffs instead of rewriting files
vim-go:   -diffcmd string
vim-go:             diff command invoked when using -d (default "diff")
vim-go:   -force
vim-go:             proceed, even if conflicts were reported
vim-go:   -from string
vim-go:             identifier to be renamed; see -help for formats
vim-go:   -help
vim-go:             show usage message
vim-go:   -offset string
vim-go:             file and byte offset of identifier to be renamed, e.g. 'file.go:#123'.  For use by editors.
vim-go:   -tags build tags
vim-go:             a list of build tags to consider satisfied during the build. For more information about build tags, see the description of build constraints in the documentation for the go/build package
vim-go:   -to string
vim-go:             new name for identifier
vim-go:   -v        print verbose information
```

### Configuration (**MUST** fill this out):

* vim-go version: commit ae41131

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`): NVIM v.0.2.2

* Go version (`go version`):go version go1.10.1 darwin/amd64
* Go environment (`go env`): GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/b.strelnikov/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/b.strelnikov/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5j/5c2v5jcx2xs1d5d3wyrk7pz40000gp/T/go-build393243272=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bhcleek** [comment]
This was resolved in https://github.com/fatih/vim-go/pull/1771 (it was merged in https://github.com/fatih/vim-go/commit/32ae8640716530bd55062379177da51efb37dfd2, 3 days after ae41131).
