### ISSUE TITLE
**Omni completion (^O^N^P) Pattern not found** error encountered on typing <C-x><C-o>

### ISSUE THREAD

**Issue by gautamkvashisht** [fatih/vim-go#1825]
### What did you do? (required. The issue will be **closed** when not provided.)
After installing **vim-go** plugin in _GVim_ using **vim-plug**, I opened a Go program and started programming in Go. Then I typed `<C-x><C-o>` in Vim to get code completion suggestions.

### What did you expect to happen?
I expected it to give code completion suggestions.

### What happened instead?
But I'm getting `-- Omni completion (^O^N^P) Pattern not found`.

### Configuration (**MUST** fill this out):

* vim-go version: 1.17

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc): 
```
" vim-plug configuration
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" vim-go plugin
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" Initialize plugin system
call plug#end()

let g:lightline = {
  \     'active': {
  \         'left': [['mode', 'paste' ], ['readonly', 'filename', 'modified']],
  \         'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding']]
  \     }
  \ }

let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
let g:go_auto_sameids = 1
let g:go_fmt_command = "goimports"
let g:go_auto_type_info = 1

filetype plugin on
```
* Vim version (first three lines from `:version`): 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 05 2018 16:15:22)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.
```

* Go version (`go version`): go1.10.2 linux/amd64

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN="/home/gkv/go/bin"
GOCACHE="/home/gkv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gkv/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build213799803=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by Carpetsmoker** [comment]
Why do you have:

    set omnifunc=syntaxcomplete#Complete

You're also loading some other Go completion plugin it seems?

    " Code completion in Go
    Plug 'mdempsky/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }

Please:

1. Try and reproduce with a smaller vimrc which adds less other stuff.
2. If it still doesn't work, please add more details about what you did. e.g. which code you used. Right now all it says it "it doesn't work". Well, clearly it *does* work for many people, so just "it doesn't work" isn't very useful.

**Comment by gautamkvashisht** [comment]
Thanks. I removed some additonal plugins from my .gvimrc and now <C-x><C-o> seems to be working. But I want to know how do I get autocompletion as I type because then I won't have to do <C-x><C-o> repeatedly.

**Comment by fatih** [comment]
> But I want to know how do I get autocompletion as I type because then I won't have to do repeatedly.

Checkout these plugins:
https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L130

I'm closing this as I think this is resolved right now.
