### ISSUE TITLE
Feature request: automatic underscore

### ISSUE THREAD

**Issue by zwhitchcox** [fatih/vim-go#1829]
So, it would be great if there were a setting to automatic underscore unused variables during development. Often, I will be writing a chunk of code and have a variable I'm going to use in one minute, but I just need to test something else, and it makes me underscore it out. Ideally there would be a setting in go to turn this off, but I do not know of that functionality anywhere. It would be great if this could be done automatically, so it didn't slow down my work flow and make me lose my train of thought so much.

**Comment by zwhitchcox** [comment]
Maybe commenting out would be a better solution, so you don't lose the variable name

**Comment by fatih** [comment]
The idea is great, but that would require a new tool, that understands the program and makes sure automatically unassign them. To implement it in vim-go, we need to implement such a tool. Unless there is one, I don't think we have the bandwidth to work on this. Thanks!
