### ISSUE TITLE
feature request: auto install package and deps on save.

### ISSUE THREAD

**Issue by sicojuy** [fatih/vim-go#1835]
### What did you do? (required. The issue will be **closed** when not provided.)
Auto complete does not work with my own packages, only if I exec "go install" for the packages.

### What did you expect to happen?
When I save file, auto install the packages.

### Configuration (**MUST** fill this out):

* vim-go version: 
master branch

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5

* Go version (`go version`): 
go version go1.10.1 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/liaoziqian/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/liaoziqian/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sw/cpl5gg9x2rz929rskpt1htnh0000gn/T/go-build518698052=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by Carpetsmoker** [comment]
I think this would be a lot of work for very surprising behaviour that almost no one wants.

**Comment by sicojuy** [comment]
@Carpetsmoker Hi, [vscode-go](https://github.com/Microsoft/vscode-go) has supported this feature. I have no experience with development vim plugin. If no one want to do this, I will try to do it.

**Comment by bhcleek** [comment]
If it's just an autocompletion problem, can you please provide replication steps? I use autocompletion frequently and do not encounter the behavior you're describing.
 
Relatedly, have you set `g:go_code_autobuild`?

**Comment by sicojuy** [comment]
I'm sorry, it's my problem. When I use vim with a simple vimrc configuration. The problem can not reproduce. I think that the problem is in my vim configuration. Thanks @bhcleek @Carpetsmoker .
