### ISSUE TITLE
How to Vertical Alignment?

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [fatih/vim-go#1837]
Is there any way to vertical align go code (see example below) with vim-go (or any other packages)?

amely aligning vertically. For example:

```
s := a()
something := a()
somethingLonger := a()
```

could be:

```
s               := a()
something       := a()
somethingLonger := a()
```

**Comment by bhcleek** [comment]
All code is formatted with `gofmt`. You can get what you're looking for by wrapping the variables that you want to align in a var statement:

```
var (
	s               = a()
	something       = a()
	somethingLonger = a()
)
```



https://go-proverbs.github.io/ : 
> Gofmt's style is no one's favorite, yet gofmt is everyone's favorite

**Comment by Carpetsmoker** [comment]
`gofmt` will put it back anyway, so it's not useful.

Also there are many plugins that do this: https://duckduckgo.com/lite/?q=vim%20align – no need to duplicate this in vim-go, I think.

**Comment by CodeMonkeyKevin** [comment]
ok, thanks
