### ISSUE TITLE
interface keyword does not get auto-completed

### ISSUE THREAD

**Issue by stefanos82** [fatih/vim-go#1838]
Specs:
```txt
Vim 8.0.1766
vim-go: the latest (GoUpdateBinaries)
System: GNU / Debian testing 64-bit
Go version: 1.10.1
```
When I type `inter` and press tab key, nothing happens. Other keywords get auto-completed without a problem.

Is this behavior normal?

**Comment by Carpetsmoker** [comment]
I'll assume you're using `gocode`, which is the default completion that vim-go uses with omnicomplete. It doesn't complete keywords; only built-in types.

See https://github.com/nsf/gocode/issues/312

If you want to add it, you can start by looking at:
https://github.com/nsf/gocode/blob/46e8fd2234a86934e3e8496c7405984ff7b18df5/_gccgo/package.go#L14
https://github.com/nsf/gocode/blob/f1eef9a6ba005abb145d7b58fdd225e83a3c6a05/package_bin.go#L783
https://github.com/nsf/gocode/blob/d7aee89652f1bd8ca319c64d6dee1bc1dfd9b6ef/decl.go#L1411

Not familiar with the code, but that's what I found with a quick search for `uint64`.
