### ISSUE TITLE
Doesn't respect GoDebugCurrent/GoDebugBreakpoint highlight group customizations

### ISSUE THREAD

**Issue by mkomitee** [fatih/vim-go#1839]
### What did you do? (required. The issue will be **closed** when not provided.)

I tweaked my colorscheme to specify a different highlight group configuration for GoDebugCurrent.

### What did you expect to happen?

When I started debugging, I expected the current line to be highlighted using my customizations.

### What happened instead?

When I started vim, I checked, and my customizations were applied, but when I started my debug session, it was overridden with the defaults from autoload/go/debug.vim.

### Configuration (**MUST** fill this out):

* vim-go version: 7ac1e62fa30d84946e93a3820bb6cf6a431186ed

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

After installing vim-go using the recommended method for vim8 packages, the following vimrc can be used to replicate the problem:

```
runtime defaults.vim

augroup custom
  autocmd!
  autocmd FileType go hi! GoDebugCurrent term=underline ctermbg=237 guibg=#3c3836
augroup END
```

After opening a simple main.go file, the GoDebugCurrent highlight group from the vimrc is applied, but after actually starting a debug session, the defaults have been installed.

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr  3 2018 10:22:54)
Included patches: 1-1655
```

I compiled it myself, so the third line shows the host on which it was built.

* Go version (`go version`):
```
go version go1.10.2 linux/amd64
```

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mkomitee/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mkomitee/go"
GORACE=""
GOROOT="/home/mkomitee/go-1.10.2"
GOTMPDIR=""
GOTOOLDIR="/home/mkomitee/go-1.10.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build012171596=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by Carpetsmoker** [comment]
It's loaded when `autoload/go/debug.vim` is loaded – see the bottom of that file.

Maybe add check if it's already defined, or a custom autocmd? Patches welcome ;-)

**Comment by Carpetsmoker** [comment]
Great, thanks! I'm about to head off for a few days, I'll look when I get back.
