### ISSUE TITLE
Is there a way to put GoLint issues and errors in the gutter?

### ISSUE THREAD

**Issue by trstringer** [fatih/vim-go#1844]
### What did you do? (required. The issue will be **closed** when not provided.)

Normal development with vim-go.

### What did you expect to happen?

I'd like to see the vim "gutter" show that there are linting issues or errors in the code without having to run `:GoLint` explicitly.

### What happened instead?

No view of errors, have to run `:GoLint` to see them.

### Configuration (**MUST** fill this out):

* vim-go version: latest

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc): https://github.com/trstringer/dotfiles/blob/master/.vimrc

* Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 23 2018 12:15:34)
Included patches: 1-20
Modified by <bugzilla@redhat.com>

* Go version (`go version`): go version go1.10.2 linux/amd64

* Go environment (`go env`):

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/trstringer/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/trstringer/dev/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build620522669=/tmp/go-build -gno-record-gcc-switches"

**Comment by Carpetsmoker** [comment]
Vim-go doesn't have that feature right now, but you can use ALE of Syntasic, which work just as well – if not better – than vim-go for linting.

**Comment by trstringer** [comment]
Perfect thank you!
