### ISSUE TITLE
Suggestion: Allow echon messages to be disabled

### ISSUE THREAD

**Issue by LeOtaku** [fatih/vim-go#1848]
When using vim-go in conjunction with other plugins/mappings the "echo/echon" status messages can sometimes mess things up. In my case this only results in minor visual quirks ("text glitching" because of rapid updates) but I would still like to be able to remove them.

(I removed the default bug report layout, because it doesn't really make sense here, I hope this is not a problem)

**Comment by Carpetsmoker** [comment]
What *exactly* is causing problems, and what would you expect to happen? How is Vim-go supposed to communicate with the user if it can't `echo` stuff?

There are some options to make vim-go a bit less verbose btw: `g:go_echo_go_info` and `g:go_echo_command_info`. See the `:help` pages for them as well.

**Comment by Carpetsmoker** [comment]
I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.

**Comment by LeOtaku** [comment]
This problem magically fixed itself one day after reporting the bug. Sorry for not getting back to you/closing the issue myself.
