### ISSUE TITLE
Autocomplete broken in vim 8.1

### ISSUE THREAD

**Issue by tobstarr** [fatih/vim-go#1860]
### What did you do? (required. The issue will be **closed** when not provided.)
Try to use autocomplete (<C-x><C-o>) in vim 8.1 (the new default in fedora)

### What did you expect to happen?
autocomplete to work as with vim 8.0

### What happened instead?
the autocomplete menu is completely broken (the menu box no longer disappears and for vim somehow changes the most recent files). The initial box shows up but everything after that is then broken.

### Configuration (**MUST** fill this out):

* vim-go version:

tested with HEAD (1b98bd8) and v1.17

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
filetype plugin off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'fatih/vim-go'
call vundle#end()
filetype plugin indent on
```

* Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun  6 2018 10:52:31)
Included patches: 1-35
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
```

* Go version (`go version`):
go1.10.2

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root"
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build167525075=/tmp/go-build -gno-record-gcc-switches"
```
(executed in a standard docker container run via `docker run -t -i --rm fedora:28 bash` and then installing `dnf install -y vim go`).

**Comment by fatih** [comment]
It chould be `gocode`. Can you remove the `gocode` binary and try this PR: https://github.com/fatih/vim-go/pull/1853 this doesn't have autobuild, so you have to `:GoInstall` before starting the auto completing.

**Comment by bhcleek** [comment]
Before trying #1853, make sure gocode isn't running and then try autocomplete again; I've seen gocode hang sometimes, causing Vim to never render the autocomplete dialog.

Also, make sure gocode isn't running before going to #1853 otherwise you may not be testing what you think you're testing :-).

**Comment by tobstarr** [comment]
I can confirm that things are working with the code from #1853 using this setup https://github.com/tobstarr/vim-8.1-test in a docker container!

**Comment by apiarian** [comment]
I'm having a similar problem between vim-go and `maralla/completor.vim`. Completion shows up but then locks in the open panel. Tried #1853 gocode with no difference. Uninstalling completor makes the problem go away, but the built-in omnicompletion strings from the file itself aren't as useful as proper go-specific completions.

**Comment by apiarian** [comment]
If I roll back from MacOS homebrew `macvim` `8.1-148` to `8.1-147` the problem goes away.

**Comment by flowerinthenight** [comment]
I can confirm @apiarian 's comment as well.

**Comment by zerowidth** [comment]
Good catch, @apiarian. While there may be other issues with `gocode`, this appears to be an issue with `8.1-148` that was patched upstream but hasn't made it into macvim yet, macvim-dev/macvim#691. Once I reinstalled `8.1-147` my completion (with `maralla/completor.vim`) works again.

**Comment by tobstarr** [comment]
Just a quick update from my side. I tested everything with the same version of vim-go (v1.17) but with an updated version of vim (8.1.95 instead of 8.1.35) and now things seem to work again (without even the need to recompile `nsf/gocode`). Looks more like an issue with vim then vim-go I suppose?
