### ISSUE TITLE
GoTest nolonger works

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [fatih/vim-go#1868]
### What did you do? (required. The issue will be **closed** when not provided.)
Ran :GoTest in both inside and outside $GOPATH

### What did you expect to happen?
It checking for errors

### What happened instead?
If ran inside $GOPATH i get the error 
`can't load package: package /home/simon/Code/go/src/Programs/gate/client: import "/home/simon/Code/go/src/Programs/gate/client": cannot import absolute path`
If ran outside $GOPATH i get the error
`You are not in a go package`

This started happening out of nowhere, it worked a few days ago. I'm using arch so it could be an update that screwed everything up

### Configuration (**MUST** fill this out):

* vim-go version:
1.17-1

* `vimrc`:
https://pastebin.com/NQD2YGbF

* Vim version:
NVIM v0.3.0

* Go version:
go version go1.10.3 linux/amd64

* Go environment:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/simon/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/simon/Code/go/"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build076969175=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by Carpetsmoker** [comment]
Looks like you have `import "/home/simon/Code/go/src/Programs/gate/client"` in your Go code? Like the error says: `cannot import absolute path`.

**Comment by AlmightyFloppyFish** [comment]
Nope, that's the point. Doesn't matter what go file it is. Could just be an empty main loop with 0 imports.

I should prob mention that the file it says it cannot import is the file i have open and trying to test. Not sure why you closed the issue here

**Comment by AlmightyFloppyFish** [comment]
Solved by removing the vim-gocode package. Most likely was in conflict with vim-go.
