### ISSUE TITLE
Can't get install to work

### ISSUE THREAD

**Issue by ahraber** [fatih/vim-go#1869]
### What did you do? (required. The issue will be **closed** when not provided.)
installed plugin via several methods, vim8 plugin, pathogen, zip, etc. essentially a fresh install, no other custom vim plugins before this.

### What did you expect to happen?
Propper installation.

### What happened instead?
Didn't install properly.  I can use `:help vim-go` and `:GoUpdateBinaries` and `:GoPath` and `:GoInstallBinaries` . All the other commands I'm expecting to use don't work.

:scriptnames:
```
  1: /etc/vimrc                                                                                                                                                  
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: /usr/share/vim/vim81/defaults.vim
  4: /usr/share/vim/vim81/syntax/syntax.vim
  5: /usr/share/vim/vim81/syntax/synload.vim
  6: /usr/share/vim/vim81/syntax/syncolor.vim
  7: /usr/share/vim/vim81/filetype.vim
  8: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
  9: /usr/share/vim/vimfiles/ftdetect/conkyrc.vim
 10: /usr/share/vim/vimfiles/ftdetect/gofiletype.vim
 11: /usr/share/vim/vim81/ftplugin.vim
 12: /usr/share/vim/vim81/indent.vim
 13: /usr/share/vim/vimfiles/plugin/fzf.vim
 14: /usr/share/vim/vimfiles/plugin/go.vim
 15: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
 16: /usr/share/vim/vim81/plugin/gzip.vim
 17: /usr/share/vim/vim81/plugin/logiPat.vim
 18: /usr/share/vim/vim81/plugin/manpager.vim
 19: /usr/share/vim/vim81/plugin/matchparen.vim
 20: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 21: /usr/share/vim/vim81/plugin/rrhelper.vim
 22: /usr/share/vim/vim81/plugin/spellfile.vim
 23: /usr/share/vim/vim81/plugin/tarPlugin.vim
 24: /usr/share/vim/vim81/plugin/tohtml.vim
 25: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 26: /usr/share/vim/vim81/plugin/zipPlugin.vim
 27: ~/.vim/pack/plugins/start/vim-go/plugin/go.vim
 28: ~/.vim/pack/plugins/start/vim-go/ftdetect/gofiletype.vim
```

### Configuration (**MUST** fill this out):

* vim-go version: 
v1.17 tag

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
empty, also tried with various examples other people posted

* Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:52:08)
Included patches: 1-22
Compiled by Arch Linux
```

* Go version (`go version`):
1.10.3

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN="/home/me/go/bin"
GOCACHE="/home/me/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/me/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR="/home/me/tmp"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/home/me/tmp/go-build618909547=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by ahraber** [comment]
Peculiar update -- when I type `:help go` and tab complete, I see all of the functions. I just cannot execute them from within go. When I try `:GoBuild` for example, it returns: `GoBuild: Not an editor command`.

**Comment by ahraber** [comment]
Figured it out. :joy:

**Comment by ahraber** [comment]
Figured it out, I cleaned everything up and reinstalled. Been working w/ it for about 3 hours and no problems. :+1:

**Comment by oshriPP** [comment]
> Figured it out, I cleaned everything up and reinstalled. Been working w/ it for about 3 hours and no problems. 👍

I'm having the same issue, I tried to delete the `~/.vim` and reinstall the plugin but without success. 
What do you mean by clean everything?     
How do you install the plugin? 
To install, I ran these lines. 

```
git clone https://github.com/fatih/vim-go.git  ~/.vim/pack/plugins/start/vim-go
git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go
```

Thank you.
