### ISSUE TITLE
Vgo Support

### ISSUE THREAD

**Issue by llimllib** [fatih/vim-go#1870]
### What did you do? (required. The issue will be **closed** when not provided.)

* Create a module outside of `$GOPATH`, using vgo
* hack hack hack
* Notice that vim was complaining about perfectly valid code
  * example: `go vet` complains that it can't find my imports; `vgo vet` is silent

### What did you expect to happen?

* I guess in the short term, I'd like to be able to change the go binary name to `vgo`? For example, [lint.vim says](https://github.com/fatih/vim-go/blob/32ae8640716530bd55062379177da51efb37dfd2/autoload/go/lint.vim#L119):

```vim
    let [l:out, l:err] = go#util#Exec(['go', 'vet', go#package#ImportPath()])
```

But I'd like to substitute `vgo` for `go` there, perhaps with a global go binary variable?

(I would be happy to work on a PR for this if you would guide me as to how you think it ought to work)

### What happened instead?

I got go vet errors

### Configuration (**MUST** fill this out):

* vim-go version: I don't know how to find this, but it's recent and the problem exists in master, as shown above

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc): no vimrc necessary, easy to repro

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 13 2018 06:21:30)
macOS version
Included patches: 1-1700
```

* Go version (`go version`): `go version go1.10.3 darwin/amd64`

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN="/Users/llimllib/go/bin"
GOCACHE="/Users/llimllib/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/llimllib/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4l/0mttg4pd53q5q7xkrgsbbv0w0000gn/T/go-build279233207=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by Carpetsmoker** [comment]
You can't really do this. See the "I want to use a different binary name than "go", can I do this?" section in `:help  go-troubleshooting` how to use `vgo` instead of `go`.

The `vgo` binary name is just an experiment, and eventually it should get integrated in the regular `go` command, so I don't think it's worth adding support for this experimental version.

**Comment by llimllib** [comment]
Very well, thanks for the response
