### ISSUE TITLE
:GoInstallBinaries thinks it works, actually does nothing, :GoInstall doesn't pull

### ISSUE THREAD

**Issue by zilman** [fatih/vim-go#1872]
### What did you do? (required. The issue will be **closed** when not provided.)

:GoInstallBinaries

### What did you expect to happen?

> vim-go: gogetdoc not found. Installing github.com/zmb3/gogetdoc to folder /Users/Gene/Go/bin/
vim-go: guru not found. Installing golang.org/x/tools/cmd/guru to folder /Users/Gene/Go/bin/
vim-go: golint not found. Installing github.com/golang/lint/golint to folder /Users/Gene/Go/bin/
...

### What happened instead?

`/Users/Gene/Go/bin/` remains unmodified

If I do `go get -v github.com/zmb3/gogetdoc` it will show up in `/Users/Gene/Go/src/github.com/` and `/Users/Gene/Go/bin`, if I delete it from the later and run `:GoInstall github.com/zmb3/gogetdoc`, it will now place a gogetdoc binary in `/Users/Gene/Go/bin`.

Finally if I do `:GoInstall github.com/rogpeppe/godef` for example (something I didn't go get prior), it comes back with: 

```
|| package github.com/rogpeppe/godef: cannot find package "github.com/rogpeppe/godef" in any of: /usr/local/Cellar/go/1.10.3/libexec/src/github.com/rogpeppe/godef (from $GOROOT) /Users/Gene/Go/src/github.com/rogpeppe/godef (from $GOPATH)
```
### Configuration (**MUST** fill this out):

* vim-go version: v1.17

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

> Plug 'fatih/vim-go'

I tried tinkering with the following lines to no effect (currently they are all commented out):

```
" format with goimports instead of gofmt
" let g:go_fmt_command = "goimports"
" let g:go_autodetect_gopath = 0
" let g:go_bin_path = ""
" let $GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
```

* Vim version (first three lines from `:version`):
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5

* Go version (`go version`):
go version go1.10.3 darwin/amd64

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Gene/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Gene/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ws/2xpp7b5n3vj5h69xf79hqfnw0000gn/T/go-build269716848=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

> echo $GOPATH
> /Users/Gene/Go

> echo $PATH
> /usr/local/opt/sqlite/bin:/Users/Gene/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Gene/Go/bin:/usr/local/opt/go/libexec/bin

> :echom system("echo $GOPATH")
> /Users/Gene/Go^@

**Comment by bhcleek** [comment]
I am unable to duplicate the issue you described with `:GoInstallBinaries`; packages are retrieved and installed as expected for me on every attempt.

`:GoInstall` requires the package to be available on your system; it simply calls `go install` and does not do a `go get` first.
