### ISSUE TITLE
How can I install vim-go?

### ISSUE THREAD

**Issue by agn-7** [fatih/vim-go#1875]
In the readme document, install stable version mentioned instead of using master branch.   
Then I get the source-code from this [link](https://github.com/fatih/vim-go/releases/tag/v1.17).   
but I can't see the installation tutorial, I only found a **docker-file** on this package, Is this package installation via docker? or if another way to install, please guide me.

**Comment by juanwolf** [comment]
If you downloaded the sources, you need to place the vim-go directory inside `~/.vim/pack/plugins/start/`

**Comment by agn-7** [comment]
Is there another way without download the source code?

**Comment by juanwolf** [comment]
You could use a Plugin Manager such as [vim-plug]( https://github.com/junegunn/vim-plug) where you can specify the tags you want to install: https://github.com/junegunn/vim-plug#example or [Pathogen](https://github.com/tpope/vim-pathogen).

There's many others, here's a quick list: https://www.slant.co/topics/1224/~plugin-managers-for-vim

**Comment by juanwolf** [comment]
@agn-7 Any news?

**Comment by fatih** [comment]
You can use pathogen and git clone the specific tag or you can use `vim-plug` by setting an explicit tag:

```
Plug 'fatih/vim-go', { 'tag': '*' }
```

`*` means to select the latest tagged release. You can pin to a specific tag if you wish. I use vim-plug myself and recommend it to others as well. It's an excellent plugin and does the work well. Thanks
