### ISSUE TITLE
GoImports not working

### ISSUE THREAD

**Issue by anfeierde** [fatih/vim-go#1876]
### What did you do? (required. The issue will be **closed** when not provided.)
 `:GoInstallBinariesc`  all installed,`:GoBuild` and `:GoRun` can run, but `:GoImports` not working

### Configuration (**MUST** fill this out):

* vim-go version:v1.17

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
 ```
 call vundle#begin()
 Plugin 'VundleVim/Vundle.vim'
 Plugin 'fatih/vim-go'
 call vundle#end()
 let g:go_fmt_command = "goimports"
```

* Vim version (first three lines from `:version`):v8.0

* Go version (`go version`):v1.9.3

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wkchen/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wkchen/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nm/dk0lg6v120b7pflbv9w2l8z00000gn/T/go-build589846478=/tmp/go-build -gno-record-gcc-switches -fno-common"
VGOMODROOT=""
```

**Comment by Obayanju** [comment]
Hey, did you find a solution? goimports doesn't work for me too.

**Comment by lucker0087** [comment]
me too
