### ISSUE TITLE
GoDoc syntax highlighting

### ISSUE THREAD

**Issue by tylerFowler** [fatih/vim-go#1879]
It would be nice if the godoc file type defined here could be a superset of the actual Go syntax to make it easier to read, even something basic like what godoc.org uses. At least I think so.. Who knows how often I would mistake it for a code pane.

### Configuration (**MUST** fill this out):

* vim-go version: `1.17`
* Vim version (first three lines from `:version`): 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  5 2018 06:52:49)
macOS version
Included patches: 1-150
Compiled by Homebrew
```

**Comment by bhcleek** [comment]
vim-go doesn't parse the godoc; that's left up to to tools like `godoc` and `gogetdoc`.

**Comment by tylerFowler** [comment]
@bhcleek I meant I guess that it would be nice to have syntax highlighting for the `godoc` filetype, similar to what happens when you use the `:GoDoc` command to get a godoc pane and then in that pane run `set ft=go`. Though I imagine there would be slight differences in the syntax highlighting to deal with the plaintext found in the `godoc` output.

**Comment by bhcleek** [comment]
Feel free to submit a PR.
