### ISSUE TITLE
Question: Error on test function does not jump to the assertion failed line code

### ISSUE THREAD

**Issue by masch** [fatih/vim-go#1880]
### What did you do? (required. The issue will be **closed** when not provided.)
Run :GoTest command on this example:
package main_test
```
import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func ReturnTrue() bool {
	return true
}

func TestFunction(t *testing.T) {
	assertion := assert.New(t)

	assertion.Equal(false, ReturnTrue())
}
```
### What did you expect to happen?
The test function fails, but it does not jump to the `assertion.Equal(false, ReturnTrue())` line

### What happened instead?
It creates an empty file the next screenshot:

![screenshot from 2018-07-14 21-36-21](https://user-images.githubusercontent.com/4921/42729422-fba0c9ac-87ad-11e8-9e7f-dc56d7df531d.png)

### Configuration:

* vim-go version:
master

* `vimrc` you used to reproduce:
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

* Vim version:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 10 2018 08:28:52)

* Go version:
go version go1.10 linux/amd64

* Go environment:
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/XXX/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/XXX/.gvm/pkgsets/go1.10/global"
GORACE=""
GOROOT="/home/XXX/.gvm/gos/go1.10"
GOTMPDIR=""
GOTOOLDIR="/home/XXX/.gvm/gos/go1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build112347917=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
This a known issue with older versions of `github.com/stretchr/testify/assert`. Please upgrade it to at least https://github.com/stretchr/testify/commit/a726187e3128d0a0ec37f73ca7c4d3e508e6c2e5

**Comment by bhcleek** [comment]
Older versions of `github.com/stretchr/testify` do not play nicely with vim-go, because of the way it manipulates test output. Please make sure you're using at least https://github.com/stretchr/testify/commit/a726187e3128d0a0ec37f73ca7c4d3e508e6c2e5.

If you can duplicate a problem with `testing.T` methods, feel free to re-open this issue.
