### ISSUE TITLE
GoRun in Neovim Terminal does not exit when terminal closed

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#1891]
### What did you do? (required. The issue will be **closed** when not provided.)
Go source code is in my vim buffer. I have the following configuration set as I'm using neovim:

let g:go_term_enabled = 1
let g:go_term_mode = "split"
let g:go_term_height = 13

and I have the following event loop in my go code

```
	for {
		select {
		case sig := <-sigChan:
			switch sig {
			case os.Interrupt:
				// received interupt gracefully kill server
				log.Printf("received interrupt signal. gracefully stopping service")
				grpcServer.GracefulStop()
				os.Exit(0)
			case os.Kill:
				log.Printf("recived kill signal. exiting ungracefully")
				os.Exit(1)
			default:
				log.Printf("received unhandled signal: %v", sig)
			}
		case err := <-grpcErrChan:
			log.Printf("received grpc server error. exiting: %s", err)
			os.Exit(1)
		}
	}
```

I run "GoRun" which launches my binary in a terminal for testing. Once testing is complete I close the terminal emulator. The launched process continues to run 

```
❯ lsof -nP -i4TCP:8003 | grep LISTEN
main    21810 louis   10u  IPv6 0x140c114bf2689c63      0t0  TCP *:8003 (LISTEN)
```

the binary must be killed manually which is inconvenient. 

Issue opened at neovim repo also: https://github.com/neovim/neovim/issues/8760#event-1741345951

### What did you expect to happen?
When the terminal emulator is closed the go binary should be sent a SIGINT or a SIGKILL. I'm not exactly sure if vim-go is manipulating the way the neovim terimal emulator is called, but I cannot send ctrl-c to the terminal window either. If this is a purely neovim issue feel free to close this ticket. 

### What happened instead?
The binary continues to run until it is killed. 

### Configuration (**MUST** fill this out):

* vim-go version:
MASTER

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

" vim-go Configuration
let g:go_disable_autoinstall = 0
let g:go_highlight_functions = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_build_constraints = 1
let g:go_term_enabled = 1
let g:go_term_mode = "split"
let g:go_term_height = 13
" let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = "5s"
let g:neocomplete#enable_at_startup = 1
let g:go_fmt_command = "goimports"
let g:go_list_type = "quickfix"
let g:go_test_timeout = "600s"
autocmd FileType go map <leader>b :GoBuild <CR>
autocmd FileType go map <leader>r :GoRun <CR>
au FileType go nmap <leader>RT <Plug>(go-run-tab)
autocmd FileType go map <leader>l :GoMetaLinter <CR>
autocmd FileType go nmap <leader>R :GoRename <CR>
autocmd FileType go map <leader>o :GoDecls <CR>
autocmd FileType go map <leader>O :GoDeclsDir <CR>
autocmd FileType go map <leader>d :GoDoc <CR>
autocmd FileType go map <leader>I :GoInfo <CR>
autocmd FileType go map <leader>ii :GoImport 
autocmd FileType go map <leader>ia :GoImportAs 
autocmd FileType go map <leader>f :GoFillStruct <CR>
autocmd FileType go map <leader>t :GoTestFunc -v -race <CR>
autocmd FileType go map <leader>T :GoTest -v -race <CR>
autocmd FileType go map <leader>c :GoTestCompile <CR>
autocmd FileType go map <leader>at :GoAddTags <CR>
autocmd FileType go map <C-n> :cnext<CR>
autocmd FileType go map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

* Vim version (first three lines from `:version`):
neovim 0.3.0

* Go version (`go version`):
```
❯ go version
go version go1.10.1 darwin/amd64
```

* Go environment (`go env`):
```
❯ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/louis/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m2/gl_nd53n44vcnjbv49n6_kv40000gn/T/go-build048905402=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by justinmk** [comment]
> When the terminal emulator is closed

How _exactly_ are you closing the terminal buffer. Closing a window (`:q`) without exiting Nvim doesn't kill the buffer. You must delete the buffer.

> I cannot send ctrl-c to the terminal window either

Are you in normal-mode or terminal-mode (hit `i` in the terminal buffer to enter terminal-mode). See also `:help terminal-mode`.

**Comment by ldelossa** [comment]
@justinmk was able to fix the issue by catching SIGHUP also. I was killing the terminal window with "q!". This sends a SIGHUP not a SIGINT like I was expecting.
