### ISSUE TITLE
GoDef fails to resolve named imports or dot-imports

### ISSUE THREAD

**Issue by sykesm** [fatih/vim-go#190]
It doesn't look like GoDef can determine the right package to use for named imports or dot-imports.

Named example:

``` go
package main

import f "fmt"

func main() {
    f.Println("Hello!")
}
```

Running :GoDef when the cursor is over Println results in the following message: `godef: no declaration found for f.Printf`.

Dot-import example:

``` go
package main

import . "fmt"

func main() {
    Println("Hello!")
}
```

For this file, GoDef for Println results in: `godef: no declaration found for godef`. 

Is there a way to support these patterns - especially named imports? While dot imports are generally frowned upon, it would be good if the plugin could try to resolve against them as well.

Thanks.

**Comment by linshibo** [comment]
Me too.
  import "time"
  select {
    case <-time.After(time.Second * 30):
        LookUp("stop cpuprof")
   }
when I move my cusor to "After"  , it echos "godef: no declaration found for time.After".
it happens when it refers to system pkg.

**Comment by rogpeppe** [comment]
@linshibo I suspect that last problem is to do with another issue, not this one.
It happens when you've updated the Go version to a recent version,
because the location of the standard library inside $GOROOT has changed,
so the (now outdated) go/build package doesn't find the system source.

Try rebuilding godef and see if that fixes the problem.

**Comment by k4rtik** [comment]
Thanks @rogpeppe, worked for me after rebuilding godef for a similar issue.

**Comment by abourget** [comment]
@rogpeppe any changes you'll add those dot imports in godef after all ?

I'm working with `ginkgo` and `gomega` and these use dot imports for BDD-style development.  Love it or hate it, some lib use that for testing, and with `godef` right now there's no way to jump around code like we normally do.

I've heard IntelliJ's go idea plugin does it, and jumps past the dot import boundaries. It'd be great to have that under vim and emacs too :)

**Comment by abourget** [comment]
Also using https://godoc.org/github.com/raphael/goa/design/dsl which proposes using dot imports.. but it really hinders navigation.

what I usually do with gomega is have a `utils.go` where I:

```go
var Expect = gomega.Expect
var BeTrue = gomega.BeTrue
```

it adds an indirection and avoids imports on all files in the package.  I'd prefer to be able to jump through dot imports though !

**Comment by GerryG** [comment]
"The other known failing of godef is that if a package's identifier doesn't match the last segment of its import path, it won't work. This makes godef quite a bit faster, but it's wrong. It needs fixing, but I have no time to work on it. Patches gratefully received!"

This really makes godef unusable. I'm trying to play with go-ipfs and extend it, and I don't think it would really be possible to align with the code I'm importing. I could "fix" my code, but trying to patch dependencies is a lost cause. There is no point to the feature of having an explicit identifier if it isn't supported.

Is this going to be fixed and if so when? I don't think the tool is usable without this issue fixed.

**Comment by GerryG** [comment]
Now, I don't know why this issue is posted against go-vim. The problem is in godef, no?
