### ISSUE TITLE
What happened to commit 31c6314?

### ISSUE THREAD

**Issue by lilydjwg** [fatih/vim-go#1911]
### What did you do? (required. The issue will be **closed** when not provided.)
I'm trying to merge upstream changes from this repo, onto the commit last time I got.

### What did you expect to happen?
git should have merged new changes smoothly because what I've changed is not conflicting with upstream changes.

### What happened instead?
Many files are in conflicting state after git merge.

### Configuration (**MUST** fill this out):
N/A.

----

I notice that the last commit upstream, i.e. 31c6314, has disappeared. Instead, a commit ca8ef8a with the same message exists. The latest commit I have in common is 476239117d80fa68a92bfa937910f2644e0020a7. Have you rebased master? If so, could you avoid that in the future? It confuses git when merging.

My local changes to this is simple: to un-ignore doc/tags and add my generated one in repo. I want doc/tags in repo so that I won't need to generate them every time I update where I have my instance of Vim configuration.

**Comment by bhcleek** [comment]
We do not typically force push over master. The commit you're referring to is nearly a year old, and I don't recollect if there were problems with it at the time; it's impossible for me to say with certainty whether or not something happened that caused us to force push over it.

**Comment by lilydjwg** [comment]
Sorry. It seems to be my git tool (git-subrepo) misleadingly rebased the signed commits.
