### ISSUE TITLE
Vim freezes on jumping to a tag

### ISSUE THREAD

**Issue by GoingFast** [fatih/vim-go#1912]
### What did you do? (required. The issue will be **closed** when not provided.)

gd

### What did you expect to happen?

not freeze

### What happened instead?

froze

### Configuration (**MUST** fill this out):

* vim-go version: 
latest

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

Plugin 'fatih/vim-go', { 'do': ':GoUpdateBinaries' } " {{{
nnoremap <leader>r :GoIfErr<CR>
nnoremap <C-g> :GoDecls<CR>

let g:go_fmt_experimental = 1
let g:go_def_mapping_enabled = 1
let g:go_fmt_command = 'goimports'
let g:go_fmt_fail_silently = 1
let g:go_term_enabled = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_addtags_transform = "snakecase"
let g:go_snippet_engine      = "neosnippet"
"}}}

* Vim version (first three lines from `:version`):

NVIM v0.2.2                                                                                                                                          
Build type: RelWithDebInfo                                                                                                                           
LuaJIT 2.1.0-beta3  

* Go version (`go version`):
go version go1.10.1 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/risla/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/risla/work"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build510179514=/tmp/go-build -gno-record-gcc-switches"

FUNCTION  go#util#Exec()
Called 2 times
Total time:   0.992050
 Self time:   0.000167

count  total (s)   self (s)
    2              0.000009   if len(a:cmd) == 0
                                call go#util#EchoError("go#util#Exec() called with empty a:cmd")
                                return ['', 1]
                              endif
                            
    2              0.000010   let l:bin = a:cmd[0]
                            
                              " Lookup the full path, respecting settings such as 'go_bin_path'. On errors,
                              " CheckBinPath will show a warning for us.
    2   0.000994   0.000022   let l:bin = go#path#CheckBinPath(l:bin)
    2              0.000008   if empty(l:bin)
                                return ['', 1]
                              endif
                            
                              " Finally execute the command using the full, resolved path. Do not pass the
                              " unmodified command as the correct program might not exist in $PATH.
    2   0.990985   0.000074   return call('s:exec', [[l:bin] + a:cmd[1:]] + a:000)

**Comment by bhcleek** [comment]
`gd` generally works (I've been using it all day) without issue. Can you provide a source file where you see it failing?

**Comment by fatih** [comment]
Closing this because `gd` is working fine and there are no responses yet. Please, next time provide a reproducible case for us so we can test it. Thanks!
