### ISSUE TITLE
Omni completion (^O^N^P) Pattern not found

### ISSUE THREAD

**Issue by bzeron** [fatih/vim-go#1913]
### What did you do? (required. The issue will be **closed** when not provided.)
```
error encountered on typing <C-x><C-o>
```
### What did you expect to happen?
```
I expected it to give code completion suggestions.
```
### What happened instead?
```
Omni completion (^O^N^P) Pattern not found.
```
### Configuration (**MUST** fill this out):
* vim-go version:
```
vim-go version: 1.17
```
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
set nocompatible
filetype off
set number
syntax on
 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
 
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'

call vundle#end()
filetype plugin indent on
```
* Vim version (first three lines from `:version`):
```
Mac's own VIM

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)
Garbage after option argument: "-version"
More info with: "vim -h"
```
* Go version (`go version`):
```
go version go1.11beta3 darwin/amd64
```
* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN="/Users/zhengya/go/bin"
GOCACHE="/Users/zhengya/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zhengya/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bt/gh05fvc17sqfhmty4bymb_s40000gn/T/go-build411240184=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment]
In general, autocompletion works. If you can provide some details about what you were trying to autocomplete and where, we may be able to to pinpoint the problem.

**Comment by bzeron** [comment]
I only modified the .vimrc file and  install  Vundle.vim

**Comment by bhcleek** [comment]
What go file were you editing? Where in that file were you trying to autocomplete?

**Comment by bhcleek** [comment]
`fmt` is not a resolvable identifier in that example. If you import the fmt package, does the autocompletion work for you?

**Comment by bzeron** [comment]
not  work

**Comment by shaohk** [comment]
Hi, how did u issue?
