### ISSUE TITLE
Q: is there a quick filter to auto-complete pop up?

### ISSUE THREAD

**Issue by HouzuoGuo** [fatih/vim-go#1917]
### What did you do?
Use auto completion (C-x,C-o).

### Configuration

* vim-go version:
https://github.com/fatih/vim-go/commit/04699c8916c777ad3c6dc8a803d55d8d222b3026

* Vim version (first three lines from `:version`):
8.0

* Go version (`go version`):
1.10.3

Does vim-go's auto completion have a quick filter to narrow down candidates? E.g. if candidates are "Compare" and "Contains", typing "ns" in a quick filter leaves only Contains as the candidate.

Thanks!

**Comment by bhcleek** [comment]
After C-x,C-o, you can use C-o, C-n, or C-p to cycle through the matches.

The autocompletion behavior is handled by Vim, not by vim-go. vim-go only provides the set of autocompletion candidates to the Vim.
