### ISSUE TITLE
location list doesn't open in a horizontal split over all windows

### ISSUE THREAD

**Issue by floriankammermann** [fatih/vim-go#1918]
### What did you do?
I open neovim with 4 vertical splits. 1 vsplit = nerdtree, 2-4 vsplit = go files
I edit a file in vsplit 3 and save it with errors, so that the locationlist is opened with the compliation failure.

### What did you expect to happen?
The locationlist should open in a horizontal split under all the 4 windows.
For example fzf opens a horizontal split under all windows when I enter the command Ag.

### What happened instead?
The locationlist opens as horizontal split only under vsplit 3.

### Configuration (**MUST** fill this out):

* vim-go version: 1.18

* `vimrc` you used to reproduce: https://github.com/floriankammermann/vimconfig/blob/master/init.vim

* Vim version (first three lines from `:version`): NVIM v0.3.1

* Go version (`go version`): go1.10.3 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/flo/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/flo/go/"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build958483040=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
Vim has two kinds of errors windows: quickfix and locationlist. vim-go uses both. If you want _all_ vim-go errors to use the quickfix window, then can set `g:go_list_type='quickfix'`.
