### ISSUE TITLE
vim-go make fail

### ISSUE THREAD

**Issue by chinaten** [fatih/vim-go#1919]
### What did you do? (required. The issue will be **closed** when not provided.)
make

### What did you expect to happen?
./scripts/install-vim: 65: ./scripts/install-vim: curl: not found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [install] Error 2

### Configuration (**MUST** fill this out):

* vim-go version:

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):

* Go version (`go version`):

* Go environment (`go env`):

**Comment by Carpetsmoker** [comment]
The error is:

    curl: not found

So looks like you need to install `curl`?

Also note that `./scripts/install-vim` is intended for development/running tests, and not the way to install either Vim or vim-go. See the README for installation instructions: https://github.com/fatih/vim-go#install
