### ISSUE TITLE
Using GoDef to jump to a custom identifier

### ISSUE THREAD

**Issue by alourie** [fatih/vim-go#1921]
I find GoDef a great feature to jump around the code, but way too often I find myself wanting to jump to a type/function that is not in my file, so it's not "under the cursor".

It would be really nice to have an option to `:GoDef <mything>` so that it would move me to that code.

It is at all possible?

**Comment by bhcleek** [comment]
You can use `:GoDecls` and `:GoDeclsDir` with ctrlp or fzf. ref: https://github.com/fatih/vim-go-tutorial#move-between-functions

**Comment by alourie** [comment]
@bhcleek No, that doesn't work. GoDecls[Dir] only works with functions, whereas I expect it to also jump to types/interfaces. I don't think the ticket is resolved.

**Comment by bhcleek** [comment]
`:GoDecls` and `:GoDeclsDir` work on more than just functions; they work on most types. Have you tried them?

**Comment by bhcleek** [comment]
Fatih blogged about it a couple of years ago and included a useful video:  https://medium.com/@farslan/navigation-between-functions-and-types-in-vim-go-f9dd7de8ca37

**Comment by alourie** [comment]
@bhcleek I have tried and it only shows function declarations and, strangely, _some_ types, but not all. I'll watch the video and let you know. Thanks!

**Comment by fatih** [comment]
@alourie any updates?

**Comment by alourie** [comment]
@fatih I've watched the video and I'm trying to use `:GoDecls[Dir]` but for some reason, it doesn't catch all the definitions in the project... I am working on `github.com/gocql/gocql` project if that makes any difference.

**Comment by fatih** [comment]
Do you have `ctrlp`, `unite`, etc.. installed? What does `:GoDecls` shows you?

**Comment by alourie** [comment]
@fatih yea, I use ctrlp. It shows a list of functions, but almost no types, just one or two maybe. Not the ones I'm looking for.

**Comment by bhcleek** [comment]
@alourie I'm not seeing any problems with gocql. Which types are you not seeing?

FWIW, if there's a problem here, it may lie with github.com/fatih/motion 🤔

**Comment by bhcleek** [comment]
closed for lack of feedback.
