### ISSUE TITLE
What setting is missing from my "bare" vimrc that causes "Error detected while processing... go.vim"?

### ISSUE THREAD

**Issue by therealplato** [fatih/vim-go#1930]
### What did you do? (required. The issue will be **closed** when not provided.)
My :GoInfo was hanging indefinitely. My first guess, as always, was "something is interfering." I created a tiny config and ran `vim -u ~/.vimrc-bare file.go`. I observed startup error spam. I ran `:PlugClean` so vim-plug would remove other plugins' files. I continued to observe startup error spam. I ran `rm -rf ~/.vim/plugged/vim-go`, restarted vim, ran `:PlugInstall`, restarted vim, and continued to observe startup error spam.

I've now worked around this - I prepended https://github.com/tpope/vim-sensible/blob/v1.1/plugin/sensible.vim to the bare config below, at which point startup errors disappeared. I did not find any docs at https://github.com/junegunn/vim-plug/, https://github.com/fatih/vim-go/ or https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt that specified which of sensible's setting was required.

### What did you expect to happen?
Expected :GoInfo to start working again

### What happened instead?
vim reported syntax errors in vim-go's files on startup:
```
Error detected while processing /Users/plato/.vim/plugged/vim-go/plugin/go.vim:
line   14:
E15: Invalid expression:
E15: Invalid expression:
line   15:
E10: \ should be followed by /, ? or &
line   16:
E10: \ should be followed by /, ? or &
line   17:
E10: \ should be followed by /, ? or &
line   33:
...
E399: Not enough arguments: syntax region goPackageComment    start=/\v(\/\/.*\n)+\s*package/
```

### Configuration (**MUST** fill this out):

* vim-go version:
dont know how to check this, but `:PlugInstall` presumably took today's master

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```vim
call plug#begin('~/.vim/plugged')
  Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
```

* Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  7 2018 17:25:45)
macOS version
Included patches: 1-1450
```
* Go version (`go version`):
```
go version go1.10 darwin/amd64
```

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/plato/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/plato/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f3/5g5_5drs6hx2p82mv80n0j800000gn/T/go-build537671261=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by Carpetsmoker** [comment]
If you use `vim -u file` then `set nocompatible` is *not* set automatically; it's *only* set automatically if the `~/.vimrc` or `~/.vim/vimrc` file is found. It's pretty confusing; but it is what it is; see `:help compatible-default` for more details.

This is the reason I always recommend people add `set nocompatible` to their vimrc (even though some purists insist that it's not needed).

So try adding that, or using `vim -N -u file`.

**Comment by therealplato** [comment]
Thanks @Carpetsmoker, `set nocompatible` resolves the issue.
Does vim-go depend on a vim feature that does not work when `compatible` is on? Or vim-plug?
