### ISSUE TITLE
Move to maintained version of gocode?

### ISSUE THREAD

**Issue by berfarah** [fatih/vim-go#1932]
### What did you do? (required. The issue will be **closed** when not provided.)

Checked the repo below:
https://github.com/nsf/gocode/commit/9f3c24f3a0fe7119e933616ddcc867356d271398

Looks like nsf/gocode is official no longer being maintained.

 It also is much more aggressive than its fork (https://github.com/mdempsky/gocode) about building/compiling. In large codebases this can cause a spectacular amount of processes to be started 30+ go builds of the same files). I'm happy to provide more detail here, but didn't want to distract too much from the other issue.

I saw there was a PR introducing the fork, but that some additional configuration was required for it to work. As a result, I believe it was reverted.

Is there anything that can be farmers out to volunteers for that task? I'd be happy to help.

**Comment by Carpetsmoker** [comment]
We did exactly this: #1853

**Comment by berfarah** [comment]
My apologies, @Carpetsmoker. I thought that PR was reverted?

**Comment by berfarah** [comment]
I stand corrected - I checked again and I don't know what I saw but I was definitely wrong.
