### ISSUE TITLE
error message does not show in quickfix

### ISSUE THREAD

**Issue by jhinrichsen** [fatih/vim-go#1941]
### What did you do?

Note: i have successfully used vim-go on the mac in all sorts of setups and it never failed on me. Obviously i am doing something stupid on debian, but i am running out of ideas.

Installed both vim (no python support) and vim-nox (python3 support) on plain debian 9 stretch. Followed the "Quick setup" in the vim-go tutorial to install "vim-plug", and added minimal plugin section to empty $HOME/.vimrc. Created a sample hello world in $HOME/go/src/hello/hello.go with a syntax error in it.

Typed :GoBuild

### What did you expect to happen?

Build shows the error message

### What happened instead?

Build shows only quickfix window, but no error message.

### Configuration (**MUST** fill this out):

* vim-go version:

Tried a couple of releases up to 1.18 by "git checkout" and vim restart.

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

* Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):

* Go version (`go version`):

go version go1.11 linux/amd64

* Go environment (`go env`):

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jot/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jot/go"
GOPROXY=""
GORACE=""
GOROOT="/home/jot/bin/go"
GOTMPDIR=""
GOTOOLDIR="/home/jot/bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build373885101=/tmp/go-build -gno-record-gcc-switches"

**Comment by jhinrichsen** [comment]
Seems to be a problem with the first error message. If the go file being built contains two errors, cursor jumps to first location, but the error of the second is shown.

**Comment by jhinrichsen** [comment]
Reproduced problem with latest neovim 0.3.1

````
NVIM v0.3.1
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -s
td=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLAR
ATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/jot/repos/neovim/build/conf
ig -I/home/jot/repos/neovim/src -I/home/jot/repos/neovim/.deps/usr/include -I/usr/include -I/home/jot/repos/n
eovim/build/src/nvim/auto -I/home/jot/repos/neovim/build/include
```

**Comment by fatih** [comment]
@jhinrichsen is there a way you can provide as a simple Go source code that fails where we can reproduce it on our own end?

**Comment by jhinrichsen** [comment]
```
package main

import "fmt"

// Test

func main() {
        fmt.Println("Hello world")
        a
}

func a() string {
}

```

should report

- hello.go|9 col 2| a evaluated but not used
- hello.go|13 col 1| missing return at end of function

**Comment by bhcleek** [comment]
This works fine for me. Your statusline seems to be two lines high instead of the usual one. Might it be drawing over the first item in the quickfix list somehow?

**Comment by jhinrichsen** [comment]
Fiddling around w/ terminal colors made the yellow on yellow line show the error. Sorry about wasting your time.
