### ISSUE TITLE
:GoDef doesn't jump to identifier if it's opened in a new window

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#1944]
Using `:GoDef` on a vertical split doesn't jump to the identifier.  To reproduce:

1. Add following to `vimrc`
```
  autocmd FileType go nmap <silent> <Leader>v <Plug>(go-def-vertical)
```

2. Call `<leader>v` on an identifier
3. Observe how the cursor is still on the same position and didn't jump to the newly opened vertical split.

`gd`  works fine, but `-vertical`, `-split` and `-tab` no more jump to the identifier.

**Comment by bhcleek** [comment]
What's the value of `g:go_def_mode` when you see this bug?

**Comment by fatih** [comment]
It's set to `let g:go_def_mode = "guru"`. This started today after I pulled the latest changes. Something in the async code in `guru` might trigger this? I opened the issue so I don't forget and we can track down the issue.

**Comment by fatih** [comment]
I'm going to do a git bisect to get the exact SHA. Pretty sure it started happening in this last 2-3 days (as I'm actively pulling the changes). I'll post more once I have it.

**Comment by fatih** [comment]
```
$ vim-go git:(2eb76d5) git bisect bad
2eb76d5ece14519cf48cace0799f1787e4a738b1 is the first bad commit
commit 2eb76d5ece14519cf48cace0799f1787e4a738b1
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Sun Aug 26 09:33:41 2018 -0700

    refactor guru jobs to use vim-go's async api

:040000 040000 7fdeaf5dc046510d1ba27b893c287346e8c39a96 35226557725baf70d549859a2dc4d9c929fcb52c M      autoload
```

Works fine before this commit, afterward it is broken. I'll check if I can find the issue.
