### ISSUE TITLE
Function go#config#FoldEnable already exists, add ! to replace it

### ISSUE THREAD

**Issue by hujianxin** [fatih/vim-go#1951]
### What did you do? (required. The issue will be **closed** when not provided.)
Ctrl-x Ctrl-o

### What did you expect to happen?
Complete

### What happened instead?
Error detected while processing /home/hujianxin/.vim/plugged/vim-polyglot/autoload/go/config.vim:
line  426:
E122: Function go#config#FoldEnable already exists, add ! to replace it
Press ENTER or type command to continue
Error detected while processing function go#complete#Complete:
line    3:
E171: Missing :endif

### Configuration (**MUST** fill this out):

* vim-go version:v1.18

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  3 2018 11:00:44)
Included patches: 1-346

* Go version (`go version`):
go version go1.10.3 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hujianxin/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hujianxin/go"
GORACE=""
GOROOT="/home/hujianxin/Code/go"
GOTMPDIR=""
GOTOOLDIR="/home/hujianxin/Code/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build662268724=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
I pushed a fix that addresses `Function go#config#FoldEnable already exists, add ! to replace it`, but you should be aware that vim-polyglot is not vim-go, and the error you're seeing is from vim-polyglot.

Many things have changed since the v1.18 release; do you experience the second error, `Error detected while processing function go#complete#Complete:` on the latest master?

**Comment by hujianxin** [comment]
@bhcleek I solved this issue by puting Plug 'sheerun/vim-polyglot' behind Plug 'fatih/vim-go'
