### ISSUE TITLE
Error when saving go.mod

### ISSUE THREAD

**Issue by tebeka** [fatih/vim-go#1953]
### What did you do? (required. The issue will be **closed** when not provided.)
Edited a `go.mod` file containing 
```go
module main

require github.com/pelletier/go-toml v1.2.0
```

### What did you expect to happen?
File to be saved

### What happened instead?
Got the error
`vim-go: unknown list type command value found ('GoModFmt'). Please open a bug report in the vim-go repo.`

### Configuration (**MUST** fill this out):

* vim-go version:
1b65f774e01e0588f33c7cdb89cfc8b1afb4e88d

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
See https://gist.github.com/tebeka/424b8d66510c06ba0b3d727136a6bac0

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org

* Go version (`go version`):
go version go1.11 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/miki/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/miki/Projects/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build907213399=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
Thanks for the report @tebeka . Can you verify that #1954 solves the issue for you?

**Comment by fatih** [comment]
I like errors like this, excellent :)

**Comment by tebeka** [comment]
If fixes this issue, thanks.

Why does it transform:
```go
module main

require (
    github.com/pelletier/go-toml v1.2.0
)
```

to
```
module main

require github.com/pelletier/go-toml v1.2.0
```

**Comment by Carpetsmoker** [comment]
Because that's what it does :-) Just like with import paths in Go.

Ask rsc; but my guess is that it's just his personal preference, and he writes the tools, so...
