### ISSUE TITLE
autocompletion list of the import statement provides go types/symbols instead of package's paths 

### ISSUE THREAD

**Issue by idanko** [fatih/vim-go#1955]
A recent GoInstall has broken the autocompletion for import statements and it does not work for me. It's a fresh install to a clear system. After putting a cursor to the import clause and typing <c-x><c-o> the suggestion window list contains go keywords and types instead for the package's folders:

![vim-go_bug](https://user-images.githubusercontent.com/8293386/45240704-3a047300-b2f2-11e8-839b-e8bcffe2d785.jpg)

## vim-go
commit: fb173c3a849fdc47a267e905cee5e29a88797d61

## vim
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453

## nvim
$ nvim --version
NVIM v0.3.2-408-gf62d4865d
Build type: Release
LuaJIT 2.0.5

**Comment by bhcleek** [comment]
This is a bug in https://github.com/mdempsky/gocode.
