### ISSUE TITLE
:GoInstallBinaries  vim-go: go executable not found.

### ISSUE THREAD

**Issue by hecong2735** [fatih/vim-go#1965]
### What did you do? (required. The issue will be **closed** when not provided.)
I use :GoInstallBinaries. my shell is zsh

### What did you expect to happen?
it works

### What happened instead?
vim show 'vim-go: go executable not found.' 

### Configuration (**MUST** fill this out):

* vim-go version:
the latest(sorry i dont know how to find my vim-go version)
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
 55 filetype off
 56 set rtp+=~/.vim/bundle/Vundle.vim
 57 call vundle#begin()
 58 Plugin 'VundleVim/Vundle.vim'
 59 Plugin 'Valloric/YouCompleteMe'
 60 Plugin 'tomasr/molokai'
 61 Plugin 'Raimondi/delimitMate'
 62 Plugin 'fatih/vim-go'
 63 Plugin 'honza/vim-snippets'
 64 call vundle#end()
 65 filetype plugin indent on
  98 let g:molokai_original=1
 99 let g:rehash256=1
100 let g:go_autodetect_gopath = 0
101 set shell='/bin/zsh'
102 let g:go_bin_path = expand("$HOME/go")
```

* Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  7 2018 09:58:21)
Included patches: 1-349
Modified by jonathonf.fernyhough@york.ac.uk
* Go version (`go version`):

go version go1.9 linux/amd64

* Go environment (`go env`):

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build829939213=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Comment by bhcleek** [comment]
From within Vim, does `:echo $PATH` show that `/usr/local/go/bin` is in `$PATH`?

**Comment by hecong2735** [comment]
Thanks, I found the problem, I did not configure the root user's PATH variable. Now the problem is solved

**Comment by hecong2735** [comment]
> From within Vim, does `:echo $PATH` show that `/usr/local/go/bin` is in `$PATH`?

Thanks, I found the problem, I did not configure the root user's PATH variable. Now the problem is solved.

**Comment by lostinblue** [comment]
I fixed this by just installed `apt-get install golang` on a fresh install. Still dont have a `/usr/local/go/bin` too. So this may be helpful to some.

**Comment by VinGarcia** [comment]
Just adding for future reference, I had the same problem and fixed it in a different way: I just stopped using zsh.

This problem happened to me on Mac, and I am a Linux user so changing to bash was actually something I was already planning on doing. 

To do this on OSX just run this command:

```bash
chsh -s /bin/bash
```

Insert your password and restart your terminal, then `GoInstallBinary` should just work.

**Comment by jkopczyn** [comment]
I currently have this same problem, but switching from `zsh` won't help me because I'm already using `bash`. It does seem to be a PATH-within-vim problem, but the obvious places to try to set root's PATH aren't working for me. Somewhat smaller `vimrc`:
```set nocompatible                                                                                     
" needed to load plugins right                                                                       
filetype off                                                                                         
filetype plugin indent off                                                                           
                                                                                                     
set rtp+=~/.vim/bundle/Vundle.vim                                                                    
call vundle#begin()                                                                                  
" let Vundle manage Vundle, required                                                                 
Plugin 'VundleVim/Vundle.vim'                                                                        
" probably needs `vim +PluginInstall +qall` run in shell at least once                               
                                                                                                     
Plugin 'fatih/vim-go'                                                                                
                                                                                                     
call vundle#end()                                                                                    
" no longer needed once plugins are loaded                                                           
filetype plugin indent on                                                                            
syntax on```
