### ISSUE TITLE
Metalinter not running correctly on save

### ISSUE THREAD

**Issue by smlx** [fatih/vim-go#1969]
### What did you do?

Configured Metalinter to auto-run on save.

### What did you expect to happen?

Metalinter to run and report errors.
There are definitely lint issues in this file, and v1.18 of vim-go correctly reports them.
See the extra debug info below.

### What happened instead?

Metalinter reported no errors. I see:
```
vim-go: [gometalinter] SUCCESS
```

### Configuration

* vim-go version: v1.18-126-g9254470

* `vimrc` you used to reproduce:

```
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()

syntax on
filetype plugin indent on

let g:go_metalinter_autosave = 1
```

* Vim version: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707
Modified by pkg-vim-maintainers@lists.alioth.debian.org
```
This is just the default version in Debian 9.

* Go version (`go version`):

```
go version go1.11 linux/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/scott/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/scott/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build225643306=/tmp/go-build -gno-record-gcc-switches"
```

### Extra debug information

I bisected the issue to this commit:

```
2eb76d5ece14519cf48cace0799f1787e4a738b1 is the first bad commit
commit 2eb76d5ece14519cf48cace0799f1787e4a738b1
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Sun Aug 26 09:33:41 2018 -0700

    refactor guru jobs to use vim-go's async api

:040000 040000 7fdeaf5dc046510d1ba27b893c287346e8c39a96 35226557725baf70d549859a2dc4d9c929fcb52c M	autoload
```

Interestingly, I only see this issue in some .go files - others seem to correctly flag lint issues.

The project I see the issue with is in my GOPATH, so weird module interaction shouldn't be a factor..

**Comment by bhcleek** [comment]
Do you consistently see this problem in a particular Go file? Can you provide a file/package that can be used to demonstrate the problem?

**Comment by bhcleek** [comment]
I'm also wondering what happens in this file when you run `:GoMetaLinter` manually; do you see your expected errors in that case?

**Comment by smlx** [comment]
@bhcleek Sorry for the delay in my response on this.

[Here's a repository](https://gitlab.com/smlx/bug-sample) that I can reproduce the bug in. [`debug.go`](https://gitlab.com/smlx/bug-sample/blob/master/internal/debug/debug.go) has a syntax/lint error, but I get the gometalinter success message on `:w`.

If I run `:GoMetaLinter` manually it seems to work. I get a quickfix list of issues.

**Comment by bhcleek** [comment]
I am unable to reproduce the problem you're describing with that file. When I save the file I get two errors:
```
internal/debug/debug.go|7 col 1 warning| exported function SomeFunc should have comment or be unexported (golint)
internal/debug/debug.go|8 col 2 error| undefined: a (vet)
```

What is the value of your `g:go_metalinter_autosave_enabled` option?

**Comment by smlx** [comment]
I've created a docker environment based on Debian 9 that you can use to reproduce the problem.

```
git clone https://gitlab.com/smlx/bug-environment.git && cd bug-environment
docker build . -t vim-go-bug && docker run --rm -it vim-go-bug vim /root/go/src/gitlab.com/smlx/bug-sample/internal/debug/debug.go +w
```

**Comment by smlx** [comment]
I haven't set `g:go_metalinter_autosave_enabled` (see my `.vimrc` above), and it doesn't appear to be set in my environment.

**Comment by smlx** [comment]
That works. Thanks @bhcleek!
