### ISSUE TITLE
go_jump_to_error also jumps to warnings

### ISSUE THREAD

**Issue by desdic** [fatih/vim-go#1977]
First ... Thank you for an awesome plugin! I'm not sure if this is intended or not but can it be turned off for warnings ?

### What did you do? (required. The issue will be **closed** when not provided.)
Added go_jump_to_error=1 in my vimrc

### What did you expect to happen?
That is only jumps to errors and not warnings

### What happened instead?
Jumps to the first warning or error

### Configuration (**MUST** fill this out):
let g:go_jump_to_error = 1

* vim-go version:
commit sha 53d36f46d9701f3ac421a6ec13ff66be83b156ad (tag v1.18)

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 12 2018 23:25:13)
Included patches: 1-374
Compiled by Arch Linux

* Go version (`go version`):
go version go1.11 linux/amd64
* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kgn/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kgn/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build397684979=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
Most of the quickfix errors set by vim-go do not set their levels, because most go tools only output errors, not warnings, so there's effectively no difference.
