### ISSUE TITLE
GoDef unable to jump definition in other files in macOS

### ISSUE THREAD

**Issue by tengteng** [fatih/vim-go#1980]
### What did you do? (required. The issue will be **closed** when not provided.)
This is a recent issue. I updated gocode and go-vim in .vim/bundle/ (via git pull). Then run :GoDef (or c-]) on some symbol. vim-go gives `vim-go: [searching declaration] FAIL` error and does not jump to the definition.
Already tried `:GoUpdateBinaries` . Unfortunately it doesn't help.

### What did you expect to happen?
vim-go should jump to the definition of the symbol.

### What happened instead?
jump doesn't happen. See error messages:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"xxx.go" 309L, 7732C
vim-go: [searching declaration] dispatched
vim-go: [searching declaration] FAIL
```

### Configuration (**MUST** fill this out):

* vim-go version:
[c6ea9](https://github.com/fatih/vim-go/commit/1656f2ff1bb8c4865b2e9870c2be3468974c6ea9)
```
commit 1656f2ff1bb8c4865b2e9870c2be3468974c6ea9 (HEAD -> master, origin/master, origin/HEAD)
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Wed Sep 19 09:46:22 2018 -0700

    update CHANGELOG.md for #1978
```
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
 82 let g:gotags_bin="gotags"
 83 function! UpdateGoTags()
 84   let _result_ = system("rm tags")
 85   unlet _result_
 86   let _result_ = system(g:gotags_bin ." -R -f tags .")
 87   unlet _result_
 88   redraw
 89 endfunction

132 let g:tagbar_type_go = {
133             \ 'ctagstype' : 'go',
134             \ 'kinds'     : [
135                 \ 'p:package',
136                 \ 'i:imports:1',
137                 \ 'c:constants',
138                 \ 'v:variables',
139                 \ 't:types',
140                 \ 'n:interfaces',
141                 \ 'w:fields',
142                 \ 'e:embedded',
143                 \ 'm:methods',
144                 \ 'r:constructor',
145                 \ 'f:functions'
146             \ ],
147             \ 'sro' : '.',
148             \ 'kind2scope' : {
149                 \ 't' : 'ctype',
150                 \ 'n' : 'ntype'
151             \ },
152             \ 'scope2kind' : {
153                 \ 'ctype' : 't',
154                 \ 'ntype' : 'n'
155             \ },
156             \ 'ctagsbin'  : 'gotags',
157             \ 'ctagsargs' : '-sort -silent'
158             \ }
```
* Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 16 2018 18:20:26)
macOS version
```
* Go version (`go version`):
`go version go1.10.4 darwin/amd64`
Also tried `go version go1.11 darwin/amd64` Same error.
* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tengteng/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tengteng/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w6/60466prx4x7f7nyg74__8t_80000gn/T/go-build332266073=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment]
`:GoDef` and jumping to a definition in another file (even in another package) is working well for me regardless of the `g:go_def_mode` option. Can you provide a reproducible test case?

**Comment by bhcleek** [comment]
I am still unable to duplicate the problem you're describing. It works for me regardless of the value of `g:go_def_mode`.

**Comment by tengteng** [comment]
hmmm... Is there any way I can get more detailed info/logs for this? Should I turn on verbose on vim? I don't know what else are different... Also checked tags file and it looks fine.
```
Node    regression.go   3;"     t       access:public   line:3  type:struct
Pred    regression.go   7;"     w       access:public   ctype:Node      line:7  type:float64
RegressionTree  regression.go   15;"    t       access:public   line:15 type:struct
```

**Comment by tengteng** [comment]
Also tried `{Visual}CTRL-]` works well (jump to another file), as well as `:tag {name}`.
The issue seems to occur only on `CTRL-]` when jumping to a different file..

**Comment by bhcleek** [comment]
`CTRL-]` works fine for me to jump to another file. What is the value of your `g:go_def_mapping_enabled`? Does changing the value of `g:go_def_mode` change the behavior you're seeing?

The tags file is irrelevant; vim-go doesn't use the tags file to jump.

If you run `:map`, what's the value of the `<C-]>` mapping?

**Comment by tengteng** [comment]
```
n  <C-T>       *@:<C-U>call go#def#StackPop(v:count1)<CR>
n  <C-W>]      *@:<C-U>call go#def#Jump("split")<CR>
n  <C-W><C-]>  *@:<C-U>call go#def#Jump("split")<CR>
n  <C-]>       *@:GoDef<CR>
```
You are right, I just tried to mv vim-go out of ~/.vim/bundle and jumping works fine..

**Comment by tengteng** [comment]
I tried to set g:go_def_mode="godef" and it works! g:go_def_mode="guru" gave me that error.

**Comment by bhcleek** [comment]
FWIW, use `g:go_def_mode='guru'`. I'm not sure what's going on with your configuration, but it doesn't seem to be an issue with vim-go.

To be sure it wasn't a recent issue with guru, I updated it, and everything still works.

**Comment by flori** [comment]
I am having exactly the same problem with the same symptoms on Mac. If I use `g:go_def_mode='godef'` using `C-]`  works again. It also works if I disable the `vim-go` plugin in pathogen and use vim's native tags support.

I also noticed that jumping to a definition in gospace/src/foo.com/bar… seems to work, while jumping from one function call in a file of my local package to the function definition in another file of my local package doesn't seem to work:

```
package baz

func foo() {
  return
}
```

```
package baz

func bar() {
  foo() // C-] doesn't work from here!
  return
}
```

**Comment by kkh913** [comment]
I wasted about 2 hours on the same problem and finally solved it thanks to @flori . The key to the solution is `let g:go_def_mode='godef'`.
