### ISSUE TITLE
Add support for `gomvpkg`

### ISSUE THREAD

**Issue by pianohacker** [fatih/vim-go#1985]
`gomvpkg` allows you to move packages, much like `gorename` does for identifiers. A `:GoMvPkg` command (or similar) that integrated support for this command and had a prompt much like `:GoRename` would be very nice.

Usage: https://github.com/golang/tools/blob/master/cmd/gomvpkg/main.go#L30
`go get` path: `golang.org/x/tools/cmd/gomvpkg`

**Comment by fatih** [comment]
Hi @pianohacker 

I've thought about this a long time ago. But this command takes a lot of time and it's better to call this from a shell and observe the state instead of calling it inside from vim-go. Not sure how efficient and usable this could be from vim-go.

**Comment by phux** [comment]
@pianohacker I use this hack:
https://github.com/phux/.dotfiles/blob/master/roles/neovim/files/ftplugin/go.vim#L149
