### ISSUE TITLE
Latest master breaks tab completion

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#1989]
### What did you do? (required. The issue will be **closed** when not provided.)
Pulled down master, could no longer tab complete to obtain autocomplete of methods within an imported package

### What did you expect to happen?
Tab completion to present a list of methods, structs, and variables within a package.

### What happened instead?
No list came up. Just checked out v1.18 and issue is no longer present.

### Configuration (**MUST** fill this out):

* vim-go version:
MASTER

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
N/A No changes between v1.18 and MASTER in regards to vimrc

* Vim version (first three lines from `:version`):
❯ nvim --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

* Go version (`go version`):
❯ go version
go version go1.10.3 darwin/amd64

* Go environment (`go env`):
❯ go env
GOARCH="amd64"
GOBIN="/Users/louis/git/go/bin"
GOCACHE="/Users/louis/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mc/xwfdd41j1j74xfmcmphbwpgw0000gn/T/go-build047933153=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bhcleek** [comment]
Try running `:GoUpdateBinaries`.

Also, Neovim 0.2.2 is no longer supported by vim-go; upgrade to Neovim 0.3.1.

**Comment by bhcleek** [comment]
Try running `:GoUpdateBinaries`.

Also, Neovim 0.2.2 is no longer supported by vim-go; upgrade to Neovim 0.3.1.

**Comment by ldelossa** [comment]
@bhcleek did both, no luck.

**Comment by bhcleek** [comment]
Autocompletion with Neovim is working for me. Can you provide a repository and that demonstrates the problem you're seeing?

Also, what do you mean by "tab completion"? I typically use ctrl-x ctrl-o` to do autocompletion.

**Comment by vn-ki** [comment]
I am experiencing the same thing. Omni completion does not work.

**Comment by bhcleek** [comment]
gocode is in a fractured state right now. vim-go and other editors are using github.com/mdempsky/gocode, but some other 
plugins use github.com/nsf/gocode. For various reasons, the two are incompatible.

Please try to make sure you're using mdempsky and duplicate the problem with only vim-go as your only plugin.

**Comment by bhcleek** [comment]
`:GoUpdateBinaries` will handle it for you.

**Comment by bhcleek** [comment]
Be sure to call `gocode close` first to shutdown nsf.

**Comment by ldelossa** [comment]
@bhcleek great call,

removed nsf/gocode
installed mdempsky/gocode

MUST kill the original GoCode binary if it's running, I did use ps to find and kill it. 

Working great now.
