### ISSUE TITLE
:GoInstallBinaries installs without .exe on Windows with GVIM

### ISSUE THREAD

**Issue by kozie** [fatih/vim-go#1994]
### What did you do? (required. The issue will be **closed** when not provided.)
- Installed Go freshly on a new laptop with the official msi (Windows 10 x64)
- Installed vim-go with plug on GVIM 8.1
- Ran :GoInstallBinaries in gvim

Running something like go get -u github.com/mdempsky/gocode from cmd seems to do the job as expected.

### What did you expect to happen?
All necessary binaries installed and vim-go fully functioning

### What happened instead?
all binaries installed don't end with .exe resulting in vim-go features not functioning.

### Configuration (**MUST** fill this out):
* vim-go version: 1.18 (latest as of now)

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc): https://github.com/kozie/dotfiles/blob/master/.vimrc

* Vim version (first three lines from `:version`): 
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:36:07)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1

* Go version (`go version`):
go version go1.11 windows/amd64

* Go environment (`go env`):
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Koos\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Koos\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Koos\AppData\Local\Temp\go-build015388142=/tmp/go-build -gno-record-gcc-switches

**Comment by bhcleek** [comment]
Fixed in https://github.com/fatih/vim-go/pull/1990

**Comment by kozie** [comment]
Oh really, i totally missed that issue 🙈 Thanks anyway!
