### ISSUE TITLE
Input delay when hitting enter outside of a func

### ISSUE THREAD

**Issue by mirza-s** [fatih/vim-go#1996]
### What did you do? (required. The issue will be **closed** when not provided.)
Open a go file with more than 400 lines of code.
Navigate near the end of the file that is not inside a func(). Hit enter 3 times.

### What did you expect to happen?
No delay

### What happened instead?
Delay of around 300ms per line depending on file position.

Not noticeable in first 300 lines of code.  Becomes worse for larger files.
No noticable delay if done inside a func() independent of file size.

Bug Introduced in commit 8ab771c

**Comment by bhcleek** [comment]
Thank you for the report. I reverted https://github.com/fatih/vim-go/commit/8ab771cb0f2d1993cb8bb9c633733d56bbfce479; there isn't an obvious solution for the slowdown it caused, and it's not essential...
