### ISSUE TITLE
ftplugin for gomod file type returns early because b:did_ftplugin already defined

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#1997]
### What did you do? (required. The issue will be **closed** when not provided.)

* Open `go.mod` file
* `:set ft` confirms file type is `gomod`
* `:set commentstring` however shows `/*%s*/`. This contradicts with https://github.com/fatih/vim-go/blob/master/ftplugin/gomod.vim#L13

Hence anything that comments a section of a `go.mod` file introduces the wrong comment syntax. 

### What did you expect to happen?

* `:set commentstring` to give `// %s` 

### What happened instead?

Per answer to first section.

The reason appears to be that loading a `go.mod` file initially causes Vim to consider the file `ft=lprolog`. This also has the side effect of setting `b:did_ftplugin=1`. Hence when [this check](https://github.com/fatih/vim-go/blob/master/ftplugin/gomod.vim#L3-L5) is run as part of the subsequent detection and setting of `ft=gomod`, the ftplugin returns early.

### Configuration (**MUST** fill this out):

* vim-go version:

78d5fbad54188900547ef18b4c67d421968ba9aa

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 24 2018 14:47:13)
Included patches: 1-429
Compiled by myitcv@myitcv
```

* Go version (`go version`):

```
go version go1.11 linux/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build986536959=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
Does https://github.com/fatih/vim-go/pull/1947 resolve this for you?

**Comment by myitcv** [comment]
@bhcleek it does, yes. I'll defer to you/others whether that is the "right" solution in this case though.
