### ISSUE TITLE
Can't seem to get vim-go working :(?

### ISSUE THREAD

**Issue by Ncage1974** [fatih/vim-go#200]
Hello everyone. I posted the same problem on StackOverflow (http://stackoverflow.com/questions/26291691/install-vim-go-in-linux) and no one has yet been able to figure out my issue. So here goes:

I would best be described as a dabbler at this point in linux/vim. I'm trying to get started with go. Trying to install the vim-go plugin and i'm having issues. I'm using the following post (http://obahua.com/setup-vim-for-go-development/).

I added the following to the end of my ~/.bashrc file:
export GOPATH=~/gocode
export PATH=$PATH:$GOPATH/bin
and created the following directory ~/gocode

So i created my ~/.vim/bundle & ~/.vim/autoload directories. I downloaded pathogen.vim to the autoload directory. I cloned the github repository for vim-go into the bundle directory which created a vim-go directory.

I created my ~/.vimrc file and added the following:
call pathogen#infect()
syntax enable
filetype plugin on
set number
let g:go_disable_autoinstall = 0

I executed the following from the vim console (which worked after installing Hg):
:GoInstallBinaries
FYI, i don't use vundle and to be honest don't even know what it is :).

So far the plugin doesn't seem to be working. A guy on stackoverflow was able to help me getting the help part working but thats all thats working. Any help would be appreciated.

**Comment by paulswanson** [comment]
It's not possible to get vim-go working on a standard Ubuntu 14.04 install with the instructions provided.

**Comment by mborho** [comment]
Same problem here.

**Comment by atomduan** [comment]
Same problem here
