### ISSUE TITLE
nvim, unknown option build

### ISSUE THREAD

**Issue by mikowiec** [fatih/vim-go#2003]
### What did you do? (required. The issue will be **closed** when not provided.)
open file "main.go" from vim-go-tutorial

### What did you expect to happen?
file should be opened

### What happened instead?
- 1 test case: nvim freezed, while open file *.go via command line
- 2 test case: nvim started well empty, then open *.go file via :e command.  
  Error message observed: `E518: Unknown option: build` , line 21 in  
  `.config\nvim\plugged\vim-go\compiler\go.vim`

### Configuration (**MUST** fill this out):

* vim-go version: 1.17

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`): NVIM v0.2.2 

* Go version (`go version`): go version go1.8.3 windows/386

* Go environment (`go env`):

### issue fixed, but not tested carefully:
file: `.config\nvim\plugged\vim-go\compiler\go.vim`, line 21
before:
```vim
if filereadable("makefile") || filereadable("Makefile")
  CompilerSet makeprg=make
else
  CompilerSet makeprg=go\ build
endif
```
fixed:
```vim
if filereadable("makefile") || filereadable("Makefile")
  CompilerSet makeprg=make
else
  let gocmd = 'go build'
  CompilerSet makeprg=gocmd
endif
```

**Comment by bhcleek** [comment]
Does this still happen for you with Neovim 0.3.1?

**Comment by mikowiec** [comment]
Tested with neovim 0.3.1, issue exists

**Comment by bhcleek** [comment]
I don't have a Windows box to test on quickly, and it's not clear to me whether this a general problem on Windows or only with Neovim on Windows...

**Comment by smartding** [comment]
> I don't have a Windows box to test on quickly, and it's not clear to me whether this a general problem on Windows or only with Neovim on Windows...

neovim 0.3.1 has no problem opening golang source files on Ubuntu 16.04
