### ISSUE TITLE
vim-go add support to gx package management?

### ISSUE THREAD

**Issue by xiedeacc** [fatih/vim-go#2008]
### What did you do?
I want to jump a function in IPFS, bu it faild if a function was defined in  "gx/ipfs/QmYmsdtJ3HsodkePE3eU3TsCaP2YvPZJ4LoXnNkDE5Tpt7/go-multiaddr" like this
maybe it caused that package was managed by gx, so vim-go cannot find the source code, how fix it? or
vim-go add support to gx package manager?

* vim-go version:
newest
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
if really need, I'll provide it
* Vim version (first three lines from `:version`):
8.1
* Go version (`go version`):
1.10
* Go environment (`go env`):
GOBIN="/root/src/go/bin"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/src/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build853729181=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
As long as the package is in `GOPATH`, jumping should work fine. Can you create an easily reproducible example of where it fails?
