### ISSUE TITLE
:GoBuild always succeeds (Windows/Vim 8)

### ISSUE THREAD

**Issue by jagardaniel** [fatih/vim-go#2009]
Hi! I'm new to both vim, go and vim-go so I'm sorry if this isn't an vim-go issue or already an known issue. I didn't find anything when I searched. I guess Windows and vim isn't a super popular combination.

### What did you do?
I'm trying to build a very simple file using `:GoBuild`.
```go
package main

import (
	"fmt"
)

func main() {
	test := "test"
	fmt.Println("Hello!")
}
```
### What did you expect to happen?
I expect the build to fail since the variable test is not used.

### What happened instead?
The build succeeds.

### My amateur analysis
So it looks like the `:GoBuild` ignores the result of `go build [...]` since everything is a success even if the code shouldn't compile. I'm using Vim 8 on Windows and I don't have this issue on Linux. I have tried it on another Windows machine with a default installation of go, vim8 and vim-go and it has the same issue. I'm running Windows 10.

`:GoBuild` works as it should if:
* I set a buildtag to anything other than nothing. `let g:go_build_tags = ' '` is enough.
* I use the function without async (for vim7) in the `autoload/go/cmd.vim` file
* Neovim (0.3.1 on Windows) with the same vim-go version

My guess is that this has something to do with the arguments for the `go build [...]` command and how vim8 is executing async jobs. I tried to dig a little bit in the code and this how the argument list looks like `['go', 'build', '-tags', '', '.', 'errors']` with no build tags set. If i run the command on Windows or Linux it just returns 0 with no output. Could this be what happens on Windows, that the command doesn't even run? But at the same time `:GoBuild` works on Linux so I'm not sure.

But this is actually good for my self-esteem since everything is a success!

### Configuration

* vim-go version:
92b360f

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  2 2018 22:03:35)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-450

* Go version (`go version`):
go version go1.11.1 windows/amd64

* Go environment (`go env`):
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\daniel\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\daniel\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\daniel\AppData\Local\Temp\go-build183390022=/tmp/go-build -gno-record-gcc-switches

Thanks
/Daniel

**Comment by bhcleek** [comment]
This is mostly a bug in Vim8; it *ought* to be able to parse the arguments in the list and make the right call.

**Comment by bhcleek** [comment]
@jagardaniel can you give #2011 a try to see if it resolves the problem for you?

**Comment by bhcleek** [comment]
🤦‍♂️ sorry about that; it was missing some quotes around the function name. Can you try it again?

**Comment by jagardaniel** [comment]
Thanks again @bhcleek. I tried the updated version but `:GoBuild` still succeeds every time. I could be wrong  but it looks like the variable set in the if-section isn't actually used by `job_start` so it still uses the old cmd list.

**Comment by bhcleek** [comment]
Another 🤦‍♂️ . Thanks for the help and your patience. Sorry for the trouble. I corrected the assignment if you want to try again. If not, I understand; in that case I'll try to find a windows box to test with soon.

**Comment by jagardaniel** [comment]
Don't worry. I'm just glad if I can help in any way :) I tried the updated version and it works great, so #2011 fixes the issue I have. Thank you for the help, much appreciated.
