### ISSUE TITLE
Add syn but not work

### ISSUE THREAD

**Issue by und3fined** [fatih/vim-go#2012]
Hi guys,

this is script added to `go#config#HighlightVariableDeclarations()` but not work

```
" Variable Declarations
if go#config#HighlightVariableDeclarations()
  syn match goVarDefs /\v\w+(,\s*\w+)*\ze(\s*:\=)/
  syn match goVarDefs /\v(var\s*|const\s*)\zs\w+\ze(\s*\w+)/
  hi def link goVarDefs           Special
endif
```
```
var foo Bar
```
`foo` not highlight 

i'm try command, it's work well
```
:match goVarDefs /\v(var\s*|const\s*)\zs\w+\ze(\s*\w+)/
```

![Sample](https://downloader.disk.yandex.com/disk/d55f411f9d3b9d3335668d8804f8ba147a8e2afb72ca5a734303067bb1a6623d/5bbb38a8/Sv-X_3tZJ0Tw_p8DbO3W5u_V3gbuZtj5Fi8VnKjdaBqpdY-Lh0jDQni-5RePwneaW7QnK5aRjnmiAUudoZs8vg%3D%3D?uid=302670053&filename=Screen%20Shot%202018-10-08%20at%2013.55.24.png&disposition=attachment&hash=&limit=0&content_type=image%2Fpng&fsize=161134&hid=a7f2fc821d6d7b5edc96d9c959106b81&media_type=image&tknv=v2&etag=14b57474c5ac05983487ea3a8e279c25)

Please help @fatih

**Comment by Carpetsmoker** [comment]
Did you enable the setting? See `:help go-syntax`.

**Comment by und3fined** [comment]
Hi @Carpetsmoker 
Settings HighlightVariableDeclarations enabled. My config show on :verborse syntax
But not work

**Comment by bhcleek** [comment]
It looks like you're trying _add_ highlighting of the variable name in a variable declaration. The line you're trying to add, though, may need to take into account that `var` is matched as a keyword, so always takes precedence. If you can change your new line to take into account the `goVar` group by using a `contains` predicate, you may be able to accomplish what you're trying to do. e.g.: https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L162

**Comment by und3fined** [comment]
I'm use for this highlight
`au BufEnter *.go match goVarDefs /\v(var\s*|const\s*)\zs\w+\ze(\s*\w+)/`

thank @bhcleek 
i can't read all logic highlight on `syntax/go.vim`, so i can't change goVar/goConst name
