### ISSUE TITLE
vim commands :wq and :wqa quit vim before saving *.go files

### ISSUE THREAD

**Issue by justinjensen** [fatih/vim-go#2019]
### What did you do? (required. The issue will be **closed** when not provided.)
Tried to save *.go files and quit vim using the vim commands :wq and :wqa

### What did you expect to happen?
My changes to be saved and vim to exit

### What happened instead?
Vim exited but the changes made to the file did not persist.

### Configuration (**MUST** fill this out):
* vim-go version: 620e8ac

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```vim
set t_Co=16
set encoding=utf-8
set tabstop=2
set shiftwidth=2
set expandtab

set undodir=~/.vim/undo//
set backupdir=~/.vim/backup//
set directory=~/.vim/swapfiles//

map <C-z> :tabp<CR>
map <C-x> :tabn<CR>
map <C-@> :tabe
imap <C-z> <ESC>:tabp<CR>i
imap <C-x> <ESC>:tabn<CR>i
imap <C-@> <ESC>:tabe

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
Plug 'pangloss/vim-javascript'
call plug#end()

syntax on
```

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 12 2018 23:25:13)
Included patches: 1-374
Compiled by Arch Linux

* Go version (`go version`):
go version go1.11.1 linux/amd64

* Go environment (`go env`):
```bash
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/justin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/justin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build201364610=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by justinjensen** [comment]
After spending more time with it, the problem seems to only be occurring with new *.go files and only occurs intermittently.  This is what I found:
`:w` followed by `:q` succeeds 100% of the time with both new files and existing files.
`:wq` and `:wqa` succeed 100% of the time with only existing files open.
`:wq` fails about 90% of the time with only one new file open.
`:wqa` fails 100% of the time with multiple new files open.
`:wqa` fails 100% of the time with multiple existing and new files open but only with new files, existing files are saved as expected.

**Comment by bhcleek** [comment]
There's a simple duplication path:
```
vim main.go
:wqa
```

This seems to be a vim problem, not a vim-go problem. Here's two ways to duplicate the problem without vim-go being involved:
```
vim -u NONE main.go
:wqa
```
```
vim main.foo
:wqa
```

Since this is not a vim-go problem, I'm closing this issue.
