### ISSUE TITLE
[Feature] Use <cword> by default for :GoImport

### ISSUE THREAD

**Issue by kristijanhusak** [fatih/vim-go#2020]
It would be great to default `:GoImport` to use the `expand('<cword>')`, instead of requiring input each time. It can be really time consuming to type in what i want to import.

**Comment by bhcleek** [comment]
Try using `let g:go_fmt_command = "goimports"`; I very rarely have to use `:GoImport` with that setting.

**Comment by kristijanhusak** [comment]
Yeah that works. Thanks.
