### ISSUE TITLE
vim-go reads from combined stdout+stderr when invoking godef

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#2026]
### What did you do? (required. The issue will be **closed** when not provided.)

Setup with:

```
export GOPATH=$(mktemp -d)
export PATH=$GOPATH/bin:$PATH
cd $(mktemp -d)
go mod init example.com/hello
GO111MODULE=off go get github.com/ianthehat/godef
echo "cGFja2FnZSBtYWluCgppbXBvcnQgImZtdCIKCmZ1bmMgbWFpbigpIHsKCWlmIHsKCXZhciBteSBzdHJpbmcKCWZtdC5QcmludGxuKCJzID0gJXZcbiIsIG15KQp9Cg==" | base64 --decode >main.go
cat main.go
```

which gives:

```
package main

import "fmt"

func main() {
        if {
        var my string
        fmt.Println("s = %v\n", my)
}
```

We are trying to use `godef` to jump from the usage of `my` (byte offset 89)

This is a Go modules-aware version of `godef`. 

As you can see, it outputs to stderr:

```
$ godef -o 89 -f $PWD/main.go
go list stderr <<# example.com/hello
./main.go:6:5: syntax error: missing condition in if statement
>>
/tmp/tmp.1t76r4tRWE/main.go:7:6
$ godef -o 89 -f $PWD/main.go 2>/dev/null
/tmp/tmp.1t76r4tRWE/main.go:7:6
```

`vim-go` appears to be reading from a combined stdout + stderr, because trying to perform a `:GoDef` in Vim fails and causes a jump to an empty file, corresponding to the first line of the combined output above:

```
"go list stderr <<# example.com/hello" [New DIRECTORY]
```

Per https://gophers.slack.com/archives/C0VPK4Z5E/p1539801419000100, vim-go should be reading from stdout, and only in case the process exits with a non-zero exit code print stderr:

```
 myitcv [19:35]
Thanks @Heschi Kreinick - the issue at the moment is that Vim appears to be reading the _combined_ output (i.e. stdout + stderr) and not separating between the two
According to Russ some time ago (can't recall the issue), the general best practice in this respect is only to read stdout
(e.g. with `go list`)
And then, as you suggest, print stderr in case of a non-zero exit code
Just wanted to firm up on that (or any other approach) before suggesting a fix in `vim-go`

Heschi Kreinick [19:36]
I think that's absolutely right as a general rule. It might make sense to make packages.Load quieter anyway just for expedience.
```

### What did you expect to happen?

Jump to the definition of `my`

### What happened instead?

Per above.

### Configuration (**MUST** fill this out):

* vim-go version: 75b54e482f6c104fb41a9687e2cba4105e9c8fcf

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 17 2018 06:34:38)
Included patches: 1-481
Compiled by myitcv@myitcv
```

* Go version (`go version`):

```
go version go1.11.1 linux/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build054412873=/tmp/go-build -gno-record-gcc-switches"
```

cc @bhcleek

**Comment by myitcv** [comment]
FYI as of https://go-review.googlesource.com/c/tools/+/142997 this is no longer an issue. But for completeness, given the referenced Slack channel, still feels like a change we should make.

**Comment by bhcleek** [comment]
Thanks, @myitcv.

You're right, vim-go does read the combined output. Changing that has larger implications, and I'm not sure there's a good general solution for Vim. We still need to support vim74 for a while, and there isn't a good way to separate stdout and stderr output using vim's `system()` call.

However, vim-go shouldn't be jumping to the file location if `godef` exits with a non-zero exit code (see https://github.com/fatih/vim-go/blob/master/autoload/go/def.vim#L72-L75). As it stands, I can't duplicate what you're seeing; the output of `godef` from `github.com/ianthehat/godef` isn't the same as you documented, and the exit code is non-zero. 🤔 

FWIW, I agree with Heschi:
> It might make sense to make packages.Load quieter anyway just for expedience.

**Comment by myitcv** [comment]
> FWIW, I agree with Heschi:

Great; that's what's happened per https://github.com/fatih/vim-go/issues/2026#issuecomment-430800201

It's highly likely you've tried post that CL being merged hence not being able to repro... but in any case everything is working now so I agree this is not an urgent fix on the `vim-go` side, particularly if it has wider implications.
