### ISSUE TITLE
Missing GoDebug* Documentations

### ISSUE THREAD

**Issue by LinArcX** [fatih/vim-go#2028]
Hi. i'm reading this tutorial:
https://github.com/fatih/vim-go-tutorial
But i cannot see any documentation about __GoDebugStart__, __GoDebugBreakpoint__ and etc..
How to work with them?

**Comment by Carpetsmoker** [comment]
It's not in the "tutorial", which is not being maintained any more. The `:help go-debug` page is fairly comprehensive, so that's a good place to start from.

**Comment by Carpetsmoker** [comment]
The tutorial is not being maintained any more, as it says at the top of the README.

**Comment by LinArcX** [comment]
Aha. Yes. Thank you again.
