### ISSUE TITLE
gocode-gomod completions slow with module mode

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#2035]
### What did you do? (required. The issue will be **closed** when not provided.)

Tried to use completions within an unsaved Go file within a module.

Install:
* `gocode` as of https://github.com/stamblerre/gocode/commit/12640289f65065d652cc942ffa01a52bece1dd53
* `goimports` as of https://go-review.googlesource.com/c/tools/+/142697/

Clone https://github.com/myitcvscratch/20181030_bc_vimgo_slowness_repro.git to a directory in, for example, `/tmp`

In one terminal run `gocode-gomod` as a server:

```
gocode-gomod -s -debug
```

In the other terminal, open `main_test.go`:

* jump down to line 70
* replace the entire line with `S` in normal mode (which will leave you in insert mode)
* type `mod<C-x-o>` to try and complete `mod`

Observe that there is a delay before the `gocode-gomod` server even gets invoked. When it is invoked it responds quickly. 

At this point, notice that we have been running with `autowrite` turned off, so the delay is because of https://github.com/fatih/vim-go/blob/master/autoload/go/cmd.vim#L11

Now `:set autowrite` and repeat the three bullet point steps above.

Notice there is _still_ a delay in invoking the `gocode-gomod` server.

### What did you expect to happen?

Quick completions. 

If I don't have `autowrite` set, I shouldn't need to be reminded of that via a message, or be arbitrarily delayed after the message.

If I do have `autowrite` set, then we should not be firing `AutoCmd`'s for save, because this will invoke `goimports` which, in module-mode, is much slower than its non-module counterpart.

Ideally, we would temporarily write the current state of the buffer to disk (without invoking `AutoCmd`'s, run `gocode-gomod`, then restore the file on disk and buffers to their original state. But given this is just a temporary workaround until we get overlay support in `go/packages`, I think simply skipping the `AutoCmd`'s will suffice. Then ensuring post the completion request that we "taint" the file so the user is left in the same state of the file being unwritten. This is less than ideal because the file on disk is not left in the state the user likely expects... because they did not initiate an explicit write to disk (arguably `autowrite` leaves the door open for this but still)

### What happened instead?

Slow completions; despite the actual `gocode-gomod` command itself being very fast.

### Configuration (**MUST** fill this out):

* vim-go version: d5ce080c25806d68189be641e19996898138f1a4

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```vim
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 09:06:54)
Included patches: 1-500
Compiled by myitcv@myitcv
```

* Go version (`go version`):

```
go version go1.11.1 linux/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/tmp.qEA7mlDaXq"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.COn5IjkoG7/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build879364371=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
What value do you have set for `g:go_gocode_propose_source` ?

> Observe that there is a delay before the gocode-gomod server even gets invoked. When it is invoked it responds quickly.

Did you profile it? If not, then how did you determine "when it is invoked"? 🤔  If you did, then I'd love to see that profile, but don't worry about trying to provide a profile if you don't already have one; I'll take care of it while analyzing.

> If I don't have autowrite set, I shouldn't need to be reminded of that via a message, or be arbitrarily delayed after the message.

I disagree; as long as we require the file to be written, it's important to communicate to the user that vim-go cannot complete the requested operation reliably.

> If I do have autowrite set, then we should not be firing AutoCmd's for save, because this will invoke goimports which, in module-mode, is much slower than its non-module counterpart.

If the performance problem is in goimports, then arguably this isn't a problem for vim-go to solve, especially if goimports is going to be fixing it soon 🤔 

I'll take a look soon to see if there's a good way to handle what you're trying to do in a way that is more performance without introducing subtle edge cases (skipping autocmds and restoring the file may not be as simple as you'd think because of many subtle edge cases that vim-go has had to contend with in other areas with similar concerns).

Philosophically, using autowrite here is generally fine; vim-go uses it in many other places (e.g. when linting), and it's only being done now because of the limitations of `golang.org/x/tools/go/packages`, which is used by gocode.

**Comment by bhcleek** [comment]
I've profiled this several times and and do not see the autocmds being a problem; gocode's initial start is always slow whether in module mode or not. I've seen the initial autocompletion with modules perform slowly, but it's much faster after the first time.

**Comment by myitcv** [comment]
Sorry, I totally missed your response 8 days ago. I'll pull together a screen recording of the issue.

**Comment by myitcv** [comment]
> Did you profile it?

Just for my future reference, can you point me towards something that shows how/where to do this? My "profiling" was simply anecdotal "this feels slow". Then when I ran up `gocode-gomod -s -debug` in a separate terminal I could see where the extra delay was coming in, because the `gocode-gomod` server was not being hit immediately. 

>> If I don't have autowrite set, I shouldn't need to be reminded of that via a message, or be arbitrarily delayed after the message.

> I disagree; as long as we require the file to be written, it's important to communicate to the user that vim-go cannot complete the requested operation reliably.

Fair enough that we warn people, but perhaps once at startup would do as opposed to on each completion request? Just FYI, I didn't see those warning messages in any case, just felt the 1 second delay.

> If the performance problem is in goimports, then arguably this isn't a problem for vim-go to solve, especially if goimports is going to be fixing it soon 🤔

This rather unfortunate in-between state is simply a function of not having overlay support. So whilst we're not in a perfect state, then I don't think our work arounds need to be perfect either 😄. So any discussion about auto-write is, by definition if overlay support comes soon, going to be short-lived. I think we just need to come up with the best solution for now that gives people the best possible modules experience given the current state of the tools out there.

FWIW I think we potentially have different tolerances for delay. I'm seeing a noticeable (to me) delay without the `noa w | set modified` approach (instead of `call go#cmd#autowrite()`), so I have that change applied locally on top of the latest vim-go release. Again, I don't mind running with that as a local solution for now.

**Comment by bhcleek** [comment]
Here's how to profile:
```
:profile start profile.log
:profile func *
:profile file *
" At this point do slow actions
:profile pause
:noautocmd qall!
```

I didn't see any less delay without saving. Do you have any autocommands setup for Go files other than what vim-go automatically configures?

**Comment by bhcleek** [comment]
I'm reluctant to write without autocmds, because then we'll be putting code in a state that's unexpected (e.g. unformatted and without the expected imports). The delay you've described would seem to be more significant than is explained by taking 0.2 seconds to write a file.

**Comment by myitcv** [comment]
@bhcleek as discussed offline, given this is hopefully a temporary (and short-lived) situation we find ourselves in until overlay support arrives, I don't think it's worth us spending too much time on this 👍 

> The delay you've described would seem to be more significant than is explained by taking 0.2 seconds to write a file.

Not quite sure I follow, but the 0.2 seconds is definitely coming from autocmds, of which `goimports` will be one.
