### ISSUE TITLE
Add option to avoid cursor jump for linters and others

### ISSUE THREAD

**Issue by krhubert** [fatih/vim-go#2038]
### What did you do? (required. The issue will be **closed** when not provided.)

run `:GoMetaLinter!`

### What did you expect to happen?

Lint error list without cursor jump to first error (`go#list#JumpToFirst`)

### What happened instead?

`E477: No ! allowed`

### Configuration (**MUST** fill this out):

* vim-go version:

commit d5ce080c25806d68189be641e19996898138f1a4

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```vim
let g:go_metalinter_autosave = 1
```

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 20:13:43)
Included patches: 1-197, 322, 377-378, 422, 550
Modified by pkg-vim-maintainers@lists.alioth.debian.org
```

Moreover, it would be nice to have this configurable via vimrc:
```vim
let g:go_metalinter_autosave = 1
let g:go_metalinter_not_jump = 1
```

**Comment by fatih** [comment]
We already have this:

```
<
                                                        *'g:go_jump_to_error'*

Use this option to enable/disable passing the bang attribute to the mappings
|(go-build)|, |(go-run)|, etc..  When enabled it will jump to the first error
automatically (means it will NOT pass the bang attribute to the appropriate
command, i.e: (go-run) -> :GoRun ). Note, that calling this doesn't have any
affect on calling the commands manually. This setting is only useful for
changing the behaviour of our custom static mappings. By default it's enabled.
>
  let g:go_jump_to_error = 1
<
```

Is this not helpful?

**Comment by krhubert** [comment]
I haven't known about go_jump_to_error - It is exactly what I've been looking for but... it's not compatible with Gometalinter because this cmd doesn't support bang attribute.

So it is all about adding bang attribute to gomentalinter.

**Comment by krhubert** [comment]
@bhcleek big thanks for the fix!

Unfortunately there is still pbm when the linter is executed via job (https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L64)

For now I just comment this and it works but I just wanted let you know.

Here callback from Options is called and there is something wrong with the callback
https://github.com/fatih/vim-go/blob/master/autoload/go/job.vim#L323

Check https://gist.github.com/krhubert/c77784548604a544c0b19350015ffe0e for presentation.

Vim config:

```vim
set nocompatible
filetype off

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()

let g:go_jump_to_error = 0
let g:go_metalinter_autosave = 1
```
