### ISSUE TITLE
Shouldn't include webapi

### ISSUE THREAD

**Issue by mattn** [fatih/vim-go#204]
It seems vim-go include webapi/json.vim. I'm glad to see webapi-vim is used for another plugins.
However many users uses webapi-vim as plugin. So webapi/json.vim won't be updated even though webapi-vim is upgraded.

**Comment by fatih** [comment]
Webapi will be removed, once we change back Oracle's functions to read from json to plain GNU style. Related issue #311

**Comment by fatih** [comment]
Once we merge #319, Webapi will be removed.

**Comment by fatih** [comment]
Webapi is now removed.
