### ISSUE TITLE
New installation not showing all commands

### ISSUE THREAD

**Issue by sbromberger** [fatih/vim-go#2042]
### What did you do? (required. The issue will be **closed** when not provided.)
Following the installation instructions in the README (vim 8), I cloned the repo into `~/.vim/pack/plugins/start/vim-go` and then checked out the latest tag (v1.18).

I then ran `vim bfs.go` (an existing Go file) and did a `:GoInstallBinaries` and `:GoUpdateBinaries`.

I then exited, restarted, and tried `:Go^D`. The only commands available were , `GoInstallBinaries`, `GoUpdateBinaries`, and `GoPath`.

Additional info:
```
runtimepath=~/.vim,~/.vim/pack/plugins/start/vim-go,/usr/local/share/vim/vimfiles,/usr/local/share/vim/vim81,/usr/local/share/vim/
vimfiles/after,~/.vim/after
```
### What did you expect to happen?
I expected to see more commands.

### What happened instead?
I only saw the aforementioned commands.

### Configuration (**MUST** fill this out):
* vim-go version:
```
~/.vim/pack/plugins/start/vim-go$ git status
HEAD detached at v1.18
```
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
set number
```
* Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 06:56:05)
macOS version
Included patches: 1-500
```
* Go version (`go version`):
```
go version go1.11.1 darwin/amd64
```

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/me/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rx/z4bctjjj6jl6nf0vsyyrp3xc001qfx/T/go-build364553275=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by sbromberger** [comment]
I noticed that v1.18 was still using `nsf/gocode` so I switched to master, but it still did not resolve the issue. Stepping through with `vim -D` shows the plugin being evaluated.

**Comment by bhcleek** [comment]
It doesn't look like your vimrc has filetype plugins enabled. Try adding `filetype plugin indent on` to it.

**Comment by sbromberger** [comment]
I managed to get up and running with Plug so I think I’ll stick with that. Thanks.

**Comment by YaguraStation** [comment]
Can reproduce @sbromberger issue with vim 8.0 (without _vim-plug_). 

Something to add: When starting vim without a `~/.vimrc` the other commands re-appear and work. Starting vim with the simplest vimrc (e.g. one line `set number`) causes this issue to occur again.

**Comment by patrickjane** [comment]
I've just installed the go tools on macOS (via pkg) and installed the vim-go plugin the same way the OP did (git clone), and while `:GoInstallBinaries` successfully installed stuff in `$HOME/go/`, I also still see only the initial 3 commands `GoInstallBinaries`, `GoUpdateBinaries`, and `GoPath`.
