### ISSUE TITLE
gofmt erases the index buffer from vim-fugitive

### ISSUE THREAD

**Issue by sp4ke** [fatih/vim-go#2043]
### What did you do? (required. The issue will be **closed** when not provided.)
1. Use `let g:go_fmt_autosave = 1` as in the default setup.
2. Have `vim-fugitive` plugin installed and be in a Git repo with changes in the working tree compared to the index
3. Run `Gdiff :0` or `press D` from a changed file in the status window (`:Gst`)
4. Move changes to the index buffer using `do`
5. Save the index buffer `:w`
6. The index buffer is emptied because `gofmt` runs for it as it also has a `go` filetype.

### What did you expect to happen?
1. `gofmt` should not run on *fugitive* buffers which is any buffer starting with `fugitive://`
2. ~~An other acceptable solution that is not dependent dependent on plugins is to have an option to disable the auto formatting on the fly. I did not find such a function and even changing the filetype before writing the git index buffer does not work.~~ I missed the `:GoFmtAutoSaveToggle` option, which temporarily  fixes the problem but is still a manual operation to do every time a diff buffer is opened.  

### What happened instead?
The fugitive index buffer was formatted and emptied before being saved which effectively an *empty file is staged* 

I tested the same scenario with auto formatting disabled and the issue does not occur. 

### Configuration (**MUST** fill this out):

* vim-go version: HEAD

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc): No vimrc used, just fugitive installed

* Vim version (first three lines from `:version`):
NVIM v0.3.1                                                                                                                                                                   
Build type: Release                                                                                                                                                           
LuaJIT 2.0.5 

* Go version (`go version`):
go version go1.11.1 linux/amd64       
                                                                                                                                        
* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN="***"
GOCACHE="***"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="***"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build148903007=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
I'm unable to duplicate what you're describing with Vim8. It looks like this is a vim-fugitive problem with Neovim: https://github.com/tpope/vim-fugitive/issues/1102.
