### ISSUE TITLE
Plugin conflicts with majutsushi/tagbar and sheerun/vim-polyglot

### ISSUE THREAD

**Issue by cmavromichalis** [fatih/vim-go#2046]
### What did you do? (required. The issue will be **closed** when not provided.)
Created the following vimrc file:
" set up vim-plug
call plug#begin('~/.vim/plugged')

Plug 'sheerun/vim-polyglot'
Plug 'fatih/vim-go'
Plug 'https://github.com/majutsushi/tagbar.git'
" initialize plugin system
call plug#end()

" Go-vim plugin
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_auto_type_info = 0
let g:go_highlight_trailing_whitespace_error = 0
let g:go_fmt_command = 'goimports'
let g:go_list_type = 'quickfix'

" vim-go error suppression
let g:go_fmt_fail_silently = 0

" tagbar settings
autocmd VimEnter * nested :TagbarOpen

" Syntax highlighting
syntax enable

### What did you expect to happen?
The plugins to work together

### What happened instead?
They do not; I'm not sure who's issue it is, so to say, but I see the error is from vim-go so thought I would report it. Use the vimrc file from above and open any .go file to reproduce

### Configuration (**MUST** fill this out):

* vim-go version:
master; 8513febab5c698553acc7ac33f4185fb2da664d2

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
It is above.

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  5 2018 20:31:42)
Included patches: 1-513
Compiled by me

* Go version (`go version`):
go version go1.11 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/me/projects/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build251403446=/tmp/go-build -gno-record-gcc-switches"

<img width="952" alt="screen shot 2018-11-06 at 4 52 42 pm" src="https://user-images.githubusercontent.com/15347540/48101966-1ec8bd80-e1e6-11e8-91b6-00ee08d76447.png">

**Comment by bhcleek** [comment]
vim-polyglot vendors part of vim-go. I'd recommend disabling go from vim-polyglot.

See https://github.com/fatih/vim-go/issues/2045
