### ISSUE TITLE
:GoDeclsDir open correct file with wrong content.

### ISSUE THREAD

**Issue by konstantinzolotarev** [fatih/vim-go#2047]
### What did you do? (required. The issue will be **closed** when not provided.)
Run `:GoDeclsDir` command and jumped to struct/function declaration.

### What did you expect to happen?
File with this struct/function declaration opened

### What happened instead?
File opened but with content:
```
package main

import "fmt"

func main() {
  fmt.Println("vim-go")
}
```

And for test packages:
```
package main

import "testing"

func TestHelloWorld(t *testing.T) {
  // t.Fatal("not implemented")
}
```

After `:edit` command (tried to refresh file content) same file with correct content opened in new buffer.
Switching back to buffer opened by `:GoDeclsDir` this message appears
```
:bnext
W13: Warning: File "pkg/mailer/sendgrid.go" has been created after editing started
[O]K, (L)oad File:
``` 

### Configuration (**MUST** fill this out):

* vim-go version:
 Same issue with `master` branch and `v1.19` and also `v1.18`

**But it works as expected in `v1.17` and less**

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
https://gist.github.com/konstantinzolotarev/d4c218a864de503c7007428ad49aeb2d

* Vim version (first three lines from `:version`):
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -W
extra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_
GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20181019-20909-1hlaj6i/neovim-0.3.1/build/config -I/tm
p/neovim-20181019-20909-1hlaj6i/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20181019-20909-1hlaj6i/neo
vim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20181019-20909-1hlaj6i/neovim-0.3.1/build/include
Compiled by brew@HighSierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```
* Go version (`go version`):
`go version go1.11 darwin/amd64`
* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/konstantinzolotarev/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/konstantinzolotarev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7k/5zgrpjsx3xs6x6c58vklls7m0000gn/T/go-build504542193=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by konstantinzolotarev** [comment]
![vim](https://user-images.githubusercontent.com/286431/48131994-ad971200-e29a-11e8-95d5-46f168379148.gif)

**Comment by konstantinzolotarev** [comment]
Reverting this PR https://github.com/fatih/vim-go/pull/1878 makes it work correctly

**Comment by bhcleek** [comment]
Thank you for submitting a fix for this already.

I'm not clear on how to replicate the problem you've encountered, though, and from looking at your fix, I'm not sure why it's necessary given that the `ctrlp#decls#enter` sets `s:current_dir` and makes sure it's the current directory before calculating the filepath to pass to ctrlp. In the interest of being thorough and making sure we can test different scenarios with your change, can you please provide some clear steps to replicate that problem you've encountered?

**Comment by konstantinzolotarev** [comment]
I created new project similar to this: https://github.com/konstantinzolotarev/vim-go-test-project

Open project in `nvim` (`nvim .`)
Open file `pkg/mailer/mailler.go`
Run `:GoDelcsDir` - it will show list of definitions. and select any.
It will open file with wrong content

**Comment by bhcleek** [comment]
> Open project in nvim (nvim .)
> Open file pkg/mailer/mailler.go
> Run :GoDelcsDir - it will show list of definitions. and select any.

I am unable to duplicate the problem you've described using those steps; it works fine for me; I think something may be going on on your system. Are you willing to apply  this patch:
```
diff --git a/autoload/ctrlp/decls.vim b/autoload/ctrlp/decls.vim
index 5e68b3f..8de0088 100644
--- a/autoload/ctrlp/decls.vim
+++ b/autoload/ctrlp/decls.vim
@@ -46,6 +46,10 @@ function! ctrlp#decls#accept(mode, str) abort
     " i.e: /Users/fatih/vim-go/main.go
     let filepath =  fnamemodify(filename, ":p")
 
+    call go#util#EchoInfo("accept cwd: " . getcwd())
+    call go#util#EchoInfo("accept filename: " . filename)
+    call go#util#EchoInfo("accept filepath: " . filepath)
+
     " acceptile is a very versatile method,
     call ctrlp#acceptfile(a:mode, filepath)
     call cursor(line, col)
@@ -114,6 +118,10 @@ function! ctrlp#decls#enter() abort
       let space .= " "
     endfor
 
+    call go#util#EchoInfo("enter cwd: " . getcwd())
+    call go#util#EchoInfo("enter filename: " . decl.filename)
+    call go#util#EchoInfo("enter relative filename: " . fnamemodify(decl.filename, ":."))
+
     call add(s:decls, printf("%s\t%s |%s:%s:%s|\t%s",
           \ decl.ident . space,
           \ decl.keyword,
```
to v1.19 on your system and then provide the results of `:messages` here for further analysis?

**Comment by bhcleek** [comment]
Thank you! That actually pinpoints the problem:
```
vim-go: enter cwd: /Users/konstantinzolotarev/go/src/github.com/LiflandGaming/om-contact
vim-go: enter filename: /Users/konstantinzolotarev/go/src/github.com/LiflandGaming/om-contact/pkg/mailer/mailer.go
vim-go: enter relative filename: pkg/mailer/mailer.go
vim-go: accept cwd: /Users/konstantinzolotarev/go/src/github.com/LiflandGaming/om-contact/pkg/mailer
vim-go: accept filename: pkg/mailer/sendgrid.go
vim-go: accept filepath: pkg/mailer/sendgrid.go
```
In `ctrlp#decls#enter`, `s:current_dir` is set to the directory containing the current buffer and later the relative path is calculated relative to the actual current working directory, which in your case is a couple of directories up from the current buffer. Then in `ctrl#decls#accept`, the current directory is changed to the buffer's directory, and the absolute filename is calculated from that.
