### ISSUE TITLE
GoDebugStop results in lots of error messages

### ISSUE THREAD

**Issue by smartding** [fatih/vim-go#2059]
### What did you do? (required. The issue will be **closed** when not provided.)

GoDebugStop after GoDebugStart with some GoDebugBreakpoint set
The go file is a simple test file:

```
package main

import "fmt"

func main() {
        test(1, 2)
        fmt.Println("vim-go")
}

func test(a, b int) int {
        c := a + b   //break point here
        return c
}
```

### What did you expect to happen?

GoDebugStop should exit without any error

### What happened instead?

Lots of error messages after executing GoDebugStop.
From messages:
vim-go: API server listening at: 127.0.0.1:8181

Error detected while processing function 341[1]..<SNR>125_stack_cb:
line    2:
E474: Attempt to decode a blank string
Error detected while processing function 341[1]..<SNR>125_stack_cb:
line    2:
E474: Failed to parse
Error detected while processing function 337[1]..<SNR>125_stack_cb:
line    2:
E474: Attempt to decode a blank string
Error detected while processing function 337[1]..<SNR>125_stack_cb:
line    2:
E474: Failed to parse
Error detected while processing function 333[1]..<SNR>125_stack_cb:
line    2:
E474: Attempt to decode a blank string
Error detected while processing function 333[1]..<SNR>125_stack_cb:
line    2:
E474: Failed to parse
Error detected while processing function 328[1]..<SNR>125_start_cb:
line    1:
E474: Attempt to decode a blank string
Error detected while processing function 328[1]..<SNR>125_start_cb:
line    1:
E474: Failed to parse
vim-go: vim-go
vim-go: [debug] SUCCESS

### Configuration (**MUST** fill this out):

* vim-go version:
    commit 192725ad5016e95043804889fccb06bbba7e06d4

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
    call plug#begin('~/.vim/plugged')

    Plug 'fatih/vim-go'
    Plug 'ctrlpvim/ctrlp.vim'
    Plug 'scrooloose/nerdtree'
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'zchee/deoplete-go', { 'do': 'make'}
    Plug 'mileszs/ack.vim'
    Plug 'godlygeek/tabular'
    Plug 'plasticboy/vim-markdown'
    Plug 'tpope/vim-fugitive'
    Plug 'ekalinin/Dockerfile.vim', {'for' : 'Dockerfile'}
    Plug 'SirVer/ultisnips'
    Plug 'tpope/vim-commentary'
    Plug 'Raimondi/delimitMate'
    Plug 'ervandew/supertab'
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'

    call plug#end()

    set mouse=a        
    set number         
    set relativenumber 
    set encoding=utf-8 
    set hidden         
    set nobackup      
    set noshowmode     
    set cursorline     
    set splitright     
    set splitbelow     
    set ignorecase   
    set smartcase      
    set pumheight=10  
    set lazyredraw     

    set clipboard+=unnamedplus

    let g:go_highlight_functions             = 1 
    let g:go_highlight_function_arguments    = 1
    let g:go_highlight_function_calls        = 1
    let g:go_highlight_methods               = 1
    let g:go_highlight_structs               = 1
    let g:go_highlight_operators             = 1
    let g:go_highlight_types                 = 1
    let g:go_highlight_fields                = 1
    let g:go_highlight_extra_types           = 1
    let g:go_highlight_build_constraints     = 1
    let g:go_highlight_variable_declarations = 1
    let g:go_highlight_variable_assignments  = 1
    let g:go_highlight_format_strings        = 1
    let g:go_highlight_variable_declarations = 1
    let g:go_highlight_variable_assignments  = 1

    let g:go_fmt_command                     = 'goimports'  " fmt and manage imports
    let g:go_def_mode                        = 'godef'     " change GoDef engine to godef, guru is too slow

    au FileType go nmap <silent> <leader>r <Plug>(go-decls)
    au FileType go nmap <silent> <leader>t <Plug>(go-decls-dir)
    au FileType go nmap <silent> <leader>d <Plug>(go-def)
    au FileType go nmap <silent> <leader>l <Plug>(go-metalinter)
    au FileType go nmap <silent> <Leader>i <Plug>(go-info)

* Vim version (first three lines from `:version`):
    NVIM v0.3.1-1-g489d32f2b

* Go version (`go version`):
    go1.10.3 linux/amd64

* Go environment (`go env`):

    GOARCH="amd64"
    GOBIN=""
    GOCACHE="/home/smart/.cache/go-build"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/smart/go/"
    GORACE=""
    GOROOT="/usr/local/go"
    GOTMPDIR=""
    GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    CXX="g++"
    CGO_ENABLED="1"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"
    PKG_CONFIG="pkg-config"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build500038776=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
I can't duplicate the problem you're describing. You may want to rebuild.

**Comment by smartding** [comment]
> I can't duplicate the problem you're describing. You may want to rebuild delve.

The problem is still t here after I updated all vim plugin,  and rebuilt all dependencies by running GoUpdateBinaries. 

I also disabled all vim plugins except vim-go, the problem is still there.

Is there anything else you think I should try?

**Comment by bhcleek** [comment]
I believe #2075 will resolve this for you. Can you give it a try?

**Comment by smartding** [comment]
> I believe #2075 will resolve this for you. Can you give it a try?

Yes, problem solved!
No more error messages after GoDebugStop
