### ISSUE TITLE
guru not working well with go 1.11

### ISSUE THREAD

**Issue by dongfengkuayue** [fatih/vim-go#2060]
### What did you do? (required. The issue will be **closed** when not provided.)
I typed :GoCallers in vim ,it reported "vim-go: guru: couldn't load packages due to errors: runtime/internal/sys, runtime, runtime/internal/atomic and 1 more".

### What did you expect to happen?
return callers

### What happened instead?

It reported "vim-go: guru: couldn't load packages due to errors: runtime/internal/sys, runtime, runtime/internal/atomic and 1 more".
### Configuration (**MUST** fill this out):

* vim-go version:
v1.19
* Vim version (first three lines from `:version`):
8.1.500
* Go version (`go version`):
1.11.2

**Comment by bhcleek** [comment]
This would be a problem with guru, not vim-go. However, before you report a problem to github.com/golang/tools, you may want to try rebuilding guru.
