### ISSUE TITLE
support specific go.mod when navigating

### ISSUE THREAD

**Issue by bhcleek** [fatih/vim-go#2062]
Support a go.mod context (e.g. the authoritative go.mod) so that, for instance, jumping to definitions in other modules will continue to respect any overrides, replace directives, and versioned requirements that are in the original go.mod.

**Comment by bhcleek** [comment]
This will be supported by leveraging the current working directory as the directory within the module that should be considered the current context. Work still needs to be done so that `godef`, `guru`, etc, will work correctly, because as-is, they change into the directory containing the buffer before executing.

**Comment by scottschulthess** [comment]
this would be great, as ever since we switched from vendoring to go modules, go to definition has stopped working for me on modules (obviously) 

only work around i saw was to just vendor them temporarily

**Comment by bhcleek** [comment]
@scottschulthess `godef` has support for modules now; try it again after `:GoUpdateBinaries` and making sure sure `g:go_def_mode='godef'`. `guru` doesn't support modules.

This issue is really about making sure that jumping into source code of modules will work as expected when using replacements in the main module.

**Comment by bhcleek** [comment]
vim-go relies on gopls to module support now. `gopls` is started when the first go file is opened and uses the current working directory as it working directory.
