### ISSUE TITLE
when go build error, jump in to a new go file 

### ISSUE THREAD

**Issue by alexniver** [fatih/vim-go#2066]
### What did you do? (required. The issue will be **closed** when not provided.)
when i try build file use ',b', build error

### What did you expect to happen?
I want just jump to the error file's error line

### What happened instead?
 sometimes it not jump to the error line(sometimes it do the right thing), it jump into a total new go file with a main func

![peek 2018-11-21 02-45](https://user-images.githubusercontent.com/3366229/48796070-91cf4980-ed39-11e8-8ae2-4c15bd216eb7.gif)

### Configuration (**MUST** fill this out):
```

```
* vim-go version:
1.19 - (November 4, 2018) 

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
let mapleader = ","

set autowrite
set nocompatible            " Disable compatibility to old-time vi
set showmatch               " Show matching brackets.
set ignorecase              " Do case insensitive matching
set mouse=v                 " middle-click paste with mouse
set hlsearch                " highlight search results
set tabstop=4               " number of columns occupied by a tab character
set softtabstop=4           " see multiple spaces as tabstops so <BS> does the right thing
set expandtab               " converts tabs to white space
set shiftwidth=4            " width for autoindents
set autoindent              " indent a new line the same amount as the line just typed
set number                  " add line numbers
set wildmode=longest,list   " get bash-like tab completions
set cc=80                   " set an 80 column border for good coding style


" set tab, default 4 space
" set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
" Spaces & Tabs {{{
set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing
set shiftwidth=4    " number of spaces to use for autoindent
set expandtab       " tabs are space
set autoindent
set copyindent      " copy indent from the previous line
" }}} Spaces & Tabs

autocmd BufNewFile,BufRead,BufWrite *.go setlocal tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" html/js/coffe/jade, use 2 space
autocmd Filetype html setlocal ts=2 sw=2 expandtab
autocmd Filetype javascript setlocal ts=2 sw=2 expandtab
autocmd Filetype coffeescript setlocal ts=2 sw=2 expandtab
autocmd Filetype jade setlocal ts=2 sw=2 expandtab

autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')


call plug#begin()
" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
Plug 'AndrewRadev/splitjoin.vim'
Plug 'SirVer/ultisnips'
Plug 'fatih/molokai'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-fugitive'

if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

call plug#end()

map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go nmap <leader>r  <Plug>(go-run)
autocmd FileType go nmap <leader>t  <Plug>(go-test)
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)

let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_addtags_transform = "camelcase"
let g:go_list_type = "quickfix"
let g:go_test_timeout = '10s'
let g:go_highlight_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = "5s"
let g:go_auto_sameids = 1

let g:rehash256 = 1
let g:molokai_original = 1
colorscheme molokai


autocmd FileType go nmap <Leader>i <Plug>(go-info)
let g:go_auto_type_info = 1

" nerdtree
map <F2> :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen=1


" auto locate to last edit positon
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

set updatetime=100
```
* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 05 2018 21:42:14)
包含补丁: 1-1766
修改者 pkg-vim-maintainers@lists.alioth.debian.org
编译者 pkg-vim-maintainers@lists.alioth.debian.org

* Go version (`go version`):
go version go1.11.1 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alex/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alex/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build670059975=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
Can you provide some detail about how to replicate the failure you're seeing?

**Comment by alexniver** [comment]
@bhcleek  I finally find how to replicate the failure  on my computer.

I use ubuntu 18.10 64 desktop 

when I open a totally new terminal use ctrl alt T, and in this terminal,  I can replicate the failure , like gif below


![peek 2018-11-22 00-05](https://user-images.githubusercontent.com/3366229/48855650-7161c680-edef-11e8-9a3d-f005266f79d3.gif)


but then I press ctrl shift T, open a new terminal tab, in this new tab, everything works fine, like gif below

![peek 2018-11-22 00-08](https://user-images.githubusercontent.com/3366229/48855666-79216b00-edef-11e8-8fa5-611445dbd451.gif)


may be there are some difference between a totally new terminal and a tab terminal?

**Comment by bhcleek** [comment]
Is `~/alexniver/test` a symlink to `~/go/src/github.com/alexniver.com/alexniver/test`?

**Comment by alexniver** [comment]
@bhcleek  yes, oh, i know, it's because i use a soft link right?. is this a issue?

**Comment by bhcleek** [comment]
Yes

**Comment by jordansissel** [comment]
I'm new to this plugin (but not new to Go) and hit this issue. I use project-based symlinks ($PWD = ~/projects/foo, which is a symlink to ~/projects/go/src/some/path/foo). My experience is that this doesn't cause me problems for other go tooling, but maybe vim-go uses a tool I haven't used before?

Can you point me at any guidance on this? I understand a workaround would be to offer that I stop using such a directory layout, but isn't this a bug? If it's a "won't fix", I'd like to know more details, and maybe I can write a patch that provides a better experience (warns the user, etc) in these scenarios.
