### ISSUE TITLE
Can not to-to-definition to a local function without running `go get` first

### ISSUE THREAD

**Issue by lylex** [fatih/vim-go#2071]
### What did you do? (required. The issue will be **closed** when not provided.)
I cloned my repo from github, and then run go mod download, and then I run df to a function defined in the repo(not in the same file).

### What did you expect to happen?
It will go to the function definition without errors.

### What happened instead?
It did not go the function's definition, and show `vim-go: [searching declaration] FAIL`. However, when I firstly `go get` that package, everything is fine.

### Configuration (**MUST** fill this out):

* vim-go version:
v1.19

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
set nocompatible            
filetype off             

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'

let g:neocomplcache_enable_at_startup = 1
let g:neosnippet#disable_runtime_snippets = {
\   '_' : 1,
\ }

Plugin 'Shougo/neocomplcache'
Plugin 'Shougo/neosnippet'
Plugin 'Shougo/neosnippet-snippets'

call vundle#end()          
filetype plugin indent on   
set nocp
set rtp+=~/.vim/autoload/pathogen.vim

execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set cursorline
set ignorecase

nmap <silent> <F1> :NERDTree<CR>
nmap <silent> <F2> :set nonumber<CR>
nmap <silent> <F3> :set number<CR>

set incsearch
```

* Vim version (first three lines from `:version`):
8.1.155

* Go version (`go version`):
1.11.2

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lylex/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lylex/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build379138018=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by lylex** [comment]
Currently, I workaround this issue by `go get` that repo first. But, since I am working on the repo and doing changes on it, it is not so convenient to do so. Thanks.

**Comment by lylex** [comment]
@bhcleek Yes, I am working on `GO111MODULE=on` mod, which ignores GOPATH. And thus it downloads the third-party packages to the consolidated folder. So that I can clone my working repository any where, and what I need to do is just run `go mod download` to get all the dependent packages. I think it is much more convenient now. So I think, if vim-go supports it, that will be great.

**Comment by bhcleek** [comment]
vim-go relies on `godef` and guru for identifying definitions to jump to. Neither `godef` nor `guru` has full support for modules yet. Until they do, you'll need to `go get` the dependencies.
