### ISSUE TITLE
vimscript errors when running GoDebugStart

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#2072]
### What did you do? (required. The issue will be **closed** when not provided.)
Used :GoDebugStart to begin to test delve integration and received the following errors in the status line

```
vim-go: API server listening at: 127.0.0.1:8181
Error detected while processing function <SNR>131_on_stdout[24]..<SNR>133_out_cb[22]..<SNR>133_call_jsonrpc:
line   81:
E605: Exception not caught: (let):connection failed: connection refused
Press ENTER or type command to continue
Error detected while processing function <SNR>131_on_stdout[24]..<SNR>133_out_cb:
line   22:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function <SNR>131_on_stdout:
line   24:
E170: Missing :endfor
```

### What did you expect to happen?
vim debug windows created and continue testing delve integration

### What happened instead?
received errors above on statusline

### Configuration (**MUST** fill this out):

* vim-go version:
current master (updated today)

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
https://github.com/ldelossa/dotfiles/blob/master/vimrc

* Vim version (first three lines from `:version`):
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5

* Go version (`go version`):
go version go1.11.2 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN="/Users/louis/git/go/bin"
GOCACHE="/Users/louis/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mc/xwfdd41j1j74xfmcmphbwpgw0000gn/T/go-build158095971=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bhcleek** [comment]
Can you provide clear steps to replicate the problem you're experiencing?

For what it's worth, I've only seen the error you're seeing when trying to use `:GoDebugStart` in a library (e.g. _not_ `main`) package. If you're trying to use `:GoDebugStart` to debug tests, use `:GoDebugTest` instead.

**Comment by ldelossa** [comment]
Steps to reproduce:

* Open vim at root of project directory. My project directory structure is:
```
~/git/go/src/oden/btc master* 1m 35s
❯ tree
.
├── README.md
├── avgring.go
├── cmd
│   └── btc
│       └── main.go
├── handler.go
├── internal
│   └── binance
│       └── client.go
└── tags

4 directories, 6 files
```
* With vim open I use netrw to the cmd/btc/main.go file
* With my cursor inside the main function I use the statusline to call :GoDebugStart
* I receive the following errors in sequence...
```
vim-go: API server listening at: 127.0.0.1:8181
Error detected while processing function <SNR>100_on_stdout[24]..<SNR>97_out_cb[22]..<SNR>97_call_jsonrpc:
line   81:
E605: Exception not caught: (let):connection failed: connection refused
Press ENTER or type command to continue
Error detected while processing function <SNR>100_on_stdout[24]..<SNR>97_out_cb:
line   22:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function <SNR>100_on_stdout:
line   24:
E170: Missing :endfor
Press ENTER or type command to continue
```

**Comment by bhcleek** [comment]
`:GoDebugStart` expects to be passed a package name or the current directory to be the directory to find the `main` package to be debugged.

see `:help :GoDebugStart` and `:help go-debug-intro`.

**Comment by ldelossa** [comment]
Ah! Sorry about that, assumed currently directly was provided if no further
input.

**Comment by ldelossa** [comment]
Still having trouble getting this to work. I used `cd` inside vim and changed to the directory where my main.go file is located "cmd/btc/main.go" 
![image](https://user-images.githubusercontent.com/5642902/48981477-f8d76000-f0a3-11e8-84a1-68d8fb6b3d4c.png)

Now I try ":GoDebugStart ." assuming "." as current directory. 

I get the same vim script errors as above.

**Comment by bhcleek** [comment]
What you're describing works fine for me. Does `dlv debug oden/btc/cmd/btc` work for you from the commandline?

**Comment by ldelossa** [comment]
@bhcleek that solved it, I'm on macos majove and had to run `xcode-select --install` to install xcode command line tools.
