### ISSUE TITLE
Q: Can we make guru use fzf to show its output?

### ISSUE THREAD

**Issue by svanharmelen** [fatih/vim-go#2073]
I prefer using fzf for everything I can :wink: and for example for `GoDecls` this works great. But when using `go-referrers` (which I use quite a lot) the results are always loaded in the quickfix window.

So I was looking at the `vim-go` code to see if I could add support for that. I noticed that in `vim-go/autoload/go/list.vim` it says the window used by guru is not configurable and I looked at `vim-go/autoload/go/guru.vim` to find out more, but fail to find the point were the output gets loaded into the quickfix window. 

So any pointer where to start would be very much appreciated. Thanks!

**Comment by bhcleek** [comment]
The guru output for `:GoReferrers` is parsed and populated into the window in `s:parse_guru_output`: https://github.com/fatih/vim-go/blob/master/autoload/go/guru.vim#L554-L566.

**Comment by bhcleek** [comment]
This is probably better handled as a couple of contributions to https://github.com/junegunn/fzf.vim so that it could work for _all_ errors in either the quickfix list or the locationlist. 🤔

**Comment by reaysawa** [comment]
@bhcleek is the problem that the function to feed the result list into FZF doesn't work for both?

Building custom sources is usually done by hand by the users, so I don't think a way to "automate" that into the plug-in source for custom needs would be welcome, unless I'm misunderstanding something... If you want help with integrating the parsed guru info into FZF I can lend a hand, although I'm brand new to Go in general.

**Comment by bhcleek** [comment]
There's really no need to do this just for `:GoReferrers`. All `:GoReferrers` does is update the quickfix or location list s (depending on your settings). It would be more useful to think about the general problem of being able to navigate the errors with fzf. There's already a plugin like that: https://github.com/fszymanski/fzf-quickfix/blob/master/autoload/fzf_quickfix.vim.

**Comment by bhcleek** [comment]
> Ahh, I think I get it now: being able to navigate through quickfix errors using FZF? 

yes

> And that should be something built into it?

yes, or just use the plugin I linked in my previous comment or a similar one.

> If so I definitely agree, although the content of the items between them are generally similar, so it ends up not being a problem to do a little conversion (if any).

quickfix and location lists items are accessible by `getqflist()` and `getloclist()`, respectively. After the list is populated, the plugin should just query those and use the return value as the input to the functions to navigate with fzf.

> Some plug-ins interact with the quickfix window (e.g. https://github.com/romainl/vim-qf, https://github.com/neomake/neomake, etc...), so building a qf list first, and then parsing it once again in FZF, seems counter-intuitive.

Why does it matter if other plugins interact with the quickfix window or not? Navigation of the items in the window is separate concern from what other plugins do with the window itself.
