### ISSUE TITLE
vim-go: [No write since last change] keeps bothering me

### ISSUE THREAD

**Issue by JedBeom** [fatih/vim-go#2089]
### What did you do? (required. The issue will be **closed** when not provided.)

I was just editing go code.

### What did you expect to happen?

Peaceful Editing

### What happened instead?

`vim-go: [No write since last change]` keeps bothering me in `insert mode`.
This message was suddenly appeared after updating vim-go.
I think it appears when vim tries autocompleting or showing godoc.

### Configuration (**MUST** fill this out):

* vim-go version:

commit 2e1eb6ff7a0cf67f93d4cd2210702d933565c022

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
Plugin 'fatih/vim-go'
Plugin 'stamblerre/gocode', {'rtp': 'nvim/'} " I changed my gocode for supporting go modules.
Plugin 'Shougo/deoplete.nvim'
Plugin 'zchee/deoplete-go', {'do': 'make'}

...

let g:go_auto_type_info = 1
```

* Vim version (first three lines from `:version`):

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
```

* Go version (`go version`):

`go version go1.11.2 darwin/amd64`

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/beom/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/beom/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3h/nwl1v1b15p93qym3zj4bh_480000gn/T/go-build701528194=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
<img width="1280" alt="screen shot 2018-12-11 at 9 51 41 pm" src="https://user-images.githubusercontent.com/20675630/49803983-c496bb80-fd94-11e8-81ab-67376a435070.png">

**Comment by JedBeom** [comment]
More screenshot for it
<img width="1280" alt="screen shot 2018-12-12 at 12 09 47 am" src="https://user-images.githubusercontent.com/20675630/49809443-3f1a0800-fda2-11e8-87df-63ebfae8f872.png">

**Comment by bhcleek** [comment]
Does this occur if you have deoplete disabled? Does it make a difference whether you're using module mode or GOPATH mode?

**Comment by JedBeom** [comment]
@bhcleek I've turned deoplete off, and started editing a go file, the message appeared again.
But on GOPATH project, the message doesn't appear.

**Comment by bhcleek** [comment]
Do you still have the problem if you comment out `Plugin 'stamblerre/gocode', {'rtp': 'nvim/'} " I changed my gocode for supporting go modules.`? Can you duplicate the problem with _only_ vim-go as the only plugin?

**Comment by JedBeom** [comment]
Yes, I commented out `Plugin 'stamblerre/gocode', {'rtp': 'nvim/'}` and there's the same problem.

**Comment by bhcleek** [comment]
Due to a limitation with github.com/stamblerre/gocode, you'll need to either enable Vim's `autowrite` option, enabled its `autorwriteall` option, or disable vim-go's `g:go_auto_type_info` option.

**Comment by shabbyrobe** [comment]
`g:go_auto_type_info` is disabled for me and I still get the error. Setting autowrite and triggering an autocompletion runs ALE, which at least shows me the completions now but also a bunch of spurious compile errors.

**Comment by JedBeom** [comment]
I enabled ‘autowrite’ option and I don’t get an error now. Thx

**Comment by Lautankard** [comment]
How to solve this error？
