### ISSUE TITLE
Jumping to declaration doesn't work for built-in symbols

### ISSUE THREAD

**Issue by wzhliang** [fatih/vim-go#2095]
### What did you do? (required. The issue will be **closed** when not provided.)

Move cursor on to something like `fmt.Printf()` and then press `Ctrl-]`

### What did you expect to happen?

Jump to `Printf()`

### What happened instead?

Vim displays `vim-go: searching...` and nothing happens

### Configuration (**MUST** fill this out):

* vim-go version: 97235dd7fba637419fdc603a893ae803abb62775

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):
Nvim 0.3.1

* Go version (`go version`):
1.11.2

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wliang/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wliang/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w9/94w1nwh93hd9yrrzsm2qvfjc0000gn/T/go-build892916928=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bhcleek** [comment]
I've tried the revision you referenced, and jumping to the definition works fine for me. Can you provide a clear replication path and the simplest vimrc possible that can demonstrate the problem you're encountering?

There have been several changes and a release since 97235dd. You may want to try upgrading before doing anything else.

**Comment by wzhliang** [comment]
I upgraded to latest. I behaves different now: it prints `Searching.. FAIL`

Here is my vimrc
https://gist.github.com/wzhliang/e75963c9159e5d17addd0b6ead4bdc77

**Comment by EVODelavega** [comment]
@wzhliang did you recently upgrade your golang version, too? I had some issues with `:GoErrCheck` after an upgrade, but running `:GoUpdateBinaries` solved that. You're either using `guru` or `godef`, wihch might be compiled with the previous version of go you were using, that would explain the problem

**Comment by wzhliang** [comment]
@EVODelavega `GoUpdateBinaries` worked! Thanks
