### ISSUE TITLE
Add config var to override the default templates directory

### ISSUE THREAD

**Issue by EVODelavega** [fatih/vim-go#2100]
### What did you do?

I've created [a PR](https://github.com/fatih/vim-go/pull/2099) that adds a config variable to enable people to manage template files a bit better. Especially when they'd like to use project-specific templates.

I'm raising it as an issue so that I can get some input on whether there's anything that could be added. The long and short of it is that in addition to being able to set things like this in a project-specific config file:

```vimL
g:go_template_file = "my_template.go"
```

Having to organise all the template names in the `vim-go/templates` directory, it'd now be possible to set something like:

```vimL
g:go_template_dir = expand("~/go/src/my-project/.templates")
g:go_template_file = "normal_template.go"
```

This doesn't require me to manage all the templates in a single directory, but rather ties the project-specific config and templates together in the project path. Once the project is done, I can just `rm -r ~go/src/my-project`, and everything is tidied up, no need to check the config, and clean out my central `templates` directory, making sure not to accidentally remove a template file used by another project.

**Comment by bhcleek** [comment]
Closing; feedback will be on the PR.
