### ISSUE TITLE
:GoRun fills up disk over time

### ISSUE THREAD

**Issue by kipukun** [fatih/vim-go#2103]
### What did you do? (required. The issue will be **closed** when not provided.)

Ran `:GoRun` in a project using `map <F2>` a multitude of times.

### What did you expect to happen?

The Go file runs a multitude of times.

### What happened instead?

The Go file runs a multitude of times, but fills my disk with ???

### Configuration (**MUST** fill this out):

* vim-go version:

v1.19

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

https://i.kipu.ws/05c6.txt

* Vim version (first three lines from `:version`):

>>VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.

* Go version (`go version`):

`go version go1.10 linux/amd64`

* Go environment (`go env`):

`
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kipukun/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kipukun/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build714453539=/tmp/go-build -gno-record-gcc-switches"
`

**Comment by kipukun** [comment]
Well, for starters, trying to `go run main.go` in my current project directory errors because it cannot find functions defined in another file `handlers.go` also in `package main` (which makes sense). However, running `:GoRun` in the `main.go` buffer runs it just fine, which is weird. 

Also, I'm not running any code that writes to a file. The only thing it does is access a DB, but it does not write to the DB thus far.

**Comment by kipukun** [comment]
I'm going to close this issue for now, since I don't really have any proof it's vim-go. Sorry that I was being a little confrontational. I'll re-open this if I find some hard proof. Thanks for your time.

**Comment by bhcleek** [comment]
> Sorry that I was being a little confrontational

Thanks for the apology, but I didn't perceive your communication as confrontational. 😄 

If this is an issue, I definitely want to fix it, but I've reviewed the code and don't see any place that would cause this. Please do let us know if you find something that points to vim-go specifically.
