### ISSUE TITLE
Autocomplete does not work within incomplete if statements

### ISSUE THREAD

**Issue by cskr** [fatih/vim-go#2115]
### What did you do?

* Create a directory outside `GOPATH` and initialize it as a module with `go mod init github.com/cskr/foo`.
* Create `main.go` with following content.

```golang
package main

func main() {
	var v MyStruct
}

type MyStruct struct {
	Field int
}
```

* Hit `C-x C-o` after typing `if v.` immediately after the variable declaration as shown below,

```golang
func main() {
	var v MyStruct
	if v.
}
```

### What did you expect to happen?

I expected `Field` to be auto-completed.

### What happened instead?

`Pattern not found` was displayed as error. However, if I add braces at the end of `if` as shown below and then try `C-x C-o`, it works.

```golang
func main() {
	var v MyStruct
	if v. {}
}
```

### Configuration (**MUST** fill this out):

* vim-go version: master (d0c5d5f)

* `vimrc` you used to reproduce (only relevant lines):

```
set completeopt-=preview
let g:go_fmt_command='goimports'
let g:go_fmt_options='-local github.com/cskr'
let g:go_gocode_unimported_packages=1
```

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
```

* Go version (`go version`): `go version go1.11.4 linux/amd64`

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cskr/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cskr/go"
GOPROXY=""
GORACE=""
GOROOT="/home/cskr/tools/go"
GOTMPDIR=""
GOTOOLDIR="/home/cskr/tools/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build958461974=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
Thank you for a great issue report. Unfortunately, this looks like it's an issue for github.com/stamblerre/gocode.

**Comment by cskr** [comment]
Thank you. I have reported it at https://github.com/stamblerre/gocode/issues/23.
