### ISSUE TITLE
Invalid expression: go#config#HighlightFunctionParameters()

### ISSUE THREAD

**Issue by TcM1911** [fatih/vim-go#2118]
### What did you do? (required. The issue will be **closed** when not provided.)
Opened a go source file

### What did you expect to happen?
No error message

### What happened instead?
Error:
```
..../vim-go/syntax/go.vim:
line  272:
E117: Unknown function: go#config#HighlightFunctionParameters
E15: Invalid expression: go#config#HighlightFunctionParameters()
```

### Configuration (**MUST** fill this out):

* vim-go version: 

commit 8342cd4ffdadccfc30284088560939f4c1ab2789

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
```

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  8 2018 11:23:48)
Included patches: 1-570
Compiled by Arch Linux

* Go version (`go version`):
go version go1.11.4 linux/amd64

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE=[redacted]
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=[redacted]
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build943766610=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
Do you have polyglot installed?

**Comment by TcM1911** [comment]
Yes, I do

**Comment by TcM1911** [comment]
Re-ran the build script for polyglot and it fixed it. If anyone else runs into this problem, run the `build` script in the polyglot root folder.

Closing
