### ISSUE TITLE
GoInfo doesn't work on assigned variables

### ISSUE THREAD

**Issue by kaihendry** [fatih/vim-go#2119]
### What did you do? (required. The issue will be **closed** when not provided.)

https://s.natalian.org/2019-01-07/go-info.mp4

### What did you expect to happen?

Hover over svc and for it to indicate it's type *S3

### What happened instead?

Nothing

### Configuration (**MUST** fill this out):

* v1.19-88-g8342cd4

* https://github.com/kaihendry/dotfiles/blob/master/.config/nvim/init.vim
*```
 NVIM v0.3.3
Build type: Release
LuaJIT 2.0.5
```

* go version go1.11.4 linux/amd64

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hendry/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hendry/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build906482915=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by kaihendry** [comment]
How come VScode is instant btw? Do they not share the same gocode?

1. Yes
2. Tried a longer time. No dice.
3. 3.3GB
4. No

https://s.natalian.org/2019-01-08/gocode-debug.mp4 <-- debugging on my Arch machine
https://s.natalian.org/2019-01-08/gocode-debug-void.mp4 <-- debugging on Void machine

gocode does seem like a mysterious beast and neovim's :GoInfo's result of `vim-go: [gocode] SUCCESS` is very misleading.

I'm none the wiser why it fails on Arch. I got it working on Void by install a dependency `go get github.com/jmespath/go-jmespath` that it seemed to be complaining about.

Back on Arch, `g:go_info_mode='guru'` seems to work better than without https://s.natalian.org/2019-01-08/gocode-guru.mp4

Really puzzled by these parse errors in gocode debug.

<img src="https://s.natalian.org/2019-01-08/1546911394_2548x1398.png">

With https://s.natalian.org/2019-01-08/main.go <-- this code runs fine !

**Comment by bhcleek** [comment]
> gocode does seem like a mysterious beast

gocode is intended for autocompletion. As such, when it's used for getting type info, it only takes up to the cursor position into account. That's why you were seeing a couple of results from gocode: when on the `s` in `s3`, its' finding all in-scope identifiers that start with `s`. Since there's two results, vim-go doesn't know which one to display, so doesn't display any. TBH, I'd never considered this limitation of using gocode for type info before. Guru doesn't have such limitations.

>  and neovim's :GoInfo's result of vim-go: [gocode] SUCCESS is very misleading.
It's only telling you that the call to gocode was successful; gocode exited with a successful exit code.

You might consider raising an issue with https://github.com/mdempsky/gocode about the errors you saw later in the gocode output, though.

**Comment by bhcleek** [comment]
> gocode is intended for autocompletion. As such, when it's used for getting type info, it only takes up to the cursor position into account. That's why you were seeing a couple of results from gocode: when on the s in s3, its' finding all in-scope identifiers that start with s. Since there's two results, vim-go doesn't know which one to display, so doesn't display any. TBH, I'd never considered this limitation of using gocode for type info before. Guru doesn't have such limitations.

I took another look at how gocode is used when getting identifier info, and realized that the information I gave you there is wrong. It actually does try to match the identifier under the cursor to the candidates that are provided from gocode.
