### ISSUE TITLE
:GoInfo reports success but no results

### ISSUE THREAD

**Issue by bhcleek** [fatih/vim-go#2120]
### What did you do? (required. The issue will be **closed** when not provided.)
In a short variable declaration and with `g:go_info_mode='gocode'` set, place the cursor variable name and then run `:GoInfo`.

### What did you expect to happen?
A message that tells me that identifier at the cursor position could be found (because gocode does't know about the type of the identifier since it only looks up to the cursor position.

### What happened instead?
A `vim-go: [gocode] SUCCESS` message.

related to https://github.com/fatih/vim-go/issues/2119#issuecomment-452144007

**Comment by stefanos82** [comment]
So, I was the first one who observed this peculiar behavior when I reported #2105 ticket?

With `guru` works as expected, but should I wait for a fix so I can switch back to `gocode` or I shouldn't worry about it?

**Comment by bhcleek** [comment]
I'd never noticed that particular problem before, so I created the issue. #2122 should resolve it, but IMO, guru is better to use for `g:go_info_mode`.
