### ISSUE TITLE
Is dep supported?

### ISSUE THREAD

**Issue by reaysawa** [fatih/vim-go#2121]
This isn't as much of an issue as it is a question.

Docs mention [godep](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1436) being supported, but it seems like that project has been discontinued. As someone completely unfamiliar with the language at this point, I don't know if both are equivalent and the option still works, as it seems [dep](https://github.com/golang/dep) uses a different folder structure and different dependency files too.

Suggestion: deprecate the option as the tool is no longer supported **or** update the info to use dep instead.

**Comment by bhcleek** [comment]
`dep` doesn't need any special support. The legacy versions of `godep` that used a `_workspace` directory are supported for the users that still need it, and there's no harm in keeping the functionality.
