### ISSUE TITLE
$HOME/.vim/ftplugin not working anymore

### ISSUE THREAD

**Issue by stefanos82** [fatih/vim-go#2124]
I don't know what you did, but I have updated vim-go today and now I cannot use my mapped keys.

`gocomplete.vim` consists of 
```vim
setlocal omnifunc=gocomplete#Complete
```
and `gomappedkeys.vim` consists of 
```vim
inoremap <buffer> <C-k> <C-x><C-o>
autocmd FileType go nmap <F5> <Plug>(go-run)
autocmd FileType go nmap <C-i> <Plug>(go-imports)
autocmd FileType go nmap <C-l> <Plug>(go-info)
```
The full path for files is `$HOME/.vim/ftplugin/go/`

**Comment by bhcleek** [comment]
It was probably https://github.com/fatih/vim-go/pull/2109. I'll take a deeper look this weekend.

**Comment by stefanos82** [comment]
@bhcleek OK, I think I may have resolve my issue.

Since [1ed9b52](https://github.com/fatih/vim-go/commit/1ed9b521929606a282edc72c7627addb8c3914b9), with this major refactoring it made it unnecessary for me to be explicit for filetypes with regards to my mapped keys.

First, I moved my aforementioned files to `$HOME/.vim/after/ftplugin/` because I placed them in the wrong directory and after a bit of investigation, I read a couple of articles that suggested to use the `after` path which gets parsed last.

I did so and I removed the `autocmd FileType go` part from my mapped keys and now works as expected.

Therefore consider it fixed, **but**! if you think my solution is not the proper one, then please by all means correct me where I'm wrong and let me know so I can apply yours if you have a better suggestion that is.

Else, feel free to close it.

**Comment by bhcleek** [comment]
I think your solution is the right one. Thank you for the quick turnaround.
