### ISSUE TITLE
gocode-gomod is not run when go.mod is present

### ISSUE THREAD

**Issue by twexler** [fatih/vim-go#2129]
I'm not 100% sure if this is an issue with deoplete-go or vim-go, but: 

### What did you do? (required. The issue will be **closed** when not provided.)
Wrote some code.

### What did you expect to happen?
- Auto-completions to appear while writing code.
- vim-go/deoplete-go to launch `gocode-gomod`

### What happened instead?
- Auto-completion returned "invalid type"
- vim-go/deoplete-go launched `gocode`

### Configuration (**MUST** fill this out):
https://github.com/twexler/init.vim/blob/master/init.vim
* vim-go version: `a61545f`

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
```
* Vim version (first three lines from `:version`):
```
NVIM v0.3.2-dev
Build type: RelWithDebInfo
Lua 5.1
```
* Go version (`go version`): `go version go1.11.1 linux/amd64`

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/twexler/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/twexler/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/twexler/dev/kubaas-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build484905912=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by twexler** [comment]
I've been able to work around this issue by symlinking `$GOPATH/bin/gocode` to `$GOPATH/bin/gocode-gomod`, but I haven't tested to see if this breaks non-module based codebases

**Comment by bhcleek** [comment]
I'd suggest that you isolate the problem to either vim-go or deoplete and then create an issue the correct project.
