### ISSUE TITLE
GoDef failed when using GoModules

### ISSUE THREAD

**Issue by janbaer** [fatih/vim-go#2137]
### What did you do? (required. The issue will be **closed** when not provided.)

I've create a new project with using the Go module support, The project is located outside of the GOPATH directory. I've initialized it with `go mod init github.com/janbaer/sherlock`

When I'm in the **main.go** and I want to go to a function of sub package with using GoDef it fails.

### What did you expect to happen?

It  should jump to the expected function

### What happened instead?

I just see the error in the status line: vim-go: [searching declaration] FAIL

When I go into the function manually I see the following output in the status line:
```
vim-go: func HandleI(nspect invalid type, _ invalid type, _ http.HandlerFunc, _ invalid type, ResponseWriter *http.Request, r *http.Request)
```
but the function name is **HandleInspect**. It's the same with any other function in this package and also other packages.

Navigating to local functions works. It works also in other projects without but also with GoModules support.

### Configuration (**MUST** fill this out):

* vim-go version: latest master

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 28 2019 15:24:39)
Included patches: 1-837

* Go version (`go version`): 1.11.4

* Go environment (`go env`):

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jan/Projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jan/Projects/sherlock/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build410959908=/tmp/go-build -gno-record-gcc-switches"

**Comment by janbaer** [comment]
I just found the hint that `GoUpdateBinaries` might could help and it works now for me. But I still see this strange status line when I'm into the function:

```
vim-go: func HandleI(nspect invalid type, _ invalid type, _ http.HandlerFunc, _ invalid type, ResponseWriter *http.Request, r *http.Request)
```

**Comment by bhcleek** [comment]
The function signature comes from either gocode or guru. If you're not seeing the `(` in the wrong place when in GOPATH mode, then then problem doesn't lie with vim-go in this case.

**Comment by janbaer** [comment]
How can I investigate what **gocode** returns when it'll be called from vim-go. With which parameters will it be called under the hood?

**Comment by bhcleek** [comment]
1. Set `g:go_debug=['shell-commands']` so that the command and all its arguments will be output as a list when it's run. You can also see it in the output of `:messages`.
2. Convert the list to a commandline, and add the `-debug` option.
3. Stop any running `gocode` processes:

```
$ gocode-gomod exit
$ gocode exit
$ gocode close #(just in case you have a  nsf/gocode running)
```

4. In a separate terminal window, run the command you created in step 2.

**Comment by janbaer** [comment]
@bhcleek  Thank you very much for your instructions. I followed and  I just tried to execute the following command:

```
gocode-gomod -debug -sock unix -f vim -builtin -fallback-to-source -cache autocomplete /home/jan/Projects/sherlock/handlers/handlers.go 258
```
But it hangs and no output will be produced.

This was the command as it was in the messages list:

```
vim-go: job command: ['/home/jan/Projects/go/bin/gocode-gomod', '-sock', 'unix', '-f', 'vim', '-builtin', '-fallback-to-source', '-cache', 'autocomplete', '/home/jan/Projects/sherlock/ha
ndlers/handlers.go', 258]
```

**Comment by bhcleek** [comment]
gocode is a server. After starting it on the commandline, you'll need to do the operation in Vim from which you're seeing the wrong output.

**Comment by bhcleek** [comment]
`gocode-gomod` will only be used when you're in module mode. `-debug` is an option parsed by the `flag`, so should come _before_ the `autocomplete` argument.

**Comment by janbaer** [comment]
My project is using the module mode, so I think I should use gocode-gomode. But I also tried gocode with the same result. No output on the commandline..

```
gocode-gomod -debug -sock unix -f vim -builtin -fallback-to-source -cache autocomplete
```

**Comment by janbaer** [comment]
I closed the issue because the main problem with GoDef is working now for me
