### ISSUE TITLE
GoInstallBinaries GoUpdateBinaries error, missing project name

### ISSUE THREAD

**Issue by kynrai** [fatih/vim-go#2158]
### What did you do? (required. The issue will be **closed** when not provided.)

Attempted to run GoUpdateBinaries, I get:

```
vim-go: Updating gogetdoc. Reinstalling github.com/zmb3/gogetdoc to folder /Users/steve/go/bin/
Error downloading github.com/zmb3/gogetdoc: error: program failed: missing project name^@
Error installing github.com/zmb3/gogetdoc: error: program failed: missing project name^@
```

This happens for every binary then the run exits fine. All binaries can be run from the CLI with go get just fine.

### What did you expect to happen?

GoUpdateBinaries to work

### What happened instead?

All programs fail with 

```
vim-go: Updating gogetdoc. Reinstalling github.com/zmb3/gogetdoc to folder /Users/steve/go/bin/
Error downloading github.com/zmb3/gogetdoc: error: program failed: missing project name^@
Error installing github.com/zmb3/gogetdoc: error: program failed: missing project name^@
```

Then the program exits
### Configuration (**MUST** fill this out):

* vim-go version:
latest

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin()
Plug 'fatih/vim-go'
call plug#end()

" Golang settings
let g:go_highlight_extra_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_term_enabled = 1
let g:go_fmt_command = "goimports"
let g:go_gocode_unimported_packages = 1
let g:go_auto_type_info = 1
let g:go_auto_sameids = 1
let g:go_def_reuse_buffer = 1
let g:go_def_mode = 'godef'
```

* Vim version (first three lines from `:version`):

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
```

* Go version (`go version`):
`go version go1.12 darwin/amd64`

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/steve/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/steve/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dg/79bk87h55_q9w4ym1j_8nbwr0000gn/T/go-build840933872=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment]
Make sure your working directory is in GOPATH for a quick workaround.

**Comment by kynrai** [comment]
Unfortunately
Changing the working dir, setting it, opening in it etc does not seem to solve the issue. Unless im missing something specific with VIM and working directory.

**Comment by bhcleek** [comment]
Do you have `GO111MODULE=on` set by chance?

**Comment by kynrai** [comment]
I do not have `GO111MODULE=on` just the default settings from `brew install go`

**Comment by bhcleek** [comment]
I just updated my local machine to Go 1.12 and ran `:GoUpdateBinaries` without any problems.

Does `go build -o $(go env GOPATH)/bin/gogetdoc github.com/zmb3/gogetdoc` work on your machine?

**Comment by kynrai** [comment]
Yeah I can manually build all the binaries required. in the same terminal as i'm running vim, in the vim terminal anywhere really. 

What does the error message mean when it says its missing a project name?

**Comment by bhcleek** [comment]
I'm not sure what that means. I've never seen it before, I'm unable to duplicate it, and I can't find anything on the web that explains it either. Are you sure you can duplicate this with a clean vimrc? Do you have the same issue with Go 1.11?

**Comment by bhcleek** [comment]
FYI, it's always a good idea to clear out $GOPATH/pkg after upgrading Go.

**Comment by kynrai** [comment]
Same issues with go1.11

I used a minimal .vimrc
```
filetype plugin indent on
syntax enable

call plug#begin()
Plug 'fatih/vim-go'
call plug#end()
```
and cleared out the pkg dir. same issue :( 
Starting to think its probably some wider system issue but for all other editors/plugins/IDEs and go toolchain, everything works fine. Only vim-go gives this rather cryptic error. Not sure what else to try.

**Comment by kynrai** [comment]
Whats the exact command vim-go executes? there must be a way for me to reproduce this locally at a lower level.

**Comment by bhcleek** [comment]
It uses the command I mentioned in https://github.com/fatih/vim-go/issues/2158#issuecomment-468959145

**Comment by kynrai** [comment]
The command works fine, im at a loss :(

**Comment by kynrai** [comment]
I think I'll close this issue, there seems to be no way to reproduce my issue on any other machine so probably not a vim-go issue. Thanks for the help

**Comment by andrewXiaoyu** [comment]
may be GFW issue,if you are in china
