### ISSUE TITLE
Error detected while processing function go#auto#echo_go_info

### ISSUE THREAD

**Issue by itetao** [fatih/vim-go#2159]
Hey,  i got a problem , don't known how to solve it, can you help me, very thanks
![deoplete1](https://user-images.githubusercontent.com/46645709/53716479-13ce2300-3e90-11e9-9ffd-3b8df78bc4dc.png)

* vim-go version:
the newest version

* Vim version (first three lines from `:version`):
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
* Go version (`go version`):  
go1.12 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN="/home/miao/go/bin"
GOCACHE="/home/miao/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/miao/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build899302343=/tmp/go-build -gno-record-gcc-switches"

**Comment by itetao** [comment]
![vim-go1](https://user-images.githubusercontent.com/46645709/53716637-850dd600-3e90-11e9-8e9e-cdf0dc8dd8c1.png)

**Comment by jar3k** [comment]
@itetao Try to update vim-polyglot, it should help (see: https://github.com/sheerun/vim-polyglot/commit/ed677c34d55a0e025b7008f29419498a3989cde2).

**Comment by itetao** [comment]
@jar3k  yeah, i update it, and now works fine, thanks very much to your help
