### ISSUE TITLE
When going to definition it shows Error detected while processing function go#guru#SameIds

### ISSUE THREAD

**Issue by jgimeno** [fatih/vim-go#2162]
### What did you do? (required. The issue will be **closed** when not provided.)
Go to the definition of an interface, it works correctly but if I go several times ramdonly it fails. Once it fails the first time, it fails always until restart nvim.

When it fails and I do `gd` it shows on the bottom:

```
vim-go: [searching declaration] SUCCESS
Error detected while processing function go#guru#SameIds[27]..<SNR>151_run_guru[2]..<SNR>151_async_guru[31]..go#job#Options:
line  129:
E127: Cannot redefine function <SNR>163_exit_cb: It is in use
```

I press then enter and it goes to the definition.

### What did you expect to happen?

Not show the error.

### What happened instead?

Showed an error and after it it goes to the definition.

### Configuration (**MUST** fill this out):

* vim-go version: 1.19

* Vim version (first three lines from `:version`):
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5

* Go version (`go version`):
go version go1.12 darwin/amd64

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jgimeno/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jgimeno/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lr/20v7hz1j5cnfrzxlyw47bw5r0000gn/T/go-build544694843=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment]
Do you have the same problem with latest master?

**Comment by bhcleek** [comment]
closing due to lack of feedback

**Comment by entombedvirus** [comment]
I can repro this locally on vim-go master @ 5eab407f13e312c7534c5c6aed0eaa451c45536a

Steps to repro for me are:

1. have both of these turned on:
```
let g:go_auto_sameids = 1
let g:go_auto_type_info = 1
```
2. open nvim
3. open any .go file
4. place cursor over a method symbol
5. press `Ctrl-]` to jump to defn. The jump succeeds without any errors
6. press `Ctrl-t` to jump back
7. press `Ctrl-]` again. This time this error shows up in the status area: `Error detected while processing function go#guru#SameIds[27]..<SNR>117_run_guru[2]..<SNR>117_async_guru[31]..go#job#Options:` After pressing enter, jump succeeds normally.

My env details:

* NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5

* go version
go version go1.11 linux/amd64

* go env

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rravi-1/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rravi-1/.gotools:/home/rravi-1/analytics/go:/home/rravi-1/.gotools:/home/rravi-1/analytics/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build115200486=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
Thank you for confirming @entombedvirus . With your steps and the vim-go settings you provided, I was able to identify the problem. Please open another issue if you find that it's still a problem for you.

**Comment by entombedvirus** [comment]
Just updated to master @ 2a21c6a9d05bab22f1fdc0f09874188f960d16f7 and confirm that the error no longer shows up. Thank you @bhcleek!
