### ISSUE TITLE
:GoDef stopped working since update

### ISSUE THREAD

**Issue by svarogg** [fatih/vim-go#2167]
### What did you do? (required. The issue will be **closed** when not provided.)
I have just updated all plugins using Vundle and restarted nvim.
Everything worked just before the update.

In normal mode, I've put the cursor above a call for a function, and pressed `gd`, or alternatively, typed `:GoDef`

### What did you expect to happen?
nvim should have gone to the definition of said function

### What happened instead?
nvim stayed in the same place, and the error message "E119: Not enough arguments for function: go#def#Jump" appeared briefly in the status line

### Configuration (**MUST** fill this out):

* vim-go version:
v1.19
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
" This is not the full vimrc, only the parts that are relevant to go:
let g:go_auto_sameids = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
let g:go_auto_type_info = 1
let g:go_snippet_engine = "neosnippet"
au FileType go nmap <leader>gt :GoDeclsDir<cr>

let g:ale_linters = {'go': ['go build', 'golint']}
let g:ale_open_list = 1

* Vim version (first three lines from `:version`):
                                                                                                                                                                            
NVIM v0.3.1                                                                                                                                                                                   
Build type: RelWithDebInfo                                                                                                                                                                    
LuaJIT 2.1.0-beta3                                                                                                                                                                            
* Go version (`go version`):
go version go1.12 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mike/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mike/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build581517140=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
Have you been able to duplicate this with all plugins except vim-go disabled? 

Are you using vim-polyglot?

**Comment by svarogg** [comment]
Never mind, I have figured it out.

As it seems vim-go was installed into two different locations for some reason, and only one of them got updated.

Sorry for wasting your time and thanks for the help.
