### ISSUE TITLE
Provide and option to add `-s` flag to `gofmt` call

### ISSUE THREAD

**Issue by bagrat** [fatih/vim-go#2168]
### What did you do? (required. The issue will be **closed** when not provided.)
The `gofmt` on write works perfectly. But when I run `gometalinter` externally, I get an error:

```
file is not gofmted with -s (gofmt)
```

### What did you expect to happen?
It would be great to have the option to add the `-s` flag to the `gofmt` call done by `vim-go`

### What happened instead?
N/A

### Configuration (**MUST** fill this out):
Does not apply, as this is rather a feature request.

**Comment by bagrat** [comment]
Will be happy to come up with a PR if some general directions are provided.

**Comment by bhcleek** [comment]
This already exists. See `:help g:go_fmt_options`.

**Comment by bagrat** [comment]
awesome, thank you @bhcleek !
