### ISSUE TITLE
where is "return type" when autocompleting with gopls

### ISSUE THREAD

**Issue by ggarlic** [fatih/vim-go#2186]
### What did you do? (required. The issue will be **closed** when not provided.)
after switching to gopls, when autocompleting, there's no "return type" in function signature

### What did you expect to happen?
function signature with return type
![图片](https://user-images.githubusercontent.com/889875/54806290-87f02f80-4cb4-11e9-9c9a-32c84f174ea3.png)

### What happened instead?
function signature w/o return type
![图片](https://user-images.githubusercontent.com/889875/54803359-2dea6c80-4caa-11e9-93ad-3bb6113377fd.png)

### Configuration (**MUST** fill this out):

* vim-go version:
`commit id: cf0b9c919ef1e6e312bc471495d989abb42a5eea`

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```vimrc
let g:go_fmt_command = "goimports"
let g:go_auto_type_info = 1
let g:go_addtags_transform = "camelcase"
let g:go_def_mode='gopls'
```

* Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 11 2019 08:36:40)
macOS version
Included patches: 1-1000
Compiled by Homebrew
```
* Go version (`go version`):
`go version go1.12.1 darwin/amd64`
* Go environment (`go env`):
```bash
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ggarlic/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ggarlic/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/41/g8vw25jx34x8lq8wb_ncnn180000gn/T/go-build008273956=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment]
I'm continuing to monitor this with `gopls`. As-is, there is _a_ solution, but it's not ideal and has several edge cases. Please be patient with the `gopls` integration; `gopls` is still a work in progress.

**Comment by ggarlic** [comment]
@bhcleek  👌 i'll wait

P.S.: i think the not so ideal solution you mean is something like changing the 'abbr' field of match
https://github.com/fatih/vim-go/blob/master/autoload/go/lsp.vim#L409
```viml
 let l:match = {'abbr': l:item.label, 'word': l:item.textEdit.newText, 'info': '', 'kind': go#lsp#completionitemkind#Vim(l:item.kind)}
```
to
```viml
let l:match = {'abbr': l:item.label . " " . l:item.detail, 'word': l:item.textEdit.newText, 'info': '', 'kind': go#lsp#completionitemkind#Vim(l:item.kind)}
```

P.S.: great work for integrating `gopls`, thanks 🍺

**Comment by sheerun** [comment]
It bit me as well. I'd be really happy if vim-go showed return types by default in autocomplete :)

**Comment by sheerun** [comment]
btw. the change @ggarlic suggested doesn't work for me as I get: `Omnifunc returned bad value to YCM! Vim(let):...: go#lsp#completionitemkind#Vim(l:item.kind)}`

@bhcleek Could you reopen this issue so you we can track progress on this?

**Comment by sheerun** [comment]
btw. following work for me:

```
    let l:match = {'abbr': l:item.label . " " . get(l:item, 'detail', ''), 'word': l:item.textEdit.newText, 'info': '', 'kind': go#lsp#completionitemkind#Vim(l:item.kind)}
```

@bhcleek Maybe it would be good idea to make it default until you have final solution with gopls?
