### ISSUE TITLE
Document how to disable go module support

### ISSUE THREAD

**Issue by kevinburke** [fatih/vim-go#2191]
When I hit `:GoBuild` now, vim-go attempts to cd up two directories and run `go mod init`. How do I disable this behavior? I read through doc/vim-go.txt but did not find any documentation in the `:GoBuild` command nor any for `mod`.

**Comment by kevinburke** [comment]
Ah, I need to set GO111MODULE=off in my environment.

**Comment by bhcleek** [comment]
As you discovered, this wasn't vim-go at all; it was the go command.

**Comment by kevinburke** [comment]
Fair, it turns out it was the third line of a three-line error message, which wasn't super clear either...
