### ISSUE TITLE
SSH Prompt when creating main.go in module subdir

### ISSUE THREAD

**Issue by dadleyy** [fatih/vim-go#2194]
This could be a result of me not fully understanding go modules, but vim is prompting me for ssh credentials to github when creating a `main.go` file in a subdir of module.

### What did you do? (required. The issue will be **closed** when not provided.)

1. Create module for current directory w/ `go mod init ...`
2. Create `main.go` file (no prompt)
3. Create subdirectory
4. `cd` into subdir
5. Create `main.go` file
6. ❗️ SSH Prompt

![login-prompt](https://user-images.githubusercontent.com/1545348/55031148-51802080-4fe4-11e9-9659-030f267043d8.gif)

### What did you expect to happen?

I expected `main.go` to be created the same way the `main.go` was at the root directory of the module, without needing the ssh prompt.

### Configuration (**MUST** fill this out):

* vim-go version: `40fa2df` (installed with [Vundle](https://github.com/VundleVim/Vundle.vim)).

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" ...
Plugin 'fatih/vim-go'
call vundle#end()
```

* Vim version (first three lines from `:version`):

[MacVim 8.1.950](https://github.com/macvim-dev/macvim/releases/tag/snapshot-155)

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 18 2019 23:51:40)
macOS version
Included patches: 1-950
```

* Go version (`go version`): `go version go1.12 darwin/amd64`

**Comment by bhcleek** [comment]
vim-go isn't doing any magic here. I suspect that if you disable vim-go and try this same thing, you're going to get the same result.

**Comment by dadleyy** [comment]
@bhcleek it only happens when I have this plugin installed with vundle _and_ am using MacVim. Seems more like a MacVim issue I guess, just wanted to see if anyone else has experienced the same thing.

**Comment by hamdiallam** [comment]
I've been having this same issue and it's driving me nuts! Repeated ssh prompts when canceled. Removing vim-go fixed the issue but i'd like to use the package.

@dadleyy did your fix resolve the issue completely?

**Comment by hamdiallam** [comment]
ahh, i'm still getting this error. Most annoying thing

**Comment by bhcleek** [comment]
I don't normally monitor closed issues, but something brought up today made me remember this issue. 

I suspect that you're getting this because vim-go makes frequent use of `go list`. What you're likely encountering is an artifact of https://github.com/golang/go/issues/29452. If you run `go list -v` in that nested directory you're going to see `go list` reach out to try to find some dependencies.
