### ISSUE TITLE
omni completion fails on windows

### ISSUE THREAD

**Issue by wining** [fatih/vim-go#2197]
### What did you do? (required. The issue will be **closed** when not provided.)
```go
package main

type test struct {
	a int
	b int
}

func main() {
	t := &test{}
	t.a = 1
	t.
}
```
when input t.\<C-X\>\<C-O\> omni completion does not work。 the messages：
![图片](https://user-images.githubusercontent.com/4005513/55124767-5f4bb800-5142-11e9-9897-2658eb96757a.png)
omnifunc=go#complete#Complete
### What did you expect to happen?
omni completion menu popup

### What happened instead?
nothing happened 

### Configuration (**MUST** fill this out):

* vim-go version:
the master branch with commit "ce3d69e"
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
set encoding=utf-8
set shortmess=filnxtToOc
filetype plugin indent on
syntax on
set shiftwidth=4
set whichwrap=b,s,h,l,<,>,[,]
set completeopt=menuone,longest,noinsert
let g:go_fmt_command = "goimports"
let g:go_gocode_unimported_packages = 1
let g:go_list_type = 'quickfix'
let g:go_list_height = 10
```
* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 20 2019 23:02:23)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1027   
* Go version (`go version`):
go version go1.12.1 windows/amd64
* Go environment (`go env`):
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\master\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\GOPATH;D:\Work\mhserver\static;C:\Users\master\go;
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\master\AppData\Local\Temp\go-build044359946=/tmp/go-build -gno-record-gcc-switches

**Comment by bhcleek** [comment]
Can you check whether #2198 solves this for you?

**Comment by wining** [comment]
no。 another error appears
![图片](https://user-images.githubusercontent.com/4005513/55131771-edcc3380-515a-11e9-8e55-f25f0877107b.png)

**Comment by bhcleek** [comment]
Thank you for taking the time to try that branch. I've made an additional change. If you have the opportunity, could you try again using the latest commit on #2198 ?

**Comment by wining** [comment]
![图片](https://user-images.githubusercontent.com/4005513/55138335-29bcc400-516e-11e9-8b35-f52ab7b04aaa.png)

**Comment by bhcleek** [comment]
Hmm. That's better at least, but I'm not sure why it's failing. The logs from gopls will be useful, though.

Set `g:go_debug=['lsp']`, try the autocompletion, and then get the output from `:echo g:go_lsp_log`.

**Comment by wining** [comment]
![图片](https://user-images.githubusercontent.com/4005513/55138945-98e6e800-516f-11e9-9c62-64f0c8f82d73.png)

**Comment by bhcleek** [comment]
Does it work if you move change the filename? If not, then what if you change the filename and move it down a directory (e.g. $GOPATH/src/foo/foo.go)?

**Comment by wining** [comment]
Change the filename doesnot work。
Move down a directory works.

![图片](https://user-images.githubusercontent.com/4005513/55139578-0fd0b080-5171-11e9-99f1-0e703bf08cd8.png)
and Is there a method can config the popup-menu shows?

**Comment by bhcleek** [comment]
vim-go doesn't expose any options to configure the autocompletion dialog. If it did, what would you want to configure?

**Comment by wining** [comment]
I want to display the type .
![图片](https://user-images.githubusercontent.com/4005513/55140443-13653700-5173-11e9-92e1-b38b3b1a24f6.png)

**Comment by davidhenrygao** [comment]
> Does it work if you change the filename? If not, then what if you change the filename and move it down a directory (e.g. $GOPATH/src/foo/foo.go)?

I get the same problem, too.
why it can't work outsite the $GOPATH/src dir?
