### ISSUE TITLE
Preload gopls asynchronously

### ISSUE THREAD

**Issue by orlangure** [fatih/vim-go#2207]
Thank you for adding `gopls` support to `vim-go`.

As many may have noticed, the first usage of `gopls` is very slow, but the successive usages are very fast. Is there a way to perform the heavy preloading task asynchronously when vim starts instead of when `gopls` is actually accessed for the first time?

**Comment by bhcleek** [comment]
That will be added in the near future

**Comment by RaduBerinde** [comment]
Related to this - I enter and exit vim frequently, it would be cool if there was a way to set up `gopls` to run outside of vim and configure vim to connect to that.

**Comment by svanharmelen** [comment]
Additionally it would be great if this can be configurable. I use an LSP client and next to vim-go, so it would be nice if I can tell vim-go it should not to try to do any “smart” LSP things to prevent all these actions to be done by two plugins.
