### ISSUE TITLE
GoImport autocomplete not working in go mod project

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#2212]
### What did you do? (required. The issue will be **closed** when not provided.)
Hit colon and entered "GoImport" and tried to tab complete to package in current directory. Current directory is a go modules project. 

### What did you expect to happen?
Tab completion be aware of itself being in a go module directory. 

### What happened instead?
No tab completion. I did manually type the import and syntax tab completion worked fine. 

### Configuration (**MUST** fill this out):

* vim-go version:
HEAD

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5

* Go version (`go version`):
go version go1.12.1 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN="/Users/louis/git/gopath/bin"
GOCACHE="/Users/louis/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/louis/git/go/openfleet/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mc/xwfdd41j1j74xfmcmphbwpgw0000gn/T/go-build017737187=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bhcleek** [comment]
> Hit colon and entered "GoImport" and tried to tab complete to package in current directory. Current directory is a go modules project.

What did you type before trying to tab complete? Just `:GoImport`?  We need more information to understand your expectations here.

**Comment by ldelossa** [comment]
Sure, 

I have a repository:

```
~/git/go/openfleet master*
❯ tree
.
├── charts
│   ├── etcd-operator-init
│   │   ├── Chart.yaml
│   │   ├── charts
│   │   ├── templates
│   │   │   ├── NOTES.txt
│   │   │   ├── _helpers.tpl
│   │   │   ├── deployment.yaml
│   │   │   ├── role.yaml
│   │   │   ├── role_binding.yaml
│   │   │   └── service_account.yaml
│   │   └── values.yaml
│   └── openfleet-etcd
│       ├── Chart.yaml
│       ├── charts
│       ├── templates
│       │   ├── etcdcluster.yaml
│       │   └── nodeport.yaml
│       └── values.yaml
├── cmd
├── controlplane
│   ├── event.go
│   ├── eventlistener.go
│   ├── membership
│   │   ├── eventlistener.go
│   │   ├── eventlistener_test.go
│   │   ├── events.go
│   │   └── leasemanager.go
│   ├── reducer.go
│   └── state.go
├── go.mod
├── go.sum
└── tags
```

My working directory that neovim sees is typically the root. Tho the problem exists even I cd into a nested package. 

I open a buffer to controlplane/membership/event.go 

I hit ":" and then tab to GoImport. I now expect tab completion to autofill "github.com/ldelossa/openfleet" but I do not get that far. It cannot locate openfleet. ldelossa folder is in my GoPath, openfleet folder is not in my GoPath, it is outside of it and using "go mod"
