### ISSUE TITLE
Omni complete fail

### ISSUE THREAD

**Issue by wining** [fatih/vim-go#2214]
### What did you do? (required. The issue will be **closed** when not provided.)
```
package main

type Foo struct {
}

func (f *Foo) print() {
}

func main() {
	f := &Foo{}
	_ = f
        f.
}
```
Input "f." and ^X^O, complete menu doesn't pop-up.
The messages :
![图片](https://user-images.githubusercontent.com/4005513/55693826-bf184d80-59e3-11e9-89e5-59b73015f1d5.png)
### Configuration (**MUST** fill this out):

* vim-go version:
The master branch with commit 686167f5f03cedbfa5d188ee0d88c1ff2a1892ac [686167f]
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr  1 2019 19:15:50)
Included patches: 1-1099
Compiled by root@localhost.localdomain
* Go version (`go version`):
go version go1.11.1 linux/amd64
* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build159889427=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
I can't duplicate this. Perhaps it was a problem with `gopls` that's already been fixed? Can you run `:GoUpdateBinaries gopls`, exit vim, and then try the autocompletion again?

**Comment by bhcleek** [comment]
Nevermind. I can't duplicate what you're seeing exactly, but I can duplicate something similar.

**Comment by bhcleek** [comment]
You can use f04098811b8a7aba3dba699ed98f6f6e39b7d7ac until this is fixed on master.
