### ISSUE TITLE
what are default linters for golangci-linter in vim-go?

### ISSUE THREAD

**Issue by ChengYayu** [fatih/vim-go#2216]
### What did you do? (required. The issue will be **closed** when not provided.)
 
I saved one of my go files.

### What did you expect to happen?

I want to replace gometalinter with golangci-lint.
these are default linters in my mind.
deadcode, errcheck, gosimple, govet, ineffassign, staticcheck, structcheck, typecheck, unused, varcheck.
so these linters will all work, when i saved one of my go files.

### What happened instead?

Just govet and golint works.

### Configuration (**MUST** fill this out):

```
" GoMetaLinter settings
let g:go_metalinter_autosave = 1
let g:go_metalinter_command = "golangci-lint"
let g:go_list_type = 'quickfix'
```

**Comment by bhcleek** [comment]
`govet` and `golint`. `errcheck` should probably be added, too, for consistency.

https://github.com/fatih/vim-go/blob/master/autoload/go/config.vim#L265
