### ISSUE TITLE
GoInstallBinaries filed to install

### ISSUE THREAD

**Issue by amkgo** [fatih/vim-go#222]
In Windows 7, Vim 7.4 Yongwei build(2014-07-22 http://wyw.dcweb.cn/#download)
GOPATH=C:\myfolder\myprj; GOBIN=<empty>

When execute `:GoInstallBinaries` with GOBIN empty, vim-go says will install binaries to C/bin folder and actually installed the binaries not in `%GOPATH%/bin` but to this folder:
<:pwd folder>\C\bin

When I set `let g:go_bin_path="C:/myfolder/myprj/bin"` the binaries will be installed correctly.

Andrew

**Comment by debuuu** [comment]
I'm getting this problem, fresh install of vim-go, on Windows 10. Looking through the source, I couldn't find the fix that @alexaandru made. Wondering if this is known to be back for Win 10 or if I'm doing something else wrong.
