### ISSUE TITLE
Error from `go#lsp#DidOpen` function

### ISSUE THREAD

**Issue by yech1990** [fatih/vim-go#2220]
**An error occur on opening a go file.**

![errorgo](https://user-images.githubusercontent.com/5415510/55798549-d0f01280-5b01-11e9-9385-3267165dcdee.png)

### Configuration (**MUST** fill this out):

* vim-go version:

```
commit 9a7cf4a68adcc9327af33cd1449e7859c0e32af8
```

* Vim version (first three lines from `:version`):
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
```

* Go version (`go version`):

```
go version go1.12.3 linux/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/usr/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/usr/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build867612051=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by pedroandrade** [comment]
Same issue here and `:GoInstallBinaries` fix it

you should try  `:GoinstallBinaries` and restart the neovim

**Comment by yech1990** [comment]
I wonder can `GoinstallBinaries` be wrapped into a function, and vim plugin manager can install those packages on updating vim-go.

Some other vim plugin which are written in JavaScript, can be compliled by yarn/npm, right after plugin manager fetched a new version.

**Comment by ont** [comment]
Got slightly different error after today `vim-go` update:
```
Error detected while processing function <SNR>54_register[9]..go#lsp#DidOpen:
line   19:
E117: Unknown function: sendMessage
E15: Invalid expression: l:lsp.sendMessage(l:msg, l:state)
```
But also successfully fix it with `:GoinstallBinaries` command.

**Comment by wangycc** [comment]
[No Name]                                                                                                        0,0-1          All
E492: Not an editor command: GoinstallBinaries
