### ISSUE TITLE
Autocomplete still wants gocode(-gomod) with gopls

### ISSUE THREAD

**Issue by tommyknows** [fatih/vim-go#2222]
### What did you do?

Wanted to switch from `gocode` and `gocode-gomod` to `gopls` instead, as `gocode-gomod` uses a lot of CPU on my system (I was trying to debug this when I saw gopls).
I installed `gopls` and set `let g:go_def_mode='gopls'` in my vimrc.
Then removed both gocode binaries.

### What did you expect to happen?

I do not need the binaries for `gocode` and `gocode-gomod` anymore

### What happened instead?

When starting vim, I get the message that binaries are missing and and I should install them with the `GoInstallBinaries` command.

Why do I still need the binaries?
Also, is it a config error that both gocode-binaries are started when working with modules?

Thank you

**Comment by bhcleek** [comment]
`gocode` and `gocode-gomod` are still needed when `g:go_info_mode='gocode'`. What value do you have set for `g:go_info_mode` and `g:go_auto_type_info`?

**Comment by tommyknows** [comment]
I didn't set any values for these variables - and I guess that the default then is gocode.
But after adding
```
let g:go_info_mode='guru'
let g:go_auto_type_info='gopls'
```

to my vimrc, gocode isn't needed anymore :)

Thank you for your help.

**Comment by bhcleek** [comment]
FWIW, `gopls` is not a valid value for `g:go_auto_type_info`.

**Comment by tommyknows** [comment]
Right, sorry. I didn't notice because I overwrite this value a few lines below.
```
let g:go_auto_type_info = 1
```
