### ISSUE TITLE
Quickfix stops displaying 

### ISSUE THREAD

**Issue by emil2k** [fatih/vim-go#2225]
### What did you do? (required. The issue will be **closed** when not provided.)

Ran `:GoBuild` on a file with a syntax error, just placed an `a` on a random line.

At first the quickfix window shows as expected with `:ls` output is a follows:

```
[Quickfix List] GoBuild                                                                                                   1,1             All
:ls
  1 #a   "split.go"                     line 0
  2      "split_test.go"                line 0
  3 %a-  "[Quickfix List]"              line 1
```
<img width="828" alt="Screen Shot 2019-04-11 at 10 57 33 AM" src="https://user-images.githubusercontent.com/2730310/55944360-bffde900-5c48-11e9-916f-043c1810b0c2.png">

If go to quickfix buffer with `:bnext<CR>` and then do `:bp <BAR> bd #<CR>` to close the quickfix buffer.

The next time I run `:GoBuild` instead of a quickfix list window showing at the bottom a window opens at the bottom with the cursor on the line containing the syntax error. The `:ls` output is:

```
:ls
  1  h   "split.go"                     line 14
  2 %a   "split_test.go"                line 1
  3  h-  "[No Name]"                    line 1
```

<img width="854" alt="Screen Shot 2019-04-11 at 10 59 29 AM" src="https://user-images.githubusercontent.com/2730310/55944491-02272a80-5c49-11e9-8750-01606c20f25d.png">

### What did you expect to happen?

A quickfix window should open at the bottom with a list of errors. Clicking enter on one of the lines should take the cursor in the original window to the line of the error. It should keep working like that even if I close the quicklist buffer.

### What happened instead?

A new one-line window opens at the bottom that shows the file at the location of the error.  

### Configuration (**MUST** fill this out):

* vim-go version:

```
emil - ~/.vim/bundle/go > git show HEAD
commit 9a7cf4a68adcc9327af33cd1449e7859c0e32af8 (HEAD -> master, origin/master, origin/HEAD)
Merge: 680a273 81cdaeb
Author: Billie Cleek <bhcleek@users.noreply.github.com>
Date:   Mon Apr 8 20:25:44 2019 -0700

    Merge pull request #2218 from bhcleek/fix-did-change
    
    Fix did change
```

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
execute pathogen#infect()
syntax on
filetype plugin indent on
set number
set laststatus=2
" Use system clipboard:  http://stackoverflow.com/a/10979533/220710
set clipboard=unnamed
set backspace=indent,eol,start
set wildmode=longest,list,full
set wildmenu
set hidden
colorscheme molokai
imap ii <Esc>
nmap c :hide<CR>

" Disable Ex Mode
nnoremap Q <nop>

" Show a line at 80 characters
autocmd BufWinEnter,WinEnter * setlocal colorcolumn=80
autocmd BufWinLeave,WinLeave * setlocal colorcolumn=0

" Automatically close completion pane
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Force the .md extension to Markdown
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.md setlocal textwidth=80

" Buffer traversal
let g:airline#extensions#tabline#enabled = 1
nmap <Leader>n :enew<cr>
nmap <Leader>f :bnext<CR>
nmap <Leader>d :bprevious<CR>
nmap <Leader>q :bp <BAR> bd #<CR>
nmap <Leader>l :ls<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
noremap <Leader>0 :10b<CR>

" Go
au FileType go nmap <Leader>a <Plug>(go-imports)
au FileType go nmap <Leader>r <Plug>(go-run)
au FileType go nmap <Leader>b <Plug>(go-build)
au FileType go nmap <Leader>t <Plug>(go-test)
au FileType go nmap <Leader>tt <Plug>(go-test-func)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <Leader>gb <Plug>(go-doc-browser)
au FileType go nmap gd <Plug>(go-def)
```

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950
```

* Go version (`go version`):

```
go version go1.12.1 darwin/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/emil/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/emil/Code"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sg/nh_hm05n2cq68v2ll_j6pccm0000gp/T/go-build869396885=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment]
I have tried to duplicate this multiple times without success. I can't think of anything in vim-go that would explain this behavior, and I don't see anything in the vimrc you provided that explains it either.

To help us analyze this, can you use `set nohidden` and see if you still see the same problem? If you do, then can you disable any other plugins that you're using to see if there's some interplay there that's causing it?

**Comment by emil2k** [comment]
With `set nohidden` the behavior persists, but after closing the quicklist buffer and running `GoBuild` the `:ls` output is showing without the "No Name" buffer:

```
:ls
  1 %a   "split.go"                     line 14
  2 #    "split_test.go"                line 1
Press ENTER or type command to continue
```

I had the other plugins disabled in the initial report, this is what my `.vim` folder looks like:

```
.vim
├── autoload
├── bundle
│   └── go
├── bundle.bk
│   ├── ack
│   ├── airline
│   ├── fugitive
│   ├── go
│   ├── largefile
│   ├── qf
│   ├── snippets
│   ├── tagbar
│   ├── ultisnips
│   ├── whitespace
│   └── ycm
└── colors
```

- `go` is the `vim-go` repo
- `autoload` contains only pathogen
- `bundle.bk` has all my old plugins

**Comment by bhcleek** [comment]
I've been trying to duplicate this without success, but I noticed a couple of things about your original description that don't quite seem to line up with the screenshots you provided.

In the second step (after running `:GoBuild` the second time), you say:
> The :ls output is:
> 
```
:ls
  1  h   "split.go"                     line 14
  2 %a   "split_test.go"                line 1
  3  h-  "[No Name]"                    line 1
```

Notice that `split_test.go` is the active buffer according to `:ls`, but your screenshot shows `split.go`. I'm not quite sure what that means, but it's an inconsistency that might be part of the problem.

When I open a go file, then edit its test file, go back to the original go file (based on the first `:ls` output you pasted, I think that's basically what you did) and then follow the directions you provided, I end up with only the quickfix window after the `bp | bd #` command, because:
1. at the start the `split.go` is active
2. after changing to the quickfix window `split.go` is the alternate window.
3. `:bnext` makes `split.go` the active buffer again with the quickfix window the alternate.
4. in `bp | bd #`, the alternate buffer, `#`, is the quickfix window.

**Comment by emil2k** [comment]
I'm not sure, but I might have also switched active buffers before running `:ls`.

I can reproduce this easily on my setup, so I think it is best for me to look at the source and try to debug this. It will be a good way to learn more about vim. I'll report back when I have more insights.

**Comment by bhcleek** [comment]
@emil2k have you found the root cause?

**Comment by emil2k** [comment]
@bhcleek I took a quick look at the code yesterday, but I haven't had the time to look into it deeper yet.

**Comment by emil2k** [comment]
@bhcleek I tried to debug this a bit today, but I go nowhere really, my knowledge of vim internals is insufficient.

Here are some logs though that maybe you can make sense off, these are the outputs for `:12verbose GoBuild` the `works.log` is for when the build works as expected and the `fails.log` is for when it fails as described before:

[fails.log](https://github.com/fatih/vim-go/files/3104755/fails.log)
[works.log](https://github.com/fatih/vim-go/files/3104756/works.log)

I diffed these and tried to find something that could have gone wrong, but had no luck, tell me if you get some clue from this and I can investigate further.

**Comment by bhcleek** [comment]
The logs aren't terribly helpful.

I didn't realize this _ever_ works for you. What exactly do you do differently when it works vs when it doesn't?

A video of your failure case may be helpful. Here's what I'm doing to (unsuccessfully) try to duplicate what you've described:
![2225](https://user-images.githubusercontent.com/1958864/56552524-6cd93f80-6540-11e9-91c9-c359f2bb7565.gif)

You can create a video on a mac pretty easily by using Shift+Cmd+5 and then running `ffmpeg -i $MOV 2225.gif` (you might need to install `ffmpeg` with brew).

**Comment by emil2k** [comment]
The gif screen cast is making this page really slow in my browser so I just uploaded the screencast  here:
https://streamable.com/ipwre

All other plugins except pathogen are disabled and it is using the following `.vimrc`:

```
execute pathogen#infect()
syntax on
filetype plugin indent on
set number
set laststatus=2
" Use system clipboard:  http://stackoverflow.com/a/10979533/220710
set clipboard=unnamed
set backspace=indent,eol,start
set wildmode=longest,list,full
set wildmenu
set nohidden
colorscheme molokai
imap ii <Esc>
nmap c :hide<CR>

" Disable Ex Mode
nnoremap Q <nop>

" Show a line at 80 characters
autocmd BufWinEnter,WinEnter * setlocal colorcolumn=80
autocmd BufWinLeave,WinLeave * setlocal colorcolumn=0

" Automatically close completion pane
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Force the .md extension to Markdown
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.md setlocal textwidth=80

" Buffer traversal
let g:airline#extensions#tabline#enabled = 1
nmap <Leader>n :enew<cr>
nmap <Leader>f :bnext<CR>
nmap <Leader>d :bprevious<CR>
nmap <Leader>q :bp <BAR> bd #<CR>
nmap <Leader>l :ls<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
noremap <Leader>0 :10b<CR>

" Go
au FileType go nmap <Leader>a <Plug>(go-imports)
au FileType go nmap <Leader>r <Plug>(go-run)
au FileType go nmap <Leader>b <Plug>(go-build)
au FileType go nmap <Leader>t <Plug>(go-test)
au FileType go nmap <Leader>tt <Plug>(go-test-func)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <Leader>gb <Plug>(go-doc-browser)
au FileType go nmap gd <Plug>(go-def)
```

Also the package directory only contains that `test.go` file:

```
emil - /tmp/go > tree .
.
└── test.go

0 directories, 1 file
```

**Comment by bhcleek** [comment]
Your quick fix window is behaving very differently from mine. When I change to the quickfix window and `:hide` it, `:ls` no longer reports it _and_ `:bnext` doesn't have another buffer to change _to_. I wonder if this is a difference in Vim or whether you've somehow overridden your quickfix window by using something like `vim-qf`.

**Comment by emil2k** [comment]
I only had the `vim-go` plug in in the `bundle` directory when I did this test and the `.vimrc` was as posted previously. 

How is the closing of the quickfix buffer affecting vim-go on the subsequent `GoBuild` call?

**Comment by bhcleek** [comment]
I'm not sure how it's affecting it, because I can't figure out why your quickfix window isn't behaving the same as mine. After you `:hide` the quickfix window, what's `:ls` report?

**Comment by bhcleek** [comment]
@emil2k any progress on this?

**Comment by emil2k** [comment]
@bhcleek Sorry for the delay, I got carried away working on something else and neglected this.

Before `GoBuild` and `hide`:

```
:ls
  1 %a   "main.go"                      line 5
```

After `GoBuild` and `hide`:

```
:ls
  1 %a   "main.go"                      line 5
  3  h-  "[Quickfix List]"              line 0
```

After `bnext` and `bp | bd #` on the quicklist buffer:

```
:ls
  1 %a   "main.go"                      line 5
```

After another `GoBuild` call, without  a `hide` call on the window that pops up at the bottom which is the buffer of the file with the cursor on the line with the error (expected behavior would be to see the quicklist buffer with the error listed):

```
:ls
  1 %a   "main.go"                      line 5
```

I'm using this file as the test file, it is the only file in the directory, and as stated before all other plugins are disabled and the `.vimrc` is as posted previously:

```
package main

import "fmt"

a

func main() {
	fmt.Println("vim-go")
}
```

**Comment by bhcleek** [comment]
@emil2k are you still seeing this problem?

**Comment by emil2k** [comment]
I can't reproduce it anymore.

**Comment by bhcleek** [comment]
Thank you for confirming
