### ISSUE TITLE
Omnicomplete spawns a new buffer.

### ISSUE THREAD

**Issue by dsimmons** [fatih/vim-go#223]
I'm only filing this issue because it's driving me nuts and I've been unsuccessful at tracking down the root cause. Admittedly, my Vimscript debugging skills (or knowledge for that matter) are sufficiently lacking. My hope is that someone has seen this behavior before and/or I'm able to be pointed in the right direction.

**The issue:**
- Any time a completion menu opens up, at that same exact moment, a [Scratch] buffer opens as well.
- This buffer stays open while the completion menu is active -- as soon as it disappears, so does the buffer.
- Any time I move through the completion menu options, the buffer updates to reflect the type information / method signature that my cursor/highlight is over.

**Where I'm at:**
- I've pinpointed the behavior to `vim-go` specifically (or more generally, go code). Completion for other languages doesn't produce the same issue.
- The text that I'm seeing in the buffer appears to be coming from the `go - info` component. It always mirrors what my cursor is over in the completion menu (specifically, the type / method signature info).
- I've played around with both the `ftplugin/go.vim` and `autoload/go/complete.vim` -- it appears that it's at least being kicked off in there because I was able to comment out some of the code that appeared to shell out to `go info` and get it to not happen anymore, but that killed completion completely.
- I tried profiling Vim to no avail.

It's particularly annoying because I default to a Solarized colorscheme but have an `autocmd` on golang buffers to switch it to Molokai. Every time this happens (a few times a minute), a new/empty scratch buffer is spawned and my editor flickers as it's assigned a golang `ft` and subsequently changes colors. Flicker aside, there's a noticeable quarter-second or so delay / performance degradation, screen real-estate is lost, and the code that I'm looking at changes vertical positioning. :confused: 

**Screenshot**
![screenshot](https://dl.dropboxusercontent.com/u/6968139/oss/issues/Screenshot%202014-11-10%2014.00.39.png)

Any ideas?

**Comment by ChrisMcKenzie** [comment]
@dsimmons :+1: thanks this saved me so much frustration!

**Comment by dsimmons** [comment]
Glad this helped someone else! :smile:

**Comment by nero1991** [comment]
@dsimmons 👍 thanks

**Comment by antoineco** [comment]
Also related:
https://stackoverflow.com/q/3105307/4716370

**Comment by konstantinzolotarev** [comment]
@dsimmons Thank you very much ! You just saved my life =D
