### ISSUE TITLE
how to disable that Autocompletion is enabled by default via 'omnifunc'

### ISSUE THREAD

**Issue by ofttryaj** [fatih/vim-go#2232]
### What did you do? (required. The issue will be **closed** when not provided.)

I do not want to use the vim-go's default autocompletion
### What did you expect to happen?

how to disable that Autocompletion is enabled by default via 'omnifunc'
### Configuration (**MUST** fill this out):
" Golang
let g:go_play_open_browser = 0
let g:go_fmt_fail_silently = 1
let g:go_fmt_command = "goimports"
let g:go_list_type = "quickfix"
let g:go_def_mode = ""
let g:go_info_mode = ""
" let g:go_metalinter_enabled = 1
" let g:go_metalinter_command = "gometalinter"
" beautify it
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
let g:go_bin_path = expand("/Users/wlfg/go/bin")
* vim-go version:

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):
neovim v0.3.4
* Go version (`go version`):
go1.12.3
* Go environment (`go env`):

**Comment by bhcleek** [comment]
Set `omnifunc` in an `after/ftplugin/go.vim` to whatever you want it to be.
