### ISSUE TITLE
Error installing golang.org/x/tools/cmd/gopls

### ISSUE THREAD

**Issue by adamzyg** [fatih/vim-go#2233]
### What did you do? (required. The issue will be **closed** when not provided.)
GoInstallBinaries

### What did you expect to happen?
Install successfully

### What happened instead?
vim-go: gopls not found. Installing golang.org/x/tools/cmd/gopls to folder /home/xxxxxx/go/bin/
Error installing golang.org/x/tools/cmd/gopls: # golang.org/x/tools/internal/tool^@../../../golang.org/x/tools/internal/tool/tool.go:85:15: s.Output undefined (type *flag.FlagSet has no
 field or method Output, but does have flag.output)^@../../../golang.org/x/tools/internal/tool/tool.go:86:16: s.Output undefined (type *flag.FlagSet has no field or method Output, but d
oes have flag.output)^@../../../golang.org/x/tools/internal/tool/tool.go:133:16: s.Output undefined (type *flag.FlagSet has no field or method Output, but does have flag.output)^@
vim-go: installing finished!

### Configuration (**MUST** fill this out):

* vim-go version:
commit 863e0e91cd2fb5d7624f6447a80e668c897c7e4a

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
let g:go_version_warning = 0                                                                                                                                                             
set runtimepath^="/home/xxxxxx/.vim_go_runtime"

source /home/xxxxxx/.vim_go_runtime/vimrc/basic.vim
source /home/xxxxxx/.vim_go_runtime/vimrc/filetypes.vim
source /home/xxxxxx/.vim_go_runtime/vimrc/plugins.vim
source /home/xxxxxx/.vim_go_runtime/vimrc/extended.vim

try
  source /home/xxxxxx/.vim_go_runtime/custom_config.vim
catch
endtry

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056

* Go version (`go version`):
go version go1.9.7 linux/amd64
* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xxxxxx/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build543461607=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Comment by bhcleek** [comment]
You're using a very old version of Go; `flag.Ouput` was added in Go 1.10: https://golang.org/doc/go1.10#flag
