### ISSUE TITLE
:GoInstallBinaries fails - Error installing golang.org/x/tools/cmd/gopls

### ISSUE THREAD

**Issue by sding3** [fatih/vim-go#2246]
### What did you do? (required. The issue will be **closed** when not provided.)
Ran :GoInstallBinaries in vim  

### What did you expect to happen?
Expected Go binaries to be installed successfully 

### What happened instead?
Go binaries were not installed successfully due to the following error:
```
Error installing golang.org/x/tools/cmd/gopls: # golang.org/x/tools/internal/lsp/source^@go/src/golang.org/x/tools/internal/lsp/source/symbols.go:226:18: ti.EmbeddedType undefined (type *types.Interface has no field or method Embed
dedType)^@
```

### Configuration (**MUST** fill this out):

* vim-go version:
```
tag: v1.20  
commit 58cda9d64bb822ed567ed775e30839d7344feb4a  
```

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
no vimrc  

* Vim version (first three lines from `:version`):
```VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)```

* Go version (`go version`):
```go version go1.10.4 linux/amd64```

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build679087800=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
`gopls` is not intended to be buildable by old versions of Go, and newer versions of vim-go do not explicitly support older versions of Go either. If you'd like `gopls` to be buildable by older versions of Go, please create an issue in github.com/golang/go.

**Comment by stamblerre** [comment]
I apologize, but we won't be supporting Go 1.10 in `gopls`. Please see https://github.com/golang/go/issues/31693.

**Comment by sding3** [comment]
No problem - that's fine.
