### ISSUE TITLE
GoPath is wrong on MacOS 10.14.4 with MacVim 8.1.950

### ISSUE THREAD

**Issue by AllenDang** [fatih/vim-go#2249]
### What did you do? (required. The issue will be **closed** when not provided.)
:GoPath returns my gopath is set to /User/myname/go
But my GoPath is set to /User/myname/Documents/Gocode.
So :GoInstallBinaries installs all the required tools in wrong directory.

### What did you expect to happen?
:GoPath should load my $GOPATH env setting correctly.

### What happened instead?
:GoPath returns my gopath is set to /User/myname/go

### Configuration (**MUST** fill this out):

* vim-go version:
1.20 - (April 22, 2019)

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
filetype plugin indent on
set backspace=indent,eol,start

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950

* Go version (`go version`):
go version go1.12 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/myname/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/myname/Documents/Gocode"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y0/ghys9qvn4c7cykcv61jhb__r0000gn/T/go-build646436878=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bhcleek** [comment]
With gui applications on macOS, you need to make sure your environment variables are exported for them correctly using `launchctl setenv` or by configuring an app's plist: https://superuser.com/questions/476752/setting-environment-variables-in-os-x-for-gui-applications.
