### ISSUE TITLE
Syntax-only configuration

### ISSUE THREAD

**Issue by gbrlsnchs** [fatih/vim-go#2250]
This is a feature request.

I have used this plugin for some time and it's been great, but I have instead switched to a generic LSP client. However, this plugin also contains syntax/indentation improvements, which I can't find in any other plugin.

It would be nice to not pollute my command list with commands I won't use (not because they're not nice, but because I don't need them anymore) either by disabling the core functionality by setting a variable or by splitting this repo in two, still I think the former is more viable.

It's fine if this idea is rejected, meaning I'd have to fork and maintain a syntax-only repo by my own. Thank you anyway for the great work.

**Comment by bhcleek** [comment]
generic LSP support will leave a lot of functionality out (e.g. `:GoTest`, `:GoBuild`, `:GoFreeVars`, `:GoImport`, `:GoFillStruct`, `:GoCallers`, etc.), because LSP doesn't support everything that vim-go does. 

Given that, perhaps it's best for you to simply add `delcommand` commands to your `after/ftplugin/go.vim` file to remove the commands that are noise for you?

**Comment by gbrlsnchs** [comment]
@bhcleek what about `vim-go` initializing stuff in the background (like the LSP server, for example), how can I avoid that (if `vim-go` ever does that)?

**Comment by bhcleek** [comment]
The only long running server that vim-go depends on is `gopls`, an LSP server. Right now there isn't a good way to keep it from being initialized, because several things depend on it, and more will depend on it going forward as we drop support for older tools that are being deprecated.

**Comment by gbrlsnchs** [comment]
I see... I think that's the only issue, in this case. Running `delcommand` sounds fine to me, but having an unused instance of `gopls` server running is troublesome, as the generic LSP client I'm using also spawns an instance of `gopls`. Instead of having this "syntax-only mode", there could be an option to prevent `vim-go` to start the server... or have the syntax-related stuff in a different plugin, which I think is difficult to achieve.

**Comment by bhcleek** [comment]
`gopls` has recently released support for sharing the server between multiple clients, and vim-go supports that model by leveraging `g:go_gopls_options`. Given that `gopls` can be shared among clients and that vim-go depends on gopls for a number of features, I think it's appropriate to close this now.

WDYT, @gbrlsnchs ?

**Comment by gbrlsnchs** [comment]
For my use case, this is fine, since I use another LSP client to communicate with `gopls`. Thanks.
