### ISSUE TITLE
gopls functionality doesn't when GOPATH should be detected

### ISSUE THREAD

**Issue by dhduvall** [fatih/vim-go#2254]
### What did you do? (required. The issue will be **closed** when not provided.)

I have `let g:go_autodetect_gopath = 1` in my `~/.vimrc`, which does a fine job of figuring out what `$GOPATH` should be set to in my workspace. Then I use one of the functions that uses `gopls`, such as autocomplete.

The issue seems to be that the `BufEnter` `autocmd` that sets `$GOPATH` based on the autodetected value runs after `gopls` is launched (from the `FileType` `autocmd` in the `vim-go` `augroup`, if I'm reading this correctly). If I start vim with `$GOPATH` already set correctly, everything seems to work correctly.

Perhaps I need to move away from using `g:go_autodetect_gopath`, but I'm not sure what mechanism I'd use to set `$GOPATH` (I don't want or need to set it generally outside vim, and it's potentially different for different workspaces).

### What did you expect to happen?
Get correct autocomplete results.

### What happened instead?
Get back nothing. `:messages` shows
```
vim-go: [completion] FAIL
vim-go: no matches
```

### Configuration (**MUST** fill this out):

* vim-go version:
3e9a292

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 07 2018 22:08:48)
Included patches: 1-549
Modified by team+vim@tracker.debian.org
```
* Go version (`go version`):
1.12.4

* Go environment (`go env`):

**Comment by bhcleek** [comment]
Thank you for the report @dhduvall . This may be a fairly easy fix. I'll get to it as soon as I can, but there are _some_ caveats that might complicate some use cases.

FWIW, I use https://direnv.net/ to manage these kinds of things so that even `go build` at the commandline will work.

**Comment by bhcleek** [comment]
Does #2255 resolve this for you?

**Comment by dhduvall** [comment]
Yes, it does; thank you!
