### ISSUE TITLE
Autocomplete (Ctrl+X Ctrl+O) not working

### ISSUE THREAD

**Issue by gun1x** [fatih/vim-go#2256]
### What did you do? (required. The issue will be **closed** when not provided.)
I tried using Ctrl+X Ctrl+O to trigger autocompletion

### What did you expect to happen?
Autocompletion to work.

### What happened instead?
Nothing.

Autocompletion does work if i install [youcompleteme](https://aur.archlinux.org/packages/vim-youcompleteme-git/), but I would like to work with Ctrl+X Ctrl+O

### Configuration (**MUST** fill this out):

* vim-go version:
1.20-1: https://aur.archlinux.org/packages/vim-go/

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
source $VIMRUNTIME/defaults.vim
set mouse=""
set nu
set laststatus=2
set t_Co=256
set wildmode=longest,list
let g:powerline_pycmd = 'py3'
nnoremap <C-Up> <C-W><C-K>
nnoremap <C-Down> <C-W><C-J>
nnoremap <C-Right> <C-W><C-L>
nnoremap <C-Left> <C-W><C-H>
nnoremap <F5> :terminal % <CR>
set splitbelow
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
let g:indentLine_color_term = 239
colorscheme ron
```
* Vim version (first three lines from `:version`):
```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 26 2019 21:55:55)
Included patches: 1-1186
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     +emacs_tags        +insert_expand     +modify_fname      +netbeans_intg     +ruby/dyn          +terminfo          +vreplace
+arabic            +cmdline_hist      +eval              +job               +mouse             +num64             +scrollbind        +termresponse      +wildignore
+autocmd           +cmdline_info      +ex_extra          +jumplist          -mouseshape        +packages          +signs             +textobjects       +wildmenu
+autochdir         +comments          +extra_search      +keymap            +mouse_dec         +path_extra        +smartindent       +textprop          +windows
-autoservername    +conceal           -farsi             +lambda            +mouse_gpm         +perl/dyn          +startuptime       +timers            +writebackup
-balloon_eval      +cryptv            +file_in_path      +langmap           -mouse_jsbterm     +persistent_undo   +statusline        +title             -X11
+balloon_eval_term +cscope            +find_in_path      +libcall           +mouse_netterm     +postscript        -sun_workshop      -toolbar           -xfontset
-browse            +cursorbind        +float             +linebreak         +mouse_sgr         +printer           +syntax            +user_commands     -xim
++builtin_terms    +cursorshape       +folding           +lispindent        -mouse_sysmouse    +profile           +tag_binary        +vartabs           -xpm
+byte_offset       +dialog_con        -footer            +listcmds          +mouse_urxvt       +python/dyn        -tag_old_static    +vertsplit         -xsmp
+channel           +diff              +fork()            +localmap          +mouse_xterm       +python3/dyn       -tag_any_white     +virtualedit       -xterm_clipboard
+cindent           +digraphs          +gettext           +lua/dyn           +multi_byte        +quickfix          +tcl/dyn           +visual            -xterm_save
-clientserver      -dnd               -hangul_input      +menu              +multi_lang        +reltime           +termguicolors     +visualextra
-clipboard         -ebcdic            +iconv             +mksession         -mzscheme          +rightleft         +terminal          +viminfo
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_per
l/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-
rpath,/usr/lib/perl5/5.28/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.28/core_perl/CORE
 -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```
* Go version (`go version`):
```
go version go1.12.4 linux/amd64
```

* Go environment (`go env`):
```

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gunix/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gunix/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build766941931=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
Do you have `gopls` installed? (`:GoInstallBinaries gopls`)? Have you updated it recently (`:GoUpdateBinaries gopls`)?

Are you working in module more or GOPATH mode? 

Can you provide clear directions for how to duplicate the failure you're seeing?

**Comment by gun1x** [comment]
> Do you have `gopls` installed? (`:GoInstallBinaries gopls`)? Have you updated it recently (`:GoUpdateBinaries gopls`)?

I installed all binaries with `:GoInstallBinaries`, including `gopls`.

Also omnifunc is set to:
```
 omnifunc=go#complete#Complete
        Last set from /usr/share/vim/vimfiles/ftplugin/go.vim line 29
```

> Are you working in module more or GOPATH mode?

I did not set `GOPATH` so it should default to `$HOME/go`, if that is what you mean.
 
> Can you provide clear directions for how to duplicate the failure you're seeing?
1. install archlinux
2. install vim from the default repos
3. install vim-go from aur
4. open a GoLang script and try to use Ctrl+X Ctrl+O

**Comment by bhcleek** [comment]
where is the file you're opening? What are the contents of the file you're opening? What are you trying to autocomplete?

**Comment by gun1x** [comment]
The file is located in `/home/gunix/git/gun1x/wireguard_go_api/`. I am trying to get autocomplete before/after [this line](https://gitlab.com/gun1x/wireguard_go_api/blob/b1cb673a74919120d148753e9308ac78fa8b5bf4/populate_wg_config.go#L78).

Here I am typing `p.` and hitting Ctrl+X Ctrl+O, but I don't get the dropdown. On another Arch where I also got YMC, I get autocomplete for `IPAddr, PubKey, formatPeer()`. I am hoping to get the same effect without YCM, since I don't want to build all of that for this...

**Comment by bhcleek** [comment]
Does that project have a go.mod file?

**Comment by gun1x** [comment]
> go.mod

Nope.

**Comment by bhcleek** [comment]
Since you're not in GOPATH mode, `gopls` will require a `go.mod` file for your module.

**Comment by gun1x** [comment]
> Since you're not in GOPATH mode, `gopls` will require a `go.mod` file for your module.

I do not know what you mean with "GOPATH mode". Even if I set the GOPATH variable to something else (like `$HOME/.go` instead of the [default](https://github.com/golang/go/wiki/SettingGOPATH) `$HOME/go`) this, does not fix the issue. I just have to do `:GoInstallBinaries` so that the binaries get installed to the new GOPATH.

The `go.mod` file fixed it. The solution is to run `go mod init foo/bar`. This is the fix no matter if the GOPATH env var is set or not. Do you think this can be added to documentation?

**Comment by bhcleek** [comment]
GOPATH mode is described in the Go documentation: https://godoc.org/cmd/go#hdr-Preliminary_module_support. 

Because your code wasn't within `$GOPATH/src` and also didn't have a `go.mod` file, `gopls` didn't know how to resolve anything in your project.

This is just how Go works generally. If you want to submit some clarifying docs in a PR for vim-go, I'll happily review.

**Comment by MaMrEzO** [comment]
I`d just found [Vim as GO IDE](https://octetz.com/docs/2019/2019-04-24-vim-as-a-go-ide/#prerequisites) with this configuration that used "neoclide/coc.nvim" plugim, I got a very fast Completion and even a very nice parameter hints setup now...

**Comment by gun1x** [comment]
> I`d just found [Vim as GO IDE](https://octetz.com/docs/2019/2019-04-24-vim-as-a-go-ide/#prerequisites) with this configuration that used "neoclide/coc.nvim" plugim, I got a very fast Completion and even a very nice parameter hints setup now...

This looks a bit excessive, but if you want to use this setup, good for you.

I am getting vim-go [from aur](https://aur.archlinux.org/packages/vim-go/) and it just works. I also have this `.vimrc` for some stuff that should be default if you ask me:
```
let g:go_auto_sameids = 1
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_trailing_whitespace_error = 0
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_parameters = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1
let g:go_fmt_experimental = 1
let g:go_metalinter_autosave=1
let g:go_metalinter_autosave_enabled=['golint', 'govet']
```

btw, I use Arch. I mean in case you didn't figure I am using Arch because I specified AUR, I just wanted to let you know that I use Arch.

**Comment by MaMrEzO** [comment]
> > I`d just found [Vim as GO IDE](https://octetz.com/docs/2019/2019-04-24-vim-as-a-go-ide/#prerequisites) with this configuration that used "neoclide/coc.nvim" plugim, I got a very fast Completion and even a very nice parameter hints setup now...
> 
> This looks a bit excessive, but if you want to use this setup, good for you.
> 
> I am getting vim-go [from aur](https://aur.archlinux.org/packages/vim-go/) and it just works. I also have this `.vimrc` for some stuff that should be default if you ask me:
> 
> ```
> let g:go_auto_sameids = 1
> let g:go_highlight_array_whitespace_error = 1
> let g:go_highlight_chan_whitespace_error = 1
> let g:go_highlight_extra_types = 1
> let g:go_highlight_space_tab_error = 1
> let g:go_highlight_trailing_whitespace_error = 0
> let g:go_highlight_operators = 1
> let g:go_highlight_functions = 1
> let g:go_highlight_function_parameters = 1
> let g:go_highlight_function_calls = 1
> let g:go_highlight_types = 1
> let g:go_highlight_fields = 1
> let g:go_highlight_build_constraints = 1
> let g:go_highlight_generate_tags = 1
> let g:go_highlight_string_spellcheck = 1
> let g:go_highlight_format_strings = 1
> let g:go_highlight_variable_declarations = 1
> let g:go_highlight_variable_assignments = 1
> let g:go_fmt_experimental = 1
> let g:go_metalinter_autosave=1
> let g:go_metalinter_autosave_enabled=['golint', 'govet']
> ```
> 
> btw, I use Arch. I mean in case you didn't figure I am using Arch because I specified AUR, I just wanted to let you know that I use Arch.

I see, glad to see you, my Arch mate :D
WOW, I didn't know there is an AUR just for vim go!
I got to take a try, Thanks for let me know about that.
