### ISSUE TITLE
Completion no longer shows function signature in preview/quickfix

### ISSUE THREAD

**Issue by walkert** [fatih/vim-go#2265]
### What did you do? (required: The issue will be **closed** when not provided)
First - massive thanks for keeping this up!!

While moving through the completion list, the preview window is no longer opened to show the function signature (including return types).

To reproduce, edit a go file with fmt imported. Type fmt. then use omnifunc to get the completion list.
### What did you expect to happen?
In the version I was previously using (66d06f380ef3cbced060b4d514413762a4438fb4) cycling through the available options would open a preview in the quickfix box which included the signature _and_ return types.

### What happened instead?
The current version (3e9a29279627d1ac50a855376b5da4dc0f809356) just shows the signature in the completion list but no return types and _does not_ open a preview window.

#### vim-go version:
```
 git show                                                   ✘  1038 | 3:28
commit 3e9a29279627d1ac50a855376b5da4dc0f809356
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Fri Apr 26 18:23:03 2019 -0700

    update CHANGELOG.md for #2244
```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
filetype plugin indent on
let g:go_echo_go_info = 1
set noshowmode

</pre></details>

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707
Modified by pkg-vim-maintainers@lists.alioth.debian.org
```

####  Go version (`go version`):
```
go version go1.11 linux/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rando/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rando/Go"
GOPROXY=""
GORACE=""
GOROOT="/home/rando/Binaries/go"
GOTMPDIR=""
GOTOOLDIR="/home/rando/Binaries/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build556591426=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by bhcleek** [comment]
Thank you for the bug report. Good catch.

**Comment by walkert** [comment]
Thanks for the prompt fix Billie!
