### ISSUE TITLE
feature: GoDef on packages opens the package source

### ISSUE THREAD

**Issue by preslavmihaylov** [fatih/vim-go#2270]
### What did you do? (required: The issue will be **closed** when not provided)
Started with the following code:
```
package main

import "errors"
import "fmt"

func main() {
	fmt.Println("vim-go")
}

```

I hovered over `import "errors"` and typed :GoDef.

### What did you expect to happen?
Open the errors.go source file and point to the `package errors` line.
OR
open a preview window with the source files which are part of this package and choose which one to open.

### What happened instead?
Received an error:
`vim-go: [searching declaration] FAIL`

#### vim-go version:
https://github.com/fatih/vim-go/tree/3e9a29279627d1ac50a855376b5da4dc0f809356

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
""" -------------------- vim-go -------------------------
" all errors are shown in the quickfix window
let g:go_list_type = "quickfix"

" automatically add import paths when saving file
"let g:go_fmt_command = "goimports"

" enable syntax highlighting
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1

" enable go metalinter
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave = 1

" automatically show GoInfo output
" let g:go_auto_type_info = 1

" automatically highlight variable your cursor is on
let g:go_auto_sameids = 1

" adjust quickfix window height
let g:go_list_height = 8

let g:go_term_mode = "split above"
</pre></details>

[link to full vimrc](https://github.com/preslavmihaylov/dotfiles/blob/master/vimrc)

#### Vim version (first three lines from `:version`):
NVIM v0.3.4

####  Go version (`go version`):
1.11.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pmihaylov/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pmihaylov/programming/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build501012645=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
There's nothing that vim-go can do about this. But there is an ongoing discussion in the go tools group about how it can be handled by `gopls`. Once `gopls` handles it, vim-go will get it for free.
