### ISSUE TITLE
"invalid JSON-RPC header" errors when using gopls for GoDef

### ISSUE THREAD

**Issue by entombedvirus** [fatih/vim-go#2274]
### What did you do? (required: The issue will be **closed** when not provided)

After spending a lot of time trying to root cause this error, I am
    settling for a change that seems to work around the issue but I am unsure as to
    why it was breaking in the first place.

I was getting the "invalid JSON-RPC header" errors pretty frequently
    although I can't find a reliable repro. After opening neovim, jumping
    to def (C-]) and back again (C-t) repeatedly would trigger the bug 3 / 5
    times. If it didn't trigger after a few tries, restarting neovim and
    trying again seems to repro.

I debugged it down to the s:neocb call back not calling the passed in
    callback with all the elements in a:data. Though the root cause as to
    why, I am still unable to figure out.

However, in "raw" mode, s:neocb can be simplified to a single callback
    invocation with join(...) instead of calling it inside a while loop. For some reason, this seems to avoid the bug.

### What did you expect to happen?
GoDef to not throw an exception

### What happened instead?
"invalid JSON-RPC header" exception was being thrown
![image](https://user-images.githubusercontent.com/1622/57205741-82edf380-6f75-11e9-81af-560a9cdb1d29.png)

`:echo go#config#LspLog()` gives:
<detail>
<pre>
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}', '<-
Content-Length: 185

{"jsonrpc":"2.0","result":[{"uri":"file:///...snip...","range":{"start":{"line":24,"character":1},"end":{"line":24,"character":19}}}],"id":41}',  '<-
Content-Length: 199
Content-Length: 182

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}Content-Length: 1']
</pre>
<detail>

you can see where two "Content-Length" lines are right next to each other, which is happening because `s:neocb` never called the callback with the actual body that corresponds to `Content-Length: 199` and instead calls with a new header + body section. The parsing remains messed up after this point because it cannot be successfully `json_decode`-ed.

### Configuration (**MUST** fill this out):
        let g:go_def_mode = 'gopls'
        let g:go_info_mode = 'gopls'
        let g:go_auto_sameids = 1
        let g:go_auto_type_info = 1

#### vim-go version:
3e9a29279627d1ac50a855376b5da4dc0f809356

#### Vim version (first three lines from `:version`):
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5

####  Go version (`go version`):
go version go1.12.4 linux/amd64

#### Workaround patch

```
diff --git a/autoload/go/job.vim b/autoload/go/job.vim
index 328572e..473d975 100644
--- a/autoload/go/job.vim
+++ b/autoload/go/job.vim
@@ -489,6 +489,11 @@ function! s:neocb(mode, ch, buf, data, callback)
   "     for every list you receive in a callback, all items except the first
   "     represent newlines.
 
+  if a:mode ==# 'raw'
+    call a:callback(a:ch, join(a:data, "\n"))
+    return ''
+  endif
+
   let l:buf = ''
 
   " A single empty string means EOF was reached. The first item will never be
```

Please let me know how I can help debug the problem to a root cause. For now, I am going to move on with my workaround since it already ate up more time than I was planning on spending on it.

**Comment by bhcleek** [comment]
Hmm.. I'm not sure why you're experiencing that problem. The work around you have shouldn't be necessary, and I have some concern that it might be problematic in other ways, because the way neovim handles newlines is odd and presents a number of subtle edge cases.

I'll take a close look at this soon to see if I can duplicate and provide a fix.

**Comment by bhcleek** [comment]
Thank you for the detailed report and trying to fix the problem. I've tried to duplicate it, but haven't been successful. If you can duplicate it reliably, you could help me by apply this patch (undo your patch first!):

```
diff --git a/autoload/go/job.vim b/autoload/go/job.vim
index 328572e..fed4caf 100644
--- a/autoload/go/job.vim
+++ b/autoload/go/job.vim
@@ -422,6 +422,9 @@ function! s:callback2on_stderr(mode, ch, data, event) dict
 endfunction
 
 function! s:on_stdout(mode, ch, data, event) dict
+  let g:go_job_neocb_log = get(g:, 'go_job_neocb_log', [])
+  call add(g:go_job_neocb_log, {'buf': self.stdout_buf, 'data': deepcopy(a:data)})
+
   let self.stdout_buf = s:neocb(a:mode, a:ch, self.stdout_buf, a:data, self.out_cb)
 endfunction
 
```

After applying the patch, duplicate the problem. It's going to generate a lot of logs, so please stop as soon as you get the error.

After you get the error, open a new window window (`:enew`) and run `"=g:go_job_neocb_log<Enter>p` to put the contents of `g:go_job_neocb_log` as if it were a register. Then copy that to your clipboard and paste the results here. I'll analyze those to try to get to the bottom of where `s:neocb` is faulty.

**Comment by entombedvirus** [comment]
Yep, I will do this today.

I should’ve also mentioned that I tried doing the equivalent of your patch, but higher up: I basically wrote a wrapper script for gopls that writes both its stdin and stdout to temp files and what I found was that the stdout stream from gopls is correct: there are no “Content-Length: X” headers next to each other without a missing body. 

Can’t recall if I did the same thing on s:on_stdout, so I’ll get those to you.

**Comment by entombedvirus** [comment]
`g:go_job_neocb_log`:

<pre>
{'buf': '', 'data': ['Content-Length: 459
', '
', '{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":1},"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"typeDefinitionProvider":true},"custom":null},"id":1}']}
{'buf': '', 'data': ['Content-Length: 170
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 186
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: set content for file:///...snip..."}}Content-Length: 200
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}Content-Length: 199
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: going to get diagnostics for file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 163
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"didChange: file:///...snip..."}}Content-Length: 170
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 182
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 186
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: set content for file:///...snip..."}}Content-Length: 200
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}Content-Length: 199
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: going to get diagnostics for file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 182
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 184
', '
', '{"jsonrpc":"2.0","result":[{"uri":"file:///...snip...","range":{"start":{"line":24,"character":1},"end":{"line":24,"character":19}}}],"id":2}']}
{'buf': '', 'data': ['Content-Length: 163
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"didChange: file:///...snip..."}}Content-Length: 170
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: file:///...snip..."}}Content-Length: 186
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: set content for file:///...snip..."}}Content-Length: 200
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 184
', '
', '{"jsonrpc":"2.0","result":[{"uri":"file:///...snip...","range":{"start":{"line":24,"character":1},"end":{"line":24,"character":19}}}],"id":3}Content-Length: 199
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: going to get diagnostics for file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 182
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}Content-Length: 163
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"didChange: file:///...snip..."}}Content-Length: 170
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: file:///...snip..."}}Content-Length: 186
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: set content for file:///...snip..."}}Content-Length: 200
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 184
', '
', '{"jsonrpc":"2.0","result":[{"uri":"file:///...snip...","range":{"start":{"line":24,"character":1},"end":{"line":24,"character":19}}}],"id":4}Content-Length: 199
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: going to get diagnostics for file:///...snip..."}}Content-Length: 182
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}Content-Length: 188
', '
', '{"jsonrpc":"2.0","result":{"contents":{"kind":"plaintext","value":"var AllEventsTimeSlice *TimeSlice"},"range":{"start":{"line":24,"character":1},"end":{"line":24,"character":19}}},"id":5}Content-Length: 158
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: file:///...snip..."}}Content-Length: 174
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: set content for file:///...snip..."}}Content-Length: 188
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}Content-Length: 187
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: going to get diagnostics for file:///...snip..."}}']}
{'buf': '', 'data': ['Content-Length: 170
', '
', '{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}']}
</pre>

`g:go_lsp_log:`

<pre>
->
Content-Length: 223



{"method": "initialize", "jsonrpc": "2.0", "id": 1, "params": {"rootUri": "file:///...snip...", "capabilities": {"workspace": {}, "textDocument": {"hover": {"contentFormat": ["plaintext"]}}}, "processId": 1299}}
<-
Content-Length: 459



{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":1},"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"typeDefinitionProvider":true},"custom":null},"id":1}
->
Content-Length: 28655



{"method": "textDocument/didOpen", "jsonrpc": "2.0", "params": {"textDocument": {"uri": "file:///...snip...", "languageId": "go", "text": "...snip..."}}}
<-
Content-Length: 170



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: file:///...snip..."}}
<-
Content-Length: 186



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: set content for file:///...snip..."}}
<-
Content-Length: 200



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}
<-
Content-Length: 199



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: going to get diagnostics for file:///...snip..."}}
->
Content-Length: 28659



{"method": "textDocument/didChange", "jsonrpc": "2.0", "params": {"contentChanges": [{"text": "...snip..."}], "textDocument": {"uri": "file:///...snip..."}}}
->
Content-Length: 222



{"method": "textDocument/definition", "jsonrpc": "2.0", "id": 2, "params": {"textDocument": {"uri": "file:///...snip..."}, "position": {"character": 40, "line": 635}}}
<-
Content-Length: 163



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"didChange: file:///...snip..."}}
<-
Content-Length: 170



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: file:///...snip..."}}
->
Content-Length: 28659



{"method": "textDocument/didChange", "jsonrpc": "2.0", "params": {"contentChanges": [{"text": "...snip..."}], "textDocument": {"uri": "file:///...snip..."}}}
->
Content-Length: 222



{"method": "textDocument/definition", "jsonrpc": "2.0", "id": 3, "params": {"textDocument": {"uri": "file:///...snip..."}, "position": {"character": 40, "line": 635}}}
->
Content-Length: 28659



{"method": "textDocument/didChange", "jsonrpc": "2.0", "params": {"contentChanges": [{"text": "...snip..."}], "textDocument": {"uri": "file:///...snip..."}}}
->
Content-Length: 222



{"method": "textDocument/definition", "jsonrpc": "2.0", "id": 4, "params": {"textDocument": {"uri": "file:///...snip..."}, "position": {"character": 40, "line": 635}}}
<-
Content-Length: 182



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}
<-
Content-Length: 186



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: set content for file:///...snip..."}}
<-
Content-Length: 200



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}
<-
Content-Length: 199



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: going to get diagnostics for file:///...snip..."}}
<-
Content-Length: 182



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}
<-
Content-Length: 184



{"jsonrpc":"2.0","result":[{"uri":"file:///...snip...","range":{"start":{"line":24,"character":1},"end":{"line":24,"character":19}}}],"id":2}
->
Content-Length: 203



{"method": "textDocument/hover", "jsonrpc": "2.0", "id": 5, "params": {"textDocument": {"uri": "file:///...snip..."}, "position": {"character": 1, "line": 24}}}
<-
Content-Length: 163



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"didChange: file:///...snip..."}}
<-
Content-Length: 170



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: file:///...snip..."}}
<-
Content-Length: 186



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: set content for file:///...snip..."}}
<-
Content-Length: 200



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"cacheAndDiagnose: returned from diagnostics for file:///...snip..."}}
<-
Content-Length: 184



{"jsonrpc":"2.0","result":[{"uri":"file:///...snip...","range":{"start":{"line":24,"character":1},"end":{"line":24,"character":19}}}],"id":3}
->
Content-Length: 7554



{"method": "textDocument/didOpen", "jsonrpc": "2.0", "params": {"textDocument": {"uri": "file:///...snip...", "languageId": "go", "text": "...snip..."}}}
<-
Content-Length: 199

Content-Length: 182



{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"running `go vet` analyses for file:///...snip..."}}Content-Length: 1
p

</pre>

**Comment by entombedvirus** [comment]
My hypothesis is that while `s:neocb` is in the middle of looping through elements in `l:data` it is interrupted somehow and it never gets a chance to call `a:callback` with the rest of the elements in `l:data`.

I don't know enough about neovim to know whether something external can interrupt that while loop or if it's just a garden variety error that causes the while loop to stop early. The simplest explanation is the latter, but there is nothing in the status bar or in `:messages`

**Comment by bhcleek** [comment]
Thank you for that. I'd like to run this input through some tests; can you run it again and leave the file URLs unaltered if it's not a security or privacy issue for you?

**Comment by entombedvirus** [comment]
I can PM you the un-altered logs from my earliest post if you still need it after reading the rest of this post.

I think I made some more head way in to root causing the problem. I ran neovim with `nvim -V15` and writing the (very verbose) log to a file. Then in that large file, I traced the execution of vim-go code and it's interaction with gopls. I think what is happening is that, under a specific condition, it's possible for the JSON-RPC response stream parsing code in vim-go to see "lines" in a different order than what gopls emitted.

This is the sequence that I observed in the verbose log file:

1. neovim starts, open a go file, vim-go starts gopls and does handshake
2. I trigger GoDef on a symbol, which sends a request to gopls
3. gopls writes two responses: one which contains the location of the symbol and another that just a diagnostic message and vim-go code currently parses, but ignores.
4. the response from gopls is passed to `s:neocb` as a list that has the following shape:
<pre>
["Content-Length: 184\r", "\r", {"jsonrpc":"2.0","result":[{"uri":"file:///home/rravi-2/analytics/go/src/arb/pb/manifest_util.go","range":{"start":{"line":24,"character":1},"end":{"line":24,"character":19}}}],"id":4}Content-Length: 199\r", "\r", <another response that is 199 bytes long>]
</pre>
5. the while loop in `s:neocb` attempts a `call a:callback(l:msg)` with a newline appended at the end  for each element in the previous step (except for the last one).
6. during the execution of `a:callback` for the third element (the one with the location of the GoDef symbol), a new go file is opened, more requests to gopls are made, numerous autocommands are triggered and one such autocommand belongs to a different vim plugin called gitgutter. In that code, it calls [`sleep 5m`](https://github.com/airblade/vim-gitgutter/blob/1d422b9f98194e38bc56e54192c9bc66d95c21f1/autoload/gitgutter/diff.vim#L72). 
7. This is where the bug manifests: the sleep call prompts neovim to process more output from gopls, but it does so before the while loop in (4) got a chance to make `call a:callback(l:msg)` calls for the last two elements.

This also explains why my workaround avoids the issue: if we send everything `s:neocb` gets to `a:callback` in a single call to `a:callback`, then it's impossible for a sleep call (or anything else) inject stuff in the middle.

I have a 38M log file that essentially captures this sequence that I can send to you. I don't want to attach it to the ticket because it has details specific to my work setup.

**Comment by bhcleek** [comment]
Thanks for doing more analysis and for the explanation. That makes good sense to me.

I'll submit a PR to get this fixed as soon as I can.

**Comment by bhcleek** [comment]
I realized that even if I apply something like your patch, if your explanation is correct (and I have no reason to doubt it), then there is still a really nasty race condition present, though perhaps less likely to be triggered.

Let's walk it through assuming that `raw` mode joins all the lines together and calls the callback.
1. The callback takes the string and appends it to what it has buffered. By definition, that's not an atomic operation.
2. Two threads are calling the callback concurrently because Neovim apparently is running multiple threads for processing the VimL
3. Each invocation of the callback could be on the same logical line that's concatenating the string data to the existing json.

Since concatenation isn't atomic, the resulting string could still end up seriously munged up. 🤔 Do you see any flaws in this analysis that could falsify it?

This seems like a larger issue for Neovim generally to me.

**Comment by entombedvirus** [comment]
I was thinking about the same thing :) 

Specifically, what is *actually* safe to do if my understanding of what’s happening is correct? 

In most single-threaded event loop systems (like python), a given “thread” runs continuously until it hits a point in code which “yields” control. Typically, these are points where IO happens. In such a situation, the runtime suspends the “thread” that hit the yield point, searches for another “thread” that is runnable and jumps to that instead. In this model, code is still single-threaded in the sense that only part of the code is executing at any given time, but it is concurrent in the sense that an execution context can be suspended and then resumed. 

In this model, the only thing that is guaranteed to run sequentially and without interruption is code between these yield points.

If neovim’s (or maybe even Vim’s) Vimscript implementation follows that model, then callbacks registered via the async job api are separate “threads” that can be paused and resumed at specific points. But only one of them will be running at any given time. Furthermore, it looks like in neovim (maybe also in vim?), the “sleep” call is such a yield point. 

So going by that understanding, as long as there are no “sleep” calls or any other yield points between receiving the a:data lines and appending it to a flattened buffer, it should be safe. 

I tried doing some research in to whether neovims Vimscript engine works this way, but I was unable to find anything conclusive.

**Comment by bhcleek** [comment]
It's not conclusive, but based on how vim-go's tests work (there's several that have spin loops), I'm relatively confident that it must work the way we've discussed.

The good news is that this prompted me to do some research into how to handle these situations with Vim, and I believe I have a solution by using `lockvar` and `unlockvar` to manage the concurrency possible in `s:neocb`.

**Comment by bhcleek** [comment]
After talking this through on neovim/neovim#10018, I'm relatively confident that there's no good solution for this on the vim-go side: all the solutions that I can imagine on the vim-go side lack the 100% guarantee that we need. From what I can tell, the right solution is for gitgutter to use `timer_start` instead of `sleep`.

I'll leave this issue open for a couple of more days to give any interested parties an opportunity to respond.

**Comment by entombedvirus** [comment]
Thank you for following up with both neovim and gitgutter maintainers. 🙏🏾

The respective linked threads makes sense and if neovim can add a patch such that it can guarantee strictly sequential execution of async callbacks for a given channel, that would fix the problem. 

if gitgutter switches to using something other than sleep, that seems more robust for the future as well. 

Thnx again to all the maintainers involved! 🙏🏾
