### ISSUE TITLE
GoDocBrowser not linking to the correct page anchor

### ISSUE THREAD

**Issue by marcov** [fatih/vim-go#2275]
TL;DR: `GoDocBrowser` does not link to the correct page anchor for methods.

Given the following  code, place cursor on `Match` and then run `:GoDocBrowser`.
- Obtained link: [`https://godoc.org/regexp#FindString`](https://godoc.org/regexp#FindString)
- Expected link: [`https://godoc.org/regexp#Regexp.FindString`](https://godoc.org/regexp#Regexp.FindString)

```go
package main

import (
	"fmt"
	"regexp"
)

func main() {
	re := regexp.MustCompile(`(vim-go)`)
	vimgo := re.FindString("vim-go is great")
	fmt.Println(vimgo)
}
```

**Comment by bhcleek** [comment]
Do you have `gogetdoc` installed?
