### ISSUE TITLE
Post-hook failing in vim-plug

### ISSUE THREAD

**Issue by tutabeier** [fatih/vim-go#2278]
### What did you do? (required: The issue will be **closed** when not provided)
Installed Vim-Go on Nvim.

### What did you expect to happen?
Vim-go is installed with no issues.

### What happened instead?
vim-plug throws an error.

### Configuration (**MUST** fill this out):
[.vimrc](https://github.com/tutabeier/dotfiles/blob/master/roles/vim/files/vimrc#L103)
[vim-go configs](https://github.com/tutabeier/dotfiles/blob/master/roles/vim/files/config/go.vim)
[vim-plug plugins list](https://github.com/tutabeier/dotfiles/blob/master/roles/vim/files/plugins.vim#L8)

#### vim-go version:
latest

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['golint']
</pre></details>

#### Vim version (first three lines from `:version`):
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
```

####  Go version (`go version`):
`go version go1.12 darwin/amd64`

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/<USER>/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/<USER>/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y7/d9mxr9110j79f3c_gj1jm2qr0000gn/T/go-build748971058=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

![Screenshot 2019-05-07 at 11 09 42](https://user-images.githubusercontent.com/607692/57288381-a4f08e80-70b9-11e9-9513-72ef722128ac.png)
![Screenshot 2019-05-07 at 11 08 01](https://user-images.githubusercontent.com/607692/57288382-a4f08e80-70b9-11e9-8766-05b70b0976c6.png)

**Comment by bhcleek** [comment]
Your update hook seems to only run` :GoUpdateBinaries`. I've run that on my machine successfully. Can you run it manually successfully?

**Comment by tutabeier** [comment]
I've added the wrong name, is not Vundle, it's `vim-plug`.

When I run the command `:GoUpdateBinarie` from Neovim it runs correctly, but I still see the issues.

**Comment by tutabeier** [comment]
The issue is not with vim-go, it is due the `set list listchars=eol:$` I've added.

Sorry about it. Closing it.
