### ISSUE TITLE
Feature Request: Add option to globally disable gopls

### ISSUE THREAD

**Issue by wpaulino** [fatih/vim-go#2283]
This is useful for users who already have a language client set up to interact with `gopls`. `vim-go` is still useful for many of its other great features, so this would allow users to not have two instances of `gopls` consuming resources.

**Comment by bhcleek** [comment]
`gopls` is going to be necessary for many vim-go features; it's used for more than just completion; I don't foresee us adding a way to completely disable it.

**Comment by cherrot** [comment]
So is there a way to disable `vim-go`'s autocompletion feature?

**Comment by cherrot** [comment]
> So is there a way to disable `vim-go`'s autocompletion feature?

This should work. Sorry for bothering:
```vim
let g:go_code_completion_enabled = 0
```

**Comment by dhulihan** [comment]
in certain cases, the latest version of `gopls` (v0.1.3) can eat up a lot of CPU on OSX. It's not uncommon to work on several go codebases at a time in vim. When each vim session starts its own `gopls` (started by `vim-go`), you're going to start burning a LOT of CPU. 

Here's an example where I have 10 vim sessions open and 10 corresponding `gopls` processes:

![Screen Shot 2019-08-22 at 11 15 29 AM](https://user-images.githubusercontent.com/519728/63535545-effaaa00-c4ce-11e9-9743-4138e4561e6f.png)
