### ISSUE TITLE
Use gopls as default go_info_mode

### ISSUE THREAD

**Issue by pohzipohzi** [fatih/vim-go#2284]
I was running into some issues with `:GoInfo` until I set `go_info_mode` to `gopls`.

The doc for `go_info_mode` says:

```
By default `gocode` is being used as it's the fastest option. But one might also use
`gopls` or `guru` as they cover more cases and are more accurate
```

Is this still the case? Running `:GoInfo` on my machine is almost instantaneous with `gopls`. Perhaps the default value could be changed

**Comment by bhcleek** [comment]
It is still the case. The default will be changed soon.
