### ISSUE TITLE
GoInstallBinaries does not work and breaks $PATH on windows

### ISSUE THREAD

**Issue by glebtv** [fatih/vim-go#2286]
### What did you do? (required: The issue will be **closed** when not provided)

```
:echo executable("go.exe")
1
:GoInstallBinaries
# Errors:
# vim-go: could not find 'go'. Run :GoInstallBinaries to fix it

:echo executable("go.exe")
0
```

### What did you expect to happen?
Go tools binaries are installed

### What happened instead?
Fails

### Configuration (**MUST** fill this out):
Windows 10 x64
Dein and nothing else

#### vim-go version:
I have bisected it and the commit that breaks it seems to be https://github.com/fatih/vim-go/pull/2255
https://github.com/fatih/vim-go/commit/dd882abf345f04bef4e6318e90cc3c7078f78825

This works fine on vim-go v1.19 and is broken in vim-go v1.20
This seems to be similar to unresolved #2257

Workaround for dein:
```
call dein#add('fatih/vim-go', { 'rev': 'v1.19' })
" or
call dein#add('fatih/vim-go', { 'rev': '45cdcc10aa81a61c0c5bfb2059e844e9dd10d176' })
```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set runtimepath+=~/.nvim/repos/github.com/Shougo/dein.vim
set runtimepath+=~/.nvim/

if dein#load_state('~/.nvim/')
  call dein#begin('~/.nvim/')
  " Let dein manage dein
  " Required:
  call dein#add('~/.nvim/repos/github.com/Shougo/dein.vim')
endif

call dein#add('fatih/vim-go')
</pre></details>

#### Vim version (first three lines from `:version`):
Neovim 0.4.0 and 0.3.5

####  Go version (`go version`):
1.12.5

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Gleb\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Gleb\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Gleb\AppData\Local\Temp\go-build422699794=/tmp/go-build -gno-record-gcc-switches
</pre></details>

**Comment by bhcleek** [comment]
> I have bisected it and the commit that breaks it seems to be #2255
> dd882ab
> 
> This works fine on vim-go v1.19 and is broken in vim-go v1.20

Can you clarify whether you see this problem in the v1.20 release or whether you only see it in dd882ab and later?

**Comment by glebtv** [comment]
In dd882ab and later. 45cdcc10aa81a61c0c5bfb2059e844e9dd10d176 works fine for me.

**Comment by aidanbrumsickle** [comment]
The problem is because the implementation of `go#util#SetEnv` evaluates Windows paths inside double quotes, which interprets the backslashes as escape chars. See my comment: https://github.com/fatih/vim-go/commit/1237fa0e19460d0b3ed2fb8fa566659b2154b5fb#r33550571

I'm new to Github development so apologies for not just adding a pull request right away but I have to get set up for that.

**Comment by bhcleek** [comment]
Thanks, @aidanbrumsickle ! That's really helpful.

I'll put up a PR soon; would be able to test it?

**Comment by aidanbrumsickle** [comment]
Sure! I'll keep an eye out for it.
