### ISSUE TITLE
Question: Is autocomplete supposed to work with cgo(import "C") or not

### ISSUE THREAD

**Issue by chew351** [fatih/vim-go#2293]
### What did you do? (required: The issue will be **closed** when not provided)
when go file import "C"
autocomplete can't work

import "C"
autocomplete can't work

remove import "C"
autocomplete can work

### What did you expect to happen?

autocomplete can work when go file import "C"

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
vim-go is dependent on gopls for completion. Please follow https://github.com/golang/go/issues/31561.

**Comment by chew351** [comment]
Thank you Billie Cleek!




At 2019-05-16 11:09:38, "Billie Cleek" <notifications@github.com> wrote:


vim-go is dependent on gopls for completion. Please follow golang/go#31561.
