### ISSUE TITLE
completion doesn't work in files that aren't saved to disk

### ISSUE THREAD

**Issue by smartding** [fatih/vim-go#2294]
### What did you do? (required: The issue will be **closed** when not provided)
In neovim, autocompletion doesn't work on this simple go source file

```golang
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
	fmt.{cursor here}
}
```
My cursor is after "fmt.", then I pressed tab to trigger autocompletion.

### What did you expect to happen?

A pop up should show the functions in fmt package

### What happened instead?
no pop up window at all, only error messages:

```
vim-go: [completion] FAIL
Error detected while processing function go#complete#Complete[14]..<SNR>98_on_stdout[1]..<SNR>98_neocb[58]..272[23]..<SNR>96_completionErrorHandler:
line    1:
E119: Not enough arguments for function: <SNR>135_handler
Error detected while processing function go#complete#Complete[14]..<SNR>98_on_stdout[1]..<SNR>98_neocb:
line   58:
E170: Missing :endwhile
Error detected while processing function go#complete#Complete:
line   14:
E170: Missing :endwhile
Pattern not found
```
I tried GoUpdateBinaries, still the same error

#### vim-go version:
latest version, d2f1bbe458d8c7c3154ed113c3768bd84451f872

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
Plug 'mileszs/ack.vim'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'airblade/vim-gitgutter'
Plug 'ekalinin/Dockerfile.vim', {'for' : 'Dockerfile'}
Plug 'SirVer/ultisnips'
Plug 'tpope/vim-commentary'
Plug 'Raimondi/delimitMate'
Plug 'ervandew/supertab'
Plug 'elzr/vim-json', {'for' : 'json'}
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
" Plug 'zchee/deoplete-go', { 'do': 'make'}

call plug#end()

" ==================== deopete ====================
let g:deoplete#enable_at_startup = 0
set completeopt-=preview
"lazy loading: https://github.com/Shougo/deoplete.nvim/issues/780
autocmd BufNewFile,BufRead *.go call deoplete#enable()
" ==================== deoplete-go ====================
let g:deoplete#sources#go#sort_class  = ['package', 'func', 'type', 'var', 'const']
call deoplete#custom#option('omni_patterns', { 'go': '[^. *\t]\.\w*' })

</pre></details>

#### Vim version (first three lines from `:version`):

neovim 0.3.5

####  Go version (`go version`):
1.11.2
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN="/Users/smart/go/bin"
GOCACHE="/Users/smart/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/smart/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wk/n4jvtwkx5kdd6fyl57lqwmbr0000gn/T/go-build616459688=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by smartding** [comment]
I tested this problem on vim8.1, got similar error messages:
```
vim-go: [completion] FAIL
Error detected while processing function go#complete#Complete[14]..292[23]..<SNR>110_completionErrorHandler:
line    1:
E119: Not enough arguments for function: <SNR>132_handler
Error detected while processing function go#complete#Complete:
line   14:
E170: Missing :endwhile
Pattern not found
```

**Comment by bhcleek** [comment]
The only way I can trigger the errors you're seeing is if the file hasn't been saved yet. Is that true for you, too?

**Comment by bhcleek** [comment]
Alghouth #2296 will solve this, I'm not sure I'm going to merge it given https://github.com/golang/go/issues/31522.

**Comment by smartding** [comment]
> The only way I can trigger the errors you're seeing is if the file hasn't been saved yet. Is that true for you, too?

yes, I triggered this error while I was in the middle of coding, so the file isn't saved yet.

**Comment by bhcleek** [comment]
I'll leave this open for a bit. While we consider merging #2296 and while watching #31522, but for now please just save the file before trying to do completion on it.

**Comment by smartding** [comment]
> I'll leave this open for a bit while we consider merging #2296 and while watching #31522, but for now please just save the file before trying to do completion on it.

I tried again, and encountered the same error on a saved file, such as the one below:

```golang
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
	fmt.{cursor here}
}
```
I open the file, file content as shown above, move the cursor after "fmt.", because I'm using deoplete, it immediately triggered autocompletion, and the same error occur.

**Comment by bhcleek** [comment]
Can you duplicate that error using a file that's saved to disk and without any other plugins enabled?

**Comment by smartding** [comment]
> Can you duplicate that error using a file that's saved to disk and without any other plugins enabled?

yes, I disabled all my plugins except vim-go, still the same error.

my vimrc now looks like this:
```vim
call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go'

call plug#end()

"=====================================================
""===================== VIM SETTINGS =================

set nocompatible                 " enabled by default in neovim, but not in vim8
filetype plugin indent on        " configure vim to load plugins

set backspace=indent,eol,start   " Makes backspace key more powerful, required by delimitMate in vim8, not in neovim
set incsearch                    " incremental search, enabled by default in neovim, but not in vim8
set hlsearch                     " highlight search results, enabled by default in neovim, but not vim8
set ttyfast
set mouse=a                      " enable mouse
set number                       " show line number
set relativenumber               " show relative number
set encoding=utf-8               " Set default encoding to UTF-8
set hidden                       " so that we can switch to another file even if the currenty one is modified
set nobackup                     " no backup needed, git takes care of that
set noswapfile                   " not swap, they tend to make things messy
set noshowmode                   " use lightline instead for showing mode
set cursorline                   " show current line
set splitright                   " Split vertical windows right to the current windows
set splitbelow                   " Split horizontal windows below to the current windows
set ignorecase                   " Search case insensitive, also affects autocompletion
set smartcase                    " be smart when searching, always set after ignorecase, won't work alone
set wildmenu                     " candidate show in a statusline menu, default in neovim, not in vim8
set updatetime=300
set pumheight=10                 " ompletion window max size
set lazyredraw                   " seems to reduce lag when scrolling
set list listchars=tab:\|\       " set indent line for tab spaced programming language
set pastetoggle=<F1>             " toggle paste mode with f1
```

Then I open the following source file:
```golang
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
	fmt.{cursor here}
}
```
move my cursor after "fmt.", enter insert mode, and `<C-x><C-o>` to trigger autocompletion, and got the following error:
```
vim-go: [completion] FAIL
Error detected while processing function go#complete#Complete[14]..<SNR>48_on_stdout[1]..<SNR>48_neocb[58]..4[23]..<SNR>46_completionErrorHandler:
line    1:
E119: Not enough arguments for function: <SNR>53_handler
Error detected while processing function go#complete#Complete[14]..<SNR>48_on_stdout[1]..<SNR>48_neocb:
line   58:
E170: Missing :endwhile
Error detected while processing function go#complete#Complete:
line   14:
E170: Missing :endwhile
Pattern not found
```

**Comment by bhcleek** [comment]
I think you're running into a problem caused by trying to use completion in a file that is neither in a Go module nor in GOPATH. `gopls` doesn't work outside of GOPATH or go module mode.
