### ISSUE TITLE
:GoDocBrowser anchor does not link to a struct when used on a field

### ISSUE THREAD

**Issue by marcov** [fatih/vim-go#2295]
When running `:GoDocBrowser` on a structure field:
- obtained result: the URL is `<pacakage page>#<field name>`
- expected result: the URL should be `<pacakage page>#<struct name>`

`:GoDoc` handles this properly.

**Comment by bhcleek** [comment]
I'm not sure there's a solution to this for vim-go. 🤔  This might need to be solved by `gogetdoc`.
