### ISSUE TITLE
List all implementations of a interface

### ISSUE THREAD

**Issue by xuxinx** [fatih/vim-go#2298]
### What did you do? (required: The issue will be **closed** when not provided)

I have 3 files
- `testvimgo/interface.go`:
```go
package testvimgo

type MyInterface interface {
        add(float64, float64) float64
}
```
- `testvimgo/impl.go`:
```go
package testvimgo

type ImplSamePackage struct{}

func (impl *ImplSamePackage) add(o1, o2 float64) float64 {
        return 1
}
```
- `testvimgo/impl2/impl2.go`:
```go
package impl2

type ImplDifferentPackage struct{}

func (impl *ImplDifferentPackage) add(o1, o2 float64) float64 {
        return 1
}
```
`:GoImplements` when my cursor is at `type MyInterface interface`

### What did you expect to happen?

List both `ImplSamePackage` and `ImplDifferentPackage`

### What happened instead?

Only `ImplSamePackage`
![image](https://user-images.githubusercontent.com/12792855/57961812-0af3d600-7944-11e9-871f-855e2c620e80.png)

#### vim-go version:
head at d2f1bbe458d8c7c3154ed113c3768bd84451f872
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set nocompatible

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
call vundle#end()
filetype plugin indent on
</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 17 2019 12:50:30)
Included patches: 1-1336
Compiled by root@WORKSERVER
####  Go version (`go version`):
go version go1.12.5 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN="/home/xuxin/go/bin"
GOCACHE="/home/xuxin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xuxin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build545013718=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
Set guru scope using `:GoGuruScope`. See `:help go-guru-scope`.

**Comment by xuxinx** [comment]
It works. Thx.
