### ISSUE TITLE
Dont use winfixheigth on horizontal split mode

### ISSUE THREAD

**Issue by pwntester** [fatih/vim-go#2303]
### What did you do? (required: The issue will be **closed** when not provided)

When running GoRun, the new window is configured with `winfixheight` (see: https://github.com/fatih/vim-go/blob/master/autoload/go/term.vim#L37). This is messing with all my window layout.

### What did you expect to happen?
If the new window is opened in an horizontal split, then `winfixwidth` should be used instead.
If the new window is opened in a vertical split, then `winfixheight` is ok to be use.

The `winfix` option should be set depending on the split mode and therefore in:
https://github.com/fatih/vim-go/blob/master/autoload/go/term.vim#L63

### What happened instead?
`winfixwidth` is always used no matter the mode

**Comment by bhcleek** [comment]
Can you provide some reproducible steps to demonstrate the problem you're encountering?

**Comment by bhcleek** [comment]
Feel free to recreate an issue that explains what you're doing and the problems you're actually seeing so we can take action and ensure that the problems are fixed correctly.
