### ISSUE TITLE
golangci-lint with custom config error

### ISSUE THREAD

**Issue by saward** [fatih/vim-go#2305]
### What did you do? (required: The issue will be **closed** when not provided)

Tried to save file when using golinter-ci as linter with custom config.

### What did you expect to happen?

Show linter issues.

### What happened instead?

In vim, see:

```
vim-go: [golangci-lint] FAIL
```

Running the command myself from command line:

```
golangci-lint run --print-issued-lines=false --disable-all --exclude-use-default=false server.go
```

Which results in the message:

```
ERRO Running error: can't combine options --disable-all and --disable gochecknoglobals
```

I've been able to resolve this using:

```
let g:go_metalinter_command='golangci-lint run --print-issued-lines=false'
```

However, I'm not sure if that's the correct way to override, and I'm raising an issue in case there's a change that is worth making to vim-go to better support golangci-lint out of the box when a config file (with disabled items) is present.

### Configuration (**MUST** fill this out):

```
let g:go_metalinter_command='golangci-lint'
```

Separate golang-ci linter config with the following included (.golangci.yml):

```
linters:
  presets:
    - bugs
    - unused
    - style
    - format
  disable:
    - gochecknoglobals
```

#### vim-go version:

Not sure how to check, but I've just run PlugUpdate so whatever is the latest.

#### Vim version (first three lines from `:version`):

Neovim v0.3.4

####  Go version (`go version`):

1.12.4

**Comment by bhcleek** [comment]
What you're doing is the right way to do it given golangci-lint's limitations. Be aware, though, that your command is missing the `--build-tags` option that vim-go adds and also the `--exclude-use-default=use`. In the first case, as long as you don't need to lint files that have build tags and in the second case, as long as you don't care about not seeing some messages that `golint` provides, then you should be fine.
