### ISSUE TITLE
gometalinter with vet not reporting same issues when running the binary manually

### ISSUE THREAD

**Issue by tombell** [fatih/vim-go#2310]
### What did you do? (required: The issue will be **closed** when not provided)

I have `gometalinter` autosave enabled, and `vet` and `golint` as the linters to run:

```viml
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
```

However recently it's not showing errors from `vet`. However I can see these errors if I run `gometalinter` from the command line with the same linters, on the package.

```
▶ gometalinter --disable-all -E vet -E golint ./api/
api/handlers_tracklists.go:53:4:error: unknown field 'Data' in struct literal of type PagedTracklists (vet)
```

### What did you expect to happen?

See the same error reported in Vim in the quickfix window.

### What happened instead?

gometalinter reports success

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```viml
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

filetype plugin indent on

let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
```

#### Vim version (first three lines from `:version`):

```
NVIM v0.3.5
Build type: Release
LuaJIT 2.0.5
```

####  Go version (`go version`):

```
go version go1.12.5 darwin/amd64
```

#### Go environment

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tombell/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tombell/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tombell/Code/memoir/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ds/67274p3j313_xs5y4cfjb59r0000gn/T/go-build726057554=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment]
What file did you save?

**Comment by tombell** [comment]
I had `api/handlers_tracklists.go` open in vim, and that's the one I saved.

**Comment by bhcleek** [comment]
`let g:go_debug=['shell-commands']` will show you the exact command that vim-go is running. Can you do that and then see what you get when you run the same command manually?

**Comment by tombell** [comment]
```
vim-go: job command: ['/Users/tombell/.go/bin/gometalinter', '--disable-all', '--tests', '--enable=vet', '--enable=golint', '/Users/tombell/Code/memoir/api']
```

**Comment by bhcleek** [comment]
Does `:messages` reveal anything helpful?

Does `:GoMetaLinter` show the errors you're expecting to see?

**Comment by bhcleek** [comment]
FYI, the commandline that vim-go executes for gometalinter when autosaving should include a `--include` option, but I don't see that in the commandline you provided 🤔 

What version of vim-go are you using?

**Comment by tombell** [comment]
Sorry, when I saved, the debug message went away instantly, so I can't see what it was showing, so I setup `:GoMetaLinter` to run the same linters, and could copy the command. So I just assumed they were the same.

The output of `:messages` after saving is:

```"api/handlers_tracklists.go" 82L, 1794C
vim-go: job command: ['/Users/tombell/.go/bin/gopls']
vim-go: shell command: '/usr/local/bin/go' 'env' 'GOMOD'
vim-go: shell command: '/usr/local/bin/go' 'list'
vim-go: shell command: '/Users/tombell/.go/bin/goimports' '-w' '-srcdir' 'api/handlers_tracklists.go' '/var/folders/ds/67274p3j313_xs5y4cfjb59r0000gn/T/nvimP7gf6E/3.go'
"api/handlers_tracklists.go" 82L, 1794C written
vim-go: job command: ['/Users/tombell/.go/bin/gometalinter', '--disable-all', '--tests', '--enable=vet', '--enable=golint', '--include
=^handlers_tracklists.go:.*$', '/Users/tombell/Code/memoir/api']
vim-go: [gometalinter] SUCCESS```

And then after I run `:GoMetaLinter`:

```vim-go: job command: ['/Users/tombell/.go/bin/gometalinter', '--disable-all', '--tests', '--enable=vet', '--enable=golint', '--enable=
errcheck', '/Users/tombell/Code/memoir/api']
vim-go: [gometalinter] SUCCESS```

**Comment by tombell** [comment]
I also ran the command with `--include` on the command line, and that didn't return any errors, when I omitted the `--include` it did.

**Comment by tombell** [comment]
```
memoir (master) ▶ /Users/tombell/.go/bin/gometalinter --disable-all --tests --enable=vet --enable=golint  /Users/tombell/Code/memoir/api
api/handlers_tracklists.go:42:52:error: undefined: pnpage (vet)
memoir (master) ▶ /Users/tombell/.go/bin/gometalinter --disable-all --tests --enable=vet --enable=golint --include="^handlers_tracklists.go:.*$" /Users/tombell/Code/memoir/api
```

Since the output started `api/handlers_tracklists.go`, I assume the `--include` regexp isn't matching because it's assuming the output started with the filename, not the relative path?

**Comment by tombell** [comment]
I've done some digging, and discovered the `include` argument here: https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L41-L44 is different between the if branches.

Since I'm running `nvim` I'm hitting the `has_job` branch.

```
:echo fnamemodify(expand('%:p'), ":.")
```

Returns: `api/handlers_tracklists.go`

```
:echo expand('%:p:t')
```
Returns: `handlers_tracklists.go`, which is missing the relative path of the file, and just includes the file name.

**Comment by bhcleek** [comment]
Jobs are run with their working directory set to the directory that contains the active buffer.

**Comment by tombell** [comment]
Using `gometalinter` inside the directory manually, doesn't show the error either, but manually running `go vet` inside and in the project root, both show the error, so I guess it could just be a `gometalinter` problem.

**Comment by bhcleek** [comment]
That sounds likely. Perhaps it's related to using a module instead of being in GOPATH?

In any case, gometalinter is deprecated. I'd suggest trying golangci-lint instead.

**Comment by tombell** [comment]
I did originally try switching to `golangci-lint` before instead of digging into this, but that has it's own issues related to running against a pacage/buffer.
