### ISSUE TITLE
GoReferrers always use full scope instead of guru scope

### ISSUE THREAD

**Issue by xuxinx** [fatih/vim-go#2314]
### What did you do? (required: The issue will be **closed** when not provided)

I have 3 files:
1. `$GOPATH/src/vimgotest/rfa/rfa.go`
```go
package rfa

import (
        "testvimgo"
)

func hello() int {
        return testvimgo.RF
}
```
2. `$GOPATH/src/vimgotest/rfb/rfb.go`
```go
package rfb

import (
        "testvimgo"
)

func hello() int {
        return testvimgo.RF
}
```
3. `$GOPATH/src/vimgotest/rf.go`
```go
package testvimgo

var RF = 1
```

call `:GoReferrers` on `var RF = 1` with default guru scope

call `:GoReferrers` on `var RF = 1` with guru scope `testvimgo/rfa/...`

### What did you expect to happen?
> call `:GoReferrers` on `var RF = 1` with default guru scope

![image](https://user-images.githubusercontent.com/12792855/58400907-fd022b80-808e-11e9-894f-cfdc1e06c06a.png)

> call `:GoReferrers` on `var RF = 1` with guru scope `testvimgo/rfa/...`

![image](https://user-images.githubusercontent.com/12792855/58400930-0d1a0b00-808f-11e9-80ed-4e86a8709b45.png)

### What happened instead?

> call `:GoReferrers` on `var RF = 1` with default guru scope

![image](https://user-images.githubusercontent.com/12792855/58400654-5027ae80-808e-11e9-9886-721e10d089f7.png)

> call `:GoReferrers` on `var RF = 1` with guru scope `testvimgo/rfa/...`

![image](https://user-images.githubusercontent.com/12792855/58400654-5027ae80-808e-11e9-9886-721e10d089f7.png)

#### vim-go version:
head at d2f1bbe458d8c7c3154ed113c3768bd84451f872
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>
set nocompatible

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
call vundle#end()
filetype plugin indent on

set encoding=utf-8
set backspace=2
set autoindent
</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 17 2019 12:50:30)
Included patches: 1-1336
Compiled by root@WORKSERVER
```

#### Go version (`go version`):

```
go version go1.12.5 linux/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

```
GOARCH="amd64"
GOBIN="/home/xuxin/go/bin"
GOCACHE="/home/xuxin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xuxin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build729846531=/tmp/go-build -gno-record-gcc-switches"
```
</pre></details>

**Comment by bhcleek** [comment]
vim-go passes the scope to guru when it's set: https://github.com/fatih/vim-go/blob/master/autoload/go/guru.vim#L44-L63. If guru isn't using it for referrers, then that's an issue with guru.
