### ISSUE TITLE
Possible to implement GoReferrers using gopls instead of guru?

### ISSUE THREAD

**Issue by cboggs** [fatih/vim-go#2315]
### What did you do? (required: The issue will be **closed** when not provided)
Upgraded go to 1.12, vim-go to 1.20, and ran `:GoUpdateBinaries`. Then ran `:GoReferrers` in a module-based go project (ie: outside of `$GOPATH/src`).

**Note:** This issue is more a question than anything - can `gopls` provide the same functionality that `guru` currently provides re: `GoReferrers`?

### What did you expect to happen?
Expected a location list with refererrers to the selected item in the code.

### What happened instead?
Nothing, except for 100% usage of all cores on the workstation for upwards of 10 minutes.

I understand that guru is hitting end-of-life, so I don't expect it to start working well with go-modules any time soon (or ever). :-) That said, if `gopls` can fulfill this function, it would be great. I just can't seem to find any indication that vim-go yet supports this (or if it's even possible, actually).

#### vim-go version:
v1.20

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
```
call plug#begin()
Plug 'fatih/vim-go'
call plug#end()
let g:go_fmt_command = "goimports"
let g:go_term_mode = 'tabe'
let g:go_def_mode = 'gopls'
let g:go_info_mode = 'gopls'
let g:go_auto_type_info = 0
let g:python_host_prog = '/usr/bin/python'
let g:python3_host_prog = '/usr/bin/python3'
```

</pre></details>

#### Vim version (first three lines from `:version`):

```
NVIM v0.3.1-1-g489d32f2b                                                                                                                                                                
Build type: RelWithDebInfo                                                                                                                                                              
LuaJIT 2.0.5           
```
#### Go version (`go version`):

`go version go1.12.5 linux/amd64`

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cboggs/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/strofcon/projects/go"
GOPROXY=""
GORACE=""
GOROOT="/home/strofcon/bin/go"
GOTMPDIR=""
GOTOOLDIR="/home/strofcon/bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/strofcon/projects/go/code/github.com/cboggs/go-mod-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build622572263=/tmp/go-build -gno-record-gcc-switches"
```
</pre></details>

**Comment by bhcleek** [comment]
vim-go is dependent on gopls to implement this. After gopls implements the necessary request, vim-go will be updated to use it. Closing for now, as there is nothing to be done from vim-go's side yet.

**Comment by cboggs** [comment]
Perfect, that was the answer I was looking for. Thanks!

**Comment by nad2000** [comment]
@bhcleek , 
All **Go.*** commands still map to *guru*: 
https://github.com/fatih/vim-go/blob/master/ftplugin/go/commands.vim#L6 
https://github.com/fatih/vim-go/blob/94fe300c93f715e20a1f167b5e5098b2b32ea047/autoload/go/guru.vim#L407
...
https://github.com/fatih/vim-go/blob/94fe300c93f715e20a1f167b5e5098b2b32ea047/autoload/go/guru.vim#L7

I ran into an issue related to go modules not being supported by *guru* (https://github.com/golang/go/issues/24661#issuecomment-492478653) ...

Is there any way of remapping the commands to *gopls*? 
Thanks,
r
