### ISSUE TITLE
Calling :GoLint on code with warnings replaces the buffer

### ISSUE THREAD

**Issue by peterhellberg** [fatih/vim-go#2321]
### What did you do?

- Opening a file which results in a few warnings from `golint`
- Calling `:GoLint`

(This does not happend for all files, trying to figure out a reliable way to reproduce the issue)

### What did you expect to happen?

- Getting the lint warnings in a Quickfix list.

### What happened instead?

Warnings show up in the Quickfix list, but the contents of the file buffer is replaced with:
```go
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin('~/.vim/plugged')

" Plugin bundles
Plug 'SirVer/ultisnips'
Plug 'ervandew/supertab'
Plug 'honza/vim-snippets'
Plug 'peterhellberg/snippets'
Plug 'itchyny/lightline.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mileszs/ack.vim'
Plug 'nazo/pt.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'yssl/QFEnter'

" Go plugins
Plug 'fatih/vim-go'

" Git plugins
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-git'

" Color scheme
Plug 'nanotech/jellybeans.vim'

" Add plugins to &runtimepath
call plug#end()

let mapleader=","

color jellybeans

set timeout
set timeoutlen=2000

if !has('gui_running')
    set ttimeoutlen=10
    augroup FastEscape
        autocmd!
        au InsertEnter * set timeoutlen=0
        au InsertLeave * set timeoutlen=1000
    augroup END
endif

command! -nargs=1 Silent
      \   execute 'silent !' . <q-args>
      \ | execute 'redraw!'

set t_Co=256

if $TERM_PROGRAM =~ "iTerm"
  set termguicolors
endif

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

set encoding=utf-8
set clipboard=unnamed,unnamedplus
set completeopt-=preview
set expandtab
set hidden
set ignorecase
set lazyredraw
set list listchars=tab:▸\ ,trail:·,extends:>,precedes:<
set modelines=3
set mouse=c
set nobackup
set nocursorcolumn
set nocursorline
set noshowmode
set noswapfile
set nowrap
set nowritebackup
set number
set omnifunc=syntaxcomplete#Complete
set re=1
set shiftwidth=2
set shortmess=at
set shortmess+=I
set showmatch
set sidescroll=1
set sidescrolloff=1
set smartcase
set splitright
set synmaxcol=1024
set tabstop=2
set virtualedit=block
set emoji
set updatetime=100

inoremap § <Esc>

set t_BE=

hi QuickFixLine guibg=#302028 guifg=#f0a0c0 cterm=underline

syntax sync minlines=256

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Vim annoyances
" http://blog.sanctum.geek.nz/vim-annoyances/
vnoremap u y
nnoremap U <C-r>
nnoremap Q <nop>
nnoremap K <nop>
nnoremap J mzJ`z
nnoremap Y y$
inoremap jk <Esc>
inoremap JK <Esc>
inoremap Jk <Esc>
inoremap jK <Esc>

" Disable cursor line in insert mode
au InsertEnter * set nocursorline
au InsertLeave * set cursorline nopaste

" Change the cursor in insert mode
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" Set noeol on all new files
autocmd BufNewFile * set noeol

" No show command
autocmd VimEnter * set nosc

" Use space for :
noremap <space> :

" Quick ESC
imap jj <ESC>

" Jump to the next row on long lines
map <Down> gj
map <Up>   gk
nnoremap j gj
nnoremap k gk

" SuperTab
let g:SuperTabDefaultCompletionType = "context"

" UltiSnips
let g:UltiSnipsExpandTrigger="<tab>"

" Go programming
"au BufRead,BufNewFile *.go setl filetype=go nolist noexpandtab syntax=go

au FileType go nmap <Leader>d <Plug>(go-def-vertical)
au FileType go nmap <Leader>do <Plug>(go-doc-vertical)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <leader>c <Plug>(go-callers)

let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_disable_autoinstall = 1
let g:go_echo_go_info = 1
let g:go_fmt_command = 'goimports'
let g:go_metalinter_command='golangci-lint'

augroup go
  autocmd!
  autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
  autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
  autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
augroup END
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled May 27 2019 02:08:52)
macOS version
Included patches: 1-1400

#### Go version (`go version`):

go version go1.12.5 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pethel/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pethel/Go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sy/pcsz8r4n6zj7klqc8g965w757tsl7x/T/go-build857638242=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment]
You have quite a large vimrc here, and many other plugins. Can you replicate this behavior reliably in any of your files? If so, then can you try it without all the other plugins enabled?

**Comment by preslavmihaylov** [comment]
This happens on my setup as well.
I have disabled all plugins, other than `vim-go`. I think it is not a plugin clash related issue.

## Here's what I did:
1. Go to an empty folder under `$GOPATH`
2. Execute the following:
```
mkdir foo
cat > foo/foo.go <<EOF
package foo

type Foo struct {
    desc string
}
EOF
```
3. run `vim foo/foo.go`
4. type `:GoLint`

After that, the buffer is substituted with the default `main.go` template of vim-go

## Workaround
if you open `foo.go` from inside the `foo` folder this doesn't happen and `:GoLint` works normally:
1. Execute:
```
cd foo
vim foo.go
```
2. Run `:GoLint`

**Comment by bhcleek** [comment]
Thank you @preslavmihaylov . I can duplicate this and will fix it as soon as I can.
