### ISSUE TITLE
[question]vim-go: column mapper is for file

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#2322]
what does this error means?

**Comment by bhcleek** [comment]
I've never seen that message before.

Feel free to re-open if you want to take the time to explain how to get that message.

**Comment by jinleileiking** [comment]
I use vim8 and gopls.  When I `ctrl ]` it shows this message. After upgrade gopls. Works ok. If reproduced, I will reopen

**Comment by jinleileiking** [comment]
I have updated the info

**Comment by bhcleek** [comment]
Please just create a new issue, but include steps to reproduce the problem you're seeing.
