### ISSUE TITLE
Jumping to a definition via a new vertical window stopped working

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#2325]
```
  autocmd FileType go nmap <silent> <Leader>v <Plug>(go-def-vertical)
```

The above mapping stopped working. It opens the definition in a vertical window, but the cursor is not placed inside the new window. It doesn't jump anymore to the definition.

* vim-go version: latest HEAD 
* vim version: 8.1.1400

I didn't debugged it yet, just opening it to track it.

**Comment by bhcleek** [comment]
This is only an issue when `g:go_def_mode='gopls'` and is happening because the gopls integration doesn't have an exit or close handler. I'll should be able to fix this very soon.

**Comment by fatih** [comment]
Thanks Billie. Confirmed that it's fixed.
