### ISSUE TITLE
GoVet doesn't work outside GOPATH (with go modules)

### ISSUE THREAD

**Issue by preslavmihaylov** [fatih/vim-go#2331]
### What did you do?
1. Create a new folder outside of `GOPATH` with new go module.
```
# go to some folder outside GOPATH
mkdir govet-bug
cd govet-bug
go mod init github.com/preslavmihaylov/govet-bug
```

2. Create a new `main.go` file with default vim-go contents:
```
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

3. Make a basic coding error, such as using `fmt.rintln`:
```
package main

import "fmt"

func main() {
	fmt.rintln("vim-go")
}
```

4. Save file with `:x`

### What did you expect to happen?
GoVet points to failing line in quickfix window

### What happened instead?
received line `vim-go: [gometalinter] SUCCESS`

**NOTE**: My gometalinter configuration is:
```
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave_enabled = ['vet', 'errcheck']
```
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
""" -------------------- vim-go -------------------------
" all errors are shown in the quickfix window
let g:go_list_type = "quickfix"

" automatically add import paths when saving file
"let g:go_fmt_command = "goimports"

" enable syntax highlighting
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1

" enable go metalinter
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']

" let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave_enabled = ['vet', 'errcheck']
let g:go_metalinter_autosave = 1

" automatically show GoInfo output
" let g:go_auto_type_info = 1

" automatically highlight variable your cursor is on
let g:go_auto_sameids = 1

" adjust quickfix window height
let g:go_list_height = 8

" terminal opens as a horizontal split below the main window
let g:go_term_mode = "split above"

" More verbose output on failed tests in quickfix window
let g:go_test_show_name = 1

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.4                                                                                                                                                  
Build type: Release                                                                                                                                          
LuaJIT 2.1.0-beta3 

#### Go version (`go version`):

go version go1.12.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pmihaylov/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pmihaylov/programming/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build255055205=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by bhcleek** [comment]
Does `:GoVet` work for you? If so, then this is only a `gometalinter` problem, and since `gometalinter` is deprecated, I'd recommend switching `let g:go_metalinter_command='golangci-lint'`.

**Comment by preslavmihaylov** [comment]
Explicit `:GoVet` does work, but changing to `golangci-lint` didn't fix the issue

**Comment by bhcleek** [comment]
Ah yes, because `golangci-lint` doesn't report that compilation error.

As for `gometalinter` not reporting the compilation error, I can't duplicate the problem you're seeing. 
There was a problem resolved a while ago, though, where the first save of a new file wouldn't run the autosave actions.  Given that, can you confirm that you're seeing this problem on current master?

**Comment by bhcleek** [comment]
🤔 I can duplicate this now. I'll resolve it if I can.

**Comment by bhcleek** [comment]
This is a `gometalinter` bug: it simply doesn't output any errors. You can see for yourself by using `l:go_debug=['shell-commands']` and then running the command you're shown (you'll need to convert the list form into a single string, though).

`golangci-lint` also exits 0 and doesn't report any problems with any particular file.

**Comment by bhcleek** [comment]
I can duplicate this in some directories, but not others. In my home directory gometalinter returns a non-zero exit code and has errors about the line with syntax errors. Outside of my home directory, though, gometalinter exits 0 and has no output.

Can you confirm whether your experience is the same as mine?

**Comment by preslavmihaylov** [comment]
Enabling the `g:go_debug=['shell-commands']` option did allow me to more accurately trace what's going on.

## Using golangci-lint
Inside vim, I get `[golangci-lint] SUCCESS`

This is the exact command being executed in the shell:
```
/home/pmihaylov/programming/go/bin/golangci-lint run --print-issued-lines=false \
--build-tags  --disable-all --exclude-use-default=false \
--enable=vet --enable=errcheck /home/pmihaylov/programming/playground/golang/govet-bug/main.go
```

Executing it manually in the shell provides me with a different result:
```
main.go:6:6: rintln not declared by package fmt (typecheck)
level=warning msg="[runner/govet] govet error: assign: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: atomicalign: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: bools: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: buildtag: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: httpresponse: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: loopclosure: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: ctrlflow: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: lostcancel: failed prerequisites: ctrlflow@command-line-arguments"
level=warning msg="[runner/govet] govet error: nilfunc: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: printf: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: shift: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: stdmethods: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: tests: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: unmarshal: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: unsafeptr: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: unusedresult: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: buildssa: analysis skipped due to errors in package"
level=warning msg="[runner/govet] govet error: nilness: failed prerequisites: buildssa@command-line-arguments"
level=warning msg="[runner] Can't run linter govet: asmdecl: analysis skipped due to errors in package"
```

## Using gometalinter
Inside vim, I get `[gometalinter] SUCCESS`

Exact command being executed:
```
/home/pmihaylov/programming/go/bin/gometalinter --disable-all --tests --enable=vet \
--enable=errcheck --include=^main.go:.*$ /home/pmihaylov/programming/playground/golang/govet-bug
```

This yields empty output and `0 exit code`

However, executing manually in same directory:
```
gometalinter .
```

seems to work fine:
```
main.go:6:2:error: cannot refer to unexported name fmt.rintln (vet)
main.go:6:2:error: undefined: fmt.rintln (vet)
error: failed to check packages: errors while loading package github.com/preslavmihaylov/govet-bug: [/home/pmihaylov/programming/playground/golang/govet-bug/main.go:6:6:warning: error return value not checked (rintln not declared by package fmt]) (errcheck)
WARNING: failed to make error: failed to check packages: errors while loading package github.com/preslavmihaylov/govet-bug: [/home/pmihaylov/programming/playground/golang/govet-bug/main.go a relative path: lstat error: failed to check packages: errors while loading package github.com: no such file or directory
WARNING: exec: "maligned": executable file not found in $PATH
WARNING: exec: "gosec": executable file not found in $PATH
WARNING: exec: "varcheck": executable file not found in $PATH
WARNING: exec: "deadcode": executable file not found in $PATH
WARNING: exec: "goconst": executable file not found in $PATH
WARNING: exec: "gotype": executable file not found in $PATH
WARNING: exec: "staticcheck": executable file not found in $PATH
WARNING: exec: "interfacer": executable file not found in $PATH
WARNING: exec: "ineffassign": executable file not found in $PATH
WARNING: exec: "gotype": executable file not found in $PATH
WARNING: exec: "structcheck": executable file not found in $PATH
WARNING: exec: "unconvert": executable file not found in $PATH
WARNING: exec: "gocyclo": executable file not found in $PATH
```

**Comment by bhcleek** [comment]
Thank you for confirming.

vim-go needs to specify the path to the directory explicitly instead of using `.` so that file locations in the quickfix list will be populated correctly in the case where the current buffer is not in the current working directory. The problem you're encountering is two fold. First, gometalinter exits 0 and has no output when there's a compiler error and the absolute path to the directory is used. Second, golangci-lint also exits 0 in this case.

**Comment by preslavmihaylov** [comment]
How about `golangci-lint`?

Running the vim-go command manually in the shell seems to produce decent output.

**Comment by bhcleek** [comment]
The error code is 0, and no files are identified as having errors.

**Comment by preslavmihaylov** [comment]
This one is:
```
main.go:6:6: rintln not declared by package fmt (typecheck)
```

**Comment by dcu** [comment]
@preslavmihaylov were you able to solve this?

**Comment by preslavmihaylov** [comment]
So I migrated to golangci-lint and it still doesn’t show errors. 

But I installed YouCompleteMe for auto completion, and it has error detection in it apart from the code completion. Hence, I use golangci-lint for govet, lint, errcheck, etc and YCM for code completion and error detection.

**Comment by dcu** [comment]
well that's not good. it used to work fine with gometalinter. 

@bhcleek can you explain why the exact same command that's executed by vim-go returns exit code 1 in the shell and 0 in vim? I don't understand

**Comment by bhcleek** [comment]
@dcu, I don't normally monitor closed issues. If you believe you've found a new bug, please open a new issue.

I do not recall having seen golangci-lint exit 1 in the shell and 0 in vim. 

relevant:
* https://github.com/fatih/vim-go/issues/2331#issuecomment-498804018
* https://github.com/golangci/golangci-lint/issues/592
