### ISSUE TITLE
[improvement] Include error signs on lines with error/warning

### ISSUE THREAD

**Issue by preslavmihaylov** [fatih/vim-go#2332]
Whenever there is an error shown in the quickfix window, we can jump to the lines where the error is detected.

What I believe would add even more value is including error/warning signs next to the lines, where an error occurred, similar to [Syntastic](https://github.com/vim-syntastic/syntastic)'s signs:
![image](https://user-images.githubusercontent.com/7642330/58758348-f4907180-8522-11e9-932b-f70d3874171e.png)

**Comment by bhcleek** [comment]
This is more of a general vim plugin concern than one for vim-go specifically. Have you considered searching for an existing plugin that will place signs at quickfix and location list locations?
