### ISSUE TITLE
next debug command after :GoDebugStart silently tries to set breakpoint at current cursor position if no others are set

### ISSUE THREAD

**Issue by charlieblevins** [fatih/vim-go#2333]
### What did you do? (required: The issue will be **closed** when not provided)

Steps to reproduce:
1. Create a `main.go` file in an empty directory
2. Add the following code to the main.go file:
```golang
package main

import (
	"fmt"
)

var anything string

func main() {
	fmt.Println("TEST")
}
```
3. Write the file, then run :GoDebugStart
4. Once debugger starts, run :GoDebugContinue

### What did you expect to happen?
Execution to stop at main() func (or first line maybe?)

### What happened instead?
An error is reported: 
`vim-go: could not find statement at path/to/my/main.go:1, please use a line with a statement`

#### vim-go version:
Not sure how to find this

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
" Enable 24-bit colors
" important for getting colorschemes to display properly
set termguicolors

" vim-plug - start plugin definition area
call plug#begin('~/.local/share/nvim/plugged')

" elm language
Plug 'elmcast/elm-vim'

" purescript language
Plug 'raichoo/purescript-vim'

" color scheme
Plug 'larsbs/vimterial_dark'
Plug 'christophermca/meta5'
Plug 'YorickPeterse/happy_hacking.vim'
Plug 'morhetz/gruvbox'
Plug 'drewtempelmeyer/palenight.vim'
Plug 'fortes/vim-escuro'
Plug 'ayu-theme/ayu-vim'
Plug 'KabbAmine/yowish.vim'
Plug 'w0ng/vim-hybrid'

" javascript helpers
Plug 'pangloss/vim-javascript'

" linting/type-checking helper
Plug 'vim-syntastic/syntastic'

" Git integration
Plug 'tpope/vim-fugitive'

" typescript syntax highlighting
Plug 'leafgarland/typescript-vim'

" concurrency abilities - not sure if needed in nvim
Plug 'Shougo/vimproc.vim', {'do' : 'make'}

" typescript IDE server
Plug 'Quramy/tsuquyomi'

" typescript syntax file
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
" For async completion
Plug 'Shougo/deoplete.nvim'
" For Denite features
Plug 'Shougo/denite.nvim'

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" Complete vim-plug definitions and initialize system
" Remember to :PlugInstall to install plugins
call plug#end()

" Enable deoplete at startup
let g:deoplete#enable_at_startup = 1

" turn on numbers
set number
set laststatus=2
syntax enable

" default colorscheme
colorscheme hybrid
" colorscheme ayu
" colorscheme znake
" colorscheme gruvbox 

"Set tab as 4 space indent...
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

set guifont=Monaco:h20

" helpers for moving between splits
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" fold according to indentation
set foldmethod=indent
" start with all folds open - use zM to close all
set foldlevel=99

" not sure if this works yet - should cause folds
" to open if contained content matches a search
set foldopen=search

"Enable mouse
set mouse=a

" vim-javascript settings
"let g:javascript_plugin_jsdoc = 1
" support flow js types
let g:javascript_plugin_flow = 1

" disable default quickfix window for typescript
let g:tsuquyomi_disable_quickfix = 1

" not sure if this works
autocmd FileType typescript nmap <buffer> <Leader>t : <C-u>echo tsuquyomi#hint()<CR>

" Syntastic
let g:syntastic_typescript_checkers = ['tsuquyomi'] " You shouldn't use 'tsc' checker.

" Syntastic recommended beginner settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1

"sync mac clipboard to yank register
set clipboard+=unnamedplus

" Use js syntax highlighting for .json files
autocmd BufNewFile,BufRead *.json set ft=javascript

" Use typescript syntax for .tsx files
autocmd BufNewFile,BufRead *.tsx  set filetype=typescript

" Customize vimdiff highlight colors
hi DiffAdd      gui=none    guifg=NONE          guibg=#0f3006
hi DiffChange   gui=none    guifg=NONE          guibg=#262626
hi DiffDelete   gui=bold    guifg=NONE          guibg=#5b2020
hi DiffText     gui=none    guifg=NONE          guibg=#0f3006

let mapleader = (' ')

" vim-go debugger mappings
nnoremap <Leader>ds :GoDebugStart<ENTER>
nnoremap <Leader>dS :GoDebugStop<ENTER>
nnoremap <Leader>c :GoDebugContinue<ENTER>
nnoremap <Leader>' :GoDebugNext<ENTER>
nnoremap <Leader>; :GoDebugStep<ENTER>
nnoremap <Leader>: :GoDebugStepOut<ENTER>

</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):
go version go1.12.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/charlieblevins/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/charlieblevins/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qx/_95qc1c532lf7hxy2djwwl6h0000gn/T/go-build206880871=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by bhcleek** [comment]
The user experience here can definitely be improved, but for a short term solution, you can either set a breakpoint or make sure that your cursor is on a line that has an executable statement before executing `:GoDebugContinue`.

**Comment by bhcleek** [comment]
Vim-go is not a language parser, and anything we try to do here operating on text would be frought with edge cases that would likely result in unresolvable issues being created.

Closing, because I do not envision this changing any time soon.
