### ISSUE TITLE
No warning when debugging a file that has been modified after starting the debugging session

### ISSUE THREAD

**Issue by aarzilli** [fatih/vim-go#2340]
### What did you do? (required: The issue will be **closed** when not provided)

1. Debug any program
2. Modify the source code without stopping the debugger
3. Continue using the debugger

### What did you expect to happen?

Being warned that I'm debugging a stale executable

### What happened instead?

There is no warning that the executable being debugged is stale, now the line numbers reported by the debugger will be nonsensical and behavior of the debugged program will diverge from what would be expected from the source code displayed on screen.

#### vim-go version:

1.20

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 27 2019 13:46:23)
Included patches: 1-1408
Modified by jonathon.fernyhough@york.ac.uk
```

**Comment by bhcleek** [comment]
I suppose we could make all your buffers unmodifiable while debugging, but that seems unnecessarily heavy handed. It's not exactly easy to figure out which files are used in the executable you're debugging.

Do you have a particular solution in mind?

**Comment by aarzilli** [comment]
> It's not exactly easy to figure out which files are used in the executable you're debugging.

You can just compare the last modification time of the current file (the one that's receiving the debugger command) with the last modification time of the executable being debugged (delve has an API call to return it). If it's later then the executable is stale.

**Comment by bhcleek** [comment]
What's the API call that will provide the modification time of the executable being debugged? I don't see anything that will provide the time explicitly or the path to the executable to it could be checked.

**Comment by aarzilli** [comment]
https://godoc.org/github.com/go-delve/delve/service/rpc2#RPCServer.LastModified
