### ISSUE TITLE
GoAlternate doesn't preserve cursor position when switching buffers

### ISSUE THREAD

**Issue by preslavmihaylov** [fatih/vim-go#2341]
Whenever I have a go source file and a corresponding test file, I tend to use `:GoAlternate` to toggle between test file and source file.

However, this command doesn't preserve my cursor's position.
Say I am working on some function in `foo.go`, I alternate to write a test in `foo_test.go`. Once I go back to `foo.go` using `:GoAlternate`, I am back to the beginning of the source file.

Now I have to scroll around the source file all over again until I get to where I was beforehand.

This makes using the command for files larger than ~20 lines inconvenient.

**Comment by bhcleek** [comment]
vim-go doesn't do anything to manipulate the cursor. This is either your vim configuration (see `:help 'viminfo') or your `g:go_alternate_mode` (see `g:go_alternate_mode`).
