### ISSUE TITLE
Template syntax highlighting + snippet from ultisnips

### ISSUE THREAD

**Issue by santosh** [fatih/vim-go#2350]
I'm writing some templates. I wanted the go template syntax highlighting, so I wrote this line to my vimrc.

    au BufRead,BufNewFile *.gohtml set filetype=gohtmltmpl

This gives syntax highlighting of html+go very fine. 

The thing is I've UltiSnips installed; the snippet would only work if there's `.html` extension to the file. 

Is there a way which gives me snippet from `.html` but still keeping the syntax highlighting for go html template?

**Comment by bhcleek** [comment]
You'll need to check with Ultisnips to see if there's a way to get your snippet available in `gohtmltmpl` file types or `*.gohtml` files. Perhaps naming your files with a`.go.html` extension instead will give you what you want?
