### ISSUE TITLE
Pls and mod cache produce "No AST for file"

### ISSUE THREAD

**Issue by korjavin** [fatih/vim-go#2353]
### What did you do? (required: The issue will be **closed** when not provided)

1. Open go files
2. Use ^-] on a function definition 

### What did you expect to happen?
Expect to jump to func def
### What happened instead?
I've got error:  NOT AST for file ...

#### vim-go version:
commit 255f903c14350fb5d615b316661bac93db1544ce

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
Bundle 'fatih/vim-go'
  let g:go_auto_sameids = 0
  let g:go_jump_to_error = 1
  let g:go_fmt_experimental = 1
  let g:go_dispatch_enabled = 1
  let g:go_highlight_operators = 1
  let g:go_metalinter_autosave = 0
  let g:go_auto_type_info = 0
  let g:go_fmt_fail_silently = 1
 Plugin 'stamblerre/gocode', {'rtp': 'vim/'}
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
#### Go version (`go version`):

go version go1.11.10 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br>

<pre>

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build239298306=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by cnbuff410** [comment]
Same issue here. Interestingly it's not happening every single time, just occasionally for me.

**Comment by bhcleek** [comment]
This is a gopls issue. I'd suggest checking github.com/golang/go/issues. For vim-go, you can always roll your gopls version back to a known good version.

**Comment by jinleileiking** [comment]
Use gopls latest. same here

**Comment by wangtiga** [comment]
我也遇到了相同的问题，每次都是重启 vim 解决。
我目前的 gopls 版本是
```shell
$ gopls  version
version v0.1.0, built in $GOPATH mode
```

使用以下方法更新了 gopls ，先观察几天
```shell
go get -u golang.org/x/tools/cmd/gopls
go install golang.org/x/tools/cmd/gopls

gopls version
version v0.1.3-cmd.gopls, built in $GOPATH mode
```

**Comment by laotoutou** [comment]
version v0.1.6-cmd.gopls, built in $GOPATH mode. 
is ok!
