### ISSUE TITLE
There is a way to pass custom args to `GoCoverage`?

### ISSUE THREAD

**Issue by guilhermehubner** [fatih/vim-go#2359]
### What did you do?
`:GoCoverage`

### What did you expect to happen?
I am using a mock library called gomonkey (https://github.com/agiledragon/gomonkey/) and it's requires a arg to `go test` to work correctly; In this case the arg is `-gcflags=all=-l`. 

I would like to know if it is possible to pass this arg when I use `GoCoverage` command.

### What happened instead?
The tests fail :sob: 

#### vim-go version:
1.20 (3dba44e24526f05ed487d3267a7996bd6b511893)

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.3.7
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):
go version go1.12.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
Yes, `:GoCoverage` supports passing options to `go test`. See `:help :GoCoverage`.

**Comment by guilhermehubner** [comment]
@bhcleek it's works! Thank you so much!
