### ISSUE TITLE
GoDef confused by forked repo

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#2361]
### What did you do? (required: The issue will be **closed** when not provided)
Git cloned a source repository (original repository) and a forked repository. Placed cursor over keyword in forked repository. Used GoDef and was taken to symbol in the original repository

### What did you expect to happen?
GoDef should take me to the symbol in the forked repository. 

### What happened instead?
GoDef took me to the symbol in the source (original) repository. 

#### vim-go version:
HEAD

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
https://github.com/ldelossa/dotfiles/blob/master/vimrc
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.5
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.12.1 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/Users/louis/git/gopath/bin"
GOCACHE="/Users/louis/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mc/xwfdd41j1j74xfmcmphbwpgw0000gn/T/go-build399823170=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_list_type = 'quickfix'
g:go_highlight_operators = 1
g:go_jump_to_error = 1
g:go_term_enabled = 1
g:go_metalinter_deadline = '5s'
g:go_highlight_fields = 1
g:go_metalinter_command = 'golangci-lint'
g:go_def_mode = 'godef'
g:go_disable_autoinstall = 0
g:go_highlight_structs = 1
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_test_show_name = 1
g:go_test_timeout = '600s'
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_highlight_methods = 1
g:go_fmt_experimental = 1
g:go_loaded_gosnippets = 1
g:go_term_height = 13
g:go_term_mode = 'split'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_decls_mode = 'fzf'
</pre></details>

# Screenshot
![image](https://user-images.githubusercontent.com/5642902/59652190-aa320600-915a-11e9-91eb-24b207093fcc.png)

Attached screenshot is shown. Was in right buffer and ran 'pwd' so you can see I am in my forked repository. I then did GoDefVertical and the left buffer was opened, as you can see I am moved to the original 'coreos' repo.

**Comment by bhcleek** [comment]
Presumably, the import path of the `database` package referred to in the `AddLeafLayer` method is `gitub.com/coreos/clair/database` (you can verify by examining the import statements at the top of `ancestry.go`). Assuming that's the case, jumping to the definition is working correctly. To jump to the definition in the forked repository, clone it to the expected location of the original coreos repository.

**Comment by ldelossa** [comment]
@bhcleek ah you are correct, I overlooked this.
