### ISSUE TITLE
to folder /home/deniz/go/bin/  

### ISSUE THREAD

**Issue by SirmaXX** [fatih/vim-go#2362]
### What did you do? (required: The issue will be **closed** when not provided)
Actually ,I'm beginner for vim .I installed vimrc configuration from this system (https://vim-bootstrap.com/  ).Everything is working clearly but ı get a few errors.Note:ı read al issues about this problem

### What happened instead?
vim-go: could not find 'gopls'. Run :GoInstallBinaries to fix it                
Error detected while processing function <SNR>82_register[9]..go#lsp#DidOpen:   
line   19:                                                                      
E117: Unknown function: sendMessage                                             
E15: Invalid expression: l:lsp.sendMessage(l:msg, l:state)                      
vim-go: gopls not found. Installing golang.org/x/tools/cmd/gopls to folder /home
/deniz/go/bin/     (but this folder has gopls package)
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

8.0.1453
#### Go version (`go version`):

go version go1.12.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/deniz/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/deniz/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build209670749=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by SirmaXX** [comment]
ı solved my problem,I have updated my golang version 1.10 to 1.12 {gopls package not portable for 1.10 golang version} and   i removed  gopls package  in /go/bin/  and  Run :GoInstallBinaries  .This error dissapeared from command line .Now it gave "vim-go: Features that rely on gopls will not work correctly outside of GOPATH or a module.  "  this problem or warning .

**Comment by bhcleek** [comment]
A null module is a module that's outside of GOPATH and that is missing a `go.mod` file. `gopls` requires that Go files that it deals with are either in GOPATH or else in a defined module. If you want to work with null modules, then I'd suggest setting `g:go_null_module_warning=0` in your vimrc to disable the warning.

**Comment by SirmaXX** [comment]
thanks for helping :)
