### ISSUE TITLE
Syntax off after write

### ISSUE THREAD

**Issue by miekg** [fatih/vim-go#2363]
### What did you do? (required: The issue will be **closed** when not provided)

After a Debian Vim upgrade (2:8.1.0875-2) my vim + vim-go exhibits the following behaviour:
1. Open Go file; syntax highlighting is enabled
2. Write file
3. No syntax is available (`:syntax`: returns `No Syntax items defined for this buffer`) 

The issue here it that literally this upgrade made things fail, which is puzzling If you folks point me to Debian I'm happy to file a bug there as well. Just wanted to see if you may have pointers that can help me debug this.

### Configuration (**MUST** fill this out):
I'm still bisecting where my problematic config exactly is. For vim-go I just have:
~~~
au FileType go set textwidth=0 wrapmargin=0 nowrap noexpandtab tabstop=8 shiftwidth=8 softtabstop=8 number
au FileType go set smartindent
au FileType go set fileencoding=utf8
au FileType go set fileencodings=utf8
au FileType go command! Fmt silent :GoFmt
au FileType go command! Import silent :GoImport
au FileType go let g:go_fmt_command = "goimports"
au FileType go let g:go_highlight_functions = 1
au FileType go let g:go_highlight_methods = 1
au FileType go let g:go_highlight_structs = 1
au FileType go let g:go_highlight_extra_types = 1
au FileType go let g:go_highlight_operators = 1
au FileType go let g:go_highlight_build_constraints = 1
au FileType go let g:go_auto_type_info = 0
au FileType go let g:go_highlight_trailing_whitespace_error = 0
~~~

#### vim-go version:
b6a0bde7d4c64a063ea1b6365e3dd24e2d4f4df1

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
Uhm yes, still trimming that one
</pre></details>

#### Vim version (first three lines from `:version`):
~~~
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 16 2019 17:06:40)
Included patches: 1-197, 322, 377-378, 550, 649, 651, 703, 706-707
Extra patches: 8.1.1401, 8.1.1382, 8.1.1368, 8.1.1367, 8.1.1366, 8.1.1365, 8.1.1046, 8.1.0613, 8.1.0547, 8.1.0546, 8.1.0544, 8.1.0540, 8.1.0539, 8.1.0538, 8.1.0506, 8.1.0208, 8.1.0206, 8.1.0
205, 8.1.0189, 8.1.0177, 8.1.0066
~~~

#### Go version (`go version`):
go version go1.12.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/home/miek/bin/g"
GOCACHE="/home/miek/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/miek/g"
GOPROXY=""
GORACE=""
GOROOT="/home/miek/upstream/go"
GOTMPDIR=""
GOTOOLDIR="/home/miek/upstream/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build122998427=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by TAOXUY** [comment]
Come into same problem.

**Comment by miekg** [comment]
disabling `go_fmt_autosave` fixes this behaviour.
~~~
au FileType go let g:go_fmt_autosave = 0
~~~

**Comment by bhcleek** [comment]
That's quite odd. Nothing about `g:go_fmt_autosave` should cause what you're seeing. Can you verify that filetype after saving with `set filetype?`?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [fatih/vim-go] Syntax off after..." ]
>That's quite odd. Nothing about `g:go_fmt_autosave` should cause what you're seeing. Can you verify that filetype after saving with `set filetype?`?

`filetype=go` (unchanged)

I agree this is weird.

**Comment by miekg** [comment]
Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930763

**Comment by eabderh** [comment]
I believe all these issues are related to the following bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930718

In my case, the bug can be found by opening any file with syntax highlighting (.go, .json, etc) in vim (without using a .vimrc or any other plugins) and typing `:edit`. All syntax highlighting rules are then dropped.

**Comment by miekg** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930721 has more specifics and links to upstream path for vim: https://github.com/vim/vim/commit/a5616b0136cea2104a475d143a1685d71e9b2d3d

So upstream Vim/Debian problem. Closing here.
