### ISSUE TITLE
 Opening some file will cause neovim crashed

### ISSUE THREAD

**Issue by taigacute** [fatih/vim-go#2368]
### What did you do? (required: The issue will be **closed** when not provided)

vi `$Gopath/src/github.com/golangci/golangci-lint/cmd/golangci-lint/main.go`
can't see the cursor，maybe neovim crashed?  if i removed the `vim-go` ,it works
### What did you expect to happen?
work well。
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

if &compatible

set nocompatible

endif

" Add the dein installation directory into runtimepath

set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')

call dein#begin('~/.cache/dein')

call dein#add('fatih/vim-go', {'on_ft':'go'})

call dein#end()

call dein#save_state()

if dein#check_install()

call dein#install()

endif

endif

filetype plugin indent on

syntax enable

</pre></details>

#### Vim version (first three lines from `:version`):

`NVIM v0.4.0-1155-gc62690ccc`
#### Go version (`go version`):

`go verison 1.12.6`
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pendragon/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pendragon/workstation"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ct/5f1j4fl91mz_sdsl_3ksr5ph0000gp/T/go-build397710028=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by taigacute** [comment]
maybe you need this gif
![ranger](https://user-images.githubusercontent.com/41671631/60255013-89f40b00-9901-11e9-89f9-7911da0ab37f.gif)

**Comment by bhcleek** [comment]
Thank you fo the report. I think this is happening because gopls is being initialized. Does it ever become responsive?

**Comment by taigacute** [comment]
I tested some projects which have .git/, the problem will appear when the project is large。

**Comment by bhcleek** [comment]
> Does it ever become responsive?

**Comment by taigacute** [comment]
yes.

**Comment by bhcleek** [comment]
Then I think you're dealing with the time it takes gopls to initialize. What revision of vim-go are you using?

**Comment by taigacute** [comment]
i  update vim-go. problem solved! thanks for your work!
