### ISSUE TITLE
Autocompletion doesn't work for external packages with vendor

### ISSUE THREAD

**Issue by Eksapsy** [fatih/vim-go#2377]
### What did you do?

1. I triggered autocompletion with multiple packages
![](https://media.giphy.com/media/jV5WgHonCl2Of0l1gz/giphy.gif)

2. run `:GoInfo`
### What did you expect to happen?
1. Autocompletion to work along with all kind of go packages
2. GoInfo shouldn't return Fail

### What happened instead?
1. Autocompletion works only with standard packages (like log, fmt, context etc.)
Also, it prints all external package *types* as "*invalid Type"
![](https://i.imgur.com/NH4sgQP.png)
2. GoInfo returned `vim-go: [info] FAIL` instead. This happens with `gopls`, not with `gocode` or `guru`.
**But**, the autocompletion results are the same with all of them.

#### vim-go version: 
Tried **v1.20** & **master**

####  `vimrc`
<details><summary>vimrc</summary><br><pre>

" be iMproved
set nocompatible

" Required by Vundle
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" Autocompletion
Plugin 'Valloric/YouCompleteMe'
" Vim-go
Plugin 'fatih/vim-go'

let g:go_def_mode='gopls'
let g:go_info_mode='gopls'</pre></details>

#### Vim version:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  5 2019 09:19:36)
Included patches: 1-1467
Compiled by Arch Linux

#### Go version:
go version go1.12.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64" 
GOBIN="" 
GOCACHE="/home/exapsy/.cache/go-build" 
GOEXE="" 
GOFLAGS="" 
GOHOSTARCH="amd64" 
GOHOSTOS="linux" 
GOOS="linux" 
GOPATH="/home/exapsy/go" 
GOPROXY="" 
GORACE="" 
GOROOT="/usr/lib/go" 
GOTMPDIR="" 
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64" 
GCCGO="gccgo" 
CC="gcc" CXX="g++" 
CGO_ENABLED="1" 
GOMOD="/home/exapsy/vcs/gitlab.com/gphub/app/go.mod" 
CGO_CFLAGS="-g -O2" 
CGO_CPPFLAGS="" 
CGO_CXXFLAGS="-g -O2" 
CGO_FFLAGS="-g -O2" 
CGO_LDFLAGS="-g -O2" 
PKG_CONFIG="pkg-config" 
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build485796924=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
Completion generally works fine; I use it daily. If you can provide some clear steps to replicate your problem, perhaps we can solve it.

It's a good idea to use the latest gopls, too, as vim-go is dependent on it for completion. `:GoUpdateBinaries gopls` will update it for you.

**Comment by Eksapsy** [comment]
I'm not sure how you could replicate the steps. I even disabled all of the plugins, used any possible combination of 
```vimrc
let g:go_def_mode='...'
let g:go_info_mode='....'
```

and it still doesnt work.
I updated the binaries multiple times, tried [this solution](https://github.com/fatih/vim-go/issues/2018#issuecomment-429618121) and it still doesn't work.

And why `:GoInfo` even fails when `let g:go_*_mode='gopls'`? That's weird.

**Comment by Eksapsy** [comment]
The strangest thing is that VSCode works fine with **gopls** using the **Go** plugin
![image](https://user-images.githubusercontent.com/9019120/60406389-3f52e700-9bbe-11e9-9d69-65c85ee0c541.png)
(same line of code that doesn't work in Vim)

**Comment by bhcleek** [comment]
> I'm not sure how you could replicate the steps besides all the info I already gave

The info you gave is pretty generic, especially considering that completion generally works. Think about it from our perspective; we don't know what files you have or what your directory structure is, but we  know that completion generally works. If you can provide the simplest reproduction case (files, etc.) necessary to reproduce your problem, that would be ideal.

> used any possible combination of
```
let g:go_def_mode='...'
let g:go_info_mode='....'
```

None of those are relevant for completion.

Does completion work without YouCompleteMe? You can test by not loading YCM and using `C-xC-o` to trigger completion.

FWIW, this mostly sounds like a gopls issue.

**Comment by Eksapsy** [comment]
> The info you gave is pretty generic, especially considering that completion generally works.
Yes, I'm aware of that. I'm trying my best to give you as much as possible, that's why I asked for debug details, I wouldn't say Im an expert at this. Thanks in advance.

> Does completion work without YouCompleteMe? You can test by not loading YCM and using C-xC-o to trigger completion.
![image](https://user-images.githubusercontent.com/9019120/60407639-37964100-9bc4-11e9-8dc5-54fc302cad71.png)
Woah, suprisingly, this seemed to work?

I tried enabling YouCompleteMe back, and it worked again ***after I used `C-xC-o`*** but not before that.

So, any idea what's going on here? :P

**Comment by bhcleek** [comment]
That's interesting. One thing it shows is that the problem may not be lied with vim-go or gopls at all.

Keep in mind that gopls can take a while to initialize in large `GOPATH`s (I regularly work in a very large `GOPATH`, and it rarely takes more than about 10 seconds to initialize). You should see a `initialized gopls` when gopls is fully initialized. Prior to that, though, completion will likely fail.

> I updated the binaries multiple times, tried this solution, closed the gocode server and reopened it while using the gocode mode and it still doesn't work.

gocode isn't a factor with Vim 8 unless you've explicitly set `omnifunc` to use the gocode completion function.

**Comment by bhcleek** [comment]
If you can duplicate this on your machine, then use `:let g:go_debug=['lsp']` before triggering autocompletion. You'll get a window with a bunch of gopls requests, messages, and responses. Those may be helpful to understand what's happening on your system.

**Comment by Eksapsy** [comment]
I didnt succeed getting a debug window with this `let`, but by running `:messages` I found that when I'm writing the dot in `collection.` it prints
```RuntimeError: No completions found```
But when I press `C-xC-o` it prints
```vim-go: [completion] SUCCESS```
![image](https://user-images.githubusercontent.com/9019120/60408815-213eb400-9bc9-11e9-9847-c6d5b860e597.png)

**Comment by bhcleek** [comment]
What version of vim-go are you using now? (your original report said you'd tried v1.20 and master)

**Comment by Eksapsy** [comment]
![image](https://user-images.githubusercontent.com/9019120/60409197-4502f980-9bcb-11e9-80db-0986a92fa911.png)
Im at v1.20 right now.

**Comment by bhcleek** [comment]
I'd recommend that you use master. I've been trying to keep it pretty stable, and there have been a lot of improvements and more use of `gopls` since v1.20 was released.

`:let g:go_debug=['lsp']` will only cause the window to appear when `gopls` is used; it won't pop up immediately upon setting `g:go_debug`.

**Comment by Eksapsy** [comment]
> I'd recommend that you use master. I've been trying to keep it pretty stable, and there have been a lot of improvements and more use of gopls since v1.20 was released.

Alright, I've changed to master for good.

> :let g:go_debug=['lsp'] will only cause the window to appear when gopls is used; it won't pop up immediately upon setting g:go_debug.

Yeah, I actually tried to trigger it by triggering autocomplete in both shorts of ways (YCM and `C-xC-o`)

**Comment by bhcleek** [comment]
Now that you're on master, try `:GoUpdateBinaries gopls` again; it's using a stable version of gopls that was just recently introduced whereas v1.20 would use a different package that may have more bugs.

> Yeah, I actually tried to trigger it by triggering autocomplete in both shorts of ways (YCM and C-xC-o)
> Or is it not triggered like that?

It's triggered like that. But if you were on v1.20 before just now, then the messages from `gopls` wouldn't have popped up in a window, but they will with master

**Comment by Eksapsy** [comment]
I've setted `:let g:go_debug=['lsp']` in vimrc so I dont have to set it every time, I restarted vim to have vim-go updated to master, and tried triggering gopls with autocomplete (`C-xC-o & YCM).

Strangely, it all behaves the same with v1.20, and I'm still not getting any gopls debug window.

**Comment by bhcleek** [comment]
That is odd. Is there anything in `g:go_lsp_log` after setting `:let g:go_debug=['lsp']` and try completion? There really shouldn't be if you're running master, but there would be with v1.20.

**Comment by Eksapsy** [comment]
Well, yeah apparently there are some logs when running `:echo g:go_lsp_log`.
![image](https://user-images.githubusercontent.com/9019120/60410614-dd9c7800-9bd1-11e9-938c-e9f861b5e30d.png)

**Comment by bhcleek** [comment]
Yeah, that would seem to confirm that you're still on v1.20. What does `git -C ~/.vim/bundle/vim-go rev-parse HEAD` report?

**Comment by Eksapsy** [comment]
It leads to this commit
[c4b419db6c57125e91d6f292daa664b73b155b7b](https://github.com/fatih/vim-go/tree/c4b419db6c57125e91d6f292daa664b73b155b7b)

**Comment by Eksapsy** [comment]
@bhcleek I just rmrfed it and installed the plugin back. The window appeared. 
![image](https://user-images.githubusercontent.com/9019120/60412083-7930e700-9bd8-11e9-9801-2e571729bf93.png)
