### ISSUE TITLE
How disable gopls tools?

### ISSUE THREAD

**Issue by sober-wang** [fatih/vim-go#2379]
### What did you do? (required: The issue will be **closed** when not provided)
I want disable gopls tools .

### What did you expect to happen?
vim-go: Features that rely on gopls will not work correctly in a null module. 
when I use vim open a .go file. I'm spend very far time.

### What happened instead?
I want disable gopls, because I living China and can't use the gopls tools. 
I can't connect Golang language server. 

#### vim-go version:
last version

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):
Vim version 8.0

#### Go version (`go version`):
Golang 1.12

#### Go environment
<details><summary><code>Windwos or Linux </code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
Can you see http://golang.org/x/tools?

**Comment by joegrasse** [comment]
As another point to disable gopls, right now gopls doesn't support cgo.

**Comment by stamblerre** [comment]
@sober-wang: Living in China should not be a problem for using `gopls` - the `gopls` language server runs locally on your machine, so it does not need to connect to any remote servers. Additionally, the latest version of `gopls` does work in a null module.

**Comment by bhcleek** [comment]
vim-go relies on gopls for many features and we do not have plans to disable it.

The latest master revision of vim-go no longer warns about null modules, but it's a good idea to use modules or else put your project in $GOPATH/src anyway.

**Comment by sober-wang** [comment]
Thank for you.
I was misunderstand $GOPATH in last time .
My co-workers is help me clarify my problem.
