### ISSUE TITLE
neovim for mac go_template_file can't work!

### ISSUE THREAD

**Issue by peterwillcn** [fatih/vim-go#2381]
Neovim 0.3.7_2
vim-go c67d72c
go version go1.12.6 darwin/amd64
```
let g:go_template_file = "hello_world.go"
```
can't work!

**Comment by bhcleek** [comment]
Can you be more specific? What did you do? What did you expect? What happened? The pull request template guides you through providing the information needed to help us troubleshoot issues.

**Comment by peterwillcn** [comment]
@bhcleek 
This is vim-go default template `hello_world.go`
```
/*
*  test template
*/
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```
nvim go/test.go get #The test.go created should not have only one line as shown below
```
package main
```
file test.go should be apply `hello_world.go` template, but hello_world.go template can't work~
```
/*
*  test template
*/
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

**Comment by peterwillcn** [comment]
file test.go should be apply `hello_world.go` template, but hello_world.go template can't work~
```
/*
*  test template
*/
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

**Comment by bhcleek** [comment]
Do you have another go file in the directory?

**Comment by peterwillcn** [comment]
I use alpertuna/vim-header fix the problem. Thanks

**Comment by peterwillcn** [comment]
> Do you have another go file in the directory?

The template file is in ~/.vim/plugged/vim-go/templates/hello_world.go

**Comment by bhcleek** [comment]
The template file is only used when you're creating a new go file in a directory that does not have any go files.

**Comment by peterwillcn** [comment]
> The template file is only used when you're creating a new go file in a directory that does not have any go files.

So it is.
