### ISSUE TITLE
:GoDebugStart exit status 1 cannot find debugger package

### ISSUE THREAD

**Issue by ehrktia** [fatih/vim-go#2385]
### What did you do? (required: The issue will be **closed** when not provided)
installed vim-go plugin in Vim.
based on documentation started debug using `:GoStartDebug .`  in the folder where the main.go file is located.
Received below error message using `:messages`
```
vim-go: can't load package: package debugger: cannot find package "debugger" in any of:
vim-go:         /usr/local/go/src/debugger (from $GOROOT)
vim-go:         /Users/karthickayyapillai/go/src/debugger (from $GOPATH)
vim-go: exit status 1
```
* tried reinstalling Delve 
-  delve debug option using `dlv debug .` worked as expected.

## Vim Details
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 23 2019 20:00:52)
macOS version
Included patches: 1-1200
Compiled by Homebrew
```

## Delve Details
```
Delve Debugger
Version: 1.2.0
Build: b113f0d5162886415216499ab3ac807804f4164b
```

## GO Details
```
GOOS="darwin"
GOPATH="/Users/karthickayyapillai/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
```
## Goversion
`go version go1.11 darwin/amd64'

### What did you expect to happen?

Expected to see a debug session started after issue of the command.
### What happened instead?
received the error message 
```
vim-go: can't load package: package debugger: cannot find package "debugger" in any of:
vim-go:         /usr/local/go/src/debugger (from $GOROOT)
vim-go:         /Users/karthickayyapillai/go/src/debugger (from $GOPATH)
vim-go: exit status 1
```
### Configuration (**MUST** fill this out):
operating system -Mac OS /OSX
## Vim Details
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 23 2019 20:00:52)
macOS version
Included patches: 1-1200
Compiled by Homebrew
```

## Delve Details
```
Delve Debugger
Version: 1.2.0
Build: b113f0d5162886415216499ab3ac807804f4164b
```

## GO Details
```
GOOS="darwin"
GOPATH="/Users/karthickayyapillai/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
```
## Goversion
`go version go1.11 darwin/amd64'
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
```
let g:go_fmt_command="goimports"
let g:go_highlight_build_constraints=1
let g:go_highlight_extra_types=1
let g:go_highlight_fields=1
let g:go_highlight_functions=1
let g:go_highlight_methods=1
let g:go_highlight_operators=1
let g:go_highlight_structs=1
let g:go_highlight_types=1
let g:go_play_open_browser = 1
let g:go_auto_type_info = 1
let g:go_auto_sameids = 1
let g:go_updatetime = 800
let g:go_doc_keywordprg_enabled = 1
let g:go_doc_max_height = 20
let g:go_snippet_engine = "automatic"
let g:go_get_update = 1
let g:go_def_mapping_enabled = 1

```
</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 23 2019 20:00:52)
macOS version
Included patches: 1-1200
Compiled by Homebrew
```

#### Go version (`go version`):

please refer to above config 

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/karthickayyapillai/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/karthickayyapillai/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wk/2mxs2gf122x1knb02422fwcw0000gn/T/go-build925884299=/tmp/go-build -gno-record-gcc-switches -fno-common"


```
</pre></details>

Any help and pointers to resolution is highly appreciated.

**Comment by bhcleek** [comment]
`:GoStartDebug` is not a vim-go command. Are you sure you're using this plugin, or did you mistype the command in the bug report?

Where is your main.go file located?

Did you save the main.go file before running the debugger?

**Comment by bhcleek** [comment]
Also: what does `:echo getcwd()` report?

**Comment by ehrktia** [comment]
Thanks bhcleek for swift response , the command mentioned in the README.
* Debug programs with integrated `delve` support with `:GoDebugStart`.
* Completion support via `gocode`.
output of the :echo getcwd()
`/Users/karthickayyapillai/go/src/github.com/practise/misx/misx1`

**Comment by bhcleek** [comment]
Completion support isn't in play here. Where is your main.go file located and did you save it before running executing `:GoDebugStart .`?

**Comment by ehrktia** [comment]
yes I had the file saved and ran the command again to double check still the same

**Comment by bhcleek** [comment]
What is the full path to the file?

And when run in the directory that contains the file, what does `go list` output?

**Comment by ehrktia** [comment]
Full path for the file  - /Users/karthickayyapillai/go/src/github.com/practise/misx/misx1
file name : main.go
-> go list
github.com/practise/misx/misx1

**Comment by bhcleek** [comment]
That's odd, but a number of issues in vim-go have been fixed around the debugger since the last release. What version of vim-go are you using?

**Comment by ehrktia** [comment]
v1.20 
just did a pull request now.
is my bad/oversight the pull request fixed my issue and i am supposed to set the gopls value it seems.
Please close the issue and mark as resolved.
Thanks very much for your quick help and time in resolving the issue.
