### ISSUE TITLE
vim-go can not get out of edit mode

### ISSUE THREAD

**Issue by laoshaw** [fatih/vim-go#2386]
using vim8 with vim-go and I can easily enter into 'edit' mode in vim, then I can never get out of until I kill the terminal, Esc etc does not work. I have a few Plugs installed but they all worked well until I started to try vim-go which is the first time ever I had to kill vim processes to get out of it.

**Comment by bhcleek** [comment]
Please provide the information requested in the issue template. vim-go generally works well; without knowing what you did, what you saw, what version of Go you're using, which version of vim-go, etc., understanding what could be causing your problems is made very difficult.

Closing this for now, but please feel free to open a new issue with the information that the issue template requests.
