### ISSUE TITLE
How to override a specific mapping?

### ISSUE THREAD

**Issue by lfv89** [fatih/vim-go#2387]
### What did you do?

Pressed `<C-t>`.

### What did you expect to happen?

My custom mapping should have been called.

### What happened instead?

The plugin called `call go#def#StackPop(v:count1)` instead.

**Comment by bhcleek** [comment]
The mappings are in an `ftplugin` script. If you want to disable the go-def mappings entirely, then you can clear `g:go_def_mapping_enabled` (see `:help g:go_def_mapping_enabled`). If you only want to override `<C-t>`, then put your override in an after script (see `:help after`).
