### ISSUE TITLE
Completion doesn't work properly, a binary named '' is missing

### ISSUE THREAD

**Issue by downbtn** [fatih/vim-go#2391]
### What did you do? (required: The issue will be **closed** when not provided)
I use deoplete for completion, and used the instructions found in the documentation to set vim-go as a source for deoplete.

### What did you expect to happen?
I expected completion to work like normal.

### What happened instead?
When trying to write a statement, where the autocomplete dialog should have appeared, I instead got this:
`vim-go: could not find ''. Run :GoInstallBinaries to fix it                                                                                        
Error detected while processing function go#complete#Complete[11]..go#lsp#lsp#Position:
line   18:
E117: Unknown function: go#util#EchoWarn
Press ENTER or type command to continue
`
:GoInstallBinaries is a hook I set using vim-plug to run every time vim-go is updated... I ran it earlier today.
After pressing enter a few times, it disappeared, and the dialog appeared as normal. Every single character that I typed afterwards, a similar error window would display.

#### vim-go version:
The latest one from git at the time, commit 09edd7a4ff02895ffe48a51b6c83e104b7cd013a.
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin('~/.config/nvim/plugged')

Plug 'sonph/onehalf', {'rtp': 'vim/'}

if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif 
Plug 'haya14busa/incsearch.vim'
Plug 'fatih/vim-go', {'do': ':GoUpdateBinaries'}

call plug#end()
set nocompatible               " be iMproved
set number                     " line numbering
set backspace=indent,eol,start " nice backspacing
set mouse=v                    " some mouse support
set showmatch                  " no idea what this does but found this on github
set hlsearch                   " highlight search results
set shiftwidth=4 tabstop=4 softtabstop=4 expandtab " Other indent levels in my ftplugin
set autoindent  
filetype plugin indent on

let mapleader = ';'

nnoremap <leader>u :PlugUpdate<CR>
inoremap <F1> <nop>
nnoremap <F1> <nop>
vnoremap <F1> <nop>
nnoremap <F9> :make

inoremap <C-j> <C-n>
inoremap <C-k> <C-p>

if (has('termguicolors'))
  set termguicolors
endif
colorscheme onehalfdark

let g:deoplete#enable_at_startup = 1
if !exists('g:deoplete#omni#input_patterns')
    let g:deoplete#omni#input_patterns = {}
endif
call deoplete#custom#option('omni_patterns', { 'go': '[^. *\t]\.\w*' })

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.12.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/downbtn/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/downbtn/proj/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build174688331=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
It looks like `lsp-position` didn't install correctly for you. Can you run `:GoUpdateBinaries lsp-position` manually and provide its output?

**Comment by downbtn** [comment]
`vim-go: Updating lsp-position. Reinstalling github.com/bhcleek/lsp-position/cmd/lsp-position to folder /home/downbtn/proj/go/bin/
vim-go: updating finished!
`

Completion seems to work fine now. Thanks a lot!

**Comment by bhcleek** [comment]
FWIW, I have removed the need to use the lsp-position binary by refactoring to use a pure vim solution.
