### ISSUE TITLE
GoUpdateBinaries failed

### ISSUE THREAD

**Issue by adamzyg** [fatih/vim-go#2392]
### What did you do? (required: The issue will be **closed** when not provided)
:GoUpdateBinaries

### What did you expect to happen?
update binaries successfully
### What happened instead?
Error detected while processing function <SNR>85_GoInstallBinaries[19]..go#util#SetEnv:
line   16:
E117: Unknown function: execute
vim-go: Updating gogetdoc. Reinstalling github.com/zmb3/gogetdoc to folder /home/ygzheng/go/bin/
Error detected while processing function <SNR>85_GoInstallBinaries[106]..go#util#SetEnv:
line   16:
E117: Unknown function: execute
Error detected while processing function <SNR>85_GoInstallBinaries:
line  125:
E117: Unknown function: -1
vim-go: Updating guru. Reinstalling golang.org/x/tools/cmd/guru to folder /home/ygzheng/go/bin/
Error detected while processing function <SNR>85_GoInstallBinaries[106]..go#util#SetEnv:
line   16:
E117: Unknown function: execute
Error detected while processing function <SNR>85_GoInstallBinaries:
line  125:
E117: Unknown function: -1
vim-go: Updating gopls. Reinstalling golang.org/x/tools/gopls@latest to folder /home/ygzheng/go/bin/
Error detected while processing function <SNR>85_GoInstallBinaries[79]..go#util#SetEnv:
line   16:
E117: Unknown function: execute
Error installing golang.org/x/tools/gopls@latest: go: cannot use path@version syntax in GOPATH mode^@
Error detected while processing function <SNR>85_GoInstallBinaries:
line   93:
E117: Unknown function: -1
Press ENTER or type command to continue
#### vim-go version:
863e0e91cd2fb5d7624f6447a80e668c897c7e4a
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
let g:go_version_warning = 0
set runtimepath^="/home/ygzheng/.vim_go_runtime"

source /home/ygzheng/.vim_go_runtime/vimrc/basic.vim
source /home/ygzheng/.vim_go_runtime/vimrc/ack.vim
source /home/ygzheng/.vim_go_runtime/vimrc/filetypes.vim
source /home/ygzheng/.vim_go_runtime/vimrc/plugins.vim
source /home/ygzheng/.vim_go_runtime/vimrc/extended.vim

try
  source /home/ygzheng/.vim_go_runtime/custom_config.vim
catch
endtry

""" custom_config.vim
nmap <F8> :TagbarToggle<CR>
nmap <F5> :SyntasticToggleMode<CR>

" about tab
map td :tabnew .<cr>
map te :tabedit
map tc :tabclose<cr>
map tm :tabmove
map cs :sh<cr>

nnoremap <F4> :grep! "\<<cword>\>" . -r<CR>:copen<CR>

let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

"" omni completion
""Note: This option must be set in .vimrc(_vimrc).  NOT IN .gvimrc(_gvimrc)!
"" Disable AutoComplPop.
"" python
autocmd FileType python setlocal omnifunc=python3#complete#Complete
autocmd FileType python set omnifunc=jedi#completions
filetype plugin indent on

" sytaxcheck
function Py2()
    let g:syntastic_python_pylint_exec = '/usr/bin/pylint'
endfunction

function Py3()
    let g:syntastic_python_pylint_exec = '/usr/bin/pylint3'
endfunction

call Py3()   " default to Py3 because I try to use it when possible
let g:syntastic_python_checkers = ['pylint']

if &term == 'xterm' || &term == 'screen'
    set t_Co=256            " Enable 256 colors to stop the CSApprox warning and make xterm vim shine
endif
colorscheme Tomorrow-Night-Bright

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 07 2019 15:35:43)
Included patches: 1-1689
Extra patches: 8.0.0056
#### Go version (`go version`):

go version go1.12.5 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ygzheng/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ygzheng/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build419554025=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
`863e0e91cd2fb5d7624f6447a80e668c897c7e4a` is not a commit in vim-go; I'm not sure which version you're using.

The version of Vim you're using is not supported by vim-go either. You must be using at least Vim 7.4.2009. The warning that you've disabled with `let g:go_version_warning=0` exists for a reason. To take advantage of all of vim-go's features, you'll need to upgrade Vim.
