### ISSUE TITLE
NVIM GoTestFunc runs tests multiple times

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#2396]
### What did you do? (required: The issue will be **closed** when not provided)
Have a test file which I run "GoTestFunc" on. This is an integration test which writes and reads from a database.

### What did you expect to happen?
The test is performed in a single time and in the correct order for the read/write/teardown of the database to occur

### What happened instead?
Postgres logs indicate the test is being ran more than once. This is not reproducible on the command line running go test directly. 

### Configuration (**MUST** fill this out):
https://github.com/ldelossa/dotfiles/blob/master/vimrc

#### vim-go version:
MASTER 

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
https://github.com/ldelossa/dotfiles/blob/master/vimrc

#### Vim version (first three lines from `:version`):

NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.12.1 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/Users/louis/git/gopath/bin"
GOCACHE="/Users/louis/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/louis/git/go/libcscan/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mc/xwfdd41j1j74xfmcmphbwpgw0000gn/T/go-build977618147=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_list_type = 'quickfix'
g:go_highlight_operators = 1
g:go_jump_to_error = 1
g:go_term_enabled = 1
g:go_metalinter_deadline = '5s'
g:go_highlight_fields = 1
g:go_metalinter_command = 'golangci-lint'
g:go_def_mode = 'godef'
g:go_disable_autoinstall = 0
g:go_highlight_structs = 1
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_test_show_name = 1
g:go_test_timeout = '600s'
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_highlight_methods = 1
g:go_list_height = 10
g:go_fmt_experimental = 1
g:go_loaded_gosnippets = 1
g:go_term_height = 10
g:go_term_mode = 'split'
g:go_build_tags = 'integration'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_decls_mode = 'fzf'
</pre></details>

![image](https://user-images.githubusercontent.com/5642902/61167242-fda13500-a509-11e9-9478-815a3bda07ed.png)
screen 1 - This is directly after running "GoTestFunc" as you can see two processes are attempting to write to the DB.

![image](https://user-images.githubusercontent.com/5642902/61167250-1a3d6d00-a50a-11e9-94a6-fdb6efac3407.png)
screen 2 - This is directly after running "go test" on the bottom right most terminal window. As you can see no issues show up in Postgres termain. (middle right)

**Comment by ldelossa** [comment]
![image](https://user-images.githubusercontent.com/5642902/61167271-5c66ae80-a50a-11e9-93de-01e88a185209.png)
screen 3 - one additional run of "GoFuncTest" to show issue of concurrent test being ran.

**Comment by bhcleek** [comment]
With `let g:go_debug=['shell-commands']` and then running `:GoTestFunc -v`, (`-v` just so we can see which tests are run in the next step), you can see the command that vim-go uses to run `go test`. When you run that command in the terminal, what is its output?

**Comment by ldelossa** [comment]
I get the following commands:
```
vim-go: shell command: 'go' 'env' 'GOROOT'
vim-go: shell command: 'go' 'env' 'GOROOT'
vim-go: job command: ['go', 'test', '-run', 'Test_Manifest_Found$', '-v', '-race', '-tags', 'integration']
```

In this screen shot you  can see that again I get the Postgres error:
![image](https://user-images.githubusercontent.com/5642902/61173060-e428d900-a55b-11e9-9d7b-4dba1530fe43.png)

When if I run the exact same command on my terminal, I do not:

![image](https://user-images.githubusercontent.com/5642902/61173065-f99e0300-a55b-11e9-9782-5dcfda208953.png)

**Comment by bhcleek** [comment]
Can you try running that `go test` command again, but with `-count=1`, so that the test cache won't be used? e.g. `go test -run 'Test_Manifest_Found$' -count=1 -v -race -tags integration`

**Comment by ldelossa** [comment]
Ran in quick succession of each other:
https://pastebin.com/raw/EWpcCjQ2

**Comment by ldelossa** [comment]
![image](https://user-images.githubusercontent.com/5642902/61173357-471c6f00-a560-11e9-8f75-42e8937bb5f5.png)
screen - this is my running the test in parallel manually on two command line, they fail also like when I use GoTestFunc.

**Comment by bhcleek** [comment]
Please run the command that `:GoTestFunc` does with `-count=1`  and analyze your postgres processes, I think you'll see that multiple test are being run because of the subtests that are included. Those subtests are likely the source of your deadlock.

**Comment by ldelossa** [comment]
https://pastebin.com/raw/QijjBe4t - still no issue.

subtests are spawn as go routines, but they block until completion unless a "t.Parallel()" is present. 

![image](https://user-images.githubusercontent.com/5642902/61173525-8946b000-a562-11e9-856c-d58621b24402.png)
similarly I can reproduce the issue by running two tests side by side, which introduces concurrency into the equation.

**Comment by bhcleek** [comment]
Deadlocks are notoriously prone to timing conditions. vim-go is only running `go test` once per invocation of `:GoTestFunc`, which you can see in the commands that it lists when you have `g:go_debug` set to `['shell-commands']`

I should also point out that the `go test` command that vim-go executes is run in the directory of the file that is the active buffer when `:GoTestFunc` is run.

**Comment by ldelossa** [comment]
@bhcleek funny enough I simply can't reproduce the issue if I turn off nvim term 

```
" let g:go_term_enabled = 1
" let g:go_term_mode = "split"
" let g:go_term_height = 10
```

**Comment by bhcleek** [comment]
Ah, now that _is_ interesting. I'll take a closer look at the terminal handling.

**Comment by ldelossa** [comment]
Just to confirm, I ran GoFuncTest > 50 times with term off, no issue. Turned it back on and encountered issue after 3rd run.

**Comment by bhcleek** [comment]
Found the problem. https://github.com/fatih/vim-go/blob/b5874d4b7c3a612351187c24deaf628276f6cece/autoload/go/test.vim#L34 should be followed by a return statement. I'll get that fixed ASAP unless you want to submit the PR.

**Comment by ldelossa** [comment]
@bhcleek PR submitted. Thanks for identifying this.
