### ISSUE TITLE
regression: autocomplete broken by: lsp: calculate LSP positions using VimL

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#2405]
### What did you do?

1. Update vim-go to any commit between 46fd587 … d42c958 (current master).
2. Just open .go file as usually, enter beginning of some identifier name and press Tab to autocomplete the rest.

### What did you expect to happen?

Autocomplete should correctly propose suitable variants which should begins with already entered prefix of identifier name.

### What happened instead?

Autocomplete propose unrelated variants ignoring already entered prefix, same as will happens if I try to autocomplete without any prefix, i.e. by entering `(<Tab>`.

### Configuration:

```vim
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_doc_keywordprg_enabled = 0
let g:go_template_use_pkg = 1
let g:go_list_type = "quickfix"
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_parameters = 0
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 0
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 0
let g:go_highlight_variable_assignments = 0
let g:go_build_tags = "integration"
let g:go_metalinter_command = "golangci-lint"

" I'm using supertab for completion.
" Use context-dependent completion type.
" This mean it'll try each function from g:SuperTabCompletionContexts and
" if no one return anything then use g:SuperTabContextDefaultCompletionType:
" 1. s:ContextText will handle pathname completions anywhere.
" 2. s:ContextText will handle module/class/object member completions
"    outside of String/Comment (using &completefunc or &omnifunc, if any).
" 3. ContextPlainText will handle String/Comment using default completion.
" 4. s:ContextDiscover will handle everything using &completefunc, if any.
" 5. Use default.
let g:SuperTabDefaultCompletionType = 'context'
let g:SuperTabCompletionContexts = ['s:ContextText', 'ContextPlainText', 's:ContextDiscover']
let g:SuperTabContextDiscoverDiscovery = ['&completefunc:<c-x><c-u>']
let g:SuperTabContextDefaultCompletionType = '<c-p>'
function! ContextPlainText()
        let synname = synIDattr(synID(line('.'), col('.') - 1, 1), 'name')
        if synname =~ '\(String\|Comment\)'
                exec 'let complType = "' . escape(g:SuperTabContextDefaultCompletionType, '<') . '"'
                return complType
        endif
endfunction
" Set &completefunc to try &omnifunc or default one if omni fails.
autocmd FileType *
    \ if &omnifunc != '' |
    \   call SuperTabChain(&omnifunc, g:SuperTabContextDefaultCompletionType) |
    \ else |
    \   let b:SuperTabCompletionContexts = ['s:ContextText'] |
    \ endif
```

#### vim-go version:
09edd7a (7 days ago) is last good commit which doesn't have this issue.

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 13:35:53)
Included patches: 1-1486
Modified by Gentoo-8.1.1486
```

#### Go version (`go version`):
go version go1.12.7 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/powerman/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build135724726=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
It's working as you expect on my machine. Can you try running `:GoUpdateBinaries gopls`, exit vim, and then try again? If that still fails to work as you expect, can you verify whether the problem exists when using `C-x,C-o` and without loading the supertab plugin?

**Comment by powerman** [comment]
It looks like this issue happens only in specific cases. While git bisect I've tested this issue using code which is already rewritten a lot in last hours, and this issue was 100% reliable to reproduce. Now I've different code and don't have the issue even on latest master. Main difference between old and new is old code wasn't complete, probably it won't even compile - and this may affect gopls behaviour, while new code is complete and compiles. I'll continue work using current master and see if/when it happens again, and then I'll try to report more details here, to let you reproduce the issue.

**Comment by powerman** [comment]
Looks like this issue happens when autocomplete happens **not at end of the line**. I was able to reproduce it using this example code:
```go
package main

type data struct {
	field string
}

func main() {
	var a, b data
	c, d := a, b
}
```
Save it into new directory as `main.go`, open, and then try to type `.f<C-X><C-O>` after `a` and after `b` at last line (with assignment). Current master after `a` won't work as expected, after `b` work as expected. Commit 09edd7a works correctly in both positions.

**Comment by bhcleek** [comment]
Thanks for the report. This should be fixed on master now.

**Comment by powerman** [comment]
Thanks!
