### ISSUE TITLE
Empty error message appears on closing YCM suggestions window with ESC with vim-go enabled

### ISSUE THREAD

**Issue by alexryndin** [fatih/vim-go#2408]
### What did you do? (required: The issue will be **closed** when not provided)
Tried to autocomplete some function name with YCM, and then close autocomplete window with ESC button.

### What did you expect to happen?
Autocomplete windows gets closed, vim switched to normal mode
### What happened instead?
Empty error message appears with suggestion: "Press ENTER or type any command to continue "
![grim-17 07 2019-111155](https://user-images.githubusercontent.com/8342078/61358866-f076a400-a883-11e9-9659-4db7335c6b75.png)
Once I disable vim-go, everything goes well.

#### vim-go version:
master at https://github.com/fatih/vim-go/commit/d42c9586ce9fe170baa62fe22ea3ecf66417f908
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
let mapleader = "\<Space>"
" Plugins
call plug#begin('~/.local/share/nvim/plugged')
let g:gruvbox_contrast_dark = 'hard'
Plug 'morhetz/gruvbox'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-vinegar'
Plug 'eiginn/netrw'
Plug 'easymotion/vim-easymotion'
Plug 'ctrlpvim/ctrlp.vim'
let g:plug_timeout = 300 " Increase vim-plug timeout for YouCompleteMe.
Plug 'Valloric/YouCompleteMe', { 'do': './install.py --go-completer' }
Plug 'fatih/vim-go'

call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
#### Go version (`go version`):

go version go1.12.7 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/codes/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build336919592=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by bhcleek** [comment]
Does this happen for all completions, or just some? Can you duplicate this without YCM being loaded (ctxl-x,ctrl-o is the key combination to do completion with omnifunc as setup by vim-go)? After the message is shown, what does `:messages` output?

**Comment by alexryndin** [comment]
@bhcleek I can't reproduce this behavior with any type of C-X completions, even with C-X C-O (omnifunc). It is noticable that vim-go omnifunc completion looks slightly different from that of provided by YCM (which can be invoked through C-Space) e.g. functions signatures reordered:
![grim-20 07 2019-131319](https://user-images.githubusercontent.com/8342078/61577460-3df74900-aaf0-11e9-9599-ac00f69d51a7.png)
![grim-20 07 2019-131310](https://user-images.githubusercontent.com/8342078/61577461-3df74900-aaf0-11e9-90b6-71c98d8a36fc.png)
. `:messages` is empty, in my case it simply states that "vim-go: initialized gopls".
I don't know if it is actually YCM issue, but the point is that both plugins works well being enabled aside of each other.

**Comment by bhcleek** [comment]
Does it matter which plugin is loaded first in your vimrc?

**Comment by bhcleek** [comment]
If you're not seeing this issue when using `<C-x><C-o>` to trigger vim-go's omnifunc based completion, then I'm not sure how what you're seeing could be an issue for vim-go.
