### ISSUE TITLE
Can to use `ctrl+]` when not start neovim in $GOPATH dir

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#2410]
Env:

gopls: golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@v0.1.3 h1:CB5ECiPysqZrwxcyRjN+exyZpY0gODTZvNiqQi3lpeo=

vim-go: 043984a5117262c74f8b9c85f1e15dc1a7e51872
neovim: ba7ec994ae44499cb0633b0c9d55636f94d2a524

When I lauch nvim in $GOPATH dir the  `ctrl + ] ` works well, But when I launch in HOMEDIR. It does not work and show nothing. Using vim-go with gopls

**Comment by jinleileiking** [comment]
I do not know how to debug

**Comment by jinleileiking** [comment]
[debug.log](https://github.com/fatih/vim-go/files/3405196/debug.log)
Here is the profile log when click `ctrl + ]`

**Comment by jinmiaoluo** [comment]
If you wanna jump to definition, you should use `ctrl + ]` instead of `ctrl + [`

**Comment by jinleileiking** [comment]
@jinmiaoluo sorry for typo. I clicked ] . My bad.

**Comment by jinleileiking** [comment]
I found some clue:

When launch in home, the cwd of gopls process is homedir.
When lauch in $GOPATH, the cwd of gopls process is $GOPATH.

**Comment by jinleileiking** [comment]
Amusing... I have a go.mod in my homedir, delete it and worked well. Thanks @jinmiaoluo

**Comment by stamblerre** [comment]
@jinleileiking: `gopls` should work fine with a `go.mod` file. Make sure you are using the latest `gopls` as well as the latest `vim-go` (`go get golang.org/x/tools/gopls@latest`). If you still encounter issues, please open an issue on the Go issue tracker: https://github.com/golang/go/issues.
