### ISSUE TITLE
Feature Request: Make `g:go_template_file` take an absolute path

### ISSUE THREAD

**Issue by ian-howell** [fatih/vim-go#2412]
# Configuration (**MUST** fill this out):
Currently, the setting `g:go_template_file` specifies the name of a file listed under `vim-go/templates` to use to pre-populate a new buffer. This means that any templates a user desires must be stored under the `vim-go` repo, and thus makes templates non-portable.

This would be better if the `g:go_template_file` accepted an absolute path. With this change, a user could use the following setting:

```
let g:go_template_file = "$HOME/.dotfiles/vim/templates/my_template.go"
```
where the `$HOME/.dotfiles` directory is a git repo that the user can take with them between machines.

**Comment by bhcleek** [comment]
Fixed via #2434
