### ISSUE TITLE
complete with leading characters remain

### ISSUE THREAD

**Issue by qingyunha** [fatih/vim-go#2413]
### What did you do? (required. The issue will be **closed** when not provided.)
type `fmt.Pr` then `<C-X><C-O>`

omnifunc=go#complete#Complete

### What did you expect to happen?
fmt.Println

### What happened instead?
fmt.PrPrintln

### Configuration (**MUST** fill this out):

* vim-go version:
  v1.20

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
filetype plugin indent on

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 07 2019 11:42:36)
Included patches: 1-320
Modified by team+vim@tracker.debian.org

* Go version (`go version`):
go version go1.12.6 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/taoqy/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/taoqy/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build938340967=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
This was already fixed in https://github.com/fatih/vim-go/pull/2291.
