### ISSUE TITLE
[question] What mod does the vim-go uses?

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#2419]
In readme:

```
Completion and other functions that use `gopls` don't work

    Vim-go is heavily reliant on gopls for completion and other functionality.
    gopls requires either module mode or GOPATH mode; files that are neither in
    GOPATH nor in a Go module will not be analyzed by gopls.
```

How can I check the mode  when neovim launched?

**Comment by bhcleek** [comment]
The mode depends on whether your project is in $GOPATH or not. See https://golang.org/cmd/go/#hdr-Preliminary_module_support for clarification.

**Comment by jinleileiking** [comment]
@bhcleek  So I think we need some cmds to change the pls running dir. If I `:tabnew` a new project or use nerdtree select a new bookmark for a new workspace. We need change the gopls runing cwd to let gopls uses the new project go.mod.
