### ISSUE TITLE
Share gopls instance with ycm

### ISSUE THREAD

**Issue by JackDrogon** [fatih/vim-go#2421]
I use ycm for go. And I also use vim-go. But each of them create a `gopls` instance. Is there any way to share `gopls` instance with ycm.

**Comment by bhcleek** [comment]
I don't know of anyway to do this.

**Comment by hmgle** [comment]
I found a trick to share the gopls server with all other editor instances, not only with ycm.

1. Rename the gopls, in order not to start gopls by vim-go or ycm, vim-lsp...

```shell
mv $GOPATH/bin/gopls{,-server}
mv your_YouCompleteMe_DIR/third_party/ycmd/third_party/go/src/golang.org/x/tools/cmd/gopls/gopls{,.bak}
```

2. Create the gopls script:

```shell
echo '#!/bin/sh

nc localhost 9877 # or socat - tcp:localhost:9877' > $GOPATH/bin/gopls
cp $GOPATH/bin/gopls your_YouCompleteMe_DIR/third_party/ycmd/third_party/go/src/golang.org/x/tools/cmd/gopls/gopls
chmod a+x $GOPATH/bin/gopls
chmod a+x your_YouCompleteMe_DIR/third_party/ycmd/third_party/go/src/golang.org/x/tools/cmd/gopls/gopls
```

3. We start the gopls in TCP server mode, this command can be registered to system services to run on system startup:

```shell
gopls-server serve -listen "localhost:9877" -logfile /tmp/gopls_$RANDOM.log
```

4. Then open the `go` files with vim, no matter how many vim instances are started, you can see just one gopls-server is running, all clients are communicating with the gopls-server using the TCP protocol.

There is a problem with ycm: it will send the [exit notification](https://microsoft.github.io/language-server-protocol/specification#exit) to the gopls-server when it is closed. I just [comment the code](https://github.com/ycm-core/ycmd/blob/3365e2d44817d127596f59f70a6240507eb4b0bc/ycmd/completers/language_server/language_server_protocol.py#L266) related to this exit:

```python
def Exit():
  # return BuildNotification( 'exit', None )
  pass
```

I hope they can provide a config to avoid exit the gopls-server.

**Comment by bhcleek** [comment]
@stamblerre can you weigh in regarding whether the technique that @hmgle suggests is supported by `gopls` and what the ramifications for adopting it may be?

**Comment by hmgle** [comment]
As @thomasfaingnaert mentioned https://github.com/prabirshrestha/vim-lsp/issues/469#issuecomment-523162746,  we can start the gopls server outside of Vim, and use `ch_open` instead of `netcat` or `socat`.

**Comment by bhcleek** [comment]
@hmgle there are more concerns here than simply whether or not the technique is theoretically possible. `gopls serve` is mostly intended for debugging right now, and I'm concerned that advising people to use it and multiplexing connections may be sending them down an unsupported path that will make it difficult for those of us that are editor maintainers and the gopls maintainers to analyze issues, and make expose users to unexpected and strange bugs.

Also, despite the comments on https://github.com/prabirshrestha/vim-lsp/issues/469#issuecomment-523162746, dealing with stdio on Windows is handled by Vim pretty well.

I'd suggest waiting until you experience real problems with multiple gopls instances running before recommending hacks to avoid multiple instances.

**Comment by stamblerre** [comment]
I would not recommend doing this, as we do ultimately intend to support this in `gopls` directly (https://github.com/golang/go/issues/34111). It probably won't happen very soon, as it's not a high priority, but I would not endorse hacks to get around this, for the reasons that @ianthehat describes in his comments on that issue.
