### ISSUE TITLE
"Press ENTER or type command to continue" message while installation

### ISSUE THREAD

**Issue by horseinthesky** [fatih/vim-go#2423]
### What did you do? (required: The issue will be **closed** when not provided)
Message `Press ENTER or type command to continue` while installing `vim-go`. It happens several times during installation
```
vim-go: Updating golangci-lint. Reinstalling github.com/golangci/golangci-lint/cmd/golangci-lint to folder /home/horseinthesky/go/bin/
Press ENTER or type command to continue
```

### What did you expect to happen?
No requests to press Enter.

### Configuration (**MUST** fill this out):
```
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
```

#### Vim version (first three lines from `:version`):
```
NVIM v0.3.7
Build type: Release
```
#### Go version (`go version`):
```
go version go1.12.7 linux/amd64
```
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/horseinthesky/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/horseinthesky/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build274532358=/tmp/go-build -gno-record-gcc-switches"
```
</pre></details>

**Comment by bhcleek** [comment]
What does `set cmdheight?` report?

**Comment by horseinthesky** [comment]
> What does `set cmdheight?` report?

It's `cmdheight=1`

**Comment by bhcleek** [comment]
I can't duplicate what you're seeing. Can you do `:GoUpdateBinaries`, run through all the prompts you get and then provide the output of `:messages` afterwards?

**Comment by horseinthesky** [comment]
Sure.
This is for `:GoUpdateBinaries`
vim-go: Updating gogetdoc. Reinstalling github.com/zmb3/gogetdoc to folder /home/horseinthesky/go/bin/
vim-go: Updating guru. Reinstalling golang.org/x/tools/cmd/guru to folder /home/horseinthesky/go/bin/
vim-go: Updating gopls. Reinstalling golang.org/x/tools/gopls@latest to folder /home/horseinthesky/go/bin/
vim-go: Updating fillstruct. Reinstalling github.com/davidrjenni/reftools/cmd/fillstruct to folder /home/horseinthesky/go/bin/
vim-go: Updating godef. Reinstalling github.com/rogpeppe/godef to folder /home/horseinthesky/go/bin/
vim-go: Updating motion. Reinstalling github.com/fatih/motion to folder /home/horseinthesky/go/bin/
vim-go: Updating errcheck. Reinstalling github.com/kisielk/errcheck to folder /home/horseinthesky/go/bin/
vim-go: Updating dlv. Reinstalling github.com/go-delve/delve/cmd/dlv to folder /home/horseinthesky/go/bin/
vim-go: Updating gocode. Reinstalling github.com/mdempsky/gocode to folder /home/horseinthesky/go/bin/
vim-go: Updating impl. Reinstalling github.com/josharian/impl to folder /home/horseinthesky/go/bin/
vim-go: Updating golangci-lint. Reinstalling github.com/golangci/golangci-lint/cmd/golangci-lint to folder /home/horseinthesky/go/bin/
vim-go: Updating gotags. Reinstalling github.com/jstemmer/gotags to folder /home/horseinthesky/go/bin/
vim-go: Updating gorename. Reinstalling golang.org/x/tools/cmd/gorename to folder /home/horseinthesky/go/bin/
vim-go: Updating goimports. Reinstalling golang.org/x/tools/cmd/goimports to folder /home/horseinthesky/go/bin/
vim-go: Updating gocode-gomod. Reinstalling github.com/stamblerre/gocode to folder /home/horseinthesky/go/bin/
vim-go: Updating gomodifytags. Reinstalling github.com/fatih/gomodifytags to folder /home/horseinthesky/go/bin/
vim-go: Updating keyify. Reinstalling honnef.co/go/tools/cmd/keyify to folder /home/horseinthesky/go/bin/
vim-go: Updating golint. Reinstalling golang.org/x/lint/golint to folder /home/horseinthesky/go/bin/
vim-go: Updating iferr. Reinstalling github.com/koron/iferr to folder /home/horseinthesky/go/bin/
vim-go: Updating asmfmt. Reinstalling github.com/klauspost/asmfmt/cmd/asmfmt to folder /home/horseinthesky/go/bin/
vim-go: Updating gometalinter. Reinstalling github.com/alecthomas/gometalinter to folder /home/horseinthesky/go/bin/
vim-go: updating finished!
Press ENTER or type command to continue
```
And this is for `:messages`
```
vim-go: initialized gopls                                                                                                           
vim-go: updating finished!
Press ENTER or type command to continue
```

I'll try to install on a clean system (I'm on Ubuntu 18.04) on the weekend. Maybe it's just me.

**Comment by horseinthesky** [comment]
Confirmed the issue on a clean installation of Ubuntu 18.04.

vimrc
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
```

**Comment by bhcleek** [comment]
So you don't see this when you run `:GoUpdateBinaries`, but you do see it when starting Neovim? Do you see this with Vim? What about if you have `set shortmess=` in your vimrc?

**Comment by horseinthesky** [comment]
> So you don't see this when you run `:GoUpdateBinaries`, but you do see it when starting Neovim? Do you see this with Vim? What about if you have `set shortmess=` in your vimrc?

I see this only when I do `:GoUpdateBinaries`.
I've checked this with no settings in vimrc at all but plugin installation.

**Comment by bhcleek** [comment]
> I see this only when I do :GoUpdateBinaries.

You see the problem both when plug run `GoUpdateBinaries` and when you run `:GoUpdateBinaries` after initialization?

I'd also like to know if you see this with Vim; I've been unable to duplicate it with Vim or with Neovim 0.3.8.

> I've checked this with no settings in vimrc at all but plugin installation.

I understand that. I'm asking you to add `set shortmess=` to your vimrc before the lines that call `:GoUpdateBinaries`.

**Comment by horseinthesky** [comment]
> You see the problem both when plug run GoUpdateBinaries and when you run :GoUpdateBinaries after initialization?
Correct. The same situation both manually and with `PlugInstall`. I'm on Neovim 0.3.7.

> I'm asking you to add set shortmess= to your vimrc before the lines that call 
Ah sorry.
I've tried
```
set shortmess=
call plug#begin('~/.local/share/nvim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
```
but this changed nothing.

**Comment by bhcleek** [comment]
Does _every_ line of the `:GoUpdateBinaries` prompt you to press enter, or only some of them? Is it the longer ones?

**Comment by horseinthesky** [comment]
> Does _every_ line of the `:GoUpdateBinaries` prompt you to press enter, or only some of them? Is it the longer ones?

It always starts asking from `fillstruct` and continues for every single item in the list after it
```
fillstruct
godef
motion
errcheck
dlv
gocode
impl
golangci-lint
gotags
gorename
goimports
gocode-gomod
gomodifytags
keyify
golint
iferr
asmfmt
gometalinter
```

And btw it does ask for Enter only on the first installation. If it is already installed and I do `:GoUpdateBinaries` it just updates everything without any questions.
But if I remove vim-go completely new installation will ask to push Enter for every item from `fillstruct` again.

**Comment by svanburen** [comment]
FWIW, I've had this happen when using a small enough terminal that fills up the screen with the messages from the installation (https://asciinema.org/a/dFzxJcM1gz3Yx0YHFqKTz1Eyo). Not sure if this is the same issue; this doesn't seem to happen if the terminal is large enough.

**Comment by bhcleek** [comment]
@svanburen Yes, that's the only way I can duplicate this, too.

@horseinthesky what size is your screen?

**Comment by bhcleek** [comment]
@horseinthesky can you also try https://github.com/fatih/vim-go/pull/2437 and let me know if it solves your problem?

**Comment by horseinthesky** [comment]
> @horseinthesky can you also try #2437 and let me know if it solves your problem?

Yes. I've scaled terminal size to full screen and it definitely solved the issue.
It's not really handy to change the terminal size =(

And it doesn't work if my terminal is in full screen but installation goes via Ansible or bash script with  `nvim +PlugInstall +qall `.

**Comment by bhcleek** [comment]
Did you try #2437?

**Comment by horseinthesky** [comment]
> Did you try #2437?

Yes. I've tried it and it helped. BUT ONLY if I do `:GoUpdateBinaries` manually.
It doesn't work if `:GoUpdateBinaries` executed by Ansible no matter terminal windows size is.

**Comment by bhcleek** [comment]
The issues you're seeing with ansible aren't specific to vim-go per se. I'd recommend using `: silent`. e.g.
* https://github.com/fatih/vim-go/blob/master/scripts/install-vim#L96
* https://vim.fandom.com/wiki/Avoiding_the_%22Hit_ENTER_to_continue%22_prompts

**Comment by horseinthesky** [comment]
@bhcleek Thank you very much for this. Now it works as I expected!

**Comment by mattbailey** [comment]
This sill happens on neovim (v0.3.8) and vim-plug (latest) with `Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }`

if you run `:PlugUpdate` I get all these `ENTER` prompts. (even on a huge terminal window)

sort of fix:

`Plug 'fatih/vim-go', { 'do': ':silent :GoUpdateBinaries' }`

But this obviously shows zero feedback, which might be confusing.

**Comment by bhcleek** [comment]
@mattbailey I don't normally monitor closed issues. If you're still seeing problems on the latest master (https://github.com/fatih/vim-go/pull/2457 is relevant), please feel free to open a new issue.
