### ISSUE TITLE
When i use <C-x> <C-o> ,i will see  add a window at the top

### ISSUE THREAD

**Issue by myname9** [fatih/vim-go#2431]
<details><summary><code>env</code> Output:</summary><br><pre>
Vim 8.1
vim-go: the latest (GoUpdateBinaries)
Go version: 1.12.7
</pre></details>

When i use  `<C-x>` `<C-o>` ,i will see  add a window at the top

![image](https://user-images.githubusercontent.com/8705998/62102912-42301d00-b2cd-11e9-9ee1-e971794801f1.png)

how can i to hidden it?

**Comment by delphinus** [comment]
Place `set completeopt-=preview` in your vimrc.

See `:h 'completeopt'`

**Comment by myname9** [comment]
@delphinus  thank you very much 👍
