### ISSUE TITLE
vim-go: no AST for file:///my/home/dir/workspace/go/src/some/project/client.go

### ISSUE THREAD

**Issue by poy** [fatih/vim-go#2435]
### What did you do? (required: The issue will be **closed** when not provided)

1. Moved cursor to a place where a method is being invoked (e.g., `x.SomeMethod()`)
1. Used go-to definition for method (e.g., `SomeMethod`) via `g-d`
1. Got error: `vim-go: no AST for file:///my/home/dir/workspace/go/src/some/project/client.go` (where that is the name of the file I'm currently in)

### What did you expect to happen?
For the file and location of the method to be opened.

_Note:_ This sometimes works and sometime fails.

### What happened instead?

The aforementioned error appeared.

#### vim-go version:
```
255f903c14350fb5d615b316661bac93db1544ce
```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

"-----------------------------------------------------------------------------
" VIM-GO CONFIG
"-----------------------------------------------------------------------------
let g:go_fmt_command = "goimports"

" highlight go-vim
highlight goSameId term=bold cterm=bold ctermbg=250 ctermfg=239
set updatetime=100 " updates :GoInfo faster

" vim-go command shortcuts
autocmd FileType go nmap <leader>r <Plug>(go-run)
autocmd FileType go nmap <leader>t :GoTest<CR>
autocmd FileType go nmap <leader>a <Plug>(go-alternate-edit)
autocmd FileType go nmap <leader>d :GoDeclsDir<CR>
autocmd FileType go nmap <leader>g <Plug>(go-generate)
autocmd FileType go nmap <leader>? :GoDoc<CR>
autocmd FileType go nmap <leader>n :GoRename<CR>
autocmd FileType go nmap <leader>l :GoMetaLinter<CR>

</pre></details>

#### Vim version (first three lines from `:version`):

```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 31 2019 17:32:28)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
```

#### Go version (`go version`):

```
go version go1.12.5 linux/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/poy/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/poy/workspace/go"
GOPROXY="https://proxy.golang.org"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/usr/local/google/home/poy/workspace/go/src/github.com/google/kf/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build347006077=/tmp/go-build -gno-record-gcc-switches"
```

</pre></details>

**Comment by bhcleek** [comment]
What version of vim-go are you using?

When did you last run `:GoUpdateBinaries` or `:GoUpdateBinaries gopls`?

What does `gopls version` report from your shell?

Has the file you're editing been saved to disk?

Does the file you're editing have any build constraints in it?

Are there any `defer` statements before the position from which you're executing `gd`?

**Comment by poy** [comment]
> What version of vim-go are you using?

Sorry, forgot that!
```
255f903c14350fb5d615b316661bac93db1544ce
```
> When did you last run :GoUpdateBinaries or :GoUpdateBinaries gopls

Looks like I ran `:GoUpdateBinaries` on Jun 7 2019

> What does gopls version report from your shell?

```
$ gopls version
no module information, gopls not built in module mode
```

> Has the file you're editing been saved to disk?

yes

> Does the file you're editing have any build constraints in it?

no

> Are there any defer statements before the position from which you're executing gd?

no

**Comment by bhcleek** [comment]
vim-go has changed quite a bit since `255f903c14350fb5d615b316661bac93db1544ce`. Can you update vim-go, run `:GoUpdateBinaries gopls`, restart vim, and then try to duplicate your issue again?

**Comment by poy** [comment]
I just updated, and am still getting the error.

**Comment by bhcleek** [comment]
`gopls` can return that error in a number of cases. Can you duplicate the problem reliably? If so, a bug for gopls on https://github.com/golang/go may be useful if your use case isn't already documented in one of the relevant issues (https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22no+ast+for+file%22).

/cc @stamblerre

**Comment by poy** [comment]
I'll take it over there then. Thanks for the help!

**Comment by poy** [comment]
Actually, I needed to set `export GOPACKAGESDRIVER=off` and it seems to be working.

**Comment by vagababov** [comment]
+1 See this since last update.

**Comment by vagababov** [comment]
disabling GOPACKAGESDRIVER seems to work, but that's strange that pls would be broken with it.

**Comment by bhcleek** [comment]
I'm not sure what effect `GOPACKAGESDRIVER=off` will have, but I'd check with the gopls team to see whether that setting is advisable or not.

Whatever is going on here seems to be related to gopls. I'm going to close for now.

**Comment by stamblerre** [comment]
It seems like both @vagababov and @poy are Googlers, and as a result, would have the internal go/packages drivers by default on their workstations. If you are trying to do open-source work on a corp machine, you will need to set `GOPACKAGESDRIVER=off` so that it will use the `go list` driver rather than the internal driver.
