### ISSUE TITLE
Saving file (even to another file name) prevents redoing changes with Ctrl-R

### ISSUE THREAD

**Issue by AaronM04** [fatih/vim-go#2441]
### What did you do? (required: The issue will be **closed** when not provided)

Press `u` multiple times to restore file state to an old version, then type `:w! main.go.bak` to save a backup, then press ctrl-R multiple times.

### What did you expect to happen?

I would go back to the latest file state (that is, before I pressed `u` the first time). The file I am editing would be unchanged on disk.

### What happened instead?

All changes after the one I backed up were lost! The changes I wanted to back up were saved to the file I am editing! This caused work to be lost. 😢 

### Configuration (**MUST** fill this out):

Neovim v0.3.8 on Windows 10.

#### vim-go version:

Commit 510684ed3.

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
" TODO: test this
set expandtab
set ts=2
set softtabstop=2
set shiftwidth=2
call plug#begin()
Plug 'fatih/vim-go'
call plug#end()
au BufEnter,BufNew *.go setl ts=4 sw=4
</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.3.8
Build type: RelWithDebInfo
LuaJIT 2.0.5

#### Go version (`go version`):
go version go1.12.7 windows/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\x\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\x\go
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\x\AppData\Local\Temp\go-build562479490=/tmp/go-build -gno-record-gcc-switches
</pre></details>

**Comment by bhcleek** [comment]
I suspect this is because the file is saved in order to format it and `g:go_fmt_autosave` is enabled by default. I'll do some analysis and see if I can fix it quickly.

**Comment by bhcleek** [comment]
Confirmed that this is because of `g:go_fmt_autosave`. As a temporary workaround, you can disable it when you need to do this operation. I'll work to get a fix in place ASAP.

**Comment by bhcleek** [comment]
@AaronM04 I believe #2442 addresses the issue you encountered. Please feel free to give it a try. If I don't hear back from you in the next 12-16 hours, I'll likely merge it to master.

**Comment by AaronM04** [comment]
It'll be another 12 hours before I can try it out (this is my work laptop). Thank you for (probably) fixing it! :)

On August 5, 2019 7:48:24 PM PDT, Billie Cleek <notifications@github.com> wrote:
>@AaronM04 I believe #2442 addresses the issue you encountered. Please
>feel free to give it a try. If I don't hear back from you in the next
>12-16 hours, I'll likely merge it to master.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/fatih/vim-go/issues/2441#issuecomment-518475753

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AaronM04** [comment]
@bhcleek the fix looks good. Thanks for your help!
