### ISSUE TITLE
error when imported package using custom package name by go modules

### ISSUE THREAD

**Issue by xuxinx** [fatih/vim-go#2443]
### What did you do? (required: The issue will be **closed** when not provided)

Example:
```go
package main

import (
    "fmt"

    "github.com/airbrake/gobrake"
)

var airbrake = gobrake.NewNotifierWithOptions(&gobrake.NotifierOptions{})

func main() {
    _ = airbrake

    Hello()
}

func Hello() {                                                                                                                                                                                            
    fmt.Println("hello")
}
```
- this example file does not use go modules.  
- `github.com/airbrake/gobrake` uses go modules and has a custom package  name https://github.com/airbrake/gobrake/blob/14536eb9ff9cceb764325823e286573d05cd614f/go.mod#L1 and uses this name in its package.
- this example `go run main.go` is ok
  
Call `:GoCallers` on `func Hello(){`

### What did you expect to happen?
show callers

### What happened instead?
vim-go reports a error:   
```
vim-go: guru: couldn't load packages due to errors: github.com/airbrake/gobrake
```
there are messages:  
```
vim-go: [callers] dispatched
vim-go: analysing with scope github.com/xuxinx/testvimgo (see ':help go-guru-scope' if this doesn't work)...
vim-go: [callers] FAIL
vim-go: /home/xuxin/go/src/github.com/airbrake/gobrake/code_hunk.go:9:2: could not import github.com/airbrake/gobrake/v4/internal/lrucache (cannot find package "github.com/airbrake/gobrake/v4/internal/l
rucache" in any of:
vim-go:         /usr/local/go/src/github.com/airbrake/gobrake/v4/internal/lrucache (from $GOROOT)
vim-go:         /home/xuxin/go/src/github.com/airbrake/gobrake/v4/internal/lrucache (from $GOPATH))
vim-go: /home/xuxin/go/src/github.com/airbrake/gobrake/code_hunk.go:5:2: "fmt" imported but not used
vim-go: guru: couldn't load packages due to errors: github.com/airbrake/gobrake
```
#### vim-go version:
I tried both `v1.20` and the master branch
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set nocompatible

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
call vundle#end()
filetype plugin indent on
</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
```
#### Go version (`go version`):

```
go version go1.12.7 linux/amd64
```
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/home/xuxin/go/bin"
GOCACHE="/home/xuxin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xuxin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build082266884=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
`:GoCallers` uses `guru`, which is not module aware. If you're in module aware mode (e.g _not_ in `$GOPATH/src`, then `:GoCallers` won't work.

**Comment by bhcleek** [comment]
@xuxinx do you need more assistance?

**Comment by xuxinx** [comment]
@bhcleek no, I'll close it.

**Comment by sergii4** [comment]
@xuxinx How do you actually `go to callers` if guru doesn't work?
