### ISSUE TITLE
Can't get install to work. 

### ISSUE THREAD

**Issue by oshriPP** [fatih/vim-go#2444]
### What did you do? (required: The issue will be **closed** when not provided)

installed plugin via several methods, vim8 plugin, pathogen, zip, etc. essentially a fresh install, no other custom vim plugins before this.

### What did you expect to happen?
Propper installation.

### What happened instead?
I can use `:help vim-go` and`:GoUpdateBinaries` and `:GoPath` and `:GoInstallBinaries` . All the other commands I'm expecting to use don't work. 
Same issue like #1869 
#### vim-go version:
I don't know the version.
I install be download the source code from git.
```
git clone https://github.com/fatih/vim-go.git  ~/.vim/pack/plugins/start/vim-go
git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go
```
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
if &cp | set nocp | endif
let s:cpo_save=&cpo
set cpo&vim
vmap gx <Plug>NetrwBrowseXVis
nmap gx <Plug>NetrwBrowseX
vnoremap <silent> <Plug>NetrwBrowseXVis :call netrw#BrowseXVis()
nnoremap <silent> <Plug>NetrwBrowseX :call netrw#BrowseX(netrw#GX(),netrw#CheckIfRemote(netrw#GX()))
let &cpo=s:cpo_save
unlet s:cpo_save
set number
set autoindent
set background=dark
set backspace=2
set expandtab
set fileencodings=ucs-bom,utf-8,default,latin1
set modelines=0
set shiftwidth=4
set showmatch
set smartindent
set tabstop=4
set window=0
set mouse=a
" vim: set ft=vim :
syntax on

</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2019 19:03:04)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
```
#### Go version (`go version`):

`go version go1.12.7 darwin/amd64`
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/oshribr/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/oshribr/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6p/x32g3vss71z7ps2vm84gv8zc0000gn/T/go-build531477219=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment]
Add `filetype plugin indent on` to your vimrc.
