### ISSUE TITLE
cannot use :GoLSPDebugBrowser

### ISSUE THREAD

**Issue by frescoraja** [fatih/vim-go#2448]
### What did you do? (required: The issue will be **closed** when not provided)

add following line to `.vimrc`:
```vim
let g:go_debug = ['lsp']
```
open go file in vim, see the `golsplog` buffer at the bottom of my window populated with items like `received: Content-Length: XXX...{"jsonrpc":"2,0", ....}`

also see `vim-go: initialized gopls` in messages

enter `:GoLSPDebugBrowser` command

### What did you expect to happen?

Browser to open with gopls content

### What happened instead?

get the following error message:

`vim-go: gopls was not started with debugging enabled. See :help g:go_debug.`

### Configuration (**MUST** fill this out):

see vimrc, not sure exactly what you mean.

#### vim-go version:

latest. run :PlugUpdate daily

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

call plug#begin('~/.vim/vimplugs')

Plug 'neoclide/coc.nvim', { 'do': 'yarn install --frozen-lockfile' }
Plug 'w0rp/ale'

Plug 'fatih/vim-go', { 'for': ['go', 'proto'], 'do': ':GoUpdateBinaries' }
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-fugitive'

call plug#end()

syntax enable
filetype plugin indent on
set encoding=utf-8 nobomb
scriptencoding utf-8

let g:go_debug = ['lsp']
let g:go_alternate_mode = 'tabedit'
let g:go_decl_mode = 'fzf'
let g:go_def_mode = 'gopls'
let g:go_info_mode = 'gopls'
let g:go_term_mode = 'split'
let g:go_fmt_command = 'goimports'
let g:go_metalinter_command = 'golangci-lint'
let g:go_snippet_engine = 'automatic'
let g:go_list_type = 'locationlist'
let g:go_def_mapping_enabled = 0
let g:go_list_autoclose = 0
let g:go_auto_sameids = 0
let g:go_auto_type_info = 0
let g:go_doc_keywordprg_enabled = 1
let g:go_term_enabled = 1
let g:go_term_height = 10
let g:go_updatetime = 1000
let g:go_highlight_build_constraints = 1
let g:go_highlight_debug = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_function_parameters = 1
let g:go_highlight_functions = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_types = 1
let g:go_highlight_variable_assignments = 1
let g:go_highlight_variable_declarations = 1
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.0-dev
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go1.11.6

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/frescoraja/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/frescoraja/.gvm/pkgsets/go1.11.6/global:/Volumes/SamsungT5/Development/Go:/Volumes/SamsungT5/Development/FW/fw-core/common/src/
go"
GOPROXY=""
GORACE=""
GOROOT="/Users/frescoraja/.gvm/gos/go1.11.6"
GOTMPDIR=""
GOTOOLDIR="/Users/frescoraja/.gvm/gos/go1.11.6/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f8/1g5h1ykx16nb1zhd37zbycr
80000gn/T/go-build639423541=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

thank you for help

**Comment by bhcleek** [comment]
This might be related to the version of gopls you're using. Can you paste the first few lines of the gopls output from the gopls messages?

**Comment by frescoraja** [comment]
```json
sent: Content-Length: 496

{"method": "initialize", "jsonrpc": "2.0", "id": 1, "params": {"rootUri": "file:///Volumes/SamsungT5/Development/Go/src/giohello", "capabilities": {"workspace": {"workspaceFolders": true, "configuration": true, "didChangeConfiguration": {"dynamicRegistration": true}}, "textDocument": {"hover": {"contentFormat": ["plaintext"]}}}, "processId": 8382, "workspaceFolders": [{"uri": "file:///Volumes/SamsungT5/Development/Go/src/giohello", "name": "/Volumes/SamsungT5/Development/Go/src/giohello"}]}}
received: Content-Length: 616

{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"documentFormattingProvider":true,"renameProvider":true,"documentLinkProvider":{},"typeDefinitionProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"custom":null},"id":1}
sent: Content-Length: 57

{"method": "initialized", "jsonrpc": "2.0", "params": {}}
sent: Content-Length: 1532

{"method": "textDocument/didOpen", "jsonrpc": "2.0", "params": {"textDocument": {"uri": "file:///Volumes/SamsungT5/Development/Go/src/giohello/main.go", "languageId": "go", "text": "package main\n\nimport (\n\t\"image/color\"\n\n\t\"gioui.org/ui\"\n\t\"gioui.org/ui/app\"\n\t\"gioui.org/ui/f32\"\n\t\"gioui.org/ui/layout\"\n\t\"gioui.org/ui/measure\"\n\t\"gioui.org/ui/paint\"\n\t\"gioui.org/ui/text\"\n\t\"golang.org/x/image/font/gofont/goregular\"\n\t\"golang.org/x/image/font/sfnt\"\n)\n\nfunc main() {\n\tgo func() {\n\t\tw := app.NewWindow(nil)\n\t\tregular, _ := sfnt.Parse(goregular.TTF)\n\t\tvar cfg ui.Config\n\t\tvar faces measure.Faces\n\t\tops := new(ui.Ops)\n\t\tfor e := range w.Events() {\n\t\t\tif e, ok := e.(app.UpdateEvent); ok {\n\t\t\t\tcfg = &e.Config\n\t\t\t\tcs := layout.RigidConstraints(e.Size)\n\t\t\t\tops.Reset()\n\t\t\t\tfaces.Reset(cfg)\n\n\t\t\t\tlbl := text.Label{Face: faces.For(regular, ui.Sp(72)), Text: \"Hello, world\"}\n\t\t\t\tlbl.Layout(ops, cs)\n\n\t\t\t\tdrawSquare(ops, 100, 100, color.RGBA{G: 100, B: 150, A: 200})\n\n\t\t\t\tw.Update(ops)\n\t\t\t}\n\t\t}\n\t}()\n\tapp.Main()\n}\n\nfunc drawSquare(ops *ui.Ops, posX float32, posY float32, col color.RGBA) {\n\tsquare := f32.Rectangle{Max: f32.Point{X: 500, Y: 500}}\n\n\t// Position\n\tui.TransformOp{}.Offset(f32.Point{\n\t\tX: posX,\n\t\tY: posY,\n\t}).Add(ops)\n\t// Color\n\tpaint.ColorOp{Color: col}.Add(ops)\n\t// Clip corners\n\t// Draw\n\tpaint.PaintOp{Rect: square}.Add(ops)\n\t// Animate\n\tui.InvalidateOp{}.Add(ops)\n}\n"}}}
stderr: 2019/08/09 21:40:11 Debug serving on port: 55358
received: Content-Length: 268

{"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeConfiguration","method":"workspace/didChangeConfiguration"},{"id":"workspace/didChangeWorkspaceFolders","method":"workspace/didChangeWorkspaceFolders"}]},"id":1}
sent: Content-Length: 43

{"id": 1, "jsonrpc": "2.0", "result": null}
received: Content-Length: 167

{"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///Volumes/SamsungT5/Development/Go/src/giohello","section":"gopls"}]},"id":2}
sent: Content-Length: 91

{"id": 2, "jsonrpc": "2.0", "result": [{"buildFlags": [], "hoverKind": "NoDocumentation"}]}
received: Content-Length: 1126

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Build info\n----------\nversion v0.1.1, built in $GOPATH mode\n\nGo info\n-------\ngo version go1.11.6 darwin/amd64\n\nGOARCH=\"amd64\"\nGOBIN=\"\"\nGOCACHE=\"/Users/frescoraja/Library/Caches/go-build\"\nGOEXE=\"\"\nGOFLAGS=\"\"\nGOHOSTARCH=\"amd64\"\nGOHOSTOS=\"darwin\"\nGOOS=\"darwin\"\nGOPATH=\"/Users/frescoraja/.gvm/pkgsets/go1.11.6/global:/Volumes/SamsungT5/Development/Go:/Volumes/SamsungT5/Development/FW/fw-core/common/src/go\"\nGOPROXY=\"\"\nGORACE=\"\"\nGOROOT=\"/Users/frescoraja/.gvm/gos/go1.11.6\"\nGOTMPDIR=\"\"\nGOTOOLDIR=\"/Users/frescoraja/.gvm/gos/go1.11.6/pkg/tool/darwin_amd64\"\nGCCGO=\"gccgo\"\nCC=\"clang\"\nCXX=\"clang++\"\nCGO_ENABLED=\"0\"\nGOMOD=\"\"\nCGO_CFLAGS=\"-g -O2\"\nCGO_CPPFLAGS=\"\"\nCGO_CXXFLAGS=\"-g -O2\"\nCGO_FFLAGS=\"-g -O2\"\nCGO_LDFLAGS=\"-g -O2\"\nPKG_CONFIG=\"pkg-config\"\nGOGCCFLAGS=\"-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f8/1g5h1ykx16nb1zhd37zbycr80000gn/T/go-build492619174=/tmp/go-build -gno-record-gcc-switches -fno-common\"\n"}}
received: Content-Length: 308

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Volumes/SamsungT5/Development/Go/src/giohello/main.go","diagnostics":[{"range":{"start":{"line":39,"character":5},"end":{"line":39,"character":9}},"severity":1,"source":"LSP","message":"Main not declared by package app"}]}}
```

hope that helps

when i run `gopls version` from command line, i get 
```sh
version v0.1.1, built in $GOPATH mode
```

**Comment by bhcleek** [comment]
It seems that you're using an older version of gopls. Please run `:GoUpdateBinaries gopls` from within vim, restart vim after it completes, and then try `:GoLSPDebugBrowser` again.

**Comment by frescoraja** [comment]
thank you! resolved.. i never noticed that running `:GoUpdateBinaries` always errored when trying to update `gopls` .. so it never got updated. it tries to install `golang.org/x/tools/gopls@latest` version, but the projects i'm working on are using GOPATH mode..
i was able to update gopls from cmd line using 
```sh
go get -u golang.org/x/tools/gopls`
```
and GoLSPDebugBrowser works fine
thanks again

**Comment by bhcleek** [comment]
It shouldb't matter that you're in GOPATH mode, but you are using an older version of Go, and that probably makes the difference. Updating gopls the way you did, you'll be using the latest master from golang.org/x/tools instead of the most recently released version of gopls.

**Comment by frescoraja** [comment]
got it, thank you for help
