### ISSUE TITLE
can gorun be async in vim8?

### ISSUE THREAD

**Issue by NewUserHa** [fatih/vim-go#2452]
### What did you do? (required: The issue will be **closed** when not provided)
use `gorun`

### What did you expect to happen?
can modify file while  `gorun`

### What happened instead?
can't modify file while  `gorun`

### Configuration (**MUST** fill this out):
nothing

#### vim-go version:
don't know since vim-plug cloned it

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
`Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }`
</pre></details>

#### Vim version (first three lines from `:version`):
vim 8.1.1

#### Go version (`go version`):
1.12.7 win

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

nothing
</pre></details>

I see vim can run async shell/cmd command. could you make `gorun` async?

thanks

**Comment by bhcleek** [comment]
It's on the list of things to implement.

**Comment by NewUserHa** [comment]
thanks
