### ISSUE TITLE
feature request: go doc popup window for neovim

### ISSUE THREAD

**Issue by frescoraja** [fatih/vim-go#2459]
### What did you do? (required: The issue will be **closed** when not provided)

set  `g:go_doc_popup_window = 1` in my vimrc

### What did you expect to happen?

executing `:GoDoc` would open doc inside popup window near cursor

### What happened instead?

documentation info opened in buffer at bottom of window

.. would this be very difficult to do?

thanks for all your awesome work on this plugin

**Comment by georgijd** [comment]
Hi @frescoraja ,

I've recently submitted a PR which adds this funtionality: https://github.com/fatih/vim-go/pull/2451. Feel free to give it a go. I've been using it ever since with no issues.

**Comment by smartding** [comment]
> Hi @frescoraja ,
> 
> I've recently submitted a PR which adds this functionality: #2451. Feel free to give it a go. I've been using it ever since with no issues.

I've set `let g:go_doc_window_popup_window             = 1`  in my neovim config file, and I'm running neovim 0.4.2 on a debian box. But the `GoDoc` still shows up in a separate preview window. Is there any additional neovim configuration I should do?

**Comment by bhcleek** [comment]
Fixed in #2451

**Comment by datavisorchengpeng** [comment]
This config works for me:
`let g:go_doc_popup_window = 1`
