### ISSUE TITLE
GoRename fails

### ISSUE THREAD

**Issue by janbaer** [fatih/vim-go#2460]
I have the problem that GoRename will not work. I've updated my binaries with :GoUpdateBinaries before. But I always get gorename: can't find package ...

gorename from the commandline is working.

`go version go1.12.5 linux/amd64`

My project is using go modules. This is my go env:

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jan/Projects/github-oauth-bridge/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build256818828=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
Unfortunately, `gorename` doesn't work in modules. There's already an open issue for converting vim-go to use gopls for renaming, #2366 , and I plan to work on that as soon as I can get to it.

You might also find https://github.com/golang/go/issues/24661 to be of interest.

**Comment by janbaer** [comment]
Thank you for the quick response. So I'll close this issue and follow #2366
