### ISSUE TITLE
Unknown function: go#path#ToURI

### ISSUE THREAD

**Issue by msAlcantara** [fatih/vim-go#2462]
### What did you do? (required: The issue will be **closed** when not provided)
Update vim-go with `:PlugUpdate`

### What did you expect to happen?
No errors when open a .go file

### What happened instead?
Errors when open .go files
```
Error detected while processing function <SNR>61_register[9]..go#lsp#DidOpen[10]..go#lsp#message#DidOpen:
line    1:
E117: Unknown function: go#path#ToURI
E117: Unknown function: go#path#ToURI
```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
Plug 'fatih/vim-go', {'do': ':GoInstallBinaries'}

function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

let g:go_list_type = "quickfix"
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:syntastic_go_checkers = ['golint', 'govet']
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_structs = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_space_tab_error = 0
let g:go_highlight_array_whitespace_error = 0
let g:go_highlight_trailing_whitespace_error = 0
let g:go_highlight_extra_types = 1
let g:syntastic_go_checkers = ['go']

autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4 softtabstop=4

augroup completion_preview_close
  autocmd!
  if v:version > 703 || v:version == 703 && has('patch598')
    autocmd CompleteDone * if !&previewwindow && &completeopt =~ 'preview' | silent! pclose | endif
  endif
augroup END

augroup go

  au!
  au Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
  au Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
  au Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
  au Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')

  au FileType go nmap <Leader>dd <Plug>(go-def-vertical)
  au FileType go nmap <Leader>dv <Plug>(go-doc-vertical)
  au FileType go nmap <Leader>db <Plug>(go-doc-browser)

  au FileType go nmap <leader>r  <Plug>(go-run)
  au FileType go nmap <leader>t  <Plug>(go-test)
  au FileType go nmap <Leader>gt <Plug>(go-coverage-toggle)
  au FileType go nmap <Leader>i <Plug>(go-info)
  au FileType go nmap <silent> <Leader>l <Plug>(go-metalinter)
  au FileType go nmap <C-g> :GoDecls<cr>
  au FileType go nmap <leader>dr :GoDeclsDir<cr>
  au FileType go imap <C-g> <esc>:<C-u>GoDecls<cr>
  au FileType go imap <leader>dr <esc>:<C-u>GoDeclsDir<cr>
  au FileType go nmap <leader>rb :<C-u>call <SID>build_go_files()<CR>

augroup END
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 23 2019 13:09:01)
#### Go version (`go version`):

go version go1.12.9 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/home/matheus/go/bin"
GOCACHE="/home/matheus/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/matheus/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/matheus/dev/cielo/queue-alm/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build840007180=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by msAlcantara** [comment]
Som errors occurred when try to update go bineraries with `:GoUpdateBinaries`

```
Error detected while processing function <SNR>61_GoInstallBinaries:
line   19:
E117: Unknown function: go#util#SetEnv
vim-go: Updating gogetdoc. Reinstalling github.com/zmb3/gogetdoc to folder /home/matheus/go/bin
line  109:
E117: Unknown function: go#util#SetEnv
line  129:
E121: Undefined variable: Restore_modules
E116: Invalid arguments for function call
vim-go: Updating guru. Reinstalling golang.org/x/tools/cmd/guru to folder /home/matheus/go/bin
line  109:
E117: Unknown function: go#util#SetEnv
line  129:
E121: Undefined variable: Restore_modules
E116: Invalid arguments for function call
vim-go: Updating gopls. Reinstalling golang.org/x/tools/gopls@latest to folder /home/matheus/go/bin
line   82:
E117: Unknown function: go#util#SetEnv
line   96:
E121: Undefined variable: Restore_modules
E116: Invalid arguments for function call
```

**Comment by bhcleek** [comment]
These functions all exist. It seems likely that you may have multiple versions of vim-go installed, and that the loading order of the disparate versions of vim-go is the source of your issues.

**Comment by msAlcantara** [comment]
Yes, I review some folders in my `~/.vim` folder and I see some other folders of vim-go, I removed all and installed again with `:PlugInstall`, and now, all worker good. Thanks!!
