### ISSUE TITLE
the lastest version have not supported "Vi IMproved 7.4",please update the README.md

### ISSUE THREAD

**Issue by silencer001** [fatih/vim-go#2465]
### What did you do? (required: The issue will be **closed** when not provided)
When I execute “:PluginUpdate” in vim，vim-go can't be work ，the error messages：
```Error detected while processing function go#auto#fmt_autosave..go#fmt#For
mat..go#fmt#run..<SNR>43_fmt_cmd:
line    8:
E706: Variable type mismatch for: opts
line   10:
```
After I degrade to 1.16， All be ok :)

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:10:41)
Included patches: 1-207, 209-629
Modified by <bugzilla@redhat.com>

#### Go version (`go version`):

go version go1.12.6 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/opt/jud/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/jud/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build784491657=/tmp/go-build"

</pre></details>

**Comment by arp242** [comment]
Yeah, 7.4.629 is really old. You'll need to update your Vim to 7.4.2009 or newer. You should get a message about this on startup though?

**Comment by arp242** [comment]
Also note it's mentioned in the README already: https://github.com/fatih/vim-go#install
