### ISSUE TITLE
GoGuru: GoCaller and GoCallee doesn't work for some go packages

### ISSUE THREAD

**Issue by niks3089** [fatih/vim-go#2466]
### What did you do? (required: The issue will be **closed** when not provided)

`go get github.com/nabla-containers/runnc`

- Move cursor over function definition
- Type :GoCallers
- Error message is displayed:

```
vim-go: guru: couldn't load packages due to errors: github.com/opencontainers/runc/libcontainer/utils, github.com/nabla-containers/runnc/llcli, github.com/nabla-containers/runnc/libcontainer
```
I didn't have to set the GoGuru scope, since I am in the TLD.  I created another directory with a single and that works. 

### What did you expect to happen?

- Move cursor over function definition
- Type :GoCallers
- List with call sites should be displayed

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

<details><summary>vimrc</summary><br><pre>
"" Go Lang Bundle
Plug 'fatih/vim-go', {'do': ':GoInstallBinaries'}
" go
" vim-go
" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

let g:go_list_type = "quickfix"
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_structs = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_space_tab_error = 0
let g:go_highlight_array_whitespace_error = 0
let g:go_highlight_trailing_whitespace_error = 0
let g:go_highlight_extra_types = 1
autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4 softtabstop=4
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2018 17:24:51)

#### Go version (`go version`):

go version go1.12.9 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

go version go1.12.9 darwin/amd64
Sumanas-MacBook-Pro:runnc nikhil$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nikhil/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nikhil/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d2/26dywgp55ng688124qs0kcpr0000gp/T/go-build059371982=/tmp/go-build -gno-record-gcc-switches -fno-common
</pre></details>

**Comment by bhcleek** [comment]
Can you enable `go_echo_command_info` and then run the command it reports for your `:GoCallers` invocation in a shell and provide the error that the invocation in the shell outputs? Be sure to run the shell command in the directory that contains the file that you're calling `:GoCallers` from.

**Comment by bhcleek** [comment]
`guru` can't find all the callers for a function when some of the packages won't build and will fail under such conditions.

If you'll run `:messages` after `:GoCallers`, you'll see a lot of errors. Try resolving those first (`go build ./...` will be helpful for you), and then try `:GoCallers` again.

**Comment by niks3089** [comment]
No, thanks. Closing..
