### ISSUE TITLE
GoDebugStart star failed on windows

### ISSUE THREAD

**Issue by wining** [fatih/vim-go#2469]
### What did you do? (required: The issue will be **closed** when not provided)
GoDebugStart or GoDebugStart foo

### What did you expect to happen?
debug start well
### What happened instead?
![image](https://user-images.githubusercontent.com/4005513/64012759-dbfb1c00-cb50-11e9-99d6-d11181588087.png)

#### vim-go version:
the master branch
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,gbk
set autochdir
set splitright
set lazyredraw
set shortmess=filnxtToOc
filetype plugin indent on
syntax on
let g:go_fmt_command = "goimports"
let g:go_gocode_unimported_packages = 1
let g:go_list_type = 'quickfix'
let g:go_list_height = 10
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1
</pre></details>

#### Vim version (first three lines from `:version`):

![image](https://user-images.githubusercontent.com/4005513/64013572-ad7e4080-cb52-11e9-9ae7-09cac6d2f5ad.png)

#### Go version (`go version`):

go version go1.12.9 windows/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\master\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\GOPATH;D:\Work\mhserver\static;
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\master\AppData\Local\Temp\go-build489226678=/tmp/go-build -gno-record-gcc-switches

</pre></details>

**Comment by bhcleek** [comment]
This error seems to be coming from delve. Can you enable `g:go_echo_command_info`, run the command that it outputs in `D:\GOPATH\src\foo`, and see if it provides any additional information?

Are there any Go files in `D:\GOPATH\src\foo` other than `main.go`?

**Comment by wining** [comment]
Only the file main.go is in this folder.

There is no additional information.
![image](https://user-images.githubusercontent.com/4005513/64139986-713e2f00-ce35-11e9-9827-60a12092d129.png)

**Comment by wining** [comment]
dlv command runs well。
![image](https://user-images.githubusercontent.com/4005513/64140137-f6294880-ce35-11e9-9b45-df79a7e9dbd0.png)

**Comment by bhcleek** [comment]
My previous instructions had a typo.

>  Can you enable `g:go_echo_command_info`, run the command that it outputs in `D:\GOPATH\src\foo`, and see if it provides any additional information?

Should have been:
 Can you enable `g:go_debug=['shell-commands']`, run the command that it outputs in `D:\GOPATH\src\foo`, and see if it provides any additional information?

**Comment by wining** [comment]
I try this in another computer which has the save error.
Is this message ok?
![image](https://user-images.githubusercontent.com/4005513/64485533-b8bd2480-d254-11e9-940c-782bdde907a2.png)

**Comment by bhcleek** [comment]
That's helpful. Can you give #2480 a try to see if it fixes the problem for you?

**Comment by wining** [comment]
This problem is Fixed. But the command "GoDebugContine" dosenot work well.
![image](https://user-images.githubusercontent.com/4005513/64486229-ce364c80-d25c-11e9-8095-abc0b8a706cf.png)

**Comment by bhcleek** [comment]
@wining please open a new issue for the problem you're having with `:GoDebugContinue` with information that can be used to duplicate the problem you're having (e.g. did the second invocation of `GoDebugContinue` fail or the first invocation?).

FWIW, it's probably a good idea to `:GoUpdateBinaries dlv` if you haven't updated it recently.

**Comment by wining** [comment]
Ok! I have duplicate the problem and i will open a new issue.
