### ISSUE TITLE
No format on save with go_fmt_autosave 

### ISSUE THREAD

**Issue by nolash** [fatih/vim-go#2471]
### What did you do? (required: The issue will be **closed** when not provided)

Trying to achieve auto-formatting of go files on buffer write.

### What did you expect to happen?

on :w the file should be automatically goformatted

### What happened instead?

nothing happened. I tried explicitly setting `let [g:]go_fmt_autosave = 1` and `let [g:]go_fmt_command = goimports"'`. I _have_ run `GoBinaries` - everything's installed, both `gofmt` and `goimports` are available

if I add `au BufWritePre,FileWritePre *.go :GoFmt` to my `.vimrc` it works

### Configuration (**MUST** fill this out):

<details><summary>configuration</summary><br><pre>
archlinux 5.2.11 with following vim packages:

local/vim 8.1.1906-1
local/vim-colorsamplerpack 2012.10.28-5 (vim-plugins)
local/vim-ctrlp 1.80-2 (vim-plugins)
local/vim-doxygentoolkit 0.2.13-4 (vim-plugins)
local/vim-go 1.20-2 (vim-plugins) 
local/vim-latexsuite 1:1.10.0-1 (vim-plugins)
local/vim-runtime 8.1.1906-1
</pre></details>

_note: I've moved the vim-go files to `/usr/share/vim/vim81/pack/plugins/start/vim-go/...`

#### vim-go version:

1.20 (release tar.gz)

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

syntax on
autocmd BufNewFile,BufRead *.sol set syntax=solidity
autocmd BufNewFile,BufRead *.ts setfiletype typescript

map <c-t> :tabe<cr>
nmap <s-left> gT
nmap <s-right> gt
nmap <s-n> gt
nmap <s-p> gT
nmap <c-n> :set nu!<cr>
filetype plugin indent on
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 21 2019 18:00:45)
Included patches: 1-1906
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.12.9 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lash/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lash/src/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build560198869=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by bhcleek** [comment]
Can you duplicate this on master?

**Comment by bhcleek** [comment]
I also use Vim's native packages to host vim-go and don't see any issue, so I'm pretty sure that's not a relevant factor here, and the fact that `:GoFmt` exists suggests that it i not.

> nothing happened. I tried explicitly setting `let [g:]go_fmt_autosave = 1` and `let [g:]go_fmt_command = goimports"'`. I have run `GoBinaries` - everything's installed, both `gofmt `and `goimports` are available

Why did you spell `let [g:]go_fmt_autosave = 1` with brackets? 🤔 

Autoformatting generally works well. Let's see if we can isolate the problem to whatever may be unique about your configuration...

**Comment by zhangbo1882** [comment]
I have met the same issue after I upgrade the vim-go to the latest version

**Comment by bhcleek** [comment]
closing for lack of feedback

**Comment by hkparker** [comment]
I'm having the same issue, only on Arch Linux.  Seems to be an arch thing, though I haven't been able to figure out why.  Very frustrating.

**Comment by tangblue** [comment]
I'm having the same issue, only on Ubuntu 18.04.
1. Create new file
```
$ vi main.go // save and exit
$ cat main.go 
package main

import "fmt"

func main() {
        fmt.Println("vim-go")
}
```

2. Add new line
```
$ vi main.go // add new line by typing
$ cat main.go 
package main

import "fmt"

func main() {
        fmt.Println("vim-go")
    fmt.Println("vim-go")
}
```

3. The added new line's ident is 4 spaces instead of tab. The following is .vimrc:
```
$ cat ~/.vimrc 
" Comment

set tabstop=4 softtabstop=0 expandtab shiftwidth=4
set hlsearch
set ai
```

**Comment by tangblue** [comment]
According to [Troubleshooting](https://github.com/fatih/vim-go/wiki/FAQ-Troubleshooting), solved the problem by adding the following line to .vimrc:
`filetype plugin indent on`

**Comment by fricklerhandwerk** [comment]
I have the same problem on both macOS 10.14 and NixOS 19.09 in `nvim` managed through [`nix`](https://github.com/NixOS/nix)/[`home-manager`](https://github.com/rycee/home-manager).

Unfortunately the `filetype` directive does not solve the problem in my case. 

Minimal `home.nix` and `init.vim` for reproduction:
```nix
# home.nix
{ pkgs, ... }:
{
  programs.neovim = {
    enable = true;
    extraConfig = "${builtins.readFile ./init.vim}";
    plugins = with pkgs.vimPlugins; [ vim-go ];
  };
  home.packages = with pkgs; [ go ];
}
```
```vim
" init.vim
filetype plugin indent on
```

Just as for @nolash the line
```vim
au BufWritePre,FileWritePre *.go :GoFmt
```
works as a workaround.

How would I go about debugging this issue? Is there any kind of output I can check to see what is happening behind the scenes? I added
```vim
let g:go_debug = [ "shell-commands" ]
```
but cannot see any change. Where should I even find the expected output?

PS: Thank you very much for this plugin. It is a fabulously well-maintained piece of software that does the job so well that for the first time - when it broke in my new setup - I even noticed it is even there!

**Comment by eyJhb** [comment]
@bhcleek  still a problem :) What debug would be useful? Doesn't seem like it runs the command at all.
