### ISSUE TITLE
[Question] Completion with ncm2

### ISSUE THREAD

**Issue by rjshrjndrn** [fatih/vim-go#2474]
Hi,
First of all, thank you for this awesome plugin.
Is there any way to do autocompletion with [ncm2](https://github.com/ncm2/ncm2/)

**Comment by bhcleek** [comment]
I don't know. I'd suggest checking the docs for ncm2 to see how its autocompletion can be configured. If you have specific questions about what vim-go provides, I'm happy to help.

**Comment by rjshrjndrn** [comment]
Thank You.
