### ISSUE TITLE
test error format for wrapped errors using go1.13 or xerrors

### ISSUE THREAD

**Issue by mb0** [fatih/vim-go#2476]
### What did you do?

I wrote go code using the new error wrapping features in tests.

### What did you expect to happen?

Being able to jump to the file location in the quickfix list.

### What happened instead?

I looked for issues, then at the vim-go code and the documentation of vim's error format and added three lines to `vim-go/autoload/go/test.vim`:

```
diff --git a/autoload/go/test.vim b/autoload/go/test.vim
index ff15c8d..ddebf6c 100644
--- a/autoload/go/test.vim
+++ b/autoload/go/test.vim
@@ -222,6 +222,9 @@ function! s:errorformat() abort
   " always have at least one level indentation...
   let format .= ",%A" . indent . "%\\+%f:%l: %m"
   let format .= ",%A" . indent . "%\\+%f:%l: "
+  let format .= ",%C" . indent . "%\\{3}%[%^\ ]%\\+m"
+  let format .= ",%Z" . indent . "%\\{4}%f:%l"
+  let format .= ",%A" . indent . "%\\{2}" . '%\\%(  - %\\)' . "%m:"
   let format .= ",%G" . indent . "%\\{2\\,}%m"
   " }}}1
```
### Why not a pull request?

I am inexperience in vim plugin development and am not sure how to add a new test for this
feature without introducing test dependencies (go1.13 or golang.org/x/xerrors).

I am also not familiar enough with possible incompatibilities with other expected error formats.  The existing tests pass however.

But instead of letting it rot in my dotfiles due to these uncertainties, I put it out here for review and discussion.

Thanks for the great plugin :+1: and have fun!

**Comment by bhcleek** [comment]
Thank you for the contribution. 

Can you give more information about your use case for this? Were you using Go tests?

**Comment by mb0** [comment]
Sure thing. If you use go tests and print extended error information of wrapped errors:
`t.Errorf("my test error: %+v", err)` where error itself uses the new error decoration `fmt.Errorf("decorated message: %w", err)` the output has the following form:
```
--- FAIL: TestTopic (0.00s)
    topic_test.go:42: my test error: decorated message:
            path/to/pkg.(*Type).Method
                /absolute/path/to/pkg/file.go:128
          - original error message
            path/to/otherpkg.(*OtherType).Method
                /absolute/path/to/otherpkg/other.go:77
```

Without the patch the whole block is used as message, not detecting the wrapped file locations.

**Comment by bhcleek** [comment]
Thank you, that's helpful. I'll take a look at some features and see whether or not I think this makes sense to support.

If I do decide to merge it, do you mind if I push any needed changes and tests to your branch?

**Comment by mb0** [comment]
Not having a clone on github right now, but I can create one and send a pull request if that helps.

To advocate for a change, not necessarily this one: Thinking back this feature is the main ~~pain~~ inconvenience point when using vim-go, because most of the locations I want to jump to are part of the wrapped error, not in the test file. It was the one and only thing I checked after updating vim-go the last couple of times. I am just happy if this solves an annoyance for someone else.

Keep up the good work :+1:

**Comment by bhcleek** [comment]
Thanks for the feedback, and I realize now that of course you hadn't created a PR 😀.

**Comment by bhcleek** [comment]
Are you sure you're using the Go 1.13 release? I am unable to duplicate the behavior you're describing. Here's a couple of plays to demonstrate.

* https://play.golang.org/p/7_c3w8qeRZs
* https://play.golang.org/p/by5TWJdtD1t

**Comment by mb0** [comment]
ah ok, that explains it. I am still using a vendored xerrrors package. I though that change made it in.
Before that i used pkg/errors which has a similar feature, I think.

Anyway, sorry for the confusion, i should've checked,  and have a nice sunday.
