### ISSUE TITLE
GoBuild reports success even for some failures

### ISSUE THREAD

**Issue by alexaandru** [fatih/vim-go#248]
Due to how success is determined for GoBuild (and GoRun seems similar, though I don't have a failure test case yet), namely - if there are no errors in the quickfix window, then exist status is considered SUCCESS.

However some failure outputs are not parseable by quickfix (as far as I can tell, quickfix will not do anything without a file path prefix for the error line(s)) then its output is empty and that is regardless of whether the command succeeded or failed.

Failure test case: given a file with content:

```
package main
```

(that is, only the package line, no other code), ```go build``` will return:

```
 # _/home/alex
runtime.main: call to external function main.main
runtime.main: undefined: main.main
```

and an exist status of 2. However, running GoBuild from within Vim will return "[build] SUCCESS". 

We should instead rely on v:shell_error to determine the outcome, regardless of whether there is output or not for quickfix. And also, it would be nice to display ALL output, even if not parseable by quickfix (somehow, no idea how though).

**Comment by fatih** [comment]
I'm closing this as the underlying functions and tools changed a lot. Please re open if you still have the issue with a reproducible case. Thanks!
