### ISSUE TITLE
GoDebugContinue doesnot work in windows 10

### ISSUE THREAD

**Issue by wining** [fatih/vim-go#2481]
### What did you do? (required: The issue will be **closed** when not provided)
I debug the only  file "main.go" in path "E:\GoProjects\src\foo".

The dlv version:
Version: 1.3.0
Build: $Id: 2f59bfc686d60989dcef9de40b480d0a34aa2fa5 $

The commands:
GoDebugStart
GoDebugBreakPoint
GoDebugContinue

### What happened instead
After about 10 more seconds, it disappears as below:
![image](https://user-images.githubusercontent.com/4005513/64486909-02623b00-d266-11e9-909e-696540c14172.png)

#### vim-go version:
The master branch
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
filetype plugin indent on
syntax on

let g:go_fmt_command = "goimports"
let g:go_gocode_unimported_packages = 1
let g:go_list_type = 'quickfix'
let g:go_list_height = 10
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1

</pre></details>

#### Vim version (first three lines from `:version`):

![image](https://user-images.githubusercontent.com/4005513/64486860-47d23880-d265-11e9-82fd-18be43b25f4e.png)

#### Go version (`go version`):

go version go1.12.7 windows/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

set GOARCH=amd64
set GOBIN=E:\GoProjects\bin
set GOCACHE=C:\Users\wining\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\GoProjects\;
set GOPROXY=
set GORACE=
set GOROOT=D:\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\wining\AppData\Local\Temp\go-build108456678=/tmp/go-build -gno-record-gcc-switches

</pre></details>

**Comment by bhcleek** [comment]
There's an error in the delve output there. Perhaps you're not using the version of delve that you think you are. Like last time, can you start vim with `vim -c 'let g:go_debug=['shell-commands']`, duplicate y our problem, and then run the delve command that's output in the directory of the file you're debugging? You can safely elide the `---headless`, `--listen`, and `127.0.0.1:8181` options. 

Note that the command that's output by vim-go will be in an array of quoted strings. Of course, you'll want to convert that to the proper commandline form by removing the square brackets and quotes where appropriate.

**Comment by wining** [comment]
It seems to work well with dlv command.

![image](https://user-images.githubusercontent.com/4005513/64579758-89bec400-d3b6-11e9-9f44-1f369c387150.png)


![image](https://user-images.githubusercontent.com/4005513/64579757-89bec400-d3b6-11e9-8973-7b5162caecea.png)

**Comment by bhcleek** [comment]
Do you see the same problem with `:GoDebugContinue` even when debugging a very simple application? e.g.:

```
package main

func main() {
    println("Hello, vim-go debugger")
}
```

**Comment by wining** [comment]
Yes. The example has the same problem.

**Comment by bhcleek** [comment]
What's the output in the __GODEBUG_OUTPUT__ window when debugging the simple example?

**Comment by wining** [comment]
![image](https://user-images.githubusercontent.com/4005513/64585014-ad3f3a00-d3c9-11e9-8116-ef76d12e7f89.png)

**Comment by wining** [comment]
It seems to work well.  But when the first time run GoDebugContinue, it will stop for about 10 seconds.

**Comment by wining** [comment]
Is this gif helpful?
![GoDebugContinue](https://user-images.githubusercontent.com/4005513/64585364-14112300-d3cb-11e9-81f4-902535bca859.gif)

**Comment by bhcleek** [comment]
The gif doesn't seem to show much else other than what we've already talked about. 🤔

**Comment by wining** [comment]
This issue has not been fixed!
I add some log and find that the function "update_goroutines" and "update_variables" causes this.
It seems that the call "s:call_jsonrpc('RPCServer.State')" and “s:call_jsonrpc('RPCServer.ListGoroutines')”  in function "update_goroutines" are timeout.
Can i add some logs to help you？

**Comment by wining** [comment]
I add echo in function "s:call_jsonrpc" in file "autoload\go\debug.vim".
```vim
function! s:call_jsonrpc(method, ...) abort
...
      call ch_sendraw(l:ch, req_json)
      "debug
      if go#util#HasDebug('debugger-commands')
        call go#util#EchoInfo('before ch_readraw ' . l:req_json)
      endif
      let l:resp_raw = ch_readraw(l:ch)
      "debug
      if go#util#HasDebug('debugger-commands')
        call go#util#EchoInfo('after ch_readraw ' . l:resp_json)
      endif
      let resp_json = json_decode(l:resp_raw)
...

endfunction

```
![image](https://user-images.githubusercontent.com/4005513/71352040-36146700-25b0-11ea-8791-d11786a35819.png)
The three requests in Red box were timeout and had empty replies in windows.

**Comment by bhcleek** [comment]
@wining Can you please open a new issue with this information?

Also, how do you know they were timeouts?

**Comment by bhcleek** [comment]
@wining another piece of information to include in the new issue; are you still seeing the original reported behavior where you saw an error that reads, `Undefined variable`?

**Comment by wining** [comment]
> 
> 
> @wining Can you please open a new issue with this information?
> 
> Also, how do you know they were timeouts?

Because every call of "ch_readraw(l:ch)" will spend 20 seconds.

**Comment by wining** [comment]
> 
> 
> @wining another piece of information to include in the new issue; are you still seeing the original reported behavior where you saw an error that reads, `Undefined variable`?

There is no error reportes. I will create a new issue.
