### ISSUE TITLE
Make GoDoc run in the background

### ISSUE THREAD

**Issue by preslavmihaylov** [fatih/vim-go#2482]
Running `:GoDoc` makes my vim session block as it is not ran in the background. This might not be an issue for small codebases, where the blocking call is quick enough, but it causes frustration when using the command on larger codebases.

It would be great if `:GoDoc` runs in the background, without blocking my editor, similar to how  the guru-related commands work (e.g. `:GoReferrers`)

#### vim-go version:
v1.21

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
""" -------------------- vim-go -------------------------
" all errors are shown in the quickfix window
let g:go_list_type = "quickfix"

" automatically add import paths when saving file
"let g:go_fmt_command = "goimports"

" enable syntax highlighting
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1

" enable go metalinter
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']

" let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave_enabled = ['vet', 'errcheck']
let g:go_metalinter_autosave = 1

" run go imports on file save
let g:go_fmt_command = "goimports"

" don't jump to errors after metalinter is invoked
let g:go_jump_to_error = 0

" default metalinter is deprecated. Change to better alternative
let g:go_metalinter_command='golangci-lint'

" use gopls for go to definition and get info commands
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'

" vim-go debug: show shell commands being executed
" let g:go_debug=['shell-commands']

" automatically show GoInfo output
" let g:go_auto_type_info = 1

" automatically highlight variable your cursor is on
let g:go_auto_sameids = 1

" adjust quickfix window height
let g:go_list_height = 8

" terminal opens as a horizontal split below the main window
let g:go_term_mode = "split above"

" More verbose output on failed tests in quickfix window
let g:go_test_show_name = 1
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.8

#### Go version (`go version`):

go version go1.13 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pmihaylov/Library/Caches/go-build"
GOENV="/Users/pmihaylov/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pmihaylov/programming/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9v/vvj1r6_54pb855bvmtqv3wn80000gn/T/go-build035595188=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment]
I regularly use vim-go on a large codebase, and I don't see `:GoDoc` taking too long, though "too long" can be subjective. Can you give me an example of a large code base that demonstrates the problem you're seeing?

A profile might be helpful here:

```
:profile start profile.log
:profile func *
:profile file *
" At this point do :GoDoc
:profile pause
:noautocmd qall!
```

**Comment by preslavmihaylov** [comment]
So I just went through the steps you told me.

Here is the output: https://pastebin.com/0Aae8jLT

The TLDR; of that paste is this:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1  28.520051   0.000056  go#doc#Open()
    1  28.503653   0.000193  <SNR>109_gogetdoc()
    1  28.503392   0.000060  go#util#Exec()
    1  28.503107   0.000082  <SNR>52_exec()
    1  28.502963   0.000094  <SNR>52_system()
  134   0.116757             provider#python3#Call()
  115   0.076129   0.008981  <SNR>71_ReceiveMessages()
  120   0.070452             <SNR>71_Pyeval()
...
```

So I'd guess around 28s is the total time GoDoc takes on my environment.

Here are some things that might help figure out where this comes from:
1. The codebase is proprietary and not hosted on `github.com` or any `godoc.org` index.
2. Running `:GoDoc` initially takes that much time, but running it on the same function multiple times makes it significantly faster (<1s). Perhaps there is some kind of caching
3. Running `:GoDoc` in the same codebase, but on functions which are from open-source packages (e.g. `github.com/pkg/errors`) works fine

**Comment by bhcleek** [comment]
> Running :GoDoc initially takes that much time, but running it on the same function multiple times makes it significantly faster (<1s).

I think this is probably the key. Are you in GOPATH mode or module aware mode? What's the value of `GO111MODULE` and what's the output of `go env` when run in your package directory? Also, knowing the information that the issue template prompted you for would be helpful: vimrc, Go version, vim-go version, etc.

**Comment by preslavmihaylov** [comment]
I just filled out the configuration in the issue description.

I'm in `GOPATH` mode and modules are off in `GOPATH`.

Another remark:
4. I am using `dep` for package management

**Comment by bhcleek** [comment]
Is it _always_ slow the first time you run `:GoDoc` in a vim session, or is it only slow when your code has changed since you last ran `:GoDoc`? And if it _is_ slow when your code has changed since you last `:GoDoc`, is `:GoDoc` faster if you run `:GoBuild` first?

**Comment by preslavmihaylov** [comment]
It's slow without any code changes. Running `:GoBuild` did not cause any significant improvement.

**Comment by nguyenhoaibao** [comment]
Hi @bhcleek, I have the same issue, `:GoDoc` is very slow on my machine.

Here is the profile.log
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1  32.417666   0.000054  go#doc#Open()
    1  32.407363   0.000059  <SNR>152_gogetdoc()
    1  32.407275   0.000041  go#util#Exec()
    1  32.407011   0.000078  <SNR>74_exec()
    1  32.406885   0.000098  <SNR>74_system()
   11   0.022047             lightline#link()
    1   0.010248   0.000663  <SNR>152_GodocView()
    7   0.009454   0.003099  <SNR>99_line()
    3   0.007872   0.000213  lightline#update()
    5   0.007659   0.000082  lightline#statusline()
```

<details><summary>My<code>go env</code> </summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bao/.cache/go-build"
GOENV="/home/bao/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bao/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="whatever"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build019855668=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

> Is it always slow the first time you run :GoDoc in a vim session

Yes.

> is :GoDoc faster if you run :GoBuild first?

No it isn't. Godoc still slow even when I run `:GoBuild` first.

**Comment by danishprakash** [comment]
@bhcleek can we use `jobs` to make this async at least for vim/nvim versions that support jobs? Is there a specific reason to not have this asyn apart from backwards compatibility?

**Comment by bhcleek** [comment]
Making it async when possible is an option. My only concern is that the concern will go from "it locks up my system," to "it doesn't do anything," especially if it's taking 30 seconds to get the doc.

**Comment by danishprakash** [comment]
That makes sense but I'm not so sure about putting on hold the entire session for that much time. We can, for that matter, let the user know that the job is running in the background via some message on the command line. What do you think?

**Comment by preslavmihaylov** [comment]
GoReferrers works the same way I would expect GoDoc to work after implementing this. It’s true that Im not using GoReferrers anymore as it takes >30s for simple queries. 

But at least for GoDoc, it works okay for some of the queries so I would still use it

**Comment by bhcleek** [comment]
@danishprakash it will definitely have progress messages; all the jobs that vim-go executes display status to the user.

@preslavmihaylov give `:GoReferrers` another try if you're using latest master; I recently refactored it to use `gopls` under the hood, and it's much faster now.

**Comment by preslavmihaylov** [comment]
Oh I wasn’t aware that you migrated GoReferrers to gopls. Thanks for letting me know, I will give it another try

**Comment by danishprakash** [comment]
@bhcleek In that case, I think we can have it as an option and not enforce it.

**Comment by bhcleek** [comment]
Have what as an option?

**Comment by danishprakash** [comment]
Sorry, I meant having run `:GoDoc` async as an option and not enforce it all the time.

**Comment by bhcleek** [comment]
There's no need for an option; if jobs are available, it should be async and synchronous otherwise.

**Comment by danishprakash** [comment]
I'm willing to take this up in that case, I was just thinking about a point of yours you made previously:

> My only concern is that the user report will go from "it locks up my system," to "it doesn't do anything," especially if it's taking 30 seconds to get the doc.

**Comment by bhcleek** [comment]
Closing, because this the reported issue was in the gogetdoc code path, which has been replaced with gopls, which is much snappier.
