### ISSUE TITLE
Prompt user for confirmation when uploading snippet to play.golang.org.

### ISSUE THREAD

**Issue by yangmillstheory** [fatih/vim-go#2492]
Simple request: prompt the user for confirmation when `:GoPlay` is called. 

Currently no confirmation is required, so this is a security risk, since uploaded code can be private, but the play.golang.org is public. We should make the risk absolutely clear to the user.

**Comment by bhcleek** [comment]
This was previously discussed in #1615. You may be interested in Fatih's answer on that issue: https://github.com/fatih/vim-go/issues/1615#issuecomment-351929088
