### ISSUE TITLE
nvim: GoUpdateBinaries fails for keyify

### ISSUE THREAD

**Issue by dvrkps** [fatih/vim-go#2493]
### What did you do? (required: The issue will be **closed** when not provided)

:GoUpdateBinaries

### What did you expect to happen?

No errors

### What happened instead?

<details><pre>

vim-go: Updating keyify. Reinstalling honnef.co/go/tools/cmd/keyify to folder /Users/davor/bin/
Error downloading honnef.co/go/tools/cmd/keyify: get "honnef.co/go/tools/cmd/keyify": found meta tag get.metaImport{Prefix:"honnef.co/go/tools", VCS:"git", RepoRoot:"https://github.com/dominikh/go-tools"} at //honnef.co/go/tools/cmd/keyify?go-get=1^@get "honnef.co/go/tools/cmd/keyify": verifying non-authoritative m
eta tag^@honnef.co/go/tools (download)^@# cd /Users/davor/src/honnef.co/go/tools; git pull --ff-only^@You are not currently on a branch.^@Please specify which
 branch you want to merge with.^@See git-pull(1) for details.^@^@    git pull <remote> <branch>^@^@package honnef.co/go/tools/cmd/keyify: exit status 1^@
</pre></details>

#### vim-go version:
latest
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):
nvim v0.4.2

#### Go version (`go version`):
v1.13

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/davor/Library/Caches/go-build"
GOENV="/Users/davor/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/davor"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9h/yvy5nvq917n_xcbth_j21kkh0000gn/T/go-build630519607=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by bhcleek** [comment]
It looks like you may have keyify in your GOPATH already and a detached head checked out. Can you verify, and if a detached head is checked out, checkout its master branch and then try `GoUpdateBinaries` again.
