### ISSUE TITLE
ctags /gotags stopped working

### ISSUE THREAD

**Issue by ehrktia** [fatih/vim-go#2496]
### What did you do? (required: The issue will be **closed** when not provided)
started new project outside $GOPATH and ran Ctags -R . command in terminal to generate tag file .  
tag file was empty so added support to go in Ctags using custom ~/.ctags file.   
Tag generation was successful after custom tag file .  
when trying to jump to defn using `C-] ` command the following error message is flashing  
`vim-go: initialized gopls  
vim-go: [definition] FAIL  
vim-go: method "textDocument/definition" did not reply  `
## gopls 
had updated gopls and re-tried no luck.  
same with previous projects as well.  
Tags stopped working completely.  
**NOTE** - When manually grepped the tag file the required tag was present in the file.  

### What did you expect to happen?
expecting to jump to the tag generated.
### What happened instead?
received error in message 
`vim-go: initialized gopls  
vim-go: [definition] FAIL  
vim-go: method "textDocument/definition" did not reply `
### Configuration (**MUST** fill this out):
osx -10.14.6  
vim  version : 
`VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  8 2019 07:17:45)
macOS version
Included patches: 1-1999
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
`
#### vim-go version:
latest - v.1.2.1  
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>
`let g:go_updatetime = 800
let g:go_doc_keywordprg_enabled = 1
let g:go_doc_max_height = 20
let g:go_snippet_engine = "automatic"
let g:go_get_update = 1
let g:go_def_mapping_enabled = 1
let g:go_list_type = "quickfix"
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
"let g:go_metalinter_command='golangci-lint'
"Ultisnip mappings
let g:UltisnipUsePythonVersion = 3
let g:UltiSnipsExpandTrigger="<c-j>" 
let g:UltiSnipsListSnippets="<c-tab>"
let g:UltiSnipsJumpForwardTrigger="<c-h>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"
"Fugitive git leader mappings
:nmap <Leader>gs  :Gstatus<CR>
:nmap <Leader>gd  :GDoc
:nmap <Leader>gb  :Gbrowse<CR>
:nmap <Leader>gpu  :Gpush<CR>
:nmap <Leader>gsd :Gsdiff<CR>
:nmap <Leader>ga :Git add -- .<CR>
"vimgo mappings
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
:nmap <Leader>ga :GoAlternate<CR>
autocmd FileType go nmap <leader>r  <Plug>(go-run)
autocmd FileType go nmap <leader>b  <Plug>(go-build)
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
:nmap <Leader>gl :GoMetaLinter<CR>
:nmap <Leader>gd :GoDebugStart<CR>
`

#### Vim version (first three lines from `:version`):

`VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  8 2019 07:17:45)
macOS version
Included patches: 1-1999
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
`

#### Go version (`go version`):

go version go1.13 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/karthickayyapillai/Library/Caches/go-build"
GOENV="/Users/karthickayyapillai/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/karthickayyapillai/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wk/2mxs2gf122x1knb02422fwcw0000gn/T/go-build185965872=/tmp/go-build -gno-record-gcc-switches -fno-common"`
</pre></details>

**Comment by bhcleek** [comment]
vim-go doesn't use tags files for jumping to definitions.

Can you provide some more details on how to duplicate the error you're seeing? (e.g. path to a file to jump from and path to a file to jump _to_, perhaps a simple reproduction case with code).

How did you update `gopls`?

Finally, this _might_ be related to https://github.com/golang/go/issues/34298.

**Comment by ehrktia** [comment]
`goals`
went in to $GOPATH in terminal and ran the following command
`go get -u golang.org/x/tools/cmd/gopls`
`go install golang.org/x/tools/cmd/gopls`
output of `gopls version` command
` version v0.1.6-cmd.gopls, built in $GOPATH mode`

**Comment by ehrktia** [comment]
thanks very much 👍 some how it started working again now.
i did install govim and remove it from system.
All went fine left the vimrc with C-] mapping i had created for govim.

**Comment by bhcleek** [comment]
Just FYI: installing gopls that way will install its master, which may be in a broken state. You can install using `go get golang.org/x/tools/gopls@latest` at the command line or `:GoUpdateBinaries gopls` from within vim with vim-go to install the latest release of gopls.

**Comment by ehrktia** [comment]
thanks bhcleek for your additional info.
