### ISSUE TITLE
Passing flags to vet?

### ISSUE THREAD

**Issue by AckslD** [fatih/vim-go#2498]
### What did you do?
This is a question: Can I pass arguments to vet? For example can I disable the following warning
```
composites: `package/module.Struct` composite literal uses unkeyed fields (govet)
```
This can be done from terminal as `go vet -composites=false .`, however I don't know how to set this in the settings.

**Comment by bhcleek** [comment]
Yes, you can pass flags to `go vet` with `:GoVet`: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L243-L254

**Comment by AckslD** [comment]
Thanks for your reply @bhcleek! What about when using `let g:go_metalinter_autosave = 1`?
