### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by DAddYE** [fatih/vim-go#250]
Hello there!

I was looking for `GoOracle` and I didn't find the command anymore. What happened? 

I found that now the lines are commented: https://github.com/fatih/vim-go/blob/master/ftplugin/go/commands.vim#L79-L88

However I remember I saw a recent PR for improving oracle support.

**Comment by yasker** [comment]
Thank you Fatih for this brilliant work! I hope `:GoCallers` can be the next one in the queue since I found it would be another essential tool to read the code.

**Comment by hoffoo** [comment]
:+1: for :GoCallers

**Comment by ghodss** [comment]
+1 for :GoCallers as well

**Comment by fatih** [comment]
I've created a branch that supports all Oracle commands. I am no longer using a custom UI, instead I'm parsing Oracle's `plain` format. After the PR #311, I've rethought my initial decision and decided to go with a simpler way (using quickfix). I've tested each mode extensively and they all work perfectly. For testing you can use the following example file that I've used for testing it. I also added documentation for each mode, of course more info can be find in the [Oracle User Manual](golang.org/s/oracle-user-manual).

Example file to test all Oracle modes:

```go
package main

import "fmt"

type Storage interface {
	Get() string
}

func main() {
	fmt.Println("vim-go")

	i := &intStorage{}
	s := &stringStorage{}

	done := make(chan bool)

	callStorage(i, done)
	callStorage(s, done)
	<-done

}

func callStorage(s Storage, done chan bool) {
	res := s.Get()
	fmt.Printf("res = %+v\n", res)

	a := 5
	foo(a)

	done <- true
}

type intStorage struct{}

func (i *intStorage) Get() string {
	return "intStorage"
}

type stringStorage struct{}

func (s *stringStorage) Get() string {
	return "stringStorage"
}

func foo(b int) {
	fmt.Println("b", b)
	bar()
}

func bar() {
	fmt.Println("fatih arslan")
}
```

I'll going to merge the pr #319 soon. Please test and any feedback is welcome :)

**Comment by yasker** [comment]
Wow, it works great for me! Still using it but so far so great! Thank you Faith!

**Comment by fatih** [comment]
Oracle support landed now into the master branch.

**Comment by ghodss** [comment]
Just want to pile on thanks for this, this feature is AWESOME, very well done!

**Comment by akavel** [comment]
Would you accept it if I sent a PR for the *referrers* subcommand, so that actual referring lines from the source files would be shown in the quickfix window, as in [my earlier PR](https://github.com/akavel/vim-go/commit/0d2c2e32c2a6eb39a41c17ca0be0f810480d4542)? I find it much easier and more useful to browse e.g. a list like below (similar to regular grep results):

    rsrc.go|196 col 6| defined here as func main.write(coff *github.com/akavel/rsrc/coff.Coff, fnameout string) error
    rsrc.go|109 col 8| referenced in: err = write(coff, fnameout)
    rsrc.go|160 col 9| referenced in: return write(coff, fnameout)

instead of current:

    rsrc.go|196 col 6| defined here as func main.write(coff *github.com/akavel/rsrc/coff.Coff, fnameout string) error
    rsrc.go|109 col 8| referenced here
    rsrc.go|160 col 9| referenced here

**Comment by fatih** [comment]
@akavel any reason the first iteration seems to be incomplete or bad for you? I'm just asking because currently it's really easy to parse the output in `plain` mode. By **not** adding any filtering it's simple. And I'm always in favor of simplicity in those cases. However I'm open to any suggestions as always.

**Comment by akavel** [comment]
I'm not sure if I understand the question. Trying to answer, or rephrase my previous comment: the current version is generally ok (works well), but I'd really like to add an improvement, specifically in the "oracle referrers" command output. I'd like it to extend the output of the oracle (in the quickfix window) with a line copied verbatim from the Go file which is referenced by the line.

The current iteration is thus incomplete for me by missing this information (context). Currently, when using "referrers", I have to iterate over each "`referenced here`" result, and follow it (by pressing <kbd>Enter</kbd> in the quickfix window, or typing `:cn` in main window) to examine the referring place. If the contents of each line was shown in the quickfix window, I'd be able to easily ignore many of the referring places and focus only on those which look most interesting. That'd save me significant time in those cases when I need to use "referrers". (Already had at least one such situation in real usage.)

Did I manage to make it more clear now?
