### ISSUE TITLE
neovim: term close on exit - not closing

### ISSUE THREAD

**Issue by robjloranger** [fatih/vim-go#2505]
### What did you do? (required: The issue will be **closed** when not provided)

I set up vim-go with neovim.

I ran `GoTest` and `GoTestFunc` with `go_term_enabled = 1` and after the tests pass, the terminal stays open. I tried explicitly setting `go_term_close_on_exit = 1` with no luck. This was also checked with all plugins disabled **except** vim-go.

### What did you expect to happen?

I thought the terminal window would close after the tests completed, whether with failure or success.

### What happened instead?

The window remains and I have to switch to and close it.

If I switch to the window before the tests end there is an error in the quickfix:
```
Error detected while processing function <SNR>153_on_exit:              
line    6:
E472: Command failed
Press ENTER or type command to continue
```

#### vim-go version:

1.21

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

<details><summary>vimrc</summary><br><pre>
" plugins
call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'for': ['go', 'javascript'], 'do': ':UpdateRemotePlugins' }
Plug 'deoplete-plugins/deoplete-go', { 'for': ['go', 'javascript'], 'do': 'make' }
Plug 'fatih/vim-go', { 'for': ['go', 'gohtmltmpl', 'gotexttmpl'], 'do': ':GoUpdateBinaries' }
Plug 'AndrewRadev/splitjoin.vim', { 'for': 'go' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'majutsushi/tagbar', { 'for': ['go', 'javascript'] }
Plug 'levelone/tequila-sunrise.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-commentary', { 'for': ['go', 'javascript'] }
Plug 'Raimondi/delimitMate', { 'for': ['go', 'javascript'] }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
Plug 'vim-scripts/grep.vim'
call plug#end()

" general settings
set autowrite
set number
set hidden
set splitbelow
let mapleader = ","
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set backspace=indent,eol,start
nnoremap <silent> <leader><space> :noh<cr>
set hlsearch
set incsearch
set ignorecase
set smartcase

" style and theme
colorscheme tequila-sunrise
set colorcolumn=80,160

" key bindings
map <C-m> :cnext<CR>
map <C-p> :cprevious<CR>
noremap <Leader>h :<C-u>split<CR>
noremap <Leader>v :<C-u>vsplit<CR>
nnoremap <leader>q :bp<CR>
nnoremap <leader>w :bn<CR>
nnoremap <leader>x :bd<CR>
nnoremap <leader>a :cclose<CR>
nnoremap <leader>c :close<CR>
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
noremap <C-h> <C-w>h
vmap < <gv
vmap > >gv
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
nnoremap <leader>e :FZF -m<CR>
nnoremap <leader>sh :20split<CR>:terminal<CR>
" terminal specific
tnoremap <Esc> <C-\><C-n>

" deoplete
let g:deoplete#enable_at_startup = 1

" vim airline
let g:airline_theme='minimalist'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" nerd tree
let g:NERDTreeQuitOnOpen = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeDirArrows = 1
let g:NERDTreeWinSize = 50

map <C-n> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" tagbar
map <F8> :TagbarOpenAutoClose<CR>

" vim-go
let g:go_fmt_command = "goimports"
let g:go_auto_sameids = 1
let g:go_test_show_name = 1
let g:go_term_enabled = 1
let g:go_term_mode = "split"
let g:go_term_height = 20
let g:go_term_close_on_exit = 1
let g:go_list_type = "quickfix"
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1

autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go nmap <leader>r <Plug>(go-run)
autocmd FileType go nmap <leader>tt :GoTest -v<CR>
autocmd FileType go nmap <leader>tf :GoTestFunc -v<CR>
autocmd FileType go nmap <leader>tc <Plug>(go-coverage-toggle)
autocmd FileType go nmap <leader>i <Plug>(go-info)
autocmd FileType go nmap <leader>gd <Plug>(go-doc)

" grep.vim
nnoremap <silent> <leader>f :Rgrep<CR>
let Grep_Default_Options = '-IR'
let Grep_Skip_Files = '*.log *.db'
let Grep_Skip_Dirs = '.git node_modules'

"" fzf.vim
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.pyc,__pycache__
let $FZF_DEFAULT_COMMAND =  "find * -path '*/\.*' -prune -o -path 'node_modules/**' -prune -o -path 'target/**' -prune -o -path 'dist/**' -prune -o  -type f -print -o -type l -print 2> /dev/null"

""""""""" helper functions

" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

1.12.9

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/robbie/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/robbie/go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/4301"
GOTMPDIR=""
GOTOOLDIR="/snap/go/4301/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build907287327=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
The terminal window is only closed when the command run in it fails for some reason; that's by design. I've created #2508 to clarify the documentation and to resolve the problem that you noticed when you change windows before the command finishes.

**Comment by robjloranger** [comment]
awesome, that makes sense then. Thanks @bhcleek
