### ISSUE TITLE
:GoReferrers  too slow and high CPU usage

### ISSUE THREAD

**Issue by mengyaoss77** [fatih/vim-go#2509]
### What did you do? (required: The issue will be **closed** when not provided)
:GoReferrers command on a function.

If possible, please provide clear steps for reproducing the problem.
-->

### What did you expect to happen?
return references quickly

### What happened instead?
GoReferrers never returns while CPU load 100% for a long time

#### vim-go version:
latest
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
syntax on
set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin('~/.vim/plugged')

Plug 'vim-scripts/a.vim'
Plug 'Yggdroot/LeaderF'
Plug 'airblade/vim-gitgutter'
Plug 'ludovicchabant/vim-gutentags'	" Auto tags
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
Plug 'gruvbox-community/gruvbox'
Plug 'Chiel92/vim-autoformat'
Plug 'scrooloose/nerdcommenter'
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

filetype plugin indent on    " required
" Vim-go 
let g:go_template_autocreate = 0
let g:go_fmt_command = 'goimports'
"let g:go_highlight_types = 1
"let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
"let g:go_highlight_function_calls = 1
let g:go_code_completion_enabled = 0
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 21 2019 18:00:45)
包含补丁: 1-1906
编译者 Arch Linux
#### Go version (`go version`):

go version go1.13 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xx/.cache/go-build"
GOENV="/home/xx/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build490897727=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by mengyaoss77** [comment]
Maybe it's problem from guru.

**Comment by mengyaoss77** [comment]
Finding references using vscode with guru is real faster than vim-go. So strange

**Comment by bhcleek** [comment]
Do you have more information to provide? Have you tried running the guru command manually as I suggested previously?

**Comment by mengyaoss77** [comment]
> Do you have more information to provide? Have you tried running the guru command manually as I suggested previously?

Yes，vim-go shows the command is 
'xxxxx/go/bin/guru', '-tags', '', 'referrers', 'xx/go/src/xxx/xxx/xx.go:#1660' 
then I run this command in terminal, htop shows guru uses 100% of my CPU. At the same time, I use vscode to find references, htop shows a different command:
guru -modified referrers xx/go/src/xxx/xxx/xx.go:#1660

**Comment by bhcleek** [comment]
I'm curious what happens if you run the guru command twice at the command line; is performance better the second time?

vscode may use a different command than vim-go if you have unsaved changes to the file in vscode; `-modified` is used when the buffer has unsaved changed.

**Comment by mengyaoss77** [comment]
> I'm curious what happens if you run the guru command twice at the command line; is performance better the second time?
> 
> vscode may use a different command than vim-go if you have unsaved changes to the file in vscode; `-modified` is used when the buffer has unsaved changed.

I do not run the guru command twice in terminal. I do these below:
1.  run ' guru -tags '' referrers xxx/xxx/xxx.go:#893' in terminal (now cpu usage is high)
2. Then use 'Find All References' in VSCODE on same place of code ( Because of my computer is slow now, so I can see a new command ' guru -modifed .....' in htop, but the file is not modified, and the result in vscode is returned earlier than in terminal

**Comment by bhcleek** [comment]
I can't comment on what vscode does or when it chooses to use `-modified`. Vim-go will use `-modified` when your buffer has unsaved changes.

In any case, please try running the guru command in the terminal twice; the cpu usage patterns here are not being driven by vim-go.
