### ISSUE TITLE
popup window for godoc doesn't work in neovim

### ISSUE THREAD

**Issue by smartding** [fatih/vim-go#2513]
### What did you do? (required: The issue will be **closed** when not provided)

run the K and GoDoc command

### What did you expect to happen?

with `g:go_doc_window_popup_window=1` in my vimrc, I expect the godoc info to show in a popup window

### What happened instead?

the godoc info showed up in a separate preview window

#### vim-go version:

latest commit: 1bb46522d5a0568c40761a06c19b79c65233171b

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

let g:go_doc_window_popup_window             = 1
let g:go_fmt_command        = 'goimports'     
let g:go_def_mode           = 'gopls'         
let g:go_metalinter_command = 'golangci-lint' 

</pre></details>

#### Vim version (first three lines from `:version`):

neovim 0.4.2
#### Go version (`go version`):

1.12.9
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/home/smart/go/bin"
GOCACHE="/home/smart/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/smart/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build042217035=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by bhcleek** [comment]
The option is `g:go_doc_popup_window`, not `g:go_doc_window_popup_window`.

**Comment by smartding** [comment]
> The option is `g:go_doc_popup_window`, not `g:go_doc_window_popup_window`.

thanks, popup works after changing the option name.
It seems the option name changed a few days ago.

**Comment by bhcleek** [comment]
The option name has not changed, it was just spelled wrong in the changelog.
