### ISSUE TITLE
vim-go: could not determine appropriate working directory for gopls

### ISSUE THREAD

**Issue by chadcao** [fatih/vim-go#2517]
### What did you do? (required: The issue will be **closed** when not provided)

When I use vim to oepn a golang file (*.go), it show error message:
vim-go: could not determine appropriate working directory for gopls
Press ENTER or type command to continue

After I pressed ENTER to continue, the file can still be opened and it seems VIM-go works fine

### What did you expect to happen?

I do not want that error message to appear "vim-go: could not determine appropriate working directory for gopls"

### Configuration (**MUST** fill this out):
" My Plugins                                                                                |  1
Plugin 'VundleVim/Vundle.vim'                                                               |~
Plugin 'altercation/vim-colors-solarized'                                                   |~
Plugin 'tomasr/molokai'                                                                     |~
Plugin 'Lokaltog/vim-powerline'                                                             |~
Plugin 'octol/vim-cpp-enhanced-highlight'                                                   |~
Plugin 'junegunn/vim-easy-align'                                                            |~
Plugin 'scrooloose/nerdtree'                                                                |~
Plugin 'jistr/vim-nerdtree-tabs'                                                            |~
Plugin 'Xuyuanp/nerdtree-git-plugin'                                                        |~
Plugin 'majutsushi/tagbar'                                                                  |~
Plugin 'jiangmiao/auto-pairs'                                                               |~
Plugin 'vim-airline/vim-airline'                                                            |~
Plugin 'Valloric/YouCompleteMe'                                                             |~
Plugin 'airblade/vim-gitgutter'                                                             |~
Plugin 'SirVer/ultisnips'                                                                   |~
Plugin 'honza/vim-snippets'                                                                 |~
Plugin 'vim-scripts/SuperTab'                                                               |~
Plugin 'fatih/vim-go'                                                                       |~
Plugin 'dgryski/vim-godef'   

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

**Comment by chadcao** [comment]
the issue is closed.
The root cause is because the /tmp directory on my service does not exist which caused Go did not work

**Comment by AugustusKwan** [comment]
> the issue is closed.
> The root cause is because the /tmp directory on my service does not exist which caused Go did not work

I am facing the same issue. How did you fix this problem? I raise the new issue #3065 . My OS platform is Win10 1909.
