### ISSUE TITLE
Suggestion: Use separated interval for AutoTypeInfo/AutoSameids other than updatetime

### ISSUE THREAD

**Issue by delphinus** [fatih/vim-go#2524]
### What did you do?

1. Prepare vimrc

   ```vim
   set runtimepath+=~/test/vim-go
   ```

2. Launch (Neo)Vim with clean env.

   ```sh
   nvim -N -u vimrc  -i NONE new_file.txt
   ```

2. You can see the default value set to `updatetime`.

   ```vim
   :set updatetime?
   4000
   ```

3. Open `*.go` files in a new buffer.

   ```vim
   :sp another.go
   ```

4. You can see the value from `vim-go` set to `updatetime`.

   ```vim
   :set updatetime?
   800
   ```

5. Press `<C-w>w` and return to the original window: `new_file.txt`.

6. You can see `updatetime` set to the value from `vim-go`!

   ```vim
   :set updatetime?
   800
   ```

### What is the problem?

#1055 introduced the `g:go_updatetime` variable and @svanharmelen should have intended to limit the scope of `updatetime` into a buffer-local one.

But `updatetime` is a global option. You cannot use it as buffer-local.

### Suggestion

I think this is not the case to use `updatetime`. The option is used for many other plugins and `vim-go` should not depend on it.

I suggest to rewrite the logic with the `timer` feature.

1. Call func on `CursorMoved`.
2. In the func, call `timer_start()` and wait some interval.
3. After interval, do the job (ex. `AutoTypeInfo`, `AutoSameids`)

(I wrote a tiny plugin with using similar logic: [vim-auto-cursorline](https://github.com/delphinus/vim-auto-cursorline).)

I will write PR if you approve this plan.

#### vim-go version:

e50c575

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

(see above)

#### Vim version (first three lines from `:version`):

```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
```

**Comment by bhcleek** [comment]
I agree that it should user a timer, and I think your basic plan is correct. However, it should probably be modified slightly:

1. Call func on CursorMoved.
1. In the func, cancel the previously scheduled timer and then call timer_start() and wait some interval.
1. After interval, do the job (ex. AutoTypeInfo, AutoSameids)
