### ISSUE TITLE
Environment problems with vim-go and GOPATH

### ISSUE THREAD

**Issue by jabalsad** [fatih/vim-go#2528]
### What did you do? (required: The issue will be **closed** when not provided)
`:GoUpdateBinaries`

### What did you expect to happen?
The binaries update successfully.

### What happened instead?
```
vim-go: Updating gogetdoc. Reinstalling github.com/zmb3/gogetdoc to folder /Users/jleroux/code/go/bin/
vim-go: Error downloading github.com/zmb3/gogetdoc: package github.com/zmb3/gogetdoc: cannot download, $GOPATH must not be set to $GOROOT. For more details see: 'go help gopath'
vim-go: Error installing github.com/zmb3/gogetdoc: can't load package: package github.com/zmb3/gogetdoc: cannot find package "github.com/zmb3/gogetdoc" in any of:
vim-go:         /Users/jleroux/code/go/src/github.com/zmb3/gogetdoc (from $GOROOT)
vim-go:         ($GOPATH not set. For more details see: 'go help gopath')

[snip snip - repeated for all go binaries]
```

Output of `:echo $GOPATH`: `/Users/jleroux/code/go`
Output of `:echo $GOROOT`: ` `

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'fatih/vim-go'
call vundle#end()            " required
</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 30 2019 02:59:45)
macOS version
Included patches: 1-2100

#### Go version (`go version`):
go version go1.13.1 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
› go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jleroux/Library/Caches/go-build"
GOENV="/Users/jleroux/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jleroux/code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2b/5sdbq5sd49d0s7yj01l14fg49cq5nf/T/go-build926859059=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

# Things I've tried:

- uninstalling and reinstalling vim-go
- reinstalling go
- upgrading vim & go
- running `go get -u github.com/zmb3/gogetdoc` in the terminal (it succeeds)
- starting vim with `GOPATH=/Users/jleroux/code/go vim`

**Comment by bhcleek** [comment]
It looks like you don't have `GOPATH` set. Are you using the gvim on macOS?

**Comment by bhcleek** [comment]
This is really odd. The only thing I see that might be a clue to the root cause is the `$GOPATH must not be set to $GOROOT` message. 🤔 

What version of vim-go are you using?

**Comment by bhcleek** [comment]
closed for lack of feedback

**Comment by ViRu-ThE-ViRuS** [comment]
This is still an active issue... :GoUpdateBinaries always installs dependencies to ~/go no matter what the $GOPATH (or $GOBIN, $GOROOT) is set to
