### ISSUE TITLE
support staticcheck

### ISSUE THREAD

**Issue by bhcleek** [fatih/vim-go#2538]
Support staticcheck as a metalinter.

#### acceptance criteria
* staticcheck is supported as a metalinter
* staticcheck is supported as a metalinter for autosaving

#### open questions
* should the `g:go_metalinter_enabled`, `g:go_metalinter_disabled`, and `g:go_metalinter_autosave_enabled` options apply to staticcheck? If so, should `g:go_metalinter_autosave_disabled` be allowed, too? Given staticcheck's config support, perhaps these don't make sense to use at all.

**Comment by bhcleek** [comment]
gopls is adding support for staticcheck, so instead of adding support as a metalinter, this will probably be done by adding support for surfacing the gopls diagnostics in a quickfix and/or location list.

**Comment by ahuret** [comment]
Should it be possible to surface error not with  `:GoDiagnostic`, but when cursor is over the error ? ( and see error surfacing below, the same way vim give information about saving file etc.) thx !
