### ISSUE TITLE
Why :GoBuild is not for go build command?

### ISSUE THREAD

**Issue by Cornos** [fatih/vim-go#2539]
Hello, I have a general question here, I don't get it why :GoBuild don't stand for go build command on vim-go.
Why :GoBuild don't generate an output file and we need to do :Make otherwise

If someone can explain me cause I even don't get what :GoBuild do and help :GoBuild doesn't helped me :)

**Comment by bhcleek** [comment]
> I don't get it why :GoBuild don't stand for go build command on vim-go.

`:GoBuild` does call `go build`. vim-go also configured `&makeprg` in https://github.com/fatih/vim-go/blob/master/compiler/go.vim so that you can use `:Make` if you want.

> Why :GoBuild don't generate an output file and we need to do :Make otherwise

To avoid littering your system with files.

**Comment by Cornos** [comment]
Thank you for your response
> To avoid littering your system with build output.
So what :GoBuild do?

**Comment by Cornos** [comment]
I get it thank you Billie
