### ISSUE TITLE
Differentiate between functions and other blocks for folding

### ISSUE THREAD

**Issue by hupfdule** [fatih/vim-go#2551]
### What did you do? (required: The issue will be **closed** when not provided)

```vim
let g:go_fold_enable = ['block', 'import', 'varconst', 'package_comment']
setlocal foldmethod = syntax
```

### What did you expect to happen?

I expected functions to be folded, but other block constructs (like, if-blocks, switches, etc.) not to be folded.

### What happened instead?

All blocks are folded.

### Configuration (**MUST** fill this out):

(like written above)
```vim
let g:go_fold_enable = ['block', 'import', 'varconst', 'package_comment']
setlocal foldmethod = syntax
```

#### vim-go version:

v1.21

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
setlocal foldmethod=syntax
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401

or 

Neovim v0.4.2

#### Go version (`go version`):

1.13

#### Go environment

not relevant

---

The problem is that vim-go doesn't differentiate betwen functions and other blocks. Both share the same syntax group "goBlock".

Functions should have their own syntax group to allow folding on functions without having folding on other blocks.

**Comment by bhcleek** [comment]
Thank you for the suggestion.

AFAIK, Vim doesn't support the kind of folding you are expecting. Folding based on syntax works on nesting levels. See `:help syn-fold` for more information. The problem here is not the syntax block name, is that's that `syn-fold` is the only way to fold a block; it's inherent to Vim and is not something that vim-go can change.
