### ISSUE TITLE
Highlight function calls if them not defined yet

### ISSUE THREAD

**Issue by marselmustafin** [fatih/vim-go#2552]
### What did you do?
```vim
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_list_type = "quickfix"
" let g:go_autodetect_gopath = 1

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_build_constraints = 1
" let g:go_doc_popup_window = 1
" let g:go_echo_go_info = 0
let g:go_metalinter_autosave=1

autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

```
### What did you expect to happen?
Given I have following test, I want to `Bar()` be highlighted as an error and `Bar is undefined` message be shown
```go
func TestBar(t *testing.T) {
	result := Bar()
	if result != "bar" {
		t.Errorf("expecting bar, got %s", result)
	}
}
```
### What happened instead?
`Bar()` is not highlighted, no message is shown
### Configuration (**MUST** fill this out):
(written above)
#### vim-go version:
v1.21

#### Vim version (first three lines from `:version`):
Neovim v0.4.2

#### Go version (`go version`):
go version go1.13.1 darwin/amd64

#### Go environment
not relevant here

</pre></details>

**Comment by bhcleek** [comment]
gopls diagnostics may make this possible, but this particular feature is low priority. Closing for now, because there's a lot of groundwork that would have to be laid first and I don't expect to get to this particular feature any time soon.
