### ISSUE TITLE
GoFmt doesn't jump to first error

### ISSUE THREAD

**Issue by GRbit** [fatih/vim-go#2553]
I think it would be great if `:GoFmt` jumps to first error encountered

<details><summary>patch suggestion git diff</summary><br><pre>
diff --git a/autoload/go/fmt.vim b/autoload/go/fmt.vim
index 54d773b..36ce94a 100644
--- a/autoload/go/fmt.vim
+++ b/autoload/go/fmt.vim
@@ -82,7 +82,7 @@ function! go#fmt#Format(withGoimport) abort
     else
       call winrestview(l:curw)
     endif
-  else
+  elseif l:err == 0
     " Restore our cursor/windows positions.
     call winrestview(l:curw)
   endif
@@ -194,6 +194,9 @@ function! s:show_errors(errors) abort
   " this closes the window if there are no errors or it opens
   " it if there is any
   call go#list#Window(l:listtype, len(a:errors))
+  if !empty(a:errors)
+    call go#list#JumpToFirst(l:listtype)
+  endif
 endfunction
 
 function! go#fmt#ToggleFmtAutoSave() abort
</pre></details>

### What did you do? (required: The issue will be **closed** when not provided)
Write file with `gofmt` errors, or run `:GoFmt` manually with this file

### What did you expect to happen?
Cursor jumps to first error listed in the location list from gofmt
### What happened instead?
Opens list with errors, cursor doesn't moves, don't jumps anywhere. GoBuild and others jumps correctly.
### Configuration (**MUST** fill this out):
remove all other plugins for testing, except Vundle
#### vim-go version:
vim-go version: v1.21
```
$ git log -n 1
commit 2f7a00e9f2ac4ec3c49bfe6234ccd290bfb782ac (HEAD -> master, origin/master, origin/HEAD)
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Tue Oct 22 11:27:44 2019 -0700

    update CHANGELOG.md for #2547
```
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
call vundle#end()
filetype plugin indent on
let g:go_template_use_pkg = 1

"disable arrows
noremap <up> <nop>
inoremap <up> <nop>
noremap <down> <nop>
inoremap <down> <nop>
noremap <left> <nop>
inoremap <left> <nop>
noremap <right> <nop>
inoremap <right> <nop>

syntax on

" Colors and theme
set t_Co=256
set background=light
let g:nofrils_strbackgrounds=1
colorscheme nofrils-light

" Set up <TAB> length and behavior
set tabstop=4
set shiftwidth=4
set expandtab
" This makes backspace treat four spaces like a tab:
set softtabstop=4
set shiftround</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org#### Go version (`go version`):

go version go1.13.1 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/grbit/.cache/go-build"
GOENV="/home/grbit/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/grbit/ssd/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/grbit/.local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/grbit/.local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build809705322=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
Similarly to how linting works, if this is implemented, then it should not jump to the error when `gofmt` is on save.

**Comment by bhcleek** [comment]
Formatting errors are so common while developing that I think doing this would be more disruptive than beneficial to most users. One can get to the first error easily enough with `:lfirst`. Advanced users can add autocommands to jump to the first error in the error list when the quickfix/locationlist window's title is `Format`.
