### ISSUE TITLE
Unknown function: go#config#Updatetime

### ISSUE THREAD

**Issue by patrickdappollonio** [fatih/vim-go#2554]
Hello, I just updated after not updating for a while and I noticed that latest breaks my vim-go installation. I reproduced it by trying to get a smaller `.vimrc` while still including the other plugins that might conflict with `vim-go`...

### What did you do? (required: The issue will be **closed** when not provided)

* Opened or created a go file with `vim main.go`
* Navigated through the lines with `j` or `k` or `up` or `down`

### What did you expect to happen?

* Proper navigation to the next / previous line

### What happened instead?

* Error:
```
Error detected while processing function <SNR>113_timer_restart[3]..<SNR>113_timer_start:
line    1:
E117: Unknown function: go#config#Updatetime
Press ENTER or type command to continue
Error detected while processing function <SNR>113_timer_restart[3]..<SNR>113_timer_start:
line    1:
E116: Invalid arguments for function timer_start(go#config#Updatetime(), function('s:handler'))
Press ENTER or type command to continue
```

#### vim-go version:

* Latest from master, updated using `:PluginUpdate` from Vundle.

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'xolox/vim-misc'
Plugin 'sheerun/vim-polyglot'
Plugin 'jiangmiao/auto-pairs'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'mattn/emmet-vim'
Plugin 'Shougo/neocomplete.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'alvan/vim-closetag'
Plugin 'airblade/vim-gitgutter'
Plugin 'fatih/vim-go'
Plugin 'mbbill/undotree'
Plugin 'tpope/vim-endwise'
Plugin 'wavded/vim-stylus'
Plugin 'plasticscafe/vim-stylus-autocompile'
Plugin 'ekalinin/dockerfile.vim'
Plugin 'henrik/vim-indexed-search'
Plugin 'hashivim/vim-terraform'
Plugin 'avakhov/vim-yaml'
Plugin 'chase/vim-ansible-yaml'
Plugin 'elzr/vim-json'
Plugin 'sdanielf/vim-stdtabs'
Plugin 'sickill/vim-pasta'
Plugin 'mattn/gist-vim'
Plugin 'mattn/webapi-vim'
Plugin 'Valloric/MatchTagAlways'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'plasticboy/vim-markdown'
Plugin 'cespare/vim-toml'
Plugin 'pangloss/vim-javascript'
Plugin 'maxmellon/vim-jsx-pretty'
Plugin 'othree/html5.vim'
Plugin 'tpope/vim-haml'
Plugin 'posva/vim-vue'
Plugin 'mhinz/vim-grepper'
Plugin 'itspriddle/vim-shellcheck'
call vundle#end()

filetype plugin indent on

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_space_tab_error = 1
let g:go_fmt_command = "gofumpt" " https://github.com/mvdan/gofumpt
let g:go_play_open_browser = 0
let g:go_gorename_prefill = 0
let g:go_auto_sameids = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 28 2019 12:23:44)
Included patches: 1-2231
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version without GUI.  Features included (+) or not (-):
```

#### Go version (`go version`):
```
$ go version
go version go1.13 linux/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pdappollonio/.cache/go-build"
GOENV="/home/pdappollonio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pdappollonio/Golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build117633150=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2244-L2248 explains the solution.
