### ISSUE TITLE
:GoDef didn't work, just report error

### ISSUE THREAD

**Issue by aigo-tech** [fatih/vim-go#2558]
### What did you do? (required: The issue will be **closed** when not provided)
```go
// util.go
package main

/*
#include <stdio.h>

void sayHello(){
    printf("hello, world!");
}
*/
import "C"

func PrintHello() {
	C.sayHello()
}
```
```go
// main.go
package main

func main() {
	PrintHello()
}
```
That two go files above are in the same package `main`.
I invoked `:GoDef` when my cursor was hovering on the indentifier `PrintHello`, but it didn't work.
### What did you expect to happen?
Go to the definition for the function `func PrintHello ...`
### What happened instead?

vim-go: no file for file:///Users/arvin/Documents/demo/utils.go

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
" vim-go
" let g:go_def_mode='gopls' " set :GoInfo and :GoDef to use gopls
" let g:go_info_mode='gopls'
let g:go_highlight_types = 1 " unlimited syntax highlighting enabled
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_test_timeout = '15s' " :GoTest times out after 15s
let g:go_auto_type_info = 2
let g:go_fmt_command = "goimports"
let g:go_def_mapping_enabled=0 

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.2
Build type: Release

#### Go version (`go version`):

go version go1.13.1 darwin/amd64

**Comment by bhcleek** [comment]
What version of vim-go are you using? What version of gopls do you have installed? Does the file that you're jumping from exist on disk?

**Comment by aigo-tech** [comment]
> What version of vim-go are you using? What version of gopls do you have installed? Does the file that you're jumping from exist on disk?

Thanks for the reply
1. For gopls, I am sure that  I am using the latest version by running `go get golang.org/x/tools/gopls@latest`.
2. For vim-go, using commit `c0bff0c9cd8998c1a82002af93c689b492f24011`, and it's master
```
commit c0bff0c9cd8998c1a82002af93c689b492f24011 (HEAD -> master, origin/master, origin/HEAD)
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Thu Oct 31 12:00:12 2019 -0700

    update CHANGELOG.md for #2556
```
3. Those two go files in `main` package do exist on my disk, and Jumping is ok while using vscode with gopls.

**Comment by aigo-tech** [comment]
If i remove `import "C"` and `C.sayHello()` in `util.go`,  jumping will work well.
Just as:
```go
package main

/*
#include <stdio.h>

void sayHello(){
    printf("hello, world!");
}
*/
// import "C"

func PrintHello() {
	//	C.sayHello()
}

```

**Comment by aigo-tech** [comment]
Is there anything wrong with `import "C"`

**Comment by bhcleek** [comment]
This may be a bug in gopls. Can you try using the latest that is installed by vim-go by running `:GoUpdateBinaries gopls`?

**Comment by aigo-tech** [comment]
Jumping is ok while using vscode with gopls

**Comment by stamblerre** [comment]
`gopls` does not yet work with cgo (see https://github.com/golang/go/issues/32898, also listed in [Known Issues](https://github.com/golang/tools/blob/master/gopls/doc/status.md#known-issues)).

**Comment by bhcleek** [comment]
Closing, as it appears to be an issue with gopls and not something that's handleable by vim-go currently.
