### ISSUE TITLE
Can vim-go underline / highlight / actually lint in my vim buffer any errors like gocode?

### ISSUE THREAD

**Issue by fr3fou** [fatih/vim-go#2559]
I basically want this:
![image](https://user-images.githubusercontent.com/1344906/68093291-be259c80-fe9c-11e9-961b-78f3e85da3d5.png)

This is a feature that [mdempsky/gocode](https://github.com/mdempsky/gocode) had but I want to only use `vim-go`, is there any way to get this here too? gocode also ran linting in real time (or at least on save)

**Comment by bhcleek** [comment]
gocode was not a vim plugin. I'm not sure how you were accomplishing this feature.

As it stands, vim-go doesn't have this.

**Comment by bhcleek** [comment]
I'm not sure how you were accomplishing this previously, but I added a feature that highlights areas identified as errors or warnings by gopls in #2569.

**Comment by fr3fou** [comment]
:o that's great! do you have a screenshot?

**Comment by bhcleek** [comment]
I have not taken any screenshots of this feature.
