### ISSUE TITLE
question how to reload vendor changes

### ISSUE THREAD

**Issue by imjm** [fatih/vim-go#2560]
This just a question, not issue/bug

I am using go modules in project A and pointing one of a package project B to my local folder, that I am working on adding some new methods.

I add some new methods into the project B, and how could I reload the new methods in project A that I am opening in vim?

so far I have to quit the vim, and reopen it.

**Comment by bhcleek** [comment]
Can you be more specific about what you're doing and why you're closing and reopening vim?

**Comment by imjm** [comment]
project A is opening in vim, and I add some new methods in project B, now I want to use the new methods in project B in project A without reopening vim 

in vscode, I just reload window, it will reload new methods as well.

**Comment by bhcleek** [comment]
How are you adding methods to project B? Is it also open in Vim?

**Comment by imjm** [comment]
not always, sometimes just git pull the changes from my coworkers

**Comment by bhcleek** [comment]
Gopls doesn't notice changes on disk yet, so updating outside of vim won't work.
