### ISSUE TITLE
:GoInstallBinaries gocode fails on windows

### ISSUE THREAD

**Issue by navel3** [fatih/vim-go#2561]
### What did you do? (required: The issue will be **closed** when not provided)

When I call `:GoInstallBinaries gocode` following error occurs.

```
vim-go: gocode not found. Installing github.com/mdempsky/gocode to folder C:\Users\xxxx\go\bin\
vim-go: Error installing github.com/mdempsky/gocode: can't load package: package -ldflags: cannot find package "-ldflags" in any of:
vim-go:         c:\go\src\-ldflags (from $GOROOT)
vim-go:         C:\Users\xxxx\go\src\-ldflags (from $GOPATH)
vim-go: can't load package: package -H=windowsgui: cannot find package "-H=windowsgui" in any of:
vim-go:         c:\go\src\-H=windowsgui (from $GOROOT)
vim-go:         C:\Users\xxxx\go\src\-H=windowsgui (from $GOPATH)
```

The error is caused by following code.
```vim
" plugin/go.vim
        let l:build_cmd = ['go', 'build', '-o', go_bin_path . go#util#PathSep() . bin, l:importPath]
        if len(l:pkg) > 1 && get(l:pkg[1], l:platform, '') isnot ''
          let l:build_cmd += get(l:pkg[1], l:platform, '')
        endif
```

The code compose`go build` command. l:platform is appended as build flags, but the syntax is as follows.

`usage: go build [-o output] [-i] [build flags] [packages]`

### What did you expect to happen?

Installed gocode successfully.

### What happened instead?

Failed to install gocode.

#### vim-go version:

c0bff0c9cd8998c1a82002af93c689b492f24011

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.13.3 windows/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxxx\AppData\Local\go-build
set GOENV=C:\Users\xxxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxxx\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxxx\AppData\Local\Temp\go-build436488550=/tmp/go-build -gno-record-gcc-switches

</pre></details>

**Comment by bhcleek** [comment]
Can you try latest master? I merged a PR yesterday that may resolve this for you.

**Comment by navel3** [comment]
I've checked out latest master.
The problem was not reproduced.
Thanks.
