### ISSUE TITLE
GoReferrers and GoCallstack only analysize files in same package

### ISSUE THREAD

**Issue by hehailong5** [fatih/vim-go#2563]
### What did you do? (required: The issue will be **closed** when not provided)
:GoReferrers for an identifier

### What did you expect to happen?
list all the referrers for this identifier within project scope

### What happened instead?
only list referrers within the same package

#### vim-go version:
v1.21
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

root@nfvo1-E9000:~# cat .vimrc.go
set runtimepath^="/root/.vim_go_runtime"

source /root/.vim_go_runtime/vimrc/basic.vim
source /root/.vim_go_runtime/vimrc/filetypes.vim
source /root/.vim_go_runtime/vimrc/plugins.vim
source /root/.vim_go_runtime/vimrc/extended.vim

try
  source /root/.vim_go_runtime/custom_config.vim
catch
endtry

#### Vim version (first three lines from `:version`):

8.1.2151

#### Go version (`go version`):

go1.12.10

#### Go environment
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/hhl/go:/root/hhl/git/msb-apigateway-go/apiroute:/root/hhl/git/msb-sdclient-go/sdclient"
GOPROXY=""
GORACE=""
GOROOT="/root/.gvm/gos/go1.12.10"
GOTMPDIR=""
GOTOOLDIR="/root/.gvm/gos/go1.12.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build551488242=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
With vim-go 1.21, you can set the guru scope using `:GoGuruScope` (see `:help :GoGuruScope`) to cause `:GoReferrers` and `:GoCallers` (I assume that's what you mean by `:GoCallstack`?) to use more than just the current package as the guru scope.

Current master does not rely on guru for `:GoReferrers` and should provide the experience you expected. ref: https://github.com/fatih/vim-go/pull/2535

**Comment by hehailong5** [comment]
@bhcleek, Unfortunately either using g:go_guru_scope or :GoGuruScope not work for me..
besides, I got the below error message at bottom:
<apigateway-go/apiroute/src/apiroute [Location List]                                                                                      1,1             All
vim-go: /root/hhl/git/msb-apigateway-go/apiroute/src/apiroute/template...e: -1 at function 374[13]..377[26]..<SNR>111_referencesHandler, line 12

**Comment by hehailong5** [comment]
I've downloaded master, still get the same error when using :GoReferrers

vim-go: /root/hhl/git/msb-apigateway-go/apiroute/src/apiroute/cache/re...e: -1 at function 374[13]..377[26]..<SNR>111_referencesHandler, line 12

**Comment by bhcleek** [comment]
@hehailong5 now you're dealing with a different issue. Can you please open a new issue with clear replication steps so I can analyze that error and fix its root cause?

**Comment by gonzaloserrano** [comment]
Hey, so I got rid of guru because of CPU issues and trying to rely on gopls but as the issue author the output just contains results from the current package and not the whole project I'm working on. Is there any hint or way to debug this?

Running vim-go master `13c943aaad7ad98ddf0c35f6b758318f53e144fb` and `gopls` `master`.
