### ISSUE TITLE
Same ID clear after navigate away?

### ISSUE THREAD

**Issue by impguard** [fatih/vim-go#2564]
The same ID implementation is super cool, but I was wondering if there was a way to get it to auto clear when navigating away from a keyword? Right now the behaviour seems to be to stay highlighted until another word is hovered, but I'd like it to disable as soon as I navigate away (and re-enable after hovering on a word for X amount of time).

Is that possible?

**Comment by bhcleek** [comment]
To the best of my knowledge, vim doesn't have any event that indicates when a the cursor has moved away from a word. It has `CursorHold`, `CursorMovedI`, and `CursorMoved`. This functionality is too expensive to run on `CursorMoved` or `CursortMovedI`.
