### ISSUE TITLE
Can I use `gocode` instead of `gopls`?

### ISSUE THREAD

**Issue by rocket049** [fatih/vim-go#2573]
I found `gopls` can not work well with package `github.com/therecipe/qt`, But `gocode` work well.

So I want to use `gocode` instead of `gopls`.

It is not work if I add the code `let g:go_info_mode = 'gocode'` into `.vimrc`.

Is there any way to make it work?

**Comment by rocket049** [comment]
I modify `complete.vim` , replace function `go#complete#Complete()` with `go#complete#GocodeComplete()`. It works, but ugly.

Is there a nice way to do this?

**Comment by bhcleek** [comment]
Yes. Just set `omnifunc` to `go#complete#GocodeComplete()` in an `after/ftplugin/go.vim` file

https://github.com/fatih/vim-go/blob/19d4be6f328007f53c90c87e8d584f90e7094947/doc/vim-go.txt#L1201
