### ISSUE TITLE
vim report redeclared  when use build tags

### ISSUE THREAD

**Issue by theburn** [fatih/vim-go#2575]
### What did you do? (required: The issue will be **closed** when not provided)

**file1.go**

```go
// +build mem

package file
func XXX() {
     // .....
}
```

**file1_mem.go**

```go
// +build !mem

package file
func XXX() {
     // .....
}
```

when I use `vim file1_mem.go`, vim report `XXX redeclared  in this block`

I  set `let g:go_build_tags = "mem"` in the vimrc, but not work, and  I set `:GoBuildTags mem`， also not work.

### What did you expect to happen

when i use` :GoBuildTags mem` , vim don't report `XXX redeclared  in this block`

### What happened instead?

 vim report `XXX redeclared  in this block`

#### vim-go version:

vim-go version: 1.21

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

 let g:go_highlight_functions = 1
 let g:go_highlight_methods = 1
 let g:go_highlight_structs = 1
 let g:go_highlight_interfaces = 1
 let g:go_highlight_operators = 1
 let g:go_highlight_build_constraints = 1

 let g:go_fmt_command = "goimports"

 let g:go_def_mode='gopls'

 let g:go_info_mode='gopls'

 let g:go_build_tags = "mem"
 let g:syntastic_go_go_test_args = '-tags="mem"'
 let g:syntastic_go_go_build_args = '-tags="mem"'

 let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
 let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 17 2019 19:24:40)
macOS version

#### Go version (`go version`):

go version go1.12.10 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/burn/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/burn/BurnSpace/code/golang/GoProject"
GOPROXY=""
GORACE=""
GOROOT="/Users/burn/.gvm/gos/go1.12.10"
GOTMPDIR=""
GOTOOLDIR="/Users/burn/.gvm/gos/go1.12.10/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xm/qhpq825n0ps6ryd_g000zqr80000gn/T/go-build978523647=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment]
Does `go build` run without errors?

**Comment by theburn** [comment]
@bhcleek  both   `go build` and `go build --tags mem`  without errors

**Comment by bhcleek** [comment]
🤔 that's odd. The `//+build` shouldn't be taking effect at all, because it needs to be a space between `//` and `+` (e.g. `// +build`), so `go build` should be failing for you, too.

**Comment by theburn** [comment]
@bhcleek  sorry, it's my fault. written error. `// +build mem`  in my go file

**Comment by bhcleek** [comment]
`:GoBuild` is working for you now?

**Comment by theburn** [comment]
Yes， vim report `vim-go: [build] SUCCESS`

**Comment by theburn** [comment]
@bhcleek  `:GoBuild` is always success,  the error  `XXX redeclared in this block` still exists!

**Comment by bhcleek** [comment]
It literally says `XXX`?

**Comment by bhcleek** [comment]
Ah, of course it does, because the function is named `XXX`.

**Comment by bhcleek** [comment]
Can you run `:GoUpdateBinaries gopls` and see if that resolves the issue for you?

**Comment by bhcleek** [comment]
If `:GoUpdateBinaries gopls` doesn't resolve the issue, then it's very likely that you have another file in your package that defines `func XXX() { ... }`.

**Comment by theburn** [comment]
yestday， I update gopls.
```
➜  gopls version
golang.org/x/tools/gopls v0.1.7
    golang.org/x/tools/gopls@v0.1.7 h1:YwKf8t9h69++qCtVmc2q6fVuetFXmmu9LKoPMYLZid4=
```

I record a showterm  http://showterm.io/ea43c38d31dd17df6f123

**Comment by bhcleek** [comment]
So you have to move the cursor into the function to see this error. That's a key step to duplicating this issue.

Can you duplicate the issue when vim-go is the only plugin loaded?

**Comment by theburn** [comment]
Yes,  you are right, when I commet `Plugin 'Valloric/YouCompleteMe'` in ~/.vimrc, the error info disapper!
@bhcleek  Thank you very much!
