### ISSUE TITLE
vim-go: Vim(call):E28: No such highlight group name: goDiagnosticError

### ISSUE THREAD

**Issue by dvrkps** [fatih/vim-go#2576]
### What did you do? (required: The issue will be **closed** when not provided)
PlugUpgrade, PlugUpdate and GoUpdateBinaries
### What did you expect to happen?
No message

### What happened instead?
Message

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):
nvim 0.4.3

#### Go version (`go version`):
go version go1.13.4 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/davor/Library/Caches/go-build"
GOENV="/Users/davor/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/davor"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/davor/src/github.com/dvrkps/valida/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9h/yvy5nvq917n_xcbth_j21kkh0000gn/T/go-build045640412=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment]
The highlight group name is defined here: https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L391. You likely need to restart vim since the `PlugUpdate` added the group.

**Comment by dvrkps** [comment]
@bhcleek restart didn't help.
i comment vim-go and PlugClean. After that i use GoUpdateBinaries and after that message show again

**Comment by bhcleek** [comment]
I've seen the same issue on a PR now, too. I'm not sure why yet, but in the meantime, you should be able to add this to your vimrc as a workaround:
```
let g:go_highlight_diagnostic_errors=0
let g:go_highlight_diagnostic_warnings=0
```
