### ISSUE TITLE
:GoRename (gopls) creates .orig file

### ISSUE THREAD

**Issue by orlangure** [fatih/vim-go#2581]
### What did you do? (required: The issue will be **closed** when not provided)
I tried to rename a variable using `:GoRename` with `go_gorename_command` in main.go file of main package. The operation worked, but there appeared a new file: `main.go.orig`.

### What did you expect to happen?
I expected `:GoRename` to work and clean up temporary files it created, and/or not to create backups until requested explicitly.

### What happened instead?
`gopls` kept a backup of `main.go`

### Configuration (**MUST** fill this out):
```
let g:go_gorename_command = 'gopls'
```

**Comment by orlangure** [comment]
I see there is a discussion in the original issue https://github.com/fatih/vim-go/issues/2366#issuecomment-553169654

And an issue for `gopls`: https://github.com/golang/go/issues/35551

**Comment by bhcleek** [comment]
I'm reluctant to cause vim-go to delete these files. It's possible (albeit admittedly unlikely) that a user may have them legitimately versioned, and there's no way for vim-go to know that reliably.

**Comment by orlangure** [comment]
I agree. I think we should wait for `gopls` to implement a flag to keep/remove these files, and expose it via vim-go configuration. I understand that this is not possible now.

**Comment by bhcleek** [comment]
This will be resolved by https://go-review.googlesource.com/c/tools/+/207347/ when it's released. There's nothing for vim-go to do here.
