### ISSUE TITLE
func snippets error with coc-snippets

### ISSUE THREAD

**Issue by 404cn** [fatih/vim-go#2582]
### What did you do? (required: The issue will be **closed** when not provided)

I use coc-snippets and add this to my coc-settings.

`
snippets.ultisnips.directories: [
  "UltiSnips",
  "gosnippets/UltiSnips"
],
`

When i type func i got this 

<img width="1327" alt="截屏2019-11-13上午10 39 49" src="https://user-images.githubusercontent.com/24653356/68752394-35e28c80-063e-11ea-9ee5-bb3de86f8338.png">

### What did you expect to happen?

Just right func snippets.

### Configuration (**MUST** fill this out):

let g:go_def_mapping_enabled = 0

#### vim-go version:

latest version

#### Vim version (first three lines from `:version`):

NVIM v0.4.3

Build type: Release

LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.13.4 darwin/amd64

**Comment by bhcleek** [comment]
I see no evidence in your description that this is related to or caused by vim-go other than that you've configured coc to use Ultisnips. If you can provide some evidence that the fix for the problem you're seeing is required by vim-go, then I'll be happy to take a closer look.

FWIW: try to duplicate the problem with as minimal vimrc as possible and only the plugins necessary. In your case, that would mean using only vim-go and Ultisnips.

**Comment by 404cn** [comment]
@bhcleek 

At first i install vim-go coc.nvim and coc-snippets, but snippets not work when i write golang file, so i take a look at coc-snippets's README and i found this in F.A.Q

> Q: It doesn't load snippets from vim-go.

> A: It uses g:UltiSnipsSnippetDirectories which is not supported, you can add settings:

`
snippets.ultisnips.directories: [
  "UltiSnips",
  "gosnippets/UltiSnips"
],
`


> to load it.


So i add this to my coc-settins.json and snippets worked, but just func (for now) i got this error.

Also i got a little bit confused and don't know where i create an issue.

I just install these three pulgin about this, and add  ⬆️ to my coc-settings, and set lsp.

`
"languageserver": {

            "golang": {

                "command": "gopls",

                "rootPatterns": ["go.mod"],

                "filetypes": ["go"]

            },
`


I found nothing else about this, i think.

BTW: Forget my pool English. :)

**Comment by bhcleek** [comment]
I've just tested the UltiSnips integration for the `func` snippet and did not see any errors. It looks like this is probably something wrong with coc, not with vim-go or UltiSnips (and the stack trace in your screenshot would seem to support that idea). I'll leave this open for a day or two to give you a chance to provide counter evidence.

FWIW, you can test yourself using only UltiSnips and vim-go if you'll remove coc from your plugins.

**Comment by 404cn** [comment]
@bhcleek  Thanks very nuch, i will close this and take a look at coc.
