### ISSUE TITLE
Syntax Highlighting is broken

### ISSUE THREAD

**Issue by Chronophylos** [fatih/vim-go#2586]
### What did you do? (required: The issue will be **closed** when not provided)

* Updated to 10d8f9d5e33d8d18f06ca9b8e5719ab1940cb5a6
* Syntax broke

full config
![image](https://user-images.githubusercontent.com/14890588/68881263-b9ff4780-0704-11ea-8a7c-353c038f604b.png)

reduced config
![image](https://user-images.githubusercontent.com/14890588/68882392-faf85b80-0706-11ea-80ba-bc7c4cb97fab.png)

### What did you expect to happen?

The syntax to work

### What happened instead?

It broke

### Configuration (**MUST** fill this out):
nothing

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin(stdpath('data') . '/plugged')
    Plug 'fatih/vim-go', { 'for': 'go', 'do': ':GoUpdateBinaries' }
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):
go version go1.13.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/chrono/go/bin"
GOCACHE="/home/chrono/.cache/go-build"
GOENV="/home/chrono/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/chrono/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/chrono/Projects/chb3/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build045261485=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
What is reduced config vs full config?

**Comment by Chronophylos** [comment]
The reduced config is what I posted, my full config is here https://github.com/Chronophylos/dotfiles/tree/master/nvim/.config/nvim
