### ISSUE TITLE
Is it possible to run errchecks and lint on save?

### ISSUE THREAD

**Issue by derekchiang** [fatih/vim-go#259]
I don't see it in the settings.

**Comment by oryband** [comment]
@derekchiang yes you can, but this can be defined via syntastic. type `:syntastic-aggregate-errors` for more info, but here's the short solution - put this in your `.vimrc`
```vim
let g:syntastic_go_checkers = ['go', 'golint', 'govet']
```
This will execute standard go checker, `go lint` and `govet` together. You can remove the tools you don't want.

**Comment by oryband** [comment]
@fatih maybe you should reference this solution in the docs, since I guess many are using syntastic and this is a common problem people are facing.

**Comment by fatih** [comment]
@oryband I agree, we can add this to the FAQ, a lot of people are asking for it or having problems which is not vim-go related at all sometimes.

**Comment by oryband** [comment]
fyi I wasn't even aware of govet + goling until I tried to answer this issue. so yeah - should be helpful.

**Comment by StevenMaude** [comment]
This is syntastic-specific but, for anyone else wondering why only one of the checkers is working after adding the `syntastic_go_checkers` line to `.vimrc`, you also need:

```vim
let g:syntastic_aggregate_errors = 1
```
