### ISSUE TITLE
GoTestCompile with build tags

### ISSUE THREAD

**Issue by gonzaloserrano** [fatih/vim-go#2590]
### What did you do? (required: The issue will be **closed** when not provided)

Call :GoTestCompile in a test with build tags and a syntax error. Removing the build tags works as expected.

### What did you expect to happen?

The test is compiled and the syntax error reported.

### What happened instead?

Somehow the syntax error is highlighted but the test is not compiled.

#### vim-go version:

commit 10d8f9d5e33d8d18f06ca9b8e5719ab1940cb5a6 (HEAD -> master, origin/master, origin/HEAD)
Merge: 6e12e9e fb161dc
Author: Billie Cleek <bhcleek@users.noreply.github.com>
Date:   Wed Nov 13 08:32:03 2019 -0800

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 27 2019 00:46:03)
macOS version
Parches incluidos: 1-1750
#### Go version (`go version`):

go version go1.13.1 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/gonzalo/go/bin"
GOCACHE="/Users/gonzalo/Library/Caches/go-build"
GOENV="/Users/gonzalo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/gonzalo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3k/9bppsqk51p13plgw280svtgw0000gn/T/go-build201890627=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by bhcleek** [comment]
I've tried to duplicate what you're describing, but it works as expected in my tests. Can you offer an example file that demonstrates what you're experiencing?

**Comment by gonzaloserrano** [comment]
test file:

```go
// +build infra

package bug_test

import "testing"

func TestFoo(t *testing.T) {
	foo
}
```

`:mess` output:
```
vim-go: [compile test] dispatched
vim-go: [compile test] FAIL
vim-go: /Users/gonzalo/go/src/github.com/gonzaloserrano/bug
vim-go: can't load package: package .: build constraints exclude all Go files in /Users/gonzalo/go/src/github.com/g
onzaloserrano/bug
Type  :qa!  and press <Enter> to abandon all changes and exit Vim
"bug_test.go" 9L, 96C escritos
```

**Comment by bhcleek** [comment]
Did you set your build tags in vim-go with either `:GoBuildTags` or by setting `g:go_build_tags` before calling `:GoTestCompile`?

**Comment by gonzaloserrano** [comment]
Nopes! Didn't know that feature. Of course it fixed it so I'm closing the issue. Sorry and thank you for your time!

**Comment by bhcleek** [comment]
You're welcome and no apologies necessary. :bowing_man: 

A quick tip: you can always search the vim-go help before creating an issue; it's thorough and covers topics like this we'll. The wiki is also a good resource

**Comment by gonzaloserrano** [comment]
Yeah, sorry about it. Been using vim-go for years 🤦‍♂ 

So from the docs I see `let g:go_build_tags = "mycustomtag"`; I guess that multiple tabs should be separated by a space? Currently I have 3 different tags in my system.

Thanks.

**Comment by bhcleek** [comment]
The help for g:go_build_tags explains it well. See `:help g:go_build_tags`.
