### ISSUE TITLE
Show compile error on hover compile error highlighting

### ISSUE THREAD

**Issue by ahuret** [fatih/vim-go#2591]
Since I updated my binaries, when I save my go files, I got red highlights on code errors.
Problem here is that I don't have any explainations on what is causing this highlighting.
How to resolve this ?
Thanks :)

**Comment by bhcleek** [comment]
Can you provide an example? It's not clear from your description what exactly you're seeing. Ideally, you'd provide a simple file that demonstrates the problem.

There are two possibilities that spring to mind.

The first is that you may be seeing a bug in some recent changes to highlighting of some numerics.

The second (and more likely) is you're seeing the highlighting introduced in #2569 to highlight areas that gopls diagnostics have flagged. If this is the case, the actual messages from gopls aren't surfaced yet, but depending on the nature of them, you may either see the issues on save if you have `g:go_fmt_autosave` set and they're syntax errors or after `:GoBuild` or `:GoTest`.

**Comment by ahuret** [comment]
Thanks @bhcleek !
I was about vim go don't surface gopls messages yet, so you answered my question :-)
I now GoBuild automatically at save, this combined with area highighting is ok for quick debug !

Is there already an issue about this surfacing feature ? thx

**Comment by ahuret** [comment]
closing it /close

**Comment by ahuret** [comment]
closing it

**Comment by axiaoxin** [comment]
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/2876405/79840991-51ba3d80-83e9-11ea-8a16-a7fdc50b0e11.png">

there is a highlighting, but I can't get any detail info
