### ISSUE TITLE
unused in go_metalinter_enabled doesn't show an error in quickfix

### ISSUE THREAD

**Issue by yagi5** [fatih/vim-go#2592]
### What did you do? (required: The issue will be **closed** when not provided)

Write this code then save file.
```
package main

import "fmt"

func main() {
	fmt.Printf("hello vim-go!")
}

func bar() string {
	return "bar"
}
```

`golangci-lint run` shows an error.
```
$ golangci-lint run main.go
main.go:9:6: func `bar` is unused (unused)
func bar() string {
     ^
```

### What did you expect to happen?

`main.go:9:6: bar is unused (deadcode)` is shown in quickfix

### What happened instead?

`vim-go: [golangci-lint] SUCCESS` is shown

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
let g:go_linters = ['unused']
let g:go_metalinter_enabled = g:go_linters
let g:go_metalinter_command = 'golangci-lint'
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = g:go_linters
</pre></details>

#### Vim version (first three lines from `:version`):

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
```

#### Go version (`go version`):

```
go version go1.12.9 darwin/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yagi5/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yagi5/ghq"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xy/5l17f9752pqggx37c9yflmjm0000gn/T/go-build437740319=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by bhcleek** [comment]
Does the command that's run by vim-go show the error you're expecting? You can see the command that vim-go runs as an array by setting `g:go_debug=['shell-commands']`.

**Comment by bhcleek** [comment]
I can't duplicate what you've describe. Here's an animated gif showing it working as expected on master:

![recording](https://user-images.githubusercontent.com/1958864/69000934-7d118d00-088b-11ea-86e1-3736b7ce8568.gif)
