### ISSUE TITLE
GoReferrers with guru error

### ISSUE THREAD

**Issue by gonzaloserrano** [fatih/vim-go#2596]
### What did you do? (required: The issue will be **closed** when not provided)

I'm trying to use `:GoReferrers` to find symbols in different packages. I found https://github.com/fatih/vim-go/issues/2563. Then I added some vim-go config to use `guru` because `gopls` does not support multiple packages yet (see https://github.com/golang/go/issues/32869). Now looks like `:GoReferrers` is broken.

I've created a repo to reproduce it. What I'm doing is to call `:GoReferrers` on the `Foo` symbol that you can find at https://github.com/gonzaloserrano/vim-go-bug/blob/master/pkg/one/one.go#L5

### What did you expect to happen?

Find the use of `Foo` in package `two`

### What happened instead?

Similar to (but in spanish)

```
 error when trying to process function go#guru#Referrers[10]..<SNR>270_run_guru[2]..<SNR>270_async_guru[1]..<SNR>270_guru_cmd[28]..go#config#GuruScope[6]..go#util#StripTrailingSlash:
```

#### vim-go version:

de681fd1175d83751d8e7a2216d2c835a75e48dd 

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
        let g:go_def_mode = "gopls"
        let g:go_referrers_mode="guru"
        let g:go_guru_scope = "github.com/PaackEng/... github.com/gonzaloserrano/..."
        let g:go_fmt_experimental = 1
        let g:go_gorename_command = 'gopls' " instead of gorename
        let g:go_build_tags='infra sql amqp'

        set statusline+=%#goStatuslineColor#
        set statusline+=%{go#statusline#Show()}
        set statusline+=%*

        let g:go_list_type = "quickfix"
        let g:go_fmt_command = "gofumports"
        let g:go_fmt_fail_silently = 1
        let g:go_fmt_autosave = 1
        let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }

        let g:go_highlight_variable_declarations = 1
        let g:go_highlight_build_constraints = 1
        let g:go_highlight_functions = 1
        let g:go_highlight_function_calls = 1
        let g:go_highlight_methods = 1
        let g:go_highlight_operators = 1
        let g:go_highlight_types = 1
        let g:go_highlight_fields = 1
        let g:go_highlight_extra_types = 1
        let g:go_highlight_generate_tags = 1
        let g:go_term_enabled = 1
</pre></details>

#### Vim version (first three lines from `:version`):

:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 27 2019 00:46:03)
macOS version
Parches incluidos: 1-1750
Compilado por Homebrew
Versión "enorme" sin interfaz gráfica (GUI).  Aspectos incluidos (+) o no (-):
+acl               -clientserver      +diff              +folding           +libcall           -mouse_gpm         +packages          +ruby              -tag_any_white     +vartabs           -xfontset
+arabic            +clipboard         +digraphs          -footer            +linebreak         -mouse_jsbterm     +path_extra        +scrollbind        -tcl               +vertsplit         -xim
+autocmd           +cmdline_compl     -dnd               +fork()            +lispindent        +mouse_netterm     +perl              +signs             +termguicolors     +virtualedit       -xpm
+autochdir         +cmdline_hist      -ebcdic            +gettext           +listcmds          +mouse_sgr         +persistent_undo   +smartindent       +terminal          +visual            -xsmp
-autoservername    +cmdline_info      +emacs_tags        -hangul_input      +localmap          -mouse_sysmouse    +postscript        -sound             +terminfo          +visualextra       -xterm_clipboard
-balloon_eval      +comments          +eval              +iconv             +lua               +mouse_urxvt       +printer           +spell             +termresponse      +viminfo           -xterm_save
+balloon_eval_term +conceal           +ex_extra          +insert_expand     +menu              +mouse_xterm       +profile           +startuptime       +textobjects       +vreplace
-browse            +cryptv            +extra_search      +job               +mksession         +multi_byte        -python            +statusline        +textprop          +wildignore
++builtin_terms    +cscope            -farsi             +jumplist          +modify_fname      +multi_lang        +python3           -sun_workshop      +timers            +wildmenu
+byte_offset       +cursorbind        +file_in_path      +keymap            +mouse             -mzscheme          +quickfix          +syntax            +title             +windows
+channel           +cursorshape       +find_in_path      +lambda            -mouseshape        +netbeans_intg     +reltime           +tag_binary        -toolbar           +writebackup
+cindent           +dialog_con        +float             +langmap           +mouse_dec         +num64             +rightleft         -tag_old_static    +user_commands     -X11
     archivo "vimrc" del sistema: "$VIM/vimrc"
     archivo "vimrc" del usuario: "$HOME/.vimrc"
  2º archivo "vimrc" del usuario: "~/.vim/vimrc"
      archivo "exrc" del usuario: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
            predefinido para $VIM: "/usr/local/share/vim"
Compilación: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Enlazado: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -fra
mework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -l
util -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6
#### Go version (`go version`):

go version go1.13.1 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/gonzalo/go/bin"
GOCACHE="/Users/gonzalo/Library/Caches/go-build"
GOENV="/Users/gonzalo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/gonzalo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3k/9bppsqk51p13plgw280svtgw0000gn/T/go-build415937730=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by bhcleek** [comment]
What was the rest of the error message?

FWIW, I am unable to duplicate the problem as you've described it. Here's an animated gif showing it working:

![recording](https://user-images.githubusercontent.com/1958864/69074937-389a0480-09e5-11ea-8e33-8ee5707465b8.gif)

**Comment by gonzaloserrano** [comment]
```
Se ha detectado un error al procesar function go#guru#Referrers[10]..<SNR>281_run_guru[2]..<SNR>281_async_guru[1]..<SNR
>281_guru_cmd[28]..go#config#GuruScope[6]..go#util#StripTrailingSlash:
línea    1
E712: El argumento de map() debe ser una lista o un diccionario
````

**Comment by gonzaloserrano** [comment]
Means that `map()` arg must be a list or dictionary.

**Comment by bhcleek** [comment]
It's because of your `g:go_guru_scope` value. It should be a comma a separated list. Only the `:GoGuruScope` commands takes the scopes as a space separated list.

**Comment by gonzaloserrano** [comment]
Thank you,

I tried with `let g:go_guru_scope = "github.com/PaackEng/...,github.com/gonzaloserrano/..."` without luck any hints?

**Comment by gonzaloserrano** [comment]
OK I forgot the brackets... fixed now, thanks!

**Comment by gonzaloserrano** [comment]
vim-go now works but guru is eating the CPU... will report somewhere else :_)
