### ISSUE TITLE
Random highlights

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#2598]
### What did you do? (required: The issue will be **closed** when not provided)
Use vim-go ordinarily, build source code, compile tests. etc...

### What did you expect to happen?
Normal syntax highlighting 

### What happened instead?
Seemingly random characters are now being highlighted without any information. 

### Configuration (**MUST** fill this out):
https://github.com/ldelossa/dotfiles/blob/master/vimrc

#### vim-go version:
master

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.13.1 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/louis/git/gopath/bin"
GOCACHE="/Users/louis/Library/Caches/go-build"
GOENV="/Users/louis/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/louis/git/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/louis/git/go/clair/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/97/d8n7l11n68g618kz9kwmtjvr0000gn/T/go-build663898198=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_list_type = 'quickfix'
g:go_highlight_operators = 1
g:go_jump_to_error = 1
g:go_term_enabled = 1
g:go_metalinter_deadline = '5s'
g:go_highlight_fields = 1
g:go_metalinter_command = 'golangci-lint'
g:go_def_mode = 'godef'
g:go_highlight_structs = 1
g:go_disable_autoinstall = 0
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_test_show_name = 1
g:go_test_timeout = '600s'
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_highlight_methods = 1
g:go_list_height = 10
g:go_term_exit = 1
g:go_fmt_experimental = 1
g:go_loaded_gosnippets = 1
g:go_term_height = 10
g:go_term_mode = 'split'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_decls_mode = 'fzf'
</pre></details>

Screenshot:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/5642902/69164543-2b9d1400-0abe-11ea-9fc7-fac4f487bc00.png">
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/5642902/69164583-38ba0300-0abe-11ea-94bc-ae86644d2d20.png">

**Comment by bhcleek** [comment]
@ldelossa please provide a minimal vimrc and ideally duplicate this without other plugins loaded.

I'm not seeing this problem; can you provide a file that demonstrates this issue?

**Comment by ldelossa** [comment]
@bhcleek will do - but need to get home from work first. 

I did notice the highlights are because of new associations:

SpellBad	SpellBad goDiagnosticError
SpellCap	SpellCap
SpellRare	SpellRare goDiagnosticWarning

Don't believe SpellBad and SpellRare were assocaited with the goDiagnostic* syntax groups? Unless I'm just going crazy.

**Comment by bhcleek** [comment]
I can't comment on `SpellCap`, but `those `SpellRare` and `SpellBad` are a result of https://github.com/fatih/vim-go/pull/2569. You can disable that highlighting if you want. See `:help                                         'g:go_highlight_diagnostic_warnings'`.

You're also likely to see the actual errors on `:GoBuild`.

**Comment by ldelossa** [comment]
@bhcleek yup that's totally it, didn't realize that they were actually coming from the linter and gopls (I think). 

Closing this out. Thanks a lot!
