### ISSUE TITLE
How to change GoSameIds' highlight color?

### ISSUE THREAD

**Issue by zengjiwen** [fatih/vim-go#2601]
I found that the GoSameIds' highlight color is the same as vim's default search highlight. That often confuse me while coding. Instead of changing the default search highlight, is there anyway to change GoSameIds' highlight color? thanks.

**Comment by bhcleek** [comment]
Yes. `goSameId` is defined in `syntax/go.vim` as a link to `Search`. You can add a `hi def goSameId` to your vimrc or to a `after/syntax/go.vim` file to set `goSameId` to whatever you'd like.

**Comment by zengjiwen** [comment]
I got it. Thank you so much!
