### ISSUE TITLE
:GoBuild doesn't run `go get`

### ISSUE THREAD

**Issue by abitrolly** [fatih/vim-go#2602]
Created new file, added external import and tried to build it.
```shell
$ vim main.go
```
```go
package main

import (
        "fmt"
        "log"

        "github.com/awesome-gocui/gocui"
)

func main() {
        g, err := gocui.NewGui(gocui.OutputNormal)
        if err != nil {
                log.Panicln(err)
        }
        defer g.Close()

        fmt.Println("vim-go")
}
```

### What did you expect to happen?

`:GoBuild` to fetch dependencies automatically.

### What happened instead?
```
main.go|7 col 2| cannot find package "github.com/awesome-gocui/gocui" in any of: /snap/go/4762/src/github.com/awesome-gocui/gocui (from $GOROOT) /home/anatoli/go/src/github.com/awesome-gocui/gocui (from $GOPATH)
```

#### vim-go version:
master d4a9cc7

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2019 00:00:00)
Included patches: 1-2267
Modified by <bugzilla@redhat.com>
```
#### Go version (`go version`):
go version go1.13.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/anatoli/.cache/go-build"
GOENV="/home/anatoli/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/anatoli/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build368406404=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
Go will only fetch dependencies on `go build` when there's an ambient `go.mod` file and the module is either in GOPATH with GO111MODULE or the module is outside of GOPATH. Do these conditions hold true for your replication path?

**Comment by abitrolly** [comment]
There was no `go.mod` in my dir, which is outside of the GOPATH. Should `vim-go` create `go.mod` automatically for new projects?

**Comment by bhcleek** [comment]
vim-go does not create go.mod files on the fly.

**Comment by abitrolly** [comment]
@bhcleek yes, but why not?

**Comment by abitrolly** [comment]
Either create `go.mod` or provide a better error message why it doesn't fetch.

**Comment by bhcleek** [comment]
`:GoBuild` calls `go build`. `go build` doesn't get dependencies in module-aware mode without an ambient go.mod file either.

vim-go does not know what you would want a module to be named nor where the go.mod file should be placed.

**Comment by abitrolly** [comment]
`vim-go` can set the name to the parent directory and place `go.mod` near the `main.go`.

**Comment by bhcleek** [comment]
vim-go isn't going to create a go.mod file when one is missing. There are too many questions around how to handle various use cases and the feature would likely cause more confusion than the feature would be worth; not all packages are a main package and placing the go.mod file any place assumes too much about workflows that can vary quite widely among developers.

**Comment by abitrolly** [comment]
Can `vim-go` provide a wizard for new projects (creating `main.go` in empty dir)?

**Comment by bhcleek** [comment]
A file named `main.go` is not special, modules often don't have a main package at the module root, and an empty dir isn't enough of a signal to trigger creation of a `go.mod` file. Additionally, modules are generally not just a simple name; they'll usually need to be the location at which the module can be found (e.g. `golang.org/x/tools/gopls`). Other considerations include the value of GO111MODULE, whether one is in GOPATH mode or module aware mode, and whether there's an ambient module already.

I don't see the feature you're proposing providing enough value to justify its development; `:!go mod init $MODULENAME` will do what you want without requiring any magic on vim-go's part.
