### ISSUE TITLE
Is there a way to disable LSP?

### ISSUE THREAD

**Issue by pwntester** [fatih/vim-go#2604]
Im using a different LSP client so would be nice to disable vim-go one. is that possible?

**Comment by bhcleek** [comment]
gopls is used for several things in vim-go, and the list is growing. Currently, there is no way to fully disable it. You may not realize it, but features like `:GoInfo` and `g:go_auto_info` rely on gopls, too.

It's been previously discussed in #2379 and #2283.

**Comment by bhcleek** [comment]
I added support for disabling gopls in https://github.com/fatih/vim-go/pull/2605.
