### ISSUE TITLE
go_gopls_use_placeholders doesn't do anything

### ISSUE THREAD

**Issue by qhenkart** [fatih/vim-go#2607]
### What did you do? (required: The issue will be **closed** when not provided)

Successfully installed gopls and I'm now using that for autocompletion

`let g:go_gopls_use_placeholders = 0`
and 
`let g:go_gopls_use_placeholders = 1`
seem to make no difference in the code

when typing fmt. (c-x, c-o)  Both will autocomplete to fmt.Println

### What did you expect to happen?

when vimrc has 
`let g:go_gopls_use_placeholders = 1`
I expected something along the lines of 
`fmt.Println(a)`

### What happened instead?

both configuration options simply complete to 
`fmt.Println`
#### vim-go version:
current master branch

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
 let g:go_gopls_complete_unimported = 1
 let g:go_gopls_use_placeholders = 1
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 26 2019 21:43:31)
macOS version
Included patches: 1-2350
#### Go version (`go version`):

go version go1.13.4 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/qhenkart/Library/Caches/go-build"
GOENV="/Users/qhenkart/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/qhenkart/workspace/launchpad/glidr-dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1v/97x4f9mj4rj9g0q79xsfl_6h0000gn/T/go-build329206811=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment]
Thank you for the report. I've identified the issue and am working on a fix. The fix is relatively straightforward on its face, but will likely only work as desired when paired with coc. Are you a coc user?

**Comment by qhenkart** [comment]
@bhcleek actually it worked without coc, but it's really verbose and ugly (something like `someFunc({1: message string})`

however the coc recommendation was really nice and I'm very happy to have downloaded it based on your recommendation. I would love to see coc mentioned somewhere in the vim-go docs for other new users
