### ISSUE TITLE
saving go files with tagbar opening, cursor will jump to top of the file.

### ISSUE THREAD

**Issue by hellodudu** [fatih/vim-go#2619]
### What did you do? (required: The issue will be **closed** when not provided)

I'm writing go files with tagbar open. When saving file, the cursor will jump to top, then back to prev position. Please see gif below.

![qq20180323-190321](https://user-images.githubusercontent.com/519830/37826073-1c83b5e2-2ecd-11e8-9098-52725bb31971.gif)

#### reproduce steps
Open any .go file, toggle tagbar open, write some blank lines, then save file.

I aslo find some clues:
* When saving go files with tagbar close, it cannot be reproduced.
* When `g:go_fmt_autosave = 0`, even input command `:GoFmt`, it cannot be reproduced.
* When `vim-go` is disabled, `gotags` enabled, it cannot be reproduced.

### What did you expect to happen?
The cursor stays on the line where I'm writing on.

### What happened instead?
The cursor jumps to top of file, and then jump back.

### Configuration (**MUST** fill this out):
* `g:go_fmt_autosave = 0`
* `tagbar` opened

#### vim-go version:
latest

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Vim-go
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:go_fmt_command = "goimports"
let g:go_info_mode='gopls'
let g:go_def_mode = 'gopls'
let g:go_decls_includes = "func,type"
let g:go_auto_type_info = 0
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_trailing_whitespace_error = 1
let g:go_highlight_function_parameters = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1
let g:go_metalinter_autosave = 0
let g:go_metalinter_enabled = ['vet', 'errcheck']
let g:go_metalinter_deadline = "5s"
let g:go_auto_sameids = 0
" let g:go_metalinter_autosave_enabled = ["golint"]
map <leader>gr :GoRun<cr>
map <leader>gd :GoDeclsDir<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => tagbar
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd VimEnter * TagbarOpen
nnoremap <silent> <leader>tt :TagbarToggle<cr>
</pre></details>

#### Vim version (first three lines from `:version`):

vim 8.0
#### Go version (`go version`):

go 1.13
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/dudu/go/bin"
GOCACHE="/home/dudu/.cache/go-build"
GOENV="/home/dudu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dudu/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build878049873=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by bhcleek** [comment]
Normally this jumping happens quickly, but with tagbar open either it slows things down enough that you see it or tagbar's autocmd event handlers are calling redraw.

I don't think there's anything for vim-go to do here, bit I'll look into it to see whether skipping autocmd events in the formatting code makes sense

**Comment by bhcleek** [comment]
I created #2621 , but I'm not merging it yet, because I'm want to make sure it's not going to cause other problems and need additional changes first. Feel free to give it a try.

**Comment by hellodudu** [comment]
With pleasure :)

**Comment by hellodudu** [comment]
It works fine after a few days trying. Closing this, thanks a lot.

**Comment by bhcleek** [comment]
@hellodudu I just want to be clear; you'd like #2621 to be merged and haven't noticed any problems with it?

**Comment by hellodudu** [comment]
Yes, I haven't met any problems, please merge it :)

**Comment by ciehanski** [comment]
Any update on this since [#2621](https://github.com/fatih/vim-go/pull/2621) was closed and not merged? I am still experiencing this issue unfortunately. Thanks!
