### ISSUE TITLE
Seems like most of the gopls integration is not working

### ISSUE THREAD

**Issue by mnarrell** [fatih/vim-go#2620]
### What did you expect to happen?

Jump to definition, GoReferrers normal operation

### What happened instead?

```
vim-go: [definition] FAIL
vim-go: no ParseGoHandle for file:///Users/matt/go/...
vim-go: [definition] FAIL
vim-go: no CheckPackageHandles for file:///Users/matt/go/...

vim-go: [referrers] FAIL
```

#### vim-go version:

master

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin('~/tmp/nvim/gogo')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()

scriptencoding utf-8

" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files() abort
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    GoBuild -i
  endif
endfunction

" call deoplete#custom#option('omni_patterns', { 'go': '[^. *\t]\.\w*' })

" let g:go_addtags_transform = 'camelcase'
" let g:go_doc_popup_window = 1
" let g:go_fmt_command = 'goimports'
" let g:go_fmt_fail_silently = 1
" let g:go_gorename_command = 'gopls'
" let g:go_list_height = 20
" let g:go_list_type = 'quickfix'
" let g:go_metalinter_command='golangci-lint run --print-issued-lines=false'
" let g:go_updatetime = 400

" let g:go_gopls_complete_unimported = 1
" let g:go_gopls_use_placeholders = 1

" augroup vimgo
"   au!
"   au Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
"   au Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
"   au Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
"   au Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')

"   au FileType go imap <C-g> <ESC>:<C-u>GoDeclsDir<CR>
"   au FileType go nmap <C-g> :GoDeclsDir<CR>

"   " Option-T
"   au FileType go nmap †  <Plug>(go-test-func)
"   au FileType go nmap db <Plug>(go-doc-browser)
"   au FileType go nmap de <Plug>(go-def-vertical)
"   au FileType go nmap gb :<C-u>call <SID>build_go_files()<CR>
"   au FileType go nmap gc <Plug>(go-callers)
"   au FileType go nmap gf <Plug>(go-referrers)
"   au FileType go nmap gi <Plug>(go-implements)
"   au FileType go nmap gr <Plug>(go-rename)
"   au FileType go nmap tc <Plug>(go-coverage-toggle)
" augroup END

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.13.5 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Users/matt/src/work/go/bin"
GOCACHE="/Users/matt/Library/Caches/go-build"
GOENV="/Users/matt/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="github.comcast.com"
GONOSUMDB="github.comcast.com"
GOOS="darwin"
GOPATH="/Users/matt/src/work/go"
GOPRIVATE="github.comcast.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/matt/src/work/go/src/github.comcast.com/yggdrasil/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sm/9898t_t55614dtvwzsljb07h0000gn/T/go-build052499623=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 1
g:go_loaded_gosnippets = 1
g:go_list_type = 'quickfix'
g:go_highlight_format_strings = 1
g:go_gopls_complete_unimported = 1
g:go_highlight_extra_types = 1
g:go_highlight_variable_declarations = 1
g:go_highlight_operators = 1
g:go_updatetime = 400
g:go_highlight_function_calls = 1
g:go_doc_popup_window = 1
g:go_highlight_fields = 1
g:go_highlight_trailing_whitespace_error = 0
g:go_highlight_generate_tags = 1
g:go_metalinter_command = 'golangci-lint run --print-issued-lines=false'
g:go_highlight_function_parameters = 1
g:go_highlight_variable_assignments = 1
g:go_highlight_diagnostic_errors = 0
g:go_highlight_structs = 1
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_string_spellcheck = 1
g:go_addtags_transform = 'camelcase'
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_highlight_space_tab_error = 0
g:go_highlight_types = 1
g:go_highlight_diagnostic_warnings = 0
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_highlight_methods = 1
g:go_gorename_command = 'gopls'
g:go_list_height = 20
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

**Comment by mnarrell** [comment]
A restart of (Neo)VIM resolves this temporarily.

**Comment by bhcleek** [comment]
what version of gopls are using (`gopls version` will tell you)?

**Comment by mnarrell** [comment]
```
$ gopls version
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
```

**Comment by bhcleek** [comment]
I'm using the same version of gopls and not seeing problems. Perhaps you're encountering a bug in gopls that is being surfaced due to your environment or workflow. If you can narrow it down, the gopls team would likely appreciate a clear set of steps to reproduce.

**Comment by mnarrell** [comment]
Sure.  I'll keep an eye on this...

**Comment by kyluke** [comment]
I experience this off an on too. Same version of gopls. Maybe it's related to some specific project structures.

**Comment by mnarrell** [comment]
I moved to proper VIM and I don’t see this. At least not yet?

**Comment by bhcleek** [comment]
Now that's interesting and potentially something I can act on. The gopls debug logs I mentioned earlier would be useful to figure out what's going on with neovim.

**Comment by bhcleek** [comment]
Sorry,wrong issue. The request for logs I referenced was on https://github.com/fatih/vim-go/issues/2603
