### ISSUE TITLE
vim-go not respecting filetype config

### ISSUE THREAD

**Issue by allyraza** [fatih/vim-go#2622]
### What did you do? (required: The issue will be **closed** when not provided)

I installed vim-go on ubuntu a fresh install, vim-go is auto formatting go code according to `ts=2, sw=2, et`

### What did you expect to happen?
I would expect my filetype settings to work as expected

### What happened instead?
vim-go is auto formatting go code according to `ts=2, sw=2, et`

### Configuration (**MUST** fill this out):

```autocmd Filetype go setlocal ts=2 sw=2 sts=0 expandtab```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

8.0

#### Go version (`go version`):

1.13

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
Is it the expand tab part of your expectations that isn't being met? If so, then this issue address your expectations: https://github.com/fatih/vim-go/issues/1228

**Comment by bhcleek** [comment]
@allyraza I'll leave this open for a couple more days to give you a chance to respond and will close it if I don't hear from you.

**Comment by bhcleek** [comment]
closing due to lack of feedback.
