### ISSUE TITLE
no ParseGoHandle for file

### ISSUE THREAD

**Issue by codcodog** [fatih/vim-go#2628]
### What did you do? (required: The issue will be **closed** when not provided)
use `gd` go to a function define, but it failed.

The project use `govendor` instead of `go mod`, so there is no `go.mod` file.

### What did you expect to happen?
Go to the function define.
### What happened instead?
It failed: `vim-go: no ParseGoHandle for file`
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
" ============= Plug 配置 END =============
"
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" tab对齐
Plug 'godlygeek/tabular'

" 括号成对
Plug 'chun-yang/auto-pairs'

" Python 语法高亮
Plug 'hdima/python-syntax', {'for': 'python'}
" Python 缩进
Plug 'hynek/vim-python-pep8-indent', {'for': 'python'}
" Python 查看缩进
Plug 'Yggdroot/indentLine'

" markdown编辑器及其实时查看
Plug 'plasticboy/vim-markdown', {'for': 'markdown'}
Plug 'suan/vim-instant-markdown', {'for': 'markdown'}

" 前端emmet插件
Plug 'mattn/emmet-vim', {'for': ['html', 'vue']}

" 查看目录结构
Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}

" 函数列表
Plug 'majutsushi/tagbar', {'on': 'TagbarToggle'}

" fuzzy finding
Plug 'junegunn/fzf.vim'

" vue
Plug 'posva/vim-vue'

Plug 'SirVer/ultisnips'

" theme
Plug 'morhetz/gruvbox'
Plug 'dracula/vim', { 'as': 'dracula' }

" go
Plug 'fatih/vim-go', {'for': 'go'}

Plug 'Valloric/YouCompleteMe'
"
" List ends here. Plugins become visible to Vim after this call.
call plug#end() 
"
" ============= Plug 配置 END =============
"
"
"
" ============= Theme 配置 START ==========
"
set termguicolors
syntax on

syntax sync minlines=50
set synmaxcol=300  " stop syntax highlighting this many columns out
nnoremap <silent> <F5> :syntax sync fromstart<CR>

let g:gruvbox_contrast_dark = 'hard'
set background=dark
colorscheme gruvbox

" 覆盖 gruvbox 主题颜色设置
augroup DIY
    autocmd!
    autocmd ColorScheme * highlight Normal ctermbg=NONE guibg=#1d1f21
    autocmd ColorScheme * highlight CursorLine ctermbg=NONE guibg=#26292b
    autocmd WinEnter * setlocal cursorline
    autocmd WinLeave * setlocal nocursorline
    autocmd ColorScheme * highlight! link Visual CursorLine
    autocmd InsertEnter * highlight ColorColumn ctermbg=NONE guibg=#1a1b1d
    autocmd InsertLeave * highlight ColorColumn ctermbg=NONE guibg=NONE
    autocmd InsertEnter * let &colorcolumn=join(range(121, 999), ',')
    autocmd InsertLeave * let &colorcolumn=0
augroup END
"
" ============= Theme 配置 END =============
"
"
"
" ============= Options 配置 START =============
"
set expandtab                " 设置tab键换空格
set tabstop=4                " 设置tab键的宽度
set encoding=utf-8           " 设置字符编码
set shiftwidth=4             " 换行时行间交错使用4个空格
set autoindent               " 自动对齐
set cindent                  " 自动缩进4空格
set smartindent              " 智能自动缩进
set number                   " 设置行号
set rnu                      " 相对行号
set hlsearch                 " 开启高亮显示结果
set noincsearch              " 不实时查找
set wrapscan                 " 查找到底部重新回到头部
set tags=tags;/              " 设置ctags, vim在当前目录找不到tags文件时请到上层目录查找。
set splitright               " 设置vsplit在右边
set laststatus=2             " 总是显示状态栏
set directory=/tmp           " 设置swp文件存储目录
set cscopetag                " 开启 cscope
set cursorline               " 高亮当前行

set statusline=%t                                           " 文件名
set statusline+=%4m%r%w                                     " modified flag, Modified, Readonly ?
set statusline+=%=                                          " 切换到右边
set statusline+=%{toupper(&ff).'·'}                         " file format
set statusline+=%{toupper(strlen(&fenc)?&fenc:'none')}      " file encoding
set statusline+=%8(%l,%c%)                                  " line and column
set statusline+=%5P                                         " Percentage through file of displayed window
"
" ============= Options 配置 END =============
"
"
"
" =============  BASIC 映射键 配置 START =============
inoremap jj <ESC>
inoremap <C-b> <Left>
inoremap <C-f> <Right>
noremap <C-j> <C-w>j<CR>
noremap <C-k> <C-w>k<CR>
noremap <C-h> <C-w>W<CR>
noremap <C-l> <C-w>w<CR>
nnoremap <Left> :vertical resize +2<CR>
nnoremap <Right> :vertical resize -2<CR>
nnoremap <Up> :resize -2<CR>
nnoremap <Down> :resize +2<CR>
cnoremap w!! <c-u>w !sudo tee > /dev/null %
cnoremap <C-b> <Left>
cnoremap <C-f> <Right>
cnoremap <C-a> <Home>
exe "set <A-b>=\eb"
exe "set <A-f>=\ef"
cnoremap <A-b> <C-Left>
cnoremap <A-f> <C-Right>
tnoremap <ESC> <C-W>N
noremap <silent><C-]> :<C-u>MultiTag <C-r><C-w><CR>
noremap <silent><C-p> <C-x><C-o>
"
" ============= BASIC 映射键 配置 END =============
"
"
"
" ============= <LEADER> 配置 START =============
"
let mapleader=','   " 设置 <leader> 键
noremap <silent> <leader>w :update<CR>
noremap <silent> <leader>o :only<CR>
noremap <silent> <leader>v :vsp<CR>
noremap <silent> <leader>s :sp<CR><C-W>k
noremap <silent> <leader>q :quit<CR>
noremap <silent> <leader>d :bw<CR>
vnoremap <silent> <leader>a :Tab/=<CR>
vnoremap <silent> <leader>> :Tab/=><CR>
noremap <silent> <leader>n :noh<CR>
noremap <silent> <leader>, :vsplit $MYVIMRC<CR>:normal 107Gzz<CR>
noremap <leader>. :source $MYVIMRC<CR>
noremap <silent> <leader>c :vertical terminal<CR>
"
" ============= <LEADER> 配置 END ==============
"
"
"
" ============= 自定义命令配置 START =============
"
" buffers management
command! Only  call <SID>OnlyCurrentBufferCodcodog()

" dependent on fzf plugin
command! -bang -nargs=* MultiTag call <SID>multitag(<q-args>)

function! s:multitag(query)
    let pattern = '^'.a:query.'$'
    let tags    = taglist(pattern)
    let qfl     = []

    " only one tag name
    if (len(tags) == 1)
        silent execute 'silent! tag '.a:query.'|normal! zz'
        return
    " no tags
    elseif (len(tags) == 0)
        echohl WarningMsg
        echo 'Tags Not Found.'
        echohl None
        return
    endif

    " multiple tag names
    for tag in tags
        let filename = tag['filename']
        let pattern  = tag['cmd']
        let des      = filename . '|' . pattern

        call add(qfl, des)
    endfor

    call fzf#run({'source': qfl, 'sink': function('s:tagsink'), 'down': '~20%'})
endfunction

function! s:tagsink(tag)
    let tmp  = split(a:tag, '|')
    let file = tmp[0]
    " 关闭 pattern magic, 防止函数有特殊字符没法匹配，例如：`* .` 这些字符
    let cmd  = '/\M'.tmp[1][1:]
    echom cmd

    execute 'silent! e '.file.'|set ws|silent! '.cmd.'|normal! zz'
endfunction

" command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--ignore tags', {'options': '--delimiter : --nth 4..'}, <bang>0)
command! -bang -nargs=* Ag call fzf#vim#ag_raw(<q-args>, <bang>0)
"
" ============= 自定义命令配置 END =============
"
"
"
" ============= 插件配置 START =============
"
" fzf
set rtp+=~/.fzf
let g:fzf_layout = { 'down': '~20%' }

nnoremap <Leader>a :<C-u>Ag -w <C-r><C-w><CR>
nnoremap <silent> <leader>h :History<CR>
nnoremap <silent> <C-P> :Files<CR>
nnoremap <silent> <space><space> :Buffers<CR>

" NERDTree
let g:NERDTreeQuitOnOpen = 1
let NERDTreeShowLineNumbers = 1
noremap <silent> <C-n> :NERDTreeToggle<CR>

" tagbar
let g:tagbar_left = 1
let g:tagbar_autoclose = 1
let g:tagbar_show_linenumbers = 2
let g:tagbar_sort = 0

let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

noremap <silent> <leader>t :TagbarToggle<CR>
noremap <silent> <leader>f :BTags<CR>

" Python-syntax
let python_highlight_all = 1
syntax enable                " 打开语法高亮
syntax on                    " 开启文件类型侦测

" indentLine 
let g:indentLine_enabled = 0 " 默认关闭

" go
let g:go_fmt_command = "goimports"
" let g:go_fmt_fail_silently = 1
" let g:go_fmt_autosave = 0 " 关闭自动格式化代码

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_function_parameters = 1

let g:go_def_mapping_enabled = 0
let g:go_def_mode = 'gopls'

au FileType go noremap <silent> gd :GoDef<CR>
au FileType go inoremap <silent> <C-j> <ESC>3b:<C-u>GoImport <C-r><C-w><CR>zz3ea
au FileType go cnoremap GG <C-u>GoImport 

" YCM
set completeopt=longest,menu
let g:ycm_collect_identifiers_from_tags_files=1
let g:ycm_seed_identifiers_with_syntax=1
let g:ycm_filetype_blacklist = {
      \ 'tagbar' : 1,
      \ 'nerdtree' : 1,
      \}
let g:ycm_auto_trigger = 0
let g:ycm_show_diagnostics_ui = 0
let g:ycm_key_invoke_completion = '<C-o>'
"let g:ycm_collect_identifiers_from_comments_and_strings = 1

" UltiSnips 
let g:UltiSnipsExpandTrigger="<c-l>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/mysnippets']
"
" ============= 插件配置 END =============
"
"
"
" ============= 自定义配置 START =============
"
" 字典补全
set dictionary+=$HOME/.vim/doc/dict.txt
set complete+=k

" PHP 函数补全
function! s:AddPHPFuncListCodcodog()
    set dictionary-=$HOME/.vim/doc/php.txt dictionary+=$HOME/.vim/doc/php.txt
    set complete-=k complete+=k
endfunction

" go 补全
function! s:GoCompletionCodcodog()
    set dictionary-=$HOME/.vim/doc/go.txt dictionary+=$HOME/.vim/doc/go.txt
    set complete-=k complete+=k
endfunction

" python 补全
function! s:PythonCompletionCodcodog()
    set dictionary-=$HOME/.vim/doc/python.txt dictionary+=$HOME/.vim/doc/python.txt
    set complete-=k complete+=k
endfunction

" 保留当前可见 buffer, wipe out 其他不可见 buffers
function! s:OnlyCurrentBufferCodcodog()
    " list of *all* buffer numbers
    let l:buffers = range(1, bufnr('$'))

    " what tab page are we in?
    let l:currentTab = tabpagenr()
    try
        " go through all tab pages
        let l:tab = 0
        while l:tab < tabpagenr('$')
            let l:tab += 1

            " go through all windows
            let l:win = 0
            while l:win < winnr('$')
                let l:win += 1
                " whatever buffer is in this window in this tab, remove it from
                " l:buffers list
                let l:thisbuf = winbufnr(l:win)
                call remove(l:buffers, index(l:buffers, l:thisbuf))
            endwhile
        endwhile

        " if there are any buffers left, delete them
        if len(l:buffers)
            execute 'bwipeout' join(l:buffers)
        endif
    finally
        " go back to our original tab page
        execute 'tabnext' l:currentTab
    endtry
endfunction

" PHP 文件，启用补全
augroup filetype_php
    autocmd!
    autocmd FileType php call <SID>AddPHPFuncListCodcodog()
augroup END 

augroup filetype_go
    autocmd!
    autocmd FileType go call <SID>GoCompletionCodcodog()
augroup END 

" Shell 文件，缩进修改为2个空格
augroup filetype_sh
    autocmd!
    autocmd FileType sh,yaml
                \ set tabstop=2 |
                \ set shiftwidth=2
augroup END

" python 文件，可视化缩进
" 加载补全
augroup filetype_python
    autocmd!
    " indentLine 插件配置
    autocmd FileType python
                \ let g:indentLine_enabled=1 |
                \ let g:indentLine_char='·'
    autocmd FileType python call <SID>PythonCompletionCodcodog()
augroup END
"
" ============= 自定义配置 START =============

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2019 22:30:47)
Included patches: 1-2268
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.13.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cryven/.cache/go-build"
GOENV="/home/cryven/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cryven/coding/azoya_product_query"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build309583313=/tmp/go-build -gno-record-gcc-switches"

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_gosnippets = 1
g:go_highlight_function_calls = 1
g:go_highlight_fields = 1
g:go_def_mode = 'gopls'
g:go_highlight_function_parameters = 1
g:go_highlight_functions = 1
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_install = 1
g:go_def_mapping_enabled = 0
</pre></details>

**Comment by bhcleek** [comment]
Is your project in GOPATH?

What version of gopls do you have installed (you can tell by running `gopls version`)?

**Comment by mnarrell** [comment]
This resembles #2620 I opened/closed last week. I forgot to mention I’m in a mixed modules scenario. My monorepo lives beneath the GOPATH, but is all modularized.

**Comment by codcodog** [comment]
> Is your project in GOPATH?
> 
> What version of gopls do you have installed (you can tell by running `gopls version`)?

I export `GOPATH` on my project.

```bash
$ gopls version 
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
```

and I add `let g:go_debug=['lsp']` on my `.vimrc`.  

`__GOLSP_LOG__` output:
```
sent: Content-Length: 209

{"method":"textDocument/definition","jsonrpc":"2.0","id":4,"params":{"textDocument":{"uri":"file:///home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go"},"position":{"character":30,"line":24}}}
sent: Content-Length: 971

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package routers\n\nimport (\n\t\"api/v2/controllers\"\n\t\"azoya/nova\"\n)\n\nfunc RegisterRoutes(router *nova.Engine) {\n\n\tlists := controllers.NewListsControler()\n\tsuggest := controllers.NewSuggestController()\n\tcache := controllers.NewCacheControler()\n\tsearch := controllers.NewSearchController()\n\tbrand := controllers.NewBrandController()\n\n\tv2 := router.Group(\"/v2\")\n\t{\n\n\t\tv2.GET(\"/lists\", lists.Index)\n\t\tv2.GET(\"/fetch\", lists.Fetch)\n\t\tv2.POST(\"/fetch\", lists.Fetch)\n\t\tv2.GET(\"/cache/flush\", cache.Flush)\n\t\tv2.GET(\"/lists/brand\", lists.Brand)\n\t\tv2.GET(\"/suggest\", suggest.Index)\n\t\tv2.GET(\"/search\", search.Index)\n\t\tv2.GET(\"/search/brand\", search.Brand)\n\t\tv2.GET(\"/brand\", brand.Index)\n\n\t}\n\n}\n"}],"textDocument":{"uri":"file:///home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go","version":4}}}
received: Content-Length: 131

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 go/packages.Load\n\tpackages = 1"}}
received: Content-Length: 2504

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 27.148154ms for GOROOT= GOPATH=/home/cryven/coding/azoya_product_query GO111MODULE= PWD=/home/cryven/coding/azoya_product_query/src/api/v2/routers go \"list\" \"-e\" \"-json\" \"-compiled=true\" \"-test=true\" \"-export=false\" \"-deps=true\" \"-find=false\" \"--\" \"/home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go\", stderr: \u003c\u003c\u003e\u003e stdout: \u003c\u003c{\n\t\"ImportPath\": \"api/v2/controllers\",\n\t\"DepOnly\": true,\n\t\"Incomplete\": true,\n\t\"Stale\": true,\n\t\"StaleReason\": \"build ID mismatch\",\n\t\"Error\": {\n\t\t\"ImportStack\": [\n\t\t\t\"main\",\n\t\t\t\"api/v2/controllers\"\n\t\t],\n\t\t\"Pos\": \"routes.go:4:2\",\n\t\t\"Err\": \"malformed module path \\\"api/v2/controllers\\\": missing dot in first path element\"\n\t}\n}\n{\n\t\"ImportPath\": \"azoya/nova\",\n\t\"DepOnly\": true,\n\t\"Incomplete\": true,\n\t\"Stale\": true,\n\t\"StaleReason\": \"build ID mismatch\",\n\t\"Error\": {\n\t\t\"ImportStack\": [\n\t\t\t\"main\",\n\t\t\t\"azoya/nova\"\n\t\t],\n\t\t\"Pos\": \"routes.go:5:2\",\n\t\t\"Err\": \"malformed module path \\\"azoya/nova\\\": missing dot in first path element\"\n\t}\n}\n{\n\t\"Dir\": \"/home/cryven/coding/azoya_product_query/src/api/v2/routers\",\n\t\"ImportPath\": \"command-line-arguments\",\n\t\"Name\": \"routers\",\n\t\"Root\": \"/home/cryven/coding/azoya_product_query\",\n\t\"Module\": {\n\t\t\"Path\": \"command-line-arguments\",\n\t\t\"Main\": true\n\t},\n\t\"Match\": [\n\t\t\"/home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go\"\n\t],\n\t\"Incomplete\": true,\n\t\"Stale\": true,\n\t\"StaleReason\": \"stale dependency: api/v2/controllers\",\n\t\"GoFiles\": [\n\t\t\"routes.go\"\n\t],\n\t\"CompiledGoFiles\": [\n\t\t\"routes.go\"\n\t],\n\t\"Imports\": [\n\t\t\"api/v2/controllers\",\n\t\t\"azoya/nova\"\n\t],\n\t\"Deps\": [\n\t\t\"api/v2/controllers\",\n\t\t\"azoya/nova\"\n\t],\n\t\"DepsErrors\": [\n\t\t{\n\t\t\t\"ImportStack\": [\n\t\t\t\t\"main\",\n\t\t\t\t\"api/v2/controllers\"\n\t\t\t],\n\t\t\t\"Pos\": \"routes.go:4:2\",\n\t\t\t\"Err\": \"malformed module path \\\"api/v2/controllers\\\": missing dot in first path element\"\n\t\t},\n\t\t{\n\t\t\t\"ImportStack\": [\n\t\t\t\t\"main\",\n\t\t\t\t\"azoya/nova\"\n\t\t\t],\n\t\t\t\"Pos\": \"routes.go:5:2\",\n\t\t\t\"Err\": \"malformed module path \\\"azoya/nova\\\": missing dot in first path element\"\n\t\t}\n\t]\n}\n\u003e\u003e\n"}}
received: Content-Length: 233

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 go/packages.Load\n\tpackage = command-line-arguments\n\tfiles = [/home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go]"}}
received: Content-Length: 233

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 go/packages.Load\n\tpackage = command-line-arguments\n\tfiles = [/home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go]"}}
received: Content-Length: 131

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 go/packages.Load\n\tpackages = 1"}}
received: Content-Length: 2504

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 20.278123ms for GOROOT= GOPATH=/home/cryven/coding/azoya_product_query GO111MODULE= PWD=/home/cryven/coding/azoya_product_query/src/api/v2/routers go \"list\" \"-e\" \"-json\" \"-compiled=true\" \"-test=true\" \"-export=false\" \"-deps=true\" \"-find=false\" \"--\" \"/home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go\", stderr: \u003c\u003c\u003e\u003e stdout: \u003c\u003c{\n\t\"ImportPath\": \"api/v2/controllers\",\n\t\"DepOnly\": true,\n\t\"Incomplete\": true,\n\t\"Stale\": true,\n\t\"StaleReason\": \"build ID mismatch\",\n\t\"Error\": {\n\t\t\"ImportStack\": [\n\t\t\t\"main\",\n\t\t\t\"api/v2/controllers\"\n\t\t],\n\t\t\"Pos\": \"routes.go:4:2\",\n\t\t\"Err\": \"malformed module path \\\"api/v2/controllers\\\": missing dot in first path element\"\n\t}\n}\n{\n\t\"ImportPath\": \"azoya/nova\",\n\t\"DepOnly\": true,\n\t\"Incomplete\": true,\n\t\"Stale\": true,\n\t\"StaleReason\": \"build ID mismatch\",\n\t\"Error\": {\n\t\t\"ImportStack\": [\n\t\t\t\"main\",\n\t\t\t\"azoya/nova\"\n\t\t],\n\t\t\"Pos\": \"routes.go:5:2\",\n\t\t\"Err\": \"malformed module path \\\"azoya/nova\\\": missing dot in first path element\"\n\t}\n}\n{\n\t\"Dir\": \"/home/cryven/coding/azoya_product_query/src/api/v2/routers\",\n\t\"ImportPath\": \"command-line-arguments\",\n\t\"Name\": \"routers\",\n\t\"Root\": \"/home/cryven/coding/azoya_product_query\",\n\t\"Module\": {\n\t\t\"Path\": \"command-line-arguments\",\n\t\t\"Main\": true\n\t},\n\t\"Match\": [\n\t\t\"/home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go\"\n\t],\n\t\"Incomplete\": true,\n\t\"Stale\": true,\n\t\"StaleReason\": \"stale dependency: api/v2/controllers\",\n\t\"GoFiles\": [\n\t\t\"routes.go\"\n\t],\n\t\"CompiledGoFiles\": [\n\t\t\"routes.go\"\n\t],\n\t\"Imports\": [\n\t\t\"api/v2/controllers\",\n\t\t\"azoya/nova\"\n\t],\n\t\"Deps\": [\n\t\t\"api/v2/controllers\",\n\t\t\"azoya/nova\"\n\t],\n\t\"DepsErrors\": [\n\t\t{\n\t\t\t\"ImportStack\": [\n\t\t\t\t\"main\",\n\t\t\t\t\"api/v2/controllers\"\n\t\t\t],\n\t\t\t\"Pos\": \"routes.go:4:2\",\n\t\t\t\"Err\": \"malformed module path \\\"api/v2/controllers\\\": missing dot in first path element\"\n\t\t},\n\t\t{\n\t\t\t\"ImportStack\": [\n\t\t\t\t\"main\",\n\t\t\t\t\"azoya/nova\"\n\t\t\t],\n\t\t\t\"Pos\": \"routes.go:5:2\",\n\t\t\t\"Err\": \"malformed module path \\\"azoya/nova\\\": missing dot in first path element\"\n\t\t}\n\t]\n}\n\u003e\u003e\n"}}
received: Content-Length: 170

{"jsonrpc":"2.0","error":{"code":0,"message":"no CheckPackageHandles for file:///home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go","data":null},"id":4}
received: Content-Length: 667

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 9.258308ms for GOROOT= GOPATH=/home/cryven/coding/azoya_product_query GO111MODULE= PWD=/home/cryven/coding/azoya_product_query/src/api/v2/routers go \"list\" \"-e\" \"-json\" \"-compiled=true\" \"-test=true\" \"-export=false\" \"-deps=true\" \"-find=false\" \"--\" \"/home/cryven/coding/azoya_product_query/src/api/v2/routers\", stderr: \u003c\u003cgo: cannot find main module, but found glide.lock in /home/cryven/coding/azoya_product_query/src\n\tto create a module there, run:\n\tcd ../../.. \u0026\u0026 go mod init\n\u003e\u003e stdout: \u003c\u003c\u003e\u003e\n"}}
received: Content-Length: 668

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 13.950314ms for GOROOT= GOPATH=/home/cryven/coding/azoya_product_query GO111MODULE= PWD=/home/cryven/coding/azoya_product_query/src/api/v2/routers go \"list\" \"-e\" \"-json\" \"-compiled=true\" \"-test=true\" \"-export=false\" \"-deps=true\" \"-find=false\" \"--\" \"/home/cryven/coding/azoya_product_query/src/api/v2/routers\", stderr: \u003c\u003cgo: cannot find main module, but found glide.lock in /home/cryven/coding/azoya_product_query/src\n\tto create a module there, run:\n\tcd ../../.. \u0026\u0026 go mod init\n\u003e\u003e stdout: \u003c\u003c\u003e\u003e\n"}}
received: Content-Length: 407

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 36.66481ms for GOROOT= GOPATH=/home/cryven/coding/azoya_product_query GO111MODULE= PWD=/home/cryven/coding/azoya_product_query/src/api/v2/routers go \"list\" \"-m\" \"-json\" \"all\", stderr: \u003c\u003cwarning: pattern \"all\" matched no module dependencies\n\u003e\u003e stdout: \u003c\u003c\u003e\u003e\n"}}
received: Content-Length: 408

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 33.182192ms for GOROOT= GOPATH=/home/cryven/coding/azoya_product_query GO111MODULE= PWD=/home/cryven/coding/azoya_product_query/src/api/v2/routers go \"list\" \"-m\" \"-json\" \"all\", stderr: \u003c\u003cwarning: pattern \"all\" matched no module dependencies\n\u003e\u003e stdout: \u003c\u003c\u003e\u003e\n"}}
received: Content-Length: 346

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 24.792528ms for GOROOT= GOPATH=/home/cryven/coding/azoya_product_query GO111MODULE= PWD=/home/cryven/coding/azoya_product_query/src/api/v2/routers go \"env\" \"GOMOD\", stderr: \u003c\u003c\u003e\u003e stdout: \u003c\u003c/dev/null\n\u003e\u003e\n"}}
received: Content-Length: 346

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/12/20 09:24:00 21.372968ms for GOROOT= GOPATH=/home/cryven/coding/azoya_product_query GO111MODULE= PWD=/home/cryven/coding/azoya_product_query/src/api/v2/routers go \"env\" \"GOMOD\", stderr: \u003c\u003c\u003e\u003e stdout: \u003c\u003c/dev/null\n\u003e\u003e\n"}}
```

**Comment by bhcleek** [comment]
Is `/home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go`  completely empty by chance?

I'm wondering if you're getting hit by https://github.com/golang/go/issues/35949.

**Comment by codcodog** [comment]
> Is `/home/cryven/coding/azoya_product_query/src/api/v2/routers/routes.go` completely empty by chance?
> 
> I'm wondering if you're getting hit by [golang/go#35949](https://github.com/golang/go/issues/35949).

It's not empty.
```
routers 「master」$ pwd
/home/cryven/coding/azoya_product_query/src/api/v2/routers
routers 「master」$ cat routes.go 
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: routes.go
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ package routers
   2   │ 
   3   │ import (
   4   │     "api/v2/controllers"
   5   │     "azoya/nova"
   6   │ )
   7   │ 
   8   │ func RegisterRoutes(router *nova.Engine) {
   9   │ 
  10   │     lists := controllers.NewListsControler()
  11   │     suggest := controllers.NewSuggestController()
  12   │     cache := controllers.NewCacheControler()
  13   │     search := controllers.NewSearchController()
  14   │     brand := controllers.NewBrandController()
  15   │ 
  16   │     v2 := router.Group("/v2")
  17   │     {
  18   │ 
  19   │         v2.GET("/lists", lists.Index)
  20   │         v2.GET("/fetch", lists.Fetch)
  21   │         v2.POST("/fetch", lists.Fetch)
  22   │         v2.GET("/cache/flush", cache.Flush)
  23   │         v2.GET("/lists/brand", lists.Brand)
  24   │         v2.GET("/suggest", suggest.Index)
  25   │         v2.GET("/search", search.Index)
  26   │         v2.GET("/search/brand", search.Brand)
  27   │         v2.GET("/brand", brand.Index)
  28   │ 
  29   │     }
  30   │ 
  31   │ }

```

**Comment by bhcleek** [comment]
Does the error go away if you concatenate lines 16 and 17 of routes.go?

**Comment by codcodog** [comment]
> Does the error go away if you concatenate lines 16 and 17 of routes.go?

That would be a syntax error.

Maybe the project use a private package, so `gopls` failed?
> there are some third packages not in github.

**Comment by bhcleek** [comment]
Yes, it would be a syntax error generally, but I'm not sure how gopls is going to handle that when it's trying to parse the file - I think it's worth correcting that file since it's the one for which the error is being reported.

The private packages could be a problem. Assuming that you have `azoya/nova` and `api/v2/controllers` in your GOPATH or that they're vendored and you have `GOFLAGS=-mod=vendor` set, using `GO111MODULE=off` may also be useful to overcome this error.

**Comment by codcodog** [comment]
> Yes, it would be a syntax error generally, but I'm not sure how gopls is going to handle that when it's trying to parse the file - I think it's worth correcting that file since it's the one for which the error is being reported.
> 
> The private packages could be a problem. Assuming that you have `azoya/nova` and `api/v2/controllers` in your GOPATH or that they're vendored and you have `GOFLAGS=-mod=vendor` set, using `GO111MODULE=off` may also be useful to overcome this error.

I export `GOFLAGS=-mod=vendor` and `GO111MODULE=off` to my terminal. It works， but get a new error `vim-go: internal error: go list gives conflicting information for package vendor/golang.org/x/text/transform`.

Anyway, `gopls` works.

**Comment by codcodog** [comment]
`vim-go: internal error: go list gives conflicting information for package vendor/golang.org/x/text/transform`  
this error is because of my go version(`go1.13.5`).  
I change it to `go1.11.13`, it works.

Thanks @bhcleek.
And I closed this issue.
