### ISSUE TITLE
move to function declaration not working at elastic project

### ISSUE THREAD

**Issue by pan-sultan** [fatih/vim-go#2629]
### What did you do? (required: The issue will be **closed** when not provided)
1. download source code with command go get -v github.com/elastic/beats
2. try to move to some function. For example, 
> gvim winlogbeat/eventlog/wineventlog.go
> /Errorf
> press CTRL+P keeping cursor on Errorf
if the error is not reproduced then go back CTRL+T and press CTRL+P again at least two times.

### What did you expect to happen?
To move to declaration of Errorf in package fmt.

### What happened instead?
I got the error
vim-go: no CheckPackageHandles for file:///home/alek/go/src/github.com/elastic/beats/winlogbeat/eventlog/wineventlog.go
and no more happens

#### vim-go version:
latest
commit b1b9a1b0d4e9b2408b29ed566135f56ec27629b9

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()

if has("gui_running")
	set go=a
	set guifont=Ubuntu\ Mono\ 18
else
	set mouse=nvi
endif

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, D1CEC1D0C0CDCE Dec 19 2019 14:03:41)
A7C0CFCBC0D2CAC8: 1-23
B1CACECCCFC8CBC8D0CEC2C0CDCE:  

#### Go version (`go version`):

go version go1.13.1 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alek/.cache/go-build"
GOENV="/home/alek/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/alek/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/alek/soft/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/alek/soft/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build181430984=/tmp/go-build -gno-record-gcc-switches"

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

**Comment by bhcleek** [comment]
What version of `gopls` are you running (`gopls version` will tell you)?

FWIW, there's an error in that file: there is no `errors.Errorf` function. However, jumping to `fmt.Errorf`'s definition works fine for me:

![recording](https://user-images.githubusercontent.com/1958864/71201210-68d7fb80-224e-11ea-8174-22ece66606fa.gif)

**Comment by pan-sultan** [comment]
I run :GoUpdateBinaries so I think it is latest. But how to know version of gopls? --help does not see --version or something.
Try twice like me here CTRL+P then go back with CTRL+T then again CTRL+P
![Peek 2019-12-19 22-51](https://user-images.githubusercontent.com/26022428/71205076-b9814000-22b2-11ea-8542-a3e31065f8eb.gif)

**Comment by pan-sultan** [comment]
By the way, elastic/beats has two files with same name but different path.
(1) src/github.com/elastic/beats/winlogbeat/eventlog/wineventlog.go
(2) src/github.com/elastic/beats/winlogbeat/beater/winlogbeat.go
this issue is reproducible only with (1). With file (2) works fine.

**Comment by pan-sultan** [comment]
Sorry I did miss what you wrote about version command
the version
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=

**Comment by bhcleek** [comment]
`ctrl-p` moves up a line. Are you saying that trying to go up two lines by pressing ctrl-p fails, or do you have some kind of ctrl-p mapping that's not represented in the vimrc you posted?

**Comment by pan-sultan** [comment]
My mistake. Of course it is CTRL + ] then CTRL + T then CTRL + ]

**Comment by bhcleek** [comment]
Ok, let's break this down:

1. Go to `fmt.Errorf` and place the cursor in `Errorf`.
2. ctrl-] to jump to the definition of `fmt.Errorf`.
3. ctrl-t to jump back
4. ctrl-] to jump again

This all works for me; I can't duplicate the error you're seeing.

@stamblerre do you have any idea what might be going on in gopls that would cause this?

**Comment by pan-sultan** [comment]
I wrote small piece of code which I put in $GOPATH/src/tmp/main.go.
This code reproduces the issue
```go
package main

import (
	"fmt"

	"golang.org/x/sys/windows"
)

func main() {
	signalEvent, err := windows.CreateEvent(nil, 0, 0, nil)
	if err != nil {
		return nil
	}
	defer windows.CloseHandle(signalEvent)
	fmt.Println("exit")
}
```
You can repeat the steps here for fmt.Println() instead of fmt.Errorf()

1. Go to fmt.Println and place the cursor in Println.
2. ctrl-] to jump to the definition of fmt.Println.
3. ctrl-t to jump back
4. ctrl-] to jump again

So, if I comment out
> "golang.org/x/sys/windows"

jumping to definition will work fine again.
By the way, I am browsing Windows go code under Linux.

**Comment by bhcleek** [comment]
I was running a later version version of gopls than is installed by vim-go by default. Once I reset gopls to the latest release, I was able to duplicate the problem you're seeing. For me, setting `:GoBuildTags windows` resolved the error. Does it resolve it for you, too?

**Comment by pan-sultan** [comment]
Yes, it resolved the error. Should I close the issue?

**Comment by bhcleek** [comment]
Yes. When you want to use build constraints, please use `:GoBuildTags`.

**Comment by pan-sultan** [comment]
Thank you very much for help.
