### ISSUE TITLE
diagnostic highlight groups are not cleared when displaying a different buffer in a window

### ISSUE THREAD

**Issue by artem-nefedov** [fatih/vim-go#2631]
### What did you do? (required: The issue will be **closed** when not provided)

1. Create new file and add some line with "bad" code, e.g.:
```
package main

import "badimport"
```
2. Save the file (vim says `vim-go: initialized gopls`, "bad" block gets highlighted in red)
3. Open another buffer in the same window:
```
:e test
```
4. Start typing over the same line where "bad" block was located:
```


xxxxxxx[red block will start here]
```

### What did you expect to happen?

Red blocks are cleared when new buffer is opened.

### What happened instead?

Red block will stay in the same place forever, unless window is closed.

#### vim-go version:
b1b9a1b [2019-12-18 09:42:59]

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.5.0-781c708
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):
go version go1.13.4 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/anefedov/.go/bin"
GOCACHE="/Users/anefedov/Library/Caches/go-build"
GOENV="/Users/anefedov/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/anefedov/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lr/m35dp_8d1zg9trl5tjmwxyxmg2hcnp/T/go-build049015796=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment]
I'll get the fix for this in soon. Until then, you can work around it by fixing the error in the file; that should cause the red block to disappear.

**Comment by bhcleek** [comment]
@artem-nefedov you can also disable the diagnostics highlighting by using `g:go_highlight_diagnostic_errors` and `g:go_highlight_diagnostic_warnings` options.
