### ISSUE TITLE
Support for raising verbosity of gopls as metalinter

### ISSUE THREAD

**Issue by chenclee** [fatih/vim-go#2636]
### What did you do? (required: The issue will be **closed** when not provided)
Setting the GoMetaLinter to gopls on some existing codebases may result in a large number of warnings that are not feasible to fix / not worth fixing. Similar to the highlighting options split into errors/warnings, it would be nice if metalinter or gopls could be configured to not show warnings in the locationlist/quickfix.

### What did you expect to happen?
GoMetaLinter or gopls could be configured to not show warning diagnostic messages.

### What happened instead?
GoMetaLinter shows both warning and error diagnostic messages with no way to change this.

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
let g:go_fmt_command = 'goimports'
let g:go_fmt_fail_silently = 1
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['gopls']
let g:go_metalinter_command = 'gopls'
let g:go_highlight_diagnostic_warnings = 0
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 26 2019 21:43:07)
macOS version
Included patches: 1-2350

#### Go version (`go version`):

go version go1.13.5 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/[redacted]/Library/Caches/go-build"
GOENV="/Users/[redacted]/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="[redacted]"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7m/_6t6541d1x5c0bhh90dzkfqmyj8v8r/T/go-build282814583=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
</pre></details>

**Comment by bhcleek** [comment]
@stamblerre are there any plans to implement this as a configuration option in gopls? If not, vim-go can filter them out, but I'm hesitant to add that feature to vim-go if there are plans to control it in gopls.

**Comment by stamblerre** [comment]
`gopls` has a setting called `experimentalDisabledAnalyses` which is a list of the names of analyses that `gopls` should not run. Other than that, we don't have anything planned for the near future. Ultimately, we will need to add more granular settings, but that work will be done when we have a more comprehensive plan for analyses, linting, and staticcheck.

**Comment by bhcleek** [comment]
#3050 resolved this initially with a further modification in #3052.
