### ISSUE TITLE
Vim-go auto-selecting the first item in the auto-completion menu

### ISSUE THREAD

**Issue by theniceboy** [fatih/vim-go#2647]
### What did you do? (required: The issue will be **closed** when not provided)
I'm using coc.nvim. I put 	`"suggest.noselect": true` in my `coc-settings.json` and I put `set completeopt=longest,noinsert,menuone,noselect,preview` in my vimrc, but it seems like vim-go is overwriting this setting.

### What did you expect to happen?
The first option in the autocompletion menu should not get highlighted unless I press tab.

### What happened instead?
The first option in the autocompletion menu gets highlighted sometimes without me pressing tab.

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
" ===
" === vim-go
" ===
let g:go_def_mapping_enabled = 0
let g:go_template_autocreate = 0
let g:go_textobj_enabled = 0
let g:go_auto_type_info = 1
"let g:go_def_mapping_enabled = 1
let g:go_highlight_array_whitespace_error    = 1
let g:go_highlight_build_constraints         = 1
let g:go_highlight_chan_whitespace_error     = 1
let g:go_highlight_extra_types               = 1
let g:go_highlight_fields                    = 1
let g:go_highlight_format_strings            = 1
let g:go_highlight_function_calls            = 1
let g:go_highlight_function_parameters       = 1
let g:go_highlight_functions                 = 1
let g:go_highlight_generate_tags             = 1
let g:go_highlight_methods                   = 1
let g:go_highlight_operators                 = 1
let g:go_highlight_space_tab_error           = 1
let g:go_highlight_string_spellcheck         = 1
let g:go_highlight_structs                   = 1
let g:go_highlight_trailing_whitespace_error = 1
let g:go_highlight_types                     = 1
let g:go_highlight_variable_assignments      = 0
let g:go_highlight_variable_declarations     = 0

" ===
" === coc
" ===
set completeopt=longest,noinsert,menuone,noselect,preview
let g:coc_global_extensions = ['coc-python', 'coc-vimlsp', 'coc-html', 'coc-json', 'coc-css', 'coc-tsserver', 'coc-yank', 'coc-lists', 'coc-gitignore', 'coc-vimlsp', 'coc-tailwindcss', 'coc-stylelint', 'coc-tslint', 'coc-lists']
" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
	let col = col('.') - 1
	return !col || getline('.')[col - 1]	=~ '\s'
endfunction
inoremap <silent><expr> <Tab>
			\ pumvisible() ? "\<C-n>" :
			\ <SID>check_back_space() ? "\<Tab>" :
			\ coc#refresh()
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
inoremap <silent><expr> <c-space> coc#refresh()
</pre></details>

#### vim-go version:
v1.21

#### Vim version (first three lines from `:version`):
:version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-xA
EA75/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=forma
t-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-tim
e -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra
-pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wsh
adow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla
 -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENE
RATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_
UNIBI_HAS_VAR_FROM -I/build/neovim-xAEA75/neovim-0.4.3/build/config
 -I/build/neovim-xAEA75/neovim-0.4.3/src -I/usr/include -I/usr/incl
ude/lua5.1 -I/build/neovim-xAEA75/neovim-0.4.3/build/src/nvim/auto
-I/build/neovim-xAEA75/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

#### Go version (`go version`):
go version go1.13.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/david/.cache/go-build"
GOENV="/home/david/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/david/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build777598052=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
</pre></details>

**Comment by bhcleek** [comment]
vim-go does not set `completeopt`.

**Comment by theniceboy** [comment]
I got it, just needed to set `"suggest.enablePreselect": false` in `coc-settings.json` as [this issue](https://github.com/neoclide/coc.nvim/issues/1288) indicates, not vim-go related. Closing.

**Comment by wboard82** [comment]
I encountered a similar issue using `nvim-cmp` as my completion engine. Adding `preselect = cmp.PreselectMode.None` to  `cmp.setup` fixed it for me.
