### ISSUE TITLE
"vim-go: initialized gopls" should disappear after 3ms?

### ISSUE THREAD

**Issue by winkee01** [fatih/vim-go#2648]
### What did you do? (required: The issue will be **closed** when not provided)
vim open hello.go, the message "vim-go: initialized gopls" is displayed at the bottom, but never disappear.

From most experiences, the message that serves as informing purposes only display for a short time then fades, but in this case it keeping saying "vim-go: initialized gopls", kind of annoying and disturbing, is it possible to make it disappear after it accomplishes its purposes?

### What did you expect to happen?
"vim-go: initialized gopls" disappear after 3ms display.

### What happened instead?
won't disappear automatically
<img width="473" alt="initializegopls" src="https://user-images.githubusercontent.com/49930785/71952173-bc6bb280-3218-11ea-9e14-dc1d2a090939.png">

### Configuration (**MUST** fill this out):
default configuration

#### vim-go version:
latest

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
Plug 'fatih/vim-go'
</pre></details>

#### Vim version (first three lines from `:version`):

vim8.2
#### Go version (`go version`):

go version go1.13.3 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOOS="darwin"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
</pre></details>

**Comment by bhcleek** [comment]
It will disappear when the screen is next redrawn.

Since you're using Vim 8.2, I recommend that you using vim-go statusline integrion  (see `:help go#statusline#Show()` and disable `g:go_echo_command_info` - you'll end up with the experience you're looking for overall, I think.
