### ISSUE TITLE
vim-go auto set noremap K to what ?

### ISSUE THREAD

**Issue by YousyaCliff** [fatih/vim-go#2651]
### What did you do? (required: The issue will be **closed** when not provided)
I set K for quick move down (noremap K 5k), in go file K command be changed.

### What did you expect to happen?
When I press K, is same 5k

### What happened instead?
vim-go: no package constaining xxx.go

#### vim-go version:
the  new
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

unimportant Probably
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

unimportant Probably
</pre></details>

**Comment by bhcleek** [comment]
`K` is mapped to `:GoDoc` in vim-go by default, following the pattern set by `K` generally for looking up a word under the cursor (see `:help K`).

You can disable the mapping in vim-go by using `g:go_doc_keywordprg_enabled`. See `:help g:go_doc_keywordprg_enabled`  for more information.

**Comment by danielo515** [comment]
I have that set to 0 and K is still remapped to godoc.

**Comment by mavaa** [comment]
@danielo515 Had the same problem until I realized I had to put it in my .vimrc and NOT ftplugin/go.vim. Not a vim expert, but I'm guessing the last one runs after the plugin itself has initialized its bindings. So in .vimrc:

`let g:go_doc_keywordprg_enabled = 0`
