### ISSUE TITLE
Blinded by highlights

### ISSUE THREAD

**Issue by chew-z** [fatih/vim-go#2656]
I am sorry for bothering with such trivial problem but when editing lines like the one below

`url := fmt.Sprintf("http://%s%s?endpoint=%s&id=%s", c.Request.Host, c.Request.URL.Path)`

vim-go highlights entire statement with such aggressive colors  (on any base16 color palette) that I am completely blinded and can't figure out where my cursor is. That makes editing such line painful and counterproductive as I spend more time trying to figure out where my cursor is than actually editing trivial statement.

So the question is which highliht shall I clear? I have tried `:highlight clear SpellBad` and `:highlight clear SpellBadRare` but no luck.

**Comment by bhcleek** [comment]
vim-go has a number of options to control highlighting. Without knowing what you're actually seeing or what your vim-go settings are, it's difficult to give you any specific guidance.

`:help g:go_syntax` may help you. Also, you can see what highlight group is used for the position under the cursor with `<leader>sp` by putting this in your vimrc:
```
nmap <leader>sp :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
```

**Comment by chew-z** [comment]
Thank you for your help. Your answer led me to goDiagnosticWarning and that to SpellRare which is troublesome in base16 colorschemes.

So I have made unperfect but working function for toggling this highlight.

**Comment by bhcleek** [comment]
vim-go supports turning it off. See `:help g:go_highlight_diagnostic-warnings`.

If you want to keep the highlighting, but use a different group, then you can set `goDiagnosticWarning` to use a different highlight group by using `highlight default`, `highlight default link`, or `highlight` to define how you warning to be highlighted.

Of course, you could also change `SpellRare` to be configured as you desire so that it's useful in vim-go and any other plugins that make use of it.

**Comment by chew-z** [comment]
Thank you again.

The problem is not with vim-go (which BTW is really useful to me and I can't praise it high enough) but with base16 colorschemes family in VIM as per [this discussion](https://github.com/chriskempson/base16-vim/issues/182#issue-336531173).  

Highlighting in base16 made highlighted part difficult to read and almost impossible to edit. Through `SpellRare` I have made highlighting a little more accommodating.
