### ISSUE TITLE
Window scrolling position jumps on saving

### ISSUE THREAD

**Issue by korjavin** [fatih/vim-go#2657]
### What did you do? (required: The issue will be **closed** when not provided)
1. Open long *.go in a buffer
2. Make :vs 
3. Open the same buffer
4. Scroll somewhere
5. (Optional) use :set scb (for sync scrolling)
6. Make any change and save file
Result:
  buffer position will be changed and window-sync broken.

### What did you expect to happen?
Scrolling will stay the same.

### What happened instead?
Cursor stays in the same line but it's scroll position is changed.

#### vim-go version:

ee2071d
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
  Bundle 'fatih/vim-go'
  Plugin 'Chiel92/vim-autoformat'
  let g:go_jump_to_error = 1
  let g:go_fmt_experimental = 1
  Plugin 'tpope/vim-dispatch'
  let g:go_dispatch_enabled = 1
  let g:go_highlight_operators = 1
  let g:go_metalinter_autosave = 0
  let g:go_auto_type_info = 0
let g:go_fmt_fail_silently = 1

let g:go_list_type = "locationlist"
let g:go_list_height = 5
let g:go_list_type_commands = {"GoReferrers": "quickfix"}
let g:go_alternate_mode = "vsplit"
let g:go_autodetect_gopath = 1
let g:go_get_update = 0
let g:go_def_reuse_buffer = 0

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 09 2019 12:59:40)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.13 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/iv/.cache/go-build"
GOENV="/home/iv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/iv/Projects/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build519354042=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=

</pre></details>

**Comment by bhcleek** [comment]
This is because vim-go currently has to use `gofmt` to format the buffer and it gets reloaded. I'm closing this, because it will effectively be solved via #2635.
