### ISSUE TITLE
:GoErrCheck overwrites my file if it finds syntax error

### ISSUE THREAD

**Issue by winkee01** [fatih/vim-go#2661]
### What did you do? (required: The issue will be **closed** when not provided)
If the source file has a syntax error,  :GoErrorCheck will rewrite my file(buffer) with a default template. I can only ctrl + o to get back to my original file.

### What did you expect to happen?
nothing should happen to my file, except it display the corresponding error info on the bottom.
### What happened instead?
my file is overwritten, everything is gone.

<img width="531" alt="err01" src="https://user-images.githubusercontent.com/49930785/72658640-94d1d280-39ee-11ea-820a-9009d892065c.png">
<img width="574" alt="err02" src="https://user-images.githubusercontent.com/49930785/72658642-98655980-39ee-11ea-83dc-11d732c0a1f8.png">

### Configuration (**MUST** fill this out):
default
#### vim-go version:
latest
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

8.2
#### Go version (`go version`):

go version go1.13.3 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
You should be able to reload the file; nothing is actually lost.

**Comment by winkee01** [comment]
Yes, I can get back by ctrol-o. But it loads a new file to take up my current window, isn't it weird? It can show error info on the bottom, but nothing should happen to my window, right?

**Comment by bhcleek** [comment]
Yes, what you've reported is indeed a bug due to the handling of `errcheck`'s return code. There's an open PR that fixes the behavior you reported.

You can also execute `:e #` get back to the buffer. Until ##2667 is merged, I'd advise you to run `:GoBuild` before `:GoErrCheck` to make sure there aren't any syntax errors that affect the package.
