### ISSUE TITLE
Names from other files in the same package are highlighted with a red background

### ISSUE THREAD

**Issue by mortie** [fatih/vim-go#2668]
### What did you do? (required: The issue will be **closed** when not provided)

I opened one file i the package `main` which uses types and functions from other files in the same package in the same directory.

Here's a screenshot:

![Screenshot from 2020-01-19 02-39-56](https://user-images.githubusercontent.com/3728194/72673125-60016200-3a66-11ea-8aff-d92beca707a9.png)

### What did you expect to happen?

I expected vim-go to highlight types and functions from other files appropriately.

### What happened instead?

The types and functions are highlighted with a red background, as if they're undefined.

### Configuration (**MUST** fill this out):

Nothing special, just `Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }`

#### vim-go version:

https://github.com/fatih/vim-go/commit/810e4b9faf1583443fe2d027d11993fb698b080f

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

A .vimrc which does nothing other than enabling the plug-in

<details><summary>vimrc</summary><br><pre>

```
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
```

</pre></details>

#### Vim version (first three lines from `:version`):

Neovim:

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
```

Vim:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 05 2019 11:15:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
Modified by team+vim@tracker.debian.org
```

#### Go version (`go version`):

go version go1.12.10 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/martin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/martin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build367494710=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=

</pre></details>

**Comment by bhcleek** [comment]
Can you provide a simple reproduction case?

**Comment by mortie** [comment]
File `main.go`:

``` go
package main

func main() {
	PrintHello()
}
```

File `hello.go`, in the same directory:

``` go
package main

func PrintHello() {
	println("Hello World")
}
```

When opening `main.go`, the call to PrintHello is highlighted as if it's an error:

![Screenshot from 2020-01-19 10-19-15](https://user-images.githubusercontent.com/3728194/72678343-3b78aa80-3aa5-11ea-9221-7e398488f1c9.png)

**Comment by Lucus16** [comment]
Did a bit of manual bisecting, this issue is introduced in 17d97dd.

**Comment by bhcleek** [comment]
I am unable to duplicate what you're seeing. with my setup, the warning and errors are underlined instead of being shown in red.

![recording](https://user-images.githubusercontent.com/1958864/72686033-21d76300-3aa5-11ea-85b2-48ab73a99b96.gif)

What does `:GoDiagnostics` output for you?

**Comment by mortie** [comment]
`:GoDiagnostics` only says this: `main.go|4 col 2 error| undeclared name: PrintHello`

**Comment by bhcleek** [comment]
I think the issue here is a confluence of a few factors:
1. you're not in GOPATH mode
2. there isn't a go.mod file for module-aware mode to use
3. you're using Go 1.12.

If you do _any_ of these, I wonder if your problem will resolve itself:
1. put the files in a package within GOPATH
2. add a go.mod file
3. update to Go 1.13

**Comment by mortie** [comment]
Adding a go.mod file fixes it. Putting the files in GOPATH (`~/go/src/git.example.com/gotest`) does nothing. Upgrading to go 1.13.1 does nothing (not even after deleting the vim-go directory and the binaries it adds to ~/go/bin and running `PlugInstall` again).

**Comment by bhcleek** [comment]
Which version of Go is used depends on which one comes first in $PATH.

**Comment by bhcleek** [comment]
@mortie I should point out that you can disable that highlighting if you want using the options added in https://github.com/fatih/vim-go/commit/17d97ddc264e9845682d6d99ebd049ec7a710169.

It's odd that putting the file in GOPATH doesn't resolve this for you. Do you have GO111MODULE set?

I've tried duplicating this with Go 1.12.8 without success both in and out of GOPATH:
![recording](https://user-images.githubusercontent.com/1958864/72690031-f9635f00-3acc-11ea-9fe3-53e7ef879584.gif)

**Comment by bhcleek** [comment]
closed for lack of feedback
