### ISSUE TITLE
highlighting error: Invalid value for argument end_col

### ISSUE THREAD

**Issue by pauldthomson** [fatih/vim-go#2675]
### What did you do? (required: The issue will be **closed** when not provided)

Run commands :GoDef or :GoDecls. Using :GoDef then attempting to go back using ctrl-o, using :GoDecls then selecting a function from the result list and hitting enter

### What did you expect to happen?

Navigate to previous position or jump to function definition respectively

### What happened instead?

Error in quickfix appears:
`vim-go: function 371[10]..374[3]..375[2]..376[46]..<SNR>119_highlightMatches[20]..go#util#HighlightPositions, line 30: Vim(call):E475: Invalid value for argument end_col`

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre><code>
" =========================
" vim-go
" =========================
" Highlighting
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1

" Show info about type or method
let g:go_auto_type_info = 1

" Run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go nmap <leader>t  <Plug>(go-test)

" Run goimports on save
let g:go_fmt_command = "goimports"

" Control how to open buffer when alternating between test and src
autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')
autocmd Filetype go nnoremap av :<C-u>call go#alternate#Switch(0, 'vsplit')<CR>
autocmd Filetype go nnoremap at :<C-u>call go#alternate#Switch(0, 'edit')<CR>
autocmd Filetype go nnoremap <F12> :GoDecls<CR>

" Automatically highlight same identifiers (functions, variables etc)
let g:go_auto_sameids = 1

" Use gopls everywhere I can
let g:go_def_mode = 'gopls'
let g:go_info_mode = 'gopls'
let g:go_rename_command = 'gopls'
let g:go_gopls_complete_unimported = 1
</code></pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  8 2020 00:57:48)
macOS version
Included patches: 1-100

#### Go version (`go version`):
go version go1.13.6 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/pthomson/Library/Caches/go-build"
GOENV="/Users/pthomson/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pthomson/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1n/fg0y62lj3sz31db9vtvbym006nsw3r/T/go-build435011514=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
</pre></details>

**Comment by bhcleek** [comment]
I've been seeing this sometimes, too, an am trying to find a clear replication path. I plan to have a fix for it before the v1.22 release.

**Comment by bhcleek** [comment]
FWIW, this isn't specific to `:GoDef` or `:GoDecls`. It seems to be related to moving between buffers, possibly while highlighting is in-flight.

**Comment by pauldthomson** [comment]
OK. Let me know if there's anything else I can do to help.

**Comment by bhcleek** [comment]
Thank you. I have a replication path now and I think it will be relatively quick to resolve.
