### ISSUE TITLE
Don't prompt to continue with auto_type_info

### ISSUE THREAD

**Issue by ChrisPenner** [fatih/vim-go#2677]
# What did you do? (required: The issue will be **closed** when not provided)
1. Set `let g:go_auto_type_info = 1`
2. Hover over a type with a large signature when the window is small
3. I get prompted with "Press Enter to continue" if the type is longer than the status line

![image](https://user-images.githubusercontent.com/6439644/72906000-14b1b280-3cf7-11ea-801d-348c4190524c.png)

### What did you expect to happen?
I don't want to be 'prompted' every time I hover on a large type, (I'd prefer the type just get cut off if necessary)
It's extremely distracting to have to press Enter every time the Hover happens 😬 

### Configuration (**MUST** fill this out):
```
let g:go_auto_type_info = 1
set cmdheight=1
```
#### vim-go version:

`v1.22-rc.3`

#### Vim version (first three lines from `:version`):
```
NVIM v0.5.0-83b0054
Build type: Release
LuaJIT 2.0.5
```

#### Go version (`go version`):
`go version go1.13.5 darwin/amd64`

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/cpenner/go/bin"
GOCACHE="/Users/cpenner/Library/Caches/go-build"
GOENV="/Users/cpenner/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cpenner/go"
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f1/pxd3c9ln1ll05dgpp0sdsbvm0000gp/T/go-build346898420=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=

</pre></details>

**Comment by ChrisPenner** [comment]
I'm currently using `set cmdheight=2` as a simple work-around, but I'd prefer to not have to.

Thanks for all your work!

**Comment by bhcleek** [comment]
Have you tried adjusting `shortmess`? https://vim.fandom.com/wiki/Avoiding_the_%22Hit_ENTER_to_continue%22_prompts

**Comment by bhcleek** [comment]
closed for lack of feedback
