### ISSUE TITLE
Broken URLs in Wiki.

### ISSUE THREAD

**Issue by ubombi** [fatih/vim-go#2679]
Links from this page returns Unauthorized error.
https://github.com/fatih/vim-go/wiki/Screencasts

Can you, please update/remove them?

**Comment by bhcleek** [comment]
@fatih do you know if there are any valid URLs for the screen recordings, or should the links be removed?

**Comment by camilo-schoeningh-sociomantic** [comment]
Click-baiting
 
In your wiki under `Blog Posts` - `Setup VIM for Go development - Unknwon` is pointing to aadvertisement webpage.

**Comment by bhcleek** [comment]
I've commented out all the links mentioned in this issue
