### ISSUE TITLE
Run GoTest from a remote directory. 

### ISSUE THREAD

**Issue by sheki** [fatih/vim-go#268]
First of all, I am a huge fan of Vim-go. Thanks for doing this. 

I launch vim from a central directory and run GoTest on an open file, this runs fine but the QuickFix Window does not work as it has file entries with the 

Path of the File and the PWD appended, is there a way to run GoTest if I am not in the directory the test_file is in?

**Comment by fatih** [comment]
Ping @sheki  :)

**Comment by sheki** [comment]
I do not have a good repro at this point of time. I will reopen the task if I run into it again, with a screen cast. Cheers
