### ISSUE TITLE
realtime completion uses gopls documentation refers deoplete

### ISSUE THREAD

**Issue by the42** [fatih/vim-go#2680]
This is mainly a support question with a hint for a minor documentation cleanup.

Earlier versions of vim-go used deoplete. The way for autocompletion these days is gopls, the documentation is not consistent on that.

**Comment by bhcleek** [comment]
Where do you see an inconsistency?

Vim-go contains instructions for configuring deoplete, but all vim-go has ever done is to configure the `omnifunc` for Go files. It used to use gocode by default, but now uses gopls by default.

**Comment by the42** [comment]
I just found it confusing the way it is phrased as it seems as deoplete and deoplete-go are a requirement which is according to  #2185  not true.

**Comment by bhcleek** [comment]
Completion is done using `omnifunc`, which uses `gopls`. deoplete triggers completion without the user having to type `C-xC-o`. Feel free to make a PR to clarify the text in the docs if you'd like.
