### ISSUE TITLE
go run does not show in shell-command output

### ISSUE THREAD

**Issue by hamiltont** [fatih/vim-go#2681]
### What did you do?

I ran `:let g:go_debug = ['shell-commands']` to enable shell command printing, and used `:GoRun`

### What did you expect to happen?

I expected to see the shell command e.g. `go run <something>` in `:messages`

### What happened instead?

No output containing `go run`, only the `go lint` output caused by the `go#config#BuildTags` that precedes the call to `!run`

Seems to me a line could be added [hereish](https://github.com/fatih/vim-go/blob/master/autoload/go/cmd.vim#L166) to manually inject the command into the message queue if debug is enabled. I'm a bit out of my vim depth to open a PR right now. 

#### Misc info

I found this tracking down a funny bug. A manual `:!go run .` results in a successful execution, while `:GoRun` results in a hung program. I'm suspecting the program is not properly cleaning something up. Once I realized I could trigger the bug with `:GoRun` but not with `:!go run .` that is what lead to me reporting this issue. If anyone has advice on what my bug might be, or how I can reproduce it without using vim-go, that would be appreciated :-) 

#### vim-go version:

v1.21+master commits (Specifically, be73eeb6321f44cec74252ea8e2b2f046516e5ca)

####  `vimrc` to reproduce 
<details><summary>vimrc</summary><br><pre>
source $VIMRUNTIME/defaults.vim

"set packpath=~/.vim/pack/plugins,~/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after

syntax on
colorscheme slate
</pre></details>

#### Vim version

VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 23:05:43)
macOS version
Included patches: 1-2234
Compiled by Homebrew

#### Go version (`go version`):

go version go1.13.6 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

 [master] vim-go$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hamiltont/Library/Caches/go-build"
GOENV="/Users/hamiltont/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hamiltont/Programming/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b8/rkpz3m117qzgpl4xg26c44l00000gn/T/go-build676879159=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
</pre></details>

**Comment by hamiltont** [comment]
Well now I'm confused. Looking at source, it is calling an echo function. Perhaps `:messages` is the wrong place to look?

**Comment by bhcleek** [comment]
`:messages` would be the right place to look, but you're right, `:GoRun` doesn't not have the shell command echoed when `g:go_debug=['shell-commands']`.

As for the problem you were trying to track down, I'm happy to help you in a separate issue that clearly describes a replication path (generally, `:GoRun` works, so please provide specifics about your replication path if possible - if the source that you're trying to `go run` is publicly accessible, that would be ideal).

**Comment by bhcleek** [comment]
`:messages` would be the right place to look, but you're right, `:GoRun` doesn't not have the shell command echoed when `g:go_debug=['shell-commands']`.

As for the problem you were trying to track down, I'm happy to help you in a separate issue that clearly describes a replication path (generally, `:GoRun` works, so please provide specifics about your replication path if possible - if the source that you're trying to `go run` is publicly accessible, that would be ideal).

**Comment by hamiltont** [comment]
Thanks @bhcleek
