### ISSUE TITLE
vim-go has incorrect highlights after vendored files change

### ISSUE THREAD

**Issue by kevinburkemeter** [fatih/vim-go#2687]
Frequently I'll do the following pattern:

- edit go.mod to update a dependency
- background vim-go
- run "go mod vendor" to update dependencies
- foreground vim-go

When I begin editing Go files again, frequently the code I am modifying that was just changed in the dependency - say, a field that was added to a struct in the dependency - will be highlighted in red, even though the build passes with no problems.

Is there a way to signal to vim-go or lsp that it should refresh its definition list? I've tried `:e` but no dice.

**Comment by bhcleek** [comment]
The only supported way to workaround the problem you're seeing now is to exit Vim before running `go mod vendor`.

The problem you're running into is that gopls doesn't watch for file changes on disk. https://github.com/golang/go/issues/31553 is the issue for you to watch. If I'm reading that right, it's fixed on golang.org/x/tools/gopls@master, but won't be in the upcoming v0.3.0 release. @stamblerre can you confirm?

As-is, the only way to get the changes to be picked up is to restart gopls, but there isn't a supported command in vim-go to restart gopls. You can use `:call go#lsp#Restart()` if you want, but it's not supported user-facing function and may change in the future.

**Comment by stamblerre** [comment]
File watching will be available in `gopls/v0.3.0` - you can try it now in the pre-release (`GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.0-pre2`).

**Comment by kevinburkemeter** [comment]
Oh, ok, thanks!

**Comment by bhcleek** [comment]
gopls v.0.3.0 is out now. You can get it by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.0`

**Comment by bhcleek** [comment]
Closing, because I've merged the change that flips master back to using `golang.org/x/tools/gopls@latest`.
