### ISSUE TITLE
GoRename/gopls incorrectly depends on PATH ?

### ISSUE THREAD

**Issue by erwanthomas** [fatih/vim-go#2691]
### What did you do?

I used `:GoRename` with `gopls` and a `$PATH` that doesn't include the binaries installed by the plugin.

Please see the (verbose) details included at the end of the issue to reproduce exactly what I've done.

### What did you expect to happen?

I expected `:GoRename` to invoke `gopls` in the right way to safely rename a Go type.

### What happened instead?

The Go document wasn't changed and an error message was displayed instead:

    vim-go: executing job failed: No such file or directory

### Hypothetical explanation

The job is started with a shell command that invokes `gopls` directly, (incorrectly) relying on the fact it is somehow available in the `$PATH`.

With `let g:go_debug = ['shell-commands']`, I get the following message:

    vim-go: job command: ['gopls', 'rename', '-w', '/root/foo/main.go:#33', 'bar']

It seems to me that `:GoRename` doesn't prefix the `gopls` executable path with the `GOBIN`/`GOPATH/bin` path, which would contradict the intended behavior of `g:go_search_bin_path_first` (enabled by default).

#### vim-go version:

```
v1.22
```

####  minimal `vimrc` you used to reproduce:

```
let g:go_rename_command = 'gopls'
```

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 19:30:49)
Compiled by Alpine Linux
Huge version without GUI.  Features included (+) or not (-):
```

#### Go version (`go version`):

```
go version go1.13.7 linux/amd64
```

#### Go environment

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build253789496=/tmp/go-build -gno-record-gcc-switches"
```

#### gopls version

```
golang.org/x/tools/gopls 0.2.2
golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
```

### In case you want an exact reproduction of the issue

Here's a minimal system to reproduce the issue:

```Dockerfile
FROM golang:1.13.7-alpine3.11

ENV VIM_VERSION=8.2.0 \
    VIMGO_VERSION=1.22 \
    VIMGO_PATH=/root/.vim/pack/plugins/start/vim-go

RUN apk add --no-cache git "vim=~$VIM_VERSION"

RUN mkdir -p "$VIMGO_PATH" \
    && git clone \
      --depth 1 \
      --branch "v$VIMGO_VERSION" \
      https://github.com/fatih/vim-go.git \
      "$VIMGO_PATH" \
    && vim -e +GoInstallBinaries

WORKDIR /root/foo

RUN echo \
$'package main\n\
import "fmt"\n\
type foo int\n\
type arr []foo\n\
func main() {\n\
var a foo\n\
fmt.Printf("%T\\n", a)\n\
}' > main.go && go fmt main.go
```

```
docker build . -t foo
docker run --rm -it foo sh
```

Given:

- Some `$GOPATH`:

    ```
    ~/foo # go env GOPATH
    /go
    ```

- A Go document:

    ```
    ~/foo # cat main.go
    package main

    import "fmt"

    type foo int
    type arr []foo

    func main() {
    	var a foo
    	fmt.Printf("%T\n", a)
    }
    ```

#### Scenario 1

In this scenario, `$PATH` includes `$GOPATH/bin`:

    ~/foo # export PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

The `:GoRename` command succeeds to rename `foo` to `bar`:

    ~/foo # vim -c "let g:go_rename_command = 'gopls'"  -c '5' -c 'normal w' -c 'GoRename bar' main.go # and then confirm and exit Vim

**Results**:

- A success log is displayed:

    ```
    vim-go: [gorename] SUCCESS
    ```

- The Go document has changed:

    ```
    ~/foo # cat main.go
    package main

    import "fmt"

    type bar int
    type arr []bar

    func main() {
    	var a bar
    	fmt.Printf("%T\n", a)
    }
    ```

#### Scenario 2

In this scenario, `$PATH` no longer includes `$GOPATH/bin`:

    ~/foo # export PATH=/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

The `:GoRename` command fails to rename `foo` to `bar`:

    ~/foo # vim -c "let g:go_rename_command = 'gopls'"  -c '5' -c 'normal w' -c 'GoRename foo' main.go

**Results**:

- A error log is displayed:

    ```
    vim-go: executing job failed: No such file or directory
    ```

- The Go document hasn't changed.

**Comment by bhcleek** [comment]
Thanks for the thorough issue!

**Comment by erwanthomas** [comment]
https://github.com/bhcleek/vim-go/commit/462257ae83da704e78848bdb183c6c8bc52348af solved the issue indeed, thanks for the (very) quick fix !

**Comment by sgetmanring** [comment]
@bhcleek @erwanthomas what to do to fix it locally? I just pulled last vim-go:
```
From https://github.com/fatih/vim-go
   311ea9d..b686094  master     -> origin/master
Updating 311ea9d..b686094
...
autoload/go/rename.vim   |   2 +-
...
```
but rename still doesn't work for me

**Comment by erwanthomas** [comment]
@sgetmanring Pulling https://github.com/bhcleek/vim-go/commit/462257ae83da704e78848bdb183c6c8bc52348af should be enough, so maybe the issue you're facing is a different one ?

I would think so if that issue is the one you described in https://github.com/fatih/vim-go/issues/2693 (`
/Users/me/go/pkg/mod/github.com/mailru/easyjson@v0.0.0-20190614124828-94de47d64c    63/jwriter/writer.go|9 col 2| could not import github.com/mailru/easyjson/buffer (cannot find package "github.com/mailru/easyjson/buffer" in any of: /usr/local/go/src/github.com/mailru/easyjson/buffer (from $GOROOT) /Users/me/go/src/github.com/mailru/easyjson/buffer (from $GOPATH))`) because I didn't face a similar error on my system.

I don't know much about go or vimscript so I can't help a lot here, but I would suggest you try `:GoRename` from a brand new package such as the one I described in the issue description. For example:

```
$ cd "$(mktemp -d)"
$ echo 'package main

import "fmt"

type foo int
type arr []foo

func main() {
\tvar a foo
\tfmt.Printf("%T\\n", a)
}' > main.go
$ vim main.go # and then try to :GoRename foo into bar
```

Such a scenario is free of potential `import` errors and might be easier to debug the issue you're facing.

**Comment by sgetmanring** [comment]
@erwanthomas appreciate your help. Your idea totally makes sense. I tried it in completely new package and got:
```
vim-go: gorename: can't find package containing /Users/sergiigetman/Project/pills/main.go
```
So `:GoRename` relys on `gorename` not on `gopls` despite I have explicitly set it:
```
let g:go_gorename_command = 'gopls'
```

**Comment by erwanthomas** [comment]
The option name `go_gorename_command` is incorrect. Try with `let g:go_rename_command = 'gopls'` ?

**Comment by sgetmanring** [comment]
@erwanthomas thanks a lot! it was the problem! you saved my day!

**Comment by mnarrell** [comment]
@erwanthomas <https://github.com/erwanthomas> I thank you as well.  I've
been watching the vim-go and gopls release threads on this and could never
understand why this wasn't working for me.  Have a great day!
