### ISSUE TITLE
modules are not automatically loaded when changing the version

### ISSUE THREAD

**Issue by luigi-riefolo** [fatih/vim-go#2697]
### What did you do? (required: The issue will be **closed** when not provided)

Set a module dependency in `go.mod`
run `go mod tidy`
use vim-go to navigate to a function declaration

### What did you expect to happen?
Function declaration was the one in the specific version stated in `go.mod`

### What happened instead?
Function declaration is the same as the previous one.

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.8

#### Go version (`go version`):

go version go1.13.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
Can you provide a more specific set of steps for what you're doing? The description you provided is not specific enough to identify the source of the problem you're describing. Generally, though, jumping to a definition works fine.

1. Did you exit Vim before editing your go.mod?
2. Did `go mod tidy` retrieve the version of the module you edited?
3. What is `g:go_def_mode` set to?
4. What version of `gopls` are you using?
5. Are you in module aware mode or GOPATH mode?

**Comment by bhcleek** [comment]
Closing for lack of feedback.

**Comment by luigi-riefolo** [comment]
@bhcleek apologies for the late reply, hope you can reopen this or at least tell me what's the issue. 

1. Did you exit Vim before editing your go.mod?
No I didn't

2. Did go mod tidy retrieve the version of the module you edited?
Yes

3. What is g:go_def_mode set to?
It's undefined 

4. What version of gopls are you using?
golang.org/x/tools/gopls v0.3.1

5. Are you in module aware mode or GOPATH mode?
module aware

**Comment by bhcleek** [comment]
Thank you.

This is expected behavior currently, because the default `g:go_def_mode` value is `gopls`, gopls isn't watching file on the filesystem yet, and vim-go doesn't reload gopls when the ambient go.mod changes.

@stamblerre if gopls is sent a `textDocumented/didChange` for the go.mod file, will it recalculate all the dependencies?

**Comment by stamblerre** [comment]
`gopls` does support watching file system changes, though I'm not sure if vim-go is sending the `textDocument/didChangeWatchedFiles` requests. Modifications to the `go.mod` file will invalidate all package metadata for the module.

**Comment by bhcleek** [comment]
@stamblerre Do you mean `textDocument/didChange`? I don't see a `textDocument/didChangeWatchedFile` in the LSP spec.

Currently, vim-go sends `textDocument/didChange` for go files, but doesn't yet for go.mod file.

@luigi-riefolo when you edited the file, did you do that in the editor or using the `go mod` or `go get` commands?

**Comment by stamblerre** [comment]
https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_didChangeWatchedFiles is the request for file changes on disk, so the actual file watching implementation has to be in the LSP client.

**Comment by bhcleek** [comment]
Thanks. It's `workspace/didChangeWatchedFiles` so I wasn't finding it under `textDocument/didChangeWatchedFiles`.

@luigi-riefolo I can add support for notifying gopls when the go.mod file is changed _in_ vim or when its changed on disk as long as it's loaded into a buffer.

**Comment by bhcleek** [comment]
@luigi-riefolo how did you set a dependency in `go.mod` ( i.e did you use `go get` or `go mod edit` at the commandline or did you edit it in Vim)?

**Comment by luigi-riefolo** [comment]
@bhcleek I did edit it using nvim

**Comment by cposture** [comment]
I have same problem; after go get module to update module version in shell command line,  it jump to the original module in vim, so I have to reopen vim

**Comment by bkielbasa** [comment]
I have the same issue as well. Any plans to fix it?

**Comment by bhcleek** [comment]
Yes. I'm likely to fix it before the next vim-go release

**Comment by alvinlee001** [comment]
HI, sorry i would like to ask if there are any workaround to this problem, which is to restart the vim session without losing my current buffers and states? Or is there any other alternatives?

**Comment by bhcleek** [comment]
There are a couple of work arounds.

You could run `:GoUpdateBinaries gopls` which will cause `gopls` to get restarted. You could also kill the `gopls` instances manually. When `gopls` is reloaded by vim-go, it should pick up your `go.mod` changes.

**Comment by JohnStarich** [comment]
I frequently update go.mod via the command line. It'd be very convenient to watch open module's files in general, even if they haven't been opened in nvim.

Perhaps a `:GoRestartLanguageServer` would be an easy-to-add work around? The update can be pretty slow if run frequently, and I usually have multiple projects open so `pkill gopls` triggers huge CPU spikes when they restart.

**Comment by zigi-omri** [comment]
@alvinlee001 
> HI, sorry i would like to ask if there are any workaround to this problem, which is to restart the vim session without losing my current buffers and states? Or is there any other alternatives?

unrelated to vim-go: just use `mksession my.session`
when you re-open use `source my.session`
that will put you right back where you were.
