### ISSUE TITLE
[Question] Vim-go error underlines

### ISSUE THREAD

**Issue by rjshrjndrn** [fatih/vim-go#2698]
Hi,
First of all thank you for this awesome plugin.
I have a small question.
![image](https://user-images.githubusercontent.com/2563385/73897682-eb735380-48ac-11ea-999e-b40aa3efbf8a.png)
I know **the underlined line is not used anywhere. But can I see the error message somewhere?** Because the same thing happens while using some of the libraries. maybe because of variable mismatch and all.

**Comment by bhcleek** [comment]
`:GoDiagnostics` will show you the associated errors.

**Comment by smlx** [comment]
@bhcleek is there currently a way to get that automatically displayed?

**Comment by bhcleek** [comment]
You can certainly hook up the mapping, `go-diagnostics`, for it and/or hookup some autocmd events for it, but vim-go doesn't hookup either of those automatically for you.
