### ISSUE TITLE
golangci-lint doesn't open quickfix or location lists?

### ISSUE THREAD

**Issue by Integralist** [fatih/vim-go#2700]
### What did you do? (required: The issue will be **closed** when not provided)

Opened a `.go` file, made some code changes and then `:w` to write the buffer back to the file. This caused the message `vim-go: [golangci-lint] FAIL` to be displayed, but the information about what is failing isn't being shown. 

### What did you expect to happen?

I expected the quickfix window to open and to have a list of errors contained within it.

### What happened instead?

The status bar indicated there was an error `vim-go: [golangci-lint] FAIL` but it didn't open the quickfix list (nor the location list).

> Note: I manually opened both `:copen` and `:lopen` just in case the errors were listed there but for some reason the vim-go plugin had failed to simply 'open' the relevant list window.

### Configuration (**MUST** fill this out):

```viml
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

...

let g:go_fmt_command = 'goimports'
let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = '20s'

autocmd FileType go imap /. <C-x><C-o>
```

#### vim-go version:

v1.22

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set nocompatible
set nobackup
set nowritebackup
set noswapfile

call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

let g:go_fmt_command = 'goimports'
let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = '20s'

autocmd FileType go imap /. <C-x><C-o>
</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 12 2019 11:40:34)
macOS version
Included patches: 1-1839
```

#### Go version (`go version`):

```
go version go1.13 darwin/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/markmcdonnell/Library/Caches/go-build"
GOENV="/Users/markmcdonnell/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/markmcdonnell/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zk/_jgd9h392p55w9fd4lzt5dpw0000gp/T/go-build183558573=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
</pre></details>

**Comment by bhcleek** [comment]
After getting the `FAIL` message, what does `:messages` output?

**Comment by Integralist** [comment]
If the code is good, then it's...

```
"internal/pkg/proxy/base.go" 802L, 26491C written
vim-go: [golangci-lint] dispatched
vim-go: [golangci-lint] SUCCESS
```

If the code is bad, then it's...

```
"internal/pkg/proxy/base.go" 802L, 26490C written
vim-go: [golangci-lint] dispatched
vim-go: [golangci-lint] FAIL
```

**Comment by bhcleek** [comment]
What do you mean by "when the code is bad"? Do you mean it won't compile?

What happens if you run the `golangci-lint` command that vim-go uses at the command line in the directory that contains the files that you're editing when you see the `FAIL` message? (you can see each of the command line arguments of the command that it runs by using `let g:go_debug=['shell-commands']`)

**Comment by Integralist** [comment]
> What do you mean by "when the code is bad"? Do you mean it won't compile?

So when I say "the code is bad" I mean the code either wouldn't compile or in some rare occasions the code would have violated a 'style' type of lint check (but mainly it's code that wont  compile). 

> What happens if you run the golangci-lint command that vim-go uses 

I've tested this with a reduced test case file that I would expect to raise a compiler error...

```
$ /Users/markmcdonnell/go/bin/golangci-lint run --print-issued-lines=false --build-tags --disable-all --exclude-use-default=false --enable=govet --enable=golint --deadline=20s /Users/markmcdonnell/Code/Go

WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [-: import "/Users/markmcdonnell/Code/Go": cannot import absolute path]
ERRO [runner/goanalysis_metalinter] typechecking error: import "/Users/markmcdonnell/Code/Go": cannot import absolute path
WARN [runner] Can't run linter goanalysis_metalinter: assign: failed prerequisites: inspect@/Users/markmcdonnell/Code/Go
ERRO Running error: assign: failed prerequisites: inspect@/Users/markmcdonnell/Code/Go
```

I've also tested this with some 'real' code, and inside vim when I `:w` the file the response from the golangci-lint is a `SUCCESS'. But running the cli command suggests a failure...

```
/Users/markmcdonnell/go/bin/golangci-lint run --print-issued-lines=false --build-tags --disable-all --exclude-use-default=false --enable=govet --enable=golint --deadline=20s /Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy

ERRO [runner/goanalysis_metalinter] typechecking error: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path
WARN [runner] Can't run linter goanalysis_metalinter: fact_purity: failed prerequisites: buildssa@/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [-: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path]
ERRO Running error: buildssa: analysis skipped: errors in package: [-: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path]
```

I then remembered that in the 'real' example I'm working from a mono repo and so I open vim from the root directory and then `:lcd ./path/to/service` so I decided to `cd` directly to the directory (in case `:lcd` was confusing the linter somehow) and found a different response from running the cli command...

```
$ /Users/markmcdonnell/go/bin/golangci-lint run --print-issued-lines=false --build-tags --disable-all --exclude-use-default=false --enable=govet --enable=golint --deadline=20s /Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy

internal/pkg/proxy/proxy_test.go:168:25: Error return value of `resp.Body.Close` is not checked (errcheck)
internal/pkg/proxy/proxy_test.go:254:25: Error return value of `resp.Body.Close` is not checked (errcheck)
internal/pkg/proxy/proxy_test.go:319:23: Error return value of `resp.Body.Close` is not checked (errcheck)
internal/pkg/proxy/static.go:52:2: S1005: should write `sp := request.StaticPaths[r.URL.Path]` instead of `sp, _ := request.StaticPaths[r.URL.Path]` (gosimple)
internal/pkg/proxy/base.go:122:2: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (gosimple)
internal/pkg/proxy/base.go:132:2: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (gosimple)
internal/pkg/proxy/base.go:358:2: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (gosimple)
internal/pkg/proxy/base.go:648:5: S1002: should omit comparison to bool constant, can be simplified to `rh.storage.Stopped` (gosimple)
```

I then decided to open up vim from the actual directory where the code was and to break the code such that it wouldn't compile. But again, the FAIL message was displayed but no list was opened with the error and the `:messages` didn't show it either.

**Comment by bhcleek** [comment]
Thank you! That's really helpful. One last question: what is the exit code of golangci-lint when you run those commands at the commandline?

**Comment by Integralist** [comment]
So when run from the same directory as my reduced test case, the exit code was `3`.

When run from the root directory of a mono repo of a real project, the exit code was also `3`.

In both those cases the error message produced from the cli was the same shorter messages (e.g. the one that contained things like `Can't run linter goanalysis_metalinter: assign: failed prerequisites:`).

When run the cli from the actual application directory within the mono repo (if you remember from my previous comment that doing it seemed to work, in that the linters were _running_, although they still were reporting style violation type errors), in this case the exit code was a more appropriate `1`.

**Comment by bhcleek** [comment]
Thanks @Integralist . That's all really helpful. I can explain why the these kinds of lines aren't showing up:
```
ERRO [runner/goanalysis_metalinter] typechecking error: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path
WARN [runner] Can't run linter goanalysis_metalinter: fact_purity: failed prerequisites: buildssa@/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [-: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path]
ERRO Running error: buildssa: analysis skipped: errors in package: [-: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path]
```

Those lines won't use the [error format string](https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L346) used by vim-go. I'm working on a patch now to fix that.

These kinds of lines _should_ be showing up, though:
```
internal/pkg/proxy/proxy_test.go:168:25: Error return value of `resp.Body.Close` is not checked (errcheck)
internal/pkg/proxy/proxy_test.go:254:25: Error return value of `resp.Body.Close` is not checked (errcheck)
internal/pkg/proxy/proxy_test.go:319:23: Error return value of `resp.Body.Close` is not checked (errcheck)
internal/pkg/proxy/static.go:52:2: S1005: should write `sp := request.StaticPaths[r.URL.Path]` instead of `sp, _ := request.StaticPaths[r.URL.Path]` (gosimple)
internal/pkg/proxy/base.go:122:2: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (gosimple)
internal/pkg/proxy/base.go:132:2: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (gosimple)
internal/pkg/proxy/base.go:358:2: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (gosimple)
internal/pkg/proxy/base.go:648:5: S1002: should omit comparison to bool constant, can be simplified to `rh.storage.Stopped` (gosimple)
```

🤔

**Comment by bhcleek** [comment]
On save, all the errors that do not apply to the file you're currently editing are discarded: only the problems with the buffer being saved are reported. Does that explain what you're seeing? You can confirm by running `:GoMetaLinter`.

**Comment by bhcleek** [comment]
> But running the cli command suggests a failure...

Unfortunately, it seems that `golangci-lint` is exiting 0, indicating success, on my machine when it only provides this kind of output:
```
ERRO [runner/goanalysis_metalinter] typechecking error: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path
WARN [runner] Can't run linter goanalysis_metalinter: fact_purity: failed prerequisites: buildssa@/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [-: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path]
ERRO Running error: buildssa: analysis skipped: errors in package: [-: import "/Users/markmcdonnell/Code/buzzfeed/mono/perimeter/internal/pkg/proxy": cannot import absolute path]
```

After you run the commands at the commandline that output those errors, does `echo $?` output `0`?

**Comment by bhcleek** [comment]
@Integralist Would you like to test #2706 before I merge it to confirm that it resolves the issues you encountered?

**Comment by Integralist** [comment]
@bhcleek Sure thing! What's the simplest way to get setup to test your PR?

**Comment by orlangure** [comment]
@bhcleek I'm not sure it is related to this PR, but I'll ask here before submitting a new issue, because it is also related to golangci-lint output. In my case, quickfix window is populated with the results, but I can't go to any location from the list.

For example, the output is always like this:
```
|| util.go:8:60: `buildReply` - `userToken` always receives `"N/A"` (unparam)
|| func buildReply(status bool, command string, reply string, userToken string) []byte {
```
(note the `||` at the beginning). I used to be able to navigate to each warning from the list some time ago, and then it stopped working. Is it related to this issue? Should I open a new one with more details?

**Comment by bhcleek** [comment]
@Integralist it depends on how you normally install vim-go. It looks like you use Plug, so you'd just need to cd into the play where Plug places your vim-go and then run `git fetch origin refs/pull/2706/head && git checkout FETCH_HEAD`.

@orlangure that seems like a separate issue. Are you seeing that on master or with #2706 installed? Either way, make sure you're using the latest golangci-lint. However, I'll go ahead and say that the problem you're seeing there is that Vim isn't detecting which file is a problem and instead is treating the whole error line from vim-go as the error message.

**Comment by Integralist** [comment]
Thanks for the info @bhcleek 

FYI I pulled the latest version of vim-go that you recently merged and am seeing a location list open, but it's empty (most of the time, but if I do `:w` enough times it'll eventually show the following errors).

```
|| level=warning msg="[runner] Can't run linter goanalysis_metalinter: asmdecl: analysis skipped: errors in package: [-: import \"/Users/markmcdonnell/Code/Go\": cannot import absolute path]"
|| level=error msg="Running error: asmdecl: analysis skipped: errors in package: [-: import \"/Users/markmcdonnell/Code/Go\": cannot import absolute path]"
```

**Comment by Integralist** [comment]
Interestingly if I go to a real project and break the code (e.g. remove a trailing comma from an array element) then I will see for a brief flash the error message in the location list, but it's then almost immediately replaced with the above two errors.

**Comment by bhcleek** [comment]
It sounds like you have two separate issues. Please open new issues for each and we'll see if this can be explained and needs a fix or not

**Comment by bhcleek** [comment]
@Integralist no need to create an issue for issue you reported in your most recent comment. I've seen it, too, and am working on a patch now.

**Comment by bhcleek** [comment]
It's happening because there are two autocmds that each have their own errors. When you don't have a trailing comma where one is needed, `gofmt` fails, and shows the first error. Then the the metalinter, `golangci-lint` runs, and it has a completely different error. I'll see if there's anything I can about it relatively easily...

**Comment by addy1997** [comment]
Hello there,
Hello there, 
I wrote a code on Radix sort in go and I  am getting these errors while testing. Please help.

 level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [-: found packages sorts (bubblesort.go) and main (radixSort.go) in /home/runner/work/Go/Go/sorts]"

  **level=error msg="Running error: buildir: analysis skipped: errors in package: [-: found packages sorts (bubblesort.go) and main (radixSort.go) in /home/runner/work/Go/Go/sorts]"**
  
  **Error: golangci-lint exit with code 3**

Thnaks

**Comment by bhcleek** [comment]
@addy1997 you have two different packages defined. `bubblesort.go` declares the package to be named `sorts` and `radixSort.go` declares the package to be named `main`.
