### ISSUE TITLE
Consider using annotated tags when doing releases

### ISSUE THREAD

**Issue by sam-github** [fatih/vim-go#2702]
### What did you do? (required: The issue will be **closed** when not provided)

It looks like the release tagging is a bit random, sometimes `git tag` is used, sometimes `git tag -a`. The difference is not critical, but I found this when checking my submodule status:
```
git/start (master % u=) % git submodule status
 804c8db75f150f2f38ccb10f0b89d8bc999aab15 vim-go (v1.22-rc.4-6-g804c8db)
```

I know I'd committed v1.22 when it was released, so I didn't understand why git submodule thought I had something a couple commits after the last rc.

Its because the rc commits were annotated tags, and the actual release was a light-weight tag:
```
start/vim-go ((v1.22)) % git for-each-ref refs/tags
3cd998c42359a79910e73ad21ffab0ca3ba7ffd5 commit refs/tags/v1.0
bf94a57eb2cbce2bc244b54197dcf12750936dcc commit refs/tags/v1.0.1
554327af3d87f7279a33224fb39cd9f6c808cd0f commit refs/tags/v1.0.2
37234f3c84b4d1fac670d5b405663045899380db commit refs/tags/v1.0.3
48125e61d8e8999a337b7e71a669a7d3b12a5e7f commit refs/tags/v1.0.4
c0696668cf749fe8bc61ad25525ac3709c7a3b1e commit refs/tags/v1.0.5
9ebbbb512c6032ca5481b62b358a597b59ff9070 commit refs/tags/v1.1
dcbedd7b8d903819d0522a6c3385f46a464b3c9f commit refs/tags/v1.10
3eb57ac3a8e02a3d6e2bfba981144c6e1af3545b commit refs/tags/v1.11
26362e4bfcd7601da5b8fcf0041744962766ef0c commit refs/tags/v1.12
4f04d680e3095a683e6654d756cbd0d27f6d2df0 commit refs/tags/v1.13
25d00acf3958cc3f0e1402ab1cef8afe817cb1ae commit refs/tags/v1.14
010d0cc592926e97140846655f92c5c685cec374 commit refs/tags/v1.15
bf390af42c53ae217356d7763ac3e7767f0162a4 commit refs/tags/v1.16
75210b2baccf5dc8d19d60b6d0e3cd171e0b5829 commit refs/tags/v1.17
40ffc87ba3eabf299c50ace52be39c1573d0976a commit refs/tags/v1.18
9535014dbd259f4e3d4b47e358648a7d76dc716e tag    refs/tags/v1.19
9caa7fa7d43e29af5c616819c765691120b0abd5 commit refs/tags/v1.2
831bf5e2edfcc0060d002866ef06997c44047e97 tag    refs/tags/v1.20
19af134b2ad1ac5736236505ed8faecc09bcb4ff tag    refs/tags/v1.21
804c8db75f150f2f38ccb10f0b89d8bc999aab15 commit refs/tags/v1.22
60d841dc067878f019c261309938cf7bc27c9c0c tag    refs/tags/v1.22-rc.1
435723e24f1715dbbdb0c65deb3f50a6f361afd6 tag    refs/tags/v1.22-rc.2
02ec0ec8993b8c280a91a38b7c3e8a1d9b52210d tag    refs/tags/v1.22-rc.3
d813201bb464859147e7058e2dc71500a4974a30 tag    refs/tags/v1.22-rc.4
fe85bd6a4b54c7fedd695067d5fc54c4e9a87931 commit refs/tags/v1.3
6bcbaedea16a0d42cbe7b039bce83c11b5bfda47 commit refs/tags/v1.4
6e1072e78c06eac707a5eb8b20b8362c803857a6 commit refs/tags/v1.5
480b7660fae4413f2cc37fe96119f4c49214cfbe commit refs/tags/v1.6
191ba9a608c0cbf892d844474643409175cb952c commit refs/tags/v1.7
6a0c880dfc114db671e796abeab197759e732093 commit refs/tags/v1.7.1
3030ecc86602b460cb4c1fcbd4ed210f32498c1c commit refs/tags/v1.8
d9fa1bcca346b364dda4643531b894ecae666a56 commit refs/tags/v1.9
start/vim-go ((v1.22)) % git describe
v1.22-rc.4-6-g804c8db
start/vim-go ((v1.22)) % git describe --tags
v1.22
```

### What did you expect to happen?

I expected to see `v1.22` as the vim-go version from `git submodule status`, or from `git describe` when run in vim-go's repo with the v1.22 tag checked out.

Consistently using `git tag -a` when tagging would make the tagging a bit more useful and consistent. This is just a note, far from critical, close it whenever you want.

Thanks for vim-go, its amazing.

**Comment by bhcleek** [comment]
We normally use annotated tags. Vim-go v1.22 didn't get an annotated tag, though, and I'm honestly not sure why. My shell history shows that I tagged it correctly 🤷‍♂

**Comment by bhcleek** [comment]
I figured out what happened here. I spelled the tag name wrong when I did the annotated tag locally, and must have created a lightweight tag via GitHub's interface and didn't realize it.

You might be interested in https://twitter.com/bhcleek/status/1227425502656442369. I'm considering replacing the lightweight one 🤔

**Comment by sam-github** [comment]
I'd go for option c) publish v1.23 immediately as an annotated tag (version numbers are cheap), or d) ignore it
