### ISSUE TITLE
Feature: Convert :GoCallers to use gopls when enabled

### ISSUE THREAD

**Issue by rmzg** [fatih/vim-go#2711]
When gopls is enabled and working it would be nice to use it for callers and friends instead of the very old go guru program.

**Comment by bhcleek** [comment]
It would be nice, and I've been trying to figure out a way to do it, but haven't figured out a good way yet. In the meantime, you can use `:GoReferrers` to get close to the same behavior.

**Comment by hungrybirder** [comment]
> It would be nice, and I've been trying to figure out a way to do it, but haven't figured out a good way yet. In the meantime, you can use `:GoReferrers` to get close to the same behavior.

yes.

`:GoReferrers` can show the refs in Quickfix List. If I choose one ref,  the quickfix list context is empty and not closed automatically.

`coc.nvim <Plug>(coc-references)`  impls the feature is better, 
Will vim-go implement the same feature?

Thank you.

**Comment by bhcleek** [comment]
> If I choose one ref, the quickfix list context is empty and not closed automatically.

Are you saying that the quickfix list has all of its entries removed after you jump to one of the refs? That's odd and doesn't match any behavior that I know about.

> coc.nvim <Plug>(coc-references) impls this feature is better,
Will vim-go implement the same feature?

`:GoReferrers` has two modes: `gopls` and `guru`. The only difference is where it gets the data from. There aren't currently any plans to refactor. If you'd like to suggest a behavior change, feel free to open a new issue to describe and discuss it.

**Comment by stamblerre** [comment]
guru's callers and callees functionality is closer to LSP's callHierarchy feature, which `gopls` doesn't yet support: https://github.com/golang/go/issues/39461.

**Comment by bhcleek** [comment]
Thanks, @stamblerre. I subscribed to golang/go#39461 so I'll can modify vim-go when the gopls feature lands.

**Comment by stamblerre** [comment]
As a follow-up, call hierarchy has now been implemented and released in the latest few versions of `gopls`.

**Comment by bhcleek** [comment]
Thanks, Rebecca. Despite having subscribed to https://github.com/golang/go/issues/39461, I missed when it was closed.
