### ISSUE TITLE
ctrl+] behavior unpredictably broken.

### ISSUE THREAD

**Issue by PaulForgey** [fatih/vim-go#2714]
### What did you do? (required: The issue will be **closed** when not provided)

ctrl+] to locate tag under cursor

### What did you expect to happen?
navigation to the declaration

### What happened instead?
vim-go: getting file for Identifier: go [-e -json -compiled=true...920866e3f0956a4f853abb23cf7fc27061336bece86-d: permission denied

In status line of vim window.

This is one of three things which happen unpredictably. Sometimes it incorrectly says the symbol does not exist, other times it actually works. Quitting and restarting vim randomly changes the outcome.

#### vim-go version:
v1.22

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set co=132

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'tag': 'v1.22' }
call plug#end()

</pre></details>

#### Vim version (first three lines from `:version`):

:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  7 2020 00:59:23)
Included patches: 1-96
Compiled by ubuntu@ip-172-31-37-247
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +cryptv            +fork()            +mouse             +popupwin          +tag_binary        +viminfo
+arabic            +cscope            +gettext           +mouseshape        +postscript        -tag_old_static    +vreplace
+autocmd           +cursorbind        -hangul_input      +mouse_dec         +printer           -tag_any_white     +wildignore
+autochdir         +cursorshape       +iconv             -mouse_gpm         +profile           -tcl               +wildmenu
-autoservername    +dialog_con_gui    +insert_expand     -mouse_jsbterm     -python            +termguicolors     +windows
+balloon_eval      +diff              +job               +mouse_netterm     -python3           +terminal          +writebackup
+balloon_eval_term +digraphs          +jumplist          +mouse_sgr         +quickfix          +terminfo          +X11
+browse            +dnd               +keymap            -mouse_sysmouse    +reltime           +termresponse      -xfontset
++builtin_terms    -ebcdic            +lambda            +mouse_urxvt       +rightleft         +textobjects       +xim
+byte_offset       +emacs_tags        +langmap           +mouse_xterm       -ruby              +textprop          -xpm
+channel           +eval              +libcall           +multi_byte        +scrollbind        +timers            +xsmp_interact
+cindent           +ex_extra          +linebreak         +multi_lang        +signs             +title             +xterm_clipboard
+clientserver      +extra_search      +lispindent        -mzscheme          +smartindent       +toolbar           -xterm_save
+clipboard         -farsi             +listcmds          +netbeans_intg     -sound             +user_commands
+cmdline_compl     +file_in_path      +localmap          +num64             +spell             +vartabs
+cmdline_hist      +find_in_path      -lua               +packages          +startuptime       +vertsplit
+cmdline_info      +float             +menu              +path_extra        +statusline        +virtualedit
+comments          +folding           +mksession         -perl              -sun_workshop      +visual
+conceal           -footer            +modify_fname      +persistent_undo   +syntax            +visualextra
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-g
nu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include
/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1
 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -
lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXt -lX11 -lXdmc
p -lSM -lICE  -lm -ltinfo -lnsl  -lselinux -ldl

#### Go version (`go version`):

go version go1.13.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/mesa/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/src/go1.13.3/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/src/go1.13.3/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build257704699=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

version v0.1.3-cmd.gopls, built in $GOPATH mode
</pre></details>

**Comment by bhcleek** [comment]
It looks like you're using a very old version of gopls. Please try upgrading using `:GoUpdateBinaries gopls` and see if you continue to have problems.

**Comment by PaulForgey** [comment]
There was an older version in my path (should have checked for that). Re-affirmed an updated one, now on version `golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=`.

This solved the errors, however there is one remaining issue. It seems that symbols outside the go source file but in the same package (e.g. symbol in foo.go not found if editing bar.go). The symbols should be validly found and the packages compile just fine.

**Comment by bhcleek** [comment]
The problem you're describing now has tests that pass, so I'm going to need specifics to replicate. Given that it's a different issue from what you originally reported, I'm tempted to suggest that we close this issue and open a new one that provides a clear replication path.

**Comment by PaulForgey** [comment]
agreed. I'll create a new issue with a clear reproduction.
