### ISSUE TITLE
Please provide options to set args for `go_metalinter_command`

### ISSUE THREAD

**Issue by flw-cn** [fatih/vim-go#2718]
I want to be able to allow command line arguments to be set in `g:go_metalinter_command` or provide options like `g:go_metalinter_command_args` to support the same purpose.

Please provide options to set args for `go_metalinter_command`. For example `let g: go_metalinter_command_args = [...]`.

Because I need to customize my vim-go integration with golangci-lint for the following reasons:

* golangci-lint has `--exclude-use-default=true` enabled by default but vim-go suppresses it. This made vim-go misreport a lot of information during the development process so that my screen window was squashed.
* The information given by golangci-lint by default contains the code line of the error code. This is useful on the command line, so I don't want to close it in my golangci-ling config file, but it is not necessary when they appear in vim, so I need to use ` --print-issued-lines=false` to suppress them, otherwise my screen space will be squashed.
* When I'm developing in vim, I want to show only the errors caused by my modifications, and ignore the original errors, so I can focus them. For this I need `--new`. I don't want to turn it off at the command line, because I also want it to be consistent with the golangci-lint config file used in CI.
* Any other parameter inconsistency caused by different working scenarios in vim-go and the command line.

### What did you do? (required: The issue will be **closed** when not provided)

I added golangci-lint command line parameters by modifying `g:go_metalinter_command`.

### What did you expect to happen?

I expect vim-go to properly set `errorformat` and recognize the output of golangci-lint.

### What happened instead?

I found that vim-go can no longer set `errorformat` correctly, so it can't recognize the output of golangci-lint correctly.

### Configuration (**MUST** fill this out):

```
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = []
let g:go_metalinter_enabled = []
let g:go_metalinter_command = "golangci-lint run --exclude-use-default=true --print-issued-lines=false --new"
let g:go_metalinter_deadline = "5s"
```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

<details><summary>vimrc</summary><br><pre>
if has('python3')
    silent! python3 1
endif

source ~/.vim/bundle/vim-plug/plug.vim

call plug#begin('~/.vim/bundle')
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):

```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 16:52:17)
macOS version
Compiled by Homebrew
```

#### Go version (`go version`):

```
$ go version
go version go1.13.6 darwin/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/flw/.go/bin/darwin_amd64"
GOCACHE="/Users/flw/Library/Caches/go-build"
GOENV="/Users/flw/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/flw/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/df/gqfvb0_973q9b6zm7n7wk4gc0000gn/T/go-build754600049=/tmp/go-build gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
$ gopls version
golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
</pre></details>

**Comment by bhcleek** [comment]
vim-go has to be able to set some options on the command line to deliver a consistent experience, and frankly, the decisions that golangci-lint has made regarding how to handle some errors reported by some tools that they've forked are erroneous at best.

You can customize your experience by using a golangci-lint config file, but I do not envision making the golangci-lint args completely customizable.
