### ISSUE TITLE
The first line of string is overwritten and cannot be viewed

### ISSUE THREAD

**Issue by erifan** [fatih/vim-go#2721]
### What did you do? (required: The issue will be **closed** when not provided)
Install vim-go with vim-plug

### What did you expect to happen?
The first string will not be overridden
### What happened instead?
The first line of string is overwritten and cannot be viewed. See the following picture.
![Capture](https://user-images.githubusercontent.com/31343225/74317794-f6e7e280-4db6-11ea-83c3-eebae0f79722.PNG)
#### vim-go version:
tip
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" Initialize plugin system
call plug#end()

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
Included patches: 1-1453

#### Go version (`go version`):

go version go1.13.5 linux/arm64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/hostname/.cache/go-build"
GOENV="/home/hostname/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hostname/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/hostname/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/hostname/go1.13/pkg/tool/linux_arm64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build664213326=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=

</pre></details>

**Comment by bhcleek** [comment]
This is due to your colorscheme, and is most likely  related to highlighting errors or warnings from gopls diagnostics.

You have a few options, any one of which is viable:
1. Adjust the highlighting of the `SpellBad` and/or `SpellRare` highlight groups.
2. Adjust the highlighting of the `goDiagnosticError` and/or `goDiagnosticWarning` highlight groups.
3. Use a different colorscheme
4. Turn off the highlighting of diagnostics by adding `let g:go_highlight_diagnostic_warnings=1` and/or `let g:go_highlight_diagnostic_errors=1` to your vimrc
5. Disable diagnostics by adding `let g:go_diagnostics_enabled=0` to your vimrc

**Comment by bhcleek** [comment]
If you _only_ see this when your cursor is on that line, then this issue is relevant, too: https://github.com/vim/vim/issues/5533

**Comment by erifan** [comment]
@bhcleek , I selected option 4, it works, you can close this issue now, thanks very much!
