### ISSUE TITLE
Getting auto-complete to work without the C-x C-o combo?

### ISSUE THREAD

**Issue by Schachte** [fatih/vim-go#2723]
### What did you do? (required: The issue will be **closed** when not provided)

I can only get auto complete to work when I do the Cx/Co combo, but this isn't ideal for my workflow. Is it possible to have the menu auto change as I start to type after the `.` is entered?

**Comment by bhcleek** [comment]
You can use plugins like deoplete to do that. Vim-go only hooks up omnifunc (see `:help omnifunc`)
