### ISSUE TITLE
errcheck's -ignoretests flag is being ignored?

### ISSUE THREAD

**Issue by Integralist** [fatih/vim-go#2725]
### What did you do?

Executed `:GoErrCheck` with various attempts at passing a valid flag for that command:

```
:GoErrCheck! -ignoretests
:GoErrCheck! -ignoretests %
:GoErrCheck! '-ignoretests'
:GoErrCheck! '-ignoretests' % 
```

### What did you expect to happen?

I expected to see a quickfix list with a list of errors that did not include test files.

Example of the flag working perfectly when executed via my terminal shell...

```
$ errcheck
base.go:917:16: writer.Close()
proxy_test.go:168:25:   defer resp.Body.Close()
proxy_test.go:254:25:   defer resp.Body.Close()
proxy_test.go:319:23:   defer resp.Body.Close()
proxy_test.go:341:23:   defer resp.Body.Close()
proxy_test.go:363:23:   defer resp.Body.Close()
proxy_test.go:376:14:   fmt.Fprintf(w, "uh-oh!")
proxy_test.go:414:25:   defer resp.Body.Close()
                                                                                                                                                                                                $ errcheck -ignoretests
base.go:917:16: writer.Close()
```

### What happened instead?

I got a quickfix list with a list of errors that included test files.

### Configuration

```
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

...

" ALE linting
"
" go vet options depends on installing extra command:
"
"   $ go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
"
" ...just be sure to run that install outside of your projects directory,
" otherwise it'll add dependencies to your project go.mod accidentally.
"
let g:ale_go_govet_options = '-vettool=$(which shadow)'
let g:ale_linters = {'go': ['gopls']}
let g:ale_python_mypy_options = '--ignore-missing-imports --strict-equality'
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '▲'
highlight link ALEWarningSign String
highlight link ALEErrorSign Title

nmap <silent> <leader>x :ALENext<cr>
nmap <silent> <leader>z :ALEPrevious<cr>

" vim-go
let g:go_fmt_command = 'goimports'
let g:go_gopls_complete_unimported = 1
let g:go_gopls_staticcheck = 1
let g:go_metalinter_command='gopls'
let g:go_metalinter_deadline = '20s'

" vim-go: check if any expressions return an error type that aren't being handled
autocmd BufWritePost *.go :GoErrCheck! -ignoretests %
```

#### vim-go version:

v1.22

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

set nocompatible
set nobackup
set nowritebackup
set noswapfile

call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

autocmd BufWritePost *.go :GoErrCheck! -ignoretests %

</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 12 2019 11:40:34)
macOS version
Included patches: 1-1839
```

#### Go version (`go version`):

```
go version go1.13 darwin/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/markmcdonnell/Library/Caches/go-build"
GOENV="/Users/markmcdonnell/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/markmcdonnell/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zk/_jgd9h392p55w9fd4lzt5dpw0000gp/T/go-build183558573=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
</pre></details>

**Comment by Integralist** [comment]
Interesting.

So I created a test go script in a random directory on my computer and the following configuration in my vimrc worked fine...

```viml
autocmd BufWritePost *.go :GoErrCheck! -ignoretests
```

And by 'worked fine' I mean I got a message in the status bar saying `vim-go: [errcheck] PASS`.

But when checking on a real project I get...

```
vim-go: error: failed to check packages: go [list -e -json -compiled -test=false -export=false -deps=true -tags= -- .]: exit status 1: build .: cannot find module for path .
vim-go:
```

**Comment by Integralist** [comment]
So inbetween creating this issue ticket, closing vim and opening it again, it seems the original `:GoErrCheck! -ignoretests` call that I manually executed is now showing the same error I just reported in the above comment 

(where as _previously_ that command would have at least run the `:GoErrCheck` successfully, even if it meant the `-ignoretests` flag wasn't being respected) 🤔

**Comment by Integralist** [comment]
**UPDATE**: _INTERESTING_! So here's some steps I took to try and figure out what was going on...

1. open vim
2. open file
3. manually execute `:GoErrCheck! -ignoretests` << ERROR ([as above comment](https://github.com/fatih/vim-go/issues/2725#issuecomment-586204221))!

---

1. open vim
2. open file
3. manually execute `:GoErrCheck!` << WORKS when not passing `-ignoretests` flag
4. `:ccl` then execute `:GoErrCheck! -ignoretests` << WORKS same as if no flag provided.

---

So seems like if I try to call `:GoErrCheck!` with the `-ignoretests` flag _first_ then it'll error. To get it to work in any sense, I have to call `:GoErrCheck!` _without_ the flag first, and then any subsequent calls _with_ a flag are run without error although now ignoring the flag when I want the flag to take effect.

This would explain why my `autocmd` failed as when I opened vim, then opened the file, I immediately ran `:w` which triggered the autocmd where upon the `-ignoretests` flag was passed and as `:GoErrCheck!` hadn't been called before that the autocmd errored.

**Comment by bhcleek** [comment]
I think that all the issues you're seeing can be explained by a small bug in the vim-go code for handling the `:GoErrCheck` command. As-is, if you pass any options, then you also need to pass the package to check. You can confirm by trying your `-ignoretests` invocations and adding the import path that you want to check.

I'll work on a fix.

**Comment by bhcleek** [comment]
A robust fix probably isn't possible. If you pass options, you must also pass the import path(s) to check.

**Comment by bhcleek** [comment]
🤔 alternatively, I suppose we could make it so that its behavior matches the docs: always run it for the current package, and then options can be given without specifying a package. 

Here are the choices before me:
1. update docs to indicate that if any options are passed, then the package name must also be given. The advantage with this approach is that `:GoErrCheck` can be run on any arbitrary package.
2. update the code so that it _always_ checks the current package. Advantage: that would seem to match the behavior as documented in the vim-go help file.

WDYT? As a user, what are your expectations?

**Comment by bhcleek** [comment]
Looking at this again, the docs say that it always runs `errcheck` for the current package, which means I can fix this pretty easily. PR coming up.

**Comment by Integralist** [comment]
Nice 👍 I would have expected it to run against the current package any way so that SGTM.
