### ISSUE TITLE
looks godoc and gopls did not work if gofile (with go mod) in a symlink folder ? 

### ISSUE THREAD

**Issue by Shane-XB-Qian** [fatih/vim-go#2731]
to reproduce:
1, ln -sf /somewhere/onedir hereAsymlink
2, write a simple gofile in this 'hereAsymlink' folder
3, godoc and gopls looks did not work.

### What did you expect to happen?
wish 'shift-k' (godoc) and 'omni-completion' (gopls) work ...

### What happened instead?
can not see doc / omni-completion.

### Configuration (**MUST** fill this out):
let g:go_doc_popup_window    = 0

#### vim-go version:
commit b3c3b6585388565c1de7a9e0a14f8aedb07b7839 (HEAD -> master, origin/master, origin/HEAD)
Date:   Tue Feb 11 18:51:20 2020 -0800

#### Vim version (first three lines from `:version`):
v8.2.260

#### Go version (`go version`):
v1.13.8 linux/amd64

#### gopls version
v0.3.2

maybe a duplicate topic in somewhere by someone, just want to confirm you knew and that's a knew & common issue for now, right?

**Comment by bhcleek** [comment]
There are a number of problems with symlinks and the Go tooling. 

Some references where the use of symlinks have come up before:
* https://github.com/golang/go/issues/15507#issuecomment-241581036
* https://github.com/fatih/vim-go/issues/1599#issuecomment-349608647
