### ISSUE TITLE
Neovim go test vertical split regression from #2639

### ISSUE THREAD

**Issue by drewbailey** [fatih/vim-go#2735]
### What did you do? (required: The issue will be **closed** when not provided)
Prior to https://github.com/fatih/vim-go/pull/2639 in neovim, vertical splits when running `:GoTestFunc!` where opened in an equally spaced split, now on master the new split takes up most of the available space, and it also throws and error.

Prior to #2639 
![image](https://user-images.githubusercontent.com/2614075/74952918-f3fc7b80-53ce-11ea-93cb-4323f603ed36.png)

master
![image](https://user-images.githubusercontent.com/2614075/74953016-1a221b80-53cf-11ea-835d-02fb2f52d72c.png)

I haven't had the time to dig in and look for the exact diff that introduced the change yet

relevant config
```
let g:go_term_enabled = 1
let g:go_term_mode='vsplit'
let g:go_term_close_on_exit = 0

```

**Comment by bhcleek** [comment]
Thank you for the report. I'll look into it soon.
