### ISSUE TITLE
Error Behaviour change

### ISSUE THREAD

**Issue by shaneHowearth** [fatih/vim-go#2738]
### What did you do? (required: The issue will be **closed** when not provided)
Executed a write with `:w`, with errors in my code. The linters run, a little window opens displaying the errors, my cursor's focus is set to the first error listed in the window, I hit `enter` on one of the errors

### What did you expect to happen?
I expect the cursor to be taken to the error listed in the window

### What happened instead?
The cursor stays in the little window, and I have to manually change focus to the code window, and move to the line with the reported error

#### vim-go version:
latest commit in the tree is commit 311ea9dbbe91186afc8262cb2a2e52b406a32dbd (HEAD -> master, origin/master, origin/HEAD)
Merge: 804c8db 184a888
Author: Billie Cleek <bhcleek@users.noreply.github.com>
Date:   Thu Jan 30 21:13:18 2020 -0800

    Merge pull request #2688 from abeltay/update-readme

    Update README to new GoMetaLinter
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
$ cat ~/.vimrc
"execute pathogen#infect()

filetype plugin indent on
filetype on
syntax on
set runtimepath^=~/.vim/bundle/nerdtree
set runtimepath^=~/.vim/bundle/auto-pairs
set runtimepath^=~/.vim/bundle/vim-fugitive
set runtimepath^=~/.vim/bundle/vim-go
set runtimepath^=~/.vim/bundle/vim-rails
set runtimepath^=~/.vim/bundle/vim-abolish
set runtimepath^=~/.vim/bundle/semantic-highlight
set runtimepath+=~/.fzf
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set nocompatible
set number
" set paste
set background=dark
"Make lowercase searches case-insensitive, mixed/upper-case case-sensitive
set ignorecase
set smartcase
set hlsearch
set incsearch
set clipboard=unnamedplus
set textwidth=80

"Show file name in window header
set title

"Enable ruler (bottom right corner)
set ruler

"Prevent lines breaking in the middle of words
set lbr

"set colorcolumn=50,72,80
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set list
set laststatus=2

" toggle GBlame
function! s:ToggleBlame()
    if &l:filetype ==# 'fugitiveblame'
        close
    else
        Gblame
    endif
endfunction

" Key maps
"Avoid q: typo that pops up the annoying command history box
nnoremap q: :q
nnoremap <silent> \ :Commentary<cr>
nnoremap <F2> :setlocal spell! spelllang=en_us<cr>
nnoremap <silent> <F3> :NERDTreeToggle<cr>
" nnoremap <F5> :e!<cr>
nnoremap <silent> <F6> :call <sid>ToggleBlame()<cr>
nnoremap <silent> <F7> :r ~/.vim/snippets/goErr<cr>
nnoremap <silent> <F8> :r ~/.vim/snippets/goTest<cr>
" nnoremap <F8>  :SemanticHighlightToggle<cr>
" set scroll lock per pane
nnoremap <F9> :set scb!<cr>

if !exists("autocommands_loaded")
  let autocommands_loaded = 1
  autocmd BufWritePost *.go :GoMetaLinter
  autocmd BufWritePost *.go :GoBuild
  autocmd BufWritePost *.go :GoVet
  autocmd BufWritePost *.go :GoLint
endif

let g:go_metalinter_command = "golangci-lint run"
let g:go_fmt_command = "goimports"
let g:go_def_mode = "gopls"
let g:go_info_mode = "gopls"
"let g:go_highlight_function_parameters = true
let s:counter = 0
let s:timer = -1

"Comments */
autocmd FileType ruby setlocal commentstring=#\ %s

"FZF
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

set mouse=a
set ttymouse=sgr
set balloonexpr=go#tool#DescribeBalloon()
set balloondelay=250
set ballooneval
set balloonevalterm
"au BufLeave * if (exists("b:desert")) | execute "colorscheme " . b:current_colors | endif
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
Included patches: 1-1453
#### Go version (`go version`):

go version go1.13.7 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shane/.cache/go-build"
GOENV="/home/shane/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shane/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build844487055=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
</pre></details>

**Comment by bhcleek** [comment]
I'll need more information about what your quickfix window looks like: can you paste or screenshot the line in the quickfix window that you're pressing Enter on?

#### some quick tips
Also, let's get your configuration right. You have a few things that aren't necessary and a few that aren't supported.

##### autocmd configuration
```
autocmd BufWritePost *.go :GoMetaLinter
autocmd BufWritePost *.go :GoBuild
autocmd BufWritePost *.go :GoVet
autocmd BufWritePost *.go :GoLint
```

This can be shortened to 
```
let g:go_metalinter_autosave=1
autocmd BufWritePost *.go :GoBuild
```

But the `autocmd BufWritePost *.go :GoBuild` is going to cause the errors from linting to be overwritten. You might want to change it check the location or quickfix list (if you took my previous suggestion, it will be the locationlist) and only call `:GoBuild` if `getloclist(0)` returns and empty list.

However, since vim-go works off of filetypes, and not just  file extensions, you might want to change the autocmd to be guarded similarly to how vim-go does it so that when the filetype of a go file isn't `go`, then you won't have errors. That would then get us to something like this in your vimrc (though I'll admit that mine is in an `after/plugin/vim-go` file):

```
let g:go_metalinter_autosave=1
```
and then in a `after/ftplugin/go.vim` file within your runtime path:
```
autocmd BufWritePost <buffer> if empty(getloclist(0)) | call execute('GoBuild') | endif
```

##### unsupported config value
```
let g:go_metalinter_command = "golangci-lint run"
```
This isn't supported. `let g:go_metalinter_command='golangci-lint'` is, though.

**Comment by shaneHowearth** [comment]
Hi Billie, thanks for the fast response (I didn't mean for anyone to be tagged when I pasted the commit information, it was the only way I could think to display the vim-go version)
Attached is an image of the vim windows, one with an error (which is highlighted by vim-go), and the quickfix window that tells me what the error is.
![image](https://user-images.githubusercontent.com/5995621/75099533-cb66c280-5616-11ea-9fa4-f7377232f814.png)

This is before I apply the changes to my vimrc that you have suggested.

I have a question about this section
| But the autocmd BufWritePost *.go :GoBuild is going to cause the errors from linting to be  overwritten. You might want to change it check the location or quickfix list (if you took my previous suggestion, it will be the locationlist) and only call :GoBuild if getloclist(0) returns and empty list.

| However, since vim-go works off of filetypes, and not just file extensions, you might want to change the autocmd to be guarded similarly to how vim-go does it so that when the filetype of a go file isn't go, then you won't have errors. That would then get us to something like this in your vimrc (though I'll admit that mine is in an after/plugin/vim-go file):


I have to be honest, I don't understand what you are asking me to do here i have gone for the 
```
let g:go_metalinter_autosave=1
autocmd BufWritePost *.go :GoBuild
```
Option, but don't understand what else I need to do

**Comment by bhcleek** [comment]
The reason that the you can't jump from the error to the line in the file on which the errors exists is because golangci-lint's output of that error doesn't put the file location (name, line, and possibly column) in a standard format, so vim-go can't parse that bit out. This is expected behavior. Not all problems reported by golangci-lint will have that characteristic, but this particular one does.

On to the other things about your config file!

What you have here:
```
let g:go_metalinter_autosave=1
autocmd BufWritePost *.go :GoBuild
```

will mostly work, but there will be some edge cases. For instance, if you set the filetype to something other than go, then `:GoBuild` won't be available to you depending on when the filetype was set. This is mostly an edge case, and something you probably don't need to worry about too much.

**Comment by bhcleek** [comment]
vim-go might be able to get that error location, actually. I'll put up a PR in the next couple of days.

**Comment by shaneHowearth** [comment]
Ok, I don't understand. Until I upgraded I've always been able to jump to the error by clicking on it, that's why I titled this a behaviour change (I wouldn't have noticed otherwise :)

**Comment by bhcleek** [comment]
Some output provided by golangci-lint doesn't make it easy to get the location easily. The entries in the quickfix entry where you're seeing this problem are from golangci-lint output that puts the file location in a non-standard place within the line.

However, after closer inspection, I think the problems you're reporting were mostly resolved on master via https://github.com/fatih/vim-go/pull/2720 and https://github.com/fatih/vim-go/pull/2706.
