### ISSUE TITLE
Cannot initialize gopls 

### ISSUE THREAD

**Issue by ryanjzq** [fatih/vim-go#2739]
### What did you do? (required: The issue will be **closed** when not provided)
I ran :GoUpdateBinaies after I installed vim-go. 
gopls could not be updated, but all the other packages were fine.

### What did you expect to happen?
gopls can be updated normally.

### What happened instead?
Error downloading golang.org/x/tools/cmd/gopls: Fetching https://golang.org/x/tools/cmd/gopls?go-get=1^@Parsing meta tags from https://golang.org/x/tools/cmd/gopls?go-get=1 (status code 200)^@get "
golang.org/x/tools/cmd/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/gopls?go-get=1^@
get "golang.org/x/tools/cmd/gopls": verifying non-authoritative meta tag^@Fetching https://golang.org/x/tools?go-get=1^@Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)^
@golang.org/x/tools (download)^@package golang.org/x/tools/cmd/gopls: cannot find package "golang.org/x/tools/cmd/gopls" in any of:^@^I/usr/local/go/src/golang.org/x/tools/cmd/gopls (from $GOROOT)^
@^I/Users/ryanjiang/go/src/golang.org/x/tools/cmd/gopls (from $GOPATH)^@

I have gopls installed, version v0.3.2, using the following
`GO111MODULE=on go get golang.org/x/tools/gopls@latest`

I think vim-go should download gopls from golang.org/x/tools/gopls, there's an extra 'cmd' in the path. 

Right now if I open a .go file, I got message `vim-go: initialize gopls`, and the message never goes away

#### vim-go version:
v1.22

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set nocompatible 
filetype off 

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Valloric/YouCompleteMe'
Plugin 'flazz/vim-colorschemes'
" Add maktaba and codefmt to the runtimepath.
" (The latter must be installed before it can be used.)
Plugin 'google/vim-maktaba'
Plugin 'google/vim-codefmt'
" Also add Glaive, which is used to configure codefmt's maktaba flags. See
" `:help :Glaive` for usage.
Plugin 'google/vim-glaive'

Plugin 'fatih/vim-go'

" All of your Plugins must be added before the following line
call vundle#end()            " required

call glaive#Install()
" Optional: Enable codefmt's default mappings on the <Leader>= prefix.
Glaive codefmt plugin[mappings]
 "Glaive codefmt google_java_executable="java -jar /path/to/google-java-format-VERSION-all-deps.jar"
Glaive codefmt gofmt_executable="gofmt"

augroup autoformat_settings
  autocmd FileType bzl AutoFormatBuffer buildifier
  autocmd FileType c,cpp,proto,javascript AutoFormatBuffer clang-format
  autocmd FileType dart AutoFormatBuffer dartfmt
  autocmd FileType go AutoFormatBuffer gofmt
  autocmd FileType gn AutoFormatBuffer gn
  autocmd FileType html,css,json AutoFormatBuffer js-beautify
  autocmd FileType java AutoFormatBuffer google-java-format
  autocmd FileType python AutoFormatBuffer yapf
  " Alternative: autocmd FileType python AutoFormatBuffer autopep8
augroup END

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" For YCM to detect syntax properly, got it at the following location
" https://github.com/rasendubi/dotfiles/blob/master/.vim/.ycm_extra_conf.py
let g:ycm_use_clangd = 0
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"

let g:go_fmt_command = "goimports"

" https://github.com/fatih/vim-go/issues/2603#issuecomment-565236314
let g:go_gopls_enabled = 1 
" https://github.com/fatih/vim-go/issues/2301#issuecomment-499183536
let g:go_null_module_warning = 0 
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_debug=['lsp']

set number 
set tabstop=2
set autoindent
set smartindent
set hlsearch
set t_Co=256
set paste
set ignorecase smartcase
set completeopt-=preview
colorscheme elflord 
syntax on

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950

#### Go version (`go version`):

go version go1.12.17 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/Users/ryanjiang/go/bin"
GOCACHE="/Users/ryanjiang/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ryanjiang/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b4/g656pzgn35950jjg5bn3f34h0000gn/T/go-build914100902=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_gopls_enabled = 1
g:go_null_module_warning = 0
g:go_debug = ['lsp']
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
g:go_def_mode = 'gopls'
g:go_jump_to_error = 1
g:go_info_mode = 'gopls'
</pre></details>

**Comment by bhcleek** [comment]
Vim-go has installed gopls from `golang.org/x/tools/gopls` since June 2019; I suspect you have multiple copies of vim-go installed and the older instance is in your runtimepath before the newer instance.

ref: https://github.com/fatih/vim-go/commit/4899a0e5088f07c367f178641d46295d09a68c47#diff-19f78a24be6fe98ac3243a1b93028a15R59

**Comment by ryanjzq** [comment]
Thanks Billie, turns out my vim-go was not updated properly, and was running a stale version. I updated vim-go and ran :GoUpdateBinaries again and was able to download gopls.
