### ISSUE TITLE
Syntax highlighting breaks down after sql statements in multiline strings

### ISSUE THREAD

**Issue by trashhalo** [fatih/vim-go#2744]
### What did you do? (required: The issue will be **closed** when not provided)
Edited a go file that has back ticks around sql statemetns

### What did you expect to happen?
Syntax highlighting to not break after the backtick.

### What happened instead?
![Screenshot 2020-02-26 at 9 18 18 AM](https://user-images.githubusercontent.com/177491/75353207-ff412280-5878-11ea-983c-28f8796b7193.png)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 14 2020 09:17:44)
Included patches: 1-257
Compiled by stephen@penguin

#### Go version (`go version`):

go version go1.13.7 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/stephen/.cache/go-build"
GOENV="/home/stephen/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/stephen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/stephen/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/stephen/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/stephen/dev/intake/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build984535789=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 0
g:go_gopls_complete_unimported = 1
g:go_highlight_operators = 0
g:go_highlight_fields = 0
g:go_highlight_variable_declarations = 0
g:go_metalinter_command = 'golangci-lint'
g:go_gorename_command = 'gopls'
g:go_referrers_mode = 'gopls'
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_metalinter_autosave = 0
g:go_gopls_use_placeholders = 1
g:go_highlight_types = 0
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_highlight_methods = 1
g:go_loaded_gosnippets = 1
g:go_highlight_build_constraints = 0
g:go_loaded_install = 1
</pre></details>

**Comment by bhcleek** [comment]
I am not able to duplicate this. Can you provide a simple code file that demonstrates the problem you're encountering?

FWIW, syntax highlighting in Vim is regular expression based and only looks at a given number of lines to determine the context. It's possible that there isn't a good fix for this, but if I can find one that's relatively straightforward I'll see what I can do if you can provide a replication path.

**Comment by trashhalo** [comment]
If someone else comes to this issue with the same problem you can work around it by adding this to your vimrc
```vim
:syntax clear goCharacter
:syntax clear goRawString
```

**Comment by bhcleek** [comment]
Doing that will remove all patterns for matching those groups. There are likely other solutions available that won't remove the highlighting for all strings.

**Comment by bhcleek** [comment]
@trashhalo should I wait for you to provide a replication path, or should we close this?

**Comment by trashhalo** [comment]
> @trashhalo should I wait for you to provide a replication path, or should we close this?

Life got in the way of replying immediately. I mostly wanted to document this in the issue tracker in case someone else hit the same issue. Mission accomplished!

Since its the weekend now, I spent some time today to try and create a small replication and I got one. https://gist.github.com/trashhalo/0455c0e05c0eab5b043f06c004d94d1b

Be sure to note the comment in the code. You have to hit your synmaxcol for this issue to kick in. This explains why in the photo I posted syntax highlighting stops coloring at the letter b in the query.

**Comment by bhcleek** [comment]
Thank you. Since you tracked this down to synmaxcol, I'm going to close this issue.
