### ISSUE TITLE
Vim-go crashes when trying to save syntax error go files

### ISSUE THREAD

**Issue by rjshrjndrn** [fatih/vim-go#2751]
### What did you do? (required: The issue will be **closed** when not provided)

1. Create a go file
2. Create syntax error
3. try to save

### What did you expect to happen?
get a quick fix window with error
### What happened instead?
vim-go crashed
#### vim-go version:
master branch
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }
"{{{
let g:go_fmt_command = "goimports"
"}}}

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.5.0-404-g49cd750d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.13.8 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rajeshr/.cache/go-build"
GOENV="/home/rajeshr/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rajeshr/go_code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build747216850=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.2
    golang.org/x/tools/gopls@v0.3.2 h1:eP1aj1AvT6ynElQH6KP0mmOT2gnWa1gYclHL4wGUbMo=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
> vim-go crashed

Can you provide more details?

**Comment by rjshrjndrn** [comment]
This is fixed in commit ff3eeea1befd40b7ab443f7a17d2c7698458bb20.

Thank you
