### ISSUE TITLE
vim-go highlighting of gopls diagnostics not updating on write

### ISSUE THREAD

**Issue by miscing** [fatih/vim-go#2753]
### What did you do? (required: The issue will be **closed** when not provided)
Highlighting seems to work incorrectly, cannot think of a way reproduce issue other than stating that highlighting does not update on ":w" since last update. For some reason quitting and re-entering file does work. Writing to file fails to pickup both new errors and remove fixed errors

### What did you expect to happen?
Highlighting to disappear as per usual behavior before update. Also new syntax errors should highligh automatically after a write to file. Now requires exiting and re-entering.

### What happened instead?
Incorrect highlighting persists unless one exits and re-opens vim.

#### vim-go version:
v.1.22
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
call plug#begin()
Plug 'majutsushi/tagbar' "F7 toggles ctag bar
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' } "GO vim stuff, tutorial in same dudes github

" Activate features
Plug 'tpope/vim-commentary' "gc{motion} to comment out, gcc=comment line
Plug 'tpope/vim-surround' "Surround stuff with stuff
Plug 'ctrlpvim/ctrlp.vim' "fuzzy search firectory
" List ends here. Plugins become visible to Vim after this call.
call plug#end()

set number "line numbers
set mouse=a "mouse support

syntax on
colorscheme molokai

set list
set listchars=tab:\|·,trail:_,extends:>,precedes:<,nbsp:~

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

 go1.13.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.2
</pre></details>

**Comment by bhcleek** [comment]
Can you be more specific? I'll need a way to replicate what you're seeing if this has any chance of getting fixed.

A few things I'mo wondering:
* does this have anything to do with whether or not saving adds imports (e.g. if you `g:go_fmt_command` is `goimports` and there's a missing import.)
* Does this happen with both Vim and Neovim?
* Does this happen on current master?
* Does writing the file twice have any effect?

**Comment by davidlubomirov** [comment]
I have the exact same issue.
After an update of all binaries`:GoUpdateBinaries`, now after saving a file, errors are not highlighting.

How I caught the issue:
1. I'm opening a file with 2 errors, both of the same time - call to non-existing function in a package
2. After fix on the first highlighted error and save the file`:w`, the second highlight is disappearing

I've tried running all type of commands in order to get it working. But the highlighting is not showing.
The only way to resolve it - close and re-open VIM, but again it's working only until I save a file `:w`

**Comment by bhcleek** [comment]
I'm having a hard time duplicating what's being described here. Here's a quick animated gif from my machine of everything working as expected. What am I doing wrong to duplicate what you're describing?

![recording](https://user-images.githubusercontent.com/1958864/75649036-bf769400-5c06-11ea-835d-87168e460213.gif)

**Comment by miscing** [comment]
![govim-issue](https://user-images.githubusercontent.com/61654431/75679920-2d6b9b80-5c99-11ea-88a2-6a284e01d330.gif)

Here is the issue. With some further testing it seems it is only broken in my go/src directory, any go file outside it works normally. No idea why.

**Comment by bhcleek** [comment]
@miscing I can't duplicate this in $GOPATH either.

Does this problem still exist for you on master?

Also, can you run vim with `let g:go_debug=['lsp']` and provide the output of the gopls debug window after saving the file?

**Comment by miscing** [comment]
It still persists on master.

debug output:
sent: Content-Length: 288^M^@^M^@{"method": "textDocument/didChange", "jsonrpc": "2.0", "params": {"contentChanges": [{"text": "package main\n\nimport \"fmt\"\n\nfunc main() {\n\n\t// hello := \"hello\"\n\tfmt.Println(hello)\n}\n"}], "textDocument": {"uri": "file:///[REMOVED:GOPATH]/go/src/hello/main.go", "version": 6}}}

sent: Content-Length: 288^M^@^M^@{"method": "textDocument/didChange", "jsonrpc": "2.0", "params": {"contentChanges": [{"text": "package main\n\nimport \"fmt\"\n\nfunc main() {\n\n\t// hello := \"hello\"\n\tfmt.Println(hello)\n}\n"}], "textDocument": {"uri": "file:///[REMOVED:GOPATH]/go/src/hello/main.go", "version": 7}}}

**Comment by bhcleek** [comment]
There should be a lot more output than that.

**Comment by miscing** [comment]
[govim_log.txt](https://github.com/fatih/vim-go/files/4277136/govim_log.txt)

My apologies i was using the command wrong. Too long for github comment so I linked the log file, hope that's fine?

**Comment by miscing** [comment]
[govim_log.txt](https://github.com/fatih/vim-go/files/4277243/govim_log.txt)

My apologies i used the command wrong. File didn't fit here so i linked it here, hope that's okay.

**Comment by bhcleek** [comment]
That log doesn't show any `publishDiagnostics` notifications from gopls. Did you fully replicate the issue in the Vim session that that log is from?

**Comment by miscing** [comment]
[govim-issue.txt](https://github.com/fatih/vim-go/files/4277373/govim-issue.txt)

Another attempt. Thanks for the patience.

**Comment by bhcleek** [comment]
@miscing those logs show that the diagnostics were cleared after your edits.

The first diagnostic that identified the problematic code:
```
received: Content-Length: 298

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file://REMOVED/go/src/hello/main.go","version":1,"diagnostics":[{"range":{"start":{"line":6,"character":13},"end":{"line":6,"character":18}},"severity":1,"source":"compiler","message":"undeclared name: hello"}]}}
```

followed by writing your changes:
```
sent: Content-Length: 285

{"method": "textDocument/didChange", "jsonrpc": "2.0", "params": {"contentChanges": [{"text": "package main\n\nimport \"fmt\"\n\nfunc main() {\n\n\thello := \"hello\"\n\tfmt.Println(hello)\n}\n"}], "textDocument": {"uri": "file://REMOVED/go/src/hello/main.go", "version": 2}}}
sent: Content-Length: 285

{"method": "textDocument/didChange", "jsonrpc": "2.0", "params": {"contentChanges": [{"text": "package main\n\nimport \"fmt\"\n\nfunc main() {\n\n\thello := \"hello\"\n\tfmt.Println(hello)\n}\n"}], "textDocument": {"uri": "file://REMOVED/go/src/hello/main.go", "version": 3}}}
```

followed by the diagnostics that show that there are no errors:
```
received: Content-Length: 153

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file://REMOVED/go/src/hello/main.go","version":2,"diagnostics":[]}}
```
I'm still unable to duplicate what you're describing. The last screen recording you posted doesn't show the command you're typing, which is what I'd need to be able to see to understand when the file is being written so that I can correlate that with what's highlighted.

**Comment by davidlubomirov** [comment]
@bhcleek 

I've created a small project outside GOPATH.

- [project](https://github.com/davidlubomirov/vim-go-issue)
- [recording](https://github.com/davidlubomirov/vim-go-issue/blob/master/vim-go-issue.gif)
- [issue log without mod init](https://github.com/davidlubomirov/vim-go-issue/blob/master/issue-without-go-mod)
- [issue log after mod init](https://github.com/davidlubomirov/vim-go-issue/blob/master/issue-output-with-mod-init)

**NOTE:**  I have other projects defined outside GOPATH, but this problem never showed before the binaries update I did couple of days ago.

**Comment by miscing** [comment]
github.com/miscing/govim-highlighting-issue

Did the same, one directory has gif of issue inside gopath and other gif of no issue outside gopath.
Used nvim commands and vim config file included.

gif of issue and logs included here too:
![issue](https://user-images.githubusercontent.com/61654431/75772480-b7c50580-5d54-11ea-8f3e-d101a2db8003.gif)
[issue-logs.txt](https://github.com/fatih/vim-go/files/4281054/issue-logs.txt)

**Comment by bhcleek** [comment]
Thank your patience.

I can duplicate this now and will have a fix soon.

**Comment by bhcleek** [comment]
A quick progress report:

I'm making headway, but am currently fighting getting some useful tests working so I can validate my fixes; we have to be careful with this to avoid introducing a regression.

In the meantime, you might consider either disabling the gopls diagnostic highlighting entirely or going back to revision that doesn't have this problem (https://github.com/fatih/vim-go/commit/252602d546901a50adc0fc310ff54c6b0d6cc9cb ?) or v1.22.

**Comment by davidlubomirov** [comment]
@bhcleek I guess only checkout to v1.22 is not enough.

What else I need to execute ?

**Comment by bhcleek** [comment]
@davidlubomirov That should be enough, but you have to check it out to the right place. Without knowing how you manage your Vim plugins, it's impossible for me to say precisely what you need to do.

**Comment by dannywolfmx** [comment]
Hi, i get think a i have a same error.
I dont get the highlight error, after save the file (i need to close the file and reopen). If i disable the go_fmt_autosave, the highlight works fine. 
![Peek 06-03-2020 21-14](https://user-images.githubusercontent.com/1672871/76135821-41dcca80-5ff0-11ea-8dd7-af687340ecd8.gif)

**Comment by bhcleek** [comment]
I've made progress on the tests, so I'll be able to focus on implementing a fix.

**Comment by bhcleek** [comment]
The solution for this issue was delayed, because my computer took a dive shortly after my last progress update.

I have good tests, and am working on a fix, but am having a hard time getting one in place. Interestingly, I can duplicate the issue pretty easily. I'm trying to figure out if this is a bug in Vim or not. Either way, using `gopls` for `g:go_fmt_command` helps avoid this issue, but comes with a tradeoff: `:GoImports` has to be called explicitly when `g:go_fmt_command` is set to `gopls`, because it doesn't adjust the imports yet.

**Comment by bhcleek** [comment]
I have the tests passing. Now I need to write one more to deal with another situation that the code was trying to workaround when formatting or imports are changed on write.

**Comment by bhcleek** [comment]
I'm finally nearly done with this. It was surprisingly tricky to get right, and I suspect there is still an edge case that I'm going to try to verify and hopefully resolve before I merge the PR after I put it up.

**Comment by zhaogaolong** [comment]
This problem reappeared。
my env
nvim: v0.6.0
gopls version: golang.org/x/tools/gopls v0.7.1
