### ISSUE TITLE
fmt problem

### ISSUE THREAD

**Issue by AlimByWater** [fatih/vim-go#2761]
Right after i type point in  `fmt.` vim freezes.
It freezes and on the bottom of window i see 

> vim-go: initializing gopls
I tried to reinstall it few times (throw Plug and simple straight clonning from git) and nothing changed
![image](https://user-images.githubusercontent.com/50614529/76239367-7fd12d00-6242-11ea-8a3f-73b956d7f389.png)

**Comment by bhcleek** [comment]
Please fill out the template. There is not enough information here to be useful to diagnose or replicate what you're seeing
