### ISSUE TITLE
Feature: GoImplements jumps to the single implementation

### ISSUE THREAD

**Issue by a-b** [fatih/vim-go#2762]
I'd like to request configurable feature when the interface has only one implementation jump to implementation without popping up a quickfix list.

**Comment by vimalk78** [comment]
how do you get `:GoImplements` to work at all? for me it just never retuns any result.
ends in `vim-go: [implements] FAIL`

**Comment by bhcleek** [comment]
@a-b I think the best way for you to get this behavior is to leverage VimL jump to the quickfix entry when there's only one quickfix element and the title of the quickfix window is `GoImplements`.
