### ISSUE TITLE
Godef  no identifier found when source file changed

### ISSUE THREAD

**Issue by lxstorm** [fatih/vim-go#2763]
### What did you do? (required: The issue will be **closed** when not provided)
when source file add line before variable and save, godef show `no identifier found` error when I try to foud the definition of this variable

1. create a file t.go, now if i move the cursor on main's testF and `gd` the it can jump to func testF correctly

```
package main

func testF() {}

func main() {
    testF()
}
```
debug info

> sent: Content-Length: 178^M^@^M^@{"method":"textDocument/definition","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///data00/home/luoxi.000/go/src/tt/t/t.go"},"position":{"character":1,"line":5}}}

> received: Content-Length: 167^M^@^M^@{"jsonrpc":"2.0","result":[{"uri":"file:///data00/home/luoxi.000/go/src/tt/t/t.go","range":{"start":{"line":2,"character":5},"end":{"line":2,"character":10}}}],"id":4}

2. don't close the vim, insert a line before testF() 
```
package main

func testF() {}

func main() {

    testF()
}
```
debug info

> sent: Content-Length: 178^M^@^M^@{"method":"textDocument/definition","jsonrpc":"2.0","id":3,"params":{"textDocument":{"uri":"file:///data00/home/luoxi.000/go/src/tt/t/t.go"},"position":{"character":1,"line":6}}}

> received: Content-Length: 87^M^@^M^@{"jsonrpc":"2.0","error":{"code":0,"message":"no identifier found","data":null},"id":3}

3. `:w` and `gd`will produce `vim-go: no identifier found`

if I close the file and reopen it, the `gd` can jump to the right place

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

> :version
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 13 2018 20:20:49)
> Included patches: 1

#### Go version (`go version`):

> go version go1.13 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

> golang.org/x/tools/gopls v0.3.2
>     golang.org/x/tools/gopls@(devel)

</pre></details>

**Comment by bhcleek** [comment]
I can't duplicate what you're describing. Can you update to the latest gopls with `:GoUpdateBinaries gopls` and try again?

**Comment by bhcleek** [comment]
closed for lack of feedback

**Comment by lxstorm** [comment]
Sorry for my late feedback, Finally I found how to reproduce it, If I have a home which is a soft link like ` /home/luoxi.000 -> /data00/home/luoxi.000`
cd to the directory above where pwd echos `/home/luoxi.000/go/src/tt/t/t.go`, now the problem can reproduce according to the steps above. 
(GOPATH `/home/luoxi.000/go` or `/data00/home/luoxi.000` both have this problem)
Seems like the gopls cache use path with prefix `/data000` as the cache key, however the definition use `/home` prefix?

**Comment by bhcleek** [comment]
Go tools typically do not support symlinks. https://github.com/golang/go/issues/15507#issuecomment-241581036

**Comment by nickChenyx** [comment]
I have same problem, and found workaround, for new guys.
here my file in `/home/cyx/go/src/demo/main.go`, and my `$GOPATH=$HOME/go` equals  `/home/cyx/go`.
i found `/data00/home/cyx/go/src/demo/main.go` when vim-go send file path to `gopls`. (you can set `let g:go_def_mode='gopls'` see the lsp debug log). 
so i try to set my  `$GOPATH=/data00/home/cyx/go` and solve the problem.
