### ISSUE TITLE
Errors/warnings not showing up in the quickfix or location windows

### ISSUE THREAD

**Issue by trstringer** [fatih/vim-go#2764]
### What did you do? (required: The issue will be **closed** when not provided)

I am using vim-go in Vim, and neither the quickfix or location windows are showing a summary of the errors/warnings/linting issues for the current buffer.

### What did you expect to happen?

Show summary of issues for the current buffer.

### What happened instead?

Empty quickfix and location windows.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'scrooloose/nerdtree'
" Plugin 'jiangmiao/auto-pairs'
Plugin 'ekalinin/Dockerfile.vim'
Bundle 'jistr/vim-nerdtree-tabs'
Plugin 'w0rp/ale'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'martinda/Jenkinsfile-vim-syntax'
Plugin 'fatih/vim-go'
Plugin 'dracula/vim'

Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set number
set relativenumber
set nowrap
set splitbelow
set splitright
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set foldmethod=indent
set foldlevelstart=99
set wildignore+=**/node_modules/**
set wildignore+=**/site-packages/**
set wildignore+=**/vendor/**
set wildignore+=*.pyc
set wildmenu
set wildmode=list:full
set path=.,,**
set background=dark
set fileformat=unix
set nohlsearch
syntax on

" YCM
let g:ycm_python_binary_path = 'python'
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_autoclose_preview_window_after_insertion = 1

" vim-go
let g:go_def_mapping_enabled = 0
" let g:go_fold_enable = []
let g:go_fmt_experimental = 1

" NERDTree
let g:NERDTreeWinSize=26
let g:NERDTreeIgnore=['\.egg-info$', 'venv', 'Session.vim', '__pycache__', '\.pyc$']

" Mappings
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
inoremap jj <esc>
nnoremap <C-]> :NERDTreeTabsToggle <CR>

au BufNewFile,BufRead *.py,*.js,*.sh
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

au BufNewFile,BufRead *.yml,*.yaml,*.tf
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
    \ set autoindent |
    \ set expandtab |
    \ set cursorcolumn

" the Dockerfile plugin does a filetype detection on docker-compose.ya?ml
" but this formatting and filetype should remain YAML
" autocmd BufRead,BufNewFile docker-compose*.{yaml,yml}* set ft=yml

highlight LineNr ctermfg=blue
highlight CursorLineNr ctermfg=blue
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2020 21:48:46)
Included patches: 1-2269
#### Go version (`go version`):

go version go1.13.6 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/trstringer/.cache/go-build"
GOENV="/home/trstringer/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/trstringer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build861566960=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
</pre></details>

**Comment by bhcleek** [comment]
I can't tell from your description what actions you're taking when you expect the lists to be populated. Can you clarify?

**Comment by trstringer** [comment]
Sorry for the lack of clarity! Here's a screenshot. I thought that this error/warning/linting issue should appear in quickfix:

![Screen Shot 2020-03-12 at 1 05 15 PM](https://user-images.githubusercontent.com/1445483/76546621-33fcce80-6462-11ea-9c49-70d69c9bdff8.png)

**Comment by bhcleek** [comment]
You can use `:GoDiagnoatics` to see those errors.

**Comment by trstringer** [comment]
Ah good information. Is there any way to get those errors into quickfix or location window?

**Comment by bhcleek** [comment]
You could use the mapping to make it easier (see `:help go-diagnostics`) , but there's no way to to have it populate on the fly. Doing so would potentially overwrite error lists when you don't want it to.

**Comment by trstringer** [comment]
Thanks!
