### ISSUE TITLE
GoCoverage appends build tags even when empty interfering with manually providing it

### ISSUE THREAD

**Issue by asutoshpalai** [fatih/vim-go#2765]
### What did you do? (required: The issue will be **closed** when not provided)

```
:GoCoverage . -tags abc 
```

### What did you expect to happen?
For the normal coverage workflow

### What happened instead?
```
vim-go: run "go help test" or "go help testflag" for more information
```

With `shell-command` logging, I got the following output:

```
vim-go: job command: ['go', 'test', '-tags', '', '-coverprofile', '/var/folders/wb/hj0lprc55kl472yvy0v059yc0000gq/T/vVByTpj/2', '.', '-tags', 'abc']
```

Basically even though my build tags are empty, it's still adding it. The relevant code I believe is at https://github.com/fatih/vim-go/blob/52b66c0b125e095bc5a1d54d9810c5a0c8141906/autoload/go/coverage.vim#L53 

Locally removing the tags fixed it.

#### vim-go version:
364a8cfe33b21151dacb8886a0c4eb0855759d57

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries'  }
call plug#end()

let g:go_debug = ['shell-commands']

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  3 2020 01:40:25)
macOS version
Included patches: 1-200

#### Go version (`go version`):

go version go1.13.7 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="redacted"
GOENV="redacted"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="redacted"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.7/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="<redracted>"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wb/hj0lprc55kl472yvy0v059yc0000gq/T/go-build293350086=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_metalinter_autosave_enabled = ['golint', 'govet', 'typecheck']
g:go_metalinter_command = 'golangci-lint'
g:go_gotags_bin = 'gotags'
g:go_metalinter_autosave = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

**Comment by bhcleek** [comment]
To use the build tags, please rely on `:GoBuildTags` to set them before calling `:GoCoverage`.
