### ISSUE TITLE
:GoDef throws E909 & E171 -- 

### ISSUE THREAD

**Issue by AlbericC** [fatih/vim-go#2767]
### What did you do? (required: The issue will be **closed** when not provided)

`:Godef` on any symbol in go source code

### What did you expect to happen?

jump to the definition of said symbol

### What happened instead?

Vim doesn't jump to definition, but reports errors : 

    Error while processing function 18[13]..20[26]..<SNR>129_definitionHandler:
    E909: Cannot index a special variable
    Error detected while processing function 18:
    E171: Missing :endif

with godebug = pls, It seems like the filepath is not converted the same way in this situation, 

    sent: Content-Length: 182 {"method":"textDocument/hover","jsonrpc":"2.0","id":45,"params":{"textDocument":{"uri":"file:///C:/Users/ACOR/go/src/wcsms/logger/logger.go"},"position":{"character":21,"line":153}}} 
    received: Content-Length: 200 {"jsonrpc":"2.0","result":{"contents":{"kind":"plaintext","value":"func (ColorLogger).Fail(a ...interface{})"},"range":{"start":{"line":153,"character":21},"end":{"line":153,"character":25}}},"id":45}

indeed hover works fine, but 
    
    sent: Content-Length: 199 {"method":"textDocument/definition","jsonrpc":"2.0","id":46,"params":{"textDocument":{"uri":"C%3A%2FUsers%2FACOR%2Fgo%2Fsrc%2Fwcsms%2Freflex_authentication.go"},"position":{"character":7,"line":49}}}
    received: Content-Length: 39 {"jsonrpc":"2.0","result":null,"id":46}

and definitions seem to be  broken

For what it's worth, I updated through Plug recently and before that I did not encounter this issue before that. 

#### vim-go version:
master as of today : commit 52b66c0

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
let g:mapleader = ','
filetype on
filetype plugin on
filetype indent on                  " load language specific indent files
syntax enable                       " allow syntax highlighting

"Plugins {{{
call plug#begin()
Plug 'junegunn/vim-plug'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
"}}}

"folding vim: foldmethod=marker foldlevel=0:
</pre></details>

#### Vim version (first three lines from `:version`):

    VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 10 2019 22:01:47)                                                                                                                                                                              
    MS-Windows 64-bit GUI version with OLE support                                                                                                                                                                                                  
    Included patches: 1-1661  
#### Go version (`go version`):

    go version go1.13.5 windows/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ACOR\AppData\Local\go-build
set GOENV=C:\Users\ACOR\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ACOR\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ACOR\AppData\Local\Temp\go-build360200098=/tmp/go-build -gno-record-gcc-switches

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
</pre></details>

**Comment by bhcleek** [comment]
Can you give https://github.com/fatih/vim-go/issues/2767 a try to see if it solves the problem for you? I don't have a Windows machine readily available to test it on.

**Comment by AlbericC** [comment]
It does !

**Comment by sober-wang** [comment]
> 
> 
> It does !

How to fix it? 
I meet it , I feel confuse.
