### ISSUE TITLE
GoRun / Test / Debug not working with multi modules directories

### ISSUE THREAD

**Issue by yarinm** [fatih/vim-go#2770]
### What did you expect to happen?
I have a single repository with many go modules each in its own respective directory.
I usually open nvim under the root of the repository and working on the different modules.

Code completion and other features with gopls work properly on any file I work on while my working directory is the root of repository.

However, when I try and run / test / debug one of the go files I work on I get several errors in the following format:
`cannot find module providing package github.com/XXX: working directory is not part of a module`

This is also reproducible when I try and do go run with the full file path while I'm in the root folder.
Is there a way to overcome this ? 

I tried working with autochdir but that starts to break many plugins I like to use like NERDTree and FZF

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
#### Go version (`go version`):

go version go1.14 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:

</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/yarin/go/bin"
GOCACHE="/Users/yarin/Library/Caches/go-build"
GOENV="/Users/yarin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yarin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_d/xzxqwkds3cxb18cm25lwgqch0000gn/T/go-build228462867=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
</pre></details>

**Comment by bhcleek** [comment]
Does `:GoAddWorkspace` work for you to add additional workspaces (e.g. add a workspace for each module)?

**Comment by yarinm** [comment]
@bhcleek I don't have such command.

I think I've found a solution which can be somewhat reasonable. I've created in the root directory a module and I've added each module in the repo there used replace to set it to use the local copies. Does it makes sense to do that?

**Comment by bhcleek** [comment]
That should work, but if you don't have the `:GoAddWorkspaces`, though, it indicates that you may be running an old version of vim-go.

**Comment by yarinm** [comment]
I updated vim-go and GoAddWorkspace <full path to specific module> doesn't help.

**Comment by bhcleek** [comment]
Ok. I'll give this workflow some attention soon. In the meantime, your workaround will work ok for your local environment

**Comment by bhcleek** [comment]
I'm not able to duplicate the problem that you're describing. What version of vim-go are you using?

**Comment by yarinm** [comment]
I'm using the latest version (commit 50d52bafa00448ca8cde2b0e05b0fe71c9397762).

Maybe I'm call GoAddWorkspace wrong?

I'm trying to call it by doing :GoAddWorkspace ./someDirectoryInTheMonoRepo

**Comment by bhcleek** [comment]
As long as your working directory is the root of the mono repo, that should be fine.

What's especially strange here is that the error looks like it's from gopls, but that has nothing to do with `:GoTest`, `:GoRun`,or `:GoDebugStart`. I think I'm going to need a simple reproduction example. Can you provide a script to create an faithful directory structure that I can use to try to duplicate what you're seeing (be sure it duplicates on your machine, too ;-) )?

**Comment by yarinm** [comment]
https://github.com/yarinm/vim-go-issue

It reproduces very easily in my example:
Notice I created go.mod in the root

1. Open VIM from the root directory and open mycomp/main.go, from there do ":GoRun" and it works
2. Remove the go.mod from the root directory
3. Reopen VIM from the root directory, open mycomp/main.go and run :GoRun again

I currently get:
```
:!go run '/Users/yarin/workspace/vim-go-issue/mycomp/main.go'  2>&1| tee /var/folders/bv/_kllxtj105v9nhkbt5r2rslh0000gn/T/nvimNGNwlu/4
mycomp/main.go:3:8: cannot find package "yarin/mylib" in any of:
        /usr/local/Cellar/go/1.14/libexec/src/yarin/mylib (from $GOROOT)
        /Users/yarin/go/src/yarin/mylib (from $GOPATH)
```

I'm trying to run (when I don't have the go.mod file):
```
:GoAddWorkspace mycomp/
:GoAddWorkspace mylib/
```

And run the :GoRun again but I get the same error..

**Comment by bhcleek** [comment]
Is the `go.mod` in your root the only `go.mod` in your repo?

**Comment by bhcleek** [comment]
`:!go run` isn't executed by vim-go, it's just shelling out. If `go run` at the commandline and `:!go run` in Vim don't work, then there are issues for you to resolve in your repo regardless of vim-go.

**Comment by bhcleek** [comment]
I see that you do have more `go.mod` files in your repo. Sorry I missed the link to your repo previously.

Your main.go also references yarin/mylib, but you're starting out with your working directive above the mycomp module.

From what I can tell, it seems that the problem here is mostly that the go tool does does not try to resolve references to the module relative to the source file location; it expects your working directory to be within the module. In vim, this means that you should cd into the mycomp directory. At the command line, you'd need to cd into the mycomp directory to get its `go.mod` file to be respected as you expect.

Try making sure that go commands work as you expected first; once you do that, I think it will become clear what you need to do within vim-go.

**Comment by bhcleek** [comment]
As for the vim-go commands:

* `:GoRun` can be easily changed to support what your expections are here
* `:GoDebug` already`:GoTest` should already work and I've confirmed that they do on my machine. 

I never see the original error that you reported, `cannot find module providing package github.com/XXX: working directory is not part of a module`.

**Comment by yarinm** [comment]
I think if GoRun / Debug / Test would run from the file’s directory and not from the CWD I’ve opened vim from it would work without an issue (as I see when I’m running go run from the shell)

**Comment by bhcleek** [comment]
:`GoDebugStart` and `:GoTest` do cause the or grams to run in the buffers directory.

**Comment by bhcleek** [comment]
@yarinm #2782 should solve the issue you've seen with `:GoRun`. Can you give it a try?

I haven't been able to duplicate the original error message you described or any issues with `:GoDebugStart` or `:GoTest`. Can you provide more details about exactly what problems you're seeing with those and a clear replication path?

**Comment by yarinm** [comment]
@bhcleek Works great!
