### ISSUE TITLE
" : GoUpdateBinaries " invalid version

### ISSUE THREAD

**Issue by yangxyo** [fatih/vim-go#2775]
# What did you expect to happen?
I hope to update the vim-go. 
I do it manually,  `go get github.com/zmb3/gogetdoc`, it worked.
But `: GoUpdateBinaries`, It's wrong.

### What happened instead?
```
vim-go: Error installing github.com/zmb3/gogetdoc@master: go get github.com/zmb3/gogetdo
c@master: github.com/zmb3/gogetdoc@master: invalid version: Get "https://proxy.golang.or
g/github.com/zmb3/gogetdoc/@v/master.info": dial tcp 172.217.24.17:443: i/o timeout
vim-go: Updating guru. Reinstalling golang.org/x/tools/cmd/guru@master to folder /Users/
sweeney/Documents/code/go/bin
vim-go: Error installing golang.org/x/tools/cmd/guru@master: go get golang.org/x/tools/c
md/guru@master: golang.org/x/tools/cmd/guru@master: invalid version: Get "https://proxy.
golang.org/golang.org/x/tools/cmd/guru/@v/master.info": dial tcp 172.217.24.17:443: i/o
timeout
vim-go: Updating gopls. Reinstalling golang.org/x/tools/gopls@latest to folder /Users/sw
eeney/Documents/code/go/bin
vim-go: Error installing golang.org/x/tools/gopls@latest: go get golang.org/x/tools/gopl
s@latest: module golang.org/x/tools/gopls: Get "https://proxy.golang.org/golang.org/x/to
ols/gopls/@v/list": dial tcp 172.217.24.17:443: i/o timeout
vim-go: Updating fillstruct. Reinstalling github.com/davidrjenni/reftools/cmd/fillstruct
@master to folder /Users/sweeney/Documents/code/go/bin
vim-go: Error installing github.com/davidrjenni/reftools/cmd/fillstruct@master: go get g
ithub.com/davidrjenni/reftools/cmd/fillstruct@master: github.com/davidrjenni/reftools/cm
d/fillstruct@master: invalid version: Get "https://proxy.golang.org/github.com/davidrjen
ni/reftools/cmd/fillstruct/@v/master.info": dial tcp 172.217.24.17:443: i/o timeout
vim-go: Updating godef. Reinstalling github.com/rogpeppe/godef@master to folder /Users/s
weeney/Documents/code/go/bin
vim-go: Error installing github.com/rogpeppe/godef@master: go get github.com/rogpeppe/go
def@master: github.com/rogpeppe/godef@master: invalid version: Get "https://proxy.golang
.org/github.com/rogpeppe/godef/@v/master.info": dial tcp 172.217.24.17:443: i/o timeout
```

#### vim-go version:
latest

####  `vimrc` you used to reproduce:

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go'}

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  4 2020 22:41:50)

#### Go version (`go version`):
go version go1.14 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Users/sweeney/Documents/code/go/bin"
GOCACHE="/Users/sweeney/Library/Caches/go-build"
GOENV="/Users/sweeney/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sweeney/Documents/code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9n/5k9ghmws7kd6zswgsvlcdcsh0000gn/T/go-build416859345=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by yangxyo** [comment]
I use `export GOPROXY=https://goproxy.cn,direct` to resolve this problem.
But I have a doubt.
I used a proxy.
`export ALL_PROXY=socks5://127.0.0.1:20808`
And I can visit this page through terminal.
![image](https://user-images.githubusercontent.com/32320149/76701380-958b9a00-66fb-11ea-925b-8110547cfcae.png)
what happened?

**Comment by bhcleek** [comment]
@yangxyo all the errors are i/o timeout errors. Whatever problems you're experiencing seem to be peculiar to your particular configuration.

Under the hood vim-go is just using `go get`, so if you can get `go get` to work at your commandline, then the problem you're having with `:GoUpdateBinaries` will likely be resovled, too.

**Comment by crrrrrw** [comment]
I use GOPROXY

```
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
```
it works for me
