### ISSUE TITLE
vim-go is producing messages with autocomplete selection's documentation if I hit escape - could someone help debug?

### ISSUE THREAD

**Issue by JoeHFB** [fatih/vim-go#2776]
### What did you do? (required: The issue will be **closed** when not provided)
1. I created the following stub `.vimrc` and `ftplugin/go.vim` (I pasted them in the configuration section below)

2. I created a sample go file below
<details><summary>test.go</summary><br><pre>
package main

import "fmt"

func main() {
	blah := &Blah{}
}

type Blah struct{}

// Test comment to test autocomplete popup content.
// More irrelevant messages
// Even more...
// ...
func (b *Blah) PrintSomeString(input string) {
	fmt.Printf("alsfkdjalsdfjdas %s", input)
}
</pre></details>

2. Right below the line `blah := &Blah{}`, I tried the following two things:

- `blah.`  -> selected my test function `PrintSomeString` -> hit `esc`
![image](https://user-images.githubusercontent.com/60893676/76774097-e04bf700-6779-11ea-8379-bca2ad1e266c.png)

- `fmt.`   -> selected `Errorf` -> hit `esc`
![image](https://user-images.githubusercontent.com/60893676/76774116-e641d800-6779-11ea-9f6e-bc16b69b575e.png)

### What did you expect to happen?

If I `esc` out of autocomplete, I expected nothing else to happen other than exiting out of the autocomplete. But...

1. `blah.`:  When I hit escape, I didn't expect this to pop up at the bottom (red box) redisplaying the doc of the selected autocomplete option
![image](https://user-images.githubusercontent.com/60893676/76774155-f5288a80-6779-11ea-8945-f929df4b6a76.png)

2. `fmt.`: Same thing.  But also - this one didn't display any documentation period on the popup window like `blah.` did
![image](https://user-images.githubusercontent.com/60893676/76774214-070a2d80-677a-11ea-8ba5-0e25413a285f.png)

Here I'd also expect the docs to show up

### What happened instead?
_Note: This happens to me in all go code (I have several repos that I work with) - and I tried moving to use coc.nvim with gopls as the language server instead as well with vim-go's autocomplete disabled - but that also had the exact same issue as this did_

In both cases, that `vim-go: {function signature} ... {documentation}` message block came up at the bottom of my screen after I hit `esc` (I do this when I mistakenly typed something and autocomplete pops up)

For `fmt.`, I also expected the docs to show up - but it didn't. :(  Also, is it just me or is the autocomplete list there after `fmt.` a lot smaller than it should be?  https://golang.org/pkg/fmt/#pkg-index  Looking at this I'd expect a lot more to show up there than just three.

#### vim-go version:
Err, looks like I'm on on an unversioned commit `52b66c0b125e095bc5a1d54d9810c5a0c8141906`... In https://github.com/fatih/vim-go/issues/2221 bhcleek had advised to use master so I just kept doing it...

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" Migrate to Vim-Plug based on https://github.com/junegunn/vim-plug/wiki/tips
call plug#begin('~/.vim/bundle')

Plug 'jiangmiao/auto-pairs'

Plug 'lifepillar/vim-mucomplete'

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

Plug 'ErichDonGubler/vim-sublime-monokai'

call plug#end()

filetype plugin indent on
set encoding=utf-8

set completeopt=menuone,popup,noinsert

set showmatch

set number

set incsearch
set ignorecase
set smartcase
set hlsearch

syntax on
set background=dark
set termguicolors
colorscheme sublimemonokai
let g:sublimemonokai_term_italic = 1

set autoindent
set expandtab
set softtabstop=4
set shiftwidth=4
set shiftround

set backspace=indent,eol,start

set laststatus=2
set noshowmode

augroup csharp_settings
    autocmd!

    " Go and C# - Auto remove preview window after autocomplete
    autocmd CompleteDone *.cs,*.go if pumvisible() == 0 | pclose | endif
augroup END

" Turn off bracketed paste mode on launch
" workaround for https://github.com/vim/vim/issues/1start671
if has('unix')
  let s:uname = system('echo -n "$(uname)"')
  if !v:shell_error && s:uname ==? 'Linux'
    set t_BE=
  endif
endif
</pre></details>

<details><summary>ftplugin/go.vim</summary><br><pre>
" mucomplete trigger omni completion after a dot or after two characters
let g:mucomplete#enable_auto_at_startup = 1
MUcompleteAutoOn

" source: https://github.com/lifepillar/vim-mucomplete/issues/46
let g:mucomplete#can_complete = {
  \ 'default': {
  \    'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\%(\k\k\|\.\)$' }
  \    }
  \  }

set splitbelow

set noexpandtab

set tabstop=4

let g:go_code_completion_enabled = 1

let g:go_auto_type_info = 1

let g:go_doc_popup_window = 1
</pre></details>

#### Vim version (first three lines from `:version`):

```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 16 2020 10:00:36)
Included patches: 1-391
```

#### Go version (`go version`):

```
$ go version
go version go1.14 linux/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:
</summary><br><pre>

$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jhong/.cache/go-build"
GOENV="/home/jhong/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/REDACTED"
GONOSUMDB="github.com/REDACTED"
GOOS="linux"
GOPATH="/home/jhong/go"
GOPRIVATE="github.com/REDACTED"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build317448105=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

$ gopls version
golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
</pre></details>

**Comment by bhcleek** [comment]
Whether the documentation shows up in the popup is a function of whether it's provided by gopls or not; not all items provided by gopls have that documentation.

The documentation you're seeing at the bottom of your screen is enabled by `g:go_echo_go_info`, which is enabled by default.

**Comment by JoeHFB** [comment]
Ah I see - disabling that got rid of the issue.  I thought that would be printing the func signature like what `GoInfo` does... thanks for the quick help!
