### ISSUE TITLE
It's not time to abandon gocode！

### ISSUE THREAD

**Issue by rocket049** [fatih/vim-go#2783]
Gopls is not good enough!

It's not time to abandon gocode！

For example:

Package 'github.com/therecipe/qt' cannot be processed correctly by gopls.

But gocode worked well before.

**Comment by markkuit** [comment]
It would be of much help if you could provide details on what is not being processed correctly and what you expected instead. Help us help you by following the issue template.

**Comment by rocket049** [comment]
I am using go1.14.1 now, and I used earlier version before.

The package 'github.com/therecipe/qt' is used in gopath mode.

I don't know what the problem is.

I can only describe phenomena.

With gopls, it does not recognize any types or methods of objects in this package.

**Comment by bhcleek** [comment]
FWIW, I clone `github.com/therecipe/qt` into a clean GOPATH and was able to use completion within it without any problems.

@rocket049 gocode is no longer maintained; it _is_ time to drop support for it. If you strongly desire to keep using gocode, then you are free to remain on a version of vim-go that supports it. Any version of vim-go from e2395b7b22c7267eeb73f8973eaeea085870c625 or earlier has support for gocode.

As @markkuit said, you can help us help you by using the issue template. As it stands, there's no indication here exactly what you're doing, what you're expecting to happen, what's actually happening, what the state of your system is, etc. Hence, it's impossible for us to help you without more information. 

I'm closing this. Feel free to open a new issue with the issue template filled out if you believe there is a bug in vim-go or if you need help with something.
