### ISSUE TITLE
folds disappear on :GoImports call

### ISSUE THREAD

**Issue by salarkhan** [fatih/vim-go#2789]
### What did you do? (required: The issue will be **closed** when not provided)
1. installed vim-go
1. set foldmethod config in vimrc
1. set gopls config in vimrc
2. open go file
3. fold things
4. call :GoImports

### What did you expect to happen?
folds are maintained

### What happened instead?
folds disappeared 
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()

set hidden
set foldmethod=syntax
set viewoptions=cursor,folds,slash,unix

let g:go_highlight_extra_types = 1
let g:go_fmt_command = "gopls"
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.12 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/salarkhan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/salarkhan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/salarkhan/code/gitmux/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build167337996=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by bhcleek** [comment]
You can try using `let g:go_fmt_experimental=1` in your vimrc to work around this.

As you noted in #2525, `let g:go_fmt_experimental` isn't perfect and comes with tradeoffs. Unfortunately, you're runnning into a long standing issue with vim-go that's unlikely to be fixed anytime soon.

However, I do intend to add support for using gopls to organize the imports, too. That will likely resolve the issue with folds.

**Comment by bhcleek** [comment]
I nearly have a PR ready for using `gopls` for imports. When it's submitted, would you be willing to test it out?

**Comment by salarkhan** [comment]
Absolutely!

**Comment by bhcleek** [comment]
Thank you :bow:

#2791 is ready to test.

**Comment by salarkhan** [comment]
hm, doesn't seem to work for me using `neovim`  & `vim-plug`:
```
Plug 'bhcleek/vim-go', { 'do': ':GoUpdateBinaries', 'branch': 'lsp/imports' }
```
i'll try again with a minimal .vimrc later today

**Comment by bhcleek** [comment]
@salarkhan fyi, I spelled that option wrong in #2791. #2794 is coming very soon.

**Comment by salarkhan** [comment]
@bhcleek i've noticed that `g:go_imports_mode:gopls` organizes imports, but does not bring in missing ones. calling `:GoImports` manually, however, brings in missing imports. i prefer having folds preserved over auto-imports working, so i can live with it. 

it's likely a `gopls` issue, not a `vim-go` issue, but i figured this would be helpful for you to be aware of this regardless

thanks for all your work in this super niche area!

**Comment by bhcleek** [comment]
@salarkhan let's continue this in a new issue if needed.

But `let g:go_import_mode="gopls"` works to add imports, too; I use it all regularly. Perhaps you really did mean `g:goimports_mode:gopls`, though? If that's the case, then that second `:` should be `=` and the value needs to be quoted.

Thank you for your kind words :bow:

**Comment by salarkhan** [comment]
ah, sorry for typing it incorrectly earlier, it was def set correctly in my vimdc. i'll open a new ticket for this:
```
let g:go_fmt_command = "gopls"
let g:go_imports_mode = "gopls"
```
