### ISSUE TITLE
[Question] Arguments to dlv

### ISSUE THREAD

**Issue by gianarb** [fatih/vim-go#2793]
This is a question / feature request and not a bug.

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
Included patches: 1-343
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.13 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gianarb/.cache/go-build"
GOENV="/home/gianarb/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gianarb/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/gianarb/go/src/github.com/profefe/profefe/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build363943870=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.1.8-0.20200330040139-fa3cc9eebcfe h1:7vbAIOWzasvQtKVhR95bmAEFTV5zmjEtk/0/HoWW0aw=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_test_prepend_name = 1
g:go_rename_command = 'gopls'
g:go_metalinter_autosave_enabled = ['vet']
g:go_metalinter_command = 'gopls'
g:go_def_mode = 'gopls'
g:go_def_mapping_enabled = 0
g:go_diagnostics_enabled = 1
g:go_test_show_name = 1
g:go_metalinter_enabled = 1
g:go_metalinter_autosave = 1
g:go_fmt_command = 'gopls'
g:go_jump_to_error = 1
g:go_omnifunc_enabled = 0
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

Hello!
I am trying to pass arguments to dlv when running `:GoDebugStart` but the behavior I get is not what I expect.

## Run

```
:GoDebugStart -s3.region us-east-1 -s3.bucket bucket -log.level=debug
```

## Expectation 

The debug mode starts and `dlv` has `-s3.region us-east-1 -s3.bucket bucket -log.level=debug` as binary arguments.

## What I get

Very quickly I get those messages but nothing happens. Even when looking for processes: `ps aux | grep tmp` or `ps aux | grep dlv` nothing shows up

```
vim-go: [debug] dispatched
vim-go: [debug] SUCCESS
```

# Test 2

## Run

```
:GoDebugStart -- -s3.region us-east-1 -s3.bucket bucket -log.level=debug
```

**IMPORTANT:** I have added `--` before the arguments

## What I get

```
vim-go: [debug] dispatched
```
This is the last message I get, vim-go does not enter in debug mode and I have a process running this time:

```
/home/gianarb/go/bin/dlv debug -- --output /tmp/vskvEvy/55 --headless --api-version 2 --listen 127.0.0.1:8181 --log --log-output debugger,rpc -- -s3.region us-east-1 -s3.bucket toolsus1.a.influxcloud.net-profefe -log.level=debug
```

**Comment by bhcleek** [comment]
Are you trying to pass arguments to delve or to the application you're debugging?

**Comment by gianarb** [comment]
Hello! The app I am debugging

**Comment by bhcleek** [comment]
To pass arguments to the app, you'll need to explicitly specify the package argument to `:GoDebugStart`. e.g. `:GoDebugStart . -s3.region us-east-1 -s3.bucket bucket -log.level=debug`

**Comment by gianarb** [comment]
Hello @bhcleek !

Thank you for your help! It is working as expected!

have a good weekend
