### ISSUE TITLE
Organizing imports on save with gopls

### ISSUE THREAD

**Issue by orlangure** [fatih/vim-go#2795]
Is it possible to organize imports on save using `go_imports_mode='gopls'`? I currently use the following configuration, which explicitly says that `go_fmt_command` is `goimports`, and it runs on save:

```
  let g:go_fmt_autosave=1
  let g:go_fmt_command='goimports'
  let g:go_imports_mode='gopls'
```

If I change `go_fmt_command` to `gopls`, the code is formatted on save as expected, but the imports are no longer organized. Is there a way to both use `gopls` for `fmt` and `imports`, and run it on save?

I use the recent master, with all binaries updated to their master as well.

Thank you!

**Comment by bhcleek** [comment]
Not yet, but it's coming.

**Comment by bhcleek** [comment]
You can setup an autocmd to do this manually now if you'd like by adding something like this to your `after/ftplugin/go.vim` file (untested):
```
autocmd BufWritePre <buffer> :GoImports
--



flux-kubernetes01.nyc3.internal.digitalocean.com
--

**Comment by orlangure** [comment]
Thanks, I managed to come up with something that seemed to work (I also added `:silent` to the command), but then other weird issues started to appear, like trailing tab on a blank line between stdlib and external imports, or just crazy formatting of my imports.

I'll stick to my previous setup for now, thank you!
