### ISSUE TITLE
GoFmt causes neovim to crash. 

### ISSUE THREAD

**Issue by ryadzenine** [fatih/vim-go#280]
I am not sure the intent is to support neovim this early. However out of curiosity, i used neovim (Head at 91b378d) with vim-go (Head at 7086354). 
Every time, i save a file with auto_fmt or every time i invoke :GoFmt. neovim goes in the background than stops working (like when you hit Ctrl-Z). 
When i disable auto_fmt or avoid using :GoFmt everything works perfectly fine. 
(Note : setting g:go_fmt_command = "goimports" does not change anything)

I am note sure this has anything to do with the plugin itself. Please accept my apologies if this is not relevant here.

**Comment by fatih** [comment]
There was a problem which was causing Vim to crash, but honestly neovim is still in their early stages (and I don't use it) So I can't do anything right now, sorry :/

**Comment by ryadzenine** [comment]
No problem, i am not an active neovim user myself. i just taught that i had to report it. that's how open source works right.
