### ISSUE TITLE
go_gopls_options usage

### ISSUE THREAD

**Issue by nwaywood** [fatih/vim-go#2807]
In [your documentation](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2414) you say:

> 'g:go_gopls_options' can be used to configure
how vim-go starts `gopls` so that the instance can be shared with other
plugins and vim-go user's can leverage the full power of vim-go.

I want to do this since I use coc.nvim. So I looked up the gopls docs to figure out how to do this but their [documentation for command line flags is empty](https://github.com/golang/tools/blob/master/gopls/doc/command-line.md)

I would greatly appreciate it if you could provide an example of how to do this, thanks.

**Comment by bhcleek** [comment]
You can use `gopls -h` at the command line to see the options available.

I use `let g:go_gopls_options = ['-remote=auto']`. You'll have to check with `coc.nvim` to understand how to configure it to also use a shared instance.

https://github.com/golang/go/issues/33030#issuecomment-582063229 documents that there's support for multiple concurrent clients now and links to https://github.com/golang/go/issues/34111 for information about that feature.

**Comment by nwaywood** [comment]
@bhcleek Thanks for the reply.

I assume many people will be in this situation using something like `coc.nvim` for lsp support in other languages. Is this the recommended way to do this? Or is it recommend to just disable `coc.nvim` for golang?

**Comment by bhcleek** [comment]
It's not an either-or situation; do what works for you. Sharing the gopls instance is an efficiency, but not required. coc.nvim and vim-go each use gopls.

**Comment by nwaywood** [comment]
For anyone who comes across this issue. Unfortunately I was not able to get the `-remote=auto` thing to work. So I just disabled `gopls` in `vim-go` and am using `gopls` from `coc.nvim`.

If seems to be working fine, however note that I only really use the language server for go to definition, autocomplete and go to buffer symbol

**Comment by ygworldr** [comment]
@nwaywood [See this issue](https://github.com/josa42/coc-go/issues/76) which might help.

**Comment by nwaywood** [comment]
@ygworldr subscribed to the issue. Thank you :)

**Comment by ygworldr** [comment]
@nwaywood Not sure if it will help but we can but hope. ☺
