### ISSUE TITLE
Alternative to gogetdoc for :GoDoc

### ISSUE THREAD

**Issue by mgartner** [fatih/vim-go#2808]
I'm curious if there are any plans for replacing gogetdoc for the `:GoDoc` command.

Currently, gogetdoc doesn't work well for large projects (and possible projects with cgo). It uses 100% CPU and hangs for minutes or longer. I think this issue is related to https://github.com/Microsoft/vscode-go/issues/1907, https://github.com/zmb3/gogetdoc/issues/47, https://github.com/golang/go/issues/29427.

Could `gopls` be used to provide documentation? Are there any other options?

I was working on a PR to add an option to use `go doc` only, but couldn't think of a consistent way to get the correct package name, so it'd be a lot less accurate than gogetdoc.

**Comment by bhcleek** [comment]
> Could gopls be used to provide documentation?

`gopls` does have some capability to provide documentation, and vim-go does already uses that for hover balloons. It could be extended to also work for `:GoDoc`.

I don't currently have any PRs in progress for that; feel free to submit a PR.

> Are there any other options?

`go doc` is an option, and vim-go already uses that in some cases. With the help of `gopls` it might be possible to get enough information about the position under the cursor to leverage `go doc` for `:GoDoc` without any arguments.

**Comment by bhcleek** [comment]
@mgartner feel free to give #2822  a try
