### ISSUE TITLE
Quickfix window persists/duplicates errors when GoMetalinter runs on save

### ISSUE THREAD

**Issue by tombell** [fatih/vim-go#2809]
### What did you do? (required: The issue will be **closed** when not provided)

Open a file, add an error or two, then save the file, and save multiple times, then remove the errors, and save

### What did you expect to happen?

The errors to be displayed by `typecheck`, but only 1 time, and then to be cleared when the errors are fixed, and the file saved again.

### What happened instead?

The errors kept duplicating in the quickfix window, and persisted even when the errors were fixed.

<img width="931" alt="Screenshot 2020-04-06 at 15 02 04" src="https://user-images.githubusercontent.com/129327/78566760-9ce42600-7817-11ea-9f29-6e67e5d528ee.png">

<img width="931" alt="Screenshot 2020-04-06 at 15 02 10" src="https://user-images.githubusercontent.com/129327/78566767-9d7cbc80-7817-11ea-97de-29e02e2a7600.png">

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary>

```
call plug#begin()
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'fatih/vim-go'
call plug#end()

filetype plugin indent on

syntax on
set background=dark
colorscheme dracula

let g:go_template_autocreate = 0

let g:go_fmt_command = 'goimports'
let g:go_rename_command = 'gopls'

let g:go_highlight_types = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1

let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['typecheck', 'golint']
```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.14.1 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tombell/Library/Caches/go-build"
GOENV="/Users/tombell/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tombell/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tombell/Code/moniker/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/31/yfjsk42x5sb20gm7chy3hmmc0000gn/T/go-build504997319=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_highlight_functions = 1
g:go_highlight_methods = 1
g:go_metalinter_autosave_enabled = ['typecheck', 'golint']
g:go_rename_command = 'gopls'
g:go_metalinter_autosave = 1
g:go_highlight_extra_types = 1
g:go_loaded_gosnippets = 1
g:go_highlight_types = 1
g:go_jump_to_error = 1
g:go_loaded_install = 1
g:go_highlight_operators = 1
g:go_template_autocreate = 0
</pre></details>

**Comment by bhcleek** [comment]
Do you see any errors? What does `:messages` output?

**Comment by bhcleek** [comment]
I can duplicate this. I'll put up a PR soon to fix it.
