### ISSUE TITLE
GoDoc can not found correct package path when package name has extension

### ISSUE THREAD

**Issue by blu3gui7ar** [fatih/vim-go#281]
An example is 

import "gopkg.in/yaml.v2"

A quick fix might be 

diff --git a/autoload/go/tool.vim b/autoload/go/tool.vim
index b7e040b..6195305 100644
--- a/autoload/go/tool.vim
+++ b/autoload/go/tool.vim
@@ -32,7 +32,7 @@ function! go#tool#Imports()
     endif

     for package_path in split(out, '\n')
-        let package_name = fnamemodify(package_path, ":t")
+        let package_name = fnamemodify(package_path, ":t:r")
         let imports[package_name] = package_path
     endfor

**Comment by fatih** [comment]
Can you open a PR with a test file that shows the error and your fixes? We can include and merge it back to the master. Thanks.
