### ISSUE TITLE
Question: Does go-imports affect Vim undo file history?

### ISSUE THREAD

**Issue by stefanos82** [fatih/vim-go#2811]
I have noticed the following behavior: I work on a file that does not yet need any imported package, I save it, and I close my editor to continue with other tasks.

I re-open my previously closed file, I run some new changes in it and now based on my latest modifications, I need to run `go-imports` to do the chore for me.

I run the code, it works.

I realized I had a typo in a `fmt.Printf()` and went to fix it by undoing my latest changes.

Well, it does not undo anymore...seems like `go-imports` first copies my actual buffer somewhere only that knows, it imports the missing package name(s) it needs to do so, and deletes that buffer without passing those changes to my `$HOME/.vim/tmp/`.

Am I doing something wrong?

Please advice.

Thank you.

P.S.: My specs are the following:
```sh
GNU / Linux Debian testing 64-bit, fully updated on a daily basis
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 24 2020 03:21:40)
    Included patches: 1-439
vim-go: fully updated with :PluginUpdate (Vundle) and run :GoUpdateBinaries as well
```

**Comment by bhcleek** [comment]
Yes, vim-go does affect undo history, but tries hard to minimize impact. The exact behavior varies depending on the vim-go options that you have set. However, I'm not aware of anything that would cause undo history to be lost. 

Given the lack of information here with regard to clear replication steps and vim-go settings, I'm going to close this. Feel free to open a new issue with the template filled out if you believe there's a bug in vim-go or need more help.
