### ISSUE TITLE
Possibly a bug with go-imports

### ISSUE THREAD

**Issue by stefanos82** [fatih/vim-go#2812]
### What did you do? (required: The issue will be **closed** when not provided)

I edited a source file, run `go-imports` to insert the necessary package dependencies and vim undo mechanism stopped working.

- Create a new folder, run `vim main.go` to generate a default main file; you should see something like:

```go
package main

import "fmt"

func main() {
    fmt.Println("vim-go")
}
```
- Replace `"vim-go"` with `"Hello Go!"` string, save your changes and close Vim.
- Re-open the file now, press `u` to rollback to original string message; you should see again `"vim-go"`.
- Now add anything that needs to get imported; for example, below `fmt.Println()` add `runtime.GC()`.
- Run the `go-imports`; I have mapped `Ctrl-i` to do so; save changes.

### What did you expect to happen?
When I pressed `u` to undo changes, I expected to rollback to previous version of my file.

### What happened instead?
Nothing at all...

#### vim-go version:
The latest one via `:PluginUpdate` and `:GoUpdateBinaries`

####  `vimrc` you used to reproduce:

```vim
Plugin 'fatih/vim-go'
```

This is what I have for mapping my hotkeys to `go-imports`:
```vim
" For Golang
autocmd FileType go nmap <F5> <Plug>(go-run)
autocmd FileType go nmap <C-i> <Plug>(go-imports)
```

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

```txt
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 24 2020 03:21:40)
Included patches: 1-439
```

#### Go version (`go version`):

```txt
go version go1.14.1 linux/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/stefanos/go/bin"
GOCACHE="/home/stefanos/.cache/go-build"
GOENV="/home/stefanos/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/stefanos/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build329324934=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=
</pre></details>

**Comment by bhcleek** [comment]
> Replace "vim-go" with "Hello Go!" string, save your changes and close Vim.
> * Re-open the file now, press u to rollback to original string message; you should see again "vim-go".
> * Now add anything that needs to get imported; for example, below fmt.Println() add runtime.GC().
> * Run the go-imports; I have mapped Ctrl-i to do so; save changes.

> What did you expect to happen?
> * When I pressed u to undo changes, I expected to rollback to previous version of my file.

**Comment by bhcleek** [comment]
I've tried duplicate what you've described here multiple times; undoing the changes works fine for me.
