### ISSUE TITLE
GoRun erroring out with 'no such file or directory'

### ISSUE THREAD

**Issue by celer** [fatih/vim-go#2813]
### What did you do? (required: The issue will be **closed** when not provided)

I'm using a vagrant environment which reinstalls vim and vim-go each time the environment is built, so it's constantly pulling the latest versions. So I'm literally doing a git clone to install vim-go each time I build the environment. 

Things were working great up until recently. Now when I try to use GoRun I have issues:

:GoRun cmd/watch_stream.go

I now get:

stat cmd/watch_stream.go: no such file or directory

but the file is clearly there:

!stat cmd/watch_stream.go

  File: cmd/watch_stream.go
  Size: 1036      	Blocks: 8          IO Block: 4096   regular file
Device: 30h/48d	Inode: 25971       Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ vagrant)   Gid: ( 1000/ vagrant)
Access: 2020-04-06 19:38:44.000000000 +0000
Modify: 2020-04-06 19:38:42.000000000 +0000
Change: 2020-04-06 19:38:42.000000000 +0000
 Birth: -

and also running it via go works:

!go run cmd/watch_stream.go

Install the latest version of vim-go on linux, with Vim 8.2
Try to use GoRun to execute a program

### What did you expect to happen?

The program should execute

### What happened instead?

Got an error saying 'stat ...: no such file or directory'

### Configuration (**MUST** fill this out):

add-apt-repository ppa:jonathonf/vim
apt-get install -y ssh git screen sudo vim
mkdir -p ~vagrant/.vim/autoload ~vagrant/.vim/bundle && \
curl -LSso ~vagrant/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

git clone https://github.com/fatih/vim-go.git ~vagrant/.vim/bundle/vim-go

cat > ~vagrant/.vimrc << EOF
        execute pathogen#infect()
        syntax on
        filetype plugin indent on
EOF

sudo -u vagrant vim -E -c GoInstallBinaries -c q || true

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 27 2020 12:36:15)
Included patches: 1-460
Modified by jonathon.fernyhough@york.ac.uk

#### Go version (`go version`):

go version go1.13.8 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vagrant/.cache/go-build"
GOENV="/home/vagrant/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vagrant/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build104260089=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
`:GoRun` now executes in the directory that contains the current buffer. You'll need to specify the path to files relative to the current buffer's directory.

**Comment by bhcleek** [comment]
I'm going to put up a PR so that you won't have to use paths relative to the buffer.
