### ISSUE TITLE
GoGuruScope is not working

### ISSUE THREAD

**Issue by thotz** [fatih/vim-go#2816]
## What did you do? (required: The issue will be **closed** when not provided)
Install go plugin for vim and tried to traverse the code via GoCallees, GoCallers.

### What did you expect to happen?
GoCallees should list 
### What happened instead?
vim-go: guru: couldn't load packages due to errors: github.com/rook/rook/vendor/k8s.io/kubernetes/pkg/util/parsers, k8s.io/gengo/generator, k8
s.io/kubernetes/pkg/util/filesystem and 262 more

it took more than a minute as well

i tried a lot of combination with GoGuruScope command as well 
#### vim-go version:
master
####  `vimrc` you used to reproduce:
used the same conf file in this repo
https://github.com/fatih/vim-go-tutorial/blob/master/vimrc
#### Vim version (first three lines from `:version`):

vim-common-8.2.236
#### Go version (`go version`):

go1.13.6
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/go/src/github.com/rook/rook/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build153372366=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=

</pre></details>

**Comment by thotz** [comment]
Pls note GoDef is working as expected

**Comment by bhcleek** [comment]
The error you're seeing is due to `guru`; I don't believe there's anything that vim-go can do to workaround this. You can see this for yourself by executing `let g:go_debug=['shell-commands']` before  running `:GoCallees` or `:GoCallers` and then manually executing the command that's shown at the commandline.
