### ISSUE TITLE
when i add /root/.vimrc, :w gofmt does not work

### ISSUE THREAD

**Issue by guogeer** [fatih/vim-go#2828]
### What did you do? (required: The issue will be **closed** when not provided)
only use git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go,
other way is ok!

### What did you expect to happen?
when is :w save go file, it should format.
### What happened instead?
go file not format, but if i remve /root/.vimrc, it will work.
#### vim-go version:
1.22
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set ts=4
set autoindent
</pre></details>

#### Vim version (first three lines from `:version`):

version 8.0.1453
#### Go version (`go version`):

go version go1.14.2 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/server/src/main/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build883142835=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
Your `/root/.vimrc` does needs `filetype plugin indent on`

**Comment by guogeer** [comment]
emm. it is ok, solve my problem. thank you!
