### ISSUE TITLE
How to customize error highlighting?

### ISSUE THREAD

**Issue by vaniakov** [fatih/vim-go#2829]
Hi, I use neovim and vim-go with conjunction with ale plugin. I customized ale error highlighting but can't customize the one that goes with vim-go. I've read the documentation and troubleshooting section but didn't find the answer there.

Is it possible to edit/disable linter errors highlighting in vim-go?
Example:
while typing:
![зображення](https://user-images.githubusercontent.com/8692788/79350986-cc461180-7f40-11ea-968b-3725b45f13db.png)
after saving or after opening the file:
![зображення](https://user-images.githubusercontent.com/8692788/79351122-f7c8fc00-7f40-11ea-9215-0723ec4640ff.png)

**Comment by bhcleek** [comment]
You're looking for `g:go_highlight_diagnostic_errors` and  `g:go_highlight_diagnostic_warnings`: 
https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2142-L2153

**Comment by vaniakov** [comment]
@bhcleek thank you, It worked. 
Btw why is it prefixed "diagnostic"?

**Comment by bhcleek** [comment]
it's diagnostic, because it they come from the `textDocument/publishDiagnostics` messages from LSP.

**Comment by bhcleek** [comment]
You can customize the highlighting however you'd like by using the usual means to override highlight definitions. You can see the groups that are linked by default in https://github.com/fatih/vim-go/blob/master/syntax/go.vim. If you want to override some, that usual place to do that is in a `after/syntax/go.vim` file.

**Comment by vaniakov** [comment]
I see, `goDiagnosticWarning`.
Thank you.
