### ISSUE TITLE
Issues with Vundle install

### ISSUE THREAD

**Issue by RodneyBrown** [fatih/vim-go#283]
It seems much of vim-go is being loaded after install with Vundle.  For example I can do :help vim-go and it works.

However I have the following problems:

1.  There is no syntax highlighting.  I had this working previously before switching from pathogen to vundle

2.  GoInstallBinaries complains about $GOPATH not being set even though I have it defined in my .bashrc and doing an "echo $GOPATH" in the shell gives:
/home/rbrown/.gotools

**Comment by fatih** [comment]
I think your Vundle setup is broken. Sorry can't do anything here because it's just works. Do you have other Go plugins? If yes please remove them.
