### ISSUE TITLE
vim-go is inserting hard tabs with expandtab in vimrc

### ISSUE THREAD

**Issue by rsanden** [fatih/vim-go#2836]
### What did you do? (required: The issue will be **closed** when not provided)

1. Install vim-go using Vim8 packages
`git clone 'https://github.com/fatih/vim-go' $HOME/.vim/pack/plugins/start/vim-go`

2. Add a plugin file to set some initial settings
```
cat << 'EOF' > $HOME/.vim/plugin/go.vim
let g:go_fmt_autosave = 0
let g:go_imports_autosave = 0
EOF
```
3. Edit a `.go` file. Press tab.

### What did you expect to happen?

I expect vim to insert 4 spaces, since I have `set expandtab` in vimrc.

### What happened instead?

Vim inserts a hard tab character instead.

Note: this seems similar to #1228 , but in that ticket, the reporter wants to use `gofmt`. Of course, you cannot combine spaces and `gofmt`.

**I have disabled gofmt**, and so I expect `expandtab` to function normally.

#### vim-go version:
3c68cba46575b036e0824e4f354b82d0b3d180c8

####  `vimrc` you used to reproduce:
```
set nocompatible
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
filetype plugin on
```

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2020 07:54:11)
Included patches: 1-592
Compiled by me@myserver
```
I tried a few different versions, with the same behavior.

#### Go version (`go version`):
```
go version go1.14.2 linux/amd64
```

#### Go environment
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/me/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/me/goroot/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build473364536=/tmp/go-build -gno-record-gcc-switches"
```

#### gopls version
```
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
```

**Comment by rsanden** [comment]
I think I might be going about this the wrong way.

I have no qualms with putting `setlocal noexpandtab` in `vim-go/ftplugin/go.vim`. It makes sense that the default behavior is the behavior compatible with gofmt.

I'm mostly confused because when I try to override this value by setting `setlocal expandtab` in `~/.vim/plugin/go.vim` or `~/.vim/ftplugin/go.vim`, it doesn't have any effect. Maybe I'm just doing this incorrectly?

**Comment by bhcleek** [comment]
Yes, using the after directory is the way to do this. However, may want to put the vim-go settings in a `after/plugin/vim-go.vim` instead of `after/ftplugin/go.vim` and only leave the `setlocal expandtab` in the `after/ftplugin/go.vim`. 

If you leave the vim-go settings in `after/ftplugin/go.vim`, then you will find any changes to vim-go settings you make after opening a Go buffer (e.g. `:GoFmtAutosaveToggle`  or `let g:go_fmt_command='gopls'`) will be reset to the values in your `after/ftplugin/go.vim` values when you open another Go buffer.

Here are my own after files for your reference:
* https://github.com/bhcleek/vim/blob/master/after/ftplugin/go.vim
* https://github.com/bhcleek/vim/blob/master/after/plugin/vim-go.vim

**Comment by rsanden** [comment]
@bhcleek That's excellent advice - thanks so much!

Thanks also for all of the great work on the vim-go project. It's really appreciated.
