### ISSUE TITLE
GoDoc showing Undocumented for packages

### ISSUE THREAD

**Issue by kmyokoyama** [fatih/vim-go#2838]
### What did you do? (required: The issue will be **closed** when not provided)
Tried to open documentation for packages using both `Shift+k` and `:GoDoc` with cursor over the package name.

Steps:
1. Open a .go file free of syntax errors.
2. Place the cursor over a package identifier such as `fmt` or `log`.
3. Try to open documentation:
3.a. Press `Shift+k`, or
3.b. Enter `:GoDoc` (without any argument).

It is worth noting that entering the full command `:GoDoc fmt` (with package name as argument) works just as expected, and `:GoDocBrowser` (without any argument) also works fine. This leads me to conclude that it should be a genuine feature.

### What did you expect to happen?
A new window presenting the package's documentation:

```
package fmt // import "fmt"

Package fmt implements formatted I/O with functions analogous to C's printf
and scanf. The format 'verbs' are derived from C's but are simpler.
[...]
```

### What happened instead?

A new window is displayed containing the following text (in the case of `fmt`):
```
package fmt

Undocumented
```

#### vim-go version:
As of https://github.com/fatih/vim-go/commit/c9f97c83c282d396387e5c1f01bb61b0f63252b7

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set number

filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set updatetime=100 "Useful for vim-gitgutter sign updates.
nmap <CR> o<Esc>
imap <C-o> <Esc>O
map <C-w><S-g> :tab split<CR>

call plug#begin('~/.vim/plugged')
" Plugins list ommited.
call plug#end()

" General config
set t_Co=256
set background=dark
colorscheme monokain
highlight Normal ctermbg=none
highlight nonText ctermbg=none
syntax on
set backspace=indent,eol,start
autocmd Filetype gitcommit setlocal textwidth=72

" vim-go
let g:go_fmt_command = "goimports" " Run goimports along gofmt on each save.    
let g:go_auto_type_info = 1 " Automatically get signature/type info for object under cursor.

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org

#### Go version (`go version`):

go version go1.14.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kmyokoyama/.cache/go-build"
GOENV="/home/kmyokoyama/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kmyokoyama/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/kmyokoyama/go/src/github.com/kmyokoyama/lets-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build315052305=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
The implementation for getting documentation recently changed. To give you a full answer, I need to know which version of vim-go you're using.

I suspect you're on latest master, though, and that this can be explain by `gopls` not returning the documentation for the package. I've created golang/go#38526.

**Comment by bhcleek** [comment]
If you are on master and you'd like a workaround, you can revert to f935649819b523fdf805c93337771f5c34224c1f.

**Comment by kmyokoyama** [comment]
Hi, @bhcleek. Thank you for the reply.

Yes, I'm indeed on master (on revision https://github.com/fatih/vim-go/commit/c9f97c83c282d396387e5c1f01bb61b0f63252b7, newer than https://github.com/fatih/vim-go/commit/f935649819b523fdf805c93337771f5c34224c1f). Reverting to this previous rev, am I going to lose anything too relevant?

**Comment by bhcleek** [comment]
There are only a few commits in master since then. I don't think there's anything essential that you'll be missing, but only you can determine that for your needs

**Comment by bhcleek** [comment]
This has been fixed upstream in `gopls`. Closing this issue, because the next release of `gopls` will have the fix.
