### ISSUE TITLE
All arguments to `:GoRun` are decorated with paths

### ISSUE THREAD

**Issue by tja** [fatih/vim-go#2841]
### What did you do?

Consider this simple Go program:

```go
package main

import (
    "fmt"
    "os"
)
                        
func main() {
    fmt.Println(os.Args)
}
```

Launching the program via..

```
:GoRun main.go foobar
```

### What did you expect to happen?

That the command line argument `foobar` is passed to the Go program untouched and the output would be:

```
[/var/folders/c3/m34lcjs11pjg6s4c58pxkxsr0000gn/T/go-build641210589/b001/exe/main foobar]
```

This is what happened until recently.

### What happened instead?

The argument `foobar` is decorated with a path and the output becomes:

```
[/var/folders/c3/m34lcjs11pjg6s4c58pxkxsr0000gn/T/go-build641210589/b001/exe/main /Users/thomas/Development/sources/foobar]
```

#### vim-go version:

`vim-go` is installed via Vundle. The latest commit is 07869cdfb066dcb287673eee3effb30021a970b8.

#### Vim version

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 14:47:07)
macOS version
Included patches: 1-500
```

#### Go version (`go version`):

```
go version go1.14.1 darwin/amd64
```

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_highlight_function_calls = 1
g:go_highlight_fields = 1
g:go_highlight_variable_declarations = 1
g:go_highlight_variable_assignments = 1
g:go_highlight_function_arguments = 1
g:go_highlight_structs = 1
g:go_disable_autoinstall = 0
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_highlight_methods = 1
g:go_loaded_gosnippets = 1
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by tja** [comment]
It seems that passing command line arguments to `:GoRun` was working by accident. Looking through other issues I realize that `:GoRun` does expect all parameters to be files. However, it was always working for me until commit: fd75f3b2aceac85b79c211a38ee2467a070d0d53.

**Comment by bhcleek** [comment]
You raise a good point. I'll give some thought to finding a solution to #2813 and #2770 while preserving the ability to specify non-file arguments to `go run`.

**Comment by tja** [comment]
Thanks a bunch!
