### ISSUE TITLE
GoDocBrowser error

### ISSUE THREAD

**Issue by sding3** [fatih/vim-go#2845]
### What did you do? (required: The issue will be **closed** when not provided)

GoDocBrowser while the cursor is on `fmt.Println`

### What did you expect to happen?

Expect go doc to show up in the browser

### What happened instead?

Got following errors:

```
Error detected while processing function go#doc#OpenBrowser[2]..go#lsp#DocLink[13]..<SNR>54_await[3]..4[13]..6[26
]..<SNR>54_wrapper[1]..<SNR>45_docLinkFromHoverResult:
line   10:
E716: Key not present in Dictionary: link, '']
Error detected while processing function go#doc#OpenBrowser[2]..go#lsp#DocLink[13]..<SNR>54_await[3]..4:
line   13:
E171: Missing :endif
Error detected while processing function go#doc#OpenBrowser[2]..go#lsp#DocLink[13]..<SNR>54_await:
line    3:
E170: Missing :endwhile
Error detected while processing function go#doc#OpenBrowser:
line    2:
E171: Missing :endif
Press ENTER or type command to continue
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
Included patches: 1-343
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.14 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shang/.cache/go-build"
GOENV="/home/shang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build248733480=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Do you see this problem with the latest gopls? You can run `:GoUpdateBinaries gopls` to get the latest.

**Comment by sding3** [comment]
That fixed it. Thanks!
