### ISSUE TITLE
Is there a command to automatically import the package name

### ISSUE THREAD

**Issue by guonaihong** [fatih/vim-go#2849]
### What did you do? (required: The issue will be **closed** when not provided)
:GoImport

### What did you expect to happen?
For example, I write gin.New () in the code
A line will be added after import
"github.com/gin-gonic/gin"

### What happened instead?
No automatic package name import
#### vim-go version:
```
8.0.1453
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2017 Sep 20
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  augroup END

else

  set autoindent		" always set autoindenting on

endif " has("autocmd")

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

execute pathogen#infect()

set nu
set ts=4
set sw=4
set expandtab
set tags=tags;

call plug#begin('~/.vim/plugged')

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'tag': '*' }

call plug#end()

</pre></details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
go version go1.13.1 linux/amd64
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
You're looking for `:GoImports`, not `:GoImport`. See the help for those two commands for more information.

Also, you may considering reading the help for `g:go_fmt_command`, `g:go_imports_mode`, `g:go_imports_autosave`, and `g:go_fmt_autosave`.

**Comment by guonaihong** [comment]
@bhcleek thank you
