### ISSUE TITLE
Cannot install godef

### ISSUE THREAD

**Issue by campadrenalin** [fatih/vim-go#285]
This isn't your responsibility at all, but I suspect it's the underlying reason why I'm not able to access commands like :GoLint (it's detecting not all binaries are installed), so I'll complain here and hopefully such a complaint will get forwarded to the responsible parties.

Godef will not install for me on Debian Wheezy. It depends on something that either does not exist, or has been moved.

```
user@host:~/.vim/bundle/vim-go$ go get -v code.google.com/p/rog-go/exp/cmd/godef
code.google.com/p/goplan9 (download)
package code.google.com/p/goplan9/plan9/acme
	imports code.google.com/p/goplan9/plan9/acme
	imports code.google.com/p/goplan9/plan9/acme: cannot find package "code.google.com/p/goplan9/plan9/acme" in any of:
	/usr/local/go/src/code.google.com/p/goplan9/plan9/acme (from $GOROOT)
	/home/user/go/src/code.google.com/p/goplan9/plan9/acme (from $GOPATH)
```

While I don't want to pass undue stress on to others, I've had a long day that was mostly wasted dealing with a hard disk failure while updating my kernel and openvpn packages. I really want something to just work as intended. Anything.

**Comment by tmkbry** [comment]
Issue filled here:
https://code.google.com/p/rog-go/issues/detail?id=12

Temporary solution: 
https://stackoverflow.com/questions/27860178/how-to-rebuild-godef-to-work-with-go-1-4

**Comment by fatih** [comment]
Thanks for the report. Rog fixed it and it's available upstream:

https://code.google.com/p/rog-go/source/detail?r=7088342b70fc1995ada4986ef2d093f340439c78
