### ISSUE TITLE
GoDef mappings not being disabled

### ISSUE THREAD

**Issue by nickcorin** [fatih/vim-go#2850]
### What did you expect to happen?
After setting `let g:go_def_mapping_enabled = 0`,  the default mappings for `:GoDef` should not be present.

### What happened instead?
`<Esc>` is still mapped to `:GoDefPop`.

#### vim-go version:
I'm not sure if `vim-go` has a version number, but this is the commit I'm on: `16f5cdc0ccd58c736613633ea3b80ad313e49601`

####  `vimrc` you used to reproduce:

```
let g:go_fmt_command='goimports'
let g:go_autodetect_gopath = 1
let g:go_def_mapping_enabled = 0

augroup go_bindings
	autocmd! go_bindings

	autocmd BufNewFile,BufRead *.go setlocal expandtab
	autocmd BufNewFile,BufRead *.go setlocal shiftwidth=4
	autocmd BufNewFile,BufRead *.go setlocal tabstop=4

	autocmd BufNewFile,BufRead *.go nnoremap <buffer> <C-d> :GoDoc<CR>
	autocmd BufNewFile,BufRead *.go nmap <buffer> <C-d> <esc>:GoDoc<CR>

	autocmd BufNewFile,BufRead *.go nnoremap <buffer> <C-]> :GoDef<CR>
	autocmd BufNewFile,BufRead *.go nnoremap <buffer> <C-[> :GoDefPop<CR>

	autocmd BufNewFile,BufRead *.go inoremap <buffer> <leader>f :GoFmt<CR>
	autocmd BufNewFile,BufRead *.go nnoremap <buffer> <leader>v :GoVet<CR>

	autocmd BufNewFile,BufRead *.go nnoremap <buffer> <leader>t :GoAlternate<CR>
	autocmd BufNewFile,BufRead *.go nnoremap <buffer> <leader>r :GoReferrers<CR>
	autocmd BufNewFile,BufRead *.go nnoremap <buffer> <leader>d :GoDecls<CR>
	autocmd BufNewFile,BufRead *.go nnoremap <buffer> <leader>D :GoDeclsDir<CR>
augroup end

```

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):
`
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
`
#### Go version (`go version`):

1.14.1

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

`16f5cdc0ccd58c736613633ea3b80ad313e49601:version
NVIM v0.4.3
Build type: Release
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nicholas/Library/Caches/go-build"
GOENV="/Users/nicholas/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nicholas/go"
GOPRIVATE=""
GOPROXY="http://gomodsproxy.prod.luno.com:8731"
GOROOT="/usr/local/Cellar/go/1.14.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h8/ky573xzs3k71792pxnpxkqth0000gp/T/go-build104274250=/tmp/go-build -gno-record-gcc-switches -fno-common"
`
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=`
</pre></details>

**Comment by bhcleek** [comment]
I don't see any place in vim-go where `<Esc>` is mapped to `:GoDefPop`.

**Comment by nickcorin** [comment]
Hm.. Strange.

I can see explicitly when I run `:nmap`, that `Esc` is bound to it.

First 3 lines of `:nmap`.

```
n  <C-D>        @:GoDoc<CR>
n  <Esc>       *@:GoDefPop<CR>
n  <C-]>       *@:GoDef<CR>
```

I'm happy to post the rest of my `init.vim`, although I pasted the entirety of where I map anything for Go files.

I'll keep digging a bit.

**Comment by nickcorin** [comment]
By means of commenting out lines of code in my `init.vim`, it seems like this is the culprit (unsurprisingly):

`autocmd BufNewFile,BufRead *.go nnoremap <buffer> <C-[> :GoDefPop<CR>`

Perhaps it's something with my terminal that's misinterpreting the `[` character.

**Comment by nickcorin** [comment]
This seems like a potential issue or strange configuration with `kitty` rather than `vim-go`.

**Comment by nickcorin** [comment]
For anyone that runs into the same problem. It seems like this isn't an issue with `vim-go`, `vim`, nor `kitty`.

As it turns out `<Ctrl>-[` is actually the raw escape code for `<Esc>`. This means that when you type `<Esc>` and `<Ctrl>-[` the same escape sequences are generated. Your terminal can't distinguish the difference.

I'm still trying to find a way to get around it for the case of using `<Ctrl>-[` for `:GoDefPop`.
