### ISSUE TITLE
Guru doesn't work or works slow

### ISSUE THREAD

**Issue by sergii4** [fatih/vim-go#2851]
### What did you do? (required: The issue will be **closed** when not provided)
Call `:GoCallers`, `GoImplements`

### What did you expect to happen?
Works as described in [tutorial](https://github.com/fatih/vim-go/wiki/Tutorial#guru)
### What happened instead?
<details><summary><code>`:GoCallers`:</code> Output:</summary><br><pre>
vim-go: [callers] FAIL
vim-go: /Users/sergiigetman/go/pkg/mod/github.com/privateRepo/utils-go@v0.0.0-20191011131324-aa3129ce7d25/log/log.go:9:2: c
ould not import github.com/airbrake/gobrake (cannot find packag
e "github.com/airbrake/gobrake" in any of:
vim-go:         /usr/local/go/src/github.com/airbrake/gobrake (
from $GOROOT)
vim-go:         /Users/sergiigetman/go/src/github.com/airbrake/
gobrake (from $GOPATH))
vim-go: /Users/sergiigetman/go/pkg/mod/github.com/!edison!junio
r/utils-go@v0.0.0-20191011131324-aa3129ce7d25/log/log.go:10:2:
could not import github.com/go-stack/stack (cannot find package
 "github.com/go-stack/stack" in any of:
vim-go:         /usr/local/go/src/github.com/go-stack/stack (fr
om $GOROOT)
vim-go:         /Users/sergiigetman/go/src/github.com/go-stack/
stack (from $GOPATH))
vim-go: /Users/sergiigetman/go/pkg/mod/google.golang.org/grpc@v
1.28.0/status/status.go:35:2: could not import github.com/golan
g/protobuf/proto (go/build: importGo github.com/golang/protobuf
/proto: exit status 1
vim-go: error writing go.mod: open /Users/sergiigetman/go/pkg/m
od/google.golang.org/grpc@v1.28.0/go.mod416608871.tmp: permissi
on denied
vim-go:
vim-go: )
vim-go: /Users/sergiigetman/go/pkg/mod/google.golang.org/grpc@v
1.28.0/status/status.go:38:2: could not import google.golang.or
g/grpc/codes (go/build: importGo google.golang.org/grpc/codes:
exit status 1
vim-go: error writing go.mod: open /Users/sergiigetman/go/pkg/m
od/google.golang.org/grpc@v1.28.0/go.mod968195252.tmp: permissi
on denied
vim-go:
vim-go: )
vim-go: /Users/sergiigetman/go/pkg/mod/google.golang.org/grpc@v
1.28.0/status/status.go:39:2: could not import google.golang.or
g/grpc/internal (go/build: importGo google.golang.org/grpc/inte
rnal: exit status 1
</pre></details>

`:GoImplements` takes long time

#### vim-go version:
v1.22-242-gd71ad2d
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
filetype plugin indent on
syntax on
packloadall
silent! helptags ALL
set shortmess=a
set cmdheight=2

" VIM GO:

map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>c :cclose<CR>
map <C-k> :.w !pbcopy<CR><CR>
map <C-p> :r !pbpaste<CR>

" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go nmap <leader>r  <Plug>(go-run)
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
autocmd FileType go nmap <leader>t  <Plug>(go-test)

autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')

autocmd FileType go nmap <leader>i <Plug>(go-info)

"let g:go_bin_path = "/usr/local/bin/go"
"let $GOPATH = $HOME."/go"

let g:go_fmt_command = "goimports"
let mapleader = ","
let g:go_highlight_types = 1

let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']
let g:go_list_type = "quickfix"
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_rename_command = 'gopls'
"let g:go_auto_sameids = 1
let g:go_textobj_include_function_doc = 1

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
#### Go version (`go version`):

go version go1.12 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/Users/sergiigetman/go/bin"
GOCACHE="/Users/sergiigetman/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sergiigetman/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vj/jqm1qtdj5718h0lx8z0c7qn00000gn/T/go-build80880
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
</pre></details>

**Comment by sergii4** [comment]
I have found related issue that just closed:
https://github.com/fatih/vim-go/issues/2443

> :GoCallers uses guru, which is not module aware. If you're in module aware mode (e.g not in $GOPATH/src, then :GoCallers won't work.

If guru `:GoCallers` doesn't work with modules shouldn't it be reflected in tutorial?
What is possible workaround?

**Comment by bhcleek** [comment]
This is a known issue with guru. I don't have time to update the tuturial as often as I'd like.

There isn't a good workaround for `:GoCallers` use of `guru` yet.

**Comment by bhcleek** [comment]
FWIW, I'll probably merge https://github.com/fatih/vim-go/pull/2704 soon.
