### ISSUE TITLE
:GoRename doesn't work with example from tutorial

### ISSUE THREAD

**Issue by strogiyotec** [fatih/vim-go#2857]
Good day, I was following the Tutorial from wiki page and faced a problem that `:GoRaname` didn't work. I am using the last version of vim-go. I found this issue 
https://github.com/fatih/vim-go/issues/2691
It says that in order to fix it I should add the following line to my vim config
```
let g:go_rename_command = 'gopls' 
```
Now it works. I'm not quite sure if it is a permanent solution for everyone who has the latest version of vim-go if so maybe we should add this hint to Tutorial page ? I can create pull request for it

**Comment by bhcleek** [comment]
That will become the default soon. However, using `gopls` for renaming is only required in module mode. `:GoRename` should work with `gorename` just fine in GOPATH mode.

**Comment by strogiyotec** [comment]
Thank you , is it ok If I add this info into Tutorial page ?

**Comment by bhcleek** [comment]
yes

**Comment by bhcleek** [comment]
I've updated the tutorial
