### ISSUE TITLE
vim-go: no views in the session

### ISSUE THREAD

**Issue by manjitsinghm** [fatih/vim-go#2860]
### What did you do? (required: The issue will be **closed** when not provided)
I have installed and configure vim-go. 

Goimport and other tools works find but GoDef is not working for me. When i give the command :GoDef I get the message "vim-go: no views in the session". 

### What did you expect to happen?
I expected GoDef to take me to the file having a function definition.

### What happened instead?
Instead I got the error "vim-go: no views in the session

### Configuration (**MUST** fill this out):
windows system. I am using console emulator for Linux terminals on windows.

#### vim-go version:
https://tpo.pe/pathogen.vim

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb  7 2019 12:09:30)
Included patches: 1-877
Compiled by <alexpux@gmail.com>

#### Go version (`go version`):

go version go1.14.2 windows/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

set GO111MODULE=
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOCACHE=C:\Users\mmatharu\AppData\Local\go-build
set GOENV=C:\Users\mmatharu\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:/timezone/go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\mmatharu\AppData\Local\Temp\go-build108059058=/tmp/go-build -gno-record-gcc-switches

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_highlight_methods = 1
g:go_highlight_structs = 1
g:go_loaded_gosnippets = 1
g:go_highlight_functions = 1
g:go_highlight_operators = 1
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Can you duplicate this with a very simple package that only imports packages from the standard library? Does it matter if you're in GOPATH more or module aware mode? Which mode are you in when you see this error?

As a workaround, you might consider adding `let g:go_def_mode='godef'` to your vimrc, but that may not be sufficient, because you may get this same error from other commands that rely on `gopls`.

**Comment by manjitsinghm** [comment]
I see the issue when I am in GOPATH mode i tried setting G0111MODULE=ON but there was no difference. I didn't understood the way u asked me to duplicate.

I tried the workaround u suggested i.e.  I set g:go_def_mode='godef' in my .vimrc and following is my observation - 
1) when i look for definition of my packages by running :GoDef it jumps to a new file ""D" [New File]"

Should i try downgrading the golang version currently i am using the most recent version

**Comment by bhcleek** [comment]
I don't think the problem has anything to do with the version of Go.

I noticed that your GOPATH uses forward slashes instead of backslashes: that may be the source of your problem.

**Comment by manjitsinghm** [comment]
I tried changing my GOPATH as follows - 
i) export GOPATH="\d\timezone\go" I got the error "vim-go: could not determine appropriate working directory for gopls"
ii) export GOPATH="D:\timezone\go" I got the same error as original "vim-go: no views in the session"

**Comment by bhcleek** [comment]
Thanks. I think it's time to get a debugging log from gopls then. Can you add `let g:go_debug=["lsp"]` to your vimrc and try again? After the `vim-go: no views in the session` message appears, Can you copy the full LSP log and provide it here?

**Comment by manjitsinghm** [comment]
Please find the error logs of lsp -

===== sent =====
Content-Length: 579

{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///d/timezone/go/src/ecp_service","capabilities":{"workspace":{"workspaceFolders":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true}},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["source.organizeImports"]}}},"completion":{"completionItem":{"snippetSupport":false}},"hover":{"contentFormat":["plaintext"]}}},"processId":21580,"workspaceFolders":[{"uri":"file:///d/timezone/go/src/ecp_service","name":"/d/timezone/go/src/ecp_service"}]}}
===== received =====
Content-Length: 950

{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","source.fixAll","source.organizeImports"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["tidy","upgrade.dependency","generate"]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":""}},"id":1}
===== sent =====
Content-Length: 52

{"method":"initialized","jsonrpc":"2.0","params":{}}
===== sent =====
Content-Length: 4924

{"method":"textDocument/didOpen","jsonrpc":"2.0","params":{"textDocument":{"uri":"file:///d/timezone/go/src/ecp_service/main.go","version":1,"languageId":"go","text":"// Schemes: https, http\r\n// BasePath: /v1.0/\r\n// Version: 0.0.1\r\n// Host:127.0.0.1:9000\r\n// Consumes:\r\n//   - application/json\r\n// Produces:\r\n//   - application/json\r\n// Security:\r\n//   - bearer: []\r\n// SecurityDefinitions:\r\n//  bearer:\r\n//       type: apiKey\r\n//       name: Authorization\r\n//       in: header\r\n// swagger:meta\r\npackage main\r\n\r\nimport (\r\n\t\"ecp_service/config\"\r\n\t\"ecp_service/datastorage\"\r\n\t\"ecp_service/handler\"\r\n\t\"ecp_service/logger\"\r\n\t\"net/http\"\r\n)\r\n\r\n// Responsible to initiate the web server\r\nfunc main() {\r\n\tvar configData config.Config\r\n\tconfigData, err := config.LoadConfiguration(\"config/config.json\")\r\n\tPasswordError := config.LoadPasswdFile(\"config/passwd.json\")\r\n\t_, err = config.LoadConfigEndPoints(\"config/endpointmapping.json\")\r\n\r\n\t// Initialize Redis\r\n\tdatastorage.RedisInit()\r\n\tpong, err := datastorage.RedisClient.Ping().Result()\r\n\tlogger.Log.Print(pong, err)\r\n\tif err != nil {\r\n\t\tlogger.Log.Fatal(\"Error \", err)\r\n\t}\r\n\r\n\t//Initialize the controller access api\r\n\tdatastorage.InitControllerAccess()\r\n\r\n\tif PasswordError != nil {\r\n\t\tlogger.Log.Fatal(\"Error \", PasswordError)\r\n\t}\r\n\r\n\tvar logpath = configData.WebServer.LogPath\r\n\tlogger.InitLogger(logpath)\r\n\r\n\tif err != nil {\r\n\t\tlogger.Log.Fatal(\"Error \", err)\r\n\t}\r\n\r\n\tport := configData.WebServer.Port\r\n\t// Database connection for MySQL\r\n\tif err = datastorage.DBConn(); err != nil {\r\n\t\tlogger.Log.Fatal(\"Failed to start Webserver due to database issue -\", err)\r\n\t}\r\n\t// Database connection for MSSQL\r\n\tif err = datastorage.DBMSSqlConn(); err != nil {\r\n\t\tlogger.Log.Error(\"Failed to opem MSSQL database. -\", err)\r\n\t}\r\n\r\n\t//the Group\r\n\thttp.HandleFunc(\"/v1.0/groups/\", handler.AuthenticationMiddleware(handler.ReceiveGroups))\r\n\t//WorldTimeZones\r\n\thttp.HandleFunc(\"/v1.0/time-zones/\", handler.AuthenticationMiddleware(handler.TimeZones))\r\n\t//the User\r\n\thttp.HandleFunc(\"/v1.0/users/\", handler.AuthenticationMiddleware(handler.ReceiveUsers))\r\n\t//Locations\r\n\thttp.HandleFunc(\"/v1.0/locations/\", handler.AuthenticationMiddleware(handler.ReceiveLocations))\r\n\t//Countries\r\n\thttp.HandleFunc(\"/v1.0/countries/\", handler.AuthenticationMiddleware(handler.ReceiveCountries))\r\n\t//Countries\r\n\thttp.HandleFunc(\"/v2.0/countries/\", handler.AuthenticationMiddleware(handler.ReceiveCountries))\r\n\t//Clients\r\n\thttp.HandleFunc(\"/v1.0/clients/\", handler.AuthenticationMiddleware(handler.ReceiveClients))\r\n\t//Watchlist\r\n\thttp.HandleFunc(\"/v1.0/watchlist/\", handler.AuthenticationMiddleware(handler.ReceiveWatchlist))\r\n\t//UserLogin\r\n\thttp.HandleFunc(\"/v1.0/login/\", handler.UserLogin)\r\n\t//download\r\n\thttp.HandleFunc(\"/v1.0/download/\", handler.AuthenticationMiddleware(handler.ReceiveDownload))\r\n\t//QuickConnect\r\n\thttp.HandleFunc(\"/v1.0/quickconnects/\", handler.AuthenticationMiddleware(handler.ReceiveQuickConnect))\r\n\t//profilePhoto\r\n\thttp.HandleFunc(\"/v1.0/profileimage/\", handler.AuthenticationMiddleware(handler.ReceiveProfileImage))\r\n\t//Notes\r\n\thttp.HandleFunc(\"/v1.0/notes/\", handler.AuthenticationMiddleware(handler.ReceiveNotes))\r\n\t//Authenticate Controller\r\n\thttp.HandleFunc(\"/v1.0/controller/authentication/\", handler.AuthenticationMiddleware(handler.ControllerInfo))\r\n\t//API Key\r\n\thttp.HandleFunc(\"/v1.0/apikey/\", handler.ApiKey)\r\n\t//DeviceDiscovery\r\n\thttp.HandleFunc(\"/v1.0/devicediscovery/\", handler.ReceiveDeviceDiscovery)\r\n\t//Mute Location\r\n\thttp.HandleFunc(\"/v1.0/mutes/\", handler.AuthenticationMiddleware(handler.ReceiveMute))\r\n\t//Alert Modes - Chennal\r\n\thttp.HandleFunc(\"/v1.0/alert-channels/\", handler.AuthenticationMiddleware(handler.AlertChannels))\r\n\t//System Alerts\r\n\thttp.HandleFunc(\"/v1.0/alerts/\", handler.AuthenticationMiddleware(handler.SystemAlerts))\r\n\t//Search\r\n\thttp.HandleFunc(\"/v1.0/search/\", handler.AuthenticationMiddleware(handler.ReceiveSearch))\r\n\t//HelpSupport\r\n\thttp.HandleFunc(\"/v1.0/helpsupport/\", handler.AuthenticationMiddleware(handler.HelpSupport))\r\n\t//default page count\r\n\thttp.HandleFunc(\"/v1.0/userpreference/\", handler.AuthenticationMiddleware(handler.ReceiveUserPreference))\r\n\r\n\t//default page count for backward compatiblity which should depricated with next FORCE UPGRADE release. JIRA - CC001-2515\r\n\thttp.HandleFunc(\"/v1.0/defaultsize/\", handler.AuthenticationMiddleware(handler.ReceiveUserPreference))\r\n\r\n\tlogger.Log.Fatal(http.ListenAndServeTLS(\":\"+port, configData.SSLCertificate.CertificatePath, configData.SSLCertificate.CertificateKeyPath, nil))\r\n}\r\n"}}}
===== stderr =====
2020/04/27 23:24:56 debug server listening on port 60277
===== received =====
Content-Length: 268

{"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeConfiguration","method":"workspace/didChangeConfiguration"},{"id":"workspace/didChangeWorkspaceFolders","method":"workspace/didChangeWorkspaceFolders"}]},"id":1}
===== sent =====
Content-Length: 38

{"id":1,"jsonrpc":"2.0","result":null}
===== received =====
Content-Length: 253

{"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///d/timezone/go/src/ecp_service","section":"gopls"},{"scopeUri":"file:///d/timezone/go/src/ecp_service","section":"gopls-/d/timezone/go/src/ecp_service"}]},"id":2}
===== received =====
Content-Length: 1034

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/04/27 23:25:01 Build info\n----------\ngolang.org/x/tools/gopls 0.4.0\n    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=\n    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\n    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\n    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=\n    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=\n    golang.org/x/tools@v0.0.0-20200407041343-bf15fae40dea h1:DUwLyMDMUauGMd9kSLIlhhYJNELm06HuxeBdkFkeax4=\n    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=\n    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=\n    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=\n\nGo info\n-------\ngo version go1.14.2 windows/amd64\n\n"}}
===== sent =====
Content-Length: 121

{"id":2,"jsonrpc":"2.0","result":[{"buildFlags":[],"hoverKind":"Structured"},{"buildFlags":[],"hoverKind":"Structured"}]}
===== received =====
Content-Length: 273

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"Error loading workspace folders (expected 1, got 0)\nfailed to load view for file:///d/timezone/go/src/ecp_service: invalid workspace configuration: The system cannot find the path specified.\n"}}
===== sent =====
Content-Length: 4929

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"// Schemes: https, http\r\n// BasePath: /v1.0/\r\n// Version: 0.0.1\r\n// Host:127.0.0.1:9000\r\n// Consumes:\r\n//   - application/json\r\n// Produces:\r\n//   - application/json\r\n// Security:\r\n//   - bearer: []\r\n// SecurityDefinitions:\r\n//  bearer:\r\n//       type: apiKey\r\n//       name: Authorization\r\n//       in: header\r\n// swagger:meta\r\npackage main\r\n\r\nimport (\r\n\t\"ecp_service/config\"\r\n\t\"ecp_service/datastorage\"\r\n\t\"ecp_service/handler\"\r\n\t\"ecp_service/logger\"\r\n\t\"net/http\"\r\n)\r\n\r\n// Responsible to initiate the web server\r\nfunc main() {\r\n\tvar configData config.Config\r\n\tconfigData, err := config.LoadConfiguration(\"config/config.json\")\r\n\tPasswordError := config.LoadPasswdFile(\"config/passwd.json\")\r\n\t_, err = config.LoadConfigEndPoints(\"config/endpointmapping.json\")\r\n\r\n\t// Initialize Redis\r\n\tdatastorage.RedisInit()\r\n\tpong, err := datastorage.RedisClient.Ping().Result()\r\n\tlogger.Log.Print(pong, err)\r\n\tif err != nil {\r\n\t\tlogger.Log.Fatal(\"Error \", err)\r\n\t}\r\n\r\n\t//Initialize the controller access api\r\n\tdatastorage.InitControllerAccess()\r\n\r\n\tif PasswordError != nil {\r\n\t\tlogger.Log.Fatal(\"Error \", PasswordError)\r\n\t}\r\n\r\n\tvar logpath = configData.WebServer.LogPath\r\n\tlogger.InitLogger(logpath)\r\n\r\n\tif err != nil {\r\n\t\tlogger.Log.Fatal(\"Error \", err)\r\n\t}\r\n\r\n\tport := configData.WebServer.Port\r\n\t// Database connection for MySQL\r\n\tif err = datastorage.DBConn(); err != nil {\r\n\t\tlogger.Log.Fatal(\"Failed to start Webserver due to database issue -\", err)\r\n\t}\r\n\t// Database connection for MSSQL\r\n\tif err = datastorage.DBMSSqlConn(); err != nil {\r\n\t\tlogger.Log.Error(\"Failed to opem MSSQL database. -\", err)\r\n\t}\r\n\r\n\t//the Group\r\n\thttp.HandleFunc(\"/v1.0/groups/\", handler.AuthenticationMiddleware(handler.ReceiveGroups))\r\n\t//WorldTimeZones\r\n\thttp.HandleFunc(\"/v1.0/time-zones/\", handler.AuthenticationMiddleware(handler.TimeZones))\r\n\t//the User\r\n\thttp.HandleFunc(\"/v1.0/users/\", handler.AuthenticationMiddleware(handler.ReceiveUsers))\r\n\t//Locations\r\n\thttp.HandleFunc(\"/v1.0/locations/\", handler.AuthenticationMiddleware(handler.ReceiveLocations))\r\n\t//Countries\r\n\thttp.HandleFunc(\"/v1.0/countries/\", handler.AuthenticationMiddleware(handler.ReceiveCountries))\r\n\t//Countries\r\n\thttp.HandleFunc(\"/v2.0/countries/\", handler.AuthenticationMiddleware(handler.ReceiveCountries))\r\n\t//Clients\r\n\thttp.HandleFunc(\"/v1.0/clients/\", handler.AuthenticationMiddleware(handler.ReceiveClients))\r\n\t//Watchlist\r\n\thttp.HandleFunc(\"/v1.0/watchlist/\", handler.AuthenticationMiddleware(handler.ReceiveWatchlist))\r\n\t//UserLogin\r\n\thttp.HandleFunc(\"/v1.0/login/\", handler.UserLogin)\r\n\t//download\r\n\thttp.HandleFunc(\"/v1.0/download/\", handler.AuthenticationMiddleware(handler.ReceiveDownload))\r\n\t//QuickConnect\r\n\thttp.HandleFunc(\"/v1.0/quickconnects/\", handler.AuthenticationMiddleware(handler.ReceiveQuickConnect))\r\n\t//profilePhoto\r\n\thttp.HandleFunc(\"/v1.0/profileimage/\", handler.AuthenticationMiddleware(handler.ReceiveProfileImage))\r\n\t//Notes\r\n\thttp.HandleFunc(\"/v1.0/notes/\", handler.AuthenticationMiddleware(handler.ReceiveNotes))\r\n\t//Authenticate Controller\r\n\thttp.HandleFunc(\"/v1.0/controller/authentication/\", handler.AuthenticationMiddleware(handler.ControllerInfo))\r\n\t//API Key\r\n\thttp.HandleFunc(\"/v1.0/apikey/\", handler.ApiKey)\r\n\t//DeviceDiscovery\r\n\thttp.HandleFunc(\"/v1.0/devicediscovery/\", handler.ReceiveDeviceDiscovery)\r\n\t//Mute Location\r\n\thttp.HandleFunc(\"/v1.0/mutes/\", handler.AuthenticationMiddleware(handler.ReceiveMute))\r\n\t//Alert Modes - Chennal\r\n\thttp.HandleFunc(\"/v1.0/alert-channels/\", handler.AuthenticationMiddleware(handler.AlertChannels))\r\n\t//System Alerts\r\n\thttp.HandleFunc(\"/v1.0/alerts/\", handler.AuthenticationMiddleware(handler.SystemAlerts))\r\n\t//Search\r\n\thttp.HandleFunc(\"/v1.0/search/\", handler.AuthenticationMiddleware(handler.ReceiveSearch))\r\n\t//HelpSupport\r\n\thttp.HandleFunc(\"/v1.0/helpsupport/\", handler.AuthenticationMiddleware(handler.HelpSupport))\r\n\t//default page count\r\n\thttp.HandleFunc(\"/v1.0/userpreference/\", handler.AuthenticationMiddleware(handler.ReceiveUserPreference))\r\n\r\n\t//default page count for backward compatiblity which should depricated with next FORCE UPGRADE release. JIRA - CC001-2515\r\n\thttp.HandleFunc(\"/v1.0/defaultsize/\", handler.AuthenticationMiddleware(handler.ReceiveUserPreference))\r\n\r\n\tlogger.Log.Fatal(http.ListenAndServeTLS(\":\"+port, configData.SSLCertificate.CertificatePath, configData.SSLCertificate.CertificateKeyPath, nil))\r\n}\r\n"}],"textDocument":{"uri":"file:///d/timezone/go/src/ecp_service/main.go","version":2}}}
===== sent =====
Content-Length: 179

{"method":"textDocument/definition","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///d/timezone/go/src/ecp_service/main.go"},"position":{"character":43,"line":82}}}
===== received =====
Content-Length: 91

{"jsonrpc":"2.0","error":{"code":0,"message":"no views in the session","data":null},"id":2}

**Comment by bhcleek** [comment]
Thank you. I think the problem here is that you're console emulator for Linux terminals on Windows. I'm not sure if the proper place to address this is in your system, in vim-go, or in `gopls`. It _looks_ like vim-go is sending the kind of paths that should work in the Linux terminal, but I'm not sure how `gopls` deals with that.

I'm curious if the problem persists after running `:GoUpdateBinaries gopls` in Vim session started from the Linux terminal.

I don't have a Windows system that I can test this with.

**Comment by stamblerre** [comment]
I have a Windows machine that I have access to, so @manjitsinghm, if you're able to share full repro steps, I can try to reproduce.

/cc @heschik who added this check

**Comment by heschik** [comment]
We need much more specific detail about what the setup is here to do any real diagnosis. Right now, it looks like `gopls` is receiving very strange Linux-style paths (`/d/timezone/go/src/ecp_service`) despite running completely in Windows. What exactly is the "console emulator for Linux terminals on windows" and how exactly is vim being started?

**Comment by bhcleek** [comment]
@heschik the paths are because of the linux emulation layer. I think it's WSL: https://docs.microsoft.com/en-us/windows/wsl/install-win10. Despite it being on Windows, the paths are Linux like _because_ vim is running in WSL. I'm most curious whether this is issue is because the `gopls` on the @manjitsinghm's system wasn't built in WSL.

**Comment by manjitsinghm** [comment]
Let me explain my setup I am on windows 10 system. I have installed go version 1.14.2 and it has installed all binaries in c drive at location C:\Go\bin. 
I have a Linux emulator on windows. I have installed it for using Linux terminals on windows that is the reason we see Linux type path on windows being exchanged with gopls. 
My apologies if I am not using the packages in the expected style/environment.
Let me know if any more information is required. I will try reinstalling golang with the above options mentioned - https://docs.microsoft.com/en-us/windows/wsl/install-win10 and let u know the results.

**Comment by bhcleek** [comment]
@manjitsinghm If you're _only_ using a linux emulator in Windows and not WSL, you _might_ be able to get things to work as expected, but I'm not sure and this isn't really a supported configuration. Please let us know if you find a way to get everything working with the emulator.

**Comment by manjitsinghm** [comment]
ok

**Comment by manjitsinghm** [comment]
by any chance can i get the gopls build on Linux system that understands the Linux way for file path? I can i try deploying that and try?

**Comment by bhcleek** [comment]
You can cross compile gopls for Linux on your windows machine with `GOOS=linux GO111MODULE=on go get golang.org/x/tools/gopls@latest`

**Comment by bhcleek** [comment]
@manjitsinghm have you made any progress? Do we need to leave this issue open?

**Comment by manjitsinghm** [comment]
bhcleek, I have switched to ubuntu VM and everything is working as expecting. Closing the issue. Thanks!

**Comment by manjitsinghm** [comment]
I have switched to ubuntu VM and everything is working as expecting. Closing the issue. Thanks!

**Comment by patrickriordan** [comment]
For anyone else hitting this issue:
I'm getting a "no views in session error" with git-bash which uses paths like /c/Users/... instead of C:\Users as mentioned eariler
But WSL1 and WSL2 debian worked fine for me using linux vim/vim-go/go of course.

I think this is related to git-bash, I haven't tried extensively getting it working with Command Prompt, but I'm getting different error with it, complaining that GoDef wasn't an editor command.

**Comment by alessioalex** [comment]
any way to get this working in Git bash? Thanks

**Comment by manjitsinghm** [comment]
No
