### ISSUE TITLE
GoDef hangs if target file not open in buffer

### ISSUE THREAD

**Issue by pauldthomson** [fatih/vim-go#2864]
### What did you do? (required: The issue will be **closed** when not provided)
Went to a symbol in a Go file, ran the `:GoDef` command

### What did you expect to happen?
File containing the definition is opened in a new buffer

### What happened instead?
The new buffer is opened, but vim doesn't jump to the buffer. Instead it seems to hang. Pressing ctrl-c then kills whatever is hanging and vim jumps to the definition in the newly opened buffer. The `:messages` command shows this:
```
vim-go: [definition] SUCCESS
"pkg/controller/table/table_controller.go" 128L, 4640C
vim-go: Vim:Interrupt
```
where the Vim:Interrupt is from me pressing ctrl-c

This _doesn't_ happen if the target file is already open in another buffer i.e. once the buffer is loaded, `:GoDef` works as expected.

#### vim-go version:
13af5df

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" =========================
" Vim built in config
" =========================
filetype plugin indent on
syntax on
set cursorline
set number
set relativenumber
set autowrite
set encoding=utf-8
set tabstop=4 
set expandtab 
set shiftwidth=4 
set smarttab
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set noerrorbells
set visualbell
set splitbelow
set splitright

"Get the 2-space YAML as the default when hit carriage return after the colon
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" Disable arrowkeys in insert and normal modes
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap <Up>    <NOP>
inoremap <Down>  <NOP>
inoremap <Left>  <NOP>
inoremap <Right> <NOP>

" Move visual selection
vnoremap J :m '>+1<cr>gv=gv
vnoremap K :m '<-2<cr>gv=gv

" Map leader to space
let mapleader="\<Space>"

" Always show statusline
set laststatus=2

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Use jk to exit insert mode 
inoremap jk <ESC>

" Use ctrl+hjkl to navigate splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Save buffer
nnoremap <leader>w :w<cr>

" Copy to system clipboard in visual mode
vmap <leader>y "+y

" Paste from system clipboard
nmap <leader>p "+p

" =========================
" NERDTree
" =========================

" Toggle NERDTree
map <C-n> :NERDTreeToggle<CR>

" Show hidden files in NERDTree
let NERDTreeShowHidden=1

" =========================
" vim-java
" =========================

" Java syntax
let g:java_highlight_functions = 1

" =========================
" Colourscheme
" =========================
colorscheme codedark

" =========================
" vim-airline
" =========================
let g:airline_theme = 'codedark'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'

" =========================
" vim-gitgutter
" =========================
" To make gitgutter diff markers show faster
set updatetime=100

" =========================
" vim-fugitive
" =========================
" Open fugitive diff in verticle splits
set diffopt+=vertical

" =========================
" fzf
" =========================
set rtp+=/usr/local/opt/fzf

" fzf files
nnoremap <leader>f :Files<CR>

" fzf lines in file
nnoremap <leader>/ :BLines<cr>

" fzf vim commands
nnoremap <leader>c :Commands<cr>

" Open fzf buffers list
nnoremap <leader>e :Buffers<cr>

" Use ripgrep
nnoremap <leader>r :Rg<Space>

if executable('rg')
  let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --follow --glob "!.git/*"'
endif

" =========================
" vim-terraform
" =========================
" Format terraform
let g:terraform_fmt_on_save = 1
let g:tereraform_align = 1

" =========================
" coc.nvim
" =========================
" Use <tab> for trigger completion and navigate to next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

" Coc rename
nmap <F2> <Plug>(coc-rename)

" Use enter to select completion
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" =========================
" vim-go
" =========================
" Highlighting
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1

" Show info about type or method
let g:go_auto_type_info = 1

" Run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go nmap <leader>t  <Plug>(go-test)

" Run goimports on save
let g:go_fmt_command = "goimports"

" Control how to open buffer when alternating between test and src
autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')
autocmd Filetype go nmap <leader>gav <Plug>(go-alternate-vertical)
autocmd Filetype go nmap <leader>ga <Plug>(go-alternate-edit)
autocmd Filetype go nmap <F12> :GoDecls<CR>
autocmd FileType go nmap <F10> :GoTest<CR>
autocmd FileType go nmap <F9> :GoTestFunc<CR>
autocmd FileType go nmap <F7> :GoReferrers<CR>

" Automatically highlight same identifiers (functions, variables etc)
let g:go_auto_sameids = 1

" Use gopls everywhere I can
let g:go_def_mode = 'gopls'
let g:go_info_mode = 'gopls'
let g:go_rename_command = 'gopls'
let g:go_gopls_complete_unimported = 1

" =========================
" indentLine
" =========================
" Scrolling performance
let g:indentLine_faster     = 1
let g:indentLine_setConceal = 0
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 19 2020 22:39:33)
macOS version
Included patches: 1-600

#### Go version (`go version`):

go version go1.14.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/pthomson/Library/Caches/go-build"
GOENV="/Users/pthomson/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com/tyro-private"
GONOSUMDB="github.com/tyro-private"
GOOS="darwin"
GOPATH="/Users/pthomson/go"
GOPRIVATE="github.com/tyro-private"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1n/fg0y62lj3sz31db9vtvbym006nsw3r/T/go-build755232971=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
</pre></details>

**Comment by bhcleek** [comment]
I use `:GoDef` frequently without problems. Does it _ever_ work for you? Can you provide a simple reproduction case?

**Comment by pauldthomson** [comment]
It started a couple of weeks ago. It seems to always hang if the target is in a new file, and that file isn't yet loaded in a buffer. If the file _is_ loaded, it works fine.

How would you like me to provide the case? Sample repo or just screen record the bahaviour?

**Comment by bhcleek** [comment]
>  if the target is in a new file, and that file isn't yet loaded in a buffer.

If it's a _new_ file relative to _what_?

> How would you like me to provide the case? Sample repo or just screen record the behaviour?

A sample repo is ideal.

I'll help you get to the bottom of this, and `gopls` is the preferred option, but you might be interested to know that you can set `g:go_def_mode` to use `godef` or `guru` to jump to definitions instead of `gopls`, too.

**Comment by pauldthomson** [comment]
> If it's a new file relative to what?
Relative to the symbol whose definition I'm wanting to jump to. E.g. if I had this in `file-1.go`
```
f.someFunction()
```
and `someFunction()` was defined in `file-2.go`, then running `:GoDef` on that function would cause the hang, but only if `file-2.go` wasn't already open in another buffer.

> I'll help you get to the bottom of this, and gopls is the preferred option, but you might be interested to know that you can set g:go_def_mode to use godef or guru to jump to definitions instead of gopls, too.
I could give that a shot, but I don't think it's `gopls`, the definition seems to be found, the file containing the definition is opened in another buffer, but it hangs before switching to that buffer/tab.

As for a repo, in github.com/schemahero/schemahero, if I go to this file/line: https://github.com/schemahero/schemahero/blob/841b9e897f278e34e9b04a041e9968eb1b5b0d8c/pkg/controller/table/reconile_table.go#L199 and run `:GoDef` on `r.getPlanPod()`, I can replicate the behaviour.

**Comment by bhcleek** [comment]
I'm able to jump to the definiton of `r.getPlanPod`, though on the first attempt there is a delay.

**Comment by pauldthomson** [comment]
Hmmm. OK I fired up another computer and it also worked fine (all my dotfiles are in git so the setup is somewhat the same).

I guess at this point the only thing I can think of is something about my Go setup or Vim? I'll close this issue anyway. Thanks for your help and sorry for misleading :)

**Comment by pauldthomson** [comment]
Seems it's Vim. My other computer was running `8.2.500` and the one with the issue had `8.2.600`. Just updated the former and it now suffers the same issue.
