### ISSUE TITLE
auto_type_info close window if cursor is not in the function

### ISSUE THREAD

**Issue by strogiyotec** [fatih/vim-go#2865]
Good day,  I have a problem with auto_type_info parameter , it's enabled in my vimrc and according to help manual:
```
Whenever the cursor changes the type info will be
updated
```
It works perfectly well for example
```
io.ByteReader.ReadByte()
 fmt.Println()
```
when my cursor is in ReadByte method I have a hint 
```
func (ByteReader).ReadByte() (byte, error)
```
But I want to remove this hint when my cursor is not in the function, for example if my cursor points to comment or bracket then I still have function info related to previous method.Is it possible to change this behavior it ?

**Comment by bhcleek** [comment]
This isn't possible with vim-go as-is. On its face, it seems relatively straightforward to accomplish, but for it's more complex than it appears due to async calls and other messages that may be shown that it wouldn't make sense to clear.

**Comment by strogiyotec** [comment]
@bhcleek  thank you for response
