### ISSUE TITLE
Error on saving go file with syntax errors

### ISSUE THREAD

**Issue by Hritik14** [fatih/vim-go#2868]
### What did you do? (required: The issue will be **closed** when not provided)
Whenever saving a go file that contains some error, this weird text appears
``` 
Error detected while processing function go#auto#fmt_autosave[6]..go#fmt#Format[53]..go#fmt#ShowErrors:
```

### What did you expect to happen?
Not show that unhelpful message and save the file and let my linter check for syntactical errors.

### What happened instead?
This weird error barged in 
![image](https://user-images.githubusercontent.com/7457065/80607342-04764580-8a53-11ea-9e91-b76ef5496457.png)

####  `vimrc` you used to reproduce:

Nothing specific to vim-go

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 13:23:00)
Included patches: 1-510
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.14.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hritik/.cache/go-build"
GOENV="/home/hritik/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hritik/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build000909212=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.2
    golang.org/x/tools/gopls@v0.3.2 h1:eP1aj1AvT6ynElQH6KP0mmOT2gnWa1gYclHL4wGUbMo=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_gosnippets = 1
g:go_gotags_bin = 'gotags'
g:go_jump_to_error = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Thank you for the report.

Can you add `g:go_debug=['lsp']` to your vimrc, duplicate the problem you're seeing and then provide the LSP debug logs here?

After you've done that, please consider updating `gopls` to the latest release with `:GoUpdateBinaries gopls`: it may not cause the same problem.

**Comment by Hritik14** [comment]
After enabling that debug flag, the error disappeared but this huge text got populated in my loclist/quicfix list : http://ix.io/2k6y
Disabling the debug flag made the error popup come again. 
I've updated `gopls` as you asked.

**Comment by bhcleek** [comment]
> After enabling that debug flag, the error disappeared but this huge text got populated in my loclist/quicfix list : http://ix.io/2k6y

I think you confused the LSP debug window with your quickfix window; those messages are _not_ in the quickfix/location window.

However, after reviewing those logs, I can see that you're not formatting with LSP (I should have notice that previously - it's clear in the function list that the functions in `lsp.vim` aren't relevant to what you're seeing.

What does `gofmt` report if you run it from the shell on the file that you're having problems with?

**Comment by bhcleek** [comment]
@Hritik14 should we keep this open?

**Comment by Hritik14** [comment]
Yes! Apologies for late reply. 
I don't think the problem is with gofmt, seems more with `vim-go`.
I've creating an asciinema describing the whole mess: https://asciinema.org/a/EPQZVJS0igrh2RHwSsucuSKTh

**Comment by Hritik14** [comment]
Just to make sure it's none of the other plugins, I disabled all of them and created a very minimal vimrc, still the same. 
[![asciicast](https://asciinema.org/a/MrTo1jkc1keofEIT1qUfFN2WB.svg)](https://asciinema.org/a/MrTo1jkc1keofEIT1qUfFN2WB)

**Comment by bhcleek** [comment]
Based on the error message, it looks like you may have a mix of some different versions of vim-go files on your system.

Can you see how many files `list.vim` files you have and what their paths are?

**Comment by bhcleek** [comment]
Also, how many `fmt.vim` files do you have and what are their paths?

**Comment by Hritik14** [comment]
Only one for both
```sh
❯ find . -iname "*list.vim" -or -iname "*fmt.vim*"
./autoload/go/asmfmt.vim
./autoload/go/fmt.vim
./autoload/go/list.vim
```

**Comment by bhcleek** [comment]
Can you go up some levels and try again; I suspect you have residue from a previous install of vim-go?

Also, after loading a go file and getting the error you're seeing, can you run `:verbose function go#fmt#ShowErrors`, `:verbose function go#Fmt#Format`, `:verbose function go#list#ParseFormat`, and provide each of the outputs here?

**Comment by Hritik14** [comment]
Doesn't seem to be multiple `vim-go` here: 
```
❯ pwd && find . -iname "list.vim" -or -iname "fmt.vim"                        [NORMAL]
/home/hritik/.vim
./pack/my_plugins/start/vim-go/autoload/go/fmt.vim
./pack/my_plugins/start/vim-go/autoload/go/list.vim
./pack/my_plugins/start/ale/autoload/ale/list.vim
./pack/my_plugins/start/lexima.vim/autoload/vital/_lexima/Data/List.vim
```

<details>
<summary>:verbose function go#fmt#ShowErrors</summary>

```
  function go#fmt#ShowErrors(errors) abort
        Last set from ~/.vim/pack/my_plugins/start/vim-go/autoload/go/fmt.vim line 188
1    let l:errorformat = '%f:%l:%c:\ %m'
2    let l:listtype = go#list#Type("GoFmt")
3
4    call go#list#ParseFormat(l:listtype, l:errorformat, a:errors, 'Format')
5    let l:errors = go#list#Get(l:listtype)
6
7    " this closes the window if there are no errors or it opens
8    " it if there are any.
9    call go#list#Window(l:listtype, len(l:errors))
   endfunction
```
</details>

`:verbose function go#Fmt#Format`
`E123: Undefined function: go#Fmt#Format`

<details>
<summary>
verbose function go#list#ParseFormat
</summary>
```
   function go#list#ParseFormat(listtype, errformat, items, title, add) abort
        Last set from ~/.vim/pack/my_plugins/start/vim-go/autoload/go/list.vim line 61
1    " backup users errorformat, will be restored once we are finished
2    let old_errorformat = &errorformat
3
4    " parse and populate the location list
5    let &errorformat = a:errformat
6    try
7      call go#list#Parse(a:listtype, a:items, a:title, a:add)
8    finally
9      "restore back
10     let &errorformat = old_errorformat
11   endtry
   endfunction
```
</details>

**Comment by Hritik14** [comment]
Weird. A recent update seems to have fixed this.
[![asciicast](https://asciinema.org/a/FwcFODFSX3mf4WjBkETby8AD9.svg)](https://asciinema.org/a/FwcFODFSX3mf4WjBkETby8AD9)

Currently my head is at d8bbc29e8315289e5a88f7d47a4b64243dd9701f

**Comment by Hritik14** [comment]
Unrelated, but can you tell me if there's a way I can instruct vim-go to not to open loclist/quickfix list on errors. I would just like to have the error indicators (`>>`) and open the loclist manually.

**Comment by bhcleek** [comment]
Vim-go doesn't set those indicators at all.

**Comment by bhcleek** [comment]
It's too late now, but I wanted to point out that `go#Fmt#Format` should have been `go#fmt#Format`, and I've corrected my original comment for any future readers that use the technique.

**Comment by Hritik14** [comment]
I should probably open a new issue if it takes more than one reply now but what I'd want is v-go to only populate the location list/quickfix list on errors and NOT open them in a split.

**Comment by bhcleek** [comment]
Vim-go doesn't support populating quickfix or location list windows without opening them. I'm not sure why you'd want that, either. The markers that you're referring to are not created by vim-go. However, if you're not interested in the errors that vim-go populates and the quickfix or location list windows that it opens, then you can choose to not run the commands that do that.

Feel free to open an issue if you want to discuss this further.
