### ISSUE TITLE
Add args list for metalinter command

### ISSUE THREAD

**Issue by MrGossett** [fatih/vim-go#2870]
## What did you do? (required: The issue will be **closed** when not provided)

I want to add the `--fix` flag to `golangci-lint run` in my metalinter command.

_(please pardon potential over-explaining, as I want to be clear about what I'm trying to accomplish)_

`golangci-lint` provides a [command-line option `--fix`](https://github.com/golangci/golangci-lint/blob/eeff3902d440513f5598391d6589c779d39af796/README.md#command-line-options) that will fix found issues when supported by the linter. For example, the `gofmt` linter can automatically simplify statements resulting in changes like this one:

```diff
- var _ = []T{T{}, T{}}
+ var _ = []T{{}, {}}
```

There is no config file corollary for the `--fix` flag, so it must be suppled as a command-line flag if it is to be used. I would like to include this flag when executing `:GoMetaLinter`. I tried this:

```vim
g:go_metalinter_command = 'golangci-lint run --fix'
```

But doing this means that other `g:go_metalinter_*` configuration is ignored since the command now does not match one of the sentinel commands. Instead, I would need to maintain `g:go_metalinter_command` as a single string that embeds all of the configuration that would otherwise be expressed in `g:go_metalinter_*` options.

The actual CLI command that is run by `:GoMetaLinter` (when configured to use `golangci-lint`) is built up [here](https://github.com/fatih/vim-go/blob/2880123a98d735729a777b5e44317d383faec293/autoload/go/lint.vim#L405-L420):

```vim
function! s:golangcilintcmd(bin_path, haslinter)
  let cmd = [a:bin_path]
  let cmd += ["run"]
  let cmd += ["--print-issued-lines=false"]
  let cmd += ['--build-tags', go#config#BuildTags()]
  " do not use the default exclude patterns, because doing so causes golint
  " problems about missing doc strings to be ignored and other things that
  " golint identifies.
  let cmd += ["--exclude-use-default=false"]

  if a:haslinter
    let cmd += ["--disable-all"]
  endif

  return cmd
endfunction
```

This results in something like `golangci-lint run --print-issued-lines=false --build-tags --exclude-use-default=false` returned in `cmd`.

That function is called by [`metalintercmd`](https://github.com/fatih/vim-go/blob/2880123a98d735729a777b5e44317d383faec293/autoload/go/lint.vim#L398), which in turn is called during [`go#lint#Gometa`](https://github.com/fatih/vim-go/blob/2880123a98d735729a777b5e44317d383faec293/autoload/go/lint.vim#L17) (at least it is in my use case, when `g:go_metalinter_command = 'golangci-lint'`). The resulting command [collects](https://github.com/fatih/vim-go/blob/2880123a98d735729a777b5e44317d383faec293/autoload/go/lint.vim#L24) [more](https://github.com/fatih/vim-go/blob/2880123a98d735729a777b5e44317d383faec293/autoload/go/lint.vim#L44) [flags](https://github.com/fatih/vim-go/blob/2880123a98d735729a777b5e44317d383faec293/autoload/go/lint.vim#L47) as appropriate according to the user's configuration.

### What did you expect to happen?

I'd like to be able to add an option like this:

```vim
g:go_metalinter_command_flags = ['--fix']
```

so that `vim-go` will execute a command like this:

```
golangci-lint run --fix ...
```

Causing a buffer that started like this (for example):

```go
package example

var _ = []T{T{}, T{})
```

to be updated to contain this:

```go
package example

var _ = []T{{}, {})
```

### What happened instead?

As far as I can tell, there is no way for me to add the `--fix` flag to the list of args used with `golangci-lint run`.

#### vim-go version:

[`13af5df`](https://github.com/fatih/vim-go/commit/13af5df6a1b3bc4bdfd03e3c05fa600d1dd16de6) (`HEAD` of `master` at the time of writing). v1.22 is the most recent release.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br>

```vim
" plugins
call plug#begin('~/.vim/plugged')

" Golang
Plug 'fatih/vim-go', {'for': 'go'}
let g:go_gopls_enabled = 1
let g:go_def_mode = "gopls"
let g:go_info_mode = "gopls"
let g:go_referrers_mode = "gopls"
let g:go_rename_command = "gopls"
let g:go_auto_type_info = 1
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_fold_enable = ["block", "import", "varconst", "package_comment", "comment"]
let g:go_gocode_unimported_packages = 1
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_function_parameters = 1
let g:go_highlight_functions = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_trailing_whitespace_error = 1
let g:go_highlight_types = 1
let g:go_highlight_variable_assignments = 1
let g:go_highlight_variable_declarations = 1
let g:go_metalinter_enabled = []
let g:go_metalinter_command = "golangci-lint"
let g:go_metalinter_deadline = "60s"
let g:go_statusline_duration = "15s"
let g:go_test_show_name = 1

call plug#end()

set nocompatible
syntax enable
syntax sync minlines=256
filetype plugin on
set fdm=syntax
set foldlevelstart=20
set nocursorcolumn
set re=1

" remove trailing whitespace on save
au BufWritePre <buffer> :%s/\s\+$//e

let mapleader = ","
au FileType dockerfile,go setlocal sw=8 ts=8 noet tw=80
au FileType go setlocal autowrite
" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

au FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
au FileType go nmap <Leader>l <Plug>(go-metalinter)
au FileType go nmap <Leader>f :GoFmt
au Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
au Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
au Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
au Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')
au FileType go setlocal sw=4 ts=4 noet
"
" quickfix navigation: ctrl-n for next, ctrl-p for previous.
map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>
```

</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 29 2020 01:33:43)
macOS version
Included patches: 1-654

#### Go version (`go version`):

go version go1.14.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/Library/Caches/go-build"
GOENV="$HOME/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="$HOME/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="$HOME/Code/green/project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5q/hz1mlwc55q77lwr16k454bnm0000gn/T/go-build980957767=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 1
g:go_auto_type_info = 1
g:go_highlight_variable_assignments = 1
g:go_list_type = 'quickfix'
g:go_metalinter_deadline = '20s'
g:go_highlight_methods = 1
g:go_highlight_function_parameters = 1
g:go_highlight_fields = 1
g:go_fold_enable = ['block', 'import', 'varconst', 'package_comment', 'comment']
g:go_highlight_trailing_whitespace_error = 1
g:go_rename_command = 'gopls'
g:go_gopls_enabled = 1
g:go_statusline_duration = '15s'
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_variable_declarations = 1
g:go_doctor_loaded_install = 1
g:go_gocode_unimported_packages = 1
g:go_highlight_extra_types = 1
g:go_highlight_generate_tags = 1
g:go_metalinter_command = 'golangci-lint'
g:go_build_tags = 'integration'
g:go_loaded_gosnippets = 1
g:go_highlight_functions = 1
g:go_highlight_operators = 1
g:go_referrers_mode = 'gopls'
g:go_test_show_name = 1
g:go_jump_to_error = 1
g:go_highlight_space_tab_error = 1
g:go_metalinter_enabled = []
g:go_loaded_install = 1
g:go_highlight_build_constraints = 1
g:go_def_mode = 'gopls'
g:go_highlight_function_calls = 1
g:go_fmt_command = 'goimports'
g:go_info_mode = 'gopls'
g:go_highlight_array_whitespace_error = 1
g:go_highlight_types = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by MrGossett** [comment]
In an attempt to be helpful, I have a branch on a fork that implements the basic behavior I'm looking for: https://github.com/MrGossett/vim-go/commit/abacde9ffbae37696c2ccc9ef52ea796765bd64a

**Comment by bhcleek** [comment]
I understand the desire, but dealing with those args will be difficult to support. I think we've done all we can do to support `golangci-lint`. May I humbly suggest that ask `golangci-lint` to support `--fix` in the config file instead?
