### ISSUE TITLE
GoMetaLinter opens the hello_world.go template with linter output as its filename

### ISSUE THREAD

**Issue by hajekjiri** [fatih/vim-go#2871]
### What did you do? (required: The issue will be **closed** when not provided)

1. create the following file in `$(go env GOPATH)/src/hello-world/main.go` and open it with `vim`
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("Helo World")
}

func mySleep(time int) {
	time.Sleep(500 * time.Millisecond)
}
```
2. run `:GoMetaLinter`

### What did you expect to happen?

- get output from the linter in the quickfix list

### What happened instead?

- got output from the linter in the quickfix list
- vim opened a new buffer called `type int has no field or method Sleep) /home/jiri/projects/go/src/hello-world/main.go` with a copy of the `hello_world.go` template in it
```go
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

#### vim-go version:
tip of the master branch as of writing (13af5df), same behavior appears in v1.22

####  `vimrc` you used to reproduce:
<details><summary>vimrc</summary><br><pre>
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 26 2020 11:23:21)
Included patches: 1-510
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.14.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jiri/.cache/go-build"
GOENV="/home/jiri/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jiri/projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build687388801=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
I'm not able to duplicate the problem you're describing. With the file you've provided, `:GoMetaLinter` populates the quickfix with the expected errors and does not open another buffer.

To help us figure out why you're seeing the behavior you're describing, can you run `G"=getqflist()p` after running `:GoMetaLinter` to put the raw contents of the quickfix list in a buffer, and then copy and paste those contents here?

**Comment by hajekjiri** [comment]
The quickfix list was already in its own buffer. `G"=getqflist()p` doesn't seem to do anything, though something might be wrong since running the same thing with a typo (e.g. `G"=getqflistasdf()p` gives me no errors (and also does nothing). Anyway, here's the output.
```
type int has no field or method Sleep) /home/jiri/projects/go/src/hello-world/main.go|13 col 24 warning| time.Millisecond undefined (type int has no field or method Millisecond
type int has no field or method Sleep) /home/jiri/projects/go/src/hello-world/main.go|13 col 24 error| time.Millisecond undefined (type int has no field or method Millisecond
```

**Comment by bhcleek** [comment]
Can you try `G"=getloclist()p` instead?

**Comment by bhcleek** [comment]
I also really need the raw golangci-lint output to see what the error message it's outputting is. You can get that by adding `call go#util#EchoInfo(string(a:messages))` at line 430 in lint.vim: https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L430

**Comment by hajekjiri** [comment]
> Can you try G"=getloclist()p instead?

Nothing happens.

> You can get that by adding call go#util#EchoInfo(string(a:messages)) at line 430 in lint.vim

Nothing changes. I'm getting the same output.

Running `golangci-lint run` outside of vim gives me this which might be what you're looking for.
```
WARN [runner] Can't run linter goanalysis_metalinter: S1009: failed prerequisites: [(inspect@hello-world, isgenerated@hello-world): analysis skipped: errors in package: [/home/jiri/projects/go/src/hello-world/main.go:13:7: time.Sleep undefined (type int has no field or method Sleep) /home/jiri/projects/go/src/hello-world/main.go:13:24: time.Millisecond undefined (type int has no field or method Millisecond) /home/jiri/projects/go/src/hello-world/main.go:5:2: "time" imported but not used]] 
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/home/jiri/projects/go/src/hello-world/main.go:13:7: time.Sleep undefined (type int has no field or method Sleep) /home/jiri/projects/go/src/hello-world/main.go:13:24: time.Millisecond undefined (type int has no field or method Millisecond) /home/jiri/projects/go/src/hello-world/main.go:5:2: "time" imported but not used] 
ERRO Running error: buildssa: analysis skipped: errors in package: [/home/jiri/projects/go/src/hello-world/main.go:13:7: time.Sleep undefined (type int has no field or method Sleep) /home/jiri/projects/go/src/hello-world/main.go:13:24: time.Millisecond undefined (type int has no field or method Millisecond) /home/jiri/projects/go/src/hello-world/main.go:5:2: "time" imported but not used]
```

**Comment by bhcleek** [comment]
Unfortunately, the commandline logs aren't sufficient, because `golangci-lint` outputs the logs in a different format when it's run by vim-go (I've never been able to get it to use the output format from the commandline that it does when vim-go runs it).

> Nothing happens.

When you run that command, you'll need to be in the window whose location list has opened. Is it opening a locationlist or a quickfix list for you? If it's the latter, then `getqflist()` should be used instead of `getloclist()`. Reading your issue again, it looks like it should be `getqflist()`, because you're seeing this after running `:GoMetaLinter`, not when saving.

> Nothing changes. I'm getting the same output.

Understood. This is because you're seeing this when running `:GoMetaLinter`. You can disregard that request. What I really need is the output from `getqflist()`. So let's talk about `G"=getqflist()p `:
1. `G` to go to the end of the buffer
2. `"=getqflist()` use the expression register
3. `p` to paste the value from the expression register.

**Comment by hajekjiri** [comment]
Oh, I see. Here's what I'm getting from `G"=getqflist()p`.
```
{'lnum': 19, 'bufnr': 3, 'col': 24, 'pattern': '', 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'module': '', 'text': 'time.Millisecond undefined (type int has no field or method Millisecond'}
{'lnum': 19, 'bufnr': 3, 'col': 24, 'pattern': '', 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'e', 'module': '', 'text': 'time.Millisecond undefined (type int has no field or method Millisecond'}
```

**Comment by bhcleek** [comment]
Thanks. That's enough info, I think. I'll try to get a fix in place soon.

**Comment by bhcleek** [comment]
@hajekjiri it's going to be hard for me to fix this, because:
1. I can't duplicate it
2. I don't have the actual raw messages that golangci-lint is giving you (though with the totality of your comments I think I can piece it together)

Can you try updating golangci-lint (`:GoUpdateBinares golangci-lint`) to see if this is still a problem for you afterwards?

**Comment by bhcleek** [comment]
@hajekjiri one more request: before you update golangci-lint or if you update it and still have the same problem, can you give https://github.com/fatih/vim-go/pull/2874 a try to see if it resolve the problem you're seeing?

**Comment by hajekjiri** [comment]
```
$ golangci-lint --version
golangci-lint has version v1.26.1-0.20200501152037-1b9f29a3043a built from (unknown, mod sum: "h1:p8WoqL/gdPpjvJdnvycbW+RZR4SYfBTw24CYKKGx0kY=") on (unknown)
```

#2874 does resolve the problem!

**Comment by bhcleek** [comment]
Do you have have the problem with master and the updated golangci-lint?

**Comment by hajekjiri** [comment]
Yes, that's actually been my setup the entire time. I already had the latest golangci-lint.

Also tried downgrading golangci-lint to v1.26.0, v1.25.0, and v1.24.0, but they all behaved the same in terms of this problem.

**Comment by bhcleek** [comment]
Thanks for confirming. I won't be able to merge #2874 as-is, because it breaks other scenarios. I'm going to try to adjust the error parsing, but I might have to revert #2835 completely if the already tested scenarios and the one you're encountering can't both be satisfied.

Unfortunately, I still can't duplicate the problem you're seeing, so I'm not sure I can construct a test that will cover it with confidence. Would you be willing to test the solution once I have one for you to try?

**Comment by hajekjiri** [comment]
Sure! Happy to help.

I'm also able to reproduce this on my other laptop, though it's set up very similarly to my daily driver I'm on. I'll try this on a fresh Arch Linux install in the next few days once I find some extra time to go through it.

**Comment by bhcleek** [comment]
@hajekjiri I was finally able to duplicate what you're seeing. It looks like the only real solution is to remove revert #2835. I'll put up a PR soon.

**Comment by bhcleek** [comment]
FWIW, the reason you're seeing this is that there are two errors in the file that prevent linters from running.
