### ISSUE TITLE
GoMetaLinter throws undefined variable errors

### ISSUE THREAD

**Issue by dethtron5000** [fatih/vim-go#2872]
### What did you do? (required: The issue will be **closed** when not provided)
Open any Go file
Run `:GoMetaLinter`

### What did you expect to happen?
I expected the linter results to be in the results menu

### What happened instead?
I get the following error
```
Error detected while processing function go#lint#Gometa[44]..<SNR>118_errorformat:
line   35:
E121: Undefined variable: l:efm
``` 
It appears on every Go project that I try to run it on.
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
let g:go_fmt_command = "goimports"
let g:ale_linters_explicit = 1
let g:ale_completion_enabled = 1
let g:ale_fix_on_save = 1
let g:go_metalinter_command = "golangci-lint run"
let g:go_rename_command = "gopls"
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 12 2020 17:46:30)
macOS version
Included patches: 1-539

#### Go version (`go version`):

go version go1.14.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/PeterOlson/Library/Caches/go-build"
GOENV="/Users/PeterOlson/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/PeterOlson/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/PeterOlson/Documents/workspace/frs/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0_/rjgf0wn55gj3p4cnmyptmzvr0000gp/T/go-build955324147=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.2
    golang.org/x/tools/gopls@v0.3.2 h1:eP1aj1AvT6ynElQH6KP0mmOT2gnWa1gYclHL4wGUbMo=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_gosnippets = 1
g:go_rename_command = 'gopls'
g:go_metalinter_command = 'golangci-lint run'
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
`golangci-lint run` is not a supported value for `g:go_metalinter_command`.

**Comment by sentriz** [comment]
^ to add to above, just remove the `run` eg.
`let g:go_metalinter_command = 'golangci-lint'`
this is working well finally with golangci-lint `v1.26`
`$ cd $(mktemp -d); go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.26.0`
`$ golangci-lint version`
