### ISSUE TITLE
Vim freezes when encounter big commented number while syntax is enabled

### ISSUE THREAD

**Issue by alabarjasteh** [fatih/vim-go#2873]
### What did you do? (required: The issue will be **closed** when not provided)
Open a file with about 100 lines of code containing the line blow:

``` go
// when syntax is enabled, hitting j in normal mode at this line cause vim to freeze
// const bigNum = 9223372036854775808543522345
```
As soon as the number is cleared the problem solved.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
syntax on
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2019 14:45:40)
Included patches: 1-503, 505-680, 682-1312
Compiled by root@apple.com

#### Go version (`go version`):

go version go1.13.7 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Ala/Library/Caches/go-build"
GOENV="/Users/Ala/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/Ala/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/Ala/Desktop/ultimate-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nw/qhdq14yn06d4_splr7rzqz480000gn/T/go-build382438794=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_fmt_fail_silently = 1
g:go_snippet_engine = 'neosnippet'
g:go_metalinter_autosave = 1
g:go_loaded_install = 1
g:go_loaded_gosnippets = 1
g:go_jump_to_error = 1
g:go_list_type = 'quickfix'
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
I'm not not able to duplicate the problem you've described.

> As soon as the number is cleared the problem solved.

What does this mean?

**Comment by alabarjasteh** [comment]
I'm new to vim and vim-go, I'm not sure if it is normal that comments get processed. Last night I saw strange highlights within commented notes come and go. In the situation I issued when there is a big const in comments for example in line 50 and I hit G in normal mode to see the the end of the file ,vim freezes. When press j on the line above (line 49 in this scenario), after a pause syntax automatically turn of and when I try to enable it, vim complaints: " 'redrawtime' exceeded, syntax highlighting disabled."

> what does this mean?


``` Go
// Line below makes problem.
// const bigNum = 9223372036854775808543522345 
```

``` Go
// No problem anymore.
// const bigNum =  
```

If I open the file with this command, no such problem appears again.
``` 
$ vim -u ~/.vimrc --noplugin -N -i NONE file.go
```

 I include more of my vimrc as follows.

<details><summary>vimrc</summary><br><pre>
set autowrite

let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1

set updatetime=300
let g:go_auto_sameids = 1

let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_structs = 1 


</pre></details>

Thank you.

**Comment by bhcleek** [comment]
Syntax highlighting in Vim is based on regular expression. In the case of numbers, the comment lines _will_ be processed, though the comment highlighting should ultimately be used instead of the number highlighting.

Can you provide the file full file that you're having a problem with?

**Comment by alabarjasteh** [comment]
[constant.go.zip](https://github.com/fatih/vim-go/files/4571088/constant.go.zip)

It is from: https://github.com/hoanhan101/ultimate-go/

**Comment by bhcleek** [comment]
I don't see any delay when moving onto or away from the untyped const at https://github.com/hoanhan101/ultimate-go/blob/master/go/language/constant.go#L68-L73.

Perhaps this is related to your machine specs? Since I'm not sure what version of vim-go you're using, it's hard to know whether you're using some of the changes to number highlighting that were introduced last last year.

**Comment by martskins** [comment]
@alabarjasteh do you happen to have `set re = 1` in your `vimrc`? Having it set to 1 results in the issue for me, but using the default 0 works fine.

**Comment by alabarjasteh** [comment]
Updating vim with `brew install vim` solved the problem. 
Thank you @bhcleek. Thank you @martskins, your comment helped me to understand the problem.
