### ISSUE TITLE
GoRename does not use gopls as defined in .vimrc

### ISSUE THREAD

**Issue by captainviet** [fatih/vim-go#2877]
### What did you do? (required. The issue will be **closed** when not provided.)
Set the following global variable in `~/.vimrc`
```
let g:go_rename_command = "gopls"
let g:go_debug = ['shell-commands']
```
Running `:GoRename hello` command

### What did you expect to happen?
The variable is correctly renamed to `hello`

### What happened instead?
Got this messages from vim
```
vim-go: [gorename] dispatched
vim-go: job command: ['/Users/vince.dang/go/bin/gorename', '-offset', '/Users/vince.dang/go/src/.../src/middleware/middleware.go:#1052', '-to', 'hello', '-tags', '']
vim-go: [gorename] FAIL
"/usr/local/go/src/unicode/utf8/utf8.go" [readonly] 523L, 14427C
```
Seems the job command is still `gorename` instead of `gopls` as I set in `~/.vimrc`
Checking from vim command line shows the variable has been set
```
:let g:go_rename_command
g:go_rename_command    gopls
```

In another attempt, I tried to set another global variable
```
let g:go_gorename_bin = "gopls"
```
This time the command printed out in vim `:messages` is `gopls` as expected, but the flags seems wrong, as it's still using `-offset` for `gorename`
```
vim-go: [gorename] dispatched
vim-go: job command: ['/Users/vince.dang/go/bin/gopls', '-offset', '/Users/vince.dang/go/src/git.garena.com/shopee/pl/spm_wsa/src/middleware/middleware.go:#1044', '-to', 'fuck', '-tags', '']
vim-go: [gorename] FAIL
```

### Configuration (**MUST** fill this out):

* vim-go version:
not sure how to check the vim-go version, please advise~

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
set clipboard=unnamed

" Vanilla VIM features
set path+=**
set wildmenu
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=',\(^\|\s\s\)\zs\.\S+'

set relativenumber
set number
set cursorline
set cursorcolumn

" Enable mouse selection
set mouse=r
" Auto-indentation
set autoindent
" set smartindent

" Paste
set pastetoggle=<f5>

" Don't try to be vi compatible
set nocompatible

" For Go
set rtp+=$GOPATH/src/golang.org/x/lint/misc/vim
autocmd BufWritePost,FileWritePost *.go execute 'Lint' | cwindow
let g:go_fmt_command = "goimports"
let g:go_rename_command = "gopls"
let g:go_debug = ['shell-commands']
```

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  8 2020 00:57:48)
macOS version
Included patches: 1-100

* Go version (`go version`):
go version go1.14.2 darwin/amd64

* Go environment (`go env`):
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vince.dang/Library/Caches/go-build"
GOENV="/Users/vince.dang/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/vince.dang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/vince.dang/go/src/.../go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g3/f4snpt0n1js0vtrjzxwrllldwdrl6p/T/go-build557974267=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bhcleek** [comment]
This is quite strange. I've checked the git history fo the code and don't see any revision that would explain what you're seeing here.

> not sure how to check the vim-go version, please advise~

It really depends on how you install and manage vim-go. Often you can cd into the directory where you have vim-go's source and run `git rev-parse HEAD` to see the revision.

**Comment by orlangure** [comment]
I'm seeing something similar after `:GoRename`:
```
vim-go: [gorename] dispatched
vim-go: [gorename] SUCCESS
```
But after this `SUCCESS`, wrong variable is renamed, one that is a few lines below.
I'm using the most recent vim, vim-go and all the binaries.

**Comment by captainviet** [comment]
I installed vim-go from Vundle, here's the commit found from `~/.vim/bundle/vim-go`
```
>> git rev-parse HEAD
9a4f21e5343437bdb4619f19b48cbf6d5cb7755c
```
Looks like `v1.22` from https://github.com/fatih/vim-go/commit/9a4f21e5343437bdb4619f19b48cbf6d5cb7755c

> This is quite strange. I've checked the git history fo the code and don't see any revision that would explain what you're seeing here.

oh from this version seems the command is fixed as
```vim
  let cmd = [bin_path, "-offset", offset, "-to", to_identifier, '-tags', go#config#BuildTags()]
```
instead of different commands for `gorename` and `gopls` as in https://github.com/fatih/vim-go/blob/master/autoload/go/rename.vim

maybe I can try installing the latest version of vim-go?

**Comment by bhcleek** [comment]
v1.22 is the latest release. And it does have the ability to use either `gorename` or `gopls` for renaming: https://github.com/fatih/vim-go/blob/v1.22/autoload/go/rename.vim#L36-L43. If you don't see the same source in your vim-go directory, then you're using an older version of vim-go.

Based on what you've told me so far, I suspect that you may have multiple versions of vim-go installed and an older one is being loaded first, preventing the newer one from being loaded. You can check to see where it's being loaded from using the instructions at https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2453-L2462 and then checking to see which revision it is.

Feel free to try latest master.

**Comment by captainviet** [comment]
actually from the commit link above I'm not sure which version, as it mentioned both `v1.20` and `v1.22` in the titlle

anw, after running `:PluginUpdate` to install the latest version, `GoRename` works as expected, the command printed in shell is `gopls`
```vim
vim-go: [gorename] dispatched
vim-go: job command: ['/Users/vince.dang/go/bin/gopls', 'rename', '-w', '/Users/vince.dang/go/src/...spm_wsa/src/structs/structs.go:#103', 'NewName']
vim-go: [gorename] SUCCESS
```

thanks a lot for your help!
