### ISSUE TITLE
go_imports_mode not adding/removing imports

### ISSUE THREAD

**Issue by salarkhan** [fatih/vim-go#2878]
### What did you do? (required: The issue will be **closed** when not provided)
opened a go file:
```
package main
import (
        "fmt"
        "time"
)

func main() {
        value := "string"
        //value := time.Now()
        fmt.Println(value)
}
```
and `:w` the file

### What did you expect to happen?
expected `time` to be removed

### What happened instead?
`time` was not removed. it is removed if i call `:GoImports`

#### vim-go version:
https://github.com/fatih/vim-go/releases/latest

####  `vimrc` you used to reproduce:
<details><summary>vimrc</summary><br><pre>
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
" ---------------------------------
let g:go_fmt_command = "gopls"
let g:go_imports_mode = "gopls"
</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):

#### Go version (`go version`):
go version go1.12 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/salarkhan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/salarkhan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build253236978=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=</pre></details>

**Comment by bhcleek** [comment]
Writing won't add or remove imports with the configuration you have. Add `let g:go_imports_autosave=1` to your vimrc and it should, though.

**Comment by salarkhan** [comment]
wowwwwww guess i should RTFM. sorry for wasting your time, and thanks again!
