### ISSUE TITLE
ErrCheck (GoErrCheck) doesn't work

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#288]
When `:GoErrCheck` I just get the file I'm working on printed to screen followed by an:
```vim
GoErrCheck returned error
```
WAT.
![](http://mybroadband.co.za/vb/attachment.php?attachmentid=71940&d=1379691163)

**Comment by fatih** [comment]
Can you please pull the latest master and try again? We wasn't checking for packages which were not inside the GOPATH or is not a valid import path, which is a requirement for `errcheck`. It now displays an error if you run it on an invalid file. I've also fixed some quirks (displaying an error if there were none).

**Comment by oryband** [comment]
@fatih Yay! Now works. ErrCheck is slow though - takes 2 seconds for results to return on a very small codebase (<1000 lines)
