### ISSUE TITLE
Feature: :A/:AS/:AV shortcuts for :GoAlternate

### ISSUE THREAD

**Issue by cofyc** [fatih/vim-go#2880]
like [a.vim](https://github.com/vim-scripts/a.vim)

- `:A` is short for `:GoAlternate`
- `:AS` splits and switches between main and test files
- `:AV` vertical  splits and switches between main and test files

what do you think?

**Comment by bhcleek** [comment]
All vim-go command start with `:Go`, and I believe it should remain so. I think what you're looking for, though, is a way to cause those commands to execute with minimal typing. Vim-go has mappings for just that: https://github.com/fatih/vim-go/blob/master/ftplugin/go/mappings.vim#L80-L82.

You can configure your Vim to use those mappings with a key combination of your choice. An example is provided in the help file: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L931-L939
