### ISSUE TITLE
want mechanism to set extra environment variables when running gopls

### ISSUE THREAD

**Issue by dhduvall** [fatih/vim-go#2885]
### What did you do? (required: The issue will be **closed** when not provided)

I load up a Go source file and hit `^]` to take me to the definition of a function in a dependent module.

### What did you expect to happen?

Well, **want**, not expect. I have a per-repo module cache, which I need to tell the Go tools about with `$GOPATH`. I want the jump to take me to that cache (since that's what's used in the build), rather than the cache in `$HOME/go`.

### What happened instead?

It took me to the source file in `$HOME/go`.

When I set `$GOPATH` appropriately and `GO111MODULE=on` (the latter needed because I'm still running Go 1.12) before running vim, those environment variables were present in the environment of `gopls`, and it took me to the right place.  If I change the setting `l:opts` in `s:newlsp()` to add the `env` key with those two environment variables in the value dict, it also works. But I don't have a way to do that without modifying the `vim-go` source. It'd be nice to set some variable in my `.vimrc` and have it apply to the `gopls` job. I don't think there's any way for `vim-go` to figure out what I need automatically.

#### vim-go version:

620d285ff6ea6a563f640af25938d511f25e076f

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 14 2020 23:46:42)
Included patches: 1-259
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):
1.12.15

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/duvall/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/duvall/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/net.b10e/go-1.12.15"
GOTMPDIR=""
GOTOOLDIR="/opt/net.b10e/go-1.12.15/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/duvall/b10e/Product-mod/golang/src/bg/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build214232677=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
</pre></details>

**Comment by bhcleek** [comment]
Applying GOPATH and GO111MODULE only to gopls would leave other tools (e.g. `godef`, `guru`, etc.) in a different state. May I ask why you don't set those before or when starting vim so that they'll be set for all tools?

You might be interested in https://direnv.net/: I use it regularly partially for the kind of use case you're describing here.

**Comment by dhduvall** [comment]
I can set them before starting vim, or in my `.vimrc`; that's probably a better solution for the reasons you suggest. I hadn't really thought about the other tools, because either I don't end up using them, or I haven't run into any issues they might have with my setup.
