### ISSUE TITLE
g:go_imports_autosave and g:go_fmt_autosave do not work together

### ISSUE THREAD

**Issue by piersy** [fatih/vim-go#2889]
### What did you do? (required: The issue will be **closed** when not provided)

I used the following  init.vim and saved a file with potential simplifications and missing imports
```vim
call plug#begin()
Plug 'fatih/vim-go', {'tag': 'v1.23' }
call plug#end()

let g:go_imports_autosave=1
let g:go_fmt_autosave = 1
let g:go_fmt_options = {
  \ 'gofmt': '-s',
  \ }
```

I also tried the following configuration suggested by @bhcleek 
https://github.com/fatih/vim-go/pull/2867#issuecomment-624863214

But experienced the same result.

### What did you expect to happen?
Both imports and fmt with simplifications to be applied.
### What happened instead?
The imports were added but the simplifications were not applied.
####  `vimrc` you used to reproduce:
```vim
call plug#begin()
Plug 'fatih/vim-go', {'tag': 'v1.23' }
call plug#end()

let g:go_imports_autosave=1
let g:go_fmt_autosave = 1
let g:go_fmt_options = {
  \ 'gofmt': '-s',
  \ }
```
#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.13.8 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pierspowlesland/.cache/go-build"
GOENV="/home/pierspowlesland/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pierspowlesland/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pierspowlesland/projects/autonity/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build040175437=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_fmt_options = {'gofmt': '-s'}
g:go_imports_autosave = 1
g:go_fmt_autosave = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
try adding `let g:go_imports_mode='gopls'` to your vimrc; that should do the imports with `gopls` and then the formatting with `gofmt`, giving you the result you want.

What I hadn't noticed clearly in https://github.com/fatih/vim-go/pull/2867#issuecomment-624863214 was that you desire to adjust imports and simplify the code. `goimports` doesn't have an option simplify and `gofmt` won't adjust imports, but because the two operations are distinct with `gopls`, using `gopls` for adjusting imports and `gofmt` for formatting should be what you need.

**Comment by piersy** [comment]
@bhcleek That works thanks.

I think it would be useful to update the help with a clear description of how these 2 settings interact and maybe an example of this config, since it seems like a setting most people would want but it's quite tricky to get it set up correctly.

Just for clarity, this is the `init.vim` that worked for me.
```vim
call plug#begin()
Plug 'fatih/vim-go', {'tag': 'v1.23' }
call plug#end()

let g:go_imports_mode='gopls'
let g:go_imports_autosave=1
let g:go_fmt_autosave = 1
let g:go_fmt_options = {
  \ 'gofmt': '-s',
  \ }
```

**Comment by bhcleek** [comment]
Agreed. I'll update the docs this weekend
