### ISSUE TITLE
Cannot import absolute Path

### ISSUE THREAD

**Issue by digitaico** [fatih/vim-go#2894]
Hi,  thanks for such an awesome plugin.

I have an issue that say this: 

`runner] Can't run linter goanalysis_metalinter: asmdecl: analysis skipped: errors in package: [-: import \"/path to my folder\": cannot import absolute path]`

`Running error: asmdecl: analysis skipped: errors in package: [-: import \"/path to my folder\": cannot import absolute path]  `

I can :GoInstallBinaries without issue,  even build and run,  however this error is recurrent,  and don't get how to fix it.  
This is my go env
`GO111M

- ODULE=""
- GOARCH="amd64"
- GOBIN=""
- GOCACHE="/home/jea/.cache/go-build"
- GOENV="/home/jea/.config/go/env"
- GOEXE=""
- GOFLAGS=""
- GOHOSTARCH="amd64"
- GOHOSTOS="linux"
- GONOPROXY=""
- GONOSUMDB=""
- GOOS="linux"
- GOPATH="/home/jea/go"
- GOPRIVATE=""
- GOPROXY="https://proxy.golang.org,direct"
- GOROOT="/usr/local/go"
- GOSUMDB="sum.golang.org"
- GOTMPDIR=""
- GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
- GCCGO="gccgo"
- AR="ar"
- CC="gcc"
- CXX="g++"
- CGO_ENABLED="1"
- GOMOD=""
- CGO_CFLAGS="-g -O2"
- CGO_CPPFLAGS=""
- CGO_CXXFLAGS="-g -O2"
- CGO_FFLAGS="-g -O2"
- CGO_LDFLAGS="-g -O2"
- PKG_CONFIG="pkg-config"
- GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build353071874=/tmp/go-build -gno-record-gcc-switches"

`
and go $PATH, 
`go 
 /home/jea/.local/bin:/home/jea/.sdkman/candidates/kotlin/current/bin:/usr/local/bin:/opt/firefox/firefox:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin:/opt/android-studio/bin:/usr/local/go/bin:/usr/bin:/home/jea/.local/bin:/home/jea/software/CSDTK/bin:/home/jea/software/CSDTK/mingw32/usr/bin:/home/jea/software/CSDTK/mips-rda-elf/bin:/home/jea/software/CSDTK/rv32-elf/bin:/home/jea/software/CSDTK/bin/mips-elf-gcc:/home/jea/software/CSDTK/cooltools/libcoolhost_library.so:/home/jea/software/CSDTK/cooltools:/sbin/ldconfig:/opt/intelliIdea/bin/: unknown command
`

**Comment by bhcleek** [comment]
Something in your dependency graph is using an absolute path in an import statement. Try running golangci-lint at the command line; it might help you identify what it is

**Comment by digitaico** [comment]
bash does not recognize the command golangci-lint,  nor go golangci-lint,  also tried :golangci-lint from vim, always not recognized command.  Even, traying to install golanci-lint,  does not exist on debian packages.  Mine is Linux, Debian buster (10) linux 4.19.0-9.

**Comment by bhcleek** [comment]
It's probably in your `$GOPATH/bin`. Check `/home/jea/go/bin` to see if `golangci-lint` is there.

If you want to see the exact command to run, add `let g:go_debug=['shell-commands']` to your vimrc. The commands that vim-go runs will be output as an array so you can see each of the individual argument that vim-go uses to run the application.

**Comment by bhcleek** [comment]
@digitaico do you need more help or should we close this?
