### ISSUE TITLE
Error with paths executing GoRun

### ISSUE THREAD

**Issue by allesan** [fatih/vim-go#2896]
### What did you do? (required: The issue will be **closed** when not provided)
I'm trying to read file from the disk that is located in the root of my go code with this.
`file, err := ioutil.ReadFile("./config.json")`

### What did you expect to happen?
Application to run smoothly.

### What happened instead?
I got error for files that are reading from disk with relative path saying that file config.json is not found.
If I give absolute path of the file to the ioutil.ReadFile() everything is working fine.

### Configuration (**MUST** fill this out):
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_structs = 1
let g:go_code_completion_enabled = 1
let g:go_rename_command = 'gopls'
let g:go_fmt_command = 'gopls'
let g:go_list_type = "quickfix"
map <F8> :silent<CR>:GoRun main.go<CR>

#### vim-go version:
1.23
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):
8.2

#### Go version (`go version`):
1.14

**Comment by bhcleek** [comment]
To help you solve this, I need reproduction steps as explicitly stated as a requirement in the issue template. I'll leave this open until tomorrow to give you a chance to fill out the first piece of information requested in the issue template with clear reproduction steps.

**Comment by allesan** [comment]
I have updated my answer. Sorry for not filling all the required steps.

**Comment by bhcleek** [comment]
The working directory will be the directory that contains the active buffer when you execute `:GoRun`. Does that help?

**Comment by allesan** [comment]
Yeah, it's working if I run GoRun when main.go is open!
What gives? 
In 1.22 this has worked from any buffer.

**Comment by bhcleek** [comment]
Without knowing what your directory/package structure is and which files it doesn't work from, it's difficult to say. If you can provide clear instructions for duplicating, I'm sure we can solve it

**Comment by allesan** [comment]
Well, this is root of my project
config.json  database  go.mod  go.sum  main.go  models  routes  utils

I'm using gin as my router.

And GoRun works only when I run it when main.go is the active buffer. Not from any other file. And it used to work from every other file as well.

**Comment by bhcleek** [comment]
Which file are you in when it doesn't work?

**Comment by allesan** [comment]
Only this

open ./config.json: no such file or directory

**Comment by allesan** [comment]
> Which file are you in when it doesn't work?

Any other file in the directories. I have several subdirectories in models, and 1-2 files in routes, utils and database.

**Comment by allesan** [comment]
Well, now I noticed that it works also when I'm in config.json file.
So, it works only when I'm in the file that is in the root of the project, and that are only main.go and config.json.

**Comment by bhcleek** [comment]
The working directory for your executable will always be the directory that contains the active buffer when you execute `:GoRun`.

**Comment by allesan** [comment]
Okay, I understand that. But this was not the case with 1.22
Can I "fix" this somehow? What has changed?
Or do I have to downgrade to 1.22?

**Comment by bhcleek** [comment]
It was changed in #2755 

There's nothing for you to fix other than your code; generally speaking, one shouldn't hard code a relative path into a binary, because binaries can be executed with any directory set as the working directory.

**Comment by allesan** [comment]
In this case I don't have other option. 
This is very unfortunate for me, because this renders GoRun useless for me.
I'll try to find some workaround.

Thanks for your help!

**Comment by bhcleek** [comment]
Some options to help you along:
* give your application a flag that specifies where the `config.json` can be found
OR
* get the path to your `config.json` from an environment variable
* put the `config.json` in a well-known location and use an absolute path in your `ioutil.ReadAll` call.
