### ISSUE TITLE
GoMetaLinter using golangci-lint doesn't work complaining about absolute path imports

### ISSUE THREAD

**Issue by turbopape** [fatih/vim-go#2901]
### What did you expect to happen?
When I run :GoMetaLinter I should have reports about my code in quickfix

### What happened instead?
I get this message:
|| [runner] Can't run linter goanalysis_metalinter: errcheck: analysis skipped: errors in package: [-: import \"/Users/turbopape/work/osprey/go/test\": cannot import absolute path]

The job command is: 

['/Users/turbopape/work/osprey/go/bin/golangci-lint', 'run', '--print-issued-lines=false', '--build-
tags', '', '--exclude-use-default=false', '--disable-all', '--enable=vet', '--enable=errcheck', '--deadline=30s', '/Users
/turbopape/work/osprey/go/test']

If I coerce GoMetalinter to run on that exact file: 

:GoMetaLinter /Users/turbopape/work/osprey/go/test/main.go it works.

also, golangci-linter works fine in shell if I don't use absolute paths.

I imagine I have to change the command to no use all the path in the golangci-lint command generated by vim-go, but I can't figure out how.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" vim-go
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
let g:go_fmt_command = "goimports"

" Map error items navigation
map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

" Only show in quickfix
let g:go_list_type = "quickfix"
autocmd FileType go nmap <leader>b  <Plug>(go-build)
autocmd FileType go nmap <leader>r  <Plug>(go-run)

" Check configs
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave_enabled = ['vet', 'errcheck']
let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = "30s"
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.14.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/turbopape/work/osprey/go/bin"
GOCACHE="/Users/turbopape/Library/Caches/go-build"
GOENV="/Users/turbopape/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/turbopape/work/osprey/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l8/lps8w6l14_l6crhfdr1vjvfw0000gn/T/go-build747583073=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_list_type = 'quickfix'
g:go_metalinter_deadline = '30s'
g:go_metalinter_autosave_enabled = ['vet', 'errcheck']
g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
g:go_metalinter_autosave = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
One of the files in `/Users
/turbopape/work/osprey/go/test` probably as a leading slash on an import statement.

What do you see if you run `/Users/turbopape/work/osprey/go/bin/golangci-lint run --print-issued-lines=false --build-
tags '' --exclude-use-default=false --disable-all --enable=vet --enable=errcheck --deadline=30s /Users
/turbopape/work/osprey/go/test` in a shell?

vim-go must use absolute paths to make sure that the path is correct.

**Comment by turbopape** [comment]
No there's actually only one file, with only one import statement (the one in the vimg-go tutorial)
The command you've shared outputs:
```shell
 [runner] Can't run linter goanalysis_metalinter: errcheck: analysis skipped: errors in package: [-: import "/Users/turbopape/work/osprey/go/test": cannot import absolute path]
ERRO Running error: errcheck: analysis skipped: errors in package: [-: import "/Users/turbopape/work/osprey/go/test": cannot import absolute path]
```

**Comment by bhcleek** [comment]
I've tried duplicating this, but can't except for when an import statement has a leading slash. I updated golangic-lint to the latest using `:GoUpdateBinaries golangci-lint` and tried again, but the results didn't change.

I noticed, though, that your directory doesn't seem to be in the right place. It's at $GOPATH/test, but that's generally not where Go code belongs. code within $GOPATH is expected to be below $GOPATH/src. (though I can't duplicate the problem you're seeing regardless of where the code is).

Given the error you're seeing on the commandline, it really does look like you have a leading slash in an import statement in some Go file in /Users/turbopape/work/osprey/go/test. If that's not the case, then I'd suggest updating to the latest golangci-lint using `:GoUpdateBinaries golangci-lint` and trying again. If that still doesn't fix the problem, then it's appropriate to create an issue for golangci-lint given that vim-go is correctly reporting golangci-lint's output: https://github.com/golangci/golangci-lint/issues.

Finally, you might consider avoiding golangci-lint altogether by using golpls for metalinting. Here's what I run in my own personal config:
```
let g:go_metalinter_command = 'gopls'
let g:go_gopls_staticcheck = 1
```

**Comment by turbopape** [comment]
Thank you so much for your help :)
The folder test really does only contain one single main.go with the code I shared - no imports with leading slash.
I updated the binaries so many times before I filed the issue, retired now but can still to no avail ...
I think I'll go ahead and use gopls like you suggested.
Thank you so much for your efforts and your time again :)

**Comment by bhcleek** [comment]
@turbopape this has come up a few times recently, but no one has been able to provide a set of steps that I can use to duplicate the problem.

I'm curious if you have any other go files in your $GOPATH anywhere. If so, can you check to see if any of them have a leading slash in the import statements?

**Comment by turbopape** [comment]
@bhcleek I checked all my code under $GOPATH and did find no import with a leading slash.
Besides, I created an empty folder, set the GOPATH to it and checked. Still the same: Cannot import /Current/Path ...

**Comment by turbopape** [comment]
@bhcleek moving my code under $GOPATH/src made golangci-lint work. apparently this is assumed but is referred nowhere ... 
Thank you :)

**Comment by bhcleek** [comment]
I still can't duplicate what the errors you're seeing, but it seems like the problem lies with golangci-lint.

FWIW, you _should_ be able to work with Go code outside of $GOPATH/src. In that case you'll need an ambient `go.mod` file to be able to import anything other than the standard library or relatiave imports. Some community provided tools may not work well when neither in GOPATH mode nor module aware mode.

In any case, since you've resolved this on your end and the underlying tool issue doesn't lie with vim-go, I'm going to close this unless you think there's something more I can do to help.

**Comment by turbopape** [comment]
Hey, thank you for your help. I THink you can go ahead and close the issue,
thank you:)

Le dim. 31 mai 2020 à 15:28, Billie Cleek <notifications@github.com> a
écrit :

**Comment by jkamdjou** [comment]
I had the same issue described by @turbopape. I was running outside of my $GOPATH/src, and solved it by creating a `go.mod` (eg `go mod init foo`) in that directory. Thanks for your suggestion @bhcleek
