### ISSUE TITLE
(go-def-vertical/split) doesn't open a split when jumping to a different place in same file [NeoVim]

### ISSUE THREAD

**Issue by ahouseago** [fatih/vim-go#2911]
### What did you do? (required: The issue will be **closed** when not provided)
In NeoVim, I used the `(go-def-vertical)` mapping to jump to a definition of a function defined in the same file in a vertical split:
```vim
autocmd FileType go nnoremap <buffer> <localleader>dv :<C-U>call go#def#Jump("vsplit", 0)
```

The same as `<Plug>(go-def-vertical)` except without immediately invoking it, waiting for me to hit `<CR>` before jumping.

### What did you expect to happen?
The file would be opened again in a new vertical split and it would jump to the function definition, like using `:vsplit` then `:GoDef`.

### What happened instead?
A split was not opened, and instead it jumped to the definition in the current buffer.

#### vim-go version:
Latest (not sure how to check, but used `:PlugUpdate` before submitting this.
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
let g:go_def_mapping_enabled = 0
augroup GoStuff
  autocmd!
  autocmd FileType go nmap <buffer> <localleader>h <Plug>(go-describe)
  autocmd FileType go nnoremap <buffer> <localleader>dd :<C-U>call go#def#Jump('', 0)
  autocmd FileType go nnoremap <buffer> <localleader>dx :<C-U>call go#def#Jump("split", 0)
  autocmd FileType go nnoremap <buffer> <localleader>dv :<C-U>call go#def#Jump("vsplit", 0)
  autocmd FileType go nnoremap <buffer> <localleader>dt :<C-U>call go#def#Jump("tab", 0)
augroup end
call plug#begin('~/.local/share/nvim/plugged')
  Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
let g:go_fmt_command = "goimports"
let g:go_auto_sameids = 1
let g:go_updatetime = 100
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.14.3 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ahouseago/Library/Caches/go-build"
GOENV="/Users/ahouseago/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ahouseago/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ahouseago/go/src/github.com/org/repo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yv/v4z5w9952qg56_ky2ysm1s540000gp/T/go-build908039345=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_updatetime = 100
g:go_auto_sameids = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
g:go_def_mapping_enabled = 0
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Yes, when the definition is in the same buffer, the buffer is not split. If that's what you want then perhaps the right solution for you is modify your mapping to split first and use `''` as the first argument to `go#def#Jump`.

**Comment by bhcleek** [comment]
FWIW, calling `go#def#Jump` directly isn't officially supported. Consider using the mappings. For your current mapping that would be:
```
autocmd FileType go nnoremap <buffer> <localleader>dv <Plug>(go-def-vertical)
```

**Comment by ahouseago** [comment]
Ok, if it's intentional that the split versions don't split if jumping in the same buffer then this is not a bug 🙂 I'll look into updating my mapping to split first.

The reason I don't use the `<Plug>(go-def-vertical)` mapping was because I use a similar mapping for other file types that doesn't include the `<CR>` at the end and was aiming for consistency!
