### ISSUE TITLE
ch_sendraw(): write failed

### ISSUE THREAD

**Issue by 9mm** [fatih/vim-go#2912]
### What did you do? (required: The issue will be **closed** when not provided)

I opened a file (in both Vim and MacVim)

### What did you expect to happen?

No error

### What happened instead?

When opening a .go file, I get this error:

<img width="1037" alt="Screen Shot 2020-06-08 at 11 33 08 AM" src="https://user-images.githubusercontent.com/1386207/84067358-2df08e00-a97c-11ea-9f27-0f8eac6ba233.png">

####  `vimrc` you used to reproduce:

I deleted everything out of my .vimrc except plug (to load vim-go) and it still happens.

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 26 2020 06:16:44)
macOS version
Included patches: 1-539

#### Go version (`go version`):

go version go1.14.3 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zesty/Library/Caches/go-build"
GOENV="/Users/zesty/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zesty/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zesty/Code/router/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/38/37ysgzs118j3q38m2ttn1j300000gn/T/go-build092737874=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.1.2
    golang.org/x/tools/gopls@v0.1.3 h1:CB5ECiPysqZrwxcyRjN+exyZpY0gODTZvNiqQi3lpeo=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_gotags_bin = 'gotags'
g:go_jump_to_error = 1
g:go_fmt_command = 'goimports'
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by rolfbachmann** [comment]
Same probleme here, on Linux too.

Vim Version: 8.2.935
Go Version: go version go1.14.4 linux/amd64
gopls version: golang.org/x/tools/gopls v0.1.7
    golang.org/x/tools/gopls@v0.1.7 h1:YwKf8t9h69++qCtVmc2q6fVuetFXmmu9LKoPMYLZid4=

**Comment by bhcleek** [comment]
Try a new version of `gopls`: `:GoUpdateBinaries gopls`.

Your version of `gopls` is long out of date and a lot has changed since the version that you're using.

**Comment by 9mm** [comment]
ah interesting, I didnt know I had to run that. Thanks
