### ISSUE TITLE
Error detected while processing function <SNR>37_register[9]

### ISSUE THREAD

**Issue by scrawld** [fatih/vim-go#2916]
After I updated Vim-Go, the following error occurred when I opened the file
```
vim-go: initializing gopls
Error detected while processing function <SNR>37_register[9]..go#lsp#DidOpen[29]..312[29]..315:
line   15:
E631: ch_sendraw(): write failed
Press ENTER or type command to continue
```

**Comment by bhcleek** [comment]
There is not enough detail here to analyze the problem. Please feel free to open a new issue that provides the information the issue template asks for.
