### ISSUE TITLE
Error after update  E631: ch_sendraw(): write failed

### ISSUE THREAD

**Issue by scrawld** [fatih/vim-go#2919]
### What did you expect to happen?

After I updated VIM-GO, I hope it can be used normally

### What happened instead?

An error has been reported in the.go file after updating

	vim-go: initializing gopls
	Error detected while processing function <SNR>37_register[9]..go#lsp#DidOpen[29]..282[29]..285:
	line   15:
	E631: ch_sendraw(): write failed
	Press ENTER or type command to continue

####  `vimrc` you used to reproduce: I've tried

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

	VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 17 2020 18:24:00)
	Included patches: 1-587
	Compiled by jiayd163@163.com
	Huge version without GUI.  Features included (+) or not (-):
	+acl               +cindent           +cursorshape       +file_in_path      +job               +menu              +mouse_urxvt       +popupwin          +signs             -tcl               +vartabs           -X11
	+arabic            -clientserver      +dialog_con        +find_in_path      +jumplist          +mksession         +mouse_xterm       +postscript        +smartindent       +termguicolors     +vertsplit         -xfontset
	+autocmd           -clipboard         +diff              +float             +keymap            +modify_fname      +multi_byte        +printer           -sound             +terminal          +virtualedit       -xim
	+autochdir         +cmdline_compl     +digraphs          +folding           +lambda            +mouse             +multi_lang        +profile           +spell             +terminfo          +visual            -xpm
	-autoservername    +cmdline_hist      -dnd               -footer            +langmap           -mouseshape        -mzscheme          -python            +startuptime       +termresponse      +visualextra       -xsmp
	-balloon_eval      +cmdline_info      -ebcdic            +fork()            +libcall           +mouse_dec         -netbeans_intg     +python3           +statusline        +textobjects       +viminfo           -xterm_clipboard
	+balloon_eval_term +comments          +emacs_tags        -gettext           +linebreak         -mouse_gpm         +num64             +quickfix          -sun_workshop      +textprop          +vreplace          -xterm_save
	-browse            +conceal           +eval              -hangul_input      +lispindent        -mouse_jsbterm     +packages          +reltime           +syntax            +timers            +wildignore
	++builtin_terms    +cryptv            +ex_extra          +iconv             +listcmds          +mouse_netterm     +path_extra        +rightleft         +tag_binary        +title             +wildmenu
	+byte_offset       +cscope            +extra_search      +insert_expand     +localmap          +mouse_sgr         -perl              -ruby              -tag_old_static    -toolbar           +windows
	+channel           +cursorbind        -farsi             +ipv6              -lua               -mouse_sysmouse    +persistent_undo   +scrollbind        -tag_any_white     +user_commands     +writebackup
	   system vimrc file: "$VIM/vimrc"
	     user vimrc file: "$HOME/.vimrc"
	 2nd user vimrc file: "~/.vim/vimrc"
	      user exrc file: "$HOME/.exrc"
	       defaults file: "$VIMRUNTIME/defaults.vim"
	  fall-back for $VIM: "/usr/share/vim"
	Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
	Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo   -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

	GOARCH="amd64"
	GOBIN="/home/ziyang/etc/go/bin"
	GOCACHE="/home/ziyang/.cache/go-build"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH="/home/ziyang/etc/go:/home/ziyang/work/cms_oprate:/home/ziyang/work/cms_risk:/home/ziyang/work/coinutils:/home/ziyang/work/inquiry:/home/ziyang/work/notify_server:/home/ziyang/work/proxy_server:/home/ziyang/work/script_projects:/home/ziyang/work/user:/home/ziyang/work/walletbch:/home/ziyang/work/walletbsv:/home/ziyang/work/walletdoge:/home/ziyang/work/walletltc"
	GOPROXY="https://goproxy.io"
	GORACE=""
	GOROOT="/usr/local/go"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build629504418=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

	golang.org/x/tools/gopls v0.1.7
	    golang.org/x/tools/gopls@v0.1.7 h1:YwKf8t9h69++qCtVmc2q6fVuetFXmmu9LKoPMYLZid4=

</pre></details>

![avatar](https://s17.aconvert.com/convert/p3r68-cdx67/8f84t-aebdl.gif)

**Comment by bhcleek** [comment]
This may be due to the old `gopls` version that you have. Please try running `:GoUpdateBinaries gopls` and try again.

**Comment by scrawld** [comment]
The GoPLS version executed after the update said there was no such command, and vim opened the go file with the same error
```
ziyang@Dev-25:~$ gopls version
gopls: Unknown command version
The Go Language source tools.

Usage: gopls [flags] <command> [command-flags] [command-args]

Available commands are:
  serve : run a server for Go code using the Language Server Protocol
  query : answer queries about go source code

gopls flags are:
  -listen string
        address on which to listen for remote connections
  -logfile string
        filename to log to. if value is "auto", then logging to a default output file is enabled
  -mode string
        no effect
  -port int
        port on which to run gopls for debugging purposes
  -profile.cpu string
        write CPU profile to this file
  -profile.mem string
        write memory profile to this file
  -profile.trace string
        write trace log to this file
  -remote string
        *EXPERIMENTAL* - forward all commands to a remote lsp
```

**Comment by scrawld** [comment]
This error will still occur if you open a file or report an error
```
Error detected while processing function go#def#Jump[75]..go#lsp#Definition[1]..go#lsp#DidChange[24]..342[29]..345:
line   15:
E631: ch_sendraw(): write failed
```

**Comment by bhcleek** [comment]
Can you add `let g:go_debug=['shell-commands]` to you vimrc and report the command that it uses for the `gopls` invocation? Also, what does `which gopls` report from your commandline?

**Comment by scrawld** [comment]
These error messages appear
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
vim-go: job command: ['/home/ziyang/etc/go/bin/gopls', '-remote=auto']
vim-go: shell command: '/usr/local/go/bin/go' 'env' 'GOMOD'
vim-go: initializing gopls
Error detected while processing function <SNR>37_register[9]..go#lsp#DidOpen[29]..282[29]..285:
line   15:
E631: ch_sendraw(): write failed
vim-go: shell command: '/usr/local/go/bin/go' 'list' '-tags' '' '-f' '{{.Name}}'
vim-go: shell command: '/home/ziyang/etc/go/bin/goimports' '-w' '-srcdir' 'a.go' '/tmp/vrGvlOu/2.go'
vim-go: job command: ['/home/ziyang/etc/go/bin/gopls', '-remote=auto']
vim-go: shell command: '/usr/local/go/bin/go' 'env' 'GOMOD'
vim-go: initializing gopls
Error detected while processing function go#auto#fmt_autosave[23]..go#fmt#Format[65]..go#fmt#update_file[20]..go#lsp#DidChange[24]..297[29]..300:
line   15:
E631: ch_sendraw(): write failed
"a.go" 7L, 67C [w]
E492: Not an editor command: Error detected while processing function <SNR>37_register[9]..go#lsp#DidOpen[29]..282[29]..285:
2 fewer lines; before #3  2 seconds ago
Press ENTER or type command to continue
```

`which gopls` Execute command output
```
ziyang@Dev-25:~$ which gopls
/home/ziyang/etc/go/bin/gopls
```

**Comment by bhcleek** [comment]
I think the root of the problem you're experiencing is that your `gopls` is out of date. What was the output of `:GoUpdateBinaries gopls` ?

**Comment by phongvcao** [comment]
@bhcleek I got this issue and :GoUpdateBinaries gopls fixed the issue. Can you add an option to automatically run :GoUpdateBinaries gopls & related binaries when this issue happens? Probably put this in a try-catch block or smt. Thanks.

**Comment by bhcleek** [comment]
@phongvcao is not one that can always be easily detected. I do not intend to add an option that automatically reinstalls binaries.

It's a good idea to run `:GoUpdateBinaries` when you update vim-go or Go.

**Comment by scrawld** [comment]
I just use this command to update gopls
```
GO111MODULE=on go get golang.org/x/tools/gopls@v0.4.0
```
Perform `gopls version` output:
```
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
```
