### ISSUE TITLE
error setting breakpoint on second :GoDebugStart

### ISSUE THREAD

**Issue by cposture** [fatih/vim-go#2920]
# What did you do?

`~/go/src/code.byted.org/er/be_api_external` is the golang project root dir，I can use other vim-go commands normally.

Because the project is private and cannot be made public, I want to use other projects to reproduce the error, but the debug function works normally.

I open my project main.go file, and then use `:GoDebugStart`，then show debug window normal；And GoDebug Window output the message: 
```
ERR: 2020-06-12T10:44:09+08:00 debug layer=rpc API server pid = 85456
ERR: 2020-06-12T10:44:09+08:00 info layer=debugger launching process with args: [/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/voKnaK6/5]
ERR: 2020-06-12T10:44:10+08:00 warning layer=debugger could not set asyncpreemptoff <nil>
```
And I run continuly `:GoDebugContinue`，it occur other error， `:message`
```
vim-go: Process 85481 has exited with status 0
vim-go: Vim(return):E716: Dictionary 中不存在键: goroutineID
vim-go: Vim(return):E716: Dictionary 中不存在键: goroutineID
vim-go: [debug] SUCCESS
vim-go: [debug] dispatched
vim-go: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/
```

### Configuration
all: https://github.com/cposture/my-vim/blob/master/.vimrc
vim-go:
```
"=========================================
" vim-go 插件配置
"=========================================
" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction
autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
map <leader>] :cnext<CR>
map <leader>[ :cprevious<CR>
nnoremap <leader>[[ :cclose<CR>
autocmd FileType go nmap <leader>r  <Plug>(go-run)
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
"保存文件时自动 import package
let g:go_fmt_command = "goimports"
"高亮类型
"let g:go_highlight_types = 1
"高亮函数
"let g:go_highlight_functions = 1
"高亮操作符
let g:go_highlight_operators = 1
"保存时自动执行 'vet', 'golint', 'errcheck'
let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = "10s"
"自动展示光标下的类型信息
let g:go_auto_type_info = 1
"禁用自动跳转到第一个错误的代码，因为保存时检查错误就自动跳，有点烦
let g:go_jump_to_error = 0
```

#### vim-go version:
lastest

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  8 2020 00:19:54)
macOS version
包含补丁: 1-740
编译者 admin@MacBook-Pro.local
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl               +cmdline_info      -farsi             +langmap           +mouse_sgr         +profile           +tag_binary        +virtualedit
+arabic            +comments          +file_in_path      +libcall           -mouse_sysmouse    +python/dyn        -tag_old_static    +visual
+autocmd           +conceal           +find_in_path      +linebreak         +mouse_urxvt       +python3/dyn       -tag_any_white     +visualextra
+autochdir         +cryptv            +float             +lispindent        +mouse_xterm       +quickfix          -tcl               +viminfo
-autoservername    -cscope            +folding           +listcmds          +multi_byte        +reltime           +termguicolors     +vreplace
-balloon_eval      +cursorbind        -footer            +localmap          +multi_lang        +rightleft         +terminal          +wildignore
+balloon_eval_term +cursorshape       +fork()            -lua               -mzscheme          -ruby              +terminfo          +wildmenu
-browse            +dialog_con        +gettext           +menu              +netbeans_intg     +scrollbind        +termresponse      +windows
++builtin_terms    +diff              -hangul_input      +mksession         +num64             +signs             +textobjects       +writebackup
+byte_offset       +digraphs          +iconv             +modify_fname      +packages          +smartindent       +textprop          -X11
+channel           -dnd               +insert_expand     +mouse             +path_extra        -sound             +timers            -xfontset
+cindent           -ebcdic            +ipv6              -mouseshape        -perl              +spell             +title             -xim
-clientserver      +emacs_tags        +job               +mouse_dec         +persistent_undo   +startuptime       -toolbar           -xpm
+clipboard         +eval              +jumplist          -mouse_gpm         +popupwin          +statusline        +user_commands     -xsmp
+cmdline_compl     +ex_extra          +keymap            -mouse_jsbterm     +postscript        -sun_workshop      +vartabs           -xterm_clipboard
+cmdline_hist      +extra_search      +lambda            +mouse_netterm     +printer           +syntax            +vertsplit         -xterm_save
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
         $VIM 预设值: "/Users/admin/bin/vim-8.2/share/vim"
编译方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
链接方式: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -lintl -framework AppKit
```
#### Go version (`go version`):
go version go1.14.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/admin/go/bin"
GOCACHE="/Users/admin/Library/Caches/go-build"
GOENV="/Users/admin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="code.byted.org/*"
GONOSUMDB="code.byted.org/*"
GOOS="darwin"
GOPATH="/Users/admin/go"
GOPRIVATE="code.byted.org/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/admin/go/src/code.byted.org/er/be_api_external/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/go-build505328656=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_highlight_operators = 1
g:go_metalinter_deadline = '10s'
g:go_gotags_bin = 'gotags'
g:go_metalinter_autosave = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 0
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by cposture** [comment]
dlv debug command is normal, 
```
PSM=abc RUNTIME_IDC_NAME=efg  dlv debug -- -psm=abc -conf-dir=/Users/admin/go/src/code.byted.org/er/be_api_external/output/conf/ -log-dir=/Users/admin/go/src/code.byted.org/er/be_api_external/output/log
```
PSM and RUNTIME_IDC_NAME is my envrimonent

**Comment by bhcleek** [comment]
Have you set any breakpoints before running `:GoDebugStart` or `:GoDebugContinue`? It looks like your program may be running to completion after `:GoDebugContinue` without encountering any breakpoints. 🤔

**Comment by cposture** [comment]
yep，I set breakpoints  and find that Failed to load configuration，program exec os.Exit(-1) .The above error message misled me，you can reproduce the error with the flowing code：
```
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("vim-go")
	os.Exit(-1)
}
```
First don’t set any breakpoints, and then exec `: GoDebugStart`; then exec `: GoDebugContinue`, it will stuck in the line（os.Exit(-1)），what is it mean？why？

And I continue to exe `GoDebugContinue`, it show 
```
vim-go: Process 94191 has exited with status 0
vim-go: Process 94191 has exited with status 0
vim-go: Process 94191 has exited with status 0
vim-go: Process 94191 has exited with status 0
```
the same line duplicate 4 times，and  I continue to exe `GoDebugContinue`, it show 
```
vim-go: Process 94191 has exited with status 0
vim-go: [debug] SUCCESS
vim-go: could not find file /Users/admin/go/src/go_exit/
```
I hope it can express the error message more accurately，`vim-go: could not find file` misled me

**Comment by cposture** [comment]
And I want to konw how to inject enviroment like dlv to program when :GoDebugStart(PSM, RUNTIME_IDC_NAME)
```
PSM=abc RUNTIME_IDC_NAME=efg  dlv debug -- -psm=abc -conf-dir=/Users/admin/go/src/code.byted.org/er/be_api_external/output/conf/ -log-dir=/Users/admin/go/src/code.byted.org/er/be_api_external/output/log
```

**Comment by bhcleek** [comment]
Vim-go needs to do a better job communicating when the process being debugged exits; I'll work on improving that.

> First don’t set any breakpoints, and then exec : GoDebugStart; then exec : GoDebugContinue, it will stuck in the line（os.Exit(-1)），what is it mean？why？

When you don't set any breakpoints before running `:GoDebugContinue` the first time, vim-go will attempt to set a breakpoint on the current cursor line. When you ran `:GoDebugContinue`, I can only assume that you didn't have any breakpoints set and that vim-go therefore set a breakpoint on the line where your cursor was positioned, which was the `os.Exit(-1)` line.

> the same line duplicate 4 times

I can improve this , but the short answer is that you're seeing this line 4 times because there are four operations that vim-go tries to do and they're all returning an error because the process has exited.

> I continue to exe GoDebugContinue, it show
```
vim-go: Process 94191 has exited with status 0
vim-go: [debug] SUCCESS
vim-go: could not find file /Users/admin/go/src/go_exit/
```

I'm not sure about that file path, but the error about the process having exited is because the code being debugged originally ran to completion. Was the application you were debugging at `/Users/admin/go/src/go_exit/`?

**Comment by bhcleek** [comment]
> And I want to konw how to inject enviroment like dlv to program when :GoDebugStart(PSM, RUNTIME_IDC_NAME)

You can set environment variables in vim-go and they will be seen by the program being debugged:
```
:let $PSM='abc'
:let $RUNTIME_IDC_NAME='efg'
:GoDebugStart
```

**Comment by bhcleek** [comment]
I think that #2921 will handle most if not all of the concerns you raised here, though I'll admit that I'm not sure about the `could not find file` messages you reported.

Can you give #2921 a try and see if you believe it resolves this issue for you?

**Comment by cposture** [comment]
> I'm not sure about that file path, but the error about the process having exited is because the code being debugged originally ran to completion. Was the application you were debugging at `/Users/admin/go/src/go_exit/`?

`/Users/admin/go/src/go_exit/` is the project root, `/Users/admin/go/` is GoPath, file tree:
```
20-06-14 10:06 MacBook-Pro:~/go/src/go_exit(:|✔)
#ll
total 16
drwxr-xr-x   4 admin  staff   128B  6 12 13:43 .
drwxr-xr-x  17 admin  staff   544B  6 14 01:25 ..
-rw-r--r--   1 admin  staff    21B  6 12 13:42 go.mod
-rw-r--r--   1 admin  staff    91B  6 12 13:43 main.go
```

**Comment by cposture** [comment]
> I think that #2921 will handle most if not all of the concerns you raised here, though I'll admit that I'm not sure about the `could not find file` messages you reported.
> 
> Can you give #2921 a try and see if you believe it resolves this issue for you?

Ok thank you very much. i give it a try now, 
```
Plug 'bhcleek/vim-go', {'branch': 'debug/stop-on-exit'}
```

**Comment by cposture** [comment]
There is a breakpoint problem, it can be reproduced.

## context
`/Users/admin/go/src/go_exit/`  is project root dir, `/Users/admin/go/` is my GOPATH dir

main.go:
```
package main

import (
        "fmt"
        "os"
)

func main() {
        fmt.Println("vim-go")
        os.Exit(-1)
}
```

## problem
First  exec `: GoDebugStart`; and then set breakpoint on `os.Exit(-1)`, and then exec : `GoDebugContinue` two times.It quits as I hoped and Breakpoint mark exists normaly.

But When i continue to debug, exec `:GoDebugStart`, it ocour an error, 
message
```
vim-go: [debug] dispatched
vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/go_exit/
```
GODEBUG_OUTPUT window show:
```
ERR: 2020-06-14T10:31:52+08:00 debug layer=rpc <- RPCServer.CreateBreakpoint(rpc2.CreateBreakpointIn{"Breakpoint":{"id":0,"name":"","addr":0,"addrs":null,"file":"/Users/admin/go/src/go_exit/","line":10,"Cond":"","continue":false,"traceReturn":false,"goroutine":false,"stacktrace":0,"LoadArgs":null,"LoadLocals":null,"hitCount":null,"totalHitCount":0}})
ERR: 2020-06-14T10:31:52+08:00 debug layer=rpc -> *rpc2.CreateBreakpointOut{"Breakpoint":{"id":0,"name":"","addr":0,"addrs":null,"file":"","line":0,"Cond":"","continue":false,"traceReturn":false,"goroutine":false,"stacktrace":0,"LoadArgs":null,"LoadLocals":null,"hitCount":null,"totalHitCount":0}} error: "could not find file /Users/admin/go/src/go_exit/"
```
I think it should set breakpoint  on `/Users/admin/go/src/go_exit/main.go` not `/Users/admin/go/src/go_exit/` root dir.

**Comment by cposture** [comment]
The branch where the above problem occurs is bhcleek/vim-go'('branch': 'debug/stop-on-exit'})

**Comment by bhcleek** [comment]
I can't reproduce this. Can you do a screen recording and show me what you're doing starting from the commandline where you invoke vim?

**Comment by cposture** [comment]
https://drive.google.com/file/d/1SBG1pX1qVgNFYnhT02UoXMEVHxjP2Trs/view?usp=sharing

**Comment by bhcleek** [comment]
Thank you, @cposture . For some reason I'm still having a problem duplicating. Can I ask you for one more thing? Can you add `:let g:go_debug=['shell-commands']` to your vimrc, duplicate the problem, and then provide the output of `:messages` after you see the `vim-go: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/
Configuration` message?

**Comment by cposture** [comment]
Using your branch, it can not reproduce the error `vim-go: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/`, but has a new error `vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/`,

the fellow is message,  `:let g:go_debug=['shell-commands']` and use your branch

```
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: shell command: '/usr/local/go/bin/go' 'list'
vim-go: [debug] dispatched
vim-go: job command: ['/Users/admin/go/bin/dlv', 'debug', 'code.byted.org/er/be_api_external', '--output', '/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/vGUf90n/6', '--h
eadless', '--api-version', '2', '--listen', '127.0.0.1:8181', '--log', '--log-output', 'debugger,rpc', '--', '-conf-dir=/Users/admin/go/src/code.byted.org/er/be_api_external
/output/conf/', '-log-dir=/Users/admin/go/src/code.byted.org/er/be_api_external/output/log']
vim-go: [debug] SUCCESS
vim-go: shell command: '/usr/local/go/bin/go' 'list'
vim-go: [debug] dispatched
vim-go: job command: ['/Users/admin/go/bin/dlv', 'debug', 'code.byted.org/er/be_api_external', '--output', '/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/vGUf90n/8', '--h
eadless', '--api-version', '2', '--listen', '127.0.0.1:8181', '--log', '--log-output', 'debugger,rpc', '--', '-conf-dir=/Users/admin/go/src/code.byted.org/er/be_api_external
/output/conf/', '-log-dir=/Users/admin/go/src/code.byted.org/er/be_api_external/output/log']
vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/
```

**Comment by cposture** [comment]
Use fatih/vim-go and :let g:go_debug=['shell-commands'] reproduce the error` vim-go: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/`
![image](https://user-images.githubusercontent.com/8305198/84599081-fb75f200-aea1-11ea-9fcb-6a27e85b51d3.png)

**Comment by bhcleek** [comment]
It looks like you did that on master instead of on the branch for PR #2921 . Can you do it on #2921 instead, please?

**Comment by cposture** [comment]
> It looks like you did that on master instead of on the branch for PR #2921 . Can you do it on #2921 instead, please?

Yes, I specifically checkout the master branch，PR #2921  has fix the error

**Comment by bhcleek** [comment]
> Using your branch, it can not reproduce the error vim-go: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/, but has a new error vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/

> Yes, I specifically checkout the master branch，PR #2921 has fix the error

These ☝️  statements seem to be in conflict. Can you clarify if #2921 has a problem that we need to solve before merging it?

**Comment by cposture** [comment]
> Use fatih/vim-go and :let g:go_debug=['shell-commands'] reproduce the error` vim-go: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/`
> ![image](https://user-images.githubusercontent.com/8305198/84599081-fb75f200-aea1-11ea-9fcb-6a27e85b51d3.png)

Ignore it

**Comment by cposture** [comment]
> Using your branch, it can not reproduce the error `vim-go: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/`, but has a new error `vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/`,
> 
> the fellow is message, `:let g:go_debug=['shell-commands']` and use your branch
> 
> ```
> vim-go: initializing gopls
> vim-go: initialized gopls
> vim-go: shell command: '/usr/local/go/bin/go' 'list'
> vim-go: [debug] dispatched
> vim-go: job command: ['/Users/admin/go/bin/dlv', 'debug', 'code.byted.org/er/be_api_external', '--output', '/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/vGUf90n/6', '--h
> eadless', '--api-version', '2', '--listen', '127.0.0.1:8181', '--log', '--log-output', 'debugger,rpc', '--', '-conf-dir=/Users/admin/go/src/code.byted.org/er/be_api_external
> /output/conf/', '-log-dir=/Users/admin/go/src/code.byted.org/er/be_api_external/output/log']
> vim-go: [debug] SUCCESS
> vim-go: shell command: '/usr/local/go/bin/go' 'list'
> vim-go: [debug] dispatched
> vim-go: job command: ['/Users/admin/go/bin/dlv', 'debug', 'code.byted.org/er/be_api_external', '--output', '/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/vGUf90n/8', '--h
> eadless', '--api-version', '2', '--listen', '127.0.0.1:8181', '--log', '--log-output', 'debugger,rpc', '--', '-conf-dir=/Users/admin/go/src/code.byted.org/er/be_api_external
> /output/conf/', '-log-dir=/Users/admin/go/src/code.byted.org/er/be_api_external/output/log']
> vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/
> ```
https://github.com/fatih/vim-go/issues/2920#issuecomment-643709256

It was new problem using PR #2921

**Comment by bhcleek** [comment]
Your original error was `vim-go: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/`. The new error is `vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/code.byted.org/er/be_api_external/`, but if you look closely I think you'll see that the only difference in the old and new errors is some new text that I added in #2921. 

Since I can't duplicate this I need a couple things to help me get to the bottom of it (using the branch from #2921). First, I need a screen recording starting with the invocation of vim. Second, I need the output of `:messages` after duplicating the problem with `let g:go_debug=['shell-commands']` added to your vimrc.

**Comment by cposture** [comment]
https://drive.google.com/file/d/1raANwCPCslwr1gxIdjIgWeEAtRZrZ9HC/view?usp=sharing
message:
```
"main.go" 11L, 91C
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: [debug] dispatched
vim-go: job command: ['/Users/admin/go/bin/dlv', 'debug', '--output', '/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/vF8fQ94/5', '--headless', '--api-version', '2', '--li
sten', '127.0.0.1:8181', '--log', '--log-output', 'debugger,rpc']
vim-go: [debug] SUCCESS
vim-go: [debug] dispatched
vim-go: job command: ['/Users/admin/go/bin/dlv', 'debug', '--output', '/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/vF8fQ94/6', '--headless', '--api-version', '2', '--li
sten', '127.0.0.1:8181', '--log', '--log-output', 'debugger,rpc']
vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/go_exit/
```

**Comment by cposture** [comment]
Clearer video
https://drive.google.com/file/d/1iTK9G6pRgrW89WeR1r0JB1n8WrqQYeAf/view?usp=sharing

**Comment by bhcleek** [comment]
Thanks! That's what I needed. Unfortunately, though, I still can't duplicate the problem you're seeing. Clearly it works the first time, and I'm not sure what would change between the first and second runs that would cause an error when trying to toggle the breakpoint the second time.

I've pushed a temporary commit to #2921 that will show us exactly which line is causing an error. Can you run it again and let me know what the new error message is? It should be `vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/go_exit/` with some additional text.

**Comment by cposture** [comment]
> Thanks! That's what I needed. Unfortunately, though, I still can't duplicate the problem you're seeing. Clearly it works the first time, and I'm not sure what would change between the first and second runs that would cause an error when trying to toggle the breakpoint the second time.
> 
> I've pushed a temporary commit to #2921 that will show us exactly which line is causing an error. Can you run it again and let me know what the new error message is? It should be `vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/go_exit/` with some additional text.

This is new message after update vim-go
```
"main.go" 11L, 91C
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: [debug] dispatched
vim-go: job command: ['/Users/admin/go/bin/dlv', 'debug', '--output', '/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/vpXtqLl/5', '--headless', '--api-version', '2', '--li
sten', '127.0.0.1:8181', '--log', '--log-output', 'debugger,rpc']
vim-go: [debug] SUCCESS
vim-go: [debug] dispatched
vim-go: job command: ['/Users/admin/go/bin/dlv', 'debug', '--output', '/var/folders/rj/0rvtn98n2ys411yw3mr7118w0000gp/T/vpXtqLl/6', '--headless', '--api-version', '2', '--li
sten', '127.0.0.1:8181', '--log', '--log-output', 'debugger,rpc']
vim-go: could not toggle breakpoint: could not find file /Users/admin/go/src/go_exit/ (from function <SNR>178_out_cb[42]..go#debug#Breakpoint[35]..<SNR>178_call_jsonrpc，第
43 行)
```

**Comment by bhcleek** [comment]
Thank you. That confirms that the problem is coming from delve and not from Vim. Can you duplicate this problem using the delve cli?

Here are the basic operations you'd need to try to duplicate with the delve cli:
```
❯❯❯ cd $GOPATH/src/go_exit
❯❯❯ dlv debug go_exit
(dlv) b main.go:10
(dlv) continue
> main.main() main.go:10 (hits goroutine(1):1 total:1) (PC: 0x10c2773)
     5:         "os"
     6: )
     7:
     8: func main() {
     9:         fmt.Println("vim-go")
=>  10:         os.Exit(-1)
    11: }
(dlv) continue
(dlv) quit
❯❯❯ dlv debug go_exit
(dlv) b main.go:10
Breakpoint 1 set at 0x10c2773 for main.main() main.go:10
```

At that point you may see an error similar to what you're seeing in vim-go. If you do see that error, then `quit` should be sufficient to get you out of the delve cli. If you don't see the an error, then execute `continue` twice, the process should run to completion, and then you can exit the delve cli with `quit`.

Afterwards, you might also try updating delve with `:GoUpdateBinaries delve` and then see if the problem in vim-go persists.

**Comment by cposture** [comment]
dlv run normal

```
20-06-15 13:37 MacBook-Pro:~/go/src/go_exit(:|✔)
#dlv debug test
Type 'help' for list of commands.
(dlv) b main.go:10
Breakpoint 1 set at 0x10c26a3 for main.main() ./main.go:10
(dlv) continue
vim-go
> main.main() ./main.go:10 (hits goroutine(1):1 total:1) (PC: 0x10c26a3)
     5:         "os"
     6: )
     7:
     8: func main() {
     9:         fmt.Println("vim-go")
=>  10:         os.Exit(-1)
    11: }
(dlv) continue
Process 90430 has exited with status 255
(dlv) quit
20-06-15 13:38 MacBook-Pro:~/go/src/go_exit(:|✔)
#dlv debug test
Type 'help' for list of commands.
(dlv) b main.go:10
Breakpoint 1 set at 0x10c26a3 for main.main() ./main.go:10
(dlv) continue
vim-go
> main.main() ./main.go:10 (hits goroutine(1):1 total:1) (PC: 0x10c26a3)
     5:         "os"
     6: )
     7:
     8: func main() {
     9:         fmt.Println("vim-go")
=>  10:         os.Exit(-1)
    11: }
(dlv) continue
Process 90464 has exited with status 255
(dlv) quit
```

**Comment by cposture** [comment]
#dlv version
Delve Debugger
Version: 1.4.1
Build: $Id: bda606147ff48b58bde39e20b9e11378eaa4db46 $

**Comment by bhcleek** [comment]
Why did you run `dlv debug test` instead of `dlv debug go_exit`?

**Comment by cposture** [comment]
> Why did you run `dlv debug test` instead of `dlv debug go_exit`?

my module name is `test`, 
```
#cat go.mod
module test

go 1.14
```

**Comment by bhcleek** [comment]
After the first debugging session ends, can you execute `:sign place` and let me know what it outputs?

**Comment by cposture** [comment]
https://drive.google.com/file/d/12jlVR4j-6FUqcttgwzOKhyGV-ZH0YFa9/view?usp=sharing

**Comment by bhcleek** [comment]
Thank you @cposture. That explains the problem you're seeing.

The code to figure out the file name in which already placed signs exist so that breakpoints can be added examines the output from `sign place` to look for the filenames using `^Signs for `, which doesn't match your `sign place` output, so no filename is ever found.

On my machine `sign place` returns
```
Signs for main.go:
    line=10  id=1  name=godebugbreakpoint  priority=10
```

but on your machine it reads
```
main.go  <CHINESE CHARACTERS> Signs:
    line=10  id=1  name=godebugbreakpoint  priority=10
```

It's _possible_ that this is caused by your version of Vim. I know it works on my machine on version both before and after your version of Vim. Can you update to at least Vim 8.2.0950 and see if that resolves the issue for you?

**Comment by bhcleek** [comment]
I pushed a change to #2920 that I think will resolve the problem for you, but I don't know how to get a version of Vim that I can test it with. Can you give #2920 a try and let me know if it resolves the problem for you?

**Comment by bhcleek** [comment]
@cposture have you been able to try the latest changes on #2920?

**Comment by cposture** [comment]
Thank you for your reply，I will try later using lastest patch

**Comment by bhcleek** [comment]
@cposture I don't mean to be a bother, but I've been waiting to merge #2920 until I hear back from you in case there's more work to be done or the fix isn't quite right. Have you had a chance to try the latest on #2920?

**Comment by cposture** [comment]
yes, it may be cause by the output contained chinese charactor, my vim was built with souce code
I try with newest patch, but it show the same error, could not found file

```
--- Signs ---
main.go 的 Signs:
    line=10  id=1  name=godebugbreakpoint  priority=10
```

**Comment by cposture** [comment]
I build vim with the fellow command, There is nothing suspicious
```
./configure --prefix=/Users/admin/bin/vim-8.2/ --with-features=huge --enable-fail-if-missing --enable-python3interp=yes --enable-pythoninterp=yes --enable-gui=auto --with-python-config-dir=/usr/lib/python2.7/config/ --with-python3-config-dir=/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin --with-python3-command=python3.8
```

**Comment by cposture** [comment]
I found the bug from your patch, and I has test it myself

**Comment by bhcleek** [comment]
@cposture what was the bug in my patch?

Also, I pushed another commit to #2921 that uses `sign_getplaced` instead of trying to parse output of `sign placed`. Can you give the latest on #2921 a try again and make sure it works for you?

**Comment by cposture** [comment]
this my comment in code review，the bug：
![image](https://user-images.githubusercontent.com/8305198/85242577-fbfa2400-b471-11ea-875c-7ce25fde2825.png)

**Comment by cposture** [comment]
I try the latest  #2921，It work now，the error that breakpoint not found was fixed

**Comment by bhcleek** [comment]
Thank you for testing, @cposture. I've incorporated the needed change to #2921 that you identified.

**Comment by cposture** [comment]
thank you，it's awesome
