### ISSUE TITLE
vim-go with other lsp client

### ISSUE THREAD

**Issue by smartding** [fatih/vim-go#2923]
I'm using coc.nvim as a lsp client because it works with other languages, not just golang.

Is is possible to disable all lsp-related functions in vim-go, and keep the rest? I do like the "auto import on save" and many other features from vim-go.

**Comment by bhcleek** [comment]
You can add `let g:go_gpls_enabled =1` to your vimrc. See `:help g:go_gopls_enabled`.

However, there shouldn't be any need to disable `gopls` in vim-go and will likely have effects that you're not expecting. Why do you want to disable `gopls`?

Are you aware that the `gopls` instance can be shared among multiple Vim plugins? With vim-go you'd need to either use latest master or add `let g:go_gopls_options=['-remote=auto']`. Additionally, you'll have to configure other plugins to also use the shared `gopls` instance.

**Comment by smartding** [comment]
> You can add `let g:go_gpls_enabled =1` to your vimrc. See `:help g:go_gopls_enabled`.
> 
> However, there shouldn't be any need to disable `gopls` in vim-go and will likely have effects that you're not expecting. Why do you want to disable `gopls`?
> 
> Are you aware that the `gopls` instance can be shared among multiple Vim plugins? With vim-go you'd need to either use latest master or add `let g:go_gopls_options=['-remote=auto']`. Additionally, you'll have to configure other plugins to also use the shared `gopls` instance.

I wanted to disable all gopls-related vim-go functions because I found 2 instances of gopls running when using neovim. I assume one is started by vim-go, the other by coc.nvim.

 When I set g:go_gopls_enabled =0, there's just 1 instance of gopls.

**Comment by vcavallo** [comment]
I'm having the same issue with coc.vim - when vim-go is using gopls (even with -remote=auto) there are many instances of gopls spawned.

**Comment by jonaustin** [comment]
FWIW; I had this same issue and it was apparently because I also had the [coc-go](https://github.com/josa42/coc-go) extension installed.

So I have these in my vimrc:
```
	let g:go_def_mapping_enabled=0  " let coc.nvim handle
	let g:go_gopls_enabled=1 " still needed for GoInfo hover (g:go_auto_type_info)
```

And after uninstalling  coc-go, I no longer have 2 Go LSP servers listed in `:CocList services`

**Comment by Iceber** [comment]
@jonaustin Hi, how did you configure it in coc-config.json, is that right?
```json
    "languageserver": {
        "golang": {
            "command": "gopls",
            "rootPatterns": ["go.mod", ".git/"],
            "filetypes": ["go"]
        }
    }
```

I'm using coc.nvim and it always reminds me that package import failed

**Comment by jonaustin** [comment]
@Iceber Just checked and I don't actually have any explicit config for Go in my coc-settings.json at all.
(I don't have a coc-config.json, but I'm assuming they're the same thing)

fwiw these are all the settings in my vimrc for vim-go:
```
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
  " Notes:
    " ]] and [[ to jump to next/prev function (can also use motions like 3[[
    " and d]])
    " C-] / gd and C-t to jump forward backward in GoDef stack (GoDefStack)
  " https://github.com/fatih/vim-go/issues/3237#issuecomment-853037821

	" To play with more:
	" :GoFillStruct -- `j := play{}` will fill out the struct with default values from play declaration
	" :GoKeyify -- `j2 := play{"me", 42, true} -- expand out the struct with keys
	" :GoReferrers - find all the references to a function, method, type, or variable in your source code.
	" :GoImplements -- list of all interfaces that are implemented
	" :GoFiles -- list of files in the current package
	" :GoMetaLinter -- run all linters
	" :GoTest, :GoFunction, :GoTestCompile, :GoAlternate, :GoTestFunc
	" :GoCoverageToggle, GoCoverageBrowser
	" :GoChannelPeers
	" :TagBar - list entities in file (`?` to see keys)

  " folding
  " needed due to some bug
  set foldmethod=expr
  set foldexpr=nvim_treesitter#foldexpr()
  set nofoldenable

  " https://hackernoon.com/my-neovim-setup-for-go-7f7b6e805876
  "  ]] takes you to the next function or method
  "  [[ takes you to the previous function or method
  "  shift-K to get docs for a func
  let g:go_addtags_transform = "snakecase" " for json struct tags
  au FileType go set noexpandtab
  au FileType go set shiftwidth=2
  au FileType go set softtabstop=2
  au FileType go set tabstop=2
  " note: :GoCoverageClear to clear highlights
  let g:go_auto_type_info = 1 " show actual data type in status line when hovered
  let g:go_highlight_build_constraints = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_types = 1
  let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck', 'gosec'] " :GoMetaLinter (or GoLint or GoVet)

    " Let coc.nvim handle LSP
    " also, just to note somewhere: having the coc-go extension installed was
    " resulting in 2 go lsp servers (:CocList services); uninstalling coc-go
    " fixed it
    let g:go_def_mapping_enabled=0
    let g:go_gopls_enabled=1 " still needed for GoInfo hover (g:go_auto_type_info)

  " coc.nvim integration
    let g:go_diagnostics_level = 0 " let coc handle diagnostics
  " let g:go_metalinter_enabled = []
    let g:go_doc_keywordprg_enabled = 0 " use coc.nvim's much prettier floating window
```

**Comment by jonaustin** [comment]
Also, fwiw, when I open a .go file in vim and run `:CocList Services`, this is what I see
```
* go [running] go, gomod, gowork
```

**Comment by Iceber** [comment]
Thanks for your comments

> Also, fwiw, when I open a .go file in vim and run `:CocList Services`, this is what I see
> 
> ```
> * go [running] go, gomod, gowork
> ```

This looks like it uses the coc-go plugin

**Comment by jonaustin** [comment]
You're right, apparently had it completely backwards, doh; it's been a while, but must have fixed the 2 go LSP processes by disabling vim-go's LSP.

Will edit the initial post to fix, but yeah, the config above lets coc.nvim handle the LSP side, and it's been working quite well.

To hopefully be clear; I don't have anything for go in my coc-settings.json, but in order to get LSP with the above configuration, `:CocInstall coc-go` is needed.
