### ISSUE TITLE
ch_sendraw(): write failed on :GoFmt

### ISSUE THREAD

**Issue by AdamVanScyoc** [fatih/vim-go#2925]
[vimrc.txt](https://github.com/fatih/vim-go/files/4781726/vimrc.txt)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 12 2020 00:47:07)
macOS version
Included patches: 1-539

#### Go version (`go version`):

go version go1.14.3 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Adam/Library/Caches/go-build"
GOENV="/Users/Adam/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/Adam/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/Adam/go/src/bitbucket.app.clemson.edu/mobile/myclemson/go/myclemson/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mb/q4d_kzwd0z77w94qc78gv30w0000gt/T/go-build394937452=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.1.5
    golang.org/x/tools/gopls@v0.1.5 h1:bfyquCQT+XBur/qfeq64IXf1fv54Kh4y6/tDWA31M3g=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_fmt_experimental = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
g:go_gpls_enabled = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

Running `:GoFmt` or saving a .go file results in the error:
```
vim-go: initializing gopls
Error detected while processing function go#fmt#Format[65]..go#fmt#update_file[20]..go#lsp#DidChange[24]..157[29]..160:
line   15:
E631: ch_sendraw(): write failed 
```

**Comment by stamblerre** [comment]
This may not fully resolve your issue, but please update your `gopls` version by running `:GoUpdateBinaries`. The current version of `gopls` is `v0.4.1`, so the one you are using is very out-of-date.

**Comment by AdamVanScyoc** [comment]
This fixed it, thanks! I had previously re-run `:GoInstallBinaries" but I didn't know that there was a`:GoUpdateBinaries` command.
