### ISSUE TITLE
How to zoom in on a window opened with gd

### ISSUE THREAD

**Issue by lyb-Q** [fatih/vim-go#2926]
> I want to enlarge these two windows.This is the window that opens after my code jumps

![addd](https://s1.ax1x.com/2020/06/16/NFUM0P.png)

> What do I need to do?

**Comment by bhcleek** [comment]
I'm not sure what you want to do. What do you mean by "enlarge? Do you want to make the text larger? Do you want to make one window occupy a larger percentage of the screen space that the other? Something else?

**Comment by lyb-Q** [comment]
> I'm not sure what you want to do. What do you mean by "enlarge? Do you want to make the text larger? Do you want to make one window occupy a larger percentage of the screen space that the other? Something else?

How to do so can jump open the full screen of the window . thank you

**Comment by bhcleek** [comment]
see `:help ctrl-w__`.

The question you're asking is more of a Vim question than a vim-go question. You'll find that the Vim help file is very thorough and there are a good number of resources on the web to help you learn Vim.

**Comment by lyb-Q** [comment]
ok,thank you.
