### ISSUE TITLE
FillStruct using gopls (feature request)

### ISSUE THREAD

**Issue by ubombi** [fatih/vim-go#2940]
According to [golang go 37576](https://github.com/golang/go/issues/37576) , [golang tools 220](https://github.com/golang/tools/pull/220) and [googlesource 227437](https://go-review.googlesource.com/c/tools/+/227437/) 

`:GoFillStruct` is now implemented in gopls. So we can use it, instead of `davidrjenni/reftools/cmd/fillstruct`

**Comment by bhcleek** [comment]
I'll keep an eye on the gopls releases and will likely update vim-go to use gopls for fill struct after a release of gopls that includes [cl 227437](https://go-review.googlesource.com/c/tools/+/227437/).

**Comment by ubombi** [comment]
Released in [v0.4.2](https://github.com/golang/tools/releases/tag/gopls%2Fv0.4.2)
