### ISSUE TITLE
Some characters are blacked out after launching vim the first time in iterm2

### ISSUE THREAD

**Issue by adasfan** [fatih/vim-go#2945]
### What did you do? (required: The issue will be **closed** when not provided)
Open any Go file in iterm2 after installing the vim-go plugin. Issue did not happen before vim-go was installed

<img width="1337" alt="Screen Shot 2020-07-01 at 11 15 54 PM" src="https://user-images.githubusercontent.com/1285684/86323207-49545f00-bbf1-11ea-974d-db2ed698ab4c.png">

### What did you expect to happen?
The characters show up after resizing the window

#### vim-go version:
latest
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 18 2020 17:05:56)
macOS version
Included patches: 1-1000

#### Go version (`go version`):

go version go1.14.4 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/muratcetin/Library/Caches/go-build"
GOENV="/Users/muratcetin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/muratcetin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/muratcetin/Exercism/go/hamming/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m9/pvr3dj057kvgm6vpttb0lfv80000gn/T/go-build465587998=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.2
    golang.org/x/tools/gopls@v0.4.2 h1:SPpw/YOMhYKB5TjtZj77ddcTDQkpkUZtw4+0jtVYwro=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
This is most likely related to your iTerm2 settings, your colorscheme, and the highlight groups defined by vim-go. There are a number of ways to get to the bottom of this.
* Try using a different colorscheme - does it suffer from the same problem?
* How are your colors for iTerm configured and what color theme is it using?
* Try to duplicate this with the minimally needed vimrc - can you identify the lines in your vimrc that trigger this?

**Comment by adasfan** [comment]
I tried other color schemes but it did not help. This is my .vimrc -- I do not see how any of the content can lead to the issue -- are you able to repro on your side?

```
set nocompatible              " required
set autowrite
syntax on
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'fatih/vim-go'

" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)
Bundle 'djoshea/vim-autoread'
" ...

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
```

**Comment by adasfan** [comment]
agreed that it is iterm2 specific as I cannot repro in terminal

**Comment by bhcleek** [comment]
I use iTerm2 regularly and don't see this problem. We're outside of vim-go territory now, but I'll give you a few tips.

First, check the colors in iTerms2:
![image](https://user-images.githubusercontent.com/1958864/86388311-6ddc2580-bc49-11ea-8a77-5ca2c1ef6a22.png)

* Try some of the different color presets there to see if you can identify the problem
* How do you have the contrast set? Try adjusting that to see if it helps.

Also, iTerm is a true color terminal and I use tmux, too. To get the full benefits of the colorscheme I use in tmux in iTerm2, I had to add this to my vimrc:

```
if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
	" Allow color schemes to do bright colors without forcing bold.
	set t_Co=16
elseif &t_Co == 256 && ($TERM ==# "screen-256color" || $TERM ==# "xterm-256color")
	if exists('+termguicolors')
		" set foreground and background colors to their respective defaults (by
		" default this is done automatically only when $TERM is xterm; See :help
		" xterm-true-color).
		let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
		let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
		set termguicolors
	else
		let g:solarized_termcolors=256
	endif
endif
```
