### ISSUE TITLE
GoDebug and GoDebugTest do not work

### ISSUE THREAD

**Issue by sebiwi** [fatih/vim-go#2947]
### What did you do? (required: The issue will be **closed** when not provided)
I ran `GoDebugStart` on line 10 of the `fizzbuzz.go` file provided below, and `GoDebugTest` on the test file provided below, both of which were located on `/tmp/test`:
```
// fizzbuzz.go
package fizzbuzz

import "fmt"

func fizzbuzz(number int) string {
	return ""
}

func main() {
	number := 1
	fmt.Print(number)
	fmt.Print(fizzbuzz(1))
}

// fizzbuzz_test.go
// Package fizzbuzz provides a fizzbuzz function.
package fizzbuzz

import (
	"testing"
)

func TestFizzbuzzReturns1On1(t *testing.T) {
	want := "1"
	got := fizzbuzz(1)
	if got != want {
		t.Errorf("got: '%v', want: '%v'", got, want)
	}
}

```

### What did you expect to happen?

I expected the debugger to run.

### What happened instead?

From the fizzbuzz.go file, with the `GoDebugStart` command I got this error:

```
vim-go: could not launch process: not an executable file
```

From the fizzbuzz_test.go file, with the `GoDebugTest` command, I get an empty Stacktrace window, an empty Variables window, an empty GoRoutines window, and on the Output window I can see:

```
ERR: 2020-07-02T16:14:31+02:00 debug layer=rpc API server pid = 12676
ERR: 2020-07-02T16:14:31+02:00 info layer=debugger launching process with args: [/var/folders/rv/wpk98b2x2xb9rddt8qsbtgld3gkt95/T/vqKwKHk/5]
ERR: 2020-07-02T16:14:32+02:00 warning layer=debugger could not set asyncpreemptoff <nil>
```

If I try to `GoDebugBreakpoint`, I get:

```
ERR: 2020-07-02T16:14:31+02:00 debug layer=rpc API server pid = 12676
ERRR: 2020-07-02T16:14:31+02:00 debug layer=rpc API server pid = 12676
ERR: 2020-07-02T16:14:31+02:00 info layer=debugger launching process with args: [/var/folders/rv/wpk98b2x2xb9rddt8qsbtgld3gkt95/T/vqKwKHk/5]
ERR: 2020-07-02T16:14:32+02:00 warning layer=debugger could not set asyncpreemptoff <nil>
ERR: 2020-07-02T16:14:32+02:00 warning layer=debugger could not set asyncpreemptoff <nil>
ERR: 2020-07-02T16:16:06+02:00 debug layer=rpc <- RPCServer.CreateBreakpoint(rpc2.CreateBreakpointIn{"Breakpoint":{"id":0,"name":"","addr":0,"addrs":null,"file":"/private/tmp/test/fizzbuzz.go","line":10,"Cond":"","continue":false,"traceReturn":false,"goroutine":false,"stacktrace":0,"LoadArgs":null,"LoadLocals":null,"hitCount":null,"totalHitCount":0}})
ERR: 2020-07-02T16:16:06+02:00 debug layer=rpc -> *rpc2.CreateBreakpointOut{"Breakpoint":{"id":0,"name":"","addr":0,"addrs":null,"file":"","line":0,"Cond":"","continue":false,"traceReturn":false,"goroutine":false,"stacktrace":0,"LoadArgs":null,"LoadLocals":null,"hitCount":null,"totalHitCount":0}} error: "could not find file /private/tmp/test/fizzbuzz.go"
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" Disable vi compatibility
set nocompatible
" Install vim-plug if it is not installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'for': 'go' }
call plug#end()            " required
</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 18 2020 17:05:56)
macOS version
Included patches: 1-1000
 
#### Go version (`go version`):
go version go1.14.4 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sebacace/Library/Caches/go-build"
GOENV="/Users/sebacace/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sebacace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rv/wpk98b2x2xb9rddt8qsbtgld3gkt95/T/go-build488989799=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

</pre></details>

**Comment by bhcleek** [comment]
`package fizzbuzz` needs to be `package main` to be an executable to cause `:GoDebugStart` to be able to execute it.

After you run `:GoDebugTest` and set a breakpoint you'll need to run `:GoDebugContinue`.

**Comment by sebiwi** [comment]
The renaming fixed one part, thanks!

I think there's something weird which happens when you use `/tmp` as a project directory, the directory changes to `/private/tmp` when executing the debug commands. This is solved when using any other normal directory other than `/tmp`.

Is this a bug?

**Comment by bhcleek** [comment]
It's not a bug. `/tmp` is a symlink to `/private/tmp` in macOS and Vim always resolves paths that are within symlinks to the actual absolute path.

**Comment by sebiwi** [comment]
Alright, thank you very much @bhcleek!

I'm closing this issue now.
