### ISSUE TITLE
godef: Command not found

### ISSUE THREAD

**Issue by nbari** [fatih/vim-go#295]
I have set ``$GOBIN`` to match ``$GOPATH/bin`` in where I have:

    gocode
    godef
    goimports
    golint
    gorename
    gotags

But for some reason the plugin is not founding or calling the proper command.

any ideas ?

I am calling it using ``:GoDef``

**Comment by fatih** [comment]
What does `which godef` gives you ? Is `GoLint` or `GoRename` not working too ?

**Comment by nbari** [comment]
``which godef``  returns 
   
    godef: Command not found.

But ``$GOBIN`` is not on my ``$PATH`` so that is expected, also tried setting the path with ``g:go_bin_path`` but didn't work.

``GoLin``t, ``GoRename`` also not working

**Comment by fatih** [comment]
That's not possible. What do you use as Vim? It seems Vim can't read your environment variables. What gives `:echo $GOPATH`, `:echo $GOBIN` and `:echo $PATH` ?

**Comment by nbari** [comment]
vim does reads the environment variables, ``:echo $GOPATH`` etc,  prints the corresponding paths, but some one the goXXX binaries are not been call I just got "command not found",

this is my current [.vimrc](https://github.com/nbari/my-vim/blob/master/.vimrc)

**Comment by fatih** [comment]
Let us go one by one. First `:GoDef`. So you call `:GoDef` and you only get "command not found" right? But this shouldn't be happen because vim-go checks for the binary and displays an error. So you shouldn't never get the error in the first place. 

Here is the code where it does the check: https://github.com/fatih/vim-go/blob/master/autoload/go/tool.vim#L102

Can you add debug logs to see what you get? Like: `:echo binpath`

**Comment by nbari** [comment]
This is some how related [The odd thing about GOBIN](https://groups.google.com/forum/#!topic/golang-nuts/-mN8R_Fx-7M), I will for now let the environment just with ``$GOPATH`` since I like the "separations' of binaries, I installed the binaries required by the plugin using ``:GoInstallBinaries`` and they currently reside in: ``$GOPATH/bin``.

While opening vim I can validate that ``:echo $PATH`` contains now the ``$GOPATH/bin``  appended at the end, so if I am right https://github.com/fatih/vim-go/blob/master/autoload/go/tool.vim#L125 is working.

Running ``:echo binpath`` throws:

     E121: Undefined variable: binpath 
     E15: Invalid expression: binpath

**Comment by nbari** [comment]
Ok seems that I found the problem, seems to be a shell problem.

in order to make it work I added this to my .vimrc:

      set shell=/bin/sh

After that, ``:GoDef``, ``:GoInfo`` etc working.

Currently I am using csh

**Comment by fatih** [comment]
We have something for `fish` that states this: https://github.com/fatih/vim-go#im-using-fish-shell-but-have-some-problems-using-vim-go Seems the same applies for `csh`. Glad you find it! Mind open a PR and adding this to FAQ? If not I can add it myself :)

**Comment by nbari** [comment]
Sure, let me try to doit :)

**Comment by nbari** [comment]
Some other plugins had this same issue, here is an example as a reference so maybe can help you improve the existing code: https://github.com/airblade/vim-gitgutter/issues/101

**Comment by fatih** [comment]
We have a FAQ entry which explains it.
