### ISSUE TITLE
go-run-{split,vertical} gated by has("nvim") instead of has("terminal")

### ISSUE THREAD

**Issue by wy100101** [fatih/vim-go#2954]
called <plug>(go-run-split)

### What did you expect to happen?

expected to see the program run in a split terminal. 

### What happened instead?

Nothing because the mapping is gated by if has("nvim")

### Configuration (**MUST** fill this out):
vim 8.2 on linux

#### vim-go version:
latest install via vundle

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 01 2020 12:33:53)
Included patches: 1-1105
Modified by jonathon.fernyhough@york.ac.uk

#### Go version (`go version`):
go version go1.14 linux/amd64

#### Go environment
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/mdoughty/go/bin"
GOCACHE="/home/mdoughty/.cache/go-build"
GOENV="/home/mdoughty/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mdoughty/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build018391634=/tmp/go-build -gno-record-gcc-switches"

#### gopls version
golang.org/x/tools/gopls 0.4.2

**Comment by wy100101** [comment]
It seems like a change from `has("nvim")` to `has("terminal")` fixes the issue.

I'll send a MR if people agree this is the right solution.

**Comment by bhcleek** [comment]
Changing it to `has('terminal')` would break the mapping for Neovim. However, changing it to `has('terminal') || has('nvim')` would work for both. Feel free to submit a PR.

**Comment by bhcleek** [comment]
closed by #2956
