### ISSUE TITLE
Navigation with mod vendor not working

### ISSUE THREAD

**Issue by thinkski** [fatih/vim-go#2955]
### What did you do?

Within an example project, ran `go mod vendor` to create `vendor/` copies of the project's dependencies. Verified that `vendor/modules.txt` exists and `go.mod` looks okay. Then opened a `bar/main.go` file and attempted to jump to the definition of a function within `vendor/` via ctrl+].

### What did you expect to happen?

Expected `ctrl+]` to jump to the definition of a function within `vendor/`.

### What happened instead?

Was jumped into definition within `~/go/pkg/mod/github.com`.

#### vim-go version:

1.20

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" vim-go
let g:go_def_mode="godef"
let g:go_fmt_command = "goimports"
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 17 2020 17:49:10)
macOS version
Included patches: 1-503, 505-680, 682-2292

#### Go version (`go version`):

go version go1.14.1 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/chris/go/bin"
GOCACHE="/Users/chris/Library/Caches/go-build"
GOENV="/Users/chris/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/chris/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/chris/go/src/github.com/thinkski/foo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fl/r95c1ngj5399cv1pl_c27v780000gn/T/go-build218303391=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.2
    golang.org/x/tools/gopls@v0.4.2 h1:SPpw/YOMhYKB5TjtZj77ddcTDQkpkUZtw4+0jtVYwro=
</pre></details>

**Comment by bhcleek** [comment]
I'm not sure why this is happening, but let's start with some basics.

First, make sure your `godef` is up to date with `:GoUpdateBinaries godef`. I suspect that will solve your problem, but if it doesn't, I'll need some information about whether you're operating in GOPATH mode or module aware mode, your `GO111MODULE` value, etc.

I also noticed that you're several vim-go versions behind.

**Comment by thinkski** [comment]
Updated `godef` with `:GoUpdateBinaries godef`, restarted Vim. Unfortunately, `ctrl+]` still jumps to `~/go/pkg/` version.

Believe I'm operating within GOPATH mode, as am within the GOPATH (i.e. `~/go/src/github.com/foo/subdir/subdir`).

`GO111MODULES` env variable is empty -- environment variable is not set.

Tried fetching latest master from `vim-go`, but issue persists.

**Comment by bhcleek** [comment]
Do you have an ambient `go.mod` file?

I'm having a hard time duplicating this, but I'm sure we'll figure out what's going on. I'm putting a few suggestions below ordered by things to check and try in order to shorten our back and forth cycle. 

1. Do you have multiple `godef` files? Check your $PATH, $GOPATH/bin, and $GOBIN. If you find more than one, please delete them all and then run `:GoUpdateBinaries godef` again.
1. Try setting `GOFLAGS=-mod=vendor` (you'll need to make sure it's exported and available before starting vim).
1. Do you have any symlinks in the path of the source code that you're jumping from?
1. Have you considered using `gopls` for jumping to definitions? In the most recent release of vim-go, it's the default for `g:go_def_mode`, so you could try removing the `let g:go_def_mode='godef'` from you vimrc.

**Comment by thinkski** [comment]
Thank you, `export GOFLAGS=-mod=vendor` resolved it. After setting it, navigation works as intended. `unset GOFLAGS`, and it reverts to the unexpected behavior.

For completeness, in answer to the other questions and suggestions:
- There's a `go.mod` in `~/go/src/github.com/foo/bar`, but not in `~/go/src/github.com/foo/bar/baz/`.
- I can only find one `godef` in `~/go/bin/godef`. `GOBIN=$HOME/go/bin` and `GOPATH=$HOME/go`.
- There are no symlinks in `~/go/src/github.com/foo/bar/baz/`.
- I did try `gopls` but encountered the same behavior.
