### ISSUE TITLE
Setting filetype asm does not make sense

### ISSUE THREAD

**Issue by adah1972** [fatih/vim-go#2957]
Currently there is this line in ftdetect/gofiletype.vim:

```
au BufRead,BufNewFile *.s setfiletype asm
```

This does not make sense, as .s is not a Go suffix, and it is done already in the standard filetype.vim.

I have found this out because I need to check the content of .s files and set the filetype properly. *It does not work when vim-go is present*, as it forcefully overrides my setting.

**Comment by bhcleek** [comment]
> This does not make sense, as .s is not a Go suffix, and it is done already in the standard filetype.vim.

`.s` is the traditional extension for assembly files, including in the Go community.

> I have found this out because I need to check the content of .s files and set the filetype properly. It does not work when vim-go is present, as it forcefully overrides my setting.

Where and how are you setting the filetype?

This should mostly be a function of where the file that sets the filetype is in your runtimepath. I see two valid options:
1. vim-go could potentially add the `FALLBACK` option to its `setfiletype` call.
2. adust either how or where your filetype is set. I'd recommend that you read about the differences between `setfiletype` (`:help setfiletype`) and `'filetype'` (`:help 'filetype'`) as well as the runtimepath `:help runtimepath`), vimrc (`:help vimrc`), and `after` directories (`:help after-directory`).

**Comment by adah1972** [comment]
> `.s` is the traditional extension for assembly files, including in the Go community.

Of course it is the traditional extension for assembly files, but the type `asm` is not good for each case. My purpose was set it to `arm` for ARM assembly.

The standard filetype.vim does not set the filetype to `asm` in all cases. It tries to detect the assembly type, but currently it does not detect ARM assembly.

> Where and how are you setting the filetype?

In another plugin, similar to what you do, but I set the filetype only when I can determine it is ARM assembly.

For more details, see https://github.com/adah1972/arm-syntax-vim/commit/ff3c9c0c480af558e214b18251a5c451f49fe90b.

I know the difference between `setfiletype` and `set filetype=`. Actually I need to use `set filetype=`, as ftdetect code is loaded after filetype.vim has done its job. It *is* a bit bewildering that vim-go could reset the filetype after my setting, but, anyway, there is no reason it should repeat what filetype.vim already does.

**Comment by adah1972** [comment]
Two more things that I have just found:

- Removing the autocommand for *.s from ftdetect/gofiletype.vim does not affect the vim-go functionality in any way, as far as I can see. It still loads your ftplugin/asm.vim.
- My bad for not updating vim-go to the latest version, as the problem is non-existent now. You used to use `set filetype=`, but now you use `setfiletype`…

Actually your current `setfiletype` is never executed, as filetype.vim already does this.
