### ISSUE TITLE
Operators not highlighted when using gruvbox

### ISSUE THREAD

**Issue by elleven11** [fatih/vim-go#2963]
### What did you do? (required: The issue will be **closed** when not provided)
Installed vim-go, gruvbox and set let g:go_highlight_operators = 1

### What did you expect to happen?
Operators getting colored

### What happened instead?
White operators

### Configuration (**MUST** fill this out):
Neovim with vim-go and gruvbox theme.
But i tried disabling everything except for vim-go and gruvbox, and same problem.
but when i disable gruvbox the highlighting works!
I also highlight functions and function calls, and those get highlighted when gruvbox is on

#### vim-go version:
Latest

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
"
""" Main rc, for generic keybindings, settings and plugin loading
"

" Specify a directory for plugins call plug#begin('~/.nvim/plugged')
call plug#begin('~/.nvim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'morhetz/gruvbox'

" Initialize plugin system
call plug#end()

" sourcing rcs

" true colors, needs patched urxvt or st to work right
set termguicolors

" colorscheme
colorscheme gruvbox
syntax on

" yes
inoremap jj <ESC>

" setting clipboard to system
set clipboard=unnamedplus

" cursor blinkage
:set guicursor=v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50,a:blinkwait1700-blinkoff400-blinkon950-Cursor/lCursor,sm:block,n:block-blinkon0

" move between splits
nmap <C-H> :wincmd h<CR>
nmap <C-J> :wincmd j<CR>
nmap <C-K> :wincmd k<CR>
nmap <C-L> :wincmd l<CR>

" j/k will move virtual lines (lines that wrap)
noremap <silent> <expr> j (v:count == 0 ? 'gj' : 'j')
noremap <silent> <expr> k (v:count == 0 ? 'gk' : 'k')

set relativenumber
set nu

set smarttab
set cindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
" always uses spaces instead of tab characters
set expandtab

" keep undos in a file
set undofile
set undodir=~/.local/share/nvim/cache

" lines to keep cursor vertically centered
set scrolloff=10

" remember cursor location
set viminfo='100,\"2500,:200,%,n~/.cache/.viminfo

" Character 'limit' line
set colorcolumn=110

set hidden 
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" don't show signcolumn
set signcolumn=no

let g:go_highlight_build_constraints = 1

let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1

let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_types = 1
let g:go_highlight_function_calls = 1
</pre></details>
my full normal main vim rc: https://pastebin.com/8HRVfqf6
but as i said, even if i disable everything except vim-go and gruvbox it does not work

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.14.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/elleven/.cache/go-build"
GOENV="/home/elleven/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/elleven/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build062496517=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.3
    golang.org/x/tools/gopls@v0.4.3 h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
</pre></details>

**Comment by bhcleek** [comment]
vim-go uses the `Operator` highlight group by default for operators when `g:go_highlight_operators` is set. If gruvbox doesn't color those, then that's an issue for gruvbox, not vim-go.

With gruvbox, `Operator` is linked to `Normal`:
```
:highlight Operator
Operator       xxx links to Normal
```

You have three options to address this:
First option: modify your vim configuration to set `Operator` to something more to your liking in a `after/plugin/gruvbox/colors/gruvbox.vim`
Second option: modify your vimrc to configure `goOperator` differently (this option is tersely referenced in the [vim-go help](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2626-L2633)) .
Third option: open an issue with gruvbox to ask them to configure the `Operator` highlight group differently.

**Comment by elleven11** [comment]
Ah, alright gotcha.
But if you look : https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L1026
other languages have the operator hi on!
and go has also some highlighting:
https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L1261

Btw, i set myself the highlighting anyways.

**Comment by bhcleek** [comment]
It looks like what you want is for gruvbox to add either
`hidef link goOperator GruvboxPurple` or `hidef link Operator GruvboxPurple`.

Note that gruvbox links `Operator` to `Normal` currently: https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L591
