### ISSUE TITLE
interrupt failure when using ctrlp

### ISSUE THREAD

**Issue by julianvmodesto** [fatih/vim-go#2964]
### What did you do? (required: The issue will be **closed** when not provided)
I'm using ctrlp with vim-go.

When I open CtrlP, it seems that vim-go interrupts and closes the buffer due to a highlight group error. I've tried turning off highlight errors and warnings, but the interrupt will continue to close the CtrlP buffer.

### What did you expect to happen?

Ideally, vim-go doesn't interrupt and close the new CtrlP buffer.

### What happened instead?

The buffer closes with this error in the logs:

```
  Error detected while processing function <SNR>267_PrtFocusMap[1]..<SNR>267_PrtAdd[4]..<SNR>267_BuildPrompt[6]..<SNR>267_Update[11]..<SNR>267_Render[38]..<SNR>267_highlight:
  line   10:
  E28: No such highlight group name: CtrlPLinePre
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

call plug#begin()

Plug 'kien/ctrlp.vim'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

let g:go_highlight_diagnostic_errors=0
let g:go_highlight_diagnostic_warnings=0

let g:go_fmt_command = 'goimports'
let g:go_rename_command = 'gopls'

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1

let g:go_list_type = "quickfix"
let g:go_fmt_fail_silently = 1

let g:go_auto_type_info = 1

let g:go_auto_sameids = 1
let g:ctrlp_working_path_mode = 0

</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.4.3

#### Go version (`go version`):
go1.14.4 linux/amd64

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
$ gopls version
golang.org/x/tools/gopls 0.4.3
    golang.org/x/tools/gopls@v0.4.3 h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
</pre></details>

**Comment by bhcleek** [comment]
This looks like a ctrlp issue, because all the script functions seem to point to ctrlp files. `BuildPrompt` is not a vim-go function and the last function in your call stack, `highlight` is from the same script (one can tell because of the same `<SNR>267_` prefix). `CtrlPLinePre` is not a vim-go highlight identifier either.

Am I missing an imnportant indicator that vim-go is at issue here?

**Comment by bhcleek** [comment]
closing for lack of feedback
