### ISSUE TITLE
Add a blog to Blog Post Wiki

### ISSUE THREAD

**Issue by jogendra** [fatih/vim-go#2966]
Recently, I wrote a blog post [Using Vim for Go development](https://jogendra.dev/using-vim-for-go-development) which is I think relevant to vim-go. Please add it to [blog post wiki](https://github.com/fatih/vim-go/wiki/Blog-Posts).

Link to blog: [https://jogendra.dev/using-vim-for-go-development](https://jogendra.dev/using-vim-for-go-development)

**Comment by bhcleek** [comment]
That's a great post. Good work! I've added it to the blog post wiki.

You may consider mentioning that Vim-go can use gopls for completion; there's no need to install coc.nvim to get code completion for Go in Vim.

You may also be interested in https://shapeshed.com/vim-netrw/. I, too, used NERDTree for a long time, but abandoned it in favor of netrw after reading https://shapeshed.com/vim-netrw/. Netrw comes installed with Vim, eliminating the need to install another plugin. I have yet to find something that I want from Netrw that it can't provide.

**Comment by jogendra** [comment]
Hi, @bhcleek Thanks for adding it to the wiki. I hope it will help someone you start out with vim-go ✨ 💖 

I am new to vim and Go both. I found these plugins well after doing research about them. Reading the vim-go docs, I noticed that it supports auto-completion as well. One main thing why I used coc.nvim was, it's extensions work like in VSCode. I will use it for a while and also use vim-go's auto-completion feature, see what works better for me. Also, I will update the post with the same.

I also come across https://shapeshed.com/vim-netrw/ while I was looking for file-system window plugin. I am loving NERDTree so far. Maybe I will try _vim-netrw_ when I will get bored with NERDTree or it doesn't work well. Thanks for sharing your thoughts on this.


Do you prefer using auto-completion all the time? I sometimes find it very irritating auto-completion popping out. But sometimes they are very helpful, especially when we are not familiar with the package/library syntax. What's your thought on this?
