### ISSUE TITLE
GoDoc and GoDocBrowser fails with E714: List required

### ISSUE THREAD

**Issue by simonhughcom** [fatih/vim-go#2968]
### What did you do?
Tried to run GoDoc or GoDocBrowser.

### What did you expect to happen?
To show some documentation.

### What happened instead?
A error was shown:
"""
Error detected while processing function go#doc#open:
line    5:
E714: List required
"""
### Configuration (**MUST** fill this out):
Just default config for vim-go.

####  `vimrc` you used to reproduce:
<details><summary>vimrc</summary><br><pre>
set nocompatible
filetype plugin indent on
syntax on
let plugin_path='~/.vim/bundle'
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

Also tried with Vim 8.2 with same result.

#### Go version (`go version`):

go version go1.14.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/simon/.local/go/bin"
GOCACHE="/home/simon/.cache/go-build"
GOENV="/home/simon/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/simon/.local/go:/home/simon/projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/simon/.local/go/src/github.com/heptio/velero/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build241298662=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/cmd/gopls master-cmd.gopls
    golang.org/x/tools@(devel)

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_gotags_bin = 'gotags'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
> golang.org/x/tools/cmd/gopls master-cmd.gopls
>    golang.org/x/tools@(devel)

The development version of gopls isn't supported by vim-go. I'm not sure how you'd have anything other than a gopls release given that your vimrc has `Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }`. Something seems amiss 🤔

**Comment by simonhughcom** [comment]
I did install go from the arch repo. Could that be it?

**Comment by simonhughcom** [comment]
Ok So I have no idea how but there was already a version of gopls on my system (Which strangely was not tied to any arch packages).
I removed it and ran 'GoInstallBinaries' again which installed the correct version of gopls and everything works.

Thank you for you help anyway.

But just a suggestion, maybe add a check for the correct versions of all the necessary binaries to warn people.
