### ISSUE TITLE
Terminal escape sequences on command line

### ISSUE THREAD

**Issue by GeoffRussell** [fatih/vim-go#2971]
### What did you do? (required: The issue will be **closed** when not provided)

made some syntax error and then wrote the file to disk ... ie.,

:wa

### What did you expect to happen?

I expected the file to be written to disk ... which it was  ... but

### What happened instead?

My vim command line got polluted with an ansi terminal escape seqence (ESC>4;mESC>4:2m"main.go" ... etc)

NB ... also :help go-troubleshooting  ... gives an " E149 No Help " message dispite vim-go.txt being installed in
.vim/plugged/vim-go/doc ... so something is screwy in my installation ... despite cloning the repository as required

### Configuration (**MUST** fill this out):

Linux Ubuntu 16.04.06 LTS
Vim 8.2

#### vim-go version:
20150303-3

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

call plug#begin()
        Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 27 2020 10:52:11)
Included patches: 1-1303
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version with GTK3 GUI.  Features included (+) or not (-):

#### Go version (`go version`):

go version go1.13.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/geoff/.cache/go-build"
GOENV="/home/geoff/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/geoff/LETTERS/GO"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build976608192=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.3
    golang.org/x/tools/gopls@v0.4.3 h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
![vim-go-image](https://user-images.githubusercontent.com/6374333/89118160-8fe3f480-d4e2-11ea-9488-d81e99bb8d1d.png)

</pre></details>

**Comment by bhcleek** [comment]
Version 20150303-3 is not a release of vim-go 🤔 

> also :help go-troubleshooting ... gives an " E149 No Help " message dispite vim-go.txt being installed in
.vim/plugged/vim-go/doc ... so something is screwy in my installation ... despite cloning the repository as required

`:help helptags` explains how to install help for plugin. Vim-plug's FAQ explains how to add the help tags for plugins managed by Plug: https://github.com/junegunn/vim-plug/wiki/faq#does-vim-plug-generate-help-tags-for-my-plugins

**Comment by GeoffRussell** [comment]
Thanks for the help ...

> Version 20150303-3 is not a release of vim-go 

Sorry, but I don't know how to find the version. I look in the CHANGELOG ... and I can see v1.23 ... so I guess that's it. The other number (20150303-3) was the version of the ubuntu package vim-gocomplete.  I think I installed that  prior to doing the git-clone.
In any event ... I have two vim-go directories under .vim    1) .vim/plugged/vim-go and 2) .vim/pack/plugins/start/vim-go the CHANGELOG.md files in both are identical.
 
> 
> > also :help go-troubleshooting ... gives an " E149 No Help " message dispite vim-go.txt being installed in
> > .vim/plugged/vim-go/doc ... so something is screwy in my installation ... despite cloning the repository as required

I fixed this ... so my help now works. 
> 
> `:help helptags` explains how to install help for plugin. Vim-plug's FAQ explains how to add the help tags for plugins managed by Plug: https://github.com/junegunn/vim-plug/wiki/faq#does-vim-plug-generate-help-tags-for-my-plugins

I have one clue about the problem.   If I unset the TERM environment variable before starting vim, then the problem vanishes.  It
seems that vim sets TERM to "dumb" in such situations. My desktop environment normally sets TERM to xterm-256color. But using "dumb" causes other problems ... not with vim but with bash.  So the best work around so far is
a script (#!/bin/bash \n unset TERM \n /usr/bin/vim $*)  but I figure vim may be a little hampered by the dumb setting.

Cheers,

**Comment by bhcleek** [comment]
> In any event ... I have two vim-go directories under .vim 1) .vim/plugged/vim-go and 2) .vim/pack/plugins/start/vim-go the CHANGELOG.md files in both are identical.

You'll want to get rid one or the other. If you get rid of the `.vim/plugged/vim-go`, then be sure to modify your vimrc to not use Plug to manage it.

> I have one clue about the problem. If I unset the TERM environment variable before starting vim, then the problem vanishes. It
seems that vim sets TERM to "dumb" in such situations. My desktop environment normally sets TERM to xterm-256color. But using "dumb" causes other problems ... not with vim but with bash. So the best work around so far is
a script (#!/bin/bash \n unset TERM \n /usr/bin/vim $*) but I figure vim may be a little hampered by the dumb setting.

This is a good indicator that the problem is not with vim-go. Without more of your vimrc, though, it's nearly impossible to tell what the problem is, though. Check to see what `:set term?` reports - it might point the way for you.

**Comment by GeoffRussell** [comment]
Sorry ... I got sidetracked with other tasks ... many thanks for your help on this.
