### ISSUE TITLE
Metalinter invokes golint,even when I have specified that I want to use golangci-lint

### ISSUE THREAD

**Issue by ksewo** [fatih/vim-go#2975]
### What did you expect to happen?
I should get same linting errors as when running ```golangci-lint run```. When running it directly in terminal, I don't have any linting errors, but when using :GoMetaLinter I have errors from golint

### What happened instead?
I am getting error "exported type `MyType` should have comment or be unexported (golint)", which shouldn't occur as I am using golangci-lint run instead golint

### Configuration (**MUST** fill this out):

.golangci.yml (just default linters enabled):
```
  1 linters:
  2   enable:
  3   ¦ - govet
  4   ¦ - errcheck
  5   ¦ - staticcheck
  6   ¦ - unused
  7   ¦ - gosimple
  8   ¦ - structcheck
  9   ¦ - varcheck
 10   ¦ - ineffassign
 11   ¦ - deadcode
 12   ¦ - typecheck
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
 let g:go_metalinter_command='golangci-lint'
 let g:go_metalinter='golangci-lint'
 let g:go_metalinter_autosave = 1
 let g:go_highlight_types = 1
</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):
go version go1.14.7

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/home/ksewo/.cache/go-build"
GOENV="/home/ksewo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ksewo/programming/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ksewo/programming/go/src/myproject/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build964508305=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.4
</pre></details>

**Comment by bhcleek** [comment]
The golangci-lint linters used by vim-go are controlled by `g:go_metalinter_enabled`. Please see `:help g:go_metalinter_enabled`.

**Comment by ksewo** [comment]
@bhcleek Thanks.
For anyone facing this issue, use it:
```
 let g:go_metalinter_command='golangci-lint'
 let g:go_metalinter_enabled=[]
 let g:go_metalinter_autosave_enabled=[]
```
it will disable every additional linters and just call golangci-lint
