### ISSUE TITLE
Question: function signature completion

### ISSUE THREAD

**Issue by slawosz** [fatih/vim-go#298]
Hi,
first of all, great work!
Lets say I have such package:
```go
package foo

def Bar(url string, body []byte) {
//...
}
```

What I would like to achieve, is whan I would write:
```
foo.Bar[]
```
I would like to get dialog (similar to one for completion) where `foo.Bar(url string, body []byte)` would be written. 

Is it a possible to get something similar in vim-go, and if not, how you think it would be possible to get?

**Comment by fatih** [comment]
Hi @slawosz 

This is a feature of https://github.com/nsf/gocode. vim-go just acts a wrapper of expanding the result. Let me look if we can do it. I'll let you know about this once I'm finished.

**Comment by fatih** [comment]
Hi @slawosz, I've just checked it extensively, for now it's not possible as there is no direct bridge between YCM and UltiSnips.
