### ISSUE TITLE
[ termux ]CANNOT install cross-compiled binaries when GOBIN is set

### ISSUE THREAD

**Issue by chenrry666** [fatih/vim-go#2980]
### What did you do? (required: The issue will be **closed** when not provided)
i use vim-plug and i install vim-go

i run :GoInstallBinaries
### What did you expect to happen?
install lots of useful tools
### What happened instead?
![Screenshot_2020-08-16-15-16-13-98_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/40446983/90328995-77400800-dfd3-11ea-987a-c83535d7bd9c.jpg)

### Configuration (**MUST** fill this out):
i install it and no config
#### vim-go version:
v1.23
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
filetype plugin indent on
syntax on
call plug#begin('~/.local/share/nvim/plugged')'

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8

set cul
set cuc
set nu                                                                
set mouse=a
set selection=exclusive
set selectmode=mouse,key                                              set showmatch                                                                                                                               set tabstop=4
set shiftwidth=4                              
</pre></details>

#### Vim version (first three lines from `:version`):

neovim v0.4.4 Release
#### Go version (`go version`):

go version go1.15 android/arm64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/data/data/com.termux/files/home/.cache/go-build"
GOENV="/data/data/com.termux/files/home/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="android"
GOINSECURE=""
GOMODCACHE="/data/data/com.termux/files/home/workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="android"
GOPATH="/data/data/com.termux/files/home/workspace/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/data/data/com.termux/files/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64"
GCCGO="gccgo"
AR="ar"
CC="aarch64-linux-android-clang"
CXX="aarch64-linux-android-clang++"
CGO_ENABLED="0"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/data/data/com.termux/files/usr/tmp/go-build826460
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

it can't be install by vim-go
</pre></details>

**Comment by bhcleek** [comment]
What happens when you try to `go install` a binary from the command line?

**Comment by bhcleek** [comment]
FWIW, I suspect you need to set `GOHOSTOS=linux` and `GOOS=linux` when you run Vim. You can do this either from within vim:
```
:let $GOOS=linux
:let $GOHOST=linux
```

or else set them in the shell before launching Vim.

**Comment by chenrry666** [comment]
> FWIW, I suspect you need to set `GOHOSTOS=linux` and `GOOS=linux` when you run Vim. You can do this either from within vim:
> 
> ```
> :let $GOOS=linux
> :let $GOHOST=linux
> ```
> 
> or else set them in the shell before launching Vim.

I try that ,it doesn't work 
I think I can install them manually.

**Comment by chenrry666** [comment]
> What happens when you try to `go install` a binary from the command line?

because i doesnt set GOBIN in my .zshrc , so i can  
install it from the command line 

my english is poor , thank u !

**Comment by bhcleek** [comment]
Can you please set `GOBIN` at your commandline and then execute a `go install` command to help us get to the bottom of this. Vim-go needs to set `GOBIN` to make sure the binaries get installed to the correct location, but I'm not sure what your GOOS and GOHOSTOS values should be on android for these binaries (I suspect they should be `linux`, but I'm not certain.

**Comment by chenrry666** [comment]
ok. My GOOS and GOHOSTOS have not been set.GOBIN is empty.
 i try to run <code>GOOS=android GOHOSTOS=linux go get -u  github.com/cosmtrek/air
</code>
the result is <details><summary>click to expand</summary><br /><code><pre>go: github.com/cosmtrek/air upgrade => v1.21.2
go: github.com/pelletier/go-toml upgrade => v1.8.0
go: github.com/creack/pty upgrade => v1.1.11
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/fatih/color upgrade => v1.9.0
go: github.com/imdario/mergo upgrade => v0.3.11
go: github.com/mattn/go-colorable upgrade => v0.1.7
go: golang.org/x/sys upgrade => v0.0.0-20200817155316-9781c653f443
#github.com/cosmtrek/air
/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64/link: running aarch64-linux-android-clang failed: exit status 1
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/go-link-292710572/go.o: Relocations in generic ELF (EM: 62)
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/go-link-292710572/go.o: Relocations in generic ELF (EM: 62)
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/go-link-292710572/go.o: Reloc</pre></code></details>

the clang looks doesn't work.
i run` clang -v` or `aarch64-linux-android-clang -v` the result is 
```
clang version 10.0.1 (https://github.com/termux/termux-packages 2f1431d824f449f09ef50aa365cdd7ed5b8c159d)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
```

then i try to set GOBIN. i run `GOBIN=~/workspace/go/bin GOOS=android GOHOSTOS=linux go get -u github.com/cosmtrek/air`
it looks bad<br />
<details><summary>click to expand</summary><code><pre>go: github.com/cosmtrek/air upgrade => v1.21.2
go: github.com/creack/pty upgrade => v1.1.11
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/fatih/color upgrade => v1.9.0
go: github.com/imdario/mergo upgrade => v0.3.11
go: github.com/pelletier/go-toml upgrade => v1.8.0
go: golang.org/x/sys upgrade => v0.0.0-20200817155316-9781c653f443
go: github.com/mattn/go-colorable upgrade => v0.1.7
go get: cannot install cross-compiled binaries when GOBIN is set</code></pre></details>:cry:

**Comment by bhcleek** [comment]
You'll need to set `GOHOSTOS` and `GOOS` so that they're the same to avoid the cross compilation issue. In most cases, one can simply leave them _unset_ and Go will compile for your system.

`GOBIN=~/workspace/go/bin GOOS=android GOHOSTOS=linux go get -u github.com/cosmtrek/air` will cross-compile, because `GOHOSTOS` and `GOOS` are different from one another.

Essentially, you need to get `GOBIN=~/workspace/go/bin go get -u github.com/cosmtrek/air` working. If you can do that, it should be a snap to get vim-go's `:GoInstallBinaries` and `:GoUpdateBinaries` working for you.

**Comment by chenrry666** [comment]
well, i did these things
i run `unset GOOS;unset GOBIN;unset GOHOSTOS`
<details><summary> <code>go env</code> print these</summary><pre><code>GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/data/data/com.termux/files/home/.cache/go-build"
GOENV="/data/data/com.termux/files/home/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="android"
GOINSECURE=""
GOMODCACHE="/data/data/com.termux/files/home/workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="android"
GOPATH="/data/data/com.termux/files/home/workspace/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/data/data/com.termux/files/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64"
GCCGO="gccgo"
AR="ar"
CC="aarch64-linux-android-clang"
CXX="aarch64-linux-android-clang++"
CGO_ENABLED="0"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/data/data/com.termux/files/usr/tmp/go-build686096</code></pre></details>

i run `GOBIN=~/workspace/go/bin go get -u github.com/cosmtrek/air` again

<details><summary>the result is</summary><pre><code>go: github.com/cosmtrek/air upgrade => v1.21.2
go: github.com/fatih/color upgrade => v1.9.0
go: github.com/imdario/mergo upgrade => v0.3.11
go: github.com/creack/pty upgrade => v1.1.11
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/pelletier/go-toml upgrade => v1.8.0
go: github.com/mattn/go-colorable upgrade => v0.1.7
go: golang.org/x/sys upgrade => v0.0.0-20200819091447-39769834ee22
go: downloading golang.org/x/sys v0.0.0-20200819091447-39769834ee22
go get: cannot install cross-compiled binaries when GOBIN is set</code></pre></details>

**Comment by bhcleek** [comment]
Yes, that would do it. I'm sorry I didn't notice that you'd set GOARCH differently before.

**Comment by chenrry666** [comment]
> Yes, that would do it. I'm sorry I didn't notice that you'd set GOARCH differently before.

haha,it doesn't matter.
🥰
