### ISSUE TITLE
Location list auto jumping to error on write (save)

### ISSUE THREAD

**Issue by andradei** [fatih/vim-go#2981]
### What did you do? (required: The issue will be **closed** when not provided)
1. Wrote some Go code, had a variable that was declared but not used
2. Saved the file with `:w`
3. Cursor jumps to the line with error

### What did you expect to happen?
The error to show up in the location list, but maintain cursor position

### What happened instead?
The cursor auto jumped to the line with the error (of unused variable)

#### vim-go version:
Commit bd56f56

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" For vim-go
let g:go_highlight_build_constraints = 1
"let g:go_auto_sameids = 1 " Highlight identifier uses
let g:go_fmt_autosave = 1
let g:go_fmt_command = 'goimports'
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_metalinter_autosave = 1
let g:go_metalinter_command='golangci-lint'
" Automatically get signature/type info for object under cursor
let g:go_auto_type_info = 1
let g:go_updatetime = 1000

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.15 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/me/my-project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build091714861=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_list_type = 'locationlist'
g:go_updatetime = 1000
g:go_fmt_autosave = 1
g:go_metalinter_command = 'golangci-lint'
g:go_def_mode = 'gopls'
g:go_info_mode = 'gopls'
g:go_metalinter_autosave = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Vim-go is behaving correctly according to your configuration. 

From `:help g:go_jump_to_error`:
> Use this option to enable/disable passing the bang attribute to the mappings
(e.g. |(go-build)|, |(go-run)|, etc.) and the metalinter on save.  When
enabled it will jump to the first error automatically (means it will NOT pass
the bang attribute to the appropriate command, i.e: (go-run) -> :GoRun ).

Try disabling `g:go_jump_to_error` by using `:let g:go_jump_to_error = 0` in your vimrc.

**Comment by andradei** [comment]
Thanks, I tried searching for a lot of terms on the documentation, but needed this help in the end.

**Comment by Thomasdezeeuw** [comment]
I tried setting `let g:go_jump_to_error = 0`, but this doesn't work for me. I tried setting it before and after I load vim-go, but it still jumps between tabs when you write the file.
