### ISSUE TITLE
Unknown function: trim

### ISSUE THREAD

**Issue by ziirish** [fatih/vim-go#2987]
Hi,

I believe commit 6d949b3830c1920917aa5df8cf427af0dd6e619e broke compatibility with vim 8.0.1453 as the `trim` function is not available. (see [doc](https://github.com/vim/vim/blob/218101442e8775bd1f05d1dda18d3946ee032dd1/runtime/doc/eval.txt#L2446-L2448))

### What did you do? (required: The issue will be **closed** when not provided)

Run `:GoInstallBinaries` under vim 8.0.1453

### What did you expect to happen?

install all `vim-go` dependencies

### What happened instead?

Got the following error:
```
Error detected while processing function <SNR>56_GoInstallBinaries[13]..go#util#hostosarch:
line    3:
E117: Unknown function: trim
E15: Invalid expression: [trim(l:hostos), trim(l:hostarch)]
Error detected while processing function <SNR>56_GoInstallBinaries:
line   13:
E714: List required
line   14:
E121: Undefined variable: l:goos
E116: Invalid arguments for function go#util#SetEnv('GOOS', l:goos)
E15: Invalid expression: go#util#SetEnv('GOOS', l:goos)
line   15:
E121: Undefined variable: l:goarch
E116: Invalid arguments for function go#util#SetEnv('GOARCH', l:goarch)
E15: Invalid expression: go#util#SetEnv('GOARCH', l:goarch)
line  149:
E121: Undefined variable: Restore_goarch
E116: Invalid arguments for function call
line  150:
E121: Undefined variable: Restore_goos
E116: Invalid arguments for function call
vim-go: installing finished!
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453

#### Go version (`go version`):

go version go1.15 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
that's very odd. The [tests run on Vim 8.0.1453](https://github.com/fatih/vim-go/runs/1004537367) and didn't have any problems with that PR 🤔

**Comment by bhcleek** [comment]
Oh, those errors did occur in CI, but it didn't halt execution, so tests passed.

**Comment by ziirish** [comment]
Impressive! Thanks for the quick fix.
