### ISSUE TITLE
Surface gopls messages

### ISSUE THREAD

**Issue by gsauthof** [fatih/vim-go#2991]
### What did you do? (required: The issue will be **closed** when not provided)

Edit a go file where gopls produces a warning, i.e.:

1. open vim and edit the following example
2. save it with `:w` - such that the highlighting is updated

Example:

```
package main

import "fmt"


type foo struct {
    number int `foo:"true`
}

func main() {
        fmt.Println("vim-go")
}
```

Cross check on the command line:

```
$ gopls check hello.go
/path/to/hello.go:7:5: struct field tag `foo:"true` not compatible with reflect.StructTag.Get:
                                      bad syntax for struct tag value
```

### What did you expect to happen?

1. the highlighting gets updated
2. the number field name is highlighted in a warning-indicating fashion
3. it's somehow possible to get the actual gopls warning message for this location. For example a quickfix-like window could be automagically shown, there could be some display when moving the cursor to that location, some shortcut could cycle through such gopls warnings or something like that.

### What happened instead?

1. only the first character of the `number` identifier is highlighted after the write
2. there is no way to display the gopls warning message

### Additional Information

There is #2591 where it's mentioned that

> the actual messages from gopls aren't surfaced yet, but depending on the nature of them, you may either see the issues on save if you have g:go_fmt_autosave set and they're syntax errors or after :GoBuild or :GoTest.

Thus, I opened this issue at this sounds like it's a missing feature that may be added at some point in time.

FWIW, the issue in the above issue isn't exposed by gofmt nor by `:GoBuild`.

#### vim-go version:

vim-go-1.23-2.fc31.x86_64

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
syntax on
filetype plugin indent on
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  5 2020 00:00:00)
Included patches: 1-905
Modified by <bugzilla@redhat.com>

#### Go version (`go version`):

go version go1.13.14 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/juser/.cache/go-build"
GOENV="/home/juser/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/juser/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build830437671=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

version 0.4.0, built in $GOPATH mode
</pre></details>

**Comment by bhcleek** [comment]
> 1. only the first character of the number identifier is highlighted after the write

That's because of gopls. The message it sends indicates the problem area is only one character wide:
```
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/bhcleek/src/vim-go/issues/2991/main.go","version":2,"diagnostics":[{"range":{"start":{"line":5,"character":1},"end":{"line":5,"character":1}},"severity":2,"source":"structtag","message":"struct field tag `foo:\"true` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"}]}}
```

> 2. there is no way to display the gopls warning message

You can display the warnings two different ways.

First, you can use `:GoDiagnostics` to see the diagnostics for a file.

Alternatively, you _should_ be able to set `g:go_metalinter_command` to `'gopls'` and us `:GoMetalinter` and/or configure the metalinter to run on save. I'm seeing a bug with that in module mode, though; I'll put a fix up for the metalinter functionality in module mode soon.
