### ISSUE TITLE
Folding acts weird

### ISSUE THREAD

**Issue by rjshrjndrn** [fatih/vim-go#2995]
### What did you do? (required: The issue will be **closed** when not provided)
enable foldmethod as syntax

### What did you expect to happen?
Have a proper fold with fuctions and vars
**Sample code**
```go
package main

import "fmt"

// Fold 1
func printString(test string) {
	fmt.Println(test)
}

// Fold 2
var (
	test string = "hello"
)

// Fold 3
func main() {
	printString(test)
}
```
![image](https://user-images.githubusercontent.com/2563385/91904436-8bb61d00-ecc2-11ea-8f86-0443e7a4c9ba.png)

### What happened instead?
vars fold eats up functions fold also
![image](https://user-images.githubusercontent.com/2563385/91904351-69240400-ecc2-11ea-9dea-d232343cf194.png)

> if I do :GoFmt the folding will become correct

#### vim-go version: 
Master Branch
commit: bf2dd524a7d7a2c6f50642ec3dae2bc1506b5c94

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

augroup auto_go
	autocmd!
        autocmd BufEnter,BufNewFile *.go set foldmethod=syntax foldnestmax=1
	autocmd BufWritePre *.go :GoDiagnostics
	autocmd BufWritePost *_test.go :GoTest
augroup end

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.5.0-622-gf26df8bb6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.14.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rajeshr/.cache/go-build"
GOENV="/home/rajeshr/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rajeshr/go_code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build918625483=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
If it's folding as you expect after `GoFmt`, what's the difference betwen your file pre and post formatting?

**Comment by rjshrjndrn** [comment]
1. open go file:
    Can't see Fold3 ( see image 2)
2. :GoFmt
     Able to see Fold3 ( image 1)

**Comment by bhcleek** [comment]
I see image 1 when opening a file with the contents you provided in your description.

**Comment by rjshrjndrn** [comment]
Sorry, I didn't get you.

To clarify things,

Image1 is the **expected behavior** ( which is not happening when you open the go file)

Image2 is the **actual behaviour** ( when you open a go file, this is the folding I've, untill I manually run a `:GoFmt`)

> Manually running a :GoFmt gives out the expected result( which is image1).

**Comment by bhcleek** [comment]
I'm seeing image 1 when I open a go file that has the contents that you provided your description; I'm not able to duplicate the behavior you're describing.

**Comment by rjshrjndrn** [comment]
oh.. I'm using coc.nvim, would that cause this behaviour ?

**Comment by bhcleek** [comment]
I don't know; try disabling all plugins other than vim-go. Do you still see the issue when vim-go is the only plugin?

**Comment by rjshrjndrn** [comment]
I think some other plugin is messing up this. Thanks for helping to figure that out. Closing this issue.

**Comment by captainroy-hy** [comment]
> I think some other plugin is messing up this. Thanks for helping to figure that out. Closing this issue.

Hi @rbisewski  Did you solve the problem? I encountered the same issue... I also used coc.nvim and vim-go.
