### ISSUE TITLE
Option to build all packages recursively `go build ./...`

### ISSUE THREAD

**Issue by ryanmcnamara** [fatih/vim-go#2996]
A frequent use case I have is that I want to build all packages in a go repository and have one quick fix list to browse through. Without this option I find myself going to the command line (out of vim) and recursively building.

I expected `:GoBuild ./...` to do this, since `go build ./...` does do what I want, but it did not work.

### What did you do? (required: The issue will be **closed** when not provided)
`:GoBuild ./...`

### What did you expect to happen?

Expected this to recursively build all packages under the current one.

### What happened instead?
Appears to just build the current package

### Configuration (**MUST** fill this out):
Unsure what this is

#### vim-go version:
e3bcc4ca13a5d48d5ee7fc26cb028c3db24ce611

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
nmap <silent> <Leader>u :GoReferrers<CR>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug  2 2020 00:45:48)
macOS version
Included patches: 1-1350

#### Go version (`go version`):

go version go1.14.4 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

I: gopls version
golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

</pre></details>

**Comment by bhcleek** [comment]
`:GoBuild ./...` builds all packages in or below the working directory.
