### ISSUE TITLE
How to change debug highlight color

### ISSUE THREAD

**Issue by strogiyotec** [fatih/vim-go#2997]
Good day , I have a problem with GoDebug specifically I don't like highlight color.Here is the screenshot
![image](https://user-images.githubusercontent.com/20584185/92160037-3e7d9c80-ede3-11ea-9e21-bf87ee3623d1.png)

As you can see this color hides the code so I want to change this color to something like white. According to **:help vim-go** I can disable this highlight using 
```
Highlight the current line and breakpoints in the debugger.

>
  let g:go_highlight_debug = 1
<
```
But is it possible to change color instead ? Thank you in advance

**Comment by bhcleek** [comment]
Yes, you can customize all the highlighting groups by providing overriding the group in an `after/syntax/go.vim` file.

Alternatively, you _should_ also be able to set them in your vimrc, but for that to work you'll need to wait for https://github.com/fatih/vim-go/pull/2998 to be merged.

The highlight group you'd want to define is `GoDebugCurrent`. You can see how vim-go defines it in the [`syntax/go.vim` file0(https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L425-L426).

**Comment by strogiyotec** [comment]
@bhcleek Thank you for response, so as far as I understand I have to fork this repo and change go.vim directly, I don't want to synchronize my  fork and main repo so I will wait for your pull request to be merged

**Comment by bhcleek** [comment]
You do not have to wait for #2998 to be merged; you can put your preferred configuration for `GoDebugCurrent` in a `after/syntax/go.vim` file within a directory in your runtimepath.
