### ISSUE TITLE
s:handleLocations() with poor performance

### ISSUE THREAD

**Issue by roy2220** [fatih/vim-go#2999]
When `:GoReferrers` results a long list (N ~=1000), there is a significant delay. 
The profile shows that `s:handleLocations` should be blamed:
```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1   5.647631   4.817558  <SNR>129_handleLocations()
    1   0.676989   0.596524  leaderf#LfPy()
 1402              0.272404  go#lsp#lsp#PositionOf()
12125              0.204054  <SNR>129_compareLocations()
 2804   0.130079   0.094530  go#path#FromURI()
    1              0.082310  <SNR>144_write_buffer()
   13   0.097819   0.068577  <SNR>107_AutoUpdate()
  609   0.103065   0.050034  airline#highlighter#get_highlight()
 1218              0.046502  <SNR>82_get_syn()
    4              0.028802  lfMru#record()
 2804              0.025688  go#uri#Decode()
   13   0.023226   0.023062  airline#extensions#tabline#buflist#list()
    5   0.022254   0.022185  <SNR>107_SetStatusLine()
   12   0.020343   0.019355  <SNR>107_GetNearbyTag()
  221   0.067979   0.017914  airline#highlighter#exec()
   23   0.114258   0.016588  287()
    4   0.016102   0.016055  <SNR>107_HandleOnlyWindow()
    1   0.015576   0.015460  301()
    1   0.169230   0.014747  go#list#Parse()
  360              0.011532  qf#filter#ReuseTitle()
```

**Comment by bhcleek** [comment]
It's _possible_ that this might be able to be improved.

Can you provide some code and a location within it to test with?

**Comment by roy2220** [comment]
@bhcleek 👌 Here is the code: https://gist.github.com/roy2220/16fa3502893e486d911a213c20e19f8d
`:GoReferrers` on `Println` causes quite a lot of delay on my laptop.

**Comment by bhcleek** [comment]
Most of the performance of `s:handleLocations` is dependent on the `getbufline()` and `readfile()` calls. I've tried a few algorithmic changes, but none resulted in better performance. I don't see a good solution to this and in any case, getting 1000 locations is a relative edge case.
