### ISSUE TITLE
error detected while processing function GoFiles

### ISSUE THREAD

**Issue by bkaradzic** [fatih/vim-go#30]
Just installed vim-go (on windows) and getting errors when opening .go files:

`E484: Can't open file <path>\AppData\Local\Temp\VIo5EB7.tmp`

.vim-go dir has: errcheck, golint, oracle, godef, goimports, gocode and installation didn't have any errors.

**Comment by TomTom86** [comment]
Hi all, i have the some problem:

when i try :GoRun or others GoCommand i have this error

![image](https://cloud.githubusercontent.com/assets/8830977/8592317/9ffccdfa-262e-11e5-9f3e-ae298ca00e6a.png)

My os is Win7, i use gvim7.4 and in my _vimrc i set:

set shell=cmd
set shellcmdflag=/c

i try :echo system("echo hi") and the error is the some:

![image](https://cloud.githubusercontent.com/assets/8830977/8592408/640c907c-262f-11e5-81fe-d2995b924697.png)

i can't understand what i wrong...

**Comment by markwest1** [comment]
This file opening error occurs when gvim is invoked from bash within MINGW64 terminal, but not when it is invoked from Windows explorer or bash within cmd.exe.

Error when invoked from MINGW64 terminal window:
![image](https://cloud.githubusercontent.com/assets/8137897/10526858/dd5ee4fa-7352-11e5-8b5f-54f8a70b9633.png)

No error when invoked from bash within cmd.exe:
![image](https://cloud.githubusercontent.com/assets/8137897/10526911/20c105e8-7353-11e5-9b44-40f3cfe70bf0.png)

Log:
![image](https://cloud.githubusercontent.com/assets/8137897/10526952/7dacab40-7353-11e5-9bcc-dfc8a90fbcc2.png)

**Comment by philwhln** [comment]
I have this set up in .vimrc

```
if $SHELL =~ 'fish'
  set shell='/bin/sh'
endif
```

but still hitting issues when trying to save a file

```
Cannot execute shell '/bin/sh'
Error detected while processing function go#fmt#Format:
line   44:
E484: Can't open file /var/folders/pf/01012ncd26d4rcz5qknsym940000gn/T/vCqzcXR/7
```

**Comment by nishanths** [comment]
@philwhln Uninstalling and reinstalling `vim-go` fixed this for me.

I'd love to know if you found the real cause of the issue.
