### ISSUE TITLE
go1.4 new "for range" syntax

### ISSUE THREAD

**Issue by knibals** [fatih/vim-go#300]
Since go1.4 a [new, variable-free, form of _for range_](http://tip.golang.org/doc/go1.4#forrange) has appeared. It not taken into account by the parser yet.
Any timeframe for implementation? And thank you for this great plugin

``` go
for range x {
	...
}
```

**Comment by fatih** [comment]
Hi @knibals. What exactly is the problem? You should be able to use it without any problem. Vim-go doesn't rely on the new Go version. Can you give more detail please. Thanks.

**Comment by knibals** [comment]
Hello @fatih. With my Go version :
```bash
go version go1.4 linux/386
```

this little script **compile without error**:

```go
func main(){
	sl := []string{"yep", "nop"}
	for range sl{
		fmt.Println("NaN")
	}
}
```
But when a save in ViM, I got this error:

```bash
forrange.go|8 col 6| : expected operand, found 'range'
forrange.go|11 col 3| : expected '{', found 'EOF'
 ```

**Comment by fatih** [comment]
I don't know how you get those, I've saved it on my localhost and it's works totally fine. Can you invoke it from the command line? Like:

```sh
gofmt forrange.go
```

**Comment by alexaandru** [comment]
This error is from Syntastic, not from vim-go. I can reproduce the error with vim-go plugin disabled.

**Comment by knibals** [comment]
Heu... I dont have Syntastic as a plugin. Just *delimitMate*, *nerdtree*, *php*, *sparkup*, *tagbar*, *vim-go* and *YouCompleteMe*.

**Comment by fatih** [comment]
Thanks @alexaandru! @knibals can you please try disable syntastic and try again? It works without any problem with vim-go.

**Comment by fatih** [comment]
Accidentally hit close. Reopened again. Did you try on the command line please ?

**Comment by alexaandru** [comment]
Disabled ALL plugins, error went away. Re-enabled ONLY Syntastic, the error was back. Re-enabled ONLY vim-go (disabled Syntastic again), error was gone again.

**Comment by knibals** [comment]
@fatih I've FMT'ed the file without problem. I've also removed ALL the plugins but vim-go, and still having the error message.

**Comment by fatih** [comment]
It must be something else. Can you share your vimrc? Do you have any other auto commands running? If it works with `gofmt` on command line, there is no way it would fail for vim-go. Do you have two `gofmt` binaries? What says `which gofmt` ? Also can you run `:!which gofmt` inside vim?

**Comment by knibals** [comment]
```gofmt``` path is correctly discovered. I've installed ``` go1.4``` via git, no mercurial. Does it count? [My vimrc is here](http://pastebin.com/GF0MCBr1)

**Comment by fatih** [comment]
I think there is another `gofmt` binary, which is old and used by vim-go, because it's inside the `PATH`. Vim-go doesn't do the formatting, gofmt does it. So it means you have a `gofmt` or `goimports` binary which is old.

**Comment by knibals** [comment]
Investigating... Keep you posted guys!

**Comment by shilov** [comment]
For anyone else that bumps into this, I had the same issue and sure enough there was an old `gofmt` binary that was being used by mistake. Just needed to remove it and the problem went away.
