### ISSUE TITLE
Using gofumports as goimports replacement produce wrong import

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#3002]
### What did you do? (required: The issue will be **closed** when not provided)

Prepare example code:
```sh
$ mkdir fumportbug
$ cd fumportbug
$ go mod init fumportbug
go: creating new go.mod: module fumportbug
$ mkdir cfg
$ cat >cfg/cfg.go <<EOF
package cfg

var MySQL struct{}
EOF
$ cat >config.go <<EOF
package fumportbug

var cfg *struct {
	MySQL struct{}
}
EOF
$ cat >bug.go <<EOF
package fumportbug

var _ = cfg.MySQL
EOF
$ 
```

Now, in command line both `goimports` and `gofumports` produce valid result (won't change `bug.go`), but vim-go with `let g:go_fmt_command = 'gofumports'` adds invalid import (with `let g:go_fmt_command = 'goimports'` it'll produce valid result - don't add or remove that import):
```
$ goimports bug.go 
package fumportbug

var _ = cfg.MySQL
$ gofumports bug.go 
package fumportbug

var _ = cfg.MySQL
$ vi bug.go # :wq
$ cat bug.go 
package fumportbug

import "fumportbug/cfg"

var _ = cfg.MySQL
$ 
```

### What did you expect to happen?
vim-go output should match gofumports output.

### What happened instead?
vim-go output does not match gofumports output.

### Configuration (**MUST** fill this out):
```vim
let g:go_fmt_command = 'gofumports'
```

#### vim-go version:
bf2dd52

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
let g:go_fmt_command = 'gofumports'
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 20 2020 21:21:41)
Included patches: 1-360
Modified by Gentoo-8.2.0360

#### Go version (`go version`):

go version go1.15.1 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/powerman/go/pkg/mod"
GONOPROXY="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GONOSUMDB="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/powerman/tmp/go/fumportbug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build823397435=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
</pre></details>

**Comment by bhcleek** [comment]
While you're free to use `let g:go_fmt_command=go_fumports`, it is not officially supported by vim-go.

**Comment by powerman** [comment]
@bhcleek I know it's not officially supported. What do you recommend me to do this this case? Maintain own vim-go fork or there is a way to somehow configure vim-go to handle this issue?

At a glance the patch is trivial (I've tested it fix this issue, but can't guarantee gofumports support won't ever need other changes, of course):
```patch
--- a/autoload/go/fmt.vim
+++ b/autoload/go/fmt.vim
@@ -167,7 +167,7 @@ function! s:fmt_cmd(bin_name, source, target)
     let opts = has_key(opts, a:bin_name) ? opts[a:bin_name] : ""
   endif
   call extend(cmd, split(opts, " "))
-  if a:bin_name is# 'goimports'
+  if a:bin_name is# 'goimports' || a:bin_name is# 'gofumports'
     call extend(cmd, ["-srcdir", a:target])
   endif
 
```

**Comment by bhcleek** [comment]
I'd recommend that you use `gopls` to format via `g:go_fmt_command` and leverage vim-go's new setting to cause `gopls` to use `gofumpt` by adding `let g:go_gopls_gofumpt=v:true` to your vimrc. From there, you can use the usual settings to adjust imports with either `gopls` or `goimports`.

Alternatively, if you're set on using the `gofumports` binary, the simplest thing is probably to add a symbolic link named `goimports` that points to your `gofumports` binary (make sure the directory containing the symbolic link is in your PATH prior to any directory containing `goimports`).
