### ISSUE TITLE
Invalid expression: go#config#GoplsGofumpt() because of conflict with vim-polyglot

### ISSUE THREAD

**Issue by haomingw** [fatih/vim-go#3009]
### What did you do? (required: The issue will be **closed** when not provided)
Open a .go file

### What happened instead?
vim-go: initializing gopls
vim-go: initialized gopls
Error detected while processing function <SNR>94_on_stdout[1]..<SNR>94_neocb[58]
..7[8]..8[4]..go#lsp#message#ConfigurationResult:
line   22:
E117: Unknown function: go#config#GoplsGofumpt
Error detected while processing function <SNR>94_on_stdout[1]..<SNR>94_neocb[58]
..7[8]..8[4]..go#lsp#message#ConfigurationResult:
line   22:
E15: Invalid expression: go#config#GoplsGofumpt()

### Configuration (**MUST** fill this out):
Install both vim-go and vim-polyglot

#### vim-go version:
latest, the problem started from Sep 7th 2020

####  `vimrc` you used to reproduce:

Plug 'sheerun/vim-polyglot'
Plug 'fatih/vim-go'

</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):
1.15.1

#### Go environment
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/haoming/.cache/go-build"
GOENV="/home/haoming/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/haoming/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/haoming/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/haoming/.golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/haoming/.golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build766912836=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
golang.org/x/tools/gopls 0.4.4

**Comment by bhcleek** [comment]
This is addressed in the troubleshooting section of vim-go's help file: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2508-L2512
