### ISSUE TITLE
Jump back after testing

### ISSUE THREAD

**Issue by rubenv** [fatih/vim-go#301]
This might be elementary vim, but I can't find it.

After running `:GoTest`, vim jumps to the location of the failing assertion. Is there a key combination to jump back to the cursor position before running the tests (the code I was editing)?

I tried `''`, but that only seems to make the jump in the same file.

**Comment by fatih** [comment]
Hi @rubenv 

We have a setting for disabling jumping to the first error. Just put this into your vimrc, it will disable it:

```
let g:go_jump_to_error = 0
```

Other than this I don't know how to jump back. You can ask #vim at freenode.

**Comment by rubenv** [comment]
Using globals marks might be a way to fix this: http://vim.wikia.com/wiki/Using_marks

My plan is to map a key combination to "save all files, set a known global mark and run tests" and an additional key combination for "return to known global mark". Should do the trick.

Thanks for this great vim plugin, really improves my quality of life during work!

**Comment by rubenv** [comment]
In case someone is looking for this:

```viml
" Map \\ to tests, but save and store position first
autocmd FileType go nmap <leader><leader> :wa<CR>mT:GoTest<CR>                                                                                                
" Jump back to last editing position before test run: \'                                                                                                      
autocmd FileType go nmap <leader>' `T
```

With the above you can hit `\\` to run tests and afterwards use `\'` to go back to your edits.

**Comment by fatih** [comment]
Glad you find a way around :+1: :)
