### ISSUE TITLE
Key mappings only active during debugging

### ISSUE THREAD

**Issue by kernel-panic96** [fatih/vim-go#3012]
Would you be interested in a PR where a debug editing mode is simulated. In which a user can define a key mapping which is active only when a debug session is in place and the user's mappings are restored afterwards. This will allow you to make mappings that are more natural like 'c' for continue without losing the builtin vim 'c' change semantics.

I wrote an extension a while back that does this. Would love to get your feedback on it https://github.com/kernel-panic96/vim-go-extensions

EDIT: sorry for some reason I cannot add a feature request label

**Comment by kernel-panic96** [comment]
Could potentially solve #1788

**Comment by bhcleek** [comment]
Yeah, that would be very useful.

I'd like to keep it as minimal as possible, though; it should be relatively easy to wire into vim-go without having to make some of the changes that you made in the extension. WDYT?

**Comment by kernel-panic96** [comment]
If you are referring to the other commands related to breakpoints, I agree. If you want me to strip down something from the debug mode implementation please elaborate.

**Comment by bhcleek** [comment]
Yeah, I think it was all the breakpoint commands and related functions that I was thinking of. If you think there are changes to the features that support breakpoints in vim-go that we should make, I'd be happy to talk about that in a separate issue/pr.

**Comment by kernel-panic96** [comment]
Cool. I'll take a look at the code base and get back to you with a PR or questions

**Comment by kernel-panic96** [comment]
@bhcleek Where do you think is the most appropriate place the code? The obvious places to me are go#debug#Start, go#debug#Stop and go#test#Test.

I have a concern for go#debug#Stop that it won't get called if the program exits on it's own. Is there any callback when dlv finishes the program?

**Comment by bhcleek** [comment]
`go#debug#Stop` does get called whenever delve exits: https://github.com/fatih/vim-go/blob/master/autoload/go/debug.vim#L1121-L1124

I'd expect this to be implemented in a couple of places:
* configuration of the mappings in `s:continue` where the mappings are already configured
* restore the mappings in `go#debug#Stop` where the autogroup is already cleared.

**Comment by kernel-panic96** [comment]
s:continue does not seem to be called at the initial startup. I have left a comment in the PR about the default mappings that most likely is related to the place from which the mappings are initialized. It would be awesome if we can sort it out.

**Comment by bhcleek** [comment]
`s:continue` does not get called at initial startup, nor should it.

I left comments in the PR that should help you get this sorted. AFAIC, we can continue the conversation there.
