### ISSUE TITLE
Error is detected but no extra information is provided.

### ISSUE THREAD

**Issue by ygworldr** [fatih/vim-go#3015]
# What did you do? (required: The issue will be **closed** when not provided)

Created a simple go file with an error. There is no indication as to what the error is.

### What did you expect to happen?

I expected to see a reason why the code is wrong.

For example, this is Python:

![screenshot-2](https://user-images.githubusercontent.com/62601401/93467498-b4a2f880-f8e5-11ea-970f-f6ea3e6a7075.png)

### What happened instead?

There is no indication as to what the error is.

![screenshot-1](https://user-images.githubusercontent.com/62601401/93467496-b40a6200-f8e5-11ea-8c11-554d00825e86.png)

#### vim-go version:

`commit 9b9b527d61a6fe10a6d0c618cc0dd113b6aa7690`

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" Go support.
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
au! BufNewFile,BufRead *.go set foldmethod=syntax

let g:go_fmt_experimental = 1  " https://github.com/fatih/vim-go/issues/502

let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_addtags_transform = "camelcase"

let g:go_highlight_fields = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_functions = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1

autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4

autocmd FileType go nmap <Leader>i <Plug>(go-info)
let g:go_auto_type_info = 1

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.4

#### Go version (`go version`):

go version go1.14.7 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yann/.cache/go-build"
GOENV="/home/yann/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/yann/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build218842861=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version

golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
</pre></details>

**Comment by bhcleek** [comment]
`:GoDiagnostics` will show you the error.

**Comment by ygworldr** [comment]
@bhcleek Thank you.
