### ISSUE TITLE
Unattended :GoUpdateBinaries with vim-plug

### ISSUE THREAD

**Issue by tombh** [fatih/vim-go#3027]
I looked in the docs and existing issues. I can't find how to run `:GoUpdateBinaries` unattended, I'm asked to press Enter for every dependency. I must have set something up wrong as I can't believe everyone is pressing Enter for all deps every time they upgrade?

**Comment by bhcleek** [comment]
This is usually due to one's `shortmess` value or a very small screen. What's does `set shortmess?` output for you?

**Comment by tombh** [comment]
Thank you so much! I feel bad this has nothing to do with vim-go. But you fixed it, I'm very happy :)
