### ISSUE TITLE
one case about omni compl failed.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [fatih/vim-go#3031]
to reproduce:
```
bash-4.4$ pwd
/home/shane/abc
bash-4.4$ tree
.
└── def
    └── ghi
        ├── main.go
        └── shape_test.go

2 directories, 2 files
bash-4.4$ 
```
if `def` folder is not a go mod managed proj, even it is a git repo root, omni failed.
as a workaround: had to cd to `ghi` folder, then it works, or manually added `ghi`  as  workspace.
but as i said at #3026 , it was not a std proj env, so perhaps 'this is not a matter', and i am not sure if it should 'implicitly' add workspace for such case. up to you.

// env & tool version is same like #3030

**Comment by bhcleek** [comment]
It's not possible to implicitly add a workspace for this. When you have a directory structure like this, you should use GOPATH. Basically, you have three options. The first two are of equal value as far as vim-go is concerned and the third is an option if you _must_:
1. Make sure the code is in a module.
2. Make sure the code is in GOPATH
3. make sure your current working directory is the directory that directly contains the code you want to work on and that it is all fully self-contained within that directory.

**Comment by Shane-XB-Qian** [comment]
i see, and i agree with that, just for giving you a case, and a new ticket as your request.
but just option#3, for now, looks vim-go did not recognized cwd in vim, but had to really cd the pwd outside, that's a little unconvinced... is that possible to make it work ?

**Comment by bhcleek** [comment]
>  looks vim-go did not recognized cwd in vim, but had to really cd the pwd outside,

> had to cd to ghi folder, then it works

These two statements seem to be in conflict.

**Comment by Shane-XB-Qian** [comment]
> seem to be in conflict.

i think you got my point .. those are 2 diff things.
---
another question: if there was not only `ghi` one folder under `def`, e.g had `jkl` also, 
then if i had add workspace for `ghi`, and if i now cd into `jkl`, then how was now managing the workspace, was those 2 workspace maybe conflict, or now only `jkl` is the right one, previous one `ghi` had been removed from workspace list ?
- if it would remove, or would not conflict each other, then 'implicitely' (if no go mod and no gopath) should be ok..
- otherwise better be there was a way to remove.. 
- or perhaps vim-go support cwd change in vim, (regardingless gopls workspace was if so), then as you said, let user fully manually control it.

**Comment by bhcleek** [comment]
I don't understand this additional scenario. Do you have a question about a specific set of actions and what the result would be?

**Comment by Shane-XB-Qian** [comment]
```
/home/shane/abc
.
└── def
    └── ghi                         // 1, if this one had added as gopls workspace
     |  ├── main.go
     |  └── shape_test.go
    └── jkl                          // 2, now open 'main.go' in this 'jkl' and trying to set this as gopls workspace too
        ├── main.go
        └── shape_test.go
```
3, then now, which one was the right gopls workspace? `ghi` or `jkl`? would then impact each other?
// cwd in vim means e.g vim opened at `abc`, but vim's cwd is `def`.

**Comment by Shane-XB-Qian** [comment]
anyway, i know this looks a little mess, and looks those a little too sensitive on path ..
perhaps better/tried to not handle such multiple-folders in one single vim instance, 
easy to confuse at least, so let it be. thx reply. closing.
