### ISSUE TITLE
GoImplements never works

### ISSUE THREAD

**Issue by vimalk78** [fatih/vim-go#3033]
### What did you do? (required: The issue will be **closed** when not provided)
Run `:GoImplements` on an interface type

### What did you expect to happen?
`vim-go` should show which all types implement the interface

### What happened instead?
vim-go stuck at :
```
vim-go: analysing with scope <package root path>/... (see ':help go-guru-scope' if this doesn't work)...
```
never shows output it used to show long back. perhaps gopls doesnt support it? guru used to support it so nicely

#### vim-go version:
latest master at commit e8da3621d6177e5b0beca318a0f9f5baa44d9350
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
plugins added:
ale
bufutils.vim
delimitMate
denite.nvim
deoplete-go
deoplete.nvim
fzf.vim
molokai
nerdtree
tagbar
vim-airline
vim-buftabline
vim-codefmt
vim-commentary
vim-floaterm
vim-fugitive
vim-gitgutter
vim-go
vim-maktaba
vim-nerdtree-tabs
vim-ruby
vim-yaml

</pre></details>

#### Vim version (first three lines from `:version`):

```
NVIM v0.5.0-245-g1bfccf028
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagn
ostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/
neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-f39ed490-c1ac-4e02-842a-04441e5f2493

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

```
#### Go version (`go version`):

```
go version go1.14.7 linux/amd64
```
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vimalkum/.cache/go-build"
GOENV="/home/vimalkum/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vimalkum/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vimalkum/go/src/github.com/openshift/elasticsearch-proxy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build033056633=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.0
    golang.org/x/tools/gopls@v0.5.0 h1:XEmO9RylgmaXp33iGrWfCGopVYDGBmLy+KmsIsfIo8Y=

</pre></details>

**Comment by vimalk78** [comment]
i used to be proud of this plugin, now it just forces me to move away from vim

**Comment by vimalk78** [comment]
https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1497-L1503
the docs says to configure ` let g:go_implements_mode = 'guru'`

But there is no such option
`E121: Undefined variable: go_implements_mode `

**Comment by bhcleek** [comment]
> https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1497-L1503 the docs says to `configure let g:go_implements_mode = 'guru'`

The docs are correct. You can use `guru` or `gopls` for implements mode. Guru will not work in Go modules, though, so only use it if you're using GOPATH mode.

When you use guru, the length of time that it takes to complete will depend on the size of your GOPATH (that's always been true with guru).

If you can provide some clear directions in a simple case to demonstrate the problem you're having, I'm more than happy to diagnose what's going on.

> But there is no such option
> `E121: Undefined variable: go_implements_mode`

Where did this come from?

**Comment by vimalk78** [comment]
> Where did this come from?
`:let g:go_implements_mode = 'guru'` on master

**Comment by bhcleek** [comment]
> `:let g:go_implements_mode = 'guru'` on master

This works for me just fine. In any case, setting a variable on the Vim cmdline doesn't require that the variable be previously defined and vim-go is not in the codepath for effecting that assignment

**Comment by vimalk78** [comment]
i am using v1.24 now, with default options, there are no settings changing default behavior of vim-go and with no guru scope specific settings
running `:GoImplements` on a package with 30 files takes 5-6 minutes
running `guru implements <filename>:#offset` never seems to finish

**Comment by vimalk78** [comment]
```
vim-go: go_def_mode value: gopls is not valid. Valid values are: [godef, guru]                               
```
with v1.24 i see this error.

**Comment by bhcleek** [comment]
That error message does not exist anywhere in v1.24. The error you're seeing was changed in v1.20: https://github.com/fatih/vim-go/commit/1e73ce2700748be4502e45b6e61e8261c2a3af8e#diff-08ab523bb9e4fa671fbfcbd936b8de4dR75.

I suspect you either installed an older version or you have multiple copies of vim-go in your runtimepath and an older version is being sourced first.

> running :GoImplements on a package with 30 files takes 5-6 minutes
running guru implements <filename>:#offset never seems to finish

vim-go relies on `guru`. If it takes 5-6 minutes to finish `:GoImplements`, then I'd expect `guru` to take just about as long. However, there can be differences on a machine with regard to which binary vim-go runs vs which is used on your commandline; it might be worth checking to see whether you have multiple copies of `guru` (perhaps one somewhere in $PATH and another either in $GOBIN or $GOPATH/bin).

You can also get much better performance for `:GoImplements` by setting `g:go_implements_mode` to `gopls` (e.g. `:let g:go_implements_mode='gopls'` in your vimrc).

**Comment by bhcleek** [comment]
Based on one of your recent comments, "running :GoImplements on a package with 30 files takes 5-6 minutes," it sounds like your original reason for opening this issue is resolved.

Are you still having problems, or should we close this?

**Comment by vimalk78** [comment]
Thanks a lot for your kind response. I was mistakenly using v1.9 , with v1.24 and setting `g:go_implements_mode` to `gopls` , `:GoImplements` works nicely

although i found an issue while running `:GoImplements` on a struct. the resulting location list is not browsable by using `cnext`
i need to switch to the location list window, and do a `cc` to follow the location

**Comment by bhcleek** [comment]
> although i found an issue while running :GoImplements on a struct. the resulting location list is not browsable by using cnext
i need to switch to the location list window, and do a cc to follow the location

That's because the default list for `:GoImplements` is the location list, not the quickfix list. You can control that with `g:go_list_type` or `g:go_list_type_commands`, but `:cc` will never work to navigate the location list; `ll` is the normal mode command to go to the first item in the location list.
