### ISSUE TITLE
Usability improvement: run GoImports on buf write pre

### ISSUE THREAD

**Issue by pedromss** [fatih/vim-go#3037]
This is a suggestion to improve (imo) the usability of the plugin out of the box.

I find my self using `:GoImports` alot to automatically fix the imports that either aren't used or are missing. The problem is I sometimes only remember to run it when I attempt to run my program and compilation files, at which time I switch back to the buffer and run `:GoImports`.

So I updated my vim configs with:
```
autocmd BufWritePre *.go GoImports
```

Which automatically does this before saving the buffer contents.

Is this something that could be set by default by vim-go? From what I can see it could be added to the other auto commands in the group https://github.com/fatih/vim-go/blob/master/plugin/go.vim#L304 .

**Comment by bhcleek** [comment]
Vim-go supports adjusting imports on save. The fastest way to get it working is by adding `let g:go_fmt_command='goimports'` to your vimrc.

See `:help g:go_fmt_command`, `:help g:go_imports_mode`, `:help g:go_fmt_autosave`, and `help g:go_imports_autosave`.
