### ISSUE TITLE
Start gopls by running `gopls serve`

### ISSUE THREAD

**Issue by stamblerre** [fatih/vim-go#3043]
We are trying to improve the `gopls` CLI experience by not defaulting to starting the server when a user runs just `gopls` on the command-line (https://github.com/golang/go/issues/41282). `gopls` already has a `gopls serve` command which can be used instead. We're asking all language client owners to switch to starting `gopls` via `gopls serve`. There's no rush on this, but just wanted to file an issue to get the process started.

Thanks!

**Comment by bhcleek** [comment]
Thanks, @stamblerre . I'll prioritize this and try to get it done ASAP.

**Comment by bhcleek** [comment]
@stamblerre `gopls serve` doesn't seem to support `-remote=auto`. Is that intentional or an oversight? `gopls -remote=auto serve` seems to work, but that makes it a bit difficult to know how options for starting the server should be passed to gopls. 🤔

**Comment by stamblerre** [comment]
Yes, I'm sorry about the trouble--it looks like it will be difficult to ask clients to make the switch until the flags work when they are passed in to `gopls` or into `gopls serve`. I filed https://github.com/golang/go/issues/41860 to track that, and https://github.com/golang/go/issues/41282 will be blocked until that issue is resolved, so there's no actionable work required on your part for now. Really sorry about this!

**Comment by bhcleek** [comment]
No worries. I appreciate the heads up. Let's leave this open for now.

For what it's worth, this will be a very easy change in vim-go

**Comment by stamblerre** [comment]
Sorry for the noise on this, but we've decided not to change the default in the end. Closing this--sorry about the inconvenience!

**Comment by bhcleek** [comment]
No apologies necessary; this is what software development looks like ;-)
