### ISSUE TITLE
GoRun with args

### ISSUE THREAD

**Issue by hoffoo** [fatih/vim-go#305]
Is something like this possible to add: ```:GoRun main.go --arg``` ?

I see that it takes a list of files, would it be possible to do something like ```:GoRun foo.go bar.go -- --arg```?

**Comment by fatih** [comment]
Hi @hoffoo ,

`GoRun` is a helper command,  just so you can quick run and play with Go snippets. It's not intended for running applications, parsing flags/envs, etc.. You can always manually invoke trough Vim's `!` motion command. Example:

`:!go run foo.go bar.go -- --arg`

This is perfectly valid. In the other hand, `GoRun` is a special command that only takes the package files of the current file.

**Comment by hoffoo** [comment]
Makes sense thanks!
