### ISSUE TITLE
how to use new defination const from personal module  in go mod environment

### ISSUE THREAD

**Issue by BraveSoldier** [fatih/vim-go#3051]
I'am so sorry. I wasn't sure if the issue template was appropriate for this. but,I still hope ask. 

I can't direct quote my module's new defination const when i update my module and 'go get -u 'my module' && go mod tidy'.  It just can be used when I must close vim and reopen it every time. 

GO111MODULE="on"

Forgive my pool english.

thanks.

**Comment by bhcleek** [comment]
Yes, if you modify the module file, then you will need to restart your vim session to pick up those changes until https://github.com/fatih/vim-go/issues/2697 is resolved.

**Comment by BraveSoldier** [comment]
> Yes, if you modify the module file, then you will need to restart your vim session to pick up those changes until #2697 is resolved.

@bhcleek   thanks for you're answer !
