### ISSUE TITLE
2 sec freeze happens in 3 sec after opening some project's first file

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#3055]
### What did you do? (required: The issue will be **closed** when not provided)

```
$ git clone https://github.com/powerman/go-monolith-example.git
$ cd go-monolith-example
$ git checkout vim-go-freeze
$ vi cmd/mono/main.go
```
Then wait for 3 seconds, and you'll see names of many go files from this project shown in status/command line. They will be shown for about 2 seconds (on my system), and vim will be frozen until this finish.

The same thing will also happens if you'll start vim opening some other file from other project, and then load any go file from project mentioned above (e.g. using `:tabedit`).

I've checked few other projects, and even this one before latest commit - freeze won't happens. I see go file names flashing in status/command line when opening files from other projects, but it happens very fast and thus won't result in noticeable freeze (it won't even happens on master branch of mentioned above project - that's why you'll need to switch branch as mentioned above).

### What did you expect to happen?

Vim shouldn't unexpectedly froze for seconds after opening files.

### What happened instead?

Vim froze for a few seconds when opening first file from mentioned above project.

#### vim-go version:

Current master: 0da52e030a3d962c1b610b1f25b467d4c37e89c5.
I bisect this issue, and it begins at 4e39c7a0144630ade7fa7e780ba34d61539b05cd. It feels like it freeze for less time at this commit than at current master.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
let g:go_metalinter_command = 'golangci-lint'
let g:go_fmt_fail_silently = 1
let g:go_fmt_command = 'gopls'
let g:go_imports_autosave = 1
let g:go_imports_mode = 'gopls'
let g:go_gopls_gofumpt = v:true
" let g:go_gopls_local = trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m;}'))
let g:go_gopls_local = {}
autocmd FileType go call s:setlocal()
let g:go_doc_keywordprg_enabled = 0
let g:go_template_use_pkg = 1
let g:go_list_type = 'quickfix'
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_parameters = 0
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 0
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 0
let g:go_highlight_variable_assignments = 0
let g:go_build_tags = 'integration'
let g:go_gopls_matcher = 'caseSensitive'
let g:go_gopls_deep_completion = 0
let g:go_gopls_temp_modfile = 1
let g:go_gopls_use_placeholders = 1
autocmd FileType go nmap <buffer> <nowait> <Leader>r     <Plug>(go-run)
autocmd FileType go nmap <buffer> <nowait> <Leader>b     <Plug>(go-build)
autocmd FileType go nmap <buffer> <nowait> <Leader>t     <Plug>(go-test)
autocmd FileType go nmap <buffer> <nowait> <Leader>T     <Plug>(go-test-func)
autocmd FileType go nmap <buffer> <nowait> <Leader>c     <Plug>(go-coverage-toggle)
autocmd FileType go nmap <buffer> <nowait> <Leader>gd    <Plug>(go-def-tab)
autocmd FileType go nmap <buffer> <nowait> <Leader>gb    <Plug>(go-doc-browser)
autocmd FileType go nmap <buffer> <nowait> <Leader>s     <Plug>(go-implements)
autocmd FileType go nmap <buffer> <nowait> <Leader>i     <Plug>(go-info)
autocmd FileType go nmap <buffer> <nowait> <Leader>e     <Plug>(go-rename)

function! s:setlocal()
    try
	let l:olddir = chdir(expand('%:p:h'))
	let l:dir = trim(system('go list -m -f {{.Dir}}'))
	if !has_key(g:go_gopls_local, l:dir)
	    let g:go_gopls_local[l:dir] = trim(system('go list -m'))
	endif
    finally
	call chdir(l:olddir)
    endtry
endfunction
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, собрано Jul 20 2020 21:21:41)
Заплатки: 1-360
С изменениями, внесёнными Gentoo-8.2.0360

#### Go version (`go version`):

go version go1.15.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/powerman/go/pkg/mod"
GONOPROXY="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GONOSUMDB="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/powerman/proj/go/go-monolith-example/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build069414943=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.1
    golang.org/x/tools/gopls@v0.5.1 h1:AF3Uh7HF08SZpKFfgJO6zfF3bbxyDXWqdkK4kMXiQ1o=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 1
g:go_list_type = 'quickfix'
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_gopls_matcher = 'caseSensitive'
g:go_highlight_function_calls = 1
g:go_highlight_function_parameters = 0
g:go_highlight_fields = 0
g:go_highlight_generate_tags = 1
g:go_gopls_deep_completion = 0
g:go_highlight_variable_declarations = 0
g:go_highlight_string_spellcheck = 1
g:go_loaded_gosnippets = 1
g:go_gotags_bin = 'gotags'
g:go_metalinter_command = 'golangci-lint'
g:go_doc_keywordprg_enabled = 0
g:go_highlight_variable_assignments = 0
g:go_highlight_format_strings = 1
g:go_gopls_local = {'/home/powerman/proj/go/go-monolith-example': 'github.com/powerman/go-monolith-example'}
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_functions = 1
g:go_template_use_pkg = 1
g:go_gopls_use_placeholders = 1
g:go_highlight_types = 1
g:go_fmt_command = 'gopls'
g:go_imports_mode = 'gopls'
g:go_jump_to_error = 1
g:go_imports_autosave = 1
g:go_gopls_gofumpt = v:true
g:go_build_tags = 'integration'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_gopls_temp_modfile = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:OFF
</pre></details>

**Comment by bhcleek** [comment]
This is mostly because of the `autocmd FileType go call s:setlocal()`. If you want to use `gopls` to adjust imports and have `g:go_gopls_local` be set dynamically to the module names, then it has to call `go list -m`. If you run `go list -m` in you'll see that it's not able to find one of the repos and that this accounts for the delay that you're seeing:

```
go: github.com/dentalcpdpro/mono@v0.0.0-20200919195101-6a7f57facecf: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/bhcleek/go/pkg/mod/cache/vcs/c0ee9bb9f3f323ad5bb101af12a431ab3ced3e3f4c30a5205e59518bafdd4b1a: exit status 128:
        ERROR: Repository not found.
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
```

If you don't want to risk such a delay, then there are two options available to you. First, you could make your `g:go_gopls_local` value a static value. Alternatively, you can use `g:go_imports_mode='goimports'` and use `b:go_fmt_options` to set the local imports as you [used to do](https://github.com/fatih/vim-go/issues/3023#issue-705963728).

A third option also probably exists. Resolving that `go list` error will likely make the delay go away once `github.com/dentalcpdpro/mono@v0.0.0-20200919195101-6a7f57facecf` is in your module cache.

**Comment by powerman** [comment]
I think all these factors are adds to the delay, but the root reason is different - it's some blocking operation running in the foreground which **may** took long enough time under some circumstances.

I had no issues with package you mentioned because it's from private repo I have access to (it's not related to this project and was added into go.mod by mistake while running vimdiff between these two projects, I think).
Also, disabling autocmd for s:setlocal result in starting this blocking operation faster (in about 1 second after opening vim instead of 3 seconds) and finishing it a bit faster (at a glance in 1 second instead of 2 seconds), but it's still hurts UX enough to be annoying.

I suppose I was lucky enough to notice this issue mostly because this project is in the middle of huge refactoring - thus there is broken go.mod and other issues - but such a "broken" state happens often in many projects and vim must not freeze just because of this.

Maybe there is a way to run this potentially long operation in background to avoid UX issues?

**Comment by powerman** [comment]
I mean, this project is small enough (less than 4K LOC). If we have 2 sec delay (yes, in unlucky case, but, still) on this project, then I suppose it may be much longer delay on larger projects.

**Comment by bhcleek** [comment]
> I had no issues with package you mentioned because it's from private repo I have access to (it's not related to this project and was added into go.mod by mistake while running vimdiff between these two projects, I think).
Also, disabling autocmd for s:setlocal result in starting this blocking operation faster (in about 1 second after opening vim instead of 3 seconds) and finishing it a bit faster (at a glance in 1 second instead of 2 seconds), but it's still hurts UX enough to be annoying.

I can't duplicate this delay even when using the vim-go settings and that you reported. However, I do wonder if a recent change could have affected this (I merged several PRs this weekend). Can you update to the latest master and see if you still see some delays when you have the autocmd for s:setlocal disabled?

>. I suppose I was lucky enough to notice this issue mostly because this project is in the middle of huge refactoring - thus there is broken go.mod and other issues - but such a "broken" state happens often in many projects and vim must not freeze just because of this.

vim-go depends on `go list`. When your module is in some broken state, there's not much that vim-go can do about any delays that `go list` introduces as a result of that. Often in these cases, the first `go list` will then cache the results (this caching will persist across vim-go sessions). Additionally, vim-go caches a lot of the information that it gets from `go list`  and vim-go tries hard to use that cache instead of shelling out to `go list` every time a piece of `go list` provided information is needed.

**Comment by bhcleek** [comment]
> P.S. I've pushed a go.mod fix into that branch.

Oh, and FWIW, I updated locally to get your fix to that branch.

**Comment by powerman** [comment]
I've just updated to current master and looks like this issue is gone. Thanks!
