### ISSUE TITLE
Help: No syntax highlight in macvim

### ISSUE THREAD

**Issue by phuna** [fatih/vim-go#306]
Hi,
Currently I see no syntax highlight in macvim, in vim everything works fine. 
I'm using zsh (brew version). I checked the environment of macvim (using echo) and they seem fine (GOPATH, GOROOT, PATH same as in terminal). However things lik :GoDef doesn't work
Please see my screenshot.
![screenshot_33](https://cloud.githubusercontent.com/assets/1096791/5995490/0dd06758-aac7-11e4-80b4-01a74ef0042f.png)

**Comment by fatih** [comment]
If :GoDef also doesn't work, it means you didnt' installed GoDef properly. Please check out the installation process. Also is there any other packages you installed before? You only need to enable vim-go and nothing else. There is no problem with syntax or something else. I'm using myself MacVim and also vim from terminal without a single problem. You can checkout my dotfile if you wish: https://github.com/fatih/dotfiles/blob/master/vimrc

**Comment by phuna** [comment]
Hi, thanks for your information. I've tried to disable all plugins except vim-go but still same problem.
How do I know if "GoDef" is installed properly? From shell I can execute godef, I also tried to set shell=/bin/sh in vimrc then run /bin/sh, godef it also works. But in macvim it still doesn't work.
Anyway, I'll try with your vimrc tonight to see if it works.

**Comment by phuna** [comment]
After comparing your vimrc and mine, I found that I just set "syntax enable" but you set it in a condition block like:
```
if has("gui_macvim")
  " Some settings... (no syntax enable here)
else
  syntax enable
endif
```
I use above condition then voila, it works :). I'm new to vim so I'm not sure if it's really the root cause, maybe I misunderstand some fundamental concepts of vim here.
Anyway thanks a lot for sharing your vimrc.

**Comment by fatih** [comment]
That's great. Happy coding :+1: :)
