### ISSUE TITLE
Error when trying to run :GoRun

### ISSUE THREAD

**Issue by ddmin** [fatih/vim-go#3060]
### What did you do? (required: The issue will be **closed** when not provided)
Try running :GoRun on a Go file

### What did you expect to happen?
No errors and the GoRun to work.
### What happened instead?
I got the following error message:
```
Error detected while processing function go#cmd#Run:
line   87:
E121: Undefined variable: l:dir
E116: Invalid arguments for function go#util#Chdir
Press ENTER or type command to continue
```
#### vim-go version: 
1.24

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#begin('~/.vim/plugged')

nnoremap \<C-h\> :GoRename\<CR\>
nnoremap \<C-b\> :GoRun\<CR\>
nnoremap \<silent\> \<C-k\> :GoDoc\<CR\>

let g:go_echo_command_info = 0
set completeopt-=preview

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.5.0-745-g405044a41
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.15.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/ddmin/Code/Go/bin"
GOCACHE="/home/ddmin/.cache/go-build"
GOENV="/home/ddmin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ddmin/Code/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ddmin/Code/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build883438039=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.1
    golang.org/x/tools/gopls@v0.5.1 h1:AF3Uh7HF08SZpKFfgJO6zfF3bbxyDXWqdkK4kMXiQ1o=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_gosnippets = 1
g:go_echo_command_info = 0
g:go_jump_to_error = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
#3062 should fix this for you.

For what it's worth, you're not running vim-go 1.24 as reported; you must be running a later revision
