### ISSUE TITLE
[vim-go] could not determine the appropriate directory for gopls

### ISSUE THREAD

**Issue by AugustusKwan** [fatih/vim-go#3065]
### Issue Description
When I try to open/edit a `.go` file, neovim has the error message '[vim-go] could not determine the appropriate directory for gopls'.
No Go completion message to select.Sometime it hangs for a while for loading something. 

#### vim-go version:
Neovim 0.4.4

####  `init.vim` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
"Golang
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries','for':['go','vim-plug'],'tag':'*' }

let g:go_fmt_command = "goimports" " 格式化将默认的 gofmt 替换
let g:go_autodetect_gopath = 1
let g:go_list_type = "quickfix"

let g:go_version_warning = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_methods = 1
let g:go_highlight_generate_tags = 1

let g:godef_split=2

let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
</pre></details>

#### Vim version (first three lines from `:version`):
Neovim v0.4.4

#### Go version (`go version`):
Go 1.14.2

#### Go environment
Windows10 1909

**Comment by bhcleek** [comment]
Does this happen for you any go file that you try to open, or only some?

Are you using the linux subsystem?

**Comment by bhcleek** [comment]
Can you run `go env GOMOD` from the directory that contains the go file that you're trying to open and let me know what the output is?

**Comment by opennota** [comment]
I get the same error. At some point `vim-go` adds the module directory to `GOPATH`: `/home/xxx/your-module:/gopath` and then tries to get the value of `GOMOD` by calling `go env GOMOD`, which responds `$GOPATH/go.mod exists but should not`. After that `vim-go` says: `could not determine appropriate working directory for gopls`.

**Comment by opennota** [comment]
After some investigation, the culprit seems to be this line in my `.vimrc`:

`let g:go_autodetect_gopath = 1`

I commented it, and the error disappeared.

**Comment by bhcleek** [comment]
Do you have a `src` directory in your module?

**Comment by opennota** [comment]
Yes, I happen to have a `src` directory in my module.

**Comment by bhcleek** [comment]
👍 if you're not using gb, godep, or similar, then you don't need `g:go_autodetect_gopath` to be set. I've added #3076 to address the underlying issue, but we should probably just remove `g:go_autodetect_gopath` support fully now that modules is out and well supported by the Go toolchain, because Go modules and vendoring obviate the need for tools like gb and godep and those tools were archived long ago.
