### ISSUE TITLE
GoRun error: cannot open error file

### ISSUE THREAD

**Issue by orpheus** [fatih/vim-go#3067]
- macOS Catalina v10.15.7
- Vim version 8.2 (installed via `brew install vim`)
- zsh: stable 5.8
- go version go1.15.3 darwin/amd64
- vim-go v1.24 ( I think - it's just latest; not sure how to check)
- (not sure how to check gopls version)
- reproduced with .vimrc empty except vim-go (using vim-plug)

when running `GoRun`
 I get `Press ENTER or type command to continue`

I'll press ENTER then I get 

```
Error detected while processing function go#cmd#Run[90]..function go#cmd#Run:
line   84:
E40: Can't open errorfile /var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T/vxX4FOs/3
Press ENTER or type command to continue
```

> edit: I logged my cmd args in a go run main.go and saw `/var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T/go-build397719300/b001/exe/main` logged as the first argument which looks similar file path above. So it looks like `:GoRun` can't find the exe main file

```
call plug#begin('~/.vim/plugged')
    Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
```

I've ran `:PlugInstall` and `:GoInstallBinaries` both run successfully. 
Anyone know what it could be?

**Comment by bhcleek** [comment]
Perhaps your temporary directory is, `/var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T`, is not writeable by the user that you're running Vim as?

**Comment by orpheus** [comment]
`ls /var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T | grep vxX4FOs` doesn't show any results
So it appears the file doesn't exist, but if I run this go script:

```
// main.go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println(os.Args[:])
}
```
`go run main.go` 

it prints: `[/var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T/go-build368585855/b001/exe/main]`

but an `ls /var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T/go-build368585855/b001/exe/main`

also says there's no file/directory so I'm not sure what's going on

**Comment by bhcleek** [comment]
> ls /var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T | grep vxX4FOs doesn't show any results

I wouldn't expect it to.

Vim-go doesn't do anything special here; if the file can't be opened, then it's very likely that either the temporary directory doesn't exist (e.g. `/var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T` or that it's not writeable by the user that you're running Vim as. Please check the permissions on the temporary directory with respect to the user that's running vim.

**Comment by orpheus** [comment]
`drwx------@  96 roark  staff  3072 Oct 24 17:13 T`

**Comment by bhcleek** [comment]
Try creating a directory within that from vim by running `:!mkdir /var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T/orpheus-test`: does that work?

**Comment by orpheus** [comment]
```
zsh:1: command not found: mkdir

shell returned 127
```
new to vim, is this a zsh problem or does vim no know mkdir? can vim run bash commands and what's the diff between creating that dir from vim vs bash?

**Comment by bhcleek** [comment]
The `!` command runs shell commands (see `:help :!`). `mkdir` is usually a command. If `:!mkdir` is not working from within Vim, then I suspect something is amiss with your system or how you're running Vim.

The vim-go issue template prompts you for a lot of information that you didn't provide. Before continuing, I think it's appropriate to provide that information instead of going back and forth and asking for it all individually as needed. Your vim version, OS, etc. will be useful to get you going.

**Comment by orpheus** [comment]
Ok I added as much information as I could find to the beginning of my post, missing anything valuable?

**Comment by bhcleek** [comment]
This is very odd. Nothing about your system jumps out at me as problematic.

Does `:make` work for you from within vim-go?

Also, can you run `:GoReportGitHubIssue`, and then instead of creating a new issue, just copy the issue text and paste it here? It will give us a bit more info than what you put in the description.

**Comment by orpheus** [comment]
`:make` gives me back

```
zsh:1: command not found: tee

shell returned 127
```

and
 
```
E40: Can't open errorfile /var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T/vN
Qqxqb/2
```

`:GoReportsGithubIssue` outputs

```
<!--
Before filing an issue, please check if vim-go's help addresses your problem (see `:help go-troubleshooting`).

Consider executing `:GoReportGitHubIssue` to populate much of this information automatically.
-->
### What did you do? (required: The issue will be **closed** when not provided)

<!--
If possible, please provide clear steps for reproducing the problem.
-->

### What did you expect to happen?

### What happened instead?

### Configuration (**MUST** fill this out):

#### vim-go version:

####  `vimrc` you used to reproduce:
<!--
Use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc.

If this is not provided or is obviously incomplete, the issue may be unceremoniously closed.
-->
<!-- vimrc -->
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):
<!-- :version -->
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 16 2020 05:34:50)
macOS version
Included patches: 1-1850

#### Go version (`go version`):
<!-- go version -->
go version go1.15.3 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
<!-- go env -->
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/roark/Library/Caches/go-build"
GOENV="/Users/roark/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/roark/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/roark/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/roark/code/github/orpheus/go/golem/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/86/htttx7197fv90v3w5v6m_s_c0000gn/T/go-build453664118=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
<!-- gopls version -->
golang.org/x/tools/gopls v0.5.1
    golang.org/x/tools/gopls@v0.5.1 h1:AF3Uh7HF08SZpKFfgJO6zfF3bbxyDXWqdkK4kMXiQ1o=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_fmt_fail_silently = 0
g:go_gopls_enabled = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
g:go_fmt_command = 'goimports'
g:go_fmt_autosave = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>
```

**Comment by bhcleek** [comment]
Thank you, that's helpful. I'm still not sure what's going on, but the fact that Vim can find neither `tee` nor `make` makes me wonder if you have a your PATH setup strangely.

1. What does `:echo $PATH` output from within Vim?
1. What does  `echo $PATH` output when run on the commandline?

**Comment by orpheus** [comment]
from vim:
```
/Users/roark/.nvm/versions/node/v12.18.2/bin:/usr/local/bin:/usr/bin:/bin:/us
r/sbin:/sbin:/usr/local/go/bin:PATH:/usr/local/go/vim
```

from cl
```
/Users/roark/.nvm/versions/node/v12.18.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:PATH:/usr/local/go/vim
```

**Comment by bhcleek** [comment]
That's pretty close to mine. THE `/usr/local/go/vim` is odd, but since it's the last element in $PATH, it shouldn't be causing the problems you're seeing.

1. From within Vim, does `:echo $USER` report `roark`?
1. From within Vim what does `!which tee` output?
1. Try kicking off a shell from within Vim (`:sh`) and running your `go run` command at the commandline there; does that work? Is the result the same or different as when you run `go run` from a shell that you didn't kick off from within Vim?

I'm nearly stumped, but I can say with some confidence that whatever is happening here, Vim-go does not appear to be the source of the problems you're seeing.

**Comment by bhcleek** [comment]
I didn't notice it before, but it appears that your PATH has something amiss: The `PATH` there looks like you may have a typo some place that you meant to have `$PATH`.

**Comment by orpheus** [comment]
there it is! that was the issue, incorrect path naming, I forgot the `$` in front of path.. that would've taken me a while to catch. Thank you my friend

I had
`export PATH=PATH:/usr/local/go/vim`

vs `export PATH=$PATH:/usr/local/go/vim`
