### ISSUE TITLE
Confused vim-go under Cygwin

### ISSUE THREAD

**Issue by FedorLap2006** [fatih/vim-go#3069]
### What did I do?

1. Nuked my old configuration and `.vim` folder (to make sure I'm doing this from scratch).
2. Downloaded `vim-plug`.
3. Added vim-go plus two-three other plugins into `.vimrc` and downloaded them.
4. Invoked "GoInstallBinaries" to make sure all modules (most I already have) is installed.
5. Opened simple testing project under go modules system.
6. Added some code to try lint and format it.
7. Ran "GoLint" and "GoFmt" and "GoMetaLinter".

P.S. I have changed some code inside `autoload/go/util.vim` just to make sure I can't fix it by myself. If this code is needed I can provide it.
P.P.S. Most of binaries which installs (`GoInstallBinaries`) I installed by myself, because I couldn't fix some bug with paths. If it needed I can reinstall them :man_shrugging: 

### What did I expect to happen?

- **GoLint**: syntax and other errors about my code
- **GoMetaLinter**: errors about code style in my code
- **GoFmt**: formatted file (`main.go` for example)

### What happened instead?
- **GoLint**: 
     ![image](https://user-images.githubusercontent.com/42876964/97116252-06bd1200-170d-11eb-9ef1-12be97d68fc8.png)
- **GoMetaLinter**: 
     ![image](https://user-images.githubusercontent.com/42876964/97116655-9a8fdd80-170f-11eb-9b7e-266056e7641c.png)
- **GoFmt**:
      ![image](https://user-images.githubusercontent.com/42876964/97116281-294f2b00-170d-11eb-828d-665b94b1aae0.png)

:red_square: But, `GoLint` and `GoMetaLinter` with `.` argument (or `./...`) seems is working normally. But `GoFmt` is still confused. 

#### vim-go version:
1.24
####  `vimrc` I used to reproduce:

<details><summary>vimrc</summary><br><pre>
" As you can see - absolutely clear config

set nocompatible " be iMproved
filetype off

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'morhetz/gruvbox'
Plug 'fatih/vim-go'
call plug#end()

set background=dark
colorscheme gruvbox
</pre></details>
#### Vim version:

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  4 2018 23:29:48)
Included patches: 1-1567
Modified by <cygwin@cygwin.com>

#### Go version:

go version go1.15 windows/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=C:\GoLang\proj\bin
set GOCACHE=C:\Users\Федор\AppData\Local\go-build
set GOENV=C:\Users\Федор\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\GoLang\proj\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\GoLang\proj
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\GoLang\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\GoLang\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\cygwin64\home\Фёдор\code\go\vim-go-test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\cygwin64\tmp\go-build381032978=/tmp/go-build -gno-record-gcc-switches

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_gosnippets = 1
g:go_jump_to_error = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
> Most of binaries which installs (GoInstallBinaries) I installed by myself, because I couldn't fix some bug with paths.

Where did you install them to? Are you sure that vim-go isn't still trying to sue the old paths? If there's a bug, please report it so we can get it fixed.

> I have changed some code inside autoload/go/util.vim just to make sure I can't fix it by myself. If this code is needed I can provide it.

This could be a problem. Please revert whatever you've done so we can deal with vim-go and not a forked version.

> GoLint: syntax and other errors about my code

You got that. The golint error told you what was wrong.

> GoMetaLinter: errors about code style in my code

The path that golangci-lint reported is odd; it looks like part of a filepath was repeated for some reason. You can add `let g:go_debug=['shell-commands']` to your vimrc to see what command is actually being run and then try it manually at the commandline to see if this is somehow a problem with golangci-lint. Be sure to execute the command with the current working directory set to the directory that contains the file for the active buffer when you ran the vim-go command.

This looks like another symptom of the same problem that golangci-lint is seeing.

**Comment by bhcleek** [comment]
> Most of binaries which installs (GoInstallBinaries) I installed by myself, because I couldn't fix some bug with paths.

Where did you install them to? Are you sure that vim-go isn't still trying to sue the old paths? If there's a bug, please report it so we can get it fixed.

> I have changed some code inside autoload/go/util.vim just to make sure I can't fix it by myself. If this code is needed I can provide it.

This could be a problem. Please revert whatever you've done so we can deal with vim-go and not a forked version.


![image](https://user-images.githubusercontent.com/1958864/97117545-ace32a80-16c1-11eb-9e59-9c2b4fb4adf0.png)
> > GoLint: syntax and other errors about my code

You got that. The golint error told you what was wrong.

![image](https://user-images.githubusercontent.com/1958864/97117561-c1272780-16c1-11eb-8a26-52134065cfc7.png)
![image](https://user-images.githubusercontent.com/1958864/97117566-cab08f80-16c1-11eb-8b7b-6fa0787ea8c8.png)

Both of these errors look like they may be related to the same underlying issue. 

The path that golangci-lint reported is odd; it looks like part of a filepath was repeated for some reason. You can add `let g:go_debug=['shell-commands']` to your vimrc to see what command is actually being run and then try it manually at the commandline to see if this is somehow a problem with golangci-lint. Be sure to execute the command with the current working directory set to the directory that contains the file for the active buffer when you ran the vim-go command.

1. What is command is vim-go running for your `:GoMetaLinter` and `:GoFmt` invocations?
1. What is the full path to the file in the active buffer you run those commands as reported by `ls` on that file from within your shell?

**Comment by bhcleek** [comment]
I have more questions for you. Thank you for patience as we work through this; I do not have a Windows machine to test with and cygwin is a different environment than the usual Windows environment.

1. Which Vim are you using? Are you starting it from within your cygin shell?
1. Can you open a file (really any file should work, but for ease of diagnosis, one of your Go files would be best), run `:echo expand('%:p')` from with Vim and report the results back here?
1. For the file above, what does `echo $PWD` output when executed in your shell within the same directory that contains that file above?
1. Are you starting Vim from a cygwin shell?

**Comment by FedorLap2006** [comment]
> I have more questions for you. Thank you for patience as we work through this; I do not have a Windows machine to test with and cygwin is a different environment than the usual Windows environment.
No problem.

> 1. Which Vim are you using? Are you starting it from within your cygwin shell?
Read "Vim version" partition. You're right, I'm running Vim from Fish shell which is running in bash.

> 2. Can you open a file (really any file should work, but for ease of diagnosis, one of your Go files would be best), run `:echo expand('%:p')` from with Vim and report the results back here?
Sure, I will try this and respond here.
> 3. For the file above, what does `echo $PWD` output when executed in your shell within the same directory that contains that file above?
I think it will be directory with `go.mod` inside, but I will check this too.
> 4. Are you starting Vim from a cygwin shell?
It seems you're repeating the same question :/

**Comment by FedorLap2006** [comment]
I think the problem in the path 
![image](https://user-images.githubusercontent.com/42876964/97118988-5fe17180-171e-11eb-8e6b-f6f0970c566f.png)
But how this can be fixed?

**Comment by FedorLap2006** [comment]
And It tries to do this
![image](https://user-images.githubusercontent.com/42876964/97119035-9fa85900-171e-11eb-9331-8c02ba3f9838.png)

**Comment by bhcleek** [comment]
The `:GoLint`error is legitimate; Go does not support importing absolute paths.

**Comment by FedorLap2006** [comment]
> The `:GoLint`error is legitimate; Go does not support importing absolute paths.

I know, but the problem isn't there. I think there's some bug (of course...) which produces absolute path instead of relative to module.

Btw, I'm using modules system, so I'm outside `GOPATH`.

**Comment by bhcleek** [comment]
I wonder if you need to do `:GoUpdateBinaries` so that the tools will be compiled and installed from within cygwin

**Comment by FedorLap2006** [comment]
You think so?

**Comment by bhcleek** [comment]
Very possibly. IIRC correctly, the tools will need to be built under cygwin in order to be used within cygwin; one cannot simply build a tool in Windows and then use them under cygwin in a lot (most? all?) cases.

**Comment by FedorLap2006** [comment]
Sadly part is golang doesn't have any distribution for cygwin. That's why we can't just get the cygwin golang and run it.

**Comment by FedorLap2006** [comment]
Btw, there's no effect for paths. The errors is still same.

**Comment by FedorLap2006** [comment]
I think this problem may be solved only if actual path of file or package will be interpreted using cygpath. There's no other way to make this work. But that's only my personal opinion.

**Comment by bhcleek** [comment]
I don't think that's right; vim-go is known to work with Cygwin. Thought it's certainly worth asking why you want to use cygwin at all given that Go works with Windows without using Cygwin.

There are a number of posts (e.g. https://groups.google.com/g/golang-dev/c/cdWJAB-2Bg8) that talk about using Go from within cygwin.

> What command is vim-go running for your :GoMetaLinter and :GoFmt invocations?
> What is the full path to the file in the active buffer you run those commands as reported by ls on that file from within your shell?

Did you answer ☝️  and I missed it?

> I know, but the problem isn't there. I think there's some bug (of course...) which produces absolute path instead of relative to module. And no, that's not my mistake - this import isn't from code.

What happens if you run the golint command at the commandline? You can see the command to run in one of your screenshots: `/cygdrive/c/GoLang/proj/bin/golint /home/Федор/code/go/vim-go-test`

**Comment by FedorLap2006** [comment]
Hmm... the same output as vim-go. I think vim go provides the full path to my file, but It works only with relative path to current working directory (for example `cd .. && echo "pwd=~/code/go" && /cygdrive/c/GoLang/proj/bin/golint vim-go-test"` works fine)

**Comment by FedorLap2006** [comment]
> I don't think that's right; vim-go is known to work with Cygwin. Thought it's certainly worth asking why you want to use cygwin at all given that Go works with Windows without using Cygwin.

Only windows 10 has normal terminal and environment for Vim. I tried MSYS instead of Cygwin but It doesn't have lastest GoLang compiler version.

**Comment by bhcleek** [comment]
> Hmm... the same output as vim-go. I think vim go provides the full path to my file, but It works only with relative path to current working directory (for example cd .. && echo "pwd=~/code/go" && /cygdrive/c/GoLang/proj/bin/golint vim-go-test works fine)

The problem here, then is not with vim-go; it's with `golint` for some reason. For a number of reasons, Vim-go provides absolute paths to tools.

> Only windows 10 has normal terminal and environment for Vim. I tried MSYS instead of Cygwin but It doesn't have lastest GoLang compiler version.

You can use gVim under windows just fine. I've also use terminal Vim in the past with Windows.

**Comment by FedorLap2006** [comment]
> You can use gVim under windows just fine. I've also use terminal Vim in the past with Windows.
Terminal vim is more comfortable, but thanks for advice :)

**Comment by FedorLap2006** [comment]
But @bhcleek is there a way to do this inside cygwin? Just... there're already setuped workflow... and I just wanted to add go linting with completion.

**Comment by bhcleek** [comment]
I think the thing that's most likely to work is to run the Vim built for Windows from within your cygwin terminal. But I'm honestly not sure if that will work or not. I have some vague recollection of doing that back when I did most of my daily work on Windows, but that was long ago and I'm not sure if my recollection is correct.

You _might_ be able to compile Go fully under cygwin and then get this to work, but I'm not sure. Back when compiling Go required a C compiler it surely would have worked, but I'm not sure about now.

What you've run into is a common misconception about how cygwin works, what its purpose is, and how to use it. You definitely are not the first person to run into this kind of problem with cygwin.

From [cygwin's homepage](https://www.cygwin.com/) 
> Cygwin is not:
>
> * a way to run native Linux apps on Windows. You must rebuild your application from source if you want it to run on Windows.
> * a way to magically make native Windows apps aware of UNIX® functionality like signals, ptys, etc. Again, you need to build your apps from source if you want to take advantage of Cygwin functionality.

The problem is that the tools are built for Windows, not for cygwin, so they don't understand the paths they're given. In some cases the paths will work, but in others they won't, and there's very little that vim-go can do about it short of detecting that Vim is running under cygwin, and then calling `cygpath` to transform paths to and from Windows and unix style paths (and as I mentioned before, that is not currently on the roadmap - the effort just isn't worth the benefit). What you're trying to do isn't a supported workflow for any cygwin tool AFAIK: one can't pass Unix style paths to a Windows tool and expect them to be correctly understood as an absolute path.

Perhaps someone out there has compiled Go for cygwin and you could use that, but I'm not aware of such a case.

**Comment by FedorLap2006** [comment]
I think I can compile by myself Go under cygwin... but I think I just won't use vim-go and will be without gopls :man_shrugging:. That was a lot of pain...

**Comment by bhcleek** [comment]
If you can get Go running under cygwin as a cygwin compiled binary, then I think you'll be able to do `:GoUpdateBinaries` and keep using vim-go if you want 🤷
