### ISSUE TITLE
quickfix not populated

### ISSUE THREAD

**Issue by artemave** [fatih/vim-go#307]
`caddexpr` adds nothing _after_ file has been written.

Here my test:

1. open `.go` file
1. `:caddexpr "xx"`
1. `:copen` - can see "xx" :+1: 
1. `:cclose`
1. `:w`
1. `:caddexpr "yy"`
1. `:copen` - no "yy" :-1: 

The above is only true for `.go` files and `vim-go` is the only `go` related plugin I've got.

Anyone else is experiencing this?

**Comment by fatih** [comment]
I've just tested it and it worked for me without any problem:

http://d.pr/i/1comy

Is there a problem with your quickfix window ? Why do add manual entries into the list ?

**Comment by artemave** [comment]
Thanks for looking into this!

> I've just tested it and it worked for me without any problem

So it must be something else in my config somewhere. Sigh.

> Is there a problem with your quickfix window ?

This one is the first I am aware of :)

> Why do add manual entries into the list ?

Only to demonstrate the issue.

**Comment by fatih** [comment]
Alright, if you have a more specific problem and open an issue with a demo file it would be better. Other than this everything works fine. I always recommend people my own vimrc just for testing, it's here: https://github.com/fatih/dotfiles/blob/master/vimrc It's not the best, but with this everything works fine. At least you have something to compare :)
