### ISSUE TITLE
GoImpl to generate functions with default doc comments

### ISSUE THREAD

**Issue by preslavmihaylov** [fatih/vim-go#3070]
It would be nice when invoking `:GoImpl` to generate the function stubs of the interface you're implementing along with default documentation.

E.g.
```go
// Foo ...
func Foo() {
    panic("not implemented")
}

// Bar ...
func Bar() {
    panic("not implemented")
}
```

This will prevent the linter warnings one gets immediately after implementing an interface

**Comment by bhcleek** [comment]
Godoc is always good to have. This would be an issue to create in the `impl` too, though: https://github.com/josharian/impl

However, having godoc for your exported identifiers should always be useful. The godoc you suggest would not be useful godoc, and I'm not sure if there would be a good way to automate creation of useful godoc; if there were, then software documentation would be much better across the board. If all you're trying to do is avoid the missing godoc errors from `golint` or your metalinter, you might consider using staticcheck or gopls as your metalinter instead.
