### ISSUE TITLE
Go syntax highlight is not working

### ISSUE THREAD

**Issue by ronak4444** [fatih/vim-go#3072]
### What did you do? (required: The issue will be **closed** when not provided)
1. Install Macvim from brew latest
2. Install spf13 package
3. Spent 14 hrs to make Go syntax highlighting work, but Failed. And this was the result of my attempts to start Go autocomplete, snippets etc features

Observations:
(vim-go) initialized gopls does appear and I am able to run GoRun, GoDoc etc commands so I assume the installation of vim-go is fine 

Sorry I do not have a way to reproduce the issue.

### What did you expect to happen?
To have Go code being highlighted with solarized colorscheme that works for python files.
### What happened instead?
Grey characters, no colors

### Screenshots 
main.go file I am working on.
![Screen Shot 2020-10-27 at 07 02 55](https://user-images.githubusercontent.com/6653737/97246144-a4563580-1822-11eb-8974-f6a353ff4dcd.png)

Vim compiled packages list + Enviornment variable:
![Screen Shot 2020-10-27 at 07 06 26](https://user-images.githubusercontent.com/6653737/97246330-1dee2380-1823-11eb-8ac9-959ac9cd8bff.png)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
`"MY PRIVATE VIMRC PROFILE FILE - Modified from SPF13 setup"

syntax on
syntax enable

""Explicitly add 256 colorscheme support
set t_Co=256

""git commit messages structuring
autocmd Filetype gitcommit setlocal spell textwidth=72

let mapleader= ','
colorscheme solarized
set guifont=Menlo\ Regular:h12
set encoding=utf-8

let g:airline_theme = 'badwolf'
let g:airline#extensions#tabline#enabled = 1

"let g:neosnippet#disable_runtime_snippets = { "_": 1, }

""" GO setup
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_def_mode = 'gopls'
let g:go_info_mode = 'gopls'
let g:go_rename_command = 'gopls'
let g:go_metalinter_command = 'golangci-lint'
let g:go_metalinter_autosave = 0
let g:go_code_completion_enabled = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_structs = 1
let g:go_highlight_methods = 1
let g:go_highlight_functions = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

au filetype go inoremap <buffer> . .<C-x><C-o>
let g:go_gopls_enabled = 1

" Enable ftplugin detection, i.e Filetype specific configs at .vim/ftplugin/
filetype plugin on
filetype plugin indent on

:cd /Users/macos/Desktop/career/code/go

" start python3
call has('python3')

" "
</pre></details>

<details><summary>vimrc.before.local</summary><br><pre>
let g:spf13_bundle_groups=['general', 'neocomplete', 'neocomplcache', 'programming', 'go' ]
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct  7 2020 20:03:34)
macOS version
Included patches: 1-1719

#### Go version (`go version`):

flagvar has value  1234

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

flagvar has value  1234

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

version master, built in $GOPATH mode

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 1
g:go_highlight_operators = 1
g:go_loaded_gosnippets = 1
g:go_code_completion_enabled = 1
g:go_snippet_engine = 'neosnippet'
g:go_rename_command = 'gopls'
g:go_gopls_enabled = 1
g:go_metalinter_command = 'golangci-lint'
g:go_def_mode = 'gopls'
g:go_info_mode = 'gopls'
g:go_highlight_structs = 1
g:go_highlight_functions = 1
g:go_metalinter_autosave = 0
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_highlight_methods = 1
g:go_gotags_bin = 'gotags'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Unfortunately, I am not familiar with spf13's package. I can assure you, though, that syntax highlighting in vim-go generally works well.

Does running `:syntax enable` or `:syntax on` affect the highlighting for you?

**Comment by ronak4444** [comment]
No it does not. However, I did ran Vim in debug mode executing step by step and in that, for a second the file is highlighted and than its gone again. The traces were not clear on what might have affected that disabling. I have a gut feeling that some packages are overriding each other and final result is grey, but whos' who is a mystery.

**Comment by bhcleek** [comment]
That's odd. Can you put your cursor over a location that should be highlighted and execute `:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')`? That will tell you whether the location has highlight groups defined.

**Comment by ronak4444** [comment]
result : 
[]

What would you @bhcleek  suggest, where I should look next? And any debugging approach suggestions, any log traces to look at? Anything to move forward.

**Comment by ronak4444** [comment]
trimmed vimrc file updated. Things like Nerdtree, neocomplete defunct settings etc where removed.

**Comment by ronak4444** [comment]
After dropping most of the packages  and simply the vim-go and Vundle with solarized theme here is what I get. The formatting has improved but it is not to the extand vimrc file looks like colorful. Am I missing here something or this is what vim-go provides?
![Screen Shot 2020-10-28 at 23 11 45](https://user-images.githubusercontent.com/6653737/97475482-500e9b00-1973-11eb-8281-0d3fd69736b0.png)

vimrc file cut for color highlights
![Screen Shot 2020-10-28 at 23 16 04](https://user-images.githubusercontent.com/6653737/97475701-9532cd00-1973-11eb-95db-4e0ae70fb334.png)

**Comment by ronak4444** [comment]
Closing this one.
The problem is with spf13 vim distro. The repo is not being maintained for years now (did not noticed earlier). And my experiments show that spf13 installation and configuration regenerates this issue.
