### ISSUE TITLE
How to configure the formatter

### ISSUE THREAD

**Issue by scrouthtv** [fatih/vim-go#3074]
### What did you do? (required: The issue will be **closed** when not provided)
1. I installed `vim-go` and the binaries using `:GoInstallBinaries`.
2. Then I openend a test file:
```
package main    
    
import "fmt"    
    
                                                                
func doSomething() error {                                                            
  var err error                                                      
       err = someFunctionThatMayGiveAnError()                            
   if err != nil { return err }                                   
err = anotherFunctionAfterwards()                              
                    return err    
}    

func sizeAutoUnit(size float64) int {    
  if size < 1000 {    
    return 0    
  } else if size < 1000 * 1000 {    
    return 1    
  } else if size < 1000 * 1000 * 1000 {    
    return 2    
  } else if size < 1000 * 1000 * 1000 * 1000 {    
    return 3    
  } else {    
    return 4    
  }    
}    
```
3. Afterwards, I saved this file.

### What did you expect to happen?
The file is saved with fixed indentation

### What happened instead?
The file is saved with fixed indentation and two more things we're changed that I do not want:
a) the if is split into multiple lines:
before:
```
if err != nil {return err}
```
afterwards:
```
if err != nil {
  return err
}
```
b) the spacing around the mathematical operators is removed:
before:
``` 
size < 1000 * 1000 * 1000 * 1000
```
afterwards:
```
size < 1000*1000*1000*1000
```
My question is how do I configure the formatter's behaviour? I already tried changing the formatter to `gopls` and their documentation says that the editor has to configure the formatter's behaviour. Where do I put that configuration?
Thanks for any help in advance

### Configuration (**MUST** fill this out):
I have nothing configured beyond my `init.vim` that I posted below.

#### vim-go version:
I'm on `master`@`a5e2535` (on commit `a5e2535d31aa1d7c0fa8a4e77ee96b92ad185be5`)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
call plug#begin()
Plug 'fatih/vim-go', {'for': 'go'}
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):
go version go1.15.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lenni/.cache/go-build"
GOENV="/home/lenni/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lenni/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lenni/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build204565315=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.5.1
    golang.org/x/tools/gopls@v0.5.1 h1:AF3Uh7HF08SZpKFfgJO6zfF3bbxyDXWqdkK4kMXiQ1o=
</pre></details>

**Comment by bhcleek** [comment]
The Go formatter cannot be configured to the level that you desire. Generally, you'll find that all the formatters (`go fmt`, `gofmt`, `goimports`, and `gopls`) share a common style with only a very small number of knobs that can be turned. Those knobs generally only control simplifications and import adjustments.

The Go team wrote about the style around the time that the first formatter, `gofmt` was released: https://blog.golang.org/gofmt.

**Comment by scrouthtv** [comment]
Thanks a lot!
