### ISSUE TITLE
staticcheck doesn't appear to run

### ISSUE THREAD

**Issue by Integralist** [fatih/vim-go#3079]
### What did you do?

I wrote some code which issued a warning when manually executing the `staticcheck` tool, but no issues were reported at the time of me writing the code within vim.

### What did you expect to happen?

I expected vim to indicate there was an issue with the code.

### Configuration:

```viml
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()

let g:go_fmt_command = 'goimports'
let g:go_gopls_complete_unimported = 1
let g:go_gopls_staticcheck = 1
let g:go_metalinter_command='gopls'
let g:go_metalinter_deadline = '20s'

autocmd BufWritePost *.go :GoErrCheck! -ignoretests
```

Example code that staticcheck should have made a suggested change for:

```diff
- if version.PreRelease(version.AppVersion) == false {
+ if !version.PreRelease(version.AppVersion) {
```

#### vim-go version:

Latest version (`35ea9ac`) as of two days ago (`v1.24`).

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 11 2020 13:03:49)                                                                             
macOS version                                                                                                                                  
Included patches: 1-1830
```

#### Go version (`go version`):

```
go version go1.15.2 darwin/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/integralist/Library/Caches/go-build"
GOENV="/Users/integralist/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/integralist/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/integralist/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/integralist/Code/fastly/cli/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zf/zlsh3t3n21ngmbzl_wr6ymm80000gn/T/go-build197159879=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.5.2
    golang.org/x/tools/gopls@v0.5.2 h1:lyHTekqy0QhXzz5hDFnfMGHk0Qmuq+LWH5VN/o19YLk=

</pre></details>

**Comment by bhcleek** [comment]
What did you do that you thought would trigger the staticcheck messages?

**Comment by bhcleek** [comment]
> Latest version (35ea9ac) as of two days ago (v1.24).

Which are you using? 35ea9ac is the latest master while v1.24 is the latest release.

**Comment by Integralist** [comment]
> Which are you using? 35ea9ac is the latest master while v1.24 is the latest release.

I'm using vim-plug and it doesn't indicate what 'version' of vim-go I have other than a commit hash so it looks like I'm not using `v1.2.4` but 'latest master'.

**Comment by Integralist** [comment]
> What did you do that you thought would trigger the staticcheck messages?

I presumed that writing code such as `if <some_value> == false` would have flagged a warning to say I should have written `if !<some_value>`.

As it happened it wasn't until my CI manually ran `staticcheck` that I discovered the code wasn't abiding by what the staticcheck tool expected.

**Comment by bhcleek** [comment]
> I'm using vim-plug and it doesn't indicate what 'version' of vim-go I have other than a commit hash so it looks like I'm not using v1.2.4 but 'latest master'.

Plug updates a git working tree. You should be able to run `git rev-parse HEAD` to know for sure which vim-go SHA you're at.

> I presumed that writing code such as if <some_value> == false would have flagged a warning to say I should have written if !<some_value>.

You can run `:GoDiagnostics` to see the warnings and errors in a quickfix window. You can set `g:go_diagnostics_level` to flag issues that staticcheck identifies when gopls is informed of an update to the code (that happens under a variety of scenarios), and you can set `g:go_metalinter_autosave` to see a warnings and errors for the current buffer in a location list window.
