### ISSUE TITLE
:GoDecls preview with fzf error

### ISSUE THREAD

**Issue by zdmgmail** [fatih/vim-go#3080]
### What did you do?

use `:GoDecls` with fzf preview

![11-04_22:18:39](https://user-images.githubusercontent.com/50515839/98122603-c9fed100-1eeb-11eb-995e-7f8bb827ee10.png)

if not preview, not get error

how can I let this preview work? 

### What did you expect to happen?

preview  like `https://github.com/liuchengxu/vista.vim`

![11-04_22:23:28](https://user-images.githubusercontent.com/50515839/98123090-64f7ab00-1eec-11eb-88b5-459b3b6b4809.png)

if cannot preview, how can I set not preview for this command but not change env var `FZF_DEFAULT_OPTS`

### Configuration 

in shell: 

`export FZF_DEFAULT_OPTS='--layout=reverse --height 80% --preview  "cat {}"'`

**Comment by bhcleek** [comment]
What you're trying to do isn't _strictly_ supported, but you could conceivably use the third field and parse it up using awk or another utility. That's relying on an implementation detail in vim-go that could change, though.

Notice that the preview you're looking for seems to mosty already in place in the `:GoDecls` output, though, too...

**Comment by zdmgmail** [comment]
> What you're trying to do isn't _strictly_ supported, but you could conceivably use the third field and parse it up using awk or another utility. That's relying on an implementation detail in vim-go that could change, though.
> 
> Notice that the preview you're looking for seems to mosty already in place in the `:GoDecls` output, though, too...

don't have preview seems ok .. but how to use the `FZF_DEFAULT_OPTS` with preview but only not preview in `:GoDecls` ?

**Comment by bhcleek** [comment]
vim-go doesn't have a good way of controlling that currently.

**Comment by bhcleek** [comment]
@zdmgmail can you give #3081  a try? I think it might be the experience you're looking for.

**Comment by zdmgmail** [comment]
> @zdmgmail can you give #3081 a try? I think it might be the experience you're looking for.

successful! thanks a lot
