### ISSUE TITLE
Feature: Integrated with the other terminal command or plugin

### ISSUE THREAD

**Issue by zdmgmail** [fatih/vim-go#3082]
### What did you do? 

I'm using the plugin `https://github.com/voldikss/vim-floaterm` 

and change many command about open term from `:term` to `:FloatermNew` or `FloatermNew --height=... position=...`

### What did you expect to happen?

I hope have an setting  change default term to this plugin , or change any `:term` command to any command, or just change `term` in a single commmand like `GoTest` or `GoImplements`

**Comment by zdmgmail** [comment]
want to use floaterm because it can show and hide, and can have many terminal , easy to switch between them

**Comment by bhcleek** [comment]
Maybe you can use some of the features of vim-floaterm to provide commands to do what you want, but I'm not sure. I don't intend to add support for that plugin to vim-go natively.
