### ISSUE TITLE
Issue with additional highlighting through _vimrc

### ISSUE THREAD

**Issue by PurpleHobo** [fatih/vim-go#3091]
### What did you do? (required: The issue will be **closed** when not provided)
installed vim-go and its binaries and tried to enable highlighting options in my _vimrc. I tried quiet a few of the things others did to fix it but it did not help.

### What did you expect to happen?
I expected things like fmt.Println() to be highlighted

### What happened instead?
no additional highlighting occurred

####  `vimrc` you used to reproduce:

<details><summary></summary><br><pre>
syntax on
set syntax=enable
call plug#begin('~/.vim/plugged')	
Plug 'OmniSharp/omnisharp-vim'
let g:OmniSharp_server_stdio = 1
let g:OmniSharp_server_path = 'C:/Users/cttry/Downloads/omnisharp-win-x64/OmniSharp.exe'
Plug 'joshdick/onedark.vim'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'morhetz/gruvbox'
Plug 'kana/vim-surround'
Plug 'vim-scripts/VimCompletesMe' 
Plug 'Yggdroot/indentLine'
call plug#end()
colorscheme gruvbox 
autocmd BufEnter *.go colorscheme onedark 
set background=dark
let g:go_fmt_command = "goimports"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_structs = 1 
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2020 07:56:56)
#### Go version (`go version`):

go version go1.15.4 windows/amd64
#### Go environment
<details><summary><code>go env</code></summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\cttry\AppData\Local\go-build
set GOENV=C:\Users\cttry\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\cttry\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\cttry\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre>golang.org/x/tools/gopls v0.5.2</details>

**Comment by PurpleHobo** [comment]
![image](https://user-images.githubusercontent.com/64588827/99042401-66099600-25d8-11eb-8dbb-9b1c6f21c600.png)
Here is an image of the lack of highlighting in my gvim (also doesnt work in vim either)

**Comment by PurpleHobo** [comment]
also doesnt work with all plugins off besides vim-plug
![image](https://user-images.githubusercontent.com/64588827/99136012-94d24b80-266e-11eb-925b-2619df0485af.png)

**Comment by bhcleek** [comment]
Thanks. I can duplicate this and will take a look soon.

**Comment by bhcleek** [comment]
Add `let g:go_highlight_function_calls=1` to your vimrc to highlight function and method calls.

**Comment by PurpleHobo** [comment]
Cheers man, it works! Thank you brother.
