### ISSUE TITLE
Feature: GoTest when multi windows

### ISSUE THREAD

**Issue by zdmgmail** [fatih/vim-go#3092]
### What did you do? 

open two files in two window , `a.go a_test.go`, use `:GoTest` in a.go

### What did you expect to happen?

 use `GoTest` in a.go and got a error, now `GoTest` will change a.go to a_test.go 

if just one window, hope it same as before
if already have another window  a_test.go , hope it just focus a_test.go, not have two a_test.go window

**Comment by bhcleek** [comment]
You can get the behavior you're looking for by adding `set switchbuf='useopen'`. See `:help switchbuf`.

**Comment by zdmgmail** [comment]
> You can get the behavior you're looking for by adding `set switchbuf='useopen'`. See `:help switchbuf`.

I add this but seems not change ..
