### ISSUE TITLE
how to not fold on save?

### ISSUE THREAD

**Issue by zdmgmail** [fatih/vim-go#3098]
### What did you do? 

use `zM` fold  all , and use `zo` open a fold

if I have vim-go, after `:w` will lose `zo` effect

my vimrc

```
set foldlevel=99
set foldenable
set foldmethod=syntax

call plug#begin(plugPosition)
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }
call  plug#end()
```

how can I not lose `zo` after save file?

**Comment by rkennedy** [comment]
You can try setting `let g:go_fmt_experimental = 1` in your .vimrc, as described in issue #502.

**Comment by bhcleek** [comment]
In addition to @rkennedy's recommendation, you may also consider using `gopls` for formatting and adjusting imports, because the method that it uses to adjust lines should not cause folds to be closed.

```
let g:go_fmt_command='gopls'
```
