### ISSUE TITLE
[feature request] ftdetect and syntax highlighting for go.sum

### ISSUE THREAD

**Issue by smartding** [fatih/vim-go#3101]
There's ftdetect and syntax highlighting for go.mod.
Can we have those for go.sum?
Right now in neovim, go.sum is assigned "herculles" for filetype, and syntax highlighting looks terrible.

**Comment by bhcleek** [comment]
Given that go.sum is not intended to be edited, I don't see much value in adding an entry to `ftdetect/gofiletype.vim` and syntax highlighting for it. But if you want to contribute a PR for a syntax files add an entry to the `ftdetect/gofiletype.vim` file, I'll gladly review it.

Alternatively, you have several methods (see `:help filetype`) to set the filetype as you desire on your system. Here's the one I would use. Create a file named `filetype.vim` next to your vimrc file with these contents:
```
if exists("did_load_filetypes")
	finish
endif
augroup filetypedetect
	au! BufRead,BufNewFile go.sum setfiletype text
augroup END
```

**Comment by smartding** [comment]
> Given that go.sum is not intended to be edited, I don't see much value in adding an entry to `ftdetect/gofiletype.vim` and syntax highlighting for it. But if you want to contribute a PR for a syntax files add an entry to the `ftdetect/gofiletype.vim` file, I'll gladly review it.
> 
> Alternatively, you have several methods (see `:help ftdetect`) to set the filetype as you desire on your system. Here's the one I would use. Create a file named `filetype.vim` next to your vimrc file with these contents:
> 
> ```
> if exists("did_load_filetypes")
> 	finish
> endif
> augroup filetypedetect
> 	au! BufRead,BufNewFile go.sum setfiletype text
> augroup END
> ```

I don't intend to edit go.sum, I just review its content occasionally, so ftdetect and syntax highlighting would be a help.
Setting filetype to text just clears all highlight, which isn't quite ideal.
I'll leave this issue open so that people can see that we've already discussed this, if it's ok with you.
