### ISSUE TITLE
run try-catch failed with  GoDef and GoDefType

### ISSUE THREAD

**Issue by johncming** [fatih/vim-go#3103]
### What did you do? (required: The issue will be **closed** when not provided)

I want to run the command `GoDef` when trying `GoDefType` failed.

```
try
    GoDefType
catch
    GoDef
endtry
```

But the result is that `GoDef` doesn't work

### What did you expect to happen?

I want to run the command `GoDef` when trying `GoDefType` failed.

### What happened instead?

`vim-go: start pos is not valid`

#### vim-go version:

go version go1.15.5 darwin/amd64

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

Not custom configs.

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 17 2020 01:45:49)
macOS version
Included patches: 1-2000

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.3
    golang.org/x/tools/gopls@v0.5.3 h1:C8QSrqjqaVzlVoHL1R9yWbROoOApRgI8gN1G+cHlPuw=
</pre></details>

**Comment by bhcleek** [comment]
Vim-go's commands generally do not throw an exception that one could catch. In addition, most of the commands are asynchronous and even if exceptions were thrown, the `catch` statement like you're trying would never catch an exception, because `:GoDef` would complete before the exception would be thrown.

**Comment by johncming** [comment]
> Vim-go's commands generally do not throw an exception that one could catch. In addition, most of the commands are asynchronous and even if exceptions were thrown, the `catch` statement like you're trying would never catch an exception, because `:GoDef` would complete before the exception would be thrown.

I got it. Thank you very much.

**Comment by bhcleek** [comment]
@johncming it's worth noting that `:GoDef` will jump to the type definition when the cursor is on a type name.
