### ISSUE TITLE
could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by dopey** [fatih/vim-go#3104]
I'm able to `go build ./...` the project and generate executables, but unable to build from within `vim-go` due to an issue accessing github https. I use `ssh` keys over git to access all my private projects, so wondering why `vim-go` is attempting to access a project over `https`. I've verified that `vim-go` tooling does work on my teams public projects and some of the private projects. But for some reason, this one isn't working. 

### What did you do? (required: The issue will be **closed** when not provided)

Trying to run `:GoBuild` on a private github project. The clone address for the project looks like `org-xxx@github.com:{team}/{repo}.git`.

### What did you expect to happen?

Expected vim-go to build the project.

### What happened instead?

Getting a fatal error that looks to be the result of permission issues involving git.

#### vim-go version:

069113c1 -- master, I believe

####  `vimrc` you used to reproduce:

The `vim-go` configuration is provided below (via the helpful github issue tool). Link to my vimrc https://github.com/dopey/home/blob/master/.vim/vimrc.

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.15.5 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/max/Library/Caches/go-build"
GOENV="/Users/max/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/max/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/max"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/max/src/github.com/smallstep/landlord/rpc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dj/3fgqh_gx4tnd07cg9ybxz8j00000gn/T/go-build169901177=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.4
    golang.org/x/tools/gopls@v0.5.4 h1:PkQWDfzw8CxoseHDQniF2GhzmndN8KnQL6gcG2gnF3Y=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_list_type = 'quickfix'
g:go_highlight_operators = 1
g:go_highlight_fields = 1
g:go_metalinter_autosave_enabled = ['deadcode', 'gosimple', 'govet', 'golint', 'ineffassign', 'staticcheck', 'structcheck', 'typecheck', 'unused', 'varcheck']
g:go_metalinter_command = 'golangci-lint'
g:go_addtags_transform = 'camelcase'
g:go_highlight_functions = 1
g:go_metalinter_autosave = 0
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_highlight_methods = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

Relatedly, how can I see the actual command that is run when I execute `:GoBuild`? If I could replicate the failure from the command line maybe I could get a better error message.

thanks

**Comment by dopey** [comment]
Made some progress in debugging and I've narrowed the issue down to being related to a `GOPRIVATE` dependency we're using. On the command line if I run `GOPRIVATE go get` everything completes successfully.

However, from within `vim-go`, with `GOPRIVATE` set in the environment I'm still getting a NOT FOUND error for that specific repo (the one using GOPRIVATE). So something in `:GoBuild` isn't respecting the `$GOPRIVATE` variable?

**Comment by bhcleek** [comment]
`:GoBuild` shells out to `go build`. You can see the commands that vim-go runs by using `let g:go_debug=['shell-commands']`. If you miss the command on the cmdline, you can use `:messages` to see it again.

From your `go env` output, it seems that `GOPRIVATE` is not set in the environment when Vim is run. How are you setting it?

**Comment by dopey** [comment]
Thanks for the quick response @bhcleek! The bit about the `go_debug...` command really helped. Was able to see that `go build -tags` was breaking only when called from a specific subfolder. Our `go.mod` is strange and the issue appears to be a problem with `golang`. We'd submit an issue but we're sort of bastardizing how `go.mod` is meant to be used, so fixing our technical debt probably make more sense.

Anyhow, thanks for helping me get further to the crux of the issue.

**Comment by ralpheichelberger** [comment]
was troubled by that same problem and found this post on stackoverflow solved my problem:
https://stackoverflow.com/questions/58305567/how-to-set-goprivate-environment-variable

**Comment by andry81** [comment]
Currently have the same issue with `git fetch`:

https://github.com/andry81/github-accum-stats/runs/4429723185?check_suite_focus=true#step:2:169

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
  Waiting 14 seconds before trying again
```

**Comment by bazen-teklehaymanot** [comment]
I was getting similar error message. In my case it was resolved after updating the PAT scopes & granting permission to read user data.

**Comment by HollisTech** [comment]
Just to save somebody else the headache: after regenerating the PAT you need to copy the new PAT into the secret, duh. Obvious now, but not obvious (to me) yesterday.
