### ISSUE TITLE
Omni completion includes too much info in the completion list

### ISSUE THREAD

**Issue by rsheasby** [fatih/vim-go#3105]
### What did you do? (required: The issue will be **closed** when not provided)

Installed vim-go in a clean init.vim
Installed dependencies with :GoInstallBinaries
Typed "fmt." and pressed C-X C-O

### What did you expect to happen?
Each completion entry to appear as one line, with just the function signature but not the comment. Only when selecting an item, I'd expect to see its documentation as a pop-up.

### What happened instead?
Each entry takes up three lines, including the documentation comment, instead of appearing as a separate pop-up window. See attached image.
![Screenshot 2020-12-03 at 12 18 07 PM](https://user-images.githubusercontent.com/13928654/100998255-eed67a80-3563-11eb-8a15-061a448fe19f.png)

### Configuration (**MUST** fill this out):
```
call plug#begin("~/.nvim_plugged/")

Plug 'fatih/vim-go', { 'for': 'go'}

call plug#end()
```

#### vim-go version:
Unsure how to check this, but was installed a few minutes ago, so presumably latest?

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

call plug#begin("~/.nvim_plugged/")
Plug 'fatih/vim-go', { 'for': 'go'}
call plug#end()
![Screenshot 2020-12-03 at 12 18 07 PM](https://user-images.githubusercontent.com/13928654/100998198-e1b98b80-3563-11eb-950b-b3c8a489d43e.png)
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.15.5 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rsheasby/Library/Caches/go-build"
GOENV="/Users/rsheasby/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rsheasby/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rsheasby/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/rsheasby/Documents/gocrypt/gocrypt/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0c/2sl06rjs6zd6zv54wz2s7fyw0000gn/T/go-build895833217=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

gopls, built in GOPATH mode master
    gopls, built in GOPATH mode@master

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
What value do you have for the`completeopt` option?

**Comment by rsheasby** [comment]
The example you saw was the default settings, but I've also tried with
`set completeopt=menu,menuone,preview,noinsert,noselect` and
`set completeopt=menu,menuone,noinsert,noselect`

**Comment by bhcleek** [comment]
I wonder if this has something to do with the version of gopls you're using. I can't duplicate the behavior you're seeing and your `gopls` version looks like it's not one of the official releases. Can you execute `:GoUpdateBinaries gopls` and try again?

**Comment by rsheasby** [comment]
Maybe it's a macOS specific problem? I initially installed gopls using GoUpdateBinaries, and I've just tried it again after cleaning out my ~/go/bin directory, then running :GoUpdateBinaries, and I'm getting the exact same behaviour.

**Comment by rsheasby** [comment]
Oh my, Apologies this was actually misplaced blame. It seems this only happens when I'm using neovim-qt for some reason. Running nvim from the command line doesn't do this. Very strange, I wonder if the issue is a missing build feature for neovim-qt or even just a misconfig.

**Comment by rsheasby** [comment]
In case anyone else stumbles upon this issue, the culprit is neovim-qt attempting to hijack the popup menu to draw it with GUI instead of TUI. The solution is to add this to ginit.vim:
```
GuiPopupmenu 0
```
