### ISSUE TITLE
Completion menu first item gets auto filled 

### ISSUE THREAD

**Issue by vivekmurali2k** [fatih/vim-go#3106]
### What did you do? (required: The issue will be **closed** when not provided)
Typed 
```go
fmt.
```

### What did you expect to happen?
Expected to get list of completion items

### What happened instead?
Got a list of items but first item was already selected and gets completed without pressing anyti
![image](https://user-images.githubusercontent.com/45914640/101055921-6d590980-35b0-11eb-9135-5c9864e315ac.png)

### Configuration (**MUST** fill this out):
    call plug#begin('~/vimfiles/plugged')
    Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
    call plug#end()

#### vim-go version:
Latest
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM 8.2
#### Go version (`go version`):

go1.15.5 windows/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\vivek\AppData\Local\go-build
set GOENV=C:\Users\vivek\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\vivek\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\vivek\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\WINDOWS\TEMP\go-build566118250=/tmp/go-build -gno-record-gcc-switches
```
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

v0.5.4
</pre></details>

**Comment by bhcleek** [comment]
This behavior is not up to vim-go. Vim-go only supplies the matches to Vim. The behavior you're seeing is controlled by `completeopt` option. See `:help 'completeopt'`.

**Comment by vivekmurali2k** [comment]
Thanks, used 
:set cot+=longest 
to fix it
Closing issue
