### ISSUE TITLE
Error reporting with vim-go in v8.1.0000 vim

### ISSUE THREAD

**Issue by guonaihong** [fatih/vim-go#3108]
### What did you do? (required: The issue will be **closed** when not provided)
Upgrade vim to version v8.1.0000

Going back to v8.0.1850 is no problem.

The next version of v8.0.1850 is v8.1

### What did you expect to happen?
Normal use of vim go
### What happened instead?
```
处理 /home/guo/.vim/plugged/vim-go/syntax/go.vim 时发生错误:
第  115 行:
E475: 无效的参数: goFormatSpecifier   /\
第  116 行:
E10: \ 后面应该跟有 /、? 或 &
第  117 行:
E10: \ 后面应该跟有 /、? 或 &
第  118 行:
E10: \ 后面应该跟有 /、? 或 &
第  119 行:
E10: \ 后面应该跟有 /、? 或 &
第  120 行:
E10: \ 后面应该跟有 /、? 或 &
第  151 行:
E10: \ 后面应该跟有 /、? 或 &
第  153 行:
E10: \ 后面应该跟有 /、? 或 &
第  156 行:
E10: \ 后面应该跟有 /、? 或 &
第  158 行:
E10: \ 后面应该跟有 /、? 或 &
第  285 行:
E10: \ 后面应该跟有 /、? 或 &
第  312 行:
E10: \ 后面应该跟有 /、? 或 &
第  313 行:
E10: \ 后面应该跟有 /、? 或 &
第  314 行:
E10: \ 后面应该跟有 /、? 或 &
第  315 行:
E10: \ 后面应该跟有 /、? 或 &
第  316 行:
E10: \ 后面应该跟有 /、? 或 &
第  353 行:
E10: \ 后面应该跟有 /、? 或 &
第  354 行:
E10: \ 后面应该跟有 /、? 或 &
第  355 行:
E10: \ 后面应该跟有 /、? 或 &
第  356 行:
E10: \ 后面应该跟有 /、? 或 &
第  364 行:
E10: \ 后面应该跟有 /、? 或 &
第  365 行:
E10: \ 后面应该跟有 /、? 或 &
第  377 行:
E399: syntax region goPackageComment    start=/\v(\/\/.*\n)+\s*package/ 的参数太少
第  378 行:
E10: \ 后面应该跟有 /、? 或 &

```
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

" Vim color file
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last Change:	2001 Jul 23

" This is the default color scheme.  It doesn't define the Normal
" highlighting, it uses whatever the colors used to be.

" Set 'background' back to the default.  The value can't always be estimated
" and is then guessed.
hi clear Normal
set bg&

" Remove all existing highlighting and set the defaults.
hi clear

" Load the syntax highlighting defaults, if it's enabled.
if exists("syntax_on")
  syntax reset
endif

let colors_name = "default"

" vim: sw=2
set nu
set ts=4
set sw=4
set expandtab
set tags=tags;

syntax enable
"filetype plugin indent on

call plug#begin('~/.vim/plugged')

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'tag': '*' }
Plug 'rust-lang/rust.vim'
Plug 'racer-rust/vim-racer'

call plug#end()

let g:rustfmt_autosave = 1
" let g:syntastic_rust_checkers = ['rustc', 'cargo']

let g:go_term_mode = "vsplit"

if has('nvim')
 Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
 Plug 'Shougo/deoplete.nvim'
 Plug 'roxma/nvim-yarp'
 Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1

augroup Racer
    autocmd!
    autocmd FileType rust nmap <buffer> gd         <Plug>(rust-def)
    autocmd FileType rust nmap <buffer> gs         <Plug>(rust-def-split)
    autocmd FileType rust nmap <buffer> gx         <Plug>(rust-def-vertical)
    autocmd FileType rust nmap <buffer> gt         <Plug>(rust-def-tab)
    autocmd FileType rust nmap <buffer> <leader>gd <Plug>(rust-doc)
    autocmd FileType rust nmap <buffer> <leader>gD <Plug>(rust-doc-tab)
augroup END

</pre></details>

#### Go version (`go version`):

go version go1.14.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/guo/.cache/go-build"
GOENV="/home/guo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/guo/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/home/guo/go-version/go1.14.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/guo/go-version/go1.14.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build596804581=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.5
    golang.org/x/tools/gopls@v0.5.5 h1:YBLs2WCwxx6mBF98Y6/mDIpKhP4Dt4Dz2q6LnMRBpDw=
</pre></details>

**Comment by bhcleek** [comment]
This looks like it may have been a bug in Vim. ref: https://github.com/vim/vim/issues/3014

Can you try updating to a later version of Vim?

**Comment by guonaihong** [comment]
I've tried the latest version and I have problems.

**Comment by bhcleek** [comment]
I'm not able to duplicate this, and I don't think I've ever seen this before. I noticed a couple of things that are odd about your vimrc, though

First the header in your vimrc says it's a color file. Is this truly a vimrc file that you're using to duplicate this problem or is it missing content?

Second, I don't see anyplace in your vimrc where syntax is enabled. `syntax reset` doesn't turn on syntax highlighting as far as I know.

Finally, `colors_name` should usually not be assigned in your vimrc.

**Comment by guonaihong** [comment]
Color is the console tag specified in the markdown syntax of GitHub. Now I have recovered。

**Comment by guonaihong** [comment]
In the problematic version, I continue to try the following methods. This problem may be related to the installation location of vim.



* Can be configured


```
./configure --with-features=huge \
--enable-multibyte \
--enable-rubyinterp=yes \
--enable-python3interp=yes \
--enable-perlinterp=yes \
--enable-luainterp=yes \
--prefix=/usr/local/vim \
```



* This is the configuration I used. There is a problem
```
./configure --with-features=huge \
--enable-multibyte \
--enable-rubyinterp=yes \
--enable-python3interp=yes \
--enable-perlinterp=yes \
--enable-luainterp=yes \
--prefix=/usr \
```

**Comment by bhcleek** [comment]
This is almost certainly not caused by the installation directory.  A commenter on vim/vim#7455 identified a likely root cause for you: https://github.com/vim/vim/issues/7455#issuecomment-743576929

**Comment by guonaihong** [comment]
It looks like it's going into vim compatibility mode
