### ISSUE TITLE
How can I see which structure implements the method defined by the interface？

### ISSUE THREAD

**Issue by youshintop** [fatih/vim-go#3109]
### What did you do? (required: The issue will be **closed** when not provided)
When I use `vim` + `vim-go` to view the source code of the project, I want to see which structures implement the methods defined by the interface?

#### vim-go version:
Latest code of current master branch
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
You can use `:GoImplements` in GOPATH mode.

**Comment by youshintop** [comment]
ok, thanks. 👍
