### ISSUE TITLE
Does my :GoDecls display correctly?

### ISSUE THREAD

**Issue by hungrybirder** [fatih/vim-go#3110]
Hello, @bhcleek 
I got a problem when I use :GoDecls command with fzf.vim.
On the right side, it just shows the function name, no function body. Is that right?

![image](https://user-images.githubusercontent.com/1021047/101743851-c6bbbe00-3b05-11eb-8b19-8ea7a9352a60.png)

`main.go`
```
package main

import "fmt"

// Hello just hello
func Hello() {
	fmt.Println("hello world")
}

func main() {
	fmt.Println("main done")
}
```

#### vimrc
```
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'stsewd/fzf-checkout.vim'
let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.8 } }
nnoremap <C-p> :GFiles<CR>
let g:fzf_action = {
  \ 'ctrl-x': 'split',
  \ 'ctrl-]': 'vsplit' }

let g:go_test_prepend_name = 1
let g:go_fmt_fail_silently = 1
let g:go_fmt_command = "goimports"
let g:go_def_mode = "gopls"
" let g:go_implements_mode = 'gopls'
let g:go_list_type = "quickfix"
let g:go_auto_type_info = 1
let g:go_fmt_autosave = 1
let g:go_auto_sameids = 0
let g:go_doc_popup_window = 1
let g:go_null_module_warning = 0
let g:go_echo_command_info = 1
let g:go_autodetect_gopath = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_metalinter_enabled = ['vet', 'golint']
let g:go_highlight_space_tab_error = 0
let g:go_highlight_array_whitespace_error = 0
let g:go_highlight_trailing_whitespace_error = 0
let g:go_highlight_extra_types = 0
let g:go_highlight_build_constraints = 1
let g:go_highlight_types = 0
let g:go_highlight_operators = 1
let g:go_highlight_format_strings = 0
let g:go_highlight_function_calls = 0
let g:go_gocode_propose_source = 1
let g:go_addtags_transform = 'camelcase'
let g:go_fold_enable = []
let g:go_debug_log_output = 'debugger'
" set vars/stack/out/goroutines windows
let g:go_debug_windows = {
            \ 'vars':  'rightbelow 55vnew',
            \ 'stack': 'topleft 5new',
            \ 'out': 'botright 4new',
\ }

function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction
```

#### Vim version (first three lines from `:version`):

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.15.5 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/liyong/go/bin"
GOCACHE="/Users/liyong/Library/Caches/go-build"
GOENV="/Users/liyong/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/liyong/go/pkg/mod"
GONOPROXY=""
GOOS="darwin"
GOPATH="/Users/liyong/go"
GOPRIVATE=""
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/liyong/go/src/github.com/hungrybirder/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d0/xcd__6ws5078rfkpggyg82680000gn/T/go-build786877765=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.5
    golang.org/x/tools/gopls@v0.5.5 h1:YBLs2WCwxx6mBF98Y6/mDIpKhP4Dt4Dz2q6LnMRBpDw=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 1
g:go_debug_windows = {'vars': 'rightbelow 55vnew', 'out': 'botright 4new', 'stack': 'topleft 5new'}
g:go_doc_popup_window = 1
g:go_highlight_space_tab_error = 0
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_install = 1
g:go_highlight_function_calls = 0
g:go_autodetect_gopath = 1
g:go_highlight_trailing_whitespace_error = 0
g:go_null_module_warning = 0
g:go_highlight_format_strings = 0
g:go_echo_command_info = 1
g:go_gotags_bin = 'gotags'
g:go_highlight_types = 0
g:go_loaded_gosnippets = 1
g:go_highlight_array_whitespace_error = 0
g:go_highlight_operators = 1
g:go_fmt_autosave = 1
g:go_test_prepend_name = 1
g:go_fold_enable = []
g:go_debug_log_output = 'debugger'
g:go_addtags_transform = 'camelcase'
g:go_auto_type_info = 1
g:go_list_type = 'quickfix'
g:go_highlight_extra_types = 0
g:go_gocode_propose_source = 1
g:go_metalinter_autosave_enabled = ['vet', 'golint']
g:go_def_mode = 'gopls'
g:go_auto_sameids = 0
g:go_metalinter_enabled = ['vet', 'golint']
g:go_highlight_build_constraints = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Yes

**Comment by hungrybirder** [comment]
> Yes

Okay. 

Thank you.

**Comment by renkam** [comment]
Is there a chance to have a longer preview? A part of a file containing currently selected file would be really useful.
