### ISSUE TITLE
vim-go: no object found for indent Xxx: no object found

### ISSUE THREAD

**Issue by axiaoxin** [fatih/vim-go#3114]
### What did you do? (required: The issue will be **closed** when not provided)

vim run :PlugUpdate

### What happened instead?

gd :GoDef are not working, error:vim-go: no object found for indent Xxx: no object found

#### vim-go version:

how to check it?

changelog:

```
## unplanned

BACKWARDS INCOMPATIBILITIES:
* Remove g:go_autodetect_gopath.
  [[GH-3078]](https://github.com/fatih/vim-go/pull/3078)

IMPROVEMENTS:
* Clarify allowed values for `gopls` related configuration options.
  [[GH-3016]](https://github.com/fatih/vim-go/pull/3016)
  [[GH-3017]](https://github.com/fatih/vim-go/pull/3017)
* Add `g:go_fillstruct_mode` to allow `:GoFillStruct` to be satisfied by either
  `fillstruct` or by `gopls`.
  [[GH-3018]](https://github.com/fatih/vim-go/pull/3018)
* Add `:GoDebugTestFunc` to debug the test function surrounding the current
  cursor location.
  [[GH-3011]](https://github.com/fatih/vim-go/pull/3011)
* Implicitly add a workspace when a file from a module is opened.
  [[GH-3028]](https://github.com/fatih/vim-go/pull/3028)
...
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" download plug.vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Initialize plugin system
call plug#begin('~/.vim/plugged')
" Go development plugin for Vim. https://github.com/fatih/vim-go
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }

call plug#end()

</pre></details>

#### Vim version (first three lines from `:version`):

IM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 16 2020 23:47:44)
macOS version
#### Go version (`go version`):

go version go1.14.2 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xx/Library/Caches/go-build"
GOENV="/Users/xx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="xx"
GONOSUMDB="xx"
GOOS="darwin"
GOPATH="/Users/ashin/go"
GOPRIVATE="xx"
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ashin/go/src/xx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3y/59j_sfld0r76zqnxtlnk87gc0000gn/T/go-build483574637=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.0
    golang.org/x/tools/gopls@v0.6.1 h1:vD171EDBkyUVyp9B45IYXklV/VEfbHgX0FKw0Q0dO30=
</pre></details>

**Comment by bhcleek** [comment]
This usually means that you are neither in module-aware mode nor in GOPATH mode. Can you provide a simple directory structure layout and instructions for an indentifier to try to jump to that I can use to duplicate the problem you're seeing?

**Comment by axiaoxin** [comment]
Emmm.. It's auto recover in a normal state now. I don't do anything.
