### ISSUE TITLE
GoMetaLinter support options

### ISSUE THREAD

**Issue by cposture** [fatih/vim-go#3115]
### What did you do? (required: The issue will be **closed** when not provided)

I want to add "-n" option when use golangci-lint, I try to reset `g:go_metalinter_command` to 

```
let g:go_metalinter_command = 'golangci-lint run -n'
```

but I found `g:go_metalinter_enabled`  doesn't work，because `g:go_metalinter_command` != `golangci-lint`

https://github.com/fatih/vim-go/blob/96b964a0eeec9585546f39487deebe7eee7d597c/autoload/go/lint.vim#L25

### What did you expect to happen?

I am thinking about any other convenient solutions, such as adding global variables or other to support add golangci option，At the same time, you can enjoy the settings of vim-go to golangci-lint

Thanks

**Comment by bhcleek** [comment]
You can use the golangci-lint options file to set options; it doesn't have to be set on the commandline.
