### ISSUE TITLE
:lgetexpr doesn't respect vim-go's errorformat before vim-go commands are called

### ISSUE THREAD

**Issue by alvalea** [fatih/vim-go#3116]
### What did you do? (required: The issue will be **closed** when not provided)

The functions **lgetxpr** and **lgetfile** do not fill the location list window after using any **:Go*** function that loads results on the location list window.

**Steps** to reproduce it in a go project:

1. Open main.go
2. Load the location window with some entries
```
:lgetexpr system('grep -Hn main *.go')
:lopen
```
3. Move the cursor to some function and call :GoCallers
```
:GoCallers
```
4. Load again the location window with some entries
```
:lgetexpr system('grep -Hn main *.go')
:lopen
```
5. The Location List is empty

### What did you expect to happen?

The Locations List window should be filled with the corresponding values.

### What happened instead?

The Location List window is empty

#### vim-go version:

v1.24

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
Empty configuration
No .vimrc
</pre></details>

#### Vim version (first three lines from `:version`):

version 8.1.2269

#### Go version (`go version`):

go version go1.15.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/al/.cache/go-build"
GOENV="/home/al/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/al/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/al/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build207346326=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.6.0
    golang.org/x/tools/gopls@v0.6.1 h1:vD171EDBkyUVyp9B45IYXklV/VEfbHgX0FKw0Q0dO30=
</pre></details>

**Comment by bhcleek** [comment]
I think this is a Vim bug. When `:lgetexpr` and `:lopen` are run in the example you provided, the locationlist doesn't seem to be honoring the `errorformat` value that's set in `compiler/go.vim` and is instead using Vim's default value. After vim-go sets and then restores `errorformat` in `autoload/go/list.vim`, the location list is using the value that vim-go set causing the second `l:getexpr` use the `errorformat` that should have been used in the first `:lgetexpr`.

It doesn't appear that there's anything that vim-go can do to address this. However, if you want to do something like this, then you can set `errorformat` before calling your `:lgetexpr`. If that's the route you decide to go, then it's a good idea to save the current `errorformat`, call `:lgetexpr`, and then restore `:errorformat` to its previous value to avoid breaking the `:make`'s (and therefore `:GoBuild`'s) expectations.

**Comment by alvalea** [comment]
Yes, setting the `errorformat` before calling `:lgetexpr` makes it work.

```
set errorformat=%f:%l:%m
```

Thank you very much
