### ISSUE TITLE
Support for moving Go packages?

### ISSUE THREAD

**Issue by iselind** [fatih/vim-go#3117]
### What did you do? (required: The issue will be **closed** when not provided)

I tried to find a command in vim-go which would allow me to refactor packages, i.e. move a package somewhere else and have the relevant import statements updated.

In my search I posted [this](https://www.reddit.com/r/golang/comments/kgwt3t/vimgo_refactoring_packages/?utm_source=share&utm_medium=web2x&context=3) entry in reddit. There it was suggested to be that I should submit an issue here.

### What did you expect to happen?
I was hoping to find such a command

### What happened instead?
I couldn't find such a command
#### vim-go version:
v1.24

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.15 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/patriki/.cache/go-build"
GOENV="/home/patriki/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/patriki/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/patriki/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/patriki/go/src/componentcoupling/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build163690547=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.0
    golang.org/x/tools/gopls@v0.6.1 h1:vD171EDBkyUVyp9B45IYXklV/VEfbHgX0FKw0Q0dO30=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_info_mode = 'gopls'
g:go_doctor_loaded_install = 1
g:go_loaded_gosnippets = 1
g:go_metalinter_command = 'golangci-lint'
g:go_code_completion_enabled = 1
g:go_loaded_install = 1
g:go_def_mode = 'gopls'
g:go_list_type = 'quickfix'
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
You're right that this isn't currently supported in vim-go. I'm not sure it should be, though: Vim is not an IDE and while vim-go brings a lot of IDE like functionality, the fundamental way that Vim works is quite different from how most IDEs work.

There is a commandline utility, [gomvpkg](https://godoc.org/golang.org/x/tools/cmd/gomvpkg),  you can use to move packages around.

**Comment by iselind** [comment]
Thank you @bhcleek for your suggestion. I'll try that for sure.

I agree that doing all sorts of IDE operations isn't within scope of vim-go.

I'm happy with this answer, thanks again!
