### ISSUE TITLE
Issuing :GoRun results in an error

### ISSUE THREAD

**Issue by luck02** [fatih/vim-go#312]
On issuing GoRun I see:

'''
➜  LegacyProducer  vim main.go

2015/02/09 12:35:06 client failed to open: %!(EXTRA *errors.errorString=kafka: Client has run out of available brokers to talk to. Is your cluster reachable?)
exit status 1

Press ENTER or type command to continue
'''
(Yes, there is a bug in my code... Working on it)

After hitting ENTER I see:

'''
"2015/02/09 12" [New DIRECTORY]
Error detected while processing BufEnter Auto commands for "*":
E344: Can't find directory "2015/02" in cdpath
E472: Command failed
Press ENTER or type command to continue
'''

which drops me in a vim window that indicates it's opening 1:main.go, but there's nothing there and I need to quit out of it in order to re-open my file.

I'm on fedora 21 - vim-spf13 + vim-go (I'm sure there's potential for conflict).

It looks like vim is issuing some sort of CD command and the directory doesn't exist.  Could be interpolation as the failure is on a logging statement.

**Comment by fatih** [comment]
Hi @luck02 ,

It seems the directory get changed or your App is removing something. I'm not quite sure but can you just  create this file and run `GoRun`

```go
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

If this works, there must be something else going on with you app. Unless you provide me any example files that I can test and reproduce, I can't do much. Because it works fine for me (I'm using GoRun very heavily btw). Let me know please how it works for you.

**Comment by luck02** [comment]
That does run, however what was causing the failure was a log statement going directly to stderr.  Looks like the output is read and possibly executed.

I'll post that code when I can (later today)

**Comment by fatih** [comment]
Ok, I'm curios what's happening. Maybe there is a branch splitting in the code that's causing which is only invoked for certain situations. I'll wait for the example file.

**Comment by ebfe** [comment]
The problem is that `GoRun` uses `:make`. This causes vim to parse stderr and
the logged lines above match the `errorformat`.

To reproduce:

```Go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Fprintf(os.Stderr, "does-not-exist:42: blablabla\n")
}
```

**Comment by luck02** [comment]
Sorry, I can't replicate the issue.

IIRC I had some broken error logging and when calling GoRun my error format string would be interpolated and cause the above error.

**Comment by juicechu** [comment]
I have the same problem on macox
