### ISSUE TITLE
go_fmt_options adds -w flag to options

### ISSUE THREAD

**Issue by JeyoungKwon** [fatih/vim-go#3124]
### What did you do? (required: The issue will be **closed** when not provided)
Attempted to add goimports-reviser as the gofmt tool, which does not take the -w flag

let g:go_fmt_command = "goimports-reviser"
let g:go_fmt_options = {
\ "goimports-reviser": "{options here}"
\}

### What did you expect to happen?
gofmt behavior

### What happened instead?
error: '-w flag provided bot not defined'

line in question here (my best guess): https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim#L160

**Comment by bhcleek** [comment]
`'goimports-reviser'` is not one of the supported values for `g:go_fmt_command`. If you want to use it, then I'd suggest creating a local wrapper script for it with the name of one of the supported options and make sure the wrapper is in your PATH before the name of the name of the supported option that you shadow.
