### ISSUE TITLE
GoCoverageBrowser showing empty coverage HTML file

### ISSUE THREAD

**Issue by zlesnr** [fatih/vim-go#3129]
### What did you do? (required: The issue will be **closed** when not provided)

Running `GoCoverageBrowser` opens an html file, but no tests or file are present in the result.  I think this is a side effect.  Note that `GoCoverage` also doesn't highlight the code properly.  This used to work, and I'm unsure if its something I changed without realizing, or something in this project.  In any case, pointers on how I might troubleshoot this would be appreciated.

It looks as if the html produced doesn't contain the results from a GoTest run, but `:GoTest` runs without issue, and reports SUCCESS.

### What did you expect to happen?

The coverage html produced would look similar to `go test ./internal/pkg -v -tags integration,unit -run '(.*)' -coverprofile=coverage.out && go tool cover -html=coverage.out`

### What happened instead?

The coverage html file was opened as if no tests had been run.  Looks empty.

#### vim-go version:
`706c73bb369d9bab0fadca6b755a7244626f61aa`

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
au BufRead,BufNewFile *.tmpl      set filetype=gotexttmpl
au Filetype go nmap <leader>ga <Plug>(go-alternate-edit)
au Filetype go nmap <leader>gah <Plug>(go-alternate-split)
au Filetype go nmap <leader>gav <Plug>(go-alternate-vertical)
au FileType go nmap <leader>gt :GoDeclsDir<cr>
au FileType go nmap <leader>gc <Plug>(go-coverage-toggle)
au FileType go nmap <leader>gdv <Plug>(go-def-vertical)
au FileType go nmap <leader>gdh <Plug>(go-def-split)
au FileType go nmap <leader>gD <Plug>(go-doc)
au FileType go nmap <leader>gDv <Plug>(go-doc-vertical)
au FileType go nmap <leader>gT <Plug>(go-test)
au FileType go highlight goField ctermfg=cyan guifg=#56b6c2
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
let g:go_fmt_command = "goimports"
let g:go_snippet_engine = "neosnippet"
let g:go_gocode_propose_source = 1
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_def_mapping_enabled = 0 " disable vim-go :GoDef short cut (gd)
let g:go_code_completion_enabled = 0
</pre></details>

#### Vim version (first three lines from `:version`):

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
```

#### Go version (`go version`):

go version go1.15.6 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zleslie/Library/Caches/go-build"
GOENV="/Users/zleslie/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zleslie/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zleslie/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zleslie/go/src/github.com/newrelic/newrelic-client-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9w/3ytbfllx4253c2b68lyz23240000gn/T/go-build865504446=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.0
    golang.org/x/tools/gopls@v0.6.1 h1:vD171EDBkyUVyp9B45IYXklV/VEfbHgX0FKw0Q0dO30=
</pre></details>

**Comment by bhcleek** [comment]
`:GoCoverageBrowser` and `:GoCoverage` are working for me; the browser displays the HTML correctly and the text is correctly highlighted. Can you run `:let g:go_debug=['shell-commands']` and then try `:GoCoverageBrowser` again?

I'd like to see the output of `:messages` afterwards.

**Comment by zlesnr** [comment]
Thank you for the response.  Here are the messages.  Should the `tags` here be populated?  Usually when running the tests I set tags to `unit,integration`.

```
vim-go: [coverage] SUCCESS
vim-go: job command: ['go', 'test', '-tags', '', '-coverprofile', '/var/folders/9w/3ytbfllx4253c2b68lyz23240000gn/T/nvimukYeI4/1259']
vim-go: [coverage] SUCCESS
vim-go: shell command: '/usr/local/bin/go' 'tool' 'cover' '-html=/var/folders/9w/3ytbfllx4253c2b68lyz23240000gn/T/nvimukYeI4/1259'
```

**Comment by zlesnr** [comment]
Setting `let g:go_build_tags = 'unit,integration` in my config has resolved the issue.  When this was working before, it must have been on a project that wasn't using build tags.  In any case, thanks for the debug pointers.
