### ISSUE TITLE
[feature] Completions for import paths

### ISSUE THREAD

**Issue by akavel** [fatih/vim-go#313]
Hi,
I'd like to have completion in import() block, like in GoSublime. (GoImports sometimes mismatches, and then it's good to be able to easily have the path completed.) I've developed a function which generates a list of all package paths available (based on GoSublime), but I don't know well how to plug it in for completion. Could you possibly add this? My code is below:

````VimL
function! SystemFirstLine(cmd)
	" Take only the first line from a command's output
	return split(system(a:cmd), "\n")[0]
endfunction

function! AkavelListGoImports()
	" Note: http://stackoverflow.com/a/6146663/98528
	"   and :help feature-list
	if has('win32') || has('win64') || has('win16') || has('win32unix')
		let pathsep = ';'
	else
		let pathsep = ':'
	endif
	let gopath = SystemFirstLine('go env GOPATH')
	let goroot = SystemFirstLine('go env GOROOT')
	let goos = SystemFirstLine('go env GOOS')
	let goarch = SystemFirstLine('go env GOARCH')
	let goosarch = goos . '_' . goarch

	let paths = split(gopath, pathsep) + [goroot]
	let allpkgs = []
	for path in paths
		let pkgs = split(globpath(path, 'pkg/' . goosarch . '/**/*.a'), "\n")
		" FIXME(akavel): make sure path doesn't end with / or \
		let prefixlen = len(path . '/pkg/' . goosarch . '/')
		" TODO(akavel): filter out any *_test.go pkgs (if present?) maybe via 'wildignore'?
		" Drop path prefix (e.g. 'c:/go/pkg/windows_amd64/') and '.a' suffix
		let pkgs = map(pkgs, 'v:val[' . prefixlen . ':-3]')
		" Windows uses \ in paths, but Go needs /
		let pkgs = map(pkgs, 'substitute(v:val, "\\", "/", "g")')
		let allpkgs = allpkgs + pkgs
	endfor
	return allpkgs
endfunction
````

**Comment by akavel** [comment]
Ok, a first prototype seems to kinda Work For Me&trade; (on Windows for now) if I add the following function below the ones quoted above:

```vim
function! AkavelGoImportsComplete(findstart, base)
	if a:findstart == 1  " can we do some completion?
		let g:go_complete_imports = 0
		let column = col('.')
		let line = getline('.')[:column]
		let quote_pos = match(line, '\v"[a-zA-Z._/-]*$')
		if quote_pos != -1
			let g:go_complete_imports = 1
			return quote_pos + 1
		endif
	else " build list of possible completions
		if g:go_complete_imports
			let allpkgs = AkavelListGoImports()
			let pkgs = []
			let n = len(a:base)-1
			for path in allpkgs
				if path[:n] ==? a:base
					call add(pkgs, path)
				endif
			endfor
			return pkgs
		endif
	endif
	return go#complete#Complete(a:findstart, a:base)
endfunction

autocmd FileType go setlocal omnifunc=AkavelGoImportsComplete
```

Also, I noticed by accident that `:GoImport` actually supports completion already... although it's kinda "more limited", in that it requires to find the nested packages level-by-level, while the above is "fully recursive" and should hopefully work with [neocomplete](https://github.com/Shougo/neocomplete.vim) and the likes. Albeit only when explicitly adding imports in source file.

**Comment by fatih** [comment]
@akavel I'm eager to test it out and check it out in more detail. However I'm currently don't have much time to check this out. However I didn't forget it and going to look at it as soon as possible. Sorry for the delayed response.

**Comment by akavel** [comment]
@fatih Sure; I'm happy to know you're interested. As for me, at the moment I'm already quite satisfied with the snippets as above, since I realized I can just sideload them safely from my .vimrc, enhancing vim-go transparently without need for any editing/patching. Still, again, I'd be even happier if this could be shared with others via integration with vim-go, for sure.

**Comment by nhooyr** [comment]
This is closed, I added it myself to gocode in nsf/gocode#332.

All you need to do is update gocode, it should work perfectly :dancer:

**Comment by fatih** [comment]
@nhooyr How did you get it working? I've tried it but with no luck (I've updated gocode btw). Deoplete-go doesn't auto complete it, nor does `c-x c-o` when I'm inside a import declaration. Do you think there is something I'm missing?

**Comment by nhooyr** [comment]
@fatih run `gocode close` and then try. Deoplete-go was recently updated as well to support it, and it should work out of the box with `c-x c-o`.

**Comment by fatih** [comment]
Alright, `gocode close` did the trick. Thanks for the new feature @nhooyr, even though I'm not using it much It's a valuable addition to those who use it. Closing this issue.
