### ISSUE TITLE
May I run go test with "--gcflag=-l" ?

### ISSUE THREAD

**Issue by guanwenbogit** [fatih/vim-go#3130]
### What did you expect to happen?
- I want to run go test on the vim by cmd :GoTest.
- However, I used the gomonkey in my tests.
- The inline func can not be mocked, without --gcflags=-l
### What happened instead?
- As it is not mocked, the test failed.
- Well, I want the cmd :GoTest can be run with --gcflags=-l
- Also, :GoCoverage needs --gcflags=-l too. Even run these commands withs leader key.

Thanks

**Comment by bhcleek** [comment]
`:GoTest` accepts `go test` flags.

**Comment by guanwenbogit** [comment]
I used :GoTest --gcflags=-l on the vim. But, it doesn't work. I have to exit vim, the exec "go test ./ --gcflags=-l" .

**Comment by guanwenbogit** [comment]
> `:GoTest` accepts `go test` flags.
I used :GoTest --gcflags=-l on the vim. But, it doesn't work. I have to exit vim, the exec "go test ./ --gcflags=-l" .

**Comment by bhcleek** [comment]
There are a lot of open questions here. Please fill out the issue template so I can know what version of vim-go you're using, what version of Go you're on, and a clear description of the nature of the failure you're seeing.

**Comment by bhcleek** [comment]
closing for lack of feedback

**Comment by PegasusWang** [comment]
`:GoTest -gcflags=all=-l ` work but `:GoCoverageBrowser -gcflags=all=-l ` not work.
