### ISSUE TITLE
staticcheck can return spurious errors on autosave

### ISSUE THREAD

**Issue by reedobrien** [fatih/vim-go#3132]
@bhcleek 

First, thanks for maintaining this plugin! 

AFAICT this change causes whatever `s:default_metalinter` is to always be called regardless of what is set in `let g:go_metlinter_command = "golangci-lint"`

That is  if I change `s:default_metalinter` that is the linter that is run. When I set it to `gopls` it reports  `metalinter` dispatched. If I set it to `golangci-lint` or `staticcheck` it reports the correct one dispatched. Again regardless of what is set in `.vimrc` for `let g:go_metlinter_command = "..."`.

Also with `staticcheck` it seems to work correctly when I run `:GoMetalinter` but when it runs on save -- via `let g:go_metalinter_autosave = 1` it fails as it appears to call `staticcheck` with a single file rather than with the package as the target. 
I can reproduce this by calling `staticcheck` on a file vs on the directory or package. This worked with staticcheck as an optional linter in `let g:go_metalinter_enabled = [..., 'staticcheck', '...']`.

These may be separate issues. Let me know if you would like to create another issue.

_Originally posted by @reedobrien in https://github.com/fatih/vim-go/issues/3126#issuecomment-756534180_

**Comment by bhcleek** [comment]
Is it because of the misspelling in `g:go_metlinter_command` (it should be `g:go_metalinter_command`)?

> Also with staticcheck it seems to work correctly when I run :GoMetalinter but when it runs on save -- via let g:go_metalinter_autosave = 1 it fails as it appears to call staticcheck with a single file rather than with the package as the target.

When you run the metalinter on save, it only metalints the file being saved. That's true and has always been true regardless of which metalinter is used.

> I can reproduce this by calling staticcheck on a file vs on the directory or package. This worked with staticcheck as an optional linter in let g:go_metalinter_enabled = [..., 'staticcheck', '...'].

`g:go_metalinter_enabled` does not control the linters used on save. `g:go_metaliner_autosave_enabled` controls the linters used on save.

**Comment by bhcleek** [comment]
FWIW, there's good test coverage of metalinter features in https://github.com/fatih/vim-go/blob/master/autoload/go/lint_test.vim (and the results provided vary by metalinter).

**Comment by reedobrien** [comment]
> Is it because of the misspelling in `g:go_metlinter_command` (it should be `g:go_metalinter_command`)?

😳 I even typed it in a second time.... my bad. Apologies.
 
> > Also with staticcheck it seems to work correctly when I run :GoMetalinter but when it runs on save -- via let g:go_metalinter_autosave = 1 it fails as it appears to call staticcheck with a single file rather than with the package as the target.
> 
> When you run the metalinter on save, it only metalints the file being saved. That's true and has always been true regardless of which metalinter is used.

> `g:go_metalinter_enabled` does not control the linters used on save. `g:go_metaliner_autosave_enabled` controls the linters used on save.

TIL...

Does this mean the new default linter won't work with `...autosave_enabled`?

**Comment by bhcleek** [comment]
The default linter will work with `g:go_metalinter_autosave_enabled` just fine.

**Comment by reedobrien** [comment]
> The default linter will work with `g:go_metalinter_autosave_enabled` just fine.

 Thanks for your cycles on this. I must be missing something else then.

AFAICT, `staticcheck` called with a single file will fail to find name declarations in a package if they are not in the file. So on save `staticcheck` fails on `thisfile.go` if say -- an error variable `ErrNope` is defined in a separate `errs.go` file in the same package. At least this is happening for me now if I use `staticcheck`

**Comment by bhcleek** [comment]
You can use `let g:go_debug=['shell-commands']` to see what command vim-go is running and then execute it at your commandline to determine whether the issue lies with vim-go or with staticcheck.

**Comment by reedobrien** [comment]
I'll try that and follow up in the next couple of days. Thanks again.

**Comment by reedobrien** [comment]
So vim-go does what you say, unsurprisingly.

1. Calling the command `:GoMetalinter` calls with a set of checks on the package where the buffer in focus' file is.
2. Calling on `autosave` calls `staticcheck` on the file in the active buffer.

However, [`staticcheck` docs](https://staticcheck.io/docs#running-the-tools) says `saticcheck` must be called like `go build`. If providing files all files in the package must be passed. This means that vim-go with `staticcheck` as the default will regularly fail checks on any `autosave` invocation unless the package contains only one file or the file in a package has no names declared in any other package files.

So the issue IMO is that there is a mismatch between how `staticcheck` expects to be called vs how `vim-go` calls the tool in the `autosave` case.
