### ISSUE TITLE
:GoImplements in gopls mode does not show implementation of error interface

### ISSUE THREAD

**Issue by sebiwi** [fatih/vim-go#3135]
### What did you do? (required: The issue will be **closed** when not provided)
```
type DictionaryErr string

func (d DictionaryErr) Error() string {
        return string(d)
}
```

Put cursor on DictionaryErr, type `:GoImplements`

### What did you expect to happen?

I expected all the interfaces implemented by `DictionaryErr` to be listed.

### What happened instead?

I see this message at the bottom:

```
vim-go: [implements] SUCCESS
```

But no interfaces are listed.

####  `vimrc` you used to reproduce:
```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'for': 'go' }
call plug#end()            " required
```

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 16 2020 05:34:50)
macOS version
Included patches: 1-1850
```
#### Go version (`go version`):
```
go version go1.15.6 darwin/amd64
```

#### Go environment
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sebiwi/Library/Caches/go-build"
GOENV="/Users/sebiwi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sebiwi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sebiwi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rv/wpk98b2x2xb9rddt8qsbtgld3gkt95/T/go-build580097905=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
#### gopls version
golang.org/x/tools/gopls v0.6.2
    golang.org/x/tools/gopls@v0.6.2 h1:c3zVKbg4zEOayCwgV/RCA3ucNriOyzfTv22fBW+D1EQ=

**Comment by bhcleek** [comment]
This seems to be because of `gopls`. If you want to use `guru` (see `:help g:go_implements_mode`), it will return the result you want, but it is known to not work in all cases in module aware mode. It's slower than gopls and is only guaranteed to work in GOPATH mode.

@stamblerre is this expected from `gopls` either since `errors` is from stdlib?

FWIW, here's the `gopls` request and response:
```
===== sent =====
Content-Length: 188

{"method":"textDocument/implementation","jsonrpc":"2.0","id":9,"params":{"textDocument":{"uri":"file:///Users/bhcleek/src/vim-go/issues/3135/foo.go"},"position":{"character":5,"line":12}}}
===== received =====
Content-Length: 38

{"jsonrpc":"2.0","result":null,"id":9}
```

**Comment by sebiwi** [comment]
I understand.

Is there any way to have this behavior working using only `gopls` instead of `guru`?

**Comment by bhcleek** [comment]
I'm not sure. That's why I asked @stamblerre in my previous comment. Let's wait for her to get back to us.

**Comment by stamblerre** [comment]
`error` is a special case, so it probably does need its own handling in the find interface implementation. I filed https://github.com/golang/go/issues/43655 upstream.

**Comment by bhcleek** [comment]
@sebiwi I'm going to close this; the only interface that doesn't show up as being implemented when using `gopls` for `g:go_implements_mode` is the `error` interface and there's nothing that vim-go can really do about that. Once golang/go#43655 is resolved and released, you should see the behavior you expect.
