### ISSUE TITLE
autoindent not working

### ISSUE THREAD

**Issue by keith-rollin** [fatih/vim-go#314]
(See https://github.com/fatih/vim-go/pull/308 for background.)

I'm having an issue with 229130c, which changed `GoIndent()` from using `&shiftwidth` to using `shiftwidth()`. The issue is that `shiftwidth()` may not yet have sufficient penetration into the installed base of vim users. If `shiftwidth()` does not exist, calls to it return nothing rather than the desired/expected value. Using the result to adjust `ind` leads to `ind` not changing as expected.

I'm running a fully up-to-date OS X 10.10, which comes with vim 7.3. I suspect that `shiftwidth()` was introduced with vim 7.4. I note that http://vimdoc.sourceforge.net/htmldoc/options.html#'shiftwidth' does not mention the new function (though http://vimhelp.appspot.com/options.txt.html does).

Checking the history of indent/go.vim, I see that it originally merely accessed `&shiftwidth`. The change in 229130c was to change these to `shiftwidth()` calls. Instead, you might want to use the approach in the version of indent/go.vim that came with go 1.3.3:

```
...
if exists("*GoIndent")                                                                    
  finish                                                                                  
endif                                                                                     

" The shiftwidth() function is relatively new.                                            
" Don't require it to exist.                                                              
if exists('*shiftwidth')                                                                  
  func s:sw()
    return shiftwidth()                                                                   
  endfunc                                                                                 
else
  func s:sw()
    return &shiftwidth                                                                    
  endfunc                                                                                 
endif                                                                                     

function! GoIndent(lnum)
...
```

`GoIndent()` then calls `s:sw()` where it currently calls `shiftwidth()` directly.

As an aside, I confirm that autoindenting works when I install vim 7.4 on my Mac.

**Comment by fatih** [comment]
Hi @keith-rollin 

Thanks for the bug report. Can you try this PR: https://github.com/fatih/vim-go/pull/315 and report back? I've checked and indeed we need to be sure it exists. I've added the fallback function logic and it works for me.

**Comment by f03lipe** [comment]
Hey, @fatih
I'm not sure this is a related issue, but my autoindent just won't work after I open braces and press enter.
:(
