### ISSUE TITLE
Error highlighting does not work anymore

### ISSUE THREAD

**Issue by mjurczik** [fatih/vim-go#3140]
### What did you do? (required: The issue will be **closed** when not provided)

Opened a file in vim with the following code:

```go
package main

import "fmt"

func main() {
	fmt.Println("vim-go")

	f, err := foo()
}

func foo() (int, error) {
	return 1, nil
}

```

Afterwards saved it with `:w`
Also tried:

- update vim-go with `:PlugUpdate` (using vim-plug
- called `:GoUpdateBinaries`
- updated vim to check if problem is connected with #3138 

### What did you expect to happen?

Highlighting errors. E.g the function call `f, err := foo()` should highlight(in red on my system) `f` and `err`, because both are declared but not used.

Errors got highlighted after saving or after opening.

### What happened instead?

Nothing gets highlighted.

### Configuration (**MUST** fill this out):

<details><summary>vimrc</summary><br><pre>

```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', {'do': ':GoUpdateBinaries'}
call plug#end()


syntax on
set termguicolors
"colorscheme base16-harmonic-dark
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set laststatus=2 " enables status bar to be always visible
set encoding=utf-8
set ignorecase "ignores case in search
set scrolloff=1
set relativenumber
set listchars=trail:·,tab:⇥\ ,nbsp:⍽,extends:▸,precedes:◂
set list
set hlsearch                  "highlight all occurrences
set incsearch                 "highlight early, while typing

" vim-go
let g:go_fmt_command = "goimports" "automatically manage imports in addition to gofmt
let g:go_list_type = "quickfix"
let g:go_highlight_types = 1

```
</pre></details>

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', {'do': ':GoUpdateBinaries'}
call plug#end()


syntax on
set termguicolors
"colorscheme base16-harmonic-dark
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set laststatus=2 " enables status bar to be always visible
set encoding=utf-8
set ignorecase "ignores case in search
set scrolloff=1
set relativenumber
set listchars=trail:·,tab:⇥\ ,nbsp:⍽,extends:▸,precedes:◂
set list
set hlsearch                  "highlight all occurrences
set incsearch                 "highlight early, while typing

" vim-go
let g:go_fmt_command = "goimports" "automatically manage imports in addition to gofmt
let g:go_list_type = "quickfix"
let g:go_highlight_types = 1

```
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 20 2021 22:47:34)
Included patches: 1-2380
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.15.7 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/tuc/projects/go"
GOCACHE="/home/tuc/.cache/go-build"
GOENV="/home/tuc/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tuc/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tuc/go:/home/tuc/projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build547723134=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.4
    golang.org/x/tools/gopls@v0.6.4 h1:PO8rURGmi+QEKZ3pk+ZXJh51EFTVTSXqxzoRzrGSTJM=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_list_type = 'quickfix'
g:go_loaded_gosnippets = 1
g:go_highlight_types = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

I didn't change my .vimrc config so i'm really confused where i screwed things up. This happened on two of my systems.
I dont really know how i can debug stuff. Let me know how i can provide more information.

I just added 

`let g:go_debug = ["shell-commands", "debugger-state", "debugger-commands", "lsp"]` 
to my .vimrc

calling `:messages`, after changing the code(still forcing to get some errors) prints me the following
```
"test.go" 13L, 133B
vim-go: job command: ['/home/tuc/go/bin/gopls', '-debug', 'localhost:0', '-remote=auto']
vim-go: shell command: '/usr/bin/go' 'env' 'GOMOD'
vim-go: shell command: '/usr/bin/go' 'env' 'GOMOD'
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: shell command: '/home/tuc/go/bin/goimports' '-w' '-srcdir' 'test.go' '/tmp/vHXWsYP/2.go'
"test.go" 13L, 133B written
vim-go: shell command: '/home/tuc/go/bin/goimports' '-w' '-srcdir' 'test.go' '/tmp/vHXWsYP/4.go'
"test.go" 13L, 130B written
```

`:GoBuild` opens the quickfix window and prints

```
1 test.go|8 col 2| f1 declared but not used
1 test.go|8 col 6| err declared but not used
```
which is expected.

also tried other colorschemes in vim, but no luck

Thanks in advance

**Comment by bhcleek** [comment]
Can I see the output of your `__GOLSP_LOG__` window, too?

FWIW, the `f1` and `err` values are highlighted on my machine as expected.

**Comment by mjurczik** [comment]
<details> 
  <summary>golsp_log</summary>
===== sent =====
Content-Length: 583

{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///home/mj/projects/go/test","capabilities":{"workspace":{"workspaceFolders":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true}},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["source.organizeImports","refactor.rewrite"]}}},"completion":{"completionItem":{"snippetSupport":false}},"hover":{"contentFormat":["plaintext"]}}},"processId":24485,"workspaceFolders":[{"uri":"file:///home/mj/projects/go/test","name":"/home/mj/projects/go/test"}]}}
===== stderr =====
serve.go:403: debug server listening at http://localhost:45013
===== received =====
Content-Length: 254

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/01/22 08:23:50 Handshake session update\n\tupdate_session=5\n\tdebug_address=\"127.0.0.1:45013\"\n\tlogfile=\"\"\n\tserver=\"1\"\n\tgopls_path=\"/home/mj/go/bin/gopls\"\n"}}
===== received =====
Content-Length: 2895

{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"change":2,"openClose":true,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor.extract","refactor.rewrite","source.fixAll","source.organizeImports"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["gopls.generate","gopls.fill_struct","gopls.regenerate_cgo","gopls.test","gopls.tidy","gopls.update_go_sum","gopls.undeclared_name","gopls.go_get_package","gopls.add_dependency","gopls.upgrade_dependency","gopls.remove_dependency","gopls.vendor","gopls.extract_variable","gopls.extract_function","gopls.gc_details","gopls.generate_gopls_mod"]},"callHierarchyProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"{\"path\":\"golang.org/x/tools/gopls\",\"version\":\"v0.6.4\",\"sum\":\"h1:PO8rURGmi+QEKZ3pk+ZXJh51EFTVTSXqxzoRzrGSTJM=\",\"deps\":[{\"path\":\"github.com/BurntSushi/toml\",\"version\":\"v0.3.1\",\"sum\":\"h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\"},{\"path\":\"github.com/google/go-cmp\",\"version\":\"v0.5.4\",\"sum\":\"h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=\"},{\"path\":\"github.com/sergi/go-diff\",\"version\":\"v1.1.0\",\"sum\":\"h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\"},{\"path\":\"golang.org/x/mod\",\"version\":\"v0.4.0\",\"sum\":\"h1:8pl+sMODzuvGJkmj2W4kZihvVb5mKm8pB/X44PIQHv8=\"},{\"path\":\"golang.org/x/sync\",\"version\":\"v0.0.0-20201020160332-67f06af15bc9\",\"sum\":\"h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=\"},{\"path\":\"golang.org/x/sys\",\"version\":\"v0.0.0-20210119212857-b64e53b001e4\",\"sum\":\"h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=\"},{\"path\":\"golang.org/x/tools\",\"version\":\"v0.1.1-0.20210119222907-0a1a9685734a\",\"sum\":\"h1:ttr/sghFptib3jlHwNS65KwGoqjr03TFzso3kpHyia8=\"},{\"path\":\"golang.org/x/xerrors\",\"version\":\"v0.0.0-20200804184101-5ec99f83aff1\",\"sum\":\"h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=\"},{\"path\":\"honnef.co/go/tools\",\"version\":\"v0.0.1-2020.1.6\",\"sum\":\"h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=\"},{\"path\":\"mvdan.cc/gofumpt\",\"version\":\"v0.1.0\",\"sum\":\"h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=\"},{\"path\":\"mvdan.cc/xurls/v2\",\"version\":\"v2.2.0\",\"sum\":\"h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=\"}]}"}},"id":1}
===== sent =====
Content-Length: 52

{"method":"initialized","jsonrpc":"2.0","params":{}}
===== sent =====
Content-Length: 186

{"method":"workspace/didChangeWorkspaceFolders","jsonrpc":"2.0","params":{"event":{"added":[{"uri":"file:///home/mj/projects/go/test","name":"/home/mj/projects/go/test"}],"removed":[]}}}
===== sent =====
Content-Length: 315

{"method":"textDocument/didOpen","jsonrpc":"2.0","params":{"textDocument":{"uri":"file:///home/mj/projects/go/test/test.go","version":2,"languageId":"go","text":"package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"vim-go\")\n\n\tf, err := foo()\n}\n\nfunc foo() (int, error) {\n\treturn 1, nil\n}\n"}}}
===== received =====
Content-Length: 99

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":4,"message":"Loading packages..."}}
===== received =====
Content-Length: 146

{"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///home/mj/projects/go/test","section":"gopls"}]},"id":1}
===== sent =====
Content-Length: 78

{"id":1,"jsonrpc":"2.0","result":[{"buildFlags":[],"hoverKind":"Structured"}]}
===== received =====
Content-Length: 548

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/01/22 08:23:51 go env for /home/mj/projects/go/test\n(root /home/mj/projects/go/test)\n(go version go version go1.15.7 linux/amd64)\n(valid build configuration = false)\n(build flags: [])\nGO111MODULE=\nGONOPROXY=\nGOPROXY=https://proxy.golang.org,direct\nGOFLAGS=\nGOPRIVATE=\nGOMODCACHE=/home/mj/go/pkg/mod\nGOPATH=/home/mj/go:/home/mj/projects/go\nGOROOT=/usr/lib/go\nGOSUMDB=sum.golang.org\nGOCACHE=/home/mj/.cache/go-build\nGOINSECURE=\nGOMOD=\nGONOSUMDB=\n\n"}}
===== received =====
Content-Length: 206

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/01/22 08:23:51 go/packages.Load\n\tsnapshot=0\n\tdirectory=/home/mj/projects/go/test\n\tquery=[./ builtin]\n\tpackages=2\n"}}
===== received =====
Content-Length: 106

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":3,"message":"Finished loading packages."}}
===== received =====
Content-Length: 268

{"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeConfiguration","method":"workspace/didChangeConfiguration"},{"id":"workspace/didChangeWorkspaceFolders","method":"workspace/didChangeWorkspaceFolders"}]},"id":2}
===== sent =====
Content-Length: 38

{"id":2,"jsonrpc":"2.0","result":null}
===== received =====
Content-Length: 99

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":4,"message":"Loading packages..."}}
===== received =====
Content-Length: 146

{"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///home/mj/projects/go/test","section":"gopls"}]},"id":3}
===== sent =====
Content-Length: 78

{"id":3,"jsonrpc":"2.0","result":[{"buildFlags":[],"hoverKind":"Structured"}]}
===== received =====
Content-Length: 428

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/mj/projects/go/test/test.go","diagnostics":[{"range":{"start":{"line":7,"character":1},"end":{"line":7,"character":2}},"severity":1,"source":"compiler","message":"f declared but not used"},{"range":{"start":{"line":7,"character":4},"end":{"line":7,"character":7}},"severity":1,"source":"compiler","message":"err declared but not used"}]}}
===== received =====
Content-Length: 548

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/01/22 08:23:51 go env for /home/mj/projects/go/test\n(root /home/mj/projects/go/test)\n(go version go version go1.15.7 linux/amd64)\n(valid build configuration = false)\n(build flags: [])\nGOPATH=/home/mj/go:/home/mj/projects/go\nGOROOT=/usr/lib/go\nGOCACHE=/home/mj/.cache/go-build\nGONOPROXY=\nGOMOD=\nGOMODCACHE=/home/mj/go/pkg/mod\nGOPROXY=https://proxy.golang.org,direct\nGONOSUMDB=\nGOPRIVATE=\nGO111MODULE=\nGOINSECURE=\nGOSUMDB=sum.golang.org\nGOFLAGS=\n\n"}}
===== received =====
Content-Length: 206

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/01/22 08:23:51 go/packages.Load\n\tsnapshot=0\n\tdirectory=/home/mj/projects/go/test\n\tquery=[./ builtin]\n\tpackages=2\n"}}
===== received =====
Content-Length: 106

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":3,"message":"Finished loading packages."}}
===== received =====
Content-Length: 170

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"2021/01/22 08:23:51 creating workspace dir: mkdir /tmp/gopls-24485.workspace: file exists\n"}}

</details>

Ok it seems that gopls is reporting the error in this line:

```
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/mj/projects/go/test/test.go","diagnostics":[{"range":{"start":{"line":7,"character":1},"end":{"line":7,"character":2}},"severity":1,"source":"compiler","message":"f declared but not used"},{"range":{"start":{"line":7,"character":4},"end":{"line":7,"character":7}},"severity":1,"source":"compiler","message":"err declared but not used"}]}}
```

Just the highlighting does not work. Maybe you can spot something else inside the log

> FWIW, the f1 and err values are highlighted on my machine as expected.

Thank you for checking. I'm going to look into it again. Seems like a specific problem on my system :(

**Comment by mjurczik** [comment]
Hello, i have new insights.

I started my laptop which also has the plugin running, and the highlighting worked.
Then i updated the version to the latest one (https://github.com/fatih/vim-go/commit/cf7ff75a3f5f6600474dc1912819fd0ce12e97ee), after that the highlighting did not work anymore.

downgraded to release v1.23 -> highlighting works
updated to pre-release v1.24-rc.1 -> highlighting still works
updated to [latest](https://github.com/fatih/vim-go/commit/cf7ff75a3f5f6600474dc1912819fd0ce12e97ee)-> highlight doesnt work anymore

I tested this on my other machine, checked out v1.24-rc.1, highlighting does work again.

I do not know what 'changed' between the pre-release and 1.24.

**Comment by weberc2** [comment]
Unfortunately the fix described above breaks other things. When I set `let g:go_diagnostics_level = 2`, having two different files of the same project open (in different neovim processes) results in a bunch of warnings related to swp files dumped onto the screen. Viewing multiple files at once is a really common use case, so this is very disappointing.

```
Found a swap file by the name "~/.local/share/nvim/swap//%Users%weberc2%projects%mono%cmd%titles%main.go.swp"
          owned by: <redacted>   dated: Fri May 20 14:57:15 2022
         file name: ~<redacted>/projects/mono/cmd/titles/main.go
          modified: no
         user name: <redacted>   host name: <redacted>
        process ID: 44848 (STILL RUNNING)
While opening file "/Users/<redacted>/projects/mono/cmd/titles/main.go"
             dated: Sun May  8 09:09:03 2022

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /Users/<redacted>/projects/mono/cmd/titles/main.go"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/Users/<redacted>/.local/share/nvim/swap//%Users%<redacted>%proje
cts%mono%cmd%titles%main.go.swp"
    to avoid this message.

Found a swap file by the name "~/.local/share/nvim/swap//%Users%<redacted>%projects%mono%pkg%pgutil%result.go.swp
"
          owned by: <redacted>   dated: Fri May 20 14:57:15 2022
         file name: ~<redacted>/projects/mono/pkg/pgutil/result.go
          modified: no
         user name: <redacted>   host name: <redacted>
        process ID: 44848 (STILL RUNNING)
While opening file "/Users/<redacted>/projects/mono/pkg/pgutil/result.go"
             dated: Mon Feb 14 09:45:29 2022

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /Users/<redacted>/projects/mono/pkg/pgutil/result.go"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/Users/<redacted/.local/share/nvim/swap//%Users%<redacted>%projects%mono%pkg%pgutil%result.go.swp"
    to avoid this message.

Found a swap file by the name "~/.local/share/nvim/swap//%Users%<redacted>%projects%mono%cmd%deployproxy%controller.go.swp"
          owned by: <redacted>   dated: Fri May 20 14:57:15 2022
         file name: ~<redacted>/projects/mono/cmd/deployproxy/controller.go
          modified: no
         user name: <redacted>   host name: <redacted>
        process ID: 44848 (STILL RUNNING)
While opening file "/Users/<redacted>/projects/mono/cmd/deployproxy/controller.go"
             dated: Mon May 16 10:45:14 2022

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /Users/<redacted>/projects/mono/cmd/deployproxy/controller.go"

    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/Users/<redacted>/.local/share/nvim/swap//%Users%<redacted>%projects%mono%cmd%deployproxy%controller.go.swp"
    to avoid this message.

Found a swap file by the name "~/.local/share/nvim/swap//%Users%<redacted>%projects%mono%cmd%deployproxy%deployment.go.swp"
          owned by: <redacted>   dated: Fri May 20 14:57:15 2022
         file name: ~<redacted>/projects/mono/cmd/deployproxy/deployment.go
          modified: no
         user name: <redacted>   host name: <redacted>
```
