### ISSUE TITLE
ctrl + ] can't jump in vim 8.2.2347

### ISSUE THREAD

**Issue by zlianzhuang** [fatih/vim-go#3145]
### What did you do? 
ctrl + ] 

### What did you expect to happen?
jump success

### What happened instead?

vim-go: [definition] SUCCESS
处理 function 536[13]..538[37]..function 536[13]..538[26]..<SNR>127_definitionHandler[8]..<SNR>148_jump_to_declaration_cb[5]..go#def#jump_to_declaration 时发生错误:
第   92 行:
E474: 无效的参数
处理 function 536 时发生错误:
第   13 行:
E171: 缺少 :endif

autoload/go/def.vim(line 206): call cursor(line, col)
this line error.  line, col i have print, it is right.

### Configuration (**MUST** fill this out):
let g:go_fmt_command = "goimports" " 格式化将默认的 gofmt 替换
let g:go_autodetect_gopath = 1
let g:go_list_type = "quickfix"
let g:go_version_warning = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_methods = 1
let g:go_highlight_generate_tags = 1
let g:godef_split=2

#### vim-go version:
latest and v1.24-rc.1

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2021 18:17:04)
包含补丁: 1-2347
编译者 Arch Linux

#### Go version (`go version`):
go version go1.15.6 linux/amd64

#### Go environment
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lzzhang/.cache/go-build"
GOENV="/home/lzzhang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/lib/go/lzzhang_gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/lib/go/lzzhang_gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build770759633=/tmp/go-build -gno-record-gcc-switches"

#### gopls version
golang.org/x/tools/gopls v0.6.4

i can run ctrl + ] success befor update vim to 8.2.2347

**Comment by bhcleek** [comment]
> i can run ctrl + ] success befor update vim to 8.2.2347

Then the problem is with Vimm, not with vim-go. I suspect you are encountering a recently introduced bug in Vim 8.2.2324 that was reported in #3137 and #3138 and then resolved by vim in vim/vim#7690. Can you try updating to at least 8.2.2363 to confirm?

**Comment by zlianzhuang** [comment]
thank you very much.
