### ISSUE TITLE
Indent plugin breaks paste mode indentation across buffers

### ISSUE THREAD

**Issue by paulswanson** [fatih/vim-go#3148]
For Vim 8.2 with vim-go 3a8e3f6, with the following .vimrc:

```
set nocompatible
filetype plugin indent on
packadd vim-go
```

When in Insert Paste Mode, indentation of pasted Go code works correctly in the initial buffer in which paste mode was set.

However, when switching to another loaded Go buffer, Paste Mode remains active, as expected, but indentation of pasted code is broken, as if Paste Mode was _not_ set.

To make indentation work correctly, `set paste` must be re-applied in every buffer containing Go files.

It seems that disabling the indent plugin resolves this misbehaviour. Yet, doc/vim-go.txt states that the indent plugin should be enabled.

It's unclear whether the documentation is incorrect or if vim-go is not cooperating properly with the indent plugin.

Either way, it seems the default behaviour is breaking paste mode indentation across Go buffers.

**Comment by bhcleek** [comment]
Vim-go's interaction with indentation for Go files (see `:help filetype-indent-on`) is limited to `indent/go.vim`.  vim-go does not modify the value of `paste`, and what Vim does with that is not up to vim-go. You may be encountering a Vim bug.

Please fill out the issue template that was presented to you when you created an issue. The information that it asks for is useful to help us help you. As it stands, I don't know what you're actually doing, what version of Vim you're on, what the relevant setting in your vimrc may be, or what problem you're _actually_ seeing (i.e. what does "indentation of pasted code is broken" actually mean?).

**Comment by paulswanson** [comment]
>  As it stands, I don't know what you're actually doing, what version of Vim you're on, what the relevant setting in your vimrc may be, or what problem you're _actually_ seeing (i.e. what does "indentation of pasted code is broken" actually mean?).

You know, that information is quite _obviously_ and _clearly_ presented in the opening lines of the issue I posted.

If you're simply going to hide behind an issue template at this point at this point, I don't see the purpose in going further with this.

But for anyone who feels remotely motivated, the steps I outlined are consistently reproducible.

Good luck.

**Comment by bhcleek** [comment]
@paulswanson I'm more than happy to help you. I'm not hiding behind an issue template; the information it asks for is relevant here. Here's some examples:
* What version of vim? Vim 8.2 is vague. As of today, there are 2425 patches that have been released on Vim 8.2. Which one are you on?
* what you're doing: What are you pasting? how can I duplicate what you're doing? What do you mean when you say that it's "broken"?

If you'd like to continue, I'll gladly help you out.

**Comment by paulswanson** [comment]
> * What version of vim? Vim 8.2 is vague. As of today, there are 2425 patches that have been released on Vim 8.2. Which one are you on?

Patch 1-1948

> * ... What are you pasting?

Any Go code that would normally be affected by the default auto indentation.

**Comment by paulswanson** [comment]
**SOLUTION**: replacing vim-go's indent/go.vim with the ostensibly newer version (2011->2017) provided by Vim (8.2 Patch 1-1948) appears to fix the problem.

@bhcleek perhaps someone could kindly look into updating this file for vim-go also. Thanks.

**Comment by bhcleek** [comment]
The only functional difference in what ships with Vim is the raw string handling, which was added in 2018 intentionally.

What are you pasting and what are you seeing that's "broken"?

**Comment by paulswanson** [comment]
Here's a test for you ... in the version of Vim described above, with the following diagnostic vimrc:
```
set nocompatible
filetype plugin indent on
packadd vim-go
```
Open a number of Go files into Vim buffers, however you like e.g. `vim foo.go bar.go`

Set paste mode `:set paste`

Copy into your system's clipboard some Go code that would normally have its indentation broken (<-insert whatever synonym you prefer here) if paste mode was NOT enabled, sample snippet provided here:

```
func (app *application) isAuthenticated(r *http.Request) bool {
	return app.session.Exists(r, "authenticatedUserID")
}
```
Enter insert mode and paste from clipboard (CTRL+V or whatever), indentation of copied code is rendered correctly.

Now, switch to another buffer of Go code, however you wish, eg.:
```
:bnext
```
Check that paste mode is still enabled, if you like:
```
:set paste?
```
Enter insert mode and paste the same, or any other snippet of Go code, resultant text will have its indentation broken, something like this
```
func (app *application) isAuthenticated(r *http.Request) bool {
		return app.session.Exists(r, "authenticatedUserID")
			}
```

The same test repeated **without** vim-go loaded / active **will** result in the indentation of the pasted text properly rendered.

Whatever the subtle differences are (I don't know), replacing vim-go's ten year old version of indent/go.vim with the newer version provided by Vim **will** result in the correct rendering of text. 

Maybe there are some other extenuating circumstances ... maybe not, but it is consistent.

Hopefully this helps anyone else facing the same issue.

**Comment by bhcleek** [comment]
> Whatever the subtle differences are (I don't know), replacing vim-go's ten year old version of indent/go.vim with the newer version provided by Vim will result in the correct rendering of text.

To be clear, the version shipping with Vim is the older version. Vim-go ships with an updated version that handles raw strings.

Thanks for the clear explanation of actions and results. I'll dig in and see if I can find a culprit.

**Comment by paulswanson** [comment]
> To be clear, the version shipping with Vim is the older version. Vim-go ships with an updated version that handles raw strings.

 Fair enough, I was just going by the copyright. 

> Thanks for the clear explanation of actions and results. I'll dig in and see if I can find a culprit.

Thanks, good luck!

**Comment by bhcleek** [comment]
This doesn't seem to have anything to do with vim-go's indent file. I can duplicate the same behavior described above with Vim's indent file. It seems to have something to do with how the `paste` option interacts with setting a filetype. When a filetype is set _after_ `:set paste` is called, the paste option seems to not take effect.

I'm not sure if this is a Vim bug or not, but I think it may be.

**Comment by paulswanson** [comment]
That's odd. For me, using the Vim provided indent/go.vim solves the problem.

I've tested it by a) simply not loading vim-go, and b) overwriting vim-go's indent/go.vim with that provided by Vim.

When using unmodified vim-go, simply calling `:set paste` an additional time in each affected buffer resolves the problem, for the life of the buffer.

So, in my tests, I'm seeing that I _only_ experience this problem when vim-go is active. No idea why, however.

**Comment by paulswanson** [comment]
For reference, here's the indent/go.vim that ships with my Vim, just in case where looking at two different things.

[go.vim.txt](https://github.com/fatih/vim-go/files/5896581/go.vim.txt)

**Comment by bhcleek** [comment]
that's the same that ships with my Vim.

> I've tested it by a) simply not loading vim-go, and b) overwriting vim-go's indent/go.vim with that provided by Vim.

That's an either/or operation. Overwriting vim-go's indent file won't do anything if vim-go isn't loaded 🤔 

> When using unmodified vim-go, simply calling :set paste an additional time in each affected buffer resolves the problem, for the life of the buffer.

I'm curious what your total order of operations is, because I can duplicate this quite easily. It has to do with when a buffer's file type is set vs when `:set paste` is called. When a new buffer is opened, the filetype is set. If `:set paste` was called after the filetype is set, then all is well. But if `:set paste` is executed before the filetype is set, then the indentation gets messed up when pasting into the buffer where filetype was set after `:set paste` was executed.

**Comment by bhcleek** [comment]
Ok, I think I know what's going on.

This is expected behavior and is documented in Vim. From `:help paste`:
> 	These options keep their value, but their effect is disabled:
		- 'cindent'
		- 'indentexpr'
		- 'lisp'
	NOTE: When you start editing another file while the 'paste' option is
	on, settings from the modelines or autocommands may change the
	settings again, causing trouble when pasting text.  You might want to
	set the 'paste' option again.


Vim-go needs to set `indentexpr`, but `indentexpr` is reset when `:set paste` is called. When the filetype is set (as happens when a buffer is initially loaded, `indentexpr` gets set for that buffer, undoing what `:set paste` did.

**Comment by paulswanson** [comment]
**> > I've tested it by a) simply not loading vim-go, and b) overwriting vim-go's indent/go.vim with that provided by Vim.**
> 
> That's an either/or operation. Overwriting vim-go's indent file won't do anything if vim-go isn't loaded 

To be clear, scenario 'a' is removing the `packadd vim-go` line from the vimrc in question, scenario 'b' is with vim-go loaded by the vimrc.

> I'm curious what your total order of operations is, because I can duplicate this quite easily. It has to do with when a buffer's file type is set vs when `:set paste` is called. When a new buffer is opened, the filetype is set. If `:set paste` was called after the filetype is set, then all is well. But if `:set paste` is executed before the filetype is set, then the indentation gets messed up when pasting into the buffer where filetype was set after `:set paste` was executed.

I'm not sure if there is much I can add to the test procedure, in terms of the order of those steps. I've used various other analogous Vim commands (eg. :b 2), to the same result.
