### ISSUE TITLE
Error when using :GoDef

### ISSUE THREAD

**Issue by VinGarcia** [fatih/vim-go#3150]
### What did you do? (required: The issue will be **closed** when not provided)

After cleaning my `~/vim/bundle` directory so it contains only `vim-go` and updating both `vim-go` and `pathogen` to the latest versions (just in case) I erased almost all commands from my `~/.vimrc` file and tried the following:

1. Created this Go file (and save it with :w):
    ```Go
    package main
    
    import (
            "fmt"
    )
    
    var goDefHere = "go def to this var"
    
    func main() {
            fmt.Println(goDefHere)
    }
    ```

2. Then with the file opened using vim I move the cursor to the line `fmt.Println(goDefHere)` and type: `:GoDef`

3. I get the following error message:
   ```
   :GoDef
   vim-go: [definition] SUCCESS
   Error detected while processing function 4[13]..6[37]..function 4[13]..6[26]..<SNR>39_definitionHandler[8]..<SNR>48_jump_to_declaration_cb[5]..go#def#jump_to_declaration:
   line   92:
   E474: Invalid argument
   Error detected while processing function 4:
   line   13:
   E171: Missing :endif
   ```

I also tested this with the variable in another file, in this case, the error message also shows up but the buffer changes to the new file, and it doesn't go to the actual definition of the variable the cursor stays on the first line of the file.

This problem seems similar to [this closed ticket][closed-ticket], but since it has been fixed and it was a long time ago I figured this might be something different.

[closed-ticket]: https://github.com/fatih/vim-go/issues/2195

### What did you expect to happen?

I expected no error, and I expected the cursor to move to the definition of the variable as it used to do.

### What happened instead?

There was an error and it worked partially (changed to the correct buffer, but didn't find the variable definition)

#### vim-go version:

007d9bc7786d703dc778de7b69895b8c1907dde7 (current HEAD of the master branch)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
execute pathogen#infect()

filetype plugin on
syn on
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2021 18:17:04)
Included patches: 1-2347
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.15.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vingarcia/.cache/go-build"
GOENV="/home/vingarcia/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vingarcia/go/pkg/mod"
GONOPROXY="gitlab.ubanquity.com"
GONOSUMDB="gitlab.ubanquity.com"
GOOS="linux"
GOPATH="/home/vingarcia/go"
GOPRIVATE="gitlab.ubanquity.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vingarcia/temp/go-mod/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build984769895=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.4
    golang.org/x/tools/gopls@v0.6.4 h1:PO8rURGmi+QEKZ3pk+ZXJh51EFTVTSXqxzoRzrGSTJM=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:OFF
</pre></details>

**Comment by bhcleek** [comment]
Vim 8.2.2347 has a regression that's since been fixed. https://github.com/fatih/vim-go/issues/3145#issuecomment-767279256 has more information and links to relevant analysis and fixes.

**Comment by VinGarcia** [comment]
@bhcleek you are right, I updated my vim to 8.2.2451 and it is now working. Thanks!
