### ISSUE TITLE
When `go_gopls_fumpt` is enabled, `go_gopls_local` has no effect

### ISSUE THREAD

**Issue by bravoecho** [fatih/vim-go#3151]
### What did you do?

I have configured `vim-go` to use `gopls` for formatting and imports, and I have prepared a dummy package to illustrate the problem.

* the `go_gopls_fumpt` and `go_gopls_local` options do not work together
* if both are set, only `gofumpt` is applied, whereas `local` is ignored
* if `gofumpt` is not enabled, then `local` will work
* if both are not set, the imports are still automatically populated normally, and basic formatting is still applied

### What did you expect to happen?

I would like that the `local` and `gofumpt` options work correctly at the same time.

Given this file (see also rest of the package, attached [vim-go-gopls-options.zip](https://github.com/fatih/vim-go/files/5937281/vim-go-gopls-options.zip))

```go
package main

import (
        "context"
        "fmt"
        "github.com/pkg/errors"
        "mymod/pkg1"
        "mymod/pkg2"
)

func main() {

        fmt.Println("vim-go")

}

func dummyFunc(ctx context.Context) {

        fmt.Println(ctx)
        pkg1.Foo()
        pkg2.Bar()
        err := errors.Wrap(errors.New("some error"), "some wrapping info")
        fmt.Println(err)

}
```

when I save I would like to obtain the following (with local imports separate from the rest, and extra lines at the beginning and end of functions removed)

```go
package main

import (
	"context"
	"fmt"

	"mymod/pkg1"
	"mymod/pkg2"

	"github.com/pkg/errors"
)

func main() {
	fmt.Println("vim-go")
}

func dummyFunc(ctx context.Context) {
	fmt.Println(ctx)
	pkg1.Foo()
	pkg2.Bar()
	err := errors.Wrap(errors.New("some error"), "some wrapping info")
	fmt.Println(err)
}
```

### What happened instead?

I obtain the following result, where only `gofumpt` was applied, whereas the `local` option was not respected:

```go
package main

import (
        "context"
        "fmt"
        "mymod/pkg1"
        "mymod/pkg2"

        "github.com/pkg/errors"
)

func main() {
        fmt.Println("vim-go")
}

func dummyFunc(ctx context.Context) {
        fmt.Println(ctx)
        pkg1.Foo()
        pkg2.Bar()
        err := errors.Wrap(errors.New("some error"), "some wrapping info")
        fmt.Println(err)
}
```

#### vim-go version:

`007d9bc7786d7`

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set encoding=utf-8
scriptencoding utf-8

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

let g:go_fmt_command = 'gopls'
let g:go_fmt_autosave = 1
let g:go_fmt_fail_silently = 1

let g:go_imports_mode = 'gopls'
let g:go_imports_autosave = 1
let g:go_gopls_local = 'mymod'
let g:go_gopls_gofumpt = v:true
</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  1 2021 23:54:08)
macOS version - x86_64
Included patches: 1-2450
```

#### Go version (`go version`):

```
go version go1.15.7 darwin/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/luca.belmondo/Library/Caches/go-build"
GOENV="/Users/luca.belmondo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/luca.belmondo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/luca.belmondo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.7_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.7_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/luca.belmondo/workspace/vim-go-bug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7l/jq5b64g946n0lxq82d8x32tryf6wnc/T/go-build767811874=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.5
    golang.org/x/tools/gopls@v0.6.5 h1:kLt9rD/dWtVdvc8LmdcxagDFih6zxYXREpKSYYZu5KE=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'gopls'
g:go_loaded_install = 1
g:go_gopls_local = 'mymod'
g:go_fmt_fail_silently = 1
g:go_imports_mode = 'gopls'
g:go_fmt_autosave = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_imports_autosave = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
This looks like a gopls bug. I've filed https://github.com/golang/go/issues/44136.
