### ISSUE TITLE
vim-go can not jump to the define of the variable or function

### ISSUE THREAD

**Issue by lxxxxxd** [fatih/vim-go#3159]
### What did you do? (required: The issue will be **closed** when not provided)

(1) I install vim-go according to https://github.com/fatih/vim-go/wiki/Tutorial#quick-setup
(2) Open a go code file `src/cmd/compile/internal/gc/plive.go` with vim
(3) I want to jump from a variable to its define, I let the cursor at the symbol, and enter Ctrl+]
(4) The window report an error: 
```
vim-go: no packages for file file:///go/src/cmd/compile/internal/gc/plive.go
``` 

#### vim-go version:
1.24
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
syntax on

call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
</pre></details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

root@f90d2f28b837:/go# go env
GO111MODULE=""
GOARCH="mips64le"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="mips64le"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_mips64le"
GCCGO="gccgo"
GOMIPS64="hardfloat"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build243708762=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

0.6.5
</pre></details>

**Comment by bhcleek** [comment]
What's in that file?

**Comment by lxxxxxd** [comment]
It is just go code in golang/go project. (`src/cmd/compile/internal/gc/plive.go`)

**Comment by bhcleek** [comment]
The contents of the file are important to help me help you. Is the file accessible some place that I can see?

Can you duplicate this problem with other files?

**Comment by lxxxxxd** [comment]
https://github.com/golang/go/blob/023c46676db26e75d244b1d38ccc4a4b8bfe3eef/src/cmd/compile/internal/gc/plive.go#L227
symbol: bvec
other files:
https://github.com/golang/go/blob/release-branch.go1.15/src/cmd/compile/internal/gc/ssa.go
https://github.com/golang/go/blob/release-branch.go1.15/src/cmd/asm/main.go

but the following files can jump normally:
https://github.com/golang/go/blob/release-branch.go1.15/src/runtime/stack.go
https://github.com/golang/go/blob/release-branch.go1.15/src/runtime/runtime2.go

**Comment by lxxxxxd** [comment]
I create a project on github, https://github.com/XiaodongLoong/docker-vim
reproduce this issue by docker container:
https://github.com/XiaodongLoong/docker-vim/tree/main/golang

**Comment by XiaodongLoong** [comment]
I found these operation `export  GO111MODULE="off"` can solve part of this issue, but there is new issue that vim-go can not jump to the symbol that is in same directory with plive.go code file, such as bvec symbol. And report the following error:
`vim-go: no object found for ident bvec: no object found`

I update the tools under GOBIN directory, but it can not work.
https://github.com/fatih/vim-go/issues/1044

**Comment by bhcleek** [comment]
Are you only seeing this error when you're trying to work on Go itself, or do you see it with other code, too?

The Go source code should never be in GOPATH. See https://golang.org/doc/contribute#checkout_go.

I'm only able to duplicate the problem you're describing when the Go source code is in GOPATH.

**Comment by XiaodongLoong** [comment]
other code is OK.
What is the version of golang you used?
` unset GOPATH` ,   the error still exist :  `vim-go: no object found for ident bvec: no object found`

**Comment by bhcleek** [comment]
`/go` is the default `GOPATH` in the `golang` container, so unsetting `GOPATH` won't have any effect for the way you're configuring the container. I'd suggest mounting the Go source code into a different location in the container or else changing `GOPATH` to a different location in the container.

**Comment by bhcleek** [comment]
@XiaodongLoong were you able to resolve your problem?

**Comment by XiaodongLoong** [comment]
Just set GOROOT to the project if the source code is  golang compile.
