### ISSUE TITLE
Can u provide go syntax with that options 

### ISSUE THREAD

**Issue by shahid777-py** [fatih/vim-go#3160]
your plugin it's great but i just need the syntax highlighting , and also the keybinds its overriding mine ,is there any way to disable or remap you keys defined in the plugin.

**Comment by bhcleek** [comment]
Modern versions of Vim have Go syntax files. They're not as complete as vim-go's, but they're still quite useful. 

If you want to keep using vim, you may find `g:go_def_mapping_enabled` and `g:go_textobj_enabled` useful. Details about each can be found in the help file.
