### ISSUE TITLE
Partial installation from the EPEL repository

### ISSUE THREAD

**Issue by gwijnja** [fatih/vim-go#3161]
### What did you do?

I installed vim-go on CentOS 7, from the EPEL repository:

```sh
$ sudo dnf install vim-go
```

...which installs without any warnings or errors.

### What did you expect to happen?

I expected RPM to install vim-go in such a way that it's functionality is available to all users right after installation. Maybe by altering `/etc/vimrc`? I'm not really an expert on vimrc files. I have used vim-go before, but only using the instructions on github, and not by installing it through the Redhat repository.

### What happened instead?

None of the vim-go commands work, like `:GoInstallBinaries` or `:help go-troubleshooting`, it does not format files automatically, etc.

Since there's a vim-go package available in the official Redhat repository, I would like to use it. But it is unclear what to do after running `dnf install vim-go`. Of course I could still follow the instructions at https://github.com/fatih/vim-go, like I used to, but that downloads vim-go from github again, and then there's no point in installing the rpm-package.

So it feels like `dnf install vim-go` provides a partial installation. The files are installed under `/usr/share/vim/vimfiles` (see the files list at the bottom of the [rpm page](https://centos.pkgs.org/7/epel-x86_64/vim-go-1.8-3.el7.x86_64.rpm.html)), but what to do with them? Do I need to point one of the vim plugin managers to the files in that directory? Would you please consider adding instructions on an installation using rpm/yum/dnf?

Right now I'm considering doing `dnf remove vim-go` and installing it the "old" way again...

#### vim-go version:

https://centos.pkgs.org/7/epel-x86_64/vim-go-1.8-3.el7.x86_64.rpm.html

####  `vimrc` you used to reproduce:

My .vimrc does not include anything about vim-go yet, because the RPM installer would not touch that of course. I thought maybe the installer would add something to `/etc/vimrc`, but there's nothing in there either. I included both, just to be sure.

<details><summary>~/.vimrc</summary><br><pre>
set title
set laststatus=1
set number
syntax enable
filetype plugin indent on

set autoindent
set smartindent
set softtabstop=4
set shiftwidth=4
set expandtab
set textwidth=79
set pastetoggle=<F12>

au BufRead,BufNewFile *.html.twig set filetype=jinja
au BufRead,BufNewFile *.volt set filetype=html

let g:html_indent_inctags = "html,body,head,tbody,li"
nnoremap <C-J> <C-W><C-J>
</pre></details>

<details><summary>/etc/vimrc</summary><br><pre>
if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif

set nocompatible        " Use Vim defaults (much better!)
set bs=indent,eol,start         " allow backspacing over everything in insert mode
"set ai                 " always set autoindenting on
"set backup             " keep a backup file
set viminfo='20,\"50    " read/write a .viminfo file, don't store more
                        " than 50 lines of registers
set history=50          " keep 50 lines of command line history
set ruler               " show the cursor position all the time

" Only do this part when compiled with support for autocommands
if has("autocmd")
  augroup redhat
  autocmd!
  " In text files, always limit the width of text to 78 characters
  " autocmd BufRead *.txt set tw=78
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
  " don't write swapfile on most commonly used directories for NFS mounts or USB sticks
  autocmd BufNewFile,BufReadPre /media/*,/run/media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
  " start with spec file template
  autocmd BufNewFile *.spec 0r /usr/share/vim/vimfiles/template.spec
  augroup END
endif

if has("cscope") && filereadable("/usr/bin/cscope")
   set csprg=/usr/bin/cscope
   set csto=0
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
      cs add $PWD/cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
      cs add $CSCOPE_DB
   endif
   set csverb
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin on

if &term=="xterm"
     set t_Co=8
     set t_Sb=m
     set t_Sf=m
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"
</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 28 2019 15:06:33)
Included patches: 1-2231
Compiled by gerben@ariel

#### Go version (`go version`):
go version go1.15.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/gerben/go/bin"
GOCACHE="/home/gerben/.cache/go-build"
GOENV="/home/gerben/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gerben/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gerben/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build188640450=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
</pre></details>

**Comment by bhcleek** [comment]
Since they're installed to `/usr/share/vim`, it's likely already in your runtimepath. You can check by executing `:set rtp?`. You may read the help the runtimepath (`:help runtimepath`) to understand how plugins are loaded.

**Comment by gwijnja** [comment]
Thanks, you pushed me exactly in the right direction. Now I understand how plugins are loaded.

This is my rtp: `runtimepath=~/.vim,/usr/local/share/vim/vimfiles,/usr/local/share/vim/vim81,/usr/local/share/vim/vimfiles/after,~/.vim/after`

My `$VIM` is `/usr/local/share/vim`, because it's not set anywhere, so it's using the 'fall-back' setting as shown in `:version`. `$VIM/vim{version}` exists, resulting in `$VIMRUNTIME` being set to `/usr/local/share/vim/vim81` and that's where it searches through a whole bunch of subdirectories for all kinds of `.vim` files.

But vim-go is not installed there. It was installed in `/usr/share/vim/vimfiles`, because the RPM spec file (in the vim-go RPM source package) says: `%global vimfiles_root %{_datadir}/vim/vimfiles` and `%{_datadir}` [defaults](https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/) to `/usr/share` on Redhat systems. So the vim and vim-go packages don't seem to be aligned... Or maybe it was intentional, so that admins and users have to enable it manually. I'm not sure.

Anyway, I fixed it by adding this to my `.vimrc`:
`set runtimepath+=/usr/share/vim/vimfiles`
And as far as I can tell everything works!

I'm learning so much today. :-) Thanks again!
