### ISSUE TITLE
Push to Vim repo

### ISSUE THREAD

**Issue by 89z** [fatih/vim-go#3164]
Currently Vim is using this Go syntax:

https://github.com/google/vim-ft-go

which is old and has some problems. I raised the issue with the Vim developers, and they say a maintainer from this repo needs to make a pull request on the Vim repo, before any change can be made.

Would the maintainers here be interested in doing that?

**Comment by bhcleek** [comment]
Sure. What do you have in mind? The vim-go syntax file has had a number of changes over the years. Is there some particular problem in Vim's copy that you're concerned about?

**Comment by 89z** [comment]
The only issue I have had so far, is that underscore are not supported in numbers. So if you do these:

~~~go
1_000
0x1_0000
~~~

they dont register as numbers with the default Vim Go highlighter

**Comment by bhcleek** [comment]
yeah, that's easy enough to fix. I'll try to submit something to Vim soon.

**Comment by 89z** [comment]
If you are interested, I found these patterns that are shorter than others I have seen:

https://github.com/arp242/gopher.vim/blob/a758784f/syntax/go.vim#L207-L230

**Comment by brammool** [comment]
For copyright reasons, it's best if you explicitly request including files in the Vim distribution.  The BSD license is probably OK.  Also make sure the file header makes clear that issues with the files are to be reported here, not at the Vim repository.  And then once in a while send me a new version (by email or pull request).

**Comment by dbarnett** [comment]
No objections from me, speaking as a maintainer on https://github.com/google/vim-ft-go.

**Comment by bhcleek** [comment]
Closed in https://github.com/vim/vim/commit/90df4b9d423485f7db16e3a65cab4f14edc815ae#diff-ba1f661313ce15c6dbaad5f0d3969dfda150d4a6e56ebf2fc3e25643fe2b15dd which included all the changes from https://github.com/vim/vim/pull/8465.
