### ISSUE TITLE
Debug map local variables

### ISSUE THREAD

**Issue by ls-guillaume-rebesche** [fatih/vim-go#3168]
### What did you do? (required: The issue will be **closed** when not provided)
I'm not sure if it's a vim-go or a delve issue (or if it's an issue at all). But when I start the debug mode and breakpoint after unmarshal some json into a `map[string]interface{}`, I can't see the key or the values of the map (I can only see the type of the values).
Here is the code:
```go
bodyJSON := make(map[string]interface{})
err = json.Unmarshal(body, &bodyJSON)
```

### What did you expect to happen?

See the list of key/pair in the local variable window.

### What happened instead?

![Screen Shot 2021-03-08 at 5 52 04 PM](https://user-images.githubusercontent.com/38915436/110396224-9f5d8a00-803d-11eb-9379-483dc8d1aed8.png)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set nocompatible " be iMproved, required
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=/usr/local/opt/fzf
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'junegunn/fzf.vim'
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plugin 'fatih/vim-go'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'dense-analysis/ale'
Plugin 'airblade/vim-gitgutter'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" Put your non-Plugin stuff after this line

" GLobal settings
set relativenumber
autocmd Filetype python setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
autocmd Filetype go setlocal tabstop=4 shiftwidth=4 softtabstop=5
set shiftwidth=4
set undofile " Maintain undo history between sessions
set undodir=~/.vim/undodir

" swap files directory
set directory=$HOME/.vim/swap//

" airline
let g:airline_theme='simple'

" Run goimports along gofmt on each save
let g:go_fmt_command = "goimports"
" Automatically get signature/type info for object under cursor
let g:go_auto_type_info = 1

" syntax highlighting on
syntax on

" incremental search
set is

" highlighting searches
set hls

" better maouse usage
set mouse=a
set clipboard=unnamed
</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  5 2020 21:30:37)
macOS version
Included patches: 1-503, 505-680, 682-2292

#### Go version (`go version`):
go version go1.15.5 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/guillaume.rebesche/Library/Caches/go-build"
GOENV="/Users/guillaume.rebesche/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/guillaume.rebesche/workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/guillaume.rebesche/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/guillaume.rebesche/workspace/sdk/go1.15.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/guillaume.rebesche/workspace/sdk/go1.15.5/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/guillaume.rebesche/workspace/go/src/github.com/ls-guillaume-rebesche/preferences-service/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z9/nyg9xnj55j54f_lhczq9yyg00000gp/T/go-build035088768=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.5.4
</pre></details>

**Comment by bhcleek** [comment]
It's a bit of both. We can improve the experience in vim-go by handling maps better, but it does not appear that delve provides the values in this case.

Here's a sample of the relevant portion of the delve output:
```
{
      "name": "bodyJSON",
      "addr": 824633778224,
      "onlyAddr": false,
      "type": "map[string]interface {}",
      "realType": "map[string]interface {}",
      "flags": 1,
      "kind": 21,
      "value": "",
      "len": 1,
      "cap": 0,
      "children": [
        {
          "name": "",
          "addr": 824634179592,
          "onlyAddr": false,
          "type": "string",
          "realType": "string",
          "flags": 0,
          "kind": 24,
          "value": "foo",
          "len": 3,
          "cap": 0,
          "children": [],
          "base": 824633819507,
          "unreadable": "",
          "LocationExpr": "",
          "DeclLine": 0
        },
        {
          "name": "",
          "addr": 824634179720,
          "onlyAddr": false,
          "type": "interface {}",
          "realType": "interface {}",
          "flags": 0,
          "kind": 20,
          "value": "",
          "len": 0,
          "cap": 0,
          "children": [
            {
              "name": "data",
              "addr": 824633786544,
              "onlyAddr": true,
              "type": "string",
              "realType": "string",
              "flags": 0,
              "kind": 24,
              "value": "",
              "len": 3,
              "cap": 0,
              "children": [],
              "base": 824633819504,
              "unreadable": "",
              "LocationExpr": "",
              "DeclLine": 0
            }
          ],
          "base": 0,
          "unreadable": "",
          "LocationExpr": "",
          "DeclLine": 0
        }
      ],
      "base": 824634097712,
      "unreadable": "",
      "LocationExpr": "[block] DW_OP_fbreg -0xc0  (escaped)",
      "DeclLine": 12
    }
```

I'll see about improving the experiene soon.
