### ISSUE TITLE
'redrawtime' exceeded, syntax highlighting disabled

### ISSUE THREAD

**Issue by mallochine** [fatih/vim-go#3171]
### What did you do? (required: The issue will be **closed** when not provided)

If it helps, I only see this on the M1 Mac. Doesn't happen on my windows.

Steps to repro.
1. open a go file with these contents
2. it hangs. Doing `:messages` show a error message `'redrawtime' exceeded, syntax highlighting disabled`

```
package main

import "fmt"

func main() {
	fmt.Println("000000000000000000000000000000000000000000000000a")
}
```

### What did you expect to happen?

Ummm, syntax highlighting should work on such a simple file? LOL.

### What happened instead?

Got error: `'redrawtime' exceeded, syntax highlighting disabled`

####  `vimrc` you used to reproduce:

```
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'fatih/vim-go'
call vundle#end()            " required
filetype plugin indent on    " required

syntax on
```

#### Vim version (first three lines from `:version`):

If it helps, I'm on the latest M1 Macbook Air.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 23 2020 06:06:20)
macOS version
Included patches: 1-850
```

#### Go version (`go version`):

`go version go1.16 darwin/arm64`

#### Go environment

```
tmp# go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/genius/Library/Caches/go-build"
GOENV="/Users/genius/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/genius/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/genius/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cb/ywnyqljd6ml5pfqx1f0zkcpc0000gn/T/go-build1609639433=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

#### gopls version

```
golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=
```

**Comment by bhcleek** [comment]
I can't duplicate this on my macbook pro either.

What's redrawtime set to on your M1 (`:set redrawtime?`)?

**Comment by mallochine** [comment]
Are you on the M1 chip? set redrawtime shows me 2000, but I set it to 10000 and 20000 too and that didn't help.

**Comment by bhcleek** [comment]
No, I'm not on the M1 chip, nor do I have access to one.

**Comment by mallochine** [comment]
Given that that go code works on my linux server and windows, the main difference is apparently something to do with the. M1 Mac.

There are online services that rent out macs. There's one for the M1 Mac, especially since it's been 4+ months since it was released.

Here's one: https://www.computerworld.com/article/3605768/how-to-rent-a-virtual-m1-mac-mini-for-12-cents-an-hour.html

**Comment by mallochine** [comment]
Here I got an even simpler repro. Was just playing around with it. This should help make the problem a lot simpler to find?

```
package main

import "fmt"

func main() {
        fmt.Println("000000000000000000000000000000000000000000000000a")
}
```

**Comment by MattDietz** [comment]
I'm seeing this on a mid-2015 Macbook, as well, so I wouldn't say it's something about the M1

**Comment by bhcleek** [comment]
Ah, good point, @MattDietz I always forget about that setting. 

@mallochine  what does `:set re?` report on your M1?

**Comment by mallochine** [comment]
Did I do it right?

`regexpengine=0`

**Comment by mallochine** [comment]
Both of these fail
`set re=1`
and 
`set re=0`

**Comment by bhcleek** [comment]
@mallochine what did `set re?` report before you made any changes to try to set it?

**Comment by mallochine** [comment]
regexpengine=1

________________________________

**Comment by bhcleek** [comment]
Can you try `set re=2`?

**Comment by mallochine** [comment]
ah. That worked. Why did it work? What's the lesson here (besides use "set re=2")

**Comment by bhcleek** [comment]
It used a different regex engine. I don't know the particulars.  Usually `set re=0` is sufficient, but perhaps that's causing it to select the old engine on your machine.

`:help 're'` has details for you.

**Comment by MattDietz** [comment]
Have to admit I never bothered to see what it did, either, but it appears 0 automatically selects an engine and may change itself at any time.

```'regexpengine' 're'     number  (default 0)
                        global
        This selects the default regexp engine. two-engines
        The possible values are:
                0       automatic selection
                1       old engine
                2       NFA engine
        Note that when using the NFA engine and the pattern contains something
        that is not supported the pattern will not match.  This is only useful
        for debugging the regexp engine.
        Using automatic selection enables Vim to switch the engine, if the
        default engine becomes too costly.  E.g., when the NFA engine uses too
        many states.  This should prevent Vim from hanging on a combination of
        a complex pattern with long text.```

**Comment by jkopczyn** [comment]
Same problem for me today, and same fix (`re=2`). Thanks!

**Comment by adoliver** [comment]
> Same problem for me today, and same fix (`re=2`). Thanks!

Still an issue in 2024 on M1 machine and set re? showed regexpengine=1 when the file is first opened. forcing re=0 or re=2 worked for me on vim v9.0.1544

After updating to the current vim version v9.1.500 this issue went away and regexpengine was set to 0 when the file first  opened without a force in .vimrc

**Comment by yvardhineni** [comment]
`set re=2` solved the issue for me in vim for M1 2021.
