### ISSUE TITLE
GoDefType -> "vim-go: start pos is not valid"

### ISSUE THREAD

**Issue by thockin** [fatih/vim-go#3174]
### What did you do? (required: The issue will be **closed** when not provided)

Used `:GoDefType` on a field of a struct.  Sometimes it works and sometimes it says "vim-go: start pos is not valid".  Example file for me is `github.com/kubernetes/kubernetes/staging/src/k8s.io/api/discovery/v1/types.go`.  `EndpointSliceList.Items` always fails.

I have not been able to identify what is different when it works/doesn't.

### What did you expect to happen?

Go to type definition

### What happened instead?

"vim-go: start pos is not valid"

#### vim-go version:

v1.24

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'fatih/vim-go'

call vundle#end()

filetype plugin indent on
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 12 2020 10:29:41)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.16 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thockin/.cache/go-build"
GOENV="/home/thockin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/thockin/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/thockin/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3107532890=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=

</pre></details>

**Comment by bhcleek** [comment]
This is ultimately coming from `gopls`. Here's the request and response from `gopls`:
```
===== sent =====
Content-Length: 227

{"method":"textDocument/typeDefinition","jsonrpc":"2.0","id":21,"params":{"textDocument":{"uri":"file:///Users/bhcleek/src/k8s.io/kubernetes/staging/src/k8s.io/api/discovery/v1/types.go"},"position":{"character":4,"line":192}}}
===== received =====
Content-Length: 79

{"jsonrpc":"2.0","error":{"code":0,"message":"start pos is not valid"},"id":21}
```

At first, I thought the problem might be the way GOPATH is configured (i.e. _not_ set to the staging directory), but that doesn't seem to be the case; I get the same problem regardless of how GOPATH is set.

This even seems to be duplicatable when `types.go` is placed in its own module and reduced to 
```
package v1

type EndpointSlice struct{}

type EndpointSliceList struct {
	// List of endpoint slices
	Items []EndpointSlice `json:"items" protobuf:"bytes,2,rep,name=items"`
}
```

Strangely, other requests for information from the same location (e.g. `textDocument/hover`) seem to work fine:
```
===== sent =====
Content-Length: 181

{"method":"textDocument/hover","jsonrpc":"2.0","id":67,"params":{"textDocument":{"uri":"file:///Users/bhcleek/src/vim-go/issues/3174/types.go"},"position":{"character":1,"line":6}}}
===== received =====
Content-Length: 413

{"jsonrpc":"2.0","result":{"contents":{"kind":"plaintext","value":"{\"signature\":\"field Items []EndpointSlice\",\"singleLine\":\"field Items []EndpointSlice\",\"synopsis\":\"List of endpoint slices\",\"fullDocumentation\":\"List of endpoint slices\\n\",\"linkPath\":\"vim-go/3174\",\"linkAnchor\":\"EndpointSliceList.Items\"}"},"range":{"start":{"line":6,"character":1},"end":{"line":6,"character":6}}},"id":67}
===== sent =====
Content-Length: 190

{"method":"textDocument/typeDefinition","jsonrpc":"2.0","id":68,"params":{"textDocument":{"uri":"file:///Users/bhcleek/src/vim-go/issues/3174/types.go"},"position":{"character":1,"line":6}}}
===== received =====
Content-Length: 79

{"jsonrpc":"2.0","error":{"code":0,"message":"start pos is not valid"},"id":68}
```

@stamblerre this seems like a `gopls` issue. Should I create an issue there?

**Comment by bhcleek** [comment]
@thockin until this is fixed, you can workaround the problem with two `:GoDef` (`gd)` hops: first jump to the definition of the field, and then jump to the definition of the type of the field.

**Comment by stamblerre** [comment]
@bhcleek: Type definitions don't work for types like maps and slices. I think the closest feature request we have is https://github.com/golang/go/issues/38589, but if you think it should be supported, please file a feature request for this case.

**Comment by bhcleek** [comment]
@thockin Given that this is ultimately a gopls issue and outside vim-go's control, I propose we close this and start tracking golang/go#45029; I don't see anyway to reliable detect this situation from vim-go to provide a more useful error message to users.

**Comment by bhcleek** [comment]
@thockin it looks like this may be resolved soon. You may want to follow https://github.com/golang/go/issues/45029; it has a CL submitted to fix this on the `gopls` side.
