### ISSUE TITLE
GoBuildTags and gopls don't work together

### ISSUE THREAD

**Issue by benmoss** [fatih/vim-go#3175]
### What did you do? (required: The issue will be **closed** when not provided)
Tried editing [this file](https://github.com/knative/serving/blob/main/test/e2e/activator_test.go) which has the build tag `e2e` on it. I set `:GoBuildTags e2e` and it succeeds, but I still just see this error on the `package e2e` line:

```
No packages found for open file /tmp/serving/test/e2e/activator_test.go: <nil>.If this file contains build tags, try adding "-tags=<build tag>" to you...tring).Otherwise, see the troubleshooting guidelines for help investigating (https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md)
```

Debugging the LSP yields this:
<details><pre>
===== sent =====
Content-Length: 226

{"method": "workspace/didChangeWorkspaceFolders", "jsonrpc": "2.0", "params": {"event": {"added": [{"uri": "file:///tmp/serving", "name": "/tmp/serving"}], "removed": [{"uri": "file:///tmp/serving", "name": "/tmp/serving"}]}}}
===== received =====
Content-Length: 99

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":4,"message":"Loading packages..."}}
===== received =====
Content-Length: 133

{"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///tmp/serving","section":"gopls"}]},"id":7}
===== sent =====
Content-Length: 100

{"id": 7, "jsonrpc": "2.0", "result": [{"buildFlags": ["-tags", "e2e"], "hoverKind": "Structured"}]}
===== received =====
Content-Length: 540

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/03/15 15:00:35 go env for /tmp/serving\n(root /tmp/serving)\n(go version go version go1.16 linux/amd64)\n(valid build configuration = true)\n(build flags: [-tags e2e])\nGOSUMDB=sum.golang.org\nGO111MODULE=\nGOCACHE=/home/cesium/.cache/
===== received =====
Content-Length: 216

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/03/15 15:00:36 go/packages.Load\n\tsnapshot=0\n\tdirectory=/tmp/serving\n\tquery=[builtin knative.dev/serving/...]\n\tpackages=377\n"}}
===== received =====
Content-Length: 106

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":3,"message":"Finished loading packages."}}
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5

#### Go version (`go version`):
go version go1.16 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cesium/.cache/go-build"
GOENV="/home/cesium/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/cesium/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cesium/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/cesium/workspace/serving/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1942982445=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 0
g:go_auto_type_info = 0
g:go_loaded_gosnippets = 1
g:go_list_type = 'quickfix'
g:go_bin_path = '/home/cesium/.local/share/nvim/go/bin'
g:go_highlight_extra_types = 1
g:go_highlight_string_spellcheck = 1
g:go_highlight_operators = 1
g:go_code_completion_enabled = 0
g:go_jump_to_error = 1
g:go_highlight_function_calls = 1
g:go_fmt_autosave = 0
g:go_highlight_fields = 1
g:go_snippet_engine = 'ultisnips'
g:go_highlight_trailing_whitespace_error = 1
g:go_gopls_enabled = 1
g:go_highlight_variable_declarations = 1
g:go_highlight_format_strings = 1
g:go_echo_command_info = 0
g:go_highlight_function_parameters = 1
g:go_def_mode = 'gopls'
g:go_info_mode = 'gopls'
g:go_highlight_variable_assignments = 1
g:go_highlight_chan_whitespace_error = 1
g:go_mod_fmt_autosave = 0
g:go_highlight_functions = 1
g:go_highlight_space_tab_error = 1
g:go_metalinter_autosave = 0
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_fmt_experimental = 1
g:go_highlight_generate_tags = 1
g:go_referrers_mode = 'gopls'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_def_mapping_enabled = 0
g:go_highlight_array_whitespace_error = 1
g:go_gopls_options = ['-remote=auto']
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by findleyr** [comment]
Hi, does `:GoBuildTags` work as expected with a non-remote gopls (i.e. `let g:go_gopls_options = []`)?  Any method to specify build tags in gopls (for example setting `GOFLAGS`) _should_ work with the remote: the local gopls forwards its `go env` to the daemon. If it works without the remote, and doesn't work with the remote, that's a gopls bug (and one that I'm ultimately responsible for...).

Thanks.

**Comment by benmoss** [comment]
It appears it's not working when I set it to non-remote as well.

**Comment by benmoss** [comment]
So an interesting wrinkle that I discovered is that it's just `gd` / `Ctrl-]` that don't work, `:GoDef` works fine. `gd` (my normal way of go-deffing) does absolutely nothing, and `Ctrl-]` responds with 

```
E433: No tags file
E426: tag not found: EnsureTearDown
```

which I take to mean that some other tag-jumping thing is trying to take over instead of `:GoDef`

**Comment by benmoss** [comment]
Well this was a total wild goose chase because it turned out to be obliviously using https://github.com/josa42/coc-go/ for jumping to definitions now! Thanks @findleyr for sticking with me through this debugging adventure 😄
