### ISSUE TITLE
godef doesn't jump to the defintion of local functions (different file) and variables...

### ISSUE THREAD

**Issue by sameeroak11** [fatih/vim-go#3176]
### What did you do? (required: The issue will be **closed** when not provided)

The source code directory structure that I'm working on doesn't follow the stricter conventions such src directory. The code is haphazardly placed in a directory.
The project uses go modules.

Everything is working just good the only exception being godef (keys gd and :GoDef) doesn't jump to package local functions and variables that're defined in a different file in the same package. Tired of trying so many other things.

No clear direction so far.
Does vim-go work with go modules?

### What did you expect to happen?
Jump to the definition of package local functions/variables on gd or :GoDef.

### What happened instead?
vim-go: guru: no object for identifier

### Configuration (**MUST** fill this out):
Nothing specific apart from these ones in the .vimrc:

####  `vimrc` you used to reproduce:

<details><summary>
" golang specific vimrc configurations:
filetype plugin indent on

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'
"	Plug 'fatih/vim-go', { 'for': 'go' }
Plug 'fatih/vim-go'
Plug 'majutsushi/tagbar'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'nsf/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }

Plug 'morhetz/gruvbox'
Plug 'Shougo/neosnippet'
Plug 'Shougo/neosnippet-snippets'
Plug 'ctrlpvim/ctrlp.vim'

call plug#end()

nmap <F2> :NERDTreeToggle<CR>
au FileType go nmap <F8> :TagbarToggle<CR>
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gs <Plug>(go-info)

" let g:go_debug=['shell-commands']

" let g:go_fmt_command = "goimports"
" let g:go_fmt_command = "gofmt"

let g:go_fmt_fail_silently = 1
let g:go_fmt_autosave = 0

</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

version 8.1.2269

#### Go version (`go version`):

go 1.16

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

The only point to mention is GOPATH points to a directory /usr/local/golang/auxpkg
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

Not using.
</pre></details>

**Comment by bhcleek** [comment]
Module aware mode is unsupported w/ guru.

If you don't want to use `gopls`, then you can use `godef`: `let g:go_def_mode='godef'`

However, since your `g:go_def_mode` is unset in your vimrc, `:GoDef` seems to be using `guru`, and `gopls` has been the default value for `g:go_def_mode` since v1.23, it looks like you may be using an old version of vim-go. I'd strongly encourage you to upgrade to either the latest release or master.

**Comment by bhcleek** [comment]
closing for lack of feedback.
