### ISSUE TITLE
GoRename (gopls) does not work with GoBuildTags

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#3177]
### What did you do? (required: The issue will be **closed** when not provided)

Clone repo and open in vim file https://github.com/powerman/go-monolith-example/blob/master/ms/auth/service_integration_test.go, then try to use GoRename at line 87 to rename `clientAuthInt` to `clientInt`.
It will fail with error: `vim-go: gopls: no packages returned: packages.Load error`.
With `let g:go_debug = ['shell-commands']` it shows:
```
vim-go: shell command: '/usr/bin/go' 'env' 'GOMOD'
vim-go: [gorename] dispatched
vim-go: job command: ['/home/powerman/go/bin/gopls', 'rename', '-w', '/home/powerman/proj/go/go-mono
lith-example/ms/auth/service_integration_test.go:#2419', 'clientInt']
```
This happens because file has `// +build integration`. I've configured it, but this doesn't helps with GoRename:
```
:GoBuildTags
vim-go: current build tags: integration
```

### What did you expect to happen?
GoRename should work.

### What happened instead?
GoRename doesn't work. To make it work I have to remove build tags from the file first.

#### vim-go version:
Current master (fe66df2057a90ae38bd154035b0751f0f50e6752).

####  `vimrc` you used to reproduce:
Full version available at https://github.com/powerman/dotvim/blob/master/vimrc

<details><summary>vimrc</summary><br><pre>
let g:go_metalinter_command = 'golangci-lint'
let g:go_fmt_fail_silently = 1
let g:go_fmt_command = 'gopls'
let g:go_imports_autosave = 1
let g:go_imports_mode = 'gopls'
let g:go_gopls_gofumpt = v:true
" let g:go_gopls_local = trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m;}'))
let g:go_gopls_local = {}
autocmd FileType go call s:setlocal()
let g:go_doc_keywordprg_enabled = 0
let g:go_template_use_pkg = 1
let g:go_list_type = 'quickfix'
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_parameters = 0
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 0
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 0
let g:go_highlight_variable_assignments = 0
let g:go_build_tags = 'integration'
let g:go_gopls_matcher = 'caseSensitive'
let g:go_gopls_deep_completion = 0
let g:go_gopls_temp_modfile = 1
let g:go_gopls_use_placeholders = 1
autocmd FileType go nmap <buffer> <nowait> <Leader>r     <Plug>(go-run)
autocmd FileType go nmap <buffer> <nowait> <Leader>b     <Plug>(go-build)
autocmd FileType go nmap <buffer> <nowait> <Leader>t     <Plug>(go-test)
autocmd FileType go nmap <buffer> <nowait> <Leader>T     <Plug>(go-test-func)
autocmd FileType go nmap <buffer> <nowait> <Leader>c     <Plug>(go-coverage-toggle)
autocmd FileType go nmap <buffer> <nowait> <Leader>gd    <Plug>(go-def-tab)
autocmd FileType go nmap <buffer> <nowait> <Leader>gb    <Plug>(go-doc-browser)
autocmd FileType go nmap <buffer> <nowait> <Leader>s     <Plug>(go-implements)
autocmd FileType go nmap <buffer> <nowait> <Leader>i     <Plug>(go-info)
autocmd FileType go nmap <buffer> <nowait> <Leader>e     <Plug>(go-rename)

function! s:setlocal()
    try
	let l:olddir = chdir(expand('%:p:h'))
	let l:dir = trim(system('go list -m -f {{.Dir}}'))
	if !has_key(g:go_gopls_local, l:dir)
	    let g:go_gopls_local[l:dir] = trim(system('go list -m'))
	endif
    finally
	call chdir(l:olddir)
    endtry
endfunction
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, собрано Jan 23 2021 14:04:15)
Заплатки: 1-814
С изменениями, внесёнными Gentoo-8.2.0814-r100

#### Go version (`go version`):

go version go1.16.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/powerman/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/powerman/proj/go/go-monolith-example/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2164728747=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 1
g:go_list_type = 'quickfix'
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_gopls_matcher = 'caseSensitive'
g:go_highlight_function_calls = 1
g:go_highlight_function_parameters = 0
g:go_highlight_fields = 0
g:go_highlight_generate_tags = 1
g:go_gopls_deep_completion = 0
g:go_highlight_variable_declarations = 0
g:go_highlight_string_spellcheck = 1
g:go_loaded_gosnippets = 1
g:go_gotags_bin = 'gotags'
g:go_metalinter_command = 'golangci-lint'
g:go_doc_keywordprg_enabled = 0
g:go_highlight_variable_assignments = 0
g:go_highlight_format_strings = 1
g:go_gopls_local = {'/home/powerman/proj/go/go-monolith-example': 'github.com/powerman/go-monolith-example'}
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_functions = 1
g:go_template_use_pkg = 1
g:go_gopls_use_placeholders = 1
g:go_highlight_types = 1
g:go_fmt_command = 'gopls'
g:go_imports_mode = 'gopls'
g:go_jump_to_error = 1
g:go_imports_autosave = 1
g:go_gopls_gofumpt = v:true
g:go_build_tags = 'integration'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_gopls_temp_modfile = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:OFF
</pre></details>

**Comment by bhcleek** [comment]
Yes, this is a known issue currently. I have a local branch that has this fix nearly ready. Until then, the workaround is to either use `gorename` outside of module mode or else remove the build constraint while doing a rename.

**Comment by powerman** [comment]
@bhcleek Thanks. It mostly works, but there are few new issues:

After successful rename it now prints two lines instead of one:
```
vim-go: [rename] SUCCESS                                                          
vim-go: [rename] SUCCESS
```

And if I (by mistake) try to rename identifier to itself (no changes), then previously it works (does nothing), but now it throws exception:

```
vim-go: [rename] SUCCESS                                                          
vim-go: [rename] FAIL
Error detected while processing function go#rename#Rename[31]..go#lsp#Rename[14]..<SNR>165_await:
line    8:
E605: Exception not caught: (call):E121: Undefined variable: documentChanges
Error detected while processing function go#rename#Rename:
line   31:
E171: Missing :endif
```

**Comment by bhcleek** [comment]
I'll fix both of these. You might want to look into using vim-go status line integration and turn off `g:go_echo_command_info`; the statusline integration is a more fully featured solution and is redundant with  what `let g:go_echo_command_info=1` enables.

**Comment by powerman** [comment]
Thanks, but with my setup I don't have a status line.
I'm using large enough font, so I don't like to lose one line of screen space for a status line. And I'm using vim tabs, so with `laststatus=1` there is no status line on screen (most of time, except rare cases when I open more than one vim window in a tab).
I've played with vim-airline, but at the end of day it looks less useful than one extra line for my code.
