### ISSUE TITLE
tagbar is too slow to highlight the current symbol if auto_type_info is disabled.

### ISSUE THREAD

**Issue by igungor** [fatih/vim-go#318]
1. disable auto_type_info by `let g:go_auto_type_info=0`
2. open up `tagbar` via `:TagbarOpen`
3. move the cursor onto another function/method.
4. observe the delay on tagbar buffer while it tries to highlight the current symbol.

this side effect is caused by changing the global updatetime variable: https://github.com/fatih/vim-go/blob/master/ftplugin/go.vim#L43

@fatih why do we need to change this global variable if the auto-type-info is disabled? this control seems redundant. what do you think?

**Comment by fatih** [comment]
It shouldn't change the variable if it's disabled. Because `get()` returns zero by default if `go_auto_type_info` is not set. So if it's disabled it shouldn't touch it at all. Can you remove those three lines and test again?

**Comment by igungor** [comment]
Yeah you're right. Removing the check revealed that default `updatetime` value was `4000` by default. vim-go wasn't slowing down tagbar, it was speeding up the process actually if the auto_type_info is [ON] :)

I'm closing this issue.

**Comment by fatih** [comment]
Hehe :) Glad you find it, I think that was the reason I've added the updatetime, because the default is really slow.
