### ISSUE TITLE
`g:go_gopls_enabled = 0` may disable auto formatting on save

### ISSUE THREAD

**Issue by kit494way** [fatih/vim-go#3187]
### What did you do? (required: The issue will be **closed** when not provided)
Disable gopls by setting `g:go_gopls_enabled = 0`.

### What did you expect to happen?
Only LSP features are disabled.

### What happened instead?
Auto formatting on save is also disabled.

This is happening from the change https://github.com/fatih/vim-go/pull/2986 .
If goimports is not installed, disabling gopls by `g:go_gopls_enabled = 0` also disables auto formtting on save despite `g:go_fmt_autosave = 1`.
Although installing goimports or `g:go_imports_autosave = 0` resolve this problem, I report this issue because I was a little surprised at first.

#### vim-go version:
bd89f47

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
let g:go_gopls_enabled = 0
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.15.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kit494way/.cache/go-build"
GOENV="/home/kit494way/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kit494way/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kit494way/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build820749993=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.9
    golang.org/x/tools/gopls@v0.6.9 h1:LBBcE2y3Tb4bp79JVLWCQBbvYCFEs5ADGWsQDoSLk1Q=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_code_completion_enabled = 0
g:go_fmt_autosave = 1
g:go_gopls_enabled = 0
g:go_jump_to_error = 1
g:go_imports_autosave = 0
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Vim-go expects that users install the tools it depends on (e.g. with `:GoUpdateBinaries`); `goimports` should be present. Because `goimports` and `gofmt` overlap in functionality, vim-go has long deduplicated and run only `goimports` when it would be redundant `gofmt`.
