### ISSUE TITLE
Provide a way to call `iferr` from Insert mode

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#3193]
### What did you do? (required: The issue will be **closed** when not provided)

I'm trying to use `:GoIfErr` / `go#iferr#Generate()` from insert mode, e.g. as a snippet (see https://github.com/SirVer/ultisnips/issues/1335) or using `iabbr`. The problem is it doesn't leave cursor in position one might expect - just below inserted `if` block. So, I had to use workaround by wrapping provided vim-go function to fix cursor position:

```vim
autocmd FileType go iabbr <buffer> errn <C-R>=<SID>goiferr()<CR>
function! s:goiferr()
    call go#iferr#Generate()
    return "\<Esc>O"
endfunction
```

### What did you expect to happen?

There should be a way to turn `iferr` into snippet(-like thing) out of box, e.g. it would be nice if this will work:

```vim
autocmd FileType go iabbr <buffer> errn <C-R>=go#iferr#Snippet()<CR>
```

Another possible improvement is to provide a function which will be compatible with calling from UltiSnip using `!v go#iferr#Snippet()` (I suppose such function should return text to insert instead of doing actual edits).

### What happened instead?

I had to invent a workaround and mix snippets with iabbr, then remember to use different keys to trigger one or another. :disappointed:

**Comment by powerman** [comment]
BTW, the tool itself is small and looks not maintained anymore, so it may worth to switch to one of it forks or just make our own - it may be easier than try to fix it in vim.

**Comment by bhcleek** [comment]
There are a number of UltiSnip snippets that ship with Vim-go. I think the one you're looking for is `errn`: https://github.com/fatih/vim-go/blob/master/gosnippets/UltiSnips/go.snippets#L162-L167

**Comment by powerman** [comment]
Well, you know, that snippet isn't as smart as `iferr` tool. Ideally I'd like to press same `errn<Tab>` to trigger snippet, but have this snippet run `iferr` to insert more smart `if err != nil` block.

**Comment by bhcleek** [comment]
Have you looked at the other snippets? e.g. `errn,`, etc? They may not  be as smart at the `iferr`, tool, but they get the job done pretty well.

> The problem is it doesn't leave cursor in position one might expect

Where do you expect it to leave the cursor?

> Another possible improvement is to provide a function which will be compatible with calling from UltiSnip using `!v go#iferr#Snippet()`

Sure, I could do that easily enough. I'll try to put up a PR by the end of the weekend.

**Comment by powerman** [comment]
> Where do you expect it to leave the cursor?

Same way as existing `errn` snippet works - on next line below `if` block.

**Comment by bhcleek** [comment]
That's where it places the cursor on my machine. Where are you seeing it place the cursor?

**Comment by powerman** [comment]
Well, it's not on next line, it's at **beginning** of next line - this isn't the same thing if next line has different indent (e.g. it's a line with a brace closing current block). Look: https://asciinema.org/a/avDNay6hiXJeL0RTQxpRCJy33

Also when calling it from INSERT mode using e.g. `iabbr … <C-R>=go#iferr#Generate()<CR>` then we get extra "0" inserted at beginning of next line (probably because of `return 0` at end of the function): https://asciinema.org/a/7o03DF38KVjppatt7qrrHkT4c

What I want is to make it work this way in INSERT mode out-of-box: https://asciinema.org/a/hMUa1HdV7HPsovMkMTV0nz1xo

**Comment by powerman** [comment]
> at **beginning** of next line

Actually, it's somewhere on next line, not necessarily at beginning - as you can see in first recording after first `:GoIfErr`.

**Comment by bhcleek** [comment]
> probably because of return 0 at end of the function

`go#iferr#Generate()` does not have a `return 0` at the end of it. I'm not sure where that zero is coming from.

In any case, you might try `autocmd FileType go iabbr <buffer> iferr <Cmd>GoIfErr<CR>`. I think it gets you pretty close to what you're looking for and with some fiddling, you can probably adjust that to get exactly what you desire.

**Comment by powerman** [comment]
This doesn't work in vim-8.2.0814, it just inserts raw string `<Cmd>GoIfErr`.

**Comment by bhcleek** [comment]
I'm on 8.2.2200 and it works fine. I'm not sure when `<Cmd>` support was added. I'd encourage you to look at the docs; it's possible that you may need to use `<Cmd>:GoIfErr<CR>` or something similar.

**Comment by powerman** [comment]
map-cmd was added in 8.2.1978 (Nov 12) :disappointed:

**Comment by bhcleek** [comment]
Is upgrading Vim an option for you? I'm reluctant to try to add something that is ultimately redundant with features that Vim is adding natively.

**Comment by powerman** [comment]
I agree it doesn't makes sense to add something if it's already implemented by vim itself. No, upgrading is not an option - I'm using latest version available in Gentoo. So, we can close this issue, I think. Thanks!
