### ISSUE TITLE
syntax colors are changed after `:w` (in 'delek' colorset)

### ISSUE THREAD

**Issue by gucio321** [fatih/vim-go#3195]
### What did you do? (required: The issue will be **closed** when not provided)
I'm writting code in go using vim-go plugin.
After `:PluginInstall!` I saw a strange bug:
the syntax colors are changed after saving file `:w`
To Reproduce
- run vim --cmd "color delek" /tmp/file.go
- paste a following code:
```golang
package main

func main() {
   v := []int{}
   v = append(v, 5) // this line is the most important
}
```
- save file (`:w`)
- the color of `append` will be changed

### What did you expect to happen?
this shouldn't happen. It looks, like base vim's syntax color is applied at start. After saving file coloring is refreshed and editor uses plugin's color.

#### vim-go version:
1.24

####  `vimrc` you used to reproduce:
<details><summary>vimrc</summary><br><pre>
" I paste only these lines, for vim-go
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'fatih/vim-go'

call vundle#end()            " required
filetype plugin indent on    " required
let g:go_fmt_command = "/home/user/go/bin/gofumpt"
</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 22 2021 00:00:00)
Included patches: 1-2637
Modified by <bugzilla@redhat.com>

#### Go version (`go version`):

go version go1.16.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/git/d2/me/OpenDiablo2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2421036035=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.9
    golang.org/x/tools/gopls@v0.6.9 h1:LBBcE2y3Tb4bp79JVLWCQBbvYCFEs5ADGWsQDoSLk1Q=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_highlight_extra_types = 1
g:go_highlight_trailing_whitespace_error = 1
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_space_tab_error = 1
g:go_fmt_command = '/home/mszeptuch/go/bin/gofumpt'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
This is happening because of diagnostics that vim-go receives from `gopls` when  the file is saved. `gopls` diagnostics identify that `v` is not used, and therefore flags it. Vim-go updates the highlighting accordingly.
