### ISSUE TITLE
Argument list error displayed for octal literals

### ISSUE THREAD

**Issue by carbonin** [fatih/vim-go#3196]
### What did you do? (required: The issue will be **closed** when not provided)
Wrote (:w) the following go file:
```go
package main

import "fmt"

func main() {
        thing(0o123, "abc")
}

func thing(x int, y string) {
        fmt.Printf("%d %s", x, y)
}
```

### What did you expect to happen?
The file to write without errors
### What happened instead?
`thing.go|6 col 9| missing ',' in argument list (and 1 more errors)`
In the error location list
#### vim-go version:
master (ce95699)
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 22 2021 00:00:00)
Included patches: 1-2541
Modified by <bugzilla@redhat.com>

#### Go version (`go version`):

go version go1.15.7 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ncarboni/.cache/go-build"
GOENV="/home/ncarboni/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ncarboni/Source/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ncarboni/Source/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build534920714=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

I've also seen this display an issue about missing a trailing ',' for struct literal, but couldn't get that to reproduce as easily.

**Comment by carbonin** [comment]
Update: Does not happen with `v1.24`

**Comment by bhcleek** [comment]
Your version of `gopls` is very old. I suspect it may be the source of the problem. Can you try updating it with `:GoUpdateBinaries gopls`?

**Comment by carbonin** [comment]
:facepalm: Closing
