### ISSUE TITLE
gopls doesn't get go.mod file updates

### ISSUE THREAD

**Issue by palcalde** [fatih/vim-go#3197]
Hello! I've seen that GoToDefinition works great with gopls when I want to navigate into a given module library, it navigates to my `go/pkg/mod` folder. This is extremely useful in my day to day coding. However, if I change in go.mod some module version, vim-go keeps going to the previous one. i.e if I update go.mod module A to change from v1.0 to v2.0, gopls doesn't realize the change and keeps navigating always to methods and definitions on `~/go/pkg/mod/A@v1.0/...`

I've used `:GoLSPDebugBrowser` and I've seen that every time I change go.mod there is no `textDocument/didChange` notification sent to `gopls` server, so I guess that is the reason why it does not pick up the new module version listed in go.mod.

I've tried:
- go build, go mod tidy, go run, etc etc.. and nothing triggers any notification to inform `gopls`  about the version change

Current workarounds:
- restart vim, that restarts `gopls` and so picks up the new go.mod version.
- call `:GoAddWorkspace` passing your directory where the module is, that refreshes the state in `gopls` of that folder and so picks up the new versions of go.mod modules. 
- I've tested as well initializing `gopls` with some experimental go modules features, [like experimentalWorkspaceModule](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#experimentalworkspacemodule-bool) but didn't work either.

Is this expected to happen?

Thank you!

**Comment by bhcleek** [comment]
Yes, if you modify the module file, then you will need to restart your vim session to pick up those changes until #2697 is resolved.
