### ISSUE TITLE
support not show type_info  when type too long

### ISSUE THREAD

**Issue by zdmgmail** [fatih/vim-go#3198]
use `let g:go_auto_type_info = 1`, 

if type info short,  show in bottom, 

if type too long ,  need `Press ENTER or type command to continue`

Is there a way use `let g:go_auto_type_info = 1`  but not auto show when it need press enter?

![04-09_22:54:26](https://user-images.githubusercontent.com/50515839/114199685-1b255c00-9987-11eb-9028-c66096a643d1.png)

**Comment by bhcleek** [comment]
This is really a question about Vim generally. The shortmess option has details about how to shorten the messages. I think you're looking for `T` (see `:help shortmess`).

**Comment by zdmgmail** [comment]
> This is really a question about Vim generally. The shortmess option has details about how to shorten the messages. I think you're looking for `T` (see `:help shortmess`).

yeah , seems should ues `T`, but I tried  `set shortmess+=T` or `set shortmess=T` not change ...

**Comment by bhcleek** [comment]
There's no other way for vim-go to deal with this generally; it's dependent on the width of your screen, the length of the message, and your `shortmess` setting.
