### ISSUE TITLE
Integration with gometalinter

### ISSUE THREAD

**Issue by noonien** [fatih/vim-go#320]
Are there any plans to integrate with [gometalinter](https://github.com/alecthomas/gometalinter)?

**Comment by fatih** [comment]
Thanks for bringing it up. I don't think to integrate it right now. Let's wait until it get's some momentum. Also each linter has his own format and for some of them it requires special formatting rules.  I don't want to add them right now.

**Comment by alecthomas** [comment]
> Also each linter has his own format and for some of them it requires special formatting rules.

That is actually the very problem that gometalinter solves. It runs errcheck, structcheck, vet, deadcode, golint, gotype, defercheck, varcheck, gocyclo, and go vet and normalises their output to a single format:

```
<file>:<line>:[<col>]: <message> (<linter>)
```

**Comment by noonien** [comment]
Has this been given any further consideration? As @alecthomas suggested, since I've created this issue, gometalinter has standardized its output format, and is similar to output given from gofmt.

Having the ability to run all linters on save would be a great benefit to any project.

Please reconsider. Thank you!

**Comment by tsenart** [comment]
+1

**Comment by xla** [comment]
+1

**Comment by fatih** [comment]
I'll reopen and add label it as `feature`. Will tackle it later or soon :)

**Comment by xla** [comment]
@fatih Thanks for the follow-up!

**Comment by tgrosinger** [comment]
+1 this feature request. I was going to open an issue asking for integrating go-vet and go-lint on save (similar to what go-plus does for Atom), but this sounds like it would be even better in the long run.

**Comment by siddharthist** [comment]
+1

**Comment by josephglanville** [comment]
+1

**Comment by karlmutch** [comment]
+1

**Comment by fatih** [comment]
It's on my schedule, I didn't forget it, no need for the +1's ;)

**Comment by fatih** [comment]
A related issue: https://github.com/alecthomas/gometalinter/issues/49

**Comment by fatih** [comment]
I've started to implement `gometalinter` and finally have a working version here: https://github.com/fatih/vim-go/pull/553 Please try to use it and comment on any issues you find :)

**Comment by fatih** [comment]
This is now merged to master. Please check #553 or the docs how to use it.
