### ISSUE TITLE
GoRun does not wait for input

### ISSUE THREAD

**Issue by bon-ami** [fatih/vim-go#3200]
### What did you do? (required: The issue will be **closed** when not provided)
Edit my go files in NeoVim and :GoRun

code piece, `fmt.Scanln`
### What did you expect to happen?
Terminal window opens and wait for my input
### What happened instead?
Terminal window opens and closes immediately without my input
### Configuration (**MUST** fill this out):
Windows 10
#### vim-go version:
1.24 / 4-2-2021 ce95699efa82921f80fdc0984d002ff81584c6e6
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set nocompatible
call plug#begin('~\AppData\local\nvim\plugged')
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
</pre></details>

#### Vim version (first three lines from `:version`):

neovim 0.5.0-746
#### Go version (`go version`):

go1.15.5 windows/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\H\AppData\Local\go-build
set GOENV=C:\Users\H\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\H\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\H\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\H\AppData\Local\Temp\go-build431317306=/tmp/go-build -gno-record-gcc-switches
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.2
    golang.org/x/tools/gopls@v0.5.2 h1:lyHTekqy0QhXzz5hDFnfMGHk0Qmuq+LWH5VN/o19YLk=
</pre></details>

**Comment by bhcleek** [comment]
What does `echo go#config#TermEnabled()` report on your machine?

**Comment by bhcleek** [comment]
By default, neovim's terminals don't allow input. You can enable it, though. Here's a couple of tips:
* https://github.com/neovim/neovim/issues/8816
* https://vi.stackexchange.com/questions/3670/how-to-enter-insert-mode-when-entering-neovim-terminal-pane

**Comment by Ruixi-rebirth** [comment]
I have set neovim to turn on automatic term insertion, but when I GoRun it did not wait for input
![image](https://user-images.githubusercontent.com/75824585/140891888-e6656afb-f31f-4e3b-bb80-756b5c780441.png)
![image](https://user-images.githubusercontent.com/75824585/140891962-3b131cd3-9abe-4487-955a-f2bb6a3fd3de.png)
![image](https://user-images.githubusercontent.com/75824585/140891989-476b8dda-85ed-4ca1-a09c-4b24883ea67e.png)
