### ISSUE TITLE
GoInstallBinaries does not use `go env GOBIN`

### ISSUE THREAD

**Issue by aletheia7** [fatih/vim-go#3204]
### What did you do?
Installed the vim-go binaries with :GoInstallBinaries.

### What did you expect to happen?
I wanted the binaries installed in ~/bin (/var/root/bin).

GOBIN is set to /var/root/bin via ```go env -w GOBIN=/var/root/bin```. The documentation under g:go_bin_path for v1.25 and master 3ec431eaefb75520cbcfed0b6d0d7999d7ea3805 states GOBIN will be used. GOBIN is not set via an environment variable. g:go_bin_path is not set in .vimrc.

### What happened instead?
:GoInstallBinaries installed go binaries to /var/root/go/bin. /var/root/go/bin was made first.

#### vim-go version
Tried: v1.25 and master 3ec431eaefb75520cbcfed0b6d0d7999d7ea3805 

####  `vimrc`
```
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
```

#### Vim version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 10 2021 22:12:04)
macOS version - x86_64
Included patches: 1-2750
Compiled by Homebrew
#### Go version
go version go1.16.3 darwin/amd64
#### Go environment
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/var/root/bin"
GOCACHE="/var/root/Library/Caches/go-build"
GOENV="/var/root/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/var/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/var/root/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/go-build568528766=/tmp/go-build -gno-record-gcc-switches -fno-common"
#### gopls
golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=

**Comment by aletheia7** [comment]
FYI: When I add ```let g:go_bin_path="/var/root/bin"``` in .vimrc, ```:GoInstallBinaries``` installed binaries to /var/root/bin as expected.

**Comment by bhcleek** [comment]
`go env -w` changes the default settings of the given values. Vim-go's documentation clearly states that `$GOBIN` will be used if it's set. Since your environment variable is not set, it's not being used.

We could certainly stop using `$GOBIN` and rely on `go env GOBIN` to get the value, but that's a change from current documented behavior. As it is currently, vim-go is working as documented.

I'll probably have to change this regardless before Go 1.17 since it's expected to entirely drop support for GOPATH.

**Comment by aletheia7** [comment]
> `go env -w` changes the default settings of the given values. Vim-go's documentation clearly states that `$GOBIN` will be used if it's set. Since your environment variable is not set, it's not being used.
> 
> We could certainly stop using `$GOBIN` and rely on `go env GOBIN` to get the value, but that's a change from current documented behavior. As it is currently, vim-go is working as documented.
> 
> I'll probably have to change this regardless before Go 1.17 since it's expected to entirely drop support for GOPATH.

```go env GOBIN``` would be a great idea. It also supports the $GOBIN as an override.
