### ISSUE TITLE
How do I add a package dependency from vim?

### ISSUE THREAD

**Issue by kaihendry** [fatih/vim-go#3205]
I recreate my project's go.mod like so `go mod init github.com/kaihendry/tracing` and it shows that some dependencies are not installed. Next it wants me to I suppose run `go get` manually from the command line?

<img src="https://s.natalian.org/2021-04-21/1618976769_1918x1047.png">

### What did you expect to happen?

A convenience function to get the package under my cursor.

### What happened instead?

Hoop jumping

####  `vimrc` you used to reproduce:

https://github.com/kaihendry/dotfiles/blob/master/.vimrc

#### Vim version (first three lines from `:version`):

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.16.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hendry/.cache/go-build"
GOENV="/home/hendry/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/hendry/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hendry/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/hendry/tmp/tracing/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3163151883=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.9
    golang.org/x/tools/gopls@v0.6.9 h1:LBBcE2y3Tb4bp79JVLWCQBbvYCFEs5ADGWsQDoSLk1Q=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_auto_sameids = 1
g:go_metalinter_enabled = ['vet', 'golint']
g:go_loaded_install = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Vim-go doesn't yet have a way for you to explicitly add a dependency. You can run `go get` from the command line to add your dependency in the usual way.

**Comment by bhcleek** [comment]
> Hoop jumping

Vim isn't an IDE; it's focused on editing buffers. I'm not opposed to adding a function to add a dependency per se, though.

> vim-go version: latest, not sure where to get this or why isn't it filled in by GoReportGitHubIssue?

There isn't a reliable way to get this information; it very much depends on how you've installed vim-go. Usually it's cloned via some means, so you only need to cd to the vim-go work tree and run `git rev-parse HEAD`.
