### ISSUE TITLE
(go-imports) mapping no longer formats with gopls enabled

### ISSUE THREAD

**Issue by thsnr** [fatih/vim-go#3208]
### What did you do? (required: The issue will be **closed** when not provided)

Invoked the `<Plug>(go-imports)` mapping with `gopls` support enabled after upgrading from vim-go 1.24 to 1.25.

### What did you expect to happen?

The current file imports to be organized _and_ the Go source code to be formatted.

### What happened instead?

The current file imports were organized, but the source code was not formatted.

### Details

`(go-imports)` is mapped to `go#fmt#Format(1)`: https://github.com/fatih/vim-go/blob/f3ebf20e2c5dd672d55af26fdde6edb41971336b/ftplugin/go/mappings.vim#L36
 If `go#fmt#Format` is invoked with `withGoImport == 1` and `gopls` is enabled, then it calls `go#lsp#Imports` and immediately returns, without reaching the `go#lsp#Format` call below: https://github.com/fatih/vim-go/blob/f3ebf20e2c5dd672d55af26fdde6edb41971336b/autoload/go/fmt.vim#L20-L43

#### vim-go version:

v1.25

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
let g:go_fmt_autosave = 0
au FileType go nmap &lt;leader&gt;i &lt;Plug&gt;(go-imports)
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)
Included patches: 1-2434
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.15.9 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tiit/.cache/go-build"
GOENV="/home/tiit/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tiit/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tiit/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.15/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build388249424=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_template_autocreate = 0
g:go_metalinter_command = 'golangci-lint'
g:go_loaded_gosnippets = 1
g:go_gotags_bin = 'gotags'
g:go_loaded_install = 1
g:go_fmt_autosave = 0
g:go_def_mapping_enabled = 0
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Yes, that's true. The `go-imports` mapping is to do the same as `:GoImports` does. In `gopls` mode, `:GoImports` only adjusts imports, but the documentation needs to be adjusted to make that clear.

**Comment by thsnr** [comment]
Makes sense, I had a a feeling that this was the case, but the function name `go#fmt#Format` made me think again.

In this case could a `go-fmt` mapping be added to do the same as `:GoFmt`? This seems to be missing. Or should I open a separate issue for this feature request?

**Comment by bhcleek** [comment]
I'm not opposed to it, but I wonder whether it's needed given that formatting can happen on save. What's the value of having a mapping for it when it can happen on save anyway?

**Comment by thsnr** [comment]
I admit that for me personally it is just an old habit to only invoke formatting explicitly. The mapping might not be very useful to many others, in which case there is no need to add it and I can easily add my own (or get accustomed to auto-formatting).

**Comment by thsnr** [comment]
Thank you, @bhcleek! :+1:
