### ISSUE TITLE
No way to tell, which files were affected by :GoRename

### ISSUE THREAD

**Issue by Flygrounder** [fatih/vim-go#3211]
### What did you do? (required: The issue will be **closed** when not provided)
I've renamed a function, that is used outside of the current file.

### What did you expect to happen?
One of the following:
1. All files, affected by rename are saved on disk
2. These files would be opened as buffers instead

### What happened instead?
None of the things above. I still have one buffer opened and changes were not written to disk. But when I open any affected file, there are unsaved modifications. This is very frustrating since I do not know, which files were affected by change and if I simply quit vim, these changes would not be saved.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" Plugins
call plug#begin('~/.vim/plugged')
Plug 'https://github.com/fatih/vim-go.git'
call plug#end()
```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.16.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/flygrounder/.cache/go-build"
GOENV="/home/flygrounder/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/flygrounder/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/flygrounder/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/flygrounder/Projects/go-mtg-vk/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1044327966=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by Flygrounder** [comment]
After doing some research, I've realized, that they were opened as hidden buffers and I've checked my buffers with `:ls` instead of `:ls!`. Sorry for false alarm

**Comment by bhcleek** [comment]
I'm glad you were able to find the resolution.

May I also recommend that you set `autowrite` and/or `autowriteall` (see `:help autowrite`) so that the buffers will be saved as Vim-go moves through them?

**Comment by Flygrounder** [comment]
Oh, I will try these options, thanks for the tip. 

Also, maybe this behaviour (opening hidden buffers on rename) is worth documenting? It was unclear for me and I've found nothing about it in the docs.
