### ISSUE TITLE
GoDebugBreakpoint not saved between sessions

### ISSUE THREAD

**Issue by kaihendry** [fatih/vim-go#3213]
If I quit vim and re-enter vim, my breakpoints are not to found. How do I fix it so vim remembers?

**Comment by bhcleek** [comment]
I'm not sure if it's possible. If it is possible, then viminfo and/or sessions would be the mechanism you're looking for.

**Comment by kaihendry** [comment]
I just tried https://bocoup.com/blog/sessions-the-vim-feature-you-probably-arent-using ... set a break point and saving session


    :mks ~/.vim/sessions/rooster.vim
    :q
    vim -S ~/.vim/sessions/rooster.vim

But it lost the breakpoint. Damn.
