### ISSUE TITLE
upon saving file vim freezes and laptop starts heating up.

### ISSUE THREAD

**Issue by relentless-coder** [fatih/vim-go#3214]
### What did you do? (required: The issue will be **closed** when not provided)
It was working as expected until last night, now `:w` or `:wq` commands  freeze up my vim session and my laptop starts heating up with the fans running at full speed. At that point I have to restart my machine, because even if I close vim, the fans don't slow down.

I went through related issues listed regarding Syntastic, but I removed it and it still doesn't work. I am not sure if Syntastic is the cause of it because I've been using vim-go for a month, and it didn't cause any issue with Syntastic.

I'd like to mention, I installed JetBrains' GoLand last night, and started encountering issue with vim-go after that. But even after completely removing GoLand from my system, vim-go is still freezing on file save.

an example go file:

```
package main

import "fmt"

func sqrRt(x int) int {
	return x * x
}

func mulTwo(y int) int {
	return y * 2
}

func addTwo(z int) int {
	return z + 2
}

func main() {
	fmt.Println("vim-go")
	rs := sqrRt(mulTwo(addTwo(8)))
	fmt.Println(rs)
}
```
after running `:w` or `:wq` it just freezes.

### What did you expect to happen?

To vim to save or close file as expected

### What happened instead?

vim session is unresponsive

<img width="530" alt="Screenshot 2021-05-02 at 12 02 19 PM" src="https://user-images.githubusercontent.com/22293231/116804734-d97b7180-ab3e-11eb-8d78-8e4827769efb.png">

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 27 2021 03:10:38)
macOS version - x86_64
Included patches: 1-2550

#### Go version (`go version`):

go version go1.16 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/relentless-coder/Library/Caches/go-build"
GOENV="/Users/relentless-coder/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/relentless-coder/Workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/relentless-coder/Workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/relentless-coder/Workspace/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bb/syjkq1rj28s688v6cg4hrd180000gn/T/go-build1752729916=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_gocode_autobuild = 0
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Are you in a working directory with a lot of go types rooted there?

Can you run with `g:go_debug=['lsp']` and provide the gopls logs?

**Comment by relentless-coder** [comment]
@bhcleek my working dir is `$GO_PATH/src/github.com/relentless-coder/learn_go`

and here are the gopls logs after saving the file once.

```
===== sent =====
Content-Length: 648

{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///Users/relentless-coder/Workspace","capabilities":{"workspace":{"workspaceFolders":true,"workspaceEdit":{"documentChanges":true},"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true}},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["source.organizeImports","refactor.rewrite"]}}},"completion":{"completionItem":{"snippetSupport":false}},"hover":{"contentFormat":["plaintext"]}}},"processId":63137,"workspaceFolders":[{"uri":"file:///Users/relentless-coder/Workspace","name":"/Users/relentless-coder/Workspace"}]}}
===== stderr =====
serve.go:414: debug server listening at http://localhost:52420
===== received =====
Content-Length: 279

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/05/04 19:35:49 Handshake session update\n\tupdate_session=3\n\tdebug_address=\"127.0.0.1:52420\"\n\tlogfile=\"\"\n\tserver=\"1\"\n\tgopls_path=\"/Users/relentless-coder/Workspace/go/bin/gopls\"\n"}}
===== received =====
Content-Length: 2952

{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"change":2,"openClose":true,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor.extract","refactor.rewrite","source.fixAll","source.organizeImports"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["gopls.add_dependency","gopls.add_import","gopls.apply_fix","gopls.check_upgrades","gopls.gc_details","gopls.generate","gopls.generate_gopls_mod","gopls.go_get_package","gopls.list_known_packages","gopls.regenerate_cgo","gopls.remove_dependency","gopls.run_tests","gopls.test","gopls.tidy","gopls.toggle_gc_details","gopls.update_go_sum","gopls.upgrade_dependency","gopls.vendor","gopls.workspace_metadata"]},"callHierarchyProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"{\"path\":\"golang.org/x/tools/gopls\",\"version\":\"v0.6.10\",\"sum\":\"h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=\",\"deps\":[{\"path\":\"github.com/BurntSushi/toml\",\"version\":\"v0.3.1\",\"sum\":\"h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\"},{\"path\":\"github.com/google/go-cmp\",\"version\":\"v0.5.4\",\"sum\":\"h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=\"},{\"path\":\"github.com/sergi/go-diff\",\"version\":\"v1.1.0\",\"sum\":\"h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\"},{\"path\":\"golang.org/x/mod\",\"version\":\"v0.4.1\",\"sum\":\"h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=\"},{\"path\":\"golang.org/x/sync\",\"version\":\"v0.0.0-20201020160332-67f06af15bc9\",\"sum\":\"h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=\"},{\"path\":\"golang.org/x/sys\",\"version\":\"v0.0.0-20210124154548-22da62e12c0c\",\"sum\":\"h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=\"},{\"path\":\"golang.org/x/tools\",\"version\":\"v0.1.1-0.20210408155258-593413344da1\",\"sum\":\"h1:B+9Jhwu5uM+kDMAkoQH6IUoIoS48VbRqwLyceNdpRK8=\"},{\"path\":\"golang.org/x/xerrors\",\"version\":\"v0.0.0-20200804184101-5ec99f83aff1\",\"sum\":\"h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=\"},{\"path\":\"honnef.co/go/tools\",\"version\":\"v0.1.3\",\"sum\":\"h1:qTakTkI6ni6LFD5sBwwsdSO+AQqbSIxOauHTTQKZ/7o=\"},{\"path\":\"mvdan.cc/gofumpt\",\"version\":\"v0.1.1\",\"sum\":\"h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=\"},{\"path\":\"mvdan.cc/xurls/v2\",\"version\":\"v2.2.0\",\"sum\":\"h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=\"}]}"}},"id":1}
===== sent =====
Content-Length: 52

{"method":"initialized","jsonrpc":"2.0","params":{}}
===== sent =====
Content-Length: 202

{"method":"workspace/didChangeWorkspaceFolders","jsonrpc":"2.0","params":{"event":{"added":[{"uri":"file:///Users/relentless-coder/Workspace","name":"/Users/relentless-coder/Workspace"}],"removed":[]}}}
===== sent =====
Content-Length: 494

{"method":"textDocument/didOpen","jsonrpc":"2.0","params":{"textDocument":{"uri":"file:///Users/relentless-coder/Workspace/go/src/github.com/relentless-coder/learn_go/fn_chain.go","version":2,"languageId":"go","text":"package main\n\nimport \"fmt\"\n\nfunc sqrRt(x int) int {\n\treturn x * x\n}\n\nfunc mulTwo(y int) int {\n\treturn y * 2\n}\n\nfunc addTwo(z int) int {\n\treturn z + 2\n}\n\nfunc main() {\n\tfmt.Println(\"vim-go\")\n\trs := sqrRt(mulTwo(addTwo(8)))\n\tfmt.Println(rs)\n}\n"}}}
===== received =====
Content-Length: 99

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":4,"message":"Loading packages..."}}
===== received =====
Content-Length: 154

{"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///Users/relentless-coder/Workspace","section":"gopls"}]},"id":1}
===== sent =====
Content-Length: 78

{"id":1,"jsonrpc":"2.0","result":[{"buildFlags":[],"hoverKind":"Structured"}]}
===== sent =====
Content-Length: 499

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package main\n\nimport \"fmt\"\n\nfunc sqrRt(x int) int {\n\treturn x * x\n}\n\nfunc mulTwo(y int) int {\n\treturn y * 2\n}\n\nfunc addTwo(z int) int {\n\treturn z + 2\n}\n\nfunc main() {\n\tfmt.Println(\"vim-go\")\n\trs := sqrRt(mulTwo(addTwo(8)))\n\tfmt.Println(rs)\n}\n"}],"textDocument":{"uri":"file:///Users/relentless-coder/Workspace/go/src/github.com/relentless-coder/learn_go/fn_chain.go","version":6}}}
===== sent =====
Content-Length: 225

{"method":"textDocument/formatting","jsonrpc":"2.0","id":2,"params":{"options":{"insertSpaces":false},"textDocument":{"uri":"file:///Users/relentless-coder/Workspace/go/src/github.com/relentless-coder/learn_go/fn_chain.go"}}}
===== sent =====
Content-Length: 313

{"method":"textDocument/codeAction","jsonrpc":"2.0","id":3,"params":{"context":{"only":["source.organizeImports"]},"range":{"end":{"character":0,"line":21},"start":{"character":0,"line":0}},"textDocument":{"uri":"file:///Users/relentless-coder/Workspace/go/src/github.com/relentless-coder/learn_go/fn_chain.go"}}}
===== sent =====
Content-Length: 499

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package main\n\nimport \"fmt\"\n\nfunc sqrRt(x int) int {\n\treturn x * x\n}\n\nfunc mulTwo(y int) int {\n\treturn y * 2\n}\n\nfunc addTwo(z int) int {\n\treturn z + 2\n}\n\nfunc main() {\n\tfmt.Println(\"vim-go\")\n\trs := sqrRt(mulTwo(addTwo(8)))\n\tfmt.Println(rs)\n}\n"}],"textDocument":{"uri":"file:///Users/relentless-coder/Workspace/go/src/github.com/relentless-coder/learn_go/fn_chain.go","version":7}}}

```

**Comment by bhcleek** [comment]
It looks like your working directory is `/Users/relentless-coder/Workspace`. Can you try changing into your `learn_go` repository to before you start vim to see if it makes a difference?

**Comment by relentless-coder** [comment]
I am starting vim from within the `learn_go` directory. my $GO_PATH is `/Users/relentless-coder/Workspace/go`

**Comment by npmaile** [comment]
I believe I'm having the same issue, and I believe it may have something to do with `GoFmt` not working properly. 
If I run `GoFmt` from within any go file regardless of location, it takes a long time and never formats the file. 

I am using neovim, and I have no plugins installed except for vim-go, and I have not configured it beyond the defaults. 

This is using vim-go v1.25 with `go version go1.16.3 darwin/amd64`

**Comment by bhcleek** [comment]
@relentless-coder My hypothesis is that `gopls` is taking a while to initialize. I've seen this happen when operating in a large Go module. I didn't notice it before, but the reason vim-go is using `/User/relentless-coder/Workspace` is it's workspace root for `gopls` is because you're working in module aware mode and have a `go.mod` file there. How large is this module?

I suspect that if you'll wait until `gopls` is fully initialized (e.g. until that first save finishes), then all future operations will be fast.

/cc @stamblerre is there some output from `gopls` that we can use to know when `gopls` has actually loaded the module? This seems like an issue with `gopls` not fulfilling any requests until that's happened; ideally it would be able to do some operations after initialization but before the module has been initially fully processed by `gopls` or provide a notification when  it's ready to handle files in a particular workspace.

**Comment by npmaile** [comment]
Subsequent writes aren't any faster. Also, it doesn't do the formatting or anything.

**Comment by bhcleek** [comment]
How large is the module?

**Comment by npmaile** [comment]
I get the same issue if I make a new go file in its own directory with nothing but the hello world that vim-go generates.

**Comment by bhcleek** [comment]
How large is the module in `/Users/relentless-coder/Workspace` ?

**Comment by stamblerre** [comment]
> /cc @stamblerre is there some output from `gopls` that we can use to know when `gopls` has actually loaded the module? This seems like an issue with `gopls` not fulfilling any requests until that's happened; ideally it would be able to do some operations after initialization but before the module has been initially fully processed by `gopls` or provide a notification when it's ready to handle files in a particular workspace.

Yes actually -- `gopls` uses [progress reports](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#progress) to report when it's ready. For example, on start up, you should see messages like:

```
[Trace - 20:26:35.498 PM] Received request 'window/workDoneProgress/create - (1)'.
Params: {"token":"5577006791947779410"}

[Trace - 20:26:35.500 PM] Received notification '$/progress'.
Params: {"token":"5577006791947779410","value":{"kind":"begin","title":"Setting up workspace","message":"Loading packages..."}}

[Trace - 20:26:37.389 PM] Received notification '$/progress'.
Params: {"token":"5577006791947779410","value":{"kind":"end","message":"Finished loading packages."}}
```

**Comment by relentless-coder** [comment]
@bhcleek `learn_go` just contains one file. I didn't initialize a module in it.

`~/Workspace` is where all my programming projects reside. `~/Workspace/go` is my GO_PATH

**Comment by relentless-coder** [comment]
> Subsequent writes aren't any faster. Also, it doesn't do the formatting or anything, so I'm not sure that's it.

Same for me. I've noticed that earlier, if I I saved the file it would format code, remove unused imports. However, now it just freezes for a while, and then returns to normal. It does save the file.

**Comment by bhcleek** [comment]
@relentless-coder according to your `go env` output your module root is `/Users/relentless-coder/Workspace`. I can't help you if you won't answer the questions I ask. One more time: how large is this module?

**Comment by relentless-coder** [comment]
I found the issue, somehow a go module was initialized inside my `~/Workspace` directory. I removed it and now the issue is fixed.

Thank you for your input, that's why I was confused why `~/Workspace` is a module root, when all my go code is within my GO_PATH.
