### ISSUE TITLE
Post-update hook fails. Vim(function):E127: Cannot redefine function go#util#env: It is in use

### ISSUE THREAD

**Issue by Racle** [fatih/vim-go#3217]
After running `:PlugUpgrade` and `:PlugUpdate`, vim-go would say that `Post-update hook for vim-go ... Vim(function):E127: Cannot redefine function go#util#env: It is in use`.

After running manually `:GoUpdateBinaries` it says
```
error detected while processing /home/<myuser>/.local/share/nvim/plugged/vim-go/autoload/go/util.vim:
line   91:
E127: Cannot redefine function go#util#env: It is in use
```
but seems to be installing go packages still.

Neovim: `NVIM v0.5.0-dev` (had single vim instance open.)
Plug config: `Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }`

After relaunching vim and running `:GoUpdateBinaries` again, it would work just fine.

Might be non-issue, but I'll report this anyway if there is something wrong.

**Comment by bhcleek** [comment]
If you can't duplicate it, I'm not sure how to troubleshoot it.

**Comment by bhcleek** [comment]
closing for lack of feedback
