### ISSUE TITLE
Sourcing job.vim takes lot of time

### ISSUE THREAD

**Issue by suhas-bn-1412** [fatih/vim-go#3228]
![image](https://user-images.githubusercontent.com/52152465/118439856-60fede00-b704-11eb-97ad-ffab10ff07af.png)

As you can see in line no 112, sourcing the file `/home/snataraj/.vim/plugged/vim-go/autoload/go/job.vim` is taking a lot of time. This happens when I try to open .go files.

**Comment by suhas-bn-1412** [comment]
When I try to open .go files through vim with vim-go plugin installed, it takes a lot of time. I looked into the start up time(using "vim <file>.go --startuptime vim.log") of vim and noticed that sourcing the job.vim is the one making it longer that usual.

**Comment by bhcleek** [comment]
Closing. Feel free to open a new issue that provides the information that the template asks for.

As-is, I have no way to duplicate this, I don't know anything about your system or your editor, and a quick good faith attempt to reproduce on my machine does not see results anywhere close to what you're reporting here.

And for what it's worth, the script you provided shows that `job.vim` is loading in less than a millisecond. I suspect this is related to a large module
