### ISSUE TITLE
Opening a .go file using vim slows down because of vim-go

### ISSUE THREAD

**Issue by suhas-bn-1412** [fatih/vim-go#3229]
### What did you do? (required: The issue will be **closed** when not provided)
I installed vim-go plugin and tried to open .go files and it takes a lot of time. Upon inspection, I noticed that sourcing some files related to vim-go plugin is consuming most of the time

![image](https://user-images.githubusercontent.com/52152465/118537347-7a3a7580-b76a-11eb-9f86-4a95eccc59e4.png)

As you can see the time difference between line 111 and 112, sourcing path.vim (or job.vim I don't exactly know how logs are printed) takes a lot of time

### What did you expect to happen?
I expected that the file would open immediately

### What happened instead?
It takes more time to open the file

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
 silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
   \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
 autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

"------------------------------------------------------------------------------
" Plug installed plugins

call plug#begin('~/.vim/plugged')

" Golang syntax highlighting, auto completions
Plug 'fatih/vim-go'

" NERDtree for file browsing
Plug 'preservim/nerdtree'

" Botton line (vim status bar)
Plug 'itchyny/lightline.vim'

" Color scheme
Plug 'gryf/wombat256grf'

call plug#end()
"------------------------------------------------------------------------------

" Turn on syntax highlighting
syntax on

" Backapce should work over everything
set backspace=indent,eol,start

" Show line numbers
set number

" tab uses this many spaces
set tabstop=8

" Status bar
set laststatus=2

" Last line
set showmode
set showcmd

" colorscheme
colorscheme wombat256grf

" Any vertical splits to happen on right
set splitright

" Any horizontal splits to happen at bottom
set splitbelow

"------------------------------------------------------------------------------
" NERDtree
nnoremap <F1> :NERDTreeToggle<CR>
nnoremap <F2> :NERDTree<CR>
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = '^'

"------------------------------------------------------------------------------
" lightline -> status bar

if !has('gui_running')
          set t_Co=256
endif

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
"------------------------------------------------------------------------------



"------------------------------------------------------------------------------
" Solve any issues caused by plugins
"
"
" Vim taking time to load
" https://stackoverflow.com/questions/14635295/vim-takes-a-very-long-time-to-start-up
set clipboard=exclude:.*

"------------------------------------------------------------------------------
```
</details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/snataraj/.cache/go-build"
GOENV="/home/snataraj/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/snataraj/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/net/wtl-netapp-2/vol/VIEW/swbuild_snap_view/vobs/fw-tools/gitrepos_data/golang_master_2/golang-1.13.7"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/net/wtl-netapp-2/vol/VIEW/swbuild_snap_view/vobs/fw-tools/gitrepos_data/golang_master_2/golang-1.13.7/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build724252137=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>
(PS: specify how to check gopls version, I'll paste the output)

**Comment by bhcleek** [comment]
you get can get the version of `gopls` with `gopls version` or by using `:GoReportGitHubIssue` in Vim and copying it from the information populated for you.

**Comment by suhas-bn-1412** [comment]
:GoReportGithubIssue won't work as I'm using vim inside ssh session. 
'gopls version' didn't work in terminal(-bash: gopls: command not found)  or  vim(E492: Not an editor command: gopls version)

**Comment by bhcleek** [comment]
`gopls` may be in your `$GOPATH/bin` or `$GOBIN` directories; it sounds like neither is in your `$PATH`, so try:
`$GOBIN/gopls version` and `$GOPATH/bin/gopls version`.

**Comment by suhas-bn-1412** [comment]
gopls version:
golang.org/x/tools/gopls v0.6.11
    golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=

**Comment by bhcleek** [comment]
The strange thing here is that job doesn't do much. You can even see in your profile that the time executing code in that file was very small; it's the total duration that took a long time.

Can you add `let g:go_debug=['shell-commands']` to your vimrc and duplicate this? I'm curious exactly which command is being executed when you see this delay.

Have you tried using `top` or other tools to see what's running on your system?

**Comment by suhas-bn-1412** [comment]
After adding  <code>let g:go_debug=['shell-commands']</code>, I see these are the shell commands that are being run
<code>vim-go: shell command: 'go' 'env' 'GOBIN'</code>

**Comment by bhcleek** [comment]
I suspect there's more than that. You can execute `:messages` to see them all.

As I mentioned before, I don't think this is vim-go that's the problem. Running using `top` to see what's taking a while may be helpful for you, too.

**Comment by suhas-bn-1412** [comment]
<code>
vim-go: shell command: 'go' 'env' 'GOBIN'
</code>
<br>
<code>
vim-go: shell command: 'go' 'env' 'GOPATH'
</code>
<br>
<code>
vim-go: job command: ['/home/snataraj/go/bin/gopls', '-remote=auto']
</code>
<br>
<code>
vim-go: shell command: '/usr/local/fw-tools/Linux/bin/go' 'env' 'GOMOD'
</code>
<br>
<code>
vim-go: shell command: '/usr/local/fw-tools/Linux/bin/go' 'env' 'GOMOD'
</code>
<br>
<code>
vim-go: initializing gopls
</code>
<br>
<code>
vim-go: initialized gopls
</code>
<br>
This is the complete output of ":messages"

**Comment by bhcleek** [comment]
Thank you

The good news is that I don't see anything unexpected here. The bad news for you is that I don't see anything that points to a problem in vim-go itself. As I mentioned previously, the original startup profile output shows that the time spent _in_ `job.vim` is minimal.

The only things I've been able to think of are to:
1. update your version of Go; your current version is three major versions behind (make sure to do `:GoUpdateBinaries` afterwards!).
2. Create a fuller profile so we can see exactly where the duration is being spent. To do this, you'd need to start Vim, but without opening a Go file until the profiling has been setup. Something like this
```
:profile start profile.log
:profile func *
:profile file *
" At this point do slow actions (e.g. open a go file).
:profile pause
:noautocmd qall!
```

**Comment by bhcleek** [comment]
closed for lack of feedback.

**Comment by keyboard-clacker** [comment]
This is happening for me as well, though I don't see anything off in this profile I don't think?

https://gist.github.com/keyboard-clacker/919ddd0a078673abcfec8480aa20c104

**Comment by vegerot** [comment]
I'm having the same issue
