### ISSUE TITLE
Vim helptags E154: Duplicate Tag after PR#319

### ISSUE THREAD

**Issue by ClaudiaJ** [fatih/vim-go#323]
Vim reports the following after PR#319:

`Vim(helptags):E154: Duplicate tag "'g:go_play_browser_..ome/claudiaj/.cache/neobundle/.neobundle/doc/vim-go.txt`

It looks like some of the documentation got duplicated in this commit, so section for Text Objects and Settings exist twice

**Comment by fatih** [comment]
Sorry for it, what a mistake from me. Just removed it with https://github.com/fatih/vim-go/commit/b23b0bf3a59a3637942174106d5c2ed856628bbf
