### ISSUE TITLE
Neovim folding in buffers disapears

### ISSUE THREAD

**Issue by ygworldr** [fatih/vim-go#3237]
### What did you do? (required: The issue will be **closed** when not provided)

Open two (or more go files) using neovim.

### What did you expect to happen?

I expected folding in all buffer.

### What happened instead?

Folding happens only on the first buffer. When I switch buffer, there is no folding on any other buffers. Switching back to the first buffer and folding has vanished.

Trying `zc` show "E490: No folding found"

![Peek 2021-05-26 09-19](https://user-images.githubusercontent.com/62601401/119627589-3e577e00-be04-11eb-96af-7e95bdfac117.gif)

#### vim-go version:

`commit 8c883d7f30c220d572177e8ff1d3945f618b492a` installed via Plug.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
"Configure vim-go
" -▼-
autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4 foldmethod=syntax foldnestmax=1
autocmd FileType go nmap <Leader>i <Plug>(go-info)
let g:go_auto_type_info = 1
let g:go_doc_popup_window = 1
let g:go_fmt_autosave = 1
let g:go_fmt_command = "gopls"
let g:go_fmt_experimental = 1  " https://github.com/fatih/vim-go/issues/502
let g:go_fmt_fail_silently = 0
let g:go_fold_enable = ['block', 'import', 'varconst', 'package_comment']
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_functions = 1
let g:go_highlight_operators = 1
let g:go_highlight_types = 1
let g:go_metalinter_autosave = 1
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck', 'revive']
" GOPLS horrors?
" https://github.com/fatih/vim-go/issues/2760
" https://github.com/josa42/coc-go/issues/76#issuecomment-659947017
let g:go_gopls_enabled = 1
let g:go_gopls_options = ['-remote=auto', '-rpc.trace']
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_referrers_mode = 'gopls'
" -▲-

```
</details>

#### Vim version (first three lines from `:version`):

`NVIM v0.5.0-dev+1328-gc40de6e5f`

#### Go version (`go version`):

`go version go1.15.12 linux/amd64`

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yann/.cache/go-build"
GOENV="/home/yann/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/yann/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/yann/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build733702523=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.11
    golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=
</pre></details>

**Comment by bhcleek** [comment]
I'm unable to duplicate the behavior you're seeing. Are you sure this has something to do with vim-go and isn't related to folding in your editor generally?

**Comment by ygworldr** [comment]
90% sure… It was working fine before I installed `vim-go`. The behaviour only appears in go files, if I try with two (or more) Python files, the behaviour is correct -- the folding stays when I switch buffers.

I could add my whole massive `init.vim` file here if that helps… ¯\\\_(ツ)\_/¯

**Comment by bhcleek** [comment]
I don't _think_ your whole `init.vim` is necessary. I would be interested in seeing the output of `:set`, though.

Do you see this same behavior on Vim and also on the most recent release of Neovim?

**Comment by ygworldr** [comment]
Here it is:

```
:set
--- Options ---
  autowriteall        lines=116           showtabline=2       spell
  columns=86          mouse=a             sidescrolloff=5     tabstop=4
  expandtab           scroll=56           signcolumn=yes      termguicolors
  foldmethod=marker   scrolloff=1         smartindent         updatetime=50
  helplang=en         shiftwidth=4        softtabstop=4       window=115
  completeopt=menu,menuone,noselect
  foldmarker=-▼-,-▲-
  runtimepath=~/.config/nvim,~/.config/nvim/plugged/vim-sensible,~/.config/nvim/plugge
d/lualine.nvim,~/.config/nvim/plugged/nerdtree,~/.config/nvim/plugged/nerdtree-git-plu
gin,~/.config/nvim/plugged/vim-easy-align,~/.config/nvim/plugged/vim-devicons,~/.confi
g/nvim/plugged/vim-toml,~/.config/nvim/plugged/vim-fugitive,~/.config/nvim/plugged/vim
-gitgutter,~/.config/nvim/plugged/file-line,~/.config/nvim/plugged/vim-delve,~/.config
/nvim/plugged/vimwiki,~/.config/nvim/plugged/nord.nvim,~/.config/nvim/plugged/SimpylFo
ld,~/.config/nvim/plugged/vimtex,~/.config/nvim/plugged/dart-vim-plugin,~/.config/nvim
/plugged/vim-asciidoctor,~/.config/nvim/plugged/vim-terraform,~/.config/nvim/plugged/n
vim-lspconfig,~/.config/nvim/plugged/completion-nvim,~/.config/nvim/plugged/nvim-trees
itter,~/.config/nvim/plugged/nvim-compe,~/.config/nvim/plugged/nvcode-color-schemes.vi
m,~/.config/nvim/plugged/popup.nvim,~/.config/nvim/plugged/plenary.nvim,~/.config/nvim
/plugged/telescope.nvim,~/.config/nvim/plugged/nvim-web-devicons,~/.config/nvim/plugge
d/nvim-bufferline.lua,~/.config/nvim/plugged/vim-go,/etc/xdg/nvim,~/.local/share/nvim/
site,~/.local/share/flatpak/exports/share/nvim/site,/var/lib/flatpak/exports/share/nvi
m/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/var/lib/snapd/desktop/nvim/sit
e,~/share/nvim/runtime,~/share/nvim/runtime/pack/dist/opt/matchit,~/lib64/nvim,/var/li
b/snapd/desktop/nvim/site/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/
after,/var/lib/flatpak/exports/share/nvim/site/after,~/.local/share/flatpak/exports/sh
are/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/
plugged/nerdtree-git-plugin/after,~/.config/nvim/plugged/vimtex/after,~/.config/nvim/p
lugged/nvim-treesitter/after,~/.config/nvim/plugged/nvim-compe/after,~/.config/nvim/af
ter
  shortmess=filnxtToOFc
  spelllang=en_gb,fr
  statusline=%!v:lua.require'lualine'.statusline()
  tabline=%!v:lua.nvim_bufferline()
  viewoptions=folds,cursor,curdir
```

I am afraid I only use Neovim… 

Thank you very much for your help. It is much appreciated.

**Comment by bhcleek** [comment]
I wonder if this has something to do with the changing `foldmethod` and an ordering of operations for when folds get applied initially, the `foldmethod` getting changed from `marker` to `syntax`, and what happens when changing tabs.

Vim-go doesn't set `foldmethod` anywhere. Do you have any `after/ftplugin/go.vim` or `after/plugin/vim-go.vim` files in any of your runtimepath? Do you have any `autocmd` commands in your vimrc or any `after` files? If so, what are those files and `autocmd` commands, respectively?

**Comment by ygworldr** [comment]
> I wonder if this has something to do with the changing foldmethod and an ordering of operations 
 for when folds get applied initially, the foldmethod getting changed from marker to syntax, and what happens when changing tabs.

I tried to remove it. No change.

> Vim-go doesn't set foldmethod anywhere. Do you have any after/ftplugin/go.vim or after/plugin/vim-go.vim files in any of your runtimepath?

Ah, yes, my apologies: 

```
 ; cat .config/nvim/ftplugin/go.vim
set noexpandtab
set tabstop=4
set shiftwidth=4
set foldmethod=syntax
set foldnestmax=1
```

> Do you have any autocmd commands in your vimrc or any after files? If so, what are those files and autocmd commands, respectively?

A few:

```
autocmd FileType go nmap <Leader>i <Plug>(go-info)
autocmd FileType go,c,cpp,python,yaml,dockerfile set nospell
```

**Comment by bhcleek** [comment]
how is that first fold happening at all? I don't see your markers in either of your tabs in the screen animation you provided. It seems like some important steps to reproduce this issue may be missing from the description and screen animation.

**Comment by ygworldr** [comment]
> how is that first fold happening at all?

Now, that is the question, isn't it? It is syntax-based and works fine in one and only one file. The next buffer I open, all folds are gone.

**Comment by bhcleek** [comment]
Try as I might, I can't duplicate what you're seeing with either Vim 8.2 or Neovim 0.4.4, but you're running a later version of Neovim.

If we're going to get to the bottom of this, then I'm going to need a more complete and explicit recipe for reproduction that starts from launching vim.

**Comment by ygworldr** [comment]
![Peek 2021-05-31 09-38](https://user-images.githubusercontent.com/62601401/120165906-f36aab80-c1f3-11eb-9999-90d4f3876606.gif)

That is the whole journey. I have attached my whole `init.vim` file with a `.log` extension… 

Again, thank you so much for doing this. Much appreciated.

[init.vim.log](https://github.com/fatih/vim-go/files/6568981/init.vim.log)

**Comment by bhcleek** [comment]
Thank you for the more complete screen animation. Unfortunately, I still can't duplicate what you're seeing, and I don't have the time (nor is the enough information here) to create a complete duplicate of your environment. You have a lot of plugins; I suggest commenting doing some spelunking and troubleshooting in your `.nvim` directory to figure out what's going on.

Here are a few tips to get you started:
1. Try to duplicate this behavior with a minimal configuration. That often means commenting out the loading of all the other plugins and any other customizations you have for go files.
2. I'm not sure how you're causing `:bn` to open a new tab, but that raised my eyebrows a bit and may provide a good starting point for trying to get to the bottom of this.
3. Can you duplicate this issue when you use only a single tab to edit the files instead of having a tab per file? Keep it simple: use `:edit` to start editing the second file in the one open tab. Does it have folds? What happens if you switch back to the first file using `:edit`?

**Comment by ygworldr** [comment]
Utterly understandable, thank you so much for the help so far. 

`:bn` does not open a new tab at all! It's a new buffer (as expected). I just have a list of buffers appearing as tabs because I am weird.

I shall try to get a minimal configuration file and see where the problem lies. I shall report here.

**Comment by ygworldr** [comment]
_I found the culprit!_ 

```
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
```

Setting the following in `~/.config/nvim/ftplugin/go.vim`:

```
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
"set foldmethod=syntax ← comment this out!
```

make the folding behave as expected!

@bhcleek Thank you so much for all your help and kind attention.
