### ISSUE TITLE
Allow adding flags to run with go test

### ISSUE THREAD

**Issue by mpldr** [fatih/vim-go#3238]
### What did you do?

I have a test-function that relies on the package import path (I know, not so great but I didn't find a way to reliably test it another way). However I can't work with any test in this package because `:GoTest` and `:GoCoverage` fail because I have no way of executing the tests with the `-trimpath` flag

### What did you expect to happen?

not applicable

### What happened instead?

not applicable

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
if deemed necessary, can be added later
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am May 16 2021 18:44:28)
Inklusive der Patches: 1-2859
Übersetzt von Arch Linux

#### Go version (`go version`):

go version go1.16.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/moritz/.cache/go-build"
GOENV="/home/moritz/.config/go/env"
GOEXE=""
GOFLAGS="-buildmode=exe"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="git.mw.local"
GOMODCACHE="/home/moritz/go/pkg/mod"
GONOPROXY="git.mw.local/*"
GONOSUMDB="git.mw.local/*"
GOOS="linux"
GOPATH="/home/moritz/go"
GOPRIVATE="git.mw.local/*"
GOPROXY="direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/moritz/Projects/glog/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3894532581=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.11
    golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_highlight_extra_types = 1
g:go_highlight_trailing_whitespace_error = 1
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_space_tab_error = 1
g:go_fmt_command = 'gopls'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_gopls_gofumpt = 1
g:go_loaded_install = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
`:GoTest` and `:GoCoverage` accept arguments that will be passed to `go test`.

**Comment by mpldr** [comment]
This does not seem to work for me:

[![asciicast](https://asciinema.org/a/axSIaBNaUYpCOO2VYI7ZfqW18.svg)](https://asciinema.org/a/axSIaBNaUYpCOO2VYI7ZfqW18)

**Comment by bhcleek** [comment]
Can you add `let g:go_debug=['shell-commands']`, try again, and then paste the output of `:messages` here?

**Comment by mpldr** [comment]
```go
vim-go: shell command: 'go' 'env' 'GOBIN'
vim-go: shell command: 'go' 'env' 'GOPATH'
vim-go: job command: ['/home/moritz/go/bin/gopls', '-remote=auto']
vim-go: shell command: '/usr/bin/go' 'env' 'GOMOD'
vim-go: shell command: '/usr/bin/go' 'env' 'GOMOD'
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: shell command: 'go' 'env' 'GOROOT'
vim-go: [test] dispatched
vim-go: job command: ['go', 'test', '-trimpath']
vim-go: [test] FAIL
vim-go: /home/moritz/Projects/glog
vim-go: --- FAIL: TestIsTerminal (0.00s)
vim-go: FAIL
vim-go: exit status 1
vim-go: FAIL        git.sr.ht/~poldi1405/glog^I0.044s
```

This is interesting, because TestIsTerminal is not the one that is supposed to fail… The expected fail is TestGetCaller

**Comment by bhcleek** [comment]
I think that shows that `-trimpath` is being passed correctly. 

`go test` isn't run in a terminal from vim-go by default; there is no tty, though you could try using terminal mode by using `let g:go_term_enabled`, but depending on what that test does, that may not be enough.

In any case, the originally reported problem here seems to be ruled out.

**Comment by mpldr** [comment]
I agree, thanks.
