### ISSUE TITLE
:GoDebugConnect can not work with remote server

### ISSUE THREAD

**Issue by JellyZhang** [fatih/vim-go#3239]
### What did you do? (required: The issue will be **closed** when not provided)

1. build a simple demo Go program and run it in my server with docker.
code: 
```
package main

import (
	"fmt"
	"gotest/hello"
	"log"
	"net/http"
)

const port = "8000"

func main() {
	http.HandleFunc("/hi", hello.Hi)
	fmt.Println("runing on port: " + port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}

-------
package hello

import (
	"fmt"
	"net/http"
)

func Hi(w http.ResponseWriter, r *http.Request) {
	a := make([]int, 0)
	a = append(a, 1)
	a = append(a, 2)
	fmt.Fprintf(w, "HostName: %v", a)
}

```
2. run on my azure server with docker: 
`sudo docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -d -p 8000 -p 5656 { my_image }`

3. get into container and start dlv server:
` dlv attach 7 -l "0.0.0.0:5656" --headless --log --log-output=rpc --api-version=2 --accept-multiclient `

4. in my mac, use pure delve to connect, success:
![image](https://user-images.githubusercontent.com/34066678/119684827-66cc9000-be77-11eb-9c61-5ffdb10c29a1.png)

5. in my mac,  restart over and use :GoDebugConnect to connect to delve server, failed.

![image](https://user-images.githubusercontent.com/34066678/119678426-143ca500-be72-11eb-9f7e-289ff886d81e.png)
![image](https://user-images.githubusercontent.com/34066678/119678578-38988180-be72-11eb-8427-75a1078b3b0b.png)

( i mask the addr but i am sure they are the same)

### What did you expect to happen?
:GoDebugConnect success to connect.
### What happened instead?
vim-go : could not start debugger: Vim(let) : connection failed

#### vim-go version: 
1.25 (I just found out my vim-go does not have :GoDebugConnect so i updated to latest)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" vim-go
let g:go_def_mapping_enabled = 0
let g:go_textobj_enabled = 0

let g:go_doc_keywordprg_enabled = 0
let g:go_fmt_command = "goimports" " 格式化將預設的 gofmt 替換
let g:go_autodetect_gopath = 1
let g:go_list_type = "quickfix"

let g:go_gopls_complete_unimported = 1

let g:go_version_warning = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_methods = 1
let g:go_highlight_generate_tags = 1

let g:godef_split=2

```
</details>

#### Vim version (first three lines from `:version`):
NVIM v0.5.0-9f704c8
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):
go1.15.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jelly/Library/Caches/go-build"
GOENV="/Users/jelly/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jelly/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jelly/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jelly/workspace/gotest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zc/mxplkrd57pv1tbqsqb2bvlh40000gn/T/go-build497995798=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.5.0
    golang.org/x/tools/gopls@v0.5.0 h1:XEmO9RylgmaXp33iGrWfCGopVYDGBmLy+KmsIsfIo8Y=
</pre></details>

**Comment by bhcleek** [comment]
The `connection refused` indicates that the issue is not with vim-go; it's making the connection to _something_ and getting refused. Might you have firewall rules that are preventing the connection?

**Comment by JellyZhang** [comment]
> The `connection refused` indicates that the issue is not with vim-go; it's making the connection to _something_ and getting refused. Might you have firewall rules that are preventing the connection?

Well, But i succeed to connect with pure delve , so I think it might not be a problem with filrewall rules or network?

**Comment by bhcleek** [comment]
Yeah, I agree that it seems like it _shouldn't_ be, but that error is pretty clear. I wonder if the most recent release of Neovim, v0.4.4 sees the same problem? What about Vim proper?

**Comment by JellyZhang** [comment]
> Yeah, I agree that it seems like it _shouldn't_ be, but that error is pretty clear. I wonder if the most recent release of Neovim, v0.4.4 sees the same problem? What about Vim proper?

i Just tried neovim 0.4.4 and vim-go commit baaede26a056a9cfbecbdaf8eaf0ff68a007c76d (in which added :GoDebugConnect), both failed. I think it might be my computer's problem, any advice on how to debug this?

**Comment by bhcleek** [comment]
Let's make sure you're running the right version of delve in vim-go. Can you verify that you only have one copy of `dlv` on your machine? If there are more than one, what are the absolute paths to them?

**Comment by JellyZhang** [comment]
> Let's make sure you're running the right version of delve in vim-go. Can you verify that you only have one copy of `dlv` on your machine? If there are more than one, what are the absolute paths to them?

i think so. i just got installed delve yesterday with `go install github.com/go-delve/delve/cmd/dlv@latest`  and the version is 
```
Delve Debugger
Version: 1.5.0
Build: $Id: ca5318932770ca063fc9885b4764c30bfaf8a199 $
```

**Comment by bhcleek** [comment]
I doubt this will solve your issue, but to be sure, can you execute `:GoUpdateBinaries dlv` and see if you can still duplicate the problem afterwards?

**Comment by bhcleek** [comment]
> I think so. i just got installed delve yesterday with go install github.com/go-delve/delve/cmd/dlv@latest and the version is


Delve is currently at v1.6.1, and 1.5.0 was released nearly a year ago, so something seems amiss.

**Comment by JellyZhang** [comment]
> > I think so. i just got installed delve yesterday with go install github.com/go-delve/delve/cmd/dlv@latest and the version is
> 
> Delve is currently at v1.6.1, and 1.5.0 was released nearly a year ago, so something seems amiss.

after i `GoUpdateBinaries dlv`, my `dlv version` become 
```
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
```
but still same error.

Also, I found that [vim-delve](https://github.com/sebdah/vim-delve) can successfully `:DlvConnect` to my server. Will this be a problem of vim-go?

**Comment by JellyZhang** [comment]
In addition, after it  says`vim-go : could not start debugger: Vim(let) : connection failed`, neovim will quickly crash and throw a `bus error`.
what hell is this `bus error`, it's my first time to see.
![image](https://user-images.githubusercontent.com/34066678/120024500-e302d700-c021-11eb-8eec-8c3c07694e54.png)

**Comment by JellyZhang** [comment]
> In addition, after it says`vim-go : could not start debugger: Vim(let) : connection failed`, neovim will quickly crash and throw a `bus error`.
> what hell is this `bus error`, it's my first time to see.
> ![image](https://user-images.githubusercontent.com/34066678/120024500-e302d700-c021-11eb-8eec-8c3c07694e54.png)

after google it, it seems it's a core dump. So Is there any difference of using `dlv` between `vim-go` and `vim-delve`?

**Comment by bhcleek** [comment]
I have no idea what that bus error is, but I can use `:GoDebugConnect` successfully. Given that you originally said that you'd just install delve last week and then `:GoUpdateBinaries dlv` updated it to something else, it seems likely that the state of your system isn't quite what you think it is. But I think I can help you figure out what's going on.

First, can you add `let g:go_debug=['shell-commands']` to your vimrc and then try debugging your application. After you get the error about not being able to connect, run `:messages` to see exactly what command vim-go used to start delve. It'll be an array of commandline arguments. Run those at the commandline to start figuring out where the problem lies.

> Is there any difference of using dlv between vim-go and vim-delve?

I'm sure there is; they're different plugins. I've never used vim-delve and don't know any of the particulars, though.
