### ISSUE TITLE
Gopls initialization error

### ISSUE THREAD

**Issue by krtbgb** [fatih/vim-go#3241]
### What did you do? (required: The issue will be **closed** when not provided)
Gopls could not be initialized when writing/quitting in vim and would hang indefinitely. After checking :messages, I could see that gopls could not be found and wasn't in my path.

### What did you expect to happen?
I expected gopls to initialize or to see an error message.
### What happened instead?
Gopls could not be initialized and was hanging indefinitely.
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
filetype plugin indent on

" colors
syntax enable
set t_Co=256
set background=dark
set colorcolumn=80
let g:molokai_original = 1
let g:rehash256 = 1
colorscheme molokai

" turn relative line numbers on
:set relativenumber
:set rnu

" build habits
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" airline
let g:airline_theme='dark'

" fzf
set rtp+=/usr/local/opt/fzf

nmap <C-f> :GFiles<CR>
nmap <C-F> :Files<CR>
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  8 2021 05:44:12)
macOS version
Included patches: 1-2029
#### Go version (`go version`):

go version go1.16.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/kbugbee/go/bin"
GOCACHE="/Users/kbugbee/Library/Caches/go-build"
GOENV="/Users/kbugbee/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kbugbee/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kbugbee/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/88/f6g5yfd51y323jv0w7m86klm0000gn/T/go-build695847927=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.11
    golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=
</pre></details>

**Comment by bhcleek** [comment]
Duplication of this issue requires that `g:go_echo_command_info` is enabled.

**Comment by paddatrapper** [comment]
I get the same error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/kyle/go/bin/gopls'
```

I seems to be ignoring the `GOPATH` and `PATH` set in the environment

<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kyle/.cache/go-build"
GOENV="/home/kyle/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kyle/projects/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kyle/projects/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/kyle/projects/flanksource/karina/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1621013113=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
@paddatrapper the problem for @krtbgb was that his environment in Vim was not what he thought it was, so `gopls` wasn't found. I suggest you run `:!go env GOPATH` and `:echo $GOPATH` from within Vim after you see the gopls initialization message.

**Comment by paddatrapper** [comment]
```
:!go env GOPATH
/home/kyle/projects/.go
:echo $GOPATH
/home/kyle/projects/.go
```

**Comment by bhcleek** [comment]
@paddatrapper please open a separate issue; I'm virtually certain that issue you're experiencing is slightly different and is likely related to your environment.

**Comment by paddatrapper** [comment]
#3242 3242
