### ISSUE TITLE
Gopls requires binary in ~/go/bin ignoring $GOPATH

### ISSUE THREAD

**Issue by paddatrapper** [fatih/vim-go#3242]
### What did you do? (required: The issue will be **closed** when not provided)
`vim test.go`

### What did you expect to happen?
`vim test.go` should initialize correctly with an alternative `$GOPATH`.

### What happened instead?
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/kyle/go/bin/gopls'
```

### Configuration (**MUST** fill this out):

All commands run within vim using `:!` 

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
execute pathogen#infect()
call pathogen#helptags()

filetype plugin indent on

let g:go_echo_command_info = 1
```
</details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)
Included patches: 1-2434
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.16 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kyle/.cache/go-build"
GOENV="/home/kyle/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kyle/projects/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kyle/projects/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1862550245=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=
</pre></details>

**Comment by bhcleek** [comment]
Can you add `let g:go_debug=['shell-commands']` to your vimrc and try again. After the failure, I'd like to know the output of `:messages`.

**Comment by bhcleek** [comment]
What do you mean by "alternative $GOPATH?"

**Comment by paddatrapper** [comment]
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>                                              
vim-go: job command: ['/home/kyle/projects/.go/bin/gopls', '-remote=auto']
vim-go: shell command: '/usr/local/go/bin/go' 'env' 'GOMOD'
vim-go: shell command: '/usr/local/go/bin/go' 'env' 'GOMOD'
vim-go: initializing gopls
vim-go: shell command: '/usr/local/go/bin/go' 'list' '-tags' '' '-f' '{{.Name}}'
vim-go: initialized gopls
FileNotFoundError: [Errno 2] No such file or directory: '/home/kyle/go/bin/gopls'
```

Sorry, that was bad wording, I mean with `$GOPATH` as `~/projects/.go` and not `~/go`

**Comment by paddatrapper** [comment]
The issue I find without having `gopls` in `~/go/bin` is that auto-completion and the like do not work. Occasionally the file will not be templated either

**Comment by bhcleek** [comment]
I'm not sure that error is coming from vim-go at all. Vim-go errors are prefixed with `vim-go: ` _and_ you can see that the path vim-go is using to start gopls is correct: `vim-go: job command: ['/home/kyle/projects/.go/bin/gopls', '-remote=auto']`.

I suspect this error is coming from a different plugin that's also trying to use `gopls`.

**Comment by paddatrapper** [comment]
For those tests, the only plugin available is vim-go. I moved .vim/bundle and recreated it with only this plugin. Will check if YouCompleteMe was disabled,as that is the only system-wide plugin that I'm not sure as disabled and get back to you

**Comment by bhcleek** [comment]
Do you have any updates @paddatrapper  ?

**Comment by paddatrapper** [comment]
Yup, it is YouCompleteMe. Apologies for the noise
