### ISSUE TITLE
Ability to add custom linters?

### ISSUE THREAD

**Issue by JohnMaguire** [fatih/vim-go#3243]
### What did you do? (required: The issue will be **closed** when not provided)

I created a custom linter / static analysis tool using this package: https://pkg.go.dev/golang.org/x/tools/go/analysis

*EDIT* - Actually, I just realized I was reading your guide while working on this. Thanks a bunch for this article: https://arslan.io/2019/06/13/using-go-analysis-to-write-a-custom-linter/

### What did you expect to happen?

I expected there to be a way to add my new linter to my vim-go configuration (probably through the GoMetaLint command) so that it would automatically run on save.

### What happened instead?

Adding my linter to `g:go_metalinter_enabled` does not seem to cause it to be run.

### Configuration (**MUST** fill this out):

```
let g:go_metalinter_autosave = 1                   
let g:go_metalinter_autosave_enabled = ['derplint']
```

#### vim-go version:

`70cd0009f89d8d4ed0e36924e5a3d58f14e88c34`

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 28 2021 06:58:52)
Included patches: 1-2891
Compiled by Arch Linux
```

#### Go version (`go version`):

`go version go1.16.4 linux/amd64`

#### gopls version

```
golang.org/x/tools/gopls v0.6.9
    golang.org/x/tools/gopls@v0.6.9 h1:LBBcE2y3Tb4bp79JVLWCQBbvYCFEs5ADGWsQDoSLk1Q=
```

**Comment by bhcleek** [comment]
Vim-go doesn't support running arbitrary linters. You can read `:help g:go_metalinter_command` and `:help g:go_metalinter_enabled` to understand more about what's supported.

**Comment by JohnMaguire** [comment]
@bhcleek Thanks for the response, do you know of any solutions for running custom Go linters in vim? I was hoping to leverage vim-go since it's an all-inclusive plugin, and already understands how to parse the output of a Go Analyzer.
