### ISSUE TITLE
Unable to browse/view vim-go help in vim8.2 but able to use various other vim-go features

### ISSUE THREAD

**Issue by bdutta** [fatih/vim-go#3246]
### What did you do? (required: The issue will be **closed** when not provided)
1. Installed vim-go plugin in vim 8.2 on Alpine Linux 3.13.5 VM running on KVM hypervisor
2. Many of vim-go features for browsing Go source code seem to be working fine i.e. I can jump to declaration, definition etc. and creating a new file gets auto-initialized with the snippet that does `fmt.Println("vim-go")` as well.
3. However browsing the help documentation for vim-go doesn't seem to work. I can however browse the standard vim documentation.
4. I can see the `vim-go.txt` tag under 'LOCAL ADDITIONS' when I enter the command `:help`. On doing `CTRL-]` on that tag, I get the error: `E149: Sorry, no help for vim-go.txt`. The vim-go.txt file is indeed there under ~/.vim/pack/plugins/start/vim-go/doc/ directory, and has requisite permissions (0644).

### What did you expect to happen?
Expected that the vim.go.txt would be loaded and rendered properly under vim help browser, and I'd be able to browse through the help document.

### What happened instead?
Got the error: `E149: Sorry, no help for vim-go.txt`

### Configuration (**MUST** fill this out):
Sorry, not clear what should be provided here. Configuration of what ?

#### vim-go version:
Sorry, not clear how to get the vim-go version

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>
version 6.0
if &cp | set nocp | endif
let s:cpo_save=&cpo
set cpo&vim
inoremap <C-U> u
map Q gq
vmap gx <Plug>NetrwBrowseXVis
nmap gx <Plug>NetrwBrowseX
vnoremap <silent> <Plug>NetrwBrowseXVis :call netrw#BrowseXVis()
nnoremap <silent> <Plug>NetrwBrowseX :call netrw#BrowseX(netrw#GX(),netrw#CheckIfRemote(netrw#GX()))
inoremap  u
let &cpo=s:cpo_save
unlet s:cpo_save
filetype plugin indent on
set autoindent
set background=dark
set backspace=indent,eol,start
set display=truncate
set fileencodings=ucs-bom,utf-8,default,latin1
set history=200
set incsearch
set langnoremap
set nolangremap
set nomodeline
set mouse=a
set nrformats=bin,hex
set ruler
set runtimepath=~/.vim,~/.vim/pack/plugins/start/vim-go,/usr/share/vim/vimfiles,/usr/share/vim/vim82,/usr/share/vim/vimfiles/after,~/.vim/after
set scrolloff=5
set showcmd
set suffixes=.bak,~,.o,.h,.info,.swp,.obj,.info,.aux,.log,.dvi,.bbl,.out,.o,.lo
set ttimeout
set ttimeoutlen=100
set wildmenu
" vim: set ft=vim :
</details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 11 2021 03:39:27)
Included patches: 1-2320
Compiled by Alpine Linux

#### Go version (`go version`):
go version go1.15.12 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bdutta/.cache/go-build"
GOENV="/home/bdutta/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bdutta/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bdutta/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build858349393=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.6.11
    golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=
</pre></details>

**Comment by bhcleek** [comment]
Execute `:helptags ALL`

**Comment by bdutta** [comment]
Perfect. That solved it. It is probably a very noobish hiccup, as I'm back to vim after a good 8-9 years and forgotten many basics. Might be a useful thing to mention under Troubleshooting/FAQ. Thanks.
