### ISSUE TITLE
i=0;i<n;i++ is wrongly highlighted as goOctalError

### ISSUE THREAD

**Issue by opennota** [fatih/vim-go#3253]
### What did you do? (required: The issue will be **closed** when not provided)

I wrote some code without (unneeded) spaces:

```
package main
func main() { for(int i=0;i<1;i++){} }
```

### What did you expect to happen?

There's no red highlighting.

### What happened instead?

![image](https://user-images.githubusercontent.com/5520115/123536686-14bcaa00-d756-11eb-972c-8d0496ae0dad.png)

#### vim-go version:

e32b1a46ad5fc1fcb6765ef6150726c0af174c68

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```
</details>

#### Vim version (first three lines from `:version`):

Vi IMproved 8.2

#### Go version (`go version`):

go version go1.16.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/gocode"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/home/xxx/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/xxx/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build826151962=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
v0.7.0
</pre></details>

**Comment by bhcleek** [comment]
Vim's syntax highlighting is based on regular expressions, and you're hitting an edge case in the highlight group for `goOctalError`, but since saving and formatting will change the formatting such that the highlight group no longer applies, I'm not too worried about this; I think we should close this as a won't fix.

**Comment by opennota** [comment]
I don't see why. It's easily fixable. You can just add `;` after `:`.

Before:

```
syn match       goOctalError        "\<-\=0[0-7oO_]*\(\([^ \t0-7oOxX_/)\]\}\:]\|[oO]\{2,\}\|__\)\S*\|_\|[oOxX]\)\>"
```

After:

```
syn match       goOctalError        "\<-\=0[0-7oO_]*\(\([^ \t0-7oOxX_/)\]\}\:;]\|[oO]\{2,\}\|__\)\S*\|_\|[oOxX]\)\>"
```

**Comment by bhcleek** [comment]
> I don't see why. It's easily fixable.

As I said before, it's because this edge case doesn't apply after formatting is applied.

Feel free to submit a PR if you want.
