### ISSUE TITLE
Error when working with fzf

### ISSUE THREAD

**Issue by ermusthofa** [fatih/vim-go#3254]
### What did you do? (required: The issue will be **closed** when not provided)

Using fzf.vim with vim-go
1. Install fzf and vim-go using vim-plug
2. Open go files and start fuzzy searching
3. After opening a file, the error happens

I have tried both `g:go_auto_sameids` setting with enable and disable, but neither solve the problem.

### What did you expect to happen?
No error
### What happened instead?
```vim
Error detected while processing function <SNR>87_handler[2]..go#tool#Info[9]..go#lsp#Info[17]..283[
47]..286:

E900: Invalid channel id
```
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set number
set rnu
set history=100
filetype plugin on
filetype indent on
set autoread
set updatetime=300
set scrolloff=10
set ruler
set backspace=eol,start,indent

set ignorecase
set smartcase
set hlsearch
set incsearch
set lazyredraw 
set magic
set showmatch 
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set ai "Auto indent
set si "Smart indent
set nowrap "Wrap lines
</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.16 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="~/Dev/go/bin"
GOCACHE="~/.cache/go-build"
GOENV="~/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="~/Dev/go/pkg/mod"
GONOPROXY="gitlab.com/project/*"
GONOSUMDB="gitlab.com/project/*"
GOOS="linux"
GOPATH="~/Dev/go"
GOPRIVATE="gitlab.com/project/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1466335158=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_highlight_function_calls = 1
g:go_fmt_autosave = 1
g:go_metalinter_deadline = '5s'
g:go_highlight_fields = 1
g:go_metalinter_autosave_enabled = ['vet', 'golint']
g:go_def_mapping_enabled = 0
g:go_highlight_functions = 1
g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
g:go_metalinter_autosave = 1
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
The version of `gopls` you're using is quite old. Can you try upgrading it using `:GoUpdateBinaries gopls` and try again?

Also, does `:messages` show any other errors that could help us understand what's going on here?

**Comment by k3rn31** [comment]
Hello, same problem here. I have to restart Vim to make it stop showing that error.
I updated the binaries and it stopped showing the error for a few minutes, then it started again.

**Comment by bhcleek** [comment]
Closing for lack of feedback. It looks like others may be encountering a similar issue. Please open a new issue and provide some details and clear replication steps so I can understand how to replicate what you're seeing.
