### ISSUE TITLE
having an issue plus a question

### ISSUE THREAD

**Issue by turco32** [fatih/vim-go#3255]
Hello,
I am new to using vim-go, when i run `GoBuild` i get a `go.mod not found` error. i did install the binaries with `:GoInstallBinaries`.
any reason this might be happening? am i just supposed to use `:make`?

2) when i make a new .go file (e.g example.go) i see boilerplate code with a print function(looks like a hello world message). how do i stop this from happening? excuse my ignorance.

vim-go version:1.25
env:debian buster 10

**Comment by bhcleek** [comment]
`:BuildGo` is not a vim-go command. Do you mean `:GoBuild`? Assuming that's what you mean, then it sounds like you may be operating in module aware mode, but don't have an ambient `go.mod` file. 

The template use can be disabled. See [`:help g:go_template_autocreate`](https://github.com/fatih/vim-go/blob/e32b1a46ad5fc1fcb6765ef6150726c0af174c68/doc/vim-go.txt#L1952-L1970).

**Comment by turco32** [comment]
thanks bchleek. I think im not compling the code correcntly. i found :make did it. im new to go so sorry for the stupid questions

as for the template :help g:go_template_autocreate didnt work, but what i ended up doing is going into the template folder and editing the "hello_world.go" and "test_hello_world.go" files as empy go files, so now when it loads its a blank file.

**Comment by bhcleek** [comment]
`:make` will work, but it's effectively the same as `:GoBuild` in most cases. If `:GoBuild` isn't working for you, then it's certainly worth figuring out why.

If `:help g:go_template_autocreate` isn't working you you, then try running `:helptags ALL` and then try `:help g:go_template_autocreate` again. Alternatively, you can read the source in the link I provided in my last comment. You're certainly free to edit the templates on your machine, but they'll be overwritten the next time you upgrade vim-go.

You can disable the use of the templates by using `let g:go_template_autocreate = 0` in your vimrc. You can can also provide a different template anywhere on your system. See the help for more info.

**Comment by turco32** [comment]
if you don't mind helping me i'd like to figure it out. So i ran :helptags ALL and vim throws this at me "E152 Cannot open /usr/share/vim/vim81/doc/tags for writing"

**Comment by bhcleek** [comment]
What is the output of `set runtimepath?` ?

**Comment by turco32** [comment]
`  runtimepath=~/.vim,~/.vim/pack/plugins/start/vim-go,/var/lib/vim/ad
dons,/usr/share/vim/vimfiles,/usr/share/vim/vim81,/usr/share/vim/vimf
iles/after,/var/lib/vim/addons/after,~/.vim/after`

**Comment by bhcleek** [comment]
Try generating just the help tags for vim-go `:helptags $HOME/.vim/pack/plugins/start/vim-go`.

The problem you're running into is that you're running vim as a user that can't modify the `/usr/share/vim/vim81/doc` directory as `helptags ALL` wants to do, so you can generate just the vim-go tags instead of trying to do all of them. Alternatively, you could probably run vim using `sudo` and then use `:helptags ALL`.
