### ISSUE TITLE
Disabling vim-go startup messages

### ISSUE THREAD

**Issue by rodneykeeling** [fatih/vim-go#3258]
### What did you do? (required: The issue will be **closed** when not provided)
Ran `nvim main.go` on the terminal

### What did you expect to happen?
`vim-go` does not produce messages on nvim startup unless there are errors/warnings
### What happened instead?
`vim-go` produces the following messages on nvim startup in sequential order (list received via `:messages`):
```
vim-go: initialized gopls
vim-go: Finished loading packages.
vim-go: Finished loading packages.
```
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>
Nothing really custom WRT vim-go, but here are my settings: https://github.com/rodneykeeling/configs/blob/master/.config/nvim/lua/r/settings.lua
</details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rodney/.cache/go-build"
GOENV="/home/rodney/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rodney/golib/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rodney/golib:/home/rodney/dev/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1742569107=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.11
</pre></details>

**Comment by bmedicke** [comment]
Did you manage to hide these messages?

**Comment by Chase-Lambert** [comment]
I'm also looking for the solution to this @rodneykeeling. Can you please share if you found one, I couldn't see it in your .dotfiles

**Comment by famiji** [comment]
So, is there any way to hide these messages？

**Comment by famiji** [comment]
> Did you manage to hide these messages?
So, is there any way to hide these messages？

**Comment by famiji** [comment]
> Did you manage to hide these messages?

So, is there any way to hide these messages？
