### ISSUE TITLE
vim-go clearing visual selections

### ISSUE THREAD

**Issue by thockin** [fatih/vim-go#3259]
### What did you do? (required: The issue will be **closed** when not provided)

Open a largish file.  Hit `V` (visual mode).  Select as block of text.  Hit `:`

About 2/3 of the time the visual block will be cleared and I have to start over.  The other 1/3 it works fine.  Disabling vim-go makes the problem go away completely.

### What did you expect to happen?

Not to clear the visual block.

### What happened instead?

I wasted my time selecting hundreds of lines of code over and over.

#### vim-go version:

1.25 (f3ebf)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set nocompatible  " Enables Vim specific features
filetype off      " Reset filetype detection

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" This is the Vundle package, which can be found on GitHub.
" For GitHub repos, you specify plugins using the
" 'user/repository' format
Plugin 'gmarik/Vundle.vim'

Plugin 'fatih/vim-go'
let g:go_fmt_command = "goimports"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_types = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_auto_sameids = 1
let g:go_fold_enable = ['block', 'import', 'varconst', 'package_comment']

call vundle#end()

filetype plugin indent on       " Re-enable filetype detection

set bg=dark                     " I like dark backgrounds
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 12 2020 10:29:41)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.16 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thockin/.cache/go-build"
GOENV="/home/thockin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/thockin/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/thockin/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/thockin/src/go/src/k8s.io/kubernetes/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3357611155=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_highlight_methods = 1
g:go_highlight_fields = 1
g:go_fold_enable = ['block', 'import', 'varconst', 'package_comment']
g:go_auto_sameids = 1
g:go_highlight_structs = 1
g:go_highlight_extra_types = 1
g:go_highlight_generate_tags = 1
g:go_loaded_gosnippets = 1
g:go_highlight_functions = 1
g:go_highlight_operators = 1
g:go_jump_to_error = 1
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_highlight_interfaces = 1
g:go_highlight_types = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by thockin** [comment]
Turning on LSP logging I see this when it happens:

When it works I see:

```
===== sent =====
Content-Length: 269

{"method":"textDocument/references","jsonrpc":"2.0","id":30,"params":{"context":{"includeDeclaration":true},"textDocument":{"uri":"file:///home/thockin/src/go/src/k8s.io/kubernetes/pkg/registry/core/service/storage/rest_test.go"},"position":{"character":2,"line":103}}}
===== received =====
Content-Length: 72

{"jsonrpc":"2.0","error":{"code":0,"message":"no object found"},"id":30}
```

What I find is that if I hit `:` before that RPC completes, it gets cleared.  If I wait until the RPC is done, it seems to work.

**Comment by bhcleek** [comment]
Thanks. I'll see if I can get this fixed next week. In the meantime, I suspect you can work around this by disabling  `g:go_auto_sameids`

**Comment by thockin** [comment]
That does seem to work around this.  I still see it when I load a new file
and very quickly do a visual block - the "startup" RPCs are still flowing
for several second and they also clear the visual.

**Comment by bhcleek** [comment]
Yeah, that makes sense. Thanks for the additional info. I'll try to make sure the fix is robust enough to handle those cases, too

**Comment by bhcleek** [comment]
You may also be able to workaround this when opening a new file and quickly selecting by disabling `g:go_diagnostics_level`

**Comment by bhcleek** [comment]
I've been digging into this trying to figure out exactly what's causing it, but so far haven't been able to find the culprit.

FWIW, I did learn that if you've gotten to the point that you've started the ex command (i.e. typed `:`), then what you last selected will still be available; `'<,'>` is the _last_ visual selected area.

**Comment by thockin** [comment]
I wish I could help - I know nothing about vim internals..

**Comment by bhcleek** [comment]
No worries, Tim. I wasn't expecting you to provide more info; I only wanted to let you and any other readers that I'm working on this.

**Comment by thockin** [comment]
Thanks.  I did try to dig in, but there's so much base comprehension
missing that it was fruitless :)

**Comment by bhcleek** [comment]
The problem seems to be that if the mode was transitioned from visual mode to ex mode, Vim doesn't preserve the visual selection highlight that was active at the time ex mode was entered when redrawing after VimL execution.

Vim always redraws after executing VimL. If ex mode is active in that case, then the visual selection is no longer highlighted upon redraw, though `'<,'>` still accurately represents the last visual selection, so your ex command will work as expected. If you're in visual mode when VimL redraws after executing VimL, the visual selection is still highlighted.

I've finally convinced myself that this is simply how Vim works, though I can't find any documentation that confirms, nor can I find any issues in the Vim repository about this behavior.

After a lot of troubleshooting, I've convinced myself that this isn't a behavior that vim-go can influence.

**Comment by thockin** [comment]
ACK.  Thanks for that. Is it worth pushing on in vim itself?

**Comment by bhcleek** [comment]
Yeah, I think so. I'll try to craft a simple VimL replication that would be useful for Braam and the other Vim devs to duplicate the problem. I'll leave this issue open until then as a reminder for myself to do that and to create the Vim issue.

**Comment by bhcleek** [comment]
I've been unable to duplicate this in a simple repro plugin, which suggests that there's something in vim-go that's triggering this behavior.

https://github.com/vim/vim/issues/8795 seems to describe this same behavior, but using `noincsearch` doesn't change the behavior for me w/ vim-go.

**Comment by bhcleek** [comment]
After rereading vim/vim#8795 and Bram's [comment](https://github.com/vim/vim/issues/8795#issuecomment-905734865) there, I don't think there's anything that vim-go can do to change this behavior (or at least the tradeoffs wouldn't be worth it).
