### ISSUE TITLE
Don't add `fixed` import name

### ISSUE THREAD

**Issue by SamuelTheJackson** [fatih/vim-go#3262]
When you import a package with the followinig name 

`github.com/test/test-package` 

the import is rewritten to 

`test_package github.com/test/test-package` 

Is it possible to turn off this behavior and don't add `test_package`, because it's not necessary to add this.

**Comment by bhcleek** [comment]
That's controlled by the imports adjuster; it'll either be `goimports` or `gopls` that adjusts imports and AFAIK, neither has a lever to pull to do that. FWIW, that the benefit of the way it's being done now is that it makes it clear to readers that the package name in the package being imported is different than the final segment of the import path.
