### ISSUE TITLE
GoDef sometimes doesn't work

### ISSUE THREAD

**Issue by wellsjo** [fatih/vim-go#3263]
### What did you do? (required: The issue will be **closed** when not provided)

1) Open vim to a *.go file, wait for `gopls` to initialize. 
2) Try to use GoDef and nothing happens

### What did you expect to happen?
To be taken to the definition
### What happened instead?
Nothing
#### vim-go version:
`32bcf75`
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
  Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
  function GoFix()
    GoImports
    GoFmt
  endfunction
  au FileType go nmap gim :call GoFix()<CR>
  au FileType go nmap gb :GoBuild<CR>
  " By default, 'gd' does go-def in the same buffer, so we disable
  " the default and make our own use go-def-tab.
  let g:go_def_mapping_enabled = 0
  au FileType go nmap <silent> gd <Plug>(go-def-tab)
  let g:go_fmt_command = "goimports"
  let g:go_fmt_autosave = 0
  let g:go_imports_autosave = 0
```
</details>

#### Vim version (first three lines from `:version`):

`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 12 2021 04:36:29)`
#### Go version (`go version`):

1.16.6
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wells/Library/Caches/go-build"
GOENV="/Users/wells/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wells/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wells/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wells/src/cryptowatch/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6x/wddz56311wb6_ks2g9_sglw00000gn/T/go-build3279710690=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
</pre></details>

**Comment by bhcleek** [comment]
I'll need more information than this to be able to duplicate the problem. Can you provide a instructions for how to duplicate the problem you're seeing?

**Comment by yanpozka** [comment]
I don't know if it's the same issue, but my `:GoDef` doesn't work, it runs for a while and then I see this message:
`vim-go: no packages returned: packages.Load error` (on red)

**Comment by wellsjo** [comment]
my issue seems to be fixed, I think `gopls` wasn't starting correctly for some reason. It works now, not sure why. closing.

**Comment by bhcleek** [comment]
@yanpozka the error usually happens when you're in a file guarded with build tags that are not satisfied by the tags you currently have configured. See `:help GoBuildTags`
