### ISSUE TITLE
Almost no Go commands available in Vim

### ISSUE THREAD

**Issue by trstringer** [fatih/vim-go#3267]
### What did you do? (required: The issue will be **closed** when not provided)

This is a fresh config for Vim, and trying to get vim-go working again from zero config.

When I have a Go file open and type `:GoDef` on a function, I get the error message:

> E492: Not an editor command: GoDef

But I can page through Go commands: `GoInstallBinaries`, `GoPath`, and `GoUpdateBinaries`.

And I can also view the help for those other commands that apparently aren't editor commands (e.g. `:h GoDef` *does* work).

I installed vim-go by doing: `git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go`. And then I ran both `:GoInstallBinaries` and `:GoUpdateBinaries`. But still this problem persists.

I also tried to run `:helptags ALL` but that didn't seem to fix anything.

### What did you expect to happen?

I expected `GoDef` to work.

### What happened instead?

I got an error message:

> E492: Not an editor command: GoDef

#### vim-go version:

Using the 1.25 tag:

```
~/.vim/pack/plugins/start/vim-go [v1.25|✔]
 $ git log -1
commit f3ebf20e2c5dd672d55af26fdde6edb41971336b (HEAD, tag: v1.25)
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Sun Apr 18 15:09:39 2021 -0700

    update CHANGELOG.md for v1.25
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" Basic Vim options
set nocompatible
set nowrap
set number
set relativenumber
set splitbelow
set splitright
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Styling
colorscheme nord
syntax on

" File browsing options
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_winsize = 25

" Mappings
inoremap jj <esc>
nnoremap <C-]> :Lexplore <CR>

" Go
let g:go_def_mapping_enabled = 0
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)
Included patches: 1-2434
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.16.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/trstringer/.cache/go-build"
GOENV="/home/trstringer/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/trstringer/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/trstringer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2111070456=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
</pre></details>

**Comment by bhcleek** [comment]
Does adding `filetype plugin indent on`  to your vimrc resolve this for you?

ref: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2655-L2661

**Comment by trstringer** [comment]
Yes, that worked! Apologies for opening this issue that was answered in the docs, I must've missed that when I was combing through it earlier!
