### ISSUE TITLE
Generic syntax

### ISSUE THREAD

**Issue by hyunsooda** [fatih/vim-go#3269]
### What did you expect to happen?
Searching related issue
### Configuration (**MUST** fill this out):
Nothing
#### vim-go version:
latest
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

8.0
#### Go version (`go version`):

1.17.1beta1
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

Is there a plan to support generic syntax? There seems no discussion about its support. The generic feature was finalized to implement and the beta version is also released.

**Comment by stamblerre** [comment]
You can begin using `gopls` with generics by following the instructions here: https://github.com/golang/tools/blob/master/gopls/doc/advanced.md#working-with-generic-code.

**Comment by hyunsooda** [comment]
Hi @stamblerre, thanks for providing good instruction.

That instruction seems to stands for building ```gotip``` to compile generic code, but go1.71beta1 does already it. Also, I failed to get installed. The author said that the build might fail, but not provided any other corresponding instruction.

**Comment by dfinkel** [comment]
I'm pretty sure that generics (type-parameters)  are not part of Go 1.17. (I'd expect them to be reasonably prominent in the release-notes: https://tip.golang.org/doc/go1.17)
My understanding is that go 1.18 will likely have generics. (which will be released around December)

**Comment by hyunsooda** [comment]
Hi @dfinkel,

Yes, but go1.71beta1 supports generic experimentally, so my question was to ask whether vim-go has a plan to support its syntax highlighting.

**Comment by bhcleek** [comment]
@hyunsooda yes, I plan to add syntax support for Go's generics syntax sometime at or near the time that generics are added to the language (tentatively scheduled for the Go 1.18 release)

**Comment by hyunsooda** [comment]
Hi @bhcleek, 

Good to know. Let me close. 
Thanks.

**Comment by Integralist** [comment]
👋🏻  `go1.18beta1` is now available and I was able to get vim-go to work by following these steps...

```bash
$ go mod init example/generics
$ go get golang.org/x/tools/gopls@master golang.org/x/tools@master
$ go install golang.org/x/tools/gopls
```

Once I opened vim up with a `main.go` containing generic code it stopped complaining about invalid syntax.
