### ISSUE TITLE
"Invalid channel id" when editing file

### ISSUE THREAD

**Issue by ribtoks** [fatih/vim-go#3270]
### What did you do? (required: The issue will be **closed** when not provided)

Updated `vim-go` to latest version and was editing files as usual. After around 5 seconds of normal editing and autocomplete, this error message starts to appear.

I cannot provide steps to reproduce because I did not do anything special.

I already tried everything I found in similar issues in this project like `:GoUpdateBinaries gopls` etc. Nothing helped.

### What did you expect to happen?

No error messages appearing

### What happened instead?

![image](https://user-images.githubusercontent.com/505555/128152163-8c9c0a8d-0338-497b-80bd-ce7702ac9437.png)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.16.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/redacted/.cache/go-build"
GOENV="/home/redacted/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/redacted/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/redacted/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/redacted/Projects/redacted/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build343282085=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_fmt_fail_silently = 1
g:go_list_type = 'quickfix'
g:go_highlight_operators = 1
g:go_highlight_function_calls = 1
g:go_highlight_fields = 1
g:go_def_mode = 'godef'
g:go_auto_sameids = 0
g:go_addtags_transform = 'camelcase'
g:go_highlight_functions = 1
g:go_test_timeout = '10s'
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_autodetect_gopath = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by ribtoks** [comment]
This stopped when I set `g:go_auto_type_info = 0` in `.vimrc`

**Comment by bhcleek** [comment]
I suspect gopls was crashing, but I can't be certain without more information about how to reproduce.
