### ISSUE TITLE
GoBuildTags not working on project with `// +build integration`

### ISSUE THREAD

**Issue by Skarlso** [fatih/vim-go#3271]
### What did you do? (required: The issue will be **closed** when not provided)

Go build tags aren't working. I'm opening this project: https://github.com/weaveworks/eksctl which has ` // +build integration` tag on integration tests. I set integration with :`GoBuildTags integration` and it still doesn't build.
By building I mean, that the file is not compiling. Not the literal building action. :)

### What did you expect to happen?

To build the integration files.

### What happened instead?

It did not.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

NeoVim 0.5.0 and vim 8.2.3100
#### Go version (`go version`):

1.16.6.
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/skarlso/Library/Caches/go-build"
GOENV="/Users/skarlso/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/skarlso/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/skarlso/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gh/m47qw8n917n9gym8n_7ttlsc0000gn/T/go-build2664396916=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

```
gopls version
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
```
</pre></details>

**Comment by bhcleek** [comment]
What command are you running? What result are you seeing?

**Comment by Skarlso** [comment]
I'm not running anything. It's not compiling the source because of the build tag.

<img width="1918" alt="Screenshot 2021-08-04 at 20 24 45" src="https://user-images.githubusercontent.com/182850/128234467-39950159-6689-4f21-99aa-270b71a141e9.png">

**Comment by bhcleek** [comment]
I strongly suspect that error is not coming from vim-go.

Please provide the additional information about your environment (e.g. the version of vim-go, relevant portions of your vimrc), and try to duplicate without other plugins loaded.

**Comment by Skarlso** [comment]
Tried that. Remove all plugins but vim-go. Vim-go is at `master`. Still, can't compile the test file.

Vimrc (not sure what's relevant config I'm not doing anything to vim-go other than enabling syntax highlighting):

```
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
...
let g:go_highlight_functions = 1
let g:go_ighlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
```

**Comment by Skarlso** [comment]
Oh and I also have this set up:

```
let g:go_build_tags = 'integration'

```

In case it needs that when vim is starting up instead of just providing it via `:GoBuildTags`.

**Comment by bhcleek** [comment]
This balloon window doesn't come from vim-go. As far as I can tell this is not a vim-go issue.

**Comment by Skarlso** [comment]
That balloon is only surfacing the error ( it's ale ), but I tried without anything and it I still wasn't able to compile this file. As in going use go to implementation or anything else. I only enabled vim-go as a plugin and uninstalled everything else.

**Comment by bhcleek** [comment]
I'm confused about the symptoms you're experiencing here that are vim-go related. The one thing you've pointed to is from ALE, not from vim-go. Vim-go doesn't continuously compile. I'm also not sure how to interpret the statement that this is from ALE but you've disabled plugins other than vim-go.

Can you please provide steps to duplicate using only vim-go?

**Comment by Skarlso** [comment]
Have vanilla vim. Install vim-go. Open eksctl repository using vim. Open an integration test file, any file. Try doing anything go related like navigating to implementation. Or opening a reference. Or trying to autocomplete something. It will error out because it doesn't see anything that is in the integration package because it can't compile it because of the missing build constraint.

**Comment by bhcleek** [comment]
You can see jumping to a definition, getting references, and compiling tests in an integration test file here:

![recording](https://user-images.githubusercontent.com/1958864/128608618-3b643081-da37-44e3-b1d6-fe9e111def0f.gif)

**Comment by Skarlso** [comment]
F*ck. :) Thanks. I don't really understand what's going on then. :(

**Comment by bhcleek** [comment]
I'm happy to help you figure it out if you want to reopen this.

Some things that would be helpful:
* what plugins do you have loaded?
* what does `set runtimepath?` output?
* what does `:GoBuildTags` output?
* what is the result of `:GoTestCompile`?
* What does `:messages` output after you've run `:GoTestCompile`?
