### ISSUE TITLE
Unable to set breakpoints during debugging when using :GoDebugConnect with dlv --headless

### ISSUE THREAD

**Issue by distek** [fatih/vim-go#3275]
I've checked just about everywhere that I can, and can't seem to find this exact problem.

### What did you do? (required: The issue will be **closed** when not provided)
Start delve headless in another terminal to allow for user input (by allowing stdin):
```
$ dlv debug --headless --listen 127.0.0.1:8181
API server listening at: 127.0.0.1:8181
```

However, in vim:
executing `:GoDebugConnect` and then, on a valid line of code, `:GoDebugBreakpoint` results in the following message:
```
vim-go: could not toggle breakpoint: input/output error
```
Using `dlv connect IP:port` this works as expected. I can set breakpoints, continue, next, etc.

### What did you expect to happen?
A breakpoint be set.

### What happened instead?
Error message:
```
vim-go: could not toggle breakpoint: input/output error
```
#### vim-go version:
master?
```
[distek] > cd ~/.local/share/nvim/site/pack/packer/start/vim-go/
[distek] > git pull
Already up to date.
[distek] > git branch
* master
[distek] >
```
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>
I am able to reproduce it with nothing but the following in my init.lua:

```lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.api.nvim_command('!git clone https://github.com/wbthomason/packer.nvim '.. install_path)
end

vim.api.nvim_exec([[
  augroup Packer
    autocmd!
    autocmd BufWritePost init.lua,conf-*.lua PackerCompile
  augroup end
]], false)

local use = require('packer').use
require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use 'fatih/vim-go'
end)
```
</details>

#### Vim version (first three lines from `:version`):

Giving you all of it as I'm assuming my LuaJIT is not important here:

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -
U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra
-pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing
-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-co
lor=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UN
IBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neov
im/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I
/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
#### Go version (`go version`):

go version go1.16.7 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/distek/.cache/go-build"
GOENV="/home/distek/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/distek/Programming/golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/distek/Programming/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/distek/Programming/golang/src/local/distek.local/debugger-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1828363591=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.1
    golang.org/x/tools/gopls@v0.7.1 h1:Mh3Z8Xcoq3Zy7ksSlwDV/nzQSbjFf06A+L+F8YHq55U=

</pre></details>

**Comment by distek** [comment]
I did some basic sleuthing but was unable to get anything of value other than the JSON sent *to* delve from vim-go:
```
{"id": 2, "method": "RPCServer.CreateBreakpoint", "params": [{"Breakpoint": {"file": "/home/distek/Programming/golang/src/local/distek.local/debugger-test/main.go", "line": 33}}]}
```

`main.go`:
```go
  1 package main
  2
  3 import (
  4     "fmt"
  5     "strings"
  6
  7     "github.com/spf13/pflag"
  8 )
  9
 10 var input string
 11
 12 func someFunc(a string) (string, int) {
 13     split := strings.Split(a, "")
 14
 15     revd := make([]string, len(split))
 16
 17     o := 0
 18     for i := len(split) - 1; i >= 0; i-- {
 19         revd[o] = split[i]
 20
 21         o++
 22     }
 23
 24     revdJoin := strings.Join(revd, "")
 25
 26     return revdJoin, len(a)
 27 }
 28
 29 func main() {
 30     pflag.StringVarP(&input, "input", "i", "", "some description")
 31     pflag.Parse()
 32
 33     res, count := someFunc(input)
 34     fmt.Println(res)
 35     fmt.Println(count)
 36 }
```

**Comment by bhcleek** [comment]
I'm not sure if it will matter, but try setting `--api-version 2`

**Comment by distek** [comment]
That was it! Thank you so much this has been driving me crazy!

Closing!
