### ISSUE TITLE
[Question] Possiblity of using subset of go binaries

### ISSUE THREAD

**Issue by Sqvid** [fatih/vim-go#3276]
### What I have tried:
Reading the FAQ and documentation.

### My question:
The following is a question about vim-go rather than a bug report:

Is it possible to use a subset of the binaries if my workflow doesn't involve the full feature set that vim-go provides? I enjoy the formatting, language server support, and tags but the plugin seems to support much more and pulls about 1.4 GB of binaries.

Apologies for not filling out all the requested information but as this is not a specific bug report it didn't seem directly relevant. Thank you for your help. If there is a more appropriate place to submit questions that don't seem to be directly covered in the FAQ/Wiki please let me know.

**Comment by bhcleek** [comment]
You could run `:GoInstallBinaries` for the binaries that you want to use. e.g. `:GoInstallBinaries gopls`, `:GoInstallBinaries revive`, etc.

**Comment by Sqvid** [comment]
Yes that works thank you!

I believe it was this line in README.md that threw me off:

> You will also need to install all the necessary binaries. vim-go makes it easy to install all of them by providing a command, >:GoInstallBinaries, which will go get all the required binaries.

I'll close the issue/question now.
