### ISSUE TITLE
Spurious Error Message When Using Neovim 0,5,x

### ISSUE THREAD

**Issue by madranet** [fatih/vim-go#3278]
### What did you do? (required: The issue will be **closed** when not provided)

invoke `nvim` as root via `sudo -e <filename>`

#### vim-go version:

latest

----

I'm using `nvim` 0,5,x...

```
$ nvim --version
NVIM v0.5.0-dev+1429-gb585f723b
Build type: Release
<snip>

$sudo -e <somefile>

vim-go requires at least Vim 8.0.1453 or Neovim 0.4.0, but you're using an older version.
Please update your Vim for the best vim-go experience.
```

Only happens when invoking `nvim` via `sudo -e`.  I don't get this error when using `sudo nvim` directly.

**Comment by bhcleek** [comment]
What does `:version` output when you open it by editing a file using `sudo -e`?

**Comment by madranet** [comment]
Whoops. I thought OSX would use a similar approach to `update-alternatives --config editor` on Linux and that I'd previously pointed it at Neovim. But apparently I was wrong on both counts. OSX doesn't have `update-alternatives` and `sudo -e` is pointing at Vim, not Neovim.

Sorry for the mix-up.

```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 14 2021 20:35:46)
Included patches: 1-503, 505-680, 682-1283, 1365
```
