### ISSUE TITLE
Out of date errors (maybe I need to restart the inferior gopls process?)

### ISSUE THREAD

**Issue by AaronM04** [fatih/vim-go#3281]
### What did you do? (required: The issue will be **closed** when not provided)

Open a go file after getting the latest changes, when I already have Go files open from this project.

### What did you expect to happen?

No incorrect errors.

### What happened instead?

Incorrect errors were seen about a function in another file not existing, when it does exist in the new changes I pulled down.

### Configuration (**MUST** fill this out):

I'm not sure what goes here.

#### vim-go version:
```
$ git log -1
commit b8a824ae865032066793fb10c1c7d8a184a3a035 (HEAD -> master, origin/master, origin/HEAD)
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Mon Aug 9 08:48:58 2021 -0700

    update CHANGELOG.md for #3274
```

####  `vimrc` you used to reproduce:
TODO

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  1 2021 08:37:51)
macOS version - x86_64
Included patches: 1-2681

#### Go version (`go version`):

go version go1.16.5 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aaron/Library/Caches/go-build"
GOENV="/Users/aaron/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/aaron/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/aaron/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/aaron/Perforce/services_mainline/code/v2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_t/kyxlt8bn3vj358j08g3frsnm0000gn/T/go-build3338006214=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_doc_popup_window = 1
g:go_gotags_bin = 'gotags'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by AaronM04** [comment]
Update: after upgrading `gopls` with this command, I still see the same behavior:
```
GO111MODULE=on go get golang.org/x/tools/gopls@latest
```

**Comment by AaronM04** [comment]
Also, the original error goes away once I open up the file the function is defined in and then go back to the original file.

It is still a problem though because in a large file it's very hard to know which file to jump to, and there could be several such files for all the visible errors.

**Comment by bhcleek** [comment]
If you're modifying your files outside of the editor and expecting the language server to know about those changes, you're likely going to have a hard time. There are a few things you could do to manage this.

The first option is to quit the editor before updating your files.

The second option is to open the changed files in the editor that were updated outside of the editor to cause the current contents of the file to be sent to the language server.

The last option is to kill the `gopls` instances so they'll be restarted and pick up the current contents of files on disk.
