### ISSUE TITLE
Integrating other language servers is difficult due to structured hover result

### ISSUE THREAD

**Issue by aeneev** [fatih/vim-go#3284]
I've had moderate success using non-gopls language server with vim-go, but am struggling with handling the structured hover responses.

[LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_hover) defines hover response as plain text or markdown, but gopls supports structured response and vim-go is making use of that when [showing info](https://github.com/fatih/vim-go/blob/c34c73a4269857e694cda38431601ab753fcbc3f/autoload/go/lsp.vim#L1148), [docs](https://github.com/fatih/vim-go/blob/c34c73a4269857e694cda38431601ab753fcbc3f/autoload/go/lsp.vim#L987), etc.

This in turn makes vim-go misbehave when another language server is used.

Are there any plans on reducing dependencies on non-standard LSP features?
It appears that [textDocument/signatureHelp](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_signatureHelp) method might be able to cover some of the features encoded in structured hover responses.

**Comment by bhcleek** [comment]
I don't plan to support every possible language server. When other language servers are desired, there are already great plugins facilitate using those with Vim, and trying to support others will inevitably result in an onslaught of issues to support various means of communication and idiosyncracies of other LSP servers. Even adding `gopls` support was met with dissent when it was originally considered.

**Comment by aeneev** [comment]
I am not at all versed in the ecosystem of LSPs and go development tooling, so forgive my ignorance.

I understand that attempting to support every LSP and every extension employed by every LSP wouldn't be feasible. But isn't there some common denominator?

I'll look into the other plugins for making use of LSPs, but as my journey with Go started with vim-go, I've got used to it and would love to be able to continue using it.

I've had success with the PR #3285, and am glad that I can make use of our LSP and vim-go by changing path to the gopls binary and command line options, and implementing fallbacks when textDocument/hover response isn't json.

**Comment by bhcleek** [comment]
If you'd like to use a different LSP implementation, I'd recommend using one of the LSP-specific plugins for Vim.
