### ISSUE TITLE
Autocomplete should search for the whole string case insensitive, instead of just the beginning on the string

### ISSUE THREAD

**Issue by trstringer** [fatih/vim-go#3287]
### What did you do? (required: The issue will be **closed** when not provided)

Used autocomplete.

### What did you expect to happen?

Autocomplete should search all symbols in the middle of the strings instead of just a leading string search.

Example:

Autocomplete shows:

```
HelloWorld
AnotherMessage
```

If I enable autocomplete, I can start typing "world" and I would expect "HelloWorld" to be in the list of autocomplete.

### What happened instead?

"HelloWorld" is not in the autocomplete list.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
filetype plugin indent on

" Basic Vim options
set nocompatible
set nowrap
set number
set relativenumber
set splitbelow
set splitright
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set wildignore+=**/site-packages/**
set wildignore+=**/vendor/**
set wildignore+=*.pyc
set wildignore+=**/bin/**
set wildignore+=**/venv/**
set wildmenu
set wildmode=longest,list,full
set foldmethod=indent
set foldlevelstart=99
set fileformat=unix

" Styling
colorscheme nord
syntax on

" File browsing options
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_winsize = 25

" Mappings
inoremap jj <esc>
nnoremap <C-]> :Files <CR>

" Go
let g:go_def_mapping_enabled = 0
let g:go_list_type_commands = {"GoReferrers": "quickfix"}
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)
Included patches: 1-2434
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.16.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/trstringer/.cache/go-build"
GOENV="/home/trstringer/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/trstringer/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/trstringer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/trstringer/dev/osm/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3254940079=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.7.0

</pre></details>

**Comment by bhcleek** [comment]
Vim-go integrates with Vim's completion API using `gopls` as the completion engine. What you're describing is more of a fuzzy search than a completion and isn't support by Vim AFAIK

**Comment by trstringer** [comment]
@bhcleek I actually did try setting `g:go_gopls_matcher` to `fuzzy`. It didn't seem to have any effect. https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1865

Was I using that setting incorrectly?

**Comment by bhcleek** [comment]
fuzzy will affect the candidates, not how Vim filters the candidates after they've been provided.
