### ISSUE TITLE
Package Imports keep getting reorganized on save

### ISSUE THREAD

**Issue by TimKotowski** [fatih/vim-go#3293]
When saving code, my import's keep getting reorganized and I don't want that, I also can't find a source to fix this? Any  clarification if there is a way to not have vim-go reorganize package imports in a file on save?

**Comment by bhcleek** [comment]
see `:help g:go_imports_autosave`

**Comment by TimKotowski** [comment]
I have already been on there, and I have yet to read a way to bypass the reorganization of imports. I still want it to auto import on save, but rather not have it reorganize my imports in a different order then how i want it to organized.

**Comment by bhcleek** [comment]
The two functions, adjusting and organizing imports, are inseparable.

**Comment by kargirwar** [comment]
I am also facing same issue. In fact vim-go is sometimes removing the packages that are required
for compiling. Very annoying. However I get :
Sorry, no help for g:go_imports_autosave

Am I Missing something?

**Comment by bhcleek** [comment]
@kargirwar I've seen `gopls` sometimes mess those up. I'm not exactly sure why, and the particulars would depend on your workflow. What you're describing sounds like a different issue to what @TimKotowski is dealign with. If you want help with your issue, please open a new issue.

If you're not seeing the help, then you probably need to run `:helptags ALL`. You might consider reading `:help helptags`.
