### ISSUE TITLE
GoDiagnostics all files in a dir recursive?

### ISSUE THREAD

**Issue by zdmgmail** [fatih/vim-go#3294]
Could you support use GoDiagnostics for all files in a dir recursive? 

now seems still need `gopls check **/*.go` in command line 

I know it has [packages] arg but not recursive

**Comment by bhcleek** [comment]
packages can be recursive: use the `/...` suffix.

**Comment by zdmgmail** [comment]
@bhcleek 

I try `GoDiagnostics a/b/c` get error, but `GoDiagnostics a/b/c/...`  vim-go: [diagnostics] PASS  ?

**Comment by bhcleek** [comment]
My apologies; I was mistaken. `:GoDiagnostics` doesn't support the `...` syntax, though it probably could be made to pretty easily by extending the check for the package name match: https://github.com/fatih/vim-go/blob/b8a824ae865032066793fb10c1c7d8a184a3a035/autoload/go/lsp.vim#L1381
