### ISSUE TITLE
Use "Keyword" with goPredefinedIdentifiers

### ISSUE THREAD

**Issue by 89z** [fatih/vim-go#3295]
Currently `nil` and `iota` have the same color as boolean:

https://github.com/fatih/vim-go/blob/abe94c3fcf681fde772f2906fbbdfecf5afda7c8/syntax/go.vim#L53-L57

I think it looks better as `Keyword`, example here:

https://github.com/google/vim-ft-go/blob/7b7e5954/syntax/go.vim#L89-L92

would you be willing to change that?

**Comment by bhcleek** [comment]
It's not a `Keyword` highlight, because `iota` and `nil` are not keywords 😁 

If you'd like to use a different highlight for it, you can do that in your own configuration easily enough. See https://github.com/fatih/vim-go/blob/abe94c3fcf681fde772f2906fbbdfecf5afda7c8/doc/vim-go.txt#L2808-L2818.

**Comment by 89z** [comment]
So like this?

~~~vim
hi def link     goPredefinedIdentifiers Keyword
~~~

**Comment by bhcleek** [comment]
Without the `def`: `hi link goPredefinedIdentifiers Keyword`.

**Comment by 89z** [comment]
Does that work in general, because im trying the reverse with `hi link goConstants Boolean`, and its not working. Does it require a plugin or something?

**Comment by bhcleek** [comment]
It works in general. See `:help highlight-default` and then notice how all the highlighting in vim-go uses the `default` option so that you users can customize it when they prefer something other than  the choices made in vim-go

`goConstants` isn't a highlight group in vim-go. I think you're looking for `goConst`.

**Comment by 89z** [comment]
I think the command is not working, because I am using a colorscheme:

https://github.com/NLKNguyen/papercolor-theme

If I disable the colorscheme, the command works. Hmm

**Comment by 89z** [comment]
arg, I forgot that I dont like this package, as you cant use just the syntax
