### ISSUE TITLE
support go_jump_to_quickfix

### ISSUE THREAD

**Issue by zdmgmail** [fatih/vim-go#3302]
for each command, I always want not go to first error and  focus quickfix,

`let g:go_jump_to_error          = 0` can work half , and 

could you add a setting `go_jump_to_quickfix` support go to quickfix?

**Comment by bhcleek** [comment]
I don't understand how `g:go_jump_to_error` is working for you to not jump to an error when you're using commands. Can you elaborate?

I haven't done exactly what you want to do to jump to the quickfix window when it's opened; that's really an exercise for you to figure out. You should be able to do it by executing a function when the `qf` filetype is set (e.g. `autocmd FileType qf`), but exactly what the function should do isn't something I know off the top of my head. The easiest thing would be to iterate through the buffers using `bufgetinfo` and then use `win_gotoid` to set current window to the quickfix window.

**Comment by zdmgmail** [comment]
@bhcleek `g:go_jump_to_error` just same as you said , `let g:go_jump_to_error          = 0` and appending `!`, 

and ok I will try to figure out about quickfix
