### ISSUE TITLE
syntax: invalid highlighting of methods without receiver

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#3303]
### What did you do? (required: The issue will be **closed** when not provided)

Write methods with and without receiver:
```go
func (t *T) Method1() {}
func (*T) Method2() {}
```

### What did you expect to happen?

Both methods should have same syntax highlighing.

### What happened instead?

Method name with receiver highlighted as `goFunction` and receiver type highlighted as `goReceiverType`.
Method name without receiver highlighted as `goFunctionCall` and receiver type is not highlighted at all.
![image](https://user-images.githubusercontent.com/1354301/137623286-355201bb-f3e9-45e7-ac59-e82bfe016633.png)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
let g:go_metalinter_command = 'golangci-lint'
let g:go_fmt_fail_silently = 1
let g:go_gopls_gofumpt = v:true
let g:go_gopls_local = {}
autocmd FileType go call s:setlocal()
let g:go_doc_keywordprg_enabled = 0
let g:go_template_use_pkg = 1
let g:go_list_type = 'quickfix'
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_parameters = 0
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 0
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 0
let g:go_highlight_variable_assignments = 0
let g:go_build_tags = 'integration'
let g:go_gopls_matcher = 'caseSensitive'
let g:go_gopls_deep_completion = 0
let g:go_gopls_temp_modfile = 1
let g:go_gopls_use_placeholders = 0
autocmd FileType go nmap <buffer> <nowait> <Leader>r     <Plug>(go-run)
autocmd FileType go nmap <buffer> <nowait> <Leader>b     <Plug>(go-build)
autocmd FileType go nmap <buffer> <nowait> <Leader>t     <Plug>(go-test)
autocmd FileType go nmap <buffer> <nowait> <Leader>T     <Plug>(go-test-func)
autocmd FileType go nmap <buffer> <nowait> <Leader>c     <Plug>(go-coverage-toggle)
autocmd FileType go nmap <buffer> <nowait> <Leader>gd    <Plug>(go-def-tab)
autocmd FileType go nmap <buffer> <nowait> <Leader>gb    <Plug>(go-doc-browser)
autocmd FileType go nmap <buffer> <nowait> <Leader>s     <Plug>(go-implements)
autocmd FileType go nmap <buffer> <nowait> <Leader>i     <Plug>(go-info)
autocmd FileType go nmap <buffer> <nowait> <Leader>e     <Plug>(go-rename)
" Try to use <Cmd>GoIfErr<CR> after upgrading to 8.2.1978.
autocmd FileType go iabbr <buffer> errn                  <C-R>=<SID>goiferr()<CR>

function! s:goiferr()
    call go#iferr#Generate()
    return "\<Esc>O"
endfunction

function! s:setlocal()
    try
	let l:olddir = chdir(expand('%:p:h'))
	let l:dir = trim(system('go list -m -f {{.Dir}}'))
	if !has_key(g:go_gopls_local, l:dir)
	    let g:go_gopls_local[l:dir] = trim(system('go list -m'))
	endif
    finally
	call chdir(l:olddir)
    endtry
endfunction
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, собрано Oct 11 2021 22:36:01)
Заплатки: 1-814
С изменениями, внесёнными Gentoo-8.2.0814-r100

#### Go version (`go version`):

go version go1.17.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/powerman/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/powerman/proj/go/go-monolith-example/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1077099845=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.2
    golang.org/x/tools/gopls@v0.7.2 h1:kRKKdvA8GOzra8rhSFDClOR7hV/x8v0J0Vm4C/gWq8s=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 1
g:go_list_type = 'quickfix'
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_gopls_matcher = 'caseSensitive'
g:go_highlight_function_calls = 1
g:go_highlight_function_parameters = 0
g:go_highlight_fields = 0
g:go_highlight_generate_tags = 1
g:go_gopls_deep_completion = 0
g:go_highlight_variable_declarations = 0
g:go_highlight_string_spellcheck = 1
g:go_loaded_gosnippets = 1
g:go_gotags_bin = 'gotags'
g:go_metalinter_command = 'golangci-lint'
g:go_doc_keywordprg_enabled = 0
g:go_highlight_variable_assignments = 0
g:go_highlight_format_strings = 1
g:go_gopls_local = {'/home/powerman/proj/go/go-monolith-example': 'github.com/powerman/go-monolith-example'}
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_functions = 1
g:go_template_use_pkg = 1
g:go_gopls_use_placeholders = 0
g:go_highlight_types = 1
g:go_jump_to_error = 1
g:go_gopls_gofumpt = v:true
g:go_build_tags = 'integration'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_gopls_temp_modfile = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:OFF
</pre></details>

**Comment by powerman** [comment]
@bhcleek After updating I get this error on running `vi file.go`:
```
Error detected while processing /home/powerman/proj/vim/dotvim/bundle/go/ftplugin/go/commands.vim:
line  121:
E176: Invalid number of arguments
```

**Comment by bhcleek** [comment]
I accidentally pushed changes that shouldn't have been included. Try updating again; it should be fine now.

**Comment by bhcleek** [comment]
Are you seeing it incorrect in the same way or are you seeing a new problem now?

**Comment by powerman** [comment]
It's a new problem, take a look:
![image](https://user-images.githubusercontent.com/1354301/137638917-2da0e769-fbf8-4d06-b0f1-04d4af5eff5b.png)

**Comment by powerman** [comment]
To be precise, now:
1. Receiver variable is incorrectly highlighted using `goReceiverType` instead of `goReceiverVar`.
2. Star symbol is incorrectly highlighted using `goReceiver` instead of `goPointerOperator`.

**Comment by bhcleek** [comment]
Thank you.

I've reverted my original changes for now until I can find a proper fix for this, though I'm not sure it will actually be possible to fix. This may be a deficiency we have to accept.

I'll mess with the regular expressions and syntax matches and will submit a new PR if I find a way to fix this properly.

**Comment by powerman** [comment]
Thanks, latest fix works for me.
