### ISSUE TITLE
fzf does not wrap in GoDecls

### ISSUE THREAD

**Issue by co60ca** [fatih/vim-go#3307]
### What did you do? (required: The issue will be **closed** when not provided)

1. Opened a .go file
2. Used GoDecls to view the functions

(Images below)

### What did you expect to happen?

GoDecls would use fzf with a wrap to show long function lines.

### What happened instead?

fzf shows the long function lines truncated.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" Go - required for vim-go
filetype plugin indent on

" Go syntax highlighting
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1

" Auto formatting and importing
let g:go_fmt_autosave = 1
let g:go_fmt_command = "goimports"

" Status line types/signatures
let g:go_auto_type_info = 1

" Go Autocomplete
autocmd filetype go set listchars=tab:\ \ 
"                                     ctrl+space
autocmd filetype go inoremap <buffer> <C-@> <C-x><C-o>
autocmd filetype go set completeopt=menu,preview
autocmd filetype go set et!

" Cheatsheet

autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
let g:go_auto_type_info = 1
let g:go_auto_sameids = 

let g:go_fmt_command="gopls"
let g:go_gopls_gofumpt=1

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 30 2021 06:51:40)
macOS version
Included patches: 1-2029

#### Go version (`go version`):

go version go1.16 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/<user>/Library/Caches/go-build"
GOENV="/Users/<user>/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/<user>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/<user>/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_w/6ypmkk3s1cg6pq327fzsk5ww0000gn/T/go-build3861429138=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.2
    golang.org/x/tools/gopls@v0.7.2 h1:kRKKdvA8GOzra8rhSFDClOR7hV/x8v0J0Vm4C/gWq8s=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_highlight_operators = 1
g:go_highlight_extra_types = 1
g:go_highlight_function_calls = 1
g:go_fmt_autosave = 1
g:go_highlight_fields = 1
g:go_auto_sameids = 1
g:go_highlight_functions = 1
g:go_fmt_command = 'gopls'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_gopls_gofumpt = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

I searched the issues/code for anything with fzf/GoDecls/wrapping and it doesn't seem like people have cared about this issue, or it doesn't occur for them.

fzf has a preview-window setting that allows for wrapping. I'm unsure if in the past this was set to wrap by default but in my version it is not set.

```bash
fzf --version
0.27.3 (brew)
```

I'd suggest just setting this to wrap for everyone:

```diff
diff --git a/autoload/fzf/decls.vim b/autoload/fzf/decls.vim
index 89647450..6182e0ee 100644
--- a/autoload/fzf/decls.vim
+++ b/autoload/fzf/decls.vim
@@ -143,7 +143,7 @@ function! fzf#decls#cmd(...) abort
         \)
   call fzf#run(fzf#wrap('GoDecls', {
         \ 'source': call('<sid>source', a:000),
-        \ 'options': printf('-n 1 --with-nth 1,2 --delimiter=$''\t'' --preview "echo {3}" --ansi --prompt "GoDecls> " --expect=ctrl-t,ctrl-v,ctrl-x%s', colors),
+        \ 'options': printf('-n 1 --with-nth 1,2 --delimiter=$''\t'' --preview "echo {3}" --preview-window "wrap" --ansi --prompt "GoDecls> " --expec
t=ctrl-t,ctrl-v,ctrl-x%s', colors),
         \ 'sink*': function('s:sink')
         \ }))
 endfunction
 ```
 
 But I'm unsure if this will cause issue with people with lower versions of fzf. It may also be good to introduce a parameter, but I don't know anything about vim script or how that would work. I don't expect this to be an fzf or fzf-vim issue because they will say they have a parameter for it which vim-go just doesn't set.
 
 ### Screenshots:
#### Without change:
 ![Screen Shot 2021-10-18 at 10 41 11 AM](https://user-images.githubusercontent.com/6857411/137753936-995595fd-6a6f-485a-ac47-ff088e68eca2.png)
 #### With change:
 ![Screen Shot 2021-10-18 at 10 40 11 AM](https://user-images.githubusercontent.com/6857411/137753933-1b81a9d8-371c-4160-848e-01ded224071c.png)

**Comment by bhcleek** [comment]
Feel free to submit a PR for this change; I'll gladly review it.
