### ISSUE TITLE
E900: Invalid channel id - gopls crash when using vim-fugitive diff

### ISSUE THREAD

**Issue by kerma** [fatih/vim-go#3313]
Using [fugitive's](https://github.com/tpope/vim-fugitive) :Gdiffsplit crashes gopls.

In order to reproduce:
* open vim with vim-fugitive and vim-go plugins
* open file with a git version history
* run :Gvdiffsplit or :Gdiffsplit
* Navigate to a function and run :GoDef
* The following error is displayed:

```
Error detected while processing function go#def#Jump[75]..go#lsp#Definition[7]..281[43]..284:
line   11:
E900: Invalid channel id
```

Debug log has:
```
===== sent =====
Content-Length: 248
{"method": "textDocument/definition", "jsonrpc": "2.0", "id": 596, "params": {"textDocument": 
   {"uri": "fugitive%3A///Users/user/src/mm/ems/.git//0/pkg/domain/treasury/provider.go"}, 
   "position": {"character": 18, "line": 0}}}
===== stderr =====
gopls: remote disconnected: failed reading header line: EOF
```

gopls log shows a panic:
```
panic: parse "fugitive%3A///Users/user/src/mm/ems/.git//0/pkg/domain/treasury/provider.go": 
invalid URI for request
```

### What did you expect to happen?
No error message.

I'm a bit torn whether it's a bug in gopls or in vim-go. Gopls should handle the incoming uri's better, and not crash. However, vim-go could be smarter about handling those crashes or have a way to disable sending strangely named things to gopls in the first place. 

Or maybe I'm just missing proper configuration to disable gopls actions with certain types of files/buffers?

EDIT:
Current gopls implementation expects URL's to be in the correct format:
* https://github.com/golang/tools/blob/4ea6123e078542fd57c72b5f527b5705b39c33f4/internal/span/uri.go#L32
* https://github.com/golang/tools/blob/4ea6123e078542fd57c72b5f527b5705b39c33f4/internal/lsp/definition.go#L16

Similar issue from it's repo which is actually not fixed: https://github.com/golang/go/issues/40272

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
call plug#begin('~/.config/nvim/plugins')
  Plug 'fatih/vim-go'
  Plug 'tpope/vim-fugitive'
call plug#end()

let g:go_debug = ['lsp'] 
let g:go_auto_type_info = 1
let g:go_def_mode='gopls'
let g:go_doc_popup_window = 1
let g:go_fmt_autosave = 1
let g:go_fmt_command = "goimports"
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_info_mode='gopls'
```
</details>

#### Vim version (first three lines from `:version`):
NVIM v0.5.1

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/pkg/mod"
GOOS="darwin"
GOPATH="/Users/user"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.6/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pd/zlm4qxk13jj3rd4809mg3sr00000gn/T/go-build1184455591=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output: </summary><br><pre>
golang.org/x/tools/gopls v0.7.1
    golang.org/x/tools/gopls@(devel)

</pre></details>

**Comment by bhcleek** [comment]
This seems to have been resolved by `gopls`.
