### ISSUE TITLE
How can I configure vim-go to stop automatically opening the location list when there is a code issue (error, linting, etc.)?

### ISSUE THREAD

**Issue by trstringer** [fatih/vim-go#3324]
### What did you do? (required: The issue will be **closed** when not provided)

I had an error in my Go code.

### What did you expect to happen?

I expected that I would have to manually open the location list.

### What happened instead?

vim-go automatically opened the location list for me. I was reading through the help doc but I don't see a way to specify to turn off auto open on the location list when vim-go finds issues (errors or linting). I see `g:go_list_autoclose` but I don't see an option to disable auto open.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
filetype plugin indent on

" Basic Vim options
set nocompatible
set nowrap
set number
set relativenumber
set splitbelow
set splitright
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set wildignore+=**/site-packages/**
set wildignore+=**/vendor/**
set wildignore+=*.pyc
set wildignore+=**/bin/**
set wildignore+=**/venv/**
set wildignore+=*.swp
set wildmenu
set wildmode=longest,list,full
set foldmethod=indent
set foldlevelstart=99
set fileformat=unix

" Mappings
inoremap jj <esc>
nnoremap <C-]> :Files <CR>

" Go
let g:go_def_mapping_enabled = 0
let g:go_list_type_commands = {"GoReferrers": "quickfix"}
let g:go_gopls_matcher = "fuzzy"
let g:go_list_autoclose = 1
let g:go_list_height = 0
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)
Included patches: 1-2434
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.16.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/trstringer/.cache/go-build"
GOENV="/home/trstringer/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/trstringer/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/trstringer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3498974548=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.0
</pre></details>

**Comment by bhcleek** [comment]
I would need more information to know for sure, but I suspect you had a syntax error and that the location list popped up when you saved. If that's the case and you don't want the location list to open, then you'll need to turn off formatting on save. See `:help g:go_fmt_autosave` and `:help g:go_imports_autosave`.

**Comment by trstringer** [comment]
Yes! Setting `g:go_fmt_autosave` to 0 seems to have worked! Thank you!

**Comment by trstringer** [comment]
Ah I just realized, now I don't get auto formatting. Is there no way to keep auto formatting on but not open the location list? Thanks in advance!

**Comment by bhcleek** [comment]
No, there's no way to format on save and not open the error list when there are errors.

**Comment by trstringer** [comment]
Ok great thanks for the info and the help!
