### ISSUE TITLE
GoInstallBinaries and GoUpdateBinaries now fails on Go 1.14

### ISSUE THREAD

**Issue by chris3torek** [fatih/vim-go#3325]
Relates to #3316 - basically, the change there was a little over-eager.

### What did you do?

With Go version 1.14 installed, and out of date versions of gopls and other software installed, ran:

    :GoInstallBinaries

and:

    :GoUpdateBinaries

Note: these need to be run from within a Go source project that has a `go.mod` file, and you have to have the rather old verison of Go installed.  It's a pain to reproduce unless you have an old system to work on/with.

### What did you expect to happen?

Installation and/or update of binaries.

### What happened instead?

Lots of errors, nothing installed/updated; here's a sample error after turning on the debug:

```
vim-go: Updating goimports. Reinstalling golang.org/x/tools/cmd/goimports@master to folder /home/torek/go/bin/vim-go: shell command: '/usr/local/bin/go' 'install' '-v' 'golang.org/x/tools/cmd/goimports@master'
vim-go: Error installing golang.org/x/tools/cmd/goimports@master: can't load package: package golang.org/x/tools/cmd/goimports@master: can only use path@version syntax with 'go get'
```

#### vim-go version:
Not sure what's desired here; this is the `git tag` from `master`:

`v1.25-135-g96b74acc`

####  `vimrc` you used to reproduce:
Nothing special needed here.  It's just an annoyance with Go 1.14.

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  8 2019 16:12:12)
Included patches: 1-2372
Compiled by torek@elf.torek.net
```

#### Go version (`go version`):
go version go1.14.4 freebsd/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/torek/.cache/go-build"
GOENV="/home/torek/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/home/torek/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build125483124=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version

Note: this is after I updated it manually.  (It's not really relevant since we're trying to get vim-go to update it in the first place, but the template demands it, so here it is.)

<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.7.3 h1:Lru57ht8vtDMouRskFC085VAjBAZRAISd/lwvwOOV0Q=
</pre></details>

The problem is simple enough: this old version of Go doesn't like `go install ...@latest`; you have to use `go get -u ...@latest` instead.  The horrible hack below suffices to get past the issue (although at that point several modules fail to install because they require Go 1.15 or 1.16, but that's another problem entirely).

I'm no vim programmer so I didn't attempt to run `go version` and check the Go version here, but that's the obvious strategy.  The patch below is obviously inadequate, but it worked for this particular setup.

I did not test Go 1.15, so I'm not positive that `go install -v` works there; Go 1.17 seems to be the point at which we're all supposed to switch to `go install` for real.

```
commit 154eae7a796d6c0bb25fb9651caed41aa77dbea6 (HEAD -> go1.14)
Author: Chris Torek <chris.torek@gmail.com>
Date:   Mon Nov 15 15:05:51 2021 -0800

    Go binary installer: hack for Go 1.14
    
    Use "go get -u" instead of "go install -v" on Go 1.14.
    
    Note: this doesn't check the Go version, it just assumes 1.14.

diff --git a/plugin/go.vim b/plugin/go.vim
index 660f34be..72ff77e7 100644
--- a/plugin/go.vim
+++ b/plugin/go.vim
@@ -108,7 +108,9 @@ function! s:GoInstallBinaries(updateBinaries, ...)
     set noshellslash
   endif
 
-  let l:get_base_cmd = ['go', 'install', '-v']
+  " let l:get_base_cmd = ['go', 'install', '-v']
+  " for Go 1.14, we need "go get -u" here, for 1.15+ use go install
+  let l:get_base_cmd = ['go', 'get', '-u']
 
   " Filter packages from arguments (if any).
   let l:packages = {}
```

**Comment by bhcleek** [comment]
Vim-go is tested against the last two releases of Go (currently that's Go 1.17 and Go 1.16).  Go itself only supports the last two releases for security fixes: https://github.com/golang/go/security/policy.

**Comment by zzantares** [comment]
@bhcleek are there any alternatives for the ones trapped in older versions?

**Comment by chris3torek** [comment]
@zzantares I don't think there's much. After I applied the change here, I ran into several more stumbling blocks, and eventually gave up on trying to support the older system (I managed to upgrade its Go version to 1.17, with only one stumbling block _there_ instead). I find this rather disappointing though: with two Go releases a year, "2 versions" of support is just a year, and with Go acquiring modules way back in Go 1.13, it should now be possible to do a much better job.

(But I'm not getting paid for this, so.... 😺)

**Comment by bhcleek** [comment]
I see a couple of options for you.

The obvious one is to upgrade Go on your machine. Given how little the language itself changes and the [Go compatibility promise](https://go.dev/doc/go1compat), there should be little risk in that. I'm curious why there seems to be reluctance to upgrade Go.

Another alternative that would likely solve the particular issue you're dealing with is to use the version of vim-go before the change to use `go install`. The [change to use `go install`](https://github.com/fatih/vim-go/commit/359230b942b3aba79d011aa446bfcf70c12bc217#diff-5e689e2b01672bf33996e75d5e372ff60c536ce1599a1458e867cd8f4bef5160) was fairly recent. You could probably use [its parent](https://github.com/fatih/vim-go/commit/2831f4872431685d28fbe3e567cd539a455fe750) easily enough.

A third option is to manually install the tools that vim-go relies on.

Fourth, you could run vim-go in a docker container with a volume mounted from your host system and use it to install the tools using `:GoInstallBinaries`.

I'm sure there are other variations of those options that could work, too.

**Comment by zzantares** [comment]
> I'm curious why there seems to be reluctance to upgrade Go.

Oh no reluctance at all, that would be preferable IMO, but I'm not the one that manages the Go installation at my company, and I guess in order to upgrade versions several teams would need to be on board, it will happen eventually but I can't wait for that.

Thanks for the options presented, I too was thinking something along the lines of just seeing what tools vim-go relies on and install them manually, will try it. Thank you!
