### ISSUE TITLE
Unable to find references from vendored packages

### ISSUE THREAD

**Issue by sozoalvin** [fatih/vim-go#3326]
### What did you do? (required: The issue will be **closed** when not provided)

Been using vim-go fairly well for the past 2 months and just yesterday; i found out that vim-go has some trouble helping locating references

Let me try to elaborate as much as possible as I think there's a myriad list of possible problems. 

I have a fairly big repo and I can find an implemented interface that's in the 'vendored' folder without any problems. The problem comes when trying to find references to it. 

I have a couple of ways to find references and I've tried these methods: 
- Coc-references 
- :Go Implements

Both of these methods **do not** show the references. Just to be sure; I thought we could isolate it to be a **gopls** issue. However, VScode that uses the same gopls finds the references easily. 

Not just that, I looked up another repo that has exactly the same type of code structure and utilises the same 'vendored' package, my neovim/vim-go setup is able to find the references. 

If that's not weird enough; I tried using another vim plugin for golang (i dont think i need to explicitly mention the name) and it finds the references just fine.

I do not know how vim-go works under the hood but I think this is something that may be worth investigating. I am not too sure if you understood what I'm trying to convey completely but if you think there is a bug worthy to be crushed, please let me know if there are any logs somewhere that I can help provide you with. Of course, if the explanation is not clear, I will be happy to reiterate them!

### What did you expect to happen?
References FROM vendored interfaces to appear when using :GoImplements/ coc-references

### What happened instead?
Only references from the vendored package appeared instead without any references from the main project in the internal folder etc. 

#### vim-go version:
v1.25 is latest on release page.

####  `vimrc` you used to reproduce:
(do you need vimrc for this since the issue is quite erratic?)

#### Vim version (first three lines from `:version`):
vim 8.1

#### Go version (`go version`):
Go 1.16

#### Go environment
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user1/Library/Caches/go-build"
GOENV="/Users/user1Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user1/go/pkg/mod"
GONOPROXY="github.com/xternallink"
GONOSUMDB="github.com/xternalink"
GOOS="darwin"
GOPATH="/Users/user1/go"
GOPRIVATE="github.com/xternallink"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user1/go/src/github.com/xternal/xternal-repo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rt/tk2y999j06x9j2l
kfbg4gt6ddh2_zt/T/go-build3630646567=/tmp/go-build -gno-record-gcc-switches -fno-common"

#### gopls version
gopls/v0.7.3

**Comment by bhcleek** [comment]
In a large repository, it can take `gopls` a little bit of time to get everything loaded up. Once it's all loaded, I haven't been able to duplicate the problem you're describing. However, if you could duplicate this with `let g:go_debug=['lsp']` and provide me with the output from the `__GOLSP_LOG__` window, we may be able to discover the exact nature of the issue you're seeing.

The output of `:messages` after a failure may also be useful.

I won't be able to help you with the question about coc; that's a separate concern with that plugin.

**Comment by bhcleek** [comment]
closing for lack of feedback
