### ISSUE TITLE
I have set neovim to turn on automatic term insertion, but when I GoRun it did not wait for input

### ISSUE THREAD

**Issue by Ruixi-rebirth** [fatih/vim-go#3327]
I have set neovim to turn on automatic term insertion, but when I GoRun it did not wait for input
![image](https://user-images.githubusercontent.com/75824585/140891888-e6656afb-f31f-4e3b-bb80-756b5c780441.png)
![image](https://user-images.githubusercontent.com/75824585/140891962-3b131cd3-9abe-4487-955a-f2bb6a3fd3de.png)
![image](https://user-images.githubusercontent.com/75824585/140891989-476b8dda-85ed-4ca1-a09c-4b24883ea67e.png)

_Originally posted by @Ruixi-rebirth in https://github.com/fatih/vim-go/issues/3200#issuecomment-963936580_

**Comment by bhcleek** [comment]
You'll need to turn on terminal mode with `let g:go_term_enabled=1`.

**Comment by Ruixi-rebirth** [comment]
Ok, solved
