### ISSUE TITLE
multiple main modules under one directory

### ISSUE THREAD

**Issue by laoshaw** [fatih/vim-go#3329]
Not really a bug report, but more of a feature request.

To learn golang fast I have multiple single main.go under one directory so I don't need create 100 small modules/workspaces, just to practice basic syntax etc. I really do not need module/workdir etc at this stage. When I use vim-go it keeps waring/erroring: "gopls requires a module at the root of your workspace. you can work with multiple modules by opening each one as a workspace folder"

How can I silence that warning? is there a flag for that?I do want to use gopls for code completion etc.

**Comment by laoshaw** [comment]
if I create a 'go.mod' then I got 'DuplicateDecl: main redeclared in this block', which is expected, the question is that, can I disable that warning when I really need to.

**Comment by bhcleek** [comment]
You can disable gopls in vim-go with `let g:go_gopls_enabled=0` (see `:help g:go_gopls_enabled`).

**Comment by laoshaw** [comment]
that will disable all autocompletion as well right?

**Comment by bhcleek** [comment]
yes

**Comment by laoshaw** [comment]
thanks!
