### ISSUE TITLE
:GoDef working for everything except Go standard library

### ISSUE THREAD

**Issue by ghodss** [fatih/vim-go#333]
:GoDef is working great for me except when I try to run it on the standard library, e.g. anything inside the fmt package. In that case it says something like `godef: no declaration found for fmt.Printf`. It works fine within a project as well as across any projects that are in my GOPATH. Any idea what might be wrong?

**Comment by fatih** [comment]
This is weird. I'm using perfectly without any problems. Can it be because it wasn't compiled somehow? I have only one single GOPATH and the stdlib is not inside the GOPATH as usual.

**Comment by ghodss** [comment]
You're right! I was using godef compiled with an old version of Go that is no longer installed, so it couldn't find the correct libraries. I wish it would have a better error message including the paths it searched. Thank you!

**Comment by aead** [comment]
I had the same issue for Go 1.11.*
For me, exporting `GOROOT` fixed it: `export GOROOT=$(go env GOROOT)`
