### ISSUE TITLE
Can not install  golangci-lint, error `ld: framework not found CoreFoundation`. 

### ISSUE THREAD

**Issue by AGou-ops** [fatih/vim-go#3332]
### What did you do? 

run `GoInstallBinaries` command  failed.

### What happened instead?

 The error is as follows:

```bash
vim-go: golangci-lint not found. Installing github.com/golangci/golangci-lint/cmd/golangci-lint@latest to folder /opt/
homebrew/Cellar/go/1.17.2/bin
vim-go: Error installing github.com/golangci/golangci-lint/cmd/golangci-lint@latest: # github.com/golangci/golangci-li
nt/cmd/golangci-lint
vim-go: /opt/homebrew/Cellar/go/1.17.2/libexec/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
vim-go: ld: framework not found CoreFoundation
vim-go: clang: error: linker command failed with exit code 1 (use -v to see invocation)
vim-go:
vim-go: installing finished!
```

#### Vim version 

```bash
> vim -V
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
...
```

#### Go version (`go version`):

```bash
> go version
go version go1.17.2 darwin/arm64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br>
<pre>

GO111MODULE=""
GOARCH="arm64"
GOBIN="/opt/homebrew/Cellar/go/1.17.2/bin"
GOCACHE="/Users/agou-ops/Library/Caches/go-build"
GOENV="/Users/agou-ops/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/opt/homebrew/Cellar/go/1.17.2/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/opt/homebrew/Cellar/go/1.17.2"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.17.2/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wl/sjs6bs3d421cj9s478qrtjh00000gn/T/go-build2751386698=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre>

</details>

How should I fix it?

**Comment by bhcleek** [comment]
I'd start by changing `GOPATH` to something other than within homebrew. By default `GOPATH` is `$HOME/go`. I'd probably leave  it unset so that the default will be used.

`GOBIN` to some place other than homebrew's bin directory. `$HOME/go/bin` is typical (and is the default). `$HOME/bin` is what I set my `GOBIN` to.

I'm not sure why you're seeing this error, but ultimately it's not about vim-go, it's your Go installation. To solve this problem, I'd recommend trying to install `golangci-lint` at the commandline with `go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest`. Once you have that working, I suspect you'll be able to execute `:GoInstallBinaries` without any trouble.

**Comment by AGou-ops** [comment]
> I'd start by changing `GOPATH` to something other than within homebrew. By default `GOPATH` is `$HOME/go`. I'd probably leave it unset so that the default will be used.
> 
> `GOBIN` to some place other than homebrew's bin directory. `$HOME/go/bin` is typical (and is the default). `$HOME/bin` is what I set my `GOBIN` to.
> 
> I'm not sure why you're seeing this error, but ultimately it's not about vim-go, it's your Go installation. To solve this problem, I'd recommend trying to install `golangci-lint` at the commandline with `go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest`. Once you have that working, I suspect you'll be able to execute `:GoInstallBinaries` without any trouble.

yeah, you are right, it's not about vim-go. I installed Golang by Homebrew before, and I reinstall Golang through the official package. Then unset all `GOPATH` and `GOBIN` environment variables. I don't know why I was wrong before. But it works now.  

Thank you.
