### ISSUE TITLE
Got "list index out of range: 0" when opening a Go file

### ISSUE THREAD

**Issue by daisukixci** [fatih/vim-go#3334]
### What did you do? (required: The issue will be **closed** when not provided)

I opened a go file 
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Thank you for your work")
}
```

### What did you expect to happen?

Opening the file without the error

### What happened instead?

When I open a go file, I got the following error 
```
"main.go" 17L, 203C
Error detected while processing function go#package#InGOPATH:
line   15:
E684: list index out of range: 0
Error detected while processing /home/login/.vim/pack/plugins/start/vim-go/ftplugin/go/commands.vim:
line  106:
E171: Missing :endif
```
I add to checkout to 1.25 to be able to use the `GoReportGitHubIssue` as it was not working from master branch

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
" Syntastic config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
" Always have the error column on left side
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_checkers = ['pylint']
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_sh_shellcheck_args = "-x"

" Go config
let g:go_fmt_autosave = 0
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_fmt_command = "gofmt"
let g:go_gopls_enabled = 0
autocmd FileType go map <C-l> :cnext<CR>
autocmd FileType go map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>
autocmd FileType go nmap <leader>r  <Plug>(go-run)
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 08 2021 14:21:34)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.17.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/***/snap/alacritty/common/.cache/go-build"
GOENV="/home/***/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/***/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/***/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/8627"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/8627/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3610700081=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.3
    golang.org/x/tools/gopls@v0.7.3 h1:Lru57ht8vtDMouRskFC085VAjBAZRAISd/lwvwOOV0Q=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_highlight_function_calls = 1
g:go_fmt_autosave = 0
g:go_highlight_fields = 1
g:go_gopls_enabled = 0
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_highlight_types = 1
g:go_fmt_command = 'gofmt'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by mthunter2** [comment]
Hi @daisukixci,

What's the output of `keyify -version`?

**Comment by daisukixci** [comment]
> Hi @daisukixci,
> 
> What's the output of `keyify -version`?

keyify (devel, v0.3.0-0.dev.0.20211201164145-eac08b4651cf)

**Comment by bhcleek** [comment]
Does this happen when you open any Go file?

After you get this error, can you execute `:echo expand('%:p:h')` and let me know the result?

**Comment by daisukixci** [comment]
> Does this happen when you open any Go file?
> 
> After you get this error, can you execute `:echo expand('%:p:h')` and let me know the result?

Yes on all files

Here is the redacted output, let me know if you need details but this is `/home/***/Workspace/***/lambdas/***/utils` but the go file is `utils.go` in `utils` folder

**Comment by bhcleek** [comment]
What does `go list` output when run in the `utils` folder with `GO111MODULE` set to `off`?

**Comment by daisukixci** [comment]
> What does `go list` output when run in the `utils` folder with `GO111MODULE` set to `off`?

❯ env | grep -i go111
GO111MODULE=off
❯ go list
_/home/****/****/lambdas/****/utils

**Comment by bhcleek** [comment]
Based on what you said previously that your path was in `/home/***/Workspace/***/lambdas/***/utils`, but in last message, the `Workspace` directory is missing. Is that just a result of how you edited the path to redact portions?

I can't duplicate what you're seeing here, and the statement that's failing is pretty straightforward; I wonder if this is related to a Vim bug 🤔 

Is it possible for you to upgrade Vim and try again?

**Comment by daisukixci** [comment]
> Based on what you said previously that your path was in `/home/***/Workspace/***/lambdas/***/utils`, but in last message, the `Workspace` directory is missing. Is that just a result of how you edited the path to redact portions?

it's because on I use a symlink from the folder Workspace. I unredacted a bit the path for a better understanding.
`/home/login/team` is a symlink of `/home/login/Workspace/team`

> I can't duplicate what you're seeing here, and the statement that's failing is pretty straightforward; I wonder if this is related to a Vim bug thinking
> 
> Is it possible for you to upgrade Vim and try again?
Using latest ubuntu vim version, I still have the error
Using vim master version, I can't get the error but have a lot more error as i don't compile Vim with the same option Ubuntu does, so my config throws lot of  additional errors. Will continue to look how can I reproduce Ubuntu vim build

**Comment by bhcleek** [comment]
Have you been able to make any progress? Should we leave this open or close it?

**Comment by daisukixci** [comment]
Sorry this can be closed, after a vim update at some point I was not able to reproduce
