### ISSUE TITLE
`:GoInstallBinaries` outputs errors on a clean Vim install

### ISSUE THREAD

**Issue by dlo** [fatih/vim-go#3335]
### What did you do? (required: The issue will be **closed** when not provided)

I ran `:GoInstallBinaries`

### What did you expect to happen?

I expected the binaries to be installed.

### What happened instead?

<img width="833" alt="image" src="https://user-images.githubusercontent.com/38447/144766487-0690c553-c25a-43e2-8fd4-696feb06acad.png">

#### vim-go version:

Current `master`.

####  `vimrc` you used to reproduce:

```
packloadall
```

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 24 2021 14:13:28)
macOS version - x86_64
Included patches: 1-3455
```

#### Go version (`go version`):

```
go version go1.17.1 darwin/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dan/Library/Caches/go-build"
GOENV="/Users/dan/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dan/.asdf/installs/golang/1.17.1/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dan/.asdf/installs/golang/1.17.1/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/dan/.asdf/installs/golang/1.17.1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/dan/.asdf/installs/golang/1.17.1/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pv/rmyyshm95r78n31p86nnbznw0000gn/T/go-build2955652814=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.3
    golang.org/x/tools/gopls@v0.7.3 h1:Lru57ht8vtDMouRskFC085VAjBAZRAISd/lwvwOOV0Q=
</pre></details>

**Comment by dlo** [comment]
I don't know if this might be helpful, but I'm seeing this error message too on simple `go` commands. E.g., after running `:GoInfo`, I see this:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/38447/144766697-183e2a1e-ee34-43fa-8007-a37272ee80f2.png">

**Comment by bhcleek** [comment]
That seems like the version of Go that's being used by vim-go is not Go 1.17. Let's verify what version of go is in your path.

Can you run `:!which go` from within Vim and report back what it outputs?

Do you have multiple versions of Go on your system?

**Comment by dlo** [comment]
That might be the problem! I use `asdf` for managing go versions, so there are several installed. `:!which go` outputs `/usr/local/bin/go`.

**Comment by bhcleek** [comment]
What does `/usr/local/bin/go version` output?

**Comment by dlo** [comment]
`go version go1.15.7 darwin/amd64`

**Comment by bhcleek** [comment]
That's the issue: Go 1.15 doesn't support the `path@version` syntax in `go install`.

You may be interested in using `g:go_bin_path` (see `:help g:go_bin_path`).

**Comment by dlo** [comment]
That did it. Thank you so much for the help!

**Comment by bhcleek** [comment]
I'm glad we got it sorted. 

'm curious, because I've never really understood the use case with Go: why do you switch between  Go versions?

**Comment by dlo** [comment]
@bhcleek Good question. I use go 1.16 at work and I'm using go 1.17 for my personal projects.

**Comment by mfort2** [comment]
Curious, what's the problem with go version 1.15.7 above?
If I understand properly, changing from go install back to go get should work.

**Comment by bhcleek** [comment]
Switching back to `go get` would work for now, but isn't sustainable long term, because installing with `go get` is deprecated and will be removed in Go 1.18 (set to be released in February).

Go 1.15.7 is no longer supported - only the two most recent major versions of Go get security updates.
