### ISSUE TITLE
Long strings of digits cause problems

### ISSUE THREAD

**Issue by SpicyLemon** [fatih/vim-go#3337]
### What did you do?

I've been able to replicate this a few different ways.

1. Paste a long string of digits into a file.
    1. Copy a long (35+) string of digits from somewhere.
    1. Open a go file in vim.
    1. Enter insert mode.
    1. cmd+v.
1. Type a long string of digits into a file.
    1. Open a go file in vim.
    1. Enter insert mode.
    1. Type 35+ digits.
1.  Open a file with a long string of digits in it.
    1. Create a file go file with a long string of digits using something other than vim.
        E.g. execute this command:
        ```sh
        printf 'package main\n\nimport (\n\t"fmt"\n)\n\nfunc main() {\n\t// %s\n\tfmt.Println("no color")\n}\n' "$( printf '%d' $( seq 1 22 ) )" > bad.go
        ```
    1. Open the file in vim (e.g. `vi bad.go`).

Example problematic string of digits: `12345678910111213141516171819202122`

### What did you expect to happen?

Vim continues to function normally.

### What happened instead?

In each case, vim becomes generally slow or even unresponsive. Vim also stops applying syntax coloring.

More specifically for each case:
1. If the string of digits is long enough (45+), vim becomes completely unresponsive. Otherwise, the paste seems to take a while and syntax coloring on the lines below it goes away.
1. Once you get to about 17 digits, lag is noticeable between keypress and the digit appearing in vim. Once you get to 23 digits, the line and everything below it will lose coloring. Deleting some of the digits doesn't bring coloring back.
1. It takes a while for vim to finish opening the file and show the lines. Once done, there is no coloring and these lines show at the bottom:
    ```plain
    vim-go: initialized gopls
    vim-go: Finished loading packages.
    ```

#### vim-go version:

`master`

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
set number
highlight LineNr term=bold cterm=NONE ctermfg=Black ctermbg=DarkGrey gui=NONE guifg=Black guibg=DarkGrey
syntax on
set tabstop=4
set shiftwidth=4
set expandtab
set mouse=a
set hlsearch
:highlight BadWhitespace ctermbg=red guibg=red
:match BadWhitespace /\s\+$\|\t/
filetype plugin indent on
" Change cursor shape between insert and normal mode in iTerm2.app
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
endifvi
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct  1 2021 22:47:41)
macOS version - arm64
Included patches: 1-2671

#### Go version (`go version`):

go version go1.17.5 darwin/arm64
go version go1.17 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/danielwedul/Library/Caches/go-build"
GOENV="/Users/danielwedul/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/danielwedul/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/danielwedul/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.17.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.17.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yg/my5b2q657dl8h4bfs8x8y1ch0000gp/T/go-build2072106801=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.4
    golang.org/x/tools/gopls@v0.7.4 h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_highlight_space_tab_error = 1
g:go_loaded_install = 1
g:go_highlight_trailing_whitespace_error = 1
g:go_jump_to_error = 1
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_extra_types = 1
g:go_loaded_gosnippets = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
What does `:set re?` output?

**Comment by SpicyLemon** [comment]
> What does `:set re?` output?

`regexpengine=1`

**Comment by bhcleek** [comment]
That's the source of the problem you're seeing. I suspect that if you set it to 0 or 2 (0 is preferred and is the default), then you'll no long see the issue you described.

**Comment by SpicyLemon** [comment]
Yup. I added `set re=2` to my `.vimrc` and no longer have this issue.

Thanks!

I'll leave the issue open in case someone else wants to find and tweak the problem regex. Feel free to close it, though.
