### ISSUE TITLE
Lost a lot of syntax highlighting after macOS update and package update

### ISSUE THREAD

**Issue by venalen** [fatih/vim-go#3339]
### What did you do? (required: The issue will be **closed** when not provided)
I recently updated to Monterey (macOS) which required me to rebuild a lot of go binaries in order for them to run. Ultimately I decided to updated a lot of things:
* updated to Monterey
* updated to nvim 0.6.1
* updated to latest `vim-go` package

### What did you expect to happen?
I expected everything to stay the same

### What happened instead?
But I lost a lot of syntax highlighting for my go files. I have function and string highlighting, but nothing else. I tried `syntax=on` as well as `syntax=enable`, and made sure that `filetype=go`

#### vim-go version:
`v1.25`

####  `vimrc` you used to reproduce:

<details><summary>Truncated/relevant vimrc</summary>

```vim
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" fatih/go-vim
" Find declarations in file
nmap <leader>a :GoDecls<CR>
" Find declarations in directory
nmap <leader>s :GoDeclsDir<CR>
" Go to definition under cursor
nmap <leader>] :GoDef<CR>
" Go to previous definition
nmap <leader>[ :GoDefPop<CR>
" Location window next
nmap <leader>' :lnext<CR>
" Location window prev
nmap <leader>: :lprev<CR>
" Quickfix window next
nmap <leader>/ :cnext<CR>
" Quickfix window prev
nmap <leader>. :cprev<CR>
" Find all callers under cursor
nmap <leader>c :GoCallers<CR>

" fatih/vim-go syntax highlighting
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1 
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_fmt_command = "goimports"

```
</details>

#### Vim version (first three lines from `:version`):

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

#### Go version (`go version`):

`go version go1.16.7 darwin/amd64`

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vickyenalen/Library/Caches/go-build"
GOENV="/Users/vickyenalen/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/vickyenalen/go/pkg/mod"
GONOPROXY="github.com/Clever/*"
GONOSUMDB="github.com/Clever/*"
GOOS="darwin"
GOPATH="/Users/vickyenalen/go"
GOPRIVATE="github.com/Clever/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8z/l_jp23hx0hzbj7rcklpdr4dc0000gn/T/go-build228279902=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.4
    golang.org/x/tools/gopls@v0.7.4 h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=
</pre></details>

**Comment by bhcleek** [comment]
This can be caused by a few things. Let's start with the most common. What's `set re?` output?

**Comment by venalen** [comment]
Thanks for your reply! The output is `regexpengine=0`

**Comment by bhcleek** [comment]
`regexpengine=0` should be fine. I'm not sure what else may cause this 🤔 Do you this problem in all go files or only some?

**Comment by venalen** [comment]
Hey sorry for the delay! I do see it in all go files, but my laptop is on its last legs and I'll be getting a replacement soon. From there I'll be doing a fresh install of most things so I'll try to troubleshoot then. Thanks for your help!
