### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by yelfathi** [fatih/vim-go#334]
Hi, I have the following highlighting syntax issue (see attached picture: Stdin/Stdout/Stderr are not hilighted) with default vim on mac yosemite. I tried different coloschemes versions. I am using plug-vim.
And last but not least, I used different setup for vim-go highlighting with no success:

let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_trailing_whitespace_error = 1
let g:go_highlight_structs = 1
let g:go_highlight_methods = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_functions = 1
let g:go_highlight_operators = 1

![screenshot 2015-02-25 21 21 20](https://cloud.githubusercontent.com/assets/9952320/6390464/e60d3e28-bdac-11e4-8dc9-2fe7729c8900.png)

Thanks and regards!

**Comment by fatih** [comment]
This is normal, see my screenshot:

![image](https://cloud.githubusercontent.com/assets/438920/6390556/efc67afc-bdb5-11e4-82c1-55183c808697.png)

They don't get highlighted at all.

**Comment by fatih** [comment]
You can tweak the syntax file to customize it even more. However this is the norm. I wouldn't try to bother with it, it's not worth it.

**Comment by yelfathi** [comment]
Weird because on the screenshot of your repository I saw it highlighted (you changed it?) and this is why I thought about an issue. And also here to confirm before asking: https://github.com/golang/go/blob/master/src/os/file.go

**Comment by fatih** [comment]
Can you show the screenshot @yelfathi ? I'm curious which one it is.

**Comment by yelfathi** [comment]
Maybe I am mistaking but I saw yesterday on the screenshot a different highlighted ;). Anyway, can you guide me on how to customize it?

**Comment by fatih** [comment]
Weird, I didn't change anything yesterday. You might been confused I guess.

Here is the file for the syntax declarations:

https://github.com/fatih/vim-go/blob/master/syntax/go.vim

Checkout the following tutorials on how to change and update them:

http://vimdoc.sourceforge.net/htmldoc/syntax.html
http://vim.wikia.com/wiki/Creating_your_own_syntax_files

**Comment by yelfathi** [comment]
OK thanks but on the screenshot of your repo: Stdin/Stdout/Stderr are hilighted: 

https://camo.githubusercontent.com/916aef7dc813e1da4c644ee8b9eb60fb266e7e25/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3137343430342f76696d2d676f2d322e706e67

**Comment by fatih** [comment]
No it's not. The one below is `:GoDoc` output and not syntax highlighting. The code doesn't have any syntax highlighting at all.

**Comment by yelfathi** [comment]
OK fine, thanks it's clear for me!

**Comment by c0r5um** [comment]
Hi, I'm trying to find a way to highlight user defined function, they are highlighted when you declare the function with "func foo()" but not later when you call it like.
I'm trying to understand the go.vim syntax rules but it's a little cryptic, any ideas ? 

thanks
