### ISSUE TITLE
Cannot initialise gopls

### ISSUE THREAD

**Issue by Mestrace** [fatih/vim-go#3340]
### What did you do? (required: The issue will be **closed** when not provided)
Pulled a project, and open using vim.

### What did you expect to happen?
Vim-go loaded gopls successfully and vim-go function works (for example, `gd` should go to definition)

### What happened instead?

`vim-go: initializing gopls` lingers forever and none of vim-go function works.

gopls debug log shows
```
===== sent =====
Content-Length: 772

{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///home/*********************************************/","capabilities":{"worksp
===== stderr =====
serve.go:476: debug server listening at http://localhost:31651
===== stderr =====
gopls: forwarder: connecting to remote: dialing remote: dial unix /run/user/1005/gopls-a34a04-daemon.********: connect: permission denied                                           
```

#### vim-go version:
f3ebf20

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
let g:go_debug=['lsp']


call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-default branch
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'

" Initialize plugin system
call plug#end()

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 21 2021 21:10:48)
Included patches: 1-2539

#### Go version (`go version`):

go version go1.17.6 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.4
    golang.org/x/tools/gopls@v0.7.4 h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=
</pre></details>

**Comment by bhcleek** [comment]
> gopls: forwarder: connecting to remote: dialing remote: dial unix /run/user/1005/gopls-a34a04-daemon.********: connect: permission denied                                           

Seems like it's the culprit. That's not controlled directly by vim-go. I suspect permissions on your system are the root cause.

Does this happen regardless of which Go module you're working with?

**Comment by bhcleek** [comment]
closing for lack of feedback
