### ISSUE TITLE
Feature Request: Display error under cursor

### ISSUE THREAD

**Issue by mario-grgic** [fatih/vim-go#3341]
I'm using vim-go 1.25 with Vim 8.2 with patches 1-4087 on macOS and go1.17.6. In my .vimrc I have `let g:go_diagnostics_level = 2` which highlights errors/warnings for go file in the current buffer. 

However, when you navigate to the highlighted text, no error is displayed is the vim status bar. Other language server/clients do this, and it would be helpful if vim-go did this as well.

**Comment by bhcleek** [comment]
You may be interested in `:GoDiagnostics`, which will display the errors and warnings in the quickfix window.

**Comment by mario-grgic** [comment]
I am aware of `:GoDiagnostics`. I even mapped a shortcut to it, so this is not a huge priority, just nice to have. 

It seems vim-go uses lsp under the covers and lsp has the capability and option to do this already. The `let g:lsp_diagnostics_echo_cursor = 1` option controls this behavior.

**Comment by bhcleek** [comment]
Vim-go uses `gopls`, but not via another lsp plugin. If `g:lsp_diagnostics_echo_cursor` works for you, then you must be using vim-lsp; that's not an option that controls any vim-go behavior.
