### ISSUE TITLE
Couldn't load correct replaced go.mod file

### ISSUE THREAD

**Issue by crazytaxi824** [fatih/vim-go#3343]
example package
```
go get github.com/hashicorp/consul/api
```

`$GOPATH/pkg/mod/github.com/hashicorp/consul/api@v1.12.0/go.mod` file content
```
module github.com/hashicorp/consul/api

go 1.12

replace github.com/hashicorp/consul/sdk => ../sdk

require (
	github.com/hashicorp/consul/sdk v0.8.0
	// ...
)
```

### problem

1. after `go mod tidy`, `$GOPATH/pkg/mod/github.com/hashicorp/consul/sdk@v0.8.0/...` is created.

2. after `:GoDef` jump into `.../consul/api@v1.12.0/xxx.go` file, vim-go tries to read `.../consul/sdk/go.mod`, and `.../consul/sdk/` is not exist, so it cause GoDoc, GoDef ... stop working.

### vim-go error message:
```
vim-go: Finished loading packages.k@v0.8.0 (replaced by ../sdk): reading ../sdk/go.mod: open .../pkg/mod/github.com/hashicorp/consul/sdk/go.mod: no such file or directory
```

### env:

vim v8.2.4100

vim-go a319aaf6bf652dadb197807e4629ff5b1750a17b

gopls v0.7.4

**Comment by bhcleek** [comment]
I can't quite duplicate the problem you're describing. I suspect some steps are missing from your reproduction instrucdtions.

1. What directory are you in when you run `go get github.com/hashicorp/consul/api` ?
1. What directory are you in when you run `go mod tidy`?
1. What file are you editing when you use `:GoDef` to jump into a file in `github.com/hashicorp/consul/api`?

**Comment by crazytaxi824** [comment]
@bhcleek sorry, i didn't make it clearly.

1. I have a project foo

```
foo
├── go.mod
└── src
    └── main.go
```

2. run `go get github.com/hashicorp/consul/api` in `.../foo` project root directory.

3. run `go mod tidy` in `.../foo` project root directory.

4. my `.../foo/src/main.go` content

```go
package main

import (
	"log"

	"github.com/hashicorp/consul/api"
)

func main() {
	client, err := api.NewClient(&api.Config{
		Address: "xxx",
	})

	// ...
}
```

5. cursor on `NewClient()`, run `:GoDef`. it will jump to `$GOPATH/pkg/mod/github.com/hashicorp/consul/api@v1.12.0/api.go`

```go
// NewClient returns a new client
func NewClient(config *Config) (*Client, error) {
	// bootstrap the config
	defConfig := DefaultConfig()

	// ...
}
```

### Problem

My problem is when i try to `:GoDef` the `DefaultConfig()` in this function, it won't work. vim-go shows `vim-go: : packages.Load error`. 

So I dig a little deeper, found that vim-go is trying to load `$GOPATH/pkg/mod/github.com/hashicorp/consul/sdk/go.mod` instead of `$GOPATH/pkg/mod/github.com/hashicorp/consul/sdk@v0.8.0/go.mod`, because `$GOPATH/pkg/mod/github.com/hashicorp/consul/api@v1.12.0/go.mod` shows

```go
module github.com/hashicorp/consul/api

go 1.12

replace github.com/hashicorp/consul/sdk => ../sdk   (❌ this is where replace goes wrong)

require (
	github.com/hashicorp/consul/sdk v0.8.0
	//...
)
```

If I change the line to `replace github.com/hashicorp/consul/sdk => ../sdk@v0.8.0` vim-go works perfect. So I think it just the directory replace problem.

Thanks a lot for your help.

**Comment by bhcleek** [comment]
What version of Go are you using?

**Comment by crazytaxi824** [comment]
> What version of Go are you using?

1.17.6

**Comment by bhcleek** [comment]
Thank you. I was able to reproduce the problem you're seeing and have a fix nearly ready.

**Comment by crazytaxi824** [comment]
@bhcleek Big help, Thanks a lot!
