### ISSUE TITLE
GoImports not run automatically on save

### ISSUE THREAD

**Issue by eapache** [fatih/vim-go#335]
I understand based on reading the documentation that when I save a go file, it should automatically run gofmt (which works well) and go-imports, however go-imports is not being run. If I run `:GoImports` manually then it correctly runs and updates the buffer, it's just not happening on save for some reason.

**Comment by fatih** [comment]
Please check https://github.com/fatih/vim-go#settings

Add this to your vimrc:

```
let g:go_fmt_command = "goimports"
```

**Comment by eapache** [comment]
My understanding is that that setting will *replace* `gofmt` which is not what I want - ideally I would like *both* gofmt and go-imports to run on save.

**Comment by fatih** [comment]
They are the same. gofmt is a subset of gomimports. So `goimports = gofmt + automatic importing`

**Comment by eapache** [comment]
Oh, I didn't realize go-imports also did formatting still, sorry for the confusion. Thanks for your help!

**Comment by fatih** [comment]
You're welcome, have fun with vim-go :)
