### ISSUE TITLE
gopls no such file error with go_fmt_autosave on mac

### ISSUE THREAD

**Issue by shaunduncan** [fatih/vim-go#3350]
### What did you do? (required: The issue will be **closed** when not provided)

`vim -u minimal-vimrc /tmp/x.go` which would give me the short default template file. Then, without doing anything, I immediately saved the file and quicklist showed an error from gopls.

NOTE: the issue https://github.com/fatih/vim-go/issues/3219 seemed very similar to my experience and the modification of `<afile>` to `%` fixed the problem - the former was the path `/tmp/x.go` whereas the latter was the fully resolved path `/private/tmp/x.go`. This only seems to be the case when the autocmd call to `s:register()` happens - later expanded values for `<afile>` return `/private/tmp/x.go`.

### What did you expect to happen?

No error from gopls

### What happened instead?

gopls showed the error: `/private/tmp/x.go:stat /private/tmp/x.go: no such file or directory`

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
set nocompatible

call plug#begin()
Plug 'fatih/vim-go' , { 'do': ':GoUpdateBinaries' }
call plug#end()

let g:go_list_type='quickfix'
let g:go_fmt_autosave=1
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 29 2022 12:10:43)
macOS version - x86_64
Included patches: 1-4250

#### Go version (`go version`):

go version go1.17 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sduncan/Library/Caches/go-build"
GOENV="/Users/sduncan/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sduncan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sduncan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m2/lmrdj89n115ghxt2zscg7bvm0000gn/T/go-build618158904=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.5
    golang.org/x/tools/gopls@v0.7.5 h1:8Az52YwcFXTWPvrRomns1C0N+zlgTyyPKWvRazO9GG8=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_fmt_autosave = 1
g:go_jump_to_error = 1
g:go_list_type = 'quickfix'
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
I was hopeful that this would be an easy reproduction, especially given that others have reported something similar. Unfortunately, I still can't duplicate it. When I tried on my machine (a macOS box), I added a `echom expand('<afile>:p')` in `s:register()`, and it always outputs the dereferenced path of `/tmp` to `/private/tmp`.

I wonder if the others that have encountered this were also seeing it only when dealing with symlinked directories and/or if it was always `/tmp`. 🤔  I further wonder if this is some kind of race condition in Vim or macOS when it tries to dereference symlinks.

Using `%` can't be relied on in `s:register()`, because the current file is not always the file being manipulated (i.e. the current loaded buffer is not always the buffer on which `FileType` is being set).

**Comment by shaunduncan** [comment]
Yeah I totally understand not changing it - I was just mentioning that it worked.

I had the same thought with respect to symlinked directories. I did try an experiment with a symlinked directory I created manually and it didn't have the same behavior, so I ended up sorta scratching my head. The race condition was the other thing I was wondering about, but I didn't try to test anything with that.

I'm happy to help try anything to figure it out, just let me know!

**Comment by bhcleek** [comment]
Does this only occur when the file you're working with was in `/tmp` ?

**Comment by shaunduncan** [comment]
Yes and only if I edit using an absolute path. If i `cd /tmp` first and then edit `vim x.go` it won't have the same problem. But I was able to have this happen just now with a non-tmp directory that's setup in a similar manner. The key when I tried this was to not be in a directory relative to how it was setup:

```
cd ~
mkdir -p one/foo
ln -s one/foo foo
mkdir two
cd two
vim ~/foo/x.go  # then immediately save the "hello world" template file that appears
```

**Comment by bhcleek** [comment]
Thank you! That was very helpful. Can you test https://github.com/fatih/vim-go/pull/3353 and make sure it resolve the issues for you, too?

**Comment by shaunduncan** [comment]
That looks to have done the trick!
