### ISSUE TITLE
Why vim-go keeps remove useless imports even set fmt_command to `gofmt`

### ISSUE THREAD

**Issue by chunyang-wen** [fatih/vim-go#3354]
#### vim-go version:
Vim-plug install master

####  `vimrc` you used to reproduce:
```vimscript
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
let g:go_fmt_command = 'gofmt
```

Why it still formats and removes useless imports? What I expect is:

+ Format the code
+ Not remove useless imports

**Comment by bhcleek** [comment]
See `:help g:go_imports_autosave`

**Comment by chunyang-wen** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/2911134/153532872-9aaad01c-c894-4e1a-8049-0b7b763eaba6.png">

```vim
let g:go_imports_autosave = 0
```

will not automatically remove imports but will adjust the sequence.

It works as expected.
