### ISSUE TITLE
How to completely uninstall vim-go?

### ISSUE THREAD

**Issue by AGou-ops** [fatih/vim-go#3355]
### What did you do? 

I just uncomment the plug in my config and run `PlugClean` to uninstall vim-go.

![111](https://user-images.githubusercontent.com/57939102/153981075-581afba6-1ba0-4c6c-ac55-392913c82e9e.gif)

### What did you expect to happen?

Completely uninstall vim-go.

### What happened instead?

vim-go exists.

#### vim-go version:

latest.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
no additional options, just `Plug 'fatih/vim-go'`
```
</details>

#### Go version (`go version`):

`go1.17.5 darwin/arm64`

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre>> go env                                                                                                                                                                                      ║
        ║GO111MODULE="on"                                                                                                                                                                              ║
        ║GOARCH="arm64"                                                                                                                                                                                ║
        ║GOBIN=""                                                                                                                                                                                      ║
        ║GOCACHE="/Users/agou-ops/Library/Caches/go-build"                                                                                                                                             ║
        ║GOENV="/Users/agou-ops/Library/Application Support/go/env"                                                                                                                                    ║
        ║GOEXE=""                                                                                                                                                                                      ║
        ║GOEXPERIMENT=""                                                                                                                                                                               ║
        ║GOFLAGS=""                                                                                                                                                                                    ║
        ║GOHOSTARCH="arm64"                                                                                                                                                                            ║
        ║GOHOSTOS="darwin"                                                                                                                                                                             ║
       ║GOINSECURE=""                                                                                                                                                                                 ║
        ║GOMODCACHE="/Users/agou-ops/go/pkg/mod"                                                                                                                                                       ║
        ║GONOPROXY=""                                                                                                                                                                                  ║
        ║GONOSUMDB=""                                                                                                                                                                                  ║
        ║GOOS="darwin"                                                                                                                                                                                 ║
        ║GOPATH="/Users/agou-ops/go"                                                                                                                                                                   ║
        ║GOPRIVATE=""                                                                                                                                                                                  ║
        ║GOPROXY="https://proxy.golang.org,direct"                                                                                                                                                     ║
        ║GOROOT="/usr/local/go"                                                                                                                                                                        ║
        ║GOSUMDB="sum.golang.org"                                                                                                                                                                      ║
        ║GOTMPDIR=""                                                                                                                                                                                   ║
       .║GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"                                                                                                                                               ║
    ses║GOVCS=""                                                                                                                                                                                      ║
     coc║GOVERSION="go1.17.5"                                                                                                                                                                          ║
     cus║GCCGO="gccgo"                                                                                                                                                                                 ║
     dis║AR="ar"                                                                                                                                                                                       ║
     gen║CC="clang"                                                                                                                                                                                    ║
     ini║CXX="clang++"                                                                                                                                                                                 ║
     ini║CGO_ENABLED="1"                                                                                                                                                                               ║
     key║GOMOD="/dev/null"                                                                                                                                                                             ║
     pus║CGO_CFLAGS="-g -O2"                                                                                                                                                                           ║
     pus║CGO_CPPFLAGS=""                                                                                                                                                                               ║
     shp║CGO_CXXFLAGS="-g -O2"                                                                                                                                                                         ║
~        ║CGO_FFLAGS="-g -O2"                                                                                                                                                                           ║
~        ║CGO_LDFLAGS="-g -O2"                                                                                                                                                                          ║
~        ║PKG_CONFIG="pkg-config"                                                                                                                                                                       ║
~        ║GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wl/sjs6bs3d421cj9s478qrtjh00000gn/T/go-build2804308636=/tm║
~        ║p/go-build -gno-record-gcc-switches -fno-common"</details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
 gopls version                                                                                                                                                                               ║
~        ║golang.org/x/tools/gopls v0.7.4                                                                                                                                                               ║
~        ║    golang.org/x/tools/gopls@v0.7.4 h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=</details>
</pre>

**Comment by bhcleek** [comment]
Vim plugins can be removed by removing their source from the places that Vim search for it. You can use `set rtp?` to see where it's looking. There's likely a `vim-go` directory in the list of directories output by `set rtp?`. Remove it.

**Comment by AGou-ops** [comment]
> Vim plugins can be removed by removing their source from the places that Vim search for it. You can use `set rtp?` to see where it's looking. There's likely a `vim-go` directory in the list of directories output by `set rtp?`. Remove it.

@bhcleek Thanks for your reply.

Nothing related to `vim-go` plugin has been found.

<details><summary>`set rtp` output</summary>

```bash
  runtimepath=~/.config/nvim,
~/.vim/plugged/gruvbox-material,
~/.vim/plugged/lualine.nvim,
~/.vim/plugged/nvim-transparent,
~/.vim/plugged/wilder.nvim,
~/.vim/plugged/alpha-nvim,
~/.vim/plugged/impatient.nvim,
~/.vim/plugged/vim-markdown,
~/.vim/plugged/markdown-preview.nvim,
~/.vim/plugged/lens.vim,
~/.vim/plugged/vim-auto-save,
~/.vim/plugged/tagbar,
~/.vim/plugged/nvim-web-devicons,
~/.vim/plugged/nvim-tree.lua,
~/.vim/plugged/nvim-autopairs,
~/.vim/plugged/indent-blankline.nvim,
~/.vim/plugged/toggleterm.nvim,
~/.vim/plugged/plenary.nvim,
~/.vim/plugged/telescope.nvim,
~/.vim/plugged/bufferline.nvim,
~/.vim/plugged/vim-cursorword,
~/.vim/plugged/sqls.nvim,
~/.vim/plugged/vim-illuminate,
~/.vim/plugged/vim-devicons,
~/.vim/plugged/vim-delve,
~/.vim/plugged/scrollbar.nvim,
~/.vim/plugged/neoscroll.nvim,
~/.vim/plugged/vim-startuptime,
~/.vim/plugged/filetype.nvim,
~/.vim/plugged/Comment.nvim,
~/.vim/plugged/vim-visual-multi,
~/.vim/plugged/undotree,
~/.vim/plugged/persistence.nvim,
~/.vim/plugged/which-key.nvim,
~/.vim/plugged/todo-comments.nvim,
~/.vim/plugged/distant.nvim,
~/.vim/plugged/zen-mode.nvim,
~/.vim/plugged/twilight.nvim,
~/.vim/plugged/nvim-colorizer.lua,
~/.vim/plugged/vim-translator,
~/.vim/plugged/lsp-colors.nvim,
~/.vim/plugged/ale,
~/.vim/plugged/nvim-lspconfig,
~/.vim/plugged/nvim-lsp-installer,
~/.vim/plugged/cmp-nvim-lsp,
~/.vim/plugged/cmp-buffer,
~/.vim/plugged/lspkind-nvim,
~/.vim/plugged/cmp-path,
~/.vim/plugged/nvim-cmp,
~/.vim/plugged/cmp-calc,
~/.vim/plugged/cmp-emoji,
~/.vim/plugged/cmp-look,
~/.vim/plugged/gitsigns.nvim,
~/.vim/plugged/lspsaga.nvim,
~/.vim/plugged/lsp_signature.nvim,
~/.vim/plugged/vimspector,
~/.vim/plugged/diffview.nvim,
~/.vim/plugged/vim-move,
~/.vim/plugged/cmp-tabnine,
~/.vim/plugged/trouble.nvim,
/etc/xdg/nvim,
~/.local/share/nvim/site,
~/.local/share/nvim/site/pack/*/start/*,
/usr/local/share/nvim/site,
/usr/share/nvim/site,
/opt/homebrew/Cellar/neovim/0.6.0/share/nvim/runtime,
/opt/homebrew/Cellar/neovim/0.6.0/share/nvim/runtime/pack/dist/opt/matchit,
/opt/homebrew/Cellar/neovim/0.6.0/lib/nvim,
~/.local/share/nvim/site/pack/*/start/*/after,
/usr/share/nvim/site/after,
/usr/local/share/nvim/site/after,
~/.local/share/nvim/site/after,
/etc/xdg/nvim/after,
~/.vim/plugged/gruvbox-material/after,
~/.vim/plugged/vim-markdown/after,
~/.vim/plugged/cmp-nvim-lsp/after,
~/.vim/plugged/cmp-buffer/after,
~/.vim/plugged/cmp-path/after,
~/.vim/plugged/cmp-calc/after,
~/.vim/plugged/cmp-emoji/after,
~/.vim/plugged/cmp-look/after,
~/.vim/plugged/cmp-tabnine/after,
~/.config/nvim/after
```
</details>

Is the `lsp-config` caused?

**Comment by AGou-ops** [comment]
ohhh, I found another `vim-go` in` ~/.local/share/nvim/site/pack/packer/start/` directory. I deleted it and `vim-go` was uninstalled successfully!
