### ISSUE TITLE
Highlighting user-defined functions 

### ISSUE THREAD

**Issue by c0r5um** [fatih/vim-go#336]
Hi, 
I'm trying to highlight user defined function, they are correctly highlighted when you declare the function with "func" keyword  but not later when you call the function.

I'm trying to understand the go.vim file syntax but it's a little cryptic, any ideas ? 

thanks

**Comment by fatih** [comment]
Can you give an example on what you want to achieve ? Currently functions are highlighted already.

**Comment by c0r5um** [comment]
Here is a really simple example, as you can see when I call "sayHello()" it is not highlighted like the std lib functions.

![2015-02-27-184723_3840x1080_scrot](https://cloud.githubusercontent.com/assets/4492839/6417953/6f38adcc-beb1-11e4-91e4-4aae282e6235.png)

It is the standard behaviour, maybe I'm missing some options that I need to turn on ? 
I have of course in my .vimrc

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g_go_highlight_extra_types = 1

**Comment by fatih** [comment]
Hm no. Only declarations are highlighted. To be honest, what you want is to highlight every single function call. It would make the code unnecessary colorful and also in my own opinion not much readable. How is it in other languages or in emacs, sublime? I wouldn't add something like this, but I'm curious how the state in other editors or languages are. I'll wait for your response :)

**Comment by c0r5um** [comment]
I have looked several screenshots of others editors/IDE, and the highlighting of function call  is sometime present.  Each uses its own rules. 
But anyway thanks for your answers.

**Comment by fatih** [comment]
Thanks @c0r5um for the response. I'm closing the issue as this is not something I would add right now. Of course decisions can be evaluated again later once the time comes.

**Comment by c0r5um** [comment]
I was inspired by the rust plugin syntax file for vim, 
I have made a small modification  on go.vim & added an option "g:go_highlight_userdef_functions" 
It is working now, but I'm not sure about the matching expression used for function call. ( stolen from rust.vim)
Here is the modified version of go.vim https://paste.ee/p/sJVP4
