### ISSUE TITLE
Weird interaction between asdf and vim-go: garbage in GOPATH, failing GoInstallBinaries

### ISSUE THREAD

**Issue by bitwombat** [fatih/vim-go#3369]
### What did you do? (required: The issue will be **closed** when not provided)
Ran `:GoPath` when using asdf. 

### What did you expect to happen?
I expected to see just:
`/Users/bitwombat/.asdf/installs/golang/1.17.8/packages`, 
which I do if I use `Homebrew's` installation of Go (same version).

### What happened instead?
^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?103
4h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1
034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h/Us
ers/bitwombat/.asdf/installs/golang/1.17.8/packages

Similar output happens from `:GoInstallBinaries`, and many (not all) of the installations fail.

#### vim-go version:
v1.25

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'fatih/vim-go', {'do': ':GoInstallBinaries'}
call plug#end()
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 03 2022 17:05:35)
macOS version - arm64
Included patches: 1-4500

#### Go version (`go version`):

go version go1.17.8 darwin/arm64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/bitwombat/Library/Caches/go-build"
GOENV="/Users/bitwombat/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/bitwombat/.asdf/installs/golang/1.17.8/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/bitwombat/.asdf/installs/golang/1.17.8/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/bitwombat/.asdf/installs/golang/1.17.8/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/bitwombat/.asdf/installs/golang/1.17.8/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.8"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b1/lybmqdyj2xx4bk5lt3kbgxp40000gp/T/go-build1221063830=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

Not thinking this is necessarily a vim-go problem, it's just a weird one that I thought I'd show you just in case, and possibly for reference should anybody else see this. I cannot reproduce the problem outside of vim, so it seems to be an interaction between asdf, vim, and vim-go...

**Comment by bhcleek** [comment]
I'm not sure why you're seeing this, but it's almost certainly not because of vim-go.

The characters you're seeing look like terminal control codes. I wonder what the value of your `TERM` environment variable is.

**Comment by bitwombat** [comment]
You got it. With `TERM=xterm-256color`, I get the mess above, with `TERM=screen`, it's all good. 

Not sure why `asdf` makes a difference there. As soon as terminal settings get involved, *nix problems get nearly unsolvable!

The fact that all binary installs fail, though, seems like it might be worth tracking down?

<details><summary>`:GoInstall` with both `TERM=xterm-256color` and asdf's go 1.17.8</summary><br><pre>
vim-go: revive not found. Installing [github.com/mgechev/revive@latest](http://github.com/mgechev/revive@latest) to folder
vim-go: Error installing [github.com/mgechev/revive@latest](http://github.com/mgechev/revive@latest): ^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1
034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?10
34h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?103
4h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034
h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h
^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^
[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[
[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[
?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?
1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034hcmd/go: unsupported GOOS/GOARCH
pair ^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1
034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?10
34h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?103
4h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034
h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h
^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^
[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034hdarwin/^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?
1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1
034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?10
34h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?103
4h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034
h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h
^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034h^[[?1034harm64
</details>

<details><summary>`:GoInstall` with either `TERM=screen` or Homebrew's go 1.17.8</summary><br><pre>
vim-go: revive not found. Installing [github.com/mgechev/revive@latest](http://github.com/mgechev/revive@latest) to folder /Users/bitwombat/go/bin/

vim-go: guru not found. Installing [golang.org/x/tools/cmd/guru@master](http://golang.org/x/tools/cmd/guru@master) to folder /Users/bitwombat/go/bin/
</details>

This is no fun for you as a creator/maintainer, and I have a workaround, so if you just close this, I'll not be offended :)

**Comment by bhcleek** [comment]
Yeah, I'm not sure why asdf would make a difference either, but I'm not an asdf user. I can tell you with certainty that vim-go never sets `TERM`.

But I think the problem you're encountering is related to the first line in that output:
```
vim-go: revive not found. Installing [github.com/mgechev/revive@latest](http://github.com/mgechev/revive@latest) to folder
```

Notice how the folder it says it's installing to is not output. That indicates that the folder path is empty. What is `g:go_bin_path` set to on your system? What's `:!go env GOBIN` and `:!go env GOPATH` output?

**Comment by bitwombat** [comment]
Sorry @bhcleek, I meant to address this before you noticed the delay. I think it's still an issue. I have this tab open waiting for me to do more testing. I'll get to it today.

**Comment by bitwombat** [comment]
OK, I'm back to reproducing the crazy term-code-filled output.

> What is `g:go_bin_path` set to on your system? 

Not set

> What's `:!go env GOBIN`

Not set. After having lots of problems, I've been advised by teammates to just set `GOPATH` and add `$GOPATH/bin` to my `PATH`. Which seems wrong.

`asdf` sets `GOROOT`. 

Apparently nothing sets GOBIN - seems to default to GOROOT/bin, because I have tools installed there.

> and `:!go env GOPATH` output?

`/Users/me/go`

This is too much a Go question, and not a vim-go issue. 
I think the only things vim-go could help with are: 
a) clean up the output of terminal codes so I can see the error message, 
b) do some pre-flight checks and warn if the environment is not correct. 

None of this is essential, would just be helpful for a newbie like me to sort out my underlying issues.

**Comment by bitwombat** [comment]
One more thing... whatever this terminal problem is seems to pollute the filename so that it can't be found.  This error (upon startup) goes away if I set TERM=screen.

vim-go: Error loading packages: invalid workspace folder path: no such file or directory; check that the casing of the configured workspace folder path agrees with the casing reported by the
operating system: no such file or directory
vim-go: Error loading workspace folders (expected 1, got 0)
vim-go: failed to load view for file:///Users/bitwombat/code/pm/coord/%1B%5B%3F1034h%1B%5B%3F1034h%1B%5B%3F1034h%1B%5B%3F1034h%1B%5B%3F1034h%1B%5B%3F1034h/Users/bitwombat/code/pm/coord: invalid workspace folder path: no such file or directory; check that the casing of the configured workspace folder path agrees with the casing reported by the operating system: no such f
vim-go: Finished loading packages.

**Comment by bhcleek** [comment]
> This is too much a Go question, and not a vim-go issue.

Vim-go relies on a number of things in your Go environment. Given that vim-go is a plugin for Go, that shouldn't be surprising.

> I think the only things vim-go could help with are:
> a) clean up the output of terminal codes so I can see the error message,

This is not vim-go's job. I'm not sure why you're getting the terminal codes yet, but it seems very likely that there's a mismatch between TERM and how your Vim instance may be configured.

> b) do some pre-flight checks and warn if the environment is not correct.

I've never seen the problem you're having before. Once we figure out the source of your problem, I'll consider whether changes need to be made to vim-go.

> I've been advised by teammates to just set GOPATH and add $GOPATH/bin to my PATH. Which seems wrong.

There generally shouldn't be a need to do that; vim-go will automatically look for binaries in `$GOPATH/bin`. Given the error message output when you run `:GoInstallBinaries`, I wonder if you could provide me with the output of `:!go env gopath`?

All of these instances of the escape codes in your output implies that something is amiss with either your shell profile or with your Vim configuration and its terminal related options. With that in mind:
1. What is the output of `:set`?
2. Are you using screen or tmux?

**Comment by bhcleek** [comment]
@bitwombat should we close this?

**Comment by bitwombat** [comment]
Closing because it's too tough to reproduce. I've had lots of problems/confusions/interactions with terminal types, M1/Rosetta and architectures, asdf, and Go versions.

Thanks for the effort and for vim-go!
