### ISSUE TITLE
When using go workspaces (go.work) unable to start debugger, getting exit code 1

### ISSUE THREAD

**Issue by kkrime** [fatih/vim-go#3374]
### What did you do? (required: The issue will be **closed** when not provided)
Run GoDebugStart

I noticed that the debugger *only* starts when using go workspace for the sub modules in the `go.work` file (see: https://github.com/golang/tools/blob/master/gopls/doc/workspace.md), but not for any other modules

### What did you expect to happen?
A debug session to start
### What happened instead?
`:message` gives:
vim-go: directory . outside modules listed in go.work or their selected dependencies
vim-go: exit status 1
#### vim-go version:
commit 9c31c55e471bb160c70fda1374b43f41aa3147ed (HEAD -> master, origin/master, origin/HEAD)
Author: Billie Cleek <bhcleek@gmail.com>
Date:   Mon Mar 14 11:48:05 2022 -0700

    update CHANGELOG.md for #3370
####  `vimrc` you used to reproduce:

`.vimrc` basic coc + vim-go, nothing out of the ordinary 

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 17 2021 18:32:29)
#### Go version (`go version`):

go version go1.18 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/iraq/Library/Caches/go-build"
GOENV="/Users/iraq/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/iraq/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/iraq/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/iraq/go/src/test/go.mod"
GOWORK="/Users/iraq/go/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wn/qjssk5_16n798jbvn45g1pz40000gq/T/go-build3425953756=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.1
</pre></details>

**Comment by bhcleek** [comment]
What directory are you in? Is it within a Go module? 

Nothing about `:GoDebugStart` interacts with `gopls`, and those messages appear to have come from `gopls`, not from trying to start the debugger.

If you could provide clearer steps to reproduction, that may be helpful.
