### ISSUE TITLE
How to disable scratch preview on completion?

### ISSUE THREAD

**Issue by shaneutt** [fatih/vim-go#3380]
### What did you do?

Ran `<C-x><C-o>` to trigger completion for a function.

### What did you expect to happen?

Completion pops up providing valid options for the function.

### What happened instead?

Completion works, but also opens a split (`[Scratch] [Preview]`) at the top including the godoc for the function that's being highlighted when selecting from the list.

### Configuration (**MUST** fill this out):

Default configuration.

#### vim-go version:

`v1.25`

#### Vim version (first three lines from `:version`):

`NVIM v0.6.1`

#### Go version (`go version`):

`v1.18`

#### gopls version

`v0.8.1`

#### Problem Statement

I'm looking for a configuration option (or even a hacky way) to disable the `[Scratch] [Preview]` that appears for listed functions when triggering completion.

**Comment by bhcleek** [comment]
See `:help 'completeopt'`
