### ISSUE TITLE
GoDebugStop can't work normally

### ISSUE THREAD

**Issue by Pluto-yubin** [fatih/vim-go#3381]
### What did you do? (required: The issue will be **closed** when not provided)
I run a grpc-go server on WSL and tried to debug with vim, but when I fninshed to debug and typed :GoDebugStop, vim just stopped to work and I can't even move cursor like below
![1%L_D7K{@N@(940$S0(TM`5](https://user-images.githubusercontent.com/53851524/160112544-04bced6e-db55-4ea3-947d-1b92915fe67b.png)

### What did you expect to happen?
The buffer on the right side close automatically
### What happened instead?
Vim stop to work and The only way I can do is to send a request and vim will become like below 
![S3R1XYK$3%3G%{ 68@)O2H](https://user-images.githubusercontent.com/53851524/160112836-c980e206-365b-49da-a1fc-4c3cb75e8ed9.png)
In this way I can stop to debug
#### vim-go version:
I just installed at yesterday, so I think it's 1.25
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" vim-go setting
let g:syntastic_go_checkers = ['go', 'golint', 'govet', 'errcheck']
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
au filetype go inoremap <buffer> . .<C-x><C-o>
let g:go_debug_windows = {
      \ 'vars':       'rightbelow 60vnew',
      \ 'stack':      'rightbelow 10new',
      \ 'GODEBUG_OUTPUT':     'rightbelow 10new',
\ }
let g:go_debug_mappings = {
      \ '(go-debug-continue)': {'key': 'c', 'arguments': '<nowait>'},
      \ '(go-debug-next)': {'key': 'n', 'arguments': '<nowait>'},
      \ '(go-debug-step)': {'key': 's'},
      \ '(go-debug-print)': {'key': 'p'},
  \}
nnoremap gds :GoDebugStart<cr>
nnoremap gdt :GoDebugStop<cr>
nnoremap gdb :GoDebugBreakpoint<cr>
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
#### Go version (`go version`):

go version go1.16.2 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zhangyubin/.cache/go-build"
GOENV="/home/zhangyubin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/mnt/e/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/mnt/e/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/mnt/e/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/mnt/e/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2641352633=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.1
    golang.org/x/tools/gopls@v0.8.1 h1:q5nDpRopYrnF4DN/1o8ZQ7Oar4Yd4I5OtGMx5RyV2/8=
</pre></details>

**Comment by bhcleek** [comment]
Unfortunately, I don't have a Windows machine that I can use to troubleshoot this.

> The only way I can do is to send a request and vim will become like below

What do you mean by "send a request"? What are you doing to send a request?
