### ISSUE TITLE
:GoFmt reorganizes imports on save

### ISSUE THREAD

**Issue by Kuwerin** [fatih/vim-go#3382]
```
" vim-go conf                                                                                                                                                                                           
let g:go_fmt_command = 'gofmt'                                                                                                                                                                          
let g:go_imports_autosave = 0          
```
How can I stop import re-organization on save without  disabling go_fmt_autosave?

### What did you expect to happen?
Only code formatted
### What happened instead?
Code formatted + imports re-organized
### Configuration (**MUST** fill this out):
```
" vim-go conf                                                                                                                                                                                           
let g:go_fmt_command = 'gofmt'                                                                                                                                                                          
let g:go_imports_autosave = 0          
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):
 NVIM v0.5.1 

#### Go version (`go version`):
1.17.2

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kuwerin/Library/Caches/go-build"
GOENV="/Users/kuwerin/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kuwerin/Desktop/Go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/kuwerin/Desktop/Go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c7/ym3gpgv95qq8347zb9ln2yhw0000gp/T/go-build3794574532=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

latest
</pre></details>

**Comment by bhcleek** [comment]
Your settings look right to have the behavior your want.

Can you open a go file and run `:echo g:go_fmt_command` and `:echo g:go_imports_autosave`? What do they output?

**Comment by Kuwerin** [comment]
It's `gofmt` & `0`

**Comment by bhcleek** [comment]
Can you add execute `let g:go_debug=['shell-commands']` and then `:GoFmt`? After that, I'd like to know what `:messages` outputs.

**Comment by Kuwerin** [comment]
I've got this:
```vim
vim-go: initialized gopls                                                                                                                                                                                   
vim-go: Finished loading packages.                                                                                                                                                                          
"cmd/root.go" 127L, 3231C written                                                                                                                                                                           
vim-go: shell command: '/usr/local/bin/gofmt' '-w' '/var/folders/c7/ym3gpgv95qq8347zb9ln2yhw0000gp/T/nvimTVHrUn/2.go'  
```

**Comment by bhcleek** [comment]
When you say organize, do you mean that it's sorting them? That's behavior of `gofmt` that can't be changed.

**Comment by Kuwerin** [comment]
Well then thanks for your time and help, much appreciated.
