### ISSUE TITLE
"text motion objects" - "[[" AND "]]" not working with go1.18 generic syntax

### ISSUE THREAD

**Issue by crazytaxi824** [fatih/vim-go#3383]
### What did you do? (required: The issue will be **closed** when not provided)

```go
package foo

func Foo[T any](v T) T {
	return v
}
```

when i use `[[` or `]]`, an error message pops up: `vim-go: /xxx/foo.go:3:9: expected '(', found '['`.

### What did you expect to happen?

move cursor to the first line of a function.

### What happened instead?

an error message pops up: `vim-go: /xxx/foo.go:3:9: expected '(', found '['`.

### Configuration (**MUST** fill this out):

```vim
let g:go_fmt_command = 'gopls'
let g:go_info_mode = 'gopls'
let g:go_def_mode = 'gopls'
let g:go_addtags_skip_unexported = 1
```

#### vim-go version:

dcefd64ba251ffc3d497f8758036735c8f6cc824

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
let g:go_fmt_command = 'gopls'
let g:go_info_mode = 'gopls'
let g:go_def_mode = 'gopls'
let g:go_addtags_skip_unexported = 1

call plug#begin('~/.vim/plugged')
  Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 20 2022 17:46:06)
macOS version - x86_64
Included patches: 1-4600

#### Go version (`go version`):

go version go1.18 darwin/amd64

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.1
    golang.org/x/tools/gopls@v0.8.1 h1:q5nDpRopYrnF4DN/1o8ZQ7Oar4Yd4I5OtGMx5RyV2/8=
</pre></details>

**Comment by bhcleek** [comment]
Have you executed either `:GoUpdateBinaries` or `:GoUpdateBinaries motion` since upgrading to Go 1.18?

**Comment by crazytaxi824** [comment]
@bhcleek thanks a lot. After i run `:GoUpdateBinaries` manually, the problem goes away. I thought `:GoUpdateBinaries` runs automatically.
