### ISSUE TITLE
Replace path doesn't seem to be correctly picked up on go files

### ISSUE THREAD

**Issue by axsaucedo** [fatih/vim-go#3389]
### What did you do? (required: The issue will be **closed** when not provided)

When creating a go.mod file with a replace to a local filepath, the commands `go mod tidy` work correctly, but when opening the main golang files, it does not seem to identify that the files are being imported locally.

I get the error on the import of `[compiler BrokenImport] [E] could not import github.com/<org>/<repo>`.

Is there anything specific that needs ot be provided for vim-go to recognise the path from the go.mod?

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
    Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

    "...

    " Ensure coc-go doesn't clash with vim-go
    let g:go_code_completion_enabled = 0

    " disable all linters as that is taken care of by coc.nvim
    let g:go_diagnostics_enabled = 0
    let g:go_metalinter_enabled = []

    " don't jump to errors after metalinter is invoked
    let g:go_jump_to_error = 0

    " run go imports on file save
    let g:go_fmt_command = "goimports"

    " automatically highlight variable your cursor is on
    let g:go_auto_sameids = 0

    " Highlights
    let g:go_highlight_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_function_calls = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_extra_types = 1
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_generate_tags = 1

```

The commit version is `119797938eeb875e91182d6bd86eb001d0ef9029`
</details>

#### Go version (`go version`):

go version go1.18 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/<path>/.cache/go-build"
GOENV="/<path>/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/<path>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/alejandro/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/<path>/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1909392301=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.2
    golang.org/x/tools/gopls@v0.8.2 h1:+b7X2FDwmP7vxyYNOHe/ZFkecN5X8OtAgkNtuCr86wk=

</pre></details>

**Comment by bhcleek** [comment]
Vim-go doesn't do anything special that would affect this. Can you `go build` the module in question?

Also, `[compiler BrokenImport] [E] could not import github.com/<org>/<repo>` doesn't look like an error from vim-go. Where are you seeing that?

**Comment by axsaucedo** [comment]
@bhcleek ah good spot, I needed to run `go build` good shout - closing as it's all working correctly now 👍
