### ISSUE TITLE
syntax: valid code is reported error by goHexadecimalError, goOctalError, goBinaryError

### ISSUE THREAD

**Issue by itchyny** [fatih/vim-go#3393]
### What did you do? (required: The issue will be **closed** when not provided)

Using the syntax of vim-go (checked both the version bundled by official Vim, and the latest version in this repo) and write the following Go code.
```go
package main

func main() {
        println(int(0x00+10) > 0)
        println(int(0o00-10) > 0)
        println(int(0b00/10) > 0)
}
```
### What did you expect to happen?
No syntax error is reported.

### What happened instead?
All of `0x00+10`, `0o00-10`, `0b00/10` are colored as error, due to `goHexadecimalError`, `goOctalError`, `goBinaryError`.
They are all valid (and gofmt-ted) code.

### Configuration (**MUST** fill this out):
Clone vim-go in /tmp; `git clone https://github.com/fatih/vim-go /tmp/vim-go`.
Save the Go code in `What did you do?` to `/tmp/main.go`.
Run `vim /tmp/main.go`.

#### vim-go version:
f42b069ffd4ba756461b717411595ffc7b2bccb2

####  `vimrc` you used to reproduce:
```vim
set runtimepath+=/tmp/vim-go
filetype plugin indent on
syntax enable
```

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 30 2022 20:12:27)
macOS version - arm64
Included patches: 1-4650
```

#### Go version (`go version`):
go version go1.18 darwin/arm64

#### Go environment
Not related.

#### gopls version
Not related.

**Comment by bhcleek** [comment]
Fixed in #3403

**Comment by itchyny** [comment]
Not still resolved for other operators?
```go
package main

func main() {
        println(bool(0x00==0))
        println(bool(0x00!=0))
        println(bool(0x00<=0))
        println(bool(0x00>=0))
}
```

**Comment by bhcleek** [comment]
No, because gofmt puts spaces around those operators. I only handled the errors for the sequences that gofmt does not modify.

**Comment by itchyny** [comment]
OK. How about shift operators?
```go
	println(int(0x00>>1 + 1))
	println(int(0x00<<1 + 1))
```

**Comment by bhcleek** [comment]
I'm removing these matches entirely; they're of limited utility, are incredibly difficult to identify with regular expressions, and other tooling identifies the problems.

ref: https://github.com/fatih/vim-go/pull/3404
