### ISSUE TITLE
Drop deprecated golint

### ISSUE THREAD

**Issue by 06kellyjac** [fatih/vim-go#3395]
`golint` has been deprecated for almost a year.

https://github.com/golang/go/issues/38968

Can it be removed from `vim-go` or at least make it more opt-in rather than default, especially with the tool installation.
Thanks

Related:

https://github.com/NixOS/nixpkgs/issues/167717

**Comment by bhcleek** [comment]
This is done nearly a year ago.

ref: https://github.com/fatih/vim-go/pull/3248

**Comment by 06kellyjac** [comment]
Nice but it still installs golint here:

https://github.com/fatih/vim-go/blob/master/plugin/go.vim#L49

And a reference should probably be removed:

https://github.com/fatih/vim-go/blob/master/README.md?plain=1#L27
