### ISSUE TITLE
leader close will quit vim

### ISSUE THREAD

**Issue by longwuyuan** [fatih/vim-go#3396]
### What did you do? (required: The issue will be **closed** when not provided)
Used the default shortcut for closing a file which is <leader> key "," and "c" for close.
Instead of only closing the file (buffer), neovim application quit/exited/terminated and returned back to shell prompt.

### Step to reproduce
- Use https://vim-bootstrap.com and choose go as language to generate init.vim for neovim
- Start neovim and use  :Pluginstall as well as :GoInstallBinaries
- Quit neovim
- Clone https://github.com/inancgumus/learngo
- cd into clone directory for leaerngo project
- Open any .go file
- Open a few other .go files
- Observe there are multiple tabs on top
- Observe you can switch between files using <leader> z
- Finally edit any one file and then try to close it after done editing. Use <leader> + "c" key shortcut
- See neovim quit

### What did you expect to happen?
Only the file should close (buffer delete event of neovim) and neovim should not quit/exit/terminate

### What happened instead?
Neovim quit/exited/terminated 

#### vim-go version:
v1.25

####  `vimrc` you used to reproduce:
- Use https://vim-bootstrap.com and choose go as language to generate init.vim for neovim
- Start neovim and :Pluginstall as well as GoInstallBinaries

#### Vim version (first three lines from `:version`):
% nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):
1.18

#### Go environment
```
% go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8r/sh679sz97b1csl8390ks4mt40000gn/T/go-build2574270583=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

#### gopls version
% gopls version
golang.org/x/tools/gopls v0.8.1
    golang.org/x/tools/gopls@v0.8.1 h1:q5nDpRopYrnF4DN/1o8ZQ7Oar4Yd4I5OtGMx5RyV2/8=

**Comment by bhcleek** [comment]
I'm not sure what's causing this for you, but it's not vim-go, vim-go does not include any that would close the editor like this. 

Run `:verbose map` to see where the `<Leader>c` mapping is defined.

**Comment by longwuyuan** [comment]
hi @bhcleek ,
Thank you very much for responding.
From running `:verbose map` I can see this
<img width="394" alt="image" src="https://user-images.githubusercontent.com/5085914/162759685-21fc52d0-f592-466d-a9fc-46cc68203733.png">

I also verified from the init.vim file
<img width="359" alt="image" src="https://user-images.githubusercontent.com/5085914/162760324-b891643a-ccd3-463c-b606-e0e9299a6b3d.png">

I think I am certain its not a behaviour added by vim-go. I am hoping someone who used vim-go can advise/suggest and also comment if using `:bd` or `:buffer delete`  does not terminate neovim for them but just closes the file/buffer. Because `:leader c` is shortcut for `:buffer delete`. Or how do others close a file, while multiple files are open.

**Comment by bhcleek** [comment]
You can read about the behavior of `:bdelete` (`:bd` is a short form of `:bdelete`) in the help with `:help :bd`.

If you have more questions, then Neovim's [discourse](https://neovim.discourse.group/), [StackOverflow](https://stackoverflow.com/questions/tagged/neovim), or [issues](https://github.com/neovim/neovim/issues) is a better place to ask than here.
