### ISSUE TITLE
Feature Request: Display variable and parameter types

### ISSUE THREAD

**Issue by mortymacs** [fatih/vim-go#3402]
In CLion IDE, when we define a function that accepts a reference, on the function call, it shows `&:` before the parameter to give a small hint that "it's a reference":
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1261448/163413554-d1bf8313-42dc-49da-8b33-ea5ddac68a53.png)
Or in Vim/NeoVim Rustlang plugin, it shows the variable types automatically like this (`>u32`):
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1261448/163413680-2d26e23c-9ce9-41ed-a337-6e502d0e589c.png)
Or this:
![image](https://user-images.githubusercontent.com/1261448/163414643-d6c352e1-5c5e-42ae-8aa2-e0c437fa2a4a.png)

These kinds of hints are read-only and I can't even select them.
It would be great to have this feature for Golang as well.

**Comment by bhcleek** [comment]
See `:help g:go_auto_type_info`

**Comment by mortymacs** [comment]
Thank you, @bhcleek 
It's not demonstrating like others. Others are always visible but `let g:go_auto_type_info = 1` is only visible when the cursor is on the variable.

**Comment by bhcleek** [comment]
I see. True, vim-go does it differently. I don't intend to implement what you've requested.
