### ISSUE TITLE
Allow golangci-lint to use per project .golangci.yml config files rather than globally specifying which linters to use.

### ISSUE THREAD

**Issue by colinnewell** [fatih/vim-go#3405]
### What did you do? (required: The issue will be **closed** when not provided)

Run `:GoMetaLinter`

### What did you expect to happen?

I expected this to provide equivalent output to me running `golangci-lint run` locally for that file.

### What happened instead?

I saw a different set of complaints to those produced locally.

Looking at the vim-go code it looks like it sets a default set of plugins out of the box, and allows a user to alter that config using the `g:go_metalinter_enabled` variable.  That is useful, but at the editor level.  I'd really like to make the most of the per project `.golangci.yml` config files I have specifying which plugins to use.

I suspect that the solution there is to not pass so many command line flags.  If you run the meta linter using `golangci-lint run` on it's own then it loads the config file.

I thought I could be cute and set the metalinter command to avoid that code path, and that half worked.  The problem is that it also bypassed the code that dealt with the output so that you could navigate to the affected lines.

```
let g:go_metalinter_command='golangci-lint run'
```
Ideally I guess I'd want a way to either set `g:go_metalinter_enabled` to a value that indicates that the linter config should come from config, or another variable to do the same sort of thing.

### Configuration (**MUST** fill this out):

```
let g:go_metalinter_command='golangci-lint'
```

#### vim-go version:

commit ac9c3628e8bdf20f1c1e12171c053852d616d8b7

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
let g:go_fmt_command = 'goimports'
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_rename_command='gopls'
    
let g:go_metalinter_command='golangci-lint'
"let g:go_metalinter_autosave = 1
        
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_extra_types = 1

filetype off
filetype plugin indent off
set runtimepath+=/usr/lib/go/misc/vim
filetype plugin indent on
syntax on
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 17 2021 16:55:33)
Included patches: 1-2434, 3402-3403, 3409, 3428, 3487, 3564, 3581-3582, 3611, 3613, 3612, 3625, 3669, 3741
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.17.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cnewell/.cache/go-build"
GOENV="/home/cnewell/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/cnewell/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="bitbucket.org/resumelibrary/*"
GOOS="linux"
GOPATH="/home/cnewell/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build941322651=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.3
    golang.org/x/tools/gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_command = 'goimports'
g:go_rename_command = 'gopls'
g:go_loaded_install = 1
g:go_def_mode = 'gopls'
g:go_highlight_function_calls = 1
g:go_jump_to_error = 1
g:go_metalinter_command = 'golangci-lint'
g:go_info_mode = 'gopls'
g:go_loaded_gosnippets = 1
g:go_highlight_extra_types = 1
g:go_highlight_fields = 1
g:go_highlight_functions = 1
g:go_highlight_types = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
You can set `g:go_metalinter_enabled` to an empty list and (e.g.`let g:go_metalinter_enabled=[]`) to accomplish this.

**Comment by colinnewell** [comment]
Sorry, I should have mentioned that I attempted that and it didn't have the desired effect.  I believe there are other command line flags being added that mean that the config I want to load isn't.

**Comment by bhcleek** [comment]
It does add a couple of command line flags. You can use `:let g:go_debug=['shell-comands']` to see how it's invoked.

How did your experience when using `g:go_metalinter_enabled=[]` vary from what you've asked for?

**Comment by colinnewell** [comment]
Thanks, that was really useful.  It's the `--exclude-use-default=false` flag that is causing the differences.

I've simplified the exact commands, but this was essentially the difference with this one file.

```
golangci-lint run --print-issued-lines=false --build-tags '' --exclude-use-default=false cmd/cron-outage
cmd/cron-outage/main.go:67:16: Error return value of `f.Close` is not checked (errcheck)
cmd/cron-outage/main.go:62:13: G304: Potential file inclusion via variable (gosec)
golangci-lint run --print-issued-lines=false --build-tags '' cmd/cron-outage
$
```

**Comment by bhcleek** [comment]
Yes, `--exclude-use-default` will continue to be provided by vim-go.

**Comment by colinnewell** [comment]
I guess the one thing I need in that case is an option to allow me to adjust that.  Perhaps a `golangci-lint` options config that allows that to be replaced with 0 or many alternative command line options?

That combined with the list of linters ought to allow me to get the behaviour to be pretty much stock for my config and allow me to configure it entirely by file.

**Comment by bhcleek** [comment]
I understand why you may want that, but there are some golangci-lint options that must be not be adjusted by vim-go users. You may disagree with the necessity of `--exclude-use-default=false`, but it's something that I feel quite strongly about. If you feel equally strongly in the other direction, then you can set the exclude patterns in your golangci-lint config explicitly.
