### ISSUE TITLE
Could not toggle breakpoint: could not find file

### ISSUE THREAD

**Issue by StandoffVenus** [fatih/vim-go#3407]
### What did you do? (required: The issue will be **closed** when not provided)

Ran `:GoDebugBreakpoint` in my `main.go` file, then executed `:GoDebugStart.`

### What did you expect to happen?

Debugging begins successfully and stops at breakpoint.

### What happened instead?

Delve starts properly but vim-go reports the following error:

```
vim-go: could not toggle breakpoint: could not find file /Users/mule/develop/code/duck-it/cmd/duckdns/main.go
```

Obviously, this file exists - I'm editing it.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" Go settings.
" Turn off gopls (coc.nvim already running)
let g:go_gopls_enabled = 0
let g:go_def_mapping_enabled = 0
let g:go_code_completion_enabled = 0
let g:go_auto_type_info = 0
let g:go_jump_to_error = 0
let g:go_fmt_autosave = 0
let g:go_mod_fmt_autosave = 0
let g:go_doc_keywordprg_enabled = 0
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_parameters = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1
let g:go_highlight_diagnostic_errors = 0
let g:go_highlight_diagnostic_warnings = 0

" Install Go binaries into home directory
" to avoid issues with Nix read-only paths
let g:go_bin_path="${home-directory}/.vim-go-binaries"
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 01 1980 00:00:00)
macOS version - arm64
Included patches: 1-4350

#### Go version (`go version`):

go version go1.17.7 darwin/arm64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/mule/Library/Caches/go-build"
GOENV="/Users/mule/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-mod=vendor -trimpath"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mule/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mule/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/q5w6zvg9s7z43iwz1lry6b1yrz9cg3i5-go-1.17.7/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/q5w6zvg9s7z43iwz1lry6b1yrz9cg3i5-go-1.17.7/share/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mule/develop/code/duck-it/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2142110257=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.3
    golang.org/x/tools/gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 0
g:go_bin_path = '/Users/mule/.vim-go-binaries'
g:go_highlight_diagnostic_errors = 0
g:go_highlight_extra_types = 1
g:go_highlight_variable_declarations = 1
g:go_highlight_operators = 1
g:go_code_completion_enabled = 0
g:go_debug_commands = [{'request': '{"id":4,"method":"RPCServer.CreateBreakpoint","params":[{"Breakpoint":{"file":"/Users/mule/develop/code/duck-it/cmd/duckdns/main.go","line":27}}]}'}, {'response': '{"id":4,"result":null,"error":"could not find file /Users/mule/develop/code/duck-it/cmd/duckdns/main.go"}'}, {'request': '{"id":5,"method":"RPCServer.Detach","params":[{"kill":true}]}'}, {'response': '{"id":5,"result":{},"error":null}'}, {'request': '{"id":6,"method":"RPCServer.CreateBreakpoint","params":[{"Breakpoint":{"file":"/Users/mule/develop/code/duck-it/cmd/duckdns/main.go","line":40}}]}'}, {'response': '{"id":6,"result":null,"error":"could not find file /Users/mule/develop/code/duck-it/cmd/duckdns/main.go"}'}, {'request': '{"id":7,"method":"RPCServer.Detach","params":[{"kill":true}]}'}, {'response': '{"id":7,"result":{},"error":null}'}]
g:go_highlight_function_calls = 1
g:go_fmt_autosave = 0
g:go_highlight_fields = 1
g:go_gopls_enabled = 0
g:go_debug = ['debugger-commands']
g:go_doc_keywordprg_enabled = 0
g:go_def_mapping_enabled = 0
g:go_highlight_variable_assignments = 1
g:go_highlight_function_parameters = 1
g:go_mod_fmt_autosave = 0
g:go_highlight_functions = 1
g:go_highlight_types = 1
g:go_highlight_diagnostic_warnings = 0
g:go_jump_to_error = 0
g:go_loaded_gosnippets = 1
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
This error is originating in delve, not with Vim-go. You can see in the `g:go_debug_commands` that delve thinks the file doesn't exist:
```
g:go_debug_commands = [{'request': '{"id":4,"method":"RPCServer.CreateBreakpoint","params":[{"Breakpoint":{"file":"/Users/mule/develop/code/duck-it/cmd/duckdns/main.go","line":27}}]}'}, {'response': '{"id":4,"result":null,"error":"could not find file /Users/mule/develop/code/duck-it/cmd/duckdns/main.go"}'}, {'request': '{"id":5,"method":"RPCServer.Detach","params":[{"kill":true}]}'}, {'response': '{"id":5,"result":{},"error":null}'}, {'request': '{"id":6,"method":"RPCServer.CreateBreakpoint","params":[{"Breakpoint":{"file":"/Users/mule/develop/code/duck-it/cmd/duckdns/main.go","line":40}}]}'}, {'response': '{"id":6,"result":null,"error":"could not find file /Users/mule/develop/code/duck-it/cmd/duckdns/main.go"}'}, {'request': '{"id":7,"method":"RPCServer.Detach","params":[{"kill":true}]}'}, {'response': '{"id":7,"result":{},"error":null}'}]
```

**Comment by StandoffVenus** [comment]
Thanks for the quick response! Do you suggest I open this with Delve?

**Comment by bhcleek** [comment]
Does `/Users/mule/develop/code/duck-it/cmd/duckdns/main.go` exist on disk? Is that casing correct?

**Comment by StandoffVenus** [comment]
It does, casing and all - I'm launching `:GoDebugStart` from within that file.

**Comment by bhcleek** [comment]
Can you debug your application with the delve CLI, `dlv` ?

**Comment by StandoffVenus** [comment]
So, `dlv` does complain about the same issue if I try to set a breakpoint via
```
dlv> b Test /Users/mule/develop/code/duck-it/cmd/duckdns/main.go:27
Command failed: location "/Users/mule/develop/code/duck-it/cmd/duckdns/main.go:27" not found
```

However, important to note that if I instead execute
```
dlv> b Test main.go:27
```

The breakpoint is set successfully. Maybe Delve is evaluating the path relative to the file it's started from, rather than allowing absolute paths.

**Comment by bhcleek** [comment]
That's interesting. Delve handles absolute paths AFAIK.

Are any elements in the path a symlink?

**Comment by StandoffVenus** [comment]
The paths shouldn't be, but that being said, I am using Nix to manage my project so the relevant Go binaries themselves (other than those installed by vim-go) are symlinked.

**Comment by bhcleek** [comment]
I don't think that would be a concern.

Do other features of vim-go work correctly (e.g. jumping to a definition)?

**Comment by StandoffVenus** [comment]
I use coc-go for that functionality, but I disabled it and vim-go features function correctly.

**Comment by bhcleek** [comment]
Ok. Then let's see if `:GoUpdateBinaries dlv` solves this. If it doesn't, then I think it's appropriate to focus on using the Delve CLI, `dlv` and creating an issue with github.com/go-delve/delve.

**Comment by StandoffVenus** [comment]
Still no luck - I'll follow up with Delve directly. Thanks!

**Comment by StandoffVenus** [comment]
Wanted to follow up on this - not sure if you can do anything to handle it, though.

Over at the Delve [issue](https://github.com/go-delve/delve/issues/2992), aazilli noted that my `GOFLAGS` were probably messed up some how. Turns out the Nix `buildGoModule` derivation can set `-trimpath` based on a configuration parameter, which just so happens to cause this weird issue.

If I had to assume, vim-go is using the absolute path when executing Delve commands? Since the path is being trimmed, though, those absolute paths don't appear to exist to Delve. Can vim-go be updated to handle this flag?

**Comment by bhcleek** [comment]
There's nothing for vim-go to do here. Vim-go and `dlv` are properly leveraging `GOFLAGS`.

It looks like you have several options available to you. There's a `buildGoModule` option, `allowGoReference`, to cause Nix to elide the `-trimpath` from ` GOFLAGS. It also looks like there may be a way to use a hook to modify some things, but I'm not a Nix expert and I may be misunderstanding the `buildGoModule` source. I'm not sure how Nix deals with `GOFLAGS`, but it _looks_ like it may not respect the user's manual configuration of `GOFLAGS`. If that's the case, then I'd humbly submit that there's an issue with `buildGoModule`.

**Comment by StandoffVenus** [comment]
Setting `allowGoReference = true;` has sufficed for now. However, how would one be able to set breakpoints in vim-go if `-trimpath` is set? Shouldn't vim-go be passing a different path to `dlv`? Perhaps I'm misunderstanding.

**Comment by bhcleek** [comment]
One could set up `g:go_debug_substitute_paths`. But normally `-trimpath` is not set and if it is set, then presumably the user has done so intentionally. Typically, it wouldn't be used during the development process and would only be set when producing a binary that is intended for release (i.e. not during the development process).

**Comment by StandoffVenus** [comment]
That makes more sense to me - if I'm fully understanding, debugging in with `-trimpath` set is essentially pointless/erroneous to begin with.
