### ISSUE TITLE
How to auto generate return values from any function

### ISSUE THREAD

**Issue by shj00007** [fatih/vim-go#3408]
Is there any way to generate return values from any function with cammand or shortcut

#### Vim version (first three lines from `:version`):

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.18 darwin/arm64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/shj00007/Library/Caches/go-build"
GOENV="/Users/shj00007/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxxx/.gvm/pkgsets/go1.18/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxxx/.gvm/pkgsets/go1.18/global"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/xxxx/.gvm/gos/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/xxxx/.gvm/gos/go1.18/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxxx/dev/company/easy/gentry-mnp-server/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v4/jjnlkpws4l52f7jv1f4st0p80000gn/T/go-build3791937576=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.1
    golang.org/x/tools/gopls@v0.8.1 h1:q5nDpRopYrnF4DN/1o8ZQ7Oar4Yd4I5OtGMx5RyV2/8=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_updatetime = 800
g:go_highlight_function_calls = 1
g:go_fmt_autosave = 0
g:go_term_enabled = 1
g:go_highlight_fields = 1
g:go_addtags_transform = 'camelcase'
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_highlight_types = 1
g:go_jump_to_error = 1
g:go_imports_autosave = 0
g:go_loaded_gosnippets = 1
g:go_term_mode = 'vsplit'
g:go_loaded_install = 1
g:go_term_reuse = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
There is no official support for that in vim-go.
