### ISSUE TITLE
:GoInstallBinaries doesn't work with Vundle installations

### ISSUE THREAD

**Issue by nestoroprysk** [fatih/vim-go#3410]
I'm using go1.18.1 and installed vim-go with Vundle, but :GoInstallBinaries didn't work because the command was calling "go get".

With the manual installation all works (:GoInstallBinaries calls "go install", which is correct), so I suspect that Vundle installs outdated version of vim-go.

**Comment by bhcleek** [comment]
This seems like a problem with Vundle, not with vim-go. Since you've provided no information about your vimrc it's impossible to know if the problem is in your setup.
