### ISSUE TITLE
How can I :GoRun or :GoTest in the correct project root directory?

### ISSUE THREAD

**Issue by systemmonkey42** [fatih/vim-go#3411]
How do I prevent vim-go changing directory when running go?

When I am editing a module in a sub-directory, the :GoRun command becomes
useless because the project is structured so "go run" must be done from the root
of the project, which is also where I launch VIM from.

Can you add a flag to disable all the calls to "chdir()" ?

Thanks.

**Comment by bhcleek** [comment]
> How do I prevent vim-go changing directory when running go?

You don't. When `:GoRun` is executed, it's implicit that the package to be run is the package that contains the current buffer.

`:GoRun` accepts arguments; you can specify the package by providing its import path to `:GoRun` if you'd like.

> Can you add a flag to disable all the calls to "chdir()" ?

No. This would violate a number of principles in vim-go and Vim generally (namely that operations are done in the context of the current buffer, but you can accomplish what you're after by providing the import path of the package that you want to `go run` to `:GoRun` or by executing `:GoRun` from the buffer of a file in the package that you want to `go run`.
