### ISSUE TITLE
Issue with interface types when using go 1.18 and "any".

### ISSUE THREAD

**Issue by systemmonkey42** [fatih/vim-go#3412]
### What did you do? (required: The issue will be **closed** when not provided)

I'm having a specific issue with go `1.18`, and a module which uses an interface which changed in 1.18.

The code builds and runs fine, but I cannot get vim-go to accept it.

The moment I switch to `go 1.17.10`, the code still builds, and the vim warning goes away.

I tried rebuilding all the tools with go 1.17, but that didn't resolve the issue.

The following code fragment, from the gorm.io/gorm tutorial, shows how a new "logger" can be created,

```
	newLogger := logger.New(
		log.New(os.Stdout, "\r\n", log.LstdFlags),
		logger.Config{
			SlowThreshold:             time.Second,
			LogLevel:                  logger.Info,
			IgnoreRecordNotFoundError: true,
			Colorful:                  false,
		},
	)
```
The error is as follows;
```
[compiler] cannot use log.New(os.Stdout, "\r\n", log.LstdFlags) (value of type *log.Logger) as logger.Writer value in argument to logger.New: wrong type for method Printf (have func(format string, v ...invalid type), want func(string, ...interface{}))
```

The interface for logger.New( ) requires looks like
```
type logger interface {
    Printf(string, ...interface{})
}
```
While the `go 1.18` logger wants
```
func Printf(string, ...any)
```

While this compiles ok, I can't seem to get vim-go to stop complaining about it.

Any idea's?

Thanks

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
let g:go_disable_autoinstall = 0
"let g:go_fmt_autosave = 0
let g:go_fmt_command = 'gofmt'
"let g:go_fmt_command = "goimports"

" Highlight
let g:go_highlight_types = 0
let g:go_highlight_extra_types = 0
let g:go_highlight_fields = 0
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 0
let g:go_highlight_variable_assignments = 0
let g:go_highlight_diagnostic_errors = 1
let g:go_highlight_diagnostic_warnings = 1
let g:go_addtags_transform = 'snakecase'
let g:go_addtags_skip_unexported = 0

let g:go_doc_keywordprg_enabled = 0
let g:go_gopls_enabled = 1

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 19 2022 09:16:46)
Included patches: 1-4980
#### Go version (`go version`):

go version go1.18.2 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/navtrix/go/bin"
GOCACHE="/home/sm42/.cache/go-build"
GOENV="/home/sm42/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="gitx.cf"
GONOSUMDB="gitx.cf"
GOOS="linux"
GOPATH="/home/sm42/go"
GOPRIVATE="gitx.cf"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4218113669=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.3
    golang.org/x/tools/gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=
</pre></details>

**Comment by bhcleek** [comment]
> I tried rebuilding all the tools with go 1.17, but that didn't resolve the issue.

Since you're trying to get this to work with Go 1.18, rebuild them with Go 1.18, not Go 1.17.

> While this compiles ok, I can't seem to get vim-go to stop complaining about it.

Ultimately, this error is not coming from vim-go; vim-go is only surfacing the error that another tools is providing.

> [compiler] cannot use log.New(os.Stdout, "\r\n", log.LstdFlags) (value of type *log.Logger) as logger.Writer value in argument to logger.New: wrong type for method Printf (have func(format string, v ...invalid type), want func(string, ...interface{}))

That error doesn't look like a vim-go error.  Where are you seeing that? What command or operation are you executing that triggers it?

Also, the fact that it says `invalid type` there implies one or more of the following:
1. The tool that's the source of the error wasn't built with Go 1.18
2. Your module's `go` directive in `go.mod` isn't `go 1.18`

> let g:go_disable_autoinstall = 0

What is this? It's not a vim-go config value; are you sure you're using vim-go?

**Comment by systemmonkey42** [comment]
> > [compiler] cannot use log.New(os.Stdout, "\r\n", log.LstdFlags) (value of type *log.Logger) as logger.Writer value in argument to logger.New: wrong type for method Printf (have func(format string, v ...invalid type), want func(string, ...interface{}))
> 
> That error doesn't look like a vim-go error. Where are you seeing that? What command or operation are you executing that triggers it?

Now you have me worried.  I can't reproduce it today, so lets consider it a local issue.

> >let g:go_disable_autoinstall = 0
> What is this? It's not a vim-go config value; are you sure you're using vim-go?

My apologies, it was apparently deprecated in commit 7c0fce5f some time ago.

If you are new to the project, I understand if you might not have heard of it.
