### ISSUE TITLE
Vim-go autocompletion overlaps with nvim-lsp

### ISSUE THREAD

**Issue by noisersup** [fatih/vim-go#3418]
### What did you do? (required: The issue will be **closed** when not provided)
I always used vim-go for things like syntax highlighting, go-def, go-ref, etc. But for an autocompletion I used native nvim-lsp.
After updating vim-go, when I type something, my nvim-lsp window pops up, but after trying to choose specific entry in it (with <c-p> and <c-n>), a window is replaced by vim-go window. I tried to find a solution in documentation, issues and manpages and set `g.go_code_completion_enabled = 0`.

### What did you expect to happen?
After pressing <c-p> my nvim-lsp completion should move cursor to the next entry
### What happened instead?
After pressing <c-p> the vim-go window popped-out in place of nvim-lsp
### Configuration (**MUST** fill this out):
```lua
g.go_code_completion_enabled = 0
g.go_def_mode='gopls'
g.go_info_mode='gopls'
g.go_fmt_command = "goimports"
```
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.18.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/dlpbgh2hqzk83gs4xhz3r1b0x24hfcpw-go-1.18.2/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/dlpbgh2hqzk83gs4xhz3r1b0x24hfcpw-go-1.18.2/share/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2062328024=/tmp/go-build -gno-record-gcc-switches"
```

#### gopls version
<details><summary><code>gopls version</code> Output:

</pre></details>
`golang.org/x/tools/gopls v0.8.3
    golang.org/x/tools/gopls@(devel)`

**Comment by noisersup** [comment]
Described behavior:
![output](https://user-images.githubusercontent.com/42322511/170888030-315d8167-b11e-4c8e-b153-dc8e02b406bd.gif)

**Comment by bhcleek** [comment]
Vim-go's autocompletion is not hooked up automatically, and even when one does hook it up, it doesn't trigger automatically. Additionally, that second window doesn't look like a vim-go autocompletion window from vim-go.

Vim-go's autocompletion is normally wired up by setting `omnifunc` (see `:help omnifunc`) and required a mapping to be triggered to use (by default those keys are `ctrl-X,ctrl-O`). There are some plugins that will trigger `omnifunc` without using the mapping, though (e.g. SuperTab, YouCompleteMe, deoplete, etc.).

This looks like an issue with your configuration and not within vim-go's control.

**Comment by noisersup** [comment]
I thought that the bottom line was formated very similar to other vim-go functions, but if that's not vim-go - then I'm closing. Sorry for unnecessary issue and thank you for your explanation!

**Comment by bhcleek** [comment]
It looks like you may be dealing with keyword completion, which is still yet another means of completion available in Vim. See `:help ins-completion`).

**Comment by noisersup** [comment]
Thank you so much for help! I found that the problem was in fact that nvim-cmp engine removed <c-p> and <c-n> as a default keybindings.
