### ISSUE TITLE
Vim syntax highlighting is very minimal

### ISSUE THREAD

**Issue by sbvalois** [fatih/vim-go#3419]
### What did you do? (required: The issue will be **closed** when not provided)
Tried multiple themes, found this old issue: https://github.com/fatih/vim-go/issues/316#issuecomment-74412071
Compared with VSCode syntax highlighting which seems a lot better

### What did you expect to happen?
Just better syntax highlighting 
### What happened instead?
Very minor syntax highlighting
### Configuration (**MUST** fill this out):
Not sure what configuration is needed. Its a fresh install with the commands in the url above included.
#### vim-go version:
Not sure. Installed with PlugInstall
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 20 2022 18:55:37)
macOS version - arm64
Inkluderte patcher: 1-4800

#### Go version (`go version`):

go version go1.17 darwin/amd64

#### Go environment
<details><summary><code>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/stephan/Library/Caches/go-build"
GOENV="/Users/stephan/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/stephan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/stephan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/usr/local/go/misc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4x/1nq8ygdj2fngfr1y0h4kkl3m0000gn/T/go-build2526523666=/tmp/go-build -gno-record-gcc-switches -fno-common"
</code></summary><br><pre>

</pre></details>

Vim syntax highlighting:
![vim highlight](https://user-images.githubusercontent.com/83061036/171160245-ab4a826f-7e2f-45cd-9560-d86ad5c49d85.png)

Vscode syntax highlighting:
![vscode highlight](https://user-images.githubusercontent.com/83061036/171160250-07caf4d8-7680-417e-adb3-c9f8f5d7beb4.png)

**Comment by bhcleek** [comment]
The out of the box syntax highlighting is minimal, but many more elements can be highlighted by setting vim-go options. See `:help go-syntax`.

**Comment by sbvalois** [comment]
Ah that's awesome. Thanks!
