### ISSUE TITLE
"no packages returned: packages.Load error" or "no object found for ident myfunc" when we have build tags

### ISSUE THREAD

**Issue by vitaly-zdanevich** [fatih/vim-go#3420]
Ctrl-click for go to definition, when file contains build tag like
`//go:build unit_tests`

Looks like this is because of this issue https://github.com/golang/go/issues/29202

Try this two files:

```
//go:build unit_tests

package main

func main() {
	Myfunc()
}
```

```
package main

import "fmt"

func Myfunc() {
	fmt.Println("vim-go")
}
```

But maybe we can have some workaround?

#### vim-go version: 
1.26

#### Vim version:

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  4 2022 12:05:28)
Included patches: 1-4328
Modified by Gentoo-8.2.4328-r1

#### Go version (`go version`):

go version go1.18.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vitaly/.cache/go-build"
GOENV="/home/vitaly/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-tags=linux"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vitaly/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vitaly/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/vitaly/projects/river-island/svi-services/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3452794331=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.4
    golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_gosnippets = 1
g:go_jump_to_error = 1
g:go_fmt_options = {'gofmt': '-s', 'goimports': '-local github.com/River-Island'}
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:OFF
</pre></details>

**Comment by bhcleek** [comment]
If you'll set the build tags, then this will work as you expect. See `help :GoBuildTags` and `:help g:go_build_tags`

**Comment by vitaly-zdanevich** [comment]
For example, what should I add?

**Comment by vitaly-zdanevich** [comment]
Tried `GoBuildTags linux`: still the same error on Ctrl+click.

**Comment by vitaly-zdanevich** [comment]
Hm, maybe vim-go can do it for me, for every buffer?

**Comment by bhcleek** [comment]
That would be difficult to pull off without causing problems. Consider cases where files have different implementations of functions. e.g.:

file1:
```
//go:build sandbox

func work() { ... }
```

file2:
//go:build !sandbox

func work() { ... }
```

**Comment by lcarva** [comment]
This [suggestion](https://politreco.com/2019/04/per-project-configuration-for-vim/) to create a per-project config helped in my case.
