### ISSUE TITLE
`'go env GOBIN' failed` on Windows when `shell` set to `pwsh.exe`

### ISSUE THREAD

**Issue by zb140** [fatih/vim-go#3421]
### What did you do? (required: The issue will be **closed** when not provided)
Set `shell` to `pwsh.exe` in `.vimrc` and open a Go file.  The error message `'go env GOBIN' failed` is displayed several times.

The issue seems to be that [`s:system`](https://github.com/fatih/vim-go/blob/master/autoload/go/util.vim#L181) always forces `shell` to `$COMSPEC` on Windows, but `shell` is left as-is `shellescape` (called by [`go#util#Shelljoin`](https://github.com/fatih/vim-go/blob/master/autoload/go/util.vim#L300)).  `shellescape` unfortunately has different behavior for `pwsh.exe` vs `cmd.exe`, so the call to `s:system` ultimately fails.

I have been able to work around this locally by adding some code to `go#util#Shelljoin` to similarly force `shell` to `$COMSPEC`, but I'm not sure if that's really the best long-term solution.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
set shell=pwsh.exe
```
</details>

#### Vim version (first three lines from `:version`):

I don't know how to copy the `:version` output. It's Vim 8.2, Windows 64-bit GUI/console version with OLE support, included patches 1-3908.

#### Go version (`go version`):

go version go1.18.3 windows/amd64                                                                                                                                                          

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

set GO111MODULE=                                                                                                                                                                           set GOARCH=amd64                                                                                                                                                                           set GOBIN=C:\Users\zb\go\bin                                                                                                                                                               set GOCACHE=C:\Users\zb\AppData\Local\go-build                                                                                                                                             set GOENV=C:\Users\zb\AppData\Roaming\go\env                                                                                                                                               set GOEXE=.exe                                                                                                                                                                             set GOEXPERIMENT=                                                                                                                                                                          set GOFLAGS=                                                                                                                                                                               set GOHOSTARCH=amd64                                                                                                                                                                       set GOHOSTOS=windows                                                                                                                                                                       set GOINSECURE=                                                                                                                                                                            set GOMODCACHE=C:\Users\zb\go\pkg\mod                                                                                                                                                      set GONOPROXY=                                                                                                                                                                             set GONOSUMDB=                                                                                                                                                                             set GOOS=windows                                                                                                                                                                           set GOPATH=C:\Users\zb\go                                                                                                                                                                  set GOPRIVATE=                                                                                                                                                                             set GOPROXY=https://proxy.golang.org,direct                                                                                                                                                set GOROOT=C:\Program Files\Go                                                                                                                                                             set GOSUMDB=sum.golang.org                                                                                                                                                                 set GOTMPDIR=                                                                                                                                                                              set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64                                                                                                                                   set GOVCS=                                                                                                                                                                                 set GOVERSION=go1.18.3                                                                                                                                                                     set GCCGO=gccgo                                                                                                                                                                            set GOAMD64=v1                                                                                                                                                                             set AR=ar                                                                                                                                                                                  set CC=gcc                                                                                                                                                                                 set CXX=g++                                                                                                                                                                                set CGO_ENABLED=1                                                                                                                                                                          set GOMOD=NUL                                                                                                                                                                              set GOWORK=                                                                                                                                                                                set CGO_CFLAGS=-g -O2                                                                                                                                                                      set CGO_CPPFLAGS=                                                                                                                                                                          set CGO_CXXFLAGS=-g -O2                                                                                                                                                                    set CGO_FFLAGS=-g -O2                                                                                                                                                                      set CGO_LDFLAGS=-g -O2                                                                                                                                                                     set PKG_CONFIG=pkg-config                                                                                                                                                                  set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\zb\AppData\Local\Temp\go-build2553547868=/tmp/go-build -gno-record-gcc-switches
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.4                                                                                                                                                                golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=    
</pre></details>

**Comment by bhcleek** [comment]
Can you give https://github.com/fatih/vim-go/pull/3422 a try to see if it fixes the issues you're seeing. I'd also be interested to know if `:GoBuild` and `:GoTest` also continue to work (ideally, each with and without additional arguments).

**Comment by zb140** [comment]
Thanks for the quick (likely) fix!  Looking at the change, I'm confident it will work. It's late in my timezone, but I'll be happy to give it a proper test tomorrow.

**Comment by zb140** [comment]
@bhcleek I gave it a try and as far as I can tell it works great. No more errors opening files, and `:GoBuild` and `:GoTest` seem to work as expected, with and without arguments (though I will admit I was not previously a heavy user of those particular features, so I suppose it's theoretically possible I missed a subtlety).

Thanks again for the quick fix!
