### ISSUE TITLE
host mem cost of gopls while using vim-go and gopls

### ISSUE THREAD

**Issue by ltx0621** [fatih/vim-go#3424]
### What did you do? (required: The issue will be **closed** when not provided)
1. open a project on mac using vim-go
2. try the gopls's 'go-define' several times

### What did you expect to happen?
anything's fine,such as mem-cost,cpu-cost is low

### What happened instead?
high mem cost
![image](https://user-images.githubusercontent.com/68268901/173013172-23601457-3770-4cef-9960-02e603ee16d2.png)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
colorscheme molokai

set t_Co=256
let g:molokai_original = 1
let g:rehash256 = 1

syntax enable
syntax on


set tabstop=4
set softtabstop=4
set shiftwidth=4

set nocompatible
set backspace=indent,eol,start


set autoindent
set smartindent


set cscopetag
set hlsearch

set number

au BufWinLeave * silent mkview
au BufWinEnter * silent loadview

inoremap ' ''<ESC>i
inoremap " ""<ESC>i
inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i

"imap <C-Space> <C-x><C-o>
imap <F2> <C-x><C-o>

nmap <F4> :TagbarToggle<CR>
"let g:tagbar_autopreview = 1 
let g:tagbar_sort = 0 
"let g:tagbar_left = 1 
let g:tagbar_width = 30 
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

autocmd FileType go nnoremap <buffer> gd :call GodefUnderCursor()<cr>
autocmd FileType go nnoremap <buffer> <C-]> :call GodefUnderCursor()<cr>
let g:godef_split=3    
let g:godef_same_file_in_same_window=1   

let g:go_fmt_command = "goimports"
let g:goimports = 1
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'fatih/vim-go'
Plugin 'scrooloose/nerdtree'
Plugin 'majutsushi/tagbar'
"Use release branch (recommend)
Plugin 'neoclide/coc.nvim'

"Plugin 'prabirshrestha/vim-lsp'

"Plugin 'SirVer/ultisnips'

Plugin 'honza/vim-snippets'

call vundle#end()
filetype plugin indent on

let mapleader = "\<space>"


autocmd VimEnter * NERDTree
nnoremap <leader>b :NERDTreeToggle<CR>

let g:NERDTreeDirArrowExpandable = '▸'

let g:NERDTreeDirArrowCollapsible = '▾'

let NERDTreeShowLineNumbers=1

let NERDTreeAutoCenter=1

let NERDTreeShowHidden=1

let NERDTreeWinSize=31

let NERDTreeIgnore=['\.pyc','\~$','\.swp','\.git']



let g:airline#extensions#tabline#enabled = 1


let g:airline#extensions#tabline#buffer_idx_mode = 1
 nmap <leader>1 <Plug>AirlineSelectTab1
 nmap <leader>2 <Plug>AirlineSelectTab2
 nmap <leader>3 <Plug>AirlineSelectTab3
 nmap <leader>4 <Plug>AirlineSelectTab4
 nmap <leader>5 <Plug>AirlineSelectTab5
 nmap <leader>6 <Plug>AirlineSelectTab6
 nmap <leader>7 <Plug>AirlineSelectTab7
 nmap <leader>8 <Plug>AirlineSelectTab8
 nmap <leader>9 <Plug>AirlineSelectTab9
 nmap <leader>0 <Plug>AirlineSelectTab0
 nmap <leader>h <Plug>AirlineSelectPrevTab
 nmap <leader>l <Plug>AirlineSelectNextTab

 nmap <leader>d :NERDTreeToggle<CR>:w<CR>:bdelete<CR>:NERDTreeToggle<CR><C-w>w

set nobackup
set nowritebackup

set updatetime=300

set cmdheight=2


nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)

nmap <silent> gr <Plug>(coc-references)


nnoremap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

autocmd CursorHold * silent call CocActionAsync('highlight')


nmap <leader>rn <Plug>(coc-rename)


inoremap <silent><expr> <c-l> coc#refresh()

inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"


inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <M-k> "\<C-p>"
inoremap <silent><expr> <M-j> "\<C-n>"


xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)


nmap <leader>qf  <Plug>(coc-fix-current)


nmap <silent> <M-k> <Plug>(coc-diagnostic-prev)
nmap <silent> <M-j> <Plug>(coc-diagnostic-next)


autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')
" =================================================================


"let g:go_gopls_options = ['-remote=auto']
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'


nnoremap <leader>' :ter<CR>
nnoremap <leader>" :vert ter<CR>

tnoremap <C-N> <C-\><C-N>

tnoremap <C-Q> exit<CR>

nnoremap <leader>h :noh<CR>
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 17 2021 18:32:08)
macOS version - x86_64
Included patches: 1-2671, 3402, 3409, 3428, 3489

#### Go version (`go version`):

go version go1.18.3 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ltx/Library/Caches/go-build"
GOENV="/Users/ltx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ltx/go/pkg/mod"
GONOPROXY="git.querycap.com"
GONOSUMDB="git.querycap.com"
GOOS="darwin"
GOPATH="/Users/ltx/go"
GOPRIVATE="git.querycap.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/usr/local/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ld/c3fkhh2n42jcw85td138zt5m0000gn/T/go-build2836965879=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.4
    golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_highlight_extra_types = 1
g:go_highlight_trailing_whitespace_error = 1
g:go_def_mode = 'gopls'
g:go_info_mode = 'gopls'
g:go_highlight_chan_whitespace_error = 1
g:go_gotags_bin = 'gotags'
g:go_highlight_space_tab_error = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
The amount of memory used by gopls will depend on several factors, including the size of the module that's being used. Having said that, a 1GB of memory isn't that much. Issues with `gopls` performance should generally be created in golang/go, not with vim-go.
