### ISSUE TITLE
goimports do nothing

### ISSUE THREAD

**Issue by vitaly-zdanevich** [fatih/vim-go#3428]
### What did you do?

Save file, or call `:GoImports`.

### What did you expect to happen?

To have imports of our internal libs after all other imports - the last in list, the same as the result of

`goimports -local github.com/companyname path/to/file.go`

### What happened instead?

Nothing.

### Configuration:

let g:go_fmt_options = {
\ 'gofmt': '-s',
\ 'goimports': '-local github.com/companyname',
\ }

#### vim-go version:

1.26

#### Vim version:

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  4 2022 08:45:02)
Included patches: 1-4586
Modified by Gentoo-8.2.4586

#### Go version (`go version`):

go version go1.18.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vitaly/.cache/go-build"
GOENV="/home/vitaly/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vitaly/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vitaly/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3866731994=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.4
    golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_fmt_options = {'gofmt': '-s', 'goimports': '-local github.com/companyname'}
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:OFF
</pre></details>

**Comment by bhcleek** [comment]
`gopls` is the default for `g:go_fmt_command`, therefore you'll need to set `g:go_gopls_local` appropriately (e.g. `set g:go_gopls_local='github.com/companyname'`). See `:help g:go_gopls_local`.
