### ISSUE TITLE
Package imports ordering

### ISSUE THREAD

**Issue by fedemengo** [fatih/vim-go#3431]
### What did you do? (required: The issue will be **closed** when not provided)

When saving a file, the plugin correctly imports used and missing packages

### What did you expect to happen?

I was wondering if there is an option to organize import in the following way

Assume I'm working on package `github.com/fedemengo/my-package`

```go
import (
    "fmt"

    "github.com/userA/packageA"
    "github.com/userB/packageB"

    "github.com/fedemengo/my-package/internal/type"
    "github.com/fedemengo/my-package/internal/log"
)
```

### What happened instead?

```go
import (
    "fmt"

    "github.com/fedemengo/my-package/internal/type"
    "github.com/fedemengo/my-package/internal/log"
    "github.com/userA/packageA"
    "github.com/userB/packageB"
)
```
Basically the package I'm working on and all other non-standard packages are treated the same way. I understand there is no real benefit to this but it would be nice to have. If you think it's not too much work I can help.

#### vim-go version:

v1.26

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.18.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/.go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/me/path/to/repo/v2/pkg/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qz/65z_v2412j9b2mlz75nmc3yc0000gp/T/go-build1568010270=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.9.0
    golang.org/x/tools/gopls@v0.9.0 h1:nEKQdO89Fkt4QTCN1xXkZzYHWZoBvIhkjJMpUaqRKUU=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_gotags_bin = 'gotags'
g:go_gopls_enabled = 0
g:go_loaded_gosnippets = 1
g:go_def_mode = 'gopls'
g:go_info_mode = 'gopls'
g:go_def_mapping_enabled = 0
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Yes. With your configuration, the `g:go_fmt_options` will allow you to do that. See `:help 'g:go_fmt_options'`.

**Comment by fedemengo** [comment]
Thanks, unfortunately I can only have three groups, `standard, external, company` (which is what I posted in the issue) but I this issue is more related to gofmt rather than vim-go
