### ISSUE TITLE
feature: Add a go-enum tool

### ISSUE THREAD

**Issue by dzfrias** [fatih/vim-go#3439]
## Feature
There's a pretty handy tool, [go-enum](https://github.com/abice/go-enum), that generates enums for you based on a comment. I don't know if there's a place for adding new commands to vim-go, but this would be nice to add to the collection.

I made a rough draft implementation in pure vimscript, but if the original version is preferred I can work on a PR for that too. I'm not really sure if vim-go is accepting these types of features at this stage, but in the case it is I'm happy to start working on it.

**Comment by bhcleek** [comment]
Vim-go effectively already supports this. `go-enum` requires using `go generate`, and vim-go already has a `:GoGenerate` command that you can use.

**Comment by dzfrias** [comment]
Ah I see. I should've read more about `:GoGenerate`. Thanks for your help either way!
