### ISSUE TITLE
Strange symbols instead spaces

### ISSUE THREAD

**Issue by Mehonoshin** [fatih/vim-go#344]
Hi!

I've just started using your plugin and Go in general, and I faced a strange issue.
Actually I don't know how to describe it better, just check out screenshot
http://monosnap.com/image/Ocjc0bImTcs0nFCFk5qVfQuylRrt7Z

When I add two spaces for identing, my vim shows strange angle bracket symbol with dot.

It's quite annoying, anybody knows how to fix it?

**Comment by fatih** [comment]
This is calles `listchars`. You probably enabled something in your vimrc :)

http://stackoverflow.com/questions/15527870/codefolding-indent-guides-in-vim

Closing this issue, as this is not vim-go related.

**Comment by Mehonoshin** [comment]
It affects only *.go files with enabled vim-go

**Comment by fatih** [comment]
Give a link to your vimrc so I can have a look. This is not vim-go related. We don't have anything related that changes how something looks.  Did you enabled syntax highlighting errors? Or something else ?

**Comment by Mehonoshin** [comment]
https://gist.github.com/Mehonoshin/da7379d26e143e7f5cf0
When I use tab in ruby sources, all if fine, tabs are converted into 2 spaces.
In go sources tabs are highlighted

**Comment by fatih** [comment]
Can you add these and try again:

```
let g:go_highlight_space_tab_error = 0
let g:go_highlight_array_whitespace_error = 0
let g:go_highlight_trailing_whitespace_error = 0
let g:go_highlight_space_tab_error = 0
```

This disables some of the syntax error highlightings. Feel free to play with those.

**Comment by Mehonoshin** [comment]
Thanks, for info.

**Comment by fatih** [comment]
Did it solve your problem?

**Comment by Mehonoshin** [comment]
Actually not, I'm still having tabs instead of spaces, and they are still highlighted.

**Comment by Mehonoshin** [comment]
The problem is that in *.go files tabs are not present as two spaces.

**Comment by Mehonoshin** [comment]
Why it disables expandtab?
https://github.com/fatih/vim-go/blob/master/ftplugin/go.vim#L19

**Comment by le0nik** [comment]
+1, why do you force users use tabs instead of spaces?

**Comment by Wizmann** [comment]
> I have set expandtab set in my .vimrc, but it doesn't work because the plugin overrides it.

+1

**Comment by include** [comment]
+1

**Comment by alexahn** [comment]
+1

**Comment by ly-william** [comment]
@Wizmann How did you do to disable tabs ? Tried to remove the line of change it by `setlocal setexpandtab` but it doesn't seem to work for me.

**Comment by samedson** [comment]
@fatih why force users to use tabs when many programmers prefer spaces? I have to edit vim-go to disable tabs, which is a huge pain because every time I update the plugin it gives me an error from of uncommitted changes (using Vundle). I would rather have a setting to use spaces instead, or allow my .vimrc to override the plugin (like any other normal vim plugin). The plugin should not override my .vimrc.

**Comment by fatih** [comment]
@samedson 

gofmt is based on tabs. The whole Go community uses this formatting style for years. There is basically no space. Even though you go and use space, gofmt will reformat it with tabs. That's the only reason. The setting was there before I've started the `vim-go` project, it was an official setting from the core Go repo. Thanks for asking.
