### ISSUE TITLE
GoRun clears current buffer

### ISSUE THREAD

**Issue by afidalgo** [fatih/vim-go#3444]
. cd to a directory where a go project is located, run vim -p *.go
. go to any buffer and run :GoRun .
. let the program run and generate some output (mine has a lot of log statements)
. hit ctrl-c to stop the running program

### What did you expect to happen?
To go back to the buffer i was and keep editing the file

### What happened instead?
Got the buffer replaced by a code snippet (the one used for a new file) plus a splitted window with all the results of the program run

#### vim-go version:
1.26

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
set mouse=a
syntax on
set number relativenumber
filetype plugin on
filetype indent on
set tabstop=2
set shiftwidth=2
set background=dark
colo gruvbox
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>f <Plug>(go-fmt)
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 17 2022 21:26:11)
macOS version - arm64
Included patches: 1-5032

#### Go version (`go version`):

go version go1.19 darwin/arm64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/alz/Library/Caches/go-build"
GOENV="/Users/alz/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/alz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alz/OneDrive/src/PFmicro/emerg_be/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zw/tzl39_rd5hj_dclyjw0d5r9m0000gn/T/go-build4024226367=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.9.2
    golang.org/x/tools/gopls@v0.9.2 h1:iHtOeH75M+RhCxj5Dwgvx29z3Ok0VkmyTNL2Xj7chj4=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Can you please provide clear instructions for how to duplicate this? I think I may know what's going on, but I'm not sure without more details. FWIW, `:GoRun` generally works as you expect, and you can prove that to yourself by running a simple program with it:
```
package main

import (
	"fmt"
	"log"
)

func main() {
	fmt.Println("vim-go")
}
```

**Comment by afidalgo** [comment]
Tested on how you mentioned, yes, it works fine. Tried to replicate my issue doing this

`
mkdir vg
cd vg
go mod init test
`
created two .go files then opened both with 
`
vim -p *.go
` 
and ran :GoRun, program only does the fmt.Println and a log.Println, hit ctrl-c, everything returned to normal, so, no way to replicate there.

I made this to show 

[https://alz-devel.s3.amazonaws.com/Screen+Recording+2022-08-12+at+21.29.51.mov]

**Comment by bhcleek** [comment]
I think the problem here is that when `ctrl-c` is pressed, your application is exiting non-zero. Vim-go then interprets the output of your program as errors. You have a few options, any of which may resolve the behavior for you:
1. Accept it and move on. This probably isn't satisfying for you.
2. Call `log.SetFlags(log.Llongfile)` in your application. If you do this, then vim-go will likely position the cursor at the first log entry after ctrl-c.
3. Use `!go run` instead of `:GoRun`.
4. Handle SIGINT and exit 0 so that vim-go doesn't think there is an error that needs to be interpreted.

**Comment by afidalgo** [comment]
1. Yes did that for a while but it’s annoying to re open the buffer.
2. Will try this one
3. Yes, I’m doing a mix of this one and the go run in a different terminal
4. The best one for far, I’ll do this.

thanks a lot for you help!!!
