### ISSUE TITLE
qf disable 

### ISSUE THREAD

**Issue by mas-wig** [fatih/vim-go#3445]
How i can disable permanently thiss qf windows always show when error happen

![2022-08-25-225436_1366x768_scrot](https://user-images.githubusercontent.com/88357663/186713707-446bb126-a3ca-4bb2-b1b6-ed38bf36bb78.png)

**Comment by bhcleek** [comment]
What caused that quickfix window to display? It was most likely with saving or `:GoBuild`...

**Comment by bhcleek** [comment]
closed for lack of feedback
