### ISSUE TITLE
GoUpdateBinaries failed to update golangci-lint

### ISSUE THREAD

**Issue by casatwy** [fatih/vim-go#3446]
### What did you do? (required: The issue will be **closed** when not provided)

`vim +GoUpdateBinaries`

then I got this:
<img width="1440" alt="截屏2022-08-26 17 14 10" src="https://user-images.githubusercontent.com/1005781/186870885-c8498664-9631-4b7f-8a12-9bb1f8bcc079.png">

my question is:
how do I handle this: "-lang was set to go1.16; check go.mod" ? 
I'm running `vim +GoUpdateBinaries` in my home menu.
Where is the go.mod that I should check?

### What did you expect to happen?

fully update go binaries.

### What happened instead?

failed to update golangci-lint

#### vim-go version:

latest version.
(git commit hash:4d6962d8e0792617f87b37b938996f44e2a54645  Fri Aug 12 10:26:27 2022 -0700)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" I'm sure my vimrc has nothing to do with this issue.
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul 25 2022 07:38:38)
macOS version - x86_64
Included patches: 1-65

#### Go version (`go version`):

go version go1.19 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/casa/Library/Caches/go-build"
GOENV="/Users/casa/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/casa/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/casa/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/Cellar/go/1.19/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kv/87y3d9ln55vfvm7_3twnv_6m0000gn/T/go-build4071934307=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.9.4
</pre></details>

**Comment by bhcleek** [comment]
This is happening because vim-go installs the tools with the `-mod=readonly` flag when it invokes `go install` and the `-mod=readonly` is causing a problem now, though I'm not quite sure why.

It may be possible for vim-go to stop using `-mod=readonly` now, but I'm not sure off the top of my head and will need to look into it. In the meantime, `golangci-lint` may be able address this on their end...

**Comment by bhcleek** [comment]
https://github.com/golangci/golangci-lint/discussions/3177 details this problem, too. I believe this is a problem for golangci-lint to solve. 

In the meantime, you can install a the last version of golangci-lint that didn't have this problem with vim-go by using `:GoUpdateBinaries golangci-lint@v1.48.0`. You could also manually install the latest golangci-lint at the commandline with `go install github.com/golangci/golangci-lint@latest`.
