### ISSUE TITLE
Auto-close the error buffer or open up as a popup window

### ISSUE THREAD

**Issue by mortymacs** [fatih/vim-go#3448]
### What did you do? (required: The issue will be **closed** when not provided)

When I have an error in codes, a buffer will automatically be opened and shows the error. But when I address the error, it still be there but empty.

![image](https://user-images.githubusercontent.com/1261448/188123514-c1749930-c27e-43e6-b910-cfe57d77c3e7.png)

### What did you expect to happen?

I'm looking for a way to automatically close the error buffer after the fix.

### What happened instead?

It is sill open also visible as a new tab. 

![image](https://user-images.githubusercontent.com/1261448/188123632-01592a59-d705-4724-8b9e-4d09b72e6ca3.png)

![image](https://user-images.githubusercontent.com/1261448/188123716-810c91d1-f785-411f-8633-d521b8a59fc8.png)

### Configuration (**MUST** fill this out):

Everything is default. I didn't define anything spacial, except:

```vim
let g:go_auto_type_info = 0
```

#### vim-go version:

Latest version.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
let g:go_auto_type_info = 0
```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.19 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.9.4
    golang.org/x/tools/gopls@(devel)
</pre></details>

**Comment by bhcleek** [comment]
It will close after you fix the problem _and_ execute whatever action you took the first time that caused the quickfix window to open.

**Comment by mortymacs** [comment]
I showed in the second screenshot, it never closes the window.

**Comment by bhcleek** [comment]
> I showed in the second screenshot, it never closes the window. 

But you didn't provide a clear set of steps to reproduce the problem. I don't know what you're actually _doing_.

> I don't take any action to open up this window. It will appear automatically when an error found in the code.

Vim-go only adds errors to the quickfix list when the user takes some action. Based on what I see here, I suspect it's saving the file or executing `:GoBuild`, but I'm not sure. If you can tell me what you're actually doing, I may be able to help.

If you're not sure what you're doing, then executing `g:go_debug=['shell-commands', 'lsp']` and then duplicating the problem may be helpful. I'd need the contents of the `__GOLSP_LOG__`  and the output of `:messages`.

**Comment by mortymacs** [comment]
> But you didn't provide a clear set of steps to reproduce the problem. I don't know what you're actually _doing_.

Sorry, my bad. Just open up a Go file and put a syntax error and then save it. Then this window will appear in the bottom:

![image](https://user-images.githubusercontent.com/1261448/188406383-30e64dd1-79c0-43c4-b092-7fa09adf0981.png)

Also, this is my whole Neovim config file: https://github.com/mortymacs/dotfiles/blob/master/nvim/init.vim

**Comment by bhcleek** [comment]
The location list should close automatically once you fix the syntax error and save again.

**Comment by mortymacs** [comment]
I finally disabled all the plugins and tested it and it worked as you mentioned. Then I disabled plugins one by one and then I found the root cause. It was ALE package and I had to add these config based on the official document:
```vim
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
```
Thanks!
