### ISSUE TITLE
ftplugin/go/tagbar.vim breaks tagbar ctags for files arguments for nvim CLI

### ISSUE THREAD

**Issue by chrisplo** [fatih/vim-go#3452]
### What did you do? (required: The issue will be **closed** when not provided)

Started nvim with a .go file as an argument, then opened Tagbar.

### What did you expect to happen?

To see ctags for go file in tagbar just like when starting nvim without arguments, then opening .go file.

### What happened instead?

no tags shown.  If I rm `dein/.cache/init.vim/.dein/ftplugin/go/tagbar.vim -> /Users/chrisplo/.cache/dein/repos/github.com/fatih/vim-go/ftplugin/go/tagbar.vim` then the tags will be seen. 

### Configuration (**MUST** fill this out):
completely default (unless I misunderstood question)

#### vim-go version:
`22b2273c - (13 days ago) Merge pull request #3451 from bhcleek/lint-fixes - Billie Cleek (HEAD -> master, origin/master, origin/HEAD)`

#### Vim version (first three lines from `:version`):
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
```

#### Go version (`go version`):
go version go1.18.4 darwin/amd64

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.9.5
</pre></details>

####  `vimrc` you used to reproduce:
<details><summary>vimrc</summary>

```vim
nmap <F8> :TagbarToggle<CR>

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')
    call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
    call dein#add('preservim/tagbar')
    call dein#add('fatih/vim-go')
    call dein#end()
    call dein#save_state()
endif

" If you want to install not installed plugins on startup.
if dein#check_install()
    call dein#install()
endif```
</details>

**Comment by bhcleek** [comment]
> If I rm dein/.cache/init.vim/.dein/ftplugin/go/tagbar.vim -> /Users/chrisplo/.cache/dein/repos/github.com/fatih/vim-go/ftplugin/go/tagbar.vim then the tags will be seen.
What does that mean? What are you removing? What's the `->` represent?


> no tags shown. 

I'm unable to duplicate what you're describing here. When I start vim or neovim with a file argument and then open tagbar, the tags are shown fine.

**Comment by chrisplo** [comment]
it's a symlink (on left) to target (on the right), I presume dein is adding the symlink as part of how it installs vim-go's ftplugin for go.

**Comment by bhcleek** [comment]
This seems like it's something specific to your environment, but I'm not quite sure what it is. I'd recommend that you try duplicating this issue without dein. If you can create some clear replication steps and isolate the problem to vim-go, I'll be happy to help out. If the problem is specific to dein somehow, then this will be an issue for you to solve.
