### ISSUE TITLE
Variables in GODEBUG_VARIABLES pane truncated at 20 bytes

### ISSUE THREAD

**Issue by bgarber** [fatih/vim-go#3453]
### What did you do?
Trying to debug a Go program using `dlv` and `vim-go`. The variables in the `GODEBUG_VARIABLES` pane seem to be truncated at 20 bytes: 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/1001525/191589162-38afa710-ea9a-4606-874f-cd67e871284e.png">

The `GODEBUG_OUTPUT` shows the entire string correctly, when I execute `:GoDebugPrint hello`:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/1001525/191589515-633ef023-0c9a-4b6a-a21e-8d7bd11aa6c8.png">

I have already edited my `~/.config/dlv/config.yml` file to permit longer strings:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/1001525/191589753-c0f7ca9a-0894-4669-bb5c-923446e0bbbc.png">

Am I missing something?

### What did you expect to happen?
I expected the whole string to appear in the variables pane.

### What happened instead?
Strings (and most of the data) get truncated at 20 bytes.

#### vim-go version:
latest master (22b2273cfe562ac1c1af976ce77f18a3b1776f3c)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
" Setup for vim-go
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 1
" let g:go_debug = ['shell-commands']
" let g:go_auto_type_info = 1

if exists('$GOPATH')
    autocmd BufRead *.go
        \ let s:temp = matchlist(expand('%:p'),
           \ $GOPATH . '/src/\(github.com/bgarber/[^/]\+\)')
        \| if len(s:temp) > 1 | exe 'silent :GoGuruScope ' . s:temp[1] . '/...' | endif
        \| unlet s:temp
endif
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28)
Included patches: 1-313
Compiled by 'http://www.opensuse.org/'

#### Go version (`go version`):

go version go1.18.5 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bgarber/.cache/go-build"
GOENV="/home/bgarber/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-mod=mod"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bgarber/workspace/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bgarber/workspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib64/go/1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib64/go/1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build780564638=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.9.5
    golang.org/x/tools/gopls@v0.9.5 h1:F3TO5th6TUg40FHrpxZfMkMlVaaTmByeEvylgVHGH2A=
</pre></details>

**Comment by bhcleek** [comment]
You are correct; vim-go configures delve to truncate string variables to 20 characters for the variables pane. The restriction does not apply to `:GoDebugPrint`'s result.

ref: https://github.com/fatih/vim-go/blob/22b2273cfe562ac1c1af976ce77f18a3b1776f3c/autoload/go/debug.vim#L1169

**Comment by bgarber** [comment]
Thank you, @bhcleek! Just one more comment: could vim-go let the users configure this value? I think that could be a good approach. I may send you a pull request enabling this if you wish.

**Comment by bhcleek** [comment]
Thank you, bgarber, but I'd like to leave this as-is. Twenty characters is generally sufficient for someone to understand what the value is, and trying to chase down some ideal value will be a fool's errand. Delve is surprisingly configurable, but all of its options aren't going to be exposed in vim-go. With `:GoDebugPrint`, one can see the longer value when needed.
