### ISSUE TITLE
Autocompletion doesn't always work when it should

### ISSUE THREAD

**Issue by trstringer** [fatih/vim-go#3454]
### What did you do? (required: The issue will be **closed** when not provided)

I currently have a situation where if I write the following code:

    doSomeFunction(objectName.

When I type the trailing period I can invoke omnifunc/autocompletion successfully.

But if I do this:

    if doSomeFunction(objectName.

omnifunc/autocompletion doesn't give me anything.

### What did you expect to happen?

I expected the correct autocompletion to happen when I write `if doSomethingFunction(objectName.` or `if len(objectName.`.

### What happened instead?

Autocompletion did not pop up.

### Configuration (**MUST** fill this out):

```
" Go
let g:go_def_mapping_enabled = 0
let g:go_list_type_commands = {"GoReferrers": "quickfix"}
let g:go_gopls_matcher = "fuzzy"
let g:go_list_autoclose = 1
let g:go_fmt_autosave = 1
```

#### vim-go version:

22b2273cfe562ac1c1af976ce77f18a3b1776f3c

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
filetype plugin indent on

" Basic Vim options
set nocompatible
set nowrap
set number
set relativenumber
set splitbelow
set splitright
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set wildignore+=**/site-packages/**
set wildignore+=**/vendor/**
set wildignore+=*.pyc
set wildignore+=**/bin/**
set wildignore+=**/venv/**
set wildignore+=*.swp
set wildmenu
set wildmode=longest,list,full
set foldmethod=syntax
set foldlevelstart=99
set fileformat=unix
set backspace=indent,eol,start

" Styling
packadd! dracula
syntax enable
colorscheme dracula
highlight def link goType DraculaCyan
highlight def link Type DraculaCyan
highlight def link Type DraculaCyan
highlight def link SpecialComment DraculaCyan
highlight def link goSignedInts DraculaCyan
highlight def link goUnsignedInts DraculaCyan
highlight def link goFloats DraculaCyan
highlight def link goComplexes DraculaCyan
highlight def link goTypeName DraculaCyan
highlight def link goExtraType DraculaCyan
highlight def link goFunctionCall DraculaCyan
highlight def link goTypeConstructor DraculaCyan
highlight def link goDeclsFzfSpecialComment DraculaCyan
highlight def link terraType DraculaCyan
highlight def link hclBlockType DraculaCyan


" File browsing options
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_winsize = 25

" Mappings
inoremap jj <esc>
nnoremap <silent> <C-]> :Files <CR>
nnoremap <silent> <C-I> :ALEHover <CR>
" nnoremap <silent> <C-W> :pcl <CR> :lcl <CR> :ccl <CR>

" Go
let g:go_def_mapping_enabled = 0
let g:go_list_type_commands = {"GoReferrers": "quickfix"}
let g:go_gopls_matcher = "fuzzy"
let g:go_list_autoclose = 1
let g:go_fmt_autosave = 1

" YCM
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_auto_hover = ''
set completeopt-=preview
"set completeopt+=popup

" ALE
let g:ale_keep_list_window_open = 0
let g:ale_open_list = 1
let g:ale_list_window_size = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_enter = 1

" File specifications
au BufNewFile,BufRead *.bicep
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
    \ set autoindent |
    \ set expandtab |
    \ set cursorcolumn

au BufNewFile,BufRead *.sh
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set autoindent |
    \ set expandtab

au BufNewFile,BufRead mysqlsh.edit.tmp* set filetype=sql
au BufNewFile,BufRead Dockerfile* set filetype=dockerfile

augroup filetype
  au! BufRead,BufNewFile *.proto setfiletype proto
augroup end

autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

iab bookcode \setstretch{1.0}
            \<CR>```
            \<CR>```
            \<CR>\setstretch{1.4}

au FileType sql setl formatprg=/usr/bin/pg_format\ -
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 22 2022 18:10:15)
Included patches: 1-553
Compiled by trstringer@thomas-linux

#### Go version (`go version`):

go version go1.19.1 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/trstringer/.cache/go-build"
GOENV="/home/trstringer/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/trstringer/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/trstringer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4109223869=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.9.5
    golang.org/x/tools/gopls@v0.9.5 h1:F3TO5th6TUg40FHrpxZfMkMlVaaTmByeEvylgVHGH2A=
</pre></details>

**Comment by bhcleek** [comment]
This may not be due to vim-go. The behavior you're describing of triggering completion upon typing a `.` is not vim-go's behavior. I see that you also have YCM and Ale installed. Can you duplicate the problem you're seeing with vim-go (i.e. without other plugins enabled) and using the standard `ctrl-x,ctrl-o` to trigger completion?

**Comment by bhcleek** [comment]
Closing due to lack of feedback
