### ISSUE TITLE
Extra types not highlighting

### ISSUE THREAD

**Issue by hbourgeot** [fatih/vim-go#3455]
####  `init.lua` you used to reproduce:
-->

<details><summary>vimrc</summary>

```vim
vim.cmd([[
	let g:go_highlight_operators = 1
	let g:go_highlight_functions = 1
	let g:go_highlight_function_parameters = 1
	let g:go_highlight_function_calls = 1
	let g:go_highlight_types = 1
	let g:go_highlight_fiels = 1
	let g:go_highlight_build_constraints = 1
	let g:go_highlight_variable_declarations = 1
	let g:go_highlight_variable_assignments = 1
	let g:go_highlight_extra_types = 1
  let g:go_highlight_generate_tags = 1
	
	au BufRead,BufNewFile *.gohtml set filetype=gohtmltmpl
]])
```
</details>

#### Neoim version (first three lines from `:version`):

<details><summary>neovim version</summary>
<pre>
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
</pre></details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/henrry-go/.cache/go-build"
GOENV="/home/henrry-go/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/henrry-go/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/henrry-go/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/henrry-go/Documentos/proyectos/snippetbox/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2195146677=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

v0.9.5
</pre></details>

Expected
![image](https://user-images.githubusercontent.com/85085805/192124670-123d97c8-dedc-4680-9fff-de7417c9730c.png)

Gived
![image](https://user-images.githubusercontent.com/85085805/192124677-5fc3de2a-3954-46c2-b71d-cc79320b1d78.png)

**Comment by bhcleek** [comment]
How did you get the expected screenshot?

FWIW, the `g:go_highlight_extra_types` would not cause an of the types show in the fields in your second screenshot to be highlighted: it only causes some very common types from the standard library to be highlighted.

Unrelated tip: `let g:go_highlight_fiels = 1` in your `init.lua` is missing the `d` in `fields`.

**Comment by hbourgeot** [comment]
> How did you get the expected screenshot?

With Nvim Treesitter Go.
> 
> 
> FWIW, the `g:go_highlight_extra_types` would not cause an of the types show in the fields in your second screenshot to be highlighted: it only causes some very common types from the standard library to be highlighted.

So, the package log does'nt highlight with this option?
> 
> Unrelated tip: `let g:go_highlight_fiels = 1` in your `init.lua` is missing the `d` in `fields`.

My bad, thanks you

**Comment by bhcleek** [comment]
> So, the package log does'nt highlight with this option?

That's right. ref: https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L257-L264

**Comment by hbourgeot** [comment]
> That's right. ref: https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L257-L264

Thanks you very much, can I make a PR for include more packages?
