### ISSUE TITLE
[wiki] Outdated options in FAQ/troubleshooting page

### ISSUE THREAD

**Issue by bravoecho** [fatih/vim-go#3457]
Hi, the options `g:go_highlight_structs` and `g:go_highlight_interfaces`, mentioned here: <https://github.com/fatih/vim-go/wiki/FAQ-Troubleshooting#vim-becomes-sluggish-while-editing-go-files> no longer exist in recent versions of `vim-go`. Is the same advice now applicable to `g:go_highlight_types`? Thanks.

**Comment by bhcleek** [comment]
If you're seeing seeing sluggishness, then that could help, yes. But I've removed that FAQ entry, as I think it's long ago been overtaken by events.
