### ISSUE TITLE
Not an Editor Command: GoDoc, GoBuild, GoRun

### ISSUE THREAD

**Issue by kahshiu** [fatih/vim-go#346]
Im on Ubuntu 10, installed go from tar.gz and installed vim-go. Cant run these commands. 
:scriptnames doesnt show the only file being
~/.vim/bundle/vim-go/plugin/go.vim 

reading issue #96 shows that there are more than this one file needed.
where do I find these files?

 34: ~/.dotfiles/vim/bundle/vim-go/plugin/godef.vim
 35: ~/.dotfiles/vim/bundle/vim-go/plugin/godoc.vim
 36: ~/.dotfiles/vim/bundle/vim-go/plugin/goerrcheck.vim
 37: ~/.dotfiles/vim/bundle/vim-go/plugin/goinstall.vim
 38: ~/.dotfiles/vim/bundle/vim-go/plugin/goplay.vim
 39: ~/.dotfiles/vim/bundle/vim-go/plugin/gosnippet.vim
 40: ~/.dotfiles/vim/bundle/vim-go/plugin/gotagbar.vim
 41: ~/.dotfiles/vim/bundle/vim-go/plugin/gotools.vim
 42: ~/.dotfiles/vim/bundle/vim-go/plugin/oracle.vim

**Comment by fatih** [comment]
Please check installation steps, you didn't installed it properly:

https://github.com/fatih/vim-go#install

There is no `goplay.vim` or any `godef.vim` anymore.
