### ISSUE TITLE
Can't go to definition of generic function

### ISSUE THREAD

**Issue by kangsouth** [fatih/vim-go#3463]
### What did you do? (required: The issue will be **closed** when not provided)
When the cursor was on the generic function call, I typed ":GoDef", trying to go to definition of the generic function

### What did you expect to happen?
Going to the definition of generic function, like other non-generic functions.
### What happened instead?
I got an error: no object found for ident {function_name}: no object found 
#### vim-go version:
It doesn't have a tag, the commit is 0550762a69a2ef13d9f723c9478155dbc6ad7ddb
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'kien/ctrlp.vim'
Plugin 'fatih/vim-go'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'jmcantrell/vim-virtualenv'

call pathogen#infect()
syntax enable
filetype plugin on

" All of your Plugins must be added before the following line

call vundle#end() "required
filetype plugin indent on "required
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  1 2021 21:01:15)
macOS version - x86_64
包含补丁: 1-2681
#### Go version (`go version`):

go version go1.18 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="off"
GOARCH="amd64"
GOBIN="/Users/kangyanbo/go/bin"
GOCACHE="/Users/kangyanbo/Library/Caches/go-build"
GOENV="/Users/kangyanbo/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kangyanbo/go/pkg/mod"
GONOPROXY="*.byted.org/*"
GONOSUMDB="*.byted.org/*"
GOOS="darwin"
GOPATH="/Users/kangyanbo/go"
GOPRIVATE="*.byted.org,*.everphoto.cn,git.smartisan.com"
GOPROXY="https://go-mod-proxy.byted.org,https://goproxy.cn,https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nk/hhrxjyfd6h3bk2_z4cxtds2h0000gp/T/go-build2515587832=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.5
    golang.org/x/tools/gopls@v0.7.5 h1:8Az52YwcFXTWPvrRomns1C0N+zlgTyyPKWvRazO9GG8=
</pre></details>

**Comment by bhcleek** [comment]
You have a very old version of gopls, and I suspect you need to update it and/or recompile with the latest version of Go to get the support for generics.

Can you run `:GoUpdateBinaries gopls` and `:GoUpdateBinaries godef` and then try jumping to the generic definition again?

**Comment by kangsouth** [comment]
Exactly, I updated gopls and godef, it worked.
