### ISSUE TITLE
[question] GoDoc - How to follow links

### ISSUE THREAD

**Issue by MushiTheMoshi** [fatih/vim-go#3464]
Hi there,

Really appreciate all work done here, thanks!

How can I follow links on GoDoc?  

Let's say I am checking a function documentation which one of the arguments is a type, how can I see the doc of that particular type?

Thanks in advance,
Julio

**Comment by bhcleek** [comment]
`:GoDoc pkg/identifer` is the closest experience to accomplish your objective. e.g. if you're reading the docs for `"net/http".HandlerFunc` and you want to read the docs for `"net/http".ResponseWriter`, then `:GoDoc net/http ResponseWriter` will get you there.

**Comment by MushiTheMoshi** [comment]
Hi there, it works like a charm! thank you!
