### ISSUE TITLE
Errors detected while processing go#package#InGOPATH and ~/.config/nvim/plugged/vim-go/ftplugin/go/commands.vim

### ISSUE THREAD

**Issue by natemurthy** [fatih/vim-go#3465]
### What did you do? (required: The issue will be **closed** when not provided)

When I open a Go file with `vim main.go` I get the following errors detected:

![image](https://user-images.githubusercontent.com/1788878/201792676-617a20b0-d7d4-4a2e-b53e-b55a9fa8cdba.png)

### What did you expect to happen?
I expect there to be no errors when opening any Go file.

### What happened instead?
The errors above appeared

#### vim-go version:
[master @ 0550762](https://github.com/fatih/vim-go/commit/0550762a69a2ef13d9f723c9478155dbc6ad7ddb)

####  `vimrc` you used to reproduce:
https://github.com/natemurthy/dotfiles/blob/master/dot-vimrc

#### Vim version (first three lines from `:version`):
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
```

#### Go version (`go version`):
```
go version go1.17.6 darwin/amd64
```

#### Go environment
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nate/Library/Caches/go-build"
GOENV="/Users/nate/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nate/Gospace/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nate/Gospace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m8/yqvg9vk50mq2hrjx9m4rg5l40000gn/T/go-build1330381555=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

#### gopls version
```
golang.org/x/tools/gopls v0.8.1
```

**Comment by bhcleek** [comment]
`:GoDoc pkg/identifer` is the closest experience to accomplish your objective. e.g. if you're reading the docs for `"net/http".HandlerFunc` and you want to read the docs for `"net/http".ResponseWriter`, then `:GoDoc net/http ResponseWriter` will get you there.

**Comment by bhcleek** [comment]
What does `go list` report when executed in the directory where your `main.go` resides?

**Comment by bhcleek** [comment]
Also, can you run `:exe '!cd ' . expand('%:p:h') . ' && go list'` from within Vim and report the output here?

**Comment by natemurthy** [comment]
> What does `go list` report when executed in the directory where your `main.go` resides?
```
etrade-golang
```

> can you run `:exe '!cd ' . expand('%:p:h') . ' && go list'` from within Vim and report the output here?
```
:!cd /Users/nate/Workspace/github.com/natemurthy/etrade-api/golang && go list                  
etrade-golang
```

For reference, here is the source code I'm working on: https://github.com/natemurthy/etrade-api/tree/main/golang

**Comment by bhcleek** [comment]
Are any of the components of `/Users/nate/Workspace/github.com/natemurthy/etrade-api/golan` a symlink?

**Comment by natemurthy** [comment]
Nope, no symlinks:
```
nate:golang$ pwd
/Users/nate/Workspace/github.com/natemurthy/etrade-api/golang
nate:golang$ ls -al
total 24
drwxr-xr-x   5 nate  staff   160 Nov 14 14:41 .
drwxr-xr-x  12 nate  staff   384 Nov 14 16:38 ..
-rw-r--r--   1 nate  staff   210 Nov 14 14:41 go.mod
-rw-r--r--   1 nate  staff  1520 Nov 14 14:41 go.sum
-rw-r--r--   1 nate  staff  1911 Nov 14 14:41 main.go
```

**Comment by bhcleek** [comment]
I don't mean the contents of that directory, I mean that directory itself or any of its parents.

Do you have the same problem when you're using a version of Go that isn't EOL (i.e. 1.18 or 1.19)?

**Comment by natemurthy** [comment]
Ah nope, directory itself and its parents are not symlinks

Let me do some upgrades of a few libraries (been a while since I've done Go development as you can tell!)

**Comment by bhcleek** [comment]
This is odd. I've seen similar reports in the past, but I don't think I've ever found a root cause. I'd like to know what's actually coming out of that `go list` command. Can you apply this to your vim-go installation and reproduce the issue?
```
diff --git a/autoload/go/package.vim b/autoload/go/package.vim
index 0ede3d14..4e6abfbe 100644
--- a/autoload/go/package.vim
+++ b/autoload/go/package.vim
@@ -151,6 +151,7 @@ function! go#package#InGOPATH() abort
       return 0
     endif
 
+    call go#util#EchoInfo(printf("go list output '%s'", l:out))
     let l:importpath = split(l:out, '\n')[0]
     if len(l:importpath) > 0
       let s:in_gopath[l:dir] = l:importpath
```

I'd like to know what the new message is (you can get at it with `:messages`).
