### ISSUE TITLE
GoTest with  g:go_term_enabled=1 and Plug 'airblade/vim-rooter' conflict

### ISSUE THREAD

**Issue by Me1onRind** [fatih/vim-go#3466]
### What did you do? (required: The issue will be **closed** when not provided)
I run GoTest/GoTestFunc -v with let g:go_term_enabled=1.

### What did you expect to happen?
Success  pop go test command output in new terminal

### What happened instead?

error:    vim-go: [go test -v] FAIL

### Configuration (**MUST** fill this out):
```vimscript
...
Plug 'airblade/vim-rooter' 
...
let g:go_term_enabled=1
...
```

#### vim-go version:
0550762a69a2ef13d9f723c9478155dbc6ad7ddb

#### Vim version (first three lines from `:version`):
9.0.880

#### Go version (`go version`):

go1.18 linux/amd64

I find when excute term_start(["go", "test", "-v"]),  execution directory is project's root directory.  Look like cause `by` airblade/vim-rooter cause.

I try query vimscript document(https://vimhelp.org/terminal.txt.html), It looks like no parameter to control it.

I think there are two ways to reslove it:
1. excute like "cd /project/xxx/pkg && go test -v" （term_start() no easy to support this? I try failed...）
2. vim-go provider a config let ["go", "test", "-v"] to ["go", "test", "-v", "{relative path}"]

Or you have better idea. Maybe others will have same problem. Will the problem fixed？ Think you.

**Comment by bhcleek** [comment]
I'm not familiar with vim-rooter, but it looks like vim-rooter documents some options in its README that could help. Vim-go executes nearly all `go` commands in the directory that contains the file being edited when a command is run, so vim-rooter may not be necessary for Go files 🤔 

Do you have the same problem if you run `:GoTest .` ? What if you give `:GoTest` your package name as an argument (e.g. `:GoTest xxx/pkg`)?

```
I think there are two ways to reslove it:

    1. excute like "cd /project/xxx/pkg && go test -v" （term_start() no easy to support this? I try failed...）
    2. vim-go provider a config let ["go", "test", "-v"] to ["go", "test", "-v", "{relative path}"]
```

The first option is effectively what vim-go already does: https://github.com/fatih/vim-go/blob/82d41cd8666910ea0d096d769a130880835dd25d/autoload/go/term.vim#L58, but the vim-rooter is changing the directory out from underneath vim-go.

The second option is a possibility, but has performance implications that I'm not sure are worth solving to workaround this one use case.

**Comment by Me1onRind** [comment]
On, Just ```:GoTest xxx/pkg``` is ok. I think the secord option is not need provided by vim-go, this issue can close.

BTW, there is my solution if someone has same problem.
```script
function! RunGoTestFunc()
    let filepath="./" . fnamemodify(expand("%"), ":~:.:h")
    execute "GoTestFunc -v " . l:filepath
endfunction

nmap gnt :call RunGoTestFunc()<CR>
```
