### ISSUE TITLE
Can GoCoverage use an existing cover profile?

### ISSUE THREAD

**Issue by clobrano** [fatih/vim-go#3467]
I have some tests that require a specific environment to be set before being able to run `go test`. This tests create a cover profile, which I'd like to use with GoCover, however this command tries to create a cover profile by itself, and its call to `go test` fails because the environment is not set.

Is there a way to use an existing cover profile?

**Comment by bhcleek** [comment]
The functionality you're looking for isn't supported in vim-go. It's probably not too hard to add.

**Comment by clobrano** [comment]
Thank you, I will have a look how to implement it then 😊
