### ISSUE TITLE
Syntax error when defining generic function

### ISSUE THREAD

**Issue by ryantsengikala** [fatih/vim-go#3470]
### What did you do? (required: The issue will be **closed** when not provided)
I wrote a snippet
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println(f[int](1))
}

func f[T any](v any) T {
	return v.(T)
}
```

### What did you expect to happen?
I expect this should be no error
### What happened instead?
The error message `main.go|12 col 7| expected '(', found '['` popped out.
#### vim-go version:
0550762a
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
set nocompatible              " be iMproved, required
filetype on                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'

Plugin 'git://git.wincent.com/command-t.git'

Plugin 'fatih/vim-go'

call vundle#end()            " required
filetype plugin indent on    " required

syntax on
set tabstop=4
set shiftwidth=4
set nu
set hlsearch
set incsearch
set backspace=indent,eol,start
let g:go_highlight_function_calls=1
let g:go_highlight_functions=1
let g:go_highlight_methods=1
let g:go_highlight_extra_types=1
let g:go_fmt_fail_silently=0
let g:go_fmt_experimental=1
let g:go_fmt_command = "goimports"
let g:go_def_mode = 'godef'
let g:go_info_mode='gopls'
let g:go_metalinter_command = 'golangci-lint run'

execute pathogen#infect()

set laststatus=2
set statusline+=%F

let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq=1
let g:syntastic_go_checkers = ['govet', 'errcheck', 'deadcode']

augroup completion_preview_close
	autocmd!
	autocmd CompleteDone * if !&previewwindow && &completeopt =~ 'preview' | silent! pclose | endif
augroup END

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 28 2022 12:44:46)
macOS version - x86_64
編譯者:Homebrew

#### Go version (`go version`):

go version go1.19 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ryan/Library/Caches/go-build"
GOENV="/Users/ryan/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ryan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ryan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ryan/go/src/test/generic/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z0/th53n_cs6v3c_y8bwz4qb2vw0000gn/T/go-build1937935326=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.1
    golang.org/x/tools/gopls@v0.5.1 h1:AF3Uh7HF08SZpKFfgJO6zfF3bbxyDXWqdkK4kMXiQ1o=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 0
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_highlight_methods = 1
g:go_fmt_experimental = 1
g:go_loaded_gosnippets = 1
g:go_highlight_extra_types = 1
g:go_metalinter_command = 'golangci-lint run'
g:go_highlight_functions = 1
g:go_loaded_install = 1
g:go_def_mode = 'godef'
g:go_highlight_function_calls = 1
g:go_info_mode = 'gopls'
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
It's likely that this is because the version of `gopls` you're using is very old. Can you try running `:GoUpdateBinaries gopls` and try again?

**Comment by ryantsengikala** [comment]
@bhcleek I updated gopls to `golang.org/x/tools/gopls@v0.10.1`, but still show the same error.

**Comment by ryantsengikala** [comment]
> What are you doing to trigger this error? I'm unable to duplicate it at all. I'm also curious if go build when run at the commandline sees the same problem.

The error show up when I typing :w on command mode. `go build` will not generate same error.

> What is the value of the go directive in your go.mod?

```
module test/generic

go 1.19
```

> Can you add let g:go_debug=['lsp', 'shell-commands'] and duplicate again? I'd like to see the output of :messages and the content of the LSP log after duplicating.

:message
```
正體中文訊息維護者: Francis S.Lin <piaip@csie.ntu.edu.tw>,                                 Cecil Sheng   <b7506022@csie.ntu.edu.tw>
"main.go" 13L, 115B
vim-go: shell command: 'go' 'env' 'GOBIN'
vim-go: shell command: '/usr/local/go/bin/go' 'list'
vim-go: job command: ['/Users/ryan/go/bin/gopls', '-debug', 'localhost:0', '-remote=auto']
vim-go: shell command: '/usr/local/go/bin/go' 'env' 'GOMOD'
vim-go: shell command: '/usr/local/go/bin/go' 'env' 'GOMOD'
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: Finished loading packages.
vim-go: shell command: '/Users/ryan/go/bin/goimports' '-w' '-srcdir' 'main.go' '/var/folders/z0/th53n_cs6v3c_y8bwz4qb2vw0000gn/T/vkMicK4/5.go'
"main.go" 13L, 115B 已寫入
Press ENTER or type command to continue
```

LSP log after error
```
===== sent =====
Content-Length: 310

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package main\n\nimport (\n\t\"fmt\"\n)\n\nfunc main() {\n\tfmt.Println(f[int](1))\n}\n\nfunc f[T any](v any) T {\n\treturn v.(T)\n}\n"}],"textDocument":{"uri":"file:///Users/ryan/go/src/test/generic/main.go","version":3}}}
===== received =====
Content-Length: 155

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/ryan/go/src/test/generic/main.go","version":3,"diagnostics":[]}}
```

**Comment by bhcleek** [comment]
Ah, this may be because of `goimports`. Try `:GoUpdateBinaries goimports` (you may just want to `:GoUpdateBinaries` without any arguments to update all the tools and build them with Go 1.19). Alternatively, change `g:go_fmt_command = 'goimports'` to `g:go_fmt_command = 'gopls'` or remove that line altogether to use `gopls` instead of `goimports`.

Using `gopls` for formatting and importing will generally result in an improved experience; it eliminates a number of edge cases and improves performance of formatting and adjusting imports.

**Comment by ryantsengikala** [comment]
Thanks! The problem solved.
