### ISSUE TITLE
GOLSP_LOG

### ISSUE THREAD

**Issue by madzhuga** [fatih/vim-go#3478]
Not sure if that's a bug or a feature but every time I navigate to some file - it opens second window in the bottom with __GOLSP_LOG__

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/2453378/209431596-0d5d051c-a74b-4aad-b9a6-c3f974e317c6.png">

Is that a bug or maybe there is some option to hide that window? 
Thanks for help in advance.

**Comment by madzhuga** [comment]
My bad, after `GoInstallBinaries` it disappeared.

**Comment by bhcleek** [comment]
That window is not controlled by anything that `:GoInstallBinaries` would fix. It's controlled by `g:go_debug` (see `:help g:go_debug`).
