### ISSUE TITLE
Feature request: extend with template for another package files

### ISSUE THREAD

**Issue by dunrix** [fatih/vim-go#3479]
In the current state, when a new Go file is created in an already prepopulated package directory, only following contents is inserted:

`package <detected_package_name>`

see https://github.com/fatih/vim-go/blob/f7a4509fc1d1434daf922894f0aee140c9fa3f1a/autoload/go/template.vim#L36

It would become handy to define a template also for this case, besides solitary `.go` and  `_test.go` ones.
Like prepend a software license disclaimer or any other arbitrary contents with `package <name>` as a placeholder.

**Comment by bhcleek** [comment]
I think this is better supported as a snippet. Vim-go already supports a few snippet engines and provides GPL snippets for UltiSnippets and Snipmate.

You can easily customize your snippets and add additional snippets beyond what vim-go provides using the functionality provided by a snippet engine.
