### ISSUE TITLE
vim-go [any] syntax error

### ISSUE THREAD

**Issue by pictureyong** [fatih/vim-go#3480]
### What did you do? (required: The issue will be **closed** when not provided)
![image](https://user-images.githubusercontent.com/5275124/211451476-84bae753-eb1f-4921-8a7d-2d45cae90642.png)

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

**Comment by pictureyong** [comment]
expected '(', found '[' (and 1 more errors)
vim-go [any] support

**Comment by bhcleek** [comment]
I suspect your version of `gopls` hasn't been built with Go 1.19. You can rebuild it with `:GoUpdateBinaries gopls`.
