### ISSUE TITLE
Error with generics code

### ISSUE THREAD

**Issue by ryanc414** [fatih/vim-go#3484]
### What did you expect to happen?

Use generics with vim-go. Not sure if I've misconfigured something, I expected this to just work.

### What happened instead?

When using the following generics syntax, vim-go reports an error:

```
func ProcessAllMessages[T any](
	ctx context.Context,
	e levents.SQSEvent,
	processMessage func(context.Context, *T) error,
) error {
...
}
```

`expected '(', found '[' (and 2 more errors)`

#### vim-go version:

v1.28

####  `vimrc` you used to reproduce:
https://github.com/ryanc414/dotfiles/blob/master/init.vim

#### Vim version (first three lines from `:version`):
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):
go version go1.19.5 darwin/arm64

#### Go environment
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/ryancollingham/Library/Caches/go-build"
GOENV="/Users/ryancollingham/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ryancollingham/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ryancollingham/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kd/rcw4c1qx0776kvdrm18z_d9r0000gn/T/go-build3338188544=/tmp/go-build -gno-record-gcc-switches -fno-common"

#### gopls version
golang.org/x/tools/gopls v0.11.0

**Comment by bhcleek** [comment]
Run `:GoUpdateBinaries gopls`.

**Comment by ryanc414** [comment]
Thanks for your response! I tried updating binaries already but that didn't help.

Actually I discovered the root cause of the problem was ALE and not vim-go as I assumed, due to ALE using an old version of golint. I have since updated that plugin to use a different linter and all seems fixed. I'll close this issue!
