### ISSUE TITLE
New Improved Syntax Definition

### ISSUE THREAD

**Issue by charlespascoe** [fatih/vim-go#3491]
I'm a big fan of vim-go, and I've been using it for the past three years or so. The plugin itself is great, but the syntax definition doesn't highlight some useful things that I wanted (e.g. user-defined types, packages, braces, etc.), so I decided to create a new lexical syntax definition from scratch (using [Go's language specification](https://go.dev/ref/spec)) with the aim of maybe being incorporated into vim-go when it was done.

I've got it to a point where it works very well, comparable to Neovim's tree-sitter while being very fast, though I still have some more improvements planned, including generally tidying up the code and adding more comments to explain things. You can check it out here:

[vim-go-syntax](https://github.com/charlespascoe/vim-go-syntax)

(The screenshot is not the latest, as I've seen vim-go has added godoc highlighting recently). I'd be happy to put in the work to align it to the way vim-go works, including aligning config options, updating documentation, updating the syntax highlighting tests, and ongoing syntax development and improvements into the future.

Is this something you'd be interested in? I know it would be a big change, but I don't feel like it make much sense for me to have this as a standalone syntax definition, and it would benefit more people as a part of vim-go.

**Comment by bhcleek** [comment]
Thank you, Charles. I saw your post on reddit and have taken a look at the plugin and even started to see if I could incorporate it confidently. I'm definitely interested, but as someone pointed out on a reddit, such a large change is unlikely to get integrated into vim-go unless it can broken apart into incremental steps.

Breaking the changes up into incremental steps eases the burden of reviews, makes it easier to being confident that we're not introducing a slew of new bugs, and gives us the opportunity to write highlighting tests that may be missing currently.

Beyond the incremental changes, we'd want to keep highlighting group names as they are now in vim-go as much as possible, because users may have configured their own vim configurations to color their Go highlighting by leveraging the vim-go syntax group names.

**Comment by charlespascoe** [comment]
I think the person who made that comment on Reddit thought that I had taken the original syntax and modified it; in that case, it would make sense to do incremental steps.

However, main reason I started from scratch was so that I could leverage Vim's syntax features to take a more lexical approach to support things like user-defined types, which required a very different structure to the syntax definition. Another benefit of taking a lexical approach is that it eliminates certain bugs and issues present in the current syntax definition; for example:

```go
func example(
    a,
    b,
    c Foo,
) {
    // ...
}
```

When `g:go_highlight_function_parameters` is set, only the parameter `c` will be highlighted correctly, but `a` and `b` will not be. This was one of the things I wanted to address because I sometimes spread parameters like this. Also, struct literals from packages, e.g. `pkg.SomeStruct{ ... }`, are highlighted like fields instead of types when `g:go_highlight_fields` is set. I've also noticed various issues with numbers (e.g. `.123` is highlighted like a field if `g:go_highlight_fields` is set) and some less commonly used features such as labels.

The problem with these issues is that the way the syntax definition is currently structured does not lend itself well to lexically distinguishing where each token is expected to be, which makes it very hard to fix these issues (you'd have to create some very complex regular expressions to exclude certain scenarios, which would be hard to validate as correct and significantly degrade performance). I had to restructure my syntax definition a few times in order to correctly and efficiently support things like labels and fields; it took some effort, but the way it's structured now will make any any new syntax easier to implement.

In the grand scheme of things, it's a fairly new syntax definition (I started it back in October, I've spent nearly 100 hours on it so far), but I've been very proactive in testing the syntax definition against many different Go source repositories, including the Go standard library and Prometheus. I've also tested it against many permutations of valid syntax (such as spreading parameters and return values across lines), guided by the Go language specification. If you've tried it and have found any issues, please let me know; I know my syntax definition is not perfect (you can find the list of caveats at the end of the readme), but I am very thorough and experienced with lexing and Vim syntax definitions. It would definitely worth having a "beta" release just to make sure everything has been caught, but I'm confident it will go well.

In terms of highlighting group names, I have tried to keep most of them the same, but because the structure of the syntax definition is different, some of the names are different. However, this is something I could work around by linking the new syntax group names to the old ones where relevant, preserving user's custom overrides while acting as a "drop-in" replacement. Of course, it will take a little time to get there, so I wanted to get your opinion first before spending too much time.

**Comment by bhcleek** [comment]
It looks like you've put a lot of work into this, and I commend you for it.  If you're interested in breaking the problem down into discrete pull requests that each add value and solve definable problems, then I'd welcome improvements and would be happy to review each of those changes to vim-go.

Incremental changes do not have to mean that you started from vim-go's syntax file; both your solution and vim-go's are operating on the same language elements. It should therefore be reasonable to compare and contrast how each is handled and create incremental changes to vim-go's syntax to handle those elements as your syntax definition does.

A large amount of the syntax you've defined is also regular expressions. I don't have the wherewithal, though, to review a single large pull request that replaces vim-go's ~500 line syntax file with ~800 lines of script and syntax file to try to figure out what's different, what works the same, what may be broken, what regressions the new code may have, the subtleties of regular expression differences, and how one syntax file's performance compares to another performance wise in one fell swoop.

**Comment by charlespascoe** [comment]
I've spent the past few days thinking about how to approach this.

The main factor to consider is the interconnected way each of the syntax groups interact with each other in the form of contained matches, next matches, and clusters, which is how it is able to support all of the complex highlighting in a performant manner.

That said, I think the best starting point would be `type` declarations, including struct and interface type declarations. No other usage of types will be changed (e.g. parameters or variable declarations), so it should be fairly self-contained and easier to review without affecting any other parts of the syntax definition. Having this integrated and tested fist will then lay the foundation for future merges, including things like parameters. If this turns out to be too large of a change, I'll see if I can find ways to divide the types into smaller groups.

Regarding the use of regular expressions, there are certain parts of my syntax definition that are simpler (e.g. fields) because of the use of `contains` and `nextgroup`, but overall it's still a lot of regular expressions, so I take your point. In terms of performance, having run `syntime` many times on a variety of large (>2,000 line) files and comparing them both, my syntax definition is consistently more than 2x faster (usually around 2.3x) with all features enabled on both (which includes additional highlighting functionality not present in the current definition), and there are still areas that I think I can improve. I'll pull together some examples in the repo with the options I used so you can compare, plus I'll provide a comparison of performance for before and after each change as a part of each pull request.

Overall, how does this approach sound to you?

Also, what's your opinion on my approach for the config options (i.e. off, on, or a custom value string)? I like that it allows for easily changing specific items without needing to find the appropriate group name and overriding it, while still being backwards-compatible with the previous options that users will already have (though I'll need to double-check the names align).

**Comment by bhcleek** [comment]
Overall, I think this makes sense. Please try to keep the changes smallish so it's reviewable - syntax changes are tricky and can introduce regressions and thrash easily.

I'd prefer to not change how group names are configured: there's little need for such a thing and overriding works fine and is consistent with how Vim generally works.
