### ISSUE TITLE
GoReportGitHubIssue do nothing

### ISSUE THREAD

**Issue by laplasz** [fatih/vim-go#3492]
### What did you do? (required: The issue will be **closed** when not provided)
called :GoReportGitHubIssue

### What did you expect to happen?
something
### What happened instead?
nothing
### Configuration (**MUST** fill this out):
vim with vim-bootstrap supporting go languge
#### vim-go version:
could not find in the README how to get the version info
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
generated by vim-bootstrap
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 11 2023 23:54:11)
Included patches: 1-2269, 3612, 3625, 3669, 3741
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.18.3 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

O111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/mnt/disk0/home/xxx/.cache/go-build"
GOENV="/mnt/disk0/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/mnt/disk0/home/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/mnt/disk0/home/ebalbar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3660012861=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
no gopls installed

</pre></details>

**Comment by bhcleek** [comment]
What does `:echo go#config#PlayBrowserCommand` output?

**Comment by laplasz** [comment]
`E121: Undefined variable: go#config#PlayBrowserCommand`

**Comment by bhcleek** [comment]
Sorry, that should have been `:echo go#config#PlayBrowserCommand()`

**Comment by laplasz** [comment]
`firefox %URL% &`

I dont have X right now.. so this should open up a browser?

**Comment by bhcleek** [comment]
Yes. `:GoReportGitHubIssue` opens the browser to report a new issue with a lot of the issue template filled in for you.

**Comment by laplasz** [comment]
so, if no X, then an error should be raised, or a printout just to inform the user what is happening - or if no X then printout the markdown template to stdout to be able to copy it. What do you think?

**Comment by bhcleek** [comment]
X is not the only GUI available for Linux systems; I'm not sure what a good solution would be to handle this situation or that it's even worth the effort to try to handle a system that has firefox installed, but no means of running it, but let's see what we can do.

What does `echo $?` output on your system when you try to run firefox from the commandline?

**Comment by bhcleek** [comment]
closed for lack of feedback
