### ISSUE TITLE
necessary import removed by formatter

### ISSUE THREAD

**Issue by laplasz** [fatih/vim-go#3493]
### What did you do? (required: The issue will be **closed** when not provided)
import removed which is needed, similar to #43

saved a file, then the formatting feature removes necessary import
### What did you expect to happen?
import should not be removed
### What happened instead?
import removed
### Configuration (**MUST** fill this out):
vim with vim-bootstrap supporting go language
#### vim-go version:
could not find in the README how to get the version info
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
generated by vim-bootstrap
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 11 2023 23:54:11)
Included patches: 1-2269, 3612, 3625, 3669, 3741
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.18.3 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

O111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/mnt/disk0/home/xxx/.cache/go-build"
GOENV="/mnt/disk0/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/mnt/disk0/home/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/mnt/disk0/home/ebalbar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3660012861=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
no gopls installed

</pre></details>

**Comment by bhcleek** [comment]
What steps should I follow to reproduce the problem you're seeing?

**Comment by laplasz** [comment]
use vimrc file generated with vim bootstrap supporting go language
the use this file:
```
package main

import (
	"encoding/json"
	"fmt"
	"net"
	"os"
	"strconv"
	"sync"
        "time"
	"github.com/go-logr/logr"
)

var once sync.Once
var statusReporter StatusReporter

func newStatusReporter(baseLogger logr.Logger) StatusReporter {

	once.Do(func() { //atomic, does not allow repeating
		ip := "127.0.0.1"
		port, ok := os.LookupEnv("STATUS_AGGREGATOR_PORT")
		if !ok {
			port = "-1"
		}
		data, ok := os.LookupEnv("STATUS_AGGREGATOR_REPORT_PERIOD")
		if !ok {
			data = "20"
		}
		time, err := strconv.ParseInt(data, 10, 32)
		if err != nil {
			time = 20
		}
		time -= 5

		name, ok := os.LookupEnv("OPERATOR_NAME")
		if !ok {
			name = "operator"
		}

		statusReporter = StatusReporter{name: name,
			aggregatorIp:      ip,
			aggregatorPort:    port,
			reportTimerPeriod: time,
			log:               baseLogger} //thread safe

	})
	return statusReporter
}

type StatusReporter struct {
	conn              net.Conn
	aggregatorIp      string
	aggregatorPort    string
	reportTimerPeriod int64
	providers         []StatusProvider
	name              string
	log               logr.Logger
}

type StatusProvider interface {
	GetStatusReport() interface{}
}

func (r *StatusReporter) registerProvider(f StatusProvider) {
	r.providers = append(r.providers, f)
}

func (r *StatusReporter) sendStatusReport(provider StatusProvider) {

	var dataToSend map[string]interface{}

	dataJson, _ := json.Marshal(provider.GetStatusReport())
	err := json.Unmarshal(dataJson, &dataToSend)
	if err != nil {
		r.log.Error(err, "Json encode failed")
		return
	}
	dataToSend["container_name"] = r.name
	dataJson, _ = json.Marshal(dataToSend)

	_, err = r.conn.Write(dataJson)
	if err != nil {
		r.log.Error(err, "Write data failed")
	}
}

func (r *StatusReporter) startStatusReporter() {

	aggregatorAddr := r.aggregatorIp + ":" + r.aggregatorPort
	r.log.Info(fmt.Sprintf("Started listening on %s", aggregatorAddr))
	conn, err := net.Dial("udp", aggregatorAddr)
	if err != nil {
		r.log.Error(err, "Opening connection towards aggregator failed")
		return
	}
	r.conn = conn
	defer r.conn.Close()

	for {
		time.Sleep(time.Duration(r.reportTimerPeriod) * time.Second)

		for _, f := range r.providers {
			r.sendStatusReport(f)
		}
	}
}
```

time import will be deleted after saving the file

**Comment by bhcleek** [comment]
I'm unable to duplicate that behavior. The file saves for me without removing the `time` import.

Can you execute `let g:go_debug=['shell-commands', 'lsp']` and then duplicate the problem? I'd like to know the output of `:messages` and the contents of the `__GOLSP_LOG__` window.

**Comment by laplasz** [comment]
yes, will do that tomorrow - by the why this is the settings currently
```
{'go_fmt_fail_silently': 1, 'go_highlight_generate_tags': 1, 'go_jump_to_error': 1, 'go_list_type': 'quickfix', 'go_highlight_methods': 1, 'go_highlight_fields': 1, 'go_highlight_functions': 1, 'go_highl
ight_operators': 1, 'go_highlight_trailing_whitespace_error': 0, 'go_highlight_space_tab_error': 0, 'go_highlight_build_constraints': 1, 'go_loaded_install': 1, 'go_def_mode': 'gopls', 'go_highlight_stru
cts': 1, 'go_fmt_autosave': 0, 'go_info_mode': 'gopls', 'go_loaded_gosnippets': 1, 'go_highlight_array_whitespace_error': 0, 'go_highlight_types': 1, 'go_highlight_extra_types': 1}
```
so as you can see `go_fmt_command` is commented out, so should not touch the import

**Comment by bhcleek** [comment]
> so as you can see go_fmt_command is commented out, so should not touch the import

`go_fmt_command` is not present, so it will be the default vaule. However, `go_fmt_autosave` is disabled, which will prevent formatting, but `g:go_imports_autosave` will still be enabled by default.

> how to reach __GOLSP_LOG__ window? thx

It will be apparent when `g:go_debug` includes `'lsp'`.

**Comment by bhcleek** [comment]
closed for lack of feedback
