### ISSUE TITLE
is it possible to get the current settings of vim-go by using a command in vim?

### ISSUE THREAD

**Issue by laplasz** [fatih/vim-go#3494]
### What did you expect to happen?
I would like to get the current settings by a command in vim instead of opening the ~/.vimrc file
is it possible to get the settings somehow?

**Comment by bhcleek** [comment]
`:GoReportGitHubIssue` will do it for you. Alternatively, you can execute `:echo string(filter(g:, 'v:key =~ "^go_"'))`
