### ISSUE TITLE
Feature request: definition in the popup (source code)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [fatih/vim-go#3497]
Like this in [coc](https://github.com/neoclide/coc.nvim):

![image](https://user-images.githubusercontent.com/3514015/216694806-f183d017-ea6c-4e3e-8655-2f1dda290284.png)

**Comment by bhcleek** [comment]
What you're asking for already exist. See `:help go#tool#DescribeBalloon`.

**Comment by vitaly-zdanevich** [comment]
I do not understand - how to use it?

**Comment by bhcleek** [comment]
Here's an example of what you need in your vim config: https://github.com/bhcleek/vim/blob/1b24eeec4c7d156b28abbee239ab842532a58767/after/ftplugin/go.vim#L3

After that, you should be able hover over a type and see it's definition

**Comment by vitaly-zdanevich** [comment]
Added `setl balloonexpr=go#tool#DescribeBalloon()`, but nothing on the mouse hover :(

Or should I use some keyboard shortcut?

I use Vim 9 in terminal Kitty.

**Comment by bhcleek** [comment]
You'll also need to set the `balloontermeval` option

**Comment by vitaly-zdanevich** [comment]
WOW IT WORKS hover popup in Vim in terminal, is it possible..... thanks

**Comment by vitaly-zdanevich** [comment]
But what about Neovim?

**Comment by vitaly-zdanevich** [comment]
@bhcleek please
