### ISSUE TITLE
Is there any way I can get call hierarchy of a method like eclipse?

### ISSUE THREAD

**Issue by you-n-g** [fatih/vim-go#350]
I'm using vim-go and I think it would be cool if it support such a function that tells me where the function I'm reading is called.

**Comment by fatih** [comment]
Hi @you-n-g Use `:GoCallers` on a function and it will tell where it was called. Under the hood `oracle` is used. Check out the docs for more information.

**Comment by you-n-g** [comment]
I see. Thanks!
