### ISSUE TITLE
gorename on open buffer doesn't refresh in split view

### ISSUE THREAD

**Issue by hraban** [fatih/vim-go#351]
When I do a gorename in split view, buffer a.go, buffer b.go, and in the first I gorename something that has effect in the second, it doesn't propagate to the view. The file updates on disk, but not on my screen until I `:e`. It doesn't even notify me of the changes (because it's already open in a different pane).

**Comment by fatih** [comment]
How is it if you add:

```
set autoread
```

to your `.vimrc` file ?

**Comment by hraban** [comment]
Nothing. That just helps prevent the "this file was changed outside vim, but unchanged inside vim, do you want to reload it?" prompt. But it doesn't show up if the buffer is already open in a split screen.

**Comment by fatih** [comment]
>  But it doesn't show up if the buffer is already open in a split screen. 

What do you mean with this sentence? If one of the files gorename touches is already opened in one of your views, it will automatically updated. Isn't this what you want ?

**Comment by hraban** [comment]
it is what I want, but it's not what happens. Try this (in your $GOPATH/src)

```sh
mkdir test
cd test
echo -e 'package main\n\nfunc main() { foo() }' > a.go
echo -e 'package main\n\nfunc foo() int { return 3 }' > b.go
vim a.go
```

Now create a split view (c-w, v) and open b.go in one of the panes (:e b.go). Go to the "foo" name, and rename it (:GoRename bar). What happens in the other pane? Nothing, it still shows as "foo". Switch to it (c-w, w), still nothing happens. Now refresh it (:e) and voila, you see bar(). Or did I miss something?

**Comment by fatih** [comment]
Confirmed. I could reproduce it. There is some stuff to do here.

1. We need get the list of changed files, not sure GoRename gives it
2. We need a way to update buffers whose are changed and are in the changed list in step 1

**Comment by hraban** [comment]
This is related to #352 in a way: if you don't allow (or at least warn before) doing a GoRename with any unsaved buffers (which I still think is a good idea) then this problem is also solved: you can safely reload every file.

**Comment by fatih** [comment]
Yeah, I think it would be early simple to plug it into Vim's own eventer system (which notifies whenever something changes, a file, buffer, etc..). NerdTree has this too. I need some time to improve the GoRename situation imho. Thanks for bringing this up.

**Comment by hraban** [comment]
No problem, thanks for the plugin and good luck.

**Comment by fatih** [comment]
This is finally closes after a long time. Give it a try and let me know how it works. Just pull the latest master and you're good to go.

**Comment by hraban** [comment]
Hi, just tried it out with no outstanding changes in buffers (i.e. after :wa) and it worked, thanks. However, in the above example, if I have changes in a.go, unsaved, then go to b.go, and do :GoRename on a name that is also in a.go, the rename happens on disk (in both a.go and b.go) but neither file is reloaded. So both buffers look like nothing happened. Not the same issue so not worth reopening this ticket over, but renames with unsaved buffers is an open problem, it seems.
