### ISSUE TITLE
 goPredefinedIdentifiers should be different color from boolean

### ISSUE THREAD

**Issue by i1v** [fatih/vim-go#3515]
Currently nil and iota have the same color as boolean:

https://github.com/fatih/vim-go/blob/3d16fa33a9a1b707a15da3ca4e3f2a7374d0902a/syntax/go.vim#L53-L57

I think it would be more readable if predefined identifiers are a different color than booleans.

**Comment by bhcleek** [comment]
Because `nil`, `iota,`, `true`, and `false` are all [predeclared identifiers](https://go.dev/ref/spec#Predeclared_identifiers).
