### ISSUE TITLE
 Syntax highlighting only

### ISSUE THREAD

**Issue by i1v** [fatih/vim-go#3516]
I only care about the highlighting, nothing else. So I got this file:

https://github.com/fatih/vim-go/blob/master/syntax/go.vim

and copy to my local Vim install. However I get these errors:

~~~
Unknown function: go#config#FoldEnable
~~~

can you please configure this package such that people can just drop in the `go.vim` only and be done with it?

**Comment by bhcleek** [comment]
> can you please configure this package such that people can just drop in the go.vim only and be done with it?

No.

However, vim-go's syntax is provided to Vim for the Go syntax there. No need for vim-go to do anything special here.

ref: https://github.com/vim/vim/pulls?q=is%3Apr+author%3Abhcleek+is%3Aclosed

**Comment by i1v** [comment]
> However, vim-go's syntax is provided to Vim for the Go syntax there. No need for vim-go to do anything special here.

this assumes that the current code here is perfect as is. If someone has an issue with the code, they have to come here, not to the Vim repo. In those cases, it helps if the version here can be dropped in, the same as the Vim repo version.

**Comment by bhcleek** [comment]
It assumes no such thing. The syntax file in vim-go is not going to be changed to support using only the syntax file from vim-go without any other parts of vim-go. There are plenty of ways to use the syntax file from vim-go without the other bits of vim-go affecting your working style (i.e. disable gopls and the auto format and auto imports). 

If you truly want only the syntax file, then use the syntax file that comes with Vim; it includes all the vim-go syntax and is periodically updated as changes to vim-go's syntax file are proven stable enough to include in Vim. 

If the syntax file from Vim has a problem, yes, you can report it here. In that case, I'll either fix it here and the submit a PR to vim or it's likely already fixed here and all I need to do is submit a PR to vim.

**Comment by i1v** [comment]
> It assumes no such thing. The syntax file in vim-go is not going to be changed to support using only the syntax file from vim-go without any other parts of vim-go. There are plenty of ways to use the syntax file from vim-go without the other bits of vim-go affecting your working style (i.e. disable gopls and the auto format and auto imports).

maybe if you could provide some context to your decision, it would help others to understand your point of view. I have seem similar issues to this posted before, but I have never once seen a technical explanation as to WHY this wont be done, other than "because I say so". If "because I say so" is the reason, I respect that, but it would help if that is made explicit so no one questions it in the future.

The benefit of a drop in solution, like the `go.vim` in the Vim repo, is you can just copy paste that one file and be done with it, no special configuration. Do you generally no understand that benefit, or is that benefit subtracted by some drawback that I am not aware of? Dont Vim scripts offer a way to put the non-syntax bits inside a `if` statement or similar, to allow what I am suggesting?

**Comment by bhcleek** [comment]
The handling of all the config options for vim-go are in a single file, `autoload/go/config.vim`, even the options that exist purely to control syntax. That provides an easy way to know where that handling is. I'm not interested in breaking it out by purpose into different files.

There are bits in the vim-go file that are currently in vim's syntax go.vim that should probably be ripped out, but I just haven't done that yet, though I probably will (e.g. the `goDebug*`, `goSameId`, `goDiagnostic*` and `goDecls` groups). Once that's done, there will be a bit more divergence between what's in vim-go's and vim's syntax files

What you're asking for is available to you from vim: https://github.com/vim/vim/blob/master/runtime/syntax/go.vim. You can get it from there. Vim-go serves vim-go users, and I also maintain vim's go syntax file to serve gophers that use vim without vim-go.

**Comment by i1v** [comment]
> What you're asking for is available to you from vim: https://github.com/vim/vim/blob/master/runtime/syntax/go.vim. You can get it from there. Vim-go serves vim-go users, and I also maintain vim's go syntax file to serve gophers that use vim without vim-go.

thats much appreciated, but what you're suggesting creates an awkward situation. You say the code I am interested in is at https://github.com/vim/vim, but you are not a maintainer of `vim/vim`. Further, if I post an issue about the syntax code to `vim/vim`, it gets closed because we are told to contact the syntax developer directly.

then we users do that, they find that the place where they WOULD post an issue, doesn't even have the code in question, but some other code. Then when that concern is raised, the maintainer says essentially "yes the two codes are different. No, I will not change it". I am sorry for the repeated comments, but I just dont understand this current arrangement.

Would you be willing to ALSO host the exact `vim/vim` file `go.vim` somewhere? It could be here in another folder, or another branch, or even its own repo. that way, people could visit one place that has the `go.vim` they are concerned about, then post any issue or pull request to that same repo. If the `vim/vim` file `go.vim` is already hosted in some non `vim/vim` location, I would be interested to see it, so I can avoid troubling you further.

**Comment by bhcleek** [comment]
> the maintainer says essentially "yes the two codes are different. No, I will not change it".

Where has that been said? The differences between the syntax file in vim and vim-go are minimal and fall into two basic categories. The first is that the vim syntax files has options that do not depend on vim-go, but their effect is the same. The second is very recent changes to vim-go that I have not created PRs for in vim yet.

>  if I post an issue about the syntax code to vim/vim, it gets closed because we are told to contact the syntax developer directly.

It does? That's news to me. Sometimes you may be directed here, but often Braam will tag me on the issue or pull request over there. e.g. https://github.com/vim/vim/pull/11563#issuecomment-1318673231

> I just don't understand this current arrangement.

Vim's syntax file for go comes from vim-go currently. I updated it periodically. Vim-go's syntax file rarely changes, but it does occasionally. Sometime after it us updated in vim-go, I'll submit a PR to vim/vim to update its go.vim

If you find problems, feel free to raise them here or there. Depending on the nature of the problem, I'm likely to fix it here first and then later submit a PR to vim.

**Comment by i1v** [comment]
> It does? That's news to me. Sometimes you may be directed here, but often Braam will tag me on the issue or pull request over there.

I had a pull request that was closed, due to me not being the maintainer (now deleted):

https://github.com/vim/vim/pull/7347

to be fair, it looks like the upstream maintainer added my changes in a quickly following PR, so maybe I remember the situation worse than it actually was. I still think its a bad idea for Vim to be ad-hoc maintaining all the different syntaxes, but if thats their decision they can deal with it. I will try contacting them.
