### ISSUE TITLE
vim-go: failed to sync breakpoints

### ISSUE THREAD

**Issue by xD-saleem** [fatih/vim-go#3518]
### What did you do? (required: The issue will be **closed** when not provided)

Made a test file to test the new debug config
```
package main

import "fmt"
func main() {
        hi := 5
        fmt.Println(hi)
}
```

### What did you expect to happen?

I debug my code with vim-go

### What happened instead

I get this screen rather than the code.
![Screenshot from 2023-02-14 18-46-11](https://user-images.githubusercontent.com/25384958/218998450-bf66f78c-92c1-49b0-958f-f05a110278b5.png)

when i type ```:messages``` i get this error.
```
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: Finished loading packages.
vim-go: failed to sync breakpoints (function <SNR>77_on_stdout[1]..<SNR>77_neocb[61]..<SNR>83_out_cb[9]..<SNR>83_connect[42]..<SNR>83_sync_breakpoints[5]..<SNR>85_await[3]..<SNR>83_on_dat
a[27]..<SNR>83_handleRPCResult[7]..<SNR>83_handle_stack_response[12]..<SNR>83_update_windows[11]..<SNR>83_update_breakpoint[24]..<SNR>83_sync_breakpoints, line 6): Vim(let):E716: Key not
present in Dictionary: "result.Breakpoints"
vim-go: failed to sync breakpoints (function <SNR>77_on_stdout[1]..<SNR>77_neocb[61]..<SNR>83_out_cb[9]..<SNR>83_connect[42]..<SNR>83_sync_breakpoints, line 6): Vim(let):E716: Key not pre
sent in Dictionary: "result.Breakpoints"
vim-go: current goroutine not found...
vim-go: No Goroutines Running Now...
Press ENTER or type command to continue
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
let g:clang_format#auto_format=1
set textwidth=0
set wrapmargin=0

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

set textwidth=0
set wrapmargin=0


let g:clang_format#auto_format=1

" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
autocmd FileType go nmap <leader>t <Plug>(go-test)

autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')




```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.8.3

#### Go version (`go version`):

go version go1.20.1 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/slim/.cache/go-build"
GOENV="/home/slim/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/slim/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/slim/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2046189125=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=

</pre></details>

**Comment by bhcleek** [comment]
I'm able to reproduce this sporadically on both vim and neovim.

**Comment by xD-saleem** [comment]
@bhcleek Reverting to old commit worked. Thank you so much
