### ISSUE TITLE
Don't allow gorename with unsaved changes

### ISSUE THREAD

**Issue by hraban** [fatih/vim-go#352]
It's not immediately obvious that gorename works on the filesystem, completely outside vim. When I have unsaved edits, this creates a conflict and I am screwed. I think at least a "warning: save your buffers before using gorename" if any unsaved buffers are detected would be nice. Or save all buffers automatically before :GoRename?

**Comment by fatih** [comment]
We can only detect the file you are calling gorename on it, but not the others. So if `gorename` is operating on other files, the scope is determined by `gorename` itself. Vim-go doesn't have any idea about the scope itself. I would not save all buffers, but you can do it easily with `:wa` which will save all changed buffers. You can combine this, with the gorename command to a mapping such as:

```
au FileType go nmap  <leader>e  :wa<cr><Plug>(go-rename)
```

So now whenever you call `<leader>e` it will save all buffer before exeucing `gorename`.

**Comment by hraban** [comment]
I understand the situation, it's not a functionality problem, just a UI issue. Basically, the work-flow for using :GoRename is always this:

```vim
:wa
:GoRename whatever
:bufdo e
```

And if you forget any of that, you can cause yourself quite some trouble.

What would you say about a patch which:

1) Detects if any unsaved go buffers are open, and prevents GoRename from running if there are
2) executes :bufdo e after gorename

?
