### ISSUE TITLE
Add :GoPlayRun command, to run play.golang.org snippets directly

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#353]
I'm tired creating a new buffer, copying the whole content and running it. We should have something 

```viml
:GoPlayRun http://play.golang.org/p/3WhFYO7qFC
```

Which automatically downloads the script, opens a new buffer and runs it. We have the opposite already `:GoPlay` which creates a new script on http://play.golang.org. This would be also handy.

**Comment by wingyplus** [comment]
I experiment about this feature that use curl to fetch and `nokogiri` to extract code from html in example.

`curl -s http://play.golang.org/p/3WhFYO7qFC | nokogiri -E utf-8 --type html -e 'puts $_.css(\"textarea#code\").children.text'` 

I didn't find any tools better than nokogiri for query selector. What do you recommend about it? I can send a pull request if possible.

**Comment by fatih** [comment]
Append  `.go` to the url and call curl :)

**Comment by fatih** [comment]
Example:

```go
curl http://play.golang.org/p/NyNHXKNxhe.go
```

**Comment by wingyplus** [comment]
Wow, I doesn't know it can. :D

**Comment by fatih** [comment]
I don't see any use case for this.  Closing.
