### ISSUE TITLE
-mod=mod not supported

### ISSUE THREAD

**Issue by rosscosack** [fatih/vim-go#3530]
### What did you do? (required: The issue will be **closed** when not provided)
I installed the plugin via vundle and issued command :GoInstallBinaries

### What did you expect to happen?
I expected the binaries to be installed

### What happened instead?
I get this error
`vim-go: godef not found. Installing github.com/rogpeppe/godef@latest to folder /home/ross/go/bin/
vim-go: Error installing github.com/rogpeppe/godef@latest: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: motion not found. Installing github.com/fatih/motion@latest to folder /home/ross/go/bin/
vim-go: Error installing github.com/fatih/motion@latest: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: errcheck not found. Installing github.com/kisielk/errcheck@latest to folder /home/ross/go/bin/
vim-go: Error installing github.com/kisielk/errcheck@latest: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: dlv not found. Installing github.com/go-delve/delve/cmd/dlv@latest to folder /home/ross/go/bin/
vim-go: Error installing github.com/go-delve/delve/cmd/dlv@latest: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: gorename not found. Installing golang.org/x/tools/cmd/gorename@master to folder /home/ross/go/bin/
vim-go: Error installing golang.org/x/tools/cmd/gorename@master: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: iferr not found. Installing github.com/koron/iferr@master to folder /home/ross/go/bin/
vim-go: Error installing github.com/koron/iferr@master: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: gotags not found. Installing github.com/jstemmer/gotags@master to folder /home/ross/go/bin/
vim-go: Error installing github.com/jstemmer/gotags@master: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: impl not found. Installing github.com/josharian/impl@main to folder /home/ross/go/bin/
vim-go: Error installing github.com/josharian/impl@main: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: goimports not found. Installing golang.org/x/tools/cmd/goimports@master to folder /home/ross/go/bin/
vim-go: Error installing golang.org/x/tools/cmd/goimports@master: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: golangci-lint not found. Installing github.com/golangci/golangci-lint/cmd/golangci-lint@latest to folder /home/ross/go/bin/
vim-go: Error installing github.com/golangci/golangci-lint/cmd/golangci-lint@latest: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: gomodifytags not found. Installing github.com/fatih/gomodifytags@latest to folder /home/ross/go/bin/
vim-go: Error installing github.com/fatih/gomodifytags@latest: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: keyify not found. Installing honnef.co/go/tools/cmd/keyify@master to folder /home/ross/go/bin/
vim-go: Error installing honnef.co/go/tools/cmd/keyify@master: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: staticcheck not found. Installing honnef.co/go/tools/cmd/staticcheck@latest to folder /home/ross/go/bin/
vim-go: Error installing honnef.co/go/tools/cmd/staticcheck@latest: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: asmfmt not found. Installing github.com/klauspost/asmfmt/cmd/asmfmt@latest to folder /home/ross/go/bin/
vim-go: Error installing github.com/klauspost/asmfmt/cmd/asmfmt@latest: -mod=mod not supported (can be '', 'readonly', or 'vendor')
vim-go: installing finished!`
I have left off the first part because I can't scroll back to it

#### vim-go version:
I can not tell, but I installed it today so I assume it's `latest stable release`

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 11 2023 23:54:11)
Included patches: 1-2269, 3612, 3625, 3669, 3741
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.13.8 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ross/.cache/go-build"
GOENV="/home/ross/.config/go/env"
GOEXE=""
GOFLAGS="-mod="
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ross/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ross/projects/top/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build088203071=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Your installed version of Go, 1.13.8, is not supported by vim-go. Vim-go maintains support for the actively supported Go releases: https://go.dev/doc/devel/release#policy. Currently, that's Go 1.20 and Go 1.19.
