### ISSUE TITLE
Docstring in autocompletion is truncated.

### ISSUE THREAD

**Issue by jbarnes7952** [fatih/vim-go#3536]
The docstring shown with (shift-K) is different than the docstring shown with (c-X)(x-O).  The  (c-X)(x-O) docstring appears to be truncated.   

For example, with fmt.Println shift-K GoDoc shows:

> func fmt.Println(a ...any) (n int, err error)

> Println formats using the default formats for its operands and writes to standard output.
> Spaces are always added between operands and a newline is appended.
> It returns the number of bytes written and any write error encountered.

whereas the autocompletion invoked via (c-X)(x-O) shows a significantly shorter (and less useful) description. 
> Println func(a ...any) (n int, err error)

> Println formats using the default formats for its operands and writes to standard output.

The text is does not exist in the window, it cannot be scrolled and size of the window does not appear to be relevant. It is unclear if this is an expected behavior, however I have found few screenshots that suggest the full text should be there.

### What did you do? (required: The issue will be **closed** when not provided)

For testing I installed a isolated instance of vim-go and invoked help functions.

> docker run -ti --rm ubuntu /bin/bash
> 
> apt update && apt install -y vim git wget
> 
> wget https://go.dev/dl/go1.20.2.linux-amd64.tar.gz 
> rm -rf /usr/local/go && tar -C /usr/local -xzf go1.20.2.linux-amd64.tar.gz
> export PATH=$PATH:/usr/local/go/bin
> 
> cd && mkdir .vim/pack/plugins/start -p && cd .vim/pack/plugins/start
> git clone https://github.com/fatih/vim-go.git
> cd
> vim  -c GoInstallBinaries main.go

Once binaries are installed, the 'vim-go' generated main.go should show:

```
package main

import "fmt"

func main() {
        fmt.Println("vim-go")
}

```
with the cursor over "Println", shift-K will show:

> func fmt.Println(a ...any) (n int, err error)

> Println formats using the default formats for its operands and writes to standard output.
> Spaces are always added between operands and a newline is appended.
> It returns the number of bytes written and any write error encountered.

(c-X)(c-O) shows only:

> Println func(a ...any) (n int, err error)
> 
> Println formats using the default formats for its operands and writes to standard output.

### What did you expect to happen?

Show complete (same) help?

### What happened instead?

with the cursor over "Println", shift-K will show:

> func fmt.Println(a ...any) (n int, err error)

> Println formats using the default formats for its operands and writes to standard output.
> Spaces are always added between operands and a newline is appended.
> It returns the number of bytes written and any write error encountered.

(c-X)(c-O) shows only:

> Println func(a ...any) (n int, err error)
> 
> Println formats using the default formats for its operands and writes to standard output.

The lines:

> Spaces are always added between operands and a newline is appended.
> It returns the number of bytes written and any write error encountered.

**Are missing.**

### Configuration (**MUST** fill this out):

Plugin is auto-loaded (~/.vim/pack/plugins/start) , there is NO configuration.

####  `vimrc` you used to reproduce:

Again, NO .vimrc is used as the plugin is autoloaded.

</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 17 2023 11:08:34)
Included patches: 1-2269, 3612, 3625, 3669, 3741

#### Go version (`go version`):
go version go1.20.1 linux/amd64

#### Go environment
<details>
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1858224377=/tmp/go-build -gno-record-gcc-switches"
</details>

#### gopls version
<details>
                                                              
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=

**Comment by bhcleek** [comment]
These are served by different LSP requests. You're right, the doc shown in the preview during completion will be a truncated form.

**Comment by jbarnes7952** [comment]
> These are served by different LSP requests. You're right, the doc shown in the preview during completion will be a truncated form.

Thanks, I was thinking it might be something like that on the backend as the func definitions themselves are slightly different.

Is this intentional?  Is there a way to have the omnicompletion use the same doc string as the GoDoc result?

**Comment by bhcleek** [comment]
Yes, it's intentional. The completion handler and the doc both come from `gopls`. There is no way to cause `gopls`'s `textDocument/completion` response to provide the full doc as far as I know.

**Comment by jbarnes7952** [comment]
Thanks bhcleek.
