### ISSUE TITLE
Compile error chevrons not showing when I upgrade to go1.4.2

### ISSUE THREAD

**Issue by GeorgeMac** [fatih/vim-go#354]
Previously I was using a Go distribution via brew on Mac OSX Yosemite. 
I have recently checked Go out from Github and built 1.4.2.

Since then the line error chevrons (`>>`) have stopped showing up. There are no other errors to indicate what the issue might be. I have tried messing with `GOROOT` and so on, in the hope of finding the problem, but to no avail. 

Any thoughts? Has anyone else had issues upgrading to go1.4.2, or have I just done something stupid?

Cheers

**Comment by fatih** [comment]
Hi @GeorgeMac  . The `>>` signs are not a part of vim-go. I think you are using https://github.com/scrooloose/syntastic.  Also I recommend to delete any Go installation and just use the Mac OS X installer. It's painless and rock solid.

**Comment by GeorgeMac** [comment]
Oh haha oops, cheers for the quick response! Ill look into that.
