### ISSUE TITLE
Toggling breakpoints fail after debugging once

### ISSUE THREAD

**Issue by pendar747** [fatih/vim-go#3540]
### What did you do? (required: The issue will be **closed** when not provided)

1. Run delve:
```
dlv exec <executable> --listen :9000 --accept-multiclient --headless --continue
```
2. open vim, navigate to a go file and run `:GoDebugConnect localhost:9000`
3. Place a break point in the file
4. run `GoDebugContinue` and pass through all breakpoints
5. Toggle a breakpoint by `GoDebugBreakpoint` or pressing F9

### What did you expect to happen?
Breakpoint is toggled on line.

### What happened instead?
After this vim hangs for a few seconds and then displays this error:
```
vim-go: could not toggle breakpoint: Vim(let):E716: Key not present in Dictionary: "result"
```

#### vim-go version:

git hash `e8e175ec6e47b31111dbfb0169537fda26346fe2`

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

Full vimrc: https://gist.github.com/pendar747/71ad981bbb50139a1b50b986efa9f0c6

```vim

syntax on


call plug#begin()
" This is where we will add plugins to install

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'preservim/nerdcommenter'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'dkprice/vim-easygrep' 
Plug 'jparise/vim-graphql'
Plug 'prettier/vim-prettier'
Plug 'tpope/vim-rhubarb'
Plug 'vim-test/vim-test'
Plug 'tpope/vim-dispatch'
Plug 'airblade/vim-gitgutter'
Plug 'leafgarland/typescript-vim'
Plug 'sainnhe/everforest'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

"""" Color scheme
" Important!!
if has('termguicolors')
  set termguicolors
endif
" For light version.
set background=dark
" Transparent background
let g:everforest_transparent_background = 1
" Set contrast.
" This configuration option should be placed before `colorscheme everforest`.
" Available values: 'hard', 'medium'(default), 'soft'
let g:everforest_background = 'soft'
" For better performance
let g:everforest_better_performance = 1
colorscheme everforest

" Go debug
let g:go_debug_address="localhost:9000"

" vim test
" let test#strategy = "dispatch"

" Prettier
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0
let g:prettier#config#tab_width = 2

set wildignore=*/node_modules/*
"set grepprg=rg\ --vimgrep\ --smart-case

set re=2

" tab settings
set expandtab
set tabstop=2
set shiftwidth=2 
set softtabstop=2

" Relative line number
set relativenumber

" File tree view
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

" Git status bar
let g:airline_powerline_fonts = 1

" Close nerdtree when closing other windows
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Refresh nerdtree when changing files
augroup DIRCHANGE
    au!
    autocmd DirChanged global :NERDTreeCWD
augroup END

" Coc-NVIM Golang config
autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar  4 2023 14:02:05)
macOS version - arm64
Included patches: 1-1313

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar  4 2023 14:02:05)
macOS version - arm64
Included patches: 1-1313

#### Go version (`go version`):

go version go1.20.2 darwin/arm64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/pendar/Library/Caches/go-build"
GOENV="/Users/pendar/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/pendar/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pendar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/pendar/dev/flow-cloud/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l6/cyrwt95d2dxdfryly5kkw53m0000gq/T/go-build788898688=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_debug_address = 'localhost:9000'
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
When you run `:GoDebugBreakpoint` the second time, is the process currently halted waiting for input from the debugger, or is it running?

The contents of the `__GODEBUG_OUTPUT__` may help us understand what's going on; can you provide that?

**Comment by bhcleek** [comment]
closed for lack of feedback
