### ISSUE TITLE
GoTestFunc or GoTestFile: "no tests found"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [fatih/vim-go#3542]
The code is proprietary, I cannot share it :(

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb 26 2023 13:21:10)
Included patches: 1-1157
Modified by Gentoo-9.0.1157

#### Go version (`go version`):

go version go1.20.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vitaly/.cache/go-build"
GOENV="/home/vitaly/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vitaly/go/pkg/mod"
GONOPROXY="github.com/River-Island/*"
GONOSUMDB="github.com/River-Island/*"
GOOS="linux"
GOPATH="/home/vitaly/go"
GOPRIVATE="github.com/River-Island/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/vitaly/p/ri/svi/serv/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build584633735=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.4
    golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_gosnippets = 1
g:go_gopls_local = 'github.com/River-Island'
g:go_jump_to_error = 1
g:go_build_tags = 'unit_tests'
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:OFF
</pre></details>

**Comment by bhcleek** [comment]
Without duplication steps, it's basically impossible for me to analyze what could be wrong, and I can tell you that generally `:GoTestFile` and `:GoTestFunc` work fine. The error you're seeing _might_ be related to build tags, though. Do you a build constraint in the test file and have you set `:GoBuildTags` if so?

**Comment by bhcleek** [comment]
After looking more closely at the vim-go code involved, build tags wouldn't explain this error

If you can provide provide duplication steps, I'm happy to dig into this. If not, then we'll have to close it.

**Comment by vitaly-zdanevich** [comment]
This is a proprietary code, so I cannot share the repo :(

For example, this is the start of the file:

![image](https://user-images.githubusercontent.com/3514015/233176361-617aac5c-614a-43d0-b211-040b4ee6491b.png)

And this is the end:

![image](https://user-images.githubusercontent.com/3514015/233176436-f6423584-f84d-43b1-8933-5ee4c1d2225d.png)

**Comment by bhcleek** [comment]
I don't need the proprietary code, just steps to duplicate this problem.

Does that file contain any actual tests in it? I don't see any Go test functions in what you've pasted.

**Comment by vitaly-zdanevich** [comment]
> Does that file contain any actual tests in it?

Yes, you can see on the first screenshot, right after imports.

**Comment by bhcleek** [comment]
Those are not Go tests. Go test functions take the form `func TestFoo`. What I see right below the import block is a method on a type named `TestSuite`. Both `:help :GoTestFunc` and https://go.dev/doc/code#Testing may be helpful for you.

**Comment by vitaly-zdanevich** [comment]
Maybe another format, but this is a file with tests, `go test` runs it...

**Comment by bhcleek** [comment]
You must be using some kind of testing framework that leverages that code to perform tests, but `func (s *TestSuite) TestCreateShipmentTrails() {` is not a Go test.

How would you run just that one test at the command line?

**Comment by vitaly-zdanevich** [comment]
> How would you run just that one test at the command line?

For example GoLand internally runs this:

<img width="1089" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/3514015/233568181-cd98652d-ff78-4de8-b54c-b808d0a58a56.png">

**Comment by bhcleek** [comment]
Is there a test named `TestStringSet` defined in the file that you attached the screenshots from earlier?

**Comment by vitaly-zdanevich** [comment]
No, but about that file:

> GOROOT=/opt/homebrew/Cellar/go/1.20.2/libexec #gosetup
GOPATH=/Users/ri/go #gosetup
/opt/homebrew/Cellar/go/1.20.2/libexec/bin/go test -c -tags unit_tests -o /Users/ri/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___TestCreateShipmentTrails_in_github_com_River_Island_svi_services_service_inventory_trailstorer.test github.com/River-Island/svi-services/service/inventory/trailstorer #gosetup
/opt/homebrew/Cellar/go/1.20.2/libexec/bin/go tool test2json -t /Users/ri/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___TestCreateShipmentTrails_in_github_com_River_Island_svi_services_service_inventory_trailstorer.test -test.v -test.paniconexit0 -test.run ^\QTestSuite_TrailStorerService\E$/^\QTestCreateShipmentTrails\E$ -testify.m ^TestCreateShipmentTrails$

**Comment by bhcleek** [comment]
It looks like you're using testify. Note that testify documents that you must kick off suite tests with a regular go test. From https://pkg.go.dev/github.com/stretchr/testify/suite:
```
// In order for 'go test' to run this suite, we need to create
// a normal test function and pass our suite to suite.Run
func TestExampleTestSuite(t *testing.T) {
    suite.Run(t, new(ExampleTestSuite))
}
```

Vim-go does not know about testify.

**Comment by bhcleek** [comment]
Where is your `TestCreateShipmentTrails` test? Is it in the same file whose screenshots you provided in your originating message above?

**Comment by vitaly-zdanevich** [comment]
Yes, in the command below you can see it
![image](https://user-images.githubusercontent.com/3514015/234053079-fa681fd0-6f73-430f-a5eb-f1e8c63eb400.png)

**Comment by bhcleek** [comment]
I'm sorry, but I don't see that it's in the same file. All I see is that GoLand is passing args that will include cause the test suite method you want to run to be run, but that's not the same as `TestCreateShipmentTrails` being in that file. 

Can you open the file that contains `TestCreateShipmentTrails` and run `:GoTestFile` from that file successfully?

**Comment by vitaly-zdanevich** [comment]
> Can you open the file that contains `TestCreateShipmentTrails` and run `:GoTestFile` from that file successfully?

`vim-go: [test] no tests found`

**Comment by bhcleek** [comment]
Can you show me the output of `:g/^func Test.*/` from that file?

**Comment by vitaly-zdanevich** [comment]
> Pattern not found: ^func Test.*

**Comment by vitaly-zdanevich** [comment]
> `suite.Run`

I did `grep` on our repo - such code is not exists, `Run` too.

**Comment by bhcleek** [comment]
These testify tests are being executed _somehow_. What does `go test -list '.*'` report when executed in the directory that holds the package you want to test?

**Comment by vitaly-zdanevich** [comment]
I found the root cause: we need to tun `GoTestFunc` from `suite_test.go` in the same folder, because it has `suite.Run(t, new(TestSuite))` inside. So I think, maybe we can implement something like `GoTestFolder`, relative to the currently open file?

**Comment by bhcleek** [comment]
That's what `:GoTest` does.

**Comment by vitaly-zdanevich** [comment]
As I understand, this is for $PWD folder, but what about folder of the current buffer? maybe `:GoTest %`?

**Comment by bhcleek** [comment]
@vitaly-zdanevich were able to run the tests you wanted to run?
