### ISSUE TITLE
GoDecls should use fzf preview-fg and preview-bg for color

### ISSUE THREAD

**Issue by kerma** [fatih/vim-go#3544]
### What did you do? (required: The issue will be **closed** when not provided)

Used :GoDecls

### What did you expect to happen?

:GoDecls pops up a fzf wrapped window with a matching color scheme.

### What happened instead?

fzf window colors are not matching with the scheme. 

To me it seems that the GoDecls implementation is picking up the right colors, but the configuration used in fzf --color parameter is not resulting in the expected output. 

https://github.com/fatih/vim-go/blob/master/autoload/fzf/decls.vim?plain=1#L137

When I change the configuration to use preview-fg and preview-bg I see the expected color output. 

Two relevant lines from `ps` output when GoDecls is triggered:

```
sh -c 'fzf'  -n 1 --with-nth 1,2 --delimiter=$'\t' --preview "echo {3}" --preview-window "wrap" --ansi --prompt "GoDecls> " --expect=ctrl-t,ctrl-v,ctrl-x --color dark,fg:246,bg:235,bg+:236 --no-height --border=rounded > /var/folders/4r/lt5c

fzf -n 1 --with-nth 1,2 --delimiter=\011 --preview echo {3} --preview-window wrap --ansi --prompt GoDecls>  --expect=ctrl-t,ctrl-v,ctrl-x --color dark,fg:246,bg:235,bg+:236 --no-height --border=rounded
```

The strange part is that I cannot figure out what changed, because this used to work for me still couple of weeks back. I've updated nvim, vim-go, and fzf to latest versions, and played around with fzf old versions, but cannot re-produce the old expected behaviour without using preview-fg/preview-bg. 

#### vim-go version:

master HEAD

####  `vimrc` you used to reproduce:

n/a, just vim-go plugin enabled can reproduce the issue.

#### Vim version (first three lines from `:version`):

nvim 0.9.0

#### Go version (`go version`):
1.20.3

**Comment by bhcleek** [comment]
It looks like you've created https://github.com/junegunn/fzf/issues/3283, too. Nothing changed in vim-go. I'll leave this open until we get an answer on https://github.com/junegunn/fzf/issues/3283 in case something intentionally changed in fzf that vim-go needs to adjust to.

**Comment by bhcleek** [comment]
@kerma I took a look at this on my system, and my colorscheme is respected. I wonder if you have the `FZF_DEFAULT_OPTS` environment variable or the `g:fzf_preview_window` Vim variable set?

**Comment by kerma** [comment]
No `FZF_DEFAULT_OPTS`:

```
FZF_DEFAULT_COMMAND=ag -p ~/.gitignore --ignore vendor --no-color -g ""
FZF_ALT_C_COMMAND=fd --hidden --follow --exclude '.git' --exclude 'node_modules' --type d
FZF_PREVIEW_WINDOW=:hidden
FZF_DEFAULT_OPTS=--layout=reverse
FZF_CTRL_T_COMMAND=ag -p ~/.gitignore --ignore vendor --no-color -g ""
FZF_CTRL_T_OPTS=--preview-window 'right:50%:nohidden' --bind 'enter:execute(nvim {+} >/dev/tty)+abort'
```

For preview window i have: `let g:fzf_preview_window = ['right:50%', 'ctrl-/']`

I can also reproduce this outside of vim:

https://github.com/fatih/vim-go/assets/735108/88192f3b-a619-44b5-8cd1-5c5a5138b45a

```sh
$ env | grep -i term
TERM=xterm-256color
COLORTERM=truecolor
```
