### ISSUE TITLE
godef did not works as expected

### ISSUE THREAD

**Issue by keyforone** [fatih/vim-go#3545]
### What did you do? (required: The issue will be **closed** when not provided)

I have Vim of version 9.0.1510, go of version of go1.20.4 installed in mac os x(darwin/amd64), with vim plugin installed as below in .vimrc

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/nerdtree'
Plugin 'dgryski/vim-godef'
call vundle#end()

and specify godef binary path with "let g:godef_command="/Users/bytedance/dev/bin/godef" configured in .vimrc.

The problem is that when i touch "gd" command in go project, it just shows ":call GodefUnderCursor()" msg, but does not jump to method definition or params definition

### What did you expect to happen?

the gd command works as expected

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>
"==============================================================================
" 基础配置 
"==============================================================================

" 设置 vimrc 修改保存后立刻生效，不用在重新打开
autocmd BufWritePost $MYVIMRC source $MYVIMRC

filetype plugin indent on

" 语法高亮、显示行号
syntax on
set nu

" 允许使用backspace删除字符
set backspace=2

" 高亮显示匹配的字符串
set hlsearch

" 当前目录找不到tags文件时请到上层目录查找
" set tags=tags;/

"==============================================================================
" 插件管理
"==============================================================================
set rtp+=~/.vim/bundle/Vundle.vim
set runtimepath^=~/.vim/plugged/ctrlp.vim
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.thrift,*.proto,*.sh,*.orig
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/nerdtree'
Plugin 'dgryski/vim-godef'
call vundle#end()

"==============================================================================
" 快捷键映射
"==============================================================================
let mapleader = "," 
map <silent> <Leader>q :q<CR>                                                   " 退出当前文件
map <silent> <Leader>c :tabo<CR>:q<CR>                                          " 关闭当前所有tab 
map <silent> <Leader>e :tabnew<CR>:e ~/.vimrc<CR>                               " 打开vim配置文件
map <silent> <S-H> :tabp<CR>                                                    " 切换到前一个tab 
map <silent> <S-L> :tabn<CR>                                                    " 切换到后一个tab 
map <silent> <S-X> :tabnew<CR>                                                  " 打开新的tab 
map <silent> <S-T> :TagbarToggle<CR>						" 打开标签侧边栏
map <silent> <S-N> :NERDTreeToggle<CR>						" 打开当前工作目录

"==============================================================================
" 插件定义
"==============================================================================
let g:ctrlp_map = '<leader>s'							" 打开文件搜索输入框
let g:tagbar_ctags_bin = 'ctags'
let g:tagbar_left = 1								" tarbar展示在左边
let g:tagbar_autofocus = 1 							" 打开标签侧边栏后光标在tagbar内
let g:NERDTreeWinPos = "right"							" 目录树窗口展示在右边
let g:godef_command="/Users/bytedance/dev/bin/godef"

</details>

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bytedance/Library/Caches/go-build"
GOENV="/Users/bytedance/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/bytedance/dev/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/bytedance/dev"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/bytedance/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/bytedance/tools/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vj/cmyhtlk93bd8xhjj37zm7fzh0000gn/T/go-build198735664=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=

</pre></details>

**Comment by bhcleek** [comment]
You're using https://github.com/dgryski/vim-godef for `gd`, not vim-go.
