### ISSUE TITLE
vim.lsp.buf.definition() should work with vim-go's stack

### ISSUE THREAD

**Issue by bitwombat** [fatih/vim-go#3547]
### What did you do?

Used a key mapped to `vim.lsp.buf.definition()`
Hit `<C-t>`

### What did you expect to happen?

Expected the stack to be popped and me returned to the original file.

### What happened instead?

I stayed in the definition file. Received message: `vim-go: at bottom of the godef stack`

I understand `vim-go` key maps `<C-]>` and `<C-t>` to GoDef and StackPop, but in order to work with multiple languages, I use other keys which are mapped to vim.lsp.* function calls. I was hoping that vim-go would somehow play nice with Neovim's LSP client and stack pushing/popping would work.

#### vim-go version:
master/a494378

####  `vimrc` you used to reproduce:
<details><summary>vimrc</summary>

```vim
call plug#begin()

    Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
    Plug 'neovim/nvim-lspconfig'

call plug#end()

lua << END_OF_LUA
vim.lsp.start(
    { name = 'gopls',
      cmd = {'gopls'},
      root_dir = vim.fs.dirname(vim.fs.find({'main.go'}, { upward = true })[1]),
    }
)
local lspconfig = require('lspconfig')
lspconfig.gopls.setup {}
END_OF_LUA
```
</details>

#### Vim version (first three lines from `:version`):
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

#### Go version (`go version`):
go version go1.20.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gbell/.cache/go-build"
GOENV="/home/gbell/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gbell/.asdf/installs/golang/1.20.2/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gbell/.asdf/installs/golang/1.20.2/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/gbell/.asdf/installs/golang/1.20.2/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/gbell/.asdf/installs/golang/1.20.2/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/info/programming/my_software/listen-later/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2223096910=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
You're free to disable vim-go's definition related mappings that control the stack by leveraging `g:go_def_mapping` (see `:help g:go_def_mapping`), but I'm not aware of any way to cause another plugin's behavior affect the stack that vim-go maintains.

You could also configure the mappings to do whatever you find preferable by using a `after/ftplugin/go.vim` file.

**Comment by bitwombat** [comment]
Thanks @bhcleek. That helps.
Why does vim-go maintain its own stack, rather than use vim's built-in tag stack?

**Comment by bhcleek** [comment]
Vim-go maintains its own stack, because there didn't used to be an easy easy way to hook into Vim's tag stack. https://github.com/fatih/vim-go/issues/667 has some relevant background.

Looking into this a bit more, it appears that Vim has added some functions that may make this easier to deal with now. I'll leave this open, because I may be able to leverage `settagstack()` now. https://github.com/vim/vim/commit/f49cc60aa802862c595ff619dccc11271633a94b was added in 2018. I'll see if I can do anything with that to avoid the need for a custom stack and custom mappings.

As a further breadcrumb for myself, see `:help tagstack-examples`.

**Comment by bhcleek** [comment]
@bitwombat can you give https://github.com/fatih/vim-go/pull/3548 a try (being sure that `g:go_def_mapping_enabled` is either undefined or else set to `1`!) and see if it resolves your request?

**Comment by bitwombat** [comment]
Will do - might take another day or two for me to get to it.

**Comment by bitwombat** [comment]
Beaut, works great!
Should the mapping for <C-]> also be released back to default? I'm thinking no, because even with the change, you aren't pushing/navigating based on tags, you're just using the tag stack.

**Comment by bhcleek** [comment]
I don't see any reason to disable avoid vim-go's mapping for <C-]> when `g:go_def_mapping` is enabled regardless of whether `settagstack` is available. Does that answer your question?

**Comment by bitwombat** [comment]
Yep. Thanks for the quick response. I'll look forward to the merge.
