### ISSUE TITLE
Feature request: text objects: add a struct

### ISSUE THREAD

**Issue by vitaly-zdanevich** [fatih/vim-go#3552]

**Comment by vitaly-zdanevich** [comment]
Is it already exists?

**Comment by bhcleek** [comment]
I closed this issue, because it lacks any kind of description; the title alone is not enough to understand the feature being requested or assess whether it already exists.

**Comment by vitaly-zdanevich** [comment]
I thought that title already contains all information :(

Currently in the documentation about text objects we have only this https://github.com/fatih/vim-go/blob/2a874910a242fd4a5da021ea32fb1cde3b69f79b/doc/vim-go.txt#L1209-L1248

What about structs?

**Comment by bhcleek** [comment]
I still don't know what you're asking for. Are you asking for something similar to structs as what exists for function definitions? Would these motions be for struct value declarations or struct definitions? Ultimately, do you want this to be about structs, or do you want it be about blocks (i.e. curly braces)?

Feel free to open another issue with a clear description of what you're asking for.

**Comment by vitaly-zdanevich** [comment]
> Would these motions be for struct value declarations or struct definitions?

Yes, like `das` could remove a struct.

UPDATE: oops, tried `das` just now - it really removed a struct, it mean `delete a sentence`...
