### ISSUE TITLE
Vim hangs on saving when the package is large

### ISSUE THREAD

**Issue by typeless** [fatih/vim-go#356]
Every time I edit a file in the Go toolchain like /src/cmd/internal/gc/lex.go, it hangs for seconds on saving the file and keeps consuming 100% CPU at the same time. I can find the program 6g working hard in the background by using the 'top' command. The problem happens on both Ubuntu (I forget the version and I can't reach it right now) and MacOSX 10.10.2.

:let g:go_fmt_autosave=0 doesn't fix the problem as I expected. I would like to know what other actions would be taken on file saving.

**Comment by fatih** [comment]
Are you using any other vim plugins, such as syntastic ? They are compiling the files on every save which causes this. Otherwise `vim-go` doesn't call anything once you disable it. Other problems might be syntax highlighting  (try to disable them) and don't use `goimports` which is very slow on large GOPATH directories.

**Comment by typeless** [comment]
Yes, I do.
After removing syntastic from my .vim/bundle, the problem disappears.
Please close the issue.
Thanks alot.

**Comment by fatih** [comment]
You're welcome :)

**Comment by dpetersen** [comment]
If anyone else ends up here like I did, I had the same problem and added a shortcut for `SyntasticToggleMode` that I use on my projects with longer compile times. In "passive" mode, Syntastic will still do a basic syntax check, and anything blatantly wrong will be flagged as an error. It's fast and it's better than nothing.

**Comment by benmoss** [comment]
Also had this same problem with https://github.com/roxma/nvim-completion-manager, wasn't only on saves, it was everytime I opened files.

**Comment by bhcleek** [comment]
I suspect this may be due to gocode. Can you give https://github.com/fatih/vim-go/pull/1697 a try to see if it mitigates the hangs when opening files?
