### ISSUE TITLE
can't :GoImpl in workspace mode, unrecognized interface: xxx 

### ISSUE THREAD

**Issue by kirito41dd** [fatih/vim-go#3560]
tree:
```
go.work
/package1/go.mod
/package1/...
/package2/go.mod
/package2/...
```

`:GoImpl p xx(package1) package2.xxInterface`

unrecognized interface: package2.xxInterface

**Comment by bhcleek** [comment]
Please provide the information requested in the issue template that's used when creating a new issue.

However, assuming that you're using a relatively modern version of Go, here are some things for you to know and to check:
* Vim-go depends on github.com/josharian/impl. Does it generate the interface implementation when called directly?
* I don't know whether github.com/josharian/impl supports go.work files, but I would expect it to as long as it was compiled relatively recently. When did you last run `:GoUpdateBinaries` either with no arguments or with a single argument, `impl`? It's possible that your `impl` binary was compiled before `go.work` support was added.

**Comment by kirito41dd** [comment]
### What did you do? (required: The issue will be **closed** when not provided)

i use :GoImpl in a go.work project
### What did you expect to happen?
impl the interface
### What happened instead?
has error unrecognized interface: package2.xxInterface
### Configuration (**MUST** fill this out):
```
return {
	"fatih/vim-go",
	build = ':GoInstallBinaries' -- if you need to install/update all binaries
}

```
#### vim-go version:
```
● vim-go 2.01ms  start
        e3008d9 update CHANGELOG.md for #3538 (13 days ago)
     
```
####  `vimrc` you used to reproduce:


<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

nvim 0.9.1
#### Go version (`go version`):

GOVERSION="go1.19.1"
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>


GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/x/Library/Caches/go-build"
GOENV="/Users/x/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/x/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/x/go"
GOMOD="/Users/x/work/go.mod"
GOWORK="/Users/x/work/xxx/go.work"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.12.1
    golang.org/x/tools/gopls@v0.12.2 h1:s4mznBqCHVHeuTYjxGYJhsW3Wp4FYon8YAqiJlwlpTY=
</pre></details>

**Comment by kirito41dd** [comment]
when i run:
`➜  impl -dir package1/   'es *package1.xxx' package2.Interface
`

there are nothing output and nothing change

**Comment by bhcleek** [comment]
This all works for me. I'm able to generate the implementation using vim-go and using `impl` on the commandline.

Perhaps you need to upgrade `impl` with `:GoUpdateBinaries impl`?

**Comment by kirito41dd** [comment]
after `:GoUpdateBinaries impl`, it's ok
