### ISSUE TITLE
Failed to debug 

### ISSUE THREAD

**Issue by xD-saleem** [fatih/vim-go#3563]
### What did you do? (required: The issue will be **closed** when not provided)

Made a simple program to test debugger. This is using the latest go vim
```
package main

import "fmt"
func main() {
        hi := 5
        fmt.Println(hi)
}
```

### What did you expect to happen?

I debug my code with vim-go

### What happened instead

I get this screen rather than the code.
![bug1](https://github.com/fatih/vim-go/assets/25384958/1a6f3f74-3b13-4a94-8a28-22ee8d552c28)
![bug2](https://github.com/fatih/vim-go/assets/25384958/c0894577-c90b-42b2-83f1-e6d33c6566de)

when i type ```:messages``` i get this error.
```
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: Finished loading packages.
vim-go: could not list breakpoints
vim-go: failed to sync breakpoints (function <SNR>122_on_stdout[1]..<SNR>122_neocb[61]..<SNR>130_out_cb[9]..
<SNR>130_connect[42]..<SNR>130_sync_breakpoints[5]..<SNR>132_await[3]..<SNR>130_on_data[27]..<SNR>130_handle
RPCResult[7]..<SNR>130_handle_stack_response[12]..<SNR>130_update_windows[11]..<SNR>130_update_breakpoint[27
]..<SNR>130_sync_breakpoints, line 9): Vim(let):E716: Key not present in Dictionary: "result.Breakpoints"
vim-go: could not list breakpoints
vim-go: failed to sync breakpoints (function <SNR>122_on_stdout[1]..<SNR>122_neocb[61]..<SNR>130_out_cb[9]..
<SNR>130_connect[42]..<SNR>130_sync_breakpoints, line 9): Vim(let):E716: Key not present in Dictionary: "res
ult.Breakpoints"

```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
let g:clang_format#auto_format=1
set textwidth=0
set wrapmargin=0

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

set textwidth=0
set wrapmargin=0


let g:clang_format#auto_format=1

" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
autocmd FileType go nmap <leader>t <Plug>(go-test)

autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')




```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.9.1

#### Go version (`go version`):

go version go1.20.5 linux/amd64

#### Vim version (first three lines from `:version`):

NVIM v0.8.3

#### Go version (`go version`):

go version go1.20.1 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/slim/go/gobin"
GOCACHE="/home/slim/.cache/go-build"
GOENV="/home/slim/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/slim/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/slim/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/slim/repos/saleem/Go/testdlv/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3911441411=/tmp/go-build -gno-record-gcc-switches"

</pre></details>
#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=

</pre></details>

Also i have tried this on two linux machines and it doesnt work. fresh ubuntu installation

also i tried this on a mac and it works.

**Comment by bhcleek** [comment]
What commands are you running? Where is the cursor positioned when the commands are run?

**Comment by xD-saleem** [comment]
> What commands are you running? Where is the cursor positioned when the commands are run?

GoDebugStart

my cursor is at the main function and i typed :GoDebugStart

**Comment by bhcleek** [comment]
I'm not able to duplicate this. Can you put a breakpoint some place in your code and try again? I'm curious if you'll still see this. Another thing to try is to edit the buffer that you were in when you ran `:GoDebugStart`, set a breakpoint, and then `:GoDebugContinue`.

**Comment by xD-saleem** [comment]
I have tried this. I found the problem is it with LVIM https://www.lunarvim.org/

I deleted my lunarvim config and tried it in nvim and it worked.

**Comment by xD-saleem** [comment]
We can close this.
