### ISSUE TITLE
gocodetmpl filetype

### ISSUE THREAD

**Issue by brandonbloom** [fatih/vim-go#3565]
It would be nice to have a `gocodetmpl` filetype, analogous to gohtmltmpl for html, but for templating Go code. This filetype would have syntax highlighting for Go and text templates. Some extension such as `.go.tmpl` could trigger it.

**Comment by bhcleek** [comment]
You want the union syntax of syntax/go.vim and syntax/gotexttmpl.vim?

**Comment by brandonbloom** [comment]
Right, for using text templates to generate Go code.

**Comment by bhcleek** [comment]
I'll leave this open while I consider it.

In the meantime, you could doing this yourself locally relatively easily with something like this in `.vim/syntax/gotmpl.vim`:

```
if exists("b:current_syntax")
  finish
endif

if !exists("g:main_syntax")
  let g:main_syntax = 'gotmpl'
endif

runtime! syntax/gotexttmpl.vim
runtime! syntax/go.vim
unlet b:current_syntax

let b:current_syntax = "gotmpl"

" vim: sw=2 ts=2 et
```

and then something like this in your vimrc:
```
au BufRead,BufNewFile *.go.tt set filetype=gotmpl
```

**Comment by brandonbloom** [comment]
Thanks, I gave this a try, but it didn't quite work. Comparing to `syntax/gohtmltmpl.vim`, it looks like there are two issues:

1) Should the main syntax be `go` instead of `gotmpl`?
2) With or without the change from (1), it seems like a `syntax ... add ...` statement is needed, but it's not obvious to me how to combine the lexing rules. I experimented a bit, but without much luck.

Any suggestions?

**Comment by bhcleek** [comment]
> Should the main syntax be go instead of gotmpl?

No

> With or without the change from (1), it seems like a syntax ... add ... statement is needed, but it's not obvious to me how to combine the lexing rules.

I'm not sure what you mean. Can you clarify?

In case it helps, the `set filetype=gotmpl` in the vimrc I suggested causes Vim to load the `gotmpl.vim` syntax file from the runtimepath's `syntax` directory. The `gotmpl.vim` syntax file has two `runtime` commands in it that cause the syntaxes from go.vim and gotexttmpl.vim to be loaded.
