### ISSUE TITLE
Can't share gopls instances with coc.nvim automatically

### ISSUE THREAD

**Issue by liyiheng** [fatih/vim-go#3566]
### What did you do? (required: The issue will be **closed** when not provided)
Both vim-go and coc.nvim configured with "-remote=auto" , and open a go file

### What did you expect to happen?
vim-go and coc.nvim share gopls instances. There should be 2 forwarders and  1 daemons.
Here are documents about `forwarder` and `daemon`:https://github.com/golang/tools/blob/master/gopls/doc/daemon.md

### What happened instead?
vim-go and coc.nvim both start gopls instances. There were 2 forwarders and  2 daemons.

because gopls got different `baseName`  in 
https://github.com/golang/tools/blob/3d20bbe0fb2f6c3c3b340ce4d0bbcd1ad880071c/gopls/internal/lsp/lsprpc/autostart_posix.go#L38

vim-go: 
`/tmp/gopls-cd85fd-daemon.liyiheng`
coc.nvim:
`/tmp/nvim.liyiheng/qUMdHS/gopls-cd85fd-daemon.liyiheng`

Managing the daemon manually might fix it, but that's not friendly to me as a lazy person 

#### vim-go version:
a494378f6c106a97e39c62b493c14476f9f7de4f
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
let g:go_gopls_enabled = 1
let g:go_gopls_options = ['-remote=auto']
let g:coc_channel_timeout = 3
let g:coc_user_config = {}
let g:coc_user_config['languageserver'] = {}
let g:coc_user_config['languageserver']['golang'] = {
		\   'command': 'gopls',
		\   'args': ['-remote=auto'],
		\   'rootPatterns': ['go.mod'],
		\   'filetypes': ['go']
		\}

```
</details>

#### Vim version (first three lines from `:version`):

```plaintext
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul 08 2023 13:06:53)
Included patches: 1-1676
Compiled by Arch Linux
```
#### Go version (`go version`):

go version go1.20.6 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/liyiheng/.cache/go-build"
GOENV="/home/liyiheng/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/liyiheng/go/pkg/mod"
GOOS="linux"
GOPATH="/home/liyiheng/go"
GOROOT="/usr/lib/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1931844051=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.12.1
    golang.org/x/tools/gopls@v0.12.2 h1:s4mznBqCHVHeuTYjxGYJhsW3Wp4FYon8YAqiJlwlpTY=
</pre></details>

**Comment by bhcleek** [comment]
It's probably a pathing issue. See https://github.com/josa42/coc-go/issues/76#issuecomment-659947017

**Comment by liyiheng** [comment]
```vim
let g:go_gopls_enabled = 1
let g:go_gopls_options = ['-remote=auto']
let g:coc_user_config['languageserver']['golang'] = {
		\   'command': '/home/liyiheng/go/bin/gopls',
		\   'args': ['-remote=auto'],
		\   'rootPatterns': ['go.mod'],
		\   'filetypes': ['go']
		\}
```
ps aux |grep gopls
```plaintext
liyiheng 29183  2.9  0.3 1546520 44620 ?       Ssl  09:26   0:00 /home/liyiheng/go/bin/gopls -remote=auto
liyiheng 29217  4.1  0.4 1546776 62032 ?       Ssl  09:26   0:00 /home/liyiheng/go/bin/gopls serve -listen unix;/tmp
gopls-cd85fd-daemon.liyiheng -listen.timeout 1m0s
liyiheng 29547  2.5  0.3 1472276 44432 ?       Sl   09:26   0:00 /home/liyiheng/go/bin/gopls -remote auto
liyiheng 29641  4.3  0.4 1547032 63084 ?       Ssl  09:26   0:00 /home/liyiheng/go/bin/gopls serve -listen unix;/tmp/nvim.liyiheng/wFVN0Z/gopls-cd85fd-daemon.liyiheng -listen.timeout 1m0s
liyiheng 30287  0.0  0.0   6576  2400 pts/1    S+   09:26   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox gopls
```
> EDIT: I finally find what happens: Because coc-go use its own gopls in path coc/extensions/coc-go-data/bin/gopls, but vim-go use gopls from your ${PATH} side. The arg --remote=auto from different gopls programs can not setup a same server.

But according to the output of `ps`, the instances have same binary path `/home/liyiheng/go/bin/gopls` but different socket path:
- unix;/tmp/gopls-cd85fd-daemon.liyiheng
- unix;/tmp/nvim.liyiheng/wFVN0Z/gopls-cd85fd-daemon.liyiheng

**Comment by bhcleek** [comment]
🤔 I wonder if gopls has a race condition that allows more than one server instance to be started.

What happens if you start the gopls server manually before Vim?

**Comment by bhcleek** [comment]
Are you using coc.nvim and coc-go? https://github.com/josa42/coc-go/issues/76#issuecomment-678752724 clearly says to not use both.

**Comment by liyiheng** [comment]
> Are you using coc.nvim and coc-go? [josa42/coc-go#76 (comment)](https://github.com/josa42/coc-go/issues/76#issuecomment-678752724) clearly says to not use both.

Not using coc-go

**Comment by liyiheng** [comment]
Tried to replace gopls with  another binary that does noting expcept writes `os.TempDir()` output to a file:
```
package main
import  "os"
func main() {
    dir := os.TempDir()
    os.WriteFile("/tmp/tmp_path_from_vim.txt", []byte(dir), os.ModePerm)
}
```
The process started by vim-go outputs `/tmp`,
and the other one outputs `/tmp/nvim.liyiheng/XXX`, similar to vim's `tempname()` output.

**Comment by liyiheng** [comment]
> 🤔 I wonder if gopls has a race condition that allows more than one server instance to be started.
> 
> What happens if you start the gopls server manually before Vim?

It seems gopls only checks the socket file `{temp_dir}/gopls-{project_path_hash}-daemon.{username}`

 `gopls -remote=auto`, there were 2 gopls processes: a forwarder and a daemon.
 Then opened a go file with vim, there were 5 gopls processes: 3 forwarders and 2 daemons. 

forwarders: 1 started manually, 1 started by vim-go and 1 started by coc.nvim
daemons: 1 started manually, 1 started by coc.nvim

vim-go shared daemon instance with the manually started gopls, because they use the same `/tmp/`, but coc.nvim doesn't

**Comment by bhcleek** [comment]
https://github.com/golang/go/issues/41266 and https://groups.google.com/g/golang-tools/c/y3OQNIudLzQ seem relevant. 

This doesn't look like a vim-go problem per se.

**Comment by bhcleek** [comment]
In case it's not clear in those links I posted in my previous message, try setting and exporting `XDG_RUNTIME_DIR` before starting Vim. If that works, then exporting `XDG_RUNTIME_DIR` in your profile should solve the problem for you going forward.
