### ISSUE TITLE
go_debug_mappings not set properly

### ISSUE THREAD

**Issue by jmastr** [fatih/vim-go#3568]
### What did you do? (required: The issue will be **closed** when not provided)
Set `go_debug_mappings` to:
```
g:go_debug_mappings = {'(go-debug-step)': {'key': 's'}, '(go-debug-next)': {'key': 'n'}, '(go-debug-continue)': {'key': 'c'}, '(go-debug-breakpoint)': {'key': 'b'}}
```

### What did you expect to happen?
- That all mappings are set properly
- That I find all mappings under `:map`

### What happened instead?
I only see:
```
n  b            @<Plug>(go-debug-breakpoint)
n  c            @<Plug>(go-debug-continue)
```
under `:map`, so `go-debug-step` and `go-debug-next` are missing.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 01 1980 00:00:00)
Included patches: 1-1441
Compiled by nixbld

#### Go version (`go version`):

go version go1.20.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/julian/.cache/go-build"
GOENV="/home/julian/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/julian/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/julian/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/fp9k417pvah7d6ibbnz2x2llzframbk4-go-1.20.6/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/fp9k417pvah7d6ibbnz2x2llzframbk4-go-1.20.6/share/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/julian/dev/planetmint/planetmint-go/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3889787277=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@(devel)

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_debug_mappings = {'(go-debug-step)': {'key': 's'}, '(go-debug-next)': {'key': 'n'}, '(go-debug-continue)': {'key': 'c'}, '(go-debug-breakpoint)': {'key': 'b'}}
g:go_debug_windows = {'vars': 'leftabove 51vnew', 'stack': 'leftabove 21new'}
g:go_metalinter_autosave = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by jmastr** [comment]
@bhcleek Thanks for your answer. I did `:GoDebugStart` and `:GoDebugContinue`, call `:map` and get:
```
n  b            @<Plug>(go-debug-breakpoint)
n  c            @<Plug>(go-debug-continue)
```
Do I need to do more than the commands above?

**Comment by jmastr** [comment]
@bhcleek Any idea how I can debug this issue?

**Comment by bhcleek** [comment]
Thank you @jmastr. I can duplicate this and will try to have it fixed in the next week or so.

Thank you for reporting it. You can continue to watch this issue to see when it's closed with the fix. I'll let you know if I need any more info before then.

**Comment by jmastr** [comment]
Thank you very much!
