### ISSUE TITLE
How do I use vim-go  with lazy.nvim

### ISSUE THREAD

**Issue by Mega31** [fatih/vim-go#3569]
I am trying to setup vim-go in my astovim setup and it uses lazy.nvim

i can't seem to find any guide related to it. Please do support lazy.nvim as it makes things very easy

**Comment by bhcleek** [comment]
Vim-go is a standard Vim plugin and shouldn't need to do anything special to be used by lazy.nvim. From the lazy.nvim docs, it looks like it should be fairly straightforward for you to use vim-go via lazy.nvim. I'd suggest following their guide, but I don't plan to add a guide specific to lazy.nvim to Vim-go's documentation.
