### ISSUE TITLE
Highlight parameters and not functions

### ISSUE THREAD

**Issue by josebalius** [fatih/vim-go#3572]
Is there anyway to highlight function parameters but not functions?

Based on what I see in: https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L337 - I assume the answer is no. I am wondering if this has been previously requested and/or if there's an alternative to achieve the same thing that I am missing?

**Comment by bhcleek** [comment]
I'm not certain, because I've never tried it, but I _think_ that because of https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L357, adding `highlight link goFunction NONE` to your vimrc may do what you're asking for.
