### ISSUE TITLE
Saving files using CGO blocks.

### ISSUE THREAD

**Issue by oblitum** [fatih/vim-go#358]
I have one Go file that needs to include a C header file. At the root of the package there's a C++ file (implementation of the header) to be compiled with the Go file. This file needs boost, etc so, at the CGO configuration before the `import "C"`, I'm also setting appropriate `LDFLAGS` to link to such libraries. It's expected that the compilation of this to take 4~5 seconds, but outside of the editor. When I try to just save the file with `:w` it blocks for an amount of time that seems equal to the compilation time needed to build the package.

If it's not considered a plugin issue, is there some option to disable this (of course, not talking about not loading the plugin in the first place)?

**Comment by fatih** [comment]
There is no auto command that builds your code in vim-go. `:w` does only invoke `gofmt`, which formats your Go code and it's instantaneously (unless you use `goimports`, which is slow on large repos). Are you using https://github.com/scrooloose/syntastic or something similar?

**Comment by oblitum** [comment]
@fatih ah, I'm sorry, it's syntastic fault and I didn't check it first. Do you have experience with it? What do you suggest, I'm getting use to Go development now so I don't have much experience, I do use vim-go for quite some time (formelly mostly sporadic usage), do you think it's more than enough and syntastic turns up unecessary? What command would you use in place? `:GoLint`...?

**Comment by fatih** [comment]
I'm not using it. It makes development slow. I'm invoking `:GoBuild` manually. It builds my source code (only if I want) and shows errors which I can jump to it. It also doesn't create any binary and pollute your working directory. GoLint is also good to catch problems for your app that is compiling without any problems. (Also :GoVet).

**Comment by oblitum** [comment]
Ok thanks.

**Comment by fatih** [comment]
You're welcome :)
