### ISSUE TITLE
text/template support in gopls integration?

### ISSUE THREAD

**Issue by tmc** [fatih/vim-go#3582]
Does vim-go integrate with gopls's text/template + html/template support?

How can I set templateExtensions ?

https://github.com/golang/tools/blob/627959a8e32af98dce9ff3e65ef6f491d3dcb9f6/gopls/doc/settings.md?plain=1#L80

**Comment by bhcleek** [comment]
Yes, all gopls settings that are do not have an explicit option in vim-go can be handled with `g:go_gopls_settings`. See `:help g:go_gopls_settings`: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1966-L1977
