### ISSUE TITLE
`g:go_metalinter_autosave_enabled` option can be set to not use any linter

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#3589]
I only want to run :GoBuild when save file `:w`

<img width="751" alt="image" src="https://github.com/fatih/vim-go/assets/93968/33e94621-4a1d-453d-a877-3367d0aaf7b9">

**Comment by bhcleek** [comment]
Vim-go does not have an option to build on save. It's not too difficult to set such a thing up if you want it, though, by leveraging autocommands.

But I want to be clear on what you're asking for. Are you asking for a new feature, asking for help to know how to build on save with vim-go, asking how to keep other things from running when saving, or something else entirely?

**Comment by bhcleek** [comment]
I see the title changed from what it was originally. Are you saying that you're not seeing the metalinter run when saving or are you concerned that saving does not build when `g:go_metalinter_autosave` is enabled?

**Comment by bhcleek** [comment]
Closing for lack of feedback.

**Comment by jinleileiking** [comment]
> I see the title changed from what it was originally. Are you saying that you're not seeing the metalinter run when saving or are you concerned that saving does not build when `g:go_metalinter_autosave` is enabled?

I just enable autosave of `errcheck`. 

the steps of vim is:

1. :w 
2. call metalinter_autosave cmd `errcheck`
3. call :GoBuild

What I want is do not call any checker like errcheck.

I you give it an "". I will enable the default linters.

**Comment by jinleileiking** [comment]
@bhcleek

**Comment by jinleileiking** [comment]
> I think what you want is to not call the metalinter when you run :GoBuild. Is that right?

I want not call the metalinter when I run `:w` (save file to disk)

my linters are controlled by `ale`

**Comment by bhcleek** [comment]
If you don't want to call the metalinter when saving a file, then disable by leveraging `g:go_metalinter_autosave`. You can either remove `let g:go_metalinter_autosave = 1` from your vimrc or change it to `let g:go_metalinter_autosave = 0`

**Comment by jinleileiking** [comment]
Afaik, if ` let g:go_metalinter_autosave = 1 `,  when `:w` vim-go will call metalinter and then call `:GoBuild`.

I just want: when `:w` vim-go only call `:GoBuild`

**Comment by bhcleek** [comment]
`g:go_metalinter_autosave` does not cause a build. Builds do not happen on save automatically. But if that's something you want, you can create your own `autocmd` to do it.

**Comment by bhcleek** [comment]
To prevent the metalinter from executing when writing the file, use `let g:go_metalinter_autosave = 0`.
