### ISSUE TITLE
Lua module not found for config of vim-go. Please use a `config()` function instead

### ISSUE THREAD

**Issue by stephane-archer** [fatih/vim-go#3597]
I have the following error when starting Neovim
```
Error detected while processing ~/.config/nvim/init.lua:
Lua module not found for config of vim-go. Please use a `config()` function instead
```

**Comment by bhcleek** [comment]
Vim-go does not provide a lua module for configuring vim-go, and I'm not an expert in configuring Neovim with Lua. A quick search suggests that the error you're seeing can be resolved in your Neovim configuration.
