### ISSUE TITLE
gofmt spaces

### ISSUE THREAD

**Issue by jvillasante** [fatih/vim-go#360]
Is there a way to run gofmt with spaces instead of tabs?

**Comment by fatih** [comment]
No, there is no option because `gofmt` is designed to use tabs. We have the option  `let g:go_fmt_options = ''` to pass options to fmt if you wish, however there is no option to change the behavior you want:

```sh
usage: gofmt [flags] [path ...]
  -cpuprofile="": write cpu profile to this file
  -d=false: display diffs instead of rewriting files
  -e=false: report all errors (not just the first 10 on different lines)
  -l=false: list files whose formatting differs from gofmt's
  -r="": rewrite rule (e.g., 'a[b:len(a)] -> a[b:]')
  -s=false: simplify code
  -w=false: write result to (source) file instead of stdout
```

**Comment by rajasharan** [comment]
@jvillasante @fatih 
Is there a way to run `:retab` command after gofmt is done by adding something to my .vimrc? 

That will resolve the issue (because I already have all my tab settings in place - just need to find a way to automatically run `:retab`)

**Comment by fatih** [comment]
@rajasharan no. This is a fundamental decision. Gofmt uses tabs so I don't want to change the way it's doing. You're free to modify the code yourself.

**Comment by rajasharan** [comment]
@fatih sorry I meant to ask is there a vim trick that I can add to my .vimrc file to make this happen 
(i am not too good with vim)

**Comment by mmlb** [comment]
@rajasharan you'd be going against the huge majority of go code out in the world. gofmt was created specifically so all go code looks essentially the same, and you'd be removing one of go's best features. Not to mention any time you ask for help with any code the first comment is likely to be "run gofmt" (as it should be IMO,  check out the reddit.com/r/golang for some examples)
