### ISSUE TITLE
Using code completion breaks navigation for arguments placeholders

### ISSUE THREAD

**Issue by dunric** [fatih/vim-go#3601]
### What did you expect to happen?

Using omni-completion should not affect calculation of function arguments placeholders position.

#### demonstrating example

 - insertion of `string.Contains` function with autofilled placeholders
![image](https://github.com/fatih/vim-go/assets/1522770/a6ccb73f-8d5e-462e-a6e9-fce45dc21ec8)

 - manual typing-in of function arguments keeps navigation between placeholders intact, ie. you can still go forth & back with `Ctrl-j` and `Ctrl-k` (default keybindings)
![image](https://github.com/fatih/vim-go/assets/1522770/28600ddb-f8b5-4aaa-baa6-2c670a36a781)
![image](https://github.com/fatih/vim-go/assets/1522770/4c1b4497-4d9d-41e3-9506-7135ad852890)

### What happened instead?

Invoking omni completion menu and selection of an entry did broke navigation & selection between placeholders.

 - use code completion instead of manual typing for the first function's argument
![image](https://github.com/fatih/vim-go/assets/1522770/2649276d-85fc-4a76-956a-7af8d0d5dca3)

 - after selection of the first entry (`message` string variable) with `Ctrl-y` (default) placeholders got miscalculated and navigation stops working (see invalid placeholder highlight for the first argument)
![image](https://github.com/fatih/vim-go/assets/1522770/3e778564-fa47-40db-8173-8e155a2c5b5f)

#### vim-go version:

current

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
let g:go_gopls_use_placeholders = v:true
let g:go_snippet_engine = 'ultisnips'
```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 26 2023 20:39:23)

#### Go version (`go version`):

go version go1.21.4 linux/amd64

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls (devel)
    golang.org/x/tools/gopls@(devel)
</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_get_update = 0
g:go_doc_balloon = 0
g:go_doc_url = 'http://localhost:6060'
g:go_updatetime = 800
g:go_diagnostics_level = 1
g:go_term_enabled = 1
g:go_fold_enable = ['block', 'varconst', 'import']
g:go_metalinter_command = 'staticcheck'
g:go_doc_keywordprg_enabled = 1
g:go_doc_popup_window = 0
g:go_auto_sameids = 1
g:go_template_file = '/home/dunric/.vim/templates/skeleton.go'
g:go_metalinter_autosave = 1
g:go_gopls_use_placeholders = v:true
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_term_mode = 'vertical botright split'
g:go_fillstruct_mode = 'gopls'
g:go_template_test_file = '/home/dunric/.vim/templates/skeleton_test.go'
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment]
Ctrl-j works to navigate in the scenario you're describing, not ctrl-y.

**Comment by dunric** [comment]
> Ctrl-j works to navigate in the scenario you're describing, not ctrl-y.

ctrl-y is used to select an entry from a pop-up completion menu. ctrl-j / ctrl-k no longer work, placeholder is misplaced (see the last image).

**Comment by dunric** [comment]
I may have misunderstood your reply. Are you suggesting choosing an entry from menu during "snippet mode" has to be done with ctrl-j ? In other words standard [popupmenu-keys](https://vimhelp.org/insert.txt.html#popupmenu-keys) are altered and ctrl-y should not be used (has an undefined behavior)?

**Comment by bhcleek** [comment]
I misread your description. I thought you were trying to use ctrl-y to navigate after manually entering the first argument.

However, I'm unable to duplicate the problem you're describing.

I noticed that your `gopls` is not an official version. Can you update it with `:GoUpdateBinaries gopls`?

Also, what version of vim-go are you using? Your bug report says you're using the current version. Does that mean the latest master revision, the latest tagged release, or something else?

**Comment by bhcleek** [comment]
I can duplicate what you're describing. I'm not sure what the solution is, though 🤔

**Comment by bhcleek** [comment]
I think I can fix this in the simple case where the completion text does not contain any placeholders, but it will remain for a case where a completion selection is made that contains placeholders, because Ultisnips does not support nested snippets.
