### ISSUE TITLE
[features] GoDoc window enhancements

### ISSUE THREAD

**Issue by akavel** [fatih/vim-go#361]
I'd really love if the GoDoc window was more full-featured, so that it could fully replace my need to constantly switch to http://golang.org/pkg and/or http://godoc.org, at least for all the packages I've already downloaded. For this, I tried to list below the particular features I imagine I'd like to see (order is random).

To make it clear, I don't want this to mean anything like *"you must do it for me and now!!1!11"*, but I wanted a place where I could put down what's itching me, for full reference and so that it wouldn't be lost. And so that you, or whoever else would have a chance to consider this for implementation. Specifically, myself included; I hope I might find some time to try and issue some pull requests for completing this shopping list.

  * [ ] Show the **examples, folded** by default (don't know how to do this technically, but for reference, I think e.g. TagBar can do a similar feat?)
  * [x] <del>ctags/godef-like navigation (via **<kbd>Ctrl-]</kbd> and/or <kbd>gd</kbd>) for types** (i.e. arg. types & return types for funcs, field types for structs, types for variables/consts; in case of composite types, for all the "subtypes", e.g. `map[Foo]Bar` -> link on `Foo` and `Bar`)</del> *Done via go-explorer, see below.*
  * [x] <del>Go to **source (via <kbd>Ctrl-]</kbd> and/or <kbd>gd</kbd>)**</del> *Done via go-explorer, see below.*
  * [x] <del>**Folding** and unfolding of the whole file (I'd love it if folded file would result in **an overview** like in `godoc -http`)</del> *Done via go-explorer, see below.*
  * [x] <del>Next/prev function/entry via **<kbd>]]</kbd>/<kbd>[[</kbd>**</del> *Easily stepped around via folding/unfolding in go-explorer.*
  * [ ] Packages **tree browser**, like e.g. at http://golang.org/pkg

**NOTE:** crossed-out points above are implemented by a separate plugin: https://github.com/garyburd/go-explorer

**Comment by fatih** [comment]
Hi @akavel. Thanks for creating the list. It's really cool. I'm totally aware that the current GoDoc implementation is subpar and it needs some love and improvement. @garyburd did approach me with a project that was created initially as a documentation viewer for Vim. Here are the necessary repos:

https://github.com/garyburd/gv
https://github.com/garyburd/gvt

I think if he is ok with it and it works well we can include it to vim-go. It would be a very valuable addition to vim-go.

**Comment by akavel** [comment]
Both gv and gvt seem to be totally underdocumented (more like undocumented), so I'm not really sure what's there. But given that he's the original author of godoc.org, he probably knows what he's doing, and I suppose he told you more details. That said, it'd be sure awesome if this code improves the state of things. Me, I was loosely thinking about converting godoc html output -> markdown, and then having that parsed by Vim... I know, kinda weird approach. But I looked into the godoc sources, and they're not that small, and although there's some support for templating the output, especially the link discovery etc. is done specifically for HTML-only. I thought basing on the HTML output is less work than copying the code to emit something else, and then constantly maintaining it. On the other hand, now that I think of it, maybe a contribution to godoc could be made to generalize it. Though, it's not sure if the Go core team would want to accept it.

**Comment by garyburd** [comment]
The gvt program is a work in progress. I will work on documentation soon.

My approach is to directly generate documentation in a format that's convenient to use from Vim script.  The [code](https://github.com/garyburd/gvt/blob/master/doc.go) is mostly complete.

**Comment by akavel** [comment]
If it improves the state of things, whatever way, that's sure gonna be awesome.

**Comment by akavel** [comment]
To update on this: so, the answer now is mostly "use the awesome https://github.com/garyburd/go-explorer plugin". It solves nearly all the points I listed, except the first and the last. Actually, the last one is partially solved too, via tab-completion after typing `:GeDoc ` (I say "partially" mostly because it misses the high-level one sentence package description docs).

That said, I'm not sure whether @garyburd is OK to advertise his plugin already? was it announced on golang-nuts? or does he prefer to keep it low profile yet? that said, I couldn't bear any more not mentioning it at least here... I'm using go-explorer on a regular basis now and can't imagine living without it anymore, so, methinks it's ready enough for use by the good people of Golangdom... Big, big thanks @garyburd (again)!

**Comment by fatih** [comment]
I would welcome the integration of this plugin into vim-go. I know that it could be live outside, but I've created vim-go just for this reason, to not have install many other independent tools just to have a proper Go development environment in Vim.  

Having integrated would made it let people use it with the new vim-go version and we could integrate the binary installation of go-explorer into `:GoInstallBinaries`. I could add @garyburd as a contributor to vim-go, so it wouldn't slow down development and we could merge changes back easily. Let me know if you think of this option. 

The second option would be to add and advertise `go-explorer` within vim-go's Readme (for example in the install section: https://github.com/fatih/vim-go#optional.) I'm ok with adding it.

**Comment by garyburd** [comment]
Because I do not use the vim-go plugin, I do not want to merge go-explorer with vim-go or contribute to vim-go.  Feel free to advertise go-explorer in the readme.

**Comment by fatih** [comment]
Fair enough. I'll close this issue then. I've added it to the Readme.

**Comment by garyburd** [comment]
Please feel free to merge a fork of go-explorer into vim-go. 

The go-explorer code has been stable and I do not plan to enhance the tool.

**Comment by fatih** [comment]
Thanks @garyburd. I'm more than happy to look at it. I'm reopening this issue so I don't forget it. I also need to check the source code for any existing duplicate reuse and rearrange it. I'll ping you when I have a ready PR waiting to merge. Thanks for work on go-explorer.

**Comment by garyburd** [comment]
I created a Neovim remote plugin host for Go and I am moving on to writing plugins in Go.  I plan to create a doc viewer next. You may want to integrate with that plugin when it's done instead of go-explorer.

**Comment by fatih** [comment]
I'm closing this as I don't have any time to integrate this. I'm more than happy if someon want's to tackle it. Thanks.
