### ISSUE TITLE
vim.go: $GOPATH is not set 

### ISSUE THREAD

**Issue by Leviathans** [fatih/vim-go#362]
OS:MAC OS 10.10
SHELL:ZSH
GOLANG:1.4
$GOROOT:/usr/local/go
$GOPATH:$HOME/go
what's the problem?thank u

**Comment by fatih** [comment]
I think you didn't set your Mac's environment variables. Be sure you added to all existing environment variable sources

```
.bashrc
.bash_profile
.zshrc
```

**Comment by fatih** [comment]
This is a Mac environment variable, not much I can do here. Thanks for reporting though.
