### ISSUE TITLE
Vim randomly stops when go_highlight_function_calls is on

### ISSUE THREAD

**Issue by adirizka7** [fatih/vim-go#3640]
### What did you do? (required: The issue will be **closed** when not provided)

My vim would randomly stops and I had to kill the process when opening certain files with go_highlight_function_calls enabled. If it doesn't stop, vim also becomes extremely laggy.

### What did you expect to happen?

Vim should not stop and should not be laggy when go_highlight_function_calls is enabled.

### What happened instead?

Vim randomly stops and becomes laggy.

### Configuration (**MUST** fill this out):
let g:go_def_mode='gopls'
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1
let g:go_fmt_command = "goimports"

#### vim-go version:
v1.28
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 20 2023 18:58:31)
macOS version - arm64
Included patches: 1-2136

#### Go version (`go version`):

go version go1.21.6 darwin/arm64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.14.2
    golang.org/x/tools/gopls@v0.14.2 h1:sIw6vjZiuQ9S7s0auUUkHlWgsCkKZFWDHmrge8LYsnc=

</pre></details>

**Comment by bhcleek** [comment]
What does `set re?` output?

**Comment by adirizka7** [comment]
> What does `set re?` output?

The output is `regexpengine=1`

**Comment by bhcleek** [comment]
Try changing it to 0 or 2. I use 0, but sometimes it has to be forced to use the new engine by setting it to 2.

**Comment by adirizka7** [comment]
Works like a charm! Thanks!
