### ISSUE TITLE
Syntax highlighting slows down 'gofmt' filtering(which is triggered on file saving)

### ISSUE THREAD

**Issue by typeless** [fatih/vim-go#365]
One can reproduce the problem by either `:%!gofmt` or `:%!cat` when editing a bigger file(ex: /src/cmd/internal/gc/subr.go of the Go toolchain). It takes 57 secs(measured with vim's profiler) to finish the saving command in my development server. The problem isn't present under `syntax off`.

It appears to be not a Go or vim-go specific problem though as the problem can be reproduced in C files too.

I for now use a quick workaround: enclosing `syntax off` and `syntax on` around the line `silent execute "%!" . command` in vim-go/autoload/go/fmt.vim

**Comment by fatih** [comment]
You are right, but this is mainly due Vim's poor performance. For example I have the followings in my Vimrc:

```
" speed up syntax highlighting
syntax sync minlines=256
set nocursorcolumn
set nocursorline
set synmaxcol=300
set re=1
```

Does these settings change anything for you? I don't know what to do right now, as this is more vim specific than vim-go. I've already disabled some of the expensive syntax highlighting functions long time ago https://github.com/fatih/vim-go/commit/5e79cec920ede209842b43797168247212ef1189

I'm closing this right now, but please to reopen it if you feel (and argument) it's should be stayed opened.
