### ISSUE TITLE
GoFillStruct with proto pb.go

### ISSUE THREAD

**Issue by onns** [fatih/vim-go#3655]
### What did you expect to happen?

can `GoFillStruct` ignore unknown fields of grpc proto pb file?

```go
type CollectionBase struct {
	BizType int64 `protobuf:"varint,1,opt,name=biz_type,proto3" json:"biz_type" form:"biz_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

maybe struct like this, run `GoFillStruct` will add XXX... to the code, Which is no use for coding.

I use `gopls`:

```lua
vim.g.go_fillstruct_mode = "gopls"
```

**Comment by bhcleek** [comment]
Ultimately, vim-go delegates the changes to fill the struct to `gopls` or `fillstruct`. While these fields are annoying in protobufs, they may exist in other structures for reasons that may be useful to clients.

Also, `protoc-gen-go` was updated a four years ago to no longer generated these fields.

refs:
* https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0
* https://youtrack.jetbrains.com/issue/GO-13475/Fill-struct-intention-should-ignore-autogenerated-protocol-buffer-fields
* https://youtrack.jetbrains.com/issue/GO-6397/Option-to-ignore-some-fields-on-fill-struct
* https://stackoverflow.com/questions/50704319/xxx-type-in-generated-pb-go-file
