### ISSUE TITLE
Syntax highlighting doesn't know about some operators

### ISSUE THREAD

**Issue by cespare** [fatih/vim-go#366]
vim-go recognizes these as operators:

```
+ - * / % += -= == < > != <= >= :=
```

It does not recognize these as operators:

```
& | ^ << >> &^ *= /= %= &^= && || <- ++ -- = ! ...
```

And these two, it recognizes the last two characters as being an operator separate from the first character, which is incorrect because the whole thing is a single operator:

```
<<= >>=
```

I tried fixing this in my fork a while ago:

https://github.com/cespare/vim-go/commit/beaf6eef87d56b8356a921bc1550273714a39c17

My change is too broad, though, and causes too many false positive matches. (For instance today it broke a big `/* */` comment block.)

I'll try giving it another shot at some point but I wanted to note it in the issue tracker in case someone else is motivated to tackle it sooner :)

**Comment by cespare** [comment]
Also if you write

``` go
a*b + c*d
```

(note that this is how gofmt will manage the spaces) then the `*` will not be recognized as operators.

**Comment by cespare** [comment]
Trying again with https://github.com/cespare/vim-go/commit/8e1e1bd99fcaf6b21531b993c29280fb4743e914. If it looks OK after a while I'll send over a PR.

**Comment by fatih** [comment]
Hi @cespare 

Thanks for opening this issue. I think the best way to not lose your changes is to open a PR and letting it sit it here. At least we can see each iteration and your improvements (or other people's). Also a PR is more visible for other others, so they can dive easier.

If not, I can open the PR from your branch myself, but it would be better if it's from you :)

**Comment by cespare** [comment]
Done, see #372.
