### ISSUE TITLE
Customize the background color of the compiler errors

### ISSUE THREAD

**Issue by bjt-user** [fatih/vim-go#3684]
Hi,

is it possible to configure the colors of the compiler errors that appear in the status line?

By default it is white font on yellow/sand background color.\
It is very hard to read.\
For me white on black background would be just fine.

I am using the latest commit from the `master` branch right now.\
(f365d961)

**Comment by bhcleek** [comment]
Highlighting can be customized as discussed in https://github.com/fatih/vim-go/issues/2829#issuecomment-614331995.

But I'm not sure which errors you're referring to in this case. Can you provide a screenshot to demonstrate?

**Comment by bjt-user** [comment]
These are the compiler errors that I am referring to:
![vim-go_compiler_error](https://github.com/user-attachments/assets/b023bec9-162a-4e21-9b26-e1b3769907cd)

I still haven't found the spot where I can adjust these colors.

**Comment by bhcleek** [comment]
That's the quickfix window. The color of the errors there is not configured by vim; it'll probably part of your chosen colorscheme.

**Comment by bjt-user** [comment]
Thank you @bhcleek for the hint.

I have now put this
```
highlight QuickFixLine ctermbg=none
```
into my `~/.vim/after/syntax/go.vim` and now I have white on black.
