### ISSUE TITLE
using custom tools to adjust imports

### ISSUE THREAD

**Issue by alcortesm** [fatih/vim-go#3692]
### What did you do? (required: The issue will be **closed** when not provided)

I tried running a custom tool to adjust imports, this is, a tool different than `gopls` or `goimports`.

I configured `g:go_imports_mode` to run my custom tool `foo`:
```
let g:go_imports_mode = 'foo'
```

Then I opened a Go file and ran `:GoImports`.

### What did you expect to happen?

I expected vim to call the tool `foo` and pass it the path of the file to be adjusted as an argument.

The tool `foo` is a placeholder, in reality, the tool foo will be a script that runs goimports then [cgi](https://github.com/daixiang0/gci), but I don't think that is relevant to this issue.

### What happened instead?

Vim called the gopls tool to adjust the imports.

This behavour is somewhat consistent with the documentation of 'g:go_imports_mode' which says:

```
Valid options are `goimports` and `gopls`. [...]. By default `gopls` is used.
```

So maybe this is not an issue but a feature request :).

#### vim-go version:

commit ec7a59ef10d417c0cc1cd571a165c7c9dec30d27, which is the current master at the time of writing.

####  `vimrc` you used to reproduce:

```
; cat ~/.vim/vimrc
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()


; cat ~/.vim/after/ftplugin/go.vim
let g:go_imports_mode = 'foo'
```

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44)
Included patches: 1-1378, 1499
Modified by team+vim@tracker.debian.org
```

#### Go version (`go version`):

```
; go version
go version go1.23.2 linux/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

```
; go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/alcortes/.cache/go-build'
GOENV='/home/alcortes/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/alcortes/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/alcortes/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/alcortes/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.linux-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/alcortes/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.linux-amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/alcortes/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1625970927=/tmp/go-build -gno-record-gcc-switches'
```
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

; gopls version
golang.org/x/tools/gopls v0.16.2
</pre></details>

**Comment by bhcleek** [comment]
It would be difficult for vim-go to support arbitrary tools, and we are unlikely to extend it to do so. However, if you ensure that your tool conforms to the `goimports` options and behaviors, you can alias your tool as `goimports` and get the functionality you're looking for.

**Comment by alcortesm** [comment]
thanks @bhcleek!
