### ISSUE TITLE
fyi: gorename seems not available anymore

### ISSUE THREAD

**Issue by Shane-XB-Qian** [fatih/vim-go#3696]
fyi: gorename seems not available anymore
go: golang.org/x/tools/cmd/gorename@master: module golang.org/x/tools@master found (v0.28.1-0.20241224141015-732f823c7c0a), but does not contain package golang.org/x/tools/cmd/gorename

**Comment by bhcleek** [comment]
Thank you. I'll remove it from the set of tools that gets automatically installed. I'll likely leave support in the code base to use it for now, but that will probably be removed eventually, too.
