### ISSUE TITLE
Everything not work

### ISSUE THREAD

**Issue by txthinking** [fatih/vim-go#374]
I use vundle and follow the INSTALL in README
install :PluginInstall :PluginUpdate :GoInstallBinaries :GoUpdateBinaries, all is ok.
My $PATH inlcude $GOPATH/bin, sure that all binaries in there.

But when i run ALL :Go* command in vim, Not an editor command.
and the open *.go file, no color, no anynothing just like a common text plain file

**Comment by txthinking** [comment]
my vimrc file: http://ix.io/hkG

juest type go
```
hostname ~ $ go [ type go and press TAB]
go         gocode     godef      godoc      gofmt      goimports  gold       golint     gorename   gotags     gox
```

**Comment by fatih** [comment]
Can you put the vundle on the top please. Also this is an installation problem, I really don't know what to say. Can you ask this to IRC channel #vim or vim mail list please? Thanks
