### ISSUE TITLE
Test and check Neovim compatibility 

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#375]
The recent Neovim changes are quite exciting. I've heard that vim-go works very well with Neovim. However we can make use of the new and updated async design of Neovim and leverage all long running commands to it.

**Comment by acasajus** [comment]
:+1:

**Comment by casimir** [comment]
@fatih Since you just "heard", I can confirm you it works quite well. I use this setup on a daily basis.

**Comment by shazow** [comment]
Can also confirm that vim-go works perfectly fine with Neovim.

[Neomake](https://github.com/benekastah/neomake) might be a good reference to look at, it's a build plugin that takes advantage of Neovim's async job control stuff (and still backwards compatible synchronously).

**Comment by abecciu** [comment]
:+1:

**Comment by varun06** [comment]
I am also using vim-go with neovim from some time without any issue.
:+1:

**Comment by fatih** [comment]
Closing this as it really looks good. If we want to add or support additional features, we can always open specific issues for those. Thanks all for the replies, much appreciated.
