### ISSUE TITLE
Autocompletion does not work with the code I wrote

### ISSUE THREAD

**Issue by derekchiang** [fatih/vim-go#378]
I'm developing a Go package, and for some reason autocompletion only works for the code originally in the package, but the code I added (structs, functions, etc.) does not show up in autocompletion.  It's worth noting that GoLint works, meanwhile.

Any idea why?

**Comment by fatih** [comment]
Hi Dere,

Please `go install` any necessary package to get a completion for that package. It's needs to be compiled and accessible to `gocode` server over the `pkg/` folder. If this doesn't help please open a test case with your code to gocode repo: https://github.com/nsf/gocode as gocode is responsible for the completion.

**Comment by derekchiang** [comment]
Ah, that worked.  Thanks!

**Comment by fatih** [comment]
You're welcome :)
