### ISSUE TITLE
add highlighting support for struct parameters parameters

### ISSUE THREAD

**Issue by jseaidou** [fatih/vim-go#379]
vim-go doesn't seem to recognize structs and highlight them in function definitions

![screen shot 2015-04-09 at 2 51 09 pm](https://cloud.githubusercontent.com/assets/1851365/7077712/f5f45eca-dec7-11e4-8d0e-0c2765d59153.png)

**Comment by fatih** [comment]
That's ok. It only highlights builtin types, not custom types. Please open a PR if you think it's should be included with a guard. Thanks for bringing this up.
