### ISSUE TITLE
Missing syntax highlighting for html/template files.

### ISSUE THREAD

**Issue by variadico** [fatih/vim-go#380]
Could it be as easy as bringing these files into this plugin?

https://github.com/cespare/vim-go-templates/tree/master/syntax

I could probably submit a pull request, if that would help.

**Comment by fatih** [comment]
Sounds good. But please get permission from @cespare first. I'm ok with it :+1:

**Comment by cespare** [comment]
Fine with me. I'd love to have one fewer plugin. Thanks @pi241a.

Once this is done I'll update the readme over there to point at vim-go.

**Comment by fatih** [comment]
Thanks @cespare :+1: @pi241a mind opening a PR for it ?

**Comment by fatih** [comment]
This is merged to master now. Thanks for all participates.
