### ISSUE TITLE
Better :GoCoverage support

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#384]
Instead of opening a HTML page via the system default browser, open a Vim scratch buffer and show an annotated view of the buffer. Here is an example script:

https://gist.github.com/guelfey/6253836

And here is a plugin that does it fairly well:

https://github.com/t-yuki/vim-go-coverlay

**Comment by oryband** [comment]
:+1:

**Comment by fatih** [comment]
Closing this in favor of https://github.com/t-yuki/vim-go-coverlay. We could merge this into vim-go if @t-yuki agrees, but it doesn't need to :)

**Comment by oryband** [comment]
wow, this tool is amazing. major productivity boost
![](http://theartmad.com/wp-content/uploads/2015/06/Amazing-Funny-Photos-11.jpg)

**Comment by t-yuki** [comment]
It's welcome to merge coverlay into vim-go.
However I think the quality of code is low: its implementation is a bit tricky and not good code with not-tested well even if it works as a plugin of vim-go.
So I'm afraid to make PR currently. Fork or patches are also welcome!

**Comment by oryband** [comment]
@avivl
