### ISSUE TITLE
setting let g:go_def_mapping_enabled = 0 doesn't disable gd command

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#386]
```vim
" Set this in my .vimrc,
" but pressing `gd` in a go file still goes to definition.
let g:go_def_mapping_enabled = 0
```

**Comment by fatih** [comment]
Hi @oryband. Thanks for opening this and the other PR's. I'm currently busy, however I'm going to look at it in my spare time as soon as possible.

**Comment by fatih** [comment]
I've double checked and this is indeed working. Please execute `:nmap` and see to what `gd` is mapped after you add the setting above in your `vimrc`. For example in my case there is no `gd` listed after adding it to my vimrc.

**Comment by fatih** [comment]
Ping

**Comment by oryband** [comment]
hey @fatih  I'll get to it in the following days, please hold the line until then :)

**Comment by fatih** [comment]
@oryband I'll close this issue as it works as intended.

**Comment by k-i-k-ichi** [comment]
I have the exact same bug, delete all files in .vim/views resolved this bug for me.
