### ISSUE TITLE
can't set errcheck to run on buffer save like govet, golint

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#387]
Now that errcheck has become faster (see kisielk/errcheck#56), I tried adding `errcheck` to `g:syntastic_go_checkers` to make it run on every buffer save, just like we talked about in #259:
```vim
let g:syntastic_go_checkers = ['go', 'govet', 'golint', 'errcheck']
```
However, i don't see any errcheck output for some reason, while `govet`, `golint` work. I understand this might be a syntastic issue (see scrooloose/syntastic#1286), but I thought maybe we should discuss this first in here, since it's integrated used `:GoErrCheck`:

1. I've noticed `:GoErrCheck` outputs results to quickfix window instead to the location list, where syntastic outputs all other errors. Why is that? errcheck is a checker like all others.
2. In addition, is there a way to make `vim-go`'s `:GoErrCheck` function to run instead of calling `errcheck` directly using the setting above?
3. Is there any other better way to achieve what I'm trying to do?

Thanks!

**Comment by fatih** [comment]
1. It's not a linter and quickfix is the perfect tool for it because it outputs a list of lines where error checking is absent. Both `golint` and `govet` are using quickfix window. I don't know what you mean like all others.

2. I didn't get this

3. I think you need to first get the difference between `golint` and `errcheck` and see why it doesn't work. Maybe you can contact the author of `errcheck`. I don't use syntastic so I have zero information about it :)

**Comment by oryband** [comment]
1. Using the configuration above with syntastic, `golint` and `govet` output to location list, and this is the same behaviour with all other syntax checking tools in Go as well as other languages (`go build`, `pyflakes`, `gcc`, etc). For me, `errcheck`'s output are errors that should be fix just like the above, so they should be printed to the location list. This is of course a per-user opinion.
2. I meant that I want `errcheck` to execute on buffer save and output  to location list instead of quickfix (like `golint` and `govet` do using syntastic). I can't get it to work using syntastic, so I asked for an advice how to execute it using `:GoErrcheck` instead.
3. I do get the feeling the best solution would be to send a PR to syntastic's repo.

Thanks.
