### ISSUE TITLE
setting additional syntax highlighting options slows down cursor and makes it blink

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#388]
Here are my vim-go settings:
```vim
let g:go_def_mapping_enabled = 0
let g:go_fmt_fail_silently = 1
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_structs = 1
let g:go_highlight_trailing_whitespace_error = 0
let g:go_textobj_enabled = 1
```
I'm getting heavy "cursor blinks" when navigating with these settings. e.g. holding `j`/`k` for a couple of settings completely hides the cursor because it blinks a lot, and i've no idea where the cursor is.

Turning the above settings one-by-one slowly solves the problem, decreasing the "blink time" bit-by-bit. I didn't notice a particular setting that does causes this more than the others.

Why is syntax highlighting slowing the cursor so much?

**Comment by fatih** [comment]
This is a Vim problem rather then vim-go. You can speed up it though. It was discussed here: 

https://github.com/fatih/vim-go/issues/145

Thanks for opening this.

**Comment by oryband** [comment]
@fatih thanks, I'll try the suggestions there.

**Comment by oryband** [comment]
@fatih well, setting `synmaxcol`, `re=1` and all the other recommendations, vim is still slow with all highlighting options enabled (like above): I still see garbage characters, cursor blinks, and now even slow autocomplete popups (using YCM) making vim hang when typing. Any other ideas?
