### ISSUE TITLE
:GoRename ignores files with +build tags

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#389]
I have a file with `+build integration` tag, which is ignored when renaming types with `:GoRename`.

**Comment by fatih** [comment]
This is normal, because `integration` is not a satisfied tag and the go toolset will ignore it. Check the docs here:

http://golang.org/pkg/go/build/

Basically you do the same as `// +build ignore`.

**Comment by oryband** [comment]
@fatih is there a way to send a `-tags` parameter to `:GoRename`? Right now I can't do anything. :\

**Comment by fatih** [comment]
Fortunately not, this is a constraint of the go tools. Gorename doesn't have a clue about it. You can ask this to the golang-nuts mailing list, the source code is here: https://github.com/golang/tools/ and the author is Alan Donovan.

**Comment by fatih** [comment]
Btw here is the list that satisfies the rule: 

```
- the target operating system, as spelled by runtime.GOOS
- the target architecture, as spelled by runtime.GOARCH
- the compiler being used, either "gc" or "gccgo"
- "cgo", if ctxt.CgoEnabled is true
- "go1.1", from Go version 1.1 onward
- "go1.2", from Go version 1.2 onward
- "go1.3", from Go version 1.3 onward
- "go1.4", from Go version 1.4 onward
- any additional words listed in ctxt.BuildTags
```

**Comment by fatih** [comment]
@oryband ok I have found a fix for it, I need to open a PR to the official Go repo. It'll take some time though.

**Comment by oryband** [comment]
@fatih thanks! can you elaborate?

**Comment by fatih** [comment]
Sure: https://groups.google.com/forum/#!topic/golang-nuts/M7P0xae6iWM

**Comment by oryband** [comment]
Thanks!

**Comment by fatih** [comment]
Related feature set, Alan added it:  https://go-review.googlesource.com/#/c/9172/1 Once it's in usable state I'm going to introduce a new "go_build_tags" setting and once set it will be passed to all commands that support this new `-tags` flag.

**Comment by oryband** [comment]
:+1:
