### ISSUE TITLE
syntax highlighting on combined operators not working as expected

### ISSUE THREAD

**Issue by jpittis** [fatih/vim-go#394]
````*foo```` will highlight the ````*```` as an operator as expected.

````!*foo```` will only highlight the ````!```` operator and not the ````*````.
````(*foo)```` will not highlight the ````*```` operator.

Not sure if this has been discussed. Is it intended behaviour? I'll hopefully have a look at it tomorrow and see if there's any easy fix.

relevant: #372 and 1042109ca30d442db08a5f0988837e9401d4d597

**Comment by jpittis** [comment]
This simple fix got it working for me bb1adaf8dc811f381c1051465e02f55367c69213.
I don't know my regex too well though so I could be doing something terribly wrong.

**Comment by fatih** [comment]
Adding @cespare to the conversation. If it doesn't work anything just open a PR. The initial change looks good for me.

**Comment by cespare** [comment]
Thanks for the heads up. Sent a PR.
