### ISSUE TITLE
Syntax highlighting on function names

### ISSUE THREAD

**Issue by rcousens** [fatih/vim-go#395]
For the life of me I cannot get function names to highlight like your screenshot in the repo README

![screenshot from 2015-04-21 23 23 16](https://cloud.githubusercontent.com/assets/6834920/7253127/98b9dd88-e87d-11e4-99f4-3aac842b79dc.png)

Any ideas?

I've tried your custom molokai as well and it did not highlight function names either.

**Comment by fatih** [comment]
Check out the settings section in the readme: https://github.com/fatih/vim-go#settings

Add the followings (or some of them):

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

Thanks for opening :)

**Comment by rcousens** [comment]
@fatih Thank you for the response. Very much appreciated. Love using vim-go, thanks for the great plugin.
