### ISSUE TITLE
One reason that `:GoDef` might fail silently

### ISSUE THREAD

**Issue by resal81** [fatih/vim-go#397]
So I found out why `:GoDef` would mysteriously not work while other `:Go*` commands were working. I thought you might want to add it to FAQ.

I have `mvim` and `go 1.4` installed using Homebrew. After installing `vim-go` using `Vundle`, I used it to installed the necessary binaries. However, `:GoDef` would fail without an error message, and the cursor would just jump to the beginning of the line.

The problem was that I had [EMBOSS](http://emboss.sourceforge.net) installed before installing `vim-go` which has a command called  [godef](http://emboss.sourceforge.net/apps/cvs/emboss/apps/godef.html). I think since it was already in the `$PATH`, `vim-go` assumed it's correct and didn't install Go's `godef`. Putting the right `godef` in the`$PATH` solved the issue.

**Comment by fatih** [comment]
Hi @resal81. This is a weird problem indeed :) We need to add this to troubleshoot section and move it to Wiki. I'm closing this as it's not a vim-go issue and I keep it only for vim-go. Thanks for notifying it :+1:
