### ISSUE TITLE
Path is doubled in error list when we issue the :GoInstall during package development

### ISSUE THREAD

**Issue by LubosPintes** [fatih/vim-go#399]
Windows 7 64-bit, Gvim version 7.4.699
$GOPATH = c:\go
Steps to reproduce:

:cd c:\go\src
:!md a
:cd a
:new a.go

Write something, with mistake for testing:

package a

func F() int { return 1 

:w|GoInstall

Then in quick fix is:
C:\go\src\a\c:\go\src\a\a.go|5| syntax error: unexpected EOF

**Comment by fatih** [comment]
@mattn fixed with with #400. Can you please pull the latest master and try again?

**Comment by gavrie** [comment]
It seems this fix causes a new issue, see #407.
