### ISSUE TITLE
:GoFmt on :w mess with Vim :redo

### ISSUE THREAD

**Issue by oblitum** [fatih/vim-go#40]
I thought this plugin has settled this issue but sadly, it didn't. I was one of those who tried to provide a solution [to a related question on SO](http://stackoverflow.com/a/18536378/1000282). Still my approach, which I guess is the same being used here, will mess with redo. This is very simple to reproduce:
- Open a Go source file.
- Make some modification.
- `:w` to save it.
- Press `u` to undo the previous change.
- `:w` to save it again, now with the original content.
- Try press `ctrl-r` to redo the previous modification, it won't redo, but it should.

Playing with undo and redo, the cursor may go to the top of the file without one asking for, it's very annoying.

**Comment by mitermayer** [comment]
I am facing similar problem with `vim-prettier` used similar fixed as this to solve the “undo” but the “redo”from an undo of formatted coded still takes cursor to the top.

Does this behaviour also occurs here too ?

**Comment by oblitum** [comment]
@mitermayer vim-go is one of the few plugins that got this right (the only one at the time), even though I don't use it anymore, I tested it extensively, and reported it as a model for many other plugins that had the same issue. Not sure whether it's rock solid as before, but fatih came up with a solution after a good time of fiddling.

**Comment by bhcleek** [comment]
@mitermayer vim-go does not suffer from that problem. The code hasn't changed much since the solution that @oblitum mentions. You can find the code that deals with undo in https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim
