### ISSUE TITLE
vim-go won't complete local imported library.

### ISSUE THREAD

**Issue by flyingfoxlee** [fatih/vim-go#401]
For the go builtin libs, it's OK.
`omnifunc` is set to `go#complete#Complete`

**Comment by fatih** [comment]
Please install them with `go install` before.

**Comment by flyingfoxlee** [comment]
Also the `./test.sh` failed too.

**Comment by fatih** [comment]
Yeah we need to handle that one. But completion and import are different things. Did you do what I said in my previous response?

**Comment by flyingfoxlee** [comment]
After `go install`, it works like charm. Thank you~ I'm also using supertab. Is it possible to bind omnifunc to `tab`?

**Comment by fatih** [comment]
Yes it's possible but it's out of scope. I'm using YCM for example, checkout the examples from my dotfiles (to do completion with tab): https://github.com/fatih/dotfiles/blob/master/vimrc
