### ISSUE TITLE
GoFmt error messages buffer placement (collision with tagbar)

### ISSUE THREAD

**Issue by iu0v1** [fatih/vim-go#406]
Hello.
I have some trouble with 'error messages buffer' placement.
When GoFmt return error, buffer with error messages attach (split) to tagbar window.
It's a bug or feature? :)

Thanx in advise.

![screenshot from 2015-04-30 12 21 23](https://cloud.githubusercontent.com/assets/1669027/7410199/54390792-ef35-11e4-80e6-a98d99865209.png)

**Comment by fatih** [comment]
It's totally up to you. We call `cwindow` and there are many ways to put it somewhere. For example I have this in my vimrc:

```
" This trigger takes advantage of the fact that the quickfix window can be
" easily distinguished by its file-type, qf. The wincmd J command is
" equivalent to the Ctrl+W, Shift+J shortcut telling Vim to move a window to
" the very bottom (see :help :wincmd and :help ^WJ).
autocmd FileType qf wincmd J
```

Thanks for opening the PR :)

**Comment by iu0v1** [comment]
Many thanx.

**Comment by alienth** [comment]
@fatih The autocmd solution has one significant downside. The wincmd blows away the smart resizing that `go#list#Window` does, so the location window ends up taking far more space than needed in most cases.
