### ISSUE TITLE
Struct, operator, method highlighting breaks when installing with vim-plug

### ISSUE THREAD

**Issue by hoverproject** [fatih/vim-go#409]
Upgraded to 1.0.4 via vim-plug (previously installed with Pathogen). Had the following set in vimrc:
`let g:go_highlight_functions = 1`
`let g:go_highlight_operators = 1`
`let g:go_highlight_methods = 1`
`let g:go_highlight_structs = 1`

Highlighting for structs, operators and methods no longer displayed. Removed plugin via vim-plug, re-installed with Pathogen, and highlighting worked again.

**Comment by fatih** [comment]
I'm using vim-plug and everything works as intended. I think you have an installation problem or the latest vim-plug has problem (which I can do nothing). Thanks for reporting.
