### ISSUE TITLE
Scratch window appears on autocomplete

### ISSUE THREAD

**Issue by jakesandlund** [fatih/vim-go#415]
When I go to autocomplete something like `url.ParseQuery(` below, a useless scratch window appears at the top. How do I get that to go away? Is that part of the snippets feature, or docs? I'm using YCM, if that helps.

![image](https://cloud.githubusercontent.com/assets/698077/7465143/ff95fb50-f290-11e4-8561-32263cfc4355.png)

Thanks for the cool plugin!

**Comment by nowk** [comment]
Pretty sure this is the preview feature that comes with some of the autocompleters like YCM and neocomplete. 

You should be able to turn that off with

    set completeopt-=preview

**Comment by fatih** [comment]
Yeap, as @nowk said it's a vim feature. Thanks for opening though.
