### ISSUE TITLE
Add a reference to :Helptags into Install documentation

### ISSUE THREAD

**Issue by uli-go** [fatih/vim-go#416]
I installed vim-go but I had to learn that I had to execute pathogen's :Helptags command once to make :help vim-go work. So I suggest it to be added to the vim-go documentation.

**Comment by fatih** [comment]
Yeah, but it's not a vim-go problem. For example `vim-plug` is generating help tags automatically:

https://github.com/junegunn/vim-plug/wiki/faq#does-vim-plug-generate-help-tags-for-my-plugins

I don't want to clutter the readme with every single detail. However I'll add a notice so people knows how to reach it. Thanks!

**Comment by fatih** [comment]
Here is the change: https://github.com/fatih/vim-go/commit/ea5ba7ff76f3dcb70173013812d2b967ae85ab86 Thanks again for the notice.

**Comment by uli-go** [comment]
Hi,

thanks for the response. It isn't indeed an issue of the vim-go package.
But I read the Readme and wondered why :help vim-go didn't work after I did
exactly what the Readme told me. I had to use strace to find out that vim
tried to read the tags file. I could work it out, but others?

Uli
