### ISSUE TITLE
GoTest, GoVet, GoInstall ignore autowrite option

### ISSUE THREAD

**Issue by uli-go** [fatih/vim-go#417]
While GoBuild and GoRun use make and therefore support the autowrite option, the commands GoTest, GoVet and GoInstall ignore it. GoTest will happily report success while the active buffer has an error on it. 

Here is a gist with a patch I created: https://gist.github.com/uli-go/fc5fe3f41eeb948ad785

**Comment by fatih** [comment]
Hi @uli-go. Thanks for the patch!  It makes sense and I've tested it works perfect. Just merged it.

**Comment by uli-go** [comment]
Thanks for the positive feedback.
