### ISSUE TITLE
Screenshot Config

### ISSUE THREAD

**Issue by dax0** [fatih/vim-go#418]
Is there any chance you could upload your .vim folder and .vimrc so we can start off with a working version that looks like this: https://camo.githubusercontent.com/916aef7dc813e1da4c644ee8b9eb60fb266e7e25/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3137343430342f76696d2d676f2d322e706e67

**Comment by fatih** [comment]
It's already on Github: https://github.com/fatih/dotfiles/blob/master/vimrc :)

Thanks

**Comment by dax0** [comment]
Awesome. Thanks!
