### ISSUE TITLE
Not an editor command: GoRun

### ISSUE THREAD

**Issue by skoczko** [fatih/vim-go#419]
OK, I am sure I messed something up. I am using pathogen to install the plugin. I ran :GoInstallBinaries which worked OK. I see syntax highlighting is there. Yet I can't run any of the commands: :GoRun, GoDoc, etc. Ideas?

**Comment by fatih** [comment]
This is not vim-go related issue. Search for the issues please. You didn't installed vim-go properly. Please use pathogen or any other plugin manager to avoid problems. Thanks.

**Comment by skoczko** [comment]
I _am_ using pathogen, as I have wrote above. Also, :GoInstallBinaries did work so some parts of the plugin seem to work. This is the output of :scriptnames:

 38: /Users/jakub/.vim/bundle/vim-go/syntax/go.vim
 39: /Users/jakub/.vim/bundle/vim-go/indent/go.vim

Do you see anything obvious missing?

**Comment by fatih** [comment]
Check this out: https://github.com/fatih/vim-go/issues/282#issuecomment-69174561

**Comment by skoczko** [comment]
That did the trick, thanks! Would it make sense to add to the README for future reference?

**Comment by fatih** [comment]
@skoczko this is not vim-go related, it's something because pathogen was not installed properly. vim-go doesn't rely on pathogen, you can use vundle, plug, vim-plug, neobundle, etc.. there is a lot of options to choose. Thanks for bringing this up though :)

**Comment by BruceWangNo1** [comment]
I encountered similar problems. I looked through a lot of the related issues. No dice. I came across [this page](https://github.com/fatih/vim-go) and I ran `git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go` and `:GoInstallBinaries` in vim. "GoRun" is now available.

**Comment by FantasyLeo** [comment]
# feedback
I encountered the same problem. 

I used vim8, and installing by following:
- [Vim 8 packages](http://vimhelp.appspot.com/repeat.txt.html#packages)
- - ``` git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go```

I solved it by adding the following to the file .vimrc:

```.vimrc
" Enable filetype plugins 
filetype plugin on
```

Would it make sense to add to the README for future reference?

Think twice. @fatih 

Thanks all.
