### ISSUE TITLE
GoInstallBinaries bug in mac

### ISSUE THREAD

**Issue by fjyaosun** [fatih/vim-go#421]
when I set two path to GOPATH  like:GOPATH=/Users/dudu/go:/Users/dudu/DocumentsDocuments/workspace/go_project
then i use :GoInstallBinaries in vim
then vim-go will create a folder "go:" in /Users/dudu/
then vim-go will download file in "/Users/dudu/go:/Users/dudu/DocumentsDocuments/workspace/go_project/bin/"
not in "/Users/dudu/go/bin" or "/Users/dudu/DocumentsDocuments/workspace/go_project/bin"

my English is poor ,sorry

**Comment by fatih** [comment]
Hi @fjyaosun 

I don't know what you are expecting. What exactly do you want? I've just tried it again and it works as expected. Did you set `$GOBIN` to the second folder?

**Comment by shazow** [comment]
I think the problem @fjyaosun ran into is that technically Go supports multiple paths in $GOPATH separated by `:`, and it seems it didn't split the paths and treated it as one huge path? I'm guessing the fix is to split on `:` and install on the first path.

**Comment by fatih** [comment]
@shazow we do it already, that's why I've asked if he set $GOBIN to something else:

https://github.com/fatih/vim-go/blob/master/autoload/go/path.vim#L38

**Comment by shazow** [comment]
Ah my bad, nevermind. :)

**Comment by fatih** [comment]
Closing this as I didn't receive a response for a month.
