### ISSUE TITLE
Oracle scope dependency

### ISSUE THREAD

**Issue by tsenart** [fatih/vim-go#423]
Hi Fatih,

As we bespoke on Twitter, I'm having trouble using scope dependent :Go oracle calls. You mentioned we could set it with `g:go_oracle_scope` and I'm trying to think of other ergonomic ways to do this. Here's a perhaps naive idea:  We could traverse the current working directory up until the repo root and then recursively look for `main` packages. We'd then either run the scope dependent `:Go` oracle calls with all of the found main packages, or, with another configuration, let the user pick which one to use. The user would be also able to set the path (relative or absolute) of a `main` package as an argument to the call.

**Comment by fatih** [comment]
Hi @tsenart 

Thanks for bringing this up. I agree that we should make scope handling smarter to handle common cases. For now I'm doing some changes already, which can be seen here:

https://github.com/fatih/vim-go/blob/master/autoload/go/oracle.vim#L82

I'll look into this into more detail once I have some time (I'm currently have a lot of things to do).

**Comment by tsenart** [comment]
Hi @fatih! Thanks for looking into this and food building vim-go. I wouldn't be the same go programmer without it.

**Comment by fatih** [comment]
I'll close this in favor of #437. I'm not sure traversing and finding any main package would be helpful. But the new `:GoOracleScope` has a very nice autocompletion support (it completes only go import paths) and it's really useful. I think we should use it a little bit and get a good sense about it. So other improvements can be made upon on it.
