### ISSUE TITLE
Godeps/gb aware tools

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#425]
This is just an idea. vim-go should be able to detect `Godeps`, a gb project, and many other popular options and change the `GOPATH` automatically so tools like `godef`, `gocode`, `oracle` etc.. uses the intended vendorized source codes. I've played around it locally (not pushed yet), but it works quite perfect. I'll push with updates once I'm finished with it. Any feedback is welcome again here.

**Comment by fatih** [comment]
I think we also should have a new `:GoPath` command that allows users to explicitly set their `$GOPATH` if they wish it.

**Comment by mariokostelac** [comment]
+1 for `gb` awareness. Thank you a lot for your contributions.

**Comment by fatih** [comment]
Another workspace related tool: https://github.com/skelterjohn/wgo

**Comment by fatih** [comment]
This is finished with: https://github.com/fatih/vim-go/pull/429 and it works perfect for `godep`. Once we merge this, I'll work on adding `gb` detection.

**Comment by davidbirdsong** [comment]
Did `gb` support ever get merged in? I've been using both `gb` and `vim-go` for roughly 2 years and I've yet to figure out how to get vim-go to know about the custom GOPATH under `src` and `vendor/src` in my gb project.

**Comment by bhcleek** [comment]
It did get merged. `g:go_autodetect_gopath` is the option that controls whether it looks for `src` directories: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1310-L1315.

But it _may_ be removed completely soon: https://github.com/fatih/vim-go/pull/1461#issuecomment-337719798. You may want to follow https://github.com/fatih/vim-go/pull/1525.

**Comment by davidbirdsong** [comment]
Great, thanks for the pointers. I'l track those issues.
