### ISSUE TITLE
Autocomplete function arguments

### ISSUE THREAD

**Issue by dax0** [fatih/vim-go#430]
Is it possible to autocomplete not just the function name but the arguments also and tab to each one to fill it in?

**Comment by fatih** [comment]
Hi @dax0. This could be possible unfortunately vim-go doesn't has his own autocomplete daemon or client handling the choices. The only thing it does is to create a list of possible choices coming from `gocode`. Completion via tab is another whole thing, you probably need something like YCM. I know that YCM has added recently a better support for Go. I would say ask this question to YCM's issue tracker.  

Thanks for the feedback. Let me know If you find something :)

**Comment by casimir** [comment]
The seems like a work in progress there see https://github.com/Valloric/ycmd/pull/124#issuecomment-103689974 and https://github.com/Valloric/ycmd/pull/137.
