### ISSUE TITLE
gofmt with split windows

### ISSUE THREAD

**Issue by ameihm0912** [fatih/vim-go#432]
When editing the same buffer in two windows (e.g. vertical split looking at different parts of the same file), on save in one window, the view in the other window is immediately scrolled to the end of the buffer. The window the write was executed in will have it's cursor restored to the correct location, but the other does not.

This seems to be a new issue, rolling back to ea5ba7f and the issue does not occur, it seems to have been introduced after that at some point

**Comment by fatih** [comment]
I'm aware of it too. It's probably because it's  the same buffer and the buffer content changes. Vim reloads the view and your cursor on the other window is put to the end of the file. I'll look into it. Thanks for the report @ameihm0912

**Comment by fatih** [comment]
@ameihm0912 please pull latest master and try again. Thanks for reporting again :+1:
