### ISSUE TITLE
Support for go generate

### ISSUE THREAD

**Issue by mdwhatcott** [fatih/vim-go#433]
`:GoGenerate` would invoke `go generate` just like `:GoBuild` invokes `go build`.

**Comment by fatih** [comment]
Thanks @mdwhatcott I'll add this once I have time and finished with the other tasks.

**Comment by fatih** [comment]
Related PR: #463 

@mdwhatcott I've didnt yet tried the new PR nor did I review it. However if you have an existing code that uses `go generate` I would be happy if you could try #463

**Comment by fatih** [comment]
This is now merged to master with https://github.com/fatih/vim-go/pull/463. Thanks!
