### ISSUE TITLE
go-def-split map not work well, and open a new tab

### ISSUE THREAD

**Issue by numbcoder** [fatih/vim-go#438]
My config:
```viml
au FileType go nmap <Leader>ds <Plug>(go-def-split)
```
It will open the current buffer in a split window, and open the define file in a new tab window, `go-def-vertical`  has the same problem.

MacVim 7.4(76)

Thanks!

**Comment by fatih** [comment]
I have these commands and they work perfect:

```viml
au FileType go nmap <Leader>s <Plug>(go-def-split)
au FileType go nmap <Leader>v <Plug>(go-def-vertical)
au FileType go nmap <Leader>t <Plug>(go-def-tab)
```

Are you sure you don't use any additional settings in your vimrc? Do you have other commands that might interfere with this? This feature is enabled for months and I didn't have any single complaint, so I think this might be something else on your part.

**Comment by numbcoder** [comment]
Just remove
```viml
set switchbuf=usetab,newtab
```
It works!

Thanks!
