### ISSUE TITLE
Add option to make GoTest not jump to test that failed.

### ISSUE THREAD

**Issue by rHermes** [fatih/vim-go#439]
As stated in the tile, I would very much like an option to disable the automatic jump to the test file when a test doesn't pass. When I run a test, the information in the quickfix list is all I need.

If there already is a way to do this, I'm sorry for the trouble :)

**Comment by fatih** [comment]
There is already, please have a look at the docs next time :) Add the following to your `vimrc` to disable it.

```viml
let g:go_jump_to_error = 1
```

**Comment by rHermes** [comment]
I'm very bad vim user, but I thought I looked through the documentation, both :h vim-go and :h GoTest

Could you tell me where it is, and how you found it, so I don't repeat silly mistakes such as this again :(

**Comment by fatih** [comment]
Sorry. I thought it was always there. My apologizes for my previous comment. I'll fix it. Let me re open the   the issue again and edit the title to so the missing piece is added. Sorry again.

**Comment by rHermes** [comment]
No problem!

I want to thank you for making go coding enjoyable in vim! Keep up the good work :+1:

**Comment by fatih** [comment]
Hm now that I'm thinking, I think we should completely remove the variable: `g:go_jump_to_error` and use the `!` identifier. This is how `:make` works. For example if you call it like `:make!` it will not jump to the error, `:make` will jump to the error. This is idiomatic vim usage and fit's better into the vim usage. We have already this support for both `:GoBuild` and `:GoRun`, but not for commands such as `:GoTest`, `:GoInstall`

**Comment by fatih** [comment]
Check out this: https://github.com/fatih/vim-go/issues/440 for how to improve and change this behavior. Thanks @rHermes you made me aware of something important :+1:
