### ISSUE TITLE
"autodetect GOPATH" doesn't work with `gb`

### ISSUE THREAD

**Issue by fannheyward** [fatih/vim-go#444]
It's great that vim-go added "autodetect GOPATH" feature. Seems like it doesn't work with `gb`?

I test with https://github.com/fatih/gb-example 

0. my global $GOPATH setting: `echo $GOPATH ==> /Users/fannheyward`
1. cd `gb-example`
2. `vim src/cmdname/main.go`
3. `:GoPath` doesn't changed, still `/Users/fannheyward`
3. goto `util.SnakeCase`, then `:GoDef`, error: `parseLocalPackage error: no more package files found^@godef: no declaration found for util.SnakeCase`
4. `gb build/test` works fine.

Thanks for your work, vim-go is great!

**Comment by fatih** [comment]
Hi @fannheyward 

You are totally right! `gb` support will come with this PR: https://github.com/fatih/vim-go/pull/420 It's not merged. autodetect GOPATH is currently only for godep and single mono src directories. I'll close this in favor of #420. Thanks for mentioning :)
