### ISSUE TITLE
go get complains about -f flag on :GoInstallBinaries

### ISSUE THREAD

**Issue by Bajron** [fatih/vim-go#445]
I had a problem with GoInstallBinaries. go get reported "-f flag provided but not defined". I don't know what it is supposed to do (I am newbie in go), but removing the flag in line 80 of https://github.com/fatih/vim-go/blob/master/plugin/go.vim solved the problem -- all binaries were downloaded and installed.
I am on Ubuntu 14.04, go version go1.2.1 linux/amd64

**Comment by fatih** [comment]
I think the flag was added recently. Sorry to hear this from you. I'll going to push a fix and only add -f if the `go` version is higher than `1.4.x`

**Comment by fatih** [comment]
@Bajron can you test https://github.com/fatih/vim-go/pull/446 please ?

**Comment by Bajron** [comment]
It is ok now. Thanks!
