### ISSUE TITLE
Comment Insertion

### ISSUE THREAD

**Issue by paked** [fatih/vim-go#447]
AFAIK there is no way to quickly comment out code. I feel like this would be a nice addition! I'd be more than happy to investigate this myself if it is a welcome addition.

**Comment by fatih** [comment]
You can use comment plugins and add a mapping yourself. Everyone does it like that. :)  Here is what I use:

```vimrc

Plug 'tomtom/tcomment_vim'

 map <D-/> :TComment<cr>
  vmap <D-/> :TComment<cr>gv
```
