### ISSUE TITLE
goSpaceError syntax hilighting very slow on long lines

### ISSUE THREAD

**Issue by chkno** [fatih/vim-go#449]
This rule is slow on long lines:

    syn match goSpaceError display "\(\(^\|[={(,;]\)\s*<-\)\@<=\s\+"

To reproduce:

1. Begin editing a new file foo.vim.
2. Create 5000 spaces (`5000i<space><esc>`)
3. Attempt to add a 5001th space or otherwise attempt to edit this line.  Every UI interaction incurs a ~10s lag.

Output from ":syntime report":

     TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
    19.232237   2      0      10.416958    9.616119  goSpaceError       \(\(^\|[={(,;]\)\s*<
     0.021542   2      0       0.011089    0.010771  goSpaceError       \(\<chan\)\@<=\s\+\(
     0.017746   2      0       0.008958    0.008873  goSpaceError       \(<-\)\@<=\s\+\(chan
    ...

**Comment by fatih** [comment]
Hi @chkno , I'm aware of it, that's why it's disabled by default. If you disable it:

```
let g:go_highlight_space_tab_error = 0
let g:go_highlight_array_whitespace_error = 0
let g:go_highlight_trailing_whitespace_error = 0
```

You are good to go. Unfortunately I don't have time to tackle the syntax file. Also I have some settings which speeds up the highlighting a little more:

```vim
" speed up syntax highlighting
set nocursorcolumn
set nocursorline
syntax sync minlines=256
set synmaxcol=300
set re=1
```

Does this improve your situation?

**Comment by fatih** [comment]
Any response on this?

**Comment by fatih** [comment]
Closing as I didn't get a response for over 1 month.
