### ISSUE TITLE
GoInstallBinaries errors

### ISSUE THREAD

**Issue by ambidextrousTx** [fatih/vim-go#453]
Hi. Thanks for the amazing plugin. I've used it on my work machine without issues. On my personal machine though, I cannot run GoInstallBinaries. I get errors, a snippet of which I am reproducing here:

```
vim-go: goimports not found. Installing golang.org/x/tools/cmd/goimports to folder /Users/username/Coding/GoLang/lib/bin/
Error installing golang.org/x/tools/cmd/goimports: golang.org/x/tools (download)
golang.org/x/tools/go/ast/astutil
# golang.org/x/tools/go/ast/astutil
../../lib/src/golang.org/x/tools/go/ast/astutil/enclosing.go:434: n.Lparen undefined (type *ast.Type
AssertExpr has no field or method Lparen)
../../lib/src/golang.org/x/tools/go/ast/astutil/enclosing.go:435: n.Lparen undefined (type *ast.Type
AssertExpr has no field or method Lparen)
../../lib/src/golang.org/x/tools/go/ast/astutil/enclosing.go:436: n.Rparen undefined (type *ast.Type
AssertExpr has no field or method Rparen)
../../lib/src/golang.org/x/tools/go/ast/astutil/imports.go:191: fset.File(gen.Rparen).MergeLine unde
fined (type *token.File has no field or method MergeLine)
vim-go: oracle not found. Installing golang.org/x/tools/cmd/oracle to folder /Users/ambidextrous/Cod
ing/GoLang/lib/bin/
Error installing golang.org/x/tools/cmd/oracle: golang.org/x/tools (download)
```

Both machines are running OS X. I am using Pathogen on both of them. On my work machine, GoInstallBinaries was able to install the binaries. The GOPATH etc. are pretty much identical on the two machines.

**Comment by fatih** [comment]
Can you run please:

```
go get -v -u golang.org/x/tools/cmd/goimports
```

on your local machine? This is not a vim-go problem, it seems your Go setup is broken. Or you have a dependency which is not updated. I've just tested it on a new GOPATH and I could successfully download `goimports`.

**Comment by ambidextrousTx** [comment]
Thanks - I uninstalled Go (which I had installed using a .pkg from the Go site) and reinstalled it using Homebrew. Now everything is working again.
