### ISSUE TITLE
Highlighting and autocomplete in *.go files are not working

### ISSUE THREAD

**Issue by KhaimovMR** [fatih/vim-go#456]
1. When i open *.go files there's no hightlighting at all.
2. When i press the autocomplete key specified in YouCompleteMe in status bar it displays "E764: Option 'omnifunc' is not set".

**Comment by fatih** [comment]
You didn't installed the plugin properly. Please have a look at the installation step and wiki:

https://github.com/fatih/vim-go#install
https://github.com/fatih/vim-go/wiki/FAQ-Troubleshooting

And here is my own vimrc for comparison:

https://github.com/fatih/dotfiles/blob/master/vimrc

**Comment by KhaimovMR** [comment]
I've installed it with Vundle properly. Launched ":GoInstallBinaries" and every binary was installed successfuly but i've no hightlights and autocompletion.

**Comment by KhaimovMR** [comment]
Big thanks for your .vimrc example.
Helped adding those lines before my "filetype plugin indent on":
set nocompatible
filetype off
