### ISSUE TITLE
`analysis scope has no main and no tests` in oracle functions

### ISSUE THREAD

**Issue by tobstarr** [fatih/vim-go#457]
I have a more complex go project with some main packages but also a lot of non-main packages. Whenever I use e.g. `GoCallers` on some function defined in a main package it just works, whenever I call it on a function defined in a non-main package I get the error `analysis scope has no main and no tests` from oracle.

I do not know much about oracle but it seems one would need to define all main packages from which those non-main packages could be referenced. Is that somehow possible in vim-go or is that a general oracle issue?

**Comment by tobstarr** [comment]
Seems I found the nob I need to configure to make it work `g:go_oracle_scope`. Is it possible to set this configuration on a "per project" base?

**Comment by tobstarr** [comment]
I am going with `thinca/vim-localrc` for the time being but would wonder if that can also be done via `fatih/vim-go`

**Comment by fatih** [comment]
Hi @tobstarr. You can do it, please check out the docs for `:GoOracleScope` [1]. It was added recently so you can dynamically change the scope whenever you want.  And I think it's should be fearly easy to invoke it via Vim's event mechanism to call `:GoOracleScope` whenever you enter a folder.

[1]: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L315

**Comment by tobstarr** [comment]
Thank you!

**Comment by Mehradzie** [comment]
I have set the Oracle scope and it worked (partially) but it seems it requires to kinda compile the project to get the results as I am receiving 

`oracle: couldn't load packages due to errors: ...`

My project won't build without specific tags and all, is there a workaround for this ?

**Comment by fatih** [comment]
Hi @Mehradzie 

Yes, use `:GoGuruTags`, to define your own tags. Read the doc, it contains more info about it. Thanks.

**Comment by I159** [comment]
Hi! I'm experiencing the same behavior. I'm writing a lib so it has no main.go and no main function. I have several test files and no one named just "tests.go". I don't use nothing from Oracle. What is curious - some time ago Guru used to work well. But now when I'm trying to list function callers I receive the same error as mentioned in the title.
Also I use macVim in 256 color terminal under OSX. And I have a single and correct GOPATH. How to fix this issue?

**Comment by filmil** [comment]
Hello from the future!

How, exactly, is `:GoCallers` supposed to work?  Looks like if you don't have executables to specify, you can't use them due to the `analysis scope...` error.

The advice seems to be to use `:GoGuruScope` but if I do so, I get:
```
vim-go: guru /usr/local/REDACTED/REDACTED.go not found in loaded program 
```

Are there any pointers to working examples?
