### ISSUE TITLE
Autocomplete and GOPATH

### ISSUE THREAD

**Issue by derekchiang** [fatih/vim-go#462]
So I'm developing my project in a separate directory not under GOPATH.  To get autocomplete for my own code, I have set `GOPATH` to `$GOPATH:/my/project/directory`.  My code is organized into packages under `/my/project/directory/src`.  However, autocomplete still doesn't work with my own package.  Why is that?

**Comment by fatih** [comment]
You need to install the package via `go install` because under the hood `gocode` only reads from compiled libraries. Did you install them?

**Comment by derekchiang** [comment]
So I'm using this new build tool called `gb` which in itself is GOPATH-agnostic, so it doesn't actually install compiled libraries under the system-wide GOPATH.  But, it does put the compiled libraries under `/my/project/directory/pkg`, and since I have set GOPATH to `/my/project/directory`, it's unclear to me why gocode wouldn't work.

It might be worth noting that I've set GOPATH only in the same terminal session in which I launch vim.  So does vim pick that up and pass it to gocode?  If not, then I can see why it wouldn't work.

**Comment by fatih** [comment]
Unfortunately vim-go is not designed to work well with gb yet. So I don't know why GOPATH is not passed to vim, but if it's passed and your libraries are installed the rest is up to `gocode`. So vim-go doesn't have any clue, it's just a dispatcher which uses your input, passes it to `gocode` and reflects back the possible outcomes.  Check out the debugging section in `gocode`, it''ll be helpful for you: https://github.com/nsf/gocode#debugging

In that scope I have very little offer in terms of help here, as I don't know what your issue might be. I'm closing this as this is not related to vim-go. Feel free to open if you think there is a problem with vim-go.
