### ISSUE TITLE
GoDoc cannot distinguish a variable from a package name 

### ISSUE THREAD

**Issue by ersiner** [fatih/vim-go#465]
Consider the following code snippet:

```
var lines []string
scanner := bufio.NewScanner(file)
for scanner.Scan() {
  lines = append(lines, scanner.Text())
}
```

When I try to lookup documentation for `Scan()`, GoDocBrowser tries to open https://godoc.org/scanner#Scan as if `scanner` is a package name and if course it's not correct.

**Comment by fatih** [comment]
Thanks @ersiner for reporting. I'm aware of this problem. We need to change :GoDoc to find the underlying identifier to match and jump to the doc directly. I'm closing this in favor of the duplicate already open issue #332  (which is not yet resolved).
