### ISSUE TITLE
vim.go: $GOPATH is not set

### ISSUE THREAD

**Issue by henry-zhuang** [fatih/vim-go#466]
Go is installed through brew

    vim-go: could not find 'gotags'. Run :GoInstallBinaries to fix it.

When I enter `GoInstallBinaries`, it prompt:

    vim.go: $GOPATH is not set

**Comment by fatih** [comment]
Hi @henry-zhuang. This is not vim-go related. You need to set your GOPATH imho.

**Comment by muratsplat** [comment]
Note:
If you sure what GOPATH is setted on your pc and this error shows when vim  opens a go file. The point make sure that gotags installed via `go get`.

Try call gotags your terminal. If returns 'command not found'. You should install 'gotags' via `go get`
```sh
go get -u github.com/jstemmer/gotags
```
And if retuns no message likes error. Try again to open a go file your vim..

**Comment by henry-zhuang** [comment]
@muratsplat Thank you. After I set GOPATH, it works.
