### ISSUE TITLE
(Yet another) GOPATH issue

### ISSUE THREAD

**Issue by notpratheek** [fatih/vim-go#468]
This issue maybe a slightly funky one. 

I have set my ```$GOPATH``` in ```~/.bashrc``` as so:

```bash
# export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
```
and I have added the ```let g:go_bin_path``` in my .vimrc as so: 

```vim
let g:go_bin_path = expand("~/go")
```

I tried with ```expand()``` and gave an absolute path as well. 

Now, When I launch gvim from terminal and run ```:GoInstall``` it shows installed to ```/home/<myname>/go```

but, when I launch gvim from i3wm as a keyboard shortcut, (I have bound Win Key + g to launch gvim), and run ```:GoInstall``` it shows a blank (as in ```vim-go: installed to _____ )``` 

Is there anyway to fix ? Or, should I try with i3wm developer ? 

---
I'm on Ubuntu 14.04.2 LTS, gvim (I installed vim-gtk) version gives : 7.4.052 (Yeah, Its old ! :sweat_smile: ), running ```go version``` gives ```go version go1.4.2 linux/amd64
``` and I'm using the master branch of your plugin

**Comment by fatih** [comment]
Hi @notpratheek. What happens if you don't specify `g:go_bin_path` ?

**Comment by notpratheek** [comment]
@fatih

If I remove ```g:go_bin_path```, and 

1. from terminal open gvim and run ```:GoInstall``` it shows ```vim-go: installed to /home/<myname>/go```

2. from the keyboard shortcut, running ```:GoInstall``` it shows ```vim-go: installed to ______ ```

**Comment by fatih** [comment]
Oh btw, why are you calling `:GoInstall`? Did you mean `:GoInstallBinaries` ? It seems for the second option `GOPATH` is not set.

**Comment by notpratheek** [comment]
Sorry, I meant that ! :sweat_smile: 

When I launch from shortcut and run ```:GoInstallBinaries```, It shows the error : ``` vim.go: $GOPATH is not set``` 

But opening gvim from terminal and running ```:GoInstallBinaries```, It runs fine !

**Comment by fatih** [comment]
Got it, you need to check out Linux environment variables. This is really not vim-go related. I know but you are going to call `:GoInstallBinaries` only once. I can't say much or help you here :)

**Comment by notpratheek** [comment]
Ok ! Thanks @fatih :smile:

**Comment by notpratheek** [comment]
@fatih 

I seemed to have solved the issue with the help from #i3 channel in IRC (but all and full credits to the good folks at #i3 IRC for coming up with the solution !). 

To solve it, We need to add the ```$GOPATH``` and (the updated) ```$PATH``` variables to ```.xsessionrc```, Log-out and re login.

That seems to solve this funky issue ! :smile: 

--- 

I'm leaving this info here, in case it might help someone else ! :smile:

**Comment by gustavokuklinski** [comment]
I solved starting gvim with: `bash -lc gvim`, it will wrap Gvim with the current `.profile`or `.bashrc` file.

**Comment by bettinson** [comment]
Do you have Xcode developer tools installed?
