### ISSUE TITLE
E492: Not an editor command: Fmt

### ISSUE THREAD

**Issue by henry-zhuang** [fatih/vim-go#470]
This is my .vimrc
https://github.com/henry-zhuang/dotfile/blob/master/.vimrc

When I save my *.go file, it prompt:
```
Gofmt returned error
Error detected while processing BufWrite Auto commands for "<buffer=1>":
E492: Not an editor command: Fmt
```

**Comment by fatih** [comment]
Checkout the FAW, you didn't installed it properly: https://github.com/fatih/vim-go/wiki/FAQ-Troubleshooting Also there is no `Fmt` command in vim-go.

**Comment by henry-zhuang** [comment]
@fatih It seems to syntax error cause this error information, not fomat error.
