### ISSUE TITLE
Go tool commands does not respect $GOPATH in current shell.

### ISSUE THREAD

**Issue by chakrit** [fatih/vim-go#472]
As the title says. It seems like the tool only gets the `$GOPATH` value from the default shell environment and not the current one VIM is running in.

After running `:GoImplements` on an indentifier

```
vim-go: oracle: directory /Users/chakrit/Documents/example/src/db is not beneath any of these GOROOT/GOPATH directories: /Users/chakrit/Documents/go/src, /Users/chakrit/Documents/gopath/src
```

However running `:GoPath` prints the right value from the current shell (project's root)

```
/Users/chakrit/Documents/example/lib/:/Users/chakrit/Documents/example/
```

**Comment by chakrit** [comment]
Manually invoking `:GoPath` and giving it a path makes no difference.

**Comment by chakrit** [comment]
`:GoRename` also seems to have the same problem.

**Comment by chakrit** [comment]
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 29 2015 13:30:08)
MacOS X (unix) version
Included patches: 1-712
Compiled by Homebrew
```

**Comment by fatih** [comment]
Hi @chakrit. This should be something else, I don't think it's due Gopath handling in Vim-go as it's already there for months without any problem.

* What shell are you using? 
* What gives `:echo $GOPATH` and `:GoPath` ?

**Comment by chakrit** [comment]
* What shell are you using?

`zsh 5.0.7 (x86_64-apple-darwin14.0.0)`

* What gives :echo $GOPATH and :GoPath ?

Both print the same values of `/Users/chakrit/Documents/example/lib/:/Users/chakrit/Documents/example/`

**Comment by iverberk** [comment]
I think might be have similar issues. I'm using this project https://github.com/opencontainers/runc and when I open run.go I get an error message that both imports could not be found. Obviously this project uses godeps. :echo $GOPATH gives my the default system Go path (a single directory). :GoPath actually gives me the system Go Path *and* the godeps workspace path. It seems like the gocode tool is just not looking at the GoPath set in Vim, but using the default Gopath, resulting in the 'import no found' errors'. Any idea what the problem might be? I'm also running zsh: zsh 5.0.8 (x86_64-apple-darwin14.3.0)

**Comment by fatih** [comment]
Hi everyone.

This is a weird error because GOPATH is a very core thing to vim-go. It doesn't do anything but only changing it. So it only appends certain folders if those are detected. Other than this it's up to the tool (such as goimports, oracle, etc..) how they use it.

What happens if you add this to your vimrc: `let g:go_autodetect_gopath = 0` ?

**Comment by iverberk** [comment]
Hi Fatih,

Thanks for the reply! It is a strange issue indeed. Adding ```let g:go_autodetect_gopath = 0``` makes the :GoPath command not add the godeps workspace path anymore. So then my $GOPATH within Vim and outside are the same.

So you are saying that vim-go alters the global $GOPATH environment variable so that goimports, gocode, oracle can use the updated $GOPATH? The basic issues seems to be that those tools are only looking at the default $GOPATH.

Maybe to exclude some things: when you clone that project (or https://github.com/hashicorp/vault) and open a Go file in Vim you do not have a problem with missing imports? That would mean that it is something external to vim and/or vim-go.  I'm not sure what more information to give you to help with debugging.

**Comment by fatih** [comment]
It seems even if Vim sets the GOPATH, it doesn't get pick up by the tool itself. Did you changed GOPATH from outside (to the initial value, just like vim-go did) and tried it that way too? I'm using Mac and MacVim and doesn't have any issues. And trust me I've tried this feature for approx 1 month. So it means something else must be wrong, but I don't know what :)

**Comment by chakrit** [comment]
@fatih I think this maybe related to how VIM (or vim-go?) spawns new subshell to run the `go*` commands. If I modify my `$GOPATH` in my `.zshenv` file to the project-local folder. Everything works correctly. But if I have a mismatch, the default environment seems to gets the priority.

**Comment by chakrit** [comment]
My vimscript knowledge is limited but this seems to show the problem:

```
:GoPath
/Users/chakrit/Documents/example/lib/:/Users/chakrit/Documents/example/

**Comment by chakrit** [comment]
VIM version for reference.

```sh
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 29 2015 13:30:08)
MacOS X (unix) version
Included patches: 1-712
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/System/Library/Frameworks -framework Python   -lruby.2.0.0 -lobjc   
```

Same behavior in neovim.

```sh
NVIM 0.0.0-alpha+201506222256 (compiled Jun 24 2015 10:40:19)
Commit: 20a57c497b55bb3632f0d4bcd76c18628cfa5f43
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150624-1065-nqzx0o/build/config -I/tmp/neovim20150624-1065-nqzx0o/src -I/tmp/neovim20150624-1065-nqzx0o/.deps/usr/include -I/tmp/neovim20150624-1065-nqzx0o/.deps/usr/include -I/tmp/neovim20150624-1065-nqzx0o/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150624-1065-nqzx0o/.deps/usr/include -I/tmp/neovim20150624-1065-nqzx0o/.deps/usr/include -I/tmp/neovim20150624-1065-nqzx0o/.deps/usr/include -I/tmp/neovim20150624-1065-nqzx0o/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150624-1065-nqzx0o/build/src/nvim/auto -I/tmp/neovim20150624-1065-nqzx0o/build/include
Compiled by chakrit@CX22

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by renfredxh** [comment]
I'm having the same issue which is causing `:GoErrCheck` to throw incorrect "cannot find package" errors due to it not executing to gotool with the correct GOPATH. On master using MacVim on OSX.

```
:GoPath
/Users/renfred/Code/go/src/example/Godeps/_workspace:/Users/renfred/Code/go
:echom system("echo $GOPATH") 
/Users/renfred/Code/go           
```

**Comment by gatspy** [comment]
I also use zsh shell. run macvim in terminal,it's ok. when run macvim as gui occurs errors.
using macvim open a go source file,error info like this
`vim-go: could not find 'gotags'. Run :GoInstallBinaries to fix it.`
then,run GoInstallBinaries command,
`vim.go: $GOPATH is not set`

```
echo $GOPATH
/Users/MAC/work/golang
:GoPath
Users/MAC/Work/golang/:/Users/MAC/Work/golang/vendor/

**Comment by fatih** [comment]
Hi. This is because the environment variables are not passed to VIM. You can easily check any environment variable **inside Vim** with `:echo $GOPATH`. What does this give? If it's empty it means that your Vim and OS setup is incomplete or does have some problems.

**Comment by fatih** [comment]
@renfredxh can you please disable auto detection of gopath by adding the following line to your vimrc:

```
let g:go_autodetect_gopath = 0
```

Does this solve your problem?

**Comment by renfredxh** [comment]
@fatih this problem has been resolved for now (without changing `go_autodetect_gopath`) I'm not sure why, the `$GOPATH` is still what I posted above. Maybe something to do with upgrading to go 1.5.

**Comment by fatih** [comment]
To everyone involved in this issue, can you try to add the following to your vimrc (it's explicitly sets the shell to a well known one) and try again?:

```
set shell='/bin/sh'
```

Also one of the suggestions from the #vim (freenode) channel is:

```
<osse> fatih: my guess is the user has added -i or -l which makes (in the case of bash) the shell read .bashrc and  .bash_profile or .profile. Those can set GOPATH to whatever they like
```

**Comment by chakrit** [comment]
@fatih ill try in a moment.

**Comment by chakrit** [comment]
See https://github.com/fatih/vim-go/wiki/FAQ-Troubleshooting

**Comment by iverberk** [comment]
ICYI my problem was due to a syntastic setting (let g:syntastic_check_on_open = 1). The plugin manual recommends to enable this setting. Apparently it messes with vim-go since the automatic Godeps detection did not work anymore. The solution is to enable passive mode for Go files. Hope it helps anyone.

**Comment by iharsuvorau** [comment]
I have the same issue with vim-go: 
trying to call `:GoCallees` on a function I get `vim-go: current directory is not inside of a valid GOPATH`, but `:GoDef` works fine.

`:echo $GOPATH` and `:GoPath` reports the same correct GOPATH which is configured with .zshrc.

Setting `let g:go_autodetect_gopath = 0` and `set shell='/bin/sh'` in .vimrc do not change the behaviour.

I've tried to switch to bash with GOPATH specified in .bash_profile and got the same error.

What can be wrong?

---

vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 17 2017 11:21:47)
MacOS X (unix) version
Included patches: 1-1200
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     -gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        +perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.2 -lobjc
```

**Comment by bhcleek** [comment]
@iharsuvorau this is a very old and closed issue. Please open a new issue.

**Comment by iharsuvorau** [comment]
@bhcleek, thank you, magically it's solved now. I saw that @fatih was using macvim version and I've tried to install it and see how this can work out. On the first start it also complained but after restarting it started to work fine. And the version of vim from the shell I'm using is also works fine now.
