### ISSUE TITLE
error: cgo pkg-config not supported

### ISSUE THREAD

**Issue by nhjk** [fatih/vim-go#475]
When I import packages with cgo in them, I get the error "vim-go: cgo pkg-config not supported" when trying to rename things. Here's an example with the git2go package

```go
package main

import "github.com/libgit2/git2go"

func CantRename() git.Repository {
	return git.Repository{}
}
```

**Comment by fatih** [comment]
Hi @nhjk This is directly coming from `:GoRename` and the underlying tool. Which means your code doesn't support it and this not related with vim-go. The error warning should be clear. Vim-go is just a wrapper here and there is not much it can do. Thanks for opening the issue.
