### ISSUE TITLE
Disable error check on save?

### ISSUE THREAD

**Issue by derekchiang** [fatih/vim-go#477]
When I save a buffer, some sort of error checking process automatically runs and freezes my window for a few seconds.  How do you disable that?

**Comment by fatih** [comment]
Please don't use https://github.com/scrooloose/syntastic. Vim-go doesn't do any checking, it only outputs `gofmt` error if there is any. To disable them:

```
let g:go_fmt_fail_silently = 1
```

Thanks

**Comment by ffledgling** [comment]
fwiw, for anyone that comes here thinking this is caused by vim-go, like fatih pointed out it's likely caused by syntastic, the fix for that is `:SyntasticToggleMode`

**Comment by ArthurChiao** [comment]
`:SyntasticToggleMode` - this saves me.

**Comment by nichohells** [comment]
> Please don't use https://github.com/scrooloose/syntastic. Vim-go doesn't do any checking, it only outputs `gofmt` error if there is any. To disable them:
> 
> ```
> let g:go_fmt_fail_silently = 1
> ```
> 
> Thanks

This will effectively remove the one line split window beneath my status bar which is really a buffer that looks like a git branch list, listing all the errors I have in my program one by one. Thank you!
