### ISSUE TITLE
How can I make :GoLint run on save?

### ISSUE THREAD

**Issue by coolaj86** [fatih/vim-go#483]
I tried adding `autocmd BufWritePre *.go :GoLint` to `~/.vimrc`, but that didn't work.

**Comment by fatih** [comment]
Hi @coolaj86 

Use:

```
autocmd BufWritePre *.go call go#lint#Run()
```

Thanks.

**Comment by coolaj86** [comment]
Thanks, I also just found https://github.com/fatih/vim-go/issues/259 moments ago.

```
let g:syntastic_go_checkers = ['go', 'golint', 'errcheck']
```

This also works.

**Comment by Hyvi** [comment]
> Hi @coolaj86
> 
> Use:
> 
> ```
> autocmd BufWritePre *.go call go#lint#Run()
> ```
> Thanks.

it show error : "unkown go#lint#Run()",  what is the reason?  

thanks

**Comment by solderjs** [comment]
For some reason what I tried years ago didn't work this time I set up a new machine.

Here's what I did this time.

After installing the plugin I got the binaries

```
:GoUpdateBinaries
```

Then I updated my `~/.vimrc` with the following:

```
autocmd BufWritePre *.go :GoImports
autocmd BufWritePre *.go :GoMetaLinter
```
