### ISSUE TITLE
GoRun with build tags

### ISSUE THREAD

**Issue by elct9620** [fatih/vim-go#485]
I try to run my code using `:GoRun -tags debug` but I got error message "flag needs an argument: -tags" after I executed it.

But I think it may working, is I typed wrong flags in vim?

**Comment by elct9620** [comment]
Oops, I try `:GoRun % -tags debug` and working.
But will have the shortcut like `:GoRun -tags debug` ?

**Comment by fatih** [comment]
Hi @elct9620 

`:GoRun` doesn't support flags as it's not intended for long running apps. Thanks for the issue.
