### ISSUE TITLE
Syntax highlighting for //go:generate tags

### ISSUE THREAD

**Issue by mdlayher** [fatih/vim-go#487]
Hello!  Just updated `vim-go` and I'm a huge fan of the ability to highlight build constraints.  It makes them much more visible in my platform-dependent code.

If possible, it would also be very nice to (optionally) syntax highlight `//go:generate` tags, so they don't blend into the background as much.

Thank you very much for all of your hard work on this plugin.  It makes Go development with `vim` a true pleasure.

**Comment by fatih** [comment]
Hi @mdlayher, thanks for bringing this up. We can tackle this later, for now I've marked this as `feature` and don't close this till we implement it.

**Comment by mdlayher** [comment]
Sounds great, thank you very much!

**Comment by omeid** [comment]
+1
