### ISSUE TITLE
[improvement] oracle freevars: show suggestion to mark a region

### ISSUE THREAD

**Issue by akavel** [fatih/vim-go#490]
When `:GoFreevars` is called without any selection/region, it would be nice if it showed a hint/suggestion like: "GoFreevars should be used on a (selected) region of code". Otherwise it's hard to discover that. When `:GoFreevars` is called without any region (on "empty region"?), it just shows "no freevars". I had to consult the "freevars" mode in the *"Oracle Design Doc"* to realize I need to mark a region.

**Comment by fatih** [comment]
@akavel Thanks for the tip! I've added a warning as you said, hope it makes it more usable in the future for others.
