### ISSUE TITLE
Option to make :GoDef (gd) create a new tab or split

### ISSUE THREAD

**Issue by steveeJ** [fatih/vim-go#494]
It would be nice to have the described feature. One can easily get lost down deep several gd-jumps and jumping back can be annoying.

An example would be to have commands `:GoDef{t,v,s}` with mappings of `:gd{t,v,s}` respectively. This way one could decide how to advance which each jump.

Please let me know if I'm missing an alternative way that would make things easier.

**Comment by fatih** [comment]
There are already settings @steveeJ. Did you read the README.md and the docs?:

> By default the mapping gd is enabled which opens the target identifier in current buffer. You can also 
> open the definition/declaration in a new vertical, horizontal or tab for the word under your cursor:

```
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
```

Or did I misunderstand you :) ?

**Comment by steveeJ** [comment]
@fatih: You didn't misunderstand me at all. Thanks a lot for helping me out with my blindness, and sorry for totally wasting your time!
