### ISSUE TITLE
go write tab on new line

### ISSUE THREAD

**Issue by sagax** [fatih/vim-go#495]
when i push Enter for create new line i get Tab instead Space, but i use only space. howto fix this?

thanks

**Comment by sagax** [comment]
if i replace tab to space, when i save file - all space convert to tab. nothing writed about this problem with tab in doc.

**Comment by fatih** [comment]
Hi @sagax . This is due gofmt and is normal. If you don't want to use `gofmt` add this to your vimrc: `let g:go_fmt_autosave = 0`
