### ISSUE TITLE
Upcoming changes in golang.org/x/tools

### ISSUE THREAD

**Issue by shazow** [fatih/vim-go#501]
There are discussions for changes to Go tools, mostly renaming/consolidating things. It's not planned for "several months" but worth keeping an eye on it. Also they're accepting feedback/requests for the current toolset, I figure vim-go might have opinions to share. :)

- [Design doc](https://docs.google.com/document/d/1IIjEhq54T5KZHTdSyquMhaQ58htYclQpFEX4WRVOhJw/view#heading=h.y2yf1miyweis)
- [golang-dev discussion](https://groups.google.com/d/topic/golang-dev/ghWPctylooo/discussion)

(Feel free to close the issue if this is too early to worry about.)

**Comment by fatih** [comment]
Hi Andrey. Thanks for the notice. I've already read it but didn't have the time to respond to it :) Unifying the tool will be really awesome as we rely on to many small binaries. Having a single one would improve the overall stability and it would also lower the introducing of new features (as the new binary would already have all the features we would like to have). I'll probably will look into it. 

If anyone has any recommendation feel free to comment here. Especially anything about how the usage in vim-go could be better.

**Comment by fatih** [comment]
I'm closing this as there are still no recent changes. Even if there is I think, we as a community, will catch it up fairly quickly. So I'm closing. Feel free to reopen @shazow if you think this should be open. Thanks :)
