### ISSUE TITLE
Static analysis does not seem to work correctly for non "main" package files

### ISSUE THREAD

**Issue by ajm188** [fatih/vim-go#504]
If I am writing code that is not in the main package, I get no errors/warnings about calling non-existent methods, referencing undefined types, type mis-matches etc. So, if I am working on my own package, I lose basically all benefits of using the plugin.

Not sure if this an issue with the underlying go tools, or the way vim-go uses them.

**Comment by fatih** [comment]
Hi @ajm188. vim-go is fine, have a look at oracle's user manual: golang.org/s/oracle-user-manual However if you find an inconsistency (which indeed can happen), please open an issue with a test case (code). Thanks.
