### ISSUE TITLE
GoDef cannot work with package imported with a . (period).

### ISSUE THREAD

**Issue by lanchongyizu** [fatih/vim-go#512]
![screenshot from 2015-08-04 23 35 57](https://cloud.githubusercontent.com/assets/2138456/9064971/a4373756-3b01-11e5-8c10-a4cbb6aa8896.png)
When the following command is executed
```
:GoDef Println
```
it generates 
```
parseLocalPackage error: no more package files found^@godef: no declaration found for Println
Press ENTER or type command to continue
```

**Comment by fatih** [comment]
Hi @lanchongyizu. This is a well known limitation of https://github.com/rogpeppe/godef. Please have a look at that repo. Thanks!
