### ISSUE TITLE
GoBuild rebuilds up-to-date packages

### ISSUE THREAD

**Issue by jlovison** [fatih/vim-go#513]
When running any form of vim-go's `GoBuild` command, it effectively results in a `go build -a` and rebuilds dependencies that are already up-to-date.

In my case, as I'm importing a package that uses mattn/sqlite3, which has a 20s+ build time, this means all of the functionality vim-go brings to the table from quickly accessing testing, etc is 10x slower than just Alt+Z and running from the command line.

Obviously, I doubt that was the intent, but there doesn't seem to be anywhere in the settings to modify how vim-go runs the build command.

I know [vim-dispatch](https://github.com/tpope/vim-dispatch) could help reduce the inconvenience here, but I suspect this behavior is not working as intended.

**Comment by fatih** [comment]
Hi @jlovison 

You can use `:GoInstall`, which is basically the same but touches only new files. Other than this we simply call `go build` and there is no magic here. You can pass arguments to `:GoBuild` if you wish. Thanks.

**Comment by jlovison** [comment]
Hi @fatih,

Awesome - so doing a `:GoInstall` one time fixed this (which had been happening with `:GoTest` and all other compilation commands).

Thanks for the response.
