### ISSUE TITLE
gorename URL out of date

### ISSUE THREAD

**Issue by variadico** [fatih/vim-go#519]
The URL for `gorename` has been moved to `golang.org/x/tools/refactor/rename`.

https://godoc.org/golang.org/x/tools/refactor/rename

It would need to be updated here: 
https://github.com/fatih/vim-go/blob/a248fbf42571e4451755ff17df6ddd2be3863ca3/plugin/go.vim#L15

Of course, the old URL redirects to the new one, so nothing is broken. Just something I noticed during installation.

**Comment by fatih** [comment]
Hi @variadico.

Thanks for the notice. I've just checked and the binary place didn't change though: https://github.com/golang/tools/blob/master/cmd/gorename/main.go 

And you still install it via:

```
go get golang.org/x/tools/cmd/gorename
```

The place you mention is the library, not the main package.  I think there is a setup issue with you environment?

**Comment by variadico** [comment]
Ah, derp. My bad.

Everything is working perfectly fine. Nothing to do here.
