### ISSUE TITLE
GoDef doesn't follow the GOOS & GOARCH

### ISSUE THREAD

**Issue by ericwq** [fatih/vim-go#521]
i have the following mapping in the .vimrc:

~~~bash
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
~~~

while i browsing the golang source code. 

~~~bash
$ pwd
/Users/ericwq/dev/go/src/os
$ vi file.go 
~~~
go to line 117 and try to find the definition of f.pread(b,off) with ",dt". 
vim-go will jump to the file_plan9.go instead of file_unix.go!!!

in this case, the behavior of GoDef should consider the GOOS and GOARCH environment variable, or should consider the current opened file postfix (which define the Architecture and OS, such as amd64, linux).
~~~go
func (f *File) pread(b []byte, off int64) (n int, err error) { 
~~~

one thing to mention: the golang source directory is not under the GOPATH. 
~~~bash
$ env | grep GO
GOROOT=/usr/local/go
GOPATH=/Users/ericwq/dev/go_works
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ericwq/dev/go_works"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
~~~

**Comment by fatih** [comment]
Hi @ericwq. I think this is a godef problem. vim-go is just a wrapper. I think there is already a PR: https://github.com/rogpeppe/godef/pull/1 Can you please open your issue there? Thanks
