### ISSUE TITLE
error check

### ISSUE THREAD

**Issue by 7belrhalmia** [fatih/vim-go#523]
for every save i have quickfix window appear with error , i don't have syntastic

**Comment by fatih** [comment]
Hi @7belrhalmia 

This means your code is wrongly formatted. If you don't want disaplay `gofmt` errors add this to your vimrc:

```
let g:go_fmt_fail_silently = 0
```

**Comment by 7belrhalmia** [comment]
no , when i have error on my code and i save the quifix window appear , i don't wont that

**Comment by 7belrhalmia** [comment]
it can't be error formating because vim go do GoFmt on save

**Comment by fatih** [comment]
GoFmt produces error, other than this there is no single automatic checking on vim-go. There must be something wrong with your config.

**Comment by 7belrhalmia** [comment]
this is my config : 

autocmd! FileType go noremap ,c :GoRun<cr> 
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 0

**Comment by fatih** [comment]
IT must be `let g:go_fmt_fail_silently = 1` sorry. With this, you don't get any error showing up for autosave

**Comment by 7belrhalmia** [comment]
yeah man thanks that work ,  please can you explain me when gofmt return error  , And what the difference between :GoLint   and :GoErrCheck
