### ISSUE TITLE
GoInstallBinaries doesn't go get golang.org/x/tools/cmd/cover

### ISSUE THREAD

**Issue by ereyes01** [fatih/vim-go#524]
I was trying to run go-coverage on my code, but it needed golang.org/x/tools/cmd/cover to be installed. neither GoInstallBinaries nor GoUpdateBinaries installed it.

After I manually ran the go get command in my workspace, go-coverage worked great thereafter.

**Comment by fatih** [comment]
Hi @ereyes01 

It seems it's missing

https://github.com/fatih/vim-go/blob/master/plugin/go.vim#L10

You sure we need it ? We are calling `go tool cover`. Though I'm not sure if something changed with go `1.5`

**Comment by ereyes01** [comment]
I'm still on Go 1.4.2. I guess it's needed, since that's what the minibuffer was telling me when I tried to run coverage. I understand what you mean though, as I've used `go tool cover` on the CLI without needing to install that dependency...

**Comment by ereyes01** [comment]
So I couldn't reproduce this on a new GOPATH having just run `:GoInstallBinaries`. One possible problem could have been that I hadn't run `:GoUpdateBinaries` in a really long time on that first GOPATH where I saw this error. I have since run `:GoUpdateBinaries` on that first GOPATH after reporting this bug, so I'm not sure how to easily go backwards to where I was in my old toolchain versions :-/ 

So perhaps this isn't a vim-go bug, but a toolchain compatibility issue of some sort? If you're convinced of this, feel free to close. Thanks...

**Comment by fatih** [comment]
Alright, getting done environments is a hard thing. I'll close this, if you hit something similar again just don't forget to take a screenshot :)
