### ISSUE TITLE
How to run :GoVet on save?

### ISSUE THREAD

**Issue by breerly** [fatih/vim-go#528]
Been struggling with this... any idea?

**Comment by guns** [comment]
Use an autocmd on the BufWritePost hook. You should look into asking questions like these on the vim_use mailing list or in the #vim channel on freenode.

**Comment by fatih** [comment]
You can use something like https://github.com/scrooloose/syntastic or there is a PR sitting (which I don't if it makes to add or not) you can try that one too: https://github.com/fatih/vim-go/pull/520
