### ISSUE TITLE
GoBuild flickers but GoTest not

### ISSUE THREAD

**Issue by mechmind** [fatih/vim-go#530]
When I run GoTest it runs tests in background without switching to console. But when I run GoBuild it shows me console for a moment and then build succeed and screen swithes back to editor. This creates very annoying flickering. How can I fix this? I found that vim-go looks for `Make` function and invokes it instead of `make` but how I can utilize that hook?

**Comment by fatih** [comment]
Hi @mechmind 

I don't remember adding building tests in an async way. Are you sure you it runs in background?

For `:GoBuild`, the `Make` is a part of vim-dispatch and is only called explicitly when `g:go_dispatch_enabled` is set to `1`. It's by default disabled.

**Comment by mechmind** [comment]
`go#cmd#Test` invokes `go test` using `go#tool#ExecuteInDir`. Looks like it runs a command asynchronously. BTW vim-dispatch can run `make` in background but it will not automatically open quickfix window on build completion.
Can we use `go#tool#ExecuteInDir` instead of `make` in `go#cmd#Build`? Seems like it is a better fit for a task.
Thanks.

**Comment by mechmind** [comment]
I made simple fix for `go#cmd#Build` there - https://github.com/mechmind/vim-go/tree/go-build-in-background - and vim does not flicker on build anymore, but I removed `-o > /dev/null` from command because `go build` complains about that.

**Comment by fatih** [comment]
The changes you made are not changing the execution process. In Vim everything is synchronously. Please check out your vim setup, because there is no such flickering on GoBuild. If you want truly async builds, please checkout NeoVim and use that one. Thanks
