### ISSUE TITLE
GoFmt clears file with goimports as the formatter

### ISSUE THREAD

**Issue by clentfort** [fatih/vim-go#532]
I'm using `vim-go` with `goimports` as the default formatter (`let g:go_fmt_command = "goimports"` is what I have in my `.vimrc`). No matter what contents I have in a file, when ever I save (or run `:GoFmt`) the entire contents of the file is cleared before it is written to disk. This only started to happen today, without any changes to my `.vimrc`. It worked fine before.

I use `vim-go` together with `vim-plug` and have not configured `vim-go` in any other way than changing the formatter. My `.vimrc` can be found here: https://gist.github.com/clentfort/b77418f1602bcc46ab63

**Comment by fatih** [comment]
Hi @clentfort 

Can you please give more detail by what you mean with "entire contents of the files is cleared before it is written to disk"?

Currently we directly write to the file and do not any kind of replacing. So I wonder what is different in your case.

**Comment by clentfort** [comment]
This issue has resolve itself, it seems there was some weird behavior that persisted restarting VIM, restarting my computer solved it. (I worry for my RAM and CPU)

No matter what content I had in a file, saving it would blank the file completly, i.e. remove any code or comments or anything. Just replace it with a complete blank file.

**Comment by fatih** [comment]
Got it. It's weird imho, it's the first time I see this kind of problem. If you hit it again please also attach some kind of reproducible test please. Thanks.
