### ISSUE TITLE
vim-go and YCM

### ISSUE THREAD

**Issue by svanharmelen** [fatih/vim-go#535]
I was browsing through your [vimrc](https://github.com/fatih/dotfiles/blob/master/vimrc) file and noticed you are also using vim-go together with YCM.

Now I'm noticing some strange/bad behaviour (mainly read timeout errors) from YCM while trying to autocomplete Go code. So I was wondering if you experience the same problem?

And additionally I was wondering if you compiled YCM with the `--gocode-completer` option? Your vimrc seems to indicate you didn't use that flag, but I'm wondering if that is actually the case? I can imagine it would be "cleaner" to use that flag and let YCM query gocode directly, instead of making YCM talk to omni-complete which in turn talks to vim-go, which then finally queries gocode.

Thanks!

**Comment by svanharmelen** [comment]
Anyone around that has experience with these tools and recognises my issue? Any tips and or workflows that are known to work well are very much appreciated!

Thanks!

**Comment by fatih** [comment]
Hi @svanharmelen 

I've compiled YCM probably 3-4 months ago and didn't touch it from that day. It's still work without problems. I remember YCM changing the completer (which doesn't use gocode at all and does all the heavy lifting). So if that is the case YCM is incompatible with the current vim-version. I need to test the auto completion with the latest version of YCM to give more insight.

**Comment by svanharmelen** [comment]
@fatih thanks for your response! It looks to me, that if you compile YCM without `--gocode-completer` it will follow the expected path (YCM -> omni-completer -> vim-go -> gocode), but compiled with `--gocode-completer` it will do the completion by itself (YCM -> gocode). See here for the code that goes along with it: https://github.com/Valloric/ycmd/pull/106

But no worries, I'll give neocomplete a spin in the mean time as it seems to already provide the autocompletion of function prototypes (what we talked about on Twitter) out of the box, so that saves me some time and effort :wink:

Thx!
