### ISSUE TITLE
vim-go can't run GoRun inside neovim

### ISSUE THREAD

**Issue by 7belrhalmia** [fatih/vim-go#536]
![gifrecord_2015-09-12_191250](https://cloud.githubusercontent.com/assets/13202562/9833441/3e3c5f42-598f-11e5-87a0-2f3ac51150b0.gif)

**Comment by fatih** [comment]
Hi @7belrhalmia 

Thanks for the bug report but I don't support neovim yet. You are free to use it with neovim, but until We (or I) decide that vim-go should have first class support for neovim I don't fix or debug any neovim related issues. I have many other things to do in my life, and supporting neovim is not something I want to put on the list.

**Comment by 7belrhalmia** [comment]
@fatih  ok i will make a fork that support neovim bye
