### ISSUE TITLE
Jump to definition

### ISSUE THREAD

**Issue by op** [fatih/vim-go#541]
With `gd` I'm able to jump to the definition and it's awesome. I'm used to use `]`, `CTRL-W_]` etc when working in C. Would it make sense to instruct vim to behave similar with Go and also eg `]` as `gd` etc?

**Comment by fatih** [comment]
Hi @op 

You can do it yourself very easily :) We have already mappings, so just create your own custom mappings. For example the following example is from the README:

```
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
```

We also have `<Plug>(go-def)` which opens it in the current window. So just assign your custom mapping for it.

**Comment by fatih** [comment]
Btw if you think there is a bug, we can reopen the issue and discuss it.
