### ISSUE TITLE
Add @Spell to goStringGroup

### ISSUE THREAD

**Issue by mmlb** [fatih/vim-go#543]
I'd like to have spell check within strings and have added 
```patch
diff --git a/syntax/go.vim b/syntax/go.vim
index 0c606ec..a0fcb03 100644
--- a/syntax/go.vim
+++ b/syntax/go.vim
@@ -144,7 +144,7 @@ hi def link     goSpecialString     Special
 hi def link     goEscapeError       Error
 
 " Strings and their contents
-syn cluster     goStringGroup       contains=goEscapeOctal,goEscapeC,goEscapeX,goEscapeU,goEscapeBigU,goEscapeError
+syn cluster     goStringGroup       contains=goEscapeOctal,goEscapeC,goEscapeX,goEscapeU,goEscapeBigU,goEscapeError,@Spell
 syn region      goString            start=+"+ skip=+\\\\\|\\"+ end=+"+ contains=@goStringGroup
 syn region      goRawString         start=+`+ end=+`+
 syn match       goFormatSpecifier   /%[-#0 +]*\%(\*\|\d\+\)\=\%(\.\%(\*\|\d\+\)\)*[vTtbcdoqxXUeEfgGsp]/ contained containedin=goString
```

which works. I would think this would be behind an option like `g:go_enable_string_spell` or something but do not know how to do so.

**Comment by fatih** [comment]
Hi @mmlb 

This looks like a nice idea. Is this also common for other languages? Do you think it could affect the performance? We have a lot of performance issues which is also the number one reason we put everything behind a flag.

**Comment by mmlb** [comment]
Hmm not sure what other languages enable it, I've seen C/C++ in the default syntax files w/o an option. I haven't seen much perf issues myself since I've enabled it.

I can do a quick search for the default syntax files to see how many enable and if any gate it behind a switch.

**Comment by fatih** [comment]
Sounds good, please open a PR with a flag that can disable/enable it. By default it should be disabled though (just like the others). Thanks again, I think this is a very nice detail :+1:

**Comment by mmlb** [comment]
Sure thing, PR coming.

I looked through a bunch of vim provided syntax files and about 37% define`@Spell` for strings. I looked though a-j and all of those had them on by default, I assume the reasoning is that `set spell` is option enough. I think having on by default matches best with the majority of syntax files, but will do otherwise if you want.
