### ISSUE TITLE
write is really slow in large projects

### ISSUE THREAD

**Issue by maerlyn5** [fatih/vim-go#544]
My go project is rather beefy and vim-go has gotten consistently slower and slower when trying to save a file as the project has grown. Is there a way to disable whatever vim-go is doing automatically on save? I'v tried disabling gofmt but that doesn't seem to have a noticeable impact on save time.

vim-go is amazing, thanks!

**Comment by nowk** [comment]
You might want to check out this issue https://github.com/fatih/vim-go/issues/144.

**Comment by maerlyn5** [comment]
Syntastic was 100% my problem! Thanks!

To disable auto syntax check on write, and add an explicit shortcut (Ctr-w E), add to vimrc
```
let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }
nnoremap <C-w>E :SyntasticCheck<CR> :SyntasticToggleMode<CR>
```
taken from:
http://stackoverflow.com/questions/20030603/vim-syntastic-how-to-disable-the-checker
