### ISSUE TITLE
gocode autocompletion not working with GB?

### ISSUE THREAD

**Issue by alaska** [fatih/vim-go#545]
I cannot seem to get gocode autocompletion working with GB, but perhaps I'm just not doing it right?  I have a GB project set up, and when I edit `bin/mybin/main.go` I see that gocode gets started.  And when I do `:GoPath` I get `<project_root>:<project_root>/vendor/:$GOPATH`, which looks good, but I'm not getting any autocompletion.

I know that gocode now supports GB compatibility (https://github.com/nsf/gocode/commit/85c63bdec7cd2dc6531cf2cb52d243a914ce6744) via `gocode set package-lookup-mode gb`. Is this an issue of setting this value while editing inside a gb project?

Also, side note, gocode still seems to be running when I exit Vim. Is this expected behavior?

**Comment by fatih** [comment]
Hi @alaska . You need to install all pkg's first (`gb install all`) (this is how gocode works). Also completion is not something I support right now %100 for GB, I'm still not done with it. People say it works for some, but for some it doesn't. Until I've implemented and tested it for %100 I'm not supporting it. Please have a look at the GB issue for recent changes (https://github.com/fatih/vim-go/pull/420). Thanks
