### ISSUE TITLE
vim-go breaks jumping back to last known cursor position when reopen tab

### ISSUE THREAD

**Issue by zyndiecate** [fatih/vim-go#548]
I just want to drop this issue. Sorry it is not a detailed description. Once I found the following snippet and learned to love it. 
```vim
" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif
" Remember info about open buffers on close
set viminfo^=%
```

Every time you close a tab (or buffer?) the last known cursor position was remembered. I never checked how that worked. It just worked. Since I am using `vim-go` it doesn't work anymore. Maybe somebody can enlighten me. Thanks.

**Comment by fatih** [comment]
Hi @zyndiecate 

I didn't get your question. Can you please describe with a detailed test case what's wrong? For a normal buffer, if I hit save and hit `'` it works fine without any problem.

**Comment by fatih** [comment]
Closing as I didn't get a response for 1.5 months. Please feel free to reopen in a new issue with a test case included.
