### ISSUE TITLE
GoTest - undefined: testing.M

### ISSUE THREAD

**Issue by davidbanham** [fatih/vim-go#549]
GoTest seems to choke on any usage of https://golang.org/pkg/testing/#hdr-Main

Running `go test` passes just fine, but `:GoTest` results in:

```
destiny_test.go|25| undefined: testing.M
```

Line 25 in destiny_test.go is:

```
func TestMain(m *testing.M) {
```

**Comment by fatih** [comment]
Hi @davidbanham 

I've just tested it with the following test files and it works perfectly fine for me:

demo.go:

```
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

demo_test.go:

```
package main

import (
	"flag"
	"fmt"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	flag.Parse()
	os.Exit(m.Run())
}

func TestExample(t *testing.T) {
	fmt.Println("Test is passing")
}
```

Can you provide a detailed test case so I can reproduce it?

**Comment by davidbanham** [comment]
Hi Fatih,

Thanks for doing the repro. I really should have included one in my bug report.

That same repro fails for me. I've put it in source control [here](https://github.com/davidbanham/vim-go-repro) just to rule out me copy+pasting it wrong as a cause.

I am using neovim rather than vim. I can't imagine that would be the cause, but I'm not sure where else to start looking for reasons that your machine is working and mine isn't.

Is there any other data or environment information I can give you to help track it down?

**Comment by margaery** [comment]
The testing.M type was added in Go 1.4. OP is not using the same version of Go for :GoTest and 'go test'.

**Comment by fatih** [comment]
Good point @margaery, never thought about it :) I've assumed that @davidbanham is already using 1.5.

**Comment by fatih** [comment]
Closing this as I didn't receive any response in two weeks.
