### ISSUE TITLE
Support golang 1.5 experimental vendoring in gopath

### ISSUE THREAD

**Issue by cjellick** [fatih/vim-go#551]
In golang 1.5, you can turn on experimental vendoring support. This results in the following structure:

* project root
  * my-package-1
  * vendor
    * github.com
      * foo-org
        * foo-repo

Can this structure be supported when setting up gopath resolution?

**Comment by fatih** [comment]
Hi @cjellick 

Please look at https://github.com/golang/go/issues/12278. The tools needs to be refreshed.

**Comment by fatih** [comment]
Duplicate issue: https://github.com/fatih/vim-go/issues/525
