### ISSUE TITLE
GoInstallBinaries couldn't work in China.

### ISSUE THREAD

**Issue by IchiNiNiIchi** [fatih/vim-go#554]
Because some packages  needed to install require access to 'golang.org'  which is blocked by the GFW.
As I see golang.org also host the packages in the github.
Can you change the configure to fetch them from github?

**Comment by IchiNiNiIchi** [comment]
After I change the configure file locally, it doesn't work because some dependencies the packages need
are also in the 'golang.org'.
A workaround that works for me is to
```
git clone https://github.com/golang/tools.git golang.org/x/tools
```

**Comment by fatih** [comment]
Hi @IchiNiNiIchi 

I don't how to solve this issue for you, as this is not vim-go dependent: https://github.com/golang/go/issues/8870 I'm really sad not to provide any kind of fix for this. Changing it to Github would only introduce other problems, which you already have encountered. Just use a VPN or proxy just like the others, or do it with the manually approach. `:GoInstallBinaries` is just an helper method, not something you are calling always.

**Comment by holysoros** [comment]
For anybody who reach here: https://gist.github.com/holysoros/a3114f5d42007d0023e81398364919ba
