### ISSUE TITLE
gorename doesn't work in go1.5.1: thechar redeclared in this block

### ISSUE THREAD

**Issue by yunkai** [fatih/vim-go#555]
**vim-go version**: the latest master branch with commit id: 8e372df16b17b0356b4c844829154c4103889425

**Go version**: Go1.5.1

I tested it in both Mac OS and Linux, when I type `\e` to rename go variable, vim-go will get following error:

```
vim-go: /Users/yunkai/git/go1.5.1/src/runtime/arch1_arm64.go:8:2: thechar redeclared in this block
```

**Comment by yunkai** [comment]
I found the root cause: my `gorename` is too old.

By updating `go/src/golang.org/x/tools/` project can fix it.

**Comment by divan** [comment]
Hit the same issue. As yunkai commented, updating by this command helps:

    go get -u -v golang.org/x/tools/cmd/gorename
