### ISSUE TITLE
Println syntax highlight not working

### ISSUE THREAD

**Issue by rkulla** [fatih/vim-go#556]
The capitalized version of Println doesn't highlight. This could trip up a lot of newbies trying to do the Golang tutorial and getting syntax errors when they fmt.println (which does highlight) and then run `go install`.

A simple fix could just be to add the capital `Println` to `syn keyword     goBuiltins` in syntax/go.vim.

Thanks,

**Comment by fatih** [comment]
Can  you please a screenshot with a working version and non working version. We don't highlight `Println` at all. However there are settings to enable methods, so you can do it via that.

**Comment by rkulla** [comment]
Not Working (I'm using the `Solarized` colorscheme, btw)
![screen shot 2015-10-02 at 10 13 21 am](https://cloud.githubusercontent.com/assets/244283/10252719/459f54b0-68ee-11e5-95a2-8a822d9392d9.png)

Working:
![screen shot 2015-10-02 at 10 12 46 am](https://cloud.githubusercontent.com/assets/244283/10252718/459f0c3a-68ee-11e5-9ebc-e816df8b6fa4.png)

**Comment by rkulla** [comment]
If you accidentally typed `fmt.println` (lowercase) vim-go will highlight it by default:
![screen shot 2015-10-02 at 10 15 54 am](https://cloud.githubusercontent.com/assets/244283/10252812/b3314b46-68ee-11e5-9168-10d08e939d16.png)

**Comment by fatih** [comment]
Enable it with please
```
let g:go_highlight_methods = 1`
```

`println` is a keyword, that's why it highlighted. Otherwise `Println` is a method of the package `fmt`. So if you add the setting above, it's get highlighted. Thanks for opening the PR :)

**Comment by rkulla** [comment]
I see, yeah that works. I guess it's just confusing that `fmt.println` still highlights but at least it's not the same color as method highlighting.  Thanks.
