### ISSUE TITLE
Saving take long time if using db driver

### ISSUE THREAD

**Issue by Chipsterjulien** [fatih/vim-go#560]
Hello
It took long to find out where the problem was. Everything is in the title.
if i use database/sql in my code, saving file or project take ~20s and use 100% of CPU

i tested with postgresql: http://sprunge.us/FUZb?go
It's the same with sqlite3: http://sprunge.us/OTSi?go

Best regards

**Comment by fatih** [comment]
Hi @Chipsterjulien. Please use `gofmt`. It seems you have a very large GOPATH and it slows down GoImport. Other than this there is nothing vim-go does which would cause a 20 second. It's code agnostic and all is does is invoking `gofmt`, `goimports` ... Do you use plugins like vim-syntastic?

**Comment by Chipsterjulien** [comment]
I use vim-syntastic for others languages
If i disable it, it's done but it's not a good solution for me

Thx for your quick reply

**Comment by fatih** [comment]
You can disable it for just Go. Please read the documentation for that.

**Comment by Chipsterjulien** [comment]
I seek but what I've done so far is not working

**Comment by WnP** [comment]
@Chipsterjulien use:
```viml
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
```

**Comment by Chipsterjulien** [comment]
Thx for your help

**Comment by Chipsterjulien** [comment]
The good option is: let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
