### ISSUE TITLE
GoBuild fails with dispatch enabled

### ISSUE THREAD

**Issue by philk** [fatih/vim-go#562]
I just added vim-dispatch for `GoBuild` and started seeing this error:

```
|| go install command-line-arguments: build output "/dev/null" already exists and is not an object file
```

Looks like it's actually a `go build` problem that came back in 1.5. And this isn't the only project affected:
https://github.com/scrooloose/syntastic/issues/1436
https://github.com/golang/go/issues/4851

I'm particularly happy with the anger expressed in [this commit](https://github.com/flycheck/flycheck/commit/2ed732837ed1963ab5d838449a555e0bf3991b5f) :smile: 

Changing the build command [here](https://github.com/fatih/vim-go/blob/master/autoload/go/cmd.vim#L27) to just be `go build . errors` the same as above seems to have worked fine but I have no idea what the vimscript above that means or why, so that's probably not a real fix (I assume that code's there for a reason...)

**Comment by fatih** [comment]
Hi @philk 

Yeah I've just discovered it later when I was using a Terminal instead of MacVim. It's really annoying. I'll fix it in 1-2 days. Thanks for opening the issue :+1:

**Comment by fatih** [comment]
@philk can you test it please with: https://github.com/fatih/vim-go/pull/567 ?

**Comment by philk** [comment]
:+1: working for me, thanks!

**Comment by fatih** [comment]
Awesome, I'll use my fix for a couple of days and merge once I feel it's safe to use.
