### ISSUE TITLE
vim hangs during tests

### ISSUE THREAD

**Issue by shazow** [fatih/vim-go#563]
By default, `go test` times out after 10 minutes. If you have a concurrency bug, it's likely your tests will stall until the timeout.

As far as I can tell, it's impossible to kill the test process from inside of vim, as the full interface is completely blocked until the test process is done. I can kill it from another terminal, then things are fine.

The ideal solution would be to support neovim's concurrent jobs (maybe by utilizing [Neomake](https://github.com/benekastah/neomake) when available, see also https://github.com/fatih/vim-go/issues/375#issuecomment-117668942).

As a short-term workaround, making it easier to set the default timeout for go-test to something smaller would be convenient too. (Any suggestions for what that might look like?)

**Comment by fatih** [comment]
Hi @shazow 

I totally agree, this is also the reason I'm executing some tests outside Vim :/ 

Also the reason I'm still not using neovim and the whole packages around it is because of having limited time to support multiple vim versions. It would just to much for me as a single person.

For the timeout, I think it should be just 30 seconds but with a configurable setting, such as `g:go_test_timeout = 30s`.  If it times out we'll display an error: `vim-go: test timed out after 30 seconds. Timeout can be configured with g:go_test_timeout`. Thoughts ?

**Comment by shazow** [comment]
> Also the reason I'm still not using neovim and the whole packages around it is because of having limited time to support multiple vim versions. It would just to much for me as a single person.

Absolutely, I totally understand. Have you had a chance to look at Neomake at all? I think that would make a backwards-compatible partial transition (at least for testing/building) really easy. If that looks like a good fit for you, I can try to put something together for us to experiment with.

> For the timeout, I think it should be just 30 seconds but with a configurable setting, such as g:go_test_timeout = 30s. If it times out we'll display an error: vim-go: test timed out after 30 seconds. Timeout can be configured with g:go_test_timeout. Thoughts ?

Hmm, how about adding a `go-test-short` call which runs `go test -short -timeout $go_test_timeout` and set that to 10s by default? This will let you filter your tests to only the short ones, and have a proportionally short timeout. 30s is still a long time for the UI to completely hang.

**Comment by fatih** [comment]
> Absolutely, I totally understand. Have you had a chance to look at Neomake at all? I think that would make a backwards-compatible partial transition (at least for testing/building) really easy. If that looks like a good fit for you, I can try to put something together for us to experiment with.

I couldn't look at it, but we support for example vim-dispatch with a setting. I'm totally ok to add support for NeoMake too with settings like `g:go_enable_neomake = 1`, which would be disabled by default, but neovim users could make use of it.

> Hmm, how about adding a go-test-short call which runs go test -short -timeout $go_test_timeout and set that to 10s by default? This will let you filter your tests to only the short ones, and have a proportionally short timeout. 30s is still a long time for the UI to completely hang.

Yeah, thinking now it makes more sense. But I think we should not introduce a new command. Just let us use :GoTest and enable the `-short` flag. Even though it seems like it's a breaking change, I don't think any vim users would be happy of a blocking VIM when they execute :GoTest. We also of course would introduce the timeout setting, which users can change.

**Comment by shazow** [comment]
Sounds good to me!

I'll try to find some time to fiddle with integrating Neomake. :)

**Comment by fatih** [comment]
Hi @shazow 

Checkout the PR #578. I've didn't add `-short` because I didn't want to change the behavior to much. Also the timeout is only available if no custom flags are passed via `:GoTest`. For example if you call it with `:GoTest -short -timeout=20s` we don't append anything to it.

**Comment by shazow** [comment]
:+1: Thanks! Makes sense.
