### ISSUE TITLE
Issue with filepath for error location 

### ISSUE THREAD

**Issue by harikb** [fatih/vim-go#569]
I see that vim-go is prepending $GOPATH/src even if the output of errorcheck is an absolute path (for the location of the error file). 

For example (I created a typo, just to show the issue) 

    $ errcheck bitbucket.org/yetanotherfella/tagged/server/tagserver
    /home/harry/code/src/bitbucket.org/yetanotherfella/tagged/server/tagserver/login.go:13:27: expected ';', found '{' (and 4 more errors)

Inside VIM, this shows up as             

    /home/harry/code/src//home/harry/code/src/bitbucket.org/yetanotherfella/tagged/server/tagserver/login.go|13 col 27| : expected ';', found '{' (and 4 more errors)

Now if the errorcheck outputs this way

     bitbucket.org/yetanotherfella/tagged/server/tagserver/common.go:27:10   w.Write(respJSON)
     bitbucket.org/yetanotherfella/tagged/server/tagserver/common.go:40:10   w.Write([]byte(msg))

It appears correctly inside the vim buffer. 

May be the wrappers needs to add $GOPATH  (/home/harry/code in my case) only if the output filename is relative? 

Am I missing some configuration directive?

**Comment by fatih** [comment]
Hi @harikb 

We recently introduce the fix https://github.com/fatih/vim-go/pull/564 and merged it into the master. Can you pull latest master and try again?

**Comment by harikb** [comment]
Sorry about the late response. I might have missed the email notification. Thank for you for quick response. The latest fix has solved my original problem. However, I do have an issue with the later example (it no longer works, although I do have a work around).  The later examples that prints relative path, but includes complete import path wouldn't work (makes sense though..) if I started vim from inside one of the subdirectories.

I realise it must be just a "cwd" problem. and this is longer an issue if I keep my "current directory" for vim as $GOPATH/src (and not CD in to my individual project's directory). I am OK with this setup. This was probably mentioned somewhere in the doc and I might have missed it. Thanks.  

Overall, I am very happy with this setup now. Thanks for the wonderful plugin.

**Comment by fatih** [comment]
Thanks for the response @harikb. I'm using a simple script which is automatically changing the cwd according to the file I'm working. It makes it easy to open and edit files. I'm closing this, feel free to open again if you hit problems.
