### ISSUE TITLE
GoDoc finds no doc when accessing packages imported under a specific name

### ISSUE THREAD

**Issue by piersy** [fatih/vim-go#574]
Running GoDoc on some identifier being accessed via a named package does not find any doc 

Eg running GoDoc on DecodeImage below

    import i "image"
    i.DecodeConfig(bytes.NewBuffer(contents))

Results in

    No documentation found for "i" .

If the import does not name the package go doc works fine.

**Comment by fatih** [comment]
H @piersy 

I'm aware of this problem. Check https://github.com/fatih/vim-go/issues/465 and https://github.com/fatih/vim-go/issues/332. Closing due duplicate issues.
