### ISSUE TITLE
gometalinter quickfix paths not usable for subdirectories

### ISSUE THREAD

**Issue by tmc** [fatih/vim-go#579]
```sh
vim monitor/monitor.go
```

`:GoLint` output:
```
monitor/monitor.go|10 col 6| exported type GetConfiger should have comment or be unexported
```

:GoMetaLinter output:
```
monitor.go|10 col 6 warning| exported type GetConfiger should have comment or be unexported (golint)
```
The latter doesn't open the file in question.

**Comment by fatih** [comment]
It's because gometalinter runs on the directory of the current file. What happens if you add this line to your vimrc:

```
autocmd BufEnter * silent! lcd %:p:h
```

This will automatically cd yo to the file you're editing.

**Comment by fatih** [comment]
Ping

**Comment by fatih** [comment]
Closing this as I didn't get an response. Feel free to open again with a more detailed informations. Thanks.
