### ISSUE TITLE
Another "Not an editor command"

### ISSUE THREAD

**Issue by achanda** [fatih/vim-go#581]
I hate to open another issue that is similar to the ones already reported, but hear me out please. I am using Vundle to install vim-go. My .vimrc looks like:
```
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=$GOROOT/misc/vim
filetype plugin indent on
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/syntastic'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'elzr/vim-json'
Plugin 'rust-lang/rust.vim'
Plugin 'rking/ag.vim'
Plugin 'phildawes/racer'
Plugin 'fatih/vim-go'
call vundle#end()
```
I can run all go commands fine and all of my other plugins work. `:scriptnames` shows the file is loaded
```
 33: ~/.vim/bundle/ag.vim/plugin/ag.vim
 34: ~/.vim/bundle/vim-go/plugin/go.vim
 35: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 36: /usr/share/vim/vim74/plugin/gzip.vim
```
Am I missing something?

**Comment by paulodiniz** [comment]
:+1: Having the same problem on OSX Yosemite using vundle

**Comment by achanda** [comment]
I'm using El Capitan with bash

**Comment by paulodiniz** [comment]
As @jonathanwgoodwin pointed out on https://github.com/fatih/vim-go/issues/69 , putting `filetype off` before vundle on my vimrc worked

**Comment by achanda** [comment]
I do have filetype off before vundle. Not sure why it's not working for me.

**Comment by fatih** [comment]
Hi @achanda. This is a plugin problem, not a vim-go. Please try with `pathogen` or `plug` and report back. Sorry but there is not much I can do. Thanks.
