### ISSUE TITLE
Question: run gometalinter on only the current file

### ISSUE THREAD

**Issue by trotha01** [fatih/vim-go#586]
Is there a way to run gometalinter on only the current file?

I tried ```:GoMetaLinter %```, but that still gives errors for all the files.

The use case is for working on a large code base with lots of errors, but I would like to only look at them one file at a time.

**Comment by fatih** [comment]
I've just tested it and it works for only one file when I pass the `%`. Can you please add a test case (example code) and explain how to produce it (expected result).

**Comment by trotha01** [comment]
main.go
```
package main

import "fmt"

func main() {
	fmt.Println("hello")
}
```

helper.go
```
package main

func helper() {
}
```

Open main.go in vim
Run ```:GoMetalinter %```
And you will see a warning:
```
helper.go|3 col 1 warning| helper is unused (deadcode)
```

**Comment by fatih** [comment]
This is fixed with latest master. Can you please pull and test it?

**Comment by trotha01** [comment]
I'm getting this with the latest:
``` || gometalinter: error: unknown long flag '--disable-all', try --help```

**Comment by fatih** [comment]
It's because you binary is old. Update it please.

**Comment by trotha01** [comment]
Okay, I updated gometalinter as well as it's dependencies.

So now I can't get :GoMetalinter to report any problems.

The command line gometalinter is working as expected though.

**Comment by fatih** [comment]
> So now I can't get :GoMetalinter to report any problems.

Well you said that already, didn't you?:

> If you run gometalinter main.go from the command line, there is no output. 

So that is indented, because you only pick the current file, and in main.go there is no dead code.. If you just call :GoMetaLinter it'll take the current directory. I mark this as resolved. Thanks
