### ISSUE TITLE
C syntax highlighting inside of `import "C"`

### ISSUE THREAD

**Issue by chrisnc** [fatih/vim-go#591]
I have a commit here which is a first pass at this. If you don't do anything weird it basically works, but it'd be nice to have someone more knowledgeable with Vim syntax plugins take a look. I don't think it's ready yet.

https://github.com/chrisnc/vim-go/commit/623c25e21bf07c3eb29872638e8fbf6cadcc8d02

**Comment by fatih** [comment]
Hi @chrisnc.

This is a big contribution. I'm not using cgo, but I've just announced it from twitter. Hope it catches some cgo users!

**Comment by fatih** [comment]
Hi @chrisnc. I'm closing this, as there will be a PR for this feature once you decide to contribute back. Thanks.

**Comment by chrisnc** [comment]
Okay, sounds good. I'll let you know when I have time to polish it and make it robust enough to use. I have had it enabled for a while now but I don't do enough in cgo these days to really test it a lot.
