### ISSUE TITLE
fileformat changed by GoFmt

### ISSUE THREAD

**Issue by cochran-at-niche** [fatih/vim-go#595]
I am running gvim on windows 7. When I open a new .go file, I can run the following vim command in order to check the file format:

`:set ff?`

The result is: `fileformat=dos`, which I was I expect, and what I want.

If I then run the GoFmt command, like so:

`:GoFmt`

And again check the fileformat, it now returns `fileformat=unix`, which is undesirable. Furthermore, all of my line endings have changed from crlf to lf, which I do not want (git keeps complaining to me about it).

If I run `:verbose set ff?`, it tells me that the fileformat was `Last set from ~\vimfiles\bundle\vim-go\autoload\go\fmt.go`

If I revert that file (fmt.go) to a version prior to this commit: 01578fd8632870f8285266b93c1e219df19c4002 the problem does not occur. Hence, I believe that the problem was introduced in that commit.

I should also note that I am using goimports for my GoFmt command, as established by this line in my vimrc:

`let g:go_fmt_command = "goimports"`

**Comment by wingyplus** [comment]
I think it changed by `gofmt` not vim-go itself (see https://github.com/golang/go/issues/3961 for more details).

**Comment by cochran-at-niche** [comment]
@wingyplus Then how is the "fileformat" variable, which belongs to vim, getting changed from "dos" to "unix"? If GoFmt is responsible, it should have no effect on the vim variable. Furthermore, when I revert the fmt.go file (ONLY that file), it fixes the problem - how is that explained?

**Comment by cochran-at-niche** [comment]
I think you're correct. The commit I referenced above introduced the use of gofmt's -w option, followed by reloading the current buffer. Since gofmt changes all my line endings to lf, when the current buffer is reloaded, it therefore detects the fileformat as unix.

I submitted a pull-request which fixes this issue: #615

**Comment by cochran-at-niche** [comment]
The pull-request was merged in, fixing the issue. This issue can be closed.
