### ISSUE TITLE
GoRename does not work if there are compile errors when building the current package

### ISSUE THREAD

**Issue by piersy** [fatih/vim-go#599]
I would expect gorename to be able to rename within certain scopes regardless of whether the whole package and its dependencies compile. For example in the scope of a function call.

At present I'm only able to use gorename if everything compiles. This makes re-factoring quite tiresome as you get stuck using poor names during the process and only when everything compiles can you go back and rename.

**Comment by fatih** [comment]
Hi @piersy 

Gorename is doing type based renamings and it also takes care of all packages inside GOPATH. This is how `gorename` was built in the first place. I don't think it can't be changed. Vim-go is just a wrapper so you have to open this issue to the official go/tools tracker. Thanks.
