### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by kriox26** [fatih/vim-go#609]
Hi, I've just installed `vim-go` and the commands seem to work fine, I've tried `:GoBuild` and `:GoFmt`. Both worked fine, but the `syntax highlighting` does not work. I tried with 4 different colorschemes, including the one that you recommend(`fatih/molokai`), and it's all the same.
![screen shot 2015-11-20 at 5 21 49 pm](https://cloud.githubusercontent.com/assets/8126891/11310893/3630fc7a-8fab-11e5-9206-a746f06b928c.png)

**Comment by fatih** [comment]
Hi @kriox26 . This is normal. Please read the documentations to enable more syntax options. Thanks.
