### ISSUE TITLE
vundle install of faith/vim-go asks for github username/password and later fails

### ISSUE THREAD

**Issue by aftnix** [fatih/vim-go#612]
I've tried both ways, Searched with `PluginSearch` and thus selecting `faith/vim-go` and later git cloned it in my bundle directory and initiated a `PluginInstall`. In both cases it asks for github username/password. I know it's not supposed to happen, but still i proceed with giving my username/password. But it fails with `Error processing` message.

**Comment by aftnix** [comment]
Nevermind, mistyped your name :D so the vundle was unable to find vim-go repo.

**Comment by fatih** [comment]
Good to know :)
