### ISSUE TITLE
vim-go writes two files on :w <new name>

### ISSUE THREAD

**Issue by k4rtik** [fatih/vim-go#619]
Whenever I try to reuse a .go file for writing to a new file (using `:w <newname>.go`), vim-go seems to be writing the contents of the buffer both in the old file and the new file. This is undesirable behavior.

I am using vim-go with all defaults and have looked at the doc for disabling this (autosave) behavior, but it doesn't seem to exist.

**Comment by fatih** [comment]
Hi @k4rtik 

You can disable it with:

```
let go_fmt_autosave = 0
```

**Comment by k4rtik** [comment]
Hi @fatih 

I do not want to disable running of `gofmt` (or `go fmt`), just that my old file should not be modified. Ideally, go fmt should be run only on the filename I specify in the vim `:w <filename>` command. I don't see a reason why it is run on the old file as well (triggering its undesired modification).
