### ISSUE TITLE
Cant Use :GoPath

### ISSUE THREAD

**Issue by beinnova** [fatih/vim-go#624]
Hi,
I can't use `:GoPath` for set my project path as gopath. When i try to use it i receive error message from vim.

**Comment by fatih** [comment]
Please give more information. Right now I'm clueless.

**Comment by beinnova** [comment]
Yes, sorry.
I try to set GOPATH inside vim. I have read in your documentation which for
do that I can write `:GoPath` and set gopath. But when I try to do that i
recive "GoPath is no a vim command". How I can send you more info?

2015-11-26 12:28 GMT+01:00 Fatih Arslan <notifications@github.com>:

> Please give more information. Right now I'm clueless.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fatih/vim-go/issues/624#issuecomment-159889728>.
>



-- 
*Be**innova* di *Giorgio Cerruti*
*WebSites | IT consultant | Web Developer*
*Phone: +39 340/87.68.326 :: Skype: beinnova*
*P.IVA: 10755560017*
*Visit Beinnova <http://www.beinnova.it> Site*

   - Giorgio Cerruti
   <http://it.linkedin.com/pub/giorgio-cerruti/31/422/852/>

**Comment by fatih** [comment]
It seems your're vim-go setup is broken and not installed correctly. This is not a vim-go error you're saying, it's indicating that it's not installed correctly.
