### ISSUE TITLE
go oracle has no flag "-tags"

### ISSUE THREAD

**Issue by chausat** [fatih/vim-go#625]
the "-tags" flag provided but not defined.
Run 'oracle -help' for more information.

![20151126200736](https://cloud.githubusercontent.com/assets/7158763/11422784/b2292faa-9479-11e5-81b0-d8cc3d68b7bb.png)

![20151126200851](https://cloud.githubusercontent.com/assets/7158763/11422785/ba2c8134-9479-11e5-9428-0f58ffe0bd36.png)

![20151126201156](https://cloud.githubusercontent.com/assets/7158763/11422816/ff6416d6-9479-11e5-80c0-ea34d968363a.jpg)

**Comment by fatih** [comment]
Update your oracle binary please. Thanks.

**Comment by riobard** [comment]
@fatih latest oracle binary still does not have the -tags flag. Is there anything wrong?

**Comment by jonaz** [comment]
I have the same issue. -tags is no longer available in oracle.

**Comment by fatih** [comment]
It has: https://github.com/golang/tools/blob/master/cmd/oracle/main.go#L42 

Please update your Oracle binaries, there is not much I can do here.

**Comment by jonaz** [comment]
Strange. I had to rm -rf $GOPATH/src/golang.org and go get it again. 
:GoUpdateBinaries or go get -u did not manage to update it.

**Comment by riobard** [comment]
@jonaz Thanks for the tip! Yeah, this is really strange. `$GOPATH/src/golang.org` does not seem to be under any version control. Not sure if that's why `go get -u` failed to update it. 

@fatih I guess it'll be useful to point the above gotcha somewhere so people know how to deal with it.
