### ISSUE TITLE
:GoRename error - vim-go: gorename: -to "0": not a valid identifier

### ISSUE THREAD

**Issue by nerdyworm** [fatih/vim-go#627]
This seems to be the start of the problems for me: https://github.com/fatih/vim-go/pull/577

If there is any additional information I can provide to help fix this please let me know.  Or if you can point me in the right direction then even better :D

**Comment by fatih** [comment]
Hi @nerdyworm. I don't think that you're given commit id is the root cause here.

Can you please provide more info about what's going on here? Please provide a reproducible test case.

**Comment by nerdyworm** [comment]
Typing :GoRename<CR> with my cursor on an identifier it spits out the error message.
Typing :GoRename newName<CR> also spits out the same error.

If I run the command definition of the previous version everything seems to function correctly
```command! -nargs=? GoRename call go#rename#Rename(<f-args>)```

however when I use the most recent version, the error occurs.
```command! -nargs=? GoRename call go#rename#Rename(<bang>0,<f-args>)```

**Comment by fatih** [comment]
This is really weird. I'm using the latest master and it works fine. Are you sure you updated all your files?

**Comment by nerdyworm** [comment]
I'm certain that all the plugin's files are updated correctly.

Here's what I'm going to do.  I'm going to close this issue and just assume it's my local area that is broken and not the wonderful plugin :)  If I find something I'll add another comment or send a PR.

If other people have this same issue they should chime in.  Until then we can assume it's my vim issue, which is extremely likely.

Thanks.  I really appreciate all your hard work on this project.

**Comment by fatih** [comment]
@nerdyworm sure :) Btw, I'm really open to resolve issues. But If I can't reproduce it, there is not much I can do. What you can do is compare the files, try to provide more cases and co. Thanks for using vim-go :)

**Comment by ernesto-jimenez** [comment]
@nerdyworm did you get this fixed? I've got the same problem :)

**Comment by nerdyworm** [comment]
@ernesto-jimenez I just shoved the following into my vimrc

    map ,rn :call go#rename#Rename()<cr>

(shrug)
