### ISSUE TITLE
incompatible on windows10

### ISSUE THREAD

**Issue by chausat** [fatih/vim-go#629]
when using :GoCallees, the error occured as follows:
![timline 20151127141218](https://cloud.githubusercontent.com/assets/7158763/11435111/6d6bee96-9511-11e5-9fe2-14a229955ab3.png)
![timline 20151127142146](https://cloud.githubusercontent.com/assets/7158763/11435192/5eda156e-9512-11e5-8239-4f107fdde5c6.png)

**Comment by fatih** [comment]
Can you give please a reproducible test case? How is your package laid out? What's your packages CWD?

**Comment by fatih** [comment]
Ping @chausat

**Comment by fatih** [comment]
Closing as I don't have any information and ways of testing it. Thanks.
