### ISSUE TITLE
Function names with suffixes that are builtins are highlighted incorrectly

### ISSUE THREAD

**Issue by cespare** [fatih/vim-go#633]
I think this is a recent-ish regression (I've only noticed it after a recent update).

Any function name that ends with a string that's a Go builtin is highlighted incorrectly:

<img width="273" alt="screen shot 2015-11-28 at 12 08 04 pm" src="https://cloud.githubusercontent.com/assets/318501/11453674/d9ebbc6a-95c8-11e5-8bc7-10866659a2ba.png">

**Comment by cespare** [comment]
Yeah, this is a regression caused by d52c1644aa0417a5ae613ee13a8b2358d32a1ba1.

/cc @mmlb

**Comment by fatih** [comment]
This is fixed with #628. Thanks @cespare for mentioning it.
