### ISSUE TITLE
auto completion doesn't show functions available after go1.5

### ISSUE THREAD

**Issue by browny** [fatih/vim-go#635]
I use `vim-go` and `YCM` plugins to do auto completion. My go version is `go version go1.5.1 darwin/amd64`. 

The problem is that auto completion doesn't show new function available after go1.5 (ex: https://golang.org/pkg/encoding/base64/#Encoding.WithPadding). I use **vim-plug** as plugin manager and I am sure I have updated all the plugin I installed.

How do I check which go version the auto completion binds to, or any suggestion for this issue?

Thanks

![screen shot 2015-11-30 at 4 47 42 pm](https://cloud.githubusercontent.com/assets/336427/11467306/1af29d7c-9782-11e5-9ce1-3aba5bec55a9.png)

**Comment by fatih** [comment]
This is [gocode](https://github.com/nsf/gocode) related. Please ask the question there, as vim-go is just  a wrapper. Thanks.
