### ISSUE TITLE
Error on GoInstallBinaries

### ISSUE THREAD

**Issue by 7belrhalmia** [fatih/vim-go#637]
vim-go: goimports not found. Installing golang.org/x/tools/cmd/goimports to folder /home/belr/Goprogram/bin     │# command-line-arguments
Error installing golang.org/x/tools/cmd/goimports: Fetching https://golang.org/x/tools/cmd/goimports?go-get=1   │➜  src                               
Parsing meta tags from https://golang.org/x/tools/cmd/goimports?go-get=1 (status code 200)                      │                                     
get "golang.org/x/tools/cmd/goimports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", R│                                     
epoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/goimports?go-get=1               │                                     
get "golang.org/x/tools/cmd/goimports": verifying non-authoritative meta tag                                    │                                     
Fetching https://golang.org/x/tools?go-get=1                                                                    │                                     
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)                                    │                                     
golang.org/x/tools (download)                                                                                   │                                     
# cd /home/belr/Goprogram/src/golang.org/x/tools; git pull --ff-only                                            │                                     
error: Your local changes to the following files would be overwritten by merge:                                 │                                     
        cmd/godex/gc.go                                                                                         │                                     
        cmd/godex/gccgo.go                                                                                      │                                     
        cmd/godex/godex.go                                                                                      │                                     
        cmd/godex/print.go                                                                                      │                                     
        cmd/godex/source.go                                                                                     │                                     
        cmd/godex/writetype.go                                                                                  │                                     
        cmd/godoc/handlers.go                                                                                   │                                     
        cmd/godoc/x.go                                                                                          │                                     
        cmd/oracle/main.go                                                                                      │                                     
        go/loader/loader.go                                                                                     │                                     
        go/pointer/gen.go                                                                                       │                                     
        go/pointer/testdata/maps.go                                                                             │                                     
        go/ssa/builder.go                                                                                       │                                     
        go/ssa/interp/external.go                                                                               │                                     
        go/ssa/interp/testdata/complit.go                                                                       │                                     
        go/ssa/testdata/valueforexpr.go                                                                         │                                     
        go/vcs/vcs.go                                                                                           │                                     
        godoc/godoc.go                                                                                          │                                     
        godoc/page.go                                                                                           │                                     
        godoc/proxy/proxy.go                                                                                    │                                     
        godoc/redirect/redirect.go                                                                              │                                     
        godoc/static/makestatic.go

**Comment by fatih** [comment]
Hi @7belrhalmia . Please try to run the `go get` commands from the terminal. This error is usually due the packages or the host network issues. It's not vim-go related. Thanks
