### ISSUE TITLE
Starting a new line with "o" doesn't automatically indent it.

### ISSUE THREAD

**Issue by PeterFillerman** [fatih/vim-go#641]
If you edit function, cursor is on the end of the line, and you press Enter - vim starts a new line, with all tabs.

If you stand anywhere in the line, and press "o" - vim starts a new line, no tabs, cursor on the left border of the window.

Not sure if that's expected, but it's a bit uncomfortable.

**Comment by fatih** [comment]
Hi @PeterFillerman 

Can you please give more information? I've tested it, and I can see that indents it with `o`. Did you set `autoindent`?

**Comment by PeterFillerman** [comment]
Just added autoindent, nothing changed.

I can only add that my version is

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May  4 2012 04:09:27)
Included patches: 1-429

and I remapped "o" to "h".

Don't want to annoy you with my full .vimrc, I'll try again after I'll update my vim to the last version.

**Comment by PeterFillerman** [comment]
OK, I just had to use CTRL-F in insert mode. This shortcut moves me to the correct indention level automatically, and this way empty lines stay empty.
