### ISSUE TITLE
Neovim performance

### ISSUE THREAD

**Issue by ChrisMcKenzie** [fatih/vim-go#642]
As far as i can tell right now on neovim the auto fmt feature for example still runs as a standard vim process (blocking the ui thread) is there a plan to move this to a neovim coprocess at some point. I think it would improve saving performance as it would not block the vim ui thread. 

Just a though.

**Comment by fatih** [comment]
@ChrisMcKenzie yeah, will do it in the #607 PR. Did you checked it already, I think your comment is based on that PR right?

**Comment by fatih** [comment]
Just thinking that formatting is already fast and we don't need to complicate the code there. Also having it blocking in way is ok, because we don't want to change the content during the formatting. Thanks @ChrisMcKenzie for the suggestion though :)
