### ISSUE TITLE
Find all usages of an import under cursor

### ISSUE THREAD

**Issue by PeterFillerman** [fatih/vim-go#644]
Is it possible to have it this way:

* My cursor is on the "io/ioutil"
* I type something like :GoReferrers
* I get a list of all things like ioutil.ReadDir, ioutil.ReadFile in the quickfix window

Maybe this is done already?

(And just to not ask in another issue, is there a way to find a main(), while I'm in the netrw in the package folder? How to go to an import folder by placing a cursor on it and pressing some keys?

**Comment by fatih** [comment]
Hi @PeterFillerman 

I'm not quite sure what you want. GoReferrers is for variable identifiers. I don't think it shows the public members of an imported package. Why do you need it?

**Comment by PeterFillerman** [comment]
@fatih I want not just all public members, but public members used in the opened file. With an ability to quickly jump between them with quickfix.

GoReferrers was just a bad example, please forget about it. Maybe it should be called something like :GoFindImportUsage.

I want it because, I think, it's the easiest way to quickly find out where the action is happening, without surfing through the rest of the code.

I'm fine if you wouldn't actually code this manually by hand, but maybe you know in which direction I should dig, at which programs I should look?

**Comment by fatih** [comment]
Ok there is an easy way. Please do the following (I'm using that way). 

* Install [ctrlp](https://github.com/ctrlpvim/ctrlp.vim) plugin for vim if you haven't it yet
* Add the following to your vimrc (you can configure ctrlp for you needs):

```viml
let g:ctrlp_buftag_types = {'go' : '--language-force=go --golang-types=ftv'}
```

* Create a `~/.ctags` file with the content:

```
--langdef=Go
--langmap=Go:.go
--regex-Go=/func([ \t]+\([^)]+\))?[ \t]+([a-zA-Z0-9_]+)/\2/f,func/
--regex-Go=/type[ \t]+([a-zA-Z_][a-zA-Z0-9_]+)/\1/t,type/
```

Now when you call `:CtrlPBufTag` it'll will list all identifiers and you can easily jump to it.

**Comment by PeterFillerman** [comment]
Yes, something like that! Let's see on concrete example.

In this file: https://github.com/rn2dy/sokoban-go/blob/master/render.go
I place the cursor on the import: "github.com/nsf/termbox-go"
Press some button
Magic happens
And I get this list:
* line 11, termbox.ColorBlack
* line 12, termbox.ColorWhite
* line 13, termbox.ColorBlack
* line 14, termbox.ColorBlue
* line 26, termbox.Attribute
* line 27, termbox.ColorWhite
* line 28, termbox.ColorYellow
* line 29, termbox.ColorRed
* line 30, termbox.ColorGreen
* line 34, termbox.ColorBlack
* line 63, termbox.Size()
* line 67, termbox.SetCell(x, y, ' ', debugConsoleColor, debugConsoleColor)
* line 92, termbox.Clear(backgroundColor, backgroundColor)
* line 110, termbox.SetCell(boardStartX+x*blockSize+k, boardStartY+y, ' ', cellColor, cellColor)
* line 123, termbox.SetCell(instructionStartX+k, instructionStartY+len(instructions)+j+1, ' ', tokenColor[intr.token], tokenColor[intr.token])
* line 128, termbox.Flush()
* line 131, termbox.Attribute
* line 133, termbox.SetCell(x, y, c, fg, bg)

...After typing all this, I realised that searching "termbox." works too... Except there is one annoying thing left: import string ends with "termbox-go", but the real package name is "termbox". It may confuse me in a more complex programs, if this happens. And there are probably no way to get the real name of a package from an import string, except going to the "termbox-go" folder and opening any file, and then looking for a string beginning from the word "package", which means it's not so easy to automate this task...

**Comment by fatih** [comment]
Unfortunately there is no way to get the public member of an import. You can use autocompletion `c-x c-o` on a defined indentifier, which will list it.
