### ISSUE TITLE
:let g:go_fmt_autosave = 0 doesn't work mid-session

### ISSUE THREAD

**Issue by daveyarwood** [fatih/vim-go#645]
Even after running `:let g:go_fmt_autosave = 0`, when I save a Go file, it formats it.

If I disable vim-go and restart Vim, when I save a Go file, it doesn't format it.

**Comment by daveyarwood** [comment]
It looks like maybe `let g:go_fmt_autosave = 0` only works if you include it in your vimrc. Running it as a command in the middle of a Vim session doesn't seem to disable automatic GoFmt on save.

**Comment by fatih** [comment]
@daveyarwood it's probably because of autoload. Please disable it and use `:GoFmt` whenever you want if you don't want autosave. Thanks.

**Comment by mpenkov** [comment]
I'm running into this issue as well. How can I disable autoload?

**Comment by mpenkov** [comment]
OK, I found that this:

```
let g:go_fmt_autosave = 0
let g:go_imports_autosave = 0
```

has the desired effect.
