### ISSUE TITLE
No gofmt errors in quickfix window

### ISSUE THREAD

**Issue by cespare** [fatih/vim-go#646]
Since the location list changes, I no longer get a quickfix window when there's a gofmt error on save. That was quite handy. How can I get it back?

I bisected and 8d2b81e50d6daf43f097779dd5eb4f1faf27c225 is the first commit where it stops working (I get a vim error on save at that commit) and after 056a91144b8d8f7407f3af5cffdc13db504ebfb1 there's no vim error but no quickfix window either.

**Comment by cespare** [comment]
Never mind -- the problem was that syntastic was somehow preventing the location list from working in vim-go, even though I'd configured syntastic to only run on certain filetypes (not go). Uninstalling syntastic fixed the problem.

**Comment by chehsunliu** [comment]
Your comment solved my problem! My VIM behaved differently on ArchLinux and Mac with the same `.vimrc`. Only the one on Mac displayed errors on the location list. I just removed all the customized options for syntactic and the problem was gone!!
