### ISSUE TITLE
Blank Identifier in import causes, slow write.

### ISSUE THREAD

**Issue by asmedrano** [fatih/vim-go#647]
Hi, 
I have an import that looks like this
```
import (
	"database/sql"
	"log"
	_ "github.com/mattn/go-sqlite3"
)
```

It seems to me like that blank identifer import is causing some strange behavior when goimports runs. 
It takes a while for vim to become responsive again after `:w`.

**Comment by asmedrano** [comment]
Actually I think its Syntastic exploding... anyone having any similar behavior?

**Comment by fatih** [comment]
Hi @asmedrano 

This is due goimports searching across $GOPATH. There is nothing vim-go can do here. Please use `gofmt`. Thanks
