### ISSUE TITLE
Add support for toggles of compiler flags (gcflags)

### ISSUE THREAD

**Issue by typeless** [fatih/vim-go#648]
The idea is to add two toggles named GoAsmListingEnable and GoParseTreeListingEnable, for example.

When any of them are set true, appending `-gcflags=-A` and `-gcflags=-W` respectively to the compiler commands, and then redirecting the outputs to dedicated vim buffers for examining.

I find this is helpful for developing insights about how Go turns my source code into raw materials under the hood.

**Comment by fatih** [comment]
Hi @typeless 

I think this is not something I would want to add to vim-go. It's to specific and only covers a certain percentage of vim-go's user base. I never used my self, so I wouldn't maintain something like that as every single feature is going to be more work for me in the future. Feel free to work on a PR if you want, but the possibility of merging something so niche is really low. Sorry :/ . Thanks for your comment.
