### ISSUE TITLE
:GoTest quickfix window hides multi-line outputs

### ISSUE THREAD

**Issue by shazow** [fatih/vim-go#650]
For bigger outputs, I like to have tests that output something like `t.Errorf("failed because some reason\n got: %q\nwant: %q", ...)`, this aligns the got/want nicely to see the diff for larger strings.

With the latest release, the quickfix errors window only shows one line per output. This is great for a quick view but it would be really nice if the lines could be unfolded into their full output.

I recall several other tools using folds in quickfix windows to allow for this, but I can't think of specific examples right now. Let me know if those would be helpful. :)

**Comment by fatih** [comment]
Hi @shazow 

We were already parsing them like that. Seems the `message` part needs to be revisited. Thanks for reporting.

Ps. I think we already parse for `build` or `run`. But not sure. I'm on it ;)

**Comment by shazow** [comment]
Excellent, yay! :custard:

**Comment by fatih** [comment]
@shazow This is now fixed. Please pull the latest master to get the update. Thanks again for reporting :+1:

**Comment by shazow** [comment]
Looking good, thank you!! :custard:
