### ISSUE TITLE
GoBuild fails when outside the source folder

### ISSUE THREAD

**Issue by groob** [fatih/vim-go#651]
After updating to the latest version, 0aeb07e9305f5696bfc1cffb1e3b2226d851b913, `GoBuild` does not seem to be working properly when called outside the directory where the file is in. 
The error I get with `nvim`
`vim-go: [run] Dropped "/incomplete/path/main.go" from location list (nonvalid filename)`
I tried opening the file with vim instead, and got a different error:
`package .: no buildable Go source files in /Users/groob/Desktop/example/src`
Here's a sample repo to reproduce:

```
example
└── src
    └── hello
        └── main.go

2 directories, 1 file
```

```Go
package main

import "fmt"

func main() {
	var unused string
	fmt.Println("Hello World")
}
```

It seems that everything between `$PWD` and filename is being dropped.

**Comment by svanharmelen** [comment]
Was just about to report the same problem... Having this issue as well.

**Comment by tmc** [comment]
99a3a5fec048f0dc8ef65d292e905579b7bcbf73 introduced this breaking change. FWIW this basically breaks my vim-go workflow so i've reverted to before it.

**Comment by mschenk42** [comment]
I'm also experiencing this issue since I've recently updated.  It appears that it's looking in the root directory and not the subdirectory it's contained within.

![screenshot of iterm2 12-17-15 5-42-26 pm](https://cloud.githubusercontent.com/assets/630550/11885700/ac49613a-a4e7-11e5-867b-642dbbcdaa81.png)

**Comment by fatih** [comment]
It seems it's due `cwd`. It was working for me always because I have this piece of code in my vimrc:

```
" Enter automatically into the files directory
autocmd BufEnter * silent! lcd %:p:h
```

Working on a fix.

**Comment by fatih** [comment]
Oh I think it's time to introduce some tests for vim-go, I think I'm now fixing the same issue the fourth time this year (well last year actually :))

**Comment by ironcladlou** [comment]
>Oh I think it's time to introduce some tests for vim-go, I think I'm now fixing the same issue the fourth time this year (well last year actually :))

I know how you feel... hang in there! Thanks for the hard work on this plugin.

**Comment by fatih** [comment]
Can anyone here please try https://github.com/fatih/vim-go/pull/677 It should work both with Vim and Neovim. It seems this problem exists for all instances of plain `make` usage. So :GoRun and co needs to be fixed too, but that's another issues case, just let me know if `:GoBuild` is working well or not :)

**Comment by mschenk42** [comment]
I tested the 'fix-build-error' branch and it worked correctly for me and I reconfirmed the same test will fail in the 'master" branch.

**Comment by fatih** [comment]
Thanks @mschenk42 for the feedback.
