### ISSUE TITLE
Add Neovim integration details both to doc.txt and README.md

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#652]

**Comment by shawnps** [comment]
+1 :) I am trying out neovim for the first time and I don't know what I'm doing.

**Comment by shawnps** [comment]
(and vim-go is the only thing I actually care about getting working)

**Comment by fatih** [comment]
@shawnps please check out the Issue #607, there you can find the necessary documentations for now. Actually there are not much to do, only if you want to change certain behaviors :)

**Comment by shawnps** [comment]
@fatih great, thanks! :+1:

**Comment by nhooyr** [comment]
@fatih should I have a separate section for just neovim options or should I include them throughout and label them explicitly as neovim only?

**Comment by fatih** [comment]
My ideas was put a section in Readme.md, with short explanation of `enhanced` versions of our features.  And after it populate each command in `docs/vim-go.txt` with a new paragraph, such as: 

"If NeoVim is being used, :GoBuild runs asynchronously and doesn't block the UI. Errors are populated inside the location list. We provide a new function ... which you can plug into your statusline ..."

**Comment by nhooyr** [comment]
@fatih it populates the quick fix list for me, not the location list?
