### ISSUE TITLE
New test command does not run code in nested packages

### ISSUE THREAD

**Issue by pcasaretto** [fatih/vim-go#653]
I opened vim at the root path: `/Users/pcasaretto/src/go/src/github.com/ResultadosDigitais/bliss`
Then opened https://github.com/ResultadosDigitais/bliss/blob/master/deployment/gist_output_test.go with `:e deployment/gist_output_test.go`.
Running go test with `go_term_enabled` set to 1 I get:

![screen shot 2015-12-09 at 12 47 12](https://cloud.githubusercontent.com/assets/817039/11688312/ffbe6782-9e72-11e5-92a0-87f9abcdc8df.png)

Notice the output says `Bliss test suite` which is the top level test suite.

When issuing the command `go test -v` in the deployment dir the output I get is:

![screen shot 2015-12-09 at 12 48 37](https://cloud.githubusercontent.com/assets/817039/11688344/305566ca-9e73-11e5-8b48-d0926efaf7f5.png)

**Comment by fatih** [comment]
The NeoVim integration executes `GoTest` inside the your current working directory. What happens if you put this into your vimrc and try again:

```
autocmd BufEnter * silent! lcd %:p:h
```

I think it'll be fixed automatically with the code above. I'm looking into making it the same as default `:GoTest` behavior.

**Comment by fatih** [comment]
This is fixed now @pcasaretto. Please pull latest master to get the update. Thanks for the report :+1:
