### ISSUE TITLE
Async work indicator

### ISSUE THREAD

**Issue by shazow** [fatih/vim-go#654]
The new neovim-enabled features are too fast!!

It's really hard to tell if anything is going on. Would be swell to have somekind of indicator to show that work is being done in the background.

Not sure how feasible it is to do this in a way that is compliant with everyone's layout settings, but maybe somekind of automagic [integration with airline](https://github.com/bling/vim-airline#seamless-integration)?

Also maybe this is better solved as a general job queue visualization rather than vim-go specific thing, worth debating.

(Related comment: https://github.com/fatih/vim-go/pull/607#issuecomment-163793656)

**Comment by fatih** [comment]
Hi @shazow 

Unfortunately I don't know anything that can be added automatically. I'm not in favor of modifying the statusline ourselves btw. However there is a new function called `go#jobcontrol#Statusline()` which is exactly for this. It returns the current job status and is meant to be used as a notification. Right now there are no ways to notify a user in an async way. Please use this function with airline, lightline or just manually. I'm closing this as this is already implemented. Please let me know if this doesn't solve this issue or is not sufficient and I'm happy to open it again :)

**Comment by shazow** [comment]
I think that's fair. :)
