### ISSUE TITLE
GoCallers/GoCallee: cannot find package "-1" in any of

### ISSUE THREAD

**Issue by al3xandru** [fatih/vim-go#656]
Using the latest vim/macvim and vim-go. When trying for the first time `GoCallers` and `GoCallee` I got this weird error:

```
vim-go: cannot find package "-1" in any of:
        /usr/local/Cellar/go/1.5.2/libexec/src/-1 (from $GOROOT)
        /Users/alex/Dropbox/workspace/golang/golang-driver/src/-1 (from $GOPATH)
        /Users/alex/Dropbox/workspace/golang/golang-driver/vendor/src/-1
        /Users/alex/workspace/golang/golang-driver/src/-1
        /Users/alex/.golang/src/-1
oracle: no initial packages were loaded
```

GOPATH is correct (well almost correct as there's no vendor dir). But there's definitely no -1. Any ideas?

**Comment by al3xandru** [comment]
I have found the following mappings which make me believe that's the origin of the -1.

```
nnoremap <silent> <Plug>(go-callees) :<C-u>call go#oracle#Callees(-1)<CR>
nnoremap <silent> <Plug>(go-callers) :<C-u>call go#oracle#Callers(-1)<CR>
```

**Comment by dav-** [comment]
I'm also experiencing this problem with `GoCallers` and `GoCallees`. 

    vim-go: cannot find package "-1" in any of:
            /usr/local/Cellar/go/1.5.2/libexec/src/-1 (from $GOROOT)
            /Users/derrick/****/****/api/Godeps/_workspace/src/-1 (from $GOPATH)
            /Users/derrick/gocode/src/-1
    oracle: no initial packages were loaded

**Comment by fatih** [comment]
Hi. Can you please provide a text snippet which describes your problem so I can describe it? If not there is not much I can do. It seems you're code is not under a valid GOPATH. This error comes when oracle can't find your source code under GOPATH.

**Comment by al3xandru** [comment]
GOPATH is correctly set as everything works (you can see it here https://github.com/al3xandru/golang-driver/tree/v2.). The only thing that stands up would be: GOPATH has 2 path components and I have vendoring enabled. I'll post a bit later the output of go env for full details.

**Comment by jHorovitz** [comment]
The -1 actually comes from https://github.com/fatih/vim-go/blob/9caa7fa7d43e29af5c616819c765691120b0abd5/autoload/go/package.vim#L66.

I ran into the same issue. I have link /home -> /mnt/home. The $GOPATH was specified as /home/... while the current directory as calculated by pwd is /mnt/home/.... Changing the $GOPATH to start with /mn/home fixed this. I hope this helps you, @al3xandru.

**Comment by al3xandru** [comment]
@jHorovitz thanks, but there are no symlinks in my GOPATH (as can be seen in the go env output). I'll check the code you linked to.

**Comment by al3xandru** [comment]
@jHorovitz after adding some echoms, I confirm that the issue is indeed related to a symlink present in `$GOPATH`. Once that gets dereferenced the error goes away. Thanks a lot!

I still think that this could be addressed by vim-go, but it's probably low priority.

**Comment by fatih** [comment]
@al3xandru please also have a look at this issue: https://github.com/fatih/vim-go/issues/221 It fails due the symlink problem.
