### ISSUE TITLE
"g:go_auto_type_info = 1" makes nvim super slow since today (?)

### ISSUE THREAD

**Issue by svanharmelen** [fatih/vim-go#660]
As of this morning nvim is extremely slow. I updated everything to make sure I got the latest and greatest but still everything I type or every command I type in and execute is so super slooow :disappointed: 

If I comment the line `g:go_auto_type_info = 1` all is well again. Strangely enough I didn't have any issues with this line before and I do like the feature. It would be great if this call (getting the type info) could be using nvim's async features instead of blocking the UI.

Can you confirm this problem/issue? And/or could you point me to any possible solutions?

Thanks!

**Comment by svanharmelen** [comment]
Additionally, it seems like the omnibus completion (using `vim-go`) is able a bit slower as it used to be...

**Comment by jrwren** [comment]
It does not seem to be just today. I switched to the 1.3 tag and still notice the behavior. The compile fork is taking a long time compiling source on packages with many dependencies.

**Comment by svanharmelen** [comment]
Check... Well I use `vim-go` together with `nvim` on a daily basis and I truly feel a big difference in the last few days (mainly today that is).

Not saying it's a change in `vim-go` itself that triggers this, but something in the tool chain seems to be changed for the worst...

**Comment by svanharmelen** [comment]
Just changed a few setting with the `gocode` daemon (mainly changed `autobuild` from `true` to `false`) and this seems to restore the usability for the best part. Still strange as I have that set to `true` for quite some time now.

**Comment by jrwren** [comment]
Maybe coincidental that I noticed slowness today and I had no idea why. My gocode was over a year old. Hopefully updating helps me with my speed.

**Comment by fatih** [comment]
I'm closing this as Neovim is second citizen right now. The slowness is probably due Neovims refactored code and due some third party regressions (such as YCM). I for example completely removed YCM as it was slow as hell. Thanks.
