### ISSUE TITLE
:GoTest! is jumping to first failure

### ISSUE THREAD

**Issue by wavded** [fatih/vim-go#661]
Running nvim and against current master.  Expect it not to jump but remain in the current buffer.

**Comment by fatih** [comment]
Hi @wavded. This is a bug, it's not implemente for neovim, only for vim. Thanks for mentioning it.

**Comment by fatih** [comment]
@wavded Please test https://github.com/fatih/vim-go/pull/679 and let me know how it works. I'm going to merge it by tomorrow. Thanks again for reporting :)

**Comment by fatih** [comment]
This is fixed with #679

**Comment by wavded** [comment]
Seems to work good, thx @fatih
