### ISSUE TITLE
Show function signature when filling its arguments

### ISSUE THREAD

**Issue by nothingelsematters7** [fatih/vim-go#663]
I like ```:GoInfo``` feature for functions using which I can view function arguments order with their types.

But when typed function name ```someFunction(``` with opening ```(``` I cannot view arguments anymore without returning in Normal-mode and going to function name. 

I would be great to have an option to see ```:GoInfo``` for used function when filling its argument list.

**Comment by kodek** [comment]
:+1:  I'd also love to see function signatures while in insert mode.

**Comment by shazow** [comment]
I think there's a way to do this using a preview window but that's not ideal. I've tried to get the completion hover to keep the signature while filling it out, but can't figure out the right approach to do that.

Alternatively, another solution might be to have a binding that fills out the signature as a snippet. That way it will appear inline as a reference but also remain overrideable and let you jump between fields to fill them in.

**Comment by fatih** [comment]
Hi everyone. Can you please try #685? It's far from perfect but at least it's helpful :) I'm thinking to add some docs and putting it behind a flag (maybe). Here is a sneak peak of it:

![](http://f.cl.ly/items/133V371j1d0G1V2z2V13/Screen%20Recording%202016-01-15%20at%2008.52%20PM.gif)

**Comment by Ch00k** [comment]
Is there a switch that I could use to disable this feature?

**Comment by jackielii** [comment]
https://github.com/Shougo/echodoc.vim

this plugin seems to work well, however I had to enable set cmdheight=2

**Comment by alwindoss** [comment]
@fatih this works perfectly for times when functions are simpler.
in cases like `binary.Write`, let's say I have used this to type until `binary.Write(buff, binary.B` at this point in an attempt to check what is available in `encoding/binary` package I press C-x C-o and then the function info displayed at the bottom disappears.
How do I make it appear again and make it stay?
