### ISSUE TITLE
Running :GoMetaLinter command doesn't open Location List (neovim)

### ISSUE THREAD

**Issue by nothingelsematters7** [fatih/vim-go#665]
It's because of conflict with Syntastic which uses Location list to show its output as vim-go.
I don't know how to resolve this, maybe I need to create the bug in Syntastic?
Set golang filetypes as passive for ```syntastic_mode_map``` doesn't help.

**Comment by fatih** [comment]
Hi @nothingelsematters7  If you remove syntastic, does it work? Is it because it conflicts with Syntastic?

**Comment by nothingelsematters7** [comment]
@fatih yes, it does work after removing Syntastic

**Comment by fatih** [comment]
@nothingelsematters7 there is much I can do here, as location list is associated with a window. If someone else tries to override it (which can be vim-go too) it causes conflicts. I'm going to provide an option to use quickfix in the future, but this is something I can't change for now. It's a problem of vim, not vim-go.
