### ISSUE TITLE
New binary tool: Interfacer

### ISSUE THREAD

**Issue by shazow** [fatih/vim-go#666]
Just stumbled on this one, looks really neat:

https://github.com/mvdan/interfacer

Worth keeping an eye on (feel free to close if premature to talk about).

**Comment by shazow** [comment]
One more:

https://github.com/rjeczalik/interfaces

**Comment by fatih** [comment]
What's the difference between https://github.com/josharian/impl and these ? Just curious :) We had a PR open to integrate https://github.com/rhysd/vim-go-impl into vim-go btw.

**Comment by shazow** [comment]
interfac_er_ is a linter, it suggests existing interfaces for types.

interfac_es is the reverse of impl, it generates an interface declaration from an existing type.

impl generates a type stub from an existing interface.

Getting crowded here, kinda wish some of these got merged (maybe interfacer into oracle for example)

**Comment by casimir** [comment]
@shazow note that interfacer can be available in vim-go through the `:GoMetalinter` command (see https://github.com/alecthomas/gometalinter/commit/2d14952aaa85b982a8186b33e9e9cdc54452d274 and https://github.com/alecthomas/gometalinter/commit/843d354946808db2965ea67323ad2a38a05c465a).
You just have to set `g:go_metalinter_enabled` accordingly.

**Comment by shazow** [comment]
@casimir Great point, thank you! I need to setup my metalinter.

**Comment by fatih** [comment]
Thanks all for the comment. I'm closing this in favor of #122. We have three tools about interfaces, which one can be included in gometalinter, the other can be used with `vim-go-impl` plugin and the other needs to have a new plugin interface. Please comment on #122 for any new news or contributions :)
