### ISSUE TITLE
combination of golang installed on win and vim cming from cygwin doesn't work properly with vim-go 

### ISSUE THREAD

**Issue by stachg** [fatih/vim-go#668]
In such situation GOPATH format is something like C:\path1\to\go;C:\path2\to\go but in vim, has('win32') etc are 0 and has('unix')/has('win32unix') are 1 which seem to confuse vim-go. For instance, running :GoUpdateBinaries writes to C/bin directory instead of C:\path1\to\go\bin. So it looks like GOPATH is parsed assuming unix syntax instead of windows.

**Comment by fatih** [comment]
Hi @sbdchd, how do you think we should solve this? I'm not using Windows and don't have a clear understanding of your problem. Never used cygwin too.

This is the code we use to detect if it's running under Windows or not. If it's Windows we'll change the Path separator from `/` to `\`:


```vim
" IsWin returns 1 if current OS is Windows or 0 otherwise
function! go#util#IsWin()
	let win = ['win16', 'win32', 'win64', 'win95']
	for w in win
		if (has(w))
			return 1
		endif
	endfor

	return 0
endfunction
```

**Comment by stachg** [comment]
Hi Fatih,

I normally use Linux and vim-go works great. I like the functionality very much. However, I sometimes need to use a windows tablet for golang development. This required installing golang on windows (it creates win style GOPATH) and cygwin to get Linux like environment (vim) on win (win is not my favorite dev env).

I actually tried to use let win = [&quot;win16&quot;, &quot;win32&quot;, &quot; win32unix&quot;, &quot;win64&quot;, &quot; win95&quot;] instead of the original code in util.vim but it didn&#39;t help. So I thought you might be doing additional checks somewhere else but I wasn&#39;t able to find it (I am not familiar with vim macro language). If you could give me a hint what else could I try and the best way to debug I could give it a try.

Thanks,
Stan

**Comment by fatih** [comment]
I don't have and don't use windows, so this option is a very small percentage of vim's userbase (plus when it's being used with cygwin. Please have a look at this issue: https://github.com/fatih/vim-go/issues/662, I think it's a duplicate. Until a Windows user comes and contributes a fix I can't do much. Thanks.

**Comment by stachg** [comment]
Hi Fatih,

I can try to fix it but I would need your help because I am not familiar with the code.

So far it looks like the problem comes from the fact that GOPATH is in windows format (backslashes, because go is installed on windows) and cygwin working with unix paths.

vim-go on cygwin go detects unix system and assumes &#39;/&#39; to be a path separator which causes problems with GOPATH which is windows style, i.e. &#39;\&#39; path separator. Changing GOPATH to unix style didn&#39;t work for me, golang expects windows style path. 

I think the solution would be to check win32unix which is generated by cygwin and use &#39;/&#39; separators except for GOPATH which uses &#39;\&#39;.

Any suggestions what would be the simplest way to do it?

BTW, you already seem to have windows support in vim-go code, how did you test it if you don&#39;t use windows and what vim version you assume is used in windows mode?

Thanks,
Stan

**Comment by fatih** [comment]
Hi @stachg,

Can you please use the web ui of Github? Right now you're email is not readable unfortunately and I have hard time to understand it :/ If you look at it from the webui You understand what I mean. Thanks.

**Comment by stachg** [comment]
Sorry about it. I didn't realize my phone's e-mail client was converting quotes. Here is a copy of my previous e-mail:

So far it looks like the problem comes from the fact that GOPATH is in windows format (backslashes, because go is installed on windows) and cygwin working with unix paths.

vim-go on cygwin go detects unix system and assumes "/" to be a path separator which causes problems with GOPATH which is windows style, i.e. "\" path separator. Changing GOPATH to unix style didn't work for me, golang expects windows style path.

I think the solution would be to check for win32unix which is generated by cygwin vim and use "/" separators except for GOPATH which uses "\". Any suggestions what would be the simplest way to do it? 

One more thought: checks for win32unix would probably be needed only in code which makes GOPATH processing and parse GOPATH windows instead of unix style if win32unix is true. Everything else could probably remain without change.

Please let me know what you think.
 
Thanks,
Stan

**Comment by fatih** [comment]
Hi @stachg 

We actually removed the way we would detect it: https://github.com/fatih/vim-go/pull/575

So that's win32unix is being detected as unix in cygwin. It's a little tricky and the function is being used by other helper functions. So is the only problem here :GoInstallBinaries? Because according to `575` the problem was solved already. Also how is the filesystem laid out for cygwin? I have really no idea. I can make it that the path seperator is returned as as `\` when it's in cygwin, but this contradicts with #575.

**Comment by stachg** [comment]
cygwin looks like linux so vim-go detection is fine. The problem is that there is no golang for cygwin and windows installation of golang needs to be used.  Installing golang on windows creates empty GOBIN and creates GOPATH in windows format. As a result vim-go GoInstallBinaries uses GOPATH but expects unix format which fails because path separator in unix is ':'. So instead of installing binaries to C:\path\to\go\bin for instance it will instal them to C/      For this problem I found a simple workaround which was to define g:go_bin_path in .vimc using unix/cygwin format. This solved GoInstallBinaries for me.

The other problem I had was that saving golang source file wouldn't automatically reformat the file and update the imports. Fortunately I was able find a solution for this one too. The solution that worked for me was replacing the following line in go#fmt#Format   (vim-go/autoload/go/fmt.vim)

let out = system(command . " " . l:tmpname)

with

if has('win32unix') || has('win64unix')
    let out = system(command . " " . '`cygpath -m ' . l:tmpname . '`')
else
    let out = system(command . " " . l:tmpname)
endif

where cygpath is a cygwin command which converts l:tmpname from linux path (/tmp/...  I think) to windows equivalent (something like C:/a/b/...)

Something similar would probably need to be done for other golang tools invocations. Better solution would probably be to have some kind of a wrapper around system command  and do path conversion in there if needed. system command however can take variable number of arguments so it may be not trivial. Maybe this would need to be done in some other place, I don't know.  

Thanks,
Stan

**Comment by sigmap** [comment]
add this to your `.bash_profile` 
```export GOROOT="C:/cygwin64/home/$USER/go"
export PATH=$PATH:$HOME/go/bin
export GOPATH="C:/cygwin64/home/$USER/code/gowork"
```
You might need to change `$USER` and adjust for x86 if you're not using x64.
Compiles will go to `$GOPATH/bin`
That should help.

[source](http://dimig.ga/2016/01/27/cygwin-go/)

**Comment by soniah** [comment]
For future readers: see https://github.com/golang/go/issues/23155 for how I solved this (in my comment).
