### ISSUE TITLE
Go1.6 Goimports Changes to Support Vendoring / GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by ereyes01** [fatih/vim-go#672]
I am eagerly anticipating the day when I can smoothly use vim-go with all the GO15VENDOREXPERIMENT bells and whistles. It's all almost there, and I'm so excited I can't sleep anymore! Well... I guess not that excited :-) ... but close enough!

I wanted to bring this CL to your attention because it might require changes to vim-go to work with goimports in Go 1.6: https://go-review.googlesource.com/#/c/17728/

They're still working on it, but this is probably worth keeping an eye on.

**Comment by fatih** [comment]
Thanks @ereyes01 I'm already aware of it. I'm closing this as there is not much I can do right now. Once it's ready I'll look if there are any changes needed.
