### ISSUE TITLE
Override the :A command to toggle between go implementation code and test code.

### ISSUE THREAD

**Issue by peterhellberg** [fatih/vim-go#684]
I’d like **vim-go** to have the functionality of https://github.com/benmills/vim-golang-alternate and possibly add support for optionally creating missing test files when toggling.

**Comment by fatih** [comment]
Thanks @peterhellberg for the suggestion. This is a nice feature we can add :+1:

**Comment by nhooyr** [comment]
@fatih Do we ask the author for permission or can we just take it and credit him?

**Comment by peterhellberg** [comment]
The only issue on that repo is a question about what license it should have… opened on 24 Jan 2014

I wouldn’t hold my breath for a reply from @benmills, but we should at least try to contact him.

**Comment by nhooyr** [comment]
Alright, whenever you feel is good I can create the PR.

**Comment by benmills** [comment]
Sounds good to me! Thanks for thinking of this @peterhellberg

**Comment by nhooyr** [comment]
Okie, i'll create a PR and stuff.

**Comment by nhooyr** [comment]
@peterhellberg do you really think we need an option to create the test file? don't you think it should be universally enabled?

**Comment by peterhellberg** [comment]
@nhooyr I’d be happy if the test file was automatically created.

It might be a good idea to be able to disable that feature using a `let`, what do you think?

**Comment by peterhellberg** [comment]
@nhooyr Are your code enabling the traditional commands :A :AV and :AS? (alternate, alternate vsplit and alternate split)

**Comment by nhooyr** [comment]
@peterhellberg oh I didn't know thats a thing. I just used :GoAlternate and a bunch of mappings. I can switch it to that no, problem.

**Comment by nhooyr** [comment]
It's just that the other mappings (GoRun) use the same setup I implemented instead of overriding :A. There is no GoRunVertical, you instead use the mapping <plug>(go-run-vertical). And it uses a variable to decide the default way you want it. I mean if you really think its necessary, its not that hard to just add over the current code, its like 3 lines.

**Comment by nhooyr** [comment]
You can also just add this to your .vimrc

```vim
augroup go
	autocmd!
	autocmd FilEtype go command! -bang A call go#alternate#Switch('edit<bang>')
	autocmd FilEtype go command! -bang AV call go#alternate#Switch('vsplit<bang>')
	autocmd FilEtype go command! -bang AS GoAlternate call go#alternate#Switch('split<bang>')
augroup END
```

**Comment by peterhellberg** [comment]
I’m just so used to using a.vim (and for vim-golang-alternate for go) for so many years now that :A and :AV is lodged in my muscle memory.

I can definitely change my .nvimrc if you want to keep the default command as GoAlternate.

**Comment by nhooyr** [comment]
@fatih lets wait and see what fatih thinks.

**Comment by peterhellberg** [comment]
I’m going to Vietnam tomorrow and will leave my laptop at home, will be back in Sweden in a month.

@nhooyr I’m happy with letting you and @fatih decide on how to best implement this feature.

**Comment by fatih** [comment]
I've made some comments to the PR #704 I think we shouldn't create a new file at all but it should be created if a bang `!` is passed. Such as `:GoAlternate!` , this would force to create the file. Let's discuss it in the PR.

**Comment by nhooyr** [comment]
@peterhellberg it was merged. here are the commands you need to put in your vimrc if you want your alternate commands to work.

augroup go
    autocmd!
    autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
    autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
    autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
augroup END

**Comment by fatih** [comment]
@nhooyr I've just added myself for `A`. I think we can add them to our `doc` as this is something used by many already. Mind opening a PR ;) ?

**Comment by fatih** [comment]
Closed as we have this feature now.

**Comment by nhooyr** [comment]
@fatih should I add this to the readme. It sounds like something more suited for it.

**Comment by fatih** [comment]
Readme is ok. But also add to the `doc`. The thing is README is getting long everytime we add a new feature and I don't want it to be very long. That's why I do a cleanup every 2-3 months. Vim users should look anything from the `doc` as that's is the place we should put.

**Comment by peterhellberg** [comment]
Thank you guys! I’ll update my config when I get back to Europe :)

**Comment by peterhellberg** [comment]
I’ve now updated my config and this feature works really well, but I get a `vim-go: PANIC PANIC PANIC` message when calling `:A!`

Is this the intended behavior?

**Comment by nhooyr** [comment]
No, I'll look into it.

**Comment by peterhellberg** [comment]
Note that it functions just fine, it is just an unexpected error message (possibly due to the created empty buffer not having a package line)

**Comment by nhooyr** [comment]
Yea I understood. I'm in class atm, i'll look into it at lunch.

**Comment by nhooyr** [comment]
So it only happens in empty files?

**Comment by peterhellberg** [comment]
@nhooyr Take your time, no stress :)

And yes, it only happens when an empty file/buffer is created.
Calling `:A!` on a file that has a corresponding test work just fine.

**Comment by nhooyr** [comment]
I'm not stressed, its my way of having fun :P 

alright thanks.

**Comment by nhooyr** [comment]
`PANIC PANIC PANIC` is what gocode returns if there is an error, do you have autocomplete?

**Comment by peterhellberg** [comment]
Yes, and I guess gocode is called when the buffer is switched.

Calling `:A` (with no trailing !) first shows the message `vim-go: couldn't find foo_test.go` and then after a few hundred ms `vim-go: PANIC PANIC PANIC`

**Comment by nhooyr** [comment]
I don't think that can be fixed then, its a harmless error message though.

**Comment by peterhellberg** [comment]
No, unless populating the buffer with `package <name>` :)

I think I found the underlying issue now, and it was that I have `let g:go_auto_type_info = 1` in my config.

**Comment by nhooyr** [comment]
ah yes, that calls gocode as well.

**Comment by nhooyr** [comment]
Maybe we shouldn't print the `PANIC PANIC PANIC` in that case?

**Comment by peterhellberg** [comment]
It might too much of an edge case to really care about?

**Comment by nhooyr** [comment]
I meant, ignore the `PANIC PANIC PANIC` if `g:go_auto_type_info = 1`

**Comment by peterhellberg** [comment]
Probably not, but @fatih maybe want to decide on this?

**Comment by nhooyr** [comment]
Yup. but I did find a bug in the implementation of this thanks to you. it doesn't handle empty filenames.

**Comment by nhooyr** [comment]
Alright my improvements are in #758
