### ISSUE TITLE
Save slow when using vendor directory

### ISSUE THREAD

**Issue by Jmeyering** [fatih/vim-go#688]
When using the GO15VENDOREXPERIMENT option and saving dependencies into my projects vendor directory, my saves are taking upwards of 5 seconds to complete really making it more difficult to work.

If I delete the vendor dir my saves are pretty much instantaneous, I'm importing ~8 packages at this point in time.

**Comment by fatih** [comment]
Hi @Jmeyering . vim-go doesn't do anything when you save expect calling `goimport` or `gofmt` dependent on what you set it up. I think you use syntastic, please disable it:

https://github.com/fatih/vim-go#using-with-syntastic

Thanks
