### ISSUE TITLE
Not an editor command: GoFmt

### ISSUE THREAD

**Issue by will** [fatih/vim-go#69]
I installed GoFmt with vundle, and a lot of the commands work, such as :GoBuild and :GoRun, but trying :GoFmt and :GoLint gives `E492: Not an editor command: GoFmt` and the autosave also does not work.

The first-run install thing worked and I have

```
~ ➤ ls .vim-go
errcheck  gocode    godef     goimports golint    oracle
```

Sorry, I don't know enough about vim plugins to give better error descriptions.
Any ideas on what to try would be appreciated.

**Comment by paulodiniz** [comment]
:+1:  for @jonathanwgoodwin comment, worked for me
