### ISSUE TITLE
GoRun + GoTest on non-main package segfaults vim

### ISSUE THREAD

**Issue by bmizerany** [fatih/vim-go#693]
I've been fat-fingering my `,r` intead of `,t` recently and noticed a pattern where doing so crashes vim. The easy solution is "don't do that." but I think this is a symptom of a knarly bug somewhere. This isn't the only way vim-go crashes vim for me but I can't tell you what I did before because I'm usually working in anger and am like "gah. dang it. can't stop coding. reopen vim!".

This has been happening on my old mac, and now my brand new macpro. I haven't been able to give a solid example of how to reproduce a crash until now, so here it is:

`vim x.go`

```
package x

import "testing"

func TestSomething(t *testing.T)) {}
```

`:GoRun`
`:GoTest`

Abort Trap 6

**Comment by bmizerany** [comment]
Current setup:

```
$ go version
go version devel +64e2a71 Sat Jan 9 18:27:32 2016 +0000 darwin/amd64
$ uname -a
Darwin Blakes-MBP 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

**Comment by bmizerany** [comment]
My vim-go is at 3e26758b1421ae88a8750b7c1aeaf8324c6b4912

**Comment by fatih** [comment]
Hi @bmizerany. I could reproduce it, when you do the combination `:GoRun`, `:GoTest` very fast.  I see the following error: 

```
Press ENTER or type command to continue Vim: Caught deadly signal ABRT

Vim: Finished.
[1]    97864 abort      /usr/bin/vim x.go
```

But this crash doesn't happen when you use a newer version of Vim (like installed with brew). It only happens for the default version coming from Mac OSX, which has the version:

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2015 16:22:14)
Compiled by root@apple.com
```
This version is really old (the new one is 7.4), and the new version has on top [hundreds of other patches](ftp://ftp.vim.org/pub/vim/patches/7.4/README). For example I've just received a brand new laptop too (new job), and I've compiled at that day. This version (which is 7.4) doesn't crash:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 28 2015 23:03:48)
MacOS X (unix) version
Included patches: 1-989
Compiled by fatih@Fatihs-MacBook-Pro.local
```

Unfortunately, I don't know which one of the patches fixed the issue. The best way is to use a newer version of Vim. I've looked into it and there are other fixes to, like enabling with the following:

```
$ DYLD_FORCE_FLAT_NAMESPACE=1 vim
```

There is not much I can do here right now. Maybe I should add a note in Readme for people to enfore them using version 7.4. Please let me know if updating your Vim version fixes the problem.

**Comment by nhooyr** [comment]
Interestingly I'm getting segfaults as well but on neovim and on a main package. As soon as I have reproduction instructions I'll post them.

**Comment by nhooyr** [comment]
Figured it out gonna create an issue.

**Comment by bmizerany** [comment]
Oh wow. I upgraded and not only does it appear to be fixed, but much faster too! Thanks!
