### ISSUE TITLE
flashing cursor after status line update

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#697]
This is best explained by a video. 

https://youtu.be/PugiOAWZTuQ

I start by typing some random text to show how it normally looks. I run GoBuild and then bam the cursor starts flashing a ton as I type.

It is likely to be a vim-go problem as neomake works perfectly. Neomake also seems faster than vim-go.

Let me know if the video quality is bad.

**Comment by nhooyr** [comment]
It has to do with "go#jobcontrol#Statusline" in my status line. After running GoBuild it causes the cursor to flash.

**Comment by fatih** [comment]
Hi @nhooyr  I don't know what's the correlation with :GoBuild and the cursor. We're not doing anything at the buffer and I'm using GoBuild every single way the same way you do (iTerm2 + nvim + terminal) and I don't have that problem. Do you powerline, airline, lightline or just plain statusline? I'm using lightline without any problem.

**Comment by nhooyr** [comment]
It has to do with the status line function. I'm using lightline.

**Comment by fatih** [comment]
You are right, when I disable statusline the cursor flashing goes away. I've just changed my underscore cursor to block cursor and it's more obvious now. I think it evaluates everytime you change something. In my case the flashing was happening inside the `ctrlp` buffer when I was searching for a file.

**Comment by nhooyr** [comment]
@fatih hmm is it intended that nothing is removed from `s:jobs` in `autoload/go/jobcontrol.vim`?

**Comment by nhooyr** [comment]
Ok so the problem is line 22
```vim
let import_path =  go#package#ImportPath(expand('%:p:h'))
```

**Comment by nhooyr** [comment]
Alright I got the problem, its calling `go env GOROOT` every single time. We should only call it once and store it.
