### ISSUE TITLE
GoMetaLinter Won't Install

### ISSUE THREAD

**Issue by arghtastic** [fatih/vim-go#698]
No Matter what I do, the installation for GoMetaLinter Hangs when running the command "GoInstallBinaries"

**Comment by fatih** [comment]
Hi @arghtastic It's not a vim-go problem, it must be a network problem of yours. Install it from your command line:

```
go get github.com/alecthomas/gometalinter
```

**Comment by arghtastic** [comment]
It's only gometalinter.  If I remove it from vim-go, everything else works fine.  I also did a manual grab, and that worked fine but hangs on update once gometalinter is enabled again.

**Comment by wanglinsen** [comment]
I have this problem too.

**Comment by mm-atsushiishida** [comment]
I faced same issue and resolved it.
Why the GoMetaLinter installation hangs is because , the cloning of gometalinter repository from is hanging up.
I used centos6.5 and I used git 1.7.
I updated git to 2.2 and cloning process was successfully finished.

**Comment by alecthomas** [comment]
FYI I've fixed this in gometalinter by vendoring everything (not just the linters).

**Comment by dlintw** [comment]
I have the same problem on RedHat 6.7 and git 1.7.1.  I haven't permission to upgrade git version unfortunately.
