### ISSUE TITLE
segfaults with neovim and :GoRun

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#699]
https://youtu.be/_JqR4irEy1s

As described in this video a very weird issue with :GoRun and splits. Not sure if its a neovim issue or a vim-go issue. The timing also seems to matter though I haven't experimented enough to know for sure.

This was the file I was using https://gist.github.com/nhooyr/805c62370bfb3f3f6a95

Let me know if the quality of the video sucks.

**Comment by fatih** [comment]
Hi @nhooyr this is not something I can produce. And honestly I'm not thinking of supporting neovim as a first class citizen. I'm going to update the README to reflect my intentions. It's already hard to keep up with Vim problems, and I don't want to spend time on supporting a platform which is still alpha version. Even though I'm using it, I'm ok with the segfaults (they never happened to me). What's matters is that it's working ok in Vim (which it does). Sorry and I don't want you to discourage supporting vim-go, I hope you understand me. If you find something though I'm more than happy to work one it or merge any  fix you have.

**Comment by nhooyr** [comment]
aha I managed to reproduce the crash without vim-go. Its likely a neovim issue.
