### ISSUE TITLE
auto import Complete when typing xxx.

### ISSUE THREAD

**Issue by wheelcomplex** [fatih/vim-go#701]
Hi all,

I'm using both liteide and vim(with vim-go) in office, and I found there is a pretty good feature in liteide. I have search over vim-go docs and issues for this feature, looks like it does not exist in vim-go.

The feature is that when typing "xxx." at the same time xxx has not imported, liteide will prompting "do you want to import xxx, press <enter> to import", at this time, press enter will auto import xxx and got auto complete prompt for exported method/var of xxx.

In vim-go, to get auto complete prompt for exported method/var of NOT imported xxx, I have to use vim command :GoImport xxx before I type "xxx.", although I defined a short-cut for it, but it still break the coding(you have to press <ESC> switch from code typing(edit mode) to command mode,  :GoImport xxx and return to code typing).

Thanks!

**Comment by fatih** [comment]
Hi @wheelcomplex  It's written in the README. Please instal YCM or Neocomplete. Thanks.

**Comment by wheelcomplex** [comment]
Thanks for your reply @fatih , I do read the README and actived YCM in vim, it work well to complete the public method/var of "imported" package(already listed in import( ... ) statement), but can not auto import a new package. I mean auto add package name to import ( ... ) list while typing.

For example:

<pre>
package main

func main(){
    // call os.Exit(0) in next line

}
</pre>

In current vim-go + YCM, for add os.Exit(0) to main(), we have to do follow:
1. press \<ESC\> to leave typing
2. invoke :GoImport os(so kackage os add to import(...) list)
3. press \<i\> return to typing
4. type in os\<dot\> and now YCM prompt all exported method of package os.

ps: \<dot\> mean press '.' in keyboard.

and in a "auto import" enabled vim-go+YCM, , for add os.Exit(0) to main(), we will do follow:
1. continue to type ''os<dot>" even package os does not listed in import( ... ). when we type in \<dot\>, vim-go(or something else) check the import( ... ) list and found os does not imported, it auto call :GoImport os\<CR\> to add os to import( ... ) list and prompt public method/var of os as normal.

so, with  "auto import", we save three step for import a new package.

As I know YCM can complete method of "imported" packages, but can not "auto import" a new package, do I miss something?

Sorry for my disordered English and thanks for your attention again.

**Comment by fatih** [comment]
I don't support YCM anymore. It was already totally optional. I think @oblitum wanted to create a doc: https://github.com/fatih/vim-go/commit/afba982475e1717a6433bfa69ff65ce92f87cd22#commitcomment-15935605 you can ask him too. Thanks

**Comment by DenLilleMand** [comment]
If anyone comes across this issue and is still looking for a answer, something like this is possible:
```
nnoremap <leader>gi :GoImport <C-R><C-W><cr>
inoremap <leader>gi <Esc>:GoImport <C-R><C-W><cr>A.
```
Second binding takes the word under the cursor, imports it and inserts a `.` at the end of the word which gives you the auto-complete.
