### ISSUE TITLE
GoRename sometimes does nothing

### ISSUE THREAD

**Issue by mmlb** [fatih/vim-go#705]
I'm trying to export a struct and from `xdrDecoder` to `XDRDecoder` but `GoRename` seems to do nothing. Here are the steps of what I've done.

Open the file containing the struct definition. `nvim nv/xdr_decoder.go`
Run `GoRename XDRDecoder` while cursor is on `xdrDecoder`
some message flashes too fast for me to read and for some reason a new file is opened (in this case `clone.go`, which is in a "parent" package (main) and doesn't reference `xdrDecoder` at all)
I run `:messages` and all I see is
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>                                                                                                 
"nv/xdr_decoder.go" 289L, 7311C                                                                                                                    
airline themes have been migrated to github.com/vim-airline/vim-airline-themes and will be removed from the core in the near future.               
"~/src/github.com/mistifyio/gozfs/clone.go" 21L, 394C                                                                                              
Press ENTER or type command to continue  
```

`xdrDecoder` was not renamed. I don't know if there is anything that can be done or if its just `gorename` not being helpful, but I thought to ask.

**Comment by fatih** [comment]
Hi @mmlb. Please provide a reproducible test case. Otherwise I'm not able to debug or to do anything. Also please note that `gorename` itself is not maintained by vim-go.

**Comment by mmlb** [comment]
Hey @fatih no I don't have anything available at the moment. I opened this to see if anything may pop into your head, feel free to close if not. I'll keep this in mind and see if I can come up with anything.

**Comment by fatih** [comment]
Thanks @mmlb What you could do is trying `gorename` from the terminal and see what it outputs. Maybe there is something wrong with the pkg. Thanks for opening. Feel free to open again if you have something useful.
