### ISSUE TITLE
Some weird characters are printed onto the screen

### ISSUE THREAD

**Issue by tchap** [fatih/vim-go#71]
When I use the arrow keys to move around in the command mode, from time to time some weird characters are printed, like

```
^[OA args.B = &data.BenchmarkOptions{
^[OA     RandomOutput: true,
}
```

Started happening after I installed vim-go...

**Comment by oryband** [comment]
A question everyone: Do you happen to use **zsh** and not bash? I have had this problem occuring in vim in mac+iterm2 and ubuntu+urxvt: https://groups.google.com/forum/#!topic/vim_use/UVxDG3lMQ0U/discussion

The common thing between these two setups was zsh + oh-my-zsh

**Comment by oryband** [comment]
Maybe youcompleteme or someother plugin is causing updates on cursor move just like vim-go did before this issue was fixed, and is polluting the screen in its place.

**Comment by vimalk78** [comment]
i am also facing the same issue, in Ubuntu as well as Mac

**Comment by tamasd** [comment]
I have a similar issue with macOS + iTerm + zsh + oh-my-zsh. 

For me the only thing that makes it go away is disabling neocomplete. It seems that after pressing the `.`, something takes too much time, so I see garbage characters displayed. In my case, the easiest way to reproduce is when I type a package name that is not imported yet, and then I start typing a function name really fast. If I wait about a second after typing the dot, it doesn't really happen. 

Additionally, if I try to correct a function name, there is a noticeable delay between pressing the backspace and the removal of the character from the screen.

**Comment by JuanCabre** [comment]
I am having the same issue.

I noticed that if i scroll the screen so that the escape sequences are no longer in the window, then when I scroll back, they are gone.

I have auto type info also on.

**Comment by rafaeljesus** [comment]
I facing with a similar problem when using auto completion, every time I write code which is completable like `(t testing.T)` e.g `T` when T appears I can't do anything else, even opening the file again once I go to the code the error comes again avoiding me to write anything else,

Pls see the pic below
![screen shot 2017-03-21 at 12 49 07 am](https://cloud.githubusercontent.com/assets/1216425/24132129/d7911d48-0dd1-11e7-8b9c-0fe907c8b1a1.png)

I already disabled `auto_type_info` but the error persists, shall I open an new issue?

**Comment by rafaeljesus** [comment]
I found myself a temporary solution for this `autocmd FileType go set omnifunc=` even losing completion features at least I can write code 🙂

**Comment by 178inaba** [comment]
I also encountered this problem.
My environment is `macOS` + `iTerm2`
I used `neocomplete` for autocomplete.

I will report that I could avoid the problem by deleting `$GOPATH/bin/gocode` or disabling `neocomplete`.
In addition, the report of @rafaeljesus was effective.

To me the cause of this problem seemed to be a conflict between `gocode` and `neocomplete`.

**Comment by kuiro5** [comment]
Had this issue with zsh/oh-my-zsh. Using vanilla bash solved this issue (amongst others) that I was having with vim.

**Comment by syifan** [comment]
I am experiencing the problem in vanilla BASH, Terminator. Disabling same_id highlighting solves the problem.

**Comment by kregan77** [comment]
I'm having the same issue on OSX 10.12.6, ITerm2 3.1.5, vim-go, YCM.  Here's vimrc:

```syntax on
set tabstop=4
set shiftwidth=4
set expandtab
set number
set backspace=indent,eol,start

vnoremap <C-c> :w !pbcopy<CR><CR> 
noremap <C-v> :r !pbpaste<CR><CR>

set background=dark

set laststatus=2

filetype plugin indent on

" attempt to fix issue with characters from vim normal mode getting crapped
" out onto the screen
let g:auto_type_info=0

call plug#begin('~/.vim/plugged')

Plug 'Valloric/YouCompleteMe'
Plug 'fatih/vim-go'
Plug 'w0rp/ale'

call plug#end()
```

**Comment by eidge** [comment]
Any chance this is related to tmux? I'm seeing this happening very frequently now, but only if running nvim inside tmux..

**Comment by vim345** [comment]
I was having this issue on Vim8 on Ubuntu SSHed from iterm 2, using tmux, and ZSH. I disabled all my plugins, yet I got the same garbage characters showing up in my screen. Then I went through my vimrc line by line and noticed the issue was related to this line:

```
function! GitBranch()
  return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction

function! StatuslineGit()
  let l:branchname = GitBranch()
  return strlen(l:branchname) > 0
endfunction

set statusline+=%#TabLine#
set statusline+=%{StatuslineGit()}
```

The project that I'm working on is rather large. So it takes a long time to find the current branch all the time. I believe the delay in finding the current branch is making vim to show garbage characters in my screen.

I'm not too sure if this use case applies to many people though. I'm just sharing it here just in case.

**Comment by I-Dont-Remember** [comment]
I found the same thing as @vim345 , I also have the StatuslineGit function and after commenting out my usage of it all issues dissapeared.

**Comment by Carpetsmoker** [comment]
It would be much better to get the branch name just one with an `autocmd` on `BufNewFile` and `BufReadFile`, store that in a buffer-local variable, and display it. You could also add some other autocmds (e.g. `WinEnter`) to get updates as well.

IMHO that's much better than running a shell command (*any* shell command) on every screen update ;-)

**Comment by sbromberger** [comment]
I can reproduce this reliably in my environment (from inside a Go file, `>G`, then `:w`, then up arrow). Disabling
```
let g:go_auto_type_info = 1
```
resolves the issue.

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 06:56:05)
macOS version
Included patches: 1-500
```
vim-go master as of today.
iterm 2 Build 3.2.5beta1

I tried various `updatetime` settings, nothing between 50 and 500 resolved the issue.

**Comment by john9631** [comment]
So I had it when I moved from Tilix to Terminator.  There is lots of discussion but I found that the approach below worked for me if the others don't resolve it for you - basically brute force to manage the cursor shapes and clear the screen.  There are references in the docstring.

`
    " Solve extra characters on vim screens in terminator in Linux
    " Enable different cursors based on the mode from
    " https://github.com/mjedmonds/dotfiles/commit/41c1d4639d7b2b047d260602f27a80695cf73f9c
    " Information on cursors to complete it from
    " https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes"

    if has("autocmd")
      au BufNewFile,VimEnter,BufEnter,InsertLeave * 
        \ silent execute '!echo -ne "\e[2 q"' | redraw!
      au InsertEnter,InsertChange *
        \ if v:insertmode == 'i' | 
        \   silent execute '!echo -ne "\e[6 q"' | redraw! |
        \ elseif v:insertmode == 'r' |
        \   silent execute '!echo -ne "\e[4 q"' | redraw! |
        \ endif
      au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
    endif

    let &t_SI = "\<Esc>P\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_SR = "\<Esc>P\<Esc>\<Esc>]50;CursorShape=2\x7\<Esc>\\"
    let &t_EI = "\<Esc>P\<Esc>\<Esc>]50;CursorShape=2\x7\<Esc>\\"
`

**Comment by mynyml** [comment]
It's been over a year since the last post but I'm also getting this issue on the latest update. Only happening with go file types. Using vim8.1 in plain LXTerminal. I confirmed that it stops after I disable vim-go.
