### ISSUE TITLE
After using gd to do to a definition, how do i pop the stack

### ISSUE THREAD

**Issue by krmayankk** [fatih/vim-go#712]
for e.g. in ctags you can ctrl ] to go to a defintion and Ctrl T to pop the stack and go back. How do we do this in vim-go ?

**Comment by fatih** [comment]
Hi @krmayankk. This was talked earlier here: https://github.com/fatih/vim-go/issues/667 It's not possible until there is a custom implementation. @alaska wanted to tackle it though. Thanks.

**Comment by alaska** [comment]
This is very close now.
![godefstack](https://cloud.githubusercontent.com/assets/926884/12852267/1e28dfd4-cbfc-11e5-86f2-167cc4aaed64.gif)

**Comment by alaska** [comment]
That said, you can use ctrl-i and ctrl-o to navigate the normal jumpstack
