### ISSUE TITLE
Godoc command not found

### ISSUE THREAD

**Issue by nicwest** [fatih/vim-go#715]
when using `K` on a function I'm getting the following error:
```
godoc command not found.
  install with: go get golang.org/x/tools/cmd/godoc
```

When attempting to go get as instructed I'm getting this:

```
go get -v golang.org/x/tools/cmd/godoc
golang.org/x/tools/godoc/static
golang.org/x/tools/godoc/analysis
golang.org/x/tools/present
golang.org/x/tools/blog
golang.org/x/tools/godoc
golang.org/x/tools/cmd/godoc
go install golang.org/x/tools/cmd/godoc: open /usr/lib/go/bin/godoc: permission denied
```

`sudo go install` in the `~/go/src/golang.org/x/cmd/godoc` directory complained about not having a $GOPATH set ([this did not seem like a good idea](http://stackoverflow.com/a/33755566)), so in the end I just did a `go build` and copied the binary in to my ~/go/bin directory.

Any ideas why this wouldn't be in my /usr/lib/go/bin/godoc by default (probably outside of the scope of this plugin)?

I'm running go 1.5.3 on arch linux.

**Comment by spottygreen** [comment]
If you used a package manager to install Go, check to see if there's a second package for Go containing the godoc tool.

The godoc tool is included in the official Go installation.

**Comment by nicwest** [comment]
you sir where correct.

For anyone that hits the same problem under arch the developer tools are under the separate package `go-tools` so a `pacman -S go-tools` fixes this issue.
