### ISSUE TITLE
Use `go install` instead of `go build` to improve caching for :GoBuild

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#717]
Relevant information:

https://twitter.com/davecheney/status/697182715901116416
https://twitter.com/davecheney/status/697360816484573184

**Comment by ironcladlou** [comment]
One usability issue with `go install` is that you can't always rely on wildcards for specifying the packages to build/install. For example, in most of the complex projects I work in, doing a `go install ./..` almost always fails as it tries to install packages it shouldn't. The solution to this I've implemented in other integrations has been to allow the user to specify an "installable package" list to feed through to `go install`.

The wildcard solution could be a sensible default, with a list of installable packages overriding the default.  I'm eager to hear any other solutions to this problem I wasn't aware of.

**Comment by fatih** [comment]
Thinking now, we have already `:GoInstall`. So it's there and can be used and mapped to any key. I'm closing this, I think the current status is already perfect and in a good situation.  Thanks @ironcladlou for the comment.
