### ISSUE TITLE
Remove and refactor duplicate offset functions

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#719]
Right now there are several places in vim-go that parses the byte offset of the position under the cursor. The ones I could see are below. And what interesting is that each of them has it's own way of implementing it:

https://github.com/fatih/vim-go/blob/master/autoload/go/complete.vim#L90
https://github.com/fatih/vim-go/blob/master/autoload/go/rename.vim#L67
https://github.com/fatih/vim-go/blob/master/autoload/go/oracle.vim#L65
https://github.com/fatih/vim-go/blob/master/autoload/go/def.vim#L67

Let us create a single function under `util.vim` with the function signature: `go#util#OffSet()`, remove all others and use this new function.

**Comment by nhooyr** [comment]
I'll work on this tomorrow.

**Comment by nhooyr** [comment]
The ones in oracle.vim and rename.vim are the exact same.
