### ISSUE TITLE
Regression in closing location list

### ISSUE THREAD

**Issue by cespare** [fatih/vim-go#720]
The commit 8ef677a3625219758a63e1b6826c189a480b4edb introduced a regression where sometimes the location list is not closed even though it should be.

I'm not sure of all the conditions in which this can happen, but here's one way to repro it:

1. Open a valid .go file in vim. This is split A.
2. Open a new split (split B), and open a different .go file in split B.
3. In split B, type some syntax error into the Go code.
4. `:w` to save the buffer in split B. Now the location list should open in split B because gofmt sees a syntax error.
5. Now switch back to split A and save that buffer (which should not have a syntax error). The location list should still be open in split B.
6. Switch back to split B, fix the syntax error, and save. Now the location list is still open with the old error, even though it is fixed.

At this point, the only way to get rid of the location list is either to close it manually, or else to make a new syntax error, save, fix it, and save again.

I found the commit that caused the problem via bisecting.

**Comment by fatih** [comment]
Thanks @cespare. I'll look into it after merging #700

**Comment by cespare** [comment]
Actually the fix seems simple. I'll send a PR.

**Comment by cespare** [comment]
Thanks for the super-quick response @fatih :+1:

**Comment by fatih** [comment]
You're welcome. Thank you too for sending a PR quickly, much appreciated :)
