### ISSUE TITLE
Add support for gocylco

### ISSUE THREAD

**Issue by timshannon** [fatih/vim-go#722]
Small request, but it'd be nice to have https://github.com/fzipp/gocyclo added to the list of Go binaries and Go<command> calls.

**Comment by fatih** [comment]
Hi @timshannon We already support it via `:GoMetaLinter`. Please read the docs and add it. Also have a look here: https://github.com/alecthomas/gometalinter

Thanks

**Comment by timshannon** [comment]
Whelp, sorry.  I Missed that, thanks.
