### ISSUE TITLE
When errors found vim spitting errors "Connot make changes, 'modifiable' is off

### ISSUE THREAD

**Issue by osleg** [fatih/vim-go#723]
With vim-go when doing save and the source code have errors which are added to 'llist' vim spitting errors `Connot make changes, 'modifiable' is off`.
![modifiable](https://cloud.githubusercontent.com/assets/207721/13006345/6b27abd6-d1c3-11e5-95de-84688b14faaf.png)

**Comment by fatih** [comment]
Hi @osleg. Please provide a test case. A simple `demo.go` file with errors, and then the exact commands you input to Vim to reproduce it. Also please provide your Vim version and also which Version of vim-go you're using. Thanks

**Comment by nhooyr** [comment]
@osleg are you trying to modify the location list? You cannot do that lol.

**Comment by osleg** [comment]
@nhooyr I know :)

@fatih 
That's usually happens when there is syntactic error like missing brackets like this: 
```
package main

func main() {
    a := "asd"
    if a == "asd" {
        b := a
 }
```

With this case it spitting:
```
"main.go" 8L, 71C written
0
Gofmt returned error
Error detected while processing function StripTrailingWhitespace:
line    6:
E21: Cannot make changes, 'modifiable' is off
Gofmt returned error
E21: Cannot make changes, 'modifiable' is off
Gofmt returned error
"main.go" 8L, 70C written
Press ENTER or type command to continue
```

**Comment by fatih** [comment]
I don't know what `StripTrailingWhitespace` is doing as it's not a function inside vim-go. I don't think this is vim-go related, one of your plugins is misbehaving. I'm closing this. Thanks

**Comment by marcusandre** [comment]
Hi @osleg, I had the same problem while using the [editorconfig/editorconfig-vim](https://github.com/editorconfig/editorconfig-vim) plugin with the  `trim_trailing_whitespace` option enabled.

This fixed it for me then:

```yaml
[*.go]
indent_style = tab
insert_final_newline = false
trim_trailing_whitespace = false
```

Hope it helps,
Marcus

**Comment by antony360** [comment]
FYI, this is related to, at least, spf-13, a workaround is available here : https://github.com/spf13/spf13-vim/issues/957#issuecomment-306510976

**Comment by osleg** [comment]
It seems that both vim-go and trim white list function are trying tobwrite into file while one of them (vim-go I suspect) setting modifiable to no while working. 
Looks like a race condition here
