### ISSUE TITLE
executing :GoFmt removes vim-airline status and colors, still folds everything

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#726]
1. Install https://github.com/vim-airline/vim-airline plugin
2. Notice all the fancy colors in the status bar and bask in their glory
3. Execute `:GoFmt` in some buffer
4. The status bar loses it's status and colors. For example if there were syntax errors in the buffer, they're now removed, not just "greyed out" by the colors being removed.

**Comment by oryband** [comment]
@fatih did you manage to check this issue?

**Comment by oryband** [comment]
i think this also causes all folds to close even after updating with #502 
might be somehow related to #732 ?

**Comment by fatih** [comment]
This is probably due `mkview`. Can you please update to latest master and try again ?

**Comment by oryband** [comment]
@fatih do I have to enable `g:go_fmt_experimental` ?

**Comment by fatih** [comment]
No, I think `mkview` is the culprit and it destroys it. Just use without the experimental and see what happens.

**Comment by oryband** [comment]
Looks like the color removing is fixed, but i still get everything folded randomly. This doesn't always happen and I can't pin point what is causing this.

With the experimental turned on, colors are still removed.

**Comment by oryband** [comment]
UPDATE: this happens on almost every `:GoFmt` call

**Comment by oryband** [comment]
@fatih any progress?

**Comment by eduncan911** [comment]
@oryband Faith is a busy guy.  If you can help find the problem, issue a PR.

FWIW, I cannot reproduce your issue.  `:GoFmt` works for me on master.

* Remove all your plugins, except vim-go and vim-airline.  Don't configure vim-airline, leave it default.
* Empty your .vimrc, only source vim-go and vim-airline and have no other files.

Try `:GoFmt` again.

It may be better for you to follow the format of creating new issues.

Copy and paste this below into your original post above to give more details:

```
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1.
2.
3.

### Configuration

#### `vimrc` you used to reproduce:

#### vim version: 

#### vim-go version:

#### go version:

```

**Comment by nhooyr** [comment]
@oryband can you check if https://github.com/Chiel92/vim-autoformat fixes all your problems?

**Comment by oryband** [comment]
@eduncan911 @fatih I'm sorry if I was too pressing on this, didn't mean to come out like this.
I've tried autoformat and disabled auto formatting via vim-go, and it does seem to fix the issue.

@nhooyr thanks for the tip, didn't know about this plugin.

@eduncan911 maybe it's a good idea to add new issue templates, like YouCompleteMe has: https://github.com/Valloric/YouCompleteMe/issues/new

Thanks for the help.

**Comment by oryband** [comment]
I see issue templates are already in use, alrighty then.

**Comment by eduncan911** [comment]
@oryband cool that it was resolved!

GitHub's "new issue template" is a new feature they just released a few weeks ago.  @fatih has added it here; but, it was after you created this issue.  :+1:  

I actually pasted faith's new issue template above, as quoted.  Try it.  Hit New Issue now.

**Comment by oryband** [comment]
Yeah I noticed it, very nice!
