### ISSUE TITLE
Saving sometimes changes scroll position

### ISSUE THREAD

**Issue by cespare** [fatih/vim-go#728]
Some very recent change (ff56a315974f752ab3424ae750548a3a17277f9a?) causes the buffer to be scrolled far up or down after a save (gofmt). I don't yet have good repro instructions (it only happens some of the time) so I will update this bug more later.

**Comment by fatih** [comment]
Right, that change is too big and honestly I didn't like that much. Maybe we should add it behind a setting like `go_fmt_save_folds`, which is by default disabled. I think the formatting stuff is the most problematic piece of code in vim-go. And it's due Vim's architecture and not having a set of primitives for these kind of stuff. Let me know if you find something.

**Comment by cespare** [comment]
After updating, I can no longer reproduce this bug. Perhaps ba96e1f1fed4317313bb4852293dc1cc5b005a6b fixed it? But when trying to get to the bottom of it, I was unable to find a prior commit at which the problem reproduced either.

Maybe it was some bad state of the vim-go repo on this computer. Or maybe it's just hard to reproduce reliably and it can still happen. I'll reopen if I see it again.

**Comment by cespare** [comment]
Argh, it just happened again. I'll have to spend more time trying to figure out how to reproduce it. I wrote code for a couple of hours without it happening, but yesterday it was happening on almost every save.

**Comment by cespare** [comment]
I still don't have exact repro steps, but I'm increasingly confident that ff56a315974f752ab3424ae750548a3a17277f9a caused the issue.

It's hard to track down the problem, because it's tied to some on-disk state. For example, here's the steps I took in my most recent attempt:

* I was able to reproduce the problem at tip by by adding some new code to my test file and saving.
* I checked out a commit from a few weeks ago -> the problem went away.
* Tried bisecting the commits, but the problem didn't come back.
* Even when I went back to tip, the problem had stopped happening.

I see that there's a new `views/` directory in my `.vim`, which is presumably caused by the `mkview!` calls in ff56a315974f752ab3424ae750548a3a17277f9a. I think the issue is likely to be caused by some particular state of the view file, due to the fact that the behavior carries across vim restarts.

Once I can get the problem to start happening again, I'm going to see if saving/restoring the view file when it's in a bad state can reliably reproduce the problem.

**Comment by cespare** [comment]
Update: I still don't have repro steps, but the problem is not due to the on-disk state: it's the editor process itself that's in a bad state.

I know this because I've only seen the problem occur after using the editor for a while. Once it starts happening, it keeps on happening on most saves. Deleting the views/ dir doesn't fix it, but restarting the editor (while leaving views/ alone) does fix it.

Another clue is that once the problem starts happening, every save is accompanied by a very noticeable full-page flash/refresh which doesn't normally occur.

**Comment by fatih** [comment]
@cespare this is so weird. And this is also one of the reasons I've was not much inclined to merge that particular PR as it has tons of side effects :/ I'm going to put it behind `go_fmt_experimental` setting so people who want to use save folding can enable it. And once we have the solution/fix for this, we can pull it out from that flag.

**Comment by cespare** [comment]
I've reverted the mkview changes locally and have been using vim-go for several days now without seeing any of these issues, so even though I still don't have an explanation for this issue, I am very confident that that change is the source of the problem.

@fatih Do you have the `go_fmt_experimental` change ready, or should I send a PR?

**Comment by fatih** [comment]
@cespare I'm a little bit busy recently, I can do it in 2-3 days, if you have it I can merge it.

**Comment by cespare** [comment]
@fatih See #745.
