### ISSUE TITLE
Gvim don't load $GOPATH when run from WM

### ISSUE THREAD

**Issue by martin-damien** [fatih/vim-go#733]
**OS**: Xubuntu 15.10
**Go**: 1.5.3
**Shell**: zsh 5.1.1
**Gvim**/**Vim** : 7.4

```zshrc
export GOROOT=/home/damien/.linuxbrew/opt/go/libexec
export GOPATH=$HOME/projects/go
export GOBIN=$GOROOT/bin
export PATH=$PATH:$GOBIN:$GOROOT
```

Running **vim in a terminal**: all is OK
Running **Gvim** by launching it **from the terminal**: all is OK
Running **Gvim** from Xubuntu **GUI** (main menu): 

![screenshot_2016-02-20_11-52-35](https://cloud.githubusercontent.com/assets/295478/13196216/8121b494-d7c8-11e5-8237-14cd649e5a69.png)

And when trying `:GoInstalBinaries`:

![screenshot_2016-02-20_11-53-45](https://cloud.githubusercontent.com/assets/295478/13196218/a47f8b46-d7c8-11e5-9038-1dc17c092026.png)

**Comment by fatih** [comment]
Hi @martin-damien. This is not a vim-go problem, it's your Vim app not sourcing the environment. There is nothing I can do, you have to ask this question to another place (like xubuntu forum). Thanks.

**Comment by martin-damien** [comment]
That's what I supposed :)
Thank you for your quick answer. And thank you for this awesome plugin :)
