### ISSUE TITLE
Goimports not working with vendored packages (only through vim-go, working with cmd in terminal)

### ISSUE THREAD

**Issue by relappi** [fatih/vim-go#734]
On go 1.6, Reproduction steps...

Project structure
~~~~
test.go
vendor/
  github.com/
    chzyer/
      logex/
        ...
~~~~

test.go
~~~~go
package main

func main() {
	logex.Println("hello")
}
~~~~

- Note: go get github.com/chzyer/logex was never run
- Running :GoImports (or saving with let g:go_fmt_command = "goimports") does nothing
- In a terminal running `goimports test.go` yields...

~~~~go
package main

import "github.com/chzyer/logex"

func main() {
        logex.Println("hello")
}
~~~~

**Comment by mhamrle** [comment]
I had the same problem, https://github.com/fatih/vim-go/pull/735 fixed my problem.

**Comment by fatih** [comment]
This is fixed with @mhamrle work #745. Please open an issue if the problem still insist. Thanks!

**Comment by tthanh** [comment]
I still have this issue
I try update latest goimports and vim-go but still have issue

Project structure

```
main.go
vendor/github.com/nlopes/slack/...
```

main.go
```go
package main

func main() {
	api := slack.New("")
}
```
If I run `goimports -srcdir . main.go`, it import like normal:

```go
package main

import "github.com/nlopes/slack"

func main() {
        api := slack.New("")
}
```

**Comment by ricardoseriani** [comment]
I have this problem too (and even if I run goimports without the -srcdir . it will work)
