### ISSUE TITLE
All :Go commands missing

### ISSUE THREAD

**Issue by nerakhon** [fatih/vim-go#736]
All :Go commands are missing except :GoInstall/UpdateBinaries and :GoPath. I am running Vim 7.3 and installed via Vundle. Need any data? Found another related issue, but really I cannot switch a plugin manager for the sake of one plugin, so I would like to help to troubleshoot why the issue happens.

**Comment by nerakhon** [comment]
with vim-plug the plugin works, but that sounds like a workaround to existing issue.

**Comment by fatih** [comment]
Hi @nerakhon There is no issue, it works already. Your vim setup is broken imho. The :Go commands are there if you install it correctly. Thanks.

**Comment by nerakhon** [comment]
Sorry but I cannot agree, the same issue happens on a fresh OS account with no vim settings except vundle and your plugin. We should really debug this or please remove vundle from your supported plugin managers as it is evidently broken.

**Comment by fatih** [comment]
No it works. Read https://github.com/fatih/vim-go/wiki/FAQ-Troubleshooting. Otherwise I would expect hundreds of issues from other vundle users that it doesn't work (which is not the case). I still think you have wrongly configured vimrc.

**Comment by nerakhon** [comment]
I went through the troubleshooting and non applies, here is a full .vimrc the minimalistic one:

```
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" Put your non-Plugin stuff after this line

filetype plugin indent on
```

then I execute :PluginInstall and installation succeeds with no errors.

**Comment by andrej-talon** [comment]
I experience the same problem. I have syntax highlighting and code check on save etc, but the Go* are not showing except the one mentioned up top. I used pathogen to install vim-go and it is a completely fresh install of Ubuntu as well.

**Comment by dan-compton** [comment]
Same problem here

**Comment by ls42** [comment]
Just for the record: I'm sure it's this line `filetype plugin indent on` that should really be `filetype plugin on` (omitting the `indent`).
