### ISSUE TITLE
GoRun messes up terminal

### ISSUE THREAD

**Issue by nerakhon** [fatih/vim-go#739]
### Expected behavior

When issueing :GoRun I expect the go to output to standard output "bellow vim" and return to editor seeing the edited file as before executing this command.

### Actual behavior

The window has no content except cursor and this situation can be resolved by either restarting vim or issuing write (doesn't always help) or new tab commands

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1.

vim main.go

2.

```
package main

import "fmt"

func main() {
        fmt.Printf("Hello, world.\n")
}
```
3.
:GoRun

### Configuration

OS X 10.11

$GOPATH=~/.gobin

#### `vimrc` you used to reproduce:

```
set nocompatible              " be iMproved, required

call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go'

call plug#end()

filetype plugin indent on
```

#### vim version: 

version 7.4.1401 with Lua

#### vim-go version:

latest from github as of today

#### go version:

go version go1.5.2 darwin/amd64

**Comment by fshiori** [comment]
I have the similar question on  MacVim.
Can't see any output below vim when execute GoRun.

**Comment by makedonian** [comment]
I'm having the same issue with terminal vim. This didn't used to happen before. Running `:!go run %` still works as expected

**Comment by nerakhon** [comment]
@makedonian I second that, same result with running go run via shell pipe.

**Comment by makedonian** [comment]
There is a pull request here https://github.com/fatih/vim-go/pull/743 that the author says it should fix the issue (still doesn't work for me), maybe it's something as simple as that @fatih?

**Comment by andrey-tpt** [comment]
Tested pull request #743 - works just fine for setup mentioned by @nerakhon (with the only difference as go1.6 vs go1.5.2)

**Comment by gypsydave5** [comment]
Yeah, `redraw!` is a handy command to run when Vim comes back all messed up; just run it as a Vim command as a stopgap :smile:

**Comment by makedonian** [comment]
@gypsydave5 my issue is that before, when you ran :GoRun it would show the output of the program until the next keypress. This is what's happening right now:

![test](https://cloud.githubusercontent.com/assets/471787/13479678/e6f8c7d2-e095-11e5-88e0-e22668d38fba.gif)

I'll try to go back few versions to see where it broke

**Comment by bhcleek** [comment]
@makedonian Can you try #748 to see if it resolves your issue?

**Comment by makedonian** [comment]
That worked:) Thanks for the quick turnaround @bhcleek

**Comment by fatih** [comment]
Fixed with: https://github.com/fatih/vim-go/pull/748 Thanks for the feedback. Please feel free to open again if it's not fixed.

**Comment by nerakhon** [comment]
Yep fix works, I verified it.
