### ISSUE TITLE
when I save xxx.go it shows me “-- more --” and force me to the bottom of the file

### ISSUE THREAD

**Issue by oska874** [fatih/vim-go#747]
### Expected behavior

type `:w` and immediately leave

### Actual behavior

when I save xxx.go it shows me “-- more --” and force me down to the bottom of the file

### Steps to reproduce:

1.  input codes long enough to across multiply pages
2.  type `:w`

#### vim version: 
7.4
#### vim-go version:
newst

**Comment by fatih** [comment]
Please provide your vimrc that we can use to reproduce. It's missing above. My initial thought is that you are using `goimports` and it's not updated (it's an old version). Be sure you have the latest.

**Comment by oska874** [comment]
fixed with a specific `vimrc`

**Comment by renier** [comment]
@oska874 How did you fix this? I'm seeing the same problem. Can you share your .vimrc or go: settings?
