### ISSUE TITLE
Permit disabling of snippets

### ISSUE THREAD

**Issue by lpil** [fatih/vim-go#749]
Hello!

I use https://github.com/honza/vim-snippets/ to get the majority of my snippets, and I prefer the snippets there to these ones for various reasons.

Is it possible to use vim-go without loading the snippets? It overwrites the ones provided by vim-snippets, which is frustrating.

Cheers,
Louis

**Comment by nhooyr** [comment]
let g:go_snippet_engine = "ultisnips"

**Comment by fatih** [comment]
Hi @lpil . As @nhooyr said, just add it and you're good to go
