### ISSUE TITLE
:GoDef should jump to an existing buffer if it's exists

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#753]
### Expected behavior

I expect to jump to an existing file via :GoDef.

### Actual behavior

If the target file exists, :GoDef creates another view. We end up with two window with the same file.

### Steps to reproduce:

1. Jump to a file via :GoDef
2. Go back to the source file and jump again via :GoDef
3. :GoDef creates a new file

#### `vimrc` you used to reproduce:

https://github.com/fatih/dotfiles/blob/master/init.vim

#### vim version: 

7.4

#### vim-go version:

HEAD - master

#### go version:

1.6

**Comment by eduncan911** [comment]
I actually like the existing functionality.  It keeps it consistent with other `:GoDef` lookups popping up.

Maybe when changing this feature, create a config flag to enable the "jump to existing buffer instead of opening new window"?

**Comment by fatih** [comment]
@eduncan911 it's behind a new flag `g:go_def_use_buffer` and is disabled by default, so nothing has changed for you, FYI :)
