### ISSUE TITLE
Feature request: Atoms Go-Plus like inline coverage

### ISSUE THREAD

**Issue by bahlo** [fatih/vim-go#755]
This is a feature request, so I'm not sure how to fill in the fields, but I tried my best :grin:.
The Go-Plus package for Atom is able to highlight the covered and uncovered branches in green and red. 
This is so awesome, it makes my team use Atom almost exclusively for Go development.
Is this possible with Vim? You'd need to wait a few seconds on every save since it's synchronous, but I think this is a price many would pay. Also, Neovim supports async actions.

**Comment by fatih** [comment]
Do you mean something like: https://github.com/t-yuki/vim-go-coverlay ?

**Comment by bahlo** [comment]
:hear_no_evil: Awesome, thank you! :100:

**Comment by fatih** [comment]
Bitteschön :) Btw I've live near Frankfurt for 17 years, great city :)

**Comment by bahlo** [comment]
Nice :ok_hand:. I't really is. :city_sunrise:
