### ISSUE TITLE
Add support for unused (https://github.com/dominikh/go-unused)

### ISSUE THREAD

**Issue by marcosnils** [fatih/vim-go#761]
It'd be nice if vim-go had support for unused (https://github.com/dominikh/go-unused)

Seems like metalinter is evaluating the possibility to include it in their linting suite (https://github.com/alecthomas/gometalinter/issues/98). 

Which would be the proper way to proceed?. 

1. Wait until metalinter adds it and provide a configuration variable in vim-go to enable this?. Or make vim-go users completely override the `go_metalinter_command` to enable this feature?

2. Implement some new command like `GoUnused` which directly uses the binary. 

I'll be happy to craft a PR for whatever path you decide to go.

**Comment by nhooyr** [comment]
I think its a better idea to let metalinter handle it. It is just another linter after all. We already have a configuration variable to enable different linters

```vim
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
```

**Comment by fatih** [comment]
Thanks for opening the PR @marcosnils. I'm not thinking anymore to add specialized tooling for these tools. We have settings to change the behavior and it's just a matter of time it's being included. Thanks for opening the PR.

**Comment by alecthomas** [comment]
FYI this is now in gometalinter.
