### ISSUE TITLE
IF YOU SEE THIS, REPORT A BUG

### ISSUE THREAD

**Issue by remexre** [fatih/vim-go#763]
https://github.com/Shougo/neocomplete.vim/issues/530

**Comment by nhooyr** [comment]
@remexre this is a problem with nsf/gocode

Not vim-go.

**Comment by nhooyr** [comment]
https://github.com/nsf/gocode/blob/40385eba48ae61394e5d2935b1e5c7130fa9b46b/decl.go#L50

**Comment by remexre** [comment]
Thanks
