### ISSUE TITLE
fzf support for GoDecls and GoDeclsDir

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#766]

**Comment by fatih** [comment]
@nhooyr can you please write more descriptive issues, is this a bug, or a feature request, and co... I know what you mean but please remind that a lot of people are reading the issues and we need to be more clear on this :)

**Comment by nhooyr** [comment]
@fatih sorry. It's a feature request, those commands are currently only supported for ctrlp.

**Comment by fatih** [comment]
There is no help or documentation for FZF. Seems like there is not plugin feature like we have in ctrlp. And because I'm not using it I don't have time to implement this myself from scratch. I'm open to contributions. Thanks.
