### ISSUE TITLE
Text object functions: d]] eats next function's comment

### ISSUE THREAD

**Issue by tbruyelle** [fatih/vim-go#771]
### Expected behavior

`d]]` shouldn't delete the next function's comment.

### Actual behavior

`d]]` delete the next function's comment.

### Steps to reproduce:

Type `d]]` while the next function has a comment. This comment is deleted.

#### vim version: 
7.4
#### vim-go version:
1.5
#### go version:
1.6

**Comment by fatih** [comment]
Thanks @tbruyelle for the bug report. I'll look into it.

**Comment by fatih** [comment]
Hi, @tbruyelle 

Just looking at it and seems it's totally correct. `]]` means until the next function. So you delete until the next function, which in your case are the comments. Is there anything I miss or you think it should be different?

**Comment by tbruyelle** [comment]
Hi @fatih, yes this is questionable. When I read your blog post I probably misunderstood the notion of object in vim. I thought if a function is an objet, then its comment is part of it.

**Comment by fatih** [comment]
`]]` means the beginning of the `func` keyword. So this actually pretty consistent. It might take some time to get used to it, but this is how it's being done. Thanks for opening the issue.
