### ISSUE TITLE
feature request: dsf (delete surrounding function)

### ISSUE THREAD

**Issue by brenol** [fatih/vim-go#772]
Hi!

I'm not sure if this should be posted here or in the motion repository, if so, please tell me and I'll post there!

I'd like to have the possibility of deleting/changing the surrounding function call easily, for instance:

``` go
package main

import (
    "fmt"
    "html/template"
    "strings"
)

func main() {
    v := []string{"this", "is ", " a very nice and tasty", "test"}
    fmt.Println(template.URLQueryEscaper(strings.Join(v, ",")))
}
```

Using DSF inside the strings.Join call would delete the strings.Join() call;
Then, when used again, it would delete the URLQueryEscaper call;
Leaving the following code:

``` go
package main

import (
    "fmt"
    "html/template"
    "strings"
)

func main() {
    v := []string{"this", "is ", " a very nice and tasty", "test"}
    fmt.Println(v, ",")
}
```

I think it's a very useful addition to text objects.

Thanks!

**Comment by fatih** [comment]
Hi @brenol 

This looks like a good idea, I just need to get  a better understanding of it. Are there any other `ds` motion objects you are aware of? (maybe from other plugins) ? 

As I see what left is the function parameter. Our current `if` and `af` are about function declarations. `]]` and `[[` are also used to jump between function declarations. It's all about function declaration.

But in your case, it's an expression (a function call). So it's quite different. For example I could use `dsf` to delete the surrounding of a function declaration instead of a function call.

**Comment by brenol** [comment]
Hey @fatih!

Besides vim-surround with ```ds<key>```, nope, not that I'm aware of.

And yes, it's a different use from what is done nowadays, perhaps the correct naming would be ```dsfc (delete surrounding function call)```? I'm not sure.

If I can assist in any other way, please tell me! I don't think the args being passed into the function should be deleted too, although I'm not sure.

Thanks :+1:

**Comment by fatih** [comment]
Two related links for further work:

* http://stuff.fork-bomb.org/expand_region.gif
* https://go-review.googlesource.com/21754

Seems like a better way can be done with guru's new `what

**Comment by AndrewRadev** [comment]
@brenol I found this issue while I was googling for "vim dsf". I plan on creating a plugin with that name that does exactly what you ask. In fact, I already have the functionality working (and it seems to work for your example): https://gist.github.com/AndrewRadev/d336d5b78931303cdb22, and you could take it from there.

Funnily enough, somebody took it and made it into a plugin by copy-pasting an old version of it :) https://github.com/faceleg/delete-surrounding-function-call.vim. So, you can use that if you'd like. I'm not sure how to proceed right now (should I fork the plugin that copy-pasted my code, update it and add documentation? Or make my own plugin? :)), but either way, the functionality is out there for you to use, and I don't think it needs to be go-specific.

**Comment by brenol** [comment]
@AndrewRadev  this is amazing. thank you a lot and I think you should release it as a plugin

perhaps surrounding is not the best name though, perhaps it should be something else? but thank you!

**Comment by AndrewRadev** [comment]
I did end up creating the plugin. Feel free to use it, if you'd like :).
