### ISSUE TITLE
go#complete#Info interface changed in v1.5

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#773]
### Expected behavior

Under `v1.4`, given the sample program

```go
package main

import "fmt"

func main() {
	fmt.Println("test")
}
```

with your cursor somewhere over `Println`, `:call go#complete#Info()` should echo the following to the status line:

```
vim-go: func Println(a ...interface{}) (n int, err error)
```

### Actual behavior

Under `v1.5`:

```
E119: Not enough arguments for function: go#complete#Info
```

Looks like the interface changed in `v1.5` but I couldn't see anything in the release notes?

### Steps to reproduce:

Per above

#### `vimrc` you used to reproduce:

A minimal `vim-go` setup is sufficient

#### vim version: 

`NVIM v0.1.3-355-g6b22a74`

#### vim-go version:

Per above

#### go version:

`go version go1.6 linux/amd64`

**Comment by fatih** [comment]
Hi @myitcv 
There was a recent change in those functions (refactoring). Just glancing over,  what gives `:GoInfo` ? I'll look into it, thanks for the report!

**Comment by myitcv** [comment]
@fatih - thanks. `:GoInfo` should I guess be considered the interface here. 

This was internal refactoring - I'll close this issue.
