### ISSUE TITLE
"vim-go: goimports does not support srcdir" and file clearing

### ISSUE THREAD

**Issue by velovix** [fatih/vim-go#775]
### Actual behavior

When GoImports is set to run when the file is saved (or perhaps more accurately, when GoFmt is run), vim-go complains with the following: "vim-go: goimports does not support srcdir." and the file is cleared and overwritten.

I have run `:GoUpdateBinaries`, but the problem persists.

### Expected behavior

GoImports would function normally without the error message, or at least not clear the file when it fails.

### Steps to reproduce:
1. Add `let g:go_fmt_command = "goimports"` to your .vimrc so that GoImports is triggered on save.
2. Open any Go file
3. Run `:w`

### Configuration

* `vimrc` you used to reproduce
```
syntax on
call pathogen#infect()
call pathogen#helptags()

" vim-go configuration
let g:go_fmt_command = "goimports"
```
* vim version: 7.4
* vim-go version: tip
* go version: go1.6 linux/amd64

**Comment by fatih** [comment]
Hi @velovix 

What happens if you run `goimports --help` from the terminal? I think it seems like you still have the old one. In the flags you should see the `-srcdir` flag, if that is not the case, you still have the old one.

**Comment by velovix** [comment]
Results of `goimports --help`:
```
$ goimports --help
usage: goimports [flags] [path ...]
  -d	display diffs instead of rewriting files
  -e	report all errors (not just the first 10 on different lines)
  -l	list files whose formatting differs from goimport's
  -srcdir dir
    	choose imports as if source code is from dir
  -w	write result to (source) file instead of stdout
```

It looks like I'm up to date.

**Comment by fatih** [comment]
What gives this ex command when you execute it from inside vim: 

```
:echo system("goimports --help")
:echo system("which goimports")
```

And from your terminal:

```
which goimports
```

Seems like your Vim picks up an old version somehow. This is not something I can reproduce, let's see if we can find something.

**Comment by velovix** [comment]
It looks like this wasn't an issue with vim-go after all. I found that any `echo system()` command would print nothing, so after some messing around, I decided to reinstall vim and now everything seems to be working fine again. I have no idea what happened, but I suspect that while I was experimenting with neovim, I must have messed up something. I can't seem to reproduce it, though. Thanks for working this through with me and sorry for the noise!

**Comment by PenguWin** [comment]
I have the same error like above everytime a vim-go command gets called.
Unfortunately reinstalling vim completely hasn't fixed the error for me.
The issue doesn't appear in the bash shell but in zsh it keeps to appear.

- Vim version 7.4
- OSX 10.11.5
- Go Version 1.6.2 darwin/amd64

**Comment by leakingtapan** [comment]
I just had the same issue and was able to reproduce it. The symptom happens when I am using tmux.

**Comment by tpudlik** [comment]
I ran into this problem, too.  My issue was apparently that `$GOPATH/bin` was not in PATH.  (How vim-go managed to find a version of goimport, however outdated, I'm not sure.)  Once I set `export PATH=$PATH:$GOPATH/bin` in `.bashrc`, everything worked fine.

**Comment by alaska** [comment]
I am also encountering this error, please reopen it.

This is on OSX El Capitan 10.11.6 and is *not* in a Tmux session (but it also occurs there)

`: echo system("goimports --help")`
```
usage: goimports [flags] [path ...]
  -cpuprofile string
        CPU profile output
  -d    display diffs instead of rewriting files
  -e    report all errors (not just the first 10 on different lines)
  -l    list files whose formatting differs from goimport's
  -local string
        put imports beginning with this string after 3rd-party packages
  -memprofile string
        memory profile output
  -memrate int
        if > 0, sets runtime.MemProfileRate
  -srcdir dir
        choose imports as if source code is from dir. When operating on a single
 file, dir may instead be the complete file name.
  -trace string
        trace profile output
  -v    verbose logging
  -w    write result to (source) file instead of stdout

Press ENTER or type command to continue
```

`:echo system("which goimports")`
```
/Users/alaska/go/bin/goimports

Press ENTER or type command to continue
```

And, from the terminal:
```
$ which goimports
/Users/alaska/go/bin/goimport
```

**Comment by beng** [comment]
I ran into this issue as well, but was able to fix it by running `GoUpdateBinaries`
