### ISSUE TITLE
GoCoverage fails silently when g:go_term_enabled = 1 in neovim

### ISSUE THREAD

**Issue by kron4eg** [fatih/vim-go#788]
### Actual behaviour
In neovim with `g:go_term_enabled = 1` enabled in `.vimrc`, `:GoCoverage` fail to highlight test covered parts.

### Expected behaviour
Should highlight covered and uncovered parts of source.

### Steps to reproduce:
* Add `g:go_term_enabled = 1` to vimrc
* run nvim
* open any go source file
* run `:GoCoverage`

### Configuration

* VIMRC for:
```vim
let g:go_term_enabled = 1
```
* neovim version: v0.1.3
* vim-go version: latest master (a4f44db at the moment)
* go version: 1.6.0

**Comment by fatih** [comment]
Thanks @kron4eg. This is a known bug that I also discovered. I'll look into it.

**Comment by fatih** [comment]
Hi @kron4eg This is fixed now. Please pull latest master. If it still persists please open another issue. Thanks!
