### ISSUE TITLE
jump to definition under cursor: go-def-tab

### ISSUE THREAD

**Issue by CodingBerg** [fatih/vim-go#791]
### Actual behavior

If the target buffer is already displayed in one of the tabs, instead of focusing that tab and jumping to where definition line begins, I got an error:

```
Error detected while processing function go#def#JumpMode[17]..<SNR>63_godefJump:
line   35:
E924: Current window was closed
```

After this, It goes to already opened tab at line 1.

### Expected behavior

It should focus already opened tab and jump to definition line no matter how many times I jump to the same definition using Go-To-Definiton.

### Steps to reproduce:

1. Open main.go (1st tab)
2. Go above some function and press `<Leader>+f`
3. It opens new tab and jumps to where definition line begins (2nd tab)
4. go back to 1st tab and press `<Leader>+f `again
5. It returns above error, and then goes to already opened tab (2nd tab), positioning at line 1, instead of jumping to where definition line begins

### Configuration

`au FileType go nmap <Leader>f <Plug>(go-def-tab)`

### VIM Version

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  9 2016 21:25:58)
```
Using pathogen as plugin manager.
Installed using brew, on OS X El Capitan, v10.11.4.

**Comment by fatih** [comment]
Hi @CodingBerg  

I Couldn't reproduce. Seems like you have a setting or plugin that infers with you settings. Please remove all plugins and try again. The current version works as expected.

**Comment by CodingBerg** [comment]
I had to install newer vim version because of neocomplete. And I did that using brew. When you use `vim` than you get the mentioned error. If you still use just `vi`, than everything is working fine. Also I tried to remove all plugins and clean config, still I'm having an error. Have you tried to reproduce with vi or vim?

**Comment by fatih** [comment]
@CodingBerg I've did. Here is a demo that shows it. I've recorded it for you. I'm using your own `,f` mapping:

![screen recording 2016-04-10 at 10 29 pm](https://cloud.githubusercontent.com/assets/438920/14412459/cbc800e6-ff6b-11e5-9e9f-b45ce79e7443.gif)

**Comment by CodingBerg** [comment]
Are you using same VIM ?

```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  9 2016 21:25:58)
MacOS X (unix) version
Included patches: 1-1707
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         -gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        -mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -F/private/tmp/vim20160409-25032-1dcoajt/vim-7.4.1707/Frameworks -o vim        -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc    

```

**Comment by CodingBerg** [comment]
I have only vim-go plugin enabled.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/8282230/14412663/b9d07ff2-ff67-11e5-9ca7-4c04c59dc482.gif)

**Comment by CodingBerg** [comment]
It works only with older vim editor which comes with OSX by default:
```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 28 2015 19:46:19)
Compiled by root@apple.com
```

But to use neocomplete, I need to install vim with lua support:

`brew install vim --with-lua`

which installs vim 7.4 (1707) with which I'm getting an error.
Same thing with MacVim 7.4-101 also installed using brew.

**Comment by fatih** [comment]
No, it also works with my current Vim version. I also installed it via Brew:

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 23 2016 15:44:07)
MacOS X (unix) version
Included patches: 1-1589
Compiled by Homebrew
```

**Comment by fatih** [comment]
@CodingBerg can you share your minimal vimrc please, let me test it to (It might be because you have a latest version of Vim maybe, still not sure)

**Comment by CodingBerg** [comment]
```
$ cat .vimrc 
execute pathogen#infect()
syntax on
filetype plugin indent on
colorscheme molokai
set number
let mapleader="\<SPACE>"
let g:go_fmt_command = "goimports"
au FileType go nmap <Leader>f <Plug>(go-def-tab)
```

**Comment by CodingBerg** [comment]
I've downgraded vim to your version 7.4.1589 and it works.
As you already have suggested it doesn't work for current Vim 7.4.1707.

This will be a good remedy for now. However, the issue will be present for every new user installing vim for the first time, or when upgrading to this particular version, or perhaps newer. I believe it needs a fix. Can this be fixed?


Steps how to downgrade:

1. I have uninstalled current vim and edit brew formula.
```
brew uninstall vim
brew edit vim
```

2. Then I have adjusted lines in order to download older version of vim (last known version that is working at this point of time).
```
url "https://github.com/vim/vim/archive/v7.4.1589.tar.gz"
sha256 "7a16d002958d76f8a14411fb826c96644aaef39b98bf38410c73fc5aee20c85e"
```

**Comment by fatih** [comment]
> However, the issue will be present for every new user installing vim for the first time, or when upgrading to this particular version, or perhaps newer. I believe it needs a fix. Can this be fixed?

I'll going to install the latest and test it, no worries :+1:

**Comment by mahendrakariya** [comment]
Faced the same issue with latest VIM.
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  2 2016 15:33:46)
MacOS X (unix) version
Included patches: 1-1864
Compiled by Homebrew
```

Downgrading to v7.4.1589 works fine.

**Comment by Ianvdl** [comment]
Having the same issue with the latest Vim compiled from source on Mint 17.3 (based on Ubuntu 14.04):

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 23 2016 20:30:17)
Included patches: 1-2243
```

Vim 8 is apparently due to be released soon if you'd rather investigate the bug for it instead of maintaining it for older versions. 

Thanks for vim-go, I use it daily.

**Comment by mcastelino** [comment]
-  Tested it with latest vim 8.0 build from sources. 
-  Using pathogen as plugin manager
-  No other plugin's except the default ones that are part of vim-go

vim: commit b56e7ff0dbbfa85361bdbc5b4a86ff8b57a7acbb

The issue still exists.

The vim built with configuration

```
 ./configure --with-features=huge \            
                   --enable-multibyte   \
                   --enable-rubyinterp  \
                   --enable-pythoninterp --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu    \
                  --enable-python3interp  \
                  --enable-python3interp  \
                  --with-python3-config-dir=/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu   \
                  --enable-perlinterp \
                  --enable-luainterp  \
                  --with-luajit \
                  --enable-gui=gtk2 --enable-cscope --prefix=/usr 
```

**Comment by lylex** [comment]
I ran into this issue when I got my vim upgraded to , so any workaround for it?

My vim version info is:

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
    Included patches: 1-1689
    Extra patches: 8.0.0056
