### ISSUE TITLE
Go to definition in file outside $GOPATH/src/dir/ returns out of range error

### ISSUE THREAD

**Issue by peterhellberg** [fatih/vim-go#797]
### Actual behavior

![screen shot 2016-04-13 at 21 37 18](https://cloud.githubusercontent.com/assets/565124/14506876/4a886d20-01c0-11e6-99b9-83b3cb76bffb.png)

And then the buffer is cleared and renamed `guru`

### Expected behavior

That either go to definition works for the standard library, or that it does nothing when the file is outside of a `$GOPATH/src/<dir>/`

### Steps to reproduce:

1 - Create a go file outside of a `$GOPATH/src/<dir>/`, lets say `$GOPATH/minimal.go`:
```go
package minimal

import "fmt"

func Example() {
	fmt.Println("minimal example")
}
``` 
2 - Type in `gd` (go to definition) when standing on fmt.Println

### Configuration

* vim version: NVIM 0.1.3
* vim-go version:  cd47345
* go version: 1.6

**Comment by supermarin** [comment]
Confirming on all vim versions (vim, macvim, nvim)

**Comment by fatih** [comment]
Thanks for the feed back @peterhellberg. This is now fixed in master.
