### ISSUE TITLE
<Plug>(go-run) doesn't run for the current file

### ISSUE THREAD

**Issue by apporc** [fatih/vim-go#800]
### Actual behavior

<Plug>(go-run) doesn't run the current file.
I have many .go files in the same directory, each of them contains "package main" and run on itself. When i do \<Plug\>\<go-run\> on one file, it complains "redeclaration of main".

I have to use "GoRun %" to replace <Plug>(go-run) to run just on the current file only.

### Expected behavior

As what said in the doc, (go-run) should "Calls `go run` for the current file".

**Comment by fatih** [comment]
Hi @apporc .The doc is wrong. It's for the whole package. To run for a single file you should use `:GoRun %`. Here is a mapping that runs it only for a single file you can use:

```
au FileType go nmap <leader>r  :<C-u>GoRun %<cr>
```.
