### ISSUE TITLE
vim-go auto imports can not correctly detect right imports

### ISSUE THREAD

**Issue by HackToday** [fatih/vim-go#804]
### Actual behavior

I am debugging docker code, and have one test file as this

https://github.com/docker/docker/blob/master/integration-cli/docker_cli_events_test.go#L14

when edit something in that test file and save, that 
`"github.com/docker/docker/daemon/events/testutils"` would disappear.

I need to manually disable vim-go to edit that file

### Expected behavior

vim-go should not delete that needed imports

> those code 
https://github.com/docker/docker/blob/master/integration-cli/docker_cli_events_test.go#L160
is needed for that

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. enable vim-go plugin
2. edit that file in projects
3. change that file and save

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version:
* vim-go version
* go version

**Comment by fatih** [comment]
Hi,

This is because you're using `goimports` for your gofmt save command. Please remove it from your vimrc and you're good to go. Thanks.

**Comment by HackToday** [comment]
hi @fatih why can't I use `goimports` ? Does `vim-go` have compatibility issue with `goimports` ?
