### ISSUE TITLE
:GoCoverage behaviour

### ISSUE THREAD

**Issue by bradleyfalzon** [fatih/vim-go#806]
Hi,

This is a small discussion on vim-go's newest :GoCoverage inclusion and it's default behaviour.

The original behaviour of [t-yuki/vim-go-coverlay](https://github.com/t-yuki/vim-go-coverlay) (as I understand it) via its (go-coverlay) would not toggle the coverage report, and instead rerun the test and highlight coverage. To clear the coverage report, you would use (go-clearlay).

Because this new behaviour deviates from the original vim-go-coverlay, I can only assume this behaviour is intentional or I am doing something wrong.

Is this the expected workflow:

:GoCoverage <- Execute tests and show coverage
:GoTest <- Rerun tests after a change (but this doesn't update the highlight coverage)
:GoTest
:GoCoverage <- Clear tests

Ideally, I'd prefer:

:GoCoverage <- Execute tests and show coverage
:GoCoverage <- Rerun tests after a change
:GoCoverageClear <- Clear  

Perhaps include a :GoCoverageToggle for the toggle behaviour

Am I doing something wrong/unintentionally?

### Actual behavior

When I run :GoCoverage a test is ran and code coverage syntax highlights test/untest lines.

When I execute :GoCoverage a second time, the code coverage is removed.

### Expected behavior

When I execute :GoCoverage a second time, I expected the tests to rerun and update code coverage highlight.

### Steps to reproduce:

Already discussed behaviour, if this is not enough, I'll add more.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce - not included as this may not be necessary.
* vim version: 7.4
* vim-go version: master 5c45ba9c45bc365dbd9177cc9c3de66105beac82
* go version 1.6.1

**Comment by bradleyfalzon** [comment]
Happy to send in PRs to adjust this behaviour if desirable.

**Comment by fatih** [comment]
Hi @bradleyfalzon 

This is a valid concern. We still have time to change it. So we might use the followings

```
:GoCoverage <- Execute tests and show coverage, additional calls reruns the tests
:GoCoverageClear <- Clears the coverage result
:GoCoverageToggle <- Runs tests and show coverage or clears the result if coverage is shown
```

**Comment by fatih** [comment]
Fixed and pushed to master. Thanks for the feedback.
