### ISSUE TITLE
Feature Request: gotests support

### ISSUE THREAD

**Issue by itsjamie** [fatih/vim-go#807]
It would be great to be able to run :GoGenerateTest which would build the basic scaffolding for table-driven tests.

You can find the tool here: https://github.com/cweill/gotests

Not knowing what's possible with vim as far as determining context, the way I would imagine it working:
* When inside a function in normal mode, a :GoGenerateTest would generate tests for that single function
* When inside visual mode, a :GoGenerateTest would generate tests for any functions inside the selection block.

If it's not possible, or it's hard to determine context, then `GoGenerateTestFunc` to match with `GoTestFunc` would be great.

Thank you for the awesome tool. It's the first time I've used vim for development.

**Comment by fatih** [comment]
Closing per my comment here: https://github.com/fatih/vim-go/pull/808#issuecomment-215553108 Thanks again for the feedback.
