### ISSUE TITLE
Goto definition still broken for packages

### ISSUE THREAD

**Issue by supermarin** [fatih/vim-go#809]
### Actual behavior

Typing `gD` on a package function (even system packages) like time.Tick says that my source file is not in the path where it actually is.

I haven't bisected too much, but at `a60a932` it was working as expected.

### Expected behavior

`gd` brings you to where the function is defined.

### Steps to reproduce:

1. Update vim-go to master
2. type `gd`
3. profit

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: macvim, --HEAD
* vim-go version `master`
* go version 1.6

**Comment by fatih** [comment]
Hi @supermarin 

Can you please provide a test case as the steps you said to reproduce are not reproducible. Also note that the shortcut is `gd` not `gD`.

**Comment by smreed** [comment]
I'm seeing similar behavior this morning. I'm editing a file in my home directory (this also repros inside of a `gb` project structure).

Using NVIM 0.1.4-dev

### vimrc:
```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'for': 'go' }
call plug#end()
```

### ~/test.go:
```
package main

import "fmt"

func main() {
	fmt.Println("hi")
}
```

### Repro:
1. cursor over `Println`
2. `gd`
3. `vim-go: guru: directory /home/sreed is not beneath any of these GOROOT/GOPATH directories: /usr/local/go/src, /home/sreed/go/src`

I can still use `gd` to jump to a function declared in the same file.

After reverting to the commit mentioned by @supermarin then `gd` works correctly.

**Comment by smreed** [comment]
The GOPATH reported by the `guru` error is different than what is being detected by `let $GOPATH = go#path#Detect()`.

**Comment by LK4D4** [comment]
@supermarin @smreed yeah, seems like guru can't inspect in files outside `GOPATH`, encountered that as well.

**Comment by supermarin** [comment]
@fatih oh sorry about that, edited the headline. It's indeed `gd`.

I updated the plugin to v1.6 and it seems like it's working again, just a bit slow.

**Comment by supermarin** [comment]
Steps to reproduce - nothing too fancy.
There's a project in the standard $GOPATH (e.g. ~/code/go/src/github.com/fatih/awesome),
that's using `godep` thus has some deps in the vendor/ dir.

`gd` was broken on system libraries though when opening this issue.
Before that it was broken for vendored libs, but I saw that was tracked / fixed [here](https://github.com/fatih/vim-go/issues/797).

**Comment by supermarin** [comment]
Update: seems like there's still some weird behavior;
It's probably guru's fault rather than vim-go.

```
vim-go: guru: no object for identifier
Press ENTER or type command to continue
```

**Comment by fatih** [comment]
@supermarin @LK4D4  your code needs to be beneath GOPATH. If it's not, `guru` will not work unfortunately. Closing this as there is not much I can do. Thanks!

**Comment by supermarin** [comment]
@fatih FWIW my code is beneath $GOPATH
