### ISSUE TITLE
commentstring not set for gohtmltmpl

### ISSUE THREAD

**Issue by louwers** [fatih/vim-go#810]
### Actual behavior

Vim's fold-markers and external plugins such as [vim-commentary](https://github.com/tpope/vim-commentary) use commentstring (see `:h commentstring`) to determine how to comment out a block of text for the current filetype. This is set for html, but not for gohtmltmpl.

The actual behavior is that vim inserts C-style comments in gohtmltmpl files.

```
      /* <div class="collapsed linky block"> */
```

### Steps to reproduce:

1. Enable `tpope/vim-commentary`.

2. Open gohtmltmpl file.

3. Press `gcc`.

Alternatively, create a fold-marker. I am not familiar with them.

### Solution

Include this line in vim-go:

```
autocmd FileType gohtmltmpl setlocal commentstring=<!--\ %s\ -->
```

**Comment by fatih** [comment]
Hi @louwers 

Thanks for the feedback. Can you please try https://github.com/fatih/vim-go/pull/813 and report if it works for you? Thanks.

**Comment by louwers** [comment]
Sorry for the late reply. Yes, it absolutely does. :+1:
