### ISSUE TITLE
Please provide docker image

### ISSUE THREAD

**Issue by psankar** [fatih/vim-go#811]
This is an enhancement request and not a bug.

Please provide official docker image of vim-go along with neocomplete, youcompleteme or some such auxiliary plugins already installed. Getting neocomplete + vim-go to work on mac has been very problematic (at least for me), with too many dependencies like brew, lua, macvim etc. having troubles. A official vim-go capable vim docker image for golang development, will be very helpful. Thanks for the nice project.

**Comment by fatih** [comment]
Hi @psankar 

Checkout https://medium.com/google-cloud/my-ide-in-a-container-49d4f177de#.fi16w4g6u

There are already some solutions when you search them on Google. Thanks for the feedback!
