### ISSUE TITLE
Feature req: Add a flag to tell gocode to autobuild

### ISSUE THREAD

**Issue by alienth** [fatih/vim-go#815]
As mentioned [in this comment](https://github.com/fatih/vim-go/issues/162#issuecomment-214637882), gocode can be configured to autobuild any sources which haven't been built, which will address people not getting autocomplete for stuff which isn't yet in `go/pkg`.

Microsoft/vscode-go uses this same feature. Relevant code is here: https://github.com/Microsoft/vscode-go/blob/932ccd1cf114cb38b5fef961756b3655bf06a0d4/src/goSuggest.ts#L139

The autobuild feature by gocode is described as experimental. As such it may need to be defaulted to off in vim-go and only enabled by people who want it.

**Comment by alienth** [comment]
Side note: Microsoft/vscode-go is considering on moving to guru. The author of gocode has indicated that it has [many problems and likely needs a rewrite](https://github.com/nsf/gocode/issues/307), but doesn't seem like they have the time to do it anytime soon. Microsoft may help get auto-completion into guru, as mentioned [here](https://github.com/fatih/vim-go/issues/162#issuecomment-214637882). Might be something to keep an eye on for vim-go.

**Comment by fatih** [comment]
Hi @alienth . This is now implemented on latest master. Just pull it to use. It'll be a part of the upcoming release. Thanks!
