### ISSUE TITLE
GoCoverageClear and GoCoverageToggle when syntax is off

### ISSUE THREAD

**Issue by fsouza** [fatih/vim-go#817]
### Actual behavior

I use vim with ``syntax off``. When I run GoCoverage, it turns syntax on for displaying the colors, but when I run GoCoverageClear or GoCoverageToggle it lets syntax on. Some screeshots:

*Right after opening the file:*

<img width="1391" alt="screen shot 2016-04-26 at 1 01 14 pm" src="https://cloud.githubusercontent.com/assets/108725/14825125/fdb9f902-0bae-11e6-92b6-acaae6498c8f.png">

*After running GoCoverage:*

<img width="1391" alt="screen shot 2016-04-26 at 1 00 59 pm" src="https://cloud.githubusercontent.com/assets/108725/14825141/0a591210-0baf-11e6-895b-bcb36e81a2b3.png">

*After running GoCoverageClear:*

<img width="1391" alt="screen shot 2016-04-26 at 1 01 10 pm" src="https://cloud.githubusercontent.com/assets/108725/14825147/12c81a2c-0baf-11e6-9243-552b9649e860.png">

### Expected behavior

GoCoverageClear would return the editor to the state it was before invoking GoCoverage.

### Steps to reproduce:

Run the following commands:

```
syntax off
GoCoverage
GoCoverageClear
```

### Configuration

* `vimrc` you used to reproduce: https://github.com/fsouza/vimfiles/blob/master/init.vim
* vim version: NVIM v0.1.5-24-gef205c3
* vim-go version: master, at commit e9df17fc70982012ab57d10e25206e0bd6c0cfcc
* go version: go1.6.2

**Comment by fatih** [comment]
This is a bug, should check if the user really uses syntax before I enable it. Good catch. I'll fix it.

**Comment by fatih** [comment]
This should be now fixed @fsouza. Thanks for the feedback.

**Comment by fsouza** [comment]
@fatih thanks for fixing it! :D
