### ISSUE TITLE
Slow scrolling when cursorline is enabled

### ISSUE THREAD

**Issue by moogle19** [fatih/vim-go#828]
### Actual behavior

If I activate vim-go syntax highlighting with:

```
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
```

and also activate `set cursorline` in my .vimrc, vim gets really slow.
Without the hightlights functions and/or cursorline it works perfectly.

### Expected behavior

vim should run smooth as always

### Steps to reproduce:

1.Create minimal vimrc:

```
syntax on
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
set cursorline
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
```

2.Put (only) vim-go into ~/.vim/bundle (if using pathogen)
3.Open a go file and start scrolling

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vim version: 7.4.1795
* vim-go version: master-branch
* go version: 1.6.2
* OS: OS X (if that matters)

**Comment by fatih** [comment]
Hi @moogle19 

There are many highlight groups, and Vim continuously tries to rematch them. That's why we have flags, to disable some of those. You can these settings to make it faster:

```
 set lazyredraw          " Wait to redraw
 syntax sync minlines=256
 set synmaxcol=300
 set re=1
```

Other than this there is not much we can do. Thanks for opening.

**Comment by moogle19** [comment]
Okay, thanks for the info and keep up the good work!
