### ISSUE TITLE
godef replacement guru doesn't handle files outside of of GOROOT/GOPATH?

### ISSUE THREAD

**Issue by aktau** [fatih/vim-go#829]
### Actual behavior

Often, I like to browse the source for golang/go:

$ git clone https://github.com/golang/go.git && cd go
$ vim src/runtime/mheap.go
... go to line 265 (	if s == nil || b < s.base() || b >= s.limit || s.state != mSpanInUse { )
...                                                          ^
...press 'gd' to invoke 'go to definition'
vim-go: guru: package "runtime" doesn't contain file /Users/aktau/github/golang/go/src/runtime/mheap.go
Write here what's happening ...

### Expected behavior

I expect it to go to the definition of `s.base()`. I seem to remember `godef` supported this.

### Steps to reproduce:

Already described above I hope.

### Configuration

- vim version: vim-7.4.1795
- vim-go version: 91ff811b62400e122b9411b9c7b3d695f06f2ec5 (Update CHANGELOG.md) (Fri Apr 29 00:18:52 2016 +0300)
- go version go1.6.2 darwin/amd64

**Comment by fatih** [comment]
Hi @aktau 

There is not much I can do as we use `guru definition`. This is the original query for my case:

```
guru  definition '/Users/fatih/go/src/runtime/mheap.go':#10211
```

Calling it will say:

```
guru: directory /Users/fatih/go/src/runtime is not beneath any of these GOROOT/GOPATH directories: /usr/local/go/src, /Users/fatih/Code/go/src
```

Simple main packages work outside GOPATH, but I think there is a special case for runtime. Can you please open an issue here https://github.com/golang/go/issues/ with the command above that matches your own filesystem? The title should start with `x/tools/cmd/guru: PROBLEM DESCRIPTION`.

Thanks!

**Comment by cherrot** [comment]
Is there any way to switch back to `godef`? Using `guru` would restrict my projects underneath $GOPATH. And it make me uncomfortable, especially some of them are not "pure Go" projects :(

**Comment by fatih** [comment]
@cherrot there is with the latest region:

https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L985

just set it to `godef` and you'er good to go.
