### ISSUE TITLE
Possibly use vim-projectionist?

### ISSUE THREAD

**Issue by docwhat** [fatih/vim-go#831]
In your documentation you mention how to setup `:A`, `:AV`, etc. up...

Instead, you could use [vim-projectionist](https://github.com/tpope/vim-projectionist) if it is installed...

```
if exists("g:loaded_projectionist")
  let g:projectionist_heuristics['*.go'] = {
      \ '*.go': { 'alternate': '{}_test.go', 'type': 'source' },
      \ '*_test.go': { 'alternate': '{}.go', 'type': 'test' }
      \ }
endif
```

(based on http://ahamidi.com/projectionist-for-go/)

You could actually replace the `go/alternative.vim` script with vim projectionist altogether.  The logic looks the same.  One less thing to maintain!

**Comment by fatih** [comment]
Hi @docwhat 

Thanks for the suggestion. vim-go's way is providing useful features with no big dependencies. I don't want to remove a really useful feature and point people to use an external plugin, set it up, and then use it. It's not something I want. Also we can change the way we provide the command. Thanks!

**Comment by docwhat** [comment]
No worries. If you are careful adding the above then it'll work for people with and without projectionist. 

I figured it out because your commands were overwritten by projectionists. Eg `:AV`

**Comment by fatih** [comment]
@docwhat we actually don't have `:AV`, `:A` or `:AS`. It's up to the user to add them on their own. For Example I have these in my own vimrc:

```
" I like these more!
augroup go
  autocmd!
  autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
  autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
  autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
augroup END
```

Thanks!
