### ISSUE TITLE
freevars is a normal mode mapping

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#832]
```vim
nnoremap <silent> <Plug>(go-freevars) :<C-u>call go#guru#Freevars(-1)<CR>
```

This mapping in `ftplugin/go/mappings.vim` cannot be used because it is a normal mode mapping whereas go-freevars is only usable with a selection. So it should be a visual mode mapping.

**Comment by fatih** [comment]
Fixed. An example mapping you can add to your vimrc to test it:

```
au FileType go xmap <leader>f  <Plug>(go-freevars)
```

**Comment by nhooyr** [comment]
alright thanks
