### ISSUE TITLE
OT: dropping support for Go from syntastic

### ISSUE THREAD

**Issue by lcd047** [fatih/vim-go#833]
Hi, I'm the maintainer of the [syntastic](https://github.com/scrooloose/syntastic) plugin, and I'm currently considering dropping support for Go files from syntastic in favour of `vim-go`.  If you happen to use both syntastic and `vim-go`, and / or you have strong feelings about the Go checkers in syntastic, please make your point at the [syntastic tracker](https://github.com/scrooloose/syntastic/issues/1759).  Thank you for your time, and sorry for the (mostly) off-topic post.

**Comment by fatih** [comment]
Thanks @lcd047 for opening the issue. Seems like you decided to completely turn off the checkers for Go with this commit: https://github.com/scrooloose/syntastic/commit/f280ff22207ffcddaabc8557d32ceaae03aa3975 

And on vim-go side we improved the Readme that contains to use quickfix:
https://github.com/fatih/vim-go/commit/5a846f35835656c52b0d3c639922dc548885ed31

I'm closing this issue now as I believe this issues are good enough to cover some of the pains people had in the past. Thanks!

**Comment by kevinburke** [comment]
> I'm closing this issue now as I believe this issues are good enough to cover some of the pains people had in the past. Thanks!

It'd be nice to have docs around the easiest way to provide syntastic-like functionality, e.g. "to display errors on save in the quickfix menu, add the following to your .vimrc"
