### ISSUE TITLE
autocomplete fails on gorm package.

### ISSUE THREAD

**Issue by akacase** [fatih/vim-go#835]
### Actual behavior

While using gorm (```"github.com/jinzhu/gorm"```), autocomplete (for this package) isn't functioning with neocomplete. The manual trigger (```C-x, C-o```) also does not function. Everything works with YCM.

```var DB *gorm.DB``` is a member of the main package and is globally accessible, when typing DB and then ".", completion doesn't work for package members, only local.

![screen shot 2016-05-02 at 1 12 29 pm](https://cloud.githubusercontent.com/assets/5959454/14962087/04afac0a-106b-11e6-9ca6-a5cb78fd21cb.png) 
### Expected behavior

When you import ```"github.com/jinzhu/gorm"``` into your project, it should autocomplete to members of the package, not just local members.

![screen shot 2016-05-02 at 1 11 32 pm](https://cloud.githubusercontent.com/assets/5959454/14962148/52ad5f6a-106b-11e6-8538-0f615506a553.png)
*showing that autocomplete still functions on packages aliased to single characters.*
### Steps to reproduce:

1. Make sure vim-go and neocomplete are installed
2. Create a simple project, import gorm (```"github.com/jinzhu/gorm"```)
3. Create global DB object `var DB *gorm.DB` or alias the form import
4. Check to see if autocomplete functions on that member.

### Configuration

* my `vimrc` 

```
runtime bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect()

source ~/.vim/util/neo.vim

syntax off
set backspace=indent,eol,start
set completeopt-=preview
set nocompatible
set wildmenu
set wildmode=list:longest
set ttyfast
set encoding=utf-8 nobomb

silent !mkdir -p ~/.vim/{backup,swp}/
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//

set background=dark
set hlsearch
set laststatus=2
set noerrorbells
set ruler
set showmode
set title
set showcmd
set wrap
set modeline
set shiftwidth=8
set tabstop=8
set nofoldenable
set scrolloff=10
set ignorecase

filetype on
filetype plugin on

let mapleader=","

map <Leader>l :nohlsearch<CR>
map <Leader>bd :bdelete<CR>

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

hi visual term=standout ctermfg=0 ctermbg=DarkBlue 
hi TabLine term=standout cterm=none ctermfg=DarkBlue ctermbg=0 
hi TabLineSel term=bold cterm=bold ctermfg=0 ctermbg=DarkBlue 
hi TabLineFill cterm=none ctermbg=0 
hi Search term=standout cterm=none ctermfg=0 ctermbg=DarkBlue 
hi IncSearch term=standout cterm=none ctermfg=0 ctermbg=DarkBlue 
hi MatchParen term=standout cterm=none ctermfg=0 ctermbg=DarkBlue 
```
* vim version: 7.4.1796
* vim-go version: latest
* go version: 1.6.2 darwin/amd64

If you think that this is an issue with neocomplete, I will file an issue there as well.

Thanks!

**Comment by fatih** [comment]
Hi @akacase 

You need to `go install` your package, otherwise `gocode`, the underlying completion tool doesn't work. Thanks for opening!

**Comment by akacase** [comment]
@fatih, heads up. It was my Godep folder, once removed, it started completing again.
