### ISSUE TITLE
Executing :GoFmt or :GoImports does not work on Windows

### ISSUE THREAD

**Issue by vrischmann** [fatih/vim-go#839]
### Actual behavior

Just updated vim-go on my windows machine, and looks like I can't execute any commands (I didn't test everything, just GoFmt and GoImports).

This is the error I get:

    Error detected while processing function go#fmt#Format..go#path#CheckBinPath:
    line   17:
    E117: Unknown function: exepath
    E15: Invalid expression: exepath(binpath)

I confirmed that it works before commit [62f8aa38e3686db79019d75117d35e905a74a6c5](https://github.com/fatih/vim-go/commit/62f8aa38e3686db79019d75117d35e905a74a6c5)    (which introduced exepath I think ?).

### Expected behavior

The command should not fail.

### Steps to reproduce:

1. Create a file with this:

    package main

    func main() {
        fmt.Println("foobar")
    }

2. Run `:GoImports`

### Configuration

Vim 7.4 on Windows 10.

**Comment by fatih** [comment]
Thanks @vrischmann 👍 . Fixed it back.
