### ISSUE TITLE
vim-go stopped working for go 1.4

### ISSUE THREAD

**Issue by bl-nero** [fatih/vim-go#841]
### Actual behavior

I've updated vim-go, and it stopped working for me. It started complaining about missing binaries (guru), and it looks like I can't install them, because things like `imports go/constant: unrecognized import path "go/constant"`.

### Expected behavior

Being able to run vim-go in my environment.

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. Run vim-go on Go 1.4.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version: 7.4, patches 1-1816
* vim-go version: Don't know how to check.
* go version: go1.4.2 darwin/amd64

**Comment by fatih** [comment]
Hi @bl-nero 

Vim-go works with Go 1.4, however seems like `guru` requires a higher version to be compiled. Here is a binary that I've compiled for you if you need it:

[guru-darwin-amd64.tar.gz](https://github.com/fatih/vim-go/files/254921/guru-darwin-amd64.tar.gz)

Put it somewhere where Vim-go can read it (i.e: PATH, GOBIN, etc..). You are also free to compile it with 1.6 and use it yourself. Thanks!.
