### ISSUE TITLE
why hf snippet not using http?

### ISSUE THREAD

**Issue by rahmatawaludin** [fatih/vim-go#842]
### Actual behavior

I want to use `hf` snippet. Currently, it was set like this..

````
snippet hf "http.HandlerFunc" !b
func ${1:handler}(w ResponseWriter, r *Request) {
	${0:fmt.Fprintf(w, "hello world")}
}
endsnippet
````

### Expected behavior

As I read many tutorial (like what I got from gopl.io), handler for http would look like this..

````
func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "hello world")
}
````

My question is, is this snippet without `http` is intentionally?

If not, should I make PR for this?

**Comment by fatih** [comment]
Hi @rahmatawaludin 

Good call. No it's not intentional, it should be a part of the `http` package. Happy to accept a PR if you make one ;)

**Comment by fatih** [comment]
Fixed with https://github.com/fatih/vim-go/issues/843
