### ISSUE TITLE
why "gd" is do nothing?

### ISSUE THREAD

**Issue by ljfuyuan** [fatih/vim-go#844]
my english is so poor,sorry ^ ^!

when i press "gd", there is nothing happend

the vim-go version is 1.7,but last version doing this well... 

i set the g:go_bin_path = $HOME."/vim-go/",and run ":GoInstallBinaries",the "goru" is exsited in go_bin_path

is there something wrong?

**Comment by fatih** [comment]
Do not set `go_bin_path`. Remove it please. Open you terminal and just write `guru`, if it's there it should work. Thanks!
