### ISSUE TITLE
vim-go gets too slow on Linux when save changes.

### ISSUE THREAD

**Issue by AdoHe** [fatih/vim-go#849]
### Actual behavior

Every time I use `:w` to save change, vim becomes quite slow, and it takes several minutes to complete the save process.

### Expected behavior

Write here what you're expecting ...

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1.
2.
3.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version:
* vim-go version
* go 1.6.2

I profiled this and just found this:
```
FUNCTION  SyntaxCheckers_go_go_GetLocList()
Called 1 time
Total time:  57.189625
 Self time:   0.000161

FUNCTION  <SNR>73_CacheErrors()
Called 1 time
Total time:  57.190993
 Self time:   0.000307

FUNCTION  <SNR>73_BufWritePostHook()
Called 1 time
Total time:  57.192356
 Self time:   0.000033

FUNCTION  242()
Called 1 time
Total time:  57.189838
 Self time:   0.000066
```

**Comment by fatih** [comment]
Hi @AdoHe 

It's due syntastic. Check out the README to solve it: https://github.com/fatih/vim-go#using-with-syntastic

Thanks.
