### ISSUE TITLE
hysteresis effect in `:w` -- saving takes a good while

### ISSUE THREAD

**Issue by sbinet** [fatih/vim-go#850]
### Actual behavior
Saving a `.go` file with the `goimports` hook takes a while after having saved a few `.go` files multiple times (ie: at first, it takes a reasonnable time, but after having saved ~5-10 times a `.go` file, it builds up to ~5-10 **minutes**, even when only whitespace has been added.)

### Expected behavior
Saving a `.go` file shouldn't take ~5-10 minutes when hitting `:w`.

### Steps to reproduce:

here is my `.vimrc`:
 https://github.com/sbinet/dot-config/blob/master/vim/vimrc

take a simple `main.go` file, save multiple times.
saving time should grow with the number of times you hit `:w`.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vim version: 7.4.1797-1 + `X11`
* vim-go version: 1ec3373f2fafaf6f0614f999bce831e2c51106f8
* go version: `go version go1.6.2 linux/amd64`

**Comment by sbinet** [comment]
@tbellembois, I believe you have the same issue.

**Comment by fatih** [comment]
@sbinet can you remove please this line from your vimrc:

```
au FileType go au BufWritePre <buffer> GoImports
```

Also be sure you configured `syntastic` correctly if you have installed it. From the virmc it seems like you don't have it, but I'll ask again to be sure :)

Other than this there shouldn't be a problem on vim-go side. I've just tried and it works without any problem. I would definitely catch it as I'm using it for 5-6 hours daily.

**Comment by sbinet** [comment]
no, I don't have `syntastic`.
and, yes, commenting out the `GoImports` line seems to prevent the hysteresis effect to build up.

replacing it with:
```vim
let g:go_fmt_command = "goimports"
```

fixed everything.

Thanks for the prompt support :)

**Comment by tbellembois** [comment]
Thanks a lot ! I had the same problem. Even with `syntastic` it works like a charm !
