### ISSUE TITLE
open the Godoc in browser

### ISSUE THREAD

**Issue by thiberaw** [fatih/vim-go#852]
Cursor is under **package**  keyword and I _\<leader\>gb_
The browser opens at [https://godoc.org/package#](https://godoc.org/package#) instead of [https://godoc.org/?q=package](https://godoc.org/?q=package) so I get to a Not Found Page.

**Comment by fatih** [comment]
@thiberaw please give more information. What is `<leader>gb` doing?

**Comment by thiberaw** [comment]
@fatih :open the Godoc in browser

**Comment by fatih** [comment]
@thiberaw please reopen the issue according to the [template issue](https://github.com/fatih/vim-go/blob/master/.github/ISSUE_TEMPLATE.md) , this doesn't help me unfortunately. Thanks.

**Comment by thiberaw** [comment]
ok, I will reopen this tonight
