### ISSUE TITLE
GoDef doesn't work when there are build tags

### ISSUE THREAD

**Issue by jzila** [fatih/vim-go#853]
### Actual behavior

I'm in a file with a build tag, attempting to `:GoDef` on a symbol defined in a _different_ file with that same build tag. This results in the following error message:
```
vim-go: guru: no buildable Go source files in /home/john/repos/go/src/github.com/test/foo                                                                                                             
```

### Expected behavior

I'm taken to the definition.

### Steps to reproduce:

1. Create "foo.go":
```go
// +build foo

package foo

func foo() error { return nil }
```
2. Create "bar.go":
```go
// +build foo

package foo

func bar() { _ = foo() }
```
3. On the symbol `foo` in `bar.go`, attempt to `:GoDef`.

### Configuration

nvim 0.1.3
vim-go 1.7
go 1.6

### Additional Information

This functionality used to work before the switch to Guru.

**Comment by sillyousu** [comment]
Have you set the build tags?
https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L565

**Comment by fatih** [comment]
HI @jzila 

You have to pass your build tags  via `:GoGuruTags` or the variable `g:go_guru_tags` because guru expects them. Checkout the docs please fore more info:

> This functionality used to work before the switch to Guru.

Unfortunately this is the way `guru` works. Maybe we can parse the first line of the package and add the tags ourself automatically. Can you open an issue for `guru` issue tracker (https://github.com/golang/go/issues)  to ask whether there is a way to not count the tags if possible ?

Thanks!

**Comment by jzila** [comment]
Thanks for the quick responses! I suspect the golang people will say that it's not go-like to try to guess the tags. This is especially true when there could be an ambiguity, for example when build tags are used to implement the same functionality on multiple systems (+build windows, +build linux).

I'll try to hack around to see if there's a way to parse them.

P.S. Amazing work on vim-go, @fatih! It's really fantastic.

**Comment by fatih** [comment]
Thanks for the response @jzila Closing this as there is already a solution to this (`:GoGuruTags`).

**Comment by noprysk-ua** [comment]
`:GoGuruTags` is now removed in favor of `:GoBuildTags` https://github.com/fatih/vim-go/blob/master/CHANGELOG.md.
