### ISSUE TITLE
vim.go: $GOPATH is not set

### ISSUE THREAD

**Issue by ghost** [fatih/vim-go#86]
@fatih I have installed vim-go as instructed in the github repo using pathogen.But every time i try to open vim it shows message displaying 
vim.go: $GOPATH is not set
Press ENTER or type command to continue

Plus vim-go plugin didn't work with vim also.

**Comment by mildred** [comment]
I'm having the same problem and I set my GOPATH in my shell initialisation files using backticks. When I run `:echo $GOPATH` I get the value I expect. However vim-go still tells me $GOPATH not set.

**Comment by heipacker** [comment]
i encount thiis problem too, but when i config the GOBIN var, this solved.

**Comment by netdigger** [comment]
In fact, user should use "export GOPATH=xxxx" in ~/.profile to set GOPATH. If you use "GOPATH=xxxx" and run echo $GOPATH, you can get the expect value, but vim-go can't get GOPATH

**Comment by bpo217** [comment]
@netdigger This is important, and I didn't catch it for a while... But this was my problem initially.  If you don't do this there is some strange behavior with $GOPATH in vim.

**Comment by rcdosado** [comment]
i did what netdigger had advised but still it doesnt work, here are my go environment vars:
`GOARCH="amd64"
GOBIN="/usr/bin/go"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/m1k3y/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build731985509=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
`

**Comment by Carpetsmoker** [comment]
You'll need to be clearer than "it doesn't work" @rcdosado. What did you do? What "doesn't work"?

Also note that a few things have changed since this issue was first created. `$HOME/go` is now used as `GOPATH` if it's not explicitly set, and you don't need to set `GOPATH` yourself anymore.

**Comment by zipizap** [comment]
The error xxx happened to me too when trying ":GoInstallBinaries"
I am not certain that my vim  installation is in good shape, and I have go via a snap package in ubuntu 18.04
What seemed to make it work, was to:
  - exit tmux or screen
  - in a bash session, call vim with `GOPATH=$HOME/go vim`  - and then `:GoInstallBinaries` worked this time

Just sharing the experience

**Comment by arumals** [comment]
> The error `vim.go: $GOPATH is not set and 'go env GOPATH' returns empty` happened to me too when trying ":GoInstallBinaries"
> I am not certain that my vim installation is in good shape, and I have go via a snap package in ubuntu 18.04
> What seemed to make it work, was to:
> 
> * exit tmux or screen
> * in a bash session, call vim with `GOPATH=$HOME/go vim`  - and then `:GoInstallBinaries` worked this time
> 
> Just sharing the experience

This worked for me.
