### ISSUE TITLE
:GoCoverage highlight colors broken on xterm

### ISSUE THREAD

**Issue by SpComb** [fatih/vim-go#863]
### Actual behavior

Running vim on a remote machine over SSH from an Ubuntu laptop's xterm or gnome-terminal:

![20160519-vim-go-coverage-xterm-editing](https://cloud.githubusercontent.com/assets/3950373/15394749/6112f4e6-1ddd-11e6-91a1-29976cb4d8a3.png)

Using  `:GoCoverage` to highlight covered/uncovered lines in a trivial `.go` file, all syntax highlighting for the file disappears:

![20160519-vim-go-coverage-xterm-broken](https://cloud.githubusercontent.com/assets/3950373/15394756/6ea28bf8-1ddd-11e6-8f4d-ba116dfb0c0f.png)

### Expected behavior

I am expecting to see covered/uncovered lines highlighted in different colors.

I suspect the `highlight ctermfg=...` colors used in `coverage.go` are somehow wrong, with the following patch:

	diff --git a/autoload/go/coverage.vim b/autoload/go/coverage.vim
	index 5a0c012..1d0afd1 100644
	--- a/autoload/go/coverage.vim
	+++ b/autoload/go/coverage.vim
	@@ -219,8 +219,8 @@ function! go#coverage#overlay(file)
	 
	     syntax manual
	     highlight normaltext term=bold ctermfg=59 guifg=#75715E
	-    highlight covered term=bold ctermfg=118 guifg=#A6E22E
	-    highlight uncover term=bold ctermfg=197 guifg=#F92672
	+    highlight covered term=bold ctermfg=green guifg=#A6E22E
	+    highlight uncover term=bold ctermfg=red guifg=#F92672
	 
	     " clear the matches if we leave the buffer
	     autocmd BufWinLeave <buffer> call go#coverage#Clear()
	
The highlighting seems to work better:

![20160519-vim-go-coverage-xterm-working](https://cloud.githubusercontent.com/assets/3950373/15394829/a51fa97c-1ddd-11e6-824b-742d21c14087.png)

I have no idea how color terminals are supposed to behave in vim, so I don't know if this is an appropriate fix.

### Configuration

* vim version: 2:7.4.712-2ubuntu4
* vim-go version: v1.6
* go version: go1.5.1 linux/amd64

**Comment by fatih** [comment]
Hi @SpComb 

Thanks for the feedback. I've pushed the fix to master as you said. It's due xterm and vim problems (check out `:help ctermfg` for more info).
