### ISSUE TITLE
feature request: don't open file with syntax error in current tab if file is open in other tab

### ISSUE THREAD

**Issue by marcopeereboom** [fatih/vim-go#865]
### Actual behavior

I have go-install mapped to `m` so with `,m` code is saves and installs program I am working on.  If there is a compilation error then the error is displayed.  So far so good but, I really want the error to be displayed in the tab where that file is already open (if that's the case of course).  I tend to end up typing :e# all day long because of this.
### Expected behavior

Open error in corresponding tab.
### Steps to reproduce:

This is the config required to trigger issue:

    let mapleader=','
    au FileType go nmap <Leader>m :wa<CR> <Plug>(go-install)

1. Open file a.go in vim
2. :tabnew b.go
3. in b.go write a syntax error.
4. switch to tab that contains a.go by typing :tabp
5. `,m` (to write code and install)

Now you'll end up with 2 tabs containing b.go.

### Configuration
- `vimrc`: only two lines matter that matter are pasted in steps to reproduce.
- vim version:VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 10 2016 14:27:40) Included patches: 1-1829
- vim-go version: 48cc65dfbd3172b989f82c8b67ceb6d88db3c522
- go version: go version devel +495e3c6 Tue May 17 04:02:11 2016 +0000 openbsd/amd64

**Comment by Carpetsmoker** [comment]
I think that using `set switchbuf=usetab` should fix this @marcopeereboom? It seems to work as expected in my quick test.

----

Original message for context, before I discovered that the `switchbuf` setting exists:

I'm not sure how to best fix this; this is kind of a limitation of how Vim and tabs work. It's not just a problem with vim-go but also with Syntastic or ALE.

I think that the way to fix this is to override how `<CR>` and similar mappings behave in the quickfix and location list.

One of the issues is that tabs are kind of an "afterthought" in Vim; you're supposed to use buffers to work with multiple files, and many people will tell you that this is the One True Way™ to use Vim (I personally also use tabs a lot).

**Comment by Carpetsmoker** [comment]
I'll close this for now; AFAIK `switchbuf` should do what you want. Feel free to comment if you have further problems or questions and we can reopen this issue.
