### ISSUE TITLE
:GoRename with cgo can't find indentifiers

### ISSUE THREAD

**Issue by ashb** [fatih/vim-go#867]
### Actual behavior

Edit a file with `import "C"` and try to use the `:GoRename` command. I get an error:

```
vim-go: gorename: identifier not found
```

### Expected behavior

It works without error and renames the file

### Steps to reproduce:

Sample file:

```go
package main

// #include <unistd.h>
import "C"
import "fmt"

func main() {
	foo := 1
	C.close(2)
	fmt.Println(foo)
}

```

1. Place the cusor on foo
2. Run `:GoRename foo2`

I also found a *really* odd case where my .go file was replaced with the mangled version produced by cgo, removing my cgo "special" comments, adding in extra structs etc but I can't reproduce that one now. If i see it again I'll raise another issue.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 28 2015 12:27:10)
* vim-go version:  48cc65dfbd3172b989f82c8b67ceb6d88db3c522 etc/vim/bundle/vim-go (v1.6-49-g48cc65d)
* go version: go version go1.6 darwin/amd64

**Comment by fatih** [comment]
Hi @ashb 

Unfortunately this is due the underlying tool `gorename`. I've just tried myself from the terminal with the following command (I've saved your file as `demo.go`):

```
$ gorename -v --offset demo.go:#78 -to bar
```

And it gives the error:

```
gorename: Loading package: demo
gorename: identifier not found
```

Can you please open an issue for gorename under https://github.com/golang/go/issues, with my command above (you also can test it yourself to make sure it really doesn't work). Thanks!

**Comment by ashb** [comment]
Thanks - have done!

**Comment by lazutkin** [comment]
For completeness golang/go#15793
