### ISSUE TITLE
vim.go: $GOPATH is not set

### ISSUE THREAD

**Issue by xDinomode** [fatih/vim-go#870]
### Actual behavior

When I run :GoInstallBinaries I get:

> vim.go: $GOPATH is not set

but it is set because in the terminal I run $GOPATH and get /home/dino/work: Is a directory

and I've googled everything from putting that path in my .bashrc and every other dumb place linux sets its variables 

BTW: I installed this by installing Vundle which I've never used.

### Expected behavior

To work

**Comment by fatih** [comment]
This is not a vim-go problem. Be sure you really have set up your `GOPATH` and VIM can pick it up. I suggest to ask it to your OS forums or in IRC. Thanks.

**Comment by xDinomode** [comment]
Nah Il;l just uninstall your crap

**Comment by fatih** [comment]
Go ahead Troll, I don't care ;)
