### ISSUE TITLE
Dropped from location list (nonvalid filename)

### ISSUE THREAD

**Issue by kevinburke** [fatih/vim-go#877]
### Actual behavior

When I run a test with a failure, I get the following message:

 Dropped "/Users/burke/code/go/src/github.com/Shyp/rickover/test/server/test-tools.go" from location list (nonvalid filename)vim-go: --- FAIL: TestFailedUnretryableAr
chivesJob (0.01s)

### Expected behavior

I expect to see a normal "test failed" message with details about the failure.

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. Check out this repository: github.com/Shyp/rickover
2. Open test/services/status_callback_test.go
3. In the bottom most test change ErrNotFound to nil, or change `qj.Attempts - 1` in the previous test to a random value like 29
4. Run `:GoTest` or `:GoTestFunc`

I expect to see a Fail() message, maybe with output about why the test failed. Instead I get this:

<img src="https://monosnap.com/file/Nrgh1PryysSEUcC1yVNykuXxFF3OWc.png">

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce - Removed all lines from it, except pathogen#infect with only the vim-go plugin in the bundle directory.
* vim version: neovim 1.4
* vim-go version: commit e9f44d9
* go version: go version devel +81a8f1a Mon May 30 05:24:16 2016 +0000 darwin/amd64

**Comment by fatih** [comment]
Hi @kevinburke 

Can you please provide the test output from your terminal without using `vim-go` at all? I think it's because you're using a non Go standard test suite? We only support `go test`  and the `testing` package.

**Comment by kevinburke** [comment]
@fatih - here's what I get when I run `go test ./test/services` (I removed some irrelevant console output from the run code)

```
$ go test ./test/services
--- FAIL: TestStatusCallbackFailedAtMostOnceArchivedRecordExists (0.00s)
	test-tools.go:65: status_callback_test.go:87: [Queued job not found] != [7]
FAIL
FAIL	github.com/Shyp/rickover/test/services	0.267s
```

This is test-tools.go: https://github.com/Shyp/rickover/blob/master/test/test-tools.go, or the package of assertions here: https://godoc.org/github.com/Shyp/rickover/test

We're still using `t.Fatal` and company, just calling them from a helper method.

**Comment by kevinburke** [comment]
(this is also the approach taken by the Boulder project: github.com/letsencrypt/boulder)

**Comment by fatih** [comment]
```
    test-tools.go:65: status_callback_test.go:87: [Queued job not found] != [7]
```

This is not a valid `testing` package. Which file belongs it to? `test-tools.go` or  `status_callback_test.go`? That's the error itself.

**Comment by kevinburke** [comment]
> Which file belongs it to? test-tools.go or status_callback_test.go? That's the error itself.

It comes from here: https://github.com/Shyp/rickover/blob/master/test/test-tools.go#L62-L67. As I understand it, any test where the `t.Fatal` or the `t.Error` is not generated in the function body will have this problem. 

(we use that helper because a lot of team members aren't super familiar with Go, so I wanted to make testing a little more familiar/friendly)

**Comment by tsne** [comment]
> [...] any test where the t.Fatal or the t.Error is not generated in the function body will have this problem.

That is not completely correct. If `t.Fatal` or `t.Error` are called from another function and this function replaces the output by the position of the call, then it should work correctly.

If you want to implement it that way, you can have a look at facebook's [ensure](https://github.com/facebookgo/ensure).

**Comment by fatih** [comment]
I'm closing this as this is really not a vim-go problem. We don't support third party wrappers or anything else. The errorformat is strict and that means we only support the `testing` packages errorformat. Thanks.
