### ISSUE TITLE
add missing mappings to vim docs and create some more mappings

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#880]
Noticed that a few mappings such as `<go-import>` and `<go-imports>` are missing from the vim docs.

I also noticed that we are missing a `:GoDrop` mapping or a `:GoFmt` mapping.

**Comment by fatih** [comment]
Thanks @nhooyr 

Fixed with https://github.com/fatih/vim-go/commit/acb2d8c91d94a383b68a429273c2f51d11a2d242

I don't think we should add mappings for both :GoFmt or :GoDrop. First one is always used with autosave and the second is barely used anymore because of `goimports` thanks.
