### ISSUE TITLE
vim-go requires vim-enhanced on Fedora 23

### ISSUE THREAD

**Issue by ae6rt** [fatih/vim-go#884]
I discovered that vim-go wants vim-enhanced on Fedora 23, vs vim-minimal.  The latter was what was installed out of the box.  Maybe it's worth pointing this out in the docs?  Or maybe I missed it?

Many thanks for vim-go.

**Comment by fatih** [comment]
Hi @ae6rt 

What is the difference between vim-enhanced and vim-minimal? I'm not sure why it either depends as I've heard these packages the first time. I'm not using Fedora. vim-go only depends on certain binaries which are already state in the Readme. Besides that it doesn't have any other dependencies and should just work. If you give more specific details I'm more than happy to improve the Readme. Thanks!
