### ISSUE TITLE
completion problem when cursor at **

### ISSUE THREAD

**Issue by tidezyc** [fatih/vim-go#885]
when cursor at char of `**` in a `.go` file, I get error shown this:
<img width="617" alt="screen shot 2016-06-04 at 11 28 25" src="https://cloud.githubusercontent.com/assets/1592766/15797406/76034ec8-2a49-11e6-9e9a-7bf4283f9a0f.png">
 how can I fix this!
 thx

**Comment by fatih** [comment]
@tidezyc please reopen the issue with the issues template. Unfortunately you didn't answer those questions and I don't have zero information what you're using, what you did, etc.. Thanks!
