### ISSUE TITLE
Syntastic Inline error gutter markers

### ISSUE THREAD

**Issue by apriendeau** [fatih/vim-go#886]
### Actual behavior

I no longer can receive gutter markers in Neovim or Vim when I save a file and there is a build error.

### Expected behavior

I use to receive gutter markers showing the line where the build occurred not just a quick-list after saving a file.

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. Create a build error with syntastic plugin installed 
2. When writing a bugger, there should be a gutter marker showing error on the line.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

```
let g:go_fmt_command = "goimports"

let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
let g:go_list_type = "quickfix"

let g:go_highlight_methods = 1
let g:go_highlight_functions = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
```

* vim version: NVIM v0.1.5-473-g999590b
* vim-go version: Master
* Go 1.6

**Comment by bradleyfalzon** [comment]
Your vimrc configuration suggests that go checks are only performed using the `golint`, `govet` and `errcheck` commands, and not `go` (`go` runs `go build`, provides Syntastic the information on where the errors are). This configuration is usually used when building on each save is too slow and not required. Running `:SyntasticCheck` should probably show you your build errors.

But recently Syntastic has turned off from showing these build errors by default on save (see my comment in [#848 comment](https://github.com/fatih/vim-go/issues/848#issuecomment-218924693).

So I'm not sure whether you've added the `g:syntastic_mode_map` and `g:syntastic_go_checkers` configurations in your vimrc trying to debug your issue, or whether they've always been there - and therefore Syntastic should never have been showing you those build errors.

I'd recommend you start by removing or commenting these lines from your vimrc and seeing if this fixes your issue:

```
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
```

**Comment by apriendeau** [comment]
So you answer was in combination of removing those lines and adding `go` to the checkers in the file. 

So I removed the second line and modified the first line to be:
`let g:syntastic_go_checkers = ['govet', 'errcheck', 'go']`
