### ISSUE TITLE
Syntastic integration not working

### ISSUE THREAD

**Issue by meowgorithm** [fatih/vim-go#889]
### Actual behavior

Syntastic (say, `:SyntasticCheck`) no longer reports errors. `:GoVet` and `:GoLint` still report as normal.

### Expected behavior

`:SyntasticCheck` normally highlights and outlines errors. `:SyntasticInfo` reads:

    Syntastic version: 3.7.0-144 (Vim 704, Darwin)
    Info for filetype: go
    Global mode: active
    Filetype go is active
    The current file will be checked automatically
    Available checkers: go gofmt golint gometalinter govet
    Currently enabled checkers: -

### Steps to reproduce:

1. Create a new go file.
2. Enter some uncompilable nonsense.
3. Save. Syntastic will not report errors, however `:GoVet` and `:GoLint` will.

### Configuration

* `vimrc`: https://gist.github.com/meowgorithm/f49ae3dbfb3f5e948c0673bcab747330
* vim version: 7.4 (latest in Homebrew on OS X at the time of writing)
* vim-go version: 1.6 (latest at the time of writing)
* go version: go1.6.2 darwin/amd64

**Comment by fatih** [comment]
Checkout https://github.com/fatih/vim-go/issues/886 and the Readme please. vim-go is not responsible for syntastic so there is not much I can  do. Thanks!

**Comment by meowgorithm** [comment]
Ah, wonderful. Sorry about that. Wonderful work you've done with go-vim, by the way.
