### ISSUE TITLE
doc and spelling errors

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#890]
`g:go_highlight_fields` and `g:go_highlight_structs`'s documentation is switched.

Also, `g:go_highlight_fields` is mistakenly spelled as `go:go_highlight_fields` in vim-go.txt and the changelog.

In fact it is incorrectly spelled in `syntax/go.vim`

**Comment by fatih** [comment]
Thanks @nhooyr. The doc is fixed and the syntax file was fixed https://github.com/fatih/vim-go/pull/892
