### ISSUE TITLE
vim-go package is not inside GOPATH src

### ISSUE THREAD

**Issue by thrisp** [fatih/vim-go#891]
### Actual behavior

No error checking after update to new. 

:GoErrCheck returns

'vim-go package is not inside GOPATH src'

### Expected behavior

Automatic error checking on file save

### Steps to reproduce:

See that error checking isn't running automatically on save, run :GoErrCheck

### Configuration

just using go1.6

my config from using this for a while

"let g:go_autodetect_gopath = 0
let g:go_fmt_command = "goimports"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_structs = 0
let g:go_highlight_interfaces = 0
let g:go_highlight_operators = 0
let g:go_highlight_build_constraints = 1
"let g:go_fmt_fail_silently = 0
"let g:go_fmt_autosave = 1
let g:go_bin_path = "/home/name/.gvm/pkgset/go1.6/global/bin"

**Comment by fatih** [comment]
Hi @thrisp 

This is a normal error. Your package needs to be under `GOPATH`. This is not a vim-go limitation, it's an errcheck requirement, see: `https://github.com/kisielk/errcheck#use`

**Comment by caoruidong** [comment]
Which package do you mean? The errcheck package? It is already in root/go/src/github.com/kisielk/errcheck, my GOPATH is /root/go

**Comment by Carpetsmoker** [comment]
@caoruidong No, the package you're working on and want to run `:GoErrCheck` on.

**Comment by caoruidong** [comment]
@Carpetsmoker Got it! Thank you so much!
