### ISSUE TITLE
Error Checker Doesn't Work

### ISSUE THREAD

**Issue by Integralist** [fatih/vim-go#898]
### Actual behavior

I write invalid code, but go-vim doesn't pick it up unless I manually run `:GoErrCheck`.

> Note: this used to work fine previously
> I've updated the vim-go plugin as well as all the binaries
> But this hasn't resolved the issue

### Expected behavior

I should write invalid code and when I write the buffer `:w` vim-go should automatically open up a pane to show me the errors in my code (especially considering I'm using the gometalinter for configuring multiple checkers)

I would expect errors to be highlighted the moment the file is open and not after writing the buffer (`:w`), as that's what the plugin used to do.

### Steps to reproduce:

Here is my reduced test case `app.go` (yes this is not even close to being valid Go code):

```go
package main

func main() {
        var num = 123
        alert(num)
}
```

Now if I manually run `:GoErrCheck` (which I don't know if this is what was happening originally, I just saw it as one of the listed commands available << it doesn't give as useful output though :-( ), it returns:

```
app.go | 5 col 2 | undeclared name: alert || error: failed to check packages: could not type check: couldn't load packages due to errors: github.com/integralist/test-vim-go
```

...which is at least a little bit closer to indicating there is a problem with the code.

> UPDATE: just seen in the Wiki that `:GoErrCheck` isn't what I thought it was (`Checks for unchecked errors in you current package. Errors are populated in quickfix window`)

### Configuration

Here is my reduced test case `.vimrc`

```viml
syntax on
set nocompatible
set nobackup
set nowritebackup
set noswapfile
set hidden
execute pathogen#infect()
filetype plugin indent on
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
```

Here is my Vim version output:

```bash
$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Apr  5 2016 14:53:37)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

Here is my Go version:

```bash
$ go version
go version go1.6 darwin/amd64
```

Here is my vim-go version:

```bash
$ cd ~/.vim/bundle/vim-go/
$ git tag | tail -n 1
v1.7.1
```

**Comment by bradleyfalzon** [comment]
See #848 and #896 for some discussions on this, as they maybe related.

**Comment by Integralist** [comment]
Thanks @bradleyfalzon that did the trick :-)

https://github.com/Integralist/dotfiles/commit/83c03b0f850f8faf5800f936dc78c3b4b8745bee
