### ISSUE TITLE
GoCoverage fails with cannot find package '-coverprofile'

### ISSUE THREAD

**Issue by sir-wiggles** [fatih/vim-go#899]
### Actual behavior

Executing :GoCoverage causes the following error:

    vim-go: FAILEDvim-go: can't load package: package '-coverprofile': cannot find package "'-coverprofile'" in any of: 

### Expected behavior

Coverage report to overlay buffer

### Steps to reproduce:
Minimal main.go
 
```go
package main

import "fmt"

func main() {
    fmt.Println("")
}
```
Minimal main_test.go

```go
package main

import "testing"

func TestHandler(t *testing.T) {
    main()
}
```

`:GoCoverage`

### Configuration

I can run coverage outside of vim just fine.

`:GoTest` works as expected

I know support for `neovim` is in `beta` but I poked around in the `coverage.vim` file and saw conditions for `nvim` so figured that it may be supported.  That's about the extent of my `vimscript` debugging sadly.

* `vimrc` you used to reproduce

```    
call plug#begin('~/.config/nvim/plugged')
Plug 'failt/vim-go'
call plug#end()
```

* vim version:
neovim 0.1.4

* vim-go version
vim-go 1.7.1

* go version
go version go1.6.2 darwin/amd64

**Comment by fatih** [comment]
Hi @sir-wiggles 

Just discovered this myself too in `Neovim`. If you run it in `Vim` you'll see there is no problem. Must be something that was introduced with the latest version. I'll take a look at this. Thanks.

**Comment by fatih** [comment]
Alright it's broken due this line: 

https://github.com/fatih/vim-go/pull/869/files#diff-a3998a862a20bc1665a15c84f401349fR200

Not sure how to fix it without pulling it out. We only need to escape the file after `-coverprofile` , but not the flag itself. Checking now.

**Comment by fatih** [comment]
The fix in master. Thanks for the feedback.

**Comment by sir-wiggles** [comment]
Wow you're fast! I was taking my first dive into vim scripting with this and was WAY off. 😛

Thanks for the amazing work!
