### ISSUE TITLE
Gofmt fails to find dependencies in the vendor directory

### ISSUE THREAD

**Issue by zachgersh** [fatih/vim-go#902]
### Actual behavior

I attempt to auto import `gopkg.in/yaml.v2` and instead I get nothing. Rolling back to v1.6 fixes the issue completely.

### Expected behavior

`gofmt` auto imports the file like before

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. Install vim-go latest
2. have a vendor directory
3. write small main.go that attempt to import a dependency from vendor

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* nvim version: 0.1.4 
* vim-go version: latest-stable
* go version: 1.6.2

**Comment by fatih** [comment]
Hi @zachgersh 

`gofmt` doesn't auto import dependencies. Did you add the following line to your `vimrc`:

```viml
let g:go_fmt_command = "goimports"
```

**Comment by zachgersh** [comment]
Yessir! Works fine in 1.6 so there was some sort of regression. I could try to do a git-bisect to find the commit.

**Comment by fatih** [comment]
This is now fixed in master. Thanks for the feedback @zachgersh. I've renamed some of the variables to prevent a regression like this again.
