### ISSUE TITLE
"-srcdir" option of goimports is not set

### ISSUE THREAD

**Issue by haruyama** [fatih/vim-go#903]
### Actual behavior

"-srcdir" option of goimports is not set.

At https://github.com/fatih/vim-go/blob/a9611d7d691994a1fd33821ce4220366d8711300/autoload/go/fmt.vim#L116,
vim-go compares fmt_command and "goimports".

But fmt_command is set at https://github.com/fatih/vim-go/blob/a9611d7d691994a1fd33821ce4220366d8711300/autoload/go/fmt.vim#L107, this comparison is always false in my environment.

### Expected behavior

"-srcdir" option of goimports is set.

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. :GoImports

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce: https://github.com/haruyama/Settings/blob/master/.vim/after/ftplugin/go.vim
* vim version: 7.4.1689
* vim-go version: 6efcfb275c8f7779bfc0738da730dfab19f157fe
* go version: 1.6.2

**Comment by fatih** [comment]
This is now fixed in master. Thanks for the feedback @haruyama. This seems like to be a regression.

**Comment by haruyama** [comment]
Thank you!
