### ISSUE TITLE
VIM froze and can't do anything when enter new buffer

### ISSUE THREAD

**Issue by justmao945** [fatih/vim-go#906]
### Actual behavior

VIM froze and can't do anything when enter new buffer.

### Expected behavior

Any work should be running in background and not freezeVIM.

### Steps to reproduce:

The first time to open a large Go project

PS. I don't known whether vim-go run jobs when enter new buffer or not, please tell me if I'm wrong.

**Comment by fatih** [comment]
Hi @justmao945 

Vim-go doesn't do anything blocking if you enter a new buffer. I think you have installed syntastic which causes this. Checkout https://github.com/fatih/vim-go#using-with-syntastic for more info. Please reopen another issue with more info (by following the template) if you have problems. Thanks
