### ISSUE TITLE
omnifunc doesn't leave completion mode properly

### ISSUE THREAD

**Issue by roxma** [fatih/vim-go#911]
Hi, I created a [simple auto complete plugin](https://github.com/roxma/SimpleAutoComplPop#config), to work with vim-go, I encounter this minor issue:

> when I type `htt<C-X><C-O>` it will popup a list containing http, then I type `htt<C-X><C-O>p.`. When the `.` is typed the popup menu disapears, but the event CompleteDone is not triggered. This would cause SACP failed to feed `<C-X><C-O>` properly. set the `ignoreCompletionMode` to 1 would fix this issue.

When the `.` is typed, neither `CompleteDone` event is triggered nor a popup menu is popped for me, I don't think this is a graceful behavior.

It's not a big issue, close this if you want.

**Comment by fatih** [comment]
Hi @roxma 

Thanks for the feedback. Our code is here: https://github.com/fatih/vim-go/blob/master/autoload/go/complete.vim and this is the place we set the omnifunc: https://github.com/fatih/vim-go/blob/master/ftplugin/go.vim#L24

Feel free to check the code and send a PR, which plays nice with your plugin but doesn't break other plugins (such as deoplete, neocomplete , etc...) Those plugins work well without any issue, so I suspect they either handle some special cases or your plugin does something wrong. I'm closing this issue as there is not much I can do, but I'm more than happy to include fixes or improvements to the completion wrapper :)

**Comment by roxma** [comment]
I found that these special cases are handle nicely by other plugins. It's hard to do it perfectly inside vim-go, and it would be better handled by other plugins. So there's no need for a PR. Anyway, I've already got a nicely working one :)
