### ISSUE TITLE
How to disable the scratch buffer opened when you use <c-x><c-o> ?

### ISSUE THREAD

**Issue by Misfit-John** [fatih/vim-go#912]
This feature is good but annoying because I have to close this buffer after the completion. Can I just disable it or make it close after the completion is done? Also, if this is a function , can I make it also complete ')' as well?

**Comment by bradleyfalzon** [comment]
Does `set completeopt-=preview` in your vimrc solve the issue?

**Comment by fatih** [comment]
H @Misfit-John 

This is not a vim-go issue, as @bradleyfalzon said it's a Vim feature and you have to disable it. Thanks!

**Comment by Misfit-John** [comment]
Great thanks, fixed.
