### ISSUE TITLE
go-explorer is abandonware

### ISSUE THREAD

**Issue by serussell** [fatih/vim-go#923]
This is merely a comment that go-explorer is abandoned, and has an "abandoned" notice on the front git page.  The README for vim-go still (implies) that go-explorer is recommended -- is this still the case?

**Comment by fatih** [comment]
Hi @serussell 

Go-explorer is a nice plugin that makes exploring and navigating `Go` docs inside vim very easy. I didn't know it was abandoned.  I still recommend it (even though it's not maintained). We can remove it from the README when it's not usable anymore or we integrated the plugin into vim-go (which is something I would want, but it would also bring maintenance burden that I alone can't continue myself). Thanks for the feedback!

**Comment by gabrielsimoes** [comment]
`go-explorer` isn't available on GitHub anymore
