### ISSUE TITLE
Templates should inherit package name

### ISSUE THREAD

**Issue by erikh** [fatih/vim-go#950]
### Actual behavior

* Create a package `x`
* Fill it with a file with package `x` as the first line
* Create another new file in package `x`'s directory
* Created with `package main` stanza that always comes up

### Expected behavior

I'd love it if you parsed out the package name from the current directory (presuming it's consistent so you can act sanely) and prefilled the first line with `package x`.

I hope these kinds of feature requests are ok!

**Comment by fatih** [comment]
Hi @erikh 

I'm not sure I've understand you're problem. vim-go is filling the new line with the package name according to the directory. It's not just adding a `package main`. You're sure you tested it correctly? Can you provide a testable example please with the source code as well.

**Comment by erikh** [comment]
Sure.

Basically, if I have a file like this in the 'mytest' directory already: https://gist.github.com/643bbb365cad44c7e537736fe27027f9

I think vim-go should somehow be able to assume that the package name is not 'main' but is 'mytest'. Here's a screenshot of what I'm talking about:

<img width="493" alt="screen shot 2016-07-19 at 8 15 22 pm" src="https://cloud.githubusercontent.com/assets/18923/16974043/8f4a35e6-4ded-11e6-9dc7-bd7a3d3b0638.png">

Now, this is already in the directory docker and there are other files in that dir with the `docker` package applied already as you can see, but vim-go gives me hello world with a `package main` in it. I basically just have to delete this all, but I love the idea of auto-filling packages in with stub content so I really want to use this feature. :)

**Comment by fatih** [comment]
But it's like that already :/ I mean if it's `mytest` and you open a new file, it'll be also `mytest`. Look here is a GIF that I've just made for you:

![screen recording 2016-07-19 at 11 20 pm](https://cloud.githubusercontent.com/assets/438920/16974120/67f4d4b4-4e07-11e6-86f0-b28916bf7615.gif)

**Comment by erikh** [comment]
interesting, because I'm not seeing this behavior; I just upgraded just in
case. What I am seeing is the behavior described above.

If you look at the screenshot above, you can see that it's importing the
`hello_world.go` when I opened the new file with `:e` it did not show the
same behavior yours did.

here's my .vimrc if that helps:
https://gist.github.com/73a5f2bac4e754b7410167a24dab6bb8

**Comment by erikh** [comment]
Here's my `vim --version` too (I'm guessing, but presuming this isn't operator error, this seems like a portability bug to me)

https://gist.github.com/6bd56487570e9b547f7a66f2b9bf79d3

**Comment by fatih** [comment]
Can you execute

```
go list -f '{{.Name}}'
```
in that directory?

**Comment by fatih** [comment]
Also can you please test it on another package as well

**Comment by erikh** [comment]
```
[46] erikh@contiv227 impl/docker% go list -f '{{.Name}}'                                                                                        can't load package: import cycle not allowed
package github.com/contiv/volplugin/api/impl/docker
        imports github.com/contiv/volplugin/api/impl/docker
```

Works fine in another (compiling) package where go list also works appropriately. I guess I just hit this without knowing what the cause was a number of times. I've been doing a lot of code moving in this tree lately.

Very sorry to take so much of your time!

**Comment by fatih** [comment]
No worries, happy to see you resolved it :)
