### ISSUE TITLE
GoDoc can't work

### ISSUE THREAD

**Issue by gatspy** [fatih/vim-go#951]
### Actual behavior

:GoDoc occurred a error as bellow:
gogetdoc: couldn't get package for $GOPATH/src/github.com/fatih/vim-go-tutorial/main.go: can't find package containing $GOPATH/src/github.com/fatih/vim-go-tutorial/main.go

### Steps to reproduce:

1. backup my vimrc 
2. clone your vim configuration https://github.com/fatih/dotfiles/blob/master/vimrc
3. PlugInstall
4. clone fatih/vim-go-tutorial
5. vim main.go and move cursor under "Println", run GoDoc error occurred.
6. `gogetdoc -pos $GOROOT/src/fmt/format.go:#6274` ,it's ok
7. `godoc cmd/fmt Println` and `go doc fmt Println`,it's ok

### Configuration

* `vimrc` clone from https://github.com/fatih/dotfiles/blob/master/vimrc
* vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul  8 2016 00:05:59) MacOS X (unix) version
* vim-go version: latest
* go version: go1.6.3 darwin/amd64 ,installed by brew

**Comment by fatih** [comment]
Hi @gatspy 

I think you're `GOPATH` does is not setup correctly. I've just tried it and it works.  Please check your `GOPATH` and try to fix it.

**Comment by gatspy** [comment]
Thank you for your reply.
That's really so, i link a external disk into `HOME` named as `WORK` ,then `GOPATH` setting as `$HOME/WORK`, in most cases it's correct.
now i changed `GOPATH`  directly to the physical hard disk.
