### ISSUE TITLE
GoPlay hits a 404 URL

### ISSUE THREAD

**Issue by trevrosen** [fatih/vim-go#953]
### Actual behavior
`GoPlay` command hits a URL that is 404

### Expected behavior
Server should respond by placing contents of range or file in a Go Playground screen

### Steps to reproduce:

1. Use `GoPlay` with either a range or a file. It will hit `https://play.golang.org/p`
2. Server responds with 404

**Comment by fatih** [comment]
Hi @trevrosen 

`:GoPlay` works without any problem. You might had a bad connection at that time. Thanks.

**Comment by trevrosen** [comment]
Hi thanks for taking a look, and thanks for vim-go!

I didn't have a bad connection and can reproduce this issue at will. I'm on OS X 10.10.5 (Yosemite) and this happens with either MacVim or Vim in the terminal. I've used Wireshark to verify that my code payload is being sent to the share endpoint. I appear to be losing the identifier for the share somehow, which is why the 404 to `https://play.golang.org/p`.

Before I bust out MiTMProxy to really get into the wire responses, do you mind confirming that this works on OS X? I hate to trouble you, but there's really nothing non-standard about either my Go, vim-go, or Vim installations, and I would really like to use this excellent feature.

**Comment by trevrosen** [comment]
Meh someone else on OS X here at the office tried it and it appears to work for them so I guess I'll go off and figure out whatever the hell this is.
