### ISSUE TITLE
Printing escape sequences

### ISSUE THREAD

**Issue by xibz** [fatih/vim-go#955]
### Actual behavior

When typing in vim, while vim-go is installed, the terminal prints escape sequences when in command mode. I have to `CTRL c` then `:q` to get out.

### Expected behavior

To behave like vim

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. Have vundle installed
2. Install vim-go
3. Set vimrc to include `let g:go_auto_type_info = 1`

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vimrc
```
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'fatih/vim-go'
call vundle#end()

filetype plugin on
filetype plugin indent on
filetype indent on

syntax enable
" Outdated stuff off
set nobackup
set noswapfile

let g:go_auto_type_info = 1
```
* 7.3
* 1.7.1
* 1.6

**Comment by fatih** [comment]
Yeah this is really a problem that I couldn't find my self. This is not a vim-go problem though, it's a Vim problem.  See: https://github.com/fatih/vim-go/issues/71 and http://stackoverflow.com/questions/29482036/characters-randomly-showing-up-on-screen-when-move-the-cursor-from-left-to-right

It's a `TERM` and `vim` problem. I'm closing as this is not a vim-go problem. Feel free to comment if you find a solution on your side. Thanks.
