### ISSUE TITLE
goimports -srcdir will soon also accept a full filename

### ISSUE THREAD

**Issue by bradfitz** [fatih/vim-go#956]
As discussed in https://github.com/dominikh/go-mode.el/issues/146 for emacs,

As of https://golang.org/cl/25140, `goimports -srcdir=....` will accept a full filename of the file being edited, instead of just its directory. (But directory will still work as it does today)

You'll probably want to update vim-go to pass the full name, which will enable some new features in goimports. (analyzing other files in your package's directory for better recommendations, and being aware of global variables)

**Comment by fatih** [comment]
Thanks @bradfitz for the feedback 👍 Agree that it's a terrible name as well :)  Btw, we also write to a temp file first (to catch errors and not lose undo history) and then rename the tempfile to the actual one. 

With the patch #957, the final command will be something like:
```
goimports -w -srcdir '/Users/fatih/Code/go/src/demo/demo.go' /var/folders/g2/wr9dxcns1y50g5lz0lg1__pc0000gn/T/nvimDmFecf/2
```

Let me know if you need anything else. I'll merge it once the CL is being accepted.

**Comment by bradfitz** [comment]
I submitted https://golang.org/cl/25140 so feel free to make the change whenever.

Thanks!
