### ISSUE TITLE
quotes problem with the template

### ISSUE THREAD

**Issue by vrischmann** [fatih/vim-go#959]
### Actual behavior

I'm on Windows.
I have a directory called clog, with a clog.go file containing `package clog`.

Then when I open another file foobar.go, vim-go auto creates the package line, but it's wrong: it creates _package 'clog'_.

### Expected behavior

vim-go should write the correct package line.

### Steps to reproduce:

Problem only appears on Windows, on my OS X machine it's fine.

 1. create a package foobar.
 2. create a new Go file in the same directory.

### Configuration

* gvim for windows 7.4
* last vim-go commit as of right now (9754508b38414a7544360bd6f2b33c9016517400).
* go tip

Also, I investigated the code and it looks like in https://github.com/fatih/vim-go/blob/master/autoload/go/tool.vim#L47 if I just remove the two single quote in the command it works.

Can't test if that change would work on Unixes too.

**Comment by fatih** [comment]
Hi @vrischmann 

> vim-go should write the correct package line.

What exactly? vim-go is correct. If the package is `clog` the package will be names as `clog`. What do you expect?

**Comment by vrischmann** [comment]
Sorry, should have been clearer. It writes __package 'clog'__ (with the single quotes) instead of __package clog__

**Comment by fatih** [comment]
I can't reproduce it. Removing the quotes breaks it on bash/zsh (darwin). What does this outputs for you:

```
echo go#tool#PackageName()
```

**Comment by vrischmann** [comment]
It outputs __'clog'__ (with the quotes). I'm on Windows 10 Insider, unfortunately I don't have another Windows machine to test on.

I retested using an empty .vim/bundle directory and the following .vimrc:

    set nocompatible

    filetype off
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#rc()

    Plugin 'VundleVim/Vundle.vim'
    Plugin 'fatih/vim-go'

    call vundle#end()           
    filetype plugin indent on

Results are the same. I also thought maybe it has to do with the the fact that I'm running gVim, but I get the same results either by running vim in cmd.exe, vim in Windows Powershell, or gVim.

However I just tested ` go list -f '{{.Name}}'` directly in a cmd.exe session in my package dir, and it does return __'clog'__. Running `go list -f "{{.Name}}"` however returns the correct string. I'll have to test on my Mac if it works too.

**Comment by vrischmann** [comment]
Hi.

with the following patch it appears to work fine on Mac OS X with /bin/bash as Vim's shell and on Windows. I suspect it should work the same with zsh as shell and on Linux too.

    --- a/autoload/go/tool.vim
    +++ b/autoload/go/tool.vim
    @@ -44,7 +44,7 @@ function! go#tool#Imports()
     endfunction

     function! go#tool#PackageName()
    -  let command = "go list -f '{{.Name}}'"
    +  let command = "go list -f \"{{.Name}}\""
       let out = go#tool#ExecuteInDir(command)
       if go#util#ShellError() != 0
           return -1

**Comment by fatih** [comment]
@vrischmann this seems to work for me as well. Mind opening a PR?

**Comment by vrischmann** [comment]
Sure. I'll do a quick test using zsh and on Linux to make sure and I'll open a PR

**Comment by fatih** [comment]
Yeah, that would be nice
