### ISSUE TITLE
Solarized theme incompatible with GoCoverage

### ISSUE THREAD

**Issue by blacksails** [fatih/vim-go#960]
### Actual behavior

I am using the popular solarized theme for vim together with item3 for mac.

My problem is that `:GoCoverage` highlights the text using bright colors which in the terminal theme is different shades of grey. In the following screenshot, line 10 should be green.

![skaermbillede 2016-07-25 kl 11 03 15](https://cloud.githubusercontent.com/assets/3807831/17095969/738a2578-5257-11e6-8d4a-57296285ddc1.png)

### Expected behavior

I would like to see either that vim-go recognizes that solarized is used or someway to edit the highlights that `:GoCoverage` is making.

### Steps to reproduce:

1. Install iterm on mac
2. Install solarized iterm theme
3. Install solarized vim theme
4. Run `:GoCoverage`

### Configuration

* vim version: NVIM 0.1.4
* vim-go version: newest
* go version 1.6.2

**Comment by fatih** [comment]
Hi @blacksails 

I don't want to add solarized specific logic to vim-go. I've removed the gui parts and only changing the `fg` colors. You can also override them by adding the higlight definitions to your vimrc. Thanks.

**Comment by blacksails** [comment]
@fatih ah that is sweet. Thanks a bunch!
