### ISSUE TITLE
When use  complete <CTRL N>, it is very slow...

### ISSUE THREAD

**Issue by jinleileiking** [fatih/vim-go#961]
### Actual behavior

Write here what's happening ...

### Expected behavior

Write here what you're expecting ...

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1.
2.
3.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version:
* vim-go version
* go version

**Comment by fatih** [comment]
Invalid issue. Please provide sufficient information. Thanks.

**Comment by jinleileiking** [comment]
@fatih It seems it will check all the files in the current dir, like `debug.log` When press ctrl+n

**Comment by jinleileiking** [comment]
https://github.com/jinleileiking/DotFiles 
my env
