### ISSUE TITLE
Improvement suggestion: Syntax based folding for imports

### ISSUE THREAD

**Issue by rbjorklin** [fatih/vim-go#963]
Would it be a good idea to have syntax based folding for imports much like Intellij does it?

I think it could be achieved by adding the `fold` [word at line 193](https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L192-L193).

**Comment by fatih** [comment]
Thanks @rbjorklin.

Unfortunately I don't have much time for implementing this feature, nor do I know if this is worth implementing. I don't close this and mark this as feature if someone wants to tackle it. If no one comes in 1-2 months I'm going to close it. Thanks for the suggestion! :)

**Comment by Carpetsmoker** [comment]
> I think it could be achieved by adding the fold word at line 193.

Well, that would also fold `var ( .. )` and `const ( .. )`. Some might consider that a feature, others might not :-)

At any rate, I did some work on more fine-grained folding settings today − I'll finish it up later.

**Comment by fervic** [comment]
Hi @Carpetsmoker did you make any progress on this?  I think `var( ... )` and `const( ... )` blocks should be foldable as well.

**Comment by Carpetsmoker** [comment]
Man, I can't believe it's been ten months... >_<

Either way, I created a PR @fervic @rbjorklin: #1339. Let me know if you have problems!

**Comment by rbjorklin** [comment]
I haven't written any Go in quite some time now and had honestly completely forgot about this. Feel free to close this issue. Thanks for putting in some effort though @Carpetsmoker!

**Comment by fervic** [comment]
Better late than never, I will try your PR out @Carpetsmoker. Thanks!

**Comment by fatih** [comment]
Thanks to @Carpetsmoker we have now an initial support for syntax based folding. It's on master, please pull, use it and any feedback is weldome. Please add @Carpetsmoker to the issue when reporting (issues or feature requests) :)
