### ISSUE TITLE
Syntax func first param

### ISSUE THREAD

**Issue by luatic** [fatih/vim-go#965]
Are there any chances of fixing syntax in function parameters
when comma added after first param it's not highlighted.

![vim-go](https://cloud.githubusercontent.com/assets/5059228/17152003/d8a0cfa4-536d-11e6-9fb0-154934cc504c.png)

**Comment by fatih** [comment]
@datanoise  What do you think the problem might be here?

**Comment by datanoise** [comment]
`goField` group is a bit silly though. It obviously cannot distinguish struct fields from exported names from packages.

**Comment by fatih** [comment]
Yeah. I'm looking forward to remove all the syntax rules and use AST based one. Not sure how fast it would be, but the go/parser is able to parse partially code as well. So that means we can just parse the screen we view right now and highlight it. Anyway just some ideas. Thanks for the fix!
