### ISSUE TITLE
incorrect parameter syntax highlighting.

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#977]
See the `...interface{}` parameter in these screenshots

Before 50ceca52a2b9f720d1a4e660363408be5b1ef055
![screen shot 2016-07-30 at 3 38 54 pm](https://cloud.githubusercontent.com/assets/10180857/17272722/1046a9d2-566c-11e6-9f74-78e65f4946c9.jpg)

After 50ceca52a2b9f720d1a4e660363408be5b1ef055 
![screen shot 2016-07-30 at 3 38 20 pm](https://cloud.githubusercontent.com/assets/10180857/17272718/0468a624-566c-11e6-9c13-33f9b3ef3f24.jpg)

@datanoise

**Comment by nhooyr** [comment]
Oh its because the `goVarArgs` highlight group is not linked to anything.

**Comment by datanoise** [comment]
goVarArgs is just too greedy. Plus I noticed that it overrides the `...` goOperator when `g:go_highlight_operators` is enabled. I've submitted the patch that fixes both issues.

**Comment by nhooyr** [comment]
Fantastic, thanks!
