### ISSUE TITLE
why use redraw! in Echo functions in autoload/go/util.vim

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#982]
It was changed in 8ce50ff3e26be560bc8fd575dcc510388bd497d7

Just wondering why?

**Comment by fatih** [comment]
I think with the latest `vim` it was causing a problem and I've changed it. The problem was it was not overriding the previous echo. It would like this:

```
vim-go: message 1vim-go: message2
```

Feel free to open a PR to revert it, or if you have a better solution I'm all ears :)

**Comment by nhooyr** [comment]
I have a very similar function in one of my own plugins. Just wondering whether I need to change it.

If I change it back to `:redrawstatus!` in my function, I can only reproduce the problem by `:exe 'Cmd' | Cmd`. Where `Cmd` is some command that uses the function to output an error.

`:redraw!` does fix this. I guess `:redrawstatus!` does not clear the statusline. It merely redraws the text already in there, and then the second message gets appended.

In fact, just `:redraw` fixes it. Not sure why  we need the `!`.

**Comment by fatih** [comment]
The `!` clears the screen before redrawing it.

**Comment by nhooyr** [comment]
Oh I know what it does. But `:redraw` on its own seems to work fine.

**Comment by fatih** [comment]
Alright removed it and pushed to master. I'm closing this, let me know if you hit any problems and we'll fix it.
