### ISSUE TITLE
GoAddTags: allow modifying existing comments

### ISSUE THREAD

**Issue by tobstarr** [fatih/vim-go#984]
First of all thank you for the `GoAddTags` feature, it is really great. Sometimes I do want to add a tag to a struct field which already has an existing tag set which leads to this output:

```
type User struct {
    Name string `sql:"name"` `json:"name"`
}
```

which does not compile. It would be great if `GoAddTags` would keep already existing tags but also add the new tag.

**Comment by fatih** [comment]
Fixed with #1024 please, feel free to test and reopen if it's not the case.
