### ISSUE TITLE
GoAddTags: tag options

### ISSUE THREAD

**Issue by tobstarr** [fatih/vim-go#985]
At least for my workflow it would be nice to be able to also provide e.g. the `omitempty` option when adding a `json` tag to a struct field. 

I would propose to change the behaviour of `GoAddTags json,omitempty` to produce `json:"name,omitempty"` instead of `json,omitempty:"name"` but I do not know if there are cases where one actually would want to add a tag including a comma character.

**Comment by fatih** [comment]
Hi @tobstarr 

This and the second PR (#984) you opened, I wanted to do in the next release ;)  I didn't wanted to put a lot of features. So adding them one by one is the way to go 👍 

Tag options is easy, however for the second one we need to parse the string (might be a little bit complicated, but doable). I'll keep an eye on this. If someone else want to tackle it feel free to pick it up, but let me know before if you do it.

**Comment by fatih** [comment]
Fixed with #1024 please, feel free to test and reopen if it's not the case.

**Comment by tobstarr** [comment]
@fatih is it intended that `GoAddTags json,omitempty` only works if the tag is already present? In that case things work fine, otherwise nothing happens (but something __is__ happening as the vim buffer is then marked as changed - `+`)

**Comment by fatih** [comment]
Yeah it only works if it exists. Previously it was the opposite. The buffer changes because gomodifytags changes the file again, thus the creation time changes as well. Open an issue to https://github.com/fatih/gomodifytags to track if you want :)

**Comment by tobstarr** [comment]
Any particular reason for that? I would find it really handy for `GoAddTags json,omitemty` to also create the tag of it does not exist. 

I just checked gomodifytag and the call `gomodifytags -file main.go -add-tags json -struct User -add-options json=omitempty` would do the trick (add the tag with the option if it does not exist).

Behaviour before was not the opposite, but that it created this: `json,omitempty:"name"`.

**Comment by fatih** [comment]
When I mean `oppposite`, the current implementation was like you said. I've removed it because I wanted to make it explicitly. It's very easy to change it because I've like that previously. I'm not sure why I reverted it (don't remember now). Let me check it again.
