### ISSUE TITLE
GoImpl issue with 1.8

### ISSUE THREAD

**Issue by AnatoliiPrylutskyi** [fatih/vim-go#991]
### Actual behavior

I used GoImpl to generate empty methods for struct and point to interface and it generate me:
type Tracker struct{}

```
lstat /usr/bin/vim: no such file or directorylstat /usr/bin/vim: no such file or directoryfunc (t *Tracker) Report(context.Context, entities.TrackerReport) error {
	panic("not implemented")
}
```

### Expected behavior

It should generate something like this:

```
func (t *Tracker) Report(context.Context, entities.TrackerReport) error {
	panic("not implemented")
}
```

I fix it with 
`ln -s /usr/local/bin/vim /usr/bin/vim`

### Steps to reproduce:

1. Run GoImpl with vim installed in any directory except /usr/bin/vim

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vim version: 7.4
* vim-go version: 1.8
* go version: 1.6

**Comment by Carpetsmoker** [comment]
Hm, it seems to work?

    [~]% which vim
    /usr/local/bin/vim

And then in Vim:

    :GoImpl f *Foo io.Writer

Gives me:

    func (f *Foo) Write(p []byte) (n int, err error) {
        panic("not implemented")
    }

I'm confused why this should error out with this particular error. It basically just does:

    system("/home/martin/gocode/bin/impl 'f *Foo' 'io.Writer'")

My best guess that it's in `go#path#CheckBinPath()` in `autoload/go/path.vim`, which sanitise the `$PATH` and `$GOPATH`.

What are `$PATH` and `$GOPATH` before starting Vim? What are they in Vim after you've run `:GoImpl` (`:echo $PATH`).
You can also try some printf-style debugging with `:echom` in that function (you can see the errors with `:messages`).

**Comment by AnatoliiPrylutskyi** [comment]
It works well for std lib, but I always receive error for my own interfaces.

Before vim:
$PATH: /home/apryl/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/apryl/.local/bin://home/apryl/gopath/bin:/usr/local/go/bin:/usr/local/sbin:/usr/sbin
$GOPATH:
/home/apryl/gopath

After :GoImpl inside vim PATH and GOPATH doesn't changed.

**Comment by Carpetsmoker** [comment]
So what do your files look like? Where are they located? What commands are you running? Does the commandline I showed earlier work?

**Comment by fatih** [comment]
@AnatoliiPrylutskyi please provide a demo test file (a repo) that shows what to do. The steps under the reproduce case is not helpful for us. I strongly believe this is not a vim-go problem, it seems like a local error to your own environment. If your provide something we can test ourself it would be helpful.

**Comment by AnatoliiPrylutskyi** [comment]
Here is a repo https://github.com/AnatoliiPrylutskyi/testgoimpl
I run 
`:GoImpl f *Foo foo.Fooer `
and receive same problem.

I remove all plugins for this testing except vim-go

If you wouldn't receive same results as me we could close this issue. It would be my local env problem

Thanks

**Comment by fatih** [comment]
You're provided example does work for me without any problem. I'm with @Carpetsmoker here. I don't think this is a vim-go problem though. I'm not sure what the problem is. Can you call the following from your shell:

```
impl 'f *Foo' foo.Fooer
```

What does this give you?

**Comment by AnatoliiPrylutskyi** [comment]
It is very strange, received the same error
```
lstat /usr/bin/vim: no such file or directorylstat /usr/bin/vim: no such file or directoryfunc (f *Foo) Foo() {
	panic("not implemented")
}
```
It is certainly not a problem of vim-go. Sorry for disturbing you.
Thank you.
