### ISSUE TITLE
Add error, warning, style symbols in gutter / sidebar according to locationlist and quickfix windows

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#993]
Feels like the wind is blowing in the direction where vim-go is favored over of syntastic regarding syntax checking.

One of the best features of syntastic is using gutter/sidebar visual markers to display errors and warnings from the locationlist and quickfix windows.

Is there a possibility to add this to vim-go?

**Comment by fatih** [comment]
Hi @oryband 

Vim doesn't have native support for sidebar. It's a hack and I don't think we should support it. For now at least. I'm closing this as I don't have any feature plans for this as well in the future. Thanks.

**Comment by oryband** [comment]
@fatih why is it a hack? I'm talking about the `>>` signs at the left from syntactic's repo: ![](https://github.com/scrooloose/syntastic/raw/master/_assets/screenshot_1.png)

It's the most useful feature of syntactic - seeing visually which lines has errors. Also, hovering over the line displays the error in the status bar.

**Comment by oryband** [comment]
@fatih ping

**Comment by fatih** [comment]
@oryband There is no native feature for it. If there is please let me know.
