### ISSUE TITLE
:GoCoverageClear resets highlights when colorscheme set

### ISSUE THREAD

**Issue by benbarbour** [fatih/vim-go#997]
### Actual behavior

When I execute :GoCoverage in a go source file I get the covered/uncovered highlights shown. When I execute :GoCoverageClear to turn off the highlights they do disappear, but all previously set highlights are removed.

This happens with :GoCoverageToggle twice as well. It also happens with at least two different themes (solarized and molokai).

### Expected behaviour

No highlights should be removed when the coverage annotations are cleared.

### Steps to reproduce:

1. Install [vim-plug](https://github.com/junegunn/vim-plug#installation), or modify the sample init.vim to load the plugins some other way.
2. Load neovim with the sample init.vim
2. Execute `:PlugInstall` and restart neovim (might not be needed, but can't hurt).
3. Open a go file that has a misspelling, or just take note of the highlighted column colour.
4. Execute `:GoCoverageToggle` twice.
5. Note that the spelling highlight and the colorcolumn have changed. Alternatively execute `:highlight` before and after the second execution of `:GoCoverageToggle` and note the changed values.

### Configuration

* go version: 1.6
* vim-go version: ecac655
* vim version: neovim 0.1.4 tag

#### Sample init.vim
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'fatih/vim-go' 
Plug 'tomasr/molokai'
call plug#end()

set background=dark
colorscheme molokai
highlight ColorColumn ctermbg=52
highlight clear SpellBad
highlight SpellBad cterm=underline
```

**Comment by benbarbour** [comment]
Actually, they get reset if you set the colorscheme again, or if you set syntax on. vim-go does the latter, which it clearly has to. I don't know if there's anything to be done here, unless it can save and restore the current highlight settings?

**Comment by Carpetsmoker** [comment]
>  they get reset if you set the colorscheme again

This can be fixed by hooking in to the `ColorScheme` autocommand. For an example, see: 
https://github.com/fatih/vim-go/pull/983/files#diff-6bbebb95ce25cd40d0072544e2dad91eR372

**Comment by benbarbour** [comment]
Thanks for the help!

I put this in my init.vim for now, and it seems to do the trick:

```vim
" set highlights and restore them after colorscheme is set
function! s:sethighlights()
  highlight ColorColumn ctermbg=52
  highlight clear SpellBad
  highlight SpellBad cterm=underline
endfunction

augroup highlights
  autocmd!
  autocmd ColorScheme * call s:sethighlights()
augroup end

set background=dark
colorscheme solarized
```

**Comment by fatih** [comment]
@Carpetsmoker is this fixed with your PR (#983) ?

**Comment by Carpetsmoker** [comment]
No, it's unrelated (and not a vim-go problem). `go#coverage#Clear()` does `syntax enable` which will reload the syntax file and colour scheme. I just linked to the PR because I didn't want to repeat my explanation ;-)

This is why you should always add custom highlight groups in a `ColorScheme` autocommand.

**Comment by fatih** [comment]
@benbarbour I'm closing this as it seems you find a fix for it. Thanks.
